### ISSUE TITLE
Package path is not respected for the closure build rules

### ISSUE THREAD

**Issue by achew22** [bazelbuild/bazel#491] opened 2015-10-02 06:55 UTC
It appears that package path is not respected for the 
[closure build rules](https://github.com/bazelbuild/bazel/tree/master/tools/build_rules/closure).

After copying the `closure.WORKSPACE` file into an empty directory and creating
the sample BUILD, soy, gss, and js files, building the hello target defined in
the sample `BUILD`, I get the following error:

```
ERROR: /data/demo/BUILD:1: Extension file not found: 'tools/build_rules/closure/closure_stylesheet_library.bzl
ERROR: error loading package 'demo': Extension file not found: 'tools/build_rules/closure/closure_stylesheet_library.bzl'.
```

For some reason it appears the package\_path is not being respected.

For your convenience I have created a Docker image in git repo which
should exhibit this behavior in a reproducable way.

Git repo: https://github.com/achew22/bazel-bug-build-rule-closure

**Comment by damienmg** [comment] 2015-10-02 08:00
Duplicate of #488

**Closed by damienmg** 2015-10-02 08:00 UTC
