### ISSUE TITLE
Cannot switch back and forth between an external with new_local_repository and new_http_repository

### ISSUE THREAD

**Issue by jpieper-tri** [bazelbuild/bazel#1355] opened 2016-06-08 12:52 UTC
I've run into a problem where bazel seems to get confused when switching between an external configured using "new_local_repository" and "new_http_repository".  

Brief context:  I'm developing on Ubuntu trusty, and am using some system installed packages in a C++ application.

In my particular instance, I started with boost configured as a new_local_repository to use the system installed boost.  At some later point, I decided to use a newer version of boost as a new_http_repository.  That all worked fine.  However, after that, if I use git to switch back and forth between the two states, bazel gets confused and is unable to build the new_http_repository version if it has already built it once, and then built the new_local_repository version since.

I have a minimal test repository on github which demonstrates this problem for me.

```
git clone https://github.com/jpieper-tri/bazel_local_http_external.git
cd bazel_local_http_external
git checkout master^
bazel build //...  # this is the first build on new_local and works fine
git checkout master
bazel build //... # this is the first build with new_http and works fine
git checkout master^
bazel build //... # this also works fine
git checkout master
bazel build //... # fails
```

The failure I see looks like:

```
$ bazel build //...
INFO: Found 1 target...
ERROR: missing input file '@boost//:boost_1_61_0/libs/python/src/exec.cpp'.
ERROR: /home/jpieper/.cache/bazel/_bazel_jpieper/49d5c2f61756db305af8ff7531250266/external/boost/BUILD:87:1: @boost//:boost_python: missing input file '@boost//:boost_1_61_0/libs/python/src/exec.cpp'.
Target //src:sample failed to build
Use --verbose_failures to see the command lines of failed build steps.
ERROR: /home/jpieper/.cache/bazel/_bazel_jpieper/49d5c2f61756db305af8ff7531250266/external/boost/BUILD:87:1 1 input file(s) do not exist.
INFO: Elapsed time: 3.724s, Critical Path: 0.02s
```

And the version of bazel tested with:

```
bazel version
Build label: 0.2.3
Build target: bazel-out/local-fastbuild/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Tue May 17 14:21:13 2016 (1463494873)
Build timestamp: 1463494873
Build timestamp as int: 1463494873
```

**Comment by meteorcloudy** [comment] 2016-06-08 15:59
//cc @kchodorow Can you help us?

**Comment by meteorcloudy** [comment] 2016-06-08 16:00
By the way, how about running `bazel clean` before the build?

**Comment by jpieper-tri** [comment] 2016-06-08 16:06
`bazel clean` does not help, but removing my entire ~/.cache/bazel directory does.

**Comment by kchodorow** [comment] 2016-06-08 16:08
`bazel clean --expunge` should work (basically a rm -r on the cache directory) but yeah, sounds like a bug.  I'll look into it.

**Comment by kchodorow** [comment] 2016-06-14 21:12
Duplicate of #977.

**Closed by kchodorow** 2016-06-14 21:12 UTC
Labels: category: extensibility > external repositories, P2, Under investigation
