### ISSUE TITLE
When installing on Ubuntu 14.04 I get "The package is of bad quality"

### ISSUE THREAD

**Issue by mgarbade** [bazelbuild/bazel#1302] opened 2016-05-22 15:10 UTC
I downloaded the 86_64.deb version of bazel 0.2.3 but when I double click it, I get a warning from Ubuntu Software Center saying:

**The package is of bad quality**

The installation of a package which violates the quality standards isn't allowed. This could cause serious problems on your computer. Please contact the person or organisation who provided this package file and include the details beneath.

```
Details:
Lintian check results for /home/garbade/Downloads/bazel_0.2.3-linux-x86_64.deb:
E: bazel: package-contains-ancient-file etc/ 1970-01-01
E: bazel: package-contains-ancient-file etc/bash_completion.d/ 1970-01-01
E: bazel: package-contains-ancient-file etc/bash_completion.d/bazel 1970-01-01
E: bazel: package-contains-ancient-file etc/bazel.bazelrc 1970-01-01
E: bazel: package-contains-ancient-file usr/ 1970-01-01
E: bazel: package-contains-ancient-file usr/bin/ 1970-01-01
E: bazel: package-contains-ancient-file usr/bin/bazel 1970-01-01
E: bazel: package-contains-ancient-file usr/bin/bazel-real 1970-01-01
```

Any idea what is wrong here? Should I proceed with the installation anyway or can this disrupt my system?

**Comment by hermione521** [comment] 2016-05-23 08:41
@damienmg Can you look at this? Thanks.

**Comment by mgarbade** [comment] 2016-05-23 09:14
This is exactly where I got the binaries from: 
I tried downloading `bazel_0.2.3-linux-x86_64.deb` and `bazel_0.2.3-jdk7-linux-x86_64.deb` both gave the same error as mentioned above. Also dowloading the source code and invoking `./compile.sh` failed with the error message 

`INFO: You can skip this first step by providing a path to the bazel binary as second argument:
INFO:    ./compile.sh compile /path/to/bazel
🍃  Building Bazel from scratch
JDK version (1.7) is lower than 1.8, please set $JAVA_HOME.`

However neither switching to JDK 1.8 nor setting JAVA_HOME did help...

**Comment by mgarbade** [comment] 2016-05-23 09:24
Finally it seems to work! Although I have Ubuntu 14.04 all `*.deb` packages didn't work. Finally I ended up downloading `bazel-0.2.3-jdk7-installer-linux-x86_64.sh` which worked for me. Thanks anyway ;)

**Comment by damienmg** [comment] 2016-05-23 10:01
This is a consequence of #1299. We should allow to set the timestamp in the rule.

**Comment by damienmg** [comment] 2017-02-02 09:58
Duplicate of #1132

**Closed by damienmg** 2017-02-02 09:58 UTC
Labels: category: misc > release / binary, P2, type: feature request
