### ISSUE TITLE
Apply --local_termination_grace_seconds to worker processes

### ISSUE THREAD

**Issue by kastiglione** [bazelbuild/bazel#9975] opened 2019-10-08 21:43 UTC
### Description of the problem / feature request:

`--local_termination_grace_seconds` does not appear to apply to worker processes.

### Feature requests: what underlying problem are you trying to solve with this feature?

Our developers would like to be able to stop builds quicker, without waiting for current actions to complete. Since we use rules_swift, which by default uses workers, our builds wait until in-progress worker actions complete

The current references to this option appear to be only:

* [LocalSpawnRunner.java](https://github.com/bazelbuild/bazel/blob/3948aaac26c125de8397ebe5561a2504affc85be/src/main/java/com/google/devtools/build/lib/exec/local/LocalSpawnRunner.java#L344)
* [SandboxModule.java](https://github.com/bazelbuild/bazel/blob/3948aaac26c125de8397ebe5561a2504affc85be/src/main/java/com/google/devtools/build/lib/sandbox/SandboxModule.java#L282)

### Bugs: what's the simplest, easiest wayto reproduce this bug? Please provide a minimal example if possible.

Use any rules that use workers, for example rules_swift, and set `--local_termination_grace_seconds=1`. Build a project that has longer running actions, and see that the value specified has no effect.

Looking through the source, 

### What operating system are you running Bazel on?

macOS

### What's the output of `bazel info release`?

release 0.29.1

**Comment by jmmv** [comment] 2019-10-10 15:27
This is because workers currently don't support cancellations. See #614. So i'm going to call this a duplicate of that one.

**Closed by jmmv** 2019-10-10 15:27 UTC
Labels: team-Local-Exec, untriaged
