### ISSUE TITLE
alias in external repo causes unhandled exception

### ISSUE THREAD

**Issue by wt** [bazelbuild/bazel#1297] opened 2016-05-20 09:37 UTC
After the fix for #1290, I now have a new issue.

See the branch @ https://github.com/wt/bazel_rules_nodejs/tree/broken_case-alias_in_external_repo. The top commit on that branch adds an alias in build file contents provided for an external http repository. See https://github.com/wt/bazel_rules_nodejs/commit/71df51e07718289870840b09e8b073be7ad0c7b4. On this branch, the following works:

```
wt@frisbee:~/projects/bazel/rules_nodejs$ bazel run @nodejs_linux_amd64//:bin/node -- --version
INFO: Found 1 target...
INFO: Elapsed time: 8.939s, Critical Path: 0.01s

INFO: Running command line: /home/wt/.cache/bazel/_bazel_wt/436e8eb5273604e06eefc0e49e49d4b4/external/nodejs_linux_amd64/bin/node --version
v4.4.4
wt@frisbee:~/projects/bazel/rules_nodejs$
```

The following does not:

```
wt@frisbee:~/projects/bazel/rules_nodejs$ bazel run @nodejs_linux_amd64//:other_nodejs_tool -- --version
INFO: Found 1 target...
Target @nodejs_linux_amd64//:bin/node failed to build
Use --verbose_failures to see the command lines of failed build steps.
Unhandled exception thrown during build; message: Unrecoverable error while evaluating node 'CONFIGURED_TARGET:@nodejs_linux_amd64//:other_nodejs_tool null' (requested by nodes 'TARGET_COMPLETION:LabelAndConfiguration{label=@nodejs_linux_amd64//:other_nodejs_tool, configuration=null}')
INFO: Elapsed time: 0.247s, Critical Path: 0.00s
java.lang.RuntimeException: Unrecoverable error while evaluating node 'CONFIGURED_TARGET:@nodejs_linux_amd64//:other_nodejs_tool null' (requested by nodes 'TARGET_COMPLETION:LabelAndConfiguration{label=@nodejs_linux_amd64//:other_nodejs_tool, configuration=null}')
	at com.google.devtools.build.skyframe.ParallelEvaluator$Evaluate.run(ParallelEvaluator.java:1015)
	at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:515)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:212)
	at com.google.devtools.build.lib.util.Preconditions.checkNotNull(Preconditions.java:344)
	at com.google.devtools.build.lib.analysis.DependencyResolver.dependentNodeMap(DependencyResolver.java:138)
	at com.google.devtools.build.lib.skyframe.ConfiguredTargetFunction.computeDependencies(ConfiguredTargetFunction.java:275)
	at com.google.devtools.build.lib.skyframe.ConfiguredTargetFunction.compute(ConfiguredTargetFunction.java:200)
	at com.google.devtools.build.skyframe.ParallelEvaluator$Evaluate.run(ParallelEvaluator.java:966)
	... 4 more
wt@frisbee:~/projects/bazel/rules_nodejs$
```

I would expect the second to work just as well as the first.

@lberki fixed #1290, so maybe this one will also be of interest.

**Comment by lberki** [comment] 2016-05-20 09:41
I suppose this is a duplicate of #1296, isn't it?

**Comment by wt** [comment] 2016-05-20 10:21
#1296 should be closed and this one opened if you want correct shas in the links. I rebased and force pushed the test case branch. I tried to update the issue, but I guess a new one was created instead.

**Comment by lberki** [comment] 2016-05-20 15:53
This was a fun bug :) The fix has been sent out for code review, so it should hit GitHub on Monday or Tuesday, depending on how fast the review goes. In the meantime, here is a patch:

https://gist.github.com/lberki/8599ef20a5243e326dd3b784e93f7f81

**Comment by wt** [comment] 2016-05-20 16:41
Thanks. Looking forward to the fix.

**Closed** 2016-05-23 08:35 UTC
Labels: category: External repositories, P1, type: bug

**Comment by wt** [comment] 2016-05-23 18:50
Confirmed fixed. Thanks!
