### ISSUE TITLE
"bazel coverage" fails when clang with llvm-cov is used

### ISSUE THREAD

**Issue by engineerCYB** [bazelbuild/bazel#8284] opened 2019-05-10 06:44 UTC
### Description of the problem / feature request:

It appears that bazel defaults to BAZEL_CC_COVERAGE_TOOL=GCOV now, although I believe this used to be an experimental flag. As a result, collect_cc_coverage.sh invokes:

```
"${GCOV}" -i -o "$(dirname ${gcda})" "${gcda}" &> "$gcov_log"
```

However, when clang is the compiler, `GCOV` is a symlink (named `gcov`) pointing to `llvm-gcov`. llvm-gcov does not appear to support "-i".

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

With a clang toolchain, execute:

```
bazel coverage --test_env=COVERAGE_GCOV_PATH=/usr/bin/llvm-cov-6.0 //some:testname
```

Coverage will fail, and the coverage logs will show the llvm-gcov error. Adding `--spawn_strategy=standalone --test_strategy=standalone` allows inspection of the coverage log error:

```
bazel coverage --test_env=COVERAGE_GCOV_PATH=/usr/bin/llvm-cov-6.0 //some:testname --spawn_strategy=standalone --test_strategy=standalone

$ cat bazel-myworkspace/_coverage/some/testname/test/_cc_coverage.gcov.gcov.log 
gcov: Unknown command line argument '-i'.  
gcov: Did you mean '-a'?
```

### What operating system are you running Bazel on?

Ubuntu 14.04

### What's the output of `bazel info release`?

release 0.25.0

### Any other information, logs, or outputs that you want to share?

There are two workaround that I know of:

1. Use `--experimental_use_llvm_covmap` instead and get native llvm coverage
2. Make Bazel revert back to lcov mode with:

```
bazel coverage --test_env=COVERAGE_GCOV_PATH=/usr/bin/llvm-cov-6.0 --test_env=BAZEL_CC_COVERAGE_TOOL=LCOV //some:testname
```

Is the latter recommended right now? What are the tradeoffs of GCOV and LCOV mode, and should I expect GCOV mode to work with a clang toolchain?

**Comment by iirina** [comment] 2019-05-31 11:40
Thanks for the bug report! Bazel coverage using lcov is not supported anymore. What's surprising to me is that coverage with clang was previously working with the setup you described... 
Code coverage for clang toolchains was never officially supported by Bazel. There is an open issue for adding support (#5881). Until #5881 is fixed I recommend using the `--experimental_use_llvm_covmap` flag and get native llvm coverage.

**Comment by iirina** [comment] 2019-05-31 11:41
I'll close this issue as a duplicate of #5881. Let me know if I can be of more help.

**Closed by iirina** 2019-05-31 11:41 UTC
Labels: team-Rules-CPP

**Comment by cmoore3** [comment] 2019-07-11 15:25
> Thanks for the bug report! Bazel coverage using lcov is not supported anymore. What's surprising to me is that coverage with clang was previously working with the setup you described...

My organization also had it working that way.  We're stuck waiting or switching to source-based coverage and adding the glue to get it back to working if we want to upgrade past 0.25.

> [...] There is an open issue for adding support (#5881). Until #5881 is fixed I recommend using the `--experimental_use_llvm_covmap` flag and get native llvm coverage.

Is that really a reasonable workaround?  The profdata files are unique to LLVM and the tooling to convert them back to lcov to continue with existing tools from there seems unnecessarily complex.  That's because it needs all of the relevant object files and even then the path prefixes still need substituted--similar to how it was done in this deleted code:  https://github.com/bazelbuild/bazel/commit/75b26bf67ec842d04ccb66c4f5afc40702cfab6d#diff-548a32f17d60a154c015c1733ff6669d

Rather than restoring it, reverting, or waiting for new functionality (ie support for source-based coverage) can the steps just be made generic and extendable?  That is, if users want the old functionality they can write a script and specify it in place of the default.  This supports both external users (and their need to experiment) and internal development with less coupling to Bazel.  Documenting the env. vars. or flags involved would be greatly appreciated by the user community.
