### ISSUE TITLE
Windows `repository_ctx.execute(command)` sometimes returns incomplete result

### ISSUE THREAD

**Issue by meteorcloudy** [bazelbuild/bazel#2675] opened 2017-03-14 09:28 UTC
This is causing https://github.com/bazelbuild/bazel/issues/2434 and the internal Kokoro Windows Flakiness: missing "LIB"
```
Extracting Bazel installation...
................................
____Loading package: src
____Loading package: @bazel_tools//tools/cpp
____Loading package: @bazel_tools//tools/jdk
____Loading package: @local_config_xcode//
____Loading package: @local_jdk//
ERROR: in target '//external:cc_toolchain': no such package '@local_config_cc//': key "LIB" not found in dictionary.
```

**Comment by ulfjack** [comment] 2017-03-17 10:03
Any progress? This is killing my presubmits.

**Comment by meteorcloudy** [comment] 2017-03-17 12:12
Still haven't found the root cause, but looks like there is already a workaround for the Kokoro presubmit?(cl/150360798) I'll keep digging...

**Comment by meteorcloudy** [comment] 2017-04-03 16:16
This issue might have something to do with https://github.com/bazelbuild/bazel/issues/2774
Yet, I could never reproduce this on my local machine.
//cc @laszlocsomor

**Comment by meteorcloudy** [comment] 2017-04-03 16:24
@laszlocsomor Can you check if there is similar problem in [SkylarkExecutionResult.java](https://github.com/bazelbuild/bazel/blob/13b0daaee2d2979f7fbbddd5fb054462944c0536/src/main/java/com/google/devtools/build/lib/bazel/repository/skylark/SkylarkExecutionResult.java#L193 ) ?

**Comment by dslomov** [comment] 2017-04-04 13:32
Dupe for #2774

**Comment by laszlocsomor** [comment] 2017-04-04 13:34
@dslomov : I'm not convinced of that yet. Are you sure?

**Comment by dslomov** [comment] 2017-04-04 13:34
Missed a question mark :)

**Comment by laszlocsomor** [comment] 2017-04-04 13:35
Ah :) I'm trying to repro it now.

**Comment by laszlocsomor** [comment] 2017-04-04 15:01
@meteorcloudy : re https://github.com/bazelbuild/bazel/issues/2675#issuecomment-291195407: I don't think so, I believe we may be losing the stdout/stderr somehow. Since you were unable to repro this locally, I thought maybe because you didn't redirect the output to a file, whereas on CI it is redirected I believe.

Anyway, I set up an experiment with repo rules: I was building two of them in parallel, a fast and a slow one. It seems repo rules' actions (`repository_ctx.execute`) cannot be interrupted -- neither with Ctrl+C nor with one of them calling `fail()`. 

@dslomov : because of the reasons above, I doubt this bug is a dupe of #2774.

**Comment by mhlopko** [comment] 2017-04-10 10:48
Is this still expected to be fixed in 0.5? We still have some release blockers and we will not cut the release sooner than in 2 weeks, but we should be getting ready to.

**Comment by dslomov** [comment] 2017-04-10 10:49
I do not think we have a repro, so we do not know if it is fixed or not. I do not think we need to treat it as a release blocker.

**Comment by laszlocsomor** [comment] 2017-04-10 11:41
I've added stricter error checks and more logging to `cc_configure.bzl` in hopes of catching this bug the next time it appears. We don't have a repro, sadly.

**Comment by mhlopko** [comment] 2017-04-10 11:44
Ok thanks, not treating as release blocker. Good luck! :)

**Comment by damienmg** [comment] 2017-04-11 08:00
Let's move it to 0.6

**Comment by snnn** [comment] 2017-07-17 10:50
I can reproduce it on 688dbf7a71d2c2c2a092ab77ddaa2e2bfdebef8a in a CI system. As @meteorcloudy , I could never reproduce this on my local machine.

**Comment by meteorcloudy** [comment] 2017-10-10 09:42
I finally figure out the root cause, it's a one-liner fix. I'll send it soon.

**Comment by snnn** [comment] 2017-10-22 12:38
Hi @meteorcloudy , How is it going? Is it solved?

**Comment by meteorcloudy** [comment] 2017-10-23 14:14
Well, it turned out to be much more complicated that I thought. But yes! I have a fix under review, it will be fixed soon. https://bazel-review.googlesource.com/#/c/bazel/+/18790/

**Closed** 2017-10-24 13:39 UTC
Labels: category: multi-platform > windows, P1, type: bug
