### ISSUE TITLE
incompatible_disable_legacy_cc_provider: Deprecate old C++ Starlark provider API

### ISSUE THREAD

**Issue by oquenchil** [bazelbuild/bazel#7036] opened 2019-01-04 08:07 UTC
**Flag:** --incompatible_disable_legacy_cc_provider
**Available since:** 0.22 (January 2019 release)
**Will be flipped in:** 0.25 (March 2019 release)
**Tracking issue:** #4570 

This is a tracking issue for the removal of the legacy C++ Starlark provider.

We are deprecating this old API in favor of the new C++ Starlark API that will be fully supported in the future and will provide more functionality than this deprecated API.

### Migration instructions

Replacements:

| Old API  | New API |
| ------------- | ------------- |
| `dep.cc.transitive_headers` | `dep[CcInfo].compilation_context.headers`  |
| `dep.cc.defines`  | `dep[CcInfo].compilation_context.defines.to_list()`  |
| `dep.cc.system_include_directories` | `dep[CcInfo].compilation_context.system_includes.to_list()` |
| `dep.cc.include_directories` | `dep[CcInfo].compilation_context.includes.to_list()` |
| `dep.cc.quote_include_directories` | `dep[CcInfo].compilation_context.quote_includes.to_list()` |
| `dep.cc.link_flags` | `dep[CcInfo].linking_context.user_link_flags` |
| `dep.cc.libs` | `get_libs_for_static_executable(dep)` |
| `dep.cc.compile_flags` | `get_compile_flags(dep)` |

For the methods `get_libs_for_static_executable` and `get_compile_flags`, see as an example: https://gist.github.com/oquenchil/7e2c2bd761aa1341b458cc25608da50c

**Comment by hlopko** [comment] 2019-01-04 12:10
CC @lberki

**Comment by jayconrod** [comment] 2019-01-08 00:02
Flipping this flag breaks rules_go. We need to be able to compile against and link C/C++/ObjC code. We need *most* of the information in this provider, such as `defines`, `include_directories`, `transitive_headers`, `link_flags`...

Is there a replacement? What's the migration plan?

**Comment by hlopko** [comment] 2019-01-08 06:11
Yup we'know go needs replacement. Pedro will write solid migration docs once he's back from vacation. If I had to steal comment from his unsubmitted cl, the rough plan is:

```
dep.cc.transitive_headers -> dep[CcInfo].compilation_context.headers
dep.cc.defines -> dep[CcInfo].compilation_context.defines.to_list()
dep.cc.system_include_directories -> dep[CcInfo].compilation_context.system_includes.to_list()
dep.cc.include_directories -> dep[CcInfo].compilation_context.includes.to_list()
dep.cc.quote_include_directories -> dep[CcInfo].compilation_context.quote_includes.to_list()
dep.cc.link_flags = dep[CcInfo].linking_context.user_link_flags
dep.cc.libs = get_libs_for_static_executable(dep)
dep.cc.compile_flags = get_compile_flags(dep)
```

`get_libs_for_static_executable` and `get_compile_flags` will be provided such they return what legacy provider returned. We expect at least users be surprised by what was returned and prefer to use custom logic for `get_libs_for_static_executable` and use C++ toolchain api for `get_compile_flags`.

**Comment by jayconrod** [comment] 2019-01-08 15:23
Cool, thanks for sharing those instructions. It doesn't look like `CcInfo` or `ProtoInfo` are documented yet. Are those new in Bazel 0.22.0?

Basically, I'm wondering when I should do the migration in rules_go, and how big the support window of Bazel versions can be. Since Starlark resolves symbols eagerly, and `CcInfo` and `ProtoInfo` need to be used directly (not through reflection), I think releases before migration will have a maximum Bazel version of 0.23.0, and releases after migration will have a minimum version of Bazel 0.22.0. Does that sound right?

**Comment by hlopko** [comment] 2019-01-08 16:50
(Where do you see ProtoInfo?)

Pedro will know if CcInfo was in 0.21 or sooner (ping @oquenchil).

What you can do in these cases is to use [versions.bzl](https://github.com/bazelbuild/bazel-skylib/blob/master/lib/versions.bzl) in the repository rule to pick the right version of the analysis time bzl file depending on the bazel version. We do that in rules_rust ([this is the PR](https://github.com/bazelbuild/rules_rust/pull/133), but look for the state at head, I generated many bugs there).

Does that solve your issue?

**Comment by jayconrod** [comment] 2019-01-08 17:46
I found `ProtoInfo` mentioned in #6901. Seems like both providers are deprecated in 0.22.0.

About using versions.bzl and the repository rule, that would definitely work, thanks for pointing it out in rules_rust. It's unclear to me if the additional compatibility is worth the maintenance cost though. Will have to think about it.

**Comment by hlopko** [comment] 2019-01-11 08:56
We have some issues with the doc generation, in the meantime, here are docs:

https://docs.bazel.build/versions/master/skylark/lib/CcInfo.html
https://docs.bazel.build/versions/master/skylark/lib/CompilationContext.html
https://docs.bazel.build/versions/master/skylark/lib/LinkingContext.html
https://docs.bazel.build/versions/master/skylark/lib/cc_common.html#create_compilation_context
https://docs.bazel.build/versions/master/skylark/lib/cc_common.html#create_linking_context
https://docs.bazel.build/versions/master/skylark/lib/cc_common.html#create_library_to_link

**Comment by dslomov** [comment] 2019-01-11 16:55
Please update this bug with information about what is breaking and (at least roughly) what is the migration path

**Comment by oquenchil** [comment] 2019-01-14 09:47
I added migration instructions .

**Comment by keith** [comment] 2019-01-14 18:17
@oquenchil I think there's a depo for the new version of `system_include_directories`

**Comment by keith** [comment] 2019-01-14 19:10
It also looks like this legacy shim file isn't in the 0.22 RC https://github.com/bazelbuild/bazel/tree/release-0.22.0/tools/cpp is this something that's going to be released with this or not? Otherwise we can't migrate until 0.23

**Comment by jmillikin** [comment] 2019-01-15 01:57
The docstring for `linking_context` in https://docs.bazel.build/versions/master/skylark/lib/CcInfo.html has a typo. It is `CcLinkingContext`, and should be `LinkingContext` to match https://docs.bazel.build/versions/master/skylark/lib/LinkingContext.html.

Alternatively, prefix the context types with `Cc` so the user doesn't have to what what _kind_ of compilation it's contexting.

**Comment by oquenchil** [comment] 2019-01-15 09:11
Thank you very much @keith, I fixed the table. Regarding the shim, it's not really necessary, it's just there for your inspiration. The old API isn't completely correct. 

The first method `get_compile_flags` doesn't return the compilation command line that the C++ toolchain API would (for example, on Windows using MSVC it will still use GCC style flags). Therefore, it's better to use the C++ toolchain API.

For the second method `get_libs_for_static_executable`, the artifacts are correct for a static executable but if you use the new API directly you can customize for your own rule depending on what type of libraries you support. For example  `get_libs_for_static_executable` may return dynamic libraries when you expect only static libraries.

If you are sure that the logic that you want is what is in the shim, then you can just copy over what is here to your own rules: https://github.com/bazelbuild/bazel/blob/master/tools/cpp/legacy_cc_starlark_api_shim.bzl

@jmillikin thank you for pointing that out. We are aware of it, this is due to a deprecated class that is still lying around. The documentation is auto-generated, that class will go away with the next release so the docs should be fixed.

**Comment by aehlig** [comment] 2019-01-15 09:34
> It also looks like this legacy shim file isn't in the 0.22 RC https://github.com/bazelbuild/bazel/tree/release-0.22.0/tools/cpp is this something that's going to be released with this or not?

Our policy is to not cherry-pick for features. So you will have to delay the migration.

**Comment by dslomov** [comment] 2019-01-15 11:51
> > It also looks like this legacy shim file isn't in the 0.22 RC https://github.com/bazelbuild/bazel/tree/release-0.22.0/tools/cpp is this something that's going to be released with this or not?
> 
> Our policy is to not cherry-pick for features. So you will have to delay the migration.

Does this mean we need to delay the breaking change beyond 0.23 @oquenchil @hlopko ?

**Comment by oquenchil** [comment] 2019-01-15 12:02
No need to postpone. As I commented in https://github.com/bazelbuild/bazel/issues/7036#issuecomment-454318679, people don't need to rely on the bzl file.

**Comment by oquenchil** [comment] 2019-01-15 13:32
I deleted the file from Bazel. I created a gist instead that people can copy.

**Comment by jmillikin** [comment] 2019-01-16 04:49
I'm trying out the CcInfo provider and got a Java stack trace from what seemed like a minimal "compile C source to object code" rule.

```
$ ./bazel-0.22.0rc1-darwin-x86_64 build //tests:hello_c_bin
Starting local Bazel server and connecting to it...
INFO: Invocation ID: a8940993-1551-474c-9650-a00917bd7219
Internal error thrown during build. Printing stack trace: java.lang.RuntimeException: Unrecoverable error while evaluating node '//tests:hello_c BuildConfigurationValue.Key[1e08ea8021436b7c999c252f16135df1] false' (requested by nodes '//tests:hello_c_bin BuildConfigurationValue.Key[1e08ea8021436b7c999c252f16135df1] false')
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:514)
	at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:368)
	at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.localPopAndExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
Caused by: java.lang.IllegalArgumentException: Invalid EvalException:
java.lang.IllegalStateException
	at com.google.common.base.Preconditions.checkState(Preconditions.java:491)
	at com.google.devtools.build.lib.rules.cpp.LinkerInputs$CompoundLibraryToLink.<init>(LinkerInputs.java:333)
	at com.google.devtools.build.lib.rules.cpp.LinkerInputs$CompoundLibraryToLink.<init>(LinkerInputs.java:287)
	at com.google.devtools.build.lib.rules.cpp.LinkerInputs.newInputLibrary(LinkerInputs.java:539)
	at com.google.devtools.build.lib.rules.cpp.LibraryToLinkWrapper.getPicStaticLibraryToLink(LibraryToLinkWrapper.java:990)
	at com.google.devtools.build.lib.rules.cpp.LibraryToLinkWrapper.buildStaticModeParamsForDynamicLibraryCcLinkParams(LibraryToLinkWrapper.java:886)
	at com.google.devtools.build.lib.rules.cpp.LibraryToLinkWrapper.toCcLinkingInfo(LibraryToLinkWrapper.java:346)
	at com.google.devtools.build.lib.rules.cpp.LibraryToLinkWrapper$CcLinkingContext.toCcLinkingInfo(LibraryToLinkWrapper.java:179)
	at com.google.devtools.build.lib.rules.cpp.CcInfo$Provider.createInfo(CcInfo.java:150)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.devtools.build.lib.syntax.MethodDescriptor.call(MethodDescriptor.java:134)
	at com.google.devtools.build.lib.syntax.FuncallExpression.callFunction(FuncallExpression.java:990)
	at com.google.devtools.build.lib.syntax.FuncallExpression.doEval(FuncallExpression.java:897)
	at com.google.devtools.build.lib.syntax.Expression.eval(Expression.java:69)
	at com.google.devtools.build.lib.syntax.ListLiteral.doEval(ListLiteral.java:106)
	at com.google.devtools.build.lib.syntax.Expression.eval(Expression.java:69)
	at com.google.devtools.build.lib.syntax.UserDefinedFunction.call(UserDefinedFunction.java:89)
	at com.google.devtools.build.lib.syntax.BaseFunction.callWithArgArray(BaseFunction.java:475)
	at com.google.devtools.build.lib.syntax.BaseFunction.call(BaseFunction.java:437)
	at com.google.devtools.build.lib.analysis.skylark.SkylarkRuleConfiguredTargetUtil.buildRule(SkylarkRuleConfiguredTargetUtil.java:123)
	at com.google.devtools.build.lib.analysis.ConfiguredTargetFactory.createRule(ConfiguredTargetFactory.java:308)
	at com.google.devtools.build.lib.analysis.ConfiguredTargetFactory.createConfiguredTarget(ConfiguredTargetFactory.java:207)
	at com.google.devtools.build.lib.skyframe.SkyframeBuildView.createConfiguredTarget(SkyframeBuildView.java:758)
	at com.google.devtools.build.lib.skyframe.ConfiguredTargetFunction.createConfiguredTarget(ConfiguredTargetFunction.java:780)
	at com.google.devtools.build.lib.skyframe.ConfiguredTargetFunction.compute(ConfiguredTargetFunction.java:326)
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:437)
	at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:368)
	at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.localPopAndExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)

	at com.google.devtools.build.lib.syntax.EvalException.<init>(EvalException.java:112)
	at com.google.devtools.build.lib.syntax.EvalException$EvalExceptionWithJavaCause.<init>(EvalException.java:209)
	at com.google.devtools.build.lib.syntax.EvalException$EvalExceptionWithJavaCause.<init>(EvalException.java:217)
	at com.google.devtools.build.lib.syntax.MethodDescriptor.call(MethodDescriptor.java:167)
	at com.google.devtools.build.lib.syntax.FuncallExpression.callFunction(FuncallExpression.java:990)
	at com.google.devtools.build.lib.syntax.FuncallExpression.doEval(FuncallExpression.java:897)
	at com.google.devtools.build.lib.syntax.Expression.eval(Expression.java:69)
	at com.google.devtools.build.lib.syntax.ListLiteral.doEval(ListLiteral.java:106)
	at com.google.devtools.build.lib.syntax.Expression.eval(Expression.java:69)
	at com.google.devtools.build.lib.syntax.UserDefinedFunction.call(UserDefinedFunction.java:89)
	at com.google.devtools.build.lib.syntax.BaseFunction.callWithArgArray(BaseFunction.java:475)
	at com.google.devtools.build.lib.syntax.BaseFunction.call(BaseFunction.java:437)
	at com.google.devtools.build.lib.analysis.skylark.SkylarkRuleConfiguredTargetUtil.buildRule(SkylarkRuleConfiguredTargetUtil.java:123)
	at com.google.devtools.build.lib.analysis.ConfiguredTargetFactory.createRule(ConfiguredTargetFactory.java:308)
	at com.google.devtools.build.lib.analysis.ConfiguredTargetFactory.createConfiguredTarget(ConfiguredTargetFactory.java:207)
	at com.google.devtools.build.lib.skyframe.SkyframeBuildView.createConfiguredTarget(SkyframeBuildView.java:758)
	at com.google.devtools.build.lib.skyframe.ConfiguredTargetFunction.createConfiguredTarget(ConfiguredTargetFunction.java:780)
	at com.google.devtools.build.lib.skyframe.ConfiguredTargetFunction.compute(ConfiguredTargetFunction.java:326)
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:437)
	... 6 more
```

rule:
```python
load(
    "@bazel_tools//tools/build_defs/cc:action_names.bzl",
    _C_COMPILE = "C_COMPILE_ACTION_NAME",
)
def _cc_compile(ctx, source, header, output, use_pic):
    cc_toolchain = ctx.attr._cc_toolchain[cc_common.CcToolchainInfo]

    features = cc_common.configure_features(
        cc_toolchain = cc_toolchain,
    )
    cc_ctx = cc_common.create_compilation_context(
        headers = depset([header]),
    )
    cc_compiler = cc_common.get_tool_for_action(
        feature_configuration = features,
        action_name = _C_COMPILE,
    )
    cc_vars = cc_common.create_compile_variables(
        cc_toolchain = cc_toolchain,
        feature_configuration = features,
        source_file = source.path,
        output_file = output.path,
        use_pic = use_pic,
    )
    cc_argv = cc_common.get_memory_inefficient_command_line(
        feature_configuration = features,
        action_name = _C_COMPILE,
        variables = cc_vars,
    )
    cc_env = cc_common.get_environment_variables(
        feature_configuration = features,
        action_name = _C_COMPILE,
        variables = cc_vars,
    )
    ctx.actions.run(
        inputs = depset([source, header]) + ctx.attr._cc_toolchain[DefaultInfo].files,
        outputs = [output],
        executable = cc_compiler,
        arguments = cc_argv,
        mnemonic = "CppCompile",
        progress_message = "testing cc toolchain",
        env = cc_env,
    )

def _flex_lexer_impl(ctx):
    c_src = ctx.actions.declare_file("{}.c".format(ctx.attr.nam))
    c_hdr = ctx.actions.declare_file("{}.h".format(ctx.attr.name))

    # ... actions to create c_src and c_hdr ...
    
    out_obj = ctx.actions.declare_file("{}.o".format(ctx.attr.name))
    out_obj_pic = ctx.actions.declare_file("{}.pic.o".format(ctx.attr.name))
    _cc_compile(ctx, out_src, out_hdr, out_obj, use_pic = False)
    _cc_compile(ctx, out_src, out_hdr, out_obj_pic, use_pic = True)

    cc_toolchain = ctx.attr._cc_toolchain[cc_common.CcToolchainInfo]

    features = cc_common.configure_features(
        cc_toolchain = cc_toolchain,
    )
    linking_context = cc_common.create_linking_context(
        libraries_to_link = [cc_common.create_library_to_link(
            actions = ctx.actions,
            feature_configuration = features,
            cc_toolchain = cc_toolchain,
            static_library = out_obj,
            pic_static_library = out_obj_pic,
        )],
    )

    return CcInfo(linking_context = linking_context)
```

BUILD file:
```
load("//flex:flex.bzl", "flex_lexer")

flex_lexer(
    name = "hello_c",
    src = "hello.l",
)

cc_binary(
    name = "hello_c_bin",
    deps = [":hello_c"],
)
```

**Comment by jmillikin** [comment] 2019-01-16 14:40
> If it doesn't work with the old API, the incompatible change can stay for this release and the crash would be fixed the release after.

I haven't tried it with the old API. This particular crash (incorrect and possibly glob()-supplied param crashing the entire Bazel process) seems like it's worth cherrypicking a fix for.

**Comment by hlopko** [comment] 2019-01-16 14:52
To be honest I'm not clear on this corner of the cherry-pick policy. @aehlig, do we allow cherrypicking fixes for the new functionality introduced in the candidate?

**Comment by aehlig** [comment] 2019-01-16 16:02
> @aehlig, do we allow cherrypicking fixes for the new functionality introduced in the candidate?

Our policy is clear here: we only cherry-pick fixes for regressions with respect to previous releases. The new functionality wasn't working (because it wasn't present) in 0.21, so it being broken in 0.22 is not a reason for a cherry pick.

**Comment by keith** [comment] 2019-01-18 17:21
I think there's another issue here related to the migration window. It looks like `quote_includes` doesn't exist in 0.21, so for [some projects](https://github.com/bazelbuild/rules_swift/pull/129) we won't be able to migrate until after the release

**Comment by hlopko** [comment] 2019-01-21 06:34
That's expected, the migration window for this flag is 0.22 (released hopefully this week) and it will be flipped in 0.23 (released late February) = 1 release. If you want, you can make your change forward compatible by using Skylib's [versions.bzl](https://github.com/bazelbuild/bazel-skylib/blob/master/lib/versions.bzl) (see https://github.com/bazelbuild/bazel/issues/7036#issuecomment-452370220).

**Comment by jayconrod** [comment] 2019-01-22 15:17
@hlopko FYI, I don't think the versions.bzl trick will work for all projects. In particular, I don't think it will work for rules_go without a breaking change in the WORKSPACE boilerplate.

The Starlark interpreter resolves symbols eagerly, so there can't be references to `CcInfo` in .bzl files that may be loaded by older versions of Bazel, even if those references are never evaluated. So as you suggested above, we can load compatibility functions from a .bzl file in a repository rule which uses versions.bzl to select an implementation.

The catch, for rules_go at least, is that we load all our public symbols from one file, `//go:def.bzl`, including our repository rules. That means .bzl files reachable from `//go:def.bzl` can't reference anything in external repositories, since nothing has been declared at the time those files are loaded.

If I were starting over today, I'd put all the repository rules in a separate file, `//go:deps.bzl`, so that everything reachable from `//go:def.bzl` could assume the necessary external repos have already been declared. This is what Gazelle does in order to use Skylib. Making this change now would require users to update their WORKSPACE to continue using old versions of Bazel.

It's not clear to me if that migration is worth making. The rules_go API isn't changing much anymore, so I'm hoping it will be easy enough for devs to update to newer rules_go major versions in order to get support for newer Bazel versions.

**Comment by hlopko** [comment] 2019-01-22 19:58
Then there is an option of checking in https://github.com/bazelbuild/bazel-skylib/blob/master/lib/versions.bzl in rules_go (or the part that is used). Or I missed your point?

**Comment by jayconrod** [comment] 2019-01-22 21:02
@hlopko We actually have versions.bzl checked in already, that's not the issue.

I started prototyping this a couple days ago. I wanted to have a compat.bzl file which would provide several constants and wrapper functions for different versions of Bazel. This would be loaded as `@io_bazel_rules_go_compat//:compat.bzl`. The `io_bazel_rules_go_compat` workspace would be declared in `go_rules_dependencies` (where we declare other dependencies) using a repository rule. The repository rule would use `versions.bzl` to select one of several .bzl files to be copied to `compat.bzl`.

The problem was that in WORKSPACE, we need to load `@io_bazel_rules_go//go:def.bzl` into order to get `go_rules_dependencies`, and `@io_bazel_rules_go_compat//:compat.bzl` is loaded transitively from `@io_bazel_rules_go//go:def.bzl`, before the `io_bazel_rules_compat` repo can be declared. So we get a cyclic load error.

**Comment by hlopko** [comment] 2019-01-24 22:46
Oh, is it because you load `@rules_go//go:def.bzl` from both `WORKSPACE` and `BUILD` files? Yeah I didn't think about that. I'm curious (for rules_cc), was this a conscious decision? What were the reasons to not use 2 separate bzl files?

**Comment by jayconrod** [comment] 2019-01-24 23:12
@hlopko "It was like that when I got here." :)

Seriously though, rules_go used to be that all definitions could be in `//go:def.bzl`, and it was only ~300 lines of code. Eventually, we moved stuff into private directories, but `//go:def.bzl` was always the single thing that people could load to get public definitions.

When I pulled Gazelle out into its own repository, I added separate `//:deps.bzl` (for WORKSPACE definitions) and `//:def.bzl` (for other definitions). That was necessary to add a Skylib dependency. Maybe rules_go should move to that model for newer releases. It depends on how many breaking changes are expected in the future and how long the support window needs to be.

**Comment by katre** [comment] 2019-03-01 16:20
This issue was tagged as "breaking-change-0.24" but does not appear ready to be flipped in the [0.24.0 release](https://github.com/bazelbuild/bazel/issues/6968). If this is incorrect please comment on that issue and discuss with me.

**Comment by meteorcloudy** [comment] 2019-03-22 10:26
@oquenchil Looks like the only failing projects are rules_rust and TensorFlow. TensorFlow is already disabled in downstream, if you want to flip the flag for catching the 0.25.0 cut, you can send a PR to disable rules_rust as well. 
For example https://github.com/bazelbuild/continuous-integration/commit/69cf7ec23d984dcbb41fffe946e07ebf5ab7e0f1

**Comment by hlopko** [comment] 2019-03-27 06:12
I'll flip it later this week if nothing new shows up.

**Closed** 2019-03-29 13:58 UTC
Labels: P1, bazel 1.0, breaking-change-0.25, incompatible-change, migration-0.22, migration-0.23, migration-0.24, team-Rules-CPP
