### ISSUE TITLE
improve usability of --experimental_execution_log_file

### ISSUE THREAD

**Issue by agoulti** [bazelbuild/bazel#6807] opened 2018-11-30 10:29 UTC
I want to move --experimental_execution_log_file and --experimental_workspace_rules_log_file flags out of experimental and made some adjustments to their usability.

Currently these flags dump binary proto files. So to use the logs, the users currently need to compile their respective parsers from source. I want to add the ability to output them in json, similar to how 
[Build Event Protocol](https://docs.bazel.build/versions/master/build-event-protocol.html#consume-in-a-binary-format) is being handled.

Then the two flags would become the following four:
--execution_log_binary_file
--execution_log_json_file
--workspace_rules_log_binary_file 
--workspace_rules_log_json_file 

This would also allow one to use the tools such as [jq](https://stedolan.github.io/jq/) to do the same filtering as the parsers, and much more.

One wrinkle in this has to do with execution log files. In order to be able to compare two execution logs, we need to ensure that actions appear in the same order (since Bazel is parallel, the order is nondeterministic even with an identical build).

To alleviate this, we propose the execution log files to be always sorted in a stable way as follows:

* If some output of action A appears as an input to action B, A will appear before B.
* When not constrained by (transitive) 1., any action whose name of the first output is lexicographically smaller would appear earlier.

If the execution log is enabled, Bazel would write a temporary file to disk the same way execution log is currently handled. At the end of the build is would read the file back, perform the sort, and write it out in the desired format.

**Comment by iirina** [comment] 2018-12-03 10:10
@agoulti can you assign a priority according to [priority levels](https://www.bazel.build/maintainers-guide.html#priority)?

**Comment by luxe** [comment] 2019-12-25 04:55
These flags exist today in 2.0
Is there more to be done here?

**Comment by alanfalloon** [comment] 2021-05-10 20:37
I would prefer the execution logs not be sorted at all. Our build is huge, and the sorting step on the execution log is causing bazel to crash with OOM -- luckily the raw unsorted log is left behind in a temp dir somewhere that I can recover it. For reference, a recent log of only part of our build was over 10G, and that isn't even the whole build, just one target (admittedly a top-level target).

The comparison issue should be pushed to the tool that consumes the logs, since I don't need to compare I don't want to pay the cost to sort the log.

**Comment by meisterT** [comment] 2021-05-11 14:00
Did the sorting step ever get implemented? I thought it was just a proposal?

**Comment by alanfalloon** [comment] 2021-05-12 17:40
Some kind of memory intensive post-processing exists in 4.0.0. I presume its sorting, but its easy enough to see: enabling this feature causes a *long* delay after test/build completes, even when it doesn't crash.

**Comment by meisterT** [comment] 2021-05-17 08:26
Alan, the execution log has an overhead per action, see https://cs.opensource.google/bazel/bazel/+/master:src/main/java/com/google/devtools/build/lib/exec/SpawnLogContext.java;l=73;drc=7c92cfcf9a88933c29334f6271ad3f086f7f36f4

But I don't see it doing anything *after* the test/build completes. Do you have any reproduction instructions? If you are seeing this, you may also grab a stack trace with `Ctrl+\`.

**Comment by agoulti** [comment] 2021-05-17 09:55
Tobias: yes, the sorting step was implemented.

It would be here: 
https://github.com/bazelbuild/bazel/blob/09c621e4cf5b968f4c6cdf905ab142d5961f9ddc/src/main/java/com/google/devtools/build/lib/bazel/SpawnLogModule.java#L161

If the new version of the flag is specified (execution_log_binary_file), after the build completes the log is sorted before being output.

I believe the old version of the flag (--experimental_execution_log_file) is still available and will output the raw file without attempting to sort it. It can then be processed using the Log Parser: (https://cs.opensource.google/bazel/bazel/+/master:src/tools/execlog/

**Comment by meisterT** [comment] 2021-05-17 13:33
Thanks Alexandra, I missed that (and was experimenting with `--experimental_execution_log_file`).

Alan, does that raw file help you?

**Comment by alanfalloon** [comment] 2021-05-27 18:56
That appears to do what I need, thank you. I don't observe the long delay and spike in memory usage if I stick to the old flag.

**Comment by ptarjan** [comment] 2022-03-28 21:48
+1 to the sorting step being memory intensive. This flag is sadly unusable for us as it OOMs the process after an hour of working. Can the sorting be done in a less memory intensive manner? Or farmed out to unix `sort`?

**Comment by meisterT** [comment] 2022-05-02 21:39
I don't see a way to farm this out to Unix `sort`.

I somehow have the suspicion that https://github.com/bazelbuild/bazel/blob/09c621e4cf5b968f4c6cdf905ab142d5961f9ddc/src/main/java/com/google/devtools/build/lib/bazel/execlog/StableSort.java#L108 is the issue here.

Do you happen to have a public repro that I can try?

**Comment by ptarjan** [comment] 2022-05-03 16:37
Sadly I don’t. It was in our private company repo. I’m on vacation so can’t
help cook one up but it should be easy to repro with a sharded test.

**Comment by cameron-martin** [comment] 2024-01-09 22:16
Isn't this fixed now with bazel 7? A separate flag exists for whether the output is sorted.

**Comment by tjgq** [comment] 2024-01-10 10:37
I think we can close this one, yes. We're implementing a more efficient execution log format, but that's already tracked at https://github.com/bazelbuild/bazel/issues/18643.

**Closed by tjgq** 2024-01-10 10:37 UTC
Labels: type: feature request, P2, team-Remote-Exec
