### ISSUE TITLE
`load`ing a non-existent external in `WORKSPACE` yields an `IllegalStateException`

### ISSUE THREAD

**Issue by nelhage** [bazelbuild/bazel#1670] opened 2016-08-21 15:46 UTC
If you attempt to load a `.bzl` file from a non-existent external, `bazel` dies with an inscrutable `IllegalStateException`, instead of a more helpful error message.

```
[nelhage@monomorphique:/tmp/bazelbug]$ cat WORKSPACE
load("@some_external//:rules.bzl", "some_rule")
[nelhage@monomorphique:/tmp/bazelbug]$ bazel query //...
.
java.lang.IllegalStateException: topLevelKey: TARGET_PATTERN://...
alreadyReported: false
path to cycle:
TARGET_PATTERN://...
RECURSIVE_PKG:rootedPath=[/tmp/bazelbug]/[], excludedPaths=<omitted>)
PACKAGE:
PACKAGE:external
EXTERNAL_PACKAGE:[/tmp/bazelbug]/[WORKSPACE]
cycle:
WORKSPACE_FILE:[/tmp/bazelbug]/[WORKSPACE], 1
SKYLARK_IMPORTS_LOOKUP:com.google.devtools.build.lib.skyframe.SkylarkImportLookupValue$SkylarkImportLookupKey@b748f0a1
AST_FILE_LOOKUP:@some_external//:rules.bzl
PACKAGE_LOOKUP:@some_external//
REPOSITORY:@some_external
REPOSITORY_DIRECTORY:@some_external

        at com.google.common.base.Preconditions.checkState(Preconditions.java:174)
        at com.google.devtools.build.lib.util.Preconditions.checkState(Preconditions.java:201)
        at com.google.devtools.build.skyframe.CyclesReporter.reportCycles(CyclesReporter.java:82)
        at com.google.devtools.build.lib.skyframe.SkyframeTargetPatternEvaluator.parseTargetPatternKeys(SkyframeTargetPatternEvaluator.java:164)
        at com.google.devtools.build.lib.skyframe.SkyframeTargetPatternEvaluator.parseTargetPatternList(SkyframeTargetPatternEvaluator.java:117)
        at com.google.devtools.build.lib.skyframe.SkyframeTargetPatternEvaluator.parseTargetPatternList(SkyframeTargetPatternEvaluator.java:56)
        at com.google.devtools.build.lib.skyframe.SkyframeTargetPatternEvaluator.parseTargetPattern(SkyframeTargetPatternEvaluator.java:62)
        at com.google.devtools.build.lib.skyframe.SkyframeTargetPatternEvaluator.preloadTargetPatterns(SkyframeTargetPatternEvaluator.java:86)
        at com.google.devtools.build.lib.query2.BlazeQueryEnvironment.preloadOrThrow(BlazeQueryEnvironment.java:436)
        at com.google.devtools.build.lib.query2.AbstractBlazeQueryEnvironment.evaluateQuery(AbstractBlazeQueryEnvironment.java:112)
        at com.google.devtools.build.lib.query2.BlazeQueryEnvironment.evaluateQuery(BlazeQueryEnvironment.java:126)
        at com.google.devtools.build.lib.query2.BlazeQueryEnvironment.evaluateQuery(BlazeQueryEnvironment.java:66)
        at com.google.devtools.build.lib.runtime.commands.QueryCommand.exec(QueryCommand.java:173)
        at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.execExclusively(BlazeCommandDispatcher.java:488)
        at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.exec(BlazeCommandDispatcher.java:324)
        at com.google.devtools.build.lib.runtime.CommandExecutor.exec(CommandExecutor.java:49)
        at com.google.devtools.build.lib.server.RPCService.executeRequest(RPCService.java:70)
        at com.google.devtools.build.lib.server.AfUnixServer.executeRequest(AfUnixServer.java:418)
        at com.google.devtools.build.lib.server.AfUnixServer.serve(AfUnixServer.java:215)
        at com.google.devtools.build.lib.runtime.BlazeRuntime.serverMain(BlazeRuntime.java:737)
        at com.google.devtools.build.lib.runtime.BlazeRuntime.main(BlazeRuntime.java:519)
        at com.google.devtools.build.lib.bazel.BazelMain.main(BazelMain.java:56)
java.lang.IllegalStateException: topLevelKey: TARGET_PATTERN://...
alreadyReported: false
path to cycle:
TARGET_PATTERN://...
RECURSIVE_PKG:rootedPath=[/tmp/bazelbug]/[], excludedPaths=<omitted>)
PACKAGE:
PACKAGE:external
EXTERNAL_PACKAGE:[/tmp/bazelbug]/[WORKSPACE]
cycle:
WORKSPACE_FILE:[/tmp/bazelbug]/[WORKSPACE], 1
SKYLARK_IMPORTS_LOOKUP:com.google.devtools.build.lib.skyframe.SkylarkImportLookupValue$SkylarkImportLookupKey@b748f0a1
AST_FILE_LOOKUP:@some_external//:rules.bzl
PACKAGE_LOOKUP:@some_external//
REPOSITORY:@some_external
REPOSITORY_DIRECTORY:@some_external

        at com.google.common.base.Preconditions.checkState(Preconditions.java:174)
        at com.google.devtools.build.lib.util.Preconditions.checkState(Preconditions.java:201)
        at com.google.devtools.build.skyframe.CyclesReporter.reportCycles(CyclesReporter.java:82)
        at com.google.devtools.build.lib.skyframe.SkyframeTargetPatternEvaluator.parseTargetPatternKeys(SkyframeTargetPatternEvaluator.java:164)
        at com.google.devtools.build.lib.skyframe.SkyframeTargetPatternEvaluator.parseTargetPatternList(SkyframeTargetPatternEvaluator.java:117)
        at com.google.devtools.build.lib.skyframe.SkyframeTargetPatternEvaluator.parseTargetPatternList(SkyframeTargetPatternEvaluator.java:56)
        at com.google.devtools.build.lib.skyframe.SkyframeTargetPatternEvaluator.parseTargetPattern(SkyframeTargetPatternEvaluator.java:62)
        at com.google.devtools.build.lib.skyframe.SkyframeTargetPatternEvaluator.preloadTargetPatterns(SkyframeTargetPatternEvaluator.java:86)
        at com.google.devtools.build.lib.query2.BlazeQueryEnvironment.preloadOrThrow(BlazeQueryEnvironment.java:436)
        at com.google.devtools.build.lib.query2.AbstractBlazeQueryEnvironment.evaluateQuery(AbstractBlazeQueryEnvironment.java:112)
        at com.google.devtools.build.lib.query2.BlazeQueryEnvironment.evaluateQuery(BlazeQueryEnvironment.java:126)
        at com.google.devtools.build.lib.query2.BlazeQueryEnvironment.evaluateQuery(BlazeQueryEnvironment.java:66)
        at com.google.devtools.build.lib.runtime.commands.QueryCommand.exec(QueryCommand.java:173)
        at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.execExclusively(BlazeCommandDispatcher.java:488)
        at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.exec(BlazeCommandDispatcher.java:324)
        at com.google.devtools.build.lib.runtime.CommandExecutor.exec(CommandExecutor.java:49)
        at com.google.devtools.build.lib.server.RPCService.executeRequest(RPCService.java:70)
        at com.google.devtools.build.lib.server.AfUnixServer.executeRequest(AfUnixServer.java:418)
        at com.google.devtools.build.lib.server.AfUnixServer.serve(AfUnixServer.java:215)
        at com.google.devtools.build.lib.runtime.BlazeRuntime.serverMain(BlazeRuntime.java:737)
        at com.google.devtools.build.lib.runtime.BlazeRuntime.main(BlazeRuntime.java:519)
        at com.google.devtools.build.lib.bazel.BazelMain.main(BazelMain.java:56)
```

This is obviously an error condition, but `bazel` should probably report a user-friendly error message instead of crashing.

**Comment by abergmeier-dsfishlabs** [comment] 2016-11-01 11:33
Got the same just now.

**Comment by damienmg** [comment] 2017-01-09 14:15
Duplicate of #1793, however I found another one with a nested repository.

**Comment by damienmg** [comment] 2017-02-17 09:38
The other case was fixed in https://github.com/bazelbuild/bazel/commit/448ee8124be341975633f67e35d699bbf57b963a

**Closed by damienmg** 2017-02-17 09:38 UTC
Labels: category: extensibility > skylark remote repositories, P2, type: bug
