### ISSUE TITLE
Adding dynamic_library to create_library_to_link() causes NPE

### ISSUE THREAD

**Issue by mboes** [bazelbuild/bazel#8129] opened 2019-04-24 12:19 UTC
### Description of the problem

I do not yet have a full minimal example. But consider the following incomplete snippet of code:

```python
    # XXX Workaround https://github.com/bazelbuild/bazel/issues/6874.
    # Should be find_cpp_toolchain() instead.
    cc_toolchain = ctx.attr._cc_toolchain[cc_common.CcToolchainInfo]
    feature_configuration = cc_common.configure_features(
        cc_toolchain = cc_toolchain,
        requested_features = ctx.features,
        unsupported_features = ctx.disabled_features,
    )
    library_to_link = cc_common.create_library_to_link(
        actions = ctx.actions,
        feature_configuration = feature_configuration,
        #dynamic_library = ctx.file.shared_library,
        static_library = ctx.file.static_library,
        cc_toolchain = cc_toolchain,
    )
    compilation_context = cc_common.create_compilation_context(
        headers = depset(ctx.files.hdrs),
        includes = depset(ctx.attr.includes),
    )
    linking_context = cc_common.create_linking_context(
        libraries_to_link = [library_to_link],
        user_link_flags = ctx.attr.linkopts,
    )
    cc_info = cc_common.merge_cc_infos(
        cc_infos = [
            CcInfo(
                compilation_context = compilation_context,
                linking_context = linking_context,
            )
        ] + [dep[CcInfo] for dep in ctx.attr.deps if CcInfo in dep]
    )
```

As is things work fine: the library produced by the rule to which the above snippet is part of the implementation gets linked statically by downstream dependencies and all is good. But if I want to offer the option to downstream of linking dynamically, then I uncomment the line that says,

```python
        #dynamic_library = ctx.file.shared_library,
```

Doing so results in a Bazel crash with the the following stack trace during the build:

```
FAILED: Build did NOT complete successfully (4 packages loaded, 292 targets configured)
Internal error thrown during build. Printing stack trace: java.lang.RuntimeException: Unrecoverable error while evaluating node '//tests/haskell_import:haskell_import BuildConfigurationValue.Key[a5227c6608aca346178473b6dff38bdf] false' (requested by nodes )
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:517)
	at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:370)
	at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1407)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
Caused by: java.lang.NullPointerException
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:877)
	at com.google.devtools.build.lib.vfs.PathFragment.startsWith(PathFragment.java:295)
	at com.google.devtools.build.lib.rules.cpp.LibrariesToLinkCollector.addLinkerInputs(LibrariesToLinkCollector.java:245)
	at com.google.devtools.build.lib.rules.cpp.LibrariesToLinkCollector.collectLibrariesToLink(LibrariesToLinkCollector.java:203)
	at com.google.devtools.build.lib.rules.cpp.CppLinkActionBuilder.build(CppLinkActionBuilder.java:870)
	at com.google.devtools.build.lib.rules.cpp.CcLinkingHelper.createDynamicLibrary(CcLinkingHelper.java:707)
	at com.google.devtools.build.lib.rules.cpp.CcLinkingHelper.createCcLinkActions(CcLinkingHelper.java:431)
	at com.google.devtools.build.lib.rules.cpp.CcLinkingHelper.link(CcLinkingHelper.java:340)
	at com.google.devtools.build.lib.rules.cpp.CcBinary.createTransitiveLinkingActions(CcBinary.java:788)
	at com.google.devtools.build.lib.rules.cpp.CcBinary.init(CcBinary.java:454)
	at com.google.devtools.build.lib.rules.cpp.CcTest.create(CcTest.java:36)
	at com.google.devtools.build.lib.rules.cpp.CcTest.create(CcTest.java:25)
	at com.google.devtools.build.lib.analysis.ConfiguredTargetFactory.createRule(ConfiguredTargetFactory.java:354)
	at com.google.devtools.build.lib.analysis.ConfiguredTargetFactory.createConfiguredTarget(ConfiguredTargetFactory.java:208)
	at com.google.devtools.build.lib.skyframe.SkyframeBuildView.createConfiguredTarget(SkyframeBuildView.java:764)
	at com.google.devtools.build.lib.skyframe.ConfiguredTargetFunction.createConfiguredTarget(ConfiguredTargetFunction.java:819)
	at com.google.devtools.build.lib.skyframe.ConfiguredTargetFunction.compute(ConfiguredTargetFunction.java:358)
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:440)
	... 7 more
java.lang.RuntimeException: Unrecoverable error while evaluating node '//tests/haskell_import:haskell_import BuildConfigurationValue.Key[a5227c6608aca346178473b6dff38bdf] false' (requested by nodes )
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:517)
	at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:370)
	at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1407)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
Caused by: java.lang.NullPointerException
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:877)
	at com.google.devtools.build.lib.vfs.PathFragment.startsWith(PathFragment.java:295)
	at com.google.devtools.build.lib.rules.cpp.LibrariesToLinkCollector.addLinkerInputs(LibrariesToLinkCollector.java:245)
	at com.google.devtools.build.lib.rules.cpp.LibrariesToLinkCollector.collectLibrariesToLink(LibrariesToLinkCollector.java:203)
	at com.google.devtools.build.lib.rules.cpp.CppLinkActionBuilder.build(CppLinkActionBuilder.java:870)
	at com.google.devtools.build.lib.rules.cpp.CcLinkingHelper.createDynamicLibrary(CcLinkingHelper.java:707)
	at com.google.devtools.build.lib.rules.cpp.CcLinkingHelper.createCcLinkActions(CcLinkingHelper.java:431)
	at com.google.devtools.build.lib.rules.cpp.CcLinkingHelper.link(CcLinkingHelper.java:340)
	at com.google.devtools.build.lib.rules.cpp.CcBinary.createTransitiveLinkingActions(CcBinary.java:788)
	at com.google.devtools.build.lib.rules.cpp.CcBinary.init(CcBinary.java:454)
	at com.google.devtools.build.lib.rules.cpp.CcTest.create(CcTest.java:36)
	at com.google.devtools.build.lib.rules.cpp.CcTest.create(CcTest.java:25)
	at com.google.devtools.build.lib.analysis.ConfiguredTargetFactory.createRule(ConfiguredTargetFactory.java:354)
	at com.google.devtools.build.lib.analysis.ConfiguredTargetFactory.createConfiguredTarget(ConfiguredTargetFactory.java:208)
	at com.google.devtools.build.lib.skyframe.SkyframeBuildView.createConfiguredTarget(SkyframeBuildView.java:764)
	at com.google.devtools.build.lib.skyframe.ConfiguredTargetFunction.createConfiguredTarget(ConfiguredTargetFunction.java:819)
	at com.google.devtools.build.lib.skyframe.ConfiguredTargetFunction.compute(ConfiguredTargetFunction.java:358)
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:440)
	... 7 more
java.lang.RuntimeException: Unrecoverable error while evaluating node '//tests/haskell_import:haskell_import BuildConfigurationValue.Key[a5227c6608aca346178473b6dff38bdf] false' (requested by nodes )
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:517)
	at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:370)
	at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1407)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
Caused by: java.lang.NullPointerException
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:877)
	at com.google.devtools.build.lib.vfs.PathFragment.startsWith(PathFragment.java:295)
	at com.google.devtools.build.lib.rules.cpp.LibrariesToLinkCollector.addLinkerInputs(LibrariesToLinkCollector.java:245)
	at com.google.devtools.build.lib.rules.cpp.LibrariesToLinkCollector.collectLibrariesToLink(LibrariesToLinkCollector.java:203)
	at com.google.devtools.build.lib.rules.cpp.CppLinkActionBuilder.build(CppLinkActionBuilder.java:870)
	at com.google.devtools.build.lib.rules.cpp.CcLinkingHelper.createDynamicLibrary(CcLinkingHelper.java:707)
	at com.google.devtools.build.lib.rules.cpp.CcLinkingHelper.createCcLinkActions(CcLinkingHelper.java:431)
	at com.google.devtools.build.lib.rules.cpp.CcLinkingHelper.link(CcLinkingHelper.java:340)
	at com.google.devtools.build.lib.rules.cpp.CcBinary.createTransitiveLinkingActions(CcBinary.java:788)
	at com.google.devtools.build.lib.rules.cpp.CcBinary.init(CcBinary.java:454)
	at com.google.devtools.build.lib.rules.cpp.CcTest.create(CcTest.java:36)
	at com.google.devtools.build.lib.rules.cpp.CcTest.create(CcTest.java:25)
	at com.google.devtools.build.lib.analysis.ConfiguredTargetFactory.createRule(ConfiguredTargetFactory.java:354)
	at com.google.devtools.build.lib.analysis.ConfiguredTargetFactory.createConfiguredTarget(ConfiguredTargetFactory.java:208)
	at com.google.devtools.build.lib.skyframe.SkyframeBuildView.createConfiguredTarget(SkyframeBuildView.java:764)
	at com.google.devtools.build.lib.skyframe.ConfiguredTargetFunction.createConfiguredTarget(ConfiguredTargetFunction.java:819)
	at com.google.devtools.build.lib.skyframe.ConfiguredTargetFunction.compute(ConfiguredTargetFunction.java:358)
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:440)
FAILED: Build did NOT complete successfully (4 packages loaded, 292 targets configured)
```

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

I will update the ticket with a minimal repro as soon as I have one.

### What operating system are you running Bazel on?

Linux (NixOS).

### What's the output of `bazel info release`?

bazel 0.24. I compiled a recent checkout of bazel master and get the same NPE.

**Comment by hlopko** [comment] 2019-04-24 14:03
(P1 because Bazel crash, we shouldn't crash Bazel).

**Comment by mboes** [comment] 2019-05-01 12:05
OK I finally have a repro (it is non-trivial and took quite a few hours to pin down!). See https://github.com/tweag/rules_haskell/tree/repro-bazel-8129. This branch contains a drastically paired down version of rules_haskell (about 100 lines).

The main features of the repro:

* We're using `cc_test`, not `cc_binary`.
* The `cc_test` depends on a non-cc library called `rts`.
* If the `cc_test` depends directly on `rts`, then things work fine. But if `cc_test` depends on it via an indirection, then we get the NPE.
* The indirection is a toolchain that embeds `rts` and its providers in the toolchain's provider.

Further minimizing the example to have the indirection be a rule that forwards all providers, rather than the toolchain thing above, seems to make the bug away. So the last bullet point above is apparently an essential feature of the repro.

**Comment by mboes** [comment] 2019-05-01 15:55
I haven't yet worked out a way to work around this. If you have ideas let me know.

**Comment by mboes** [comment] 2019-05-01 18:19
OK as far the workaround goes, using a custom provider along part of the dependency path works. It's extra code and extra complexity (e.g. to merge instances of the custom provider), so being able to use `CcInfo` all the way through would be nice. :)

**Comment by oquenchil** [comment] 2019-05-02 12:39
Thank you Mathieu for reporting this. I'm currently looking into it.

**Comment by oquenchil** [comment] 2019-05-03 09:04
So the problem here is not related to the C++ Starlark API. We will get the same error if we replace the haskell_import here with a cc_library rule:
https://github.com/tweag/rules_haskell/blob/fbdbc4e3297d6c6cfccf6dbcd2dd0c4e04df054b/haskell/nixpkgs.bzl#L12

The problem is that here:
https://github.com/bazelbuild/bazel/blob/fcf33965d9f4be90856f14f6fd04a7fb546a54d9/src/main/java/com/google/devtools/build/lib/rules/cpp/LibrariesToLinkCollector.java#L244

The toolchain library is built in the host configuration, therefore the path starts with bazel-out/host, unlike the solibDir and toolchainLibrariesSolibDir.

I will change the code so that the first segment of the path is ignored and the second is also ignored if it's host.

**Comment by oquenchil** [comment] 2019-05-03 09:41
This is not related to the C++ Starlark API. Replacing https://github.com/tweag/rules_haskell/blob/fbdbc4e3297d6c6cfccf6dbcd2dd0c4e04df054b/haskell/nixpkgs.bzl#L12 with a native cc_library triggers the same crash.

The problem is that the library gets built by the toolchain in the host configuraiton so the paths don't match here:
https://github.com/bazelbuild/bazel/blob/fcf33965d9f4be90856f14f6fd04a7fb546a54d9/src/main/java/com/google/devtools/build/lib/rules/cpp/LibrariesToLinkCollector.java#L245. The toolchain library's path starts with bazel-out/host, instead of having the cpu and mode.

I was first planning to fix this by just comparing the fourth segment in the paths but now I'm wondering whether toolchainLibrariesSolibDir should be set by the person creating the toolchain so that instead of "host" it says "{cpu}-{mode}" in the path. @hlopko wdyt?

**Comment by hlopko** [comment] 2019-05-08 09:09
Cc @katre 

The root of the problem is that currently toolchains are analyzed in the host configuration no matter what. Your haskell toolchain will get `libraries` in a different configuration than `cc_test` expects.

There is ongoing work to fix this:

* https://github.com/bazelbuild/proposals/blob/master/designs/2019-02-12-execution-transitions.md
* https://github.com/bazelbuild/proposals/blob/master/designs/2019-02-12-toolchain-transitions.md

@katre will know more about the status of this work.

**Comment by katre** [comment] 2019-05-08 09:27
Work is progressing. I expect the execution transition to go out in the 0.27 release next month, and at that point toolchains (like haskell) will need to migrate. I am not sure if the initial version of the toolchain transition will also be available in 0.27, or if it will be in 0.28.

**Comment by oquenchil** [comment] 2019-06-06 07:44
What's the status on this?

**Comment by hlopko** [comment] 2019-07-16 07:38
(leaving only @oquenchil assigned, so this issue has only one boss :)

**Comment by katre** [comment] 2020-05-11 16:08
The execution transition is live now, and so we should be able to start moving cc toolchains to use it. I expect we're going to need a lot of testing, however, because we've seen some very odd configurations arise out of the mix of target, exec, and android/apple transitions.

**Comment by katre** [comment] 2020-05-11 16:08
@oquenchil Is this actually a P1?

**Comment by aiuto** [comment] 2021-10-06 01:05
ping all.  Is this obsolete now?

**Comment by oquenchil** [comment] 2021-10-06 13:53
Yes, it's fixed.

**Closed by oquenchil** 2021-10-06 13:53 UTC
Labels: type: bug, P4, more data needed, team-Configurability, team-Rules-CPP
