### ISSUE TITLE
Release 5.0 - January 2022

### ISSUE THREAD

**Issue by Wyverald** [bazelbuild/bazel#14013] opened 2021-09-20 09:45 UTC
# Status of Bazel 5.0

- Target baseline: 2021-10-25
- Expected release date: 2022-01-19
- [5.0 release blockers](https://github.com/bazelbuild/bazel/milestone/31)

To report a release-blocking bug, please add it to the 5.0 release blocker milestone, and cc me.

Task list:

- [x] Pick release baseline: 8d66a4171baddcbe1569972f019e54130111202c
- [x] Create release candidate: 5.0.0rc1
- [x] Check downstream projects:
- [x] [Create draft release announcement](https://docs.google.com/document/d/1wDvulLlj4NAlPZamdlEVFORks3YXJonCjyuQMUQEmB0/edit)
- [x] Send for review the release announcement PR: https://github.com/bazelbuild/bazel-blog/pull/263
- [x] Push the release, notify package maintainers: https://github.com/bazelbuild/bazel/issues/14013#issuecomment-1016560372
- [x] Update the documentation
- [x] Push the blog post
- [x] Update the [release page](https://github.com/bazelbuild/bazel/releases/)

**Comment by aaliddell** [comment] 2021-09-20 16:43
Would you consider looking at https://github.com/bazelbuild/bazel/issues/7386 for Bazel 5? This was missed as a change on Bazel 4 and has been tripping people up for a long time. The proposed steps to change the default were begun with the addition of an incompatible flag but have got stuck there. Perhaps we can now move to flipping the default to disabling the creation of `__init__.py` files?

But perhaps this is too short notice now?

**Comment by danieljanes** [comment] 2021-09-20 17:24
...and (related to @aaliddell's comment above): #12238

**Comment by Wyverald** [comment] 2021-09-21 11:08
Thanks for flagging this; I'll check with @brandjon.

Although yeah, the purpose of this thread is more on the side of making sure any in-flight changes can make it into 5.0, rather than start prioritizing stuff now. Nevertheless, I see that this has been a long-standing issue, so let's see if we have the cycles to make it happen. (Alternatively, feel free to send PRs if you have the time!)

**Comment by Wyverald** [comment] 2021-09-22 14:12
re: `__init__.py`, please see @brandjon's update at https://github.com/bazelbuild/bazel/issues/7386#issuecomment-924320303

**Comment by matthewjh** [comment] 2021-09-24 16:16
What about #13879?

**Comment by Wyverald** [comment] 2021-09-27 14:32
I'll check with @coeuvre.

**Comment by philwo** [comment] 2021-10-01 10:24
Please add (potential) release blockers to this milestone: https://github.com/bazelbuild/bazel/milestone/31

**Comment by quval** [comment] 2021-10-05 17:12
I'm still hoping that #14011 can make the cut – it's been open for a while already been pre-reviewed by @oquenchil (see discussion on #13819), so hopefully there's not much work left before it can be merged.

**Comment by quval** [comment] 2021-10-05 17:34
Thanks, @philwo – not sure I'd say it's a release blocker, I'm just hoping to get that bug fixed :)

**Comment by philwo** [comment] 2021-10-05 17:42
Yeah, let's just put it on the list so we don't forget about it 😊 Easier to track open PRs / issues in a milestone than a free-form text like here. If it turns out to be too difficult to merge, we can push it back to the backlog.

**Comment by brentleyjones** [comment] 2021-10-20 17:58
@Wyverald I guess cherry-picks?

**Comment by bjacklyn** [comment] 2021-11-10 01:15
Is there going to be a push to release 5.0 before Bazelcon (Nov 17-18)? :)

**Comment by Wyverald** [comment] 2021-11-16 16:33
> Is there going to be a push to release 5.0 before Bazelcon (Nov 17-18)? :)

Hey, sorry I missed this. The plan was to release around BazelCon, but some unexpected delays means that it probably won't be ready. We still need to push out an rc2 with all the cherrypicks and test it for some time before pushing the release out the door, so it might take another week or two. (Don't quote me on this :P)

In other news, I'll be OOO from 20 Nov to 4 Dec, and will find someone to stand in as release manager during that time; I'll post an update here.

**Comment by brentleyjones** [comment] 2021-11-16 18:38
@Wyverald Can we get tags for rc1 and rc2? There are basilisk releases, but no tags to go along with them.

**Comment by Wyverald** [comment] 2021-11-16 18:49
Sorry, do you mean git tags? There doesn't seem to be tags for RCs of previous releases. What do you need tags for?

**Comment by brentleyjones** [comment] 2021-11-16 18:58
I guess I got spoiled by there being igt tags for all of the prerelease builds. If RCs are handled differently, go ahead and ignore me. It's just useful to be able to checkout the exact commit for a build. I had to guess which sha was for rc1.

**Comment by Wyverald** [comment] 2021-11-16 21:08
For posterity, there's actually an easy way to find the commit hash of each RC:

* `rc1` is from the baseline (see top of this thread)
* `rc{N}` where `N>1` is where the branch `release-5.0.0rc{N-1}` is, since the rc1 branch is no longer touched when rc2 comes out, etc.

**Comment by msiebuhr** [comment] 2021-11-17 12:30
As this seem like the right place (but perhaps a bit late) to bring up https://github.com/bazelbuild/continuous-integration/issues/1060 - there hasn't been a docker-based release since 3.5.0 (see https://l.gcr.io/google/bazel for currently released images).

While building a container ourselves is fairly easy, I'd still appreciate having a properly maintained release.

**Comment by Wyverald** [comment] 2021-11-19 12:58
Hi all -- I'll be going on vacation for two weeks (until 5 Dec). In the meantime, Yun (@meteorcloudy) will take over release manager duties; so please send cherrypick pull requests to him.

Thank you for your contributions!

**Comment by obruns** [comment] 2021-11-19 19:23
@meteorcloudy, f5196e2ce4e8e45ca49c271053dad8dd32be5080 (`--experimental_cpp_compile_resource_estimation`; fix for #13988 and #14092) didn't make it into any of the pre-releases. Please cherry-pick.

@wilwell FYI

**Comment by brentleyjones** [comment] 2021-11-19 19:25
@obruns The process has been for contributors to make PRs with the cherry-picks, and tag the reviewer there to get it merged.

**Comment by obruns** [comment] 2021-11-19 19:28
@brentleyjones Thanks. I didn't look at the right thing, anyway (see edited comment).

**Comment by EdSchouten** [comment] 2021-11-26 14:10
https://github.com/bazelbuild/bazel/pull/14168 <- It would be nice if this change could end up in Bazel 5. Would make life a lot easier for folks using Mac M1 hardware.

**Comment by fmeum** [comment] 2021-11-28 09:46
Sorry for being late with this, but https://github.com/bazelbuild/bazel/issues/13978 technically is a regression from 4.2.1 to 5, depending on how stable `bazel coverage` is supposed to be. I proposed a fix at https://github.com/bazelbuild/bazel/pull/13983.

**Comment by meteorcloudy** [comment] 2021-11-29 08:59
@EdSchouten Thanks, I'm importing the change, please send a PR to release-5.0.0rc2 when it's submitted.

@fmeum We'll review the fix ASAP, thanks for pinging again!

**Comment by tjoneslo** [comment] 2021-12-02 13:49
#14365 - I've come across this regression in the RC2 release.

**Comment by BalestraPatrick** [comment] 2021-12-03 23:53
Another regression in Bazel 5 that we hope to get merged and cherry-picked: https://github.com/bazelbuild/bazel/pull/14367

**Comment by brentleyjones** [comment] 2021-12-14 15:49
We are down to 0 known release blockers 😄

**Comment by Wyverald** [comment] 2021-12-14 16:11
RC3 is [out](https://releases.bazel.build/5.0.0/rc3/index.html). Hopefully this is the one :)

**Comment by Wyverald** [comment] 2021-12-20 12:35
Hi all, since we're approaching the end of the year and the holidays are upon us, and we still have a couple of outstanding release blockers in RC3, we've decided to postpone the release of 5.0 to next year. I've updated the release date tentatively to 2022-01-10.

(the previous comment aged rather poorly, alas)

**Comment by Yannic** [comment] 2021-12-24 14:02
Could we get in #14333 and #14455 please once they are merged?

**Comment by fmeum** [comment] 2021-12-24 15:40
@meteorcloudy @Wyverald Should #14447 be cherry-picked to prevent a scenario where some Bazel modules don't work (and possibly can't be made to work) with Bazel 5.0.0?

**Comment by fmeum** [comment] 2021-12-30 10:25
@Wyverald I have found another potential release blocker: #14500.

**Comment by Wyverald** [comment] 2022-01-03 10:46
@Yannic: Those two changes seem small enough that we can cherrypick them.

@fmeum: #14447 is a bit too big to cherrypick IMO. We should look at fixing backwards compatibility with 5.0 some other way (eg. having a branch in the BCR). #14500 should probably be cherrypicked as it's a regression.

**Comment by fmeum** [comment] 2022-01-03 11:22
> @fmeum: #14447 is a bit too big to cherrypick IMO. We should look at fixing backwards compatibility with 5.0 some other way (eg. having a branch in the BCR).

I agree with being careful as not to delay the release further. We should keep in mind though that there might not be usable workarounds for the lack of these select's in macros in all cases, so a BCR branch might not help. Maybe ensuring that this gets into 5.1.0 is better.

**Comment by brentleyjones** [comment] 2022-01-03 13:59
Since 5.0 includes many Apple Silicon related fixes, in particular iOS arm64 simulator support, it would be nice to get https://github.com/bazelbuild/bazel/pull/14439 in as well, which adds watchOS arm64 and tvOS arm64 simulator support.

**Comment by meteorcloudy** [comment] 2022-01-05 09:54
@brentleyjones I prefer not to delay the release of 5.0 by cherry-picking more features (which are not even yet merged), but we can maybe consider it in 5.1.

**Comment by brentleyjones** [comment] 2022-01-05 13:13
Understood.

**Comment by EdSchouten** [comment] 2022-01-05 14:53
https://github.com/bazelbuild/bazel/pull/14471 <- Would this change be eligible for cherry-picking?

**Comment by Wyverald** [comment] 2022-01-05 14:56
In general, if it's not a regression in 5.0 (compared to say 4.2), I'm reluctant to cherrypick it at this stage. It's not immediately clear to me whether #14471 is fixing a regression or an old bug.

**Comment by Wyverald** [comment] 2022-01-19 15:07
Update: The 5.0 release binaries have now been pushed. Documentation generation and the blog post are still in progress.

In the meantime, @vbatts @petemounce @excitoon could you update the relevant packages in Chocolatey, Scoop, etc.?

**Comment by petemounce** [comment] 2022-01-19 15:50
Pushed!

**Comment by brentleyjones** [comment] 2022-01-19 17:23
What the process for 5.0.1 or 5.1? There were some changes that didn't get cherry-picked into 5.0 that would be nice to get into a branch sooner rather than later (as to not forget about them).

**Comment by Wyverald** [comment] 2022-01-19 18:05
We're probably going to create a new milestone for 5.0.1, and one for 5.1 as well. For now, please ping me in those issues and I'll add them to the appropriate lists later.

**Closed** 2022-01-19 21:42 UTC
Labels: P1, type: process, release, team-XProduct

**Comment by blorente** [comment] 2022-02-03 16:09
@Wyverald I've filed an issue for one such change (https://github.com/bazelbuild/bazel/issues/14701), please let me know if this was not the appropriate way.

**Comment by vbatts** [comment] 2022-02-14 20:25
sorry for the delay.
I've kicked off builds for fedora and cento.
This marks as package name as "bazel5"
https://copr.fedorainfracloud.org/coprs/build/3493215

**Comment by vbatts** [comment] 2022-02-15 12:54
The build failed on a number of the platforms

* fedora 36 (all arches)
* fedora rawhide (all arches)

```shell
ERROR: /builddir/build/BUILD/bazel-5.0.0/src/main/cpp/BUILD:228:11: Compiling src/main/cpp/rc_file.cc failed: (Exit 1): gcc failed: error executing command 
   (cd /var/tmp/bazel_IjI0AnKi/out/execroot/io_bazel && \
   exec env - \
     PATH=/builddir/build/BUILD/bazel-5.0.0/bin-hack:/builddir/.local/bin:/builddir/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/sbin \
     PWD=/proc/self/cwd \
   /usr/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG -ffunction-sections -fdata-sections '-std=c++0x' -MD -MF bazel-out/aarch64-opt/bin/src/main/cpp/_objs/rc_file/rc_file.d '-frandom-seed=bazel-out/aarch64-opt/bin/src/main/cpp/_objs/rc_file/rc_file.o' -DBLAZE_OPENSOURCE -iquote . -iquote bazel-out/aarch64-opt/bin -include/usr/include/c++/11/limits -fno-canonical-system-headers -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' -c src/main/cpp/rc_file.cc -o bazel-out/aarch64-opt/bin/src/main/cpp/_objs/rc_file/rc_file.o)
# Configuration: 748b5b758b09e1994494c90a8cb080e0306949cc69b7accf3e2939eb3d3a3e35
# Execution platform: //:default_host_platform
<command-line>: fatal error: /usr/include/c++/11/limits: No such file or directory
compilation terminated.
[459 / 1,107] 3 actions running
     Compiling src/compiler/csharp_generator.cc [for host]; 4s local
     Compiling src/compiler/cpp_generator.cc [for host]; 4s local
     Compiling src/compiler/ruby_generator.cc [for host]; 0s local
```
https://download.copr.fedorainfracloud.org/results/vbatts/bazel/fedora-36-aarch64/03493215-bazel5/build.log.gz

* epel 7 (all arches)

```shell
ERROR: /var/tmp/bazel_ypZaJyXq/out/external/com_github_grpc_grpc/BUILD:1254:16: Compiling src/core/lib/iomgr/resolve_address_custom.cc failed: (Exit 1): gcc failed: error executing command 
   (cd /var/tmp/bazel_ypZaJyXq/out/execroot/io_bazel && \
   exec env - \
     PATH=/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/sbin:/builddir/.local/bin:/builddir/bin \
     PWD=/proc/self/cwd \
   /usr/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG -ffunction-sections -fdata-sections '-std=c++0x' -MD -MF bazel-out/ppc-opt/bin/external/com_github_grpc_grpc/_objs/grpc_base_c/resolve_address_custom.d '-frandom-seed=bazel-out/ppc-opt/bin/external/com_github_grpc_grpc/_objs/grpc_base_c/resolve_address_custom.o' -iquote external/com_github_grpc_grpc -iquote bazel-out/ppc-opt/bin/external/com_github_grpc_grpc -iquote external/upb -iquote bazel-out/ppc-opt/bin/external/upb -iquote external/com_google_protobuf -iquote bazel-out/ppc-opt/bin/external/com_google_protobuf -iquote external/com_google_absl -iquote bazel-out/ppc-opt/bin/external/com_google_absl -iquote . -iquote bazel-out/ppc-opt/bin -isystem external/com_github_grpc_grpc/include -isystem bazel-out/ppc-opt/bin/external/com_github_grpc_grpc/include -isystem external/com_github_grpc_grpc/src/core/ext/upb-generated -isystem bazel-out/ppc-opt/bin/external/com_github_grpc_grpc/src/core/ext/upb-generated -isystem external/com_github_grpc_grpc/src/core/ext/upbdefs-generated -isystem bazel-out/ppc-opt/bin/external/com_github_grpc_grpc/src/core/ext/upbdefs-generated -isystem third_party/zlib -isystem bazel-out/ppc-opt/bin/third_party/zlib -fno-canonical-system-headers -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' -c external/com_github_grpc_grpc/src/core/lib/iomgr/resolve_address_custom.cc -o bazel-out/ppc-opt/bin/external/com_github_grpc_grpc/_objs/grpc_base_c/resolve_address_custom.o)
# Configuration: cb266f3995a6d05424d5d5f9027f493b1e9335e0a601bb71bcd48f86902f55b7
# Execution platform: //:default_host_platform
In file included from external/com_github_grpc_grpc/src/core/lib/iomgr/closure.h:33:0,
                  from external/com_github_grpc_grpc/src/core/lib/iomgr/exec_ctx.h:35,
                  from external/com_github_grpc_grpc/src/core/lib/iomgr/pollset.h:27,
                  from external/com_github_grpc_grpc/src/core/lib/iomgr/pollset_set.h:24,
                  from external/com_github_grpc_grpc/src/core/lib/iomgr/resolve_address.h:36,
                  from external/com_github_grpc_grpc/src/core/lib/iomgr/resolve_address_custom.h:25,
                  from external/com_github_grpc_grpc/src/core/lib/iomgr/resolve_address_custom.cc:21:
external/com_github_grpc_grpc/src/core/lib/iomgr/resolve_address_custom.cc: In function 'grpc_error* try_split_host_port(const char*, const char*, std::string*, std::string*)':
external/com_github_grpc_grpc/src/core/lib/iomgr/resolve_address_custom.cc:97:60: error: no matching function for call to 'StrFormat(const char [28], const char*&)'
          absl::StrFormat("unparseable host:port: '%s'", name));
```
https://download.copr.fedorainfracloud.org/results/vbatts/bazel/epel-7-ppc64le/03493215-bazel5/build.log.gz

**Comment by Wyverald** [comment] 2022-02-15 13:47
Thanks, Vincent! Let's track this build failure in https://github.com/bazelbuild/bazel/issues/14819
