### ISSUE TITLE
shell toolchain, design: including common bintools

### ISSUE THREAD

**Issue by laszlocsomor** [bazelbuild/bazel#5265] opened 2018-05-25 09:14 UTC
### Description of the problem / feature request:

Design a mechanism to express that a rule executing a shell command depends on certain command line tools.

### Feature requests: what underlying problem are you trying to solve with this feature?

Not every machine has Bash installed, and those that do don't always install Bash at the same location, or have another shell interpreter installed. To accommodate all scenarios, I designed how to turn Bash, or broadly speaking, the Shell, into a toolchain. The efforts is tracked as https://github.com/bazelbuild/bazel/issues/4319.

However what Bazel treats as "the shell" is more than just the shell interpreter. Bazel assumes that not only Bash is the shell and it's installed at a fixed location, but also that common GNU binutils and other common programs such as "zip" or "grep" are also installed and are on the PATH.

Rules that execute shell commands also expect these tools to exist and be on the PATH. Bazel currently has no way to express that such rules depend on these tools.

**Comment by jin** [comment] 2019-02-19 18:28
@laszlocsomor could you add a priority to this issue please?

**Comment by laszlocsomor** [comment] 2019-02-20 10:51
Setting priority to P3 for now -- we will probably not see much advancement with this issue before Bazel 1.0, and while it is an important issue, it's not as critical as something like https://github.com/bazelbuild/bazel/issues/6351 would be.

**Comment by robinp** [comment] 2019-02-22 09:23
FYI if anyone is actively troubled by this, recently I successfully use [rules_nixpkgs](https://github.com/tweag/rules_nixpkgs) to source pinned version of binaries from `nixpkgs` (a reproducible set of linux/mac packages). No more depending on binaries being installed and put on `PATH` upfront.

See https://github.com/TreeTide/kythe/compare/master...TreeTide:nix#diff-9abc402c282da05d9ea4c75991a17bf4R31 for an example of depending on `bison` from a nixpkgs import. See https://github.com/TreeTide/kythe/compare/master...TreeTide:nix#diff-09498dbadf45966909850dc8a47ebb13R27 for how can you add `rules_nixpkgs` to your `WORKSPACE`.

**Comment by laszlocsomor** [comment] 2019-03-12 15:15
FYI @asuffield

**Comment by aherrmann** [comment] 2020-11-06 09:24
> However what Bazel treats as "the shell" is more than just the shell interpreter. Bazel assumes that not only Bash is the shell and it's installed at a fixed location, but also that common GNU binutils and other common programs such as "zip" or "grep" are also installed and are on the PATH.
> 
> Rules that execute shell commands also expect these tools to exist and be on the PATH. Bazel currently has no way to express that such rules depend on these tools.

[`rules_sh`](https://github.com/tweag/rules_sh) implements such a toolchain for Bazel, [usage described in the README](https://github.com/tweag/rules_sh#usage).

**Comment by meteorcloudy** [comment] 2021-12-23 15:14
Looks like this issue is resolved by rules_sh and the modern toolchain resolution mechanism.

**Closed by meteorcloudy** 2021-12-23 15:14 UTC
Labels: type: feature request, P3, type: process, category: misc > misc, area-Windows, team-XProduct

**Comment by fmeum** [comment] 2023-01-12 23:05
Doesn't rules_sh just define additional make variables that any `genrule`-like rule could use without supporting rules_sh specifically? If that's the case, it may be more sufficient to get the building blocks for doing that in a convenient location (e.g. skylib).

**Comment by fmeum** [comment] 2023-01-13 08:21
> Yeah but that still requires the whole ecosystem to rewrite their genrules to use those make variables.

The effort wouldn't be specific to the make variables offered by rules_sh, but should apply to *any* make variable defined by any toolchain. Even if Bazel itself provided a shell toolchain, I think that third-party genrules would still need to support toolchain and the make variables to expose to make use of it.

@alexeagle Do the rules_js genrules support toolchains and make variables? Maybe bazel-lib already has helpers for doing that properly and evaluating the make variables?
