### ISSUE TITLE
Release binaries for Windows on ARM

### ISSUE THREAD

**Issue by rubin55** [bazelbuild/bazel#13183] opened 2021-03-09 09:03 UTC
### Description of the problem / feature request:

Lately there's been a lot of traction on ARM based devices, in particular Apple's M1 and Microsoft's Surface Pro X devices. It would be great if Bazel could, next to the current x64 Windows binaries, provide Windows on ARM64 binaries. 

### Feature requests: what underlying problem are you trying to solve with this feature?

Bazel would be usable on a wider range of devices. Bazel would future-proof itself by being able to run natively on Windows on ARM, in addition to Darwin on ARM and Linux on ARM.

###  Have you found anything relevant by searching the web?

Yes, I found this commit in Bazel itself, supporting the building of Windows on ARM binaries (presumably using MSVC): https://github.com/bazelbuild/bazel/commit/1f77972536c69c27ce3076de9f634e1a02a14a5e#diff-89a237784c63ef1b97979702430787d86126537d6d0c50347c5101f74bd00b31

**Comment by sventiffe** [comment] 2021-04-28 09:22
Yun, is this something we have capacity for? How much effort would it be?

**Comment by meteorcloudy** [comment] 2021-04-28 10:32
I think this is definitely doable, but the problem is that we don't have ARM Windows machines to develop locally or test on CI.
We definitely welcome contributions from the community!

**Comment by meteorcloudy** [comment] 2023-04-06 10:58
Fixed in https://github.com/bazelbuild/continuous-integration/pull/1339

**Closed by meteorcloudy** 2023-04-06 10:58 UTC
Labels: type: feature request, P2, team-OSS
