### ISSUE TITLE
--ios_multi_cpus doesn't default to Xcode Standard Architectures

### ISSUE THREAD

**Issue by cpsauer** [bazelbuild/bazel#10733] opened 2020-02-08 07:33 UTC
Hi wonderful Bazel folks,

I noticed that the --ios_multi_cpus flag defaults to x86_64 (i.e. cpu:ios_x86_64). This is unexpected, because the Standard Architectures used for iOS compilation in Xcode haven't included the Intel simulator architectures (x86_64 and i386) in quite a while.

The current iOS default Standard Architectures are armv7,arm64, and that's what Xcode defaults to. Would you be willing to change Bazel so it defaults match Xcode's, i.e., --ios_multi_cpus defaults to armv7,arm64? Or even better, make it read and track Apple's Standard Architectures? 

I know I can fix this in my repo with a .bazelrc (and have done so), but I thought I should file an issue because it might confuse new users. I haven't checked, but I'd guess the defaults for the other apple platforms might also surprise new users.

Thanks,
Chris

**Comment by jmmv** [comment] 2020-02-13 16:12
I think this makes sense, but I'm unaware of the implications. @DavidGoldman?

**Comment by keith** [comment] 2020-02-13 16:19
This would definitely be a breaking change for folks that don't pass the arch right now for simulator builds (like us). I personally think it would be fine to switch, but don't see much value in it. Projects will always have to pass this at some point. Either for the difference between simulator and device builds, or because they don't support iOS 10 and therefore don't need the 32 bit architectures. So I think no matter what this defaults to it will always be wrong for lots of folks.

**Comment by cpsauer** [comment] 2020-02-13 20:29
Hmm... I think the goal for usability should be that people don't have to think about architecture flags for common use cases, right? And that includes the simulator use case @keith pointed out.

Xcode does nail this, and I do still think most Apple devs switching would be surprised by the Bazel defaults. 

So maybe the best fix would be piggybacking off Xcode's Standard Architectures for the minimum_os_version given in the binary rule (e.g. dropping 32bit if >= iOS 11 as Keith points out).  But perhaps the simplest fix would be to just cover all the bases by making the default `armv7,arm64,x86,x86_64`. That'd produce something that would run on all devices by default--including the simulator and armv7s devices. People wouldn't be surprised, everything would work out of the box, and folks could always trim the architecture list down if they knew more about the devices they were deploying on.

**Comment by keith** [comment] 2020-02-13 21:48
I think then the unexpected thing then would be that bazel would by default build your code 4 times, so really you'd want a combo of that and ONLY_ACTIVE_ARCH (in Xcode parlance)

**Comment by DavidGoldman** [comment] 2020-09-23 21:12
I can see the argument for making `arm64` the default, but I think most developers build/run on the simulator by default so this would be a breaking change for them. I don't think we should default to  `armv7,arm64,i386,x86_64` since that will build your code 4 times, which is expensive for larger apps. The best option here is a bazelrc tailored to your use case.

**Comment by cpsauer** [comment] 2020-09-23 21:34
Happy to fold if not useful to others :) .bazelrc'd for myself

**Comment by cpsauer** [comment] 2020-09-23 22:02
Happy to fold if not useful to others :) Not blocking me--just filed bc I thought others might want the same thing. Sounds like not--at least in this form.

_Before I close it down, though, a few related things that might be useful:_

I'm realizing that there's also a new development that might change or affect things here: 
Apple Silicon will switch simulator builds over to arm64 on some machines, right?

A possible fix that would work for Apple Silicon going forward would be having dbg/fastbuilds target the current machine's architecture (and simulator) by default, with opt/release builds possibly targeting device architectures instead. Maybe that's not worth the complexity, but it does seem like there's brokenness coming down the line here due to the Apple Silicon/Intel split.

Separately, it seems like the root issue here is not having knowledge of where the binary is going to be deployed. [That knowledge is really what  Xcode is using to determine which architectures to build, I'm realizing.] My understanding is that bazel doesn't currently have rules to deploy to a device, the simulator, or release to App Store Connect. Is that right? Not something I need right now, but it feels like transitions from deployment rules could be a good conceptual solution.

**Comment by keith** [comment] 2020-09-23 22:14
>  My understanding is that bazel doesn't currently have rules to deploy to a device, the simulator, or release to App Store Connect. Is that right? Not something I need right now, but it feels like transitions from deployment rules could be a good conceptual solution.

I'm not really sure what you mean by having rules for these? `bazel run //:someapp` does work for the simulator. Most workflows for building to device include some sort of Xcode integration such as [tulsi](https://github.com/bazelbuild/tulsi) or [xchammer](https://github.com/pinterest/xchammer) and uploading to the app store is handled outside of bazel, potentially with actool which ships with Xcode or fastlane. For the latter it's up to you to determine what architectures and other flags you want to build your `.ipa` with.

**Comment by cpsauer** [comment] 2020-09-23 22:53
Ah! Okay. From the [iOS tutorial](https://docs.bazel.build/versions/master/tutorial/ios-app.html#build-the-app-for-the-simulator), I'd assumed run didn't work and deploying with pure bazel (i.e. without tulsi) was a goal. 

To explain where I'm coming from: We're moving over from buck, where iOS build and deploy is built in as a command, similar to what bazel does for Android. We're generally quite happy with the switch, but the iOS deployment support is something we miss. 

I had been imagining bazel could potentially do something similar (or better!) using wrapper rules that let you bazel build/run for device, for the app store, etc. and have everything configured correctly, much as ios_application or ios_framework transition/configure their dependencies.

@keith, thanks for all your good thinking and patience. You'd recommend we just switch over to xchammer (or tulsi) and wrap bazel back up in Xcode? Making sure everything stays sync makes me a *little* nervous, but I'll start reading up.

Can I also ask what you think about the Apple Silicon issue down the line?

**Comment by keith** [comment] 2020-09-24 16:35
> deploying with pure bazel 

FWIW you can do a `bazel build` for device, and then run it by installing via Xcode's organizer. So if your workflow prefers that it will work.

I definitely get the value in the mobile_install setup, there was a stab at this here: https://github.com/bazelbuild/rules_apple/pull/364 which you could probably expand on if you were interested.

> have everything configured correctly

I think the problem is that this glosses over massive amounts of company-specific complexity. There is no "one true way" to build and deploy an app.

> you'd recommend we just switch over to xchammer (or tulsi) and wrap bazel back up in Xcode

I think a Xcode based workflow is what existing iOS engineers will be most familiar with, so it's worth trying to make that work for your case. If you're coming from a different background maybe this doesn't matter as much and you could productionize some of the other workflows. There is a lot of complexity in integrating with Xcode so if you could avoid it that would be great 🙃 

> Can I also ask what you think about the Apple Silicon issue down the line?

I agree that for the simulator we will likely need to default to the host's architecture in the future.

**Comment by susinmotion** [comment] 2020-10-01 20:43
Thank @keith for all of the info! I am going to close this but feel free to comment with further discussion.

**Closed by susinmotion** 2020-10-01 20:43 UTC
Labels: P2, team-Apple, type: bug
