### ISSUE TITLE
Release - patch release 0.14.1

### ISSUE THREAD

**Issue by dslomov** [bazelbuild/bazel#5340] opened 2018-06-07 10:02 UTC
A patch release of 0.14 (#5056) with a fix for #5336

**Comment by dslomov** [comment] 2018-06-07 10:10
scripts/release/release.sh create 0.14.1 10a4de9  4b80f2455e7e49a95f3a4c9102a67a57dad52207

**Comment by dslomov** [comment] 2018-06-07 10:39
I will cherry-pick a fix for #5308 into this patch release.

**Comment by meteorcloudy** [comment] 2018-06-07 12:04
@lfpino

**Comment by dslomov** [comment] 2018-06-07 12:20
rc2: `scripts/release/release.sh create 0.14.1 10a4de9  4b80f2455e7e49a95f3a4c9102a67a57dad52207 6b1635279e8b33dc1ac505ac81825e38f8797a14`

**Comment by dslomov** [comment] 2018-06-07 12:43
rc2 published, downstream tests started: https://buildkite.com/bazel/bazel-with-downstream-projects-bazel/builds/293

**Comment by dslomov** [comment] 2018-06-07 17:12
Some stuff in downstream projects fails, but they also fail in trunk pipelines in the same way.
WDYT @aehlig (current Bazel Sheriff)

**Comment by jmillikin-stripe** [comment] 2018-06-07 21:00
I've got another cherrypick request: 4ec0a7524913ab2c4641368e3f8c09b347351a08 to fix a regression in the Skylark implementation of `new_git_repository` (https://github.com/bazelbuild/bazel/pull/5146).

**Comment by dslomov** [comment] 2018-06-08 06:05
4ec0a75  does not fix a regression - it is a functionality change, or am I missing something?

**Comment by dslomov** [comment] 2018-06-08 13:10
Patch release is out: https://github.com/bazelbuild/bazel/releases/tag/0.14.1

**Comment by dslomov** [comment] 2018-06-08 13:11
Ping @petemounce for Chocolatey
Ping @ilovezfs for Homebrew

**Comment by ilovezfs** [comment] 2018-06-08 14:05
I've shipped 0.14.1 in Homebrew: https://github.com/Homebrew/homebrew-core/pull/28804

**Comment by jmillikin-stripe** [comment] 2018-06-08 16:40
> 4ec0a75 does not fix a regression - it is a functionality change, or am I missing something?

Long ago (June 2017) I noticed that `new_git_repository` was broken on MacOS for some repos (https://github.com/bazelbuild/bazel/issues/3127), and got a fix merged (https://github.com/bazelbuild/bazel/pull/3142).

It was broken again (regressed) by some refactoring in February 2018 (https://github.com/bazelbuild/bazel/commit/a22a287f53598d2a2a7eb59b72fe4e98a02435ce), but  I didn't notice because the repo we needed the fix for had been pinned to an older Bazel version (0.11). We just tried to update it to 0.14.0 and it failed due to a name conflict between `BUILD` and `build/`, since the MacOS filesystem is case-insensitive.

**Comment by dslomov** [comment] 2018-06-08 20:32
I see. I don't think this meets the bar for patch release for 0.14. Let's cherry pick it into 0.15 (#5057).
I can't help noticing that https://github.com/bazelbuild/bazel/pull/3142 has no tests, hence the bug.

**Comment by jmillikin-stripe** [comment] 2018-06-08 20:43
Yes, it's definitely my fault for not having tests there. I just hadn't thought there would be so much development velocity in that part of the code.

0.15 should be fine in terms of timeline, it looks like it's already in the RC process. Thanks for the cherrypick.

**Comment by petemounce** [comment] 2018-06-25 00:08
0.14.1 out on chocolatey.

**Comment by mhlopko** [comment] 2018-06-25 13:58
Can this issue be closed now?

**Comment by meteorcloudy** [comment] 2018-06-25 14:04
Yes.

**Closed by meteorcloudy** 2018-06-25 14:04 UTC
Labels: release
