### ISSUE TITLE
Useless execution info printed

### ISSUE THREAD

**Issue by AustinSchuh** [bazelbuild/bazel#6347] opened 2018-10-10 16:11 UTC
```
INFO: Elapsed time: 2530.925s, Critical Path: 2459.40s, Remote (0.00% of the time): [queue: 0.00%, setup: 0.00%, process: 0.00%]
INFO: 24481 processes: 20835 remote cache hit, 14 linux-sandbox, 6 local, 3626 remote.
```

The build succeeded, but the 0% stats aren't useful.

**Comment by benjaminp** [comment] 2018-10-11 14:36
#6208

**Comment by philwo** [comment] 2018-10-17 12:11
Duplicate of https://github.com/bazelbuild/bazel/issues/6208

**Closed by philwo** 2018-10-17 12:11 UTC
Labels: P2, category: remote execution / caching, team-Execution, type: bug
