### ISSUE TITLE
impossible to add tensoflow as dependency to project via git_repository/local_repository rules

### ISSUE THREAD

**Issue by Zaspire** [bazelbuild/bazel#598] opened 2015-11-13 02:31 UTC
error message for (tensor flow included via local_repository)
```
ERROR: /private/var/tmp/_bazel_user/6ec9f062c664e765880a72fac3078fb9/external/tensorflow-local/tensorflow/core/BUILD:197:1:
no such package 'tensorflow/core/platform/default/build_config': 
BUILD file not found on package path and referenced by '@tensorflow-local//tensorflow/core:tensorflow_opensource'.
ERROR: Loading failed; build aborted.

```

**Comment by damienmg** [comment] 2015-11-13 09:24
Ok @jhfield is working on fixing that. This is because remote repository cannot reference correctly Skylark files. Until this is fixed, you  need to copy the .bzl of tensorflow under the same path in your main repository

**Comment by kchodorow** [comment] 2015-11-13 14:54
Duplicate of #429.

**Closed** 2016-01-06 17:41 UTC
Labels: bug, duplicate, external repositories, P1

**Comment by Zaspire** [comment] 2016-01-07 04:58
I still can reproduce issue with latest bazel & latest tenserflow

**Comment by kchodorow** [comment] 2016-01-07 15:31
I'd imagine that tensorflow's load statements are using the old-style paths, not labels, and needs to be updated.  Perhaps file a ticket with tensorflow?
