### ISSUE TITLE
Bazel can build different tools on different execution platforms in the same build

### ISSUE THREAD

**Issue by gregestren** [bazelbuild/bazel#11748] opened 2020-07-10 22:10 UTC
For example, building on a Mac where some tools execute on the Mac and others execute on a remote Linux machine.

This tracks a [Blaze configurability roadmap](https://bazel.build/roadmaps/configuration.html) effort.

**Comment by cpsauer** [comment] 2020-09-16 05:08
Came across this looking to build and bundle together binaries, one for each platform, some of which would need to get built remotely. This would be awesome for that!

Could I ask what use case originally inspired this feature request? 

Also, @gregestren: I was just building on some of your great examples around transitions. Thank you for those!

**Comment by katre** [comment] 2020-09-16 12:31
We have mixed-backend builds we'd like to do, mostly around developers who are working on Mac laptops but want to use the Linux remote build backends, so we'd like to get that moving. There's a lot of cruft to clean up first, though, so I'm not sure when we'll be moving forward.

Mixed binaries like you want can be done with transitions, however, so I am glad you found the examples for those helpful.

**Comment by ulfjack** [comment] 2020-09-16 15:05
We have successfully run some builds where Bazel runs on a Mac and the build runs on Linux, although that required a patch to the bazel-toolchains repository which currently looks at the local host to determine the remote host (which is obviously incorrect in this case).

**Comment by cpsauer** [comment] 2020-09-17 22:04
Thanks, both of you, for replying. 

@katre, just to confirm, I *can't* currently use transitions to have parts of the graph build remotely, right? That's what it seemed like from my experience playing around with transitions, and this seemed like the issue that would lead to the change from reading the design doc ([link if anyone else is looking](https://docs.google.com/document/d/1U9HzdDmtRnm244CaRM6JV-q2408mbNODAMewcGjnnbM/edit#heading=h.y890cog3hszc)). But your comment seemed to say otherwise? Just to make it concrete: imagine building on a Mac, where you can locally (cross)compile the binary for macOS, iOS, Android (using transitions), but want to compile for Windows, Linux remotely. Or equivalently compiling from Linux, able to build for Linux, Android locally, but needing to compile for iOS, macOS, Windows remotely.

**Comment by ulfjack** [comment] 2020-09-18 09:31
@cpsauer, even if you could, the code still has other problems. In particular, it looks at the OS that Bazel runs on to select things like path style (windows with backslashes vs. linux/mac with forward slashes). Right now, even running Windows actions remotely from a Linux/Mac machine (and vice versa) is not working.

**Comment by katre** [comment] 2020-09-18 11:40
Sorry, I meant that you can use transitions to build the bundle of libraries for different platforms, _if_ they can all be built on the same platform in individual Bazel invocations. The updates to execution strategy that would be needed for mixed local/remote builds is still in the planning phase.

**Comment by cpsauer** [comment] 2020-09-22 02:50
Thanks all. Remote builds and tests that trancend platforms... what an awesome goal.

**Comment by katre** [comment] 2020-12-11 18:15
Closing this as a dupe of #11432, follow that as the official tracking issue for this effort.

**Closed by katre** 2020-12-11 18:15 UTC
Labels: P1, team-Configurability, type: feature request
