### ISSUE TITLE
compile.sh overwrites scrollback in xfce4-terminal

### ISSUE THREAD

**Issue by bsilver8192** [bazelbuild/bazel#951] opened 2016-02-21 05:36 UTC
The status lines from `./compile.sh test` overwrite previously printed output in my terminal when I'm using xfce4-terminal. I haven't seen this issue when running Bazel directly, with `./compile.sh test path/to/bazel`, or xterm. I also see the bad behavior using the Linux virtual console (ctrl+alt+f2 etc) and with `./compile.sh compile`.

For example, the output starts out like this:
```
brian[1362] aim ((da98130...) *) ~/bazel
$ ./compile.sh test
INFO: You can skip this first step by providing a path to the bazel binary as second argument:
INFO:    ./compile.sh test /path/to/bazel
🍃  Building Bazel from scratch......
INFO: Loading package: @//src/main/java/com/google/devtools/build/lib/actions
```
At a later point, it looks like this though:
```
brian[1362] aim ((da98130...) *) ~/bazel
$ ./compile.sh test
INFO: From Building src/tools/android/java/com/google/devtools/build/android/ziputils/libziputils_lib.jar (12 source files):
Note: Some input files use unchecked or unsafe operations.
INFO: From Building src/tools/android/java/com/google/devtools/build/android/libandroid_builder_lib.jar (16 source files):
```
Notice how the `INFO: You can skip this first step by providing a path to the bazel binary as second argument:` and following lines are no longer visible. Sometimes it will proceed to overwrite the `$ ./compile.sh test` and even output from previous commands.

**Comment by philwo** [comment] 2016-02-26 09:41
Assigning to our character encoding & eANSI specialist @aehlig to get an idea of what's happening here.

**Comment by aehlig** [comment] 2016-02-26 10:09
On Fri, Feb 26, 2016 at 01:41:37AM -0800, Philipp Wollermann wrote:
> Assigning to our character encoding & eANSI specialist @aehlig to get an idea of what's happening here.

For the not-ready-yet experimental UI (which suffers the same problem)
I've just sent a patch series for review

https://bazel-review.googlesource.com/#/c/3023
https://bazel-review.googlesource.com/#/c/3024

which solves a similar overriding-the-scrollback buffer problem (I'll
still have to see if your problem has the same root cause).

If that gets reviewed positively, I plan to write a patch seris that applies
that same fix also for the main UI.

-- 
Klaus Aehlig
Google Germany GmbH, Erika-Mann-Str. 33, 80636 Muenchen
Registergericht und -nummer: Hamburg, HRB 86891
Sitz der Gesellschaft: Hamburg
Geschaeftsfuehrer: Matthew Scott Sucherman, Paul Terence Manicle

**Comment by aehlig** [comment] 2016-02-26 13:29
OK, so if the problem is the one I believe it is, it should be
fixed with branch 'fix-line-eating' in my personal github repo,
see https://github.com/aehlig/bazel/tree/fix-line-eating

Can you please check if this fixes your problem? And can you please
also check if these changes introduce any regressions?

Thanks,
Klaus

-- 
Klaus Aehlig
Google Germany GmbH, Erika-Mann-Str. 33, 80636 Muenchen
Registergericht und -nummer: Hamburg, HRB 86891
Sitz der Gesellschaft: Hamburg
Geschaeftsfuehrer: Matthew Scott Sucherman, Paul Terence Manicle

**Comment by bsilver8192** [comment] 2016-02-26 20:03
Your branch does look like it fixes this for the main UI. I'm not 100% certain because I never saw the bug completely reliably, but the fix makes sense. With the fix, it does indeed keep all the lines shorter, vs before it was wrapping at the boundary of my ~215 column wide terminal window.

Also, I think I found the reason only the boostrap does this: the `--terminal_columns=97` in `scripts/bootstrap/compile.sh`. Is there some reason the width has to be set manually there, and any idea where 97 comes from?

Experimental UI with your branch looks fine too.

Thanks!

**Comment by damienmg** [comment] 2016-02-26 20:05
It's coming from my console, I was too lazy to do better. I will gladly
accept any patch for fixing that :)

**Comment by aehlig** [comment] 2016-03-01 09:48
> Your branch does look like it fixes this for the main UI. [...]

Good to hear that the fix works.

I submitted the patch series for review now.

https://bazel-review.googlesource.com/3040
https://bazel-review.googlesource.com/3041

-- 
Klaus Aehlig
Google Germany GmbH, Erika-Mann-Str. 33, 80636 Muenchen
Registergericht und -nummer: Hamburg, HRB 86891
Sitz der Gesellschaft: Hamburg
Geschaeftsfuehrer: Matthew Scott Sucherman, Paul Terence Manicle

**Comment by aehlig** [comment] 2016-03-04 07:25
These patches have been pushed as aada027aa2e21881190500ad747b4b41ab14a33e and a49f02536ef62ddf6ef5a17b0f7c1a35aaf81098. I believe the issue is fixed now. Please let me know if the issue persists/reappears.

**Closed** 2016-03-04 07:26 UTC
Labels: Bug, P2
