### ISSUE TITLE
Bazel 6 Remote JDK Toolchains Incorrect Configuration

### ISSUE THREAD

**Issue by jlaxson** [bazelbuild/bazel#17085] opened 2022-12-29 06:21 UTC
### Description of the bug:

Upgrading to Bazel 6.0.0, I get some toolchain resolution and build failures around java_library/java_binary rules.  My environment is cross-compile heavy and has remote executors on a number of platforms (linux, darwin both x86 and arm64, windows) and bazel itself is invoked on any of those platforms building for any other.

I get issues when, due to peculiarities in execution platform selection order, an exec platform is chosen for java that is distinct from the target platform.  For instance, target platform is macos_arm64, but the exec platform is @local_config_platform//:host on linux, or a remote linux platform.  For instance, here is toolchain_resolution_debug from a cross compile:

```
INFO: ToolchainResolution:   Type @bazel_tools//tools/jdk:runtime_toolchain_type: target platform //:macos_arm: execution //:macos_arm: Selected toolchain @remotejdk11_macos_aarch64//:jdk
INFO: ToolchainResolution:   Type @bazel_tools//tools/jdk:runtime_toolchain_type: target platform //:macos_arm: execution //:macos: Selected toolchain @remotejdk11_macos_aarch64//:jdk
INFO: ToolchainResolution:   Type @bazel_tools//tools/jdk:runtime_toolchain_type: target platform //:macos_arm: execution //:linux: Selected toolchain @remotejdk11_macos_aarch64//:jdk
INFO: ToolchainResolution:   Type @bazel_tools//tools/jdk:runtime_toolchain_type: target platform //:macos_arm: execution //test:downloader: Selected toolchain @remotejdk11_macos_aarch64//:jdk
INFO: ToolchainResolution:   Type @bazel_tools//tools/jdk:runtime_toolchain_type: target platform //:macos_arm: execution @local_config_platform//:host: Selected toolchain @remotejdk11_macos_aarch64//:jdk
```

A number of these selections are wrong: remotejdk11_macos_aarch64 will not run on the host platform (it is linux), nor will it run on the //:linux remote execution platform.  Nor will it run on the //test:downloader platform which specifies no OS constraints to match at all.  If bazel happens to choose any but the first configuration with identical target and exec platform, it will try to execute a darwin arm64 binary on linux with predictable fireworks.  In the ultimate case where the target and set of exec platforms are distinct, this is guaranteed to fail.  

This also fails when targeting a platform that has no JDK such as Android.  In Bazel 5.1 it worked just fine to have a java_library depended on by an android_library, now toolchain resolution just fails if you set --platforms to one with @platforms//os:android because there is no openjdk for android (and if there were, my remote exec environment has no android runners)

It seems that d5559c16ac008b86345fbbade5d600181a2fce6f changed the definition of the java toolchains to specify only target_compatible_with, not exec_compatible_with, even though the jdk itself is platform-specific.  I'm not sure I understand the benefits of that change, but at a minimum it seems like exec_compatible_with should _also_ be specified for those toolchains.

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

See https://github.com/jlaxson/bazel_java_toolchain_bug for the simple reduction involving android platforms.

### Which operating system are you running Bazel on?

Macos, linux

### What is the output of `bazel info release`?

release 6.0.0

**Comment by fmeum** [comment] 2023-03-03 11:51
Definitely not an expert on this, so take any of the following with a grain of salt. 

Note that there are two relevant Java toolchain types: the one for the JDK used for compilation (@bazel_tools//tools/jdk:toolchain_type) and the one for the JDK/JRE used as the runtime for executing a java_binary (@bazel_tools//tools/jdk:runtime_toolchain_type).

The toolchain_type JDK is used for compilation and should thus be selected based on the exec platform. Since Java compilation outputs are platform-independent, the target platform doesn't matter here.

The runtime_toolchain_type JDK is added to the runfiles of a java_binary and is executed when you do bazel run, so this actually needs to be selected based on the target platform. If you execute a Java tool during the build, there will be a transition to the exec configuration at some point, which will make the exec platform the target platform and thus again select the correct runtime.

Based on my understanding of the points above, java_library should not have a toolchain dependency on @bazel_tools//tools/jdk:runtime_toolchain_type, only on @bazel_tools//tools/jdk:toolchain_type. That would allow you to have a java_library in the deps of an android_* target even though there is no runtime for Android. I checked the Starlark implementation of the java_library rules and it should allow this, but as far as I know the native implementation is enabled by default and I have no idea how it handles toolchains.

It's worrying that your reproducer seems to indicate that this doesn't work, which looks like it could indeed be a regression in Bazel 6.

@cushon Could you take a look?

Regarding the other toolchain resolution failures you are seeing: Is it possible that some custom rules or genrules you are using aren't correctly transitioning to the exec configuration? Do you also have a reproducer for these non-Android issues?

**Comment by fmeum** [comment] 2023-03-03 11:53
Just noticed that the reproducer you linked has an empty main branch, but the content lives on the master branch.

**Comment by jlaxson** [comment] 2023-03-03 18:00
Thanks @fmeum for the attention.  I fixed up the reproducer branch and split it into two issues, one showing the problem with simply a java_library and a bespoke target platform.

I think I loosely understand the goal, but some issues I still see:
* The reproducer breaks at java_library, not even java_binary needing to build out its runfiles tree
* Even if only java_binary should have the runtime_toolchain_type dependency, I think you should still be able to `build` a java_binary without requiring a matching available toolchain?
* When using `bazel run`, If you're going to be platform-sensitive with runfiles, wouldn't you want runfiles compatible with the host platform, not target? (If you're not using a hermetic jre, you're going to get the locally installed host-platform-compatible jre)

I also pulled in the starlark rules_java and the error persists (resolving the current_java_runtime alias).  You can toggle the load statement in not_android_example/BUILD.   I think an issue is that since the rule declares its need for the runtime_toolchain_type, that must always be valid at analysis time.

> Regarding the other toolchain resolution failures you are seeing: Is it possible that some custom rules or genrules you are using aren't correctly transitioning to the exec configuration? Do you also have a reproducer for these non-Android issues?

Are you referring to the toolchain_resolution_debug output from above?

**Comment by cushon** [comment] 2023-03-04 00:49
```
ERROR: <output_base>/external/bazel_tools/tools/jdk/BUILD:28:19: While resolving toolchains for target @bazel_tools//tools/jdk:current_java_runtime
```

You can use cquery to see the patch to the target that's resolving the toolchain:

```
bazel cquery 'somepath(//not_android_example/..., @bazel_tools//tools/jdk:current_java_runtime)'
...
//not_android_example:java_test (93797ec)
@bazel_tools//tools/jdk:toolchain_java8 (93797ec)
@bazel_tools//tools/jdk:platformclasspath (93797ec)
@bazel_tools//tools/jdk:current_java_runtime (9d8e7aa)
```

The `platformclasspath` stuff depends on a JDK in the target configuration so Java compilation can cross-compile to the right JDK version (this corresponds to javac's `--bootclasspath`/`--system` flags). The Java compilation output is architecture-independent, so we only really need a JDK with the same major version as the target platform, not necessarily the same architecture, but the way the provided Java toolchains are set up right now the two are tied together.

**Comment by hvadehra** [comment] 2023-09-15 14:05
Waiting for bazel 6.4 to try #18262

**Closed** 2023-10-19 17:13 UTC
Labels: type: bug, P2, team-Rules-Java, next_month
