### ISSUE TITLE
bazel rules for protobuf

### ISSUE THREAD

**Issue by jeshjesh** [bazelbuild/bazel#1610] opened 2016-08-08 06:20 UTC
`proto_library(
           name = "foo_proto",
           srcs = ["foo.proto"],
   )
   
   java_proto_library(
           name = "foo_proto_lib",
           deps = [":foo_proto"],
   )
`
bazel build returns ERROR : name 'java_proto_library' is not defined.

**Comment by hermione521** [comment] 2016-08-08 09:35
Hi, sorry I can't reproduce with this. Could you provide more information? Eg. your bazel version and your project. Thanks!

**Comment by jeshjesh** [comment] 2016-08-09 06:09
My bazel version is 0.3.0. I want to generate java code from proto. But it seems 'java_proto_library' cannot work.

**Comment by damienmg** [comment] 2016-10-06 11:58
@cgrushko to comment but I am pretty sure java_proto_library is not in 0.3.0

**Comment by cgrushko** [comment] 2016-10-06 15:21
`java_proto_library` was introduced in July 11, while 0.3.0 was released in June.
The rule is still experimental and keeps changing, so building Bazel from head would probably give you a better experience for this rule.

**Comment by hermione521** [comment] 2016-10-10 12:02
Feel free to reopen if HEAD doesn't work for you.

**Closed by hermione521** 2016-10-10 12:02 UTC
Labels: category: rules > misc native, Under investigation
