### ISSUE TITLE
Errors After Renaming WORKSPACE to WORKSPACE.bazel

### ISSUE THREAD

**Issue by flolu** [bazelbuild/bazel#11036] opened 2020-03-27 12:47 UTC
### Description of the problem:

Everything works fine when running `bazel build //...`. But after renaming my `WORKSPACE` file to `WORKSPACE.bazel` the `bazel build //...` throws the following errors:
```
INFO: Call stack for the definition of repository 'com_github_pkg_errors' which is a go_repository (rule definition at /home/flolu/.cach
e/bazel/_bazel_flolu/9d1b897d04e9a8aa4b1c82ee6b746d0c/external/bazel_gazelle/internal/go_repository.bzl:189:17):
 - <builtin>
 - /home/flolu/.cache/bazel/_bazel_flolu/9d1b897d04e9a8aa4b1c82ee6b746d0c/external/io_bazel_rules_docker/repositories/go_repositories.bzl:44:9
 - /home/flolu/.cache/bazel/_bazel_flolu/9d1b897d04e9a8aa4b1c82ee6b746d0c/external/io_bazel_rules_docker/nodejs/image.bzl:44:5
 - /home/flolu/Desktop/workspace-rename-issue/WORKSPACE.bazel:45:1
ERROR: An error occurred during the fetch of repository 'com_github_pkg_errors':
   Not a regular file: /home/flolu/Desktop/workspace-rename-issue/WORKSPACE
ERROR: /home/flolu/.cache/bazel/_bazel_flolu/9d1b897d04e9a8aa4b1c82ee6b746d0c/external/io_bazel_rules_docker/container/go/cmd/join_layer
s/BUILD:3:1: @io_bazel_rules_docker//container/go/cmd/join_layers:go_default_library depends on @com_github_pkg_errors//:go_default_library in repository @com_github_pkg_errors which failed to fetch. no such package '@com_github_pkg_errors//': Not a regular file: /home/flolu/Desktop/workspace-rename-issue/WORKSPACE
ERROR: Analysis of target '//service:image' failed; build aborted: no such package '@com_github_pkg_errors//': Not a regular file: /home
/flolu/Desktop/workspace-rename-issue/WORKSPACE
INFO: Elapsed time: 0.815s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (25 packages loaded, 665 targets configured)
    Fetching @com_github_google_go_containerregistry; fetching
error Command failed with exit code 1.
```

### What's the simplest, easiest way to reproduce this bug?

[Here](https://github.com/flolu/bazel-workspace-rename-issue) is a minimal example which reproduces the error:
1. Clone [this](https://github.com/flolu/bazel-workspace-rename-issue) repo
2. Run `yarn install`
> Not that running `yarn build` works perfectly fine
3. Rename `WORKSPACE` file to `WORKSPACE.bazel`
4. Run `yarn build`

### What operating system are you running Bazel on?

Ubuntu 19.10

### What's the output of `bazel info release`?
```
release 2.2.0
```

**Comment by bermanboris** [comment] 2020-05-10 22:55
I can confirm this.

**Comment by flolu** [comment] 2020-09-07 20:35
Any updates?

**Comment by philwo** [comment] 2020-11-25 15:22
I don't think this is a Bazel bug. Maybe it's an issue with Gazelle not supporting WORKSPACE.bazel in that version yet?

**Comment by dzintars** [comment] 2020-11-25 15:58
Mby this https://github.com/bazelbuild/bazel-gazelle/issues/678

**Comment by philwo** [comment] 2020-11-25 16:15
@dzintars Thanks! Indeed that looks like the culprit. I'll close this issue.

**Closed by philwo** 2020-11-25 16:15 UTC
Labels: P4, team-XProduct, type: support / not a bug (process)
