### ISSUE TITLE
November release

### ISSUE THREAD

**Issue by kchodorow** [bazelbuild/bazel#2027] opened 2016-11-02 18:07 UTC
Assigning to @laszlocsomor since he has fixes he wants to get out, feel free to reassign.

**Comment by kchodorow** [comment] 2016-11-02 18:08
Previous release issue: #1902.

**Comment by petemounce** [comment] 2016-11-02 19:47
Are the pieces of automation that publish to github releases somewhere that I'd be able to PR to, to get them to publish the zip file the chocolatey package needs?

**Comment by damienmg** [comment] 2016-11-02 20:11
Yes everything is on github (scripts/ci/build.sh and
bazelbuild/continuous-integration). However, @meteorcloudy already
submitted a change for zip file but it is not in the 0.4.0 release that why
we still have to do the zip manually. Next release should have the zip file.

**Comment by petemounce** [comment] 2016-11-02 20:13
@damienmg ok. Ping me once zip+sha256 files are up at GHR, and I'll submit the package.

**Comment by petemounce** [comment] 2016-11-03 10:35
https://chocolatey.org/packages/bazel/0.4.0 is published and in their moderation queue.

**Comment by laszlocsomor** [comment] 2016-11-03 12:25
What is my responsibility as assignee of this bug?

**Comment by laszlocsomor** [comment] 2016-11-21 09:53
ci.bazel.io is down at the moment, but we're nearing the end of the month, so I'm creating a new release. We can cherrypick bugfixes for test failures if needed.

```
$ scripts/release/release.sh create 0.4.1 9a796de5c7b881d48b42101a22afb734397aadae 88bfe858aaac9138b7d0341982ca4150474479c9 b09ea9435280745e294d03d735810a56efca337f
...
Created 0.4.1RC1 on branch release-0.4.1.

$ git checkout release-0.4.1

$ scripts/release/release.sh push
...
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by laszlocsomor** [comment] 2016-11-21 10:21
After recreating the SSH keys ([following GitHub's steps](https://help.github.com/articles/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent/#platform-linux)) I could successfully push:

```
$ scripts/release/release.sh push
...
Everything up-to-date
```

**Comment by petemounce** [comment] 2016-11-21 11:18
Does that mean there is an rc in the gcs bucket I should wrap and push?

**Comment by laszlocsomor** [comment] 2016-11-21 11:48
Thanks for asking! There's a new RC, but no release yet. Do you push RCs too?

Also I know this RC will not be the final one, because last week while we still had ci.bazel.io up I already intended to start a new release but the CI was red. AFAIK we haven't fixed those tests since then and now the CI is also down. Still I decided to create a new RC so we have can have dogfooders test it if they like.

**Comment by petemounce** [comment] 2016-11-21 11:52
I push RCs too, yes. I'll do one shortly.

**Comment by laszlocsomor** [comment] 2016-11-21 11:58
Great, thank you!

**Comment by petemounce** [comment] 2016-11-21 12:02
@laszlocsomor the naming convention for the 0.4.1 rc1 doesn't follow the one for 0.4.0 - any chance you could do another one that does? Otherwise I'll need to modify the [packages/chocolatey/build.ps1](https://github.com/bazelbuild/bazel/blob/master/scripts/packages/chocolatey/build.ps1#L13-L16) script again to cope with another pattern.

* `0.4.0/rc3/bazel-0.4.0rc3-windows-x86_64.zip`
* `0.4.1-test/rc1/bazel-0.4.1-testrc1-windows-x86_64.zip`

**Comment by laszlocsomor** [comment] 2016-11-21 12:07
Let me figure out how :)

**Comment by laszlocsomor** [comment] 2016-11-21 12:20
I asked around, turns out 0.4.1-test is *not* what you're looking for. It's a test release we ran earlier. Since ci.bazel.io is now down and it's the "Bazel release" job pushing to GCS, we don't yet have an actual RC in the bucket. Sorry about the false alarm Peter.

**Comment by laszlocsomor** [comment] 2016-11-21 12:21
Thanks @meteorcloudy too!

**Comment by petemounce** [comment] 2016-11-21 12:23
No worries. Ping me when you have one.

**Comment by meteorcloudy** [comment] 2016-11-22 12:35
@petemounce Can you remove the python2 restriction on https://chocolatey.org/packages/bazel in the next release? Because now Bazel already supports python3 on Windows from `0.4.0`.

**Comment by laszlocsomor** [comment] 2016-11-22 16:44
The CI is back and it's overwhelmingly, if not completely, green! So let's abandon the previous RC (@dslomov says there'd be a lot of cherrypicks from him alone) and cut from HEAD.

I abandoned the old release (`release.sh abandon`) then started a new one:
```
$ scripts/release/release.sh create 0.4.1 2a26c3ce02370ebec317d9148a13ca53853feab6
...
Created 0.4.1RC1 on branch release-0.4.1.

$ scripts/release/release.sh push
...
To git@github.com:bazelbuild/bazel
   b0f5f36..57d4f9e  refs/notes/release-candidate -> refs/notes/release-candidate
```

**Comment by laszlocsomor** [comment] 2016-11-22 16:45
Now let's wait for the CI to run the tests for this RC.

**Comment by meteorcloudy** [comment] 2016-11-22 16:46
\o/

**Comment by meteorcloudy** [comment] 2016-11-22 16:47
Thanks @dslomov!

**Comment by laszlocsomor** [comment] 2016-11-23 08:40
Bazel-Release job failed [1], investigating.

[1] http://ci.bazel.io/view/Bazel%20bootstrap%20and%20maintenance/job/Bazel-Release/83/console

**Comment by meteorcloudy** [comment] 2016-11-23 08:48
The RC doesn't contain this change https://github.com/bazelbuild/bazel/commit/a79581e7a0f9f99c2985d3e5876fee72bc982637
Please cherry pick :)

**Comment by laszlocsomor** [comment] 2016-11-23 08:51
Creating new RC with https://github.com/bazelbuild/bazel/commit/a79581e7a0f9f99c2985d3e5876fee72bc982637

**Comment by laszlocsomor** [comment] 2016-11-23 10:26
RC2 created, pushed, tested, and announced: https://groups.google.com/forum/#!msg/bazel-discuss/DqWLzbXufjY/b9aAG_5jCAAJ

**Comment by laszlocsomor** [comment] 2016-11-23 14:02
@petemounce : 0.4.1rc2 is ready and waiting in the GCS bucket, could you please push a Chocolatey package?

**Comment by meteorcloudy** [comment] 2016-11-23 15:25
I also tested the RC could build TF with or without GPU support on Windows, so let's do it!

**Comment by petemounce** [comment] 2016-11-23 16:22
https://chocolatey.org/packages/bazel/0.4.1-rc2 now exists and is going through chocolatey's moderation (which, for RCs, I gather doesn't involve a human review, just automated tests).

**Comment by petemounce** [comment] 2016-11-29 16:09
Forgot to mention, https://chocolatey.org/packages/bazel/0.4.1-rc2-20161124-122858 has been available since 24/Nov.

**Comment by meteorcloudy** [comment] 2016-11-29 16:48
@laszlocsomor Can we have the bazel release by Wednesday? We need the new version to fix http://ci.tensorflow.org/job/tf-master-win-bzl/

**Comment by laszlocsomor** [comment] 2016-11-29 19:50
@meteorcloudy : Yes, I'm pushing it tomorrow morning. The RC will be turning 5 business days old tonight.

**Comment by meteorcloudy** [comment] 2016-11-29 19:52
@laszlocsomor Thanks! Have a good night!

**Comment by jart** [comment] 2016-11-29 22:04
I just want to make sure this release is going to include https://github.com/bazelbuild/bazel/commit/ed7ced0018dc5c5ebd6fc8afc7158037ac1df00d and https://github.com/bazelbuild/bazel/commit/4c67807964e37cfd55bbcda4c6374fcc480bcecc which are needed very badly by TensorFlow.

**Comment by laszlocsomor** [comment] 2016-11-30 09:19
I pushed the 0.4.1 candidate now:
```
$ scripts/release/release.sh release
```

@jart : This is the first time I hear about these commits, so they are *not* included. I can cherrypick them and create a new RC.

**Comment by laszlocsomor** [comment] 2016-11-30 09:27
I just noticed that the baseline commit is wrong in the release notes. It reflects the rc1 baseline + cherrypicks, not the rc2.

The rc2's baseline is https://github.com/bazelbuild/bazel/commit/2a26c3ce02370ebec317d9148a13ca53853feab6 and has one cherrypick https://github.com/bazelbuild/bazel/commit/a79581e7a0f9f99c2985d3e5876fee72bc982637.

@jart : I'll start a new release with the same baseline+cherrypick as 0.4.1-rc2, plus add the two cherrypicks if they can cleanly be merged, and call the whole thing 0.4.2 to avoid name clashes.

**Comment by laszlocsomor** [comment] 2016-11-30 09:38
Ok, that didn't work. I tried:
```
$ scripts/release/release.sh create 0.4.2 2a26c3ce02370ebec317d9148a13ca53853feab6 a79581e7a0f9f99c2985d3e5876fee72bc982637 4c67807964e37cfd55bbcda4c6374fcc480bcecc ed7ced0018dc5c5ebd6fc8afc7158037ac1df00d
```
...but there were too many merge conflicts.

So I'll just cut from HEAD (f699b502ef6a57dc68570486191ad1c318e8fd1b).

**Comment by laszlocsomor** [comment] 2016-11-30 10:02
I manually updated the release notes on GitHub for 0.4.1, so the baseline and cherrypick info are now correct.

**Comment by laszlocsomor** [comment] 2016-11-30 10:06
Started 0.4.2 release with @jart's  cherrypicks (only ed7ced0 because the other one is included in the baseline).

```
$ scripts/release/release.sh create 0.4.2 9e948640731e85c3e75b0faa2fefde61ca44d1ac ed7ced0018dc5c5ebd6fc8afc7158037ac1df00d
$ git checkout release-0.4.2
$ scripts/release/release.sh push
```

**Comment by laszlocsomor** [comment] 2016-11-30 10:33
Jenkins failed to pick up the new RC. I'll abandon and try to recreate it.

**Comment by laszlocsomor** [comment] 2016-11-30 11:52
Re: Jenkins: the problem is f17fb3a816851b9f3a954c881e3fbc35bed5d6a6, I put the `-m` to the wrong place. Fixing in the internal depot, pushing soon, then I'm retrying the failed Jenkins job, and that'll hopefully send the RC announcement email and run the tests.

**Comment by laszlocsomor** [comment] 2016-11-30 12:56
Jenkins job bug fixed (https://github.com/bazelbuild/bazel/commit/6331a94bf74b936c7cbb2868267936f0981e10d9).

Abandoning the current RC and cutting from HEAD:
```
$ scripts/release/release.sh create 0.4.2 6331a94bf74b936c7cbb2868267936f0981e10d9
$ scripts/release/release.sh push
```

**Comment by laszlocsomor** [comment] 2016-11-30 13:26
RC1 pushed and announced: https://groups.google.com/d/msg/bazel-discuss/-RB477WVkEo/VmVFOhOXCgAJ

**Comment by laszlocsomor** [comment] 2016-11-30 13:27
@petemounce : Pete, could you please create a Chocolatey package for the 0.4.1 release, and if you feel like it, for the 0.4.2rc1?

**Comment by laszlocsomor** [comment] 2016-11-30 13:31
I'll update the Homebrew package tomorrow, as I don't have my macbook here.

**Comment by petemounce** [comment] 2016-11-30 17:50
@laszlocsomor sure, doing that now.

**Comment by petemounce** [comment] 2016-11-30 18:00
@laszlocsomor Published the following:
* https://chocolatey.org/packages/bazel/0.4.1
* https://chocolatey.org/packages/bazel/0.4.2-rc1

Both wait in their queues for automated validation.

0.4.1 also has to pass a human review.

**Comment by petemounce** [comment] 2016-11-30 18:02
By the way - the nuspec is generated with the github releases URI to release notes - I'll correct that for RCs, where the release notes are in the GS bucket. By the way, it's possible to publish pre-releases to GH releases API - something to consider?

**Comment by laszlocsomor** [comment] 2016-11-30 18:47
> @laszlocsomor Published the following:

Awesome, thank you!

> By the way - the nuspec is generated with the github releases URI to release notes - I'll correct that for RCs, where the release notes are in the GS bucket.

Ok, I never noticed. :) Thanks!

> By the way, it's possible to publish pre-releases to GH releases API - something to consider?

What would that entail, we'd have a RC on the releases page? Anything else, e.g. would it make anything easier (such as nuspec generation)?

I don't feel strongly about it. @damienmg ?

**Comment by damienmg** [comment] 2016-11-30 18:55
I don't really know. Github is already quite flaky so adding more github
integration is going to add more network errors like we got for 0.4.1
Darwin installer.

**Comment by petemounce** [comment] 2016-11-30 23:19
0.4.1 has been approved.

re: releasing prerelease releases (mouthful!), https://developer.github.com/v3/repos/releases/#create-a-release - apparently, there's a prerelease boolean to pass when creating one.

**Comment by meteorcloudy** [comment] 2016-11-30 23:28
@laszlocsomor Sorry, I have a bad news here. When I was trying to build TF with GPU support, I found out that a79581e didn't make it into 0.4.1 for some reason. I confirmed this by looking at the source code of 0.4.1.

But anyway, we are having 0.4.2 soon, it's just we have to modify the release note again... :(

**Comment by laszlocsomor** [comment] 2016-12-01 10:42
Homebrew recipe is already updated for 0.4.1 (https://github.com/Homebrew/homebrew-core/pull/7417), thank you kindly @dpursehouse !

**Comment by laszlocsomor** [comment] 2016-12-01 12:28
Handing release manager role over to @iirina , closing this issue.

**Closed by laszlocsomor** 2016-12-01 12:28 UTC
Labels: Release blocker, type: process
