### ISSUE TITLE
Bazel crashes when `external` directory present

### ISSUE THREAD

**Issue by minorhacks** [bazelbuild/bazel#3307] opened 2017-06-30 22:57 UTC
### Description of the problem / feature request / question:

`bazel build //...` causes Bazel to exit with a stack trace when an (empty) `external` directory is present in the workspace root.

I understand that `external` is supposed to be a special directory for symlinking of external dependencies declared in WORKSPACE and you probably don't want users putting code in it; however, the error message is not terribly descriptive of the root cause of the issue.

### If possible, provide a minimal example to reproduce the problem:

```
mkdir /tmp/bazel_workspace
cd /tmp/bazel_workspace
touch WORKSPACE
mkdir external
bazel build ...
```

This prints:

```
Unhandled exception thrown during build; message: Unrecoverable error while evaluating node 'TARGET_PATTERN:...' (requested by nodes )
____Elapsed time: 0.341s
java.lang.RuntimeException: Unrecoverable error while evaluating node 'TARGET_PATTERN:...' (requested by nodes )
	at com.google.devtools.build.skyframe.ParallelEvaluator$Evaluate.run(ParallelEvaluator.java:474)
	at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:357)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalArgumentException: No such attribute tags in new_http_archive rule //external:bazel_j2objc
	at com.google.devtools.build.lib.packages.AbstractAttributeMapper.getIndexWithTypeCheck(AbstractAttributeMapper.java:229)
	at com.google.devtools.build.lib.packages.AbstractAttributeMapper.get(AbstractAttributeMapper.java:57)
	at com.google.devtools.build.lib.packages.NonconfigurableAttributeMapper.get(NonconfigurableAttributeMapper.java:45)
	at com.google.devtools.build.lib.packages.TargetUtils.hasConstraint(TargetUtils.java:148)
	at com.google.devtools.build.lib.packages.TargetUtils.hasManualTag(TargetUtils.java:76)
	at com.google.devtools.build.lib.pkgcache.FilteringPolicies$FilterManual.shouldRetain(FilteringPolicies.java:74)
	at com.google.devtools.build.lib.pkgcache.FilteringPolicies$AndFilteringPolicy.shouldRetain(FilteringPolicies.java:106)
	at com.google.devtools.build.lib.skyframe.RecursivePackageProviderBackedTargetPatternResolver$2.call(RecursivePackageProviderBackedTargetPatternResolver.java:304)
	at com.google.devtools.build.lib.skyframe.RecursivePackageProviderBackedTargetPatternResolver$2.call(RecursivePackageProviderBackedTargetPatternResolver.java:289)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:111)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:58)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:75)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutorService.execute(MoreExecutors.java:260)
	at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:134)
	at com.google.common.util.concurrent.AbstractListeningExecutorService.submit(AbstractListeningExecutorService.java:66)
	at com.google.devtools.build.lib.skyframe.RecursivePackageProviderBackedTargetPatternResolver.findTargetsBeneathDirectoryAsyncImpl(RecursivePackageProviderBackedTargetPatternResolver.java:289)
	at com.google.devtools.build.lib.skyframe.RecursivePackageProviderBackedTargetPatternResolver.findTargetsBeneathDirectory(RecursivePackageProviderBackedTargetPatternResolver.java:215)
	at com.google.devtools.build.lib.cmdline.TargetPattern$TargetsBelowDirectory.eval(TargetPattern.java:541)
	at com.google.devtools.build.lib.skyframe.TargetPatternFunction.compute(TargetPatternFunction.java:71)
	at com.google.devtools.build.skyframe.ParallelEvaluator$Evaluate.run(ParallelEvaluator.java:400)
	... 4 more
java.lang.RuntimeException: Unrecoverable error while evaluating node 'TARGET_PATTERN:...' (requested by nodes )
	at com.google.devtools.build.skyframe.ParallelEvaluator$Evaluate.run(ParallelEvaluator.java:474)
	at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:357)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalArgumentException: No such attribute tags in new_http_archive rule //external:bazel_j2objc
	at com.google.devtools.build.lib.packages.AbstractAttributeMapper.getIndexWithTypeCheck(AbstractAttributeMapper.java:229)
	at com.google.devtools.build.lib.packages.AbstractAttributeMapper.get(AbstractAttributeMapper.java:57)
	at com.google.devtools.build.lib.packages.NonconfigurableAttributeMapper.get(NonconfigurableAttributeMapper.java:45)
	at com.google.devtools.build.lib.packages.TargetUtils.hasConstraint(TargetUtils.java:148)
	at com.google.devtools.build.lib.packages.TargetUtils.hasManualTag(TargetUtils.java:76)
	at com.google.devtools.build.lib.pkgcache.FilteringPolicies$FilterManual.shouldRetain(FilteringPolicies.java:74)
	at com.google.devtools.build.lib.pkgcache.FilteringPolicies$AndFilteringPolicy.shouldRetain(FilteringPolicies.java:106)
	at com.google.devtools.build.lib.skyframe.RecursivePackageProviderBackedTargetPatternResolver$2.call(RecursivePackageProviderBackedTargetPatternResolver.java:304)
	at com.google.devtools.build.lib.skyframe.RecursivePackageProviderBackedTargetPatternResolver$2.call(RecursivePackageProviderBackedTargetPatternResolver.java:289)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:111)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:58)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:75)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutorService.execute(MoreExecutors.java:260)
	at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:134)
	at com.google.common.util.concurrent.AbstractListeningExecutorService.submit(AbstractListeningExecutorService.java:66)
	at com.google.devtools.build.lib.skyframe.RecursivePackageProviderBackedTargetPatternResolver.findTargetsBeneathDirectoryAsyncImpl(RecursivePackageProviderBackedTargetPatternResolver.java:289)
	at com.google.devtools.build.lib.skyframe.RecursivePackageProviderBackedTargetPatternResolver.findTargetsBeneathDirectory(RecursivePackageProviderBackedTargetPatternResolver.java:215)
	at com.google.devtools.build.lib.cmdline.TargetPattern$TargetsBelowDirectory.eval(TargetPattern.java:541)
	at com.google.devtools.build.lib.skyframe.TargetPatternFunction.compute(TargetPatternFunction.java:71)
	at com.google.devtools.build.skyframe.ParallelEvaluator$Evaluate.run(ParallelEvaluator.java:400)
	... 4 more
```

### Environment info
* Operating System:
Ubuntu 16.04

* Bazel version (output of `bazel info release`):
`release 0.5.2`

**Comment by kchodorow** [comment] 2017-07-05 14:05
Related (possibly duplicate of) #1606.

**Closed** 2017-07-07 11:09 UTC
Labels: P2

**Comment by minorhacks** [comment] 2017-07-07 21:01
Thanks for the fix! Looking forward to picking this up in the next release :)
