### ISSUE TITLE
Add the Bazel arm64 binary release

### ISSUE THREAD

**Issue by TrevorTaoARM** [bazelbuild/bazel#11134] opened 2020-04-16 03:15 UTC
Now in the Bazel binary release, there's no arm64(aarch64) binary here for downloading though it could be built from source. It's very inconvenient for its use on arm64 platform.
So I ask if Bazel arm64 binary can be added in the official release here?

**Comment by jwnimmer-tri** [comment] 2020-06-05 18:15
This might be a duplicate of #8833?

**Comment by philwo** [comment] 2020-07-07 09:02
Duplicate of #8833

**Closed by philwo** 2020-07-07 09:02 UTC
Labels: team-XProduct, untriaged
