### ISSUE TITLE
proto_library: warning: directory does not exist

### ISSUE THREAD

**Issue by jayconrod** [bazelbuild/bazel#7157] opened 2019-01-17 15:57 UTC
### Description of the problem / feature request:

Building `proto_library` targets for Well Known Types in `@com_google_protobuf` emits warnings like the one below. The build succeeds, but it would be nice if the warning can be fixed or removed.

```
$ bazel build @com_google_protobuf//:any_proto
...
INFO: From Generating Descriptor Set proto_library @com_google_protobuf//:any_proto:
external/com_google_protobuf: warning: directory does not exist.
...
```

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

```
# WORKSPACE
load("@bazel_tools//tools/build_defs/repo:git.bzl", "git_repository")

git_repository(
    name = "com_google_protobuf",
    remote = "https://github.com/protocolbuffers/protobuf",
    tag = "v3.6.1.3",
)

git_repository(
    name = "bazel_skylib",
    remote = "https://github.com/bazelbuild/bazel-skylib",
    tag = "0.6.0",
)
```

```
bazel build @com_google_protobuf//:any_proto
```

### What operating system are you running Bazel on?

Linux amd64

### What's the output of `bazel info release`?

release 0.21.0

This does not happen in 0.20.0, but it does happen in 0.22.0rc2.

**Comment by jayconrod** [comment] 2019-01-17 15:58
@lberki I wonder if this is related to recent source root changes?

**Comment by lberki** [comment] 2019-01-21 13:08
/cc @haberman

Probably, I suppose? We did reshuffle the way `protoc` is called a bit. I'm traveling this week and next, though, so I probably won't be able to look at it closely until I get back home. 

@dbabkin , can you help out?

**Comment by thaidn** [comment] 2019-03-03 03:57
Friendly ping. This still happens in 0.22.0.

**Comment by dbabkin** [comment] 2019-03-08 09:19
Hi,
There is no ETA when that will be fixed. 
Priority of this task is low, as it is warning only.

**Comment by steeve** [comment] 2019-06-06 21:28
Small ping, still happening in 0.25.3

**Comment by dapirian** [comment] 2019-06-28 17:39
Ping again, this is extremely annoying and spammy.

**Comment by lberki** [comment] 2019-07-02 13:24
Update: I have a change under review that will fix this issue. Let's see how the review goes. It's not complicated, so it shouldn't be problematic.

**Comment by lberki** [comment] 2019-07-03 06:43
...and apologies for the delay. I know it was very annoying (in fact, the reason why I fixed it was because it annoyed *me*! :) )

**Comment by lberki** [comment] 2019-07-03 10:07
Well, that was optimistic:

https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/1067#24a01f98-1ed2-4423-8d94-bf11cef557e4

The change will have to be rolled back. I'll take a look the next time I have some spare time.

**Comment by lberki** [comment] 2019-07-03 12:12
Ugh. This is awful. Hear me out.

This warning messages happens when all the source files of a `proto_library` in an external repository are generated and therefore `--proto_path=<root of external repository>` is superfluous. However, the list of proto source roots comes from the same place that we use to determine the the prefix we should cut off the exec path to obtain the proto import path.

Of course, we have to cut off different parts depending on whether the proto file is source or generated, but that we determine by... guesswork in `guessProtoPathUnderRoot`:

https://github.com/bazelbuild/bazel/blob/master/src/main/java/com/google/devtools/build/lib/rules/proto/ProtoCompileActionBuilder.java#L659

That algorithm broke when we removed the directory from the set of proto paths. The reason why only Go broke is that the line below saves us, but I don't want to rely on it:

https://github.com/bazelbuild/bazel/blob/master/src/main/java/com/google/devtools/build/lib/rules/proto/ProtoCompileActionBuilder.java#L671

, but `go_proto_library` doesn't have its equivalent.

So that change was indeed wrong. Now, the question is, how to make it right -- eliminating the warning requires that we remove a repository root from the set of proto paths if there are only generated files, but if we remove it, the algorithm to generate `-I` clauses suddenly stops working.

Furthermore, it's not trivial to decouple `--proto_path` from `-I` because they are both derived from `ProtoInfo`, which is exposed to Starlark, so we can't just change it willy-nilly.

**Comment by hlopko** [comment] 2019-07-03 12:45
Shouldn't we remove `.proto_source_root` by https://github.com/bazelbuild/bazel/issues/7153?

**Comment by lberki** [comment] 2019-07-03 13:04
This is not about the attribute, but the eponymous field of `ProtoInfo`.

**Comment by hlopko** [comment] 2019-07-03 13:10
Yup, what I'm asking is if the field makes sense when the attribute is gone.

**Comment by lberki** [comment] 2019-07-03 13:27
It does. That field tells what the _effective_ proto source root is. That's a concept that makes sense even when the attribute will be gone.

**Comment by lberki** [comment] 2019-07-03 19:10
So, I got a bit nerd sniped and I have another solution: simply create a virtual proto import directory when the `proto_library` rule has a generated `.proto` file just like we do when `strip_import_prefix` or `import_prefix` is set.

Granted, it's not _that_ simple because we still need to make sure that our internal repository keeps chugging along, but I'd gladly fork the behavior of `proto_library` in this respect (they are different already, so no big change) if that's what I have to do to make `proto_library` saner for everyone else.

That's _still_ not a tiny amount of work and it is _still_ possible that some odd downstream project breaks, but this is certainly much simpler than the previous alternative. And it doesn't even require lying to Starlark!

**Comment by lberki** [comment] 2019-07-08 09:18
Update: I have another fix. Learning from the previous one, I have to run in through all sorts of presubmits to make sure that it doesn't break anything. It introduces a slight incompatibility which I hope no one relies on, but there is only one way to be sure...

**Comment by lberki** [comment] 2019-07-08 11:52
Update: collateral damage is minimal. Unfortunately, it includes `rules_rust` and Bazel itself.

I'll send out changes to both then try to submit this.

**Comment by lberki** [comment] 2019-07-09 12:38
/cc @scentini 

Update: this will have to be rolled back due to some obscure semantic differences within Google.

The fix is trivial and expect it to land tomorrow, but I'd much rather not cowboy code up a forward fix and instead work without time presure.

**Comment by lberki** [comment] 2019-07-09 13:34
...and there is also https://github.com/bazelbuild/bazel/issues/8832, but that's fixed by https://github.com/bazelbuild/bazel-buildfarm/pull/272 . Once that's submitted and I can find some breathing room, I'll try to roll this forward again.

**Comment by lberki** [comment] 2019-07-10 08:36
Update: I have third fix. To verify, I:

* Fixed the Google-internal usage and checked that everything that was broken is now OK
* Updated the fix to grpc-java (https://github.com/grpc/grpc-java/pull/5967)
* Updated the patch to grpc-java in buildfarm (https://github.com/bazelbuild/bazel-buildfarm/pull/275)
* Ran a Bazel global presubmit
* Verified that bazel-buildfarm works with all four combinations of (last Bazel release, Bazel at HEAD + this fix) x (bazel-buildfarm at HEAD, bazel-buildfarm with the above pull request)

Third time is the charm!

**Comment by ptarjan** [comment] 2019-07-24 23:31
Has this been fixed in bazel 0.28.1 or do we have to wait for 0.29.0?

**Comment by steeve** [comment] 2019-07-25 11:06
Looking at the 0.28.1 changelog it seems you'll have to wait for 0.29.

**Comment by lberki** [comment] 2019-07-25 11:14
0.29 will it be. The fix is too invasive to be cherry-picked into a point release.

**Comment by lberki** [comment] 2019-08-28 18:22
Nope, ended up causing unexpected trouble: https://github.com/bazelbuild/bazel/issues/9219

I had to turn the fix into an incompatible flag, to be flipped in 1.0: https://github.com/bazelbuild/bazel/issues/9215

Sorry about that. Couldn't make it work without breaking people :(

**Comment by sgammon** [comment] 2019-08-29 00:51
@lberki no worries, thank you for the update

**Comment by crutcher** [comment] 2020-07-09 00:05
Is this ... dead?

**Comment by joshburkart** [comment] 2020-07-23 20:52
@lberki Can we reopen this? It's still occurring in the latest version of Bazel, right?

**Comment by MegaPanchamZ** [comment] 2020-09-27 05:56
@joshburkart 

Can confirm the error still exists in Bazel 3.x.x

**Comment by phlax** [comment] 2021-03-20 14:27
it would be great if this was fixed (and i guess the bug reopened)

we would like to make warnings into errors to prevent other proto generation issues, but i think these warnings make that not possible

**Comment by aviezab** [comment] 2021-05-29 22:42
![image](https://user-images.githubusercontent.com/34294278/120086516-c772fb80-c109-11eb-973e-d3871e436b68.png)
Still happens tho in the latest release.

**Comment by michael-lefkowitz-techlabs** [comment] 2021-07-23 00:06
I'm still having this problem. Why was this issue closed?

**Comment by comius** [comment] 2022-01-24 14:22
The reproduction on this bug is ancient. I'm tried reproduction with Bazel 5.0.0 and bzlmod:

MODULE.bazel
```
bazel_dep(name = "protobuf", version = "3.19.2", repo_name = "com_google_protobuf")
```

Command line:
```
bazel build --experimental_enable_bzlmod @com_google_protobuf//:any_proto
```

and I get no warnings.

Can somebody please provide a reproducer on Bazel 5.0.0? Or at least add a message to the thread with Bazel versions and protobuf versions where this occurs.

**Comment by phlax** [comment] 2022-01-24 14:40
we are seeing this with bazel==`4.2.1` and protobuf==`3.19.3`

**Comment by comius** [comment] 2022-01-24 14:50
I tried with bazel 4.2.1, protobuf 3.19.2 and 3.19.3; no success reproducing. Something else is missing that's causing this.

WORKSPACE
```
load("@bazel_tools//tools/build_defs/repo:git.bzl", "git_repository")

git_repository(
    name = "com_google_protobuf",
    remote = "https://github.com/protocolbuffers/protobuf",
    tag = "v3.19.3",
)

load("@com_google_protobuf//:protobuf_deps.bzl", "protobuf_deps")
protobuf_deps()
```

Command line:
```
bazel build  @com_google_protobuf//:any_proto
```

**Comment by alyssawilk** [comment] 2022-01-24 14:51
We in this case is Envoy (https://github.com/envoyproxy/envoy).  I've sent more detailed information internally for repro since the OSS instructions need some additions to build in-google, but our CI logs show it's still definitely a problem for our project and we're super happy to help you folks reproduce

**Comment by phlax** [comment] 2022-01-24 14:52
hmm - grepping (envoyproxy/envoy) repo seems to suggest that we dont load `protobuf_deps` i wonder if that is the problem

**Comment by comius** [comment] 2022-01-24 14:56
I see the warning here https://buildkite.com/bazel/envoy/builds/1811#0c20714c-e748-4c19-a6a5-844e9b4a0e70
I'll investigate further, thanks!

**Comment by comius** [comment] 2022-01-25 10:47
The problem was created by `proto_gen` rule defined in https://github.com/protocolbuffers/protobuf project.

Correct issue is reported here: https://github.com/protocolbuffers/protobuf/issues/6049
I created a PR fixing it: https://github.com/protocolbuffers/protobuf/pull/9438

I'm closing this issue, because I didn't discover any warnings produced by the rules that are part of Bazel.

**Closed by comius** 2022-01-25 10:47 UTC
Labels: P2, more data needed, team-Rules-Server

**Comment by phlax** [comment] 2023-07-22 10:14
after being resolved for some time this has issue has returned (bazel: 6.1, protobuf: 23.1)

https://dev.azure.com/cncf/envoy/_build/results?buildId=143687&view=logs&j=8c169225-0ae8-53bd-947f-07cb81846cb5&t=4d0399a5-fd0d-5446-d022-32daa00183cc&l=296

tbh it seems more related to the protobuf version but the previous ticket in protobuf suggested it was a bazel issue

cc @alyssawilk @htuch

**Comment by phst** [comment] 2024-01-15 09:26
Yeah, this is happening for me as well with Bazel 7 and Protobuf 23.1. Maybe this issue could be reopened? Or should we file a new issue?

**Comment by tpudlik** [comment] 2025-02-20 18:29
Can we reopen this issue? These warnings continue to appear on Bazel 8.1.0 and protobuf 29.0.
