### ISSUE TITLE
Using an alias in a config_setting causes java.lang.NullPointerException

### ISSUE THREAD

**Issue by StephenWassell** [bazelbuild/bazel#7941] opened 2019-04-04 08:09 UTC
### Description of the problem / feature request:

If I define an alias based on a config_setting, then use that alias in another config_setting, it crashes Bazel. I found another way to solve the original problem but thought it would be worth reporting the bug.

### Feature requests: what underlying problem are you trying to solve with this feature?

We want our build to set a certain compiler option if either of two --defines are used, but only on one platform. While trying to achieve that I found this crash.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

```
config_setting(
    name = "config-a",
    values = {
        "define": "a=1"
    },
)

alias(
    name = "alias-a",
    actual = select({
        ":config-a": ":config-a",
        "//conditions:default": ":config-a",
    }),
)

config_setting(
    name = "config-alias",
    constraint_values = [
        ":alias-a",
    ],
)

cc_binary(
    name = "test",
    copts = select({
        ":config-alias": ["-DTEST"],
        "//conditions:default": [],
    }),
)
```
bazel build //:test

### What operating system are you running Bazel on?

Linux

### What's the output of `bazel info release`?

release 0.24.1

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

n/a

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

n/a

### Any other information, logs, or outputs that you want to share?

[log.txt](https://github.com/bazelbuild/bazel/files/3042377/log.txt)

**Comment by gregestren** [comment] 2019-04-04 21:21
Thanks for this clear report, Stephen. This is easy to reproduce.

**Comment by gregestren** [comment] 2019-04-04 21:39
It turns out this isn't related to aliases, but rather the wrong type being passed to `constraint_values`. 

According to the [config_setting documentation](https://docs.bazel.build/versions/master/be/general.html#config_setting.constraint_values), `constraint_values` can only be assigned to rules of type [constraint_value](https://docs.bazel.build/versions/master/be/platform.html#constraint_value) (I admit the documentation isn't as clear on that as it could be). So passing a `config_setting` or any other rule type triggers the crash you see.

Here's an even simpler repro:

```
config_setting(
    name = "config-2",
    values = {
        "define": "a=1",
    },
)

config_setting(
    name = "config-in-select",
    constraint_values = [
        ":config-2",
    ],
)

cc_binary(
    name = "test",
    copts = select({
        ":config-in-select": ["-DTEST"],
        "//conditions:default": [],
    }),
)
```
I'll fix the crash. But about what you originally wanted to do, what about something like...


```
config_setting(
    name = "define-1",
    values = {
        "define": "a=1"
    },
    constraint_values = [whatever platform constraints trigger]
)

config_setting(
    name = "define-2",
    values = {
        "define": "a=2"
    },
    constraint_values = [whatever platform constraints trigger]
)


copts = selects.with_or({
    (":define-1", ":define-2"): ["-DTEST"],
    ...
```

(using [selects.with_or](https://docs.bazel.build/versions/master/configurable-attributes.html#selectswith_or))

I think you can also get an alias approach working similar to what you already have.

**Closed** 2019-04-05 20:15 UTC
Labels: P1, team-Configurability
