### ISSUE TITLE
data dependency should not be required for building a target

### ISSUE THREAD

**Issue by flode** [bazelbuild/bazel#15017] opened 2022-03-10 13:52 UTC
### Description of the problem / feature request:

Building a `cc_test` target also requires the `data` dependencies, even though the `data` dependencies are only needed for running/testing.
We are using data dependencies for large test data and currently these large files need to be downloaded even when just building.

### Feature requests: what underlying problem are you trying to solve with this feature?

Specify an external `data` dependency, and only have it downloaded when it's actually needed.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

```
$ cat WORKSPACE 
load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")
http_archive(
    name = "largefile",
    url = "https://github.com/bazelbuild/bazel/archive/refs/tags/6.0.0-pre.20220223.1.zip"
)

$ cat BUILD.bazel 
load("@rules_cc//cc:defs.bzl", "cc_test")
cc_test(
    name = "test",
    data = ["@largefile"],
    srcs = glob([
        "*.cpp",
        "*.hpp",
    ]),
)

$ cat x.test.cpp 
int main() {
   return 0;

$ bazel build test
```
Running the bazel command downloads the zip file, even though it's not needed for the build.

### What operating system are you running Bazel on?

Ubuntu 20.04

### What's the output of `bazel info release`?

release 5.0.0

I also tried it with today's master, same behavior there (8dcf27e590ce77241a15fd2f2f8b9889a3d7731b)

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

--

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

--

###  Have you found anything relevant by searching the web?

According to the documentation `data` does not affect how the target is built:
```
A build target might need some data files to run correctly. These data files aren't source code: they don't affect how the target is built.
```
https://docs.bazel.build/versions/main/build-ref.html#data

### Any other information, logs, or outputs that you want to share?

--

**Comment by oquenchil** [comment] 2022-03-16 07:52
All the data dependencies need to be placed in the right place in the runfiles directory. This needs to be during building and cannot wait till you start testing.

**Comment by hofst** [comment] 2022-03-16 10:25
@oquenchil Could you elaborate on that? This sounds like an unintended implementation detail of bazel that should be fixed, e.g., by putting things lazily into the runfiles directory.
Is there an alterntive way to achieve the desired behavior, i.e., have dependencies for tests that are not downloaded during build?

**Comment by sgowroji** [comment] 2022-03-19 07:11
Hello @hofst, Could you please provide complete details in a new issue  w.r.t your above [query](https://github.com/bazelbuild/bazel/issues/15017#issuecomment-1068964892).  Thanks!

**Comment by hofst** [comment] 2022-03-19 09:40
@sgowroji 
My issue is the exact issue of @flode . I think we should reopen this issue.

**Comment by carlosgalvezp** [comment] 2022-07-04 14:03
It has been discussed the perspective of "Bazel as a tool to build a binary that one will later on execute". I'd like to bring the perspective of "linting" (e.g. formatting, static code analysis). Typically this is implemented in terms of "**aspects**". The main [documentation of aspects ](https://docs.bazel.build/versions/main/skylark/aspects.html) has a nice picture showing how indeed the "runtime data dependencies" are not part of the aspect graph. And yet the data is still fetched in practice (since it's part of a "build" action), which is a huge overhead for a job that just does linting.

Is that expected? Wouldn't it be possible to add some flag to "opt-out" of this feature? If people want to run binaries outside Bazel they are anyway already kind of on their own when it comes to managing their runtime dependencies.

**Comment by digit-google** [comment] 2022-07-04 17:35
As far as I understand, Bazel needs to process the full build graph for your project to ensure it can always provide correct and reproducible builds. So having any type of dependency (data or otherwise) properly defined and available is necessary even if they are never used during a `bazel build` operation.

So I would say it is expected and part of Bazel's design, i.e. the price to pay for correctness.

**Comment by carlosgalvezp** [comment] 2022-07-04 17:44
Why make the distinction between "data" and "deps" then? If all dependencies are fully needed for any given action (build, run, test) then I don't see what benefit "data" provides. It seems counterintuitive to me since Bazel is *also* about build/test/download avoidance.

A build can be fully reproducible and correct without its runtime dependencies, or?

**Comment by digit-google** [comment] 2022-07-04 17:49
The distinction is that "data" dependencies are needed for `bazel run` and `bazel test`, but not for `bazel build`.

However, all three operations require constructing the full build dependency graph (during the load phase) to ensure 100% correctness of their results.

**Comment by Wyverald** [comment] 2022-07-05 09:51
Let me phrase it this way -- if you want something to be available at runtime but don't want it to be part of the build graph at all, then why introduce it using Bazel? You can use whatever library to download and materialize stuff at runtime. Why use a part of Bazel, a _build_ tool which happens to be able to fetch resources for _building_, for this use case?

**Comment by carlosgalvezp** [comment] 2022-07-05 10:05
> Why use a part of Bazel, a build tool
Well, Bazel is not _just_ a build tool. Bazel has commands "run" and "test", right? As a user, I expect Bazel to have custom implementations for "run" and "test" that are different / more appropriate / more optimized than for "build", in particular when it comes to handling runtime data dependencies.

Besides, as I said above, cc_library exposes the specific "data" argument, and the docs state that it's specifically designed for "runtime" dependencies. So, as a user, this tells me that Bazel makes some distinction about "build-time" vs "runtime" dependencies, since it has special constructs for it. 

The same goes for the "aspects" documentation that I linked before. The picture literally displays how Bazel is smart enough to not consider the runtime dependencies into the aspect graph.

Bazel is also marketed as "One tool, multiple languages" for "build and test". Not just "build". "build and test". 

But yes, I understand that the dependency fetching is happening at an earlier stage, before Bazel can even decide what dependencies are used where. I just want to mention that this is very unintuitive from a user perspective. If I set up a cc_test with data, I only expect this data to be fetched if I intend to run the test. If I just want to build the test, data is not needed. Bazel should not be concerned with how users run binaries outside Bazel, IMHO.

**Comment by carlosgalvezp** [comment] 2022-07-06 10:49
> you're asking build to be "smarter", no?

Yes, correct!

> How do you propose that should be achieved?

Disclaimer: I don't know anything of the internals of Bazel so the following might be very silly / impossible to implement :) 

My general understanding of Bazel is that it first creates an action graph of all the actions needed to build a target. Once the graph is created, it checks what actions are cached and which ones need to run. Finally, all results are put together into a final output.

My proposal would be that the "build" action does _not_ take into account the "data" edges when building the action graph. The "run"/"test" action would take them into account.

Then we have the use case of users who want to build with Bazel and run outside Bazel. Could the distinction between "deps" and "data" help here?

- "deps": dependencies will be fetched on all actions ("build",  "run", "test"). This allows users to run outside Bazel.
- "data": dependencies will be fetched only in "run" and "test" actions. This is for users who want to run inside Bazel.

I fully agree that no parts of Bazel should be linked into the final binaries for the purpose of finding/fetching the data dependencies.

**Comment by jrajahalme** [comment] 2023-02-12 01:14
+1 for re-opening this. Bazel should at the minimum provide a command line option to ignore data dependencies at the build time, and then make sure at `bazel run` and `bazel test` that also data dependencies are fetched.

**Closed** 2023-02-12 04:57 UTC
Labels: type: support / not a bug (process), team-ExternalDeps

**Comment by fmeum** [comment] 2023-04-03 12:53
As [another user remarked on Slack](https://bazelbuild.slack.com/archives/CA31HN1T3/p1680523964282819?thread_ts=1680521925.895909&cid=CA31HN1T3), you can achieve this behavior without any changes to Bazel itself:

```starlark
# .bazelrc

run --//:download_test_data
test --//:download_test_data

# BUILD.bazel 

load("@bazel_skylib//rules:common_settings.bzl", "bool_flag")

bool_flag(
    name = "download_test_data",
    build_setting_default = False,
)

config_setting(
    name = "should_download_test_data",
    flag_values = {":download_test_data": "True"},
)

sh_test(
    name = "my_test",
    srcs = ["my_test.sh"],
    data = select({
        "//:should_download_test_data": ["@testdata//:data.txt"],
        "//conditions:default": [],
    })
)

```

`bazel build //:my_test` will not cause `@testdata` to be fetched, but `bazel test` and `bazel run` will.

**Comment by carlosgalvezp** [comment] 2023-04-03 12:57
Good idea! Unfortunately it's not very intuitive and requires all developers to get acquainted with a non-standard usage that cannot be googled up, so there's still high risk that someone forgets and just does the natural, most straightforward thing which is add the dependencies directly. Unless you wrap all bazel rules into custom rules that do it for you, of course.

**Comment by fmeum** [comment] 2023-04-03 13:07
> Good idea! Unfortunately it's not very intuitive and requires all developers to get acquainted with a non-standard usage that cannot be googled up, so there's still high risk that someone forgets and just does the natural, most straightforward thing which is add the dependencies directly. Unless you wrap all bazel rules into custom rules that do it for you, of course.

You can always just run `bazel query` in CI to guard against buildtime deps on `@testdata`.

**Comment by fmeum** [comment] 2023-04-03 13:32
> I still haven't heard a convincing reason that data dependencies should be pulled at build time. 

You have to choose one of:
1) `bazel build //:my-target` doesn't fetch pure data dependencies.
2) After having run `bazel build //:my-target`, you can freely run, copy, deploy, package, etc. the build outputs of `//:my-target` anywhere (outside Bazel's control), knowing that they are always complete and up-to-date. 

You can't have both and Bazel just happens to be very firmly in the second camp by design. I personally find 2) much more useful than 1) in general, especially knowing that 1) can still be realized using standard techniques (select and custom build settings).
