### ISSUE TITLE
sha256 sum for bazel_nojdk for 5767cba4044c2bfd8a4c9596c44d2363630b489d

### ISSUE THREAD

**Issue by c-parsons** [bazelbuild/bazel#16129] opened 2022-08-18 20:48 UTC
Similarly to https://github.com/bazelbuild/bazel/issues/15582 , I have noticed that the most recent Bazel [prerelease commit](https://storage.googleapis.com/bazel-builds/metadata/5767cba4044c2bfd8a4c9596c44d2363630b489d.json) does not match its checksums.

**Comment by c-parsons** [comment] 2022-08-18 21:03
For what it's worth the last full release (5.2.0) and it's associated baseline 8d66a4171baddcbe1569972f019e54130111202c are both fine (sha256 sum matches).

**Comment by meteorcloudy** [comment] 2022-08-23 12:42
Rerunning the pipeline fixed the pipeline, the info in https://storage.googleapis.com/bazel-builds/metadata/5767cba4044c2bfd8a4c9596c44d2363630b489d.json is correct now, but we can keep this open for now until we figure out what's the root cause of this problem.

**Comment by meteorcloudy** [comment] 2022-08-23 12:43
Moving this issue to the CI repo since this isn't a bazel bug.

**Closed by meteorcloudy** 2022-08-23 12:43 UTC
Labels: type: bug, team-OSS
