### ISSUE TITLE
Unhelpful RuntimeException when external dep matches name of binding actual instead of binding name

### ISSUE THREAD

**Issue by dnoe** [bazelbuild/bazel#2776] opened 2017-04-03 20:56 UTC
### Description of the problem / feature request / question:

I've already solved this issue, it was due to user error on my part.  However, the error message provided by bazel was pretty unhelpful and could use improvement.

The cause of the issue was that I had referenced an external dependency that was defined in the WORKSPACE file.  However, instead of referencing it using the name in the bind statement I referenced it using the actual part of the bind name.  Interestingly if I reference a completely random external dependency name in the BUILD file I see a nice friendly error message instead.  This ugly error message seems to happen when the reference matches some other bit of information in the Bazel build configuration.

For example, WORKSPACE contains:
```
bind(
    name = "ssl",
    actual = "@boringssl//:ssl",
)
```
The build file accidentally referenced "boringssl" instead of "ssl" as external dependency resulting in this confusing error message.
```
Unhandled exception thrown during build; message: Unrecoverable error while evaluating node 'CONFIGURED_TARGET://source/common/common:assert_lib d64cd73bf4ac0c54b5469622b60c3080 (58363043 1285029092)' (requested by nodes 'CONFIGURED_TARGET://source/common/event:dispatcher_lib d64cd73bf4ac0c54b5469622b60c3080 (1786256133 1285029092)', 'CONFIGURED_TARGET://source/common/event:libevent_lib d64cd73bf4ac0c54b5469622b60c3080 (162760994 1285029092)', 'CONFIGURED_TARGET://source/common/network:connection_lib d64cd73bf4ac0c54b5469622b60c3080 (1597273262 1285029092)', 'CONFIGURED_TARGET://source/common/network:dns_lib d64cd73bf4ac0c54b5469622b60c3080 (1967058046 1285029092)', 'CONFIGURED_TARGET://source/common/network:filter_manager_lib d64cd73bf4ac0c54b5469622b60c3080 (104685281 1285029092)', 'CONFIGURED_TARGET://source/common/common:linked_object d64cd73bf4ac0c54b5469622b60c3080 (324152733 1285029092)', 'CONFIGURED_TARGET://source/common/network:address_lib d64cd73bf4ac0c54b5469622b60c3080 (1866447453 1285029092)', 'CONFIGURED_TARGET://source/common/network:utility_lib d64cd73bf4ac0c54b5469622b60c3080 (1835067096 1285029092)', 'CONFIGURED_TARGET://source/common/network:listen_socket_lib d64cd73bf4ac0c54b5469622b60c3080 (29779907 1285029092)', ...)
INFO: Elapsed time: 0.849s
java.lang.RuntimeException: Unrecoverable error while evaluating node 'CONFIGURED_TARGET://source/common/common:assert_lib d64cd73bf4ac0c54b5469622b60c3080 (58363043 1285029092)' (requested by nodes 'CONFIGURED_TARGET://source/common/event:dispatcher_lib d64cd73bf4ac0c54b5469622b60c3080 (1786256133 1285029092)', 'CONFIGURED_TARGET://source/common/event:libevent_lib d64cd73bf4ac0c54b5469622b60c3080 (162760994 1285029092)', 'CONFIGURED_TARGET://source/common/network:connection_lib d64cd73bf4ac0c54b5469622b60c3080 (1597273262 1285029092)', 'CONFIGURED_TARGET://source/common/network:dns_lib d64cd73bf4ac0c54b5469622b60c3080 (1967058046 1285029092)', 'CONFIGURED_TARGET://source/common/network:filter_manager_lib d64cd73bf4ac0c54b5469622b60c3080 (104685281 1285029092)', 'CONFIGURED_TARGET://source/common/common:linked_object d64cd73bf4ac0c54b5469622b60c3080 (324152733 1285029092)', 'CONFIGURED_TARGET://source/common/network:address_lib d64cd73bf4ac0c54b5469622b60c3080 (1866447453 1285029092)', 'CONFIGURED_TARGET://source/common/network:utility_lib d64cd73bf4ac0c54b5469622b60c3080 (1835067096 1285029092)', 'CONFIGURED_TARGET://source/common/network:listen_socket_lib d64cd73bf4ac0c54b5469622b60c3080 (29779907 1285029092)', ...)
	at com.google.devtools.build.skyframe.ParallelEvaluator$Evaluate.run(ParallelEvaluator.java:448)
	at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:501)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: No such attribute testonly in rule backward_git
	at com.google.devtools.build.lib.packages.AbstractAttributeMapper.getIndexWithTypeCheck(AbstractAttributeMapper.java:229)
	at com.google.devtools.build.lib.packages.AbstractAttributeMapper.get(AbstractAttributeMapper.java:57)
	at com.google.devtools.build.lib.packages.NonconfigurableAttributeMapper.get(NonconfigurableAttributeMapper.java:45)
	at com.google.devtools.build.lib.bazel.rules.BazelRuleClassProvider$BazelPrerequisiteValidator.isTestOnlyRule(BazelRuleClassProvider.java:267)
	at com.google.devtools.build.lib.bazel.rules.BazelRuleClassProvider$BazelPrerequisiteValidator.validateDirectPrerequisiteForTestOnly(BazelRuleClassProvider.java:253)
	at com.google.devtools.build.lib.bazel.rules.BazelRuleClassProvider$BazelPrerequisiteValidator.validate(BazelRuleClassProvider.java:197)
	at com.google.devtools.build.lib.analysis.RuleContext$Builder.validateDirectPrerequisite(RuleContext.java:1953)
	at com.google.devtools.build.lib.analysis.RuleContext$Builder.createTargetMap(RuleContext.java:1625)
	at com.google.devtools.build.lib.analysis.RuleContext$Builder.build(RuleContext.java:1464)
	at com.google.devtools.build.lib.analysis.ConfiguredTargetFactory.createRule(ConfiguredTargetFactory.java:246)
	at com.google.devtools.build.lib.analysis.ConfiguredTargetFactory.createConfiguredTarget(ConfiguredTargetFactory.java:177)
	at com.google.devtools.build.lib.skyframe.SkyframeBuildView.createConfiguredTarget(SkyframeBuildView.java:487)
	at com.google.devtools.build.lib.skyframe.ConfiguredTargetFunction.createConfiguredTarget(ConfiguredTargetFunction.java:1109)
	at com.google.devtools.build.lib.skyframe.ConfiguredTargetFunction.compute(ConfiguredTargetFunction.java:254)
	at com.google.devtools.build.skyframe.ParallelEvaluator$Evaluate.run(ParallelEvaluator.java:374)
	... 4 more
java.lang.RuntimeException: Unrecoverable error while evaluating node 'CONFIGURED_TARGET://source/common/common:assert_lib d64cd73bf4ac0c54b5469622b60c3080 (58363043 1285029092)' (requested by nodes 'CONFIGURED_TARGET://source/common/event:dispatcher_lib d64cd73bf4ac0c54b5469622b60c3080 (1786256133 1285029092)', 'CONFIGURED_TARGET://source/common/event:libevent_lib d64cd73bf4ac0c54b5469622b60c3080 (162760994 1285029092)', 'CONFIGURED_TARGET://source/common/network:connection_lib d64cd73bf4ac0c54b5469622b60c3080 (1597273262 1285029092)', 'CONFIGURED_TARGET://source/common/network:dns_lib d64cd73bf4ac0c54b5469622b60c3080 (1967058046 1285029092)', 'CONFIGURED_TARGET://source/common/network:filter_manager_lib d64cd73bf4ac0c54b5469622b60c3080 (104685281 1285029092)', 'CONFIGURED_TARGET://source/common/common:linked_object d64cd73bf4ac0c54b5469622b60c3080 (324152733 1285029092)', 'CONFIGURED_TARGET://source/common/network:address_lib d64cd73bf4ac0c54b5469622b60c3080 (1866447453 1285029092)', 'CONFIGURED_TARGET://source/common/network:utility_lib d64cd73bf4ac0c54b5469622b60c3080 (1835067096 1285029092)', 'CONFIGURED_TARGET://source/common/network:listen_socket_lib d64cd73bf4ac0c54b5469622b60c3080 (29779907 1285029092)', ...)
	at com.google.devtools.build.skyframe.ParallelEvaluator$Evaluate.run(ParallelEvaluator.java:448)
	at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:501)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: No such attribute testonly in rule backward_git
	at com.google.devtools.build.lib.packages.AbstractAttributeMapper.getIndexWithTypeCheck(AbstractAttributeMapper.java:229)
	at com.google.devtools.build.lib.packages.AbstractAttributeMapper.get(AbstractAttributeMapper.java:57)
	at com.google.devtools.build.lib.packages.NonconfigurableAttributeMapper.get(NonconfigurableAttributeMapper.java:45)
	at com.google.devtools.build.lib.bazel.rules.BazelRuleClassProvider$BazelPrerequisiteValidator.isTestOnlyRule(BazelRuleClassProvider.java:267)
	at com.google.devtools.build.lib.bazel.rules.BazelRuleClassProvider$BazelPrerequisiteValidator.validateDirectPrerequisiteForTestOnly(BazelRuleClassProvider.java:253)
	at com.google.devtools.build.lib.bazel.rules.BazelRuleClassProvider$BazelPrerequisiteValidator.validate(BazelRuleClassProvider.java:197)
	at com.google.devtools.build.lib.analysis.RuleContext$Builder.validateDirectPrerequisite(RuleContext.java:1953)
	at com.google.devtools.build.lib.analysis.RuleContext$Builder.createTargetMap(RuleContext.java:1625)
	at com.google.devtools.build.lib.analysis.RuleContext$Builder.build(RuleContext.java:1464)
	at com.google.devtools.build.lib.analysis.ConfiguredTargetFactory.createRule(ConfiguredTargetFactory.java:246)
	at com.google.devtools.build.lib.analysis.ConfiguredTargetFactory.createConfiguredTarget(ConfiguredTargetFactory.java:177)
	at com.google.devtools.build.lib.skyframe.SkyframeBuildView.createConfiguredTarget(SkyframeBuildView.java:487)
	at com.google.devtools.build.lib.skyframe.ConfiguredTargetFunction.createConfiguredTarget(ConfiguredTargetFunction.java:1109)
	at com.google.devtools.build.lib.skyframe.ConfiguredTargetFunction.compute(ConfiguredTargetFunction.java:254)
	at com.google.devtools.build.skyframe.ParallelEvaluator$Evaluate.run(ParallelEvaluator.java:374)
	... 4 more
```

### If possible, provide a minimal example to reproduce the problem:

Setup a WORKSPACE file with some external dependency and reference it in a BUILD file incorrectly using the actual name, not the bound name.

### Environment info
* Operating System:

Ubuntu (goobuntu/gLinux)

* Bazel version (output of `bazel info release`):

release 0.4.5

**Comment by buchgr** [comment] 2017-04-10 08:46
@dnoe I edited your issue by adding codeblocks around code and error messages for better readability.

@damienmg can you take a look please?

**Comment by damienmg** [comment] 2017-04-10 10:50
Maybe we should just make sure that repository rules are not target of the external package. Reducing the external package as only the bind statement.

Then we can have the follow-up to delete the external package and bind.

CC @kchodorow

**Comment by dnoe** [comment] 2017-04-10 14:46
Thanks for the formatting update - I'm new to GH issues.

I noticed just that the stack trace I gave you was actually from a different external dependency not boringssl but that shouldn't be important for the bug.

**Comment by kchodorow** [comment] 2017-04-10 15:10
Making repository rules non-targets is a bigger change, but we can certainly fix it so it doesn't print a stack trace.

**Comment by dslomov** [comment] 2018-01-15 12:28
Duplicate of https://github.com/bazelbuild/bazel/issues/3676 (yes the latter came later, but the fix for it is already in the pipeline)

**Closed by dslomov** 2018-01-15 12:28 UTC
Labels: P1, category: extensibility > external repositories, external-repos-triaged, type: bug
