### ISSUE TITLE
<nightly:bazel-tests> //src/test/java/com/google/devtools/build/lib:standalone-tests failed on macOS

### ISSUE THREAD

**Issue by damienmg** [bazelbuild/bazel#3795] opened 2017-09-22 13:53 UTC
[Error](http://ci.bazel.io/view/Bazel%20bootstrap%20and%20maintenance/job/Global/job/bazel-tests/263/artifact/tests-node=darwin-x86_64/src/test/java/com/google/devtools/build/lib/standalone-tests/test.log/*view*/)
```
1) testCommandHonorsEnvironment(com.google.devtools.build.lib.standalone.StandaloneSpawnStrategyTest)
java.lang.AssertionError: Not true that <[__CF_USER_TEXT_ENCODING=0x1F5:0x0:0x0, foo=bar, baz=boo]> is equal to <[baz=boo, foo=bar]>
	at com.google.devtools.build.lib.standalone.StandaloneSpawnStrategyTest.testCommandHonorsEnvironment(StandaloneSpawnStrategyTest.java:228)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.junit.runners.Suite.runChild(Suite.java:127)
	at org.junit.runners.Suite.runChild(Suite.java:26)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at com.google.testing.junit.runner.internal.junit4.CancellableRequestFactory$CancellableRunner.run(CancellableRequestFactory.java:89)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:160)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:138)
	at com.google.testing.junit.runner.junit4.JUnit4Runner.run(JUnit4Runner.java:112)
	at com.google.testing.junit.runner.BazelTestRunner.runTestsInSuite(BazelTestRunner.java:144)
	at com.google.testing.junit.runner.BazelTestRunner.main(BazelTestRunner.java:82)
Caused by: java.lang.AssertionError: Not true that <[__CF_USER_TEXT_ENCODING=0x1F5:0x0:0x0, foo=bar, baz=boo]> is equal to <[baz=boo, foo=bar]>
	at com.google.common.truth.FailureStrategy.fail(FailureStrategy.java:28)
	at com.google.common.truth.FailureStrategy.fail(FailureStrategy.java:22)
	at com.google.common.truth.Subject.failComparingToStrings(Subject.java:348)
	at com.google.common.truth.Subject.doEqualCheck(Subject.java:127)
	at com.google.common.truth.Subject.isEqualTo(Subject.java:104)
	... 33 more

FAILURES!!!
Tests run: 44,  Failures: 1
```

**Comment by ulfjack** [comment] 2017-09-25 09:40
Unable to reproduce, and I can't see the bazel command that ran that test.

**Comment by damienmg** [comment] 2017-09-25 09:42
With build bazel at HEAD?

**Comment by damienmg** [comment] 2017-09-25 09:43
http://ci.bazel.io/blue/rest/organizations/jenkins/pipelines/Global/pipelines/bazel-tests/runs/263/nodes/30/steps/451/log/?start=0 is the log of the test run.

**Comment by ulfjack** [comment] 2017-09-25 09:44
Closing, because I have no idea where you got that error from and the link you posted is not useful.

**Comment by ulfjack** [comment] 2017-09-25 09:44
bazel-tests is green at head?

**Comment by damienmg** [comment] 2017-09-25 09:45
Erm?

**Comment by ulfjack** [comment] 2017-09-25 09:47
Reopening with "Erm?" is not useful. I still don't know what you're talking about.

**Comment by ulfjack** [comment] 2017-09-25 09:47
http://ci.bazel.io/blue/organizations/jenkins/bazel-tests/detail/bazel-tests/1052/pipeline all green.

**Comment by ulfjack** [comment] 2017-09-25 09:51
http://ci.bazel.io/blue/organizations/jenkins/Global%2Fbazel-tests/detail/bazel-tests/271/pipeline/30 is yellow (although I don't understand why, since parts of it are red), and the page does not seem to have a single link that goes anywhere useful.

**Comment by ulfjack** [comment] 2017-09-25 09:57
Maybe you meant to post this?
http://ci.bazel.io/blue/organizations/jenkins/Global%2Fbazel-tests/detail/bazel-tests/271/tests

**Comment by damienmg** [comment] 2017-09-25 10:44
http://ci.bazel.io/blue/rest/organizations/jenkins/pipelines/Global/pipelines/bazel-tests/runs/263/nodes/30/steps/451/log/?start=0 contains the full execution log of bazel on macOS. The test log at the top of the bug was indeed taken from http://ci.bazel.io/blue/organizations/jenkins/Global%2Fbazel-tests/detail/bazel-tests/271 

The coloring of the steps are unfortunate, see https://issues.jenkins-ci.org/browse/JENKINS-39203 for the why. We use red to mark the step that has test failure (yellow means test failure). 

The Global/bazel-tests was executed by the nightly (as stated in the title of the bug). So using Bazel @ 5d41dbea25c6c9e3776516c7aa3598b8c153a410 (from http://ci.bazel.io/job/bazel/job/nightly/62/, there is the name of the upstream job around in the log).

it is known that there is issue with the UI, I'll be glad to prioritize that work but you know...

**Comment by damienmg** [comment] 2017-09-25 10:47
(and since it happened in all the nightlies since that one this means it is not a flake)

**Comment by ulfjack** [comment] 2017-09-25 10:58
Ok. But you need to provide more context when you file such bugs. Otherwise the assignee ends up spending a couple hours trying to navigate the Jenkins UI, like I did today. :-(

**Comment by damienmg** [comment] 2017-09-25 10:59
Indeed ideally we would have something that would create automatically bug with all the good info but when triaging the issues it can be hard to extract all that information :(

**Comment by ulfjack** [comment] 2017-09-25 11:07
What's the content of this file?
/Users/ci/workspace/Global/bazel-tests-node=darwin-x86_64/bazel.bazelrc

**Comment by ulfjack** [comment] 2017-09-25 11:08
What's the content of this file?
/private/var/tmp/_bazel_ci/14a274db1e6628a41b59a0d9bb823350/execroot/io_bazel/bazel-out/darwin_x86_64-fastbuild/testlogs/src/test/java/com/google/devtools/build/lib/standalone-tests/test.log

**Comment by ulfjack** [comment] 2017-09-25 11:12
Gah, Bazel doesn't have the debug info that we output in Blaze.

**Comment by ulfjack** [comment] 2017-09-25 11:14
I am still unable to reproduce on my Mac.

**Comment by ulfjack** [comment] 2017-09-25 11:46
Looking at the command-line (http://ci.bazel.io/blue/organizations/jenkins/Global%2Fbazel-tests/detail/bazel-tests/263/artifacts -> bazel-events-test.json), there's nothing obviously affecting it.

**Closed** 2018-03-21 17:11 UTC
Labels: P2, platform: other
