### ISSUE TITLE
rules_cc failing with Bazel 2.1 rc

### ISSUE THREAD

**Issue by laurentlb** [bazelbuild/bazel#10698] opened 2020-02-03 15:56 UTC
https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/1373#1a828ce2-6430-4a4b-acb0-fd1e58b02de7

```
(08:56:38) ERROR: /var/lib/buildkite-agent/builds/bk-docker-f-jdql/bazel-downstream-projects/rules_cc/examples/test_cc_shared_library/BUILD:4:1: //examples/test_cc_shared_library:cc_test: no such attribute 'dynamic_deps' in 'cc_test' rule
```

cc @meteorcloudy, @c-parsons, @oquenchil

**Comment by meteorcloudy** [comment] 2020-02-04 09:59
I'll help take a look

**Comment by meteorcloudy** [comment] 2020-02-04 10:29
The breakage is caused by https://github.com/bazelbuild/rules_cc/commit/8774a4decd63f45a636f40a75700c06b7ea9d30a

It doesn't look like a Bazel bug, the tests are supposed to run with Bazel@last_green
See https://github.com/bazelbuild/rules_cc/blob/master/.bazelci/presubmit.yml#L51

This should not be a release blocker.

**Comment by oquenchil** [comment] 2020-02-04 15:30
That's the case. Those tests are meant to run with Bazel at head only.

**Comment by laurentlb** [comment] 2020-02-06 13:29
It shows up as red on the CI, so we have to do something about it.

**Comment by oquenchil** [comment] 2020-02-06 13:34
Why is CI trying to run that test with Bazel 2.1 rc?

Our presubmit.yml excludes it:https://github.com/bazelbuild/rules_cc/blob/master/.bazelci/presubmit.yml

**Comment by laurentlb** [comment] 2020-02-06 13:36
Do you know, @meteorcloudy?

**Comment by meteorcloudy** [comment] 2020-02-06 13:47
I think @fweikert implemented the feature to skip task that suppose to run with a certain Bazel version for downstream. Do you have any idea?

**Comment by philwo** [comment] 2020-03-03 09:18
Reassigned to @fweikert to figure out why we run a test with latest_green Bazel in our downstream pipeline.

**Closed** 2020-11-19 18:14 UTC
Labels: P2, area-EngProd, team-XProduct
