### ISSUE TITLE
--test_summary=broken

### ISSUE THREAD

**Issue by hanwen** [bazelbuild/bazel#1321] opened 2016-05-30 11:58 UTC
I see that Bazel now creates XML test logs, but the test_summary flag seems broken:

$ git show HEAD
commit 4ab4f05a8cbbaa4b7d938d1d305961fe95a5416c
Author: Googler <noreply@google.com>
Date:   Fri May 27 23:47:15 2016 +0000

    Roll forward commit 8375185ee11d573562f98de14bed79a77fcfd728.
    Consider /src/ in the path when locating the java root directory.
    
    --
    MOS_MIGRATED_REVID=123469898

$ bazel test --test_summary=detailed src/test/...
WARNING: /usr/local/google/home/hanwen/vc/bazel/src/main/native/BUILD:46:16: in includes attribute of cc_binary rule //src/main/native:libunix.so: '.' resolves to 'src/main/native' not in 'third_party'. This will be an error in the future.
WARNING: /usr/local/google/home/hanwen/vc/bazel/src/main/protobuf/BUILD:36:1: in includes attribute of cc_library rule //src/main/protobuf:command_server_cc_proto: '.' resolves to 'src/main/protobuf' not in 'third_party'. This will be an error in the future. Since this rule was created by the macro 'cc_grpc_library', the error might have been caused by the macro implementation in /usr/local/google/home/hanwen/vc/bazel/tools/build_rules/genproto.bzl:104:18.
INFO: Found 24 targets and 80 test targets...
PASS: //src/test/shell/bazel:bound_targets_test
INFO: Elapsed time: 317.939s, Critical Path: 317.57s

Executed 80 out of 80 tests: 80 tests pass.
There were tests whose specified size is too big. Use the --test_verbose_timeout_warnings command line option to see which ones these are.

$ bazel version
Build label: 0.2.3
Build target: bazel-out/local-fastbuild/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Tue May 17 14:21:13 2016 (1463494873)
Build timestamp: 1463494873
Build timestamp as int: 1463494873

**Comment by hanwen** [comment] 2016-05-30 13:56
looks like the XML is parsed correctly. So why isn't it displaying?

$ strings bazel-testlogs/src/test/java/com/google/devtools/common/options/options_test/test.cache_status |tail
.com.google.devtools.common.options.OptionsTest 
boolean0
.com.google.devtools.common.options.OptionsTest 
boolean1

**Comment by dslomov** [comment] 2016-05-30 15:26
@damienmg could you take a look?

**Comment by damienmg** [comment] 2016-05-30 15:37
The JUnit Runner is outputting ant XML output format. We should support that format on all our runner instead of the internal XML format.

The TestStrategy is expected the other XML format, therefore not parsing it correctly.

**Comment by hanwen** [comment] 2016-05-30 15:42
the XML is not the problem. It's parsed fine,

gqui from bazel-testlogs/src/test/java/com/google/devtools/common/options/options_test/test.cache_status  proto blaze.TestResultData  

yields:

{       # (blaze.TestResultData) size=12.7K
  cachable   : true
  test_passed: true
  status     : PASSED   # integer=1 (enum blaze.BlazeTestStatus)
  test_times : [ 1871 ]
  passed_log : "/usr/local/google/home/hanwen/.cache/bazel/_bazel_hanwen/7bbbccf291cbb46fe61f91134f51d65d/bazel/bazel-out/local-fastbuild/testlogs/src/test/java/com/google/devtools/common/options/options_test/test.log"      # size=201; fp64=df71bd6f8eb76cd6; fp2011=08fe933c94aa048b
  run_duration_millis: 1871     # [as milliseconds]: 1 second 871 msecs
  test_case: {  # (blaze.TestCase) size=12.5K
    child: {    # (blaze.TestCase) size=52B
      name      : "com.google.devtools.common.options.AllTests" # size=43
      run_duration_millis: 369
      type      : TEST_SUITE    # integer=1 (enum blaze.TestCase.Type)
      status    : PASSED        # integer=0 (enum blaze.TestCase.Status)
    }   # test_case.child[0]
    child: {    # (blaze.TestCase) size=555B
      child: {  # (blaze.TestCase) size=113B
        name      : "missingValue"      # size=12
        class_name: "com.google.devtools.common.options.AssignmentConverterTest$MandatoryAssignmentConverterTest"       # size=91; fp64=3ac2fc190bf8dec2; fp2011=eeea205b50494ec7
        run_duration_millis: 87
        type      : TEST_CASE   # integer=0 (enum blaze.TestCase.Type)
        status    : PASSED      # integer=0 (enum blaze.TestCase.Status)
      } # test_case.child[1].child[0]

**Comment by damienmg** [comment] 2016-05-31 10:55
Oh yes you are right.

I can reproduce, but I have no idea what is going wrong. Did that ever worked on Bazel?

**Comment by hanwen** [comment] 2016-05-31 11:49
maybe PEBKAC.  I think it should only print the failing cases. Let me investigate.

**Comment by damienmg** [comment] 2016-05-31 13:54
Indeed, I tested it with the internal version and it outputs only the failed one. Closing as WAI

**Comment by hanwen** [comment] 2016-05-31 13:56
not quite closed completely.  Looks like there's no test. I'll cook one up.

**Comment by hanwen** [comment] 2016-06-01 15:41
looks like the content of the XML is a bit fubar still (is this the JUnit thing you were alluding to earlier?)

The XML doesn't mention testFail, so something is broken. Are the examples properly wired up with the new-fangled JUnit runner?


$ bazel test --test_summary=detailed examples/java-native/src/test/java/com/example/myproject:fail
..
/examples/java-native/src/test/java/com/example/myproject:fail          FAILED in 0.2s
    ERROR   .examples/java-native/src/test/java/com/example/myproject/fail

$ p bazel-testlogs/examples/java-native/src/test/java/com/example/myproject/fail/test.xml 
<?xml version="1.0" encoding="UTF-8"?>
<testsuites>
  <testsuite name="examples/java-native/src/test/java/com/example/myproject/fail" tests="1" failures="0" errors="1">
    <testcase name="examples/java-native/src/test/java/com/example/myproject/fail" status="run"><error message="exited with error code 2"></error></testcase>
  </testsuite>
</testsuites>

**Comment by damienmg** [comment] 2016-06-02 08:02
```
[dmarting@trantor git bazel (master)] $ bazel test --test_summary=detailed examples/java-native/src/test/java/com/example/myproject:fail
..
INFO: Found 1 test target...
FAIL: //examples/java-native/src/test/java/com/example/myproject:fail (see /usr/local/google/home/dmarting/.cache/bazel/_bazel_dmarting/801f5d89037be0fd22631beaaf1a3550/bazel/bazel-out/local-fastbuild/testlogs/examples/java-native/src/test/java/com/example/myproject/fail/test.log).
Target //examples/java-native/src/test/java/com/example/myproject:fail up-to-date:
  bazel-bin/examples/java-native/src/test/java/com/example/myproject/fail.jar
  bazel-bin/examples/java-native/src/test/java/com/example/myproject/fail
INFO: Elapsed time: 13.217s, Critical Path: 5.65s
//examples/java-native/src/test/java/com/example/myproject:fail          FAILED in 1.2s
    ERROR   .examples/java-native/src/test/java/com/example/myproject/fail

Executed 1 out of 1 tests: 1 fails locally.
[dmarting@trantor git bazel (master)] $ cat bazel-testlogs/examples/java-native/src/test/java/com/example/myproject/fail/test.xml 
<?xml version="1.0" encoding="UTF-8"?>
<testsuites>
  <testsuite name="examples/java-native/src/test/java/com/example/myproject/fail" tests="1" failures="0" errors="1">
    <testcase name="examples/java-native/src/test/java/com/example/myproject/fail" status="run"><error message="exited with error code 2"></error></testcase>
  </testsuite>
</testsuites>
[dmarting@trantor git bazel (master)] $ bazel version
Build label: 0.2.3
Build target: bazel-out/local-fastbuild/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Tue May 17 14:21:13 2016 (1463494873)
Build timestamp: 1463494873
Build timestamp as int: 1463494873
```

On my machine the XML is correct. Which version of Bazel are you using?

**Comment by hanwen** [comment] 2016-06-02 09:31
the XML is syntactically correct, but inside google, you the testcase would be called

  com.example.myproject.Fail

and there would be an entry for the failing test method (testFail in this case)

**Comment by damienmg** [comment] 2016-06-02 09:36
right that should be like you said. let me look at the code.

**Comment by damienmg** [comment] 2016-06-02 09:53
The issue is that the test is wrong:

```
[dmarting@trantor git bazel (master)] $ bazel test --test_summary=detailed examples/java-native/src/test/java/com/example/myproject:fail
Sending SIGTERM to previous Bazel server (pid=21040)... done.
..
INFO: Found 1 test target...
FAIL: //examples/java-native/src/test/java/com/example/myproject:fail
      /usr/local/google/home/dmarting/.cache/bazel/_bazel_dmarting/801f5d89037be0fd22631beaaf1a3550/bazel/bazel-out/local-fastbuild/testlogs/examples/java-native/src/test/java/com/example/myproject/fail/test.log

Target //examples/java-native/src/test/java/com/example/myproject:fail up-to-date:

  bazel-bin/examples/java-native/src/test/java/com/example/myproject/fail.jar

  bazel-bin/examples/java-native/src/test/java/com/example/myproject/fail

INFO: Elapsed time: 11.723s, Critical Path: 4.64s
INFO: Build completed successfully, 8 total actions
//examples/java-native/src/test/java/com/example/myproject:fail          FAILED in 0.8s
    FAILED  com.example.myproject.Fail.testFail (0.0s)

Executed 1 out of 1 tests: 1 fails locally.
[dmarting@trantor git bazel (master)] $ git diff examples/java-native/src/test/java/com/example/myproject/BUILD 
diff --git a/examples/java-native/src/test/java/com/example/myproject/BUILD b/examples/java-native/src/test/java/com/example/myproject/BUILD
index f3a262d..7691f27 100644
--- a/examples/java-native/src/test/java/com/example/myproject/BUILD
+++ b/examples/java-native/src/test/java/com/example/myproject/BUILD
@@ -30,6 +30,7 @@ java_test(
 
 java_test(
     name = "fail",
+    test_class = "com.example.myproject.Fail",
     srcs = ["Fail.java"],
     deps = ["//third_party:junit4"],
 )
[dmarting@trantor git bazel (master)] $ cat bazel-testlogs/examples/java-native/src/test/java/com/example/myproject/fail/test.xml 
<?xml version='1.0' encoding='UTF-8'?>
<testsuites>
  <testsuite name='com.example.myproject.Fail' timestamp='1970-03-22T00:36:34.641Z' hostname='localhost' tests='1' failures='1' errors='0' time='0.048' package='' id='0'>
    <properties />
    <testcase name='testFail' classname='com.example.myproject.Fail' time='0.048'>
      <failure message='This is an expected test failure.' type='java.lang.AssertionError'>java.lang.AssertionError: This is an expected test failure.
	at org.junit.Assert.fail(Assert.java:88)
	at com.example.myproject.Fail.testFail(Fail.java:12)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at com.google.testing.junit.runner.junit4.CancellableRequestFactory$CancellableRunner.run(CancellableRequestFactory.java:84)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:160)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:138)
	at com.google.testing.junit.runner.junit4.JUnit4Runner.run(JUnit4Runner.java:103)
	at com.google.testing.junit.runner.BazelTestRunner.runTestsInSuite(BazelTestRunner.java:149)
	at com.google.testing.junit.runner.BazelTestRunner.main(BazelTestRunner.java:90)

      </failure>
    </testcase>
    <system-out />
    <system-err />
  </testsuite>
</testsuites>
[dmarting@trantor git bazel (master)] $ git reset --hard
HEAD is now at 9bf2da4 Add a SpellChecker class with edit distance function.
[dmarting@trantor git bazel (master)] $ bazel test --test_output=errors examples/java-native/src/test/java/com/example/myproject:fail
INFO: Found 1 test target...
FAIL: //examples/java-native/src/test/java/com/example/myproject:fail
      /usr/local/google/home/dmarting/.cache/bazel/_bazel_dmarting/801f5d89037be0fd22631beaaf1a3550/bazel/bazel-out/local-fastbuild/testlogs/examples/java-native/src/test/java/com/example/myproject/fail/test.log

INFO: From Testing //examples/java-native/src/test/java/com/example/myproject:fail:
==================== Test output for //examples/java-native/src/test/java/com/example/myproject:fail:
Class not found: [com.example.myproject.fail]

BazelTestRunner exiting with a return value of 2
JVM shutdown hooks (if any) will run now.
The JVM will exit once they complete.

-- JVM shutdown starting at 2016-06-02 09:52:59 --

================================================================================

Target //examples/java-native/src/test/java/com/example/myproject:fail up-to-date:

  bazel-bin/examples/java-native/src/test/java/com/example/myproject/fail.jar

  bazel-bin/examples/java-native/src/test/java/com/example/myproject/fail

INFO: Elapsed time: 0.475s, Critical Path: 0.25s
INFO: Build completed successfully, 3 total actions
//examples/java-native/src/test/java/com/example/myproject:fail          FAILED in 0.2s
  /usr/local/google/home/dmarting/.cache/bazel/_bazel_dmarting/801f5d89037be0fd22631beaaf1a3550/bazel/bazel-out/local-fastbuild/testlogs/examples/java-native/src/test/java/com/example/myproject/fail/test.log

Executed 1 out of 1 tests: 1 fails locally.
```

**Comment by damienmg** [comment] 2016-06-14 18:26
This was fixed.

**Closed by damienmg** 2016-06-14 18:26 UTC
Labels: category: misc > testing, P2, type: bug
