### ISSUE TITLE
Visibility checks don't unify `//` and `@workspace_name//` when building in that workspace

### ISSUE THREAD

**Issue by jmillikin-stripe** [bazelbuild/bazel#4678] opened 2018-02-21 21:26 UTC
Forked from discussion in https://github.com/bazelbuild/bazel/pull/4435.

### Description of the problem / feature request:
When building in a workspace named `foo`, Bazel doesn't treat `@foo//something` and `//something` as the same for visibility checks. This is confusing, and prevents coordinating visibility between repositories (e.g. in Bazel's vendored third-party deps).

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

```python
# ./WORKSPACE
workspace(name="test_bazel_visibility")

# ./files_a/BUILD
filegroup(name="srcs", visibility=["@test_bazel_visibility//files_b:__pkg__"])

# ./files_b/BUILD
filegroup(name="srcs", srcs=["//files_a:srcs"])
```

```
$ bazel build //files_b:srcs
ERROR: /Users/jmillikin/src/bazel-visibility/files_b/BUILD:1:1: Target '//files_a:srcs' is not visible from target '//files_b:srcs'. Check the visibility declaration of the former target if you think the dependency is legitimate
ERROR: Analysis of target '//files_b:srcs' failed; build aborted: Analysis of target '//files_b:srcs' failed; build aborted
INFO: Elapsed time: 0.167s
FAILED: Build did NOT complete successfully (1 packages loaded)

$ bazel build @test_bazel_visibility//files_b:srcs
INFO: Analysed target @test_bazel_visibility//files_b:srcs (1 packages loaded).
INFO: Found 1 target...
Target @test_bazel_visibility//files_b:srcs up-to-date (nothing to build)
INFO: Elapsed time: 0.189s, Critical Path: 0.01s
INFO: Build completed successfully, 1 total action
```

### What operating system are you running Bazel on?

MacOS and Linux (x86-64).

### What's the output of `bazel info release`?
Linux: `release 0.10.0`
MacOS: `release 0.10.0-homebrew`

**Comment by aehlig** [comment] 2018-02-26 07:55
@dslomov for further triaging.

**Comment by dslomov** [comment] 2018-02-26 15:07
@dkelmer would you mind taking a look?

**Comment by philwo** [comment] 2018-03-28 13:37
Friendly ping @dkelmer

**Comment by dslomov** [comment] 2018-03-28 13:48
sorry for late reply: @dkelmer  and I took a look at this and realized that the easiest way to fix it would be in  the context of fixing diamond splits (https://docs.google.com/document/d/1254CQ8T4Rmeasg4NO1NPail2kLPC50VJ7Ok6JsoSe-c/), which is being worked on by @dkelmer (expanding on my prototype implementation https://bazel-review.googlesource.com/c/bazel/+/42172)

**Comment by dkelmer** [comment] 2018-07-19 20:44
This was fixed by https://github.com/bazelbuild/bazel/commit/3149beb6543c50f381f91f9645f2a4da43d20c0c

**Comment by dkelmer** [comment] 2018-07-19 20:45
Duplicate of https://github.com/bazelbuild/bazel/issues/3115

**Closed by dkelmer** 2018-07-19 20:44 UTC
Labels: P1, category: extensibility > skylark remote repositories
