### ISSUE TITLE
Fetch and build don't play well together

### ISSUE THREAD

**Issue by sustrik** [bazelbuild/bazel#7438] opened 2019-02-15 14:06 UTC
### Description of the problem / feature request:

Fetch and build don't play well together.

```
$ bazel fetch //:foo
$ bazel build //:foo --fetch=false
ERROR: While resolving toolchains for target //foo: invalid registered toolchain '@local_config_sh//:local_sh_toolchain': no such package '@local_config_sh//': to fix, run
	bazel fetch //...
```

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

I am running Bazel on a fairly big codebase. Is this a bug or feature? If it's a bug I'll try to come up with a minimal example.

### What operating system are you running Bazel on?

Linux

### What's the output of `bazel info release`?

release 0.22.0

###  Have you found anything relevant by searching the web?

No. In fact `bazel fetch` seems to have disappeared from the docs.

**Comment by sustrik** [comment] 2019-02-15 14:28
FWIW:

```
$ bazel query "somepath(//:foo, @local_config_sh//:local_sh_toolchain)"
INFO: Empty results
Loading: 0 packages loaded
```

**Comment by kormat** [comment] 2019-02-26 16:06
It looks like `bazel fetch` doesn't fetch implicit dependencies?

**Comment by dslomov** [comment] 2019-03-05 14:21
@aehlig could you take a look? it seems rather serious - looks like `fetch` does not support toolchain resolution? /cc @katre

**Comment by katre** [comment] 2019-03-05 15:57
Toolchain dependencies are only determines when a target is configured. This happens during "bazel cquery", for example, because it's a query on the configured target graph.

You absolutely do want to only fetch the actual used toolchains, not every possible toolchain. I don't know if it's possible to change "bazel fetch" to use the configured target graph (which also implies calling it with the same options you build with).

These is a related issue open, #3246.

**Comment by aehlig** [comment] 2019-03-05 17:21
> @aehlig could you take a look?

That is a bug/feature of `query`. The name `bazel fetch` is a bit of a misnomer, as [`bazel fetch` literally is a query](https://github.com/bazelbuild/bazel/blob/61c0b386e22da0f98160f70fd5584e6eb11f8d23/src/main/java/com/google/devtools/build/lib/bazel/commands/FetchCommand.java#L93) and never has been something else, since [`fetch` was added in 2015](https://github.com/bazelbuild/bazel/commit/da65629dde0b56462a45418cdbbc610e07c851a9#diff-57eb2e81c2a06dbb8b552b3f89292a91). I guess we can replace it by a different type of query, if there is an appropriate one.

**Comment by dslomov** [comment] 2019-03-11 00:21
Thanks @katre and @aehlig! Closing as duplicate of #3246

**Closed by dslomov** 2019-03-11 00:21 UTC
Labels: P1, team-ExternalDeps, type: bug
