### ISSUE TITLE
Ctrl+C / SIGINT on build actions should exit the same as build error?

### ISSUE THREAD

**Issue by EricCousineau-TRI** [bazelbuild/bazel#7880] opened 2019-03-28 18:01 UTC
### Description of the problem / feature request:

I always get confused that build errors seem to immediately kill other actions immediately, but Ctrl+C does not seem to do this (they all build to completion).

### Feature requests: what underlying problem are you trying to solve with this feature?

Is it possible to have Ctrl+C kill the other actions (safely) more quickly, without having to murder the server?

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

We have a large C++ project [[link](https://drake.mit.edu/)], with some build targets that (regrettably) take >45s to finish building.

If there's a build error, it appears that other actions are immediately terminated.

However, if I try to Ctrl+C the build process, it waits until the other objects have been completed (which could be a waste if I have to change upstream components). I'd prefer not to Ctrl+C 3 times, as it takes time for the server to spin up.

If it's useful, I can see if I can create a minimal reproduction; I'd probably first try to make some `genrule`s that artificially pause. 

### What operating system are you running Bazel on?

Ubuntu 18.04

### What's the output of `bazel info release`?

```
release 0.23.1
```

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

```
https://github.com/RobotLocomotion/drake.git  # Upstream, rather
63e8bf5d046841d5f8aad0f6b079f2c43f1fe712
63e8bf5d046841d5f8aad0f6b079f2c43f1fe712
```

###  Have you found anything relevant by searching the web?

Only #614. However, it's unclear if this feature request falls immediately under that purview; I'm only using local workers.

In this issue, it mentions that the workers should quit gracefully to prevent artifact corruption, which makes sense. However, it's odd that build errors seem to take an alternate mode of invalidation that permits earlier exit on the build actions?

### Any other information, logs, or outputs that you want to share?

Nah, not at the moment.

**Comment by jmmv** [comment] 2019-05-24 08:39
You seem to claim above that you use workers. Is that right? Which ones? If you do, #614 is indeed relevant because, when you hit Ctrl+C, Bazel is currently unable to tell those workers to stop what they are doing.

**Comment by jmmv** [comment] 2019-10-14 16:25
Considering a duplicate of #614.

**Closed by jmmv** 2019-10-14 16:25 UTC
Labels: P2, more data needed, team-Local-Exec, type: bug
