### ISSUE TITLE
Documentation issue: Common C   Build Use Cases

### ISSUE THREAD

**Issue by PradeepJigalur** [bazelbuild/bazel#11245] opened 2020-04-29 07:17 UTC
Documentation URL: https://docs.bazel.build/versions/master/cpp-use-cases.html

Please update Documentation for GoLang related usecases

**Comment by jin** [comment] 2020-04-29 11:13
Closing as dupe of https://github.com/bazelbuild/bazel/issues/3396

**Closed by jin** 2020-04-29 11:13 UTC
