### ISSUE TITLE
`tags = ["block-network"]` is not applied when `--java_debug` is on

### ISSUE THREAD

**Issue by jdanekrh** [bazelbuild/bazel#6755] opened 2018-11-25 12:12 UTC
### Description of the feature request:

I have a test with `tags = ["block-network"]`.  This test is failing with a network-related exception `java.net.UnknownHostException: java.sun.com`. I want to debug this test, so I specify `--java_debug` on the command line. When running under debugger, the exception is no longer raised and tests pass,

### Feature requests: what underlying problem are you trying to solve with this feature?

I'd like to have block-network in effect while debugging, so I can reproduce the problem easily and investigate the variables on stack in debugger to determine cause of the network access attempt.

I realize this may be difficult to achieve, because the java debugger connects over the network too.

### What operating system are you running Bazel on?

NixOS Linux and RHEL 7

**Comment by jdanekrh** [comment] 2018-11-25 15:31
(The cause of what I needed to debug was `http://java.sun.com/dtd/web-app_2_3.dtd` reference in one of the XML files ina .war file loaded to Jetty. Attempt to fetch the file failed under block-newtwork. Including `org.eclipse.jetty.toolchain:jetty-schemas'` jar fixed the problem for me.)

**Comment by ittaiz** [comment] 2018-11-25 17:12
This is dupe of #6379

**Comment by jdanekrh** [comment] 2018-11-25 19:54
Thanks, I searched for "block-network", so I did not find it. I disagree with the label "type: support / not a bug" on #6379, otherwise I don't mind closing this one in favour of that one.

**Comment by lberki** [comment] 2019-03-13 13:00
Closing this as a dupe of #6379 then.

**Closed by lberki** 2019-03-13 13:00 UTC
Labels: team-Rules-Java, untriaged
