### ISSUE TITLE
Bazel slow on XFS

### ISSUE THREAD

**Issue by AustinSchuh** [bazelbuild/bazel#852] opened 2016-02-05 06:54 UTC
See https://groups.google.com/forum/#!topic/bazel-discuss/u3_ttnFeTLQ

The sandbox creation step seems to be slower on XFS, and ends up single-threaded on a lock in the kernel.  This appears to also happen on EXT4, but to a much lesser extent.

**Comment by philwo** [comment] 2016-02-05 13:04
Hi Austin,

just wanted to say sorry that I didn't have the time to look into this earlier. I still think this is an important problem to solve.

If you or anyone else has ideas on how to improve performance by making changes in Bazel, I'd be very happy to hear about them. I'll also have a look into this myself as soon as time permits, but currently I had to shift my focus from the sandbox to the persistent workers / spawn scheduling to get something ready to ship on that side.

Philipp

**Comment by AustinSchuh** [comment] 2016-02-05 19:00
Hi Philipp,

No worries.  That was my suspicion.  I wanted to file a bug to make sure it didn't get lost.

Austin

**Comment by bsilver8192** [comment] 2016-02-07 22:14
I did some testing, and I think creating all the empty files to bind mount on top of is (at least part of) what's particularly slow on XFS on @AustinSchuh's machine, which has 8x hyperthreaded CPUs and an NVMe SSD. I have no idea why that's slow or how to speed it up though...

I did my testing using [this BUILD file](https://gist.github.com/bsilver8192/10527a862ce16bb7f79a), with tweaks to the number of genrules so it takes 10-30 seconds on different systems. Just removing the actual bind mounts for all the unused input files doesn't make much difference on @AustinSchuh's machine with XFS or ext4. However, making CreateFile in namespace-sandbox.c a no-op for those unused input files results in taking ~1/4 of the time on an XFS filesystem. On ext4, removing the file creations doesn't make much difference. Without the file creations, XFS and ext4 take about the same amount of time.

Interestingly, on my laptop (2x hyperthreaded CPUs and a SATA SSD), removing the creation of the files results in both XFS and ext4 taking ~3/4 of the time, and both filesystems are about the same for everything.

**Comment by philwo** [comment] 2016-02-09 11:58
Thanks to my colleague Ambrose, we have a proposed fix for this performance bottleneck - the trick is to not create empty files again and again, but (assuming that this is indeed what's causing XFS trouble) just create one and then hardlink the others to it.

**Comment by philwo** [comment] 2016-02-11 12:50
Thanks for the implementation of the fix, Brian. I've tried it on my machine, but actually now I'm having a hard time reproducing the initial problem at all:

I've tried the proposed genrule benchmark in a workspace + output_base lying on an ext4 / xfs filesystem in a container file lying in a tmpfs (to rule out I/O as a bottleneck), but also on a plain ext4 / xfs formatted HDD in my machine. I'm seeing the following numbers, no matter the filesystem and no matter whether I include the fix or not:

```# HDD formatted as XFS

# Unpatched Bazel
philwo@philwo:/media/hdd/workspace$ rm -f bazel-genfiles/*; /tmp/bazel-vanilla/output/bazel --output_base /media/hdd/output_base build --genrule_strategy=sandboxed --spawn_strategy=sandboxed :gen_main
INFO: Found 1 target...
Target //:gen_main up-to-date:
  bazel-genfiles/main
INFO: Elapsed time: 19.641s, Critical Path: 18.00s

philwo@philwo:/media/hdd/workspace$ rm -f bazel-genfiles/*; /tmp/bazel-vanilla/output/bazel --output_base /media/hdd/output_base build --genrule_strategy=sandboxed --spawn_strategy=sandboxed :gen_main
INFO: Found 1 target...
Target //:gen_main up-to-date:
  bazel-genfiles/main
INFO: Elapsed time: 16.944s, Critical Path: 15.71s

# Bazel with patch from https://bazel-review.git.corp.google.com/#/c/2890/
philwo@philwo:/media/hdd/workspace$ rm -f bazel-genfiles/*; /tmp/bazel-fixed/output/bazel --output_base /media/hdd/output_base build --genrule_strategy=sandboxed --spawn_strategy=sandboxed :gen_main
INFO: Found 1 target...
Target //:gen_main up-to-date:
  bazel-genfiles/main
INFO: Elapsed time: 16.374s, Critical Path: 14.67s

philwo@philwo:/media/hdd/workspace$ rm -f bazel-genfiles/*; /tmp/bazel-fixed/output/bazel --output_base /media/hdd/output_base build --genrule_strategy=sandboxed --spawn_strategy=sandboxed :gen_main
INFO: Found 1 target...
Target //:gen_main up-to-date:
  bazel-genfiles/main
INFO: Elapsed time: 18.561s, Critical Path: 16.96s
```

Without sandboxing, Bazel completes the build in ~0.3s in all cases, so we definitely have a performance issue here, but on my machine it seems to independent of the filesystem used and whether we use open() or link() for the empty files. Or maybe I'm completely missing something.

Any ideas?

**Comment by ulfjack** [comment] 2016-02-11 16:30
Can you post the results for the case without sandboxing?

**Comment by philwo** [comment] 2016-02-11 16:38
Sure:

```
philwo@philwo:/google/src/cloud/philwo/clean/google3$ mount | fgrep hdd
/dev/sdb1 on /media/hdd type xfs (rw)

philwo@philwo:/media/hdd/workspace$ rm -f bazel-genfiles/*; /tmp/bazel/output/bazel --output_base /media/hdd/output_base build --genrule_strategy=standalone --spawn_strategy=standalone :gen_main
INFO: Found 1 target...
Target //:gen_main up-to-date:
  bazel-genfiles/main
INFO: Elapsed time: 1.815s, Critical Path: 0.46s

philwo@philwo:/media/hdd/workspace$ rm -f bazel-genfiles/*; /tmp/bazel/output/bazel --output_base /media/hdd/output_base build --genrule_strategy=standalone --spawn_strategy=standalone :gen_main
INFO: Found 1 target...
Target //:gen_main up-to-date:
  bazel-genfiles/main
INFO: Elapsed time: 1.770s, Critical Path: 0.44s
```

**Comment by ulfjack** [comment] 2016-02-11 16:43
That's a factor of 10, not 100, isn't it?

**Comment by philwo** [comment] 2016-02-11 16:47
@ulfjack: Under-promise, over-deliver ;)

**Comment by bsilver8192** [comment] 2016-02-11 17:33
@philwo: that's weird. When I try it with XFS on an HDD, using hard links makes an ever bigger difference than with SSDs (4-5x).

```console
# Testing a binary with the patch.
brian[1174] iron ~/bazel_sandbox_testing
$ /tmp/brians-bazel clean && /tmp/brians-bazel build --show_result=0 //:gen_inputs && time /tmp/brians-bazel build //:main
INFO: Starting clean (this may take a while). Consider using --expunge_async if the clean takes more than several minutes.
INFO: Found 1 target...
INFO: Elapsed time: 4.614s, Critical Path: 0.62s
INFO: Found 1 target...
Target //:main up-to-date:
  bazel-genfiles/main
INFO: Elapsed time: 31.590s, Critical Path: 21.08s

real	0m31.598s
user	0m0.001s
sys	0m0.007s
# Replaced it with one without the patch.
brian[1175] iron ~/bazel_sandbox_testing
$ /tmp/brians-bazel clean && /tmp/brians-bazel build --show_result=0 //:gen_inputs && time /tmp/brians-bazel build //:main
Extracting Bazel installation...
Sending SIGTERM to previous Bazel server (pid=6856)... done.
.........
INFO: Starting clean (this may take a while). Consider using --expunge_async if the clean takes more than several minutes.
INFO: Found 1 target...
INFO: Elapsed time: 8.131s, Critical Path: 0.66s
INFO: Found 1 target...
Target //:main up-to-date:
  bazel-genfiles/main
INFO: Elapsed time: 142.895s, Critical Path: 116.34s

real	2m31.546s
user	0m0.000s
sys	0m0.006s
# I changed it to 300 genrules to get less noisy times (before running both tests).
brian[1178] iron ~/bazel_sandbox_testing
$ fgrep 'genrules =' BUILD
genrules = ['genrule_%s' % i for i in range(300)]
```

The speedup seems to get bigger on machines with more CPUs; how many does yours have?

Kernel versions I've tested (all got at least 2x faster with the patch): 3.16.7-ckt20-1+deb8u3, 4.1.12, 4.1.15. What version are you using?

Did you do a build just using a tmpfs (not XFS/etx4 in one)? I don't see any speed difference from the patch with that. The speed in the tmpfs is the same as XFS with the patch.

**Comment by philwo** [comment] 2016-02-11 19:48
@bsilver8192: That's indeed a big difference! I'll get you the data of my workstation and retry exactly using your instructions tomorrow. By the way, this is of course not a blocker to merging it - I'm already preparing that and it should be done tomorrow. I'm just curious how I can reproduce this reliably on my machine. :)

@AustinSchuh: Would you mind trying Brian's patch (https://bazel-review.googlesource.com/#/c/2890/) to see if it helps on your machine, too?

**Comment by AustinSchuh** [comment] 2016-02-11 19:57
@philwo Brian has SSH access to multiple of my machines.  His test 2 hours ago is on my desktop at home with a HD and XFS.  :)

Austin

**Comment by bsilver8192** [comment] 2016-02-11 20:08
Indeed. The machines with lots of cores (both the one with an HDD and the one with an NVMe SSD) are Austin's.

I'm curious too why you're not seeing the same results. Something I notice looking at your mount options: they're different than when I just mount an XFS partition. Not really sure why that is. Here's what I get after `mount -t xfs device mount_point`: `/dev/mapper/root-temp_xfs_partition on /tmp/temp_xfs_partition type xfs (rw,relatime,attr2,inode64,noquota)`. Different kernel versions?

Another thing that might be relevant: all of the SSDs (2 laptops + one of Austin's desktops) are being used via LVM. However, Austin's desktop with the HDD doesn't have LVM, and that's where I see the biggest difference.

**Comment by philwo** [comment] 2016-02-11 20:25
@bsilver8192 Could you please verify where Bazel puts the output base when you run the benchmark? Easiest way would be running "bazel info" in the workspace or checking where the "bazel-out" symlink in the workspace root points to.

One thing that I'm wondering about is that it shouldn't really matter what filesystem is used in the place where you put the workspace (because Bazel only reads from there, never writes). All the write I/O happens in the output base, also the sandboxes are built there. The output base on Linux should be ~/.cache/, so the filesystem of the place where the home directory lies would mostly influence the performance. In case this is a different filesystem or has special mount options, it may give us a hint :)

**Comment by bsilver8192** [comment] 2016-02-12 16:29
I've been using `--output_base` to switch the output base between the various filesystems. I agree that it shouldn't matter what filesystem the workspace is on, and I don't think it does.

I haven't been paying attention to what filesystem the workspace is (been using whatever my home directory is on the various machines, which is standard XFS or ext4 without any special mount options, like the output bases). I just tried XFS vs ext4 for the workspace on one machine, and didn't see any difference (including using the same filesystem as the output base).

I've been specifying `--output_base` when necessary and not specifying it at all when my home directory is the filesystem I want. I just tried leaving it at the default vs explicitly specifying something under my home directory and didn't see any difference.

**Comment by philwo** [comment] 2016-02-12 16:48
Thanks a lot for the tests! In that case the only mysterious thing remaining is why my machine doesn't show it. I had to tend to some other work today, but will retry the benchmark on Monday on my machine.

I'll also get your patch in on Monday - sorry for the delay.

**Comment by philwo** [comment] 2016-02-15 13:42
Still can't reproduce on my machine - I'll try with LVM on the HDD and Kernel 4.2.0 next, if I can get that to work on my machine.

Without patch:
```
philwo@philwo:/media/hdd/workspace$ /tmp/bazel-vanilla/output/bazel --output_base=/media/hdd/output_base clean &&
> /tmp/bazel-vanilla/output/bazel --output_base=/media/hdd/output_base build --show_result=0 //:gen_inputs &&
> time /tmp/bazel-vanilla/output/bazel --output_base=/media/hdd/output_base build //:main
Extracting Bazel installation...
........
INFO: Starting clean (this may take a while). Consider using --expunge_async if the clean takes more than several minutes.
INFO: Found 1 target...
INFO: Elapsed time: 4.986s, Critical Path: 0.55s
INFO: Found 1 target...
Target //:main up-to-date:
  bazel-genfiles/main
INFO: Elapsed time: 20.985s, Critical Path: 17.22s

real	0m20.991s
user	0m0.001s
sys	0m0.004s
```

With patch:
```
philwo@philwo:/media/hdd/workspace$ /tmp/bazel-brian/output/bazel --output_base=/media/hdd/output_base clean &&
> /tmp/bazel-brian/output/bazel --output_base=/media/hdd/output_base build --show_result=0 //:gen_inputs &&
> time /tmp/bazel-brian/output/bazel --output_base=/media/hdd/output_base build //:main
Extracting Bazel installation...
Sending SIGTERM to previous Bazel server (pid=24272)... done.
.........
INFO: Starting clean (this may take a while). Consider using --expunge_async if the clean takes more than several minutes.
INFO: Found 1 target...
INFO: Elapsed time: 5.059s, Critical Path: 0.59s
INFO: Found 1 target...
Target //:main up-to-date:
  bazel-genfiles/main
INFO: Elapsed time: 20.674s, Critical Path: 16.72s

real	0m20.680s
user	0m0.004s
sys	0m0.001s
```

#### Machine info:
CPU is an Intel(R) Xeon(R) CPU E5-1650 v2 @ 3.50GHz with 6 physical cores = 12 logical hyper-threading cores. My $HOME is on a Samsung SSD 850 Pro with 256GB.

I used the same mount flags for my HDD as you did and put the workspace + output base on the HDD with a freshly formatted XFS:

```
philwo@philwo:/media/hdd/workspace$ mount | fgrep hdd
/dev/sdb1 on /media/hdd type xfs (rw,relatime,attr2,inode64,noquota)

philwo@philwo:/media/hdd/workspace$ df -h | fgrep hdd
/dev/sdb1                                932G   37M  932G   1% /media/hdd
```

64GB of RAM:
```
philwo@philwo:/media/hdd/workspace$ free -h
             total       used       free     shared    buffers     cached
Mem:           62G        16G        46G       100M       328M       8.3G
-/+ buffers/cache:       8.1G        54G
Swap:         8.0G         0B       8.0G
```

```
philwo@philwo:/media/hdd/workspace$ sudo smartctl /dev/sdb
Model Family:     Western Digital Caviar Blue (SATA 6Gb/s)
Device Model:     WDC WD10EZEX-60ZF5A0
Serial Number:    WD-WMC1S7388336
LU WWN Device Id: 5 0014ee 25f3fbd7a
Firmware Version: 80.00A80
User Capacity:    1,000,204,886,016 bytes [1.00 TB]
Sector Sizes:     512 bytes logical, 4096 bytes physical
Rotation Rate:    7200 rpm
Device is:        In smartctl database [for details use: -P show]
ATA Version is:   ACS-2 (minor revision not indicated)
SATA Version is:  SATA 3.0, 6.0 Gb/s (current: 6.0 Gb/s)
Local Time is:    Mon Feb 15 14:35:35 2016 CET
SMART support is: Available - device has SMART capability.
SMART support is: Enabled
```

**Comment by philwo** [comment] 2016-02-15 13:53
Using LVM on the HDD didn't change anything.

**Comment by philwo** [comment] 2016-02-15 14:05
Using Kernel 4.2.0 doesn't change anything either. I've run out of ideas what to test. Maybe some difference in write caching? I'll just go ahead and merge it, as it obviously helps on your machines :)

```
philwo@philwo:/media/hdd/workspace$ uname -r
4.2.0-25-generic

philwo@philwo:/media/hdd/workspace$ /tmp/bazel-vanilla/output/bazel --output_base=/media/hdd/output_base clean &&
> /tmp/bazel-vanilla/output/bazel --output_base=/media/hdd/output_base build --show_result=0 //:gen_inputs &&
> time /tmp/bazel-vanilla/output/bazel --output_base=/media/hdd/output_base build //:main
Extracting Bazel installation...
........
INFO: Starting clean (this may take a while). Consider using --expunge_async if the clean takes more than several minutes.
INFO: Found 1 target...
INFO: Elapsed time: 4.808s, Critical Path: 0.50s
INFO: Found 1 target...
Target //:main up-to-date:
  bazel-genfiles/main
INFO: Elapsed time: 20.090s, Critical Path: 16.34s

real	0m20.415s
user	0m0.000s
sys	0m0.000s
```

**Comment by philwo** [comment] 2016-02-16 15:06
I'm closing this issue, now that the fix is submitted. Please reopen if you still see performance issues on XFS :)

**Closed by philwo** 2016-02-16 15:06 UTC
Labels: bug, P2, sandboxing

**Comment by bsilver8192** [comment] 2016-02-16 20:26
OK, thanks! I'm very mystified about why you don't see the same performance issue. I can't find any references online to XFS being slow about creating files, which I guess makes sense given that you don't see it, but the number of machines where it is slow is weird...

**Comment by AustinSchuh** [comment] 2016-05-27 00:19
I was having a bunch of trouble with EXT4 (bazel builds were causing the machine to be unusable), so I switched back to XFS.  Performance is now on par with EXT4, so yay, and my machine is much more responsive at the same time.  Thanks Brian and Phil!  I'll keep monitoring things, but XFS seems to be up to par with EXT4.

**Comment by jablin** [comment] 2021-08-05 10:29
Using the [build file](https://gist.github.com/bsilver8192/10527a862ce16bb7f79a) of @bsilver8192, I did some benchmarks with Bazel 4.1.0 on an eight * 2 (HT) cores CPU. TLDR: With XFS, it takes 24s instead of 10s (EXT4).

```
# on EXT4
[…]
INFO: Elapsed time: 8.830s, Critical Path: 1.61s
INFO: 104 processes: 2 internal, 102 linux-sandbox.
INFO: Build completed successfully, 104 total actions

real    0m10.249s
user    0m45.599s
sys     0m29.343s
```

```
# On XFS
[…]
INFO: 104 processes: 2 internal, 102 linux-sandbox.
INFO: Build completed successfully, 104 total actions

real    0m24.191s
user    0m47.066s
sys     0m36.849s
```

With processwrapper-sandbox instead of linux-sandbox, the timings are the same.

```
# for reference: with `--spawn_strategy=standalone`
[…]
INFO: 104 processes: 2 internal, 102 local.
INFO: Build completed successfully, 104 total actions

real    0m5.124s
user    0m41.688s
sys     0m1.605s
```

Should I open a new issue?

**Comment by philwo** [comment] 2021-08-05 12:04
> "on Linux 3.10.0"

Which distribution is that? Can you reproduce these numbers with a more modern kernel? (Not saying we shouldn't fix a performance issue on an older kernel, but it might just not be possible, because XFS improved a lot since then.)

**Comment by obruns** [comment] 2021-08-05 12:20
@philwo We are on RHEL7. The XFS filesystem is on a NVMe disk and is mounted with option nobarrier (which doesn't exist in newer kernels because it is now the default). We tried a v4.18.0 kernel (custom compiled; but it is the version that ships with RHEL8) and a recent v5.13.6 kernel. The observations with our project (not the benchmark) were the same: A lot of time is spent but core utilization by compilers is very bad.
Our sandboxes have up to 12k headers. Making them smaller is something we'd like to postpone until after the migration to Bazel.
Using ext4 on NVMe with v3.10.0 shows an almost ideal core utilization. Bazel still takes a lot of CPU time and we are aware that this is only going to improve with smaller sandboxes, obviously.

**Comment by obruns** [comment] 2021-08-05 12:31
All our XFS filesystems have the following info
```
xfs_db -r /dev/...
versionnum [0xb4b5+0x18a] = V5,NLINK,DIRV2,ATTR,ALIGN,LOGV2,EXTFLG,MOREBITS,ATTR2,LAZYSBCOUNT,PROJID32BIT,CRC,FTYPE
```

The NVMe model is `SAMSUNG MZVLB1T0HALR-000H2`.

**Comment by philwo** [comment] 2021-08-05 12:51
@obruns I see, thank you for all the information! I'm using XFS on my personal machine myself and can try to repro and improve this when I'm back home in ~1 - 2 weeks.

In the meantime, there are two flags that you could try to see if they improve performance for you:
- `--experimental_sandbox_async_tree_delete_idle_threads=auto` is available in Bazel 4.x and probably even before that.
- `--experimental_reuse_sandbox_directories` is available in the current Bazel rolling releases and will be part of Bazel 5.0.

If your sandboxes contain lots of files, these might give you a massive performance boost and don't have any drawbacks (@larsrc-google please correct me if I'm wrong 😊). These helped a lot on macOS, which also suffers from rather slow file operations - context is here https://github.com/bazelbuild/bazel/issues/8230#issuecomment-889126343.

**Comment by obruns** [comment] 2021-08-09 14:18
@philwo, thanks for suggesting the two flags.
* the impact of `--experimental_sandbox_async_tree_delete_idle_threads=auto` is negligible compared to `tmpfs`/`ext4`.
* there seems to be decent impact of `--experimental_reuse_sandbox_directories` but Bazel from `master`/rolling releases utilizes only ~10 of 16 cores which makes it difficult to know for sure.

The 10/16 core problem probably warrants a separate issue. I have seen that as early as June 2021 and independent of the aforementioned flags.

**Comment by larsrc-google** [comment] 2021-08-16 15:34
Are you saying that the same command run with Bazel 4.0.0 (or 4.1.0) uses a different amount of cores than running with a Bazel built from master? That does sound like a separate problem, yes.

**Comment by obruns** [comment] 2021-08-16 20:14
@larsrc-google Yes, all releases up to and including v4.2.0rc4 happen to utilize all cores just fine (modulo the XFS problem) but Bazel master has not been utilizing all cores for quite a while. I'll try to bisect the problem and create an issue. This may not happen until mid of September, though.

I only mentioned this because it makes testing `--experimental_reuse_sandbox_directories` impossible right now.

We have observed Bazel being slow on XFS since at least Bazel v3.7.0, probably even ever since we started porting our build to Bazel.

**Comment by gleventhal** [comment] 2022-04-22 21:05
I haven't read the whole thing, but based on my recent interactions with xfs, I would suspect that inode allocation is what's slow.  I'd be interested to see the output of xfs_info $path where $path is your xfs file system.  I am suspecting that you've got too low an agcount (ag == allocation group) for this workload and are not able to parallelize inode allocation across all cores.
