### ISSUE TITLE
ci.bazel.io: "Tutorial" project down, undeclared inclusion with external repository

### ISSUE THREAD

**Issue by laszlocsomor** [bazelbuild/bazel#543] opened 2015-10-29 09:15 UTC
How do I debug this?

The CI fails on compiling the //backend package because of an undeclared inclusion. The offending target is:

    $  /tmp/bzl/bazel/output/bazel build '@bazel_tools//third_party/ijar:zip'
    INFO: Found 1 target...
    INFO: From Compiling external/bazel_tools/third_party/ijar/zip.cc:
    external/bazel_tools/third_party/ijar/zip.cc:41:34: fatal error: third_party/ijar/zip.h: No such file or directory
     #include "third_party/ijar/zip.h"

However bazel query does find the target:

    $ /tmp/bzl/bazel/output/bazel query --output=label_kind '@bazel_tools//third_party/ijar:*' | sort
    ...
    source file @bazel_tools//third_party/ijar:zip.cc
    source file @bazel_tools//third_party/ijar:zip.h
    source file @bazel_tools//third_party/ijar:zip_main.cc

**Comment by ulfjack** [comment] 2015-10-29 10:57
This is an error message from the compiler (gcc most likely), which says
that the include search path isn't setup correctly.

It's actually a dupe of #445.

**Comment by ulfjack** [comment] 2015-10-29 10:58
Is there any way I can mark this as a dupe?

**Closed** 2015-10-29 10:58 UTC
Labels: help wanted, P1, question

**Comment by kchodorow** [comment] 2015-10-29 13:45
Under "Labels" in the right-hand column.
