### ISSUE TITLE
Visibility not working with `@my_repository` references

### ISSUE THREAD

**Issue by sergiocampama** [bazelbuild/bazel#7180] opened 2019-01-18 16:22 UTC
### Description of the problem / feature request:

Visibility is not properly processed when using the `@my_repository` syntax for referencing targets. I'd expect that I can reference targets with both `//` and `@my_repository` syntax but it seems the latter trips up visibility processing.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Check out https://github.com/sergiocampama/visibility_repro_case
`bazel build works` should succeed, but `bazel build does_not_work` doesn't.

### What operating system are you running Bazel on?

macOS Mojave

### What's the output of `bazel info release`?

release 0.21.0

**Comment by clintharrison** [comment] 2019-01-18 17:54
I believe this is fixed by `--experimental_remap_main_repo` (soon to be #7130) and this issue itself is a duplicate of #3115?

**Comment by dslomov** [comment] 2019-01-31 13:44
@dkelmer could you validate that it all works now after repository remapping is shipped?

**Comment by dkelmer** [comment] 2019-02-04 19:57
`bazel build does_not_work --experimental_remap_main_repo` builds successfully with bazel 0.22. The flag will be called --incompatible_remap_main_repo in the next release and become the default in the release following that.

**Closed by dkelmer** 2019-02-04 19:57 UTC
Labels: P2, team-ExternalDeps, type: bug

**Comment by dkelmer** [comment] 2019-02-04 20:51
Thanks for the simple repro case btw :)
