### ISSUE TITLE
Release 1.2 - November 2019 (stable)

### ISSUE THREAD

**Issue by dslomov** [bazelbuild/bazel#9983] opened 2019-10-10 15:22 UTC
Target RC: November 4th, 2019

**Comment by meisterT** [comment] 2019-11-07 07:01
If you didn't cut a baseline yet, you might want to wait until https://github.com/bazelbuild/bazel/issues/10184 is merged.

**Comment by philwo** [comment] 2019-11-12 14:41
Bazel 1.2, November 12th and a green downstream pipeline: The stars have finally aligned. Let's get this release ready:

# Status of Bazel X.Y

- Target baseline: [date]
- Expected release date: [date]
- [List of release blockers](https://github.com/bazelbuild/bazel/labels/Release%20blocker)

To report a release-blocking bug, please file a bug using the `Release blocker` label, and cc me.

Task list:

- [ ] Update GitHub issues for incompatible changes
- [x] Pick release baseline: 11deef7582dfeec7a04ee3f7236393d9b8027367
- [ ] Create release candidate:
- [ ] Check downstream projects:
- [ ] [Create draft release announcement](https://docs.google.com/document/d/1wDvulLlj4NAlPZamdlEVFORks3YXJonCjyuQMUQEmB0/edit)
- [ ] Send for review the release announcement PR:
- [ ] Push the release, notify package maintainers:
- [ ] Update the documentation
- [ ] Push the blog post
- [ ] Update the [release page](https://github.com/bazelbuild/bazel/releases/)

**Comment by philwo** [comment] 2019-11-12 15:18
Created 1.2.0rc0 with baseline 11deef7582dfeec7a04ee3f7236393d9b8027367 and cherry-pick c76c3e539c73ecf6e96e3e098be7be59e17bf276.

```
RELEASE_NUMBER=1.2.0
BASELINE_COMMIT=11deef7582dfeec7a04ee3f7236393d9b8027367
git clone https://github.com/bazelbuild/bazel.git ~/src/bazel-release-$RELEASE_NUMBER
cd ~/src/bazel-release-$RELEASE_NUMBER
scripts/release/release.sh create $RELEASE_NUMBER $BASELINE_COMMIT c76c3e539c73ecf6e96e3e098be7be59e17bf276
scripts/release/release.sh push
```

**Comment by jmillikin-stripe** [comment] 2019-11-12 21:53
Any chance of getting https://github.com/bazelbuild/bazel/pull/10110 in? It's a three-line delta that materially improves ergonomics for scripting languages (Javascript, Ruby) when using hermetic runtimes.

**Comment by philwo** [comment] 2019-11-13 09:26
Will create rc2 with additional cherry-pick https://github.com/bazelbuild/bazel/pull/10222 in order to fix broken C++ compilation when using an empty PATH.

**Comment by philwo** [comment] 2019-11-13 09:29
@jmillikin-stripe I reached out to Lukacs, if we can get this reviewed & imported today, I can cherry-pick it.

**Comment by jmillikin** [comment] 2019-11-13 10:11
@philwo Thanks a ton! I'll keep an eye on my inbox in case there's any review feedback.

**Comment by philwo** [comment] 2019-11-15 11:31
Bazel 1.2.0rc2 is ready:

```
RELEASE_NUMBER=1.2.0
RC_NUMBER=2
BASELINE_COMMIT=11deef7582dfeec7a04ee3f7236393d9b8027367
cd ~/src/bazel-release-$RELEASE_NUMBER
scripts/release/release.sh create --force_rc=$RC_NUMBER $RELEASE_NUMBER \
    $BASELINE_COMMIT \
    c76c3e539c73ecf6e96e3e098be7be59e17bf276 \
    63332eb556fadfe9edd0806add79942482adddef \
    ceadf0a063cb97c32aced143d2447781d1dafc38
scripts/release/release.sh push
```

**Comment by johnplate** [comment] 2019-11-15 16:38
Is it still possible to get #10216 into 1.2? It is a trivial fix for a syntax error occurring with mingw-gcc that prevents us (GAPID team) to upgrade to anything newer than 0.26.0. Thanks in advance!

**Comment by keith** [comment] 2019-11-20 01:51
Is there a target date for when this release will be finalized?

**Comment by philwo** [comment] 2019-11-20 09:20
@johnplate I'll get that in.

@keith I hope we can release it tomorrow. I'm not aware of any regressions or other cherry-pick requests. Will do another downstream pipeline run to ensure everything looks green on CI.

**Comment by philwo** [comment] 2019-11-20 09:25
Created Bazel 1.2.0rc3 with:

```bash
RELEASE_NUMBER=1.2.0
RC_NUMBER=3
BASELINE_COMMIT=11deef7582dfeec7a04ee3f7236393d9b8027367
cd ~/src/bazel-release-$RELEASE_NUMBER
scripts/release/release.sh create --force_rc=$RC_NUMBER $RELEASE_NUMBER \
    $BASELINE_COMMIT \
    c76c3e539c73ecf6e96e3e098be7be59e17bf276 \
    63332eb556fadfe9edd0806add79942482adddef \
    ceadf0a063cb97c32aced143d2447781d1dafc38 \
    dbe63b00954a25fa4405f7cbf273df78c16498dd
scripts/release/release.sh push
```

**Comment by philwo** [comment] 2019-11-20 12:12
Downstream is green except for TensorFlow failing on macOS, which seems to be an incompatibility with their protobuf version and Xcode 11.1: https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/1287

**Comment by davido** [comment] 2019-11-20 13:26
Am I correct to assume, that the new 1.2 release is the solution for this 1.0.1 overwrites 1.1.0 metadaten in Bazel apt repository [issue](https://github.com/bazelbuild/bazel/issues/10199)?

Can we publish 1.2 release ASAP then?

We have complaints from Gerrit users who depend on Bazel apt repository containing the version included in Gerrit's `.bazelversion` file. They are not able to install 1.1.0, and as the consequence they cannot install the right Bazel version and cannot build `gerrit`, because the minimum version check is failing.

They cannot install `bazelisk` because it is not available on their standard Linux distribution.

IOW Gerrit users are bocked and cannot work on gerrit any more.

Here is the [request ](https://gerrit-review.googlesource.com/c/gerrit/+/245759) to downgrade Bazel from 1.1.0 to 1.0.1, but that would be a pain, because we would have to revert a number of other changes as well, e.g. related to this Bazel [bug](https://github.com/bazelbuild/bazel/issues/9391).

**Comment by philwo** [comment] 2019-11-20 14:38
@davido Yes, releasing Bazel 1.2.0 will fix the metadata issue for now. I'll do some final checks now and if everything looks fine, I'll release it.

We're very close to fixing the metadata generation for the repository, too, so that it will not happen again in the future.

**Comment by philwo** [comment] 2019-11-20 15:02
Draft blog post with release notes is here: https://github.com/bazelbuild/bazel-blog/pull/209

**Comment by philwo** [comment] 2019-11-20 15:02
Release pushed and now building on CI: https://buildkite.com/bazel-trusted/bazel-release/builds/116

**Comment by keith** [comment] 2019-11-20 19:41
@philwo it looks like the public doesn't have access to the pipeline, is there a way it could be readonly publicly?

**Comment by philwo** [comment] 2019-11-20 21:04
@keith I'll see what I can do there tomorrow. 😊

If you're curious, the pipeline definition is here: https://github.com/bazelbuild/continuous-integration/blob/master/pipelines/bazel-release.yml

**Comment by philwo** [comment] 2019-11-21 13:19
Bazel 1.2.0 has been released.

**Closed by philwo** 2019-11-21 13:19 UTC
Labels: release

**Comment by chenrui333** [comment] 2019-11-22 21:20
I have submit a ticket on this, https://github.com/bazelbuild/bazel/issues/10297

It seems currently it impacts highsierra users.

**Comment by philwo** [comment] 2019-11-22 21:40
The breakage reported by @chenrui333 will require a patch release, as breaking backwards compatibility with macOS High Sierra was not intended (and is not OK) in the 1.x line.

I'll do that on Monday.

**Comment by philwo** [comment] 2019-11-25 13:09
When https://github.com/bazelbuild/continuous-integration/pull/873 is merged, I will create the patch release.

**Comment by philwo** [comment] 2019-11-26 15:51
Bazel 1.2.1 has been released.

**Comment by petemounce** [comment] 2019-11-27 02:01
Chocolatey for 1.2.0 is published, apologies for the wait.

**Comment by petemounce** [comment] 2019-11-27 22:39
1.2.1 pushed too.

**Comment by philwo** [comment] 2019-11-28 04:28
Thank you, @petemounce!
