### ISSUE TITLE
CC toolchain resolution ignores --platforms and --host_platform

### ISSUE THREAD

**Issue by samolisov** [bazelbuild/bazel#11522] opened 2020-05-29 12:10 UTC
### Description of the problem / feature request:

It looks like the toolchain resolution mechanism ignores the `--platforms` and `--host_platform` command line options. The case is the following: I wish to select `MSVC` or `clang-cl` on Windows from the command line. I've defined two platforms in my `BUILD`:

```bzl
platform(
    name = "x64_windows-clang-cl",
    constraint_values = [
        "@platforms//cpu:x86_64",
        "@platforms//os:windows",
        "@bazel_tools//tools/cpp:clang-cl",
    ],
)

platform(
    name = "x64_windows-msvc",
    constraint_values = [
        "@platforms//cpu:x86_64",
        "@platforms//os:windows",
        "@bazel_tools//tools/cpp:msvc",
    ],
)
```
And registered both in `WORKSPACE`:

```bzl
register_execution_platforms(
    ":x64_windows-msvc",
    ":x64_windows-clang-cl",
)

register_toolchains(
    "@local_config_cc//:cc-toolchain-x64_windows-clang-cl",
)
```

The order in `register_execution_platforms` **does matter**: Bazel just takes the first and looks for a toolchain that satisfies all the constraints defined by the platform. If there is a such toolchain, Bazel just uses it. And If I wish to use the second one platform and do:

```sh
$ bazel build ... --incompatible_enable_cc_toolchain_resolution --host_platform=//:x64_windows-clang-cl --platforms=//:x64_windows-clang-cl
```
Bazel just ignores it and still uses `x64_windows-msvc` as the execution platform.

Maybe it is because the toolchain resolution depends on *execution* platform, not on a host or target one while the `--host_platform` and '--platforms` command line options are for host and target platforms respectively.

Now I see only one workaround: not to register execution platforms in `WORKSPACE` but to use `--extra_execution_platforms` option and when one wish to set a `config_setting` for the platform, the `--platform` option should also been used.

A smallest project to see how to reproduce the issue can be found there:
https://github.com/samolisov/bazel-cc-platform-demo

### What operating system are you running Bazel on?

Windows 10

### What's the output of `bazel info release`?

release 3.2.0

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

N/A

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

N/A

###  Have you found anything relevant by searching the web?

I put a comment in issue #7260 and @katre suggested to open a new issue.

**Comment by katre** [comment] 2020-05-29 12:39
I see the problem. The issue is that, while the host platform is used as an execution platform (see https://docs.bazel.build/versions/3.2.0/toolchains.html#toolchain-resolution), it is the lowest-priority execution platform. Therefore, if you have registered actual execution platforms, those will be used in preference.

It looks like what you actually want is to select the compiler on Windows, between MSVC and Clang. I would recommend using the `--compiler` flag for that. Since you are using toolchain resolution, this can easily managed with an `alias` target.

```bzl
toolchain(
    name = "my_toolchain",
    exec_compatible_with = [
        "@platforms//cpu:x86_64",
        "@platforms//os:windows",
        "@bazel_tools//tools/cpp:clang-cl",
    ],
    target_compatible_with = [
        "@platforms//cpu:x86_64",
        "@platforms//os:windows",
    ],
    toolchain_type = "@bazel_tools//tools/cpp:toolchain_type",
    toolchain = ":my_toolchain_select",
)

config_setting(
    name = "use_clang",
    values = {
      "compiler": "clang",
    },
)

config_setting(
    name = "use_msvc",
    values = {
      "compiler": "msvc",
    },
)

alias(
    name = "my_toolchain_select",
    actual = select({
        ":use_clang": ":cc-compiler-x64_windows-clang-cl",
        ":use_msvc": ":cc-compiler-x64_windows-clang-msvc",
    }),
)
```

When the single toolchain is used, the select will check the value of the `--compiler` flag and delegate to the proper `cc_toolchain` target.

**Comment by samolisov** [comment] 2020-05-29 13:45
@katre thank you very much for the answer. 

The solution works fine, just to be clear, MSVC compiler has the name `msvc-cl` in the `local_config_cc` package.

Could you let me know, is there a way to specify --compiler by default? Now, if I pass no --compiler, neither `use_clang` nor `use_msvc` has been chosen. I believe `msvc-cl` should be a default option on Windows.

And one point, the documentation https://docs.bazel.build/versions/master/windows.html says:

> The --incompatible_enable_cc_toolchain_resolution flag is planned to be enabled by default in future Bazel release. Therefore, it is recommended to enable Clang support with the second approach.

Does it mean, `--compiler` flag is planned to be removed in the future?

**Comment by katre** [comment] 2020-05-29 13:51
You can add a default for the select with `//conditions:default`:

```bzl
select({
    ":use_clang": "clang option",
    ":use_msvc": "msvc option",
    "//conditions:default": "default option",
})
```

You can also set the value of any flag to a default using a [bazelrc file](https://docs.bazel.build/versions/master/guide.html#bazelrc-the-bazel-configuration-file), either a personal one or a project one.
 
I do not believe the `--compiler` flag is being removed, but that is up to the C++ rules team. We've been evolving how toolchains work with rules like C++, and I think using the flag is easier for users than adding a constraint.

I'm closing this because I think we've answered your question, feel free to re-open it or file further issues if you still have questions.

**Closed by katre** 2020-05-29 13:51 UTC
Labels: team-Configurability

**Comment by samolisov** [comment] 2020-05-29 13:52
Thank you @katre. Yes. the question is answered.
