### ISSUE TITLE
Bazel fails recognizing current workspace name when building remote repositories

### ISSUE THREAD

**Issue by katzdm** [bazelbuild/bazel#1312] opened 2016-05-25 22:20 UTC
If a workspace "SomeLib" includes a git_repository-rule, referencing an external repository which itself remotely references "@SomeLib//"-targets, Bazel will fail to find "SomeLib" during building of build-targets in the external repository, giving a "no such package" error. Bazel should recognize that the "SomeLib"-repository referenced in the external repository is the same as the current workspace, and build accordingly. This probably amounts to including a symlink in the "external/" directory for the current workspace.

**Comment by kchodorow** [comment] 2016-05-26 15:23
Duplicate of #1248.

**Closed** 2016-05-26 15:31 UTC
Labels: Duplicate
