### ISSUE TITLE
Document worker logs and reference them in error messages

### ISSUE THREAD

**Issue by tfarina** [bazelbuild/bazel#1082] opened 2016-03-24 17:10 UTC
It does not seem to be documented at http://bazel.io/docs/output_directories.html, but it gets created into the workspace output directory like ~/.cache/bazel/_bazel_tfarina/6d70a61f5bd1a13d7afc1a908d972fe8/worker-logs/

**Comment by damienmg** [comment] 2016-03-24 17:13
/cc @philwo 

Overall the whole worker functionality needs to be documented.

**Comment by natebosch** [comment] 2017-03-07 22:31
related to this it would be awesome if a failure because of bad data on stdout also comes with a easier way to find the relevant worker-log.

Today my process is:

- See [this message](https://github.com/bazelbuild/bazel/blob/d72bc57b60b26245e64f5ccafe023a5ede81cc7f/src/main/java/com/google/devtools/build/lib/worker/WorkerSpawnStrategy.java#L410)
- Hope that the worker also crashed and look above for the warning like `<mnemonic> worker (id 0) can no longer be used, because its process terminated itself or got killed`
- Run `bazel info` to find the `output_base`
- Open up the log for the appropriate worker ID to see what was output

The process I would prefer is:

- See a message about unexpected data on stdout
- See a line in the message like `see the output at <path>`
- Copy/paste the path

**Comment by susinmotion** [comment] 2020-07-09 19:42
If I'm understanding this correctly, the "reference them in error messages" part is fixed. You now get a path to the log file, in addition to the first part of the logs. 

Yes, workers still need better documentation. I'm going to close this is a duplicate of https://github.com/bazelbuild/bazel/issues/7997 and add a comment that this includes documenting the location of log files.

**Closed by susinmotion** 2020-07-09 19:42 UTC
Labels: P2, team-Local-Exec, type: documentation
