### ISSUE TITLE
bazel-workspace-name output symlink should use the declared name in WORKSPACE file

### ISSUE THREAD

**Issue by haikalpribadi** [bazelbuild/bazel#6454] opened 2018-10-19 17:51 UTC
### Description of the feature request:

At the moment, the output symlink for `bazel-<workspace-name>` uses the workspace's directory name as the `<workspace-name>`, instead of the name of the workspace declared in the `WORKSPACE` file (e.g. `workspace(name = "grakn_core")`).

### Feature requests: what underlying problem are you trying to solve with this feature?

I would like to have the Bazel output directories to be more meaningful and intuitive. At the moment, the `bazel-<workspace-name>` doesn't actually use the name of the workspace which the user expects it to be, which is the name she/he declared in the `WORKSPACE` file.

### What's the output of `bazel info release`?

release 0.18.0

**Comment by janakdr** [comment] 2020-08-24 19:29
Duplicate of #5506

**Closed by janakdr** 2020-08-24 19:29 UTC
Labels: team-Core, type: feature request, untriaged
