### ISSUE TITLE
Release 2.2 (stable) - February 2020

### ISSUE THREAD

**Issue by dslomov** [bazelbuild/bazel#10133] opened 2019-10-30 08:07 UTC
# Status of Bazel 2.2.0

- Target baseline: 78055efad0917b848078bf8d97b3adfddf91128d
- Expected release date: 2020-02-20
- [List of release blockers](https://github.com/bazelbuild/bazel/labels/Release%20blocker)

To report a release-blocking bug, please file a bug using the `Release blocker` label, and cc me.

Task list:

- [x] Update GitHub issues for incompatible changes
- [x] Pick release baseline: 78055efad0917b848078bf8d97b3adfddf91128d
- [x] Create release candidate: https://releases.bazel.build/2.2.0/rc1/index.html
- [x] Check downstream projects: https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/1389
- [x] [Create draft release announcement](https://docs.google.com/document/d/1wDvulLlj4NAlPZamdlEVFORks3YXJonCjyuQMUQEmB0/edit)
- [ ] Send for review the release announcement PR:
- [X] Push the release, notify package maintainers: @vbatts @petemounce @excitoon
- [ ] Update the documentation
- [ ] Push the blog post
- [X] Update the [release page](https://github.com/bazelbuild/bazel/releases/)

**Comment by jmillikin-stripe** [comment] 2020-02-03 09:56
Scheduling note: if possible, I'd love to get https://github.com/bazelbuild/bazel/pull/10622 into this release -- it's been delayed a fairly long time on design reviews, and our internal builds are suffering for it.

**Comment by philwo** [comment] 2020-02-03 19:27
@meteorcloudy Can we make Bazel 2.2 our first release built on Kokoro? :)

**Comment by meteorcloudy** [comment] 2020-02-04 09:40
Yes!

**Comment by philwo** [comment] 2020-02-12 15:42
@jmillikin-stripe I'm sorry, the PR you wanted to have in Bazel 2.2 still hasn't been merged yet, but I'm already super late with cutting the baseline for Bazel 2.2. The next Bazel release will already be cut on March 1st. 

 pinged Jakob, but he said he can't get it done right now, so I have to go ahead and prepare Bazel 2.2 now.

**Comment by philwo** [comment] 2020-02-13 09:51
I'm preparing Bazel 2.2.0 now:

```
RELEASE_NUMBER=2.2.0
BASELINE_COMMIT=78055efad0917b848078bf8d97b3adfddf91128d
git clone https://github.com/bazelbuild/bazel.git ~/bazel-release-$RELEASE_NUMBER
cd ~/bazel-release-$RELEASE_NUMBER
scripts/release/release.sh create $RELEASE_NUMBER $BASELINE_COMMIT
```

**Comment by gertvdijk** [comment] 2020-02-14 10:54
It's here I guess? :arrow_right: https://releases.bazel.build/2.2.0/rc1/index.html
:rocket:

**Comment by philwo** [comment] 2020-02-14 11:34
@gertvdijk Correct. :) I'll send the announcement to bazel-discuss@ now.

**Comment by nevion** [comment] 2020-02-15 09:24
@philwo  little bit of a threadjack but I noticed in the rc1 release notes the cuda/opencl file extension support I've been using for ~2 years now and that recently got accepted was reverted 
See
https://github.com/bazelbuild/bazel/commit/250647bc89d5bb42fa2456b2b497fb254c775861
https://github.com/bazelbuild/bazel/issues/6578

Is this going to be cut from 2.2 / can you maybe make sure to chase down why it's important to revert those changes and the right thing to do over all?

**Comment by gertvdijk** [comment] 2020-02-19 17:10
FWIW, 2.2.0rc1 works like a charm here as drop-in replacement for 2.1.0 (tested @ linux x86_64 via Bazelisk on some internal repos).

**Comment by philwo** [comment] 2020-02-27 15:31
@gertvdijk Let's push it then :D

I haven't heard about any release blockers.

**Comment by philwo** [comment] 2020-03-03 09:53
Release 2.2.0 has been pushed, release notes on our blog to follow.

**Comment by vbatts** [comment] 2020-03-03 13:10
fedora/centos/RHEL builds are kicked off: https://copr.fedorainfracloud.org/coprs/build/1282540
also note, this package is "bazel2"

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by vbatts** [comment] 2020-03-03 14:43
none of the aarch64 builds succeeded

**Comment by philwo** [comment] 2020-03-03 14:56
Looks like this is the error on aarch64:

```
bazel-out/aarch64-opt/bin/external/bazel_tools/tools/jdk/include/jni.h:45:10: fatal error: jni_md.h: No such file or directory
   45 | #include "jni_md.h"
```

If someone can repro and send a PR to fix it, I can look into doing a patch release. I won't have time to do it myself this week unfortunately.

**Comment by katre** [comment] 2020-03-03 15:04
We should also file this so I can track it for the next release.

**Comment by source-creator** [comment] 2020-03-27 15:40
@philwo Hi, were you able to do a patch?

I also get this exact error.

My Java details:
```
$  java -version ; javac -version
openjdk version "1.8.0_212"
OpenJDK Runtime Environment (build 1.8.0_212-8u212-b01-1+rpi1-b01)
OpenJDK Client VM (build 25.212-b01, mixed mode)
javac 1.8.0_212
```

I have confirmed that `jni_md.h` does not exist in the JDK include directory, and upon further investigation I saw:

> this is done by intent. These compat symlinks were wrong in openjdk-7.
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=760301

**Comment by davido** [comment] 2020-03-30 09:15
@vbatts I still cannot install 2.2.0 on Fedora 31:

```
  $ sudo dnf install bazel
Copr repo for bazel owned by vbatts   
=============================================================
 Package                  Arch   Version            Repository                           Size
=============================================================
 bazel                    x86_64 1.2.1-1.fc31       copr:copr.fedorainfracloud.org:vbatts:bazel
```

**Comment by source-creator** [comment] 2020-03-30 11:23
I am also still unable to build 2.2.0 on ARM.
I managed to build 2.1.1 last night on ARM.

**Comment by vbatts** [comment] 2020-03-30 12:49
> @vbatts I still cannot install 2.2.0 on Fedora 31:
> 
> ```
>   $ sudo dnf install bazel
> Copr repo for bazel owned by vbatts   
> =============================================================
>  Package                  Arch   Version            Repository                           Size
> =============================================================
>  bazel                    x86_64 1.2.1-1.fc31       copr:copr.fedorainfracloud.org:vbatts:bazel
> ```

`dnf install -y --allowerasing bazel2`

**Comment by davido** [comment] 2020-03-30 15:15
> dnf dnf install -y --allowerasing bazel2

Thanks! Should the documentation be updated: [1]?

```
 dnf copr enable vbatts/bazel
 dnf install bazel
```

[1] https://docs.bazel.build/versions/master/install-redhat.html

**Comment by philwo** [comment] 2020-03-31 05:32
@source-creator Unfortunately not yet. If anyone has a working patch that makes the build work on ARM, I'm happy to review it and get it in.

**Comment by limdor** [comment] 2020-07-20 15:12
@philwo is there a reason why this issue is still opened or just forgotten?

**Comment by philwo** [comment] 2020-07-20 19:45
@limdor Just forgotten to close it, sorry.

**Closed by philwo** 2020-07-20 19:45 UTC
Labels: release
