### ISSUE TITLE
Bazel fails rebuilds for top-level directories starting with '_' (Source forest creation failed)

### ISSUE THREAD

**Issue by bpicolo** [bazelbuild/bazel#2732] opened 2017-03-23 19:36 UTC
### Description of the problem / feature request / question:
`bazel build //_foo:bar` fails rebuilds when _foo is underscored

### If possible, provide a minimal example to reproduce the problem:
```
mkdir example
cd example
touch WORKSPACE && mkdir _somedir
echo 'genrule(name = "hello", outs = ["hello_world.txt"], cmd = "echo Hello World > $@")' >> _somedir/BUILD
# Works fine
bazel build //_somedir:hello
#  ERROR: Source forest creation failed: /private/var/tmp/_bazel_bpicolo/4fa675bbf6b3cc931c9886f9eb28a76b/execroot/cgi-bin/_somedir (File exists).
bazel build //_somedir:hello
```

### Environment info
* Operating System: 
Mac 10.12.3 sierra
* Bazel version (output of `bazel info release`):
0.4.5-homebrew

###  Have you found anything relevant by searching the web? (e.g. GitHub issues, email threads in the [bazel-discuss@googlegroups.com](https://groups.google.com/forum/#!forum/bazel-discuss) archive)

There are similar github issues. Potentially same as #1998, though '.' is more special in paths than _

**Comment by aj-michael** [comment] 2017-03-23 20:09
This looks like the same issue as https://github.com/bazelbuild/bazel/issues/1998

**Comment by bpicolo** [comment] 2017-03-23 20:10
Ah yeah, this is indeed the same:
https://github.com/bazelbuild/bazel/blob/master/src/main/java/com/google/devtools/build/lib/buildtool/SymlinkForest.java#L57

Unfortunate blacklist =(

**Comment by ericfelly** [comment] 2019-08-13 20:04
Closing as dupe of #1998

**Closed by ericfelly** 2019-08-13 20:04 UTC
Labels: team-Core, type: bug, untriaged
