### ISSUE TITLE
IDEA plugin sync fails

### ISSUE THREAD

**Issue by christian-lefty** [bazelbuild/bazel#3319] opened 2017-07-04 08:42 UTC
bazel sync fails from the Intellij IDEA plugin. This makes it more or less impossible to use.

The error from the log is:

java.lang.StringIndexOutOfBoundsException: String index out of range: -14
	at java.lang.String.substring(String.java:1955)
	at com.google.devtools.build.lib.runtime.BlazeRuntime.getRequestLogString(BlazeRuntime.java:614)
	at com.google.devtools.build.lib.runtime.CommandExecutor.exec(CommandExecutor.java:50)
	at com.google.devtools.build.lib.server.GrpcServerImpl.executeCommand(GrpcServerImpl.java:849)
	at com.google.devtools.build.lib.server.GrpcServerImpl.access$2100(GrpcServerImpl.java:104)
	at com.google.devtools.build.lib.server.GrpcServerImpl$4$1.run(GrpcServerImpl.java:915)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
bazel crash in async thread:
java.lang.StringIndexOutOfBoundsException: String index out of range: -14
	at java.lang.String.substring(String.java:1955)
	at com.google.devtools.build.lib.runtime.BlazeRuntime.getRequestLogString(BlazeRuntime.java:614)
	at com.google.devtools.build.lib.runtime.CommandExecutor.exec(CommandExecutor.java:50)
	at com.google.devtools.build.lib.server.GrpcServerImpl.executeCommand(GrpcServerImpl.java:849)
	at com.google.devtools.build.lib.server.GrpcServerImpl.access$2100(GrpcServerImpl.java:104)
	at com.google.devtools.build.lib.server.GrpcServerImpl$4$1.run(GrpcServerImpl.java:915)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

## bazel version output

Build label: 0.5.1- (@non-git)
Build target: bazel-out/local-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Wed Jun 14 10:18:29 2017 (1497435509)
Build timestamp: 1497435509
Build timestamp as int: 1497435509

## Plugin version:

Version: 2017.06.05.0.4

**Comment by philwo** [comment] 2017-07-05 08:26
Duplicate of https://github.com/bazelbuild/bazel/issues/3196.

**Closed by philwo** 2017-07-05 08:26 UTC
