### ISSUE TITLE
Default documentation links are for development version of bazel instead of released version

### ISSUE THREAD

**Issue by endobson** [bazelbuild/bazel#3336] opened 2017-07-07 19:58 UTC
The documentation links on https://www.bazel.build/ go to https://docs.bazel.build/versions/master/bazel-overview.html. This contains the documentation for the version of bazel at `master` and not the latest released version. This leads to issues where new features are added and old features are deprecated at master, but the most recent release doesn't even have the new feature. Thus when looking up how to use a feature I'm given instructions that will not work for me, even though I'm using the latest released version of the software.

I think that the default documentation links should be to the version corresponding to the release, and that developers of bazel who want the documentation for `master` can go to a non default version.

The specific issue that just bit me is the change from `ctx.file_action` to `ctx.actions.write`. This is currently visible on the documentation site but not available in 0.5.2.
https://github.com/bazelbuild/bazel/commit/90ccaa583828aa4e9bf8b7b0507ab518121ef90c

**Comment by laszlocsomor** [comment] 2017-07-10 07:41
Duplicate of https://github.com/bazelbuild/bazel/issues/1788, which is unfortunately still open.

**Comment by laszlocsomor** [comment] 2017-07-10 07:43
Also related: https://github.com/bazelbuild/bazel/issues/579

**Comment by davidzchen** [comment] 2017-08-22 20:10
Duplicate of #579 and #1788

**Closed by davidzchen** 2017-08-22 20:10 UTC
Labels: P2, type: documentation, type: feature request
