### ISSUE TITLE
"zip file closed" when building Bazel using multiplex worker

### ISSUE THREAD

**Issue by coeuvre** [bazelbuild/bazel#13565] opened 2021-06-09 03:26 UTC
We occasionally see the following error on the CI machines when building target `src/main/java/com/google/devtools/build/lib/analysis/libexec_group_collection.jar`:

```
(11:54:48) ERROR: /workdir/src/main/java/com/google/devtools/build/lib/analysis/BUILD:776:13: Building src/main/java/com/google/devtools/build/lib/analysis/libexec_group_collection.jar (1 source file) and running annotation processors (AutoAnnotationProcessor, AutoValueProcessor) failed: (Exit 1): java failed: error executing command
  (cd /var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/ec321eb2cc2d0f8f91b676b6d4c66c29/execroot/io_bazel && \
  exec env - \
    LC_CTYPE=en_US.UTF-8 \
    PATH=/var/lib/buildkite-agent/.cache/bazelisk/downloads/bazelbuild/bazel-4.1.0-linux-x86_64/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/go1.15.2.linux-amd64/bin:/opt/swift-5.2.5-RELEASE-ubuntu18.04/usr/bin \
  external/remotejdk11_linux/bin/java -XX:+UseParallelOldGC -XX:-CompactStrings '--patch-module=java.compiler=external/remote_java_tools_linux/java_tools/java_compiler.jar' '--patch-module=jdk.compiler=external/remote_java_tools_linux/java_tools/jdk_compiler.jar' '--add-exports=jdk.compiler/com.sun.tools.javac.api=ALL-UNNAMED' '--add-exports=jdk.compiler/com.sun.tools.javac.code=ALL-UNNAMED' '--add-exports=jdk.compiler/com.sun.tools.javac.comp=ALL-UNNAMED' '--add-exports=jdk.compiler/com.sun.tools.javac.file=ALL-UNNAMED' '--add-exports=jdk.compiler/com.sun.tools.javac.main=ALL-UNNAMED' '--add-exports=jdk.compiler/com.sun.tools.javac.tree=ALL-UNNAMED' '--add-exports=jdk.compiler/com.sun.tools.javac.util=ALL-UNNAMED' '--add-opens=jdk.compiler/com.sun.tools.javac.file=ALL-UNNAMED' '--add-opens=java.base/java.nio=ALL-UNNAMED' '--add-opens=java.base/java.lang=ALL-UNNAMED' -jar external/remote_java_tools_linux/java_tools/JavaBuilder_deploy.jar @bazel-out/k8-fastbuild/bin/src/main/java/com/google/devtools/build/lib/analysis/libexec_group_collection.jar-0.params @bazel-out/k8-fastbuild/bin/src/main/java/com/google/devtools/build/lib/analysis/libexec_group_collection.jar-1.params)
Execution platform: //:default_host_platform
java.lang.RuntimeException: java.lang.ExceptionInInitializerError
	at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.handleExceptions(JavacTaskImpl.java:163)
	at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.doCall(JavacTaskImpl.java:100)
	at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:94)
	at com.google.devtools.build.buildjar.javac.BlazeJavacMain.compile(BlazeJavacMain.java:123)
	at com.google.devtools.build.buildjar.ReducedClasspathJavaLibraryBuilder.fallback(ReducedClasspathJavaLibraryBuilder.java:103)
	at com.google.devtools.build.buildjar.ReducedClasspathJavaLibraryBuilder.compileSources(ReducedClasspathJavaLibraryBuilder.java:65)
	at com.google.devtools.build.buildjar.SimpleJavaLibraryBuilder.compileJavaLibrary(SimpleJavaLibraryBuilder.java:110)
	at com.google.devtools.build.buildjar.SimpleJavaLibraryBuilder.run(SimpleJavaLibraryBuilder.java:118)
	at com.google.devtools.build.buildjar.BazelJavaBuilder.build(BazelJavaBuilder.java:97)
	at com.google.devtools.build.buildjar.BazelJavaBuilder.parseAndBuild(BazelJavaBuilder.java:77)
	at com.google.devtools.build.lib.worker.WorkRequestHandler.respondToRequest(WorkRequestHandler.java:115)
	at com.google.devtools.build.lib.worker.WorkRequestHandler.lambda$createResponseThread$0(WorkRequestHandler.java:98)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.ExceptionInInitializerError
	at com.google.auto.value.processor.AutoValueProcessor.processType(AutoValueProcessor.java:227)
	at com.google.auto.value.processor.AutoValueOrOneOfProcessor.process(AutoValueOrOneOfProcessor.java:310)
	at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment.callProcessor(JavacProcessingEnvironment.java:972)
	at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs(JavacProcessingEnvironment.java:888)
	at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1214)
	at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1326)
	at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1258)
	at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:936)
	at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.lambda$doCall$0(JavacTaskImpl.java:104)
	at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.handleExceptions(JavacTaskImpl.java:147)
	... 12 more
Caused by: java.lang.IllegalStateException: zip file closed
	at java.base/java.util.zip.ZipFile.ensureOpen(ZipFile.java:915)
	at java.base/java.util.zip.ZipFile.getInputStream(ZipFile.java:378)
	at java.base/java.util.jar.JarFile.getInputStream(JarFile.java:835)
	at java.base/sun.net.www.protocol.jar.JarURLConnection.getInputStream(JarURLConnection.java:167)
	at java.base/java.net.URLClassLoader.getResourceAsStream(URLClassLoader.java:328)
	at java.base/java.lang.Class.getResourceAsStream(Class.java:2650)
	at com.google.auto.value.processor.TemplateVars.readerFromResource(TemplateVars.java:139)
	at autovalue.shaded.com.google$.escapevelocity.$Parser.parseParse($Parser.java:427)
	at autovalue.shaded.com.google$.escapevelocity.$Parser.parseDirective($Parser.java:331)
	at autovalue.shaded.com.google$.escapevelocity.$Parser.parseNode($Parser.java:218)
	at autovalue.shaded.com.google$.escapevelocity.$Parser.parseTokens($Parser.java:126)
	at autovalue.shaded.com.google$.escapevelocity.$Parser.parse($Parser.java:118)
	at autovalue.shaded.com.google$.escapevelocity.$Template.parseFrom($Template.java:101)
	at com.google.auto.value.processor.TemplateVars.parsedTemplateForResource(TemplateVars.java:119)
	at com.google.auto.value.processor.AutoValueTemplateVars.<clinit>(AutoValueTemplateVars.java:145)
	... 22 more
```

Link: https://buildkite.com/bazel/google-bazel-presubmit/builds/47141#c2bc4e84-f29f-435a-821f-27f2e69bdb7b

**Comment by coeuvre** [comment] 2021-06-09 03:28
@katre any ideas?

**Comment by katre** [comment] 2021-06-09 11:47
This is really odd. Looks like AutoValue uses this TemplateVars system when creating the source code for a class, when instantiating the autovalue.vm template (I had no idea that was how it worked).

This exception seems to say that the annotation processor is trying to handle writing the generated source code, but some jar file it depends on is either unexpectedly closed or something else has gone wrong. Of course it can't actually do anything useful like tell us which jar file it is.

[`ExecGroupCollection`](https://cs.opensource.google/bazel/bazel/+/master:src/main/java/com/google/devtools/build/lib/analysis/ExecGroupCollection.java) isn't doing anything unusual with AutoValue. Are we sure this is only happening for `ExecGroupCollection`?

The only other option I can think of is that there's an undeclared dependency for exec_group_collection and it's being read in a flaky way. Are we building in a sandbox?

**Comment by philwo** [comment] 2021-06-10 14:03
Could this be caused by multiplexed workers (which runs multiple Javac invocations via multi-threading in the same thread) and the annotation processor not being thread-safe?

**Comment by philwo** [comment] 2021-06-10 14:05
I don't know if this should belong to team-Rules-Java, team-Local-Exec or team-XProduct - WDYT?

**Comment by coeuvre** [comment] 2021-06-11 03:18
It's weird that, for the same build, the one on windows machine also failed with the same error.

https://buildkite.com/bazel/google-bazel-presubmit/builds/47141#a822e801-08c7-4919-876c-6cbdaaa99231

**Comment by katre** [comment] 2021-06-21 15:24
This is not a configurability issue. Re-assigning to Local Exec.

**Comment by coeuvre** [comment] 2021-06-22 06:39
Just encountered this error locally when trying to build a bazel binary:

```
❯ bazelisk build //src:bazel
Starting local Bazel server and connecting to it...
DEBUG: [DEDUCTED]/external/bazel_toolchains/rules/rbe_repo/version_check.bzl:68:14: 
Current running Bazel is ahead of bazel-toolchains repo. Please update your pin to bazel-toolchains repo in your WORKSPACE file.
DEBUG: [DEDUCTED]/external/bazel_toolchains/rules/rbe_repo/checked_in.bzl:103:14: rbe_ubuntu1804_java11 not using checked in configs as detect_java_home was set to True 
DEBUG: [DEDUCTED]/external/bazel_toolchains/rules/rbe_repo/version_check.bzl:68:14: 
Current running Bazel is ahead of bazel-toolchains repo. Please update your pin to bazel-toolchains repo in your WORKSPACE file.
DEBUG: [DEDUCTED]/external/bazel_toolchains/rules/rbe_repo/checked_in.bzl:103:14: rbe_ubuntu1604_java8 not using checked in configs as detect_java_home was set to True 
INFO: Analyzed target //src:bazel (332 packages loaded, 9234 targets configured).
INFO: Found 1 target...
INFO: From Building external/com_google_protobuf/java/util/libutil.jar (8 source files):
warning: -parameters is not supported for target value 1.7. Use 1.8 or later.
ERROR: [DEDUCTED]/src/main/java/com/google/devtools/build/lib/analysis/BUILD:1644:13: Building src/main/java/com/google/devtools/build/lib/analysis/libconfig/config_conditions.jar (1 source file) and running annotation processors (AutoAnnotationProcessor, AutoValueProcessor) failed: (Exit 1): java failed: error executing command external/remotejdk11_macos/bin/java -XX:+UseParallelOldGC -XX:-CompactStrings '--patch-module=java.compiler=external/remote_java_tools_darwin/java_tools/java_compiler.jar' ... (remaining 15 argument(s) skipped)
java.lang.RuntimeException: java.lang.ExceptionInInitializerError
        at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.handleExceptions(JavacTaskImpl.java:163)
        at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.doCall(JavacTaskImpl.java:100)
        at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:94)
        at com.google.devtools.build.buildjar.javac.BlazeJavacMain.compile(BlazeJavacMain.java:123)
        at com.google.devtools.build.buildjar.ReducedClasspathJavaLibraryBuilder.fallback(ReducedClasspathJavaLibraryBuilder.java:103)
        at com.google.devtools.build.buildjar.ReducedClasspathJavaLibraryBuilder.compileSources(ReducedClasspathJavaLibraryBuilder.java:65)
        at com.google.devtools.build.buildjar.SimpleJavaLibraryBuilder.compileJavaLibrary(SimpleJavaLibraryBuilder.java:110)
        at com.google.devtools.build.buildjar.SimpleJavaLibraryBuilder.run(SimpleJavaLibraryBuilder.java:118)
        at com.google.devtools.build.buildjar.BazelJavaBuilder.build(BazelJavaBuilder.java:97)
        at com.google.devtools.build.buildjar.BazelJavaBuilder.parseAndBuild(BazelJavaBuilder.java:77)
        at com.google.devtools.build.lib.worker.WorkRequestHandler.respondToRequest(WorkRequestHandler.java:115)
        at com.google.devtools.build.lib.worker.WorkRequestHandler.lambda$createResponseThread$0(WorkRequestHandler.java:98)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.ExceptionInInitializerError
        at com.google.auto.value.processor.AutoValueProcessor.processType(AutoValueProcessor.java:227)
        at com.google.auto.value.processor.AutoValueOrOneOfProcessor.process(AutoValueOrOneOfProcessor.java:310)
        at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment.callProcessor(JavacProcessingEnvironment.java:972)
        at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs(JavacProcessingEnvironment.java:888)
        at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1214)
        at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1326)
        at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1258)
        at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:936)
        at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.lambda$doCall$0(JavacTaskImpl.java:104)
        at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.handleExceptions(JavacTaskImpl.java:147)
        ... 12 more
Caused by: java.lang.IllegalStateException: zip file closed
        at java.base/java.util.zip.ZipFile.ensureOpen(ZipFile.java:915)
        at java.base/java.util.zip.ZipFile.getEntry(ZipFile.java:347)
        at java.base/java.util.zip.ZipFile$1.getEntry(ZipFile.java:1121)
        at java.base/java.util.jar.JarFile.getEntry0(JarFile.java:576)
        at java.base/java.util.jar.JarFile.getEntry(JarFile.java:506)
        at java.base/sun.net.www.protocol.jar.URLJarFile.getEntry(URLJarFile.java:131)
        at java.base/sun.net.www.protocol.jar.JarURLConnection.connect(JarURLConnection.java:137)
        at java.base/sun.net.www.protocol.jar.JarURLConnection.getInputStream(JarURLConnection.java:155)
        at java.base/java.net.URLClassLoader.getResourceAsStream(URLClassLoader.java:328)
        at java.base/java.lang.Class.getResourceAsStream(Class.java:2650)
        at com.google.auto.value.processor.TemplateVars.readerFromResource(TemplateVars.java:139)
        at autovalue.shaded.com.google$.escapevelocity.$Template.parseFrom($Template.java:100)
        at com.google.auto.value.processor.TemplateVars.parsedTemplateForResource(TemplateVars.java:119)
        at com.google.auto.value.processor.AutoValueTemplateVars.<clinit>(AutoValueTemplateVars.java:145)
        ... 22 more
Target //src:bazel failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 159.105s, Critical Path: 70.44s
INFO: 990 processes: 13 internal, 493 darwin-sandbox, 484 worker.
FAILED: Build did NOT complete successfully
```

```
❯ bazelisk version
Bazelisk version: v1.6.0
Build label: 4.1.0
Build target: bazel-out/darwin-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Fri May 21 11:16:55 2021 (1621595815)
Build timestamp: 1621595815
Build timestamp as int: 1621595815
```

**Comment by philwo** [comment] 2021-06-22 07:44
FYI @larsrc-google

**Comment by larsrc-google** [comment] 2021-06-22 09:43
FYI @cushon

**Comment by larsrc-google** [comment] 2021-06-29 15:28
@coeuvre How reproducible is this? Have you tried reproducing it outside of BuildKite?

**Comment by coeuvre** [comment] 2021-06-30 04:22
I just encountered this error once on my Macbook recently when building Bazel normally with command `bazel build //src:bazel`.

**Comment by larsrc-google** [comment] 2021-06-30 11:34
Excellent! Can you tell me what you had in applicable `.bazelrc`s? If I get a close enough repro, I can just set my MacBook to try until I get a failure.

**Comment by coeuvre** [comment] 2021-07-01 02:08
I didn't introduce any extra flags with `.bazelrc`. The repro should be (did't test though):
1. Get bazel 4.1.0
2. Clone https://github.com/bazelbuild/bazel
3. Build `bazel build //src:bazel`
4. If no error, clean and go back to 3.

**Comment by philwo** [comment] 2021-09-03 15:25
We're seeing this flakily on Bazel CI:
- https://buildkite.com/bazel/bazel-bazel/builds/17236#8c3e1a5a-886d-40ad-8006-ce48b98ad475
- https://buildkite.com/bazel/bazel-bazel/builds/17233#a638f918-52e8-4600-b903-6bd187146d42

**Comment by cushon** [comment] 2021-09-08 18:39
```
Caused by: java.lang.IllegalStateException: zip file closed
...
        at com.google.auto.value.processor.TemplateVars.readerFromResource(TemplateVars.java:139)
```

Based on the line numbers the build is using a version of AutoValue before https://github.com/google/auto/commit/f17d298a901683c0d1b0a05fa093a5936c7abcc5#diff-e48ebe2cbfa7884ad774ad31708c166f58b1572d20f7bf91b8766073b2754945L139

That changes is working around [JDK-6947916: JarURLConnection does not handle useCaches correctly](https://bugs.openjdk.java.net/browse/JDK-6947916) by catching an `IllegalStateException`.

The JDK bug is supposed to be fixed in JDK 9, so this might be a different issue with the same symptoms, but either way updating AutoValue will probably help: https://github.com/bazelbuild/bazel/pull/13956

**Closed** 2023-04-26 15:04 UTC
Labels: type: bug, P2, team-Local-Exec
