### ISSUE TITLE
Bazel crash after canonical repo name separator change

### ISSUE THREAD

**Issue by tpudlik** [bazelbuild/bazel#23216] opened 2024-08-05 23:21 UTC
### Description of the bug:

https://github.com/bazelbuild/bazel/commit/60924fdc2972184494f6382d39e8c786aa14b9a9 causes Bazel to crash when building my project:

```
Caused by: com.google.devtools.build.lib.cmdline.LabelSyntaxException: invalid repository name 'pigweed~': repo names may contain only A-Z, a-z, 0-9, '-', '_', '.' and '+'
```

Note that none of the repositories involved contain the string `pigweed~`, so (as far as I can tell) the problem is not the trivial one that we hardcode the tilde somewhere.

@Wyverald 

### Which category does this issue belong to?

External Dependency

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

I don't have a minimal repo yet, but here's a not-quite-minimal one:

```
git clone https://pigweed.googlesource.com/pigweed/examples
cd examples
git submodule update --init
# Edit `.bazelversion to point to 60924fdc2972184494f6382d39e8c786aa14b9a9
bazelisk build //...
```

This produces,

```
FATAL: bazel crashed due to an internal error. Printing stack trace:
java.lang.RuntimeException: Unrecoverable error while evaluating node 'ActionLookupData0{actionLookupKey=ConfiguredTargetKey{label=//libraries/pw_board_led_host:pw_board_led_host, config=BuildConfigurationKey[c82b5d5554450eaba3ca1dfae135430ff2b7c9ce6851543931912b63159b76c8]}, actionIndex=0}' (requested by nodes 'TargetCompletionKey{topLevelArtifactContext=com.google.devtools.build.lib.analysis.TopLevelArtifactContext@90904c3b, actionLookupKey=ConfiguredTargetKey{label=//libraries/pw_board_led_host:pw_board_led_host, config=BuildConfigurationKey[c82b5d5554450eaba3ca1dfae135430ff2b7c9ce6851543931912b63159b76c8]}, willTest=false}', 'ActionLookupData1{actionLookupKey=ConfiguredTargetKey{label=//libraries/pw_board_led_host:pw_board_led_host, config=BuildConfigurationKey[c82b5d5554450eaba3ca1dfae135430ff2b7c9ce6851543931912b63159b76c8]}, actionIndex=1}')
        at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:547)
        at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:439)
        at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinPool.scan(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
Caused by: java.util.concurrent.CompletionException: com.google.devtools.build.lib.cmdline.LabelSyntaxException: invalid repository name 'pigweed~': repo names may contain only A-Z, a-z, 0-9, '-', '_', '.' and '+'
        at com.github.benmanes.caffeine.cache.LocalLoadingCache.lambda$newMappingFunction$3(LocalLoadingCache.java:204)
        at com.github.benmanes.caffeine.cache.BoundedLocalCache.lambda$doComputeIfAbsent$13(BoundedLocalCache.java:2451)
        at java.base/java.util.concurrent.ConcurrentHashMap.compute(Unknown Source)
        at com.github.benmanes.caffeine.cache.BoundedLocalCache.doComputeIfAbsent(BoundedLocalCache.java:2449)
        at com.github.benmanes.caffeine.cache.BoundedLocalCache.computeIfAbsent(BoundedLocalCache.java:2432)
        at com.github.benmanes.caffeine.cache.LocalCache.computeIfAbsent(LocalCache.java:107)
        at com.github.benmanes.caffeine.cache.LocalLoadingCache.get(LocalLoadingCache.java:57)
        at com.google.devtools.build.lib.cmdline.RepositoryName.createUnvalidated(RepositoryName.java:97)
        at com.google.devtools.build.lib.cmdline.PackageIdentifier.discoverFromExecPath(PackageIdentifier.java:107)
        at com.google.devtools.build.lib.skyframe.ActionExecutionFunction$PackageRootResolverWithEnvironment.findPackageRootsForFiles(ActionExecutionFunction.java:733)
        at com.google.devtools.build.lib.actions.ArtifactFactory.resolveSourceArtifacts(ArtifactFactory.java:489)
        at com.google.devtools.build.lib.actions.ActionCacheChecker.getCachedInputs(ActionCacheChecker.java:828)
        at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.getActionCachedInputs(SkyframeActionExecutor.java:805)
        at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.collectInputs(ActionExecutionFunction.java:633)
        at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.computeInternal(ActionExecutionFunction.java:264)
        at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.compute(ActionExecutionFunction.java:189)
        at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:467)
        ... 7 more
Caused by: com.google.devtools.build.lib.cmdline.LabelSyntaxException: invalid repository name 'pigweed~': repo names may contain only A-Z, a-z, 0-9, '-', '_', '.' and '+'
        at com.google.devtools.build.lib.cmdline.LabelParser.syntaxErrorf(LabelParser.java:208)
        at com.google.devtools.build.lib.cmdline.RepositoryName.validate(RepositoryName.java:167)
        at com.google.devtools.build.lib.cmdline.RepositoryName.lambda$static$0(RepositoryName.java:67)
        at com.github.benmanes.caffeine.cache.LocalLoadingCache.lambda$newMappingFunction$3(LocalLoadingCache.java:197)
        ... 23 more
```

### Which operating system are you running Bazel on?

Linux

### If this is a regression, please try to identify the Bazel commit where the bug was introduced with bazelisk --bisect.

I confirmed using bazelisk bisect that the issue starts at this commit.

**Comment by tpudlik** [comment] 2024-08-05 23:30
Sorry, my repro instructions are not quite correct. This is actually a caching issue.

Actual repro steps:

1. `bazelisk build //...` the repo at some earlier Bazel version (without touching `.bazelversion`).
2. Update to https://github.com/bazelbuild/bazel/commit/60924fdc2972184494f6382d39e8c786aa14b9a9
3. Try again, and observe the crash!

This also works going the other way, except that the error message complains about `pigweed+` instead of `pigweed~`.

**Comment by Wyverald** [comment] 2024-08-05 23:34
Looks like a dupe of https://github.com/bazelbuild/bazel/issues/23180

**Closed by Wyverald** 2024-08-05 23:34 UTC
Labels: type: bug, team-ExternalDeps, untriaged
