### ISSUE TITLE
Unexpected keyword 'maxsplit', for call to method split(sep, maxsplit = None) of 'string'

### ISSUE THREAD

**Issue by vam-google** [bazelbuild/bazel#9998] opened 2019-10-11 19:49 UTC
### Description of the problem / feature request:

The `maxsplit` argument in `string.split()` method is a positional argument now, but it is still documented as [split(sep, maxsplit = None)](https://docs.bazel.build/versions/1.0.0/skylark/lib/string.html#split). 

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Call:
```bzl
"a=b".split("=", maxsplit = 1) 
``` 
anywhere in Starlark code. It works for bazel `0.28.1` and below, but the following for bazel `1.0.0`:
```
unexpected keyword 'maxsplit', for call to method split(sep, maxsplit = None) of 'string'`
```

The documentation is not updated and it is a breaking change for 1.0.0

**Comment by vam-google** [comment] 2019-10-11 19:52
Ah, whatever, not worth the trouble, probably...

**Comment by jmillikin-stripe** [comment] 2019-10-16 04:48
This is breaking the Kubernetes build (at https://github.com/kubernetes/kubernetes/blob/v1.16.2/build/code_generation.bzl#L44):
```python
return go_prefix + "/" + pkg.replace("staging/src/", "vendor/", maxsplit = 1)
```

cc @dslomov (release shepherd of v1.0)

**Comment by jin** [comment] 2019-10-16 15:28
@laurentlb

**Comment by meisterT** [comment] 2019-10-17 14:47
I assume https://github.com/bazelbuild/bazel/issues/8147 is related cc @c-parsons

**Comment by laurentlb** [comment] 2020-04-29 16:32
fyi @alandonovan 
`"a=b".split("=", maxsplit = 1)` is allowed in Python 3 and rejected in Python 2.

I think `maxsplit` was marked as positional-only in Bazel by accident.

**Comment by gregestren** [comment] 2020-07-07 19:53
What's the right priority for this?

**Comment by alandonovan** [comment] 2020-07-07 20:30
I think this is the resolution of https://github.com/bazelbuild/bazel/issues/8147 working as intended.

As with Python, nearly all parameters of Starlark built-in functions are positional only; the documentation promises to be explicit in every case where named arguments are permitted, but falls slightly short. The true list is: int(x, base), fail(sep), min(key), max(key), sorted(key, reverse). I'm not sure why Python3 decided to permit maxsplit to be named where Python2 rejected it. (Perhaps passing a second separator string for maxsplit was a frequent mistake?) Conversely, Python2 accepts int(x=1) but Python3 rejects it. I don't think it's worth adding it back.

See also go.starlark.net: https://github.com/google/starlark-go/issues/292

**Closed** 2020-07-10 12:51 UTC
Labels: P1, team-Starlark, type: bug

**Comment by alandonovan** [comment] 2020-07-10 14:26
Let's re-open this as a documentation issue.

The task is to ensure that the starlark spec makes plain that all core builtins reject named arguments, except for the following: `int(x, base)`, `fail(sep)`, `min(key)`, `max(key)`, `sorted(key, reverse)`.
