### ISSUE TITLE
Bazel 0.9 stop working on Windows10

### ISSUE THREAD

**Issue by susiwen8** [bazelbuild/bazel#4353] opened 2017-12-25 10:37 UTC
I installed Bazel 0.9 on Windows10 by Chocolatey, but when I run bazel, there is pop out window to tell me "bazel.exe has stopped working".  Does this occur to anyone else?

**Comment by mhlopko** [comment] 2018-01-02 17:04
Assigning to Laszlo, he will know how to obtain more debug information :)

**Comment by laszlocsomor** [comment] 2018-01-03 07:38
@susiwen8 : Is there more information, like an error code? I've seen similar errors when the `PATH` environment variable was set up incorrectly.

Try this workaround:

1. open `cmd.exe`
2. call `set PATH=c:\tools\msys64\bin;c:\tools\msys64\usr\bin;c:\python27;c:\windows\system32`

  Adjust the paths as needed for your platform.

3. Try running Bazel from this command prompt.

**Comment by jeness** [comment] 2018-02-03 10:23
Already set system path as above. But Bazel still stops working when run `bazel version` or `bazel`.

**Comment by laszlocsomor** [comment] 2018-02-05 08:12
@jeness :  Is there more information, like an error code?

**Comment by buchgr** [comment] 2018-03-21 15:25
Can this be closed @laszlocsomor?

**Comment by laszlocsomor** [comment] 2018-03-21 15:49
I don't know what was the original issue or if it got resolved. Since there were no more updates, I can only assume a transient failure and as such declare this bug non-reproducible.

**Closed** 2018-05-02 09:47 UTC
Labels: P4, category: misc > misc, platform: windows, type: bug
