### ISSUE TITLE
Exclude files with specific suffix

### ISSUE THREAD

**Issue by theGreatWhiteShark** [bazelbuild/bazel#1958] opened 2016-10-17 22:03 UTC
Hey,

Using an editor saving backups automatically I encounter the following issue on a regular basis.

> CONFLICT: layout/activity_main is provided with ambiguous priority from: 
>         res/layout/activity_main.xml~
>         res/layout/activity_main.xml 

I can of course use the _exclude_ directive in the glob function
`glob( [ "res/**/*" ], exclude = [ "res/**/*~" ] )`

But is it/would it be possible to specify certain suffixes in the .bazelrc similar to an .gitignore? 

Thanks

**Comment by laszlocsomor** [comment] 2016-10-31 14:48
I'd rather not do that. The `BUILD` file should completely define how the build is done. If the project needed certain `.bazelrc` entries to build correctly then that invariant would be violated.

Can you configure your editor to place scratch files somewhere else? That'd be the simplest solution IMO.

**Comment by laszlocsomor** [comment] 2016-10-31 14:52
Closing for now as this is working as intended.

**Closed by laszlocsomor** 2016-10-31 14:52 UTC
