### ISSUE TITLE
Could not find a JDK for host execution environment

### ISSUE THREAD

**Issue by comius** [bazelbuild/bazel#12686] opened 2020-12-11 07:32 UTC
Reporter: @konste

### Description of the problem / feature request:

I want to apologize upfront - I am very tired at the moment and may miss something obvious.
I try to use 4.0 RC6 on Linux (Ubuntu and CentOS) and get the error `external/bazel_tools/tools/jdk/BUILD:485:6: Configurable attribute "actual" doesn't match this configuration: Could not find a JDK for host execution environment`  It points to this `alias`: 
```
alias(
    name = "remote_jdk11",
    actual = select(
        {
            "//src/conditions:darwin": "@remotejdk11_macos//:jdk",
            "//src/conditions:windows": "@remotejdk11_win//:jdk",
            "//src/conditions:linux_aarch64": "@remotejdk11_linux_aarch64//:jdk",
            "//src/conditions:linux_x86_64": "@remotejdk11_linux//:jdk",
            "//src/conditions:linux_ppc64le": "@remotejdk11_linux_ppc64le//:jdk",
            "//src/conditions:linux_s390x": "@remotejdk11_linux_s390x//:jdk",
        },
        no_match_error = "Could not find a JDK for host execution environment, please explicitly" +
                         " provide one using `--host_javabase.`",
    ),
```

So it does not recognize that I run on linux_x86_64. I looked at `//src/conditions` and noticed that it changed. In 3.7.0 it looked like 
```
config_setting(
    name = "linux_x86_64",
    values = {"cpu": "k8"},
    visibility = ["//visibility:public"],
)
```
and in 4.0 it changed to 
```
config_setting(
    name = "linux_x86_64",
    constraint_values = [ "@platforms//os:linux", "@platforms//cpu:x86_64" ],
    visibility = ["//visibility:public"],
)
```
Could it be some --incompatible flag I am missing? I don't understand why 4.0 version of this config_setting is not recognized. 

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

> Replace this line with your answer.

### What operating system are you running Bazel on?

linux

### What's the output of `bazel info release`?

4.0.0rc

**Comment by comius** [comment] 2020-12-11 07:35
cc @konste

**Comment by comius** [comment] 2020-12-11 07:51
Bazel should work out of the box.

My best guess is that either you are using some flags or that autodetection is failing.

Are you using any of platform flags, for example  `--platforms`, `--exec_platform`, `--extra_execution_platforms`?

What linux distribution do you have?
Autodetection happens here: https://github.com/bazelbuild/bazel/blob/master/src/main/java/com/google/devtools/build/lib/bazel/repository/LocalConfigPlatformFunction.java
What is the output of `bazel query --output=build @local_config_platform//:host`?
What is the output of `java -XshowSettings`, keys `os.arch` and `os.name`?

**Comment by comius** [comment] 2020-12-11 07:52
cc @katre

**Comment by konste** [comment] 2020-12-11 10:29
Thank you @comius for your prompt attention!
After I gave myself a few hours to sleep I guessed which flag caused the problem: `--platform_mappings`
We have `platform_mappings` file which looks like this:
```
platforms:
  # Maps "@tab_toolchains//bazel/platforms:x86_windows" to "--cpu=x86_windows".
  @tab_toolchains//bazel/platforms:x86_windows
    --cpu=x86_windows

  # Maps "@tab_toolchains//bazel/platforms:x64_windows" to "--cpu=x64_windows".
  @tab_toolchains//bazel/platforms:x64_windows
    --cpu=x64_windows

  @tab_toolchains//bazel/platforms:emscripten
    --cpu=asmjs

  @tab_toolchains//bazel/platforms:osx
    --cpu=darwin

  @tab_toolchains//bazel/platforms:linux
    --cpu=k8

flags:
  # Maps "--cpu=x86_windows" to "@tab_toolchains//bazel/platforms:x86_windows".
  --cpu=x86_windows
    @tab_toolchains//bazel/platforms:x86_windows

  # Maps "--cpu=x64_windows" to "@tab_toolchains//bazel/platforms:x64_windows".
  --cpu=x64_windows
    @tab_toolchains//bazel/platforms:x64_windows

  --cpu=asmjs
    @tab_toolchains//bazel/platforms:emscripten

  --cpu=darwin
    @tab_toolchains//bazel/platforms:osx

  --cpu=k8
    @tab_toolchains//bazel/platforms:linux
 ```
The platforms used above are declared in another file like this:
```
constraint_value(
    name = "asmjs",
    constraint_setting = "@platforms//cpu",
) 

platform(
    name = "x86_windows",
    constraint_values = [
        "@platforms//os:windows",
        "@platforms//cpu:x86_32",
    ],
)

platform(
    name = "x64_windows",
    constraint_values = [
        "@platforms//os:windows",
        "@platforms//cpu:x86_64",
    ],
)

platform(
    name = "linux",
    constraint_values = [
        "@platforms//os:linux",
    ],
)

platform(
    name = "osx",
    constraint_values = [
        "@platforms//os:osx",
    ],
)

platform(
    name = "emscripten", # Platform maybe better named Electron.
    constraint_values = [
        "@tab_toolchains//bazel/platforms:asmjs",
    ],
) 
```
It works with 3.7.0 and with 4.0 EXCEPT on Linux. Removing `--platform_mappings` flag on Linux fixes the build, but I am interested in fixing platform_mappings file so that it work for both 3.7.0 and 4.0.

**Comment by katre** [comment] 2020-12-11 13:49
I'm guessing that the issue is that your `@tab_toolchains//bazel/platforms:linux` doesn't set an CPU constraint, and so it doesn't match the `configuration_values` from the config setting, which are `[ "@platforms//os:linux", "@platforms//cpu:x86_64"]`.

Is there a reason your linux platform definition is an os, but no cpu? Is your code actually cpu-independent?

**Comment by konste** [comment] 2020-12-11 19:29
Yes, this is correct, `platform:linux` should have both `os` and `cpu` specified to match the new configuration setting in 4.0. 
Thank you and please close this issue.

**Closed** 2020-12-11 19:32 UTC
Labels: more data needed, team-Configurability, untriaged

**Comment by konste** [comment] 2020-12-12 00:50
@katre @comius While I now know how to make the build work I still don't quite understand why that change helps.
1. Why `--platform_mappings` is even involved? I don't supply target platform on the command line, instead it is autodetected. Why platform mapping is evaluated and what does it affect?
2. Why the previous definition of the Linux platform 
```
platform(
    name = "linux",
    constraint_values = [
        "@platforms//os:linux",
    ],
)
```
was good enough for Bazel 3.7.0, but now must be accompanied by  `"@platforms//cpu:x86_64"` constraint to satisfy Bazel 4.0?

**Comment by katre** [comment] 2020-12-14 13:40
1. Platform mappings are used anytime that the target platform isn't specifically provided: it attempts to find the correct platform based on the other flags you have provided. If the platform autodetection is working for you, I'd suggest not supplying a platform mapping file at all.

2. The redefinition of the `//src/conditions:linux_x86_64` config setting is to make sure it remains useful during the transition away from `--cpu` and toward using platforms. I'm guessing that it worked previously because you also either specifically set the `--cpu` flag to `k8`, or kept the default value. It wasn't actually comparing to a platform previously, and so your previous platform definition for `linux` wasn't considered.
