### ISSUE TITLE
Bazel CI: SkyframeTests is flaky on windows

### ISSUE THREAD

**Issue by michajlo** [bazelbuild/bazel#11138] opened 2020-04-16 19:29 UTC
Example failure: https://buildkite.com/bazel/google-bazel-presubmit/builds/33168#1d7814fc-891d-4523-a31b-2137d46ffdd0

**Comment by jin** [comment] 2020-04-16 19:33
@meteorcloudy can we kick off the autosheriff to detect when this started flaking?

**Comment by meteorcloudy** [comment] 2020-04-17 07:53
Unfortunately, the autosheriff isn't capable of tracing flaky test yet, but that's definitely a great feature to implement!

However, we've seen this issue before, It started since 5aaceb58560da18300576ebebc332fe23e9a0622.
@meisterT I thought we fixed the problem in 1fa34dfdef06ca2091f14d4499bfe50503458d62, do you know what else we could do the reduce the flakiness?

**Comment by meisterT** [comment] 2020-04-17 11:00
I have not been able to repro this so far in a Bazel VM. Creative ideas welcome!

**Comment by meteorcloudy** [comment] 2020-04-20 15:15
@meisterT I couldn't reproduce this, either. 
But does it make sense to also increase the thread number at 
https://github.com/bazelbuild/bazel/blob/40549e7cd1aacd7dda86c7ae52a0363b0737d334/src/main/java/com/google/devtools/build/lib/skyframe/SequencedSkyframeExecutor.java#L689
?

**Comment by meisterT** [comment] 2020-04-20 15:31
Thanks Yun, I'll try that.

**Comment by philwo** [comment] 2020-11-26 10:24
Test seems to be no longer flaky (given a random sampling of recent Buildkite jobs), so closing this. :)

**Closed by philwo** 2020-11-26 10:24 UTC
Labels: area-Windows, team-XProduct, untriaged
