### ISSUE TITLE
Build Encyclopedia: document `genrule.stamp`

### ISSUE THREAD

**Issue by laszlocsomor** [bazelbuild/bazel#4219] opened 2017-12-04 09:48 UTC
Even though `genrule.stamp` is supported in Bazel, not just Blaze, it's not documented publicly.

**Comment by meisterT** [comment] 2020-05-15 13:50
dupe of #4942

**Closed by meisterT** 2020-05-15 13:50 UTC
Labels: P4, team-XProduct, type: documentation

**Comment by alokpr** [comment] 2021-07-12 22:45
This should be reopened. Both issue 4219 and issue 4942 have been closed as dups of each other.

**Comment by meisterT** [comment] 2021-07-13 07:47
@alokpr #4942 is still open.
