### ISSUE TITLE
Update Incompatible Target Skipping docs with @platforms//:incompatible constraint

### ISSUE THREAD

**Issue by philsc** [bazelbuild/bazel#12606] opened 2020-12-02 17:19 UTC
### Description of the problem / feature request:

The WORKSPACE entry for [@platforms](https://github.com/bazelbuild/platforms) points to a version that's over a year old. That means it doesn't have the `@platforms//:incompatible` constraint available.

I'd like to update the [Platforms docs](https://docs.bazel.build/versions/master/platforms.html) to use this new constraint instead of encouraging users to create their own.

This WORKSPACE entry needs to be updated:
https://github.com/bazelbuild/bazel/blob/6202271b9b1bdf1b73b1e2ad55f30cf467899005/WORKSPACE#L748-L756

How do we get the https://mirror.bazel.build mirror updated? I'm guessing that's something a Google employee must do.

I'm happy to update the WORKSPACE entry and the docs via a pull request once the mirror is sorted out.

**Comment by benjaminp** [comment] 2020-12-02 17:54
#11826

**Comment by jin** [comment] 2020-12-03 12:28
Closing as dupe of #11826.

**Closed by jin** 2020-12-03 12:28 UTC

**Comment by philsc** [comment] 2020-12-03 18:49
The intent of this ticket was to keep track of updating the docs, to which updating @platforms is a prerequisite.
That being said, I can submit a doc update PR without referencing a ticket.
