### ISSUE TITLE
IllegalArgumentException from aspect with rules_rust

### ISSUE THREAD

**Issue by googleson78** [bazelbuild/bazel#16664] opened 2022-11-04 20:47 UTC
### Description of the bug:

When trying to run an aspect, Bazel crashes and I get a java callstack.

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

0. Clone https://github.com/dfinity/ic/
1. Switch to `6be560c9b965d9b76e5b85aa052fff5a2937c0c1`
2. Apply the *patch
3. Run `bazel run --config=local @rules_rust//tools/rust_analyzer:gen_rust_project -- //rs/...`

You may have to have at least these system dependencies installed (on ubuntu 22.04):
```
openssl
bazelisk
gcc
g++
libunwind-dev
pkg-config
libssl-dev
llvm-dev
libclang-dev
zlib1g-dev
make
libsqlite3-dev
```

*patch:
```diff
diff --git a/WORKSPACE.bazel b/WORKSPACE.bazel
index bb13be238..3ef389a84 100644
--- a/WORKSPACE.bazel
+++ b/WORKSPACE.bazel
@@ -34,6 +34,10 @@ rust_register_toolchains(
     version = "1.60.0",
 )

+load("@rules_rust//tools/rust_analyzer:deps.bzl", "rust_analyzer_dependencies")
+
+rust_analyzer_dependencies()
+
 git_repository(
     name = "rules_foreign_cc",
     commit = "b1e65fec980c59cf5c2e21f7eb90fed331c36c66",
```

### Which operating system are you running Bazel on?

Ubuntu

### What is the output of `bazel info release`?

`release 5.3.1`

### What's the output of `git remote get-url origin; git rev-parse master; git rev-parse HEAD` ?

```text
git@github.com:dfinity/ic.git
5a5effbfb192134fb2d9ea149eef4f1b5f7f0fc5
6be560c9b965d9b76e5b85aa052fff5a2937c0c1
```

### Any other information, logs, or outputs that you want to share?

<details>
<summary>Click to expand for a stack trace</summary>

```
FATAL: bazel crashed due to an internal error. Printing stack trace:
java.lang.RuntimeException: Unrecoverable error while evaluating node '[]#@rules_rust//rust/private:rust_analyzer.bzl%rust_analyzer_aspect BuildConfigurationValue.Key[389e39032c3f20bb3ba86f31ee6985d1e72d294cda2a6bae39b41c0c768a0c3a] ConfiguredTargetKey{label=//rs/rosetta-api/icp_ledger/ledger:_wasm_ledger-canister-wasm-notify-method-raw, config=BuildConfigurationValue.Key[389e39032c3f20bb3ba86f31ee6985d1e72d294cda2a6bae39b41c0c768a0c3a]} {}' (requested by nodes 'com.google.devtools.build.lib.skyframe.AspectKeyCreator$TopLevelAspectsKey@2d217e55')
  at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:674)
  at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:382)
  at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(Unknown Source)
  at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
  at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source)
  at java.base/java.util.concurrent.ForkJoinPool.scan(Unknown Source)
  at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
  at java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
Caused by: net.starlark.java.eval.Starlark$UncheckedEvalException: IllegalArgumentException thrown during Starlark evaluation (//rs/rosetta-api/icp_ledger/ledger:_wasm_ledger-canister-wasm-notify-method-raw)
  at <starlark>.expand_location(<builtin>:0)
  at <starlark>._create_single_crate(/home/asdf/.cache/bazel/_bazel_asdf/015ad823763018afd0b936c07bd63072/external/rules_rust/rust/private/rust_analyzer.bzl:188)
  at <starlark>._rust_analyzer_aspect_impl(/home/asdf/.cache/bazel/_bazel_asdf/015ad823763018afd0b936c07bd63072/external/rules_rust/rust/private/rust_analyzer.bzl:92)
Caused by: java.lang.IllegalArgumentException: Multiple entries with same key: //rs/rosetta-api/icp_ledger:ledger.did=[File:[/home/asdf/git/ic[source]]rs/rosetta-api/icp_ledger/ledger.did] and //rs/rosetta-api/icp_ledger:ledger.did=[File:[/home/asdf/git/ic[source]]rs/rosetta-api/icp_ledger/ledger.did]
  at com.google.common.collect.ImmutableMap.conflictException(ImmutableMap.java:210)
  at com.google.common.collect.ImmutableMap.checkNoConflict(ImmutableMap.java:204)
  at com.google.common.collect.RegularImmutableMap.checkNoConflictInKeyBucket(RegularImmutableMap.java:146)
  at com.google.common.collect.RegularImmutableMap.fromEntryArray(RegularImmutableMap.java:109)
  at com.google.common.collect.ImmutableMap$Builder.build(ImmutableMap.java:389)
  at com.google.devtools.build.lib.analysis.starlark.StarlarkRuleContext.makeLabelMap(StarlarkRuleContext.java:1102)
  at com.google.devtools.build.lib.analysis.starlark.StarlarkRuleContext.expandLocation(StarlarkRuleContext.java:902)
  at jdk.internal.reflect.GeneratedMethodAccessor109.invoke(Unknown Source)
  at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  at java.base/java.lang.reflect.Method.invoke(Unknown Source)
  at net.starlark.java.eval.MethodDescriptor.call(MethodDescriptor.java:162)
  at net.starlark.java.eval.BuiltinFunction.fastcall(BuiltinFunction.java:77)
  at net.starlark.java.eval.Starlark.fastcall(Starlark.java:619)
  at net.starlark.java.eval.Eval.evalCall(Eval.java:672)
  at net.starlark.java.eval.Eval.eval(Eval.java:489)
  at net.starlark.java.eval.Eval.access$200(Eval.java:56)
  at net.starlark.java.eval.Eval$1Lambda.execClauses(Eval.java:808)
  at net.starlark.java.eval.Eval$1Lambda.execClauses(Eval.java:784)
  at net.starlark.java.eval.Eval.evalComprehension(Eval.java:819)
  at net.starlark.java.eval.Eval.eval(Eval.java:481)
  at net.starlark.java.eval.Eval.evalCall(Eval.java:622)
  at net.starlark.java.eval.Eval.eval(Eval.java:489)
  at net.starlark.java.eval.Eval.exec(Eval.java:271)
  at net.starlark.java.eval.Eval.execStatements(Eval.java:82)
  at net.starlark.java.eval.Eval.execFunctionBody(Eval.java:66)
  at net.starlark.java.eval.StarlarkFunction.fastcall(StarlarkFunction.java:191)
  at net.starlark.java.eval.Starlark.fastcall(Starlark.java:619)
  at net.starlark.java.eval.Eval.evalCall(Eval.java:672)
  at net.starlark.java.eval.Eval.eval(Eval.java:489)
  at net.starlark.java.eval.Eval.evalCall(Eval.java:622)
  at net.starlark.java.eval.Eval.eval(Eval.java:489)
  at net.starlark.java.eval.Eval.evalCall(Eval.java:630)
  at net.starlark.java.eval.Eval.eval(Eval.java:489)
  at net.starlark.java.eval.Eval.exec(Eval.java:271)
  at net.starlark.java.eval.Eval.execStatements(Eval.java:82)
  at net.starlark.java.eval.Eval.execFunctionBody(Eval.java:66)
  at net.starlark.java.eval.StarlarkFunction.fastcall(StarlarkFunction.java:191)
  at net.starlark.java.eval.Starlark.fastcall(Starlark.java:619)
  at com.google.devtools.build.lib.skyframe.StarlarkAspectFactory.create(StarlarkAspectFactory.java:61)
  at com.google.devtools.build.lib.analysis.ConfiguredTargetFactory.createAspect(ConfiguredTargetFactory.java:536)
  at com.google.devtools.build.lib.skyframe.AspectFunction.createAspect(AspectFunction.java:882)
  at com.google.devtools.build.lib.skyframe.AspectFunction.compute(AspectFunction.java:479)
  at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:590)
  at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:382)
  at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(Unknown Source)
  at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
  at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source)
  at java.base/java.util.concurrent.ForkJoinPool.scan(Unknown Source)
  at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
  at java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
```
</details>

**Comment by fmeum** [comment] 2022-11-04 21:21
I think that this crash should reproduce with any `ctx.expand_location` call that duplicates a target due to the use of `buildOrThrow` in https://cs.opensource.google/bazel/bazel/+/1a9e12a94e9df0a151a92b0ddb98b977226256c7:src/main/java/com/google/devtools/build/lib/analysis/starlark/StarlarkRuleContext.java;drc=1a9e12a94e9df0a151a92b0ddb98b977226256c7;l=1158. Instead of a crash, this should probably be a Starlark error. 

rules_rust could potentially use [`Target.label`](https://bazel.build/rules/lib/Target#modules.Target.label) to filter out duplicates and prevent this crash. Unfortunately, the existence of transitions means that the same label may map to different provider collections, so resolving conflicts isn't straightforward. 

@gregestren Have you perhaps already thought about how location expansion can work with transitions? Perhaps the `$(execpath label)` notation has to allow for something like `$(execpath label%attr_name)` to resolve unambiguously?

**Comment by illicitonion** [comment] 2022-11-04 22:32
See also https://github.com/bazelbuild/bazel/issues/14681

**Comment by comius** [comment] 2022-11-17 17:15
Any crashes like this need to be fixed in Bazel as well.

**Closed** 2023-10-24 16:53 UTC
Labels: type: bug, P2, team-Rules-API
