### ISSUE TITLE
Bazel crashes with bad "bind" in WORKSPACE

### ISSUE THREAD

**Issue by janakdr** [bazelbuild/bazel#674] opened 2015-12-02 22:41 UTC
```
diff --git a/WORKSPACE b/WORKSPACE
index 5e57bc4..f3f6135 100644
--- a/WORKSPACE
+++ b/WORKSPACE
@@ -33,6 +33,11 @@ new_http_archive(
 # )
 
 bind(
+    name = "bazel_tools",
+    actual = "//tools",
+)
+
+bind(
     name = "android_sdk_for_testing",
     # Uncomment and delete the //:dummy line to run integration tests.
     #   actual = "@androidsdk//:files",

$ bazel info
$ bazel info
........
java.lang.RuntimeException: Unrecoverable error while evaluating node 'WORKSPACE_FILE:[/usr/local/google/home/janakr/bazel]/[WORKSPACE]' (requested by nodes 'PACKAGE:external')
        at com.google.devtools.build.skyframe.ParallelEvaluator$Evaluate.run(ParallelEvaluator.java:968)
        at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:499)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalStateException: Got a name conflict for local_repository rule //external:bazel_tools, which can't happen: local_repository rule 'bazel_tools' in package 'external' conflicts with existing bind rule
        at com.google.devtools.build.lib.packages.ExternalPackageBuilder.build(ExternalPackageBuilder.java:42)
        at com.google.devtools.build.lib.packages.Package$Builder.finishBuild(Package.java:1301)
        at com.google.devtools.build.lib.packages.Package$Builder.build(Package.java:1332)
        at com.google.devtools.build.lib.skyframe.WorkspaceFileFunction.compute(WorkspaceFileFunction.java:101)
        at com.google.devtools.build.skyframe.ParallelEvaluator$Evaluate.run(ParallelEvaluator.java:932)
        ... 4 more
Caused by: com.google.devtools.build.lib.packages.Package$NameConflictException: local_repository rule 'bazel_tools' in package 'external' conflicts with existing bind rule
        at com.google.devtools.build.lib.packages.Package$Builder.nameConflict(Package.java:1438)
        at com.google.devtools.build.lib.packages.Package$Builder.checkForConflicts(Package.java:1366)
        at com.google.devtools.build.lib.packages.Package$Builder.addRule(Package.java:1217)
        at com.google.devtools.build.lib.packages.ExternalPackageBuilder.build(ExternalPackageBuilder.java:39)
        ... 8 more
```

We should error out gracefully with a bad WORKSPACE file, not crash.

**Comment by kchodorow** [comment] 2015-12-03 16:22
Duplicate of #168.

**Closed by kchodorow** 2015-12-03 16:22 UTC
