### ISSUE TITLE
[8.0.0] Move Bash and Python runfiles libraries out of Bazel

### ISSUE THREAD

**Issue by bazel-io** [bazelbuild/bazel#24534] opened 2024-12-02 18:50 UTC
Forked from #24219

**Comment by jwnimmer-tri** [comment] 2024-12-04 22:04
FYI This is currently a duplicate of #24396.  See also https://github.com/bazelbuild/bazel/pull/24219#issuecomment-2512792583.

**Closed** 2024-12-04 22:26 UTC
Labels: soft-release-blocker
