### ISSUE TITLE
bazel-toolchains broken on CI

### ISSUE THREAD

**Issue by buchgr** [bazelbuild/bazel#4658] opened 2018-02-19 20:53 UTC
```
//test:debian8_clang_autoconfig_test
```

consistently fails on CI (Ubuntu 16.04 and 14.04). Below is a link to the test.log:
https://storage.googleapis.com/bazel-buildkite-artifacts/6d4324f3-0543-47b6-9883-bdd43f18bcf6/test/debian8_clang_autoconfig_test/attempt_3.log

Any guidance @nlopezgi @erain @xingao267 ? Thanks :)

**Comment by xingao267** [comment] 2018-02-20 03:25
I didn't see this test fails consistently on Bazel CI. Could you give me more pointers to the dates or Jenkins links of the test that fail?

This error did occur once in the presubmit test for patch set 1 of https://bazel-review.googlesource.com/#/c/bazel-toolchains/+/38530/, but we should have already fixed that in https://bazel-review.googlesource.com/#/c/bazel-toolchains/+/38870/.

Running the test locally passes ok. I sent a dummy CL to Gerrit just to trigger the presubmit, which seems to pass (https://bazel-review.googlesource.com/#/c/bazel-toolchains/+/40430/). The dashboard for bazel-toolchains project (https://ci.bazel.build/job/bazel-toolchains/) looks ok to me as well.

**Comment by buchgr** [comment] 2018-02-20 17:00
@xingao267 we are moving to a new CI system (Buildkite) and we are seeing the error there. Also `//test:ubuntu-trusty-bazel-head-autoconfig_test` is flaky. I ll send you an invite to Buildkite and you can take a look at the pipeline.

**Comment by xingao267** [comment] 2018-02-20 17:19
Thanks! Will take a look.

**Comment by katre** [comment] 2018-02-20 21:42
This is also failing with the 0.11.0 RC4 build, see here: https://ci.bazel.build/blue/organizations/jenkins/Global%2Fbazel-toolchains/detail/bazel-toolchains/117/tests

I am marking this as a release blocker for #3959 until we can assess severity.

**Comment by xingao267** [comment] 2018-02-21 04:49
I've been trying to reproduce the error locally or on Jenkins (through Gerrit presubmit), but no luck. From the log, it seems that the test is using the wrong container to generate the toolchain configs for the test, but that shouldn't happen (we are pinning to a specific container for this test here https://github.com/bazelbuild/bazel-toolchains/blob/master/WORKSPACE#L54). I'm wondering if it could be some difference in the test setup between Jenkins and Buildkite because on the Jenkins side, the nightly seems fine (https://ci.bazel.build/job/Global/job/bazel-toolchains/). I'll see what I can figure out tomorrow.

I don't think this test failure should block the release of 0.11.0 anyway. It's pretty unlikely that the failure is due to an issue in Bazel binary that runs the test. @nlopezgi WDYT regarding the release blocker?

**Comment by buchgr** [comment] 2018-02-21 10:10
Also, we noticed that `bazel-toolchains` creates about ~50 GiB of docker images in the local docker registry. Would it be possible for your tests to automatically clean up afterwards? We currently call `docker system prune` in our CI scripts, but I think its good practice for tests to clean up afterwards.

**Comment by katre** [comment] 2018-02-21 13:15
@xingao267 This is also failing in the 0.11.0rc4 release tests on Jenkins, see the link I provided.

**Comment by nlopezgi** [comment] 2018-02-21 15:17
@katre we are working out why this test is failing, but this is _not_ a release blocker for 0.11.0. I will provide more info later once we have debugged more with @xingao, thanks.

**Comment by katre** [comment] 2018-02-21 16:01
Thanks for the clarification, I have removed the release blocker label.

**Comment by xingao267** [comment] 2018-02-21 19:01
Although we still couldn't reproduce the error locally or on Jenkins. The error occurred in Buildkite should be fixed in https://bazel-review.googlesource.com/#/c/bazel-toolchains/+/40930/.

Now it is failing due to a different issue. I removed some of the test targets in https://bazel-review.googlesource.com/#/c/bazel-toolchains/+/41030/, but buikdkite is still trying to test them. It's likely a test configuration issue.

**Comment by xingao267** [comment] 2018-02-22 15:52
The tests looks fine now on Buildkite. I'm going to close this issue. I'll open an internal tracking bug for cleaning up docker containers at the end of each test.

**Closed by xingao267** 2018-02-22 15:52 UTC
Labels: P1, breakage

**Comment by buchgr** [comment] 2018-02-22 16:00
thanks @xingao267 !! great work!
