### ISSUE TITLE
Unable to use //... with build or test

### ISSUE THREAD

**Issue by pspeter3** [bazelbuild/bazel#519] opened 2015-10-17 20:24 UTC
It seems that `bazel build //...` or `bazel test //...` will attempt to use 3rdparty dependencies and crash that are not in my workspace and crash

**Comment by lberki** [comment] 2015-10-19 08:53
By "crash" I suppose you mean "returns with an error", right? If it's an actual crash, can you provide a stack trace and/or a reproduction?

If your binary is built after https://github.com/bazelbuild/bazel/commit/c74ee3784d3fd3a722f92c39805e57b4353a4509 ,
you can just delete the tools directory in your workspace and/or remove these lines from $HOME/.bazelrc:

```
build --package_path %workspace%:....base_workspace
fetch --package_path %workspace%:.../base_workspace
query --package_path %workspace%:.../base_workspace
```

Otherwise, you can use `bazel build -k //...` or `bazel build -- //... -//tools/...`

**Comment by lberki** [comment] 2015-10-19 08:54
Closing this as Working As Intended. If the above solutions aren't good enough, please re-open.

**Closed by lberki** 2015-10-19 08:54 UTC

**Comment by pspeter3** [comment] 2015-10-27 02:33
Not having a tools directory still causes the issue to happen and removing the lines from the bazelrc makes it so a lot of tools cannot be used. Out of curiosity, what does the `-k` flag mean?

**Comment by lberki** [comment] 2015-10-27 08:53
-k means "if errors happen, don't stop immediately, but still do as much
work as you can". It's a shorthand for "--keep_going".

Wait, you remove the tools/ directory from your client, remove the
--package_path entries from your .bazelrc and "bazel build //..." still
doesn't work? What error message do you get?

On Tue, Oct 27, 2015 at 3:33 AM, Phips Peter <notifications@github.com>
wrote:

> Not having a tools directory still causes the issue to happen and removing
> the lines from the bazelrc makes it so a lot of tools cannot be used. Out
> of curiosity, what does the -k flag mean?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bazelbuild/bazel/issues/519#issuecomment-151349095>.
>



-- 
Lukács T. Berki | Software Engineer | lberki@google.com |

Google Germany GmbH | Maximillianstr. 11-15 | 80539 München | Germany
| Geschäftsführer: Matthew
Scott Sucherman, Paul Terence Manicle | Registergericht und -nummer:
Hamburg, HRB 86891

**Comment by pspeter3** [comment] 2015-10-27 18:06
I get error messages about the test runtime not existing since it is under the tools directory.

**Comment by lberki** [comment] 2015-10-27 19:26
Whoa. That's interesting. What Bazel version are you using? How does your
workspace look like? Do you have anything interesting in your .bazelrc? How
do any directories referenced in it look like?

Bazel should either use the test runtime embedded into it, the one in the
workspace or the one installed and referenced by .bazelrc . I can't think
of any combination off the top of my head that would cause this issue.
Maybe you accidentally deleted your .bazelrc?

On Tue, Oct 27, 2015 at 7:06 PM, Phips Peter <notifications@github.com>
wrote:

> I get error messages about the test runtime not existing since it is under
> the tools directory.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bazelbuild/bazel/issues/519#issuecomment-151590815>.
>



-- 
Lukács T. Berki | Software Engineer | lberki@google.com |

Google Germany GmbH | Maximillianstr. 11-15 | 80539 München | Germany
| Geschäftsführer: Matthew
Scott Sucherman, Paul Terence Manicle | Registergericht und -nummer:
Hamburg, HRB 86891
