### ISSUE TITLE
Download link not exists. or can not download any files.

### ISSUE THREAD

**Issue by netroby** [bazelbuild/bazel#423] opened 2015-09-05 08:21 UTC
http://bazel.io/docs/install.html

The document link to download bazel installer 
but the page was blank, nothing to download
https://github.com/bazelbuild/bazel/releases

**Comment by damienmg** [comment] 2015-09-07 07:22
This is a duplicate of #403

Until we do the full release (hopefully tomorrow), you can download the release candidate there:
https://storage.googleapis.com/bazel/0.1.0/rc2/index.html

**Closed by damienmg** 2015-09-07 07:22 UTC
