### ISSUE TITLE
GHS custom toolchain with custom rules (hermetic build)

### ISSUE THREAD

**Issue by DhanalakshmiDurairaj** [bazelbuild/bazel#17837] opened 2023-03-21 10:59 UTC
### Description of the bug:

Hi, 
Greetings to all,
I am working on custom GHS toolchain with custom rules.  Custom toolchain is also external dependency. We are referring custom toolchain tools from external directory. I registered toolchain in workspace. It works fine for local execution. In remote execution, we get error "No such file or directory" for the GHS tool (executable). 

Pls help me to fix the issue and figure out where I did wrong.

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

In the custom rules, I configure custom toolchain as below:
cxx_binary = rule(
    _cxx_binary_impl,
    attrs = {
        "srcs": attr.label_list(
            allow_files = [".c", ".h"],
            doc = "Source files to compile for this binary",
        ),
        "deps": attr.label_list(
            providers = [CxxInfo],
        ),
        "_cc_toolchain": attr.label(default = Label("@bazel_tools//tools/cpp:current_cc_toolchain")),
    },
    doc = "Builds an executable program from C++ source code",
    executable = True,
    #    toolchains = ["//toolchain:qnx_suite"],
    toolchains = use_cpp_toolchain(),
)

def _cxx_compile(ctx, src, hdrs, out):
    cc_toolchain = find_cpp_toolchain(ctx)
    args = ctx.actions.args()
    args.add("-o", out)
    args.add("-c")
    args.add("-iquote", ".")
    args.add(src)

    ctx.actions.run(
        executable = cc_toolchain.compiler_executable,
        outputs = [out],
        inputs = [src] + hdrs,
        arguments = [args],
        mnemonic = "CxxCompile",
        use_default_shell_env = True,
    )

### Which operating system are you running Bazel on?

Linux 18.04

### What is the output of `bazel info release`?

bazel 5.4.0

### Any other information, logs, or outputs that you want to share?

**Error as follows:**
external/ghs_compiler/toolchain/wrappers/ccarm -o bazel-out/k8-fastbuild/bin/main/main.c.o -c -iquote . main/main.c)
# Configuration: d20a3da66be757a87363ceeb80fc232cc65357a3a8fbf944e9ce35007bcdac55
# Execution platform: @local_config_platform//:host

Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
src/main/tools/linux-sandbox-pid1.cc:518: "execvp(external/ghs_compiler/toolchain/wrappers/ccarm, 0x23c0380)": **No such file or directory**

**Comment by sgowroji** [comment] 2023-03-21 12:57
Hi @DhanalakshmiDurairaj, Can you provide a sample code sample to reproduce the above issue. Thanks!

**Comment by DhanalakshmiDurairaj** [comment] 2023-03-22 23:11
Hi, 
Thanks a lot. I added tools parameter in ctx.action.run as below:

ctx.actions.run(
        executable = cc_toolchain.compiler_executable,
        tools = cc_toolchain.all_files,
        outputs = [out],
        inputs = [src] + hdrs,
        arguments = [args],
        mnemonic = "CxxCompile",
        use_default_shell_env = True,
    )

Now sandbox execution is working as expected. 
external/ghs_compiler/toolchain/wrappers/ccarm bazel-out/k8-fastbuild/bin/main/main.c.o -o bazel-out/k8-fastbuild/bin/main/hello-world)
# Configuration: c11ebfa482b4c3d0d30fc5caaae6b9e9ef23ddddb61e052d62b04a16b6120789
# Execution platform: @local_config_platform//:host
Target //main:hello-world up-to-date:
  bazel-bin/main/hello-world
INFO: Elapsed time: 17.869s, Critical Path: 4.08s
INFO: 5 processes: 3 internal, 2 linux-sandbox.
INFO: Build completed successfully, 5 total actions

**Comment by DhanalakshmiDurairaj** [comment] 2023-03-24 04:55
Hi 
Greetings to all,
I am working on GHS toolchain.  Ccarm compiler generates “per object debug info file” by providing the flag -G and the extension of the file is .dbo. Debug info file for the archive is .dba. GCC toolchain generates per object debug info file with the extension of .dwo and .dwp (for archive) by providing the flag -gsplit-dwarf. Moreover, I am trying to produce .map file also. How to get these outputs (.dbo,.dba and .map)? Please guide me, is there any way to achieve this without using custom rules?

**Comment by buildbreaker2021** [comment] 2023-04-03 08:49
Hi,
I will close this as this is not a bug.

As for finding the files you listed, they should be somewhere under `blaze-out` directory - I cannot tell exactly where this depends on your workspace. You might want to check our slack channel for more guidance.

**Closed by buildbreaker2021** 2023-04-03 08:49 UTC
Labels: type: bug, team-Rules-CPP, untriaged

**Comment by DhanalakshmiDurairaj** [comment] 2023-05-27 03:21
Hi,
Greetings to all
I have to expand the Tree artifact (that is created using declare_directory). I have to list all files and move them into list variables.
Bazel documentation (https://bazel.build/rules/lib/builtins/DirectoryExpander) talks about 

list DirectoryExpander.expand(file)

If the given File is a directory, this returns a list of Files recursively underneath the directory. Otherwise, this returns a list containing just the given File itself.

Pls help me, how to load this API (DirectoryExpander) which plugin (.bzl) file I have to load

Thanks & Regards,
D.Dhanalakshmi
