### ISSUE TITLE
Use different Java toolchains to compile different `java_library` rules

### ISSUE THREAD

**Issue by shs96c** [bazelbuild/bazel#7868] opened 2019-03-28 11:22 UTC
It's helpful to use different Java toolchains to compile different `java_library` (and other rules, such as protobufs). Two concrete examples include when targeting multi-release jars (#5947), and when a mono-repo contains `java_binary`s that target different JREs.

###  Have you found anything relevant by searching the web?

Not yet, but it looks like #6521 builds the basis on which this feature could be delivered.

**Comment by iirina** [comment] 2019-07-03 12:16
It looks like this is the same as #8735. I added more info on that issue & I'll close this as dupe of #6519 as well.

**Closed by iirina** 2019-07-03 12:16 UTC
Labels: P2, team-Rules-Java
