### ISSUE TITLE
Windows: Paths not relativized properly

### ISSUE THREAD

**Issue by laszlocsomor** [bazelbuild/bazel#1916] opened 2016-10-10 07:12 UTC
Bazel always emits absolute paths in errors on Windows, which is clunky:

```
ERROR: C:/msys64/home/$USER/bazel/example_workspace/cpp/BUILD:3:1: undeclared inclusion(s) in rule '//cpp:hello-lib':
```

or

```
Target //proto:test_proto up-to-date:
  C:/msys64/var/tmp/_blaze_$USER/9b1eed1a423cf04373eb13e215b47824/example_workspace/bazel-out/local_windows_mingw-fastbuild/bin/proto/libtest_proto.jar
```

**Comment by laszlocsomor** [comment] 2017-02-14 12:23
This is a feature request about aesthetics. P3 is accurate, maybe P4 would be fine too.

**Comment by laszlocsomor** [comment] 2019-02-28 14:40
Related: https://github.com/bazelbuild/bazel/issues/7585

This bug and that one should be easy to fix while provide for a somewhat nicer user experience.

**Comment by meisterT** [comment] 2020-05-12 09:42
Closing as it is not a bug, but cosmetics.

**Closed by meisterT** 2020-05-12 09:42 UTC
Labels: P4, platform: windows, team-Windows, type: bug
