### ISSUE TITLE
Worse caching after upgrading Bazel

### ISSUE THREAD

**Issue by rjaquino** [bazelbuild/bazel#654] opened 2015-11-27 09:47 UTC
Platform: Ubuntu 14.04
Version: Build #200 (revision 992d90e1e86a150d6c8acdebca532bc919c3d736)

We recently upgraded Bazel from a pretty old version (pre-sandboxing) to a relatively new version (Build #200 in ci.bazel.io, installed via the shell script). We've noticed much worse caching between builds in CircleCI after upgrading. We have our CircleCI set up pretty similarly to https://groups.google.com/forum/m/#!msg/bazel-discuss/ObH3GCd9L-8/XPWDuXJOCwAJ.

While debugging this issue, I came across the following. If I build a target, then shutdown Bazel (or use the --batch flag) then attempt to rebuild the target, it proceeds as if there is not a cache (it doesn't redownload external files, but does rebuild seemingly all internal files). Is this expected? It is not the behavior we saw with the older version of Bazel in CircleCI. I have not yet had a chance to reinstall the older version of Bazel and confirm this, but the existence of caching in our earlier circle setup heavily implies caching worked between Bazel processes. I couldn't find anything in the docs about artifact cache permanence.

Thanks!

**Comment by damienmg** [comment] 2015-11-27 09:56
First question, is there a specific reason to use build #200 rather than
the release candidate at
https://storage.googleapis.com/bazel/0.1.2/rc2/index.html?

It is definitely not expected and a serious issue. Is the project public so
we can try to reproduce the problem outside of CircleCI?

**Comment by rjaquino** [comment] 2015-11-27 10:06
When we started trying to upgrade, 0.1.1 had bugs that were blocking us from proceeding (and had been fixed) and 0.1.2 didn't have release candidates yet, so we picked a blue build from ci.bazel.io. I'll give the 0.1.2 release candidate a try. It's not a public project, but if I'm still experiencing the issue with 0.1.2, I'll see if I can pull together a minimal example that has the problem. We wrote some custom Skylark rules, so it's also possible we're doing something wrong in there.

**Comment by rjaquino** [comment] 2015-11-27 10:35
Confirmed that the situation is the same in 0.1.2rc2. I'll try to find a minimal example (and in doing so determine which, if any, of our Skylark rules seem to be to blame). Is it possible that we're doing some wrong/broken using Skylark, or is a `bazel shutdown` never supposed to break caching like this? Additionally, is there anything else we can do to help pinpoint the issue? I could try running with the debug version of Bazel posted here https://github.com/bazelbuild/bazel/issues/554 if the output could be of use. I imagine we'll want a shared example before that's helpful, though.

**Comment by damienmg** [comment] 2015-11-27 11:57
bazel shutdown is not breaking caching (it just shutdown the server when
not running in batch mode).

That's likely to be another instance of #554. +Lukács T. Berki
<lberki@google.com> for his expertise and he could advise on #554

**Comment by damienmg** [comment] 2015-11-27 12:22
"bazel shutdown" should never cause actions to be re-run that would not be
re-run otherwise, so this does seem like a bug. There isn't a lot we can do
without being able to reproduce the issue, so a minimal example would be
indeed very useful. I agree that this smells like #554, but let's not
assume that #554 and #654 are duplicates before figuring out what's going
on.

At least could you copy-paste the console output of Bazel on a run where it
ought not to re-run actions, but it did? At least then we'll know what
actions are erroneously re-run.

On Fri, Nov 27, 2015 at 12:57 PM, Damien Martin-guillerez <
dmarting@google.com> wrote:

> bazel shutdown is not breaking caching (it just shutdown the server when
> not running in batch mode).
>
> That's likely to be another instance of #554. +Lukács T. Berki
> <lberki@google.com> for his expertise and he could advise on #554
>
>
> On Fri, Nov 27, 2015 at 11:36 AM R.J. Aquino <notifications@github.com>
> wrote:
>
>> Confirmed that the situation is the same in 0.1.2rc2. I'll try to find a
>> minimal example (and in doing so determine which, if any, of our Skylark
>> rules seem to be to blame). Is it possible that we're doing some
>> wrong/broken using Skylark, or is a bazel shutdown never supposed to
>> break caching like this? Additionally, is there anything else we can do to
>> help pinpoint the issue? I could try running with the debug version of
>> Bazel posted here #554 <https://github.com/bazelbuild/bazel/issues/554>
>> if the output could be of use. I imagine we'll want a shared example before
>> that's helpful, though.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/bazelbuild/bazel/issues/654#issuecomment-160108870>.
>>
>


-- 
Lukács T. Berki | Software Engineer | lberki@google.com |

Google Germany GmbH | Maximillianstr. 11-15 | 80539 München | Germany
| Geschäftsführer: Matthew
Scott Sucherman, Paul Terence Manicle | Registergericht und -nummer:
Hamburg, HRB 86891

**Comment by damienmg** [comment] 2015-11-27 12:24
Wow that's a nice bug in github, last comment is from @lberki.

**Comment by rjaquino** [comment] 2015-11-27 23:32
I worked my way down the dependency tree to find the smallest example that still rebuilds after a `bazel shutdown`. I found an example using one our custom Skylark rules  - it is a single action. Full output will follow - I'm getting permission from my team to share the Skylark, and am working to have a completely isolated example I can send over. The Skylark rule invokes browserify on a file, and uses an externally downloaded node and tar of node_modules. I tried running the debug version of Bazel linked to in #554 , but it not re-run this action. Any advice for determining what "file has changed" (as mentioned in the explain files below) or suggestions for next steps (while I compile the repro-able code) would be appreciated. Thanks for your help so far!

```
$ bazel build //tools/web/imports:assert_bundle --verbose_explanations --explain /tmp/explain.txt > /tmp/build_output
.....................
____Loading package: tools/web/imports
____Loading...
____Loading package: tools/web
____Loading package: @bazel_tools//tools/jdk
____Loading package: @local-jdk//
____Loading package: @node-darwin//
____Loading package: @node_modules//
____Loading complete.  Analyzing...
____Found 1 target...
____Building...
____Writing explanation of rebuilds to '/tmp/explain.txt'
____[0 / 2] BazelWorkspaceStatusAction stable-status.txt
____[1 / 2] Bundling assert_bundle
____Building complete.
Target //tools/web/imports:assert_bundle up-to-date:
  bazel-bin/tools/web/imports/assert_bundle.js
____Elapsed time: 55.663s, Critical Path: 4.34s
```
```
$ bazel build //tools/web/imports:assert_bundle --verbose_explanations --explain /tmp/explain2.txt > /tmp/build_output
____Loading...
____Loading complete.  Analyzing...
____Found 1 target...
____Writing explanation of rebuilds to '/tmp/explain2.txt'
____[0 / 1] BazelWorkspaceStatusAction stable-status.txt
Target //tools/web/imports:assert_bundle up-to-date:
  bazel-bin/tools/web/imports/assert_bundle.js
____Elapsed time: 1.473s, Critical Path: 0.02s
```
```
$ bazel shutdown
$ bazel build //tools/web/imports:assert_bundle --verbose_explanations --explain /tmp/explain3.txt > /tmp/build_output
....................
____Loading package: tools/web/imports
____Loading...
____Loading package: tools/web
____Loading package: @bazel_tools//tools/jdk
____Loading package: @bazel_tools//tools/cpp
____Loading package: @local-jdk//
____Loading package: @node-darwin//
____Loading package: @node-linux//
____Loading package: @node_modules//
____Loading complete.  Analyzing...
____Found 1 target...
____Building...
____Writing explanation of rebuilds to '/tmp/explain3.txt'
____[0 / 2] BazelWorkspaceStatusAction stable-status.txt
____[1 / 2] Bundling assert_bundle
____[1 / 2] Still waiting for 1 job to complete:
      Running (linux-sandboxing):
        Bundling assert_bundle, 4 s
____Building complete.
Target //tools/web/imports:assert_bundle up-to-date:
  bazel-bin/tools/web/imports/assert_bundle.js
____Elapsed time: 59.822s, Critical Path: 5.51s
```

explain.txt and explain3.txt contain
```
Executing action 'Bundling assert_bundle': One of the files has changed.
```

**Comment by rjaquino** [comment] 2015-11-28 00:22
I tried again with the debugging code (this time manually applying the diff to the 0.1.2-release branch), and indeed experience the issue. Debugging output for the rebuild (i.e. the build _after_ the bazel shutdown) is here: https://gist.github.com/rjaquino/78dafdd6b0c64dfc2173. I can get other output if it would be helpful.

**Comment by rjaquino** [comment] 2015-11-28 10:11
Also, fwiw, this happens on OS X as well, so I don't believe it's related to sandboxing.

**Comment by damienmg** [comment] 2015-11-30 08:28
Ok I think I know, see commit f1ffe3621002231fe4828fe4ecfd5f64df9d2052

Can you try latest build (235) :http://ci.bazel.io/job/Bazel/235/?

**Comment by lberki** [comment] 2015-11-30 10:00
@damienmg : I don't think f1ffe36 has anything to do with this, because Bazel doesn't fetch any repositories in the invocation after the server shutdown. @rjaquino : is there a way we can reproduce this on our workstations? It would make debugging much easier. 

Also, how does the output of `bazel build -s` look like? The command line of the action invocation might hide a clue. Maybe it depends on the workspace status artifacts (`stable-status.txt` and friends) and Bazel doesn't handle this correctly after a server restart?

**Comment by rjaquino** [comment] 2015-11-30 11:18
Success! Build 235 no longer demonstrates the issue I've been having. If I build and then shutdown, then build again, the cache is respected and nothing is rebuilt. The output for the toy example is as follows. I'm a bit surprised by the output, since I get `[0/2]` where I was expecting `[0/1]`, but other than the slight difference in output, things seem resolved from my end. Full output is at the end of this comment. 

@lberki , if you'd like to debug further, I can still put together a shareable version of the example I've been using (I didn't get a chance this weekend).

For now, I'll have our team use build 235, assuming it passes our tests. One thing - I only got a chance to try it on linux so far, in Jenkins it's blue for Linux and yellow for darwin - should I be worried about the unstable status for OS X?

Thanks for all your help - I definitely want to return the effort, so let me know if I can be of assistance figuring out what exactly fixed the issue - I'm happy to install older versions and get more output, as well as put together the broken example for you.

First build (fresh installation):
```
____Found 1 target...
____Building...
____[0 / 2] BazelWorkspaceStatusAction stable-status.txt
____[1 / 2] Bundling assert_bundle
____[1 / 2] Still waiting for 1 job to complete:
      Running (linux-sandboxing):
        Bundling assert_bundle, 7 s
____Building complete.
Target //tools/web/imports:assert_bundle up-to-date:
  bazel-bin/tools/web/imports/assert_bundle.js
```
Second build (before shutdown):
```
____Found 1 target...
____Building...
____[0 / 1] BazelWorkspaceStatusAction stable-status.txt
Target //tools/web/imports:assert_bundle up-to-date:
  bazel-bin/tools/web/imports/assert_bundle.js
```

Third build (after shutdown):
```
____Found 1 target...
____Building...
____[0 / 2] BazelWorkspaceStatusAction stable-status.txt
____Building complete.
Target //tools/web/imports:assert_bundle up-to-date:
  bazel-bin/tools/web/imports/assert_bundle.js
```

**Comment by lberki** [comment] 2015-11-30 11:30
On Mon, Nov 30, 2015 at 12:18 PM, R.J. Aquino <notifications@github.com>
wrote:

> Success! Build 235 no longer demonstrates the issue I've been having. If I
> build and then shutdown, then build again, the cache is respected and
> nothing is rebuilt. The output for the toy example is as follows. I'm a bit
> surprised by the output, since I get [0/2] where I was expecting [0/1],
> but other than the slight difference in output, things seem resolved from
> my end. Full output is at the end of this comment.
>
> @lberki <https://github.com/lberki> , if you'd like to debug further, I
> can still put together a shareable version of the example I've been using
> (I didn't get a chance this weekend).
>
> For now, I'll have our team use build 235, assuming it passes our tests.
> One thing - I only got a chance to try it on linux so far, in Jenkins it's
> blue for Linux and yellow for darwin - should I be worried about the
> unstable status for OS X?
>
> Thanks for all your help - I definitely want to return the effort, so let
> me know if I can be of assistance figuring out what exactly fixed the issue
> - I'm happy to install older versions and get more output, as well as put
> together the broken example for you.
>
That would be awesome. Alternativey, you can just "git bisect"  between the
Bazel version with which you know it works and between the one with which
you know it doesn't.

> First build (fresh installation):
>
> ____Found 1 target...
> ____Building...
> ____[0 / 2] BazelWorkspaceStatusAction stable-status.txt
> ____[1 / 2] Bundling assert_bundle
> ____[1 / 2] Still waiting for 1 job to complete:
>       Running (linux-sandboxing):
>         Bundling assert_bundle, 7 s
> ____Building complete.
> Target //tools/web/imports:assert_bundle up-to-date:
>   bazel-bin/tools/web/imports/assert_bundle.js
>
> Second build (before shutdown):
>
> ____Found 1 target...
> ____Building...
> ____[0 / 1] BazelWorkspaceStatusAction stable-status.txt
> Target //tools/web/imports:assert_bundle up-to-date:
>   bazel-bin/tools/web/imports/assert_bundle.js
>
> Third build (after shutdown):
>
> ____Found 1 target...
> ____Building...
> ____[0 / 2] BazelWorkspaceStatusAction stable-status.txt
> ____Building complete.
> Target //tools/web/imports:assert_bundle up-to-date:
>   bazel-bin/tools/web/imports/assert_bundle.js
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bazelbuild/bazel/issues/654#issuecomment-160602404>.
>



-- 
Lukács T. Berki | Software Engineer | lberki@google.com |

Google Germany GmbH | Maximillianstr. 11-15 | 80539 München | Germany
| Geschäftsführer: Matthew
Scott Sucherman, Paul Terence Manicle | Registergericht und -nummer:
Hamburg, HRB 86891

**Comment by damienmg** [comment] 2015-11-30 11:31
No don't worry, that's just a flaky tests, shouldn't be a problem (Yellow means one or more test failed)

Also +1 for getting a repro.

**Comment by kayasoze** [comment] 2015-11-30 19:02
I also experience this issue with older builds.  I'll upgrade and verify.

**Comment by damienmg** [comment] 2016-01-15 16:31
Friendly ping? Can we have a repro?

**Comment by damienmg** [comment] 2016-01-21 18:49
Closing with lack of data.

**Closed by damienmg** 2016-01-21 18:49 UTC
Labels: bug, P1
