### ISSUE TITLE
An `alias` of a test is not treated as a test

### ISSUE THREAD

**Issue by shs96c** [bazelbuild/bazel#11456] opened 2020-05-21 11:09 UTC
### Description of the problem / feature request:

It should be possible to use an `alias` as a `test` in a `test_suite`

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

```py
sh_test(
  name = "test",
  srcs = ["test.sh"],
)

alias(
  name = "alias",
  actual = ":test",
)

test_suite(
  name = "suite",
  tests = [
    ":alias",
  ],
)
```

This is a contrived example to highlight the problem, but it makes clear that `alias` should be considered a test rule if the target being aliased is itself test rule. 

### What's the output of `bazel info release`?

3.1.0

**Comment by sdtwigg** [comment] 2020-05-21 15:47
This is a duplicate of https://github.com/bazelbuild/bazel/issues/10893 .

**Closed by sdtwigg** 2020-05-21 15:47 UTC
Labels: duplicate
