### ISSUE TITLE
Support @argument files in the Java binary wrapper script

### ISSUE THREAD

**Issue by cushon** [bazelbuild/bazel#6355] opened 2018-10-10 22:51 UTC
Related: #6354

JDK 9 adds support for flag files using the `@argument-file` syntax, see "java Command-Line Argument Files" in https://docs.oracle.com/javase/9/tools/java.htm.

We could back-fill support for that syntax for older `--javabase` versions by adding logic to the wrapper script.

**Comment by regisd** [comment] 2018-10-18 06:37
@cushon Duplicate of #6354 ?

**Comment by cushon** [comment] 2018-10-18 06:51
Not quite: #6354 is about adding the feature that was adding in JDK 9, this is about implementing that feature with logic in the wrapper script to support it on older JDKs.

**Comment by lberki** [comment] 2019-03-14 13:19
I'll close this one in favor of #6354 and add the information in the description of this one there.

**Closed by lberki** 2019-03-14 13:19 UTC
Labels: team-Rules-Java, type: feature request, untriaged
