### ISSUE TITLE
Make `cc_shared_library` non-experimental

### ISSUE THREAD

**Issue by lberki** [bazelbuild/bazel#16709] opened 2022-11-09 08:50 UTC
Make the cc_shared_library rule non-experimental after having been tested for enough time by users in different projects.

Major breaking changes after removal of the flag:
- The static_deps attribute is removed. Simply remove the attribute from existing targets. There is no longer a need to list everything that will be linked statically
- The roots attribute has been renamed to deps
- Several bug fixes to the rule where linker_inputs were being dropped may cause new inputs to be passed to the linker compared to previous versions which depending on the build may cause linking errors. To fix, restructure the build graph to avoid those linker inputs if they are a problem

**Comment by lberki** [comment] 2022-11-09 09:14
cc @oquenchil @lizkammer

**Comment by oquenchil** [comment] 2023-03-15 08:00
Flag has been removed. Not yet part of any release.

**Comment by lberki** [comment] 2023-03-15 08:50
🎉

**Comment by brians-neptune** [comment] 2024-03-21 00:41
This looks like it's released, time to close the issue?

**Comment by jsharpe** [comment] 2024-03-21 09:41
`cc_shared_library` still feels buggy in my experience e.g. https://github.com/bazelbuild/bazel/issues/21724 and I've also had issues with `data` deps not propagating properly through a `cc_shared_library` but I've not yet been able to isolate this problem into a simple reproducer.

**Comment by fmeum** [comment] 2024-04-03 09:12
@jsharpe Could you file a separate issue for the problem with `data` propagation? 

I will close this now as the rule is available without a flag in Bazel 7 and issues are fixed as they are being reported, just like for other rules.

**Closed by fmeum** 2024-04-03 09:12 UTC
Labels: type: bug, P1, team-Rules-CPP
