### ISSUE TITLE
Darwin tests fail with "fork: Resource temporarily unavailable"

### ISSUE THREAD

**Issue by vladmos** [bazelbuild/bazel#2902] opened 2017-04-27 11:23 UTC
Example of a failure: http://ci.bazel.io/job/gerrit/BAZEL_VERSION=HEAD,PLATFORM_NAME=ubuntu_16.04-x86_64/328/console

**Comment by damienmg** [comment] 2017-04-27 11:50
We do not have more date right now?

**Comment by damienmg** [comment] 2017-04-27 12:05
So as discussed offline with @vladmos and @philwo, the machine was totally unaccessible (neither by chrome remote desktop nor with the keyboard, the screen got not signal). They had to reboot and the symptom seemed to have gotten away.

It is unclear whether the root cause was bazel or not. I'll leave the issue open for a few month until we see it again. We need to investigate further. If the slave can still be contacted by jenkins itself, jenkins script can be used to investigate resources on the machine, even if login doesn't work.

**Comment by damienmg** [comment] 2017-07-24 21:55
Not happened again, closing now

**Closed by damienmg** 2017-07-24 21:55 UTC
Labels: breakage, category: misc > testing, On hold: more data needed, P2, type: bug
