### ISSUE TITLE
`bazel run` probably fails on long classpaths

### ISSUE THREAD

**Issue by ekuefler** [bazelbuild/bazel#1392] opened 2016-06-13 23:22 UTC
This report is based off reading source code rather than something I've actually repro'd, so apologies if I'm missing something.

Linux tends to limit the max length of a command line to around 128k. This can be a problem for Bazel java compilation since it requires jars for every transitive dep to be specified in the classpath. The java run script [attempts to mitigate this](https://github.com/bazelbuild/bazel/blob/0773430188885e075121ebf720c82bb05a39db21/src/main/java/com/google/devtools/build/lib/bazel/rules/java/java_stub_template.txt#L192) by echoing the classpath to a file and using it as an `@argfile`. But [argfiles are only implemented in stock JDK in Java 9](https://bugs.openjdk.java.net/browse/JDK-8027634), which public Bazel isn't using. So I believe this will fail if anyone tries to `bazel run` a Java binary with a large number of transitive deps.

**Comment by hermione521** [comment] 2016-06-17 12:24
Guess it's a bug. But will label as P4 because I failed to repro. (Got Java "too many constants" JVM error before this "bug")

**Comment by aiuto** [comment] 2019-03-28 02:00
Closing as "Won't Fix - obsolete".
It was not reproducible and we have moved beyond the JVMs in question.

**Closed by aiuto** 2019-03-28 02:00 UTC
Labels: P4, category: misc > misc, type: bug
