### ISSUE TITLE
Release 3.5 - August 2020

### ISSUE THREAD

**Issue by meisterT** [bazelbuild/bazel#11885] opened 2020-08-03 07:01 UTC
Tracking bug for the Bazel 3.5 release. Instructions are at https://github.com/bazelbuild/continuous-integration/blob/master/docs/release-playbook.md

**Comment by aiuto** [comment] 2020-08-06 16:51
Status update:  Branch cut slightly delayed because of power outages after storms in NYC area. Probably will cut on morning of 2020-08-07

**Comment by davido** [comment] 2020-08-10 15:10
> Probably will cut on morning of 2020-08-07

This regression seems to be a release blocker: https://github.com/bazelbuild/bazel/issues/11837?

**Comment by aiuto** [comment] 2020-08-11 03:51
Well. You win. I still have not cut the release because of extenuating
power problems. So the fix in
https://github.com/bazelbuild/bazel/pull/11838 will
be included.

**Comment by aiuto** [comment] 2020-08-12 02:52
# Status of Bazel 3.5

- Target baseline: 2020-08-03
- Expected release date: 2020-08-18
 [List of release blockers](https://github.com/bazelbuild/bazel/labels/Release%20blocker)

To report a release-blocking bug, please file a bug using the `Release blocker` label, and cc me.

Task list:

- [ ] Update GitHub issues for incompatible changes
- [x] Pick release baseline: f674007557dc73c50a19063d671c662ffa0f423e
- [x ] Create release candidate: 
- [ ] Check downstream projects:
- [ ] [Create draft release announcement](https://docs.google.com/document/d/1wDvulLlj4NAlPZamdlEVFORks3YXJonCjyuQMUQEmB0/edit)
- [ ] Send for review the release announcement PR:
- [ ] Push the release, notify package maintainers:
- [ ] Update the documentation
- [ ] Push the blog post
- [ ] Update the [release page](https://github.com/bazelbuild/bazel/releases/)

**Comment by aiuto** [comment] 2020-08-12 03:01
Currently broken and investgating:
rules_python: https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/1594#97a7e8ea-c457-4456-a566-84fa4466586c
rules_typescript: https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/1594#51e3cf05-9c63-4af5-b0ad-b80c2019df80
flogger: https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/1594#eda26e49-1c79-4ac6-b9a9-284715b51ac6
envoy coverage: https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/1594#bd8ce064-3544-4539-b37d-0da766fe0c04 (looks like a flake)

**Comment by or-shachar** [comment] 2020-08-12 09:29
Hey hey,
How can we consume rc1? https://releases.bazel.build/3.5.0/rc1/index.html is not available (yet?)

I want to test it against rules_scala and to see that our issue is indeed fixed.

**Comment by aiuto** [comment] 2020-08-12 13:51
It will be available later today. If you want it earlier, you can clone the
repo, check out the release-3.5.0rc1 branch, and build that.

**Comment by philwo** [comment] 2020-08-12 15:12
FYI, arm64 users: The arm64 build process for this release is still partly manual, so please give me a few minutes after @aiuto pushes rc1, so that I can kick-off the build and upload of the arm64 binaries ;)

**Comment by aiuto** [comment] 2020-08-12 17:30
It is now available: https://releases.bazel.build/3.5.0/rc1/index.html

**Comment by davido** [comment] 2020-08-12 17:51
@aiuto 

> So the fix in #11838 will be included.

The fix from #11838 wasn't included, unfortunately.

Now bazel is reporting ca 100 errors, when trying to build gerrit, that are actually ignored: [1].

The only available workaround to silent those errors is to migrate external workspaces from `foo-bar` to `foo_bar`. But given that this is a regression, I would rather cherry-pick the PR that is linked to #11838.

[1] http://paste.openstack.org/show/796786

**Comment by aiuto** [comment] 2020-08-12 19:14
Oh whoops. Why did I not see that.
I can cherrpick it in to rc2

**Comment by konste** [comment] 2020-08-12 20:41
Release notes advertise the new feature `cc_common.compile support for include_prefix/strip_include_prefix`, but it does not seem to be available in 3.5.0RC1 
[The fix](https://github.com/bazelbuild/bazel/commit/b37c51c7085f0aefe04034dd451acb847605ddb5) went in just a couple days ago. Is it even going to make it to 3.5.0 release?

**Comment by aiuto** [comment] 2020-08-12 20:51
I have no answer for why you don't see it. That PR was before the 3.5 baseline, so it should be there. 
I would ask @oquenchil about it. If it turns out the release notes got ahead of the functionality, we can fix the release notes more easily then a cherrypick.

**Comment by konste** [comment] 2020-08-12 21:49
The feature `cc_common.compile support for include_prefix/strip_include_prefix` does work with 3.5.0RC1
Really sorry for the false alarm! Bazelisk got me confused.

**Comment by konste** [comment] 2020-08-12 22:15
Seems to be a regression in 3.5.0RC1: https://github.com/bazelbuild/bazel/issues/11936

**Comment by aiuto** [comment] 2020-08-13 03:12
3.5.0rc2 is ready.

**Comment by davido** [comment] 2020-08-13 04:55
> 3.5.0rc2 is ready.

Thanks, confirmed that the regression #11838 is fixed in 3.5.0rc2.

**Comment by or-shachar** [comment] 2020-08-13 09:08
Just checked it on Wix repo - seems like there's a new restriction on external repository names? 
we used to have external repositories for docker images with version in their names like `busybox_1.25.0` and now we get the error:
```
10:44:25  Error in workspace: busybox_1.25.0 is not a legal workspace name
```

I didn't see this in the release notes

**Comment by meisterT** [comment] 2020-08-13 09:09
@or-shachar see https://github.com/bazelbuild/bazel/issues/11936

**Comment by philwo** [comment] 2020-08-13 09:12
Bazel 3.5.0rc2 Linux arm64 binaries have been successfullt built and uploaded to https://releases.bazel.build/3.5.0/rc2/index.html

**Comment by davido** [comment] 2020-08-13 09:27
@meisterT @or-shachar 

> 10:44:25  Error in workspace: busybox_1.25.0 is not a legal workspace name

If it is your primary `WORKSPASE` file, then I think this is rather the same regression as in #11838. I only added hyphen char, in my fix, because Gerrit project doesn't use dot char in workpsace repository names.

See also this https://github.com/bazelbuild/bazel/pull/11838#issuecomment-668435204 where  @Gromba asked to add dot char as well.

**Comment by or-shachar** [comment] 2020-08-13 10:04
@davido @meisterT  - it's not the primary workspace name but a generated workspace from the rule `container_pull`. We had dots in the external repository name which worked fine until this version

**Comment by aiuto** [comment] 2020-08-13 13:51
I'll do some hunting to figure out why we added the restriction in the first place. That will help me decide if we do a patch in the minor releases until the next major and break then, or revert totally.

**Comment by aiuto** [comment] 2020-08-13 15:35
I have a change in the pipeline to allow dot in workspace names. That will roll into RC3

**Comment by laurentlb** [comment] 2020-08-13 15:43
The issue is discussed on https://github.com/bazelbuild/bazel/issues/11837

**Comment by aiuto** [comment] 2020-08-13 18:32
We can resolve the prelude processing problem #11940 by picking a baseline from Aug. 7.   889bc0b523b47eeb38a72bf9bb6858ee525a7c7e

Now the question is if the new error reporting is a blocker or not. 
- are there reasonable workarounds?
- is  there a short fix forward to suppress the better error reporting?

And also, do we revert the change allowing hyphens in names first. Given today's discussions, that is probably called for first. 
I'll think through all this by Friday EOD and come up with a plan.

**Comment by aiuto** [comment] 2020-08-13 20:49
Background on the flogger issue: https://github.com/bazelbuild/continuous-integration/issues/1006
The proposal was to provide the needed Android SDK in the CI environment.

**Comment by aiuto** [comment] 2020-08-15 02:25
I think I have a good handle on the unneeded processing of WORKSPACE files in external repos. It should be easier to fix forward than roll back the improved error handling, so I'm going to try that approach. In the worst case, we can't do that and then we can have the debate about if this is an actual blocker or one people can work around by ignoring the log spam.

I will attempt that patch to mainline on Monday. If it goes well, I can cherrypick a new RC against the earlier baseline on Tuesday and send that out. This pushes back the expected release date to August 26 at the earliest.

**Comment by ulfjack** [comment] 2020-08-15 22:28
FYI: the hyphen issue (#11837) also affects TensorFlow, at least in some configurations.

**Comment by aiuto** [comment] 2020-08-17 23:58
Status update:
- I believe I have the WORKSPACE processing issues resolved. The change is going through review.
- I have another change out to allow dot in repo names.
- When both are merged, I can cut a new release candidate from the Aug 7 baseline, with those cherrypicks.
- I expect that can happen on 2020-08-18.

**Comment by konste** [comment] 2020-08-18 00:05
Thank you @aiuto for your diligent work on these problems! Appreciate that a lot!

**Comment by aiuto** [comment] 2020-08-18 00:16
You're welcome. Did you see the PR to update your repro? I played a lot with that today to make sure the fix would not silently break other things.

**Comment by konste** [comment] 2020-08-18 00:22
Yes, the risk of regressions is the primary concern at this point. I am going to jump on the next RC when it is available and run it through the different scenarios on all platforms to make sure it is stable.

**Comment by aiuto** [comment] 2020-08-19 17:32
I should have mentioned this, but rc3 went out yesterday, on August 18.
https://releases.bazel.build/3.5.0/rc3/index.html

**Comment by konste** [comment] 2020-08-19 17:35
Thank you for the notice! We'll jump right on it!

**Comment by pariscraigm** [comment] 2020-08-19 20:51
I am testing for regressions in rc3 for @konste and I am getting this error: `Error in compile: compile() got unexpected keyword argument 'include_prefix'`

Was `include_prefix` for `cc_common.compile` remove in rc3?

**Comment by konste** [comment] 2020-08-19 20:57
It was definitely present in RC2! And we already took a dependency on it. @aiuto please take a look.

**Comment by aiuto** [comment] 2020-08-20 02:30
That will not be in rc3, because we moved the baseline back to August 7.
How is this a release stopper if it is a new feature?

**Comment by konste** [comment] 2020-08-20 02:36
Darn... When we found it in release notes and in RC1 we took it for granted. Why the baseline had to be moved back? I already regret that I raised that issue. We'd rather get `include_prefix` feature and work around WORKSPACE issues than the other way around. Don't anybody else expect `include_prefix` to appear in 3.5.0?

**Comment by aiuto** [comment] 2020-08-20 02:42
We had to move it back because the prelude loading change was very incompatible for some users. Fixing it forward was too large a job.

**Comment by konste** [comment] 2020-08-20 02:46
I see. Well, at least it was not me who caused it. I will remove the dependency on `include_prefix` feature (too bad, too bad - it was so handy) and we re-test RC3 once again.

**Comment by steeve** [comment] 2020-08-20 15:15
Hi,

Would it be possible to cherry-pick https://github.com/bazelbuild/bazel/commit/a7a0d48fbeb059ee60e77580e5d05baeefdd5699 ?

That would unlock https://github.com/bazelbuild/rules_go/pull/2451.

Thanks!

**Comment by aiuto** [comment] 2020-08-20 20:37
Not at this late in the process. That is only from 3 days ago.

**Comment by aiuto** [comment] 2020-08-20 20:42
I just looked a little deeper and don't get the timeline.  What is the relation between the bug mentioned in bazelbuild/rules_go#2445 and that commit?  2445 says it that the 3.5 release would have the fix, but I am not seeing the connection.

**Comment by aiuto** [comment] 2020-08-20 21:55
Just for kicks, I am trying a tentative rc4. It includes:
- the features which were in rc1, because it was disappointing to see them there and then have them vanish
- plus a7a0d48 because that looks like a fix to an even earlier fairly serious regression

https://releases.bazel.build/3.5.0/rc4/index.html

**Comment by konste** [comment] 2020-08-20 22:06
Oh, wow! Feels a bit like a rollercoaster, but I enjoy it! @aiuto I appreciate the voluntary effort!

**Comment by steeve** [comment] 2020-08-21 00:04
@aiuto sounds fair, thank you for the feedback

As for bazelbuild/rules_go#2445, the fix was for https://github.com/bazelbuild/bazel/issues/11167, which was merged in https://github.com/bazelbuild/bazel/commit/a90c4084315a490c4fecc864d0b3435cc7b2bd64 which _looks_ like it's before the cut.

**Comment by aiuto** [comment] 2020-08-21 01:16
Running the downstream tests right now. https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/1608
@konste I have kids. I know the look on their faces when you tell them something is going to happen and then it doesn't.
@steeve The no-op transition problem from a7a0d48 was still a fairly significant bug.

**Comment by aiuto** [comment] 2020-08-21 01:27
@steeve rules_go fails on windows with rc4.  Is this a real problem? https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/1608#30eaebca-0f8d-4255-9653-1896d1cc0b50

**Comment by steeve** [comment] 2020-08-21 01:59
Apparently these are link errors because of duplicated symbols in msvcrt, I'd say it may be a regression in bazel, cc @jayconrod for confirmation

**Comment by konste** [comment] 2020-08-21 02:26
I am not familiar with the Buildkite, but still looking at the rules_go log out of curiosity. Is `Current running Bazel is not a release version and one was not defined explicitly in rbe_autoconfig target. Falling back to '3.3.1'` a red herring? Just making sure it is noticed.

**Comment by aiuto** [comment] 2020-08-21 03:31
Thanks for catching that. It looks to me like a test configuration problem.

**Comment by meteorcloudy** [comment] 2020-08-24 08:27
@konste Oh, yes. I meant the latest rc, which should be rc4

**Comment by aiuto** [comment] 2020-08-24 13:49
Since this has seemed to settle out, it looks like I can turn RC4 into the
real release on Wednesday or Thursday.

**Comment by aiuto** [comment] 2020-08-26 03:15
Status update:
Blog post is ready: https://github.com/bazelbuild/bazel-blog/pull/236
I should be able to push on 2020-08-26

**Comment by asuffield** [comment] 2020-09-01 13:35
ping?

**Comment by aiuto** [comment] 2020-09-02 19:50
I am trying to push it right now.  Having some ACL problems. Sigh.
They should be resolved today.

**Comment by aiuto** [comment] 2020-09-02 20:34
@vbatts @petemounce @excitoon   Bazel 3.5.0 is available at https://github.com/bazelbuild/bazel/releases

**Comment by philwo** [comment] 2020-09-02 21:28
Linux arm64 binaries have been built and uploaded. 🦾

**Comment by Yannic** [comment] 2020-09-04 12:14
`Bazelisk + Incompatible flags` on Buildkite is broken with Bazel 3.5.0: https://buildkite.com/bazel/bazelisk-plus-incompatible-flags/builds/615#1f97d2d1-4d06-454b-af61-deff7963d347/95-104

**Comment by meisterT** [comment] 2020-09-07 06:13
Filed https://github.com/bazelbuild/bazel/issues/12058

**Comment by petemounce** [comment] 2020-09-07 21:01
Chocolatey has been published.

**Comment by philwo** [comment] 2020-09-07 21:18
Thank you @petemounce 😊

**Comment by aiuto** [comment] 2020-09-09 16:20
This is for the Fedora bless package of Bazel 3.5, so it is mostly about building Bazel. Right?
Even so, does the 3.5 binary (un-repackaged) work with user projects using C++?  Or, are the rule broken as well with g++ 10.2.1

**Comment by aiuto** [comment] 2020-09-09 16:34
It looks like it fails for all platforms in \@upb, which gRPC uses. My hunch is that this is related to a 3.4 problem with gRPC that caused some rollback/forward and a 3.4.1 release.
c3ea5a1253c6cfad46fffa25d9842bce1fdc69c2
fa7299c4e446ad76f86ebc3d34cbfd756eabc644

@meteorcloudy   Do you have any ideas?

**Comment by vbatts** [comment] 2020-09-09 20:54
> This is for the Fedora bless package of Bazel 3.5, so it is mostly about building Bazel. Right?
> Even so, does the 3.5 binary (un-repackaged) work with user projects using C++? Or, are the rule broken as well with g++ 10.2.1

this is in building bazel itself. 
https://github.com/vbatts/copr-build-bazel/tree/v3.5.0-1
run: `make rpm` from a fedora 32 host.

**Comment by meteorcloudy** [comment] 2020-09-10 08:19
Looks like it's the same issue as https://github.com/bazelbuild/bazel/issues/12056

upb has fixed the problem, we should update the upb version in Bazel.

**Comment by meteorcloudy** [comment] 2020-09-10 08:33
PR sent: https://github.com/bazelbuild/bazel/pull/12077

**Comment by aiuto** [comment] 2020-09-11 16:12
@meteorcloudy  Is it time to try a 3.5.1 with the cherrypick of https://github.com/bazelbuild/bazel/commit/b3ac8f60973ba60d578ae6a653cdd993a2d206d7
or is there more to do?

**Comment by aiuto** [comment] 2020-09-11 16:13
Actually, @vbatts, perhaps you are in the best situation to test, as you have the right compiler environment.
If you patch that commit into the 3.5.0 sources does your build then work?

**Comment by vbatts** [comment] 2020-09-11 18:01
tested b3ac8f6, and it seems to rely on other files than are included in
3.5.0:

```
         File "/home/vbatts/workspace/src/github.com/vbatts/copr-build-bazel/bazel-3.5.0/tools/build_defs/repo/http.bzl", line 121, column 10, in _http_archive_impl
                 patch(ctx)
         File "/home/vbatts/workspace/src/github.com/vbatts/copr-build-bazel/bazel-3.5.0/tools/build_defs/repo/utils.bzl", line 135, column 22, in patch
                 ctx.patch(patchfile, strip)
Error in patch: Not a regular file: /home/vbatts/workspace/src/github.com/vbatts/copr-build-bazel/bazel-3.5.0/third_party/grpc/upb_gcc10_fix.patch
ERROR: no such package '@upb//bazel': Not a regular file: /home/vbatts/workspace/src/github.com/vbatts/copr-build-bazel/bazel-3.5.0/third_party/grpc/upb_gcc10_fix.patch
```

**Comment by vbatts** [comment] 2020-09-11 20:39
applied 26cbf776e0cdd8fbb9a40aca4c1be6f5313b6eb4 also
and local build is making it further, so i've kicked off https://copr.fedorainfracloud.org/coprs/build/1658045

**Comment by vbatts** [comment] 2020-09-12 00:09
Those two commits did the trick.
(The two failures are the couple of aarch64 that have consistently been failing)

**Comment by aiuto** [comment] 2020-09-12 02:21
Thanks.

I started a 3.5.1 run with those two cherrypicks + correctness bug fix from https://github.com/bazelbuild/bazel/commit/b9bb10252a004047f9a997165aa1ab7d6c6fa2e7.
```
scripts/release/release.sh create --force_rc=1 3.5.1 \
	889bc0b523b47eeb38a72bf9bb6858ee525a7c7e \
	a7a0d48fbeb059ee60e77580e5d05baeefdd5699 \
	b37c51c7085f0aefe04034dd451acb847605ddb5 \
	f6ad35fcde93f92c591778ed7db38d167f5bbc03 \
	39bc97eab295bddb35b38bfc4a2ff3d2b15d034e \
	b9706675a7abf6ceebb250f0b3dfa4087a0c35f6 \
	e574d558da17cfd0f818e7a937a07926aa270069 \
	9993785fa0c4fa4172aa31d306f3abea76833abf \
	b3ac8f60973ba60d578ae6a653cdd993a2d206d7 \
	26cbf776e0cdd8fbb9a40aca4c1be6f5313b6eb4 \
	b9bb10252a004047f9a997165aa1ab7d6c6fa2e7
```
Alas, it seems to fail on an unrelated issue. 
```
src/tools/android/java/com/android/tools/r8/CompatDxSupport.java:16: error: cannot find symbol
--
  | import com.android.tools.r8.utils.AndroidApp;
```
https://buildkite.com/bazel/bazel-bazel/builds?branch=release-3.5.1rc1.

I'll have to dig into that.

**Comment by philwo** [comment] 2020-09-12 06:51
@aiuto This looks like an incompatibility between Bazel 3.5.x and a too new Android SDK. IIRC we added a newer version of the Android build-tools on the CI machines in the meantime due to a request from the Android folks. Because Bazel's WORKSPACE build does not pin the tools to a fixed version, Bazel 3.5.x now picks up that latest version, but is not yet compatible with it.

**Comment by aiuto** [comment] 2020-09-12 15:30
On Sat, Sep 12, 2020 at 2:51 AM Philipp Wollermann <notifications@github.com>
wrote:

> @aiuto <https://github.com/aiuto> This looks like an incompatibility
> between Bazel 3.5.x and a too new Android SDK.
>
It does look like that.

> IIRC we added a newer version of the Android build-tools on the CI
> machines in the meantime due to a request from the Android folks. Because
> Bazel's WORKSPACE build does not pin the tools to a fixed version, Bazel
> 3.5.x now picks up that latest version, but is not yet compatible with it.
>
Wouldn't Bazel at head fail in CI if we did not have a corresponding change
at head to account for the new SDK?
Last night I started looking through all the commits between Aug 7 and now
but did not find evidence of that.
Perhaps it was just too long a day.

Are there notes about how we put the SDK on the CI machines? Those would be
handy for setting up personal machines to do full testing locally.

**Comment by aiuto** [comment] 2020-09-14 19:12
@philwo The obvious question is you say "we *added* a newer version.  If you really mean added, rather than replaced, this should only require pinning the version in the WORKSPACE.

**Comment by philwo** [comment] 2020-09-14 19:21
@aiuto Yes, we added Android build-tools 30.0.1 and removed unused versions 28.0.3 and 29.0.0: https://github.com/bazelbuild/continuous-integration/commit/050153de261cd0cca54d59760b2dc0ca95a49e0a.

Before this change, Bazel would have used build-tools 29.0.3, after this change it would use 30.0.1.

Bazel at HEAD and Bazel 3.6 are compatible with build-tools 30.0.1, but Bazel 3.5 is not yet compatible.

I believe the commits that added the compatibility are these:
- https://github.com/bazelbuild/bazel/commit/6b591a7e20f05224898b31ad5b03ba514eff6118
- https://github.com/bazelbuild/bazel/commit/7a11752a8ae7689d2bd482e23d466cb44a3261a1

You can check Google bug b/158484558 for some context.

I think as a way forward we have two options:
- Pin Android build-tools to 29.0.3 in the WORKSPACE of Bazel 3.5.x. This is the lowest risk, but a bit annoying as we do not have this as a commit we can cherry-pick, so we would somehow have to get it into master first and then cherry-pick it and then change master again to be pinned to build-tools 30.0.1.
- Or we can cherry-pick the above commits.

**Comment by aiuto** [comment] 2020-09-25 13:58
I am trying the cherrypicks.   I'll know if this works in about 50 minutes.
```
scripts/release/release.sh create --force_rc=1 \
	3.5.1 889bc0b523b47eeb38a72bf9bb6858ee525a7c7e \
	a7a0d48fbeb059ee60e77580e5d05baeefdd5699 \
	b37c51c7085f0aefe04034dd451acb847605ddb5 \
	f6ad35fcde93f92c591778ed7db38d167f5bbc03 \
	39bc97eab295bddb35b38bfc4a2ff3d2b15d034e \
	b9706675a7abf6ceebb250f0b3dfa4087a0c35f6 \
	e574d558da17cfd0f818e7a937a07926aa270069 \
	9993785fa0c4fa4172aa31d306f3abea76833abf \
	b3ac8f60973ba60d578ae6a653cdd993a2d206d7 \
	26cbf776e0cdd8fbb9a40aca4c1be6f5313b6eb4 \
	b9bb10252a004047f9a997165aa1ab7d6c6fa2e7 \
	6b591a7e20f05224898b31ad5b03ba514eff6118 \
	7a11752a8ae7689d2bd482e23d466cb44a3261a1
```

**Comment by aiuto** [comment] 2020-09-25 15:50
Pushed release: 3.5.1rc1
- https://releases.bazel.build/3.5.1/rc1/index.html
- https://github.com/bazelbuild/bazel/tree/release-3.5.1rc1

@vbatts @petemounce @excitoon :  Could you please test that this can be repackaged in your respective systems.

**Comment by aiuto** [comment] 2020-09-29 16:38
Since yesterday was a holiday, I will let this age one more business day before dropping the "rc1" and upgrading to 3.5.1

**Comment by philwo** [comment] 2020-09-30 21:35
Can we release Bazel 3.5.1? Due to a bug in Bazelisk (https://github.com/bazelbuild/bazelisk/issues/170), certain builds around the world are failing until we do so.

**Comment by aiuto** [comment] 2020-09-30 22:12
I will tonight. I was hoping to get a thumbs up from the downstream
packagers, but I don't want to keep you blocked.

**Comment by aiuto** [comment] 2020-10-01 17:45
I just pushed release: 3.5.1

https://github.com/bazelbuild/bazel/releases/tag/3.5.1

@vbatts @petemounce @excitoon : Could you please repackage this for your respective systems.

**Comment by vbatts** [comment] 2020-10-01 22:00
Fedora and Centos builds are kicked off: https://copr.fedorainfracloud.org/coprs/build/1691954

**Comment by vbatts** [comment] 2020-10-02 14:10
I forgot to remove the cherry-picked patches, so that build failed. 
Kicked off a new build: https://copr.fedorainfracloud.org/coprs/build/1692951

**Comment by philwo** [comment] 2020-10-06 14:50
Bazel 3.5.1 arm64 binaries uploaded to GitHub and https://releases.bazel.build/3.5.1/release/.

**Closed** 2020-10-07 07:49 UTC
Labels: release
