### ISSUE TITLE
`expand_directories` requires the directory to be an input

### ISSUE THREAD

**Issue by pauldraper** [bazelbuild/bazel#18835] opened 2023-07-03 18:04 UTC
### Description of the bug:

The expand directories function of [Args#add_all](https://bazel.build/rules/lib/builtins/Args#add_all) requires the directory to be an input to the action (run/run_shell).

I wanted to generate a list of files for tsconfig.json used for TypeScript compilation. After an hour, I realize that the directory has to be an input.

I would prefer that I could not have to regenerate the tsconfig.json when the inputs changes, only when the list of files change.

If this is infeasible, the requirement should at least be documented.

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

**WORKSPACE.bazel**

```bzl
```

**BUILD.bazel**

```bzl
load(":test.bzl", "example")

example(name = "example")
```

**rules.bzl**

```bzl
def _example_impl(ctx):
    dir = ctx.actions.declare_directory("%s.dir" % ctx.attr.name)
    ctx.actions.run_shell(
        command = 'touch "$1"/file',
        arguments = [dir.path],
        outputs = [dir],
    )

    output = ctx.actions.declare_file(ctx.attr.name)
    args = ctx.actions.args()
    args.add(output)
    args.add_all([dir])
    ctx.actions.run_shell(
        command = 'output="$1"; shift; echo "$@" > "$output"',
        arguments = [args],
        # inputs = [dir],
        outputs = [output],
    )

    return DefaultInfo(files = depset([output]))

example = rule(
    implementation = _example_impl,
)
```

Run:

```sh
bazel build example
cat bazel-bin/example
```

The file is empty:

```txt

```

### Which operating system are you running Bazel on?

macOS

### What is the output of `bazel info release`?

6.2.0

### Is this a regression? If yes, please try to identify the Bazel commit where the bug was introduced.

No

**Comment by benjaminp** [comment] 2023-07-03 18:07
#11811

**Comment by comius** [comment] 2023-08-22 17:19
Duplicate of https://github.com/bazelbuild/bazel/issues/11811

**Closed by comius** 2023-08-22 17:19 UTC
Labels: type: bug, untriaged, team-Rules-API
