### ISSUE TITLE
Building Bazel from source fails. Java maybe not be installed correctly

### ISSUE THREAD

**Issue by Jayoprell** [bazelbuild/bazel#4532] opened 2018-01-27 09:08 UTC
I want to install tensorflow on Jetson TX2 and I follow the instructions [http://www.jetsonhacks.com/2017/09/14/build-tensorflow-on-nvidia-jetson-tx2-development-kit/](url) to install it. In the installing process, bazel need to be install first. For the begainning, I compile bazel 0.9.0 and it failed. The errors are as follows:
`ERROR: /home/nvidia/Desktop/bazel/bazel-0.9.0-dist/src/main/java/com/google/devtools/common/options/BUILD:27:1: Building src/main/java/com/google/devtools/common/options/liboptions_internal.jar (35 source files) failed (Exit 1): java failed: error executing command 
  (cd /tmp/bazel_7yWeYgtw/out/execroot/io_bazel && \
  exec env - \
    LC_CTYPE=en_US.UTF-8 \
  external/local_jdk/bin/java -XX:+TieredCompilation '-XX:TieredStopAtLevel=1' -Xbootclasspath/p:third_party/java/jdk/langtools/javac-9-dev-r4023-3.jar -jar bazel-out/host/bin/src/java_tools/buildjar/java/com/google/devtools/build/buildjar/bootstrap_deploy.jar @bazel-out/host/bin/src/main/java/com/google/devtools/common/options/liboptions_internal.jar-2.params)
java.lang.InternalError: Cannot find requested resource bundle for locale en_US
	at com.sun.tools.javac.util.JavacMessages.getBundles(JavacMessages.java:128)
	at com.sun.tools.javac.util.JavacMessages.getLocalizedString(JavacMessages.java:147)
	at com.sun.tools.javac.util.JavacMessages.getLocalizedString(JavacMessages.java:140)
	at com.sun.tools.javac.util.Log.localize(Log.java:788)
	at com.sun.tools.javac.util.Log.printLines(Log.java:586)
	at com.sun.tools.javac.api.JavacTaskImpl.handleExceptions(JavacTaskImpl.java:170)
	at com.sun.tools.javac.api.JavacTaskImpl.doCall(JavacTaskImpl.java:96)
	at com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:90)
	at com.google.devtools.build.buildjar.javac.BlazeJavacMain.compile(BlazeJavacMain.java:107)
	at com.google.devtools.build.buildjar.SimpleJavaLibraryBuilder$1.invokeJavac(SimpleJavaLibraryBuilder.java:105)
	at com.google.devtools.build.buildjar.ReducedClasspathJavaLibraryBuilder.compileSources(ReducedClasspathJavaLibraryBuilder.java:54)
	at com.google.devtools.build.buildjar.SimpleJavaLibraryBuilder.compileJavaLibrary(SimpleJavaLibraryBuilder.java:108)
	at com.google.devtools.build.buildjar.SimpleJavaLibraryBuilder.run(SimpleJavaLibraryBuilder.java:116)
	at com.google.devtools.build.buildjar.BazelJavaBuilder.processRequest(BazelJavaBuilder.java:105)
	at com.google.devtools.build.buildjar.BazelJavaBuilder.runPersistentWorker(BazelJavaBuilder.java:67)
	at com.google.devtools.build.buildjar.BazelJavaBuilder.main(BazelJavaBuilder.java:45)
Caused by: java.util.MissingResourceException: Can't find bundle for base name com.google.errorprone.errors, locale en_US
	at java.util.ResourceBundle.throwMissingResourceException(ResourceBundle.java:1573)
	at java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1396)
	at java.util.ResourceBundle.getBundle(ResourceBundle.java:854)
	at com.sun.tools.javac.util.JavacMessages.lambda$add$0(JavacMessages.java:106)
	at com.sun.tools.javac.util.JavacMessages.getBundles(JavacMessages.java:125)
	... 15 more
Target //src:bazel failed to build
INFO: Elapsed time: 630.446s, Critical Path: 125.70s
FAILED: Build did NOT complete successfully
`

Then I am wondering whether the version of bazel is not compatible,  so I compile a lower bazel(0.4.5). But it did not work.

**Comment by Jayoprell** [comment] 2018-01-27 09:09
Hi, @karthee320
I built bazel successfully!(my system is ubuntu16.04)
If you are facing the similar issues as mine, it maybe that you do not install JDK8 correctly.
Please follow the below link to build bazel.
https://docs.bazel.build/versions/master/install-ubuntu.html
Please install JDK8 follow the above link, do not install other JDK on your system(e.g. download a new JDK pakage form official website and then install on your system). If you install two jdk, it maybe confuse when to build bazel!
Hope it will woks!

**Comment by cushon** [comment] 2018-01-27 23:47
This is a duplicate of #4483.

**Closed by cushon** 2018-01-27 23:47 UTC

**Comment by AIHZP** [comment] 2018-02-27 14:48
do you resolve the problem, I don't know how to fix it. If you worked out ,please  tell me how to do.Thank you very much! My email:zhi12271125@gmail.com

**Comment by cxws** [comment] 2018-11-20 09:02
- [ ] 修改本地语言成en_US,问题没有解决
 - [x] 降低jdk版本(原先是1.8.0.191),问题解决了，具体如下：
```
下载jdk-8u11-linux-x64.tar.gz，然后解压到任意目录，并修改JAVA_HOME为上面的目录，重新执行./compile.sh
```
