### ISSUE TITLE
bazel crashed when BES connection is aborted with remote cache enabled

### ISSUE THREAD

**Issue by bazingazZ** [bazelbuild/bazel#13920] opened 2021-08-30 11:57 UTC
> ATTENTION! Please read and follow:
> - if this is a _question_ about how to build / test / query / deploy using Bazel, or a _discussion starter_, send it to bazel-discuss@googlegroups.com
> - if this is a _bug_ or _feature request_, fill the form below as best as you can.

### Description of the problem / feature request:

bazel crashed when BES connection is aborted with remote cache enabled

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

bazel coverage //common/... with BES and remote cache enabled. 
BES fails to upload local file to remote cache causing the BES stream to be aborted. But bazel still tries to upload local files after command although the upload executor is already terminated.

### What operating system are you running Bazel on?

CentOS

### What's the output of `bazel info release`?

release 4.2.0

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

> Replace this line with your answer.

###  Have you found anything relevant by searching the web?

https://github.com/bazelbuild/bazel/issues/12575
>
> Places to look:
> - StackOverflow: http://stackoverflow.com/questions/tagged/bazel
> - GitHub issues: https://github.com/bazelbuild/bazel/issues
> - email threads on https://groups.google.com/forum/#!forum/bazel-discuss

### Any other information, logs, or outputs that you want to share?
```
210830 08:34:15.549:WT 47 [com.google.devtools.build.lib.buildeventservice.BuildEventServiceUploader.waitForUploads] Failed to upload files referenced by build event: java.io.FileNotFoundException: /data/.cache/bazel/base/execroot/__main__/bazel-out/k8-fastbuild/testlogs/common/manage/wrapper/trpc/collab/go_default_test/baseline_coverage.dat (No such file or directory)
java.util.concurrent.ExecutionException: java.io.FileNotFoundException: /data/.cache/bazel/base/execroot/__main__/bazel-out/k8-fastbuild/testlogs/common/manage/wrapper/trpc/collab/go_default_test/baseline_coverage.dat (No such file or directory)
	at com.google.common.util.concurrent.AbstractFuture.getDoneValue(AbstractFuture.java:564)
	at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:525)
	at com.google.common.util.concurrent.FluentFuture$TrustedFuture.get(FluentFuture.java:88)
	at com.google.devtools.build.lib.buildeventservice.BuildEventServiceUploader.waitForUploads(BuildEventServiceUploader.java:671)
	at com.google.devtools.build.lib.buildeventservice.BuildEventServiceUploader.publishBuildEvents(BuildEventServiceUploader.java:446)
	at com.google.devtools.build.lib.buildeventservice.BuildEventServiceUploader.run(BuildEventServiceUploader.java:316)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.io.FileNotFoundException: /data/.cache/bazel/base/execroot/__main__/bazel-out/k8-fastbuild/testlogs/common/manage/wrapper/trpc/collab/go_default_test/baseline_coverage.dat (No such file or directory)
	at com.google.devtools.build.lib.unix.NativePosixFiles.stat(Native Method)
	at com.google.devtools.build.lib.unix.UnixFileSystem.statInternal(UnixFileSystem.java:184)
	at com.google.devtools.build.lib.unix.UnixFileSystem.stat(UnixFileSystem.java:175)
	at com.google.devtools.build.lib.vfs.DelegateFileSystem.stat(DelegateFileSystem.java:239)
	at com.google.devtools.build.lib.remote.RemoteActionFileSystem.stat(RemoteActionFileSystem.java:275)
	at com.google.devtools.build.lib.remote.RemoteActionFileSystem.getFileSize(RemoteActionFileSystem.java:207)
	at com.google.devtools.build.lib.vfs.Path.getFileSize(Path.java:648)
	at com.google.devtools.build.lib.remote.util.DigestUtil.compute(DigestUtil.java:59)
	at com.google.devtools.build.lib.remote.ByteStreamBuildEventArtifactUploader.readPathMetadata(ByteStreamBuildEventArtifactUploader.java:127)
	at com.google.devtools.build.lib.remote.ByteStreamBuildEventArtifactUploader.lambda$upload$2(ByteStreamBuildEventArtifactUploader.java:220)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:125)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:69)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:78)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	... 1 more
210830 08:34:15.551:I 47 [com.google.devtools.build.lib.buildeventservice.BuildEventServiceUploader.publishBuildEvents] Publish interrupt. Showing up to 30 items from queues: ack_queue_size: 3364, ack_queue: [SendRegularBuildEventCommand{seq_num=1} - [com.google.devtools.build.lib.buildtool.buildevent.BuildStartingEvent@3d510cd8], SendRegularBuildEventCommand{seq_num=2} - [com.google.devtools.build.lib.runtime.OriginalUnstructuredCommandLineEvent@5c6ad852], SendRegularBuildEventCommand{seq_num=3} - [com.google.devtools.build.lib.runtime.BuildMetadataEvent@48fa0313], SendRegularBuildEventCommand{seq_num=4} - [com.google.devtools.build.lib.runtime.CommandLineEvent$CanonicalCommandLineEvent@56de5a54], SendRegularBuildEventCommand{seq_num=5} - [com.google.devtools.build.lib.runtime.CommandLineEvent$OriginalCommandLineEvent@543cd37], SendRegularBuildEventCommand{seq_num=6} - [com.google.devtools.build.lib.runtime.CommandLineEvent$ToolCommandLineEvent@266a2f2e], SendRegularBuildEventCommand{seq_num=7} - [com.google.devtools.build.lib.runtime.GotOptionsEvent@6e3a0054], SendRegularBuildEventCommand{seq_num=8} - [com.google.devtools.build.lib.pkgcache.TargetParsingCompleteEvent@51c5653c], SendRegularBuildEventCommand{seq_num=9} - [com.google.devtools.build.lib.buildeventstream.ProgressEvent@68e07c35], SendRegularBuildEventCommand{seq_num=10} - [com.google.devtools.build.lib.runtime.ExecRootEvent@65ae208a], SendRegularBuildEventCommand{seq_num=11} - [com.google.devtools.build.lib.buildeventstream.ProgressEvent@1ac77a9a], SendRegularBuildEventCommand{seq_num=12} - [com.google.devtools.build.lib.actions.BuildConfigurationEvent@8ce4dcc0], SendRegularBuildEventCommand{seq_num=13} - [com.google.devtools.build.lib.analysis.TargetConfiguredEvent@509190a0], SendRegularBuildEventCommand{seq_num=14} - [com.google.devtools.build.lib.analysis.TargetConfiguredEvent@71232382], SendRegularBuildEventCommand{seq_num=15} - [com.google.devtools.build.lib.analysis.TargetConfiguredEvent@72f3cc52], SendRegularBuildEventCommand{seq_num=16} - [com.google.devtools.build.lib.analysis.TargetConfiguredEvent@4cf45169], SendRegularBuildEventCommand{seq_num=17} - [com.google.devtools.build.lib.analysis.TargetConfiguredEvent@103cccc7], SendRegularBuildEventCommand{seq_num=18} - [com.google.devtools.build.lib.analysis.TargetConfiguredEvent@78ebc271], SendRegularBuildEventCommand{seq_num=19} - [com.google.devtools.build.lib.analysis.TargetConfiguredEvent@14161062], SendRegularBuildEventCommand{seq_num=20} - [com.google.devtools.build.lib.analysis.TargetConfiguredEvent@7a076490], SendRegularBuildEventCommand{seq_num=21} - [com.google.devtools.build.lib.analysis.TargetConfiguredEvent@cabd5e3], SendRegularBuildEventCommand{seq_num=22} - [com.google.devtools.build.lib.analysis.TargetConfiguredEvent@2af5664d], SendRegularBuildEventCommand{seq_num=23} - [com.google.devtools.build.lib.analysis.TargetConfiguredEvent@e44e671], SendRegularBuildEventCommand{seq_num=24} - [com.google.devtools.build.lib.analysis.TargetConfiguredEvent@4fa630cd], SendRegularBuildEventCommand{seq_num=25} - [com.google.devtools.build.lib.analysis.TargetConfiguredEvent@1df0f017], SendRegularBuildEventCommand{seq_num=26} - [com.google.devtools.build.lib.analysis.TargetConfiguredEvent@1c363aea], SendRegularBuildEventCommand{seq_num=27} - [com.google.devtools.build.lib.analysis.TargetConfiguredEvent@35e82073], SendRegularBuildEventCommand{seq_num=28} - [com.google.devtools.build.lib.analysis.TargetConfiguredEvent@4bb64e5b], SendRegularBuildEventCommand{seq_num=29} - [com.google.devtools.build.lib.analysis.TargetConfiguredEvent@515c6f72], SendRegularBuildEventCommand{seq_num=30} - [com.google.devtools.build.lib.analysis.TargetConfiguredEvent@7c10eed9]], event_queue_size: 16, event_queue: [SendRegularBuildEventCommand{seq_num=3365} - [com.google.devtools.build.lib.analysis.TargetCompleteEvent@6ecd308e], SendRegularBuildEventCommand{seq_num=3366} - [com.google.devtools.build.lib.buildeventstream.ProgressEvent@432727e7], SendRegularBuildEventCommand{seq_num=3367} - [com.google.devtools.build.lib.runtime.NamedArtifactGroup@383a7f7c], SendRegularBuildEventCommand{seq_num=3368} - [com.google.devtools.build.lib.buildeventstream.ProgressEvent@4d5451c9], SendRegularBuildEventCommand{seq_num=3369} - [com.google.devtools.build.lib.runtime.NamedArtifactGroup@2b8a612e], SendRegularBuildEventCommand{seq_num=3370} - [com.google.devtools.build.lib.analysis.TargetCompleteEvent@38261f2], SendRegularBuildEventCommand{seq_num=3371} - [com.google.devtools.build.lib.analysis.test.TestAttempt@516863a7], SendRegularBuildEventCommand{seq_num=3372} - [TestSummary{target=ConfiguredTarget(//common/collab/filters/xsrf:go_default_test, 9ed8d87c8815ef1d81f0abe9c83fff1e5447477d4e58ff353387efd8a98d9ee3), status=PASSED, numCached=0, numLocalActionCached=0, actionRan=true, ranRemotely=false}], SendRegularBuildEventCommand{seq_num=3373} - [com.google.devtools.build.lib.buildeventstream.ProgressEvent@3ac22769], SendRegularBuildEventCommand{seq_num=3374} - [com.google.devtools.build.lib.runtime.NamedArtifactGroup@5577f3e1], SendRegularBuildEventCommand{seq_num=3375} - [com.google.devtools.build.lib.buildeventstream.ProgressEvent@2d8c7b70], SendRegularBuildEventCommand{seq_num=3376} - [com.google.devtools.build.lib.runtime.NamedArtifactGroup@3f6b403d], SendRegularBuildEventCommand{seq_num=3377} - [com.google.devtools.build.lib.analysis.TargetCompleteEvent@2e1ee70], SendRegularBuildEventCommand{seq_num=3378} - [com.google.devtools.build.lib.buildeventstream.ProgressEvent@1439d1d6], SendRegularBuildEventCommand{seq_num=3379} - [com.google.devtools.build.lib.runtime.NamedArtifactGroup@7ebbd04b], SendRegularBuildEventCommand{seq_num=3380} - [com.google.devtools.build.lib.analysis.TargetCompleteEvent@6b6050e3]]
210830 08:34:15.569:I 47 [com.google.devtools.build.lib.buildeventservice.BuildEventServiceUploader.publishBuildEvents] About to cancel all local file uploads
210830 08:34:15.571:I 47 [com.google.devtools.build.lib.buildeventservice.BuildEventServiceUploader.publishBuildEvents] Spent 1 milliseconds doing local file upload cancelation
210830 08:41:19.318:I 20 [com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.exec] Exit status was DetailedExitCode{exitCode=BLAZE_INTERNAL_ERROR, failureDetail=message: "Crashed: (java.util.concurrent.RejectedExecutionException) Task com.google.common.util.concurrent.TrustedListenableFutureTask@49e31928[status=PENDING, info=[task=[running=[NOT STARTED YET], com.google.devtools.build.lib.remote.ByteStreamBuildEventArtifactUploader$$Lambda$742/0x00000008006fd440@41620404]]] rejected from java.util.concurrent.ThreadPoolExecutor@6fffad65[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 1676]"
crash {
  causes {
    throwable_class: "java.util.concurrent.RejectedExecutionException"
    message: "Task com.google.common.util.concurrent.TrustedListenableFutureTask@49e31928[status=PENDING, info=[task=[running=[NOT STARTED YET], com.google.devtools.build.lib.remote.ByteStreamBuildEventArtifactUploader$$Lambda$742/0x00000008006fd440@41620404]]] rejected from java.util.concurrent.ThreadPoolExecutor@6fffad65[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 1676]"
    stack_trace: "java.base/java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(Unknown Source)"
    stack_trace: "java.base/java.util.concurrent.ThreadPoolExecutor.reject(Unknown Source)"
    stack_trace: "java.base/java.util.concurrent.ThreadPoolExecutor.execute(Unknown Source)"
    stack_trace: "com.google.common.util.concurrent.MoreExecutors$ListeningDecorator.execute(MoreExecutors.java:586)"
    stack_trace: "java.base/java.util.concurrent.AbstractExecutorService.submit(Unknown Source)"
    stack_trace: "com.google.common.util.concurrent.AbstractListeningExecutorService.submit(AbstractListeningExecutorService.java:66)"
    stack_trace: "com.google.devtools.build.lib.remote.ByteStreamBuildEventArtifactUploader.upload(ByteStreamBuildEventArtifactUploader.java:220)"
    stack_trace: "com.google.devtools.build.lib.buildeventstream.BuildEventArtifactUploader.uploadReferencedLocalFiles(BuildEventArtifactUploader.java:100)"
    stack_trace: "com.google.devtools.build.lib.buildeventservice.BuildEventServiceUploader.enqueueEvent(BuildEventServiceUploader.java:196)"
    stack_trace: "com.google.devtools.build.lib.buildeventservice.BuildEventServiceTransport.sendBuildEvent(BuildEventServiceTransport.java:95)"
    stack_trace: "com.google.devtools.build.lib.runtime.BuildEventStreamer.post(BuildEventStreamer.java:268)"
    stack_trace: "com.google.devtools.build.lib.runtime.BuildEventStreamer.buildEvent(BuildEventStreamer.java:472)"
    stack_trace: "com.google.devtools.build.lib.runtime.BuildEventStreamer.buildEvent(BuildEventStreamer.java:481)"
    stack_trace: "com.google.devtools.build.lib.runtime.BuildEventStreamer.clearPendingEvents(BuildEventStreamer.java:307)"
    stack_trace: "com.google.devtools.build.lib.runtime.BuildEventStreamer.clearEventsAndPostFinalProgress(BuildEventStreamer.java:634)"
    stack_trace: "com.google.devtools.build.lib.runtime.BuildEventStreamer.close(BuildEventStreamer.java:354)"
    stack_trace: "com.google.devtools.build.lib.runtime.BuildEventStreamer.closeOnAbort(BuildEventStreamer.java:336)"
    stack_trace: "com.google.devtools.build.lib.buildeventservice.BuildEventServiceModule.forceShutdownBuildEventStreamer(BuildEventServiceModule.java:409)"
    stack_trace: "com.google.devtools.build.lib.buildeventservice.BuildEventServiceModule.afterCommand(BuildEventServiceModule.java:578)"
    stack_trace: "com.google.devtools.build.lib.runtime.BlazeRuntime.afterCommand(BlazeRuntime.java:626)"
    stack_trace: "com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.execExclusively(BlazeCommandDispatcher.java:603)"
    stack_trace: "com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.exec(BlazeCommandDispatcher.java:231)"
    stack_trace: "com.google.devtools.build.lib.server.GrpcServerImpl.executeCommand(GrpcServerImpl.java:543)"
    stack_trace: "com.google.devtools.build.lib.server.GrpcServerImpl.lambda$run$1(GrpcServerImpl.java:606)"
    stack_trace: "io.grpc.Context$1.run(Context.java:579)"
    stack_trace: "java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)"
    stack_trace: "java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)"
    stack_trace: "java.base/java.lang.Thread.run(Unknown Source)"
  }
}
```
>
> If the files are large, upload as attachment or provide link.

**Comment by coeuvre** [comment] 2021-09-02 02:22
Probably duplicate of https://github.com/bazelbuild/bazel/issues/11473.

**Closed** 2021-09-14 06:52 UTC
Labels: type: bug, untriaged, team-Remote-Exec
