### ISSUE TITLE
`attr` module not rich enough to describe `bzlmod` attributes

### ISSUE THREAD

**Issue by shs96c** [bazelbuild/bazel#14572] opened 2022-01-13 15:09 UTC
### Description of the problem / feature request:

`rules_jvm_external` (RJE) uses macros to allow people to specify complex maven requirements, such as [exclusions](https://github.com/bazelbuild/rules_jvm_external#artifact-exclusion), or to ask for a particular maven classifier to be downloaded.

The Bazel `attr` module isn't rich enough to express this kind of content, but the macro in RJE generates a JSON string which can be passed in as an `attr.string` and then decoded using `json.decode` to revivify it. It's not lovely, but it does work.

Without access to macros in a `MODULE.bazel`, it's not possible to replicate this workflow, and since the `attr` module lacks the richness to allow this to be specified it won't be possible to migrate RJE to use modules.

### Feature requests: what underlying problem are you trying to solve with this feature?

I guess that there are three possibilities for fixing this:

*  Extend `attr` to support arbitrary objects
* Allow users to specify their own "attribute" objects
* Let `MODULE.bazel` use macros defined in rulesets that are loaded.

The last of these is probably the most realistic :)

### What's the output of `bazel info release`?

5.0.0rc3

**Comment by Wyverald** [comment] 2022-01-13 15:54
Unfortunately the last of these is actually the least realistic, since MODULE.bazel evaluation happens before the dependencies are fetched (or even _which version_ we need is determined at all). This is the real reason why `load` statements aren't permitted in MODULE.bazel files, because it's simply impossible to support. (Similarly, tags aren't type-checked until right before module extension evaluation starts; before that, tags are just stored verbatim.)

I think a fourth possibility might be just to "deal with it" and use an API that doesn't include very complex attribute structures. `attr` is intentionally limited in its expressiveness mostly for the consideration of BUILD files (see linked code comment below). The same arguments don't apply as much to MODULE.bazel files, but still, food for thought.

https://github.com/bazelbuild/bazel/blob/3d78dc7e3a927612c23a6d1542bc38aad5a9703e/src/main/java/com/google/devtools/build/lib/packages/Type.java#L58-L80

**Comment by fmeum** [comment] 2022-01-13 22:42
I wonder whether most of these use cases for complex attributes couldn't be solved by offering an equivalent of the following Starlark function in `MODULE.bazel`:

```starlark
def complex_value(**kwargs):
    return "<some UUID>" + json.encode(kwargs)
```

This would allow for a uniform way to pass essentially arbitrary Starlark values into module tag attributes without having to add any complex new feature to Bazel. Module extensions could just consume these values via `attr.string()` or `attr.string_list()` and e.g. `bazel_skylib` could provide convenience functions such as `is_complex_value` and `parse_complex_value` (that essentially detect and strip off the UUID.

@shs96c What do you think, could this "generic" version of `maven.artifact` be usable enough?

Interestingly and very much unlike `BUILD` files, `MODULE.bazel` does allow function definitions. That means that if a future version of Bazel were to introduce such a global helper function, it would even be possible to offer a polyfill for Bazel 5.0.0 users they could just paste into their `MODULE.bazel`. @Wyverald Is it intended behavior that `MODULE.bazel` permits function definitions?

**Comment by shs96c** [comment] 2022-01-14 00:28
At that point, would it be simpler to have an `attr.json`? That would allow someone to pass in whatever shaped data they wanted, and the rule implementation function could get the decoded json structure back out (without needing to call `json.decode`)

It’s effectively the same as this suggestion, but requires fewer additional support functions or changes to how modules are processed.

**Comment by fmeum** [comment] 2022-01-14 07:03
Yes, that would be easier to work with for both module authors and Bazel users, but given the experience with adding new types described in the comment on `Type.java`, I don't think that a general new `attr` type has a chance to make it into Bazel. I don't know how complex it would be to add a new `attr` type for use in `MODULE.bazel` only, hence my idea for a different solution.

**Comment by shs96c** [comment] 2022-01-14 10:08
In a new attribute type isn't a possibility, a `use_macro` function feels similar to the `complex_value` suggestion above, but offers more flexibility for unforeseen use cases.

**Comment by illicitonion** [comment] 2022-01-14 10:49
Just to +1 the need to solve this somehow more than just living with it, here's an example from rules_rust's equivalent of rules_jvm_external:

https://github.com/bazelbuild/rules_rust/blob/ea22478f6dac4604b4ef38fb8e713cd1c0880084/examples/crate_universe/has_aliased_deps/workspace.bzl#L12-L34

This entire object is just sufficient to specify the parameters to build _one_ moderately complex third party dependency - it's conceivable that a single WORKSPACE may contain tens of this kind of attribute.

**Comment by Wyverald** [comment] 2022-05-24 16:43
Closing this for now. If there are cases where the flattening mentioned above doesn't work, we can reopen.

**Closed by Wyverald** 2022-05-24 16:43 UTC
Labels: type: feature request, team-ExternalDeps, area-Bzlmod
