### ISSUE TITLE
bazel build failed after updated  command line tool in Mac

### ISSUE THREAD

**Issue by wonderfuljamesjin** [bazelbuild/bazel#6195] opened 2018-09-21 05:40 UTC
hello

Recently I updated command line tool in my Mac as required, but after that,  my bazel build is not working, can you help advise how to fix it? thanks in advance

```
ERROR: /private/var/tmp/_bazel_me/57d181a2c7179aa428276012ffbf756a/external/com_google_protobuf/BUILD:135:1: undeclared inclusion(s) in rule '@com_google_protobuf//:protobuf':
this rule is missing dependency declarations for the following files included by 'external/com_google_protobuf/src/google/protobuf/stubs/mathlimits.cc':
  '/Library/Developer/CommandLineTools/usr/lib/clang/10.0.0/include/stddef.h'
  '/Library/Developer/CommandLineTools/usr/lib/clang/10.0.0/include/__stddef_max_align_t.h'
  '/Library/Developer/CommandLineTools/usr/lib/clang/10.0.0/include/float.h'
  '/Library/Developer/CommandLineTools/usr/lib/clang/10.0.0/include/stdint.h'
  '/Library/Developer/CommandLineTools/usr/lib/clang/10.0.0/include/stdarg.h'
  '/Library/Developer/CommandLineTools/usr/lib/clang/10.0.0/include/limits.h'
Target //java/com/myproject/target:build-deployment failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 5.268s, Critical Path: 2.42s
FAILED: Build did NOT complete successfully
```

**Comment by rmichela** [comment] 2018-09-27 17:13
I was able to work around the problem by downgrading to `Command Line Tools (macOS 10.13) for Xcode 9.4.1` from https://developer.apple.com/download/more/

(Apple ID required)

**Comment by rmichela** [comment] 2018-09-27 17:20
Looks like this happened before with a different release of command line tools #2852

**Comment by tetromino** [comment] 2018-10-17 19:57
This looks like a duplicate of #3787.

**Comment by tetromino** [comment] 2018-10-17 20:15
What does `xcode-select -p` say?

@sergiocampama, @DavidGoldman - do you have any insight about what might be causing this?

**Comment by jmmv** [comment] 2020-05-12 13:42
Closing due to lack of response, due to issue staleness, and because several things have changed in Xcode detection to make me think that this is fixed by now.

**Closed by jmmv** 2020-05-12 13:42 UTC
Labels: P2, team-Apple

**Comment by mehrdadn** [comment] 2020-05-19 10:40
@jmmv I'm encountering the same thing on Ubuntu 20.04 (which upgraded LLVM 9 to 10):

```
ERROR: [...]/com_google_protobuf/BUILD:106:1: undeclared inclusion(s) in rule '@com_google_protobuf//:protobuf_lite':
this rule is missing dependency declarations for the following files included by 'external/com_google_protobuf/src/google/protobuf/io/coded_stream.cc':
  '/usr/lib/clang/10.0.0/include/limits.h'
  '/usr/lib/clang/10.0.0/include/stddef.h'
  '/usr/lib/clang/10.0.0/include/__stddef_max_align_t.h'
  '/usr/lib/clang/10.0.0/include/stdarg.h'
  '/usr/lib/clang/10.0.0/include/stdint.h'
```

**Comment by jmmv** [comment] 2020-05-19 11:16
@mehrdadn It's not the same error given that this bug is about Mac and Xcode's command line tools. Please file a new one.
