### ISSUE TITLE
gcc: unrecognized option '-no-canonical-prefixes'

### ISSUE THREAD

**Issue by shitian-ni** [bazelbuild/bazel#3263] opened 2017-06-24 11:01 UTC
### Description of the problem / feature request / question:

I want to build bazel for tensorflow installation running `bazel build --config=opt --config=cuda //tensorflow/tools/pip_package:build_pip_package --verbose_failures`.
But error occurred.

![screen shot 2017-06-24 at 7 49 54 pm](https://user-images.githubusercontent.com/20103571/27508007-765934ca-5917-11e7-9638-e55e04ad8fee.png)

### Environment info
* Operating System:
SUSE Linux Enterprise Server 11 (x86_64)

* Bazel version (output of `bazel info release`):
bazel-0.5.1

* If `bazel info release` returns "development version" or "(@non-git)", please tell us what source tree you compiled Bazel from; git commit hash is appreciated (`git rev-parse HEAD`):
![screen shot 2017-06-24 at 8 06 09 pm](https://user-images.githubusercontent.com/20103571/27508052-a000b7c0-5918-11e7-8cb8-9cee33a72a17.png)

###  Have you found anything relevant by searching the web?
(e.g. [StackOverflow answers](http://stackoverflow.com/questions/tagged/bazel),
[GitHub issues](https://github.com/bazelbuild/bazel/issues),
email threads on the [`bazel-discuss`](https://groups.google.com/forum/#!forum/bazel-discuss) Google group)
https://github.com/bazelbuild/bazel/issues/591

### Anything else, information or logs or outputs that would be helpful?
(If they are large, please upload as attachment or provide link).

**Comment by mhlopko** [comment] 2017-06-26 11:49
Do you have gcc installed? What version do you have? Where is it? If it's not on PATH, does setting `CC` env variable (pointing at the gcc) help?

**Comment by shitian-ni** [comment] 2017-06-26 11:55
@mhlopko As the first screenshot shows, 4 lines below red ERROR sign, I think gcc 5.2 is used. 
How can I check which gcc is on PATH?

**Comment by mhlopko** [comment] 2017-06-26 11:58
`which gcc` will do it probably.

Unrelated note, if possible, prefer copy&pasted output over screenshots, text is much easier to read, reproduce, search, etc. Thanks! :)

**Comment by shitian-ni** [comment] 2017-06-26 11:59
![screen shot 2017-06-26 at 8 58 46 pm](https://user-images.githubusercontent.com/20103571/27538309-4c189920-5ab2-11e7-888b-18a65ac7377d.png)

**Comment by shitian-ni** [comment] 2017-06-26 12:00
`13B10694@t2a006161:~> which gcc`
`/usr/bin/gcc`

**Comment by mhlopko** [comment] 2017-07-03 15:47
Thanks! Now what `gcc --version` returns?

**Comment by mhlopko** [comment] 2017-08-18 12:25
Friendly ping.

**Comment by mhlopko** [comment] 2018-03-20 21:17
Closing since cannot repro.

**Closed by mhlopko** 2018-03-20 21:17 UTC
Labels: P3, category: rules > C++, type: bug
