### ISSUE TITLE
Bazel 0.5.2 prints "bit length overflow" messages when building deploy jars

### ISSUE THREAD

**Issue by philwo** [bazelbuild/bazel#3280] opened 2017-06-27 18:01 UTC
Please provide the following information. The more we know about your system and use case, the more easily and likely we can help.

### Description of the problem / feature request / question:

This command:

```bash
bazel --bazelrc=/dev/null build //src:bazel
```

Prints rather weird warning messages when building deploy jars:

```bash
INFO: From Building deploy jar src/java_tools/buildjar/JavaBuilder_deploy.jar:

bit length overflow
code 0 bits 6->7

bit length overflow
code 5 bits 6->7

bit length overflow
code 3 bits 6->7

bit length overflow
code 5 bits 6->7

bit length overflow
code 5 bits 6->7

[...]

INFO: From Building Java resource jar:

bit length overflow
code 4 bits 6->7
```

The build seems to work fine. The resulting `bazel-bin/src/bazel` binary seems to work fine, too.

### If possible, provide a minimal example to reproduce the problem:

```bash
wget https://github.com/bazelbuild/bazel/releases/download/0.5.2/bazel-0.5.2-installer-darwin-x86_64.sh
bash bazel-0.5.2-installer-darwin-x86_64.sh --user
git clone https://github.com/bazelbuild/bazel.git
bazel clean --expunge
bazel --bazelrc=/dev/null build //src:bazel
```

The warning messages happen during the last part of the build (starting from action ~960).

### Environment info
* Operating System:
macOS 10.12.5

* Bazel version (output of `bazel info release`):
`release 0.5.2`

**Comment by cushon** [comment] 2017-06-30 05:03
It's an issue with zlib: https://github.com/bazelbuild/bazel/blob/17770e5d78e640e419194504293df563d77ccf8c/third_party/zlib/trees.c#L530

It sounds like it's probably harmless:
* https://bugs.openjdk.java.net/browse/JDK-6358524
* https://bugzilla.mozilla.org/show_bug.cgi?id=431950

**Comment by cushon** [comment] 2017-06-30 05:17
Also, the log message only appears in debug builds. Shouldn't Bazel be shipping an opt build of singlejar?

**Comment by iirina** [comment] 2017-07-04 12:50
Thanks Liam for tracking this down. Since this is not a bazel issue, can we close this @damienmg ? It's definitely neither a release blocker nor a P1 bug.

**Comment by philwo** [comment] 2017-07-04 14:21
I'd vote for not closing it, but bringing it down to P2 and removing the release blocker.

It is quite annoying, because this happens during all Java builds with the released Bazel binary.

**Comment by iirina** [comment] 2017-07-04 14:53
It's not clear to me why we only get this output with this release and not before, since we only had one zlib version until now. Is JavaBuilder built differently now?

**Comment by philwo** [comment] 2017-07-04 14:56
Ha! Found the reason: https://github.com/bazelbuild/bazel/commit/d894345ed88f8adce600b66a310b5210d0bcb59c

That's actually a great change that I wanted to make myself, but couldn't get around to. The C++ version of SingleJar should be much faster than the Java one. Now we just have to get rid of the message. :)

**Comment by damienmg** [comment] 2017-07-05 02:10
A regression that output a lot of garbage output is definitely a P1 and
should be fixed by the next release. Since the message is harmless can we
simply swallow it in C++ singlejar?

**Comment by philwo** [comment] 2017-07-05 07:57
@damienmg Thanks for confirming. I restored the old attributes and will send a fix, I think it's just a one-line change to a BUILD file to turn off these messages.

**Comment by philwo** [comment] 2017-07-05 08:18
Fix sent: https://bazel-review.googlesource.com/c/12750/

**Closed** 2017-07-12 08:43 UTC
Labels: category: rules > java, P1, Release blocker, type: bug
