### ISSUE TITLE
$(location) should use runtime path when used in jvm_flags attribute

### ISSUE THREAD

**Issue by shahms** [bazelbuild/bazel#2475] opened 2017-02-02 20:57 UTC
We have a binary which requires the javac.jar be present in its bootclasspath.  Prior to bazel 0.4.4, the following invocation worked (but was obviously less than ideal):

    jvm_flags = [
        "-Xbootclasspath/p:$$JAVA_RUNFILES/bazel_tools/third_party/java/jdk/langtools/javac.jar",
    ],

With bazel 0.4.4 the file name specific path has broken, as the actual file name of the target is now `javac-9-dev-r3297-1.jar`.

Ideally, we'd be able to use `$(location @bazel_tools//third_party/java/jdk/langtools:javac_jar)`, however that expands to `external/bazel_tools/third_party/java/jdk/langtools/javac-9-dev-r3297-1.jar` which is the *build* path and not the *runtime* path for that file.  Needless to say, I'd like to avoid hard-coding another path which will break or fragile inline path-munging hacks.  It seems like the correct answer is for `$(location)` to use the runtime path when specified in `jvm_flags`.

**Comment by meteorcloudy** [comment] 2017-02-03 10:37
@damienmg Do you think it's reasonable to support this feature? Or is there a better way to find the runtime path of javac.jar?

**Comment by meteorcloudy** [comment] 2017-02-03 10:45
//cc @kchodorow

**Comment by damienmg** [comment] 2017-02-03 10:46
FWIW we cannot make $(location ) returns an absolute path but it should be able to return a path relative to the runfile tree. @kchodorow should definitely knows how / when it will be possible to do so.

**Comment by kchodorow** [comment] 2017-04-24 18:21
It's an awfully big hammer, but Skylark's `short_path` gives you the runtime path.  We're working on making the runtime path match the build path (for sources, at least), but it's taking a lot longer than planned.

**Comment by ittaiz** [comment] 2017-05-17 11:41
Hey, I have this exact same need but I can't use `short_path` since we're talking about a macro...
It's basically wrapping `rules_scala` with a macro and computing some values (one of them being the short_path of the output of the rule being wrapped)

**Comment by ittaiz** [comment] 2017-05-22 12:00
ping. I need this to be able to work with sandboxing/remote execution...

**Comment by mhlopko** [comment] 2017-05-23 11:14
Adding a link to a corresponding [StackOverflow question](https://stackoverflow.com/questions/44015847/bazel-how-to-guess-in-a-macro-the-short-path-of-the-output-of-the-instantiati).

**Comment by ulfjack** [comment] 2017-05-23 13:49
It seems reasonable to change $(location) to output the runtime path for attributes that are clearly only used at runtime. If there are any cases where it's not clear, we could add another function $(rlocation) or $(runtime_location) to return the runtime path.

**Comment by ittaiz** [comment] 2017-05-23 13:54
Another function would be great!

**Comment by ulfjack** [comment] 2017-05-23 19:56
Do you think that there are a lot of cases where it's unclear?

**Comment by ittaiz** [comment] 2017-05-23 20:09
Not at all. I have two use cases which both boil down to jvm_flags (one BUILD file and one in a macro). I'm just afraid a bit that changing the semantics would take longer than adding a new function.

**Comment by ulfjack** [comment] 2017-05-24 16:58
I can think of use cases that require making this configurable by the user (genrule.cmd), but maybe we should also disallow $(location) for jvm_flags, where it's basically never correct (I think).

**Comment by ittaiz** [comment] 2017-05-24 17:00
Why is this never correct? Or do you mean given a new runtime_location
function then this is never correct?

**Comment by shahms** [comment] 2017-05-24 17:02
Banning `$(location)` in `jvm_flags` seems like the opposite of a solution.

**Comment by ulfjack** [comment] 2017-05-24 17:02
jvm_flags are only applied at runtime, so a function that expands to the compile-time path is 'never' correct, except it happens to be ok for source files.

**Comment by ulfjack** [comment] 2017-05-24 17:03
@shahms - the proposal is to add $(rlocation), replace all uses of $(location) in jvm_flags with $(rlocation), and then disallow using $(location) in jvm_flags (ideally with a good error message).

**Comment by shahms** [comment] 2017-05-24 17:08
That makes more sense, thanks :-)

**Comment by lberki** [comment] 2017-06-14 10:46
See b1b02d70a16f34955863d93f80698369203edded for prior art.

**Comment by buchgr** [comment] 2017-06-14 11:39
Our documentation seems to suggest that file paths returned by $(location ...) are runtime paths

```
The expanded paths are relative to the runfiles directory of the *_test or *_binary rule.
```
https://bazel.build/versions/master/docs/be/make-variables.html#location

**Comment by lberki** [comment] 2017-06-14 11:57
That's untrue at least for genrules. A quick glance at the code says that we get execpaths, which makes sense because otherwise the `$(location)` support in `java_toolchain` wouldn't make sense.

**Comment by ulfjack** [comment] 2017-06-14 12:00
LocationExpander takes options, and can be configured to return runtime
paths. :-/

**Comment by lberki** [comment] 2017-06-14 12:06
Yeah. Not from the BUILD file, though.

**Comment by ulfjack** [comment] 2017-06-14 12:49
@buchgr just found out that this bug report is a bit vague in that it doesn't mention which rule you're using. java_binary actually expands the runtime location, not the compile-time location in jvm_flags, but scala_binary doesn't. The ctx.expand_location Skylark method calls into the code path that expands the compile-time location, and is not configurable. Unfortunately, if we need a Skylark API change, then this becomes more complex to implement. :-/

**Comment by buchgr** [comment] 2017-06-14 13:01
I would argue that we probably don't want `ctx.expand_location` to also support `$(rlocation :foo)`, but have a skylark method `ctx.expand_rlocation`. The reason for that being that for a given attribute one probably only ever wants to support either `$(location :foo)` or `$(rlocation :bar)`, and if both are used that's very likely an error. So then `ctx.expand_rlocation` could print a "smart" error message, if `$(location :foo)` is used.

**Comment by ulfjack** [comment] 2017-06-14 13:26
We do have cases where it's not an error to use both. :-) But there are also cases where it is a likely error to use one or the other.

**Comment by buchgr** [comment] 2017-06-14 13:40
Please ignore my previous comment. @ulfjack mentioned to me that there are certainly use cases where one would not want to have only one or the other but both `$(location :foo)` and `$(rlocation :bar)` to be expanded. 

So we want to give a rule writer the flexibility to support either `$(location :foo)` and `$(rlocation :bar)` or both. This would also be consistent with having `ctx.expand_make_variables` as a separate function, as opposed to having `ctx.expand_everything`.
 
So moving forward there are two ways to go:
1. Extend `ctx.expand_location` to also support `$(rlocation :bar)`. The advantage of this being that no Skylark API change is needed. Skylark API changes have to go through a review process, which AFAIK takes at least 10 business days. The disadvantage being that in order to support all three use cases, we would need two new Skylark functions `ctx.expand_location` (supports both), `ctx.expand_rlocation` (supports just rlocation) and `ctx.expand_elocation` (supports just location). I think that would be suboptimal API design, and might ultimately not pass the review process.
2. Leave `ctx.expand_location` as is and introduce `ctx.expand_rlocation`. The advantage of this being that the API stays small and clear, and through composition all uses cases can be supported. The disadvantage being that it will take longer to get into a release due to the review process. That is, we couldn’t have it in 0.5.2 but earliest in 0.5.3.
 
Either way, the scala rules would need to be updated and require bazel 0.5.2 or later. They currently require 0.3.1.
 
I personally favor the second option.

**Comment by shahms** [comment] 2017-06-14 14:39
We currently need to do this in a `genrule`, `java_test` and `java_binary` rules, specifically to generate a bootclasspath.  Reexamining the current usage, we are using `$(location //third_party/javac:javac_jar)` along with some calculated prefix. For the java rules, this is: `$$JAVA_RUNFILES/io_kythe/` in the genrule it's more convoluted, but effectively $PWD.

**Comment by buchgr** [comment] 2017-06-14 14:50
@shahms and where does the error happen, in `java_binary`? According to my code inspection we do use the runtime path in the `java_binary` `jvm_flags` attribute.

**Comment by ittaiz** [comment] 2017-06-14 15:00
Rules scala is going to require 0.5.2 for other reasons (java/scala interop
changes coming out). I dont understand how option 2 allows for me to expand
both? Just use both functions on the same argument?
It sounds like option 2 will take around 3-4 weeks with review and
implementation.

**Comment by buchgr** [comment] 2017-06-14 15:08
@ittaiz `ctx.expand_location(ctx.expand_rlocation(val))` should do the trick.

**Comment by ittaiz** [comment] 2017-06-14 15:33
I see.
I think two more points we haven't touched on are:
1. Option #1 allows users to start using this immediately without having to
ask rule maintainers to update their code and allows rule maintainers to
keep the current Bazel requirement since as you pointed out option #2 means
that every rule which will want to support it will have to do so explicitly
and by requiring 0.5.3 at least. If I understand correctly option 1 allows
me as a user to use 0.5.2 but have my custom rule depend on an older
version of the skylark API (since rlocation is used in the BUILD files)
2. How valuable is it to support only runtime or only compile time? What
are the use cases? I think that requirement adds a lot of complexity on
time, changes to rules and minimum Bazel version

**Comment by shahms** [comment] 2017-06-14 15:39
@buchgr if I remove the `$$JAVA_RUNFILES/io_kythe` prefix, the binary fails at runtime with something akin to:

Exception in thread "main" java.lang.NoSuchFieldError: ANNOTATION_PROCESSOR_MODULE_PATH
        at com.sun.tools.javac.file.Locations.initHandlers(Locations.java:1814)
        at com.sun.tools.javac.file.Locations.<init>(Locations.java:141)
        at com.sun.tools.javac.file.BaseFileManager.createLocations(BaseFileManager.java:115)
        at com.sun.tools.javac.file.BaseFileManager.<init>(BaseFileManager.java:76)
        at com.sun.tools.javac.file.JavacFileManager.<init>(JavacFileManager.java:147)
        at com.google.devtools.kythe.extractors.java.standalone.Javac8Wrapper.processCompilation(Javac8Wrapper.java:43)
        at com.google.devtools.kythe.extractors.java.standalone.AbstractJavacWrapper.process(AbstractJavacWrapper.java:93)
        at com.google.devtools.kythe.extractors.java.standalone.Javac8Wrapper.main(Javac8Wrapper.java:120)

That particularly exception is due to a mismatch between the javac versions which is rectified with a proper bootclasspath.

**Comment by buchgr** [comment] 2017-06-14 15:50
@shahms so you are using `java_binary` rule?

**Comment by shahms** [comment] 2017-06-14 15:55
Among others, but that is the error from running the resulting script created by a java_binary rule which uses `$(location)` directly when specifying `-Xbootclasspath` in `jvm_flags`.

**Comment by buchgr** [comment] 2017-06-14 16:05
> If I understand correctly option 1 allows
> me as a user to use 0.5.2 but have my custom rule depend on an older
> version of the skylark API (since rlocation is used in the BUILD files)

I don't think so. While the API will not have changed, the older version of bazel simply won't recognize `$(rlocation)` and thus fail.

> 2. How valuable is it to support only runtime or only compile time? What
> are the use cases? I think that requirement adds a lot of complexity on
> time, changes to rules and minimum Bazel version

E.g. `jvm_flags` should only ever use `$(rlocation :foo)`. So in case someone uses `$(location :bar)` within `jvm_flags` we could give a decent error message, stating that he probably wants to use `$(rlocation :bar)`. This might sound minor, but given that this is here to stay, in the future this will save a lot of developers a lot of time and headache.

It's true, however, that we would have to update some uses of `$(location :foo)` to `$(rlocation :foo)`. From taking a quick look, it seems to be mostly the java_library jvm_flags attribute where $(location :foo) returns the run path and not the exec path.

**Comment by ittaiz** [comment] 2017-06-14 16:53
Got you.
"the older version of bazel simply won't recognize $(rlocation) and thus
fail."- why would the older version of Bazel see $(rlocation)? When I run
with Bazel 0.5.2 and a custom rule which was built with 0.4.5 the rule uses
in runtime the 0.5.2 code, right? That's the one which needs to know about
$(rlocation) since the rules are a pipe.

In any case I need this soon but if there is an agreement that option 2 is
superior then I guess option 2 is what should be done.

**Comment by ulfjack** [comment] 2017-06-14 17:10
I would much prefer that all make variable replacement and function eval would happen as a single call, not multiple nested calls. It's simpler on the caller side, and it's more efficient as well (and potentially makes it easier for us to defer evaluation if applicable). The downside is that you need to do any necessary configuration upfront in a single method call.

But if this isn't scala_binary, but java_binary, then what's going wrong here? Maybe we can fix java_binary quickly, and defer the Skylark API to a later point in time?

**Comment by ittaiz** [comment] 2017-06-14 17:15
There are two different needs here.
One is java_binary and one is scala_binary.

**Comment by buchgr** [comment] 2017-06-14 17:36
@ulfjack 
So I created a small project to reproduce the error. Let's discuss offline. It's kind of hard to describe here and I know too little about bazel's directory structure.

As far as I can tell it's more an issue with the environment variables, than with `$(location :foo)`. It works when using `$RUNPATH` instead of `$JAVA_RUNFILES`. `$RUNPATH:="$JAVA_RUNFILES/__main__/"`. 

However, I don't know whether `$RUNPATH` is public API or not.

**Comment by buchgr** [comment] 2017-06-14 17:39
@ittaiz 
Right now, `$(location :foo)` means different things depending on where this is used. It's super confusing. We should definitely have `$(rlocation ...)` and define these things well. As far as I can tell, inside jvm_flags right now `$(location ...)` actually has `$(rlocation ...)` semantics, while inside skylark or a genrule it has not.

**Comment by buchgr** [comment] 2017-06-14 17:43
@shahms as a workaround, you should be able to use $RUNPATH instead of $JAVA_RUNFILES now, although we still have to clarify whether this is a workaround for a bug or the actual solution.

Please let me know if it works for you using $RUNPATH

**Comment by shahms** [comment] 2017-06-14 18:01
We've avoided using RUNPATH because it's not documented and hence (to our view) not supported, whereas JAVA_RUNFILES is (even if hard-coding the workspace name is suboptimal).  Ideally, we wouldn't need either of these as `$(rlocation)` would do the right thing.

**Comment by buchgr** [comment] 2017-06-14 18:07
@shahms 
My understanding is that `JAVA_RUNFILES` is documented and deprecated for `java_test`, but NOT for `java_binary`. So neither seems supported.

Can you life with using $RUNPATH for now until we understand what should happen and have `$(rlocation)` implemented?

**Comment by ulfjack** [comment] 2017-06-14 18:29
Neither works on Windows.

**Comment by buchgr** [comment] 2017-06-14 19:33
Hmm... using environment variables seems suboptimal either way.

We could update our java launcher script to `cd` into the runfiles directory before executing the binary ... that way we would not need `$JAVA_RUNFILES` et. al. $(rlocation :foo) would then return a relative path to the runfiles directory.

**Comment by ulfjack** [comment] 2017-06-15 06:32
That might be problematic for backwards compat reasons. Also, there're no
runfiles on Windows.

**Comment by buchgr** [comment] 2017-06-15 08:35
> That might be problematic for backwards compat reasons.

How so? Did we provide guarantees where the java binary is executed?

> Also, there're no
> runfiles on Windows.

There must be a folder, where all the generated artifacts are stored though? So on Windows we can just change directory to that one. No?

**Comment by ulfjack** [comment] 2017-06-15 15:38
Even if it wasn't documented, silently changing the cwd underneath is a _big_ change. Just think of a binary that takes a relative path on the command line - complete breakage. I think that's very likely a no-go.

No, we create a symlink tree for the runfiles on Linux, but we don't create a symlink tree at all on Windows, so there's no corresponding directory. Instead, Windows binaries need to look up the actual location given the runfiles path from a text file.

**Comment by ittaiz** [comment] 2017-06-15 17:34
Who's going to decide between option 1 and 2?

**Comment by buchgr** [comment] 2017-06-16 09:25
@ittaiz I think that will be a longer term thing. I would be happy to pick that up after my vacation. It doesn't seem to affect this issue though, since you are not using the scala rules.

@ulfjack 
That's fair. How about this: 

We implement `$(rlocation :foo)` to always generate the text `rlocation(relative/runfiles/path/to/foo)`. In our launcher scripts we parse this expression at invocation time and evaluate it to the correct path. This would be a well defined interface between the launcher script and bazel's `$(rlocation :foo)`. It's then up to the launcher script to resolve it correctly.

For Linux/OSX the Java Launcher Script could just prefix these paths with `$0.runfiles/__workspace__/`. On Windows it would do the path lookup in the text file and replace it with the correct path.

**Comment by ittaiz** [comment] 2017-06-16 09:38
We are using the scala rules. I'm not sure who said otherwise. I'll do some
analysis on Sunday to see if we can leverage the recent JavaProvider
changes (which should be out in 0.5.2 to help us out of this bind). Will
update as soon as I have more.

**Comment by buchgr** [comment] 2017-06-16 10:34
Quote @shahms 
> We currently need to do this in a genrule, java_test and java_binary rules, specifically to generate a bootclasspath.

**Comment by ittaiz** [comment] 2017-06-16 11:22
Yeah, there was a confusion.
I guess from the chatter my previous [clarification](https://github.com/bazelbuild/bazel/issues/2475#issuecomment-308498817) was missed.

**Comment by buchgr** [comment] 2017-06-16 11:44
I still don't get it. Is this bug report about `java_library` or `scala_library`?

**Comment by buchgr** [comment] 2017-06-16 13:08
@ittaiz @shahms 
I ll be on vacation for two weeks starting tomorrow. 

While not ideal at all, it seems like the `$RUNPATH/$(location :target)` hack would be a viable workaround, until we have `$(rlocation :target)` properly implemented on all platforms and skylark. Could you guys life with that hack for the next 4-6 weeks?

**Comment by ittaiz** [comment] 2017-06-16 13:55
I think the originator of this bug opened it for `java_binary`. When I commented I think we didn't understand there's a difference so I joined this ticket **although** mine is for `scala_binary`.

I can live with whatever hack works. I'll try your suggestion and if it works then I'm good.

**Comment by ittaiz** [comment] 2017-06-16 13:56
BTW,
@ulfjack said this already works for `java_binary` (since it can call the exposed native API) so what is the problem there?

**Comment by buchgr** [comment] 2017-06-16 14:10
> @ulfjack said this already works for java_binary (since it can call the exposed native API) so what is the problem there?

What do you mean by native API?

**Comment by ittaiz** [comment] 2017-06-16 14:14
[here](https://github.com/bazelbuild/bazel/issues/2475#issuecomment-308420725):

> java_binary actually expands the runtime location, not the compile-time location in jvm_flags, but scala_binary doesn't. The ctx.expand_location Skylark method calls into the code path that expands the compile-time location, and is not configurable. Unfortunately, if we need a Skylark API change, then this becomes more complex to implement. :-/

**Comment by buchgr** [comment] 2017-06-16 14:19
@ittaiz Oh I see, yes. You should still need the `$RUNPATH` prefix as I mentioned and this hack is not portable to Windows :(.

**Comment by ittaiz** [comment] 2017-06-16 14:21
So the `$RUNPATH` prefix would only work for `java_binary`? I'm good (for the next couple of months) with no windows

**Comment by buchgr** [comment] 2017-06-16 14:25
@ittaiz yes I believe so.

**Comment by ittaiz** [comment] 2017-06-16 14:29
:( That will probably be a big problem for me.
Let's hope I'll be able to push the move for `scala_junit_test` to compose of `scala_library` and `java_test`. Given it's something we've been wanting for more than a year I guess there are a few more bumps which I haven't seen yet.
cc @steren

**Comment by shahms** [comment] 2017-06-16 15:10
Yeah, $RUNPATH will serve us for now (we've been working around this for a while anyway). Thanks!

**Comment by buchgr** [comment] 2017-06-16 15:57
@ittaiz 
I am sorry about that :-(. I ll make it a priority once I am back from vacation.

You could take a look at rules appengine and do the same inside rules scala maybe?
 https://github.com/bazelbuild/rules_appengine/blob/master/appengine/appengine.bzl#L176

**Comment by ittaiz** [comment] 2017-06-16 17:54
You shouldn't be sorry at all, you're doing the best you can. Thank you!
I'll take a look and see.

**Comment by helenalt** [comment] 2017-07-11 13:10
@buchgr looking for an update on this thread

**Comment by buchgr** [comment] 2017-07-13 07:18
I won't get to it until the end of next week. I was tasked with helping to fix bazel's remote execution for the 0.5.3 release.

**Comment by ittaiz** [comment] 2017-08-24 14:59
Any update on this?

**Comment by buchgr** [comment] 2017-08-24 15:04
Yes, I ll get to it Monday!

**Comment by ittaiz** [comment] 2017-08-24 15:37
Awesome, thanks!

**Comment by ittaiz** [comment] 2017-08-25 08:46
Jakob,
Will this still take weeks due to skylark review process?

**Comment by buchgr** [comment] 2017-08-25 08:53
I expect this to take several weeks yes. I first need to come up with a design that works for all rules and platforms.

**Comment by ulfjack** [comment] 2017-10-02 07:31
Assigning to myself since I've been doing some code refactoring.

**Comment by ittaiz** [comment] 2017-10-02 07:52
Any **rough** idea on eta of this?

**Comment by ulfjack** [comment] 2017-10-10 08:02
The changes above are part of an internal refactoring that should make it much more straightforward to define and implement the right Skylark API. However, I haven't even started on the Skylark API yet, and that also needs to be reviewed by the Skylark team. I think that I'll have a Skylark API proposal in the next two weeks, plus some time for reviewing, and then some more time for implementation.

**Comment by ittaiz** [comment] 2017-10-10 13:31
I see.
Just to make sure I'm not mistaken- if one is using $(location) they
currently can't use remote execution right? Can they use remote caching?

**Comment by ulfjack** [comment] 2017-10-10 15:10
Uhm. If you are relying on a binary that you configure with a file path, and you're using $(location) for the file path, and you are trying to run that binary in an action, and the binary is executed in the Bazel exec root, then the action will likely fail if executed remotely. You can still use remote execution for all other actions, and you can use remote caching in any case.

You can annotate actions / rules with the "local" tag to get them to not be executed remotely (although I think if you do then they're also not remotely cached).

**Comment by ittaiz** [comment] 2017-10-10 16:35
The context is mainly tests which need this and are configured with it so I
think this indeed means we can't run tests remotely which in macOS (with
our existing tests) means we can't parallel them since the parallelism
solution was based on a local-remote worker running in docker.

**Comment by ulfjack** [comment] 2017-10-23 15:05
Actually, I have a plan for implementing the new rlocation (exact name TBD) function without changing the Skylark API. It would be nicer to have a new Skylark API, but it doesn't necessarily block fixing this in the short term. I should have an update this week.

**Comment by ulfjack** [comment] 2017-10-25 11:13
My proposal is that we add $(execpath), $(execpaths), $(rootpath), and $(rootpaths) functions that work the same way as $(location), but always use exec paths or root-relative paths (runtime / runfiles paths) respectively. The way I'm adding them they become available whenever $(location) is available, and perform the exact same label / dependency lookup.

I have a pending change for this, on top of a stack of four more pending changes to finish the internal refactorings.

**Comment by ittaiz** [comment] 2017-10-25 12:11
Excuse me for the noob question but what is the different between execpath and rootpath? Or rather why is rootpath needed? I assume execpath is like $(location) but when I execute the code

**Comment by ulfjack** [comment] 2017-10-25 12:46
For example, say you have expansion/BUILD:
```
genrule(name = "foo", outs = ["foo.txt"], srcs = ["bar.txt"], cmd = "cp $< $@")
```

foo.txt:
execpath = bazel-out/darwin-fastbuild/bin/expansion/foo.txt
rootpath = expansion/foo.txt

bar.txt:
execpath = expansion/bar.txt
rootpath = expansion/bar.txt

The current $(location) function sometimes returns the exec path, and sometimes returns the root-relative path, depending on how the expander is configured (except you can't configure it through the skylark API, which has no knob for that).

**Comment by ittaiz** [comment] 2017-10-25 12:53
I think I understand.
It sounds like from skylark (due to the lack of knob) $(location) always
works like $(rootpath)

**Comment by ulfjack** [comment] 2017-11-02 20:39
Unfortunately there have been some delays due to travel and public holidays in Germany, as well as a commit gone wrong, which I had to revert. I'm currently rolling it forward again, and I have a few more changes on top of that, but they're not under review yet. It looks like we'll miss the 0.8.0 window, unfortunately.

**Comment by alexeagle** [comment] 2017-11-10 19:47
When this does land - please also add testing for cross-workspace paths. If I use `$(rootpath @other_wksp//:thing)` I would expect `external/other_wksp/thing` or so

**Comment by davido** [comment] 2017-11-25 17:51
> Exception in thread "main" java.lang.NoSuchFieldError: ANNOTATION_PROCESSOR_MODULE_PATH

I'm seeing a similar failure when running Bazel `java_tools` tests on Windows: #4165.

**Comment by rzhw** [comment] 2018-02-22 23:57
Quick note that cross-workspace path tests were added in 702429bbc4d84c0da2499297a2d249237f5e6257.

**Closed** 2018-06-11 08:36 UTC
Labels: P1, category: extensibility > external repositories, customer impact, external-repos-triaged, type: feature request
