### ISSUE TITLE
Documentation issue: Migrate persistent workers content

### ISSUE THREAD

**Issue by floriographygoth** [bazelbuild/bazel#11344] opened 2020-05-10 16:34 UTC
Documentation URL: https://blog.bazel.build/2015/12/10/java-workers.html

There is good information in the "Persistent workers" blog, but it isn't in the canonical docs.

**Comment by laurentlb** [comment] 2020-05-13 10:20
Related:
* https://github.com/bazelbuild/bazel/issues/7997
* https://medium.com/@mmorearty/how-to-create-a-persistent-worker-for-bazel-7738bba2cabb

cc @philwo

**Comment by jmmv** [comment] 2020-05-15 13:52
I'd just say this is a duplicate of #7997?

**Closed by jmmv** 2020-05-15 13:52 UTC
Labels: team-Local-Exec, type: documentation, untriaged
