### ISSUE TITLE
bazel 0.12: 'error in opening zip file' when reading ijar created from maven_jar

### ISSUE THREAD

**Issue by roblg** [bazelbuild/bazel#5111] opened 2018-04-27 20:39 UTC
### Description of the problem / feature request:

In bazel 0.12, on OSX only, there appears to be a regression in ijar behavior. I pushed a minimal example to: https://github.com/roblg/bazel-ijar-issue-example

The tl;dr is, if you end up with an empty `maven_jar` as an external dependency (which can happen with automatic migrations from maven), bazel generates an invalid ijar that can't be read.

```
error: error reading bazel-out/darwin-fastbuild/genfiles/external/selenium_java/jar/_ijar/jar/external/selenium_java/jar/selenium-java-3.8.1-ijar.jar; error in opening zip file
```

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

See: https://github.com/roblg/bazel-ijar-issue-example

### What operating system are you running Bazel on?

OSX Sierra. Bazel 0.12 on linux doesn't appear to be affected.

### What's the output of `bazel info release`?

```release 0.12.0```

### Any other information, logs, or outputs that you want to share?

This doesn't appear to affect 0.13.0rc5, but I also didn't see an obviously related bug report, so I wanted to file in case someone else runs into this (or in case there's a future regression risk here that could be mitigated).

**Comment by iirina** [comment] 2018-05-02 10:00
cc: @tomlu might be related to the recent ijar stamping change

**Comment by tomlu** [comment] 2018-05-02 15:42
I'd guess this is because the manifest wasn't included in the presizing calculations that ijar does for its buffer, so for very small inputs it could fail. This was fixed on 2018-03-21, if that matches the timelines.

**Comment by cushon** [comment] 2018-05-02 18:33
My guess is the same as @tomlu's. I wasn't able to reproduce with 0.12, which doesn't rule out that issue.

@roblg please re-open if you see this again at head.

**Closed by cushon** 2018-05-02 18:33 UTC
Labels: category: rules > java, type: bug
