### ISSUE TITLE
Occasionally missing output files from remote cache with BwtB

### ISSUE THREAD

**Issue by joeljeske** [bazelbuild/bazel#21989] opened 2024-04-12 16:55 UTC
### Description of the bug:

After bumping from Bazel 6.4.0 -> 7.1.1, I see that after Bazel completes a build with remote_download_topelevel, sometimes there are one or more missing files that should have been downloaded from RBE/RC. It is inconsistent which files are missing, and do not have a pattern in mnemonic or file extension. If I retry the same build on that machine immediately after, the file is still missing. 

### Which category does this issue belong to?

Remote Execution

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

I do not have a consistent repro yet. 

### Which operating system are you running Bazel on?

Ubuntu

### What is the output of `bazel info release`?

release 7.1.1

### Is this a regression? If yes, please try to identify the Bazel commit where the bug was introduced.

Yes. I did not see these errors in 6.4.0

**Comment by brentleyjones** [comment] 2024-04-12 20:26
Maybe https://github.com/bazelbuild/bazel/issues/20737 is related? Does `--noexperimental_merged_skyframe_analysis_execution` fix it for you?

**Comment by joeljeske** [comment] 2024-04-12 21:15
Ah interesting. Let me give it a shot.

**Comment by joeljeske** [comment] 2024-04-17 16:44
Yes, @brentleyjones you are right. Flipping that flag off has eliminated this class of errors. Thank you!

Perhaps #20737 should be re-titled to not appear BEP-specific, but rather any output files could be missing?

**Comment by tjgq** [comment] 2024-04-23 09:25
Pretty sure this is a dupe of https://github.com/bazelbuild/bazel/issues/20737.

**Closed by tjgq** 2024-04-23 09:25 UTC
Labels: type: bug, untriaged, team-Remote-Exec
