### ISSUE TITLE
[documentation] Tutorials for Go language/project

### ISSUE THREAD

**Issue by ionutnechita** [bazelbuild/bazel#12766] opened 2021-01-03 18:15 UTC
Hi Bazel Team,

I noticed on your documentation page, 4 languages with related tutorials. ( C++, Java, Android and iOS ).
https://docs.bazel.build/versions/3.7.0/bazel-overview.html#tutorials

Would it be possible to create an example in Go language?

It would be a starting point for those with projects in Go.

I intend to use the bazel for a new project in the future.

Thanks.

**Comment by communikit** [comment] 2021-02-10 17:29
Since this also asking for a Go tutorial, closing as dupe of #3396

**Closed by communikit** 2021-02-10 17:29 UTC
Labels: P3, team-Documentation, type: feature request
