### ISSUE TITLE
Bazel 18.0: An illegal reflective access operation has occurred

### ISSUE THREAD

**Issue by olafure** [bazelbuild/bazel#6500] opened 2018-10-24 14:58 UTC
Ubuntu 16.04 / 64
```
rm -rf ~/.cache/bazel/
$ ./bazel shutdown
$ ./bazel 
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.protobuf.UnsafeUtil (file:/home/user/.cache/bazel/_bazel_user/install/f1e11885a5cc7ba9947679cffb18bf94/_embedded_binaries/A-server.jar) to field java.lang.String.value
WARNING: Please consider reporting this to the maintainers of com.google.protobuf.UnsafeUtil
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
WARNING: --batch mode is deprecated. Please instead explicitly shut down your Bazel server using the command "bazel shutdown".
                                                          [bazel release 0.18.0]

```

**Comment by davido** [comment] 2018-10-24 15:17
Duplicate of #6151.

**Closed** 2018-10-24 16:17 UTC
