### ISSUE TITLE
Fail to load file after updating bazel...

### ISSUE THREAD

**Issue by Sinn** [bazelbuild/bazel#246] opened 2015-06-15 19:18 UTC
So I'm using gtest, and followed the tips on the C++ basics... So when I attempt to build empty (just a main function returning 0), i get Failed to load File error.If I remove the gtest dependency and the include header from the empty.c file and I'm able to build. This just happened after I updated bazel, been around 3 to 4 weeks from previous update. I'm able to anything that is not depending on gtest.
WORKSPACE
```
    new_http_archive(
        name = "gtest",
        url = "https://googletest.googlecode.com/files/gtest-1.7.0.zip",
        sha256 = "247ca18dd83f53deb1328be17e4b1be31514cedfc1e3424f672bf11fd7e0d60d",
        build_file = "gtest.BUILD",
    )
```
gtest.BUILD
```
    cc_library(
        name = "main",
        srcs = glob(
            ["gtest-1.7.0/src/*.cc"],
            exclude = ["gtest-1.7.0/src/gtest-all.cc"]
        ),
        hdrs = glob(["gtest-1.7.0/include/**/*.h"]),
        includes = [
            "gtest-1.7.0",
            "gtest-1.7.0/include"
        ],
        linkopts = ["-pthread"],
        visibility = ["//visibility:public"],
    )
```
BUILD
```
    cc_binary(
        name = "empty",
        srcs = ["empty.c"],
        deps = ["@gtest//:main"],
    )
```

**Comment by Sinn** [comment] 2015-06-15 19:56
Also when doing bazel fecth ...
´´´
no such package 'external': Error extracting /private/var/tmp/***/b617756f007b2f3d025bc5e5204b3edc/external/gtest/gtest-1.7.0.zip to /private/var/tmp/***/b617756f007b2f3d025bc5e5204b3edc/external/gtest: /private/var/tmp/***/b617756f007b2f3d025bc5e5204b3edc/external/gtest/gtest-1.7.0/build-aux/config.h.in and...
´´´
Files are there though...

**Comment by kchodorow** [comment] 2015-06-15 20:13
Thanks for the report, I'm looking into it.

**Comment by kchodorow** [comment] 2015-06-15 20:51
Temporary workaround: run bazel clean --expunge, then build.

This was caused by
https://github.com/google/bazel/commit/86746cefb3996f3014d88a281d719b469761bf98
(and is kind of a side-effect of https://github.com/google/bazel/issues/236
).

**Comment by Sinn** [comment] 2015-06-15 21:03
Thanks, that worked.

**Comment by kchodorow** [comment] 2016-01-06 17:53
This is now fixed.

**Closed by kchodorow** 2016-01-06 17:53 UTC
Labels: bug, duplicate, external repositories, P3
