### ISSUE TITLE
Invalid remote execution TLS flags silently crash Bazel 

### ISSUE THREAD

**Issue by lfpino** [bazelbuild/bazel#13786] opened 2021-08-02 10:18 UTC
### Description of the problem / feature request:
Passing an invalid value to --tls_client_certificate and/or --tls_client_key silently crashes Bazel

$ cat BUILD 
sh_binary(
  name = "foo_sh",
  srcs = ["foo.sh"],
)
$ touch WORKSPACE
$ bazel build :foo_sh --remote_executor=foo --tls_certificate=tlscert --tls_client_certificate=client --tls_client_key=tlskey
--Silently crashes--
$ bazel --client_debug build :foo_sh --remote_executor=foo --tls_certificate=tlscert --tls_client_certificate=client --tls_client_key=tlskey
[INFO 12:14:38.550 src/main/cpp/option_processor.cc:407] Looking for the following rc files: /etc/bazel.bazelrc,/home/luis/dev/experimental/.bazelrc,/home/luis/.bazelrc
[INFO 12:14:38.550 src/main/cpp/rc_file.cc:56] Parsing the RcFile /home/luis/.bazelrc
[INFO 12:14:38.550 src/main/cpp/blaze.cc:1626] Debug logging requested, sending all client log statements to stderr
[INFO 12:14:38.551 src/main/cpp/blaze.cc:1509] Acquired the client lock, waited 0 milliseconds
[INFO 12:14:38.554 src/main/cpp/blaze.cc:1697] Trying to connect to server (timeout: 30 secs)...
[INFO 12:14:38.561 src/main/cpp/blaze.cc:1264] Connected (server pid=11000).
[INFO 12:14:38.561 src/main/cpp/blaze.cc:1974] Releasing client lock, let the server manage concurrent requests.
[INFO 12:14:39.025 src/main/cpp/blaze.cc:2093] failure_detail: message: "Crashed: (java.lang.RuntimeException) java.io.IOException: Failed to init TLS infrastructure using \'tlscert\' as root certificate: File does not contain valid certificates: tlscert, (java.io.IOException) Failed to init TLS infrastructure using \'tlscert\' as root certificate: File does not contain valid certificates: tlscert, (java.lang.IllegalArgumentException) File does not contain valid certificates: tlscert, (java.security.cert.CertificateException) could not find certificate file: tlscert"
crash {
  causes {
    throwable_class: "java.lang.RuntimeException"
    message: "java.io.IOException: Failed to init TLS infrastructure using \'tlscert\' as root certificate: File does not contain valid certificates: tlscert"
    stack_trace: "io.reactivex.rxjava3.internal.util.ExceptionHelper.wrapOrThrow(ExceptionHelper.java:46)"
    stack_trace: "io.reactivex.rxjava3.internal.observers.BlockingMultiObserver.blockingGet(BlockingMultiObserver.java:94)"
    stack_trace: "io.reactivex.rxjava3.core.Single.blockingGet(Single.java:3645)"
    stack_trace: "com.google.devtools.build.lib.remote.ReferenceCountedChannel.newCall(ReferenceCountedChannel.java:100)"
    stack_trace: "io.grpc.stub.MetadataUtils$HeaderAttachingClientInterceptor.interceptCall(MetadataUtils.java:74)"
    stack_trace: "io.grpc.ClientInterceptors$InterceptorChannel.newCall(ClientInterceptors.java:156)"
    stack_trace: "io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:142)"
    stack_trace: "build.bazel.remote.execution.v2.CapabilitiesGrpc$CapabilitiesBlockingStub.getCapabilities(CapabilitiesGrpc.java:227)"
    stack_trace: "com.google.devtools.build.lib.remote.RemoteServerCapabilities.lambda$get$0(RemoteServerCapabilities.java:79)"
    stack_trace: "com.google.devtools.build.lib.remote.Retrier.execute(Retrier.java:244)"
    stack_trace: "com.google.devtools.build.lib.remote.RemoteRetrier.execute(RemoteRetrier.java:125)"
    stack_trace: "com.google.devtools.build.lib.remote.RemoteRetrier.execute(RemoteRetrier.java:114)"
    stack_trace: "com.google.devtools.build.lib.remote.RemoteServerCapabilities.get(RemoteServerCapabilities.java:79)"
    stack_trace: "com.google.devtools.build.lib.remote.RemoteModule.verifyServerCapabilities(RemoteModule.java:178)"
    stack_trace: "com.google.devtools.build.lib.remote.RemoteModule.beforeCommand(RemoteModule.java:433)"
    stack_trace: "com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.execExclusively(BlazeCommandDispatcher.java:378)"
    stack_trace: "com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.exec(BlazeCommandDispatcher.java:231)"
    stack_trace: "com.google.devtools.build.lib.server.GrpcServerImpl.executeCommand(GrpcServerImpl.java:543)"
    stack_trace: "com.google.devtools.build.lib.server.GrpcServerImpl.lambda$run$1(GrpcServerImpl.java:606)"
    stack_trace: "io.grpc.Context$1.run(Context.java:579)"
    stack_trace: "java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)"
    stack_trace: "java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)"
    stack_trace: "java.base/java.lang.Thread.run(Unknown Source)"
  }
  causes {
    throwable_class: "java.io.IOException"
    message: "Failed to init TLS infrastructure using \'tlscert\' as root certificate: File does not contain valid certificates: tlscert"
    stack_trace: "com.google.devtools.build.lib.authandtls.GoogleAuthUtils.createSSlContext(GoogleAuthUtils.java:131)"
    stack_trace: "com.google.devtools.build.lib.authandtls.GoogleAuthUtils.newChannel(GoogleAuthUtils.java:66)"
    stack_trace: "com.google.devtools.build.lib.remote.RemoteModule$1.newChannel(RemoteModule.java:129)"
    stack_trace: "com.google.devtools.build.lib.remote.GoogleChannelConnectionFactory.lambda$create$0(GoogleChannelConnectionFactory.java:53)"
    stack_trace: "io.reactivex.rxjava3.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:43)"
    stack_trace: "io.reactivex.rxjava3.core.Single.subscribe(Single.java:4813)"
    stack_trace: "io.reactivex.rxjava3.internal.operators.single.SingleDoOnSubscribe.subscribeActual(SingleDoOnSubscribe.java:41)"
    stack_trace: "io.reactivex.rxjava3.core.Single.subscribe(Single.java:4813)"
    stack_trace: "io.reactivex.rxjava3.internal.operators.single.SingleToObservable.subscribeActual(SingleToObservable.java:35)"
    stack_trace: "io.reactivex.rxjava3.core.Observable.subscribe(Observable.java:13102)"
    stack_trace: "io.reactivex.rxjava3.core.Observable.subscribeWith(Observable.java:13155)"
    stack_trace: "com.google.devtools.build.lib.remote.grpc.SharedConnectionFactory.createUnderlyingConnectionIfNot(SharedConnectionFactory.java:93)"
    stack_trace: "com.google.devtools.build.lib.remote.grpc.SharedConnectionFactory.acquireConnection(SharedConnectionFactory.java:101)"
    stack_trace: "com.google.devtools.build.lib.remote.grpc.SharedConnectionFactory.lambda$create$4(SharedConnectionFactory.java:114)"
    stack_trace: "io.reactivex.rxjava3.internal.operators.single.SingleFlatMap$SingleFlatMapCallback.onSuccess(SingleFlatMap.java:77)"
    stack_trace: "io.reactivex.rxjava3.internal.operators.single.SingleCreate$Emitter.onSuccess(SingleCreate.java:68)"
    stack_trace: "com.google.devtools.build.lib.remote.grpc.TokenBucket$1.onNext(TokenBucket.java:79)"
    stack_trace: "io.reactivex.rxjava3.internal.util.NotificationLite.accept(NotificationLite.java:246)"
    stack_trace: "io.reactivex.rxjava3.subjects.BehaviorSubject$BehaviorDisposable.test(BehaviorSubject.java:507)"
    stack_trace: "io.reactivex.rxjava3.subjects.BehaviorSubject$BehaviorDisposable.emitFirst(BehaviorSubject.java:468)"
    stack_trace: "io.reactivex.rxjava3.subjects.BehaviorSubject.subscribeActual(BehaviorSubject.java:224)"
    stack_trace: "io.reactivex.rxjava3.core.Observable.subscribe(Observable.java:13102)"
    stack_trace: "com.google.devtools.build.lib.remote.grpc.TokenBucket.lambda$acquireToken$0(TokenBucket.java:64)"
    stack_trace: "io.reactivex.rxjava3.internal.operators.single.SingleCreate.subscribeActual(SingleCreate.java:40)"
    stack_trace: "io.reactivex.rxjava3.core.Single.subscribe(Single.java:4813)"
    stack_trace: "io.reactivex.rxjava3.internal.operators.single.SingleFlatMap.subscribeActual(SingleFlatMap.java:37)"
    stack_trace: "io.reactivex.rxjava3.core.Single.subscribe(Single.java:4813)"
    stack_trace: "io.reactivex.rxjava3.internal.operators.single.SingleDefer.subscribeActual(SingleDefer.java:43)"
    stack_trace: "io.reactivex.rxjava3.core.Single.subscribe(Single.java:4813)"
    stack_trace: "io.reactivex.rxjava3.core.Single.blockingGet(Single.java:3644)"
    stack_trace: "com.google.devtools.build.lib.remote.ReferenceCountedChannel.newCall(ReferenceCountedChannel.java:100)"
    stack_trace: "io.grpc.stub.MetadataUtils$HeaderAttachingClientInterceptor.interceptCall(MetadataUtils.java:74)"
    stack_trace: "io.grpc.ClientInterceptors$InterceptorChannel.newCall(ClientInterceptors.java:156)"
    stack_trace: "io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:142)"
    stack_trace: "build.bazel.remote.execution.v2.CapabilitiesGrpc$CapabilitiesBlockingStub.getCapabilities(CapabilitiesGrpc.java:227)"
    stack_trace: "com.google.devtools.build.lib.remote.RemoteServerCapabilities.lambda$get$0(RemoteServerCapabilities.java:79)"
    stack_trace: "com.google.devtools.build.lib.remote.Retrier.execute(Retrier.java:244)"
    stack_trace: "com.google.devtools.build.lib.remote.RemoteRetrier.execute(RemoteRetrier.java:125)"
    stack_trace: "com.google.devtools.build.lib.remote.RemoteRetrier.execute(RemoteRetrier.java:114)"
    stack_trace: "com.google.devtools.build.lib.remote.RemoteServerCapabilities.get(RemoteServerCapabilities.java:79)"
    stack_trace: "com.google.devtools.build.lib.remote.RemoteModule.verifyServerCapabilities(RemoteModule.java:178)"
    stack_trace: "com.google.devtools.build.lib.remote.RemoteModule.beforeCommand(RemoteModule.java:433)"
    stack_trace: "com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.execExclusively(BlazeCommandDispatcher.java:378)"
    stack_trace: "com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.exec(BlazeCommandDispatcher.java:231)"
    stack_trace: "com.google.devtools.build.lib.server.GrpcServerImpl.executeCommand(GrpcServerImpl.java:543)"
    stack_trace: "com.google.devtools.build.lib.server.GrpcServerImpl.lambda$run$1(GrpcServerImpl.java:606)"
    stack_trace: "io.grpc.Context$1.run(Context.java:579)"
    stack_trace: "java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)"
    stack_trace: "java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)"
    stack_trace: "java.base/java.lang.Thread.run(Unknown Source)"
  }
  causes {
    throwable_class: "java.lang.IllegalArgumentException"
    message: "File does not contain valid certificates: tlscert"
    stack_trace: "io.netty.handler.ssl.SslContextBuilder.trustManager(SslContextBuilder.java:231)"
    stack_trace: "com.google.devtools.build.lib.authandtls.GoogleAuthUtils.createSSlContext(GoogleAuthUtils.java:127)"
    stack_trace: "com.google.devtools.build.lib.authandtls.GoogleAuthUtils.newChannel(GoogleAuthUtils.java:66)"
    stack_trace: "com.google.devtools.build.lib.remote.RemoteModule$1.newChannel(RemoteModule.java:129)"
    stack_trace: "com.google.devtools.build.lib.remote.GoogleChannelConnectionFactory.lambda$create$0(GoogleChannelConnectionFactory.java:53)"
    stack_trace: "io.reactivex.rxjava3.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:43)"
    stack_trace: "io.reactivex.rxjava3.core.Single.subscribe(Single.java:4813)"
    stack_trace: "io.reactivex.rxjava3.internal.operators.single.SingleDoOnSubscribe.subscribeActual(SingleDoOnSubscribe.java:41)"
    stack_trace: "io.reactivex.rxjava3.core.Single.subscribe(Single.java:4813)"
    stack_trace: "io.reactivex.rxjava3.internal.operators.single.SingleToObservable.subscribeActual(SingleToObservable.java:35)"
    stack_trace: "io.reactivex.rxjava3.core.Observable.subscribe(Observable.java:13102)"
    stack_trace: "io.reactivex.rxjava3.core.Observable.subscribeWith(Observable.java:13155)"
    stack_trace: "com.google.devtools.build.lib.remote.grpc.SharedConnectionFactory.createUnderlyingConnectionIfNot(SharedConnectionFactory.java:93)"
    stack_trace: "com.google.devtools.build.lib.remote.grpc.SharedConnectionFactory.acquireConnection(SharedConnectionFactory.java:101)"
    stack_trace: "com.google.devtools.build.lib.remote.grpc.SharedConnectionFactory.lambda$create$4(SharedConnectionFactory.java:114)"
    stack_trace: "io.reactivex.rxjava3.internal.operators.single.SingleFlatMap$SingleFlatMapCallback.onSuccess(SingleFlatMap.java:77)"
    stack_trace: "io.reactivex.rxjava3.internal.operators.single.SingleCreate$Emitter.onSuccess(SingleCreate.java:68)"
    stack_trace: "com.google.devtools.build.lib.remote.grpc.TokenBucket$1.onNext(TokenBucket.java:79)"
    stack_trace: "io.reactivex.rxjava3.internal.util.NotificationLite.accept(NotificationLite.java:246)"
    stack_trace: "io.reactivex.rxjava3.subjects.BehaviorSubject$BehaviorDisposable.test(BehaviorSubject.java:507)"
    stack_trace: "io.reactivex.rxjava3.subjects.BehaviorSubject$BehaviorDisposable.emitFirst(BehaviorSubject.java:468)"
    stack_trace: "io.reactivex.rxjava3.subjects.BehaviorSubject.subscribeActual(BehaviorSubject.java:224)"
    stack_trace: "io.reactivex.rxjava3.core.Observable.subscribe(Observable.java:13102)"
    stack_trace: "com.google.devtools.build.lib.remote.grpc.TokenBucket.lambda$acquireToken$0(TokenBucket.java:64)"
    stack_trace: "io.reactivex.rxjava3.internal.operators.single.SingleCreate.subscribeActual(SingleCreate.java:40)"
    stack_trace: "io.reactivex.rxjava3.core.Single.subscribe(Single.java:4813)"
    stack_trace: "io.reactivex.rxjava3.internal.operators.single.SingleFlatMap.subscribeActual(SingleFlatMap.java:37)"
    stack_trace: "io.reactivex.rxjava3.core.Single.subscribe(Single.java:4813)"
    stack_trace: "io.reactivex.rxjava3.internal.operators.single.SingleDefer.subscribeActual(SingleDefer.java:43)"
    stack_trace: "io.reactivex.rxjava3.core.Single.subscribe(Single.java:4813)"
    stack_trace: "io.reactivex.rxjava3.core.Single.blockingGet(Single.java:3644)"
    stack_trace: "com.google.devtools.build.lib.remote.ReferenceCountedChannel.newCall(ReferenceCountedChannel.java:100)"
    stack_trace: "io.grpc.stub.MetadataUtils$HeaderAttachingClientInterceptor.interceptCall(MetadataUtils.java:74)"
    stack_trace: "io.grpc.ClientInterceptors$InterceptorChannel.newCall(ClientInterceptors.java:156)"
    stack_trace: "io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:142)"
    stack_trace: "build.bazel.remote.execution.v2.CapabilitiesGrpc$CapabilitiesBlockingStub.getCapabilities(CapabilitiesGrpc.java:227)"
    stack_trace: "com.google.devtools.build.lib.remote.RemoteServerCapabilities.lambda$get$0(RemoteServerCapabilities.java:79)"
    stack_trace: "com.google.devtools.build.lib.remote.Retrier.execute(Retrier.java:244)"
    stack_trace: "com.google.devtools.build.lib.remote.RemoteRetrier.execute(RemoteRetrier.java:125)"
    stack_trace: "com.google.devtools.build.lib.remote.RemoteRetrier.execute(RemoteRetrier.java:114)"
    stack_trace: "com.google.devtools.build.lib.remote.RemoteServerCapabilities.get(RemoteServerCapabilities.java:79)"
    stack_trace: "com.google.devtools.build.lib.remote.RemoteModule.verifyServerCapabilities(RemoteModule.java:178)"
    stack_trace: "com.google.devtools.build.lib.remote.RemoteModule.beforeCommand(RemoteModule.java:433)"
    stack_trace: "com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.execExclusively(BlazeCommandDispatcher.java:378)"
    stack_trace: "com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.exec(BlazeCommandDispatcher.java:231)"
    stack_trace: "com.google.devtools.build.lib.server.GrpcServerImpl.executeCommand(GrpcServerImpl.java:543)"
    stack_trace: "com.google.devtools.build.lib.server.GrpcServerImpl.lambda$run$1(GrpcServerImpl.java:606)"
    stack_trace: "io.grpc.Context$1.run(Context.java:579)"
    stack_trace: "java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)"
    stack_trace: "java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)"
    stack_trace: "java.base/java.lang.Thread.run(Unknown Source)"
  }
  causes {
    throwable_class: "java.security.cert.CertificateException"
    message: "could not find certificate file: tlscert"
    stack_trace: "io.netty.handler.ssl.PemReader.readCertificates(PemReader.java:69)"
    stack_trace: "io.netty.handler.ssl.SslContext.toX509Certificates(SslContext.java:1182)"
    stack_trace: "io.netty.handler.ssl.SslContextBuilder.trustManager(SslContextBuilder.java:229)"
    stack_trace: "com.google.devtools.build.lib.authandtls.GoogleAuthUtils.createSSlContext(GoogleAuthUtils.java:127)"
    stack_trace: "com.google.devtools.build.lib.authandtls.GoogleAuthUtils.newChannel(GoogleAuthUtils.java:66)"
    stack_trace: "com.google.devtools.build.lib.remote.RemoteModule$1.newChannel(RemoteModule.java:129)"
    stack_trace: "com.google.devtools.build.lib.remote.GoogleChannelConnectionFactory.lambda$create$0(GoogleChannelConnectionFactory.java:53)"
    stack_trace: "io.reactivex.rxjava3.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:43)"
    stack_trace: "io.reactivex.rxjava3.core.Single.subscribe(Single.java:4813)"
    stack_trace: "io.reactivex.rxjava3.internal.operators.single.SingleDoOnSubscribe.subscribeActual(SingleDoOnSubscribe.java:41)"
    stack_trace: "io.reactivex.rxjava3.core.Single.subscribe(Single.java:4813)"
    stack_trace: "io.reactivex.rxjava3.internal.operators.single.SingleToObservable.subscribeActual(SingleToObservable.java:35)"
    stack_trace: "io.reactivex.rxjava3.core.Observable.subscribe(Observable.java:13102)"
    stack_trace: "io.reactivex.rxjava3.core.Observable.subscribeWith(Observable.java:13155)"
    stack_trace: "com.google.devtools.build.lib.remote.grpc.SharedConnectionFactory.createUnderlyingConnectionIfNot(SharedConnectionFactory.java:93)"
    stack_trace: "com.google.devtools.build.lib.remote.grpc.SharedConnectionFactory.acquireConnection(SharedConnectionFactory.java:101)"
    stack_trace: "com.google.devtools.build.lib.remote.grpc.SharedConnectionFactory.lambda$create$4(SharedConnectionFactory.java:114)"
    stack_trace: "io.reactivex.rxjava3.internal.operators.single.SingleFlatMap$SingleFlatMapCallback.onSuccess(SingleFlatMap.java:77)"
    stack_trace: "io.reactivex.rxjava3.internal.operators.single.SingleCreate$Emitter.onSuccess(SingleCreate.java:68)"
    stack_trace: "com.google.devtools.build.lib.remote.grpc.TokenBucket$1.onNext(TokenBucket.java:79)"
    stack_trace: "io.reactivex.rxjava3.internal.util.NotificationLite.accept(NotificationLite.java:246)"
    stack_trace: "io.reactivex.rxjava3.subjects.BehaviorSubject$BehaviorDisposable.test(BehaviorSubject.java:507)"
    stack_trace: "io.reactivex.rxjava3.subjects.BehaviorSubject$BehaviorDisposable.emitFirst(BehaviorSubject.java:468)"
    stack_trace: "io.reactivex.rxjava3.subjects.BehaviorSubject.subscribeActual(BehaviorSubject.java:224)"
    stack_trace: "io.reactivex.rxjava3.core.Observable.subscribe(Observable.java:13102)"
    stack_trace: "com.google.devtools.build.lib.remote.grpc.TokenBucket.lambda$acquireToken$0(TokenBucket.java:64)"
    stack_trace: "io.reactivex.rxjava3.internal.operators.single.SingleCreate.subscribeActual(SingleCreate.java:40)"
    stack_trace: "io.reactivex.rxjava3.core.Single.subscribe(Single.java:4813)"
    stack_trace: "io.reactivex.rxjava3.internal.operators.single.SingleFlatMap.subscribeActual(SingleFlatMap.java:37)"
    stack_trace: "io.reactivex.rxjava3.core.Single.subscribe(Single.java:4813)"
    stack_trace: "io.reactivex.rxjava3.internal.operators.single.SingleDefer.subscribeActual(SingleDefer.java:43)"
    stack_trace: "io.reactivex.rxjava3.core.Single.subscribe(Single.java:4813)"
    stack_trace: "io.reactivex.rxjava3.core.Single.blockingGet(Single.java:3644)"
    stack_trace: "com.google.devtools.build.lib.remote.ReferenceCountedChannel.newCall(ReferenceCountedChannel.java:100)"
    stack_trace: "io.grpc.stub.MetadataUtils$HeaderAttachingClientInterceptor.interceptCall(MetadataUtils.java:74)"
    stack_trace: "io.grpc.ClientInterceptors$InterceptorChannel.newCall(ClientInterceptors.java:156)"
    stack_trace: "io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:142)"
    stack_trace: "build.bazel.remote.execution.v2.CapabilitiesGrpc$CapabilitiesBlockingStub.getCapabilities(CapabilitiesGrpc.java:227)"
    stack_trace: "com.google.devtools.build.lib.remote.RemoteServerCapabilities.lambda$get$0(RemoteServerCapabilities.java:79)"
    stack_trace: "com.google.devtools.build.lib.remote.Retrier.execute(Retrier.java:244)"
    stack_trace: "com.google.devtools.build.lib.remote.RemoteRetrier.execute(RemoteRetrier.java:125)"
    stack_trace: "com.google.devtools.build.lib.remote.RemoteRetrier.execute(RemoteRetrier.java:114)"
    stack_trace: "com.google.devtools.build.lib.remote.RemoteServerCapabilities.get(RemoteServerCapabilities.java:79)"
    stack_trace: "com.google.devtools.build.lib.remote.RemoteModule.verifyServerCapabilities(RemoteModule.java:178)"
    stack_trace: "com.google.devtools.build.lib.remote.RemoteModule.beforeCommand(RemoteModule.java:433)"
    stack_trace: "com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.execExclusively(BlazeCommandDispatcher.java:378)"
    stack_trace: "com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.exec(BlazeCommandDispatcher.java:231)"
    stack_trace: "com.google.devtools.build.lib.server.GrpcServerImpl.executeCommand(GrpcServerImpl.java:543)"
    stack_trace: "com.google.devtools.build.lib.server.GrpcServerImpl.lambda$run$1(GrpcServerImpl.java:606)"
    stack_trace: "io.grpc.Context$1.run(Context.java:579)"
    stack_trace: "java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)"
    stack_trace: "java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)"
    stack_trace: "java.base/java.lang.Thread.run(Unknown Source)"
  }
}

### What operating system are you running Bazel on?

Ubuntu 20.04

### What's the output of `bazel info release`?

release 4.1.0

###  Have you found anything relevant by searching the web?

No

**Comment by benjaminp** [comment] 2021-08-02 16:41
#13724

**Comment by coeuvre** [comment] 2021-08-03 03:58
Duplicate of #13724.

**Closed by coeuvre** 2021-08-03 03:58 UTC
