### ISSUE TITLE
[5.x] `--experimental_cc_implementation_deps` does not propagate into exec configs.

### ISSUE THREAD

**Issue by william-smith-skydio** [bazelbuild/bazel#14642] opened 2022-01-26 01:22 UTC
### Description of the problem / feature request:

Created a target with `implementation_deps` and passed `--experimental_cc_implementation_deps` on the command line. Verified that this works for targets in non-exec configurations, but for a target in exec configuration it inexplicably fails with "requires --experimental_cc_implementation_deps".

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

This is easy to reproduce. A workspace with `test/BUILD.bazel`:

```bazel
cc_binary(
    name = "foo",
    srcs = [],
    deps = [":bar"],
)

cc_library(
    name = "bar",
    hdrs = [],
    implementation_deps = [],
)

genrule(
    name = "gen",
    srcs = [],
    outs = ["gen_out"],
    cmd = "",
    exec_tools = [":foo"],
)
```

No source files needed because we can reproduce with cquery.

`bazel cquery //test:foo --experimental_cc_implementation_deps` succeeds:

```
INFO: Analyzed target //test:foo (35 packages loaded, 153 targets configured).
INFO: Found 1 target...
//test:foo (7d5651a)
INFO: Elapsed time: 1.359s
INFO: 0 processes.
INFO: Build completed successfully, 0 total actions
```

But `bazel cquery //test:gen --experimental_cc_implementation_deps` fails:

```
ERROR: /home/williamsmith/temp/test/BUILD.bazel:7:11: in implementation_deps attribute of cc_library rule //test:bar: requires --experimental_cc_implementation_deps
ERROR: /home/williamsmith/temp/test/BUILD.bazel:7:11: Analysis of target '//test:bar' failed
ERROR: Analysis of target '//test:gen' failed; build aborted: 
INFO: Elapsed time: 0.154s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (1 packages loaded, 124 targets configured)
```

It appears that the issue stems from the flag not properly propagating to the exec configuration. Removed `implementation_deps` to run `bazel cquery //test:all --experimental_cc_implementation_deps`:

```
//test:bar (5601329)
//test:bar (7d5651a)
//test:foo (5601329)
//test:foo (7d5651a)
//test:gen (7d5651a)
```

The target configuration: `bazel config 7d5651a --experimental_cc_implementation_deps | grep implementation_deps`:

```
INFO: Displaying config with id 7d5651a
  experimental_cc_implementation_deps: true
```

The exec configuration: `bazel config 5601329 --experimental_cc_implementation_deps | grep implementation_deps`:

```
INFO: Displaying config with id 5601329
  experimental_cc_implementation_deps: false
```

### What operating system are you running Bazel on?

Ubuntu 18.04.

### What's the output of `bazel info release`?

```
release 5.0.0
```

###  Have you found anything relevant by searching the web?

No.

**Comment by fmeum** [comment] 2022-01-26 07:14
It looks like this has been fixed in https://github.com/bazelbuild/bazel/commit/0c1d09e4dce4c3251c2be2c70d4575ec65b1d9d3.
The following succeeds (fixing the target name, which should be `//:gen` rather than `//test:gen` for your reproducer):
```
USE_BAZEL_VERSION=6.0.0-pre.20211110.1 bazelisk cquery //:gen --experimental_cc_implementation_deps
```

**Comment by gregestren** [comment] 2022-01-31 23:35
[@lizkammer](https://github.com/lizkammer) for 0c1d09e4dce4c3251c2be2c70d4575ec65b1d9d3.

I'll close this bug since it's fixed (@Wyverald feel free to adjust however you need for 5.1 prep).

**Closed by gregestren** 2022-01-31 23:35 UTC

**Comment by Wyverald** [comment] 2022-02-03 17:23
@bazel-io fork 5.1
