### ISSUE TITLE
`bazel version` build time string is incorrect

### ISSUE THREAD

**Issue by derekmauro** [bazelbuild/bazel#4819] opened 2018-03-09 16:39 UTC
```
$ bazel version
Build label: 0.11.1
Build target: bazel-out/k8-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Tue May 14 07:48:23 +50148 (1520362424903)
Build timestamp: 1520362424903
Build timestamp as int: 1520362424903
```

The line `Build time: Tue May 14 07:48:23 +50148 (1520362424903)` is wrong. The problem seems to stem from the computation confusing seconds with milliseconds.

```
$ date --date='@1520362424903'
Tue May 14 03:48:23 EDT 50148
$ date --date='@1520362424'
Tue Mar  6 13:53:44 EST 2018
```

**Comment by ajrepp** [comment] 2018-03-09 18:59
Seems related to #4469.

**Comment by philwo** [comment] 2018-03-16 14:30
Reassigning to @laszlocsomor, who had a fix for this (but AFAIK it had to be rolled back?).

**Comment by laszlocsomor** [comment] 2018-03-16 14:34
Yes, sadly we had to roll back the fix because it was breaking an internal test. I didn't have the time to fix it yet.

**Comment by laszlocsomor** [comment] 2018-03-16 14:58
I'm closing this as a duplicate of #4469.

**Closed by laszlocsomor** 2018-03-16 14:58 UTC
Labels: type: bug
