### ISSUE TITLE
experimental_repository_cache doesn't cache Git repositories

### ISSUE THREAD

**Issue by EdSchouten** [bazelbuild/bazel#5921] opened 2018-08-17 09:13 UTC
### Description of the problem / feature request:

When invoking Bazel with `--experimental_repository_cache=...`, I notice that all files downloaded using `http_archive()` and `http_file()` get stored there, but Git repos do not.

### Feature requests: what underlying problem are you trying to solve with this feature?

We have a bunch of systems that invoke Bazel builds through a CI system. We see that they often download third-party distfiles for nothing; they were already downloaded as part of other Bazel workspaces or on other systems. We'd like to cut down the amount of bandwidth we use.

Because of that, we're using `--experimental_repository_cache=...` to store distfiles on a shared file system.

### What's the output of `bazel info release`?

$ bazel info release
release 0.16.1

###  Have you found anything relevant by searching the web?

Similar report about Maven? https://github.com/bazelbuild/bazel/issues/4798

**Comment by aehlig** [comment] 2018-08-17 10:50
This feature request is not new (I would say, it is a duplicate of
https://github.com/bazelbuild/bazel/issues/5116); unfortunately it is
not as easy as for files (where you can use the `--experimental_repository_cache`,
or, maybe easier for your use case, the `--distdir` option). For files,
bazel has a natural identifier (the hash) of a file that it can also
verify. For external version control systems, it is a bit harder for
bazel to verify itself (which is considered essential for correctness
purpose), that it truely is a cache hit without having specific knowledge
about the version control system in question (and adding specific
knowledge for every version control system on earth wouldn't scale).

For git specifically, the current plan is to basically provide the
skylark rules with a persistant playground directory and make the rules
smart enough to use that generic git repo to avoid unnecessary fetches
(making use of the fact that git basically is a content-addressable
storage). The progress is tracked in #5116, but is rather slow. Maybe
you can coordinate with the people already working on this proposal.

-- 
Klaus Aehlig
Google Germany GmbH, Erika-Mann-Str. 33, 80636 Muenchen
Registergericht und -nummer: Hamburg, HRB 86891
Sitz der Gesellschaft: Hamburg
Geschaeftsfuehrer: Paul Terence Manicle, Halimah DeLaine Prado

**Comment by dslomov** [comment] 2018-09-10 12:32
Duplicate of #5116

**Closed by dslomov** 2018-09-10 12:32 UTC
Labels: team-ExternalDeps, untriaged
