### ISSUE TITLE
ArrayIndexOutOfBoundsException building my project with 0.5.0-release

### ISSUE THREAD

**Issue by mmorearty** [bazelbuild/bazel#3004] opened 2017-05-13 04:15 UTC
### Description of the problem / feature request / question:

Apologies again for not providing a repro case; but doing so would involve either giving you a bunch of proprietary code, or taking a lot of time to narrow this down to a smaller repro case. Hopefully the following information will be sufficient to be helpful to you...

My project, which builds fine with Bazel 0.4.5, fails with an ArrayIndexOutOfBoundsException when building from branch `release-0.5.0`, at commit 63600d7e0. Here is some of the output:

```
Target //tools/web:runner failed to build
Unhandled exception thrown during build; message: Unrecoverable error while evaluating node 'ACTION_EXECUTION:ActionLookupData{actionLookupNode=CONFIGURED_TARGET://third_party/web:minimist b8c8ccbac8a8ad873d7248727acbd71f (1193399412 1779465815), actionIndex=0}' (requested by nodes 'ARTIFACT:third_party/web/minimist.js //third_party/web:minimist b8c8ccbac8a8ad873d7248727acbd71f (513623648 1779465815)')
INFO: Elapsed time: 42.432s, Critical Path: 10.52s
java.lang.RuntimeException: Unrecoverable error while evaluating node 'ACTION_EXECUTION:ActionLookupData{actionLookupNode=CONFIGURED_TARGET://third_party/web:minimist b8c8ccbac8a8ad873d7248727acbd71f (1193399412 1779465815), actionIndex=0}' (requested by nodes 'ARTIFACT:third_party/web/minimist.js //third_party/web:minimist b8c8ccbac8a8ad873d7248727acbd71f (513623648 1779465815)')
	at com.google.devtools.build.skyframe.ParallelEvaluator$Evaluate.run(ParallelEvaluator.java:472)
	at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:497)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 0
	at com.google.common.collect.RegularImmutableList.get(RegularImmutableList.java:60)
	at com.google.devtools.build.lib.remote.TreeNodeRepository.buildParentNode(TreeNodeRepository.java:268)
	at com.google.devtools.build.lib.remote.TreeNodeRepository.buildFromActionInputs(TreeNodeRepository.java:257)
	at com.google.devtools.build.lib.remote.RemoteSpawnStrategy.exec(RemoteSpawnStrategy.java:252)
	at com.google.devtools.build.lib.analysis.actions.SpawnAction.internalExecute(SpawnAction.java:266)
	at com.google.devtools.build.lib.analysis.actions.SpawnAction.execute(SpawnAction.java:274)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.executeActionTask(SkyframeActionExecutor.java:779)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.prepareScheduleExecuteAndCompleteAction(SkyframeActionExecutor.java:722)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.access$800(SkyframeActionExecutor.java:100)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$ActionRunner.call(SkyframeActionExecutor.java:624)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$ActionRunner.call(SkyframeActionExecutor.java:581)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.executeAction(SkyframeActionExecutor.java:392)
	at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.checkCacheAndExecuteIfNeeded(ActionExecutionFunction.java:439)
	at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.compute(ActionExecutionFunction.java:200)
	at com.google.devtools.build.skyframe.ParallelEvaluator$Evaluate.run(ParallelEvaluator.java:398)
	... 4 more
java.lang.RuntimeException: Unrecoverable error while evaluating node 'ACTION_EXECUTION:ActionLookupData{actionLookupNode=CONFIGURED_TARGET://third_party/web:minimist b8c8ccbac8a8ad873d7248727acbd71f (1193399412 1779465815), actionIndex=0}' (requested by nodes 'ARTIFACT:third_party/web/minimist.js //third_party/web:minimist b8c8ccbac8a8ad873d7248727acbd71f (513623648 1779465815)')
	at com.google.devtools.build.skyframe.ParallelEvaluator$Evaluate.run(ParallelEvaluator.java:472)
	at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:497)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 0
	at com.google.common.collect.RegularImmutableList.get(RegularImmutableList.java:60)
	at com.google.devtools.build.lib.remote.TreeNodeRepository.buildParentNode(TreeNodeRepository.java:268)
	at com.google.devtools.build.lib.remote.TreeNodeRepository.buildFromActionInputs(TreeNodeRepository.java:257)
	at com.google.devtools.build.lib.remote.RemoteSpawnStrategy.exec(RemoteSpawnStrategy.java:252)
	at com.google.devtools.build.lib.analysis.actions.SpawnAction.internalExecute(SpawnAction.java:266)
	at com.google.devtools.build.lib.analysis.actions.SpawnAction.execute(SpawnAction.java:274)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.executeActionTask(SkyframeActionExecutor.java:779)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.prepareScheduleExecuteAndCompleteAction(SkyframeActionExecutor.java:722)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.access$800(SkyframeActionExecutor.java:100)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$ActionRunner.call(SkyframeActionExecutor.java:624)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$ActionRunner.call(SkyframeActionExecutor.java:581)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.executeAction(SkyframeActionExecutor.java:392)
	at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.checkCacheAndExecuteIfNeeded(ActionExecutionFunction.java:439)
	at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.compute(ActionExecutionFunction.java:200)
	at com.google.devtools.build.skyframe.ParallelEvaluator$Evaluate.run(ParallelEvaluator.java:398)
	... 4 more
```

I debugged it a little, and at that point in the code, `segments.size() = 0` and `inputStart = 0`.

If this is not enough information to be helpful, please let me know, and I'll see what I can do.

### Environment info
* Operating System:

OS X 10.12.4

* Bazel version (output of `bazel info release`):

As described above, this is branch `release-0.5.0`, at commit 63600d7e0.

**Comment by mmorearty** [comment] 2017-05-13 05:18
The target `//third_party/web:minimist` that was mentioned in the exception looks like this:

```
ts_import(
    name = "minimist",
    srcs = [
        "@DefinitelyTyped//:minimist"
    ])
```

`ts_import` is a custom rule of ours:

```
ts_import = rule(
    implementation = _ts_import_impl,
    attrs = {
        "factory": attr.string(),
        "namespace": attr.string(),
        "replace": attr.string_dict(),
        "globals": attr.string_dict(),
        "deps": attr.label_list(),
        "undeclared_deps": attr.string_list(),
        "no_deps": attr.bool(),
        "srcs": attr.label_list(
            allow_files = FileType([".js", ".d.ts"]))
    },
    outputs = {
        "dts": "%{name}.d.ts",
        "js": "%{name}.js"
    })
```

`@node_modules` looks like this:

```
    native.new_http_archive(
        name = "node_modules",
        build_file_content = NODE_MODULES_BUILD_FILE,
        url = "[url omitted]",
        sha256 = "[sha omitted]",
        strip_prefix = "node_modules")
```

The `minimist` part of node_module's build file is:

```
filegroup(
    name = "minimist",
    srcs = glob([
        "minimist/**"
    ]))
```

And `minimist/**` matches these files:

```
filegroup(
    name = "node_modules",
    srcs = [
        # ...
        "minimist/index.js",
        "minimist/package.json",
        # ...
    ])
```

**Comment by dslomov** [comment] 2017-05-16 17:01
@kchodorow could you take a look? This sounds like a potentially serious regression

**Comment by mmorearty** [comment] 2017-05-22 21:35
Good news, I was able to create a small repro case!

* Download [crashdemo.zip](https://github.com/bazelbuild/bazel/files/1020269/crashdemo.zip)
* The little shell script called `b` will run Bazel with the appropriate arguments. But to reproduce this bug, you need to use Bazel's remote caching feature, so you'll need set the environment variable `REST_CACHE_URL`. For example:

        REST_CACHE_URL=http://example.com/bazel-cache ./b

**Comment by mmorearty** [comment] 2017-05-24 00:38
Two things:

1. It turns out this affects Bazel 0.4.5 as well.
2. The above commit to Asana/bazel was my own little workaround for the crash; I don't know if it is the correct fix.

**Comment by kchodorow** [comment] 2017-05-24 16:40
This is actually related to remote caching, so I'm assigning to @ulfjack.

I tried it with 0.5.0 and it looks like there are a bunch of scenarios that cause stack traces.

With REST_CACHE_URL unset:

```
java.lang.RuntimeException: Unrecoverable error while evaluating node 'ACTION_EXECUTION:ActionLookupData{actionLookupNode=CONFIGURED_TARGET://third_party/web:tslint dd0dcde6cd650914a85c8740850caa54 (1510032701 1347877023), actionIndex=1}' (requested by nodes 'ARTIFACT:third_party/web/tslint.d.ts //third_party/web:tslint dd0dcde6cd650914a85c8740850caa54 (448242302 1347877023)')
	at com.google.devtools.build.skyframe.ParallelEvaluator$Evaluate.run(ParallelEvaluator.java:472)
	at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:497)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalStateException: Target host must not be null, or set in parameters.
	at org.apache.http.impl.client.DefaultRequestDirector.determineRoute(DefaultRequestDirector.java:787)
	at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:414)
	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:906)
	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:805)
	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:784)
	at com.google.devtools.build.lib.remote.SimpleBlobStoreFactory$RestBlobStore.get(SimpleBlobStoreFactory.java:146)
	at com.google.devtools.build.lib.remote.SimpleBlobStoreActionCache.getCachedActionResult(SimpleBlobStoreActionCache.java:218)
	at com.google.devtools.build.lib.remote.RemoteSpawnStrategy.exec(RemoteSpawnStrategy.java:264)
	at com.google.devtools.build.lib.analysis.actions.SpawnAction.internalExecute(SpawnAction.java:266)
	at com.google.devtools.build.lib.analysis.actions.SpawnAction.execute(SpawnAction.java:274)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.executeActionTask(SkyframeActionExecutor.java:779)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.prepareScheduleExecuteAndCompleteAction(SkyframeActionExecutor.java:722)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.access$800(SkyframeActionExecutor.java:100)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$ActionRunner.call(SkyframeActionExecutor.java:624)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$ActionRunner.call(SkyframeActionExecutor.java:581)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.executeAction(SkyframeActionExecutor.java:392)
	at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.checkCacheAndExecuteIfNeeded(ActionExecutionFunction.java:439)
	at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.compute(ActionExecutionFunction.java:200)
	at com.google.devtools.build.skyframe.ParallelEvaluator$Evaluate.run(ParallelEvaluator.java:398)
	... 4 more
java.lang.RuntimeException: Unrecoverable error while evaluating node 'ACTION_EXECUTION:ActionLookupData{actionLookupNode=CONFIGURED_TARGET://third_party/web:tslint dd0dcde6cd650914a85c8740850caa54 (1510032701 1347877023), actionIndex=1}' (requested by nodes 'ARTIFACT:third_party/web/tslint.d.ts //third_party/web:tslint dd0dcde6cd650914a85c8740850caa54 (448242302 1347877023)')
	at com.google.devtools.build.skyframe.ParallelEvaluator$Evaluate.run(ParallelEvaluator.java:472)
	at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:497)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalStateException: Target host must not be null, or set in parameters.
	at org.apache.http.impl.client.DefaultRequestDirector.determineRoute(DefaultRequestDirector.java:787)
	at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:414)
	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:906)
	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:805)
	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:784)
	at com.google.devtools.build.lib.remote.SimpleBlobStoreFactory$RestBlobStore.get(SimpleBlobStoreFactory.java:146)
	at com.google.devtools.build.lib.remote.SimpleBlobStoreActionCache.getCachedActionResult(SimpleBlobStoreActionCache.java:218)
	at com.google.devtools.build.lib.remote.RemoteSpawnStrategy.exec(RemoteSpawnStrategy.java:264)
	at com.google.devtools.build.lib.analysis.actions.SpawnAction.internalExecute(SpawnAction.java:266)
	at com.google.devtools.build.lib.analysis.actions.SpawnAction.execute(SpawnAction.java:274)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.executeActionTask(SkyframeActionExecutor.java:779)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.prepareScheduleExecuteAndCompleteAction(SkyframeActionExecutor.java:722)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.access$800(SkyframeActionExecutor.java:100)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$ActionRunner.call(SkyframeActionExecutor.java:624)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$ActionRunner.call(SkyframeActionExecutor.java:581)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.executeAction(SkyframeActionExecutor.java:392)
	at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.checkCacheAndExecuteIfNeeded(ActionExecutionFunction.java:439)
	at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.compute(ActionExecutionFunction.java:200)
	at com.google.devtools.build.skyframe.ParallelEvaluator$Evaluate.run(ParallelEvaluator.java:398)
	... 4 more
```

With REST_CACHE_URL set to a garbage localhost address:

```
java.lang.RuntimeException: Unrecoverable error while evaluating node 'ACTION_EXECUTION:ActionLookupData{actionLookupNode=CONFIGURED_TARGET://third_party/web:node 1002ee9a8bfc9d852de4fa9876c699c2 (1101169979 83640046), actionIndex=1}' (requested by nodes 'ARTIFACT:third_party/web/node.d.ts //third_party/web:node 1002ee9a8bfc9d852de4fa9876c699c2 (259077679 83640046)')
	at com.google.devtools.build.skyframe.ParallelEvaluator$Evaluate.run(ParallelEvaluator.java:472)
	at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:497)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.RuntimeException: PUT failed with status code 404
	at com.google.devtools.build.lib.remote.SimpleBlobStoreFactory$RestBlobStore.put(SimpleBlobStoreFactory.java:181)
	at com.google.devtools.build.lib.remote.SimpleBlobStoreActionCache.uploadBlob(SimpleBlobStoreActionCache.java:181)
	at com.google.devtools.build.lib.remote.SimpleBlobStoreActionCache.uploadBlob(SimpleBlobStoreActionCache.java:173)
	at com.google.devtools.build.lib.remote.SimpleBlobStoreActionCache.uploadFileContents(SimpleBlobStoreActionCache.java:87)
	at com.google.devtools.build.lib.remote.SimpleBlobStoreActionCache.uploadAllResults(SimpleBlobStoreActionCache.java:131)
	at com.google.devtools.build.lib.remote.RemoteSpawnStrategy.execLocally(RemoteSpawnStrategy.java:156)
	at com.google.devtools.build.lib.remote.RemoteSpawnStrategy.exec(RemoteSpawnStrategy.java:280)
	at com.google.devtools.build.lib.analysis.actions.SpawnAction.internalExecute(SpawnAction.java:266)
	at com.google.devtools.build.lib.analysis.actions.SpawnAction.execute(SpawnAction.java:274)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.executeActionTask(SkyframeActionExecutor.java:779)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.prepareScheduleExecuteAndCompleteAction(SkyframeActionExecutor.java:722)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.access$800(SkyframeActionExecutor.java:100)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$ActionRunner.call(SkyframeActionExecutor.java:624)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$ActionRunner.call(SkyframeActionExecutor.java:581)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.executeAction(SkyframeActionExecutor.java:392)
	at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.checkCacheAndExecuteIfNeeded(ActionExecutionFunction.java:439)
	at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.compute(ActionExecutionFunction.java:200)
	at com.google.devtools.build.skyframe.ParallelEvaluator$Evaluate.run(ParallelEvaluator.java:398)
	... 4 more
java.lang.RuntimeException: Unrecoverable error while evaluating node 'ACTION_EXECUTION:ActionLookupData{actionLookupNode=CONFIGURED_TARGET://third_party/web:node 1002ee9a8bfc9d852de4fa9876c699c2 (1101169979 83640046), actionIndex=1}' (requested by nodes 'ARTIFACT:third_party/web/node.d.ts //third_party/web:node 1002ee9a8bfc9d852de4fa9876c699c2 (259077679 83640046)')
	at com.google.devtools.build.skyframe.ParallelEvaluator$Evaluate.run(ParallelEvaluator.java:472)
	at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:497)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.RuntimeException: PUT failed with status code 404
	at com.google.devtools.build.lib.remote.SimpleBlobStoreFactory$RestBlobStore.put(SimpleBlobStoreFactory.java:181)
	at com.google.devtools.build.lib.remote.SimpleBlobStoreActionCache.uploadBlob(SimpleBlobStoreActionCache.java:181)
	at com.google.devtools.build.lib.remote.SimpleBlobStoreActionCache.uploadBlob(SimpleBlobStoreActionCache.java:173)
	at com.google.devtools.build.lib.remote.SimpleBlobStoreActionCache.uploadFileContents(SimpleBlobStoreActionCache.java:87)
	at com.google.devtools.build.lib.remote.SimpleBlobStoreActionCache.uploadAllResults(SimpleBlobStoreActionCache.java:131)
	at com.google.devtools.build.lib.remote.RemoteSpawnStrategy.execLocally(RemoteSpawnStrategy.java:156)
	at com.google.devtools.build.lib.remote.RemoteSpawnStrategy.exec(RemoteSpawnStrategy.java:280)
	at com.google.devtools.build.lib.analysis.actions.SpawnAction.internalExecute(SpawnAction.java:266)
	at com.google.devtools.build.lib.analysis.actions.SpawnAction.execute(SpawnAction.java:274)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.executeActionTask(SkyframeActionExecutor.java:779)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.prepareScheduleExecuteAndCompleteAction(SkyframeActionExecutor.java:722)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.access$800(SkyframeActionExecutor.java:100)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$ActionRunner.call(SkyframeActionExecutor.java:624)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$ActionRunner.call(SkyframeActionExecutor.java:581)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.executeAction(SkyframeActionExecutor.java:392)
	at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.checkCacheAndExecuteIfNeeded(ActionExecutionFunction.java:439)
	at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.compute(ActionExecutionFunction.java:200)
	at com.google.devtools.build.skyframe.ParallelEvaluator$Evaluate.run(ParallelEvaluator.java:398)
	... 4 more
```

So, looks like there are several issues here.

**Comment by ulfjack** [comment] 2017-05-24 16:52
The ArrayIndexOutOfBounds exception is most likely due to an action with 0 inputs. I fixed that at some point, but maybe I missed one code path. It's a known issue that passing bad host names will result in bad error messages / crashes for most of the remote caching implementations.

**Comment by ulfjack** [comment] 2017-05-31 07:47
I can reproduce the original report. I was mistaken about having fixed this - I was thinking of another bug (but similar). The patch you have seems about right.

**Comment by ulfjack** [comment] 2017-05-31 09:59
I've got a pull request for the AIOOB here: https://github.com/bazelbuild/bazel/pull/3085

**Closed** 2017-06-01 12:09 UTC
Labels: category: service APIs, P1, type: bug
