### ISSUE TITLE
java.lang.IllegalStateException when sandboxing a genrule with py_binary as tools

### ISSUE THREAD

**Issue by mzhaom** [bazelbuild/bazel#410] opened 2015-09-01 21:34 UTC
Snippet of my BUILD
```
py_binary(
  name = 'generate_nas_codecs',
  srcs = [
    'generate_nas_codecs.py',
  ],
  deps = [
    '//lte:rl3_codecs'
  ]
)

genrule(
  name = "generate_nas",
  tools = [
    ':generate_nas_codecs',
  ],
  cmd = 'mkdir -p $(@D); $(location :generate_nas_codecs) --cc_output=$(@D) --proto_output=lte/nas',
  outs = [
    'foo.cc'
  ]
)
```
generate_nas_codecs depends on `lte/__init__.py`

The following error message was produced by bazel:

```
INFO: Found 4 targets...
Unhandled exception thrown during build; message: Unrecoverable error while evaluating node 'ACTION_EXECUTION:action 'Executing genrule //lte/nas:generate_nas' (Genrule[[Artifact:[/usr/local/home/mzhao/s/m1/main[source]]lte/nas/generate_nas_codecs.py, Artifact:[[/usr/local/home/_bazel_mzhao/0d628749fa1a07dbc0d52d2820d49f09/main]bazel-out/host/bin]lte/nas/generate_nas_codecs, Artifact:[[/usr/local/home/_bazel_mzhao/0d628749fa1a07dbc0d52d2820d49f09/main]bazel-out/host/internal]_middlemen/lte_Snas_Sgenerate_Unas_Ucodecs-runfiles, Artifact:[/usr/local/home/mzhao/s/m1/main[source]]tools/genrule/genrule-setup.sh] -> [Artifact:[[/usr/local/home/_bazel_mzhao/0d628749fa1a07dbc0d52d2820d49f09/main]bazel-out/crosstool_v2_gcc-fastbuild/genfiles]lte/nas/nas_messages_gen.cc, Artifact:[[/usr/local/home/_bazel_mzhao/0d628749fa1a07dbc0d52d2820d49f09/main]bazel-out/crosstool_v2_gcc-fastbuild/genfiles]lte/nas/nas_messages_gen.h]])' (requested by nodes 'ARTIFACT:lte/nas/nas_messages_gen.h //lte/nas:generate_nas c9d96d36a72da57852d5385bc1a2623a', 'ARTIFACT:lte/nas/nas_messages_gen.cc //lte/nas:generate_nas c9d96d36a72da57852d5385bc1a2623a')
INFO: Elapsed time: 2.088s, Critical Path: 0.48s
java.lang.RuntimeException: Unrecoverable error while evaluating node 'ACTION_EXECUTION:action 'Executing genrule //lte/nas:generate_nas' (Genrule[[Artifact:[/usr/local/home/mzhao/s/m1/main[source]]lte/nas/generate_nas_codecs.py, Artifact:[[/usr/local/home/_bazel_mzhao/0d628749fa1a07dbc0d52d2820d49f09/main]bazel-out/host/bin]lte/nas/generate_nas_codecs, Artifact:[[/usr/local/home/_bazel_mzhao/0d628749fa1a07dbc0d52d2820d49f09/main]bazel-out/host/internal]_middlemen/lte_Snas_Sgenerate_Unas_Ucodecs-runfiles, Artifact:[/usr/local/home/mzhao/s/m1/main[source]]tools/genrule/genrule-setup.sh] -> [Artifact:[[/usr/local/home/_bazel_mzhao/0d628749fa1a07dbc0d52d2820d49f09/main]bazel-out/crosstool_v2_gcc-fastbuild/genfiles]lte/nas/nas_messages_gen.cc, Artifact:[[/usr/local/home/_bazel_mzhao/0d628749fa1a07dbc0d52d2820d49f09/main]bazel-out/crosstool_v2_gcc-fastbuild/genfiles]lte/nas/nas_messages_gen.h]])' (requested by nodes 'ARTIFACT:lte/nas/nas_messages_gen.h //lte/nas:generate_nas c9d96d36a72da57852d5385bc1a2623a', 'ARTIFACT:lte/nas/nas_messages_gen.cc //lte/nas:generate_nas c9d96d36a72da57852d5385bc1a2623a')
        at com.google.devtools.build.skyframe.ParallelEvaluator$Evaluate.run(ParallelEvaluator.java:762)
        at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$2.run(AbstractQueueVisitor.java:436)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalStateException: 'lte/__init__.py ' does not split into exactly 2 parts
        at com.google.common.base.Preconditions.checkState(Preconditions.java:173)
        at com.google.devtools.build.lib.sandbox.LinuxSandboxedStrategy.mountRunfilesFromManifests(LinuxSandboxedStrategy.java:294)
        at com.google.devtools.build.lib.sandbox.LinuxSandboxedStrategy.getMounts(LinuxSandboxedStrategy.java:194)
        at com.google.devtools.build.lib.sandbox.LinuxSandboxedStrategy.exec(LinuxSandboxedStrategy.java:119)
        at com.google.devtools.build.lib.analysis.actions.SpawnAction.internalExecute(SpawnAction.java:225)
        at com.google.devtools.build.lib.bazel.rules.genrule.GenRuleAction.internalExecute(GenRuleAction.java:59)
        at com.google.devtools.build.lib.analysis.actions.SpawnAction.execute(SpawnAction.java:233)
        at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.executeActionTask(SkyframeActionExecutor.java:769)
        at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.prepareScheduleExecuteAndCompleteAction(SkyframeActionExecutor.java:708)
        at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.access$900(SkyframeActionExecutor.java:98)
        at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$ActionRunner.call(SkyframeActionExecutor.java:609)
        at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$ActionRunner.call(SkyframeActionExecutor.java:569)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.executeAction(SkyframeActionExecutor.java:392)
        at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.checkCacheAndExecuteIfNeeded(ActionExecutionFunction.java:365)
        at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.compute(ActionExecutionFunction.java:169)
        at com.google.devtools.build.skyframe.ParallelEvaluator$Evaluate.run(ParallelEvaluator.java:726)
        ... 4 more
```

**Comment by philwo** [comment] 2015-09-02 16:06
A fix for this will be in the next push. (Duplicate of #413)

**Comment by philwo** [comment] 2015-09-03 21:13
The fix has been released - if it still doesn't work, please reopen.

**Closed by philwo** 2015-09-03 21:13 UTC
