### ISSUE TITLE
`java_library` should allow `java_toolchain` to be specified per-target

### ISSUE THREAD

**Issue by shs96c** [bazelbuild/bazel#8735] opened 2019-06-27 08:24 UTC
### Description of the problem / feature request:

When compiling a complex codebase, it is sometimes useful to have multiple java toolchains in play at the same time. Take, for example, the case where you're building a multi-release jar, and so want most classes to target Java 8. However, you also want to offer features to Java 11 developers. The simplest way to do this would be something like:

```python
java_toolchain(
  name = "java-8",
  source_version = "8",
  target_version = "8",
  ...
)

java_toolchain(
  name = "java-11",
  source_version = "11",
  target_version = "11",
  ...
)

java_library(
  name = "in-all-jars",
  # Ideally this would be set as a default, but added for clarity
  toolchain = ":java-8",
  ...
)

java_library(
  name = "new-java-only",
  toolchain = ":java-11",
  ...
)
```

### Feature requests: what underlying problem are you trying to solve with this feature?

The ability to cleanly mix different versions of Java without accidentally depending on classes from later releases in code targeting earlier releases.

### What's the output of `bazel info release`?

`release 0.26.1`

###  Have you found anything relevant by searching the web?

It may be possible to emulate much of the desired behaviour using the `javacopts` parameter of `java_library`, but that's a gross and ugly hack, and we should not stand for it.

Buck had a (poorly documented, hard to find) feature where it could set the bootclasspath depending on the selected target version of the java library being compiled. You can see a reference to it [here](https://github.com/facebook/buck/blob/master/.buckconfig#L12)

**Comment by iirina** [comment] 2019-07-03 12:14
@shs96c Thanks for the report! We are currently migrating the Java rules to platforms & toolchains (#6521). 

There are plans to enable out of the box support for building different targets with different toolchains in the same build (see #6519 and [Configurability 2019 Roadmap - flagless multiplatform builds](https://www.bazel.build/roadmaps/configuration.html)).

There is another way to accomplish this by implementing a configuration transition manually. See more at [User-defined Transitions](https://docs.bazel.build/versions/0.27.0/skylark/config.html#user-defined-transitions).

I'll close this as duplicate of #6519. Let me know if there is anything I can help with at the moment.

**Closed by iirina** 2019-07-03 12:14 UTC
Labels: team-Rules-Java, untriaged

**Comment by Globegitter** [comment] 2019-07-08 09:18
https://github.com/bazelbuild/bazel/issues/7572 is also very much related and I suppose possibly so a duplicate of #6519 then.

**Comment by smparkes** [comment] 2020-01-21 18:12
@iirina, with respect to
> There is another way to accomplish this by implementing a configuration transition manually. See more at User-defined Transitions.
Transitions are only available on the rule level, correct? So this would require a new rule instead of a rule attribute?

**Comment by dsilvasc** [comment] 2020-06-14 12:32
> There are plans to enable out of the box support for building different targets with different toolchains in the same build (see #6519 and Configurability 2019 Roadmap - flagless multiplatform builds).

Were those plans canceled?  That item is listed in the 2019 roadmap as not started and not listed in the 2020 roadmap.

**Comment by vincyyou** [comment] 2020-06-14 15:45
6519
