### ISSUE TITLE
incompatible_remap_main_repo: treat @main_repo//, @//, and // labels as equivalent.

### ISSUE THREAD

**Issue by dkelmer** [bazelbuild/bazel#7130] opened 2019-01-15 20:10 UTC
All PRs related to this change have been submitted and the behavior will not continue to evolve so this feature should be promoted to non-experimental state

**Comment by dkelmer** [comment] 2019-01-16 13:56
This flag changes the evaluation of labels where within a repository called "foo", the labels:
`@foo//some/path:lib`
`//some/path:lib`
will be treated as the same label. Right now they are treated as two different labels. 

This incompatible change is fixing a bug but it is possible that people are relying on the broken behavior in unexpected ways. Chances are no one will need to do anything, but if you encounter issues, please respond on this thread.

**Comment by deeglaze** [comment] 2019-02-27 20:26
I created #7570 before I saw this issue. This flag is causing the Asylo toolchain to fail. The CROSSTOOL has to insert compiler header include flags that point to Asylo sources when building external dependencies. This flag being true breaks the behavior that we rely on: @com_google_asylo should still resolve when building a dependency like @boringssl//:crypto, since it deponds on <netdb.h>, which Asylo's posix include paths provide.

**Comment by katre** [comment] 2019-03-01 16:19
This issue was tagged as "breaking-change-0.24" but does not appear ready to be flipped in the [0.24.0 release](https://github.com/bazelbuild/bazel/issues/6968). If this is incorrect please comment on that issue and discuss with me.

**Comment by dkelmer** [comment] 2019-03-04 16:08
@katre I was fully intending to flip it this time but I accidentally set a reminder to flip the flag right before the 0.24 cut as opposed to right after the 0.23 cut. Surprise surprise, there were breakages and I now missed the deadline :( 

So I'm now aiming for 0.25. Is there something I should update?

**Comment by katre** [comment] 2019-03-04 16:28
No, the labels are accurate now.

**Comment by dkelmer** [comment] 2019-03-04 16:29
Thanks!

**Comment by deeglaze** [comment] 2019-03-18 20:47
What is y'all's recommendation for a crosstool that depends on project X's sources to build project X, project Y (external dependency of X), and project Z (depends on X as an external dependency)?

I haven't found any way to make a single crosstool definition work for all three cases when --incompatible_remap_main_repo=true.

We get all 3 cases to work when the flag is false and our crosstool always references project X path via external/project_x_workspace/path
https://github.com/google/asylo/blob/master/asylo/distrib/sgx_x86_64/CROSSTOOL.tpl#L49

If I disregard project Z, then dropping external/project_x_workspace/ works fine. If I add both path and external/project_x_workspace/path to my crosstool, then #include_next breaks within project X and project Y, since both paths exist, and the first will go to the second instead of the system header I want.

I've since migrated the referenced CROSSTOOL to the skylark representation, and thought that I could possibly detect whether the crosstool is used by an external dependency or an internal dependency and add the appropriate paths, but this is both nasty and I don't know if it's possible.

**Comment by deeglaze** [comment] 2019-03-20 15:51
Would it be possible for Bazel to create a symlink external/main_repo_name to the main repo's source directory so that there is a canonical path to the workspace's sources both inside and outside the workspace? If the labels are the same, I think the path structures should resolve to the same place, rather than one no longer existing.

**Comment by hlopko** [comment] 2019-03-29 11:42
@deeglaze Would it be possible to create a tiny repro repository that demonstrates all your requirements that I can play with? Right now I don't see what changes with `--incompatible_remap_main_repo` and my naive repro attempt is not successful.

With Crosstool in Starlark the next logical step would be to accept artifacts for tool paths. I'd like to play with it more and your input would be very helpful. Related discussion is happening over at https://github.com/bazelbuild/bazel/issues/7746, feel free to join.

**Comment by sergiocampama** [comment] 2019-05-09 18:59
It looks like this flag affects how python tools are invoked, we're seeing errors like: https://buildkite.com/bazel/rules-apple-darwin/builds/832#4039aa5f-b5c9-4613-93eb-f3ce4ae33e31

the only change between that and a green build is adding this flag.

@brandjon ^^

**Comment by brandjon** [comment] 2019-05-09 19:05
Sounds like the flag is changing what directory names get added to the runfiles root. Python rules are known to be sensitive to the names of repos in the runfiles root. Although repo renaming in general does not (yet?) change directory names, I believe the main repo may be an exception to this.

You should be able to verify by going to the runfiles dir of the broken target and seeing if the flag controls whether or not a "build_bazel_rules_apple" directory is present.

**Comment by sergiocampama** [comment] 2019-05-09 19:16
I already verified that this flag breaks python tools, I'm wondering if it's being tracked/worked on so that this flag can be flipped by default (or that at least I can use it as a cleaner workaround than copybara to the main repo problem from #3115 )

**Comment by jayconrod** [comment] 2019-05-14 19:13
Testing rules_go with this flag on shows some failures like this:

```
$ bazel build --incompatible_remap_main_repo //go/tools/builders:embed
ERROR: While resolving toolchains for target //go/tools/builders:embed: no matching toolchains found for types @io_bazel_rules_go//go:toolchain
ERROR: Analysis of target '//go/tools/builders:embed' failed; build aborted: no matching toolchains found for types @io_bazel_rules_go//go:toolchain
```

Building the same target outside the `io_bazel_rules_go` repository succeeds.

**Comment by shahms** [comment] 2019-05-23 16:56
The Kythe failure https://buildkite.com/bazel/bazelisk-plus-incompatible-flags/builds/116#e51eb810-7764-4a5b-b59a-94e9cb7d7c87 is also related to fully-qualified toolchain_type resolution.

**Comment by shahms** [comment] 2019-05-23 17:01
```
$ bazel test --toolchain_resolution_debug //kythe/... 2>&1 |grep lexyacc 
INFO: ToolchainResolution: Looking for toolchain of type @io_kythe//tools/build_rules/lexyacc:toolchain_type...
INFO: ToolchainResolution:   Considering toolchain @local_config_lexyacc//:lexyacc_local...
INFO: ToolchainResolution:   For toolchain type @io_kythe//tools/build_rules/lexyacc:toolchain_type, possible execution platforms and toolchains: {@bazel_tools//platforms:host_platform -> @local_config_lexyacc//:lexyacc_local}
INFO: ToolchainResolver: Selected execution platform @bazel_tools//platforms:host_platform, type @io_kythe//tools/build_rules/lexyacc:toolchain_type -> toolchain @local_config_lexyacc//:lexyacc_local
INFO: ToolchainResolver: Selected execution platform @bazel_tools//platforms:host_platform, type @io_kythe//tools/build_rules/lexyacc:toolchain_type -> toolchain @local_config_lexyacc//:lexyacc_local
```
Versus:
```
$ bazel test --toolchain_resolution_debug --incompatible_remap_main_repo //kythe/... 2>&1 |grep lexyacc 
INFO: ToolchainResolution: Looking for toolchain of type @io_kythe//tools/build_rules/lexyacc:toolchain_type...
ERROR: While resolving toolchains for target //tools/build_rules/lexyacc:current_lexyacc_toolchain: no matching toolchains found for types @io_kythe//tools/build_rules/lexyacc:toolchain_type
ERROR: Analysis of target '//kythe/cxx/verifier:lexer' failed; build aborted: no matching toolchains found for types @io_kythe//tools/build_rules/lexyacc:toolchain_type
```

**Comment by hlopko** [comment] 2019-06-07 12:08
This issue does not strictly follow the policy. Could you pls update the title and provide rationale and migration instructions? This page summarizes the steps quite well: https://bazel.build/breaking-changes-guide.html. Thank you!

**Comment by aiuto** [comment] 2019-07-02 15:26
@aehlig  I believe this is the problem we were talking about the other day w.r.t. rules_pkg.
Now that @dkelmer has left the team, someone else will have to pick this up.

**Comment by dslomov** [comment] 2019-08-08 09:03
It would be *very* desirable to flipt the flag, but https://buildkite.com/bazel/bazelisk-plus-incompatible-flags/builds/201 still show breakage in downstream (including in Bazel itself). @aehlig any chance you could investigate this?

**Comment by aehlig** [comment] 2019-08-08 13:35
> It would be _very_ desirable to flipt the flag, but https://buildkite.com/bazel/bazelisk-plus-incompatible-flags/builds/201 still show breakage in downstream (including in Bazel itself). @aehlig any chance you could investigate this?

It seems that this bazelisk run used bazel 0.28.1 and the error in Bazel itself looks like #7773 where the fix was only submitted later.

**Comment by mboes** [comment] 2019-08-18 19:32
I agree that this (very breaking) change would be very desirable. rules_haskell just changed names to follow the new convention that was previously documented in the deploying guide, but unfortunately the convention has now changed again! rules_haskell is not part of the bazelbuild org, so technically we should now rename back to io_tweag_rules_haskell. Thing is, several of our users got caught out by the rename, and we don't want to inflict a change on them again.

Furthermore, when you have hundreds of BUILD files and all of them use Haskell, Scala, Go or whatever else, writing long domain qualified repo names (with no IDE help, since these are just strings) quickly gets old. The shorter name we have now for our rule set is certainly very convenient.

If this issue is fixed now, the concerns raised in https://github.com/bazelbuild/bazel/pull/8884/files#r303831544 won't be a problem anymore.

I fear that if we do not make this breaking change before Bazel 1.0, we'll be starting the Bazel ecosystem off on a poor footing and it will be difficult to reverse this later.

**Comment by aiuto** [comment] 2019-09-03 15:54
@dslomov  So this is going to not flip for 1.0?   I'll put in a last plea that we should flip it even though things break downstream.  We know 1.0 will break many projects downstream. This is the chance to correct a very strange bit of behavior that is incredibly hard to work around.

**Comment by dslomov** [comment] 2019-09-04 13:51
The problem is, @aehlig has discovered some issues with implementation of this (related to interactions between repository mappings and toolchain registration) that are hard to investigate and fix. it is not that downstream projects are broken, it is that the implementation is not fully ready. So, regrettably, we will have to keep this off.

**Comment by dhalperi** [comment] 2019-09-04 16:25
This really seems like it should be a blocker. Why is timeline rather than
functionality driving the cut?

**Comment by dslomov** [comment] 2019-09-05 08:08
Look, I agree it is unfortunate. The question is, is it a 1.0 blocker? It is not a recent regression - this has always been this way, since very early Bazel releases, and people were able to work around this. If we can fix the underlying issues fast and be confident that the implementation of this fix is rock-solid, I would gladly wait. But it does not look that way at the moment.

**Comment by laurentlb** [comment] 2019-11-15 21:00
@aehlig Did you flip the flag for Bazel 2.0? If so, please close this issue.

**Comment by aehlig** [comment] 2019-11-18 15:05
> @aehlig Did you flip the flag for Bazel 2.0? If so, please close this issue.

The flag was flipped in 81b57d605de823f8e6f846a06d8e50d9a00041e3, but there are some discussions in #10246 about undoing the flag flip. Stll, at the moment, the flag is flipped.

**Closed by aehlig** 2019-11-18 15:05 UTC
Labels: P1, breaking-change-2.0, incompatible-change, migration-0.23, migration-0.24, migration-0.25, migration-0.26, migration-0.27, migration-0.28, migration-0.29, migration-1.0, migration-1.1, migration-1.2, team-ExternalDeps
