### ISSUE TITLE
[7.1.1] Fix two `bazel mod tidy` crashes

### ISSUE THREAD

**Issue by bazel-io** [bazelbuild/bazel#21690] opened 2024-03-14 09:51 UTC
Forked from #21686

**Comment by bazel-io** [comment] 2024-03-14 17:36
Cherry-picked in https://github.com/bazelbuild/bazel/pull/21701

**Comment by Wyverald** [comment] 2024-03-14 18:09
dupe of https://github.com/bazelbuild/bazel/issues/21655

**Closed by Wyverald** 2024-03-14 18:09 UTC
