### ISSUE TITLE
Revampt CLI API

### ISSUE THREAD

**Issue by xiongchiamiov** [bazelbuild/bazel#1627] opened 2016-08-10 18:03 UTC
Sometime prior to 1.0, it would be nice if someone went through all of the CLI API and refactored it to the best they can imagine completely separated from what we currently have.  Right now there are a bunch of oddities, and once 1.0 happens I imagine you'll be even less willing to break the API that everyone's using.

For instance, if you want to override a default that's been specified in a bazelrc to make bazel stop on failures, you use the flag `--nokeep_going`.  There are several issues with this:
1. Underscores are extremely uncommon in cli flags.  If multiple words are necessary, they're almost always `--separated-by-dashes`.  Using underscores also necessitates using shift in the middle of typing a phrase, which adds more RSI-inducing strain and increases the number of `--accidental_Shift-TYpos`.
2. The mashing of "no" directly into the flag makes it difficult to read.  It turns out that Bazel also supports `--no_keep_going` and `--keep_going=no`, but these are only documented on [the website](http://www.bazel.io/docs/command-line-reference.html), not the tool itself, and are only mentioned in a general section at the top; everything about the command itself lists `--[no]keep_going`.
3. "no keep going" is just really awkwardly phrased.

These and other issues (Why does `--spawn_strategy=standalone --genrule_strategy=standalone` disable sandboxing?  What is a spawn strategy, and what is a genrule strategy?  Why are there two separate flags?  Why is it not just `--sandboxing=no`?) are rampant throughout Bazel, and we end up with very few of our users ever remembering the correct syntax, instead recording long series of commands in text files and copy+pasting them when needing to do things.

If this is an idea you'd entertain, I'd be glad to provide more examples of oddities and work on a new API, but I don't really want to go into that if you're stuck providing the same API as Blaze (or whatever).

**Comment by hermione521** [comment] 2016-08-11 08:52
@ulfjack maybe you want to answer this?

**Comment by ulfjack** [comment] 2016-08-11 09:35
1. In the 7 years I've worked on Bazel, this is the first time I hear this complaint. I agree that dashes seem slightly better, though I don't buy the RSI argument - if the amount of typing is a problem, there are other approaches to solve that. At this point in time, I'm not sure it's worth the effort to change it.

2. For a long time (years ago), I wondered why the flag is called nothin_archives - is that a typo and it's missing a g? But what does nothing_archives do? That said, we could update both the documentation and help output to change it to --keep_going[=no].

3. I'm not sure what you mean, but I'm also not a native english speaker.

4. I agree that the strategy flags are a bit weird, and are exposing an internal structure that doesn't necessarily make sense to users.

5. I also agree that we have too many options, and will happily support efforts to reduce the number options, if there is a proposal that improves the structure of things.

Blaze and Bazel are the same code; whatever changes we make to Bazel are also in Blaze, and vice versa (with some minor exceptions). If we rename all the flags, then we have to update and migrate all of our internal users as well. We have done so in the past, and we'll do so again... if it provides sufficient value.

I'm not convinced that changing to dashes provides sufficient value. I think changing the help text for boolean options is acceptable - we'd still accept the 'no' prefix as a shorthand (unless you're arguing that we shouldn't?). The *_strategy options definitely need to be reworked, and I would agree to having that block a 1.0 release.

I'd be happy to look at other proposals as well.

**Comment by jin** [comment] 2018-11-06 20:12
Closing this issue as working as intended. @xiongchiamiov, if you have a proposal on the CLI experience, please follow our new [design review process](https://bazel.build/designs/).

**Closed by jin** 2018-11-06 20:12 UTC
Labels: P3, category: extensibility > configurability, type: feature request
