### ISSUE TITLE
strings returned by glob() interpreted as labels, rather than files

### ISSUE THREAD

**Issue by ccontavalli** [bazelbuild/bazel#13150] opened 2021-03-03 20:16 UTC
### Description of the problem / feature request:

`cc_test` data dependency using `glob` is confused by file names containing `:`. Fundamentally, the string is interpreted as a label, rather than a path. How to avoid this?

### Feature requests: what underlying problem are you trying to solve with this feature?

I have a very simple scenario:

```
cc_test(
  name = "my-test",
  srcs = [ ...],
  deps = [...],
  data = glob(["testdata/**"]),
)
```
`testdata` unfortunately contains directories that contain the ':' character.
Nothing I can do about it, that's the unfortunate input naming convention, and the test I'm writing has to verify that the parsing works correctly.

For example, a directory may be named "0000:00:00.1".

When I run:
`bazel test :my-test`

I get back an error like:
ERROR: ...: my-test: invalid label 'testdata/0000:00:00.1/whatever' in element 0 of attribute 'data' in 'cc_test' rule: invalid target name 'testdata/0000:00:00.1/whatever': target names may not contain ':'.

**Ideally**, glob() would return paths escaped (is there a supported escaping scheme? Could not find references in the docs) so they can be used directly in targets. Alternatively, have a macro to perform the escaping as necessary.

### What operating system are you running Bazel on?

linux

### What's the output of `bazel info release`?

release 3.5.0

**Comment by janakdr** [comment] 2021-03-08 17:53
This isn't specific to glob: you can't refer to a source file at all that has a ':' in the name, even if you explicitly mention it in srcs or data. I think this is just a special case of https://github.com/bazelbuild/bazel/issues/374: I've asked there for confirmation, and if it is, will close this as a duplicate.

**Comment by ccontavalli** [comment] 2021-03-08 18:04
Yes, #374 is certainly related.

But orthogonal to the resolution of #374, I would expect that the function recommended for use in `BUILD` files commonly used to create the list of files to be used in attributes, returned that list in the format and with the escaping necessary for the list to be processed correctly and not mistaken for labels. I've skimmed through #374, and it was closed / reopened / closed reopened a few times, not sure what the status is.

But it sounds like once an escaping mechanism is provided (and sounds like it may be already provided? again, not sure by reading through the list), either `glob()` will need to be changed, or an escaping alternative (or options to `glob`) would need to be provided.

(stated in other ways, is there a way I can take the output of glob and escape it properly? is there a standard function to do so?).

**Comment by janakdr** [comment] 2021-03-08 22:54
My point is that all glob does is enable you to not list the files explicitly in your BUILD file. I'm not sure what it would even mean for glob to "escape" the string: if glob changed the name, then Bazel would not be able to find the file, unless Bazel had some kind of mapping from transformed names to real filenames, which is the essence of #374. Would you like to create a glob that just generates a string, not a file? It's certainly possible to do this:

```
my_rule(name = 'my_rule',  string_list_attr_not_label_list_attr = glob(['very:bad:filename/**']))
```

The issue is when the results of the glob are transformed into Labels. If you want to treat them as strings, there's no issue, but then you can't use those strings as the names of input files for Bazel.

#374 is not resolved, as far as I can see, so I'm closing this in favor fo that.

**Closed by janakdr** 2021-03-08 22:54 UTC
Labels: team-Core, type: bug, untriaged
