### ISSUE TITLE
support for excluding transitive jar from build classpath for java

### ISSUE THREAD

**Issue by rahul-nitkkr** [bazelbuild/bazel#5856] opened 2018-08-10 11:31 UTC
> ATTENTION! Please read and follow:
> - if this is a _question_ about how to build / test / query / deploy using Bazel, ask it on StackOverflow instead: https://stackoverflow.com/questions/tagged/bazel
> - if this is a _discussion starter_, send it to bazel-discuss@googlegroups.com
> - if this is a _bug_ or _feature request_, fill the form below as best as you can.

### Description of the problem / feature request:

> When using annotation processors to generate classes , having guava on the classpath causes incompatible bounds issues, due to the generated classes having guava specific implementations of java collections ->  **error: incompatible types: inference variable T has incompatible bounds**
    upper bounds: ImmutableList<ABC>,Object
    lower bounds: List<ABC>
the dependency on guava is being pulled transitively

### Feature requests: what underlying problem are you trying to solve with this feature?

> can there be a _exclude-jars_ for the java_library which allows us to specify what not to have on the classpath ?

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

> Replace this line with your answer.

### What operating system are you running Bazel on?

> Replace this line with your answer.

### What's the output of `bazel info release`?

> Replace this line with your answer.

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

> Replace this line with your answer.

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

> Replace this line with your answer.

###  Have you found anything relevant by searching the web?

> Replace these lines with your answer.
>
> Places to look:
> - StackOverflow: http://stackoverflow.com/questions/tagged/bazel
> - GitHub issues: https://github.com/bazelbuild/bazel/issues
> - email threads on https://groups.google.com/forum/#!forum/bazel-discuss

### Any other information, logs, or outputs that you want to share?

> Replace these lines with your answer.
>
> If the files are large, upload as attachment or provide link.

**Comment by davido** [comment] 2018-08-10 12:13
This is a duplicate for adding `provided_deps` attribute to `java_library` rule feature request that is tracked [here](https://github.com/bazelbuild/bazel/issues/1402).

There is a workaround, to use `neverlink = True`. That way you would probably need to duplicate quite some or all your external dependency rules: one with `neverlink = True` and one without.

**Comment by ittaiz** [comment] 2018-08-10 12:13
This sounds a bit like “provided” scope in maven, right? If so there is an
existing issue requesting that functionality and this sounds like a
duplicate of it

**Comment by rahul-nitkkr** [comment] 2018-08-10 12:58
@ittaiz : not sure if it like provided, since the transitive dep would pull in guava into the classpath,, 
@davido : so if i have my BUILD file as  
 filegroup(
    name = "main-java-sources",
    srcs = glob([
       "**/*.java"
   ]),
)

java_plugin(
    name = "org_immutables_processor_ProxyProcessor_plugin",
    generates_api = 1,
    deps = [
        "@org_immutables_value_2_4_4//:org_immutables_value_2_4_4"
    ],
    processor_class = "org.immutables.processor.ProxyProcessor",
)

java_library(
    name = "AtestBuild",
    deps = [
       "<some lib which pulls in guava>",
"@com_fasterxml_jackson_core_jackson_annotations_2_7_4//:com_fasterxml_jackson_core_jackson_annotations_2_7_4",
       "@com_fasterxml_jackson_core_jackson_databind_2_7_5//:com_fasterxml_jackson_core_jackson_databind_2_7_5",       
       "@org_apache_commons_commons_lang3_3_6//:org_apache_commons_commons_lang3_3_6",
       "@org_immutables_value_2_4_4//:org_immutables_value_2_4_4",       
       "@com_fasterxml_jackson_datatype_jackson_datatype_jdk8_2_7_4//:com_fasterxml_jackson_datatype_jackson_datatype_jdk8_2_7_4",
       "@com_fasterxml_jackson_datatype_jackson_datatype_jsr310_2_7_4//:com_fasterxml_jackson_datatype_jackson_datatype_jsr310_2_7_4",
       "@com_fasterxml_jackson_module_jackson_module_jsonSchema_2_7_5//:com_fasterxml_jackson_module_jackson_module_jsonSchema_2_7_5",
       "@com_fasterxml_jackson_core_jackson_core_2_7_4//:com_fasterxml_jackson_core_jackson_core_2_7_4",
       "@com_fasterxml_jackson_datatype_jackson_datatype_guava_2_7_4//:com_fasterxml_jackson_datatype_jackson_datatype_guava_2_7_4",             
       "@com_google_code_findbugs_jsr305_3_0_1//:com_google_code_findbugs_jsr305_3_0_1"
    ],
    srcs = [
       ":main-java-sources"
    ], 
    resources = [

    ],
    plugins = [
        ":org_immutables_processor_ProxyProcessor_plugin"
    ],
    javacopts = [ "-XepDisableAllChecks" ],
)

java_library(
    name = "AtestBuild_main",
    exports = [
        ":AtestBuild",
    ],
    visibility = ["//visibility:public"],
)

and my workspace references guava as 
new_local_repository(
    name = "com_google_guava_guava_21_0",
    path = "<path_to_guava_jar>/com.google.guava_guava-21.0",
    build_file_content = """java_import(
    name = "com_google_guava_guava_21_0",
    jars = [
        "guava.jar"
    ],
    visibility = ["//visibility:public"],
)
""",
)

, how do i go about specifying the neverlink, would it be in the BUILD file that i add a java rule for guava explicitly ?
apologies, if it sounds like a noob question!

**Comment by rahul-nitkkr** [comment] 2018-08-10 12:59
I'll add a repro as well as soon as i get home, since company firewall restrictions prohibit me to do a git commit

**Comment by davido** [comment] 2018-08-12 06:33
> how do i go about specifying the neverlink

Check the documentation: [1]. Particularly, java_import supports `neverlink`:

```python
  java_import(
      name = "foo",
      jars = ["foo-1.0.0.jar"],
      neverlink = True,
  ),
```

[1] https://docs.bazel.build/versions/master/be/java.html#java_import

**Comment by lberki** [comment] 2019-03-14 14:16
Closing this as it seems to be covered by https://github.com/bazelbuild/bazel/pull/6013 .

**Closed by lberki** 2019-03-14 14:16 UTC
Labels: team-Rules-Java, type: feature request, untriaged
