### ISSUE TITLE
Repository action to serialise and deserialise JSON

### ISSUE THREAD

**Issue by shs96c** [bazelbuild/bazel#10329] opened 2019-11-28 10:24 UTC
### Description of the problem / feature request:

One pattern that some rules follow is to provide a command for users to run to generate a config file, which is then consumed during a regular build. One example of this is `rules_jvm_external` generating its lock file. 

JSON appears to be becoming the lingua franca for this kind of information, both within the bazel ecosystem and outside it. For example, tools such as NPM use config files written in JSON.

Parsing JSON using Starlark is complicated, and there's no standardised way to do this. A method available to repository rules to serialize and deserialize JSON to and from a dict would be very helpful. If that dict contained anything that doesn't have an obvious serialization strategy, then it seems acceptable to fail the build.

### Feature requests: what underlying problem are you trying to solve with this feature?

Make handling JSON a lot easier in bazel rules.

### Similar research

The current [implementation](https://github.com/bazelbuild/rules_jvm_external/blob/master/third_party/bazel_json/lib/json_parser.bzl) used by `rules_jvm_external` is caveated as something that people shouldn't use for anything serious.

**Comment by irengrig** [comment] 2019-11-28 14:01
Duplicates #3732

**Comment by jin** [comment] 2019-11-29 05:48
Closing as dupe of #3732.

**Closed by jin** 2019-11-29 05:48 UTC
Labels: team-Front-End, untriaged
