### ISSUE TITLE
py_binary fails to find runfiles when run from symlink

### ISSUE THREAD

**Issue by drigz** [bazelbuild/bazel#4048] opened 2017-11-08 12:00 UTC
If you create a symlink to an executable created by py_binary, it will fail with `AssertionError: Cannot find .runfiles directory for ./main`.

My use case is using Bazel to create Docker containers for [ROS](http://www.ros.org/). Because ROS packages are normally installed system-wide, it expects to find executables in a certain structure, which I'm trying to recreate with symlinks.

This fails because [FindModuleSpace](https://github.com/bazelbuild/bazel/blob/7b2045e59a0ee438867acd3b11c9c6d98dcd9690/src/main/java/com/google/devtools/build/lib/bazel/rules/python/python_stub_template.txt#L74) doesn't take the link into account when guessing the path of the runfiles. It can be fixed by changing `abspath` to `realpath`, which resolves symlinks. If you'd like me to send a PR, could you point me at where I could add a test for this?

### Workaround

Use a shell script instead of a symlink:

```
#!/bin/sh
exec /path/to/executable "$@"
```

However, this means you need to add a shell to the container, so it doesn't work with normal [distroless](https://github.com/GoogleCloudPlatform/distroless) containers.

### Repro

```
> echo > WORKSPACE
> cat BUILD.bazel 
py_binary(
    name = "main",
    srcs = ["main.py"],
)
> cat main.py 
print 'hello'
> bazel build :main
> ln -s bazel-bin/main main
> ./main
Traceback (most recent call last):
  File "./main", line 178, in <module>
    Main()
  File "./main", line 117, in Main
    module_space = FindModuleSpace()
  File "./main", line 91, in FindModuleSpace
    sys.argv[0])
AssertionError: Cannot find .runfiles directory for ./main
```

### Environment info
* Operating System: Ubuntu 14.04
* Bazel version: 0.7.0

**Comment by damienmg** [comment] 2017-11-08 19:32
Duplicate of #4022

**Closed** 2017-11-08 19:32 UTC
