### ISSUE TITLE
Seemingly duplicate labels

### ISSUE THREAD

**Issue by excitoon** [bazelbuild/bazel#5419] opened 2018-06-17 10:01 UTC
### Description of the problem / feature request:

Basically it is good that Bazel forbids duplicate labels. But it should not make false-positives.
For example:
```
cc_binary(
    name = "hello",
    srcs = select({ "//conditions:default" : [], "//:x86_32_windows" : ["sources/hello.cpp"] })
        + [ "sources/common.cpp" ]
        + select({ "//conditions:default" : [], "//:x64_windows" : ["sources/hello.cpp"] })
)
```

This target looks good, but in reality it won't compile:
```
ERROR: C:/users/chebotarev_v/documents/src/bazel-issues/seemingly-duplicate-labels/BUILD:17:1: Label '//:sources/hello.cpp' is duplicated in the 'srcs' attribute of rule 'hello'
```

### Feature requests: what underlying problem are you trying to solve with this feature?

Label lists can be combined with (`+`) and come from different points of BUILD files, so these false-positives can be extremely hard to workaround in a project. I believe that should be fixed.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Please find an example here:
https://github.com/excitoon/bazel-issues/tree/master/seemingly-duplicate-labels

### What operating system are you running Bazel on?

Windows 10 x64

### What's the output of `bazel info release`?

```
Build label: 0.14.0
Build target: bazel-out/x64_windows-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Fri Jun 1 13:06:29 2018 (1527858389)
Build timestamp: 1527858389
Build timestamp as int: 1527858389
```

**Comment by cushon** [comment] 2018-06-17 22:28
Consider using `collections.uniq` from https://github.com/bazelbuild/bazel-skylib to deduplicate the `srcs` of that target, e.g.:

Add this to your `WORKSPACE`:

```
git_repository(
    name = "bazel_skylib",
    remote = "https://github.com/bazelbuild/bazel-skylib.git",
    tag = "0.1.0",  # change this to use a different release
)
```

And then use:

```
load("@bazel_skylib//:lib.bzl", "collections")

cc_binary(
    name = "hello",
    srcs = collections.uniq(select({ "//conditions:default" : [], "//:x86_32_windows" : ["sources/hello.cpp"] })
        + [ "sources/common.cpp" ]
        + select({ "//conditions:default" : [], "//:x64_windows" : ["sources/hello.cpp"] }))
)
```

**Comment by rongjiecomputer** [comment] 2018-06-19 02:43
Another solution is to just use `@bazel_tools//platforms:windows` instead of `cpu`.

```
config_setting(
    name = "windows",
    constraint_values = [
        "@bazel_tools//platforms:windows",
    ],
)

cc_binary(
    name = "hello",
    srcs = select({ "//conditions:default" : [], "//:windows" : ["sources/hello.cpp"] })
        + [ "sources/common.cpp" ]
)
```

**Comment by excitoon** [comment] 2018-06-24 11:14
Hi @cushon . Thank you for your attempt. :) The idea is good, but selects are not iterable. :)
Theoretically, I could decompose selects into custom iterable objects in Skylark and then compose it back after `collection.uniq`, like this (actually, we already use this approach for `pkg_tar`, which does not allow to have multiple copies of the same targets):
```
cc_binary(
    name = "hello",
    srcs = make_me_a_sandwich( # `select` shall happen here
        some_uniq(
            custom_concat(
                custom_select({ "//conditions:default" : [], "//:x86_32_windows" : ["sources/hello.cpp"] }),
                [ "sources/common.cpp" ],
                custom_select({ "//conditions:default" : [], "//:x64_windows" : ["sources/hello.cpp"] })
            )
        )
    )
)
```

But that decreases readability a lot and I guess involves some inefficiency. By the way, from your perspective, can it significantly slow down analysis time?

**Comment by gregestren** [comment] 2018-06-25 22:09
FYI see https://github.com/bazelbuild/bazel/commit/497ef110c344b2a309210339f125916f355530f9 for explanation of the current semantics.

What exactly makes this a false positive? Unless we dig deeper into what `//:x86_32_windows` and `//:x64_windows` mean, there's a real possibility of the label being duplicated. We don't really know for sure until analysis is happening and we know precisely which `config_settings` do and don't match.

**Comment by gregestren** [comment] 2020-05-11 21:02
I'm going to close the issue due to age, complexity of addressing the request, level of impact, current error messaging, and ability for workarounds.

It's a fair request. But trying to statically determine where duplication may or may not happen really can get technically messy, easily.

If we wanted to handle  `"//conditions:default"` explicitly, that should be easier.  But is that useful for simple reproductions or for real practical builds?

**Closed by gregestren** 2020-05-11 21:02 UTC
Labels: P3, team-Configurability, type: feature request
