### ISSUE TITLE
Ran out of Inodes

### ISSUE THREAD

**Issue by abergmeier-dsfishlabs** [bazelbuild/bazel#2951] opened 2017-05-05 12:04 UTC
### Description of the problem / feature request / question:

Since we have a lot of small files in Bazel we today ran out of Inodes on a machine (1TB partition). With Bazel forcing to write files to disks IMO this is bound to happen on big projects.
Maybe discuss here what we can do against that.

### Environment info
* Operating System: Ubuntu 16.04
* Bazel version (output of `bazel info release`): 0.4.5

**Comment by abergmeier-dsfishlabs** [comment] 2017-05-05 12:08
One measure could be to use `--experimental_sandbox_base=/run/shm` from 0.5 onwards to reduce inodes used by tests!? CC @philwo

**Comment by abergmeier-dsfishlabs** [comment] 2017-05-08 07:37
So the servers we switched to `XFS` (online increase of inodes). New desktops probably will be installed with `BTRFS` (no inode limit to begin with). Perhaps it would be good to point output_root to a `Ext`* partition?

**Comment by philwo** [comment] 2017-05-08 08:56
> With Bazel forcing to write files to disks IMO this is bound to happen on big projects.
Sorry, I don't really understand - what do you mean with "forcing to write files to disks"?

Generally speaking:
I can totally understand that this must be annoying when you hit the issue with your project. :( Yeah, Bazel creates a lot of symlinks that each take an inode for its sandboxing. But OTOH, on my desktop, which I think is a pretty standard Ubuntu setup, the 200GB big ext4 partition where my $HOME is, has 1.2 million free inodes (of 1.3 million total inodes). I can't see how this can become a problem even with big projects. If Bazel regularly has ~1 million temporary symlinks in flight, the performance must be absolutely horrible, no matter which filesystem you use? Using --experimental_sandbox_base=/run/shm should improve performance a lot then. Would be cool if you could give it a try :)

Also, yes, we can definitely add a warning to the docs. Maybe we could even make it a "best practice" to put Bazel's output base on a separate (SSD) partition to improve performance.

@AustinSchuh I think Austin has some experience with using XFS as the filesystem for desktops. How is your recent experience with it? I remember we had some performance problems with XFS in the past, too.

**Comment by abergmeier-dsfishlabs** [comment] 2017-05-08 09:14
> Sorry, I don't really understand - what do you mean with "forcing to write files to disks"?

I mean there is no way of passing information along the graph (using Skylark) aside from files.

> I can totally understand that this must be annoying when you hit the issue with your project

Well we had worse. Actually we were really lucky that it happened on Friday so we could build the whole weekend to get to incremental builds on Monday, again.

> I can't see how this can become a problem even with big projects

I am not entirely sure how we got there either. Almost all inodes are in Bazel, though.
The commit that triggered the problem, did add 400k (sandboxed) tests to the repo (don't judge). My current theory is that somehow the directories and symlinks then took all remaining inodes!?

Sadly we did not track inodes in our monitoring, so we will never know for sure.

> Using --experimental_sandbox_base=/run/shm should improve performance a lot then. Would be cool if you could give it a try

Once 0.5 is out we will :)

> How is your recent experience with it?

We (as devs here) have no experience with XFS. Our devops like that, so that is the reason we switched servers to XFS. We do have experience with BTRFS and it works quite fine.

> I remember we had some performance problems with XFS in the past, too.

Would be good to know. So far it seems a bit slower but not catastrophic.

**Comment by AustinSchuh** [comment] 2017-05-24 20:58
(Sorry for the slow response.  I've been sick and super busy)

@abergmeier-dsfishlabs I've been running XFS for a decade.  A year ago, I noticed that symlinks were slow on XFS.  I've since traced this down on my setup to a couple issues.  The first issue was that XFS was configured with 512 byte blocks instead of the native 4k blocks that the drive exposes.  The second issue seems to be that the SSD that I have quickly slows down under sustained heavy writes.  (I'm running a Samsung 950 Pro NVME drive).  I'd see good peak write speeds (3k iops), but sustained writes would slow down to 300 iops, 30 MB/s.

That can be measured using ```iostat -dx 1```.  On my system, I'd see it as high numbers in avgqu-sz, and then await being large.  (ie, the drive was queueing up massive numbers of iops, and then they'd stall in the pipeline).

I tried EXT4 and XFS with the offending drive, and my experience was that when the drive started to queue requests, XFS did better at becoming responsive sooner after a build.

If you want to try --experimental_sandbox_base in a test before 0.5.0 comes out, cd ~/.cache/bazel/_bazel_$(whoami)/md5sum/.  Then, replace bazel-sandbox with a symlink to /run/shm/, or a folder inside /run/shm/.

@philwo I've been slowly learning more about my performance problems, and have replaced the drive with an intel datacenter NVME SSD.  Your --experimental_sandbox_base flag still seems to help me a lot.  If you want the previous hardware which was giving me issues to help reproduce issues, give me a holler.

Without the flag while running a rule with ~2000 dependency files needed in the sandbox:

Device:         rrqm/s   wrqm/s     r/s     w/s    rkB/s    wkB/s avgrq-sz avgqu-sz   await r_await w_await  svctm  %util
nvme0n1           0.00     0.00    0.00 8222.00     0.00 166964.00    40.61     0.20    0.02    0.00    0.02   0.01  12.00

It then took 3m28.553s to build the target.

With the flag (peak and typical iostat lines during the build):
Device:         rrqm/s   wrqm/s     r/s     w/s    rkB/s    wkB/s avgrq-sz avgqu-sz   await r_await w_await  svctm  %util
nvme0n1           0.00     0.00    0.00    7.00     0.00   152.00    43.43     0.00    0.00    0.00    0.00   0.00   0.00

Device:         rrqm/s   wrqm/s     r/s     w/s    rkB/s    wkB/s avgrq-sz avgqu-sz   await r_await w_await  svctm  %util
nvme0n1           0.00     0.00    0.00 1156.00     0.00 88320.00   152.80   167.96   78.30    0.00   78.30   0.16  18.70

It then took 1m9.872s to build the target.

So, I'm seeing significantly reduced build times with the flag, even on a nice SSD.

**Comment by philwo** [comment] 2018-07-19 12:51
I'm closing this, as I'm not sure we can do anything to improve the situation at the moment.

For future readers: sandboxfs is a possible alternative that builds sandboxes in-memory via FUSE instead of creating symlinks. Also, moving the sandboxes to a tmpfs via `--experimental_sandbox_base` would help in this case, as we have discussed above.

**Closed by philwo** 2018-07-19 12:51 UTC
Labels: P2, type: documentation, under investigation

**Comment by guibou** [comment] 2021-01-26 14:26
We hit this issue recently on our codebase, exhausting the 25 millions inode available on the `ext4` disk. It may be a wrong usage of bazel in our case, but this is really surprising.

> Perhaps it would be good to warn about output_root to a Ext* partition?

Yes please. Some of the developers on this project hit the issue from time to time on their work machine, but we were not really able to understand it. Then it started failing sometimes in the CI, then more often up to this week when the CI is not able to succeed at all.

And unfortunately, the error is not obvious (at least on linux) if you are not fully aware of the inode limitation. I was suprised that the disk was "full" when it was only used at 20% of its capacity.

**Comment by fwingerter-Ocient** [comment] 2021-01-26 20:16
We also ran into this recently. Ideally bazel-buildfarm would treat maximum hardlink count as a basic attribute of the filesystem and create an additional inode (with its own identical copy of data) when it hits that limit.

There's a FIXME to this effect [here](https://github.com/bazelbuild/bazel-buildfarm/blob/ae7a2006ceb0ab7abaf3e5a14999712d708a7de1/src/main/java/build/buildfarm/cas/cfc/CASFileCache.java#L2003).

**Comment by bcarnes** [comment] 2021-05-03 17:35
For those who get themselves past the **_number_** of inodes...

Storing the bazel cache on an XFS vs ext4 filesystem highlights another issue at play...

The bulk of bazel's symlinks do not fit within the "symlink-inline-in-inode" limit of ~60 bytes on ext4.  So on ext4, each symlink uses the inode + a usually 4k block.  So with naive calculations, you'll run out of space even after you bump the number of inodes, on ext4.

XFS is more aggressive about placing large symlink targets inline into the inode.  We found XFS started becoming necessary for our very large projects.

https://ext4.wiki.kernel.org/index.php/Ext4_Disk_Layout#Symbolic_Links

**Comment by guibou** [comment] 2021-09-30 18:20
I hit the problem today on another codebase. We observed that bazel build was using close to 100% CPU time just for filesystem operations (on ext4 or btrfs). After creating 24 millons files, we totally saturated the disks (by reaching the number of inodes)

**Comment by AustinSchuh** [comment] 2021-09-30 18:59
@guibou , Have you tried `--experimental_sandbox_base=/dev/shm` ?  I've been running it for years now.  It makes a huge difference for my builds.

**Comment by guibou** [comment] 2021-10-01 18:48
> @guibou , Have you tried `--experimental_sandbox_base=/dev/shm` ? I've been running it for years now. It makes a huge difference for my builds.

That's an interesting proposition. That's not an option for us right now unfortunately. We are running multiples CI pipelines on the same strong machines, so the RAM is already under pressure due to the different build process, if you add (minimum) 20 GiB of data PER CI pipeline, there won't be enough RAM.

However, moving to smaller cloud instances with one CI pipeline per instance may be a solution.

/cc @teto you may be interested.

**Comment by AustinSchuh** [comment] 2021-10-02 02:31
To be clear, the sandbox base is mostly symlinks.  They are tiny in terms of RAM usage.  The only thing that takes up real space is output_base.

**Comment by cameron-martin** [comment] 2023-04-24 13:49
When using remote execution, the runfiles directories for binaries and tests are still created in `$(bazel info output_base)/execroot` on the host, regardless of the value of `--sandbox_base`. This is causing us to exhaust the number of inodes on the host. Is there any way to avoid this?
