### ISSUE TITLE
Bazel misplaces -fno-pie

### ISSUE THREAD

**Issue by bimargulies-google** [bazelbuild/bazel#10918] opened 2020-03-06 18:24 UTC
See 

https://github.com/bimargulies-google/bazel-no-pie-bug

Using

```
Build label: 2.0.0- (@non-git)
Build target: bazel-out/k8-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Mon Jan 13 16:25:21 2020 (1578932721)
Build timestamp: 1578932721
Build timestamp as int: 1578932721

```
on Alpine linux, I try to build a no-pie executable with:

```
bazel build --copt="-fno-pie" --linkopt="-fno-pie" hello_world
```
My .o file is still full of PIE:

```
OR: /BUILD:1:1: Linking of rule '//:hello_world' failed (Exit 1) gcc failed: error executing command /usr/bin/gcc @bazel-out/k8-fastbuild/bin/hello_world-2.params

Use --sandbox_debug to see verbose messages from the sandbox
/usr/bin/ld: bazel-out/k8-fastbuild/bin/_objs/hello_world/hello_world.pic.o: relocation R_X86_64_32 against `.rodata' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: final link failed: nonrepresentable section on output
```

**Comment by benjaminp** [comment] 2020-03-06 20:43
I think you probably want to pass `-no-pie` rather than `-fno-pie`. (Note also in fastbuild mode, Bazel will be compiling with `-fPIC` by default, too.)

**Comment by bimargulies-google** [comment] 2020-03-06 20:50
Thank You! That did it!

**Comment by tetromino** [comment] 2020-03-06 21:28
Also consider using `--features="-pic" --linkopt="-no-pie"` instead of setting `--copt`.

(Probably we should document this better somewhere.)

**Comment by benjaminp** [comment] 2020-03-06 21:45
Modern Linux distributions are found of distributing GCC compiled with `--enable-default-pie`, so you have to explicitly pass a "no" flag to compilation to obtain only static relocations.

**Comment by bimargulies-google** [comment] 2020-03-06 22:24
This worked for my simple 'hello_world' example, but does not work for the
bigger case with substantial dependencies like grpc.

There I am up to my ears in
credentials.cc:(.text._ZL27do_control_plane_creds_initv+0x20): undefined
reference to `operator new(unsigned long)'
.

**Comment by bimargulies-google** [comment] 2020-03-07 19:34
If you check out the failure branch in my repo, you will see that it now shows missing symbol errors.

```
bazel build  --linkopt="-no-pie" --linkopt="-static" --features="-pic" hello_world
```

I can compile this trivial program with 

```
g++ -no-pie -static -o hello_world hello_world.cc
```

and get a static executable, but bazel is not succeeding.

**Comment by benjaminp** [comment] 2020-03-08 00:32
Fully static binaries should use `features = ['fully_static_link']`.

**Comment by bimargulies-google** [comment] 2020-03-08 01:01
Adding the features = [ ... ] to the cc_binary in the BUILD file has no
effect at all. I get exactly the same undefined symbols.

**Comment by bimargulies-google** [comment] 2020-03-08 01:09
The reason seems clear... the library is included _before_ the .o, instead of after. Can I take over control of the toolchain and fix this for myself?


```
bash-5.0# cat bazel-out/k8-fastbuild/bin/hello_world-2.params
-o
bazel-out/k8-fastbuild/bin/hello_world
-Wl,-S
-Wl,-no-as-needed
-Wl,-z,relro,-z,now
-B/usr/bin
-pass-exit-codes
-lstdc++
-lm
bazel-out/k8-fastbuild/bin/_objs/hello_world/hello_world.pic.o
-static
```

**Comment by bimargulies-google** [comment] 2020-03-14 03:02
Why not a bug?

**Comment by oquenchil** [comment] 2020-03-17 14:55
Hello,

the first issue described here wasn't a bug as far as I can tell. You later bumped into a different issue which is indeed a bug. I think that might be fixed with the flag --incompatible_linkopts_to_linklibs.

I have tried to verify myself by using your docker image but I wasn't able to build bazel from head due to alpine linux not shipping with glibc which is needed for ijar. Alpine linux is not officially supported but I think that flag will fix your problem. So if you are able to build bazel from head, please try that flag and let me know if it works.

Also if you do manage to build bazel from head, I would appreciate it if you give me the steps in case I need to reproduce anything else.

**Comment by bimargulies-google** [comment] 2020-03-17 15:13
I didn't build bazel from head, I used the APK image from
https://pkgs.alpinelinux.org/package/edge/testing/x86_64/bazel. I have not
investigated how Oleg builds.

I can repro the original problem on a rather ordinary debian ...

and then I'll try your option. ...

Oh, your option isn't 2.2.0?

I'll report back when I figure out how to try it on a head build, and I'll
update the git repo to have a Dockerfile for something supported.

**Comment by oquenchil** [comment] 2020-03-17 15:19
Yes, I figured it's the same issue the flag fixes. However, the flag isn't in release Bazel, I tried to build it in your docker container to be able to confirm that everything builds without any other issues but I didn't manage. If you can use Debian, then definitely do test there as it will be easier.

**Comment by bimargulies-google** [comment] 2020-03-17 15:32
I have added Dockerfile.debian to the failure branch of the repo.

Now I'll try it with your option.

**Comment by bimargulies-google** [comment] 2020-03-17 15:33
But I'd need to run an up-to-date build of bazel. Where do I get one?

(In other words, you now have a  repro on debian, and I could try out your
fix there, or I could leave it to you, and concentrate on how I'm going to
get a working newer version on alpine).

**Comment by oquenchil** [comment] 2020-03-17 15:52
I confirmed that the flag fixes your problem.

To build bazel from head, git clone the repository and using the installed bazel do `bazel build //src:bazel`

**Comment by bimargulies-google** [comment] 2020-03-17 15:57
Thank you for all the help. Can you point me to an explanation of repair?
I'm very curious; to me, it just seems like the link command is
out-of-order, the name of the option implies that something more
complicated is going on.

**Comment by oquenchil** [comment] 2020-03-17 16:25
See https://github.com/bazelbuild/bazel/commit/906f5f1c233ca18c67a9cedd2c7182f33b88c44b.

Essentially, the Bazel repository rule that wrote what the toolchain looks like by using a template had two template variable: BAZEL_LINKOPTS and BAZEL_LINKLIBS.

Since the very beginning, libaries added by the toolchain like -lstdc++ were in BAZEL_LINKOPTS, which was wrong. However, this bug didn't show its head until I cleaned up a different part of the code where we manually modified the command line.

BAZEL_LINKOPTS appear before the libraries you as the user want to link, whereas BAZEL_LINKLIBS appear after. The fix is then to put -stdc++ in BAZEL_LINKLIBS which is where it should have been from the very beginning. However, since that is an incompatible change it has to be behind a flag.

**Comment by bimargulies-google** [comment] 2020-03-17 16:29
Given that full_static_link is nonfunctional with the 'traditional'
behavior, could it be legit to also trigger the fixed behavior on that?

**Comment by oquenchil** [comment] 2020-03-17 17:07
It would still be a breaking change because people may override themselves BAZEL_LINKLIBS and BAZEL_LINKOPTS.

**Comment by bimargulies-google** [comment] 2020-03-17 17:09
OK.

**Closed** 2020-11-19 16:02 UTC
Labels: team-Rules-CPP, type: support / not a bug (process)
