### ISSUE TITLE
Bazels untar looses sparse file information

### ISSUE THREAD

**Issue by rmohr** [bazelbuild/bazel#13501] opened 2021-05-21 09:18 UTC
> ATTENTION! Please read and follow:
> - if this is a _question_ about how to build / test / query / deploy using Bazel, or a _discussion starter_, send it to bazel-discuss@googlegroups.com
> - if this is a _bug_ or _feature request_, fill the form below as best as you can.

### Description of the problem / feature request:

When using `http_archive` bazel extracts the archive but does not check if files are sparse or not. As a consequence, it does neither expand the sparse file (in case the target filesystem does not supports parse files), nor does it keep the sparse information.

The result is a broken file.

### Feature requests: what underlying problem are you trying to solve with this feature?

I think the sparse-file info is lost her: https://github.com/bazelbuild/bazel/blob/master/src/main/java/com/google/devtools/build/lib/bazel/repository/CompressedTarFunction.java#L104.

It would be great if bazel could keep files sparse if possible or properly de-sparsifies it. Right now the file is just broken.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Take this archive, which contains a root filesystem of a VM in a sparse fashion:

```
http_archive(
    name = "libguestfs-appliance",
    sha256 = "a0c72e2ce85928270e39bbc6fb67df17887ad51c5e7794cac9c147fa247443aa",
    urls = [
        "https://storage.googleapis.com/kubevirt-prow/devel/release/kubevirt/libguestfs-appliance/appliance-1.44.1-linux-5.11.20-200-fedora33.tar.xz",
    ],
    build_file_content = """
filegroup(
    visibility = ["//visibility:public"],
    name = "appliance",
    srcs = glob(["**"]),
)
    """,
)
```

Create a fresh tar out of it:

```
pkg_tar(
    name = "appliance",
    srcs = ["@libguestfs-appliance//:appliance"],
    package_dir = "/var/lib/appliance/",
)
```

Afterwards inspect the extracted archive:

```
$ tar --list -v -f ./k8-fastbuild/bin/appliance.tar
[...]
-r-xr-xr-x 0/0       267550720 2000-01-01 01:00 ./var/lib/appliance/root
```

and compare it with the original:

```
$ tar --list -v -f appliance-1.44.1-linux-5.11.20-200-fedora33.tar
[...]
-rw-r--r-- root/root 4294967296 2021-05-17 12:07 appliance/root
[...]
```

One can see that the the file got cropped to the actual content (`267550720`) from the theoretical size of `4294967296`.

Booting this image clearly shows the symptom of the missing de-sparsificatoin:

```
supermin: creating /dev/root as block special 8:16
supermin: mounting new root on /root
[    2.773580] EXT4-fs (sdb): mounting ext2 file system using the ext4 subsystem
[    2.775747] EXT4-fs (sdb): bad geometry: block count 1048576 exceeds size of device (65320 blocks)
mount: /root: Invalid argument
[    2.777438] Kernel panic - no
```

### What operating system are you running Bazel on?

Linux

### What's the output of `bazel info release`?

```
$ bazel info release
release 3.7.2
```

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

> Replace this line with your answer.

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

> Replace this line with your answer.

###  Have you found anything relevant by searching the web?

I think here the info gets lost: https://github.com/bazelbuild/bazel/blob/master/src/main/java/com/google/devtools/build/lib/bazel/repository/CompressedTarFunction.java#L104.

### Any other information, logs, or outputs that you want to share?

> Replace these lines with your answer.
>
> If the files are large, upload as attachment or provide link.

**Comment by rmohr** [comment] 2023-06-27 08:51
@bazelbuild/triage I guess it would make in general make sense to not silently break tar archives which contain sparse files. Do you think it is something which could be fixed?

**Comment by Wyverald** [comment] 2024-02-20 23:30
dupe of https://github.com/bazelbuild/bazel/issues/20090

**Closed by Wyverald** 2024-02-20 23:30 UTC
Labels: type: bug, P3, team-ExternalDeps, help wanted
