### ISSUE TITLE
xx_test.args: argument with space is split up

### ISSUE THREAD

**Issue by laszlocsomor** [bazelbuild/bazel#6275] opened 2018-10-01 08:13 UTC
### Description of the problem / feature request:

If a test arguments in `*_test.args` contains a space, Bazel splits it up before passing it to the test, but doesn't do the same for args from `--test_arg`

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

`BUILD` file:
```
cc_test(
    name = "x",
    srcs = ["x.cc"],
    args = [
        "foo",
        "a b",
        "bar",
    ],
)
```

`x.cc` file:
```
#include <stdio.h>

int main(int argc, char** argv) {
  printf("TEST: argc=%d\n", argc);
  for (int i = 0; i < argc; ++i) {
    printf("TEST: argv[%d]=(%s)\n", i, argv[i]);
  }
  return 1;  // make sure the test fails, so --test_output=errors prints the output
}
```

Repro:
```
  $ bazel test //:x -s --test_output=errors --test_arg="baz" --test_arg="c d" --test_arg="qux"
(...)
  external/bazel_tools/tools/test/test-setup.sh ./x foo a b bar baz 'c d' qux)
FAIL: //:x (see (...)/testlogs/x/test.log)
INFO: From Testing //:x:
==================== Test output for //:x:
TEST: argc=8
TEST: argv[0]=((...)/bin/x.runfiles/__main__/x)
TEST: argv[1]=(foo)
TEST: argv[2]=(a)
TEST: argv[3]=(b)
TEST: argv[4]=(bar)
TEST: argv[5]=(baz)
TEST: argv[6]=(c d)
TEST: argv[7]=(qux)
```

### What operating system are you running Bazel on?

Linux

### What's the output of `bazel info release`?

```
  $ bazel info release
release 0.17.2
```

###  Have you found anything relevant by searching the web?

See also https://github.com/bazelbuild/bazel/issues/6274

**Comment by jin** [comment] 2018-10-01 16:09
@laszlocsomor assigning this to team-Windows, feel free to reassign if it's not right. thanks!

**Comment by jmmv** [comment] 2020-05-12 14:01
Same root cause as #6274, which I'm fixing to better highlight all problems.

**Closed by jmmv** 2020-05-12 14:01 UTC
Labels: P2, category: misc > testing, team-Local-Exec, type: bug
