### ISSUE TITLE
3.1.0rc1 unexpectedly calls repository rules with generator_name, generator_function arguments

### ISSUE THREAD

**Issue by dws-uber** [bazelbuild/bazel#11116] opened 2020-04-11 05:21 UTC
### Description of the problem / feature request:

In trying out bazel 3.1.0rc1, I noticed voluminous DEBUG output of the form

```
DEBUG: Rule '<rulename>' indicated that a canonical reproducible form can be obtained by dropping arguments ["generator_name", "generator_function"]
DEBUG: Repository <rulename> instantiated at:
  no stack (--record_rule_instantiation_callstack not enabled)
Repository rule <name> defined at:
  <path-to-bzl>:237:14: in <toplevel>
```

The repo rule in question returns a dictionary and has done so for some time.  It uses `update_attrs` from `@bazel_tools//tools/build_defs/repo:utils.bzl` to construct its return value.  What's new is that this rule is getting called with `generator_name` and `generator_function`. These appear to be coming from bazel and not from our code.  I perused the differences in the outputs of `./bazel help build --long` between bazel 3.0.0 and bazel 3.1.0rc1 and did not see anything there that pertained to this new behavior.

### Feature requests: what underlying problem are you trying to solve with this feature?

Point out the change in default behavior in case it was unintentional.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Presumably, define a repo with a rule that returns a dict, and then try to build or query.

### What operating system are you running Bazel on?

Ubuntu 18.04

### What's the output of `bazel info release`?

release 3.1.0rc1

@laurentlb

**Comment by dws-uber** [comment] 2020-04-11 05:56
@werkt

**Comment by meisterT** [comment] 2020-04-11 06:50
This is a duplicate of #11040.

**Closed** 2020-04-11 06:50 UTC
