### ISSUE TITLE
WindowsFileSystem#determineUnixRoot has a hardcoded timeout of 3 seconds, which is problematic for our unit tests

### ISSUE THREAD

**Issue by haxorz** [bazelbuild/bazel#2983] opened 2017-05-10 14:44 UTC
https://github.com/bazelbuild/bazel/blob/b13457b1434d64ab187fb511e73f01d1f2321c1e/src/main/java/com/google/devtools/build/lib/windows/WindowsFileSystem.java#L506-L507

note that this is a timeout for termination of a subprocess.

we're getting flaky test failures with stack traces like

java.lang.ExceptionInInitializerError
	at com.google.devtools.build.lib.runtime.BlazeRuntime.fileSystemImplementation(BlazeRuntime.java:825)
	at com.google.devtools.build.lib.runtime.BlazeRuntime.newRuntime(BlazeRuntime.java:971)
	at com.google.devtools.build.lib.runtime.BlazeRuntime.batchMain(BlazeRuntime.java:753)
	at com.google.devtools.build.lib.runtime.BlazeRuntime.main(BlazeRuntime.java:561)
	at com.google.devtools.build.lib.bazel.BazelMain.main(BazelMain.java:58)
Caused by: java.lang.IllegalThreadStateException: process has not exited
	at java.lang.ProcessImpl.exitValue(ProcessImpl.java:443)
	at com.google.devtools.build.lib.windows.WindowsFileSystem.determineUnixRoot(WindowsFileSystem.java:509)
	at com.google.devtools.build.lib.windows.WindowsFileSystem.<clinit>(WindowsFileSystem.java:324)
	... 5 more

take a look at https://github.com/bazelbuild/bazel/blob/5abb90d2c0cb5909f78d73adbe071e5001801823/src/test/java/com/google/devtools/build/lib/testutil/TestUtils.java#L136-L151

**Comment by laszlocsomor** [comment] 2017-05-10 14:47
Thanks! Solution is to define the msys root as a JVM variable, e.g.: https://github.com/bazelbuild/bazel/blob/65b06129504da8b4838a3d04f1cdc12df34a3716/src/test/java/com/google/devtools/build/lib/BUILD#L191

**Comment by haxorz** [comment] 2017-05-10 14:52
the test that failed for me was https://github.com/bazelbuild/bazel/blob/28c9617d53bf58dcba9572bcfdc165c62421d983/src/test/shell/bazel/bazel_windows_example_test.sh

if you're sure that the lack of bazel.windows_unix_root jvm system property is the problem, then that means my diagnosis was wrong (i just jumped at the sight of a hardcoded short timeout). but then my next question would be "how does this test ever currently pass???"

**Comment by laszlocsomor** [comment] 2017-05-10 14:58
perhaps https://github.com/bazelbuild/bazel/blob/28c9617d53bf58dcba9572bcfdc165c62421d983/src/main/java/com/google/devtools/build/lib/windows/WindowsFileSystem.java#L507 always finished within 3 seconds until now?

**Comment by laszlocsomor** [comment] 2017-05-10 15:00
i should remove that logic [1] anyway (as well as the System.getenv call in line 501), and use the `BAZEL_SH`  value from the clientenv

[1] https://github.com/bazelbuild/bazel/blob/28c9617d53bf58dcba9572bcfdc165c62421d983/src/main/java/com/google/devtools/build/lib/windows/WindowsFileSystem.java#L503-L522

**Comment by adfernandes** [comment] 2017-06-08 22:44
For me, on Windows 7 (I know, I know...), the adding `bazel.windows_unix_root` as per [this patch](https://github.com/bazelbuild/bazel/commit/686dd375601aa0633d882664fc1542d0a2832352) did nothing . And yes, I was rebuilding from 0.5.1.

The good news is that changing the timeout to 21 seconds [in WindowsFileSystem.java](https://github.com/bazelbuild/bazel/blob/28c9617d53bf58dcba9572bcfdc165c62421d983/src/main/java/com/google/devtools/build/lib/windows/WindowsFileSystem.java#L507) **did** fix the problem.

I have a relatively speedy laptop at work for development, but... there is so much Windows-anti-malware-stupidity running on the system that spawning out a process takes _waaaaaay_ longer than three seconds. Usually it can work in under 10. Usually. 

Sigh.

**Comment by adfernandes** [comment] 2017-06-09 20:57
Added PR #3160

**Comment by laszlocsomor** [comment] 2017-06-12 11:01
@adfernandes : 
> the adding bazel.windows_unix_root as per this patch did nothing

That's the bug, not the timeout.

**Comment by laszlocsomor** [comment] 2017-06-12 11:28
I managed to repro the bug: Bazel doesn't pick up the JVM flag from the bazelrc.

I modified Bazel to throw an IllegalStateException if the `bazel.windows_unix_root` JVM argument is not defined, instead of trying to run cygpath.

Without the JVM flag:
```
c:\work\bazel>"C:/tmp1/o6hbs7n0/execroot/bazel/bazel-out/msvc_x64-fastbuild/bin/src/bazel.exe" --nomaster_bazelrc --bazelrc=NUL --batch build //examples/cpp:hello-world --cpu=x64_windows_msys --host_cpu=x64_windows_msys
java.lang.ExceptionInInitializerError
        at com.google.devtools.build.lib.runtime.BlazeRuntime.fileSystemImplementation(BlazeRuntime.java:816)
        at com.google.devtools.build.lib.runtime.BlazeRuntime.newRuntime(BlazeRuntime.java:962)
        at com.google.devtools.build.lib.runtime.BlazeRuntime.batchMain(BlazeRuntime.java:744)
        at com.google.devtools.build.lib.runtime.BlazeRuntime.main(BlazeRuntime.java:552)
        at com.google.devtools.build.lib.bazel.BazelMain.main(BazelMain.java:58)
Caused by: java.lang.IllegalStateException: haha
        at com.google.devtools.build.lib.windows.WindowsFileSystem.determineUnixRoot(WindowsFileSystem.java:499)
        at com.google.devtools.build.lib.windows.WindowsFileSystem.<clinit>(WindowsFileSystem.java:324)
        ... 5 more
<unknown> crash in async thread:
java.lang.ExceptionInInitializerError
        at com.google.devtools.build.lib.runtime.BlazeRuntime.fileSystemImplementation(BlazeRuntime.java:816)
        at com.google.devtools.build.lib.runtime.BlazeRuntime.newRuntime(BlazeRuntime.java:962)
        at com.google.devtools.build.lib.runtime.BlazeRuntime.batchMain(BlazeRuntime.java:744)
        at com.google.devtools.build.lib.runtime.BlazeRuntime.main(BlazeRuntime.java:552)
        at com.google.devtools.build.lib.bazel.BazelMain.main(BazelMain.java:58)
Caused by: java.lang.IllegalStateException: haha
        at com.google.devtools.build.lib.windows.WindowsFileSystem.determineUnixRoot(WindowsFileSystem.java:499)
        at com.google.devtools.build.lib.windows.WindowsFileSystem.<clinit>(WindowsFileSystem.java:324)
        ... 5 more
```

JVM flag passed on the command line:
```
c:\work\bazel>"C:/tmp1/o6hbs7n0/execroot/bazel/bazel-out/msvc_x64-fastbuild/bin/src/bazel.exe" --nomaster_bazelrc --bazelrc=NUL --host_jvm_args=-Dbazel.windows_unix_root=c:\tools\msys64 --batch build //examples/cpp:hello-world --cpu=x64_windows_msys --host_cpu=x64_windows_msys
INFO: Found 1 target...
Target //examples/cpp:hello-world up-to-date:
  C:/tempdir/temp/_bazel_laszlocsomor/o6hbs7n0/execroot/io_bazel/bazel-out/msys_x64-fastbuild/bin/examples/cpp/hello-world.exe
INFO: Elapsed time: 2.376s, Critical Path: 0.66s
```

JVM flag in the bazelrc:
```
c:\work\bazel>echo "startup --host_jvm_args=-Dbazel.windows_unix_root=c:\tools\msys64" > my_bazelrc

c:\work\bazel>"C:/tmp1/o6hbs7n0/execroot/bazel/bazel-out/msvc_x64-fastbuild/bin/src/bazel.exe" --nomaster_bazelrc --bazelrc=my_bazelrc --batch build //examples/cpp:hello-world --cpu=x64_windows_msys --host_cpu=x64_windows_msys
java.lang.ExceptionInInitializerError
        at com.google.devtools.build.lib.runtime.BlazeRuntime.fileSystemImplementation(BlazeRuntime.java:816)
        at com.google.devtools.build.lib.runtime.BlazeRuntime.newRuntime(BlazeRuntime.java:962)
        at com.google.devtools.build.lib.runtime.BlazeRuntime.batchMain(BlazeRuntime.java:744)
        at com.google.devtools.build.lib.runtime.BlazeRuntime.main(BlazeRuntime.java:552)
        at com.google.devtools.build.lib.bazel.BazelMain.main(BazelMain.java:58)
Caused by: java.lang.IllegalStateException: haha
        at com.google.devtools.build.lib.windows.WindowsFileSystem.determineUnixRoot(WindowsFileSystem.java:499)
        at com.google.devtools.build.lib.windows.WindowsFileSystem.<clinit>(WindowsFileSystem.java:324)
        ... 5 more
<unknown> crash in async thread:
java.lang.ExceptionInInitializerError
        at com.google.devtools.build.lib.runtime.BlazeRuntime.fileSystemImplementation(BlazeRuntime.java:816)
        at com.google.devtools.build.lib.runtime.BlazeRuntime.newRuntime(BlazeRuntime.java:962)
        at com.google.devtools.build.lib.runtime.BlazeRuntime.batchMain(BlazeRuntime.java:744)
        at com.google.devtools.build.lib.runtime.BlazeRuntime.main(BlazeRuntime.java:552)
        at com.google.devtools.build.lib.bazel.BazelMain.main(BazelMain.java:58)
Caused by: java.lang.IllegalStateException: haha
        at com.google.devtools.build.lib.windows.WindowsFileSystem.determineUnixRoot(WindowsFileSystem.java:499)
        at com.google.devtools.build.lib.windows.WindowsFileSystem.<clinit>(WindowsFileSystem.java:324)
        ... 5 more
```

**Comment by laszlocsomor** [comment] 2017-06-12 13:32
@adfernandes : please see https://github.com/bazelbuild/bazel/issues/3170#issuecomment-307789964

**Comment by adfernandes** [comment] 2017-06-12 15:42
Hmm.

Actually, my instance of this bug is a little different.

I was building bazel from source, and nowhere in the docs (under either _using_ nor _installing_) does it say that on Windows the `bazelrc` file is required.

Thanks for changing the exception to "IllegalState", though. That's far less misleading than before.

But it still doesn't help someone trying to use or build bazel for the first time.

On my system, I tried **both** the prebuilt binary and building from source.

Reading the comments in this bug report, it wasn't (and still isn't) clear that a `bazelrc` is needed _even for bootstrap-building_ bazel.

In this case, the code fell back to `cygdrive` which _should have worked_ but didn't because my slow crapware-riddled corporate laptop cannot have the JVM launch an external process in less than three seconds.

So increasing the timeout **did** fix the bug... kinda'.

**Comment by laszlocsomor** [comment] 2017-06-12 16:20
> I was building bazel from source, and nowhere in the docs (under either using nor installing) does it say that on Windows the `bazelrc` file is required.

It isn't, only the `BAZEL_SH` envvar is required, but if you observe slow process spawning then yes, updating the bootstrap scripts and passing this `--host_jvm_args` is the workaround for you.

> Thanks for changing the exception to "IllegalState", though.

Uhm, I should've clarified that this was a local change :) Not yet merged. But I'm working on merging it!

> Reading the comments in this bug report, it wasn't (and still isn't) clear that a bazelrc is needed even for bootstrap-building bazel.

It's not. What makes you think it is?

**Closed** 2017-06-13 15:14 UTC
Labels: category: multi-platform > windows, P3, type: bug

**Comment by adfernandes** [comment] 2017-06-13 18:11
Hmm. Probably the difference between building from `0.5.1-dist` vs git `HEAD`.   :-)

On `0.5.1-dist` my `bazelrc` is ignored during bootstrap build (which is probably as designed), so `cygpath` is called and it times out. So that's definitely a bug and fixed by increasing the timeout.

On pre-built bazel `0.5.1`, having a `bazelrc` that sets
```
startup --host_jvm_args=-Dbazel.windows_unix_root=C:\\msys2
```
is fine.

Note that I have **always** had `BAZEL_SH` set correctly, and I do **not** have Msys2 installed at `c:\tools`.

So until the next `-dist` is rolled out I can't test the changes on `HEAD` :-(

**Comment by adfernandes** [comment] 2017-06-13 20:38
(Actually, a little side-note - it turns out that on my system, even 13 seconds is not enough to prevent a timeout... I had to set it to 21 seconds! And I've been building bazel _a lot_ from source today! Boy, I hope this problem is fixed upstream!) :)

**Comment by laszlocsomor** [comment] 2017-06-14 06:37
You could pass the --host_jvm_args flag even while bootstrapping like so:

```
$ export BAZEL_BOOTSTRAP_STARTUP_OPTIONS="-Dbazel.windows_unix_root=C:/msys2"
$ ./compile.sh
```

Ouch, that 21 second timeout sounds atrocious, I'm surprised you had the patience to try anything at all.

**Comment by laszlocsomor** [comment] 2017-06-14 06:40
And if that doesn't work for whatever reason, then please let me know, and also you could hardcode the path in [WindowsFileSystem.UNIX_ROOT](https://github.com/bazelbuild/bazel/blob/release-0.5.2/src/main/java/com/google/devtools/build/lib/windows/WindowsFileSystem.java#L323-L324) as:
```
private static final PathFragment UNIX_ROOT = PathFragment.create("c:/msys2");
```

**Comment by adfernandes** [comment] 2017-06-15 18:14
@laszlocsomor: Much appreciated, thanks!

I will **try** to get to testing it, but, unfortunately I've put a lot of time into this already. I've got enough battles to try and fight ("Why isn't maven good enough? I mean, it integrates so well with Spring!" 🤢 ) that I can only put so much effort into bazel. 😞 

But I will try!
