### ISSUE TITLE
Your build has triggered a programmatic error in the cc_shared_library rule

### ISSUE THREAD

**Issue by Ryang20718** [bazelbuild/bazel#24072] opened 2024-10-24 06:54 UTC
### Description of the bug:

cc_shared_library fails to build

### Which category does this issue belong to?

C++ Rules

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

`git clone https://github.com/Ryang20718/repro-cpp-linker`

set bazel version to 7.4.0 and `bazelisk build @gdal//:gdal`

### Which operating system are you running Bazel on?

ubuntu 20.04

### What is the output of `bazel info release`?

7.4.0

### If this is a regression, please try to identify the Bazel commit where the bug was introduced with bazelisk --bisect.

this first broke in 7.4.0 and 7.3.2 was working fine

**Comment by fmeum** [comment] 2024-10-24 13:06
Likely a duplicate of https://github.com/bazelbuild/bazel/issues/24063, which has a smaller reproducer.

**Comment by peakschris** [comment] 2024-10-24 17:35
I am also seeing this issue on a pure (I think) C++ build. 7.4.0rc2 is OK, 7.4.0 has the issue.

**Comment by fmeum** [comment] 2024-10-24 19:17
@peakschris If possible, could you share a reproducer? It's quite possible that this change just happened to unearth different underlying bugs.

**Comment by fmeum** [comment] 2024-10-24 19:23
This is an honest duplicate, the missing node is `@rust_darwin_aarch64__aarch64-apple-darwin__stable_tools//:rust_toolchain`.

@peakschris Please open a new issue if you have a reproducer without rules_rust.

**Closed by fmeum** 2024-10-24 19:23 UTC
Labels: type: bug, team-Rules-CPP, untriaged

**Comment by peakschris** [comment] 2024-10-24 19:43
We don't use rules_rust. We do have header_only cc_libraries as deps for cc_shared_library.  Hopefully the 7.4.0 change that you've reverted will fix things for us.  If not,  I'll work on a reproducer in the next couple of days.

**Comment by malkia** [comment] 2024-10-26 16:29
I also have one,

https://github.com/malkia/opentelemetry-cpp

bazel run --//:with_dll=true make_otel_sdk

but it's more complicated setup
