### ISSUE TITLE
Simple Java build failing that compiles with javac

### ISSUE THREAD

**Issue by spierce7** [bazelbuild/bazel#747] opened 2015-12-31 05:34 UTC
I'm evaluating the differences between buck (a bazel clone), and bazel for android and ios development. I have a simple test build working in buck using j2objc that I'm migrating to bazel. Something that is confusing me is that a simple java build that works with javac and buck is failing with bazel.

I'm using the bazel tutorial as a base. Inside the tutorial workspace, I've created a folder `rxjava`. Inside that folder are the rxjava sources (to eventually be compiled with the `j2objc_library` rule), and the BUILD file: [rxjava.zip](https://github.com/bazelbuild/bazel/files/75374/rxjava.zip)

Here are the contents of the BUILD file:
```python
java_library(
	name = 'rxjava',
	srcs = glob(['src-1.1.0/main/java/**/*.java']),
)
```

When I run `bazel build //rxjava:rxjava` here is the result:

```
$ bazel build //rxjava:rxjava
INFO: Found 1 target...
INFO: From Building rxjava/librxjava.jar (255 files):
rxjava/src-1.1.0/main/java/rx/Observable.java:1205: error: incompatible types: Observable<CAP#1> cannot be converted to Observable<T>
        return create(OnSubscribeToObservableFuture.toObservableFuture(future)).subscribeOn(scheduler);
                                                                                           ^
  where T is a type-variable:
    T extends Object declared in method <T>from(Future<? extends T>,Scheduler)
  where CAP#1 is a fresh type-variable:
    CAP#1 extends T from capture of ? extends T
rxjava/src-1.1.0/main/java/rx/observables/BlockingObservable.java:102: error: reference to subscribe is ambiguous
        Subscription subscription = o.subscribe(new Subscriber<T>() {
                                     ^
  both method subscribe(Observer<? super T>) in Observable and method subscribe(Subscriber<? super T>) in Observable match
  where T is a type-variable:
    T extends Object declared in class Observable
rxjava/src-1.1.0/main/java/rx/observables/BlockingObservable.java:433: error: reference to subscribe is ambiguous
        Subscription subscription = observable.subscribe(new Subscriber<T>() {
                                              ^
  both method subscribe(Observer<? super T>) in Observable and method subscribe(Subscriber<? super T>) in Observable match
  where T is a type-variable:
    T extends Object declared in class Observable
rxjava/src-1.1.0/main/java/rx/observables/BlockingObservable.java:470: error: reference to subscribe is ambiguous
        Subscription s = o.subscribe(new Subscriber<T>() {
                          ^
  both method subscribe(Observer<? super T>) in Observable and method subscribe(Subscriber<? super T>) in Observable match
  where T is a type-variable:
    T extends Object declared in class Observable
rxjava/src-1.1.0/main/java/rx/observables/BlockingObservable.java:507: error: reference to subscribe is ambiguous
        Subscription s = o.subscribe(new Subscriber<T>() {
                          ^
  both method subscribe(Observer<? super T>) in Observable and method subscribe(Subscriber<? super T>) in Observable match
  where T is a type-variable:
    T extends Object declared in class Observable
rxjava/src-1.1.0/main/java/rx/observables/BlockingObservable.java:595: error: reference to subscribe is ambiguous
        o.subscribe(s);
         ^
  both method subscribe(Observer<? super T>) in Observable and method subscribe(Subscriber<? super T>) in Observable match
  where T is a type-variable:
    T extends Object declared in class Observable
rxjava/src-1.1.0/main/java/rx/internal/operators/BlockingOperatorLatest.java:52: error: reference to subscribe is ambiguous
                source.materialize().subscribe(lio);
                                    ^
  both method subscribe(Observer<? super T>) in Observable and method subscribe(Subscriber<? super T>) in Observable match
  where T is a type-variable:
    T extends Object declared in class Observable
rxjava/src-1.1.0/main/java/rx/internal/operators/BlockingOperatorMostRecent.java:56: error: reference to subscribe is ambiguous
                source.subscribe(mostRecentObserver);
                      ^
  both method subscribe(Observer<? super T>) in Observable and method subscribe(Subscriber<? super T>) in Observable match
  where T is a type-variable:
    T extends Object declared in class Observable
rxjava/src-1.1.0/main/java/rx/internal/operators/BlockingOperatorNext.java:99: error: reference to subscribe is ambiguous
                    items.materialize().subscribe(observer);
                                       ^
  both method subscribe(Observer<? super T>) in Observable and method subscribe(Subscriber<? super T>) in Observable match
  where T is a type-variable:
    T extends Object declared in class Observable
rxjava/src-1.1.0/main/java/rx/internal/operators/BlockingOperatorToFuture.java:57: error: reference to subscribe is ambiguous
        final Subscription s = that.single().subscribe(new Subscriber<T>() {
                                            ^
  both method subscribe(Observer<? super T>) in Observable and method subscribe(Subscriber<? super T>) in Observable match
  where T is a type-variable:
    T extends Object declared in class Observable
rxjava/src-1.1.0/main/java/rx/internal/operators/BlockingOperatorToIterator.java:53: error: reference to subscribe is ambiguous
        source.materialize().subscribe(subscriber);
                            ^
  both method subscribe(Observer<? super T>) in Observable and method subscribe(Subscriber<? super T>) in Observable match
  where T is a type-variable:
    T extends Object declared in class Observable
rxjava/src-1.1.0/main/java/rx/internal/operators/OperatorMulticast.java:152: error: reference to subscribe is ambiguous
            source.subscribe(sub);
                  ^
  both method subscribe(Observer<? super T>) in Observable and method subscribe(Subscriber<? super T>) in Observable match
  where T is a type-variable:
    T extends Object declared in class Observable
rxjava/src-1.1.0/main/java/rx/observables/AsyncOnSubscribe.java:616: error: reference to subscribe is ambiguous
                .subscribe(s);
                ^
  both method subscribe(Observer<? super T>) in Observable and method subscribe(Subscriber<? super T>) in Observable match
  where T is a type-variable:
    T extends Object declared in class Observable
Note: rxjava/src-1.1.0/main/java/rx/observers/TestSubscriber.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
13 errors
BazelJavaBuilder threw exception: java compilation returned status ERROR
ERROR: /Users/spierce7/workspace/Personal/BazelTutorial/tutorial/rxjava/BUILD:1:1: Java compilation in rule '//rxjava:rxjava' failed: java failed: error executing command external/local-jdk/bin/java -Xbootclasspath/p:external/bazel_tools/third_party/java/jdk/langtools/javac.jar -client -jar external/bazel_tools/tools/jdk/JavaBuilder_deploy.jar ... (remaining 1 argument(s) skipped): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.
Target //rxjava:rxjava failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 2.613s, Critical Path: 2.45s.
```

The following javac command works fine: ```javac -sourcepath . -d out `find . -name '*.java'` ```

What is bazel doing differently? I must be configuring something incorrectly, but I'm not sure how.

**Comment by cushon** [comment] 2016-01-06 00:51
bazel is using the jdk9 javac, which has some backwards-incompatible changes to type inference: https://bugs.openjdk.java.net/browse/JDK-8075793?focusedCommentId=13865850

I see the same issue when compiling with gradle and jdk9-ea-b80.

One option is to add explicit type parameters to rxjava so it compiles against jdk9, e.g.:

```
--- a/src/main/java/rx/Observable.java
+++ b/src/main/java/rx/Observable.java
@@ -538,7 +538,7 @@ public class Observable<T> {
      */
     @SuppressWarnings("unchecked")
     public static final <T1, T2, R> Observable<R> combineLatest(Observable<? extends T1> o1, Observable<? extends T2> o2, Func2<? super T1, ? super T2, ? extends R> combineFunction) {
-        return combineLatest(Arrays.asList(o1, o2), Functions.fromFunc(combineFunction));
+        return Observable.<Object, R>combineLatest(Arrays.asList(o1, o2), Functions.fromFunc(combineFunction));
     }
```

**Comment by cushon** [comment] 2016-01-06 00:59
filed ReactiveX/RxJava#3603

**Comment by spierce7** [comment] 2016-01-06 03:24
@cushon Thanks for the response. Is there a way to tell bazel to use a javac from an older jdk?

**Comment by cushon** [comment] 2016-01-06 20:23
@spierce7 Not currently. We standardized on using a single recent version of javac because some plugins rely on internal javac APIs, and they would be hard to make portable.

**Comment by damienmg** [comment] 2016-02-15 20:14
@spierce7 you can use the jdk7 flavor that use a java8 compiler I think.

Closing issue as this is working as intended

**Closed by damienmg** 2016-02-15 20:14 UTC
Labels: Native rules (Java / C++ / Python)

**Comment by spierce7** [comment] 2016-02-16 04:30
@damienmg How would I use the jdk7 flavor?

**Comment by damienmg** [comment] 2016-02-16 09:08
You can download the release that have `-jdk7` in their name.
Building it is a bit trickier. The easiest way to do it is:
`bash -c 'export JAVA_VERSION=1.7; source scripts/ci/build.sh; export BAZEL_COMPILE_TARGET=compile; bazel_build output'`
