### ISSUE TITLE
Allow relative paths for local_repositorys

### ISSUE THREAD

**Issue by kchodorow** [bazelbuild/bazel#733] opened 2015-12-22 15:07 UTC
Right now, the path="..." attribute checks that the path was absolute.

**Comment by zombiezen** [comment] 2015-12-23 00:11
This may be a dupe of #269. I'm excited if this will be supported.

**Comment by saileshmittal** [comment] 2015-12-23 07:09
This change worked for me.
https://bazel-review.googlesource.com/#/c/2601/

Are there tests or examples that I can update?

**Closed** 2016-01-07 20:30 UTC
Labels: external repositories, feature request, P2
