### ISSUE TITLE
Possible regression between 6.4.0 and 7.x: `cc_library` does not propagate `linkopts` option

### ISSUE THREAD

**Issue by femshima** [bazelbuild/bazel#23053] opened 2024-07-21 07:02 UTC
### Description of the bug:

Hello. It seems that Bazel 7.x does not link library specified in `linkopts` of dependency, even though 6.4.0 do.

For example, the following code, which creates `libtest.so`, should link to `libuim.so` as specified in `uim` dependency. However, in 7.x, it does not link.
```bazel
# BUILD.bazel

cc_library(
    name = "uim",
    hdrs = glob([
        "usr/include/uim/**"
    ]),
    copts = [
        ""
    ],
    includes = [
        "usr/include/uim"
    ],
    linkopts = [
        "-luim",
        "-luim-scm"
    ],
)

cc_library(
    name = "test_lib",
    srcs = ["test.cc"],
    deps = [
        ":uim",
    ]
)

cc_shared_library(
    name = "test",
    roots = ["test_lib"],
)
```

I confirmed that by executing `ldd`, and also looking at `libtest.so-2.params` file. When built with 7.x, the `libtest.so-2.params` file does not include `-luim` or `-luim-scm` line.

Also, when I copy linkopts to `test_lib`, it works fine.
```diff
cc_library(
    name = "test_lib",
    srcs = ["test.cc"],
    deps = [
        ":uim",
-   ]
+   ],
+   linkopts = [
+       "-luim",
+       "-luim-scm"
+   ],
)
```

### Which category does this issue belong to?

C++ Rules

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

1. Create `WORKSPACE.bazel` and `MODULE.bazel`.
2. Create `BUILD.bazel` posted above.
3. Create empty `test.cc`.
4. Run `bazel build test --experimental_cc_shared_library` in either bazel 6.4.0 or 7.2.1.
5. Check if `src/bazel-bin/libtest.so-2.params` contains `-luim` or `-luim-scm`.

### Which operating system are you running Bazel on?

Linux

### What is the output of `bazel info release`?

release 7.2.1 (used bazelisk)

### If this is a regression, please try to identify the Bazel commit where the bug was introduced with bazelisk --bisect.

I tried to run bisect but failed, because 6.4.0 (good Bazel commit) is not an ancestor of 7.2.1 (bad Bazel commit), and their merge base commit fails to run.

**Comment by fmeum** [comment] 2024-08-05 13:33
@oquenchil Is it possible that `cc_shared_library` now drops targets that don't contribute anything linkable (except linkopts)?

**Comment by fmeum** [comment] 2024-08-05 13:33
@bazel-io flag

**Comment by oquenchil** [comment] 2024-08-05 14:24
Probably broken by https://github.com/bazelbuild/bazel/pull/20228 which fixed https://github.com/bazelbuild/bazel/issues/19920.

The fix for this one would probably be to simply take the linkopts from the `linker_input` containing no libraries then discard it, so that it doesn't throw errors about it not being exported.

**Comment by keith** [comment] 2024-08-05 17:09
https://github.com/bazelbuild/bazel/issues/21884

**Comment by iancha1992** [comment] 2024-08-05 18:02
@bazel-io fork 7.4.0

**Comment by comius** [comment] 2024-09-10 07:27
Duplicate of https://github.com/bazelbuild/bazel/issues/21884

**Closed by comius** 2024-09-10 07:27 UTC
Labels: type: bug, team-Rules-CPP, untriaged
