### ISSUE TITLE
cfg="host" build picks up target --crosstool_top when cross-compiling

### ISSUE THREAD

**Issue by rtsai** [bazelbuild/bazel#2548] opened 2017-02-18 22:55 UTC
Please provide the following information. The more we know about your system and use case, the more easily and likely we can help.

### Description of the problem / feature request / question:

The build host is Linux Ubuntu 16.04.2

We cross-compile to a target platform where -lsocket is required to link the application.

Our protobuf compiler plugin depends on a library that is also used on the target platform, where the library linkopts (filtered by select()) includes "-lsocket". The plugin is required to build protobuf generated C++ code to be compiled for the target.

However, compiling our plugin [for host] results in picking up the "-lsocket" anyway, which fails because Linux has no libsocket.so.

It seems like things being built for cfg="host" should not be using the target linkopts, etc. (I guess they should use //conditions:default?)

_If asking a question or requesting a feature, also tell us about the underlying problem you're trying to solve._

### Environment info
* Operating System:

* Bazel version (output of `bazel info release`):

* If `bazel info release` returns "development version" or "(@non-git)", please tell us what source tree you compiled Bazel from; git commit hash is appreciated (`git rev-parse HEAD`):

0.4.3

### Anything else, information or logs or outputs that would be helpful?
(If they are large, please upload as attachment or provide link).

**Comment by rtsai** [comment] 2017-05-05 15:01
Another data point is that the cfg="host" build seems to be picking up the target crosstool_top.

As an experiment (Ubuntu-16.04.2 LTS Linux, bazel-0.4.5, protobuf-v3.0.2):

1. Ran bazel build --crosstool_top=@bazel_tools//tools/cpp:toolchain //foo_proto (a cc_proto_library target that depends on a cfg="host" protoc). Everything works.

1. Copied @local_config_cc/{BUILD,CROSSTOOL} to a new //mytools/{BUILD,CROSSTOOL}, and just keep the "local" "k8" toolchain (remove armeabi-v7a, ios_x86_64, vc_14_0_x64, etc.).

1. Re-run bazel build --crosstool_top=//mytools:toolchain //foo_proto ; this should succeed because it's exactly the same

1. In //mytools:CROSSTOOL, remove "linker_flag -lstdc++"

1. Now things fail, because protoc depends on -lstdc++

Question: What exactly should cfg="host" mean w.r.t. crosstool_top?

- Should it mean @bazel_tools//tools/cpp:toolchain?
- Or should it just mean "bazel build"?

As another detail, our bazelrc is configured with "build --crosstool_top=//mytools:toolchain" because we need to tweak the out-of-the-box toolchain configuration.

**Comment by mhlopko** [comment] 2017-05-09 09:57
Hi Robert, I'm very sorry this was left unnoticed for so long. Are you setting --host_crosstool_top? Because if you don't then we use the value from --crosstool_top ([code](https://github.com/bazelbuild/bazel/blob/8bd4312fb8e738fe0cf7bd5edb5152db6325c6ad/src/main/java/com/google/devtools/build/lib/rules/cpp/CppOptions.java#L738)) Is it possible that this is the cause?

**Comment by rtsai** [comment] 2017-05-09 16:09
Yes, that was it. I don't know how I missed that in the documentation 🤦

**Comment by mhlopko** [comment] 2017-05-09 16:14
To be honest, our docs are far from perfect. Glad this got resolved. Cheers!

**Comment by rtsai** [comment] 2017-05-09 17:03
Actually, that helped, but didn't completely solve our problem, because the experiment described above is incomplete.

Rather than build a cc_proto_library, build a thing that requires a protoc plugin. We observe that we are unable to link the host plugin because of target linkopts leaking through.

After setting build --host_crosstool_top=@bazel_tools//tools/cpp:toolchain , and building a cc_binary for the target, we are still picking up target linkopts (the bazelrc doesn't set host_crosstool_top anywhere):

``
bazel build --config=target --host_crosstool_top=@bazel_tools//tools/cpp:toolchain //foo
...
/usr/bin/ld.gold: error: cannot find -lsocket
``

We have a rule that builds a protoc plugin for the host.

"bazel -s" shows that during link time, the correct host tool is being used (/usr/bin/gcc instead of the cross-compile linker). However, "-lsocket" is still showing up in bazel-out/host/bin/.../foo-2.params

I have done a "bazel clean" and the problem still persists.

**Comment by rtsai** [comment] 2017-05-10 16:30
Hi. The offending base dependency is libevent2 with linkopts:

```
cc_library(
  name = "event",
  srcs = ...
  linkopts = select({
    "//build/toolchains:qnx": ["-lsocket"],
    "//conditions:default": [],
  }),
  ...
)
```

The `config_settings` in `//build/toolchains:BUILD`:

```
config_setting(                                                                                                
    name = "qnx",                                                                                              
    values = {"define": "QNX=1"},                                                                              
    visibility = ["//visibility:public"],                                                                      
)                                                                                                              
                                                                                                               
config_setting(                                                                                                
    name = "qnx6",                                                                                             
    values = {"define": "QNX6=1"},                                                                             
    visibility = ["//visibility:public"],                                                                      
)                                                                                                              
                                                                                                               
config_setting(                                                                                                
    name = "qnx_x86",                                                                                          
    values = {                                                                                                 
        "cpu": "x86",                                                                                          
        "crosstool_top": "//build/toolchains/qnx:toolchain",                                                   
    },                                                                                                         
    visibility = ["//visibility:public"],                                                                      
)                                                                                                              
                                                                                                               
config_setting(                                                                                                
    name = "qnx_arm",                                                                                          
    values = {                                                                                                 
        "cpu": "arm",                                                                                          
        "crosstool_top": "//build/toolchains/qnx:toolchain",                                                   
    },                                                                                                         
    visibility = ["//visibility:public"],                                                                      
)                                                                                                              
                                                                                                               
config_setting(                                                                                                
    name = "qnx7",                                                                                             
    values = {"define": "QNX7=1"},                                                                             
    visibility = ["//visibility:public"],                                                                      
)                                                                                                              
                                                                                                               
config_setting(                                                                                                
    name = "qnx7_x86_64",                                                                                      
    values = {                                                                                                 
        "cpu": "x86_64",                                                                                       
        "crosstool_top": "//build/toolchains/qnx7:toolchain",                                                  
    },                                                                                                         
    visibility = ["//visibility:public"],                                                                      
)                                                                             
```

The bazelrc:

```
# Default build: Linux
build --crosstool_top=@bazel_tools//tools/cpp:toolchain

# qnx                                                                                                          
build:qnx --define QNX=1                                                                                       
build:qnx --dynamic_mode=off                                                                                   
build:qnx --host_crosstool_top=@bazel_tools//tools/cpp:toolchain                                               
    
# qnx6  
build:qnx6 --config=qnx
build:qnx6 --define QNX6=1                                                                                     
build:qnx6 --crosstool_top=//build/toolchains/qnx:toolchain                                                    

# qnx_x86
build:qnx_x86 --config=qnx6
build:qnx_x86 --cpu=x86

# qnx_arm
build:qnx_arm --config=qnx6
build:qnx_arm --cpu=arm

# qnx7
build:qnx7 --config=qnx
build:qnx7 --define QNX7=1
build:qnx7 --crosstool_top=//build/toolchains/qnx7:toolchain

# qnx7_x86_64
build:qnx7_x86_64 --config=qnx7
build:qnx7_x86_64 --cpu=x86_64
```

Finally, the offending command-line (when run on a Linux build host):

```
bazel build --config=qnx7_x86_64 //foo:cpp_plugin
ERROR: .../compiler/BUILD:10:1: Linking of rule '//foo:cpp_plugin' failed: Process exited with status 1 [sandboxed].
/usr/bin/ld.gold: error: cannot find -lsocket
```

where foo:cpp_plugin is a protoc plugin

So now that I'm looking more closely here, I realize that if I add a `"host_crosstool_top"` to `config_setting("qnx")`, then the cross-compile works as expected, which means I have an incorrect understanding of how `config_setting` works.

Shouldn't the `QNX=1` have been sufficient to match the `config_setting` for the `select`? Then the bazelrc would have provided the `host_crosstool_top` for the requested build ...

Thank you so much!

**Comment by rtsai** [comment] 2017-05-10 16:42
Any feedback is also appreciated; you can probably see what we're trying to do; maybe we're just doing something wrong.

The `define` configurations are intended to allow `select` to be written broadly (e.g., cover multiple targets), while the non-`define` configurations represent the "public" values that may be used with `bazel build --config`.

**Comment by rtsai** [comment] 2017-05-15 17:25
Ping. Are you able to comment on whether host_crosstool_top is expected to be required in the `config_setting`, given our use of `define`?

**Comment by mhlopko** [comment] 2017-05-30 12:23
I'm sorry (again) for the slow reply.

Well if your config_setting for qnx doesn't contain host_crosstool_top, it will be matched for both target and host configurations. With only the relevant pieces:
```
linkopts = select({
    "//build/toolchains:qnx": ["-lsocket"],
    "//conditions:default": [],
  }),
------------------------------------
config_setting(                                                                                                
    name = "qnx",                                                                                              
    values = {"define": "QNX=1"},                                                                              
    visibility = ["//visibility:public"],                                                                      
)        
------------------------------------
build:qnx --define QNX=1                                                                                                                                                                
build:qnx --host_crosstool_top=@bazel_tools//tools/cpp:toolchain   
```
The `-lsocket` should be added when `:qnx` is matched. That happens when the current configuration contains `--define QNX=1`. And since host configuration is to some extent a clone of target configuration, `--define QNX=1` will be part of it, even though it will use a different crosstool. So `config_setting` for `qnx` in this case is too broad, and should be made stricter by matching `host_crosstool_top` or `host_cpu`. Then the `config_setting` won't be matched when building in host configuration.

Does this make any sense?

**Comment by mhlopko** [comment] 2017-05-30 12:25
Closing again, will reopen if still not resolved.

**Closed by mhlopko** 2017-05-30 12:25 UTC
Labels: category: rules > C++, type: bug

**Comment by rtsai** [comment] 2017-05-30 14:54
Thank you!
