### ISSUE TITLE
Working directories are inconsistent between test and run

### ISSUE THREAD

**Issue by vitarb** [bazelbuild/bazel#7810] opened 2019-03-22 06:35 UTC
### Description of the problem / feature request:

Take this simple layout as an example:
```
.
├── config
│   └── foo
│       ├── BUILD.bazel
│       └── config.yaml
└── src
    └── foo
        ├── BUILD.bazel
        ├── main.go
        └── main_test.go
```
Now if we create `go_binary` and `go_test` rules passing config as `data` they then while running both would have to use different relative paths to access it due to different starting working directories.

In case of `test` working directory would be inside of the `src/foo` within symlink tree so it would need to use `../../config/foo` path, while in case of `run` it will be at the root of the tree and should use `config/foo`.

What makes it even more interesting that this behavior of `test` contradicts with the statement in [the documentation](https://docs.bazel.build/versions/master/test-encyclopedia.html) that says: *The initial working directory shall be `$TEST_SRCDIR/$TEST_WORKSPACE`.* Taking this into account, similarly to the binary it should point to the root of the tree.

Main problem with this is that in production code you would need to specify path from the repo root, while for tests you would need to specify path from the test directory and code needs to understand  in which context it is executed in order to correctly access resources. While this makes using things like local `testdata` more convenient it also brings in huge inconsistency.

### Feature requests: what underlying problem are you trying to solve with this feature?

Should we try to bring consistency and set working directory for tests to be at the root of the repo?
If no, we should update the documentation.

**Comment by linzhp** [comment] 2019-07-12 23:30
This is done in [rules_go](https://github.com/bazelbuild/rules_go/issues/1918#issuecomment-456469262), not in Bazel core. I think the rationale is to be consistent with "go test" behavior, whose working directory is in the package.

**Comment by susinmotion** [comment] 2019-09-17 19:49
Closing as a duplicate of https://github.com/bazelbuild/rules_go/issues/1918. Bazel handles this consistently, but the directory change is specific to the go rules.

**Closed by susinmotion** 2019-09-17 19:49 UTC
Labels: team-Local-Exec, untriaged
