### ISSUE TITLE
TMP: Tools used for Actions on Windows can't use tempdir()  easily

### ISSUE THREAD

**Issue by steven-johnson** [bazelbuild/bazel#2870] opened 2017-04-24 17:48 UTC
(Bazel v0.4.5 on Windows)

Summary: If you have a custom Bazel tool written in (e.g.) C++ that needs to use a temporary directory, you currently need to explicitly manage environment vars to do so.

Detail:

1. Write a tool in C++ that needs to use a temporary directory for some reason.
2. On Posixy systems, Bazel guarantees `/tmp` is writable, but since that's not a thing on Windows, the best option is generally calling Win32 `GetTempPath()`, or some wrapper code that ends up calling it (e.g. posix `tempdir()`)
3. `GetTempPath()` is documented as using values from env vars `$TMP`, `$TEMP`, and `$USER_PROFILE`; if none of those are set, it falls back to `C:\Windows`
4. Running the tool as an Action hides the default shell env, so none of the env vars in Step 3 are visible; on modern Windows systems, `C:\Windows` isn't necessarily writable by user code.
5. Watch your tool fail because it can't find a writable temporary directory.

Workarounds:

1. Explicitly specify a Windows-happy value for `$TMP` in the `env` argument to your action, taking care to add `select()` usage to only do this on Windows hosts. Or copy it from `host_configuration.default_shell_env`.
2. set `use_default_shell_env=True`, if you can live with non-hermetic builds
3. Rewrite your tool to avoid needing access to /tmp
4. Something else I haven't thought of.

My first thought for a reasonable fix here would be for `ctx.action` to ensure that a reasonable value is set for `$TMP` when running on Windows hosts; that might have unforeseen side-effects, though (e.g. portable code that directly calls `getenv("TMP")` could behave different on Windows vs non-Windows hosts).

If there was a Skylark rule to return a path to a temp directory, Workaround 1 could be done more simply, via something like `env={"TMP": ctx.tmp_dir()}`. (Arguably, you could do this now by using `ctx.genfiles_dir()`, if you're certain the tool will clean up after itself...)

**Comment by laszlocsomor** [comment] 2017-07-24 08:34
This is a blocker for https://github.com/bazelbuild/bazel/issues/3264, so I'm making it P1.

**Comment by laszlocsomor** [comment] 2017-09-04 09:24
Duplicate of https://github.com/bazelbuild/bazel/issues/1590

**Comment by laszlocsomor** [comment] 2017-09-06 18:46
Duplicate of #1590 and #2349.

**Comment by petemounce** [comment] 2017-09-12 12:02
@laszlocsomor the other 2 you linked are in milestone 0.6. I'm hoping strength of numbers pulls the fix for this into 0.6 rather than this pulling them into 0.7? ;)

**Comment by laszlocsomor** [comment] 2017-09-12 12:07
Hang in there, I'm working on it! :)

I wrote a design that's currently under review internally.

**Comment by laszlocsomor** [comment] 2017-09-25 06:02
Design is approved, I'll start implementing it this week. Stay tuned!

**Closed** 2017-11-14 14:54 UTC
Labels: category: multi-platform > windows, P1, type: feature request
