### ISSUE TITLE
repository_ctx.execute should allow showing progress

### ISSUE THREAD

**Issue by hanwen** [bazelbuild/bazel#1812] opened 2016-09-21 21:08 UTC
repostiroy rules that download things can be slow. It would be nice to show a progress bar. Or allow ctx.execute to pass  stderr to the console.

**Comment by laszlocsomor** [comment] 2016-09-22 10:49
I agree with this FR, but I don't realistically believe we can get to this in the near future, unless someone contributes the patch.

**Comment by hanwen** [comment] 2016-09-22 11:10
do the repository rules run in parallel ore are they fundamentally serial?

**Comment by damienmg** [comment] 2016-09-22 15:20
Duplicate of #1289. They do run mostly sequentially but downloads are a separate skyvalue. It would be possible to create a function to trigger // downloads though

**Closed by damienmg** 2016-09-22 15:20 UTC
Labels: P4, type: feature request
