### ISSUE TITLE
Bazel@HEAD cannot seem to keep a server process alive

### ISSUE THREAD

**Issue by lberki** [bazelbuild/bazel#22692] opened 2024-06-11 12:31 UTC
### Description of the bug:

When building Bazel from HEAD without `-c opt`, the client decides that the server process is unresponsive in about a fourth-fifth of the cases.

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

```
cd (Bazel repository)
git checkout fa2fbcdbec4a8a1b366a0f501866093738e17d8f
bazel build //src:bazel  # Note: this needs to be without -c opt, i.e. -c fastbuild

# devbazel refers to the Bazel version built above
cd (An empty directory with a MODULE.bazel file)
while true; do devbazel --bazelrc=/dev/null info server_pid; done  
```

Observe that the server restarts every once in a while.

### Which operating system are you running Bazel on?

Linux

### What is the output of `bazel info release`?

development version

### If `bazel info release` returns `development version` or `(@non-git)`, tell us how you built Bazel.

See above, from a clean source tree with `-c fastbuild` @ fa2fbcdbec4a8a1b366a0f501866093738e17d8f

**Comment by meteorcloudy** [comment] 2024-06-11 13:25
Yes, this one: https://github.com/bazelbuild/bazel/issues/20276

**Comment by meteorcloudy** [comment] 2024-06-11 13:26
And I can confirm if I revert the abseil upgrade at HEAD, we no longer have this problem.

**Comment by meteorcloudy** [comment] 2024-06-11 13:30
But let me try to upgrade grpc to
`bazel_dep(name = "grpc", version = "1.63.1")`, which contains https://github.com/grpc/grpc/commit/abbaa20223c95255f36a1bc70b3505e9daa006a2

**Comment by meteorcloudy** [comment] 2024-06-11 14:16
Upgrading grpc is going to take more effort than I expect, because it upgrades other dependencies, including protobuf. And protobuf since 26.0 no longer contains the maven dependencies: https://github.com/bazelbuild/bazel-central-registry/blob/main/modules/protobuf/26.0.bcr.1/MODULE.bazel (/cc @keith ). This means, targets like `"@com_google_protobuf//:protobuf_java"` no longer build.

**Comment by fmeum** [comment] 2024-06-11 14:27
Downgrading `abseil-cpp` is fine, I just upgraded it since it's now a dep of the new Java tool.

**Comment by meteorcloudy** [comment] 2024-06-12 07:59
The breakage should be fixed by https://github.com/bazelbuild/bazel/pull/22695, I'll rename this issue to track the upgrade of abseil-cpp

**Closed** 2024-06-12 08:00 UTC
Labels: type: bug, P1, team-OSS
