### ISSUE TITLE
'$' sign in java filegroup class (not allowed?)

### ISSUE THREAD

**Issue by andrewmed** [bazelbuild/bazel#2650] opened 2017-03-07 20:19 UTC
I have this rule:
```
filegroup(
    name = "srcs",
    srcs = glob(["**"]) + [
    ],
)
```
bazel cant include this file in the filegroup:
```
andy@laptop:~/repo/myapp$ bazel test ...
ERROR: /home/andy/repo/myapp/third_party/BUILD:3:1: //third_party:srcs: invalid label 'jmh/jmh-core-benchmarks/target/classes/org/openjdk/jmh/benchmarks/LevelInvocationBench$BenchmarkSetup.class' in element 343 of attribute 'srcs' in 'filegroup' rule: invalid target name 'jmh/jmh-core-benchmarks/target/classes/org/openjdk/jmh/benchmarks/LevelInvocationBench$BenchmarkSetup.class': target names may not contain '$'.
```
is not a dollar sign a legit java class name?

my setup
```
andy@laptop:~/repo/myapp$ bazel version
Build label: 0.4.4
Build target: bazel-out/local-fastbuild/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Wed Feb 1 18:54:21 2017 (1485975261)
Build timestamp: 1485975261
Build timestamp as int: 1485975261
andy@laptop:~/repo/myapp$ uname -a
Linux laptop 3.16.0-4-amd64 #1 SMP Debian 3.16.39-1+deb8u1 (2017-02-22) x86_64 GNU/Linux
```

**Comment by andrewmed** [comment] 2017-03-07 20:39
hmmm.. I tried to exclude `target` dirs with:
```
filegroup(
    name = "srcs",
    srcs = glob(
        ["**"],
        exclude = ["**/target/*"],
    ),
)
```
still get the same error. glob goes into the target directories...

**Comment by cushon** [comment] 2017-03-08 19:49
This is a duplicate of #374

**Comment by vladmos** [comment] 2017-03-09 14:12
Closing as a duplicate.

**Closed by vladmos** 2017-03-09 14:12 UTC
