### ISSUE TITLE
Native patch does not handle appended diffs without "diff -flags left right" headers.

### ISSUE THREAD

**Issue by deeglaze** [bazelbuild/bazel#9229] opened 2019-08-22 21:35 UTC
### Description of the problem:

A patch created with diff -Nur and appended with individual diffs results in files that look ambiguous, but are still treated in a way by the linux patch tool that produces our expected outcome.

new_file.patch:
diff -Nur didnt_exist.md didnt_exist.md
--- didnt_exist.md
+++ didnt_exist.md
@@ -0,0 +1,1 @@
+Contents
--- /dev/null
+++ new_file.md
@@ -0,0 +1,1 @@
+Uh oh, ---[^\n]*\n+++[^\n]*\n@@ isn't special.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

With the new_file.patch contents above and the following setup, you can see the failure
WORKSPACE:
workspace(name = "bazel_bug")                                                                                                                             load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")
# Skylib used as an example dependency that I patch.
skylib_version = "0.8.0"
http_archive(
name = "bazel_skylib",
type = "tar.gz",
patches = ["//:new_file.patch"],
url = "https://github.com/bazelbuild/bazel-skylib/releases/download/{}/bazel-skylib.{}.tar.gz".format (skylib_version, skylib_version),
sha256 = "2ef429f5d7ce7111263289644d233707dba35e39696377ebab8b0bc701f7818e",
) 

.bazelversion:
last_green

BUILD:
load("@bazel_skylib//lib:paths.bzl", "paths")
exports_files(["new_file.patch"])                                                                                                                         cc_library(name = "empty")

Failing command:
bazelisk build :empty

Cannot find file to patch (near line 1), old file name (%s) is not specified, new file name (didnt_exist.md) doesn't exist.

### What operating system are you running Bazel on?

Ubuntu

### What's the output of `bazel info release`?

dionnaglaze@dionnaglaze-linux:~/gitrepos/bazel_bug$ bazelisk info release                                                                                 2019/08/22 14:32:27 Using unreleased version at commit fdcde7c6a8f249460ea5894004b367163187d3ed

###  Have you found anything relevant by searching the web?

No

### Any other information, logs, or outputs that you want to share?

This has some weird semantics in linux's patch to handle this case.

a.md:
a
b
c
d

bad.patch:
diff -Nur didnt_exist.md didnt_exist.md
--- didnt_exist.md
+++ didnt_exist.md
@@ -0,0 +1,1 @@
+Contents
--- a.md
+++ a.md
@@ -3,1 +3,1 @@
-c
+cc

There is no `diff -Nur a.md a.md` line separating to two patched files, so the --- is treated as removing "-- a.md" as a line in the non-existent file. This patch fails with the Linux patch tool.

But, this does add to the start of a.md if the second diff is
--- a.md
+++ a.md
@@ -0,0 +1,1 @@
+First!

It's this second case that we have in our patch file in Asylo. We could modify how we generate our patch file to be less ambiguous, but I think Bazel should also have closer behavior to Linux's patch tool. I suspect you'll find strange patch files like these as time trickles on.

I think that if the non-context (" "-started) lines following @@ -n,m +a,b @@ exceed m+b lines, you should consider a --- to be part of a next file's diff, as a way to disambiguate.

**Comment by meteorcloudy** [comment] 2022-12-08 15:18
This is actually a duplicate of https://github.com/bazelbuild/bazel/issues/10267

**Closed by meteorcloudy** 2022-12-08 15:18 UTC
Labels: type: feature request, P2, team-ExternalDeps, help wanted
