### ISSUE TITLE
The Bazel server restarting causes a rebuild of CC rules

### ISSUE THREAD

**Issue by naphatkrit** [bazelbuild/bazel#2524] opened 2017-02-11 16:40 UTC
### Description of the problem / feature request / question:

This is easily reproducible in the Bazel repo itself.
```
bazel build --spawn_strategy=sandboxed --genrule_strategy=sandboxed --subcommands //srcs/main/tools:linux-sandbox
bazel shutdown
bazel build --spawn_strategy=sandboxed --genrule_strategy=sandboxed --subcommands //srcs/main/tools:linux-sandbox
```
The second command will result in the CC rule being rebuilt, even though it didn't need to be. Note that I put the `sandboxed` strategy to prevent the remote cache from kicking in.

### Environment info
* Operating System:
Ubuntu 12.04, Kernel 4.4.0-57-generic

* Bazel version (output of `bazel info release`):
This is from building bazel locally (`./compile.sh compile /path/to/release/bazel`)
```
release 0.4.4-2017-02-11 (@0eaff44)
```

###  Have you found anything relevant by searching the web? (e.g. GitHub issues, email threads in the [bazel-discuss@googlegroups.com](https://groups.google.com/forum/#!forum/bazel-discuss) archive)
not that I could find.

**Comment by dslomov** [comment] 2017-02-16 10:55
@ulfjack, this is something you have been working on?

**Comment by ulfjack** [comment] 2017-02-16 11:50
Yes, this is a duplicate of #2490.

**Closed by ulfjack** 2017-02-16 11:50 UTC
Labels: category: rules > C++, type: bug
