### ISSUE TITLE
Tutorial //android target is broken

### ISSUE THREAD

**Issue by kchodorow** [bazelbuild/bazel#1730] opened 2016-09-06 14:35 UTC
Something about zipalign:

```
ERROR: missing input file '@androidsdk//:build-tools/22.0.1/zipalign'.
ERROR: /home/ci/.cache/bazel/_bazel_ci/c4a50d75262886cc5ef67fcb9cdac72a/external/bazel_tools/src/tools/android/java/com/google/devtools/build/android/BUILD:24:1: Creating runfiles tree bazel-out/host/bin/external/bazel_tools/src/tools/android/java/com/google/devtools/build/android/AndroidResourceProcessingAction.runfiles [for host] failed: build-runfiles failed: error executing command /home/ci/.cache/bazel/_bazel_ci/c4a50d75262886cc5ef67fcb9cdac72a/execroot/tutorial/_bin/build-runfiles ... (remaining 2 argument(s) skipped): com.google.devtools.build.lib.shell.AbnormalTerminationException: Process terminated by signal 15.
ERROR: /home/ci/.cache/bazel/_bazel_ci/c4a50d75262886cc5ef67fcb9cdac72a/external/androidsdk/BUILD:5:1: @androidsdk//:zipalign_binary: missing input file '@androidsdk//:build-tools/22.0.1/zipalign'.
____Building complete.
Target //android:android failed to build
```

http://ci.bazel.io/view/Bazel%20bootstrap%20and%20maintenance/job/Tutorial/PLATFORM_NAME=ubuntu_15.10-x86_64/439/console

**Comment by aj-michael** [comment] 2016-09-06 14:44
The problem seems to be that we're expecting the layout of the Android SDK to contain a build-tools directory, and Jenkins is using 22.0.1 which did not.

**Comment by kchodorow** [comment] 2016-09-06 14:53
Should we update the SDK on Jenkins or make the rules backward compatible?

**Comment by aj-michael** [comment] 2016-09-06 15:02
I think we should update the SDK to 24.x.x. For better or worse, at the moment we tend to expect that developers are using the most up-to-date SDK to develop. I'm sure that `zipalign` is not the only thing that does not work with 22.0.1.

I am curious, however, and still investigating as to how Jenkins was building `//android` with SDK 22.0.1 prior to August 17.

**Comment by aj-michael** [comment] 2016-09-06 15:03
@ahumesky , thoughts on supporting older SDKs?

**Comment by aj-michael** [comment] 2016-09-06 15:17
Oops, I'm wrong. I saw that SDK 22.0.1 contains `tools/zipalign` and jumped to the assumption above.

I forgot that the `build-tools` must be installed separately from the SDK. Maybe on August 18th we set up a new Jenkins server and forgot to install SDK build-tools?

**Comment by aj-michael** [comment] 2016-09-06 15:21
This looks relevant https://github.com/bazelbuild/continuous-integration/issues/21

**Comment by aj-michael** [comment] 2016-09-06 15:50
Just some notes from my digging:

* We download the most recent build-tools version (24.0.2 at the moment) with https://github.com/bazelbuild/continuous-integration/blob/master/gce/linux-android.sh#L27
* We export the environment variable ANDROID_SDK_BUILD_TOOLS_VERSION to the value from the installed build-tools (24.0.2) with https://github.com/bazelbuild/continuous-integration/blob/master/gce/jenkins-slave.sh#L37
* We set the build_tools_version based on the environment variable https://github.com/bazelbuild/bazel/blob/master/scripts/ci/build.sh#L79.
* Judging by the Jenkins console output, it looks like the environment variable is not being set and we are defaulting to 22.0.1 which is the default. That build-tools is not installed so Jenkins fails.

**Comment by damienmg** [comment] 2016-09-06 15:57
FYI the whole setup of the Tutorial is wrong and I am working on fixit it, which led me to shave the yak to fixing the ci-staging that is needed to test actually the Tutorial setup.

**Comment by damienmg** [comment] 2016-09-13 11:26
This is now fixed \o/

**Closed by damienmg** 2016-09-13 11:26 UTC
Labels: category: rules > android, P1, type: bug

**Comment by Anmolk22** [comment] 2017-02-27 11:08
Hey @damienmg can you tell me how did you deal zipalign missing issue

**Comment by ahumesky** [comment] 2017-02-27 18:01
Hi @Anmolk22 could you open a separate bug or a discussion at [bazel-discuss](https://groups.google.com/forum/#!forum/bazel-discuss) with the details of the issue you're seeing?

**Comment by Anmolk22** [comment] 2017-02-27 18:22
@ahumesky I found the cause after going through many issues the answer quiet simple I was trying to build tensorflow using bazel from bash on msys2 over windows which is not possible as if now.
If you know that's possible let me know. 
Would up a discussion gladly. Thank you

**Comment by aj-michael** [comment] 2017-02-27 18:40
I thought we already had a bug thread for "support Android on Windows" but I can't seem to find it now. We should certainly have one, because this seems to come up a lot.

In the last week this has been asked twice on StackOverflow:
http://stackoverflow.com/questions/42400235/i-have-problems-like-configuring-basel-on-windows
http://stackoverflow.com/questions/42387999/bazel-build-error-in-tensorflow
