### ISSUE TITLE
Feature request: add target platform info in repository_ctx 

### ISSUE THREAD

**Issue by ipolyakovskiy** [bazelbuild/bazel#4636] opened 2018-02-14 15:57 UTC
### Description of the problem / feature request:
We are using libzmq in our project, I created repository_rule to compile it, because there is some platform-dependent headers generated by autoconf or cmake. To cross-compile it, I should add some flags to "./configure" call to generate headers for target platform. But I didn't find any possibilities to provide information about target platform in repository_rule. I couldn't use "select" in rules invoked from WORKSPACE and repository_ctx contains information about host platform only. 

### Feature requests: what underlying problem are you trying to solve with this feature?
To cross-compile external library sometimes you need to provide target platform information to configure/code-generation stage

###  Have you found anything relevant by searching the web?

Nothing

**Comment by davido** [comment] 2018-02-15 11:49
Duplicate of: #2045.

**Comment by ipolyakovskiy** [comment] 2018-02-15 12:27
I'm not sure about it. AFAIU there is a talk about host system configuration in that issue. I'm talking about target platform, which is build parameter like --cpu and --crosstool_top. Did I misunderstood something?

**Comment by dslomov** [comment] 2018-02-15 13:53
Repository rules do not have access to target platfrom. They execute very early, before the loading phase.
You should call `./configure && make` in the build rule that the repository rule emits instead. Cf. https://blog.envoyproxy.io/external-c-dependency-management-in-bazel-dd37477422f5

**Comment by philwo** [comment] 2018-02-15 15:55
@dslomov Marking this as "type: support" as I understand that this is working as intended. Please recategorize as feature request if you instead want to change this in the future.

**Comment by mhlopko** [comment] 2018-03-21 16:08
I'm closing since there's nothing we plan to do on this front.

**Closed by mhlopko** 2018-03-21 16:08 UTC
Labels: type: support / not a bug
