### ISSUE TITLE
java.lang.RuntimeException: Unrecoverable error while evaluating node 'ActionTemplateExpansionKey'

### ISSUE THREAD

**Issue by pylaligand** [bazelbuild/bazel#5372] opened 2018-06-12 02:12 UTC
### Description of the problem / feature request:

java.lang.RuntimeException: Unrecoverable error while evaluating node 'ActionTemplateExpansionKey' with custom template using tree artifacts.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

The bugs linked below have some repro steps. Here's the change that introduced the crash: https://fuchsia-review.googlesource.com/c/scripts/+/163849/1/sdk/bazel/base/build_defs/fidl_cc.bzl
If really needed I could try to distill this down into something that does not have Fuchsia specifics.

### What operating system are you running Bazel on?

Linux

### What's the output of `bazel info release`?

release 0.14.1

###  Have you found anything relevant by searching the web?

https://github.com/bazelbuild/bazel/issues/317#issuecomment-384074168 reports a similar error. So does https://github.com/bazelbuild/bazel/issues/5092. Neither comment thread addresses the specific stack trace.

### Any other information, logs, or outputs that you want to share?

```
Starting local Bazel server and connecting to it...
..............
INFO: Analysed 7 targets (18 packages loaded).
INFO: Found 7 targets...
Unhandled exception thrown during build; message: Unrecoverable error while evaluating node 'ActionTemplateExpansionKey{actionLookupKey=//fidl-cc:cc 5aa334f647e4f051332da6583dc5e908 false (139301120), actionIndex=2}' (requested by nodes 'fidl-cc/_pic_objs/cc/fidl-cc/cc_codegen //fidl-cc:cc 5aa334f647e4f051332da6583dc5e908 false (139301120)')
INFO: Elapsed time: 4.086s, Critical Path: 0.75s
INFO: 8 processes: 6 linux-sandbox, 2 local.
FAILED: Build did NOT complete successfully
java.lang.RuntimeException: Unrecoverable error while evaluating node 'ActionTemplateExpansionKey{actionLookupKey=//fidl-cc:cc 5aa334f647e4f051332da6583dc5e908 false (139301120), actionIndex=2}' (requested by nodes 'fidl-cc/_pic_objs/cc/fidl-cc/cc_codegen //fidl-cc:cc 5aa334f647e4f051332da6583dc5e908 false (139301120)')
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:441)
	at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:355)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalStateException
	at com.google.devtools.build.lib.rules.cpp.CppCompileActionBuilder.getActionName(CppCompileActionBuilder.java:250)
	at com.google.devtools.build.lib.rules.cpp.CppCompileActionBuilder.buildAndVerify(CppCompileActionBuilder.java:327)
	at com.google.devtools.build.lib.rules.cpp.CppCompileActionTemplate.createAction(CppCompileActionTemplate.java:120)
	at com.google.devtools.build.lib.rules.cpp.CppCompileActionTemplate.generateActionForInputArtifacts(CppCompileActionTemplate.java:91)
	at com.google.devtools.build.lib.skyframe.ActionTemplateExpansionFunction.compute(ActionTemplateExpansionFunction.java:83)
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:363)
	... 4 more
java.lang.RuntimeException: Unrecoverable error while evaluating node 'ActionTemplateExpansionKey{actionLookupKey=//fidl-cc:cc 5aa334f647e4f051332da6583dc5e908 false (139301120), actionIndex=2}' (requested by nodes 'fidl-cc/_pic_objs/cc/fidl-cc/cc_codegen //fidl-cc:cc 5aa334f647e4f051332da6583dc5e908 false (139301120)')
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:441)
	at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:355)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalStateException
	at com.google.devtools.build.lib.rules.cpp.CppCompileActionBuilder.getActionName(CppCompileActionBuilder.java:250)
	at com.google.devtools.build.lib.rules.cpp.CppCompileActionBuilder.buildAndVerify(CppCompileActionBuilder.java:327)
	at com.google.devtools.build.lib.rules.cpp.CppCompileActionTemplate.createAction(CppCompileActionTemplate.java:120)
	at com.google.devtools.build.lib.rules.cpp.CppCompileActionTemplate.generateActionForInputArtifacts(CppCompileActionTemplate.java:91)
	at com.google.devtools.build.lib.skyframe.ActionTemplateExpansionFunction.compute(ActionTemplateExpansionFunction.java:83)
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:363)
FAILED: Build did NOT complete successfully
```

**Comment by laszlocsomor** [comment] 2018-06-12 09:18
Nor sure if this is a C++ or a Skylark bug -- adding both @laurentlb and @mhlopko .

**Comment by laurentlb** [comment] 2018-06-12 09:28
Looks like C++ to me.

**Comment by laszlocsomor** [comment] 2018-06-13 09:44
> I think the action item here is to make the error message a bit more obvious, as right now the code just `throw new IllegalStateException()`.

@mhlopko : WDYT?

**Comment by mhlopko** [comment] 2018-06-15 13:03
Definitely a bug, I'll look into it. Thank you for reporting!

**Comment by mhlopko** [comment] 2018-06-22 12:58
I didn't try to repro, but it looks like a duplicate of the first part of #5092. @pylaligand is it possible that you have private headers in the directory artifacts in srcs? If yes, the fix is in the pipeline. If no, I'll have to reproduce this issue.

**Comment by pylaligand** [comment] 2018-06-22 13:03
Yes, I had headers in the tree artifact. Everything worked fine when I moved these headers to `hdrs` instead - which was the correct thing to do anyways as the headers were supposed to be public.

**Comment by mhlopko** [comment] 2018-06-22 13:06
Great, no need to repro then :)

**Closed** 2018-06-26 12:47 UTC
Labels: category: extensibility > skylark, category: rules > C++, under investigation
