### ISSUE TITLE
4c67807964e37cfd55bbcda4c6374fcc480bcecc breaks TensorFlow

### ISSUE THREAD

**Issue by dslomov** [bazelbuild/bazel#2136] opened 2016-11-24 16:37 UTC
See http://ci.bazel.io/job/TensorFlow/510/.
I confirmed that rolling back https://github.com/bazelbuild/bazel/commit/4c67807964e37cfd55bbcda4c6374fcc480bcecc fixes the issue

**Comment by dslomov** [comment] 2016-11-24 16:37
@jart please take a look.

**Comment by dslomov** [comment] 2016-11-24 16:38
To repro the problem on your local machine:
```bash
$ git clone git@github.com:tensorflow/tensorflow.git
$ cd tensorflow
$ ./configure # bazel should be in PATH
```

**Comment by jart** [comment] 2016-11-24 17:42
On it right now.

**Comment by jart** [comment] 2016-11-24 18:20
I've identified the problem. zlib web server sends `Content-Encoding: gzip` for a gzip file. My change is meant to automatically un-gzip when that happens, even though it shouldn't for the `.gz` extension.

```
curl jart@compy:~/code/tensorflow-clean$ curl -I http://zlib.net/zlib-1.2.8.tar.gz
HTTP/1.1 200 OK
Date: Thu, 24 Nov 2016 18:17:44 GMT
Server: Apache/2.4.18 (Unix) OpenSSL/1.0.1e-fips mod_bwlimited/1.4
Last-Modified: Mon, 29 Apr 2013 00:33:14 GMT
ETag: "6109a7f-8b6d3-4db7507b80680"
Accept-Ranges: bytes
Content-Length: 571091
Content-Type: application/x-gzip
Content-Encoding: gzip
```

I'm writing a fix right now. I'm going to send it straight to the GitHub repo as a pull request unless you ask me to send it somewhere else.

**Comment by jart** [comment] 2016-11-24 18:37
Actually I'm going to send a CL since none of the PRs on this repo get merged; they all seem to get patched to internal CLs.

**Comment by jart** [comment] 2016-11-24 18:38
Confirmed fix works on TensorFlow repository. Mailing CL now.

**Closed** 2016-11-25 12:21 UTC
Labels: breakage, P0, Release blocker
