### ISSUE TITLE
IllegalArgumentException compiling Java on Debian 9.9

### ISSUE THREAD

**Issue by ulfjack** [bazelbuild/bazel#8296] opened 2019-05-11 12:54 UTC
### Description of the problem / feature request:

Building Java crashes with IllegalArgumentException on Debian 9.9.
```
Exception in thread "main" java.lang.IllegalArgumentException: external/local_jdk
	at jdk.compiler/com.sun.tools.javac.file.Locations$SystemModulesLocationHandler.isCurrentPlatform(Locations.java:1862)
	at jdk.compiler/com.sun.tools.javac.file.Locations$SystemModulesLocationHandler.update(Locations.java:1851)
	at jdk.compiler/com.sun.tools.javac.file.Locations$SystemModulesLocationHandler.handleOption(Locations.java:1798)
	at jdk.compiler/com.sun.tools.javac.file.Locations.handleOption(Locations.java:2062)
	at jdk.compiler/com.sun.tools.javac.file.BaseFileManager.handleOption(BaseFileManager.java:269)
	at jdk.compiler/com.sun.tools.javac.file.BaseFileManager$2.handleFileManagerOption(BaseFileManager.java:222)
	at jdk.compiler/com.sun.tools.javac.main.Option.process(Option.java:1138)
	at jdk.compiler/com.sun.tools.javac.main.Option.handleOption(Option.java:1086)
	at jdk.compiler/com.sun.tools.javac.file.BaseFileManager.handleOption(BaseFileManager.java:232)
	at jdk.compiler/com.sun.tools.javac.main.Arguments.doProcessArgs(Arguments.java:390)
	at jdk.compiler/com.sun.tools.javac.main.Arguments.processArgs(Arguments.java:347)
	at jdk.compiler/com.sun.tools.javac.main.Arguments.init(Arguments.java:246)
	at jdk.compiler/com.sun.tools.javac.api.JavacTool.getTask(JavacTool.java:185)
	at DumpPlatformClassPath.dumpJDK9AndNewerBootClassPath(DumpPlatformClassPath.java:106)
	at DumpPlatformClassPath.main(DumpPlatformClassPath.java:67)
Caused by: java.nio.file.NoSuchFileException: external/local_jdk
	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
	at java.base/sun.nio.fs.UnixFileSystemProvider.isSameFile(UnixFileSystemProvider.java:333)
	at java.base/java.nio.file.Files.isSameFile(Files.java:1530)
	at jdk.compiler/com.sun.tools.javac.file.Locations$SystemModulesLocationHandler.isCurrentPlatform(Locations.java:1860)
	... 14 more
```

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

```
bazel build //target
```

### What operating system are you running Bazel on?

Fresh install of Debian 9.9.

### What's the output of `bazel info release`?

release 0.25.2

###  Have you found anything relevant by searching the web?

> Replace these lines with your answer.
>
> Places to look:
> - StackOverflow: http://stackoverflow.com/questions/tagged/bazel
> - GitHub issues: https://github.com/bazelbuild/bazel/issues
> - email threads on https://groups.google.com/forum/#!forum/bazel-discuss

**Comment by ulfjack** [comment] 2019-05-11 12:54
This is the failing action:
```
SUBCOMMAND: # @bazel_tools//tools/jdk:platformclasspath [action 'SkylarkAction external/bazel_tools/tools/jdk/platformclasspath.jar']
(cd /home/ulfjack/.cache/bazel/_bazel_ulfjack/d29c8222d86f95fbaf9a5871f1148863/execroot/__main__ && \
  exec env - \
  external/remotejdk11_linux/bin/java -XX:+IgnoreUnrecognizedVMOptions '--add-exports=jdk.compiler/com.sun.tools.javac.platform=ALL-UNNAMED' -cp bazel-out/k8-fastbuild/bin/external/bazel_tools/tools/jdk/platformclasspath_classes:external/remotejdk11_linux/lib/tools.jar DumpPlatformClassPath bazel-out/k8-fastbuild/bin/external/bazel_tools/tools/jdk/platformclasspath.jar external/local_jdk)
```

**Comment by ulfjack** [comment] 2019-05-11 12:59
It seems to be missing a locally installed Jdk. It works when I install one. It seems like the local_jdk workspace rule just silently continues if there's no installed Jdk?

**Comment by benjaminp** [comment] 2019-05-11 22:01
Yes, if no system JDK is detected, `@local_jdk` points to the main workspace, which can have other interesting consequences: #7342

**Comment by cushon** [comment] 2019-05-12 22:25
This looks like a dupe of #6118.

**Closed by cushon** 2019-05-12 22:25 UTC
Labels: team-Rules-Java, untriaged
