### ISSUE TITLE
How to make bazel use custom build ld (not in /usr/bin/)

### ISSUE THREAD

**Issue by renguomin** [bazelbuild/bazel#5915] opened 2018-08-16 18:04 UTC
I tried to add the new binutils path into PATH, and set use_default_shell_env=True, but bazel still use /usr/bin/ld instead of the newer version I build myself. Can someone help me?

**Comment by aiuto** [comment] 2018-08-16 19:08
Could you provide more context:
- how your workspace is set up
- how you are modifying PATH
- the rule you are creating which does the link

**Comment by renguomin** [comment] 2018-08-17 18:02
I was trying to build tensorflow 1.9 for a computer cluster in school (so I don't have root access). I have solved the problem! I knew I have to use toolchain. The problem was that there are so many toolchain related files I didn't know which one to modify. Even in one file, say CROSSTOOL, there seems to have multiple places/lines are related to the path of ld, for example:
1.  linker_flag: "-B/usr/bin"
and 2. tool_path { name: "ld" path: "/usr/bin/ar" }
I found it is really hard to know which one to change unless I read though the whole code.

Before I found the solution, I tried to change the CROSSTOOL and then compiled Bazel, it did not work. Yesterday I found an article mentioned I also need to change third_party/gpus/crosstool in tensorflow source code: http://biophysics.med.jhmi.edu/~yliu120/tensorflow.html

**Comment by renguomin** [comment] 2018-08-17 18:05
By the way the reason I need to specify a custom dynamic linker is that the ld on the cluster is too old does not support AVX2 instruction set and I didn't have root access to upgrade it.

**Comment by aiuto** [comment] 2018-08-17 19:00
Glad to hear the problem is resolved. I'll leave this open until the team working on CROSSTOOL can take in the lessons learned from your experience. They can close it at that point.

**Comment by 29x10** [comment] 2018-10-15 07:43
any update on this?

**Comment by ClaudioCimarelli** [comment] 2018-12-11 13:57
@renguomin I think I am having the same issue because bazel is using /usr/bin/ld which is old.
 To solve this is enough changing one file as in the guide you linked? Thanks, I really hope this could solve my issues...

**Comment by hlopko** [comment] 2019-01-09 14:47
I'll close now, because:

* we have docs now:
  * https://docs.bazel.build/versions/master/crosstool-reference.html
  * https://docs.bazel.build/versions/master/tutorial/crosstool.html
* we are ditching the crosstool in proto:
  * https://github.com/bazelbuild/bazel/issues/4570
* we are rewriting cc_configure to be more powerful:
  * https://github.com/bazelbuild/bazel/issues/6926

Thanks for reporting!

**Closed by hlopko** 2019-01-09 14:47 UTC
Labels: team-Rules-CPP

**Comment by timokau** [comment] 2019-06-24 17:16
Is there a way for distro maintainers to override a `tool_path` without having to patch the source? Something like setting an environment variable `BAZEL_AR_PATH=/some/path/to/ar`.

**Comment by Char-Aznable** [comment] 2019-07-26 15:37
I am having the exact same situation here (https://github.com/tensorflow/tensorflow/issues/31083) because the OS is too old and I have to use toolchain in nonstandard location. @hlopko The links you provided don't exist any more. Can you provide more information on how was this problem fixed? I am new to bazel and I'm completely lost at this point.

**Comment by izahn** [comment] 2021-06-03 09:51
For future wanderers of the web: The solution is to set GCC_HOST_COMPILER_PREFIX as noted in https://github.com/bazelbuild/bazel/issues/8715 and https://github.com/tensorflow/tensorflow/issues/31083
