### ISSUE TITLE
Support running persistent workers remotely

### ISSUE THREAD

**Issue by tsiq-charliem** [bazelbuild/bazel#10091] opened 2019-10-23 17:05 UTC
> ATTENTION! Please read and follow:
> - if this is a _question_ about how to build / test / query / deploy using Bazel, or a _discussion starter_, send it to bazel-discuss@googlegroups.com
> - if this is a _bug_ or _feature request_, fill the form below as best as you can.

### Description of the problem / feature request:

Looking for support for running persistent workers on remote hosts.

### Feature requests: what underlying problem are you trying to solve with this feature?

Currently, actions can be run with the `remote` strategy or the `worker` strategy, but we'd like a way to get the benefits of a persistent worker on a remote build. Without this, our local builds with persistent workers outperform remote builds.

### What operating system are you running Bazel on?

Ubuntu 16.04

### What's the output of `bazel info release`?

1.0.0

**Comment by buchgr** [comment] 2019-10-28 09:38
@tsiq-charliem there's the https://blog.bazel.build/2019/02/01/dynamic-spawn-scheduler.html that will get you the best of both.

We currently have no plans for to work on worker support for remote execution.

**Comment by meisterT** [comment] 2020-08-04 09:52
Closing as we don't plan to add persistent worker support for remote execution.

**Comment by ulfjack** [comment] 2020-08-12 11:50
I have a patch for this. It's pretty small, so it may be acceptable to check it in?

**Comment by meisterT** [comment] 2020-08-12 11:52
Interesting, how does that look like?

**Comment by ulfjack** [comment] 2020-08-12 11:59
Patch is here: https://github.com/ulfjack/bazel/tree/remote-persistent-worker

**Comment by meisterT** [comment] 2020-08-12 12:15
cc @coeuvre @larsrc-google

**Comment by ulfjack** [comment] 2020-10-15 21:47
Support for remote persistent workers is one of our most requested features and we've seen significant performance improvements in some real-world scenarios with proprietary codebases. I've rebased my change to HEAD, but I still need to add some tests.

**Comment by bergsieker** [comment] 2020-10-16 19:57
Your patch seems reasonable as far as adding the tool signature to the Platform. As far as I read it, it's just adding the hash of the tool paths, not trying to get a stronger signature like the digest of the binaries, right? It's possible that splitting into multiple cache keys, one for each referenced tool, might be desirable because it gives the server more scheduling flexibility in terms of prioritizing one tool over another, but I'm not sure how frequent multi-tool actions are so it may not make much difference in practice.

I'm a little skeptical of adding built-in support for this in Bazel without understanding what a workable server implementation looks like. When we've noodled around on this in the past, it's been hard to come up with something that was safe, flexible enough to handle varying workloads and multiple tools, and that provided reasonable affordances for debugging. Does this ultimately break down to per-worker pool targeting, combined with some server functionality to keep the tools up, allow for resets, etc.?

**Comment by ulfjack** [comment] 2020-10-17 21:36
Bazel already supports workers with a single worker 'tool' with a specific API (actually, there are two APIs - the vanilla API and the multiplex API). This PR only annotates the remote execution requests with just enough information to be able to implement the same API remotely. Note that it is safe for a server to ignore this information, and just continue as usual. Also note that this is behind an experimental flag.

There are any number of ways to implement this on the server-side. Per-worker pool is one way, although that doesn't seem very appealing to me. Generally speaking, we have found it straightforward to keep track of the most recent 'persistent worker key' for each worker and assign actions to a matching worker if possible.

It may be necessary to overprovision worker resources to allow the scheduler sufficient leeway in assigning actions to workers. Certainly, a first-come-first-serve scheduler will struggle if there is queueing as it won't be able to make meaningful decisions. However, a scheduler could also delay actions (say for a few hundred ms) or reorder the first few queue entries to generate more options. In the first case, there is a chance that another better-matching worker instance becomes available during that time. In the reordering case, there is a chance that another better-matching action is near the front of the queue (but probably requires a safe-guard to prevent actions from being skipped indefinitely).

On the positive side, we've seen performance improvements even if we can only find matching workers for a small percentage of actions. There's basically no downside to providing the extra information - the performance is virtually identical to the non-persistent-worker case if we can't ever schedule an action to a matching instance. We have also seen cases where moving to remote builds *without* persistent workers is a significant performance *regression* compared to local builds because the action graph is not sufficiently wide (and given the inherent overhead of remote execution), and local builds already use persistent workers.

Finally, people seem to be happy to enable this without particular regard to safety or security given the significant benefits we're seeing on the performance side. Given that people are happy to use remote caching (which has strictly worse safety and security), I find this entirely unsurprising. Debugging hasn't been an issue for us so far, maybe because persistent workers are already widely used for local execution.

**Comment by larsrc-google** [comment] 2020-11-17 17:09
Ulf, could you turn the above into a little design doc and attach it to a PR for this change?

**Comment by larsrc-google** [comment] 2021-02-11 10:32
@ericburnett

Ulf, are you far enough along with this that you could do a design doc? Eric is concerned that getting remote workers to be safe and correct is not that easy, but it would be a great feature.

**Comment by EricBurnett** [comment] 2021-02-11 21:01
+1 for a design doc. Ideally with some discussion on whether this is needed in all cases, or only to reduce latency on user-driven incremental builds - I'd be much less concerned if e.g. caching was disabled for remote-worker actions and there was no cross-user sharing of workers, as that'd significantly reduce the blast radius of issues while potentially keeping all the interesting benefits?

> Given that people are happy to use remote caching (which has strictly worse safety and security), I find this entirely unsurprising.

FWIW most groups I've worked with that enabled remote caching have poisoned their cache at least once, so I'd still suggest having a response plan for dealing with that :).

**Comment by ulfjack** [comment] 2021-03-06 00:27
I finally wrote a design doc: https://github.com/bazelbuild/proposals/pull/219

**Comment by wiwa** [comment] 2022-01-26 23:22
Would it be helpful for remexec backends to implement their ends of remote persistent workers if they could depend on `//src/main/java/com/google/devtools/build/lib/worker`? i.e. should `worker` be visible through `@bazel_tools`?

**Comment by wiwa** [comment] 2022-04-20 07:51
@ulfjack While playing around with your patch, I noted that the change doesn't fully specify the initial `--persistent_worker` command, meaning that each remote worker would have to know this ahead of time. I was able to get Bazel to spit out this information from the `WorkerKey` you exposed in a small extra change here: https://github.com/wiwa/bazel/commit/d9c7ae9abcd01b2dc7b93e0ac449df4a2c02d76b 

Unfortunately, I had to stuff it in the `Platform`'s `additionalProperties` field. What do you think about this addition? Is there a better way to specify "extra metadata" on remote execution requests? I see that your (accepted) proposal has additional data which Bazel sends. In my change, I was thinking that `ToolSignature` could be a subset of `WorkerKey`. Instead, now I'm thinking that `ToolSignature` would be... exactly `WorkerKey`, or at least, the info that we're missing from it (for example, we already have the info of the input files from the file marker).

**Comment by ittaiz** [comment] 2022-07-11 05:11
What's the status of this?
The design doc was merged a year ago. Did Ulf's patch make it in somehow?

**Comment by meisterT** [comment] 2022-07-11 07:08
> Did Ulf's patch make it in somehow?

Not yet, but we started looking into this again just last week. We have to play around with the patch to see if it needs any change.

cc @sadaf-matinkhoo @larsrc-google

**Closed** 2022-10-20 09:40 UTC
Labels: type: feature request, P3, team-Remote-Exec
