### ISSUE TITLE
Optimise repository rule generation with re-entrancy

### ISSUE THREAD

**Issue by Silic0nS0ldier** [bazelbuild/bazel#16162] opened 2022-08-25 03:07 UTC
### Description of the feature request:

Instead of restarting repository rule fetching when a new dependency is discovered, pause execution and resume once it is available.

Subject to how this is achieved, it should provide;
* A major performance boost to many repository rule implementations
* More predictable performance
* More options for optimisation (using dependency references early is now only necessary to better parallelise work, meaning there are more options for efficiently dealing with optional dependencies)

### What underlying problem are you trying to solve with this feature?

Repository rules taking a long time to complete due to late dependency references triggering restarts. Starlark implementations can be optimised by touching dependencies early on, but in practice this is easily overlooked as;

* Ruleset tests typically operate on a much smaller scale than the projects they are used for. As a result releases are often not optimised (because ruleset CI checks seem fine) and regressions are easy to introduce (because their impact cannot be captured by CI checks).
* It isn't clear from the Starlark source if a given API call will trigger a restart, profiling and debugging is often necessary to identify the bottleneck (along with being aware of the restart behaviour, so the appropriate pattern is sought out).

Further, refactoring to address the performance penalty of restarts is itself a major time sink.

* The refactoring is often non-trivial. Especially if abstractions are used.
* Sometimes referencing dependencies early is a trade-off. Implementations which deal with external elements like OS integrations may have dependencies that are conditionally required, and can only be determined at a late stage of execution. The only way to avoid an expensive restart here is to eagerly fetch optional dependencies, which could hurt performance more overall (odds are this would be discovered after refactoring, and consider that different projects may present different performance characteristics).

### Which operating system are you running Bazel on?

macOS 12.5.1

### What is the output of `bazel info release`?

release 5.1.1- (@non-git)

### If `bazel info release` returns `development version` or `(@non-git)`, tell us how you built Bazel.

With Nix, via https://github.com/NixOS/nixpkgs/archive/13e0d337037b3f59eccbbdf3bc1fe7b1e55c93fd.tar.gz

### What's the output of `git remote get-url origin; git rev-parse master; git rev-parse HEAD` ?

```text
(private repo)
```

### Have you found anything relevant by searching the web?

* https://github.com/tweag/rules_nixpkgs/pull/263
* [Writing Bazel rules: repository rules - jayconrod.com - Things to watch out for - Understand how repository rules are executed](https://www.jayconrod.com/posts/110/writing-bazel-rules--repository-rules#:~:text=Understand%20how%20repository%20rules%20are%20executed)
* https://github.com/bazelbuild/bazel-gazelle/issues/1175
* https://github.com/bazelbuild/bazel-gazelle/pull/1206
* https://github.com/bazelbuild/rules_nodejs/issues/2620
* https://github.com/bazelbuild/rules_nodejs/pull/2621
* (chain of restarts in log) https://github.com/bazelbuild/rules_docker/issues/2052

**Comment by fmeum** [comment] 2022-08-25 07:47
I briefly started working on this once using [env.getState](https://cs.opensource.google/bazel/bazel/+/8fcac10b57135f115fd001afe226f1c65ce7b244:src/main/java/com/google/devtools/build/skyframe/SkyFunction.java;l=429). 

It essentially comes down to adding some form of continuation support to the Starlark interpreter. Unfortunately, the "Starlark stack" is a mix of custom data structures and the actual Java stack - since Java doesn't have continuations, one would have to maintain additional data structures that record the state of the Java stack for all operations that aren't safe to redo (e.g. that modify local variables).

Since the Starlark interpreter is so important for Bazel's performance, I think the main challenge would be implementing all of this while not regressing performance for the case of non-reentrant evaluation (see https://github.com/bazelbuild/bazel/pull/15594 for a much smaller PR that already raised valid performance concerns). I fear that this might not be possible, which would then make a reentrant fork of the Starlark interpreter necessary that would only be used to evaluate repository rules.

That said, if anybody wants to work on this, let me know. But it's possible that an actual compiled representation for Starlark would make this effort a lot simpler.

**Comment by Wyverald** [comment] 2022-08-25 10:09
As @fmeum noted, this is actually not very easy to achieve at all, not without changes to the Starlark interpreter that allows us to store (and restart from) a call stack and a program counter. Either that, or something like `yield` in Java would work, but that's not likely to be available until 2023.

**Comment by fmeum** [comment] 2023-09-05 17:37
This is a dupe of https://github.com/bazelbuild/bazel/issues/10515, which is actively being worked on.

**Comment by Silic0nS0ldier** [comment] 2023-09-11 01:34
Clever approach taken in https://github.com/bazelbuild/bazel/commit/1590dbc4be2ce262ee9348e12cdb44c3b6ee0544. I'll keep this open for the moment since its been noted that the thread pool cap of [100](https://github.com/bazelbuild/bazel/commit/1590dbc4be2ce262ee9348e12cdb44c3b6ee0544#diff-b71ad69620096e04eff1317c90d3b0268d0508bd057527f1dbf22583bc267fa4R159) (plus OS threading limits, which `virtual` will probably address once implemented) can be a problem vs. the existing restart-prone implementation.

**Comment by Wyverald** [comment] 2024-01-17 22:43
Closing in favor of #10515.

**Closed by Wyverald** 2024-01-17 22:43 UTC
Labels: type: feature request, P4, team-ExternalDeps
