### ISSUE TITLE
linux-sandbox-pid1.cc:398: remount: Operation not permitted

### ISSUE THREAD

**Issue by sevagh** [bazelbuild/bazel#2285] opened 2016-12-22 18:04 UTC
### Description of the problem / feature request / question

I downloaded Bazel through the custom apt source (I'm on Ubuntu 16.04).

I get a "remount: Operation not permitted" when running `bazel build`.

```
src/main/tools/linux-sandbox-pid1.cc:398: "remount(NULL, /home/sevag/.cache/bazel/_bazel_sevag/0fba5ca567a0db762d7872dcf5607063/bazel-sandbox/88d96bf0-1225-43bf-b147-9dfad57b7d76-0/tmp/proc/sys/fs/binfmt_misc, NULL, 2101281, NULL)": Operation not permitted
```

### If possible, provide a minimal example to reproduce the problem:

```
sevag@sevag-ThinkPad-T460s:~/scratch/scratch$ tree
.
├── BUILD
├── hello.c
└── WORKSPACE

0 directories, 3 files
sevag@sevag-ThinkPad-T460s:~/scratch/scratch$ cat BUILD 
package(default_visibility = ["//visibility:public"])

cc_binary(
    name = "hello",
    srcs = ["hello.c"],
)

filegroup(
    name = "srcs",
    srcs = glob(["**"]),
)
sevag@sevag-ThinkPad-T460s:~/scratch/scratch$ cat hello.c 
#include <stdio>

int main(int argc, char **argv)
{
    printf("Hello\n");
    return 0;
}
sevag@sevag-ThinkPad-T460s:~/scratch/scratch$ cat WORKSPACE 
workspace(name = "my_example")
sevag@sevag-ThinkPad-T460s:~/scratch/scratch$ 
sevag@sevag-ThinkPad-T460s:~/scratch/scratch$ 
sevag@sevag-ThinkPad-T460s:~/scratch/scratch$ bazel build hello                             
INFO: Found 1 target...
ERROR: /home/sevag/scratch/scratch/BUILD:3:1: C++ compilation of rule '//:hello' failed: linux-sandbox failed: error executing command /home/sevag/.cache/bazel/_bazel_sevag/a6fdb4358711e1e33d0afe1cab550490/execroot/scratch/_bin/linux-sandbox ... (remaining 37 argument(s) skipped).
src/main/tools/linux-sandbox-pid1.cc:398: "remount(NULL, /home/sevag/.cache/bazel/_bazel_sevag/a6fdb4358711e1e33d0afe1cab550490/bazel-sandbox/e0fe1e69-9dc9-4088-b6e9-584cb3553529-0/tmp/proc/sys/fs/binfmt_misc, NULL, 2101281, NULL)": Operation not permitted
Target //:hello failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 0.302s, Critical Path: 0.06s
sevag@sevag-ThinkPad-T460s:~/scratch/scratch$ 
```

### Environment info
* Operating System:
```
$ uname -r
4.4.0-57-generic
sevag@sevag-ThinkPad-T460s:~/repos/personal/pitch-detection$ cat /etc/issue
Ubuntu 16.04.1 LTS \n \l
```
Also, this is a native Linux installation on a laptop (i.e. not a container or VM or anything).

* Bazel version (output of `bazel info release`):

`release 0.4.2`

* If `bazel info release` returns "development version" or "(@non-git)", please tell us what source tree you compiled Bazel from; git commit hash is appreciated (`git rev-parse HEAD`):

###  Have you found anything relevant by searching the web? (e.g. GitHub issues, email threads in the [bazel-discuss@googlegroups.com](https://groups.google.com/forum/#!forum/bazel-discuss) archive)

https://github.com/bazelbuild/bazel/issues/1972

**Comment by aehlig** [comment] 2016-12-23 10:16
Unfortunately I cannot reproduce the issue myself; assigning to @philwo who knows best about our sandboxes.

**Comment by sevagh** [comment] 2016-12-23 15:03
Thanks. If you need any extra information let me know.

**Comment by philwo** [comment] 2017-02-01 15:55
Thanks for reporting! I've prepared a fix for this issue. It should be pushed tomorrow and the bug automatically updated with a reference to the commit. :)

**Closed** 2017-02-02 17:01 UTC
Labels: category: sandboxing
