### ISSUE TITLE
Bitcode flag overwritten

### ISSUE THREAD

**Issue by juanctecdam** [bazelbuild/bazel#10374] opened 2019-12-05 17:42 UTC
Hi all,

I'm trying to build a library(hand tracking from MediaPipe of Google) and for some reason, even with the flag of Bitcode set to yes, I keep getting this error:
myLibrary.a does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. for architecture arm64

What can I do to solve it?

Thanks

**Comment by keith** [comment] 2019-12-05 17:47
Issue was also filed and being discussed here https://github.com/bazelbuild/rules_apple/issues/667

**Comment by allevato** [comment] 2019-12-11 18:47
We (rules_apple owners) asked for this issue to be opened here because Bitcode is handled by the native Bazel code in the `objc_library` compilation rules, not by rules_apple. I'll reopen this one and close the rules_apple issue.

**Comment by keith** [comment] 2019-12-11 19:13
Can you provide a repro case here? As long as you pass --apple_bitcode=embedded and build for device this should work. We're using this in production

**Comment by rupertks** [comment] 2019-12-20 21:30
Assigning to schumy@ for more info

**Comment by juanapp** [comment] 2019-12-21 09:50
This is the error I'm getting
`Linking of rule '//mediapipe/examples/ios/handtrackinggpu:HandTrackingGpuApp.__internal__.apple_binary' failed (Exit 1) wrapped_clang_pp failed: error executing command external/local_config_cc/wrapped_clang_pp '-stdlib=libc++' '-std=gnu++11' -arch arm64 -Xlinker -objc_abi_version -Xlinker 2 -fobjc-link-runtime -ObjC -framework CoreVideo -framework Metal -framework ... (remaining 238 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
ld: 'bazel-out/ios-arm64-min10.0-applebin_ios-ios_arm64-fastbuild/bin/mediapipe/calculators/core/libflow_limiter_calculator.lo(flow_limiter_calculator_d3b48dde6b856b9c5951f8d95e48c80d.o)' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. file 'bazel-out/ios-arm64-min10.0-applebin_ios-ios_arm64-fastbuild/bin/mediapipe/calculators/core/libflow_limiter_calculator.lo'
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
Target //mediapipe/examples/ios/handtrackinggpu:HandTrackingGpuApp failed to build
`

And I just execute it like:
`bazel build --config=ios_arm64 --apple_bitcode=embedded mediapipe/examples/ios/handtrackinggpu:HandTrackingGpuApp`

**Comment by rupertks** [comment] 2020-01-02 16:58
Thanks for the repro! We will investigate

**Comment by cpsauer** [comment] 2020-02-11 08:24
@rupertks, I think I've got a good guess as to what the problem is here.

I was just doing some tests, and it seems like `--apple_bitcode=embedded` doesn't apply correctly to the cc_libraries being compiled inside an apple/objc/ios binary. 

In my test case, when I pass both `--copt=-fembed-bitcode` `--apple_bitcode=embedded`, everything gets compiled with bitcode embedded and the linking works. The thing that tipped me off was that the object files the linker flagged as missing bitcode were all cc_libraries. Can't share my test easily bc it's deep in my codebase, but I'd bet you could roll one really fast with an apple_binary that depends on a cc_library. Mine's actually an ios_framework, but I bet it'll work with apple_binary.

**Comment by cpsauer** [comment] 2021-04-26 00:49
I think this has now been fixed (though not released) as part of https://github.com/bazelbuild/bazel/issues/12063

**Comment by sgowroji** [comment] 2022-05-27 06:42
Hello @juanctecdam, Above issue fix is already submitted, So we are closing this now.  Feel free to reopen if you are able to reproduce in the latest version.

**Closed by sgowroji** 2022-05-27 06:42 UTC
Labels: type: bug, P4, team-Rules-CPP
