### ISSUE TITLE
using androidx.work libraries causes manifest merge issue and java.lang.NoSuchMethodError

### ISSUE THREAD

**Issue by sunyal** [bazelbuild/bazel#6645] opened 2018-11-09 17:37 UTC
### Description of the problem / feature request:

Using the androidx.work libraries throws an exception during the merging of the manifest step.

```
Exception in thread "main" java.lang.NoSuchMethodError: com.google.common.base.Objects.firstNonNull(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
	at com.android.ide.common.res2.MergingException$Builder.build(MergingException.java:129)
	at com.android.manifmerger.XmlElement.<init>(XmlElement.java:140)
	at com.android.manifmerger.XmlDocument.getRootNode(XmlDocument.java:231)
	at com.android.manifmerger.ManifestMerger2.load(ManifestMerger2.java:482)
	at com.android.manifmerger.ManifestMerger2.merge(ManifestMerger2.java:130)
	at com.android.manifmerger.ManifestMerger2.access$1100(ManifestMerger2.java:58)
	at com.android.manifmerger.ManifestMerger2$Invoker.merge(ManifestMerger2.java:1163)
	at com.google.devtools.build.android.AndroidManifestProcessor.mergeManifest(AndroidManifestProcessor.java:181)
	at com.google.devtools.build.android.ManifestMergerAction.main(ManifestMergerAction.java:215)
	at com.google.devtools.build.android.ResourceProcessorBusyBox$Tool$11.call(ResourceProcessorBusyBox.java:126)
	at com.google.devtools.build.android.ResourceProcessorBusyBox.processRequest(ResourceProcessorBusyBox.java:234)
	at com.google.devtools.build.android.ResourceProcessorBusyBox.main(ResourceProcessorBusyBox.java:197)
Target //android:android failed to build
```

### Feature requests: what underlying problem are you trying to solve with this feature?

The androidx.work libraries have an AndroidManifest.xml that includes the `tools:targetApi="n"` defined and this seems to be the issue that is causing the exception.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Pull this branch and build it https://github.com/sunyal/bazel/tree/targetapi-bug

### What operating system are you running Bazel on?

Mac OSX

### What's the output of `bazel info release`?

release 0.18.1-homebrew

**Comment by jin** [comment] 2018-11-12 19:04
@sunyal What is the artifact ID of the affected AAR? I can't find androidx.work on Google Maven. The repro example also doesn't seem to have any BUILD files for repro.

**Comment by jin** [comment] 2018-11-12 19:19
I'm not able to reproduce this error with the following layout XML with `tools:targetApi="n"`

```
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    tools:targetApi="n"
    android:padding="16dp"
    android:orientation="vertical"
    android:gravity="center_vertical"
    android:layout_width="match_parent"
    android:layout_height="match_parent">

</LinearLayout>
```

**Comment by sunyal** [comment] 2018-11-13 14:31
The artifact is 'android.arch.work:work-runtime:1.0.0-alpha08'

**Comment by jin** [comment] 2018-11-13 14:58
@sunyal Thank you -- successfully reproduced with https://github.com/jin/repro/tree/master/6645

Looking into this now.

**Comment by jin** [comment] 2018-11-13 22:34
So there are two issues here:

1) Bazel is not propagating the correct error message from the wrapped exception.

I reproduced this with Blaze, and it prints this additional message:

```
java.lang.RuntimeException: <redacted>: Error: Invalid instruction 'targetApi', valid instructions are : REMOVE,REPLACE,STRICT
	at com.android.manifmerger.XmlElement.<init>(XmlElement.java:142)
	at com.android.manifmerger.XmlElement.initMergeableChildren(XmlElement.java:870)
	at com.android.manifmerger.XmlElement.<init>(XmlElement.java:170)
	at com.android.manifmerger.XmlElement.initMergeableChildren(XmlElement.java:870)
	at com.android.manifmerger.XmlElement.<init>(XmlElement.java:170)
	at com.android.manifmerger.XmlDocument.getRootNode(XmlDocument.java:230)
	at com.android.manifmerger.ManifestMerger2.load(ManifestMerger2.java:480)
	at com.android.manifmerger.ManifestMerger2.merge(ManifestMerger2.java:127)
	at com.android.manifmerger.ManifestMerger2.access$1100(ManifestMerger2.java:56)
	at com.android.manifmerger.ManifestMerger2$Invoker.merge(ManifestMerger2.java:1171)
	at com.google.devtools.build.android.AndroidManifestProcessor.mergeManifest(AndroidManifestProcessor.java:181)
	at com.google.devtools.build.android.ManifestMergerAction.main(ManifestMergerAction.java:215)
	at com.google.devtools.build.android.ResourceProcessorBusyBox$Tool$11.call(ResourceProcessorBusyBox.java:126)
	at com.google.devtools.build.android.ResourceProcessorBusyBox.processRequest(ResourceProcessorBusyBox.java:240)
	at com.google.devtools.build.android.ResourceProcessorBusyBox.main(ResourceProcessorBusyBox.java:203)
Caused by: <redacted>: Error: Invalid instruction 'targetApi', valid instructions are : REMOVE,REPLACE,STRICT
	at com.android.ide.common.res2.MergingException$Builder.build(MergingException.java:134)
	... 15 more
Caused by: java.lang.IllegalArgumentException: No enum constant com.android.manifmerger.AttributeOperationType.TARGETAPI
	at java.base/java.lang.Enum.valueOf(Enum.java:240)
	at com.android.manifmerger.AttributeOperationType.valueOf(AttributeOperationType.java:54)
	at com.android.manifmerger.XmlElement.<init>(XmlElement.java:124)
```
The Bazel crash does not print the additional line: `Error: Invalid instruction 'targetApi', valid instructions are : REMOVE,REPLACE,STRICT`. Opened https://github.com/bazelbuild/bazel/issues/6671 to track this.

2) The manifest merger library Bazel uses does not understand `tools:targetApi`.

Bazel uses the same manifest merger library as Gradle, which is from [here](https://android.googlesource.com/platform/tools/base/+/master/build-system/manifest-merger/src/main/java/com/android/manifmerger?switch-account=gaia).

The error message `Error: Invalid instruction 'targetApi', valid instructions are : REMOVE,REPLACE,STRICT` comes from [this line in XmlElement.java](https://android.googlesource.com/platform/tools/base/+/master/build-system/manifest-merger/src/main/java/com/android/manifmerger/XmlElement.java#122).

In particular, the manifest merger threw an exception while trying to convert `targetApi` to an [`OtherOperationType` enum](https://android.googlesource.com/platform/tools/base/+/master/build-system/manifest-merger/src/main/java/com/android/manifmerger/OtherOperationType.java).

```java
try {
  // is this another tool's operation type that we do not care about.
  OtherOperationType.valueOf(instruction);
  break;
}
```

Which consists of:

```java

public enum OtherOperationType {
--  
  // used to direct lint
  ignore,
    
  // used to direct lint
  targetAPI
}
```

`targetApi` != `targetAPI`, thus causing the exception. However, official docs show that the right capitalization is `targetApi` and not `targetAPI`, so there's an inconsistency here between Lint and AOSP manifest merger. It may be that the manifest merger didn't catch up the changes in Lint.

I think we may be able to patch our manifest merger jar's `OtherOperationType` to accept `targetApi`. @ahumesky WDYT?

**Comment by ahumesky** [comment] 2018-11-13 22:42
is the targetAPI vs targetApi just a mistake in the documentation, or is the correct capitalization consistent in later versions of the merger and lint? if the correct capitalization from later versions of lint and the merger is "targetApi" then we can consider patching

**Comment by jin** [comment] 2018-11-13 22:49
All of the usages I've found are capitalized as `targetApi`. They are also all used in resource XMLs and not the Android manifest. The `targetApi` usage in the androidx.work library is the only occurrence of it being used in the Android manifest, so this leads me to think that this is an incorrect usage of the attribute, and that the crash is WAI (although it should print more information).

**Comment by jin** [comment] 2018-11-13 22:51
@sunyal as a workaround, could you use `android.arch.work:work-runtime:1.0.0-alpha07` instead of `alpha08` for the time being? That revision compiles successfully for now.

**Comment by jin** [comment] 2018-11-13 22:54
This issue has been filed in https://b.corp.google.com/issues/114358542, so it looks like an upstream fix. Downgrading this to P2 as it looks like a inconsistency bug between AOSP and AndroidX.

**Comment by jin** [comment] 2018-11-14 23:11
According to the issue tracker, it looks like the fix is planned for WorkManager Alpha 12.

**Comment by sunyal** [comment] 2018-11-15 16:06
Great, will keep an eye out for that release

**Comment by jin** [comment] 2018-12-20 17:42
The fix is in 59327306bf7bb6ecc28d8b52c8bbf343361293bf

ETA Bazel 0.22

**Closed by jin** 2018-12-20 17:42 UTC
Labels: P2, team-Android, type: bug

**Comment by artem-zinnatullin** [comment] 2019-01-07 21:50
Hi @jin, 

We're hitting dead ends on this issue in google tracker https://issuetracker.google.com/issues/114358542#comment7

As your linked fix shows, it seems that the fix needs to be applied in upstream manifestmerger and new version needs to be uploaded to maven.google.com so other build systems/tools could use it too

Can we notify someone from manifestmerger teams so they accept your patch and release it to upstream?

Thanks

**Comment by jin** [comment] 2019-01-07 22:01
It's actually patched upstream by Tor here:

https://android.googlesource.com/platform/tools/base/+/5c6d992f405b0d83f3c10e4d5f6d961bef50221c%5E%21/build-system/manifest-merger/src/main/java/com/android/manifmerger

Have you confirmed that this patch is not in the latest manifmerger versions?

The reason why we manually patched it in Bazel is because we cannot upgrade the entire manifmerger jar as-is, or it'll break a ton of stuff within Google. It's a simpler workaround for this particular issue.
