### ISSUE TITLE
0.22.0 FTBFS: C++ compilation of rule '//src/tools/singlejar:output_jar'

### ISSUE THREAD

**Issue by vbatts** [bazelbuild/bazel#7296] opened 2019-01-29 22:44 UTC
### Description of the problem / feature request:

Build of 0.22.0 on Fedora rawhide

`/builddir/build/BUILD/bazel-0.22.0/src/tools/singlejar/BUILD:390:1: C++ compilation of rule '//src/tools/singlejar:output_jar' failed (Exit 1): gcc failed: error executing command`

Found about 95% toward the end of https://copr-be.cloud.fedoraproject.org/results/vbatts/bazel/fedora-rawhide-x86_64/00851673-bazel/build.log.gz

(It succeed on fedora 28, 29 and centos 7 https://copr.fedorainfracloud.org/coprs/vbatts/bazel/build/851673/)

### What operating system are you running Bazel on?

Fedora rawhide build root. (you can try the `fedora:rawhide` container)

### What's the output of `bazel info release`?

> Replace this line with your answer.

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

> Replace this line with your answer.

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

the 0.22.0 git tag

###  Have you found anything relevant by searching the web?

> Replace these lines with your answer.
>
> Places to look:
> - StackOverflow: http://stackoverflow.com/questions/tagged/bazel
> - GitHub issues: https://github.com/bazelbuild/bazel/issues
> - email threads on https://groups.google.com/forum/#!forum/bazel-discuss

### Any other information, logs, or outputs that you want to share?

Build spec: https://github.com/vbatts/copr-build-bazel
Log showing installed package versions: https://copr-be.cloud.fedoraproject.org/results/vbatts/bazel/fedora-rawhide-x86_64/00851673-bazel/root.log.gz

**Comment by rongjiecomputer** [comment] 2019-01-30 14:00
From the build log:

```
[1Asrc/tools/singlejar/output_jar.cc: In member function 'bool OutputJar::AddJar(int)':
BUILDSTDERR: 
[1A
[1A
[1Asrc/tools/singlejar/output_jar.cc: In member function 'bool OutputJar::AddJar(int)':
BUILDSTDERR: src/tools/singlejar/output_jar.cc:347:46: warning: converting a packed 'const LH*' pointer (alignment 1) to 'const LH*' (alignment 8) may result in an unaligned pointer value [-Waddress-of-packed-member]
BUILDSTDERR: src/tools/singlejar/output_jar.cc:347:46: warning: converting a packed 'const LH*' pointer (alignment 1) to 'const LH*' (alignment 8) may result in an unaligned pointer value [-Waddress-of-packed-member]
BUILDSTDERR:   347 |   while ((jar_entry = input_jar.NextEntry(&lh))) {
BUILDSTDERR:   347 |   while ((jar_entry = input_jar.NextEntry(&lh))) {
BUILDSTDERR:       |                                              ^
BUILDSTDERR:       |                                              ^
BUILDSTDERR: src/tools/singlejar/output_jar.cc:347:46: internal compiler error: Segmentation fault
BUILDSTDERR: src/tools/singlejar/output_jar.cc:347:46: internal compiler error: Segmentation fault
BUILDSTDERR: Please submit a full bug report,
BUILDSTDERR: Please submit a full bug report,
BUILDSTDERR: with preprocessed source if appropriate.
BUILDSTDERR: with preprocessed source if appropriate.
BUILDSTDERR: See <http://bugzilla.redhat.com/bugzilla> for instructions.
BUILDSTDERR: See <http://bugzilla.redhat.com/bugzilla> for instructions.
BUILDSTDERR: Preprocessed source stored into /tmp/ccXUqiMU.out file, please attach this to your bugreport.
BUILDSTDERR: Preprocessed source stored into /tmp/ccXUqiMU.out file, please attach this to your bugreport.
```

It seems like the issue is caused by the version of GCC you are using rather than Bazel itself.

**Comment by vbatts** [comment] 2019-01-30 14:33
Ah, so gcc 9.0.0-0.3.fc30

**Comment by scentini** [comment] 2019-02-04 12:19
Closing this as it seems to be unrelated to Bazel, please reopen if you disagree.

**Closed by scentini** 2019-02-04 12:19 UTC
Labels: team-Rules-CPP, type: bug, untriaged
