### ISSUE TITLE
Remote Executor Not Respecting Test Timeout

### ISSUE THREAD

**Issue by cjohnstoniv** [bazelbuild/bazel#16467] opened 2022-10-13 14:53 UTC
### Description of the bug:

When running Bazel (5.3.1, observed in previous versions as well) with a remote **executor** it seems that the "test timeout" functionality of Bazel isn't properly working.

When running with remote **cache** a test that takes greater than the allotted max time based on its size DOES take effect and these tests clearly fail with timeouts.

However when running with remote **executor** a test that takes longer than the timeout is not timing out at that point and continues to run for way longer.

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Run any test with a remote executor that takes longer than the max allowed time.

### Which operating system are you running Bazel on?

Mac,Windows,RH Linux (RHEL)

### What is the output of `bazel info release`?

release 5.3.1

### Have you found anything relevant by searching the web?

Tried searching, but was unable to find any existing cases mentioning this.

**Comment by coeuvre** [comment] 2022-10-14 08:54
Can you provide a minimal repro? might be duplicate of #12349.

**Comment by coeuvre** [comment] 2022-10-18 09:17
Closing. Feel free to reopen it if you think it's not a duplicate.

**Closed by coeuvre** 2022-10-18 09:17 UTC
Labels: type: bug, untriaged, team-Remote-Exec, awaiting-user-response

**Comment by celestialorb** [comment] 2023-09-12 19:40
I'm experiencing this as well. When running a Bazel test with `test_timeout` specified and using a remote executor I'm seeing individual tests run way past the `test_timeout` specified for all tests in that run.
