### ISSUE TITLE
Could not create symlink to repository, being used by another process

### ISSUE THREAD

**Issue by sgreenstein** [bazelbuild/bazel#5433] opened 2018-06-19 20:59 UTC
### Description of the problem / feature request:

Error message (one for every reference to @grpc):

 ```
ERROR: T:/src/path/BUILD:463:1: no such package '@grpc//':
  Could not create symlink to repository T:/src/third_party/grpc:
  Cannot create junction 
    (name=C:\users\builder\_bazel_kbuilder\c74viekg\external\grpc, 
    target=T:\src\third_party\grpc):
ERROR: src/main/native/windows/file-jni.cc(86):
    nativeCreateJunction(C:\users\builder\_bazel_kbuilder\c74viekg\external\grpc,
    T:\src\third_party\grpc):
ERROR: src/main/native/windows/file.cc(135):
    OpenDirectory(\\?C:\users\builder\_bazel_kbuilder\c74viekg\external\grpc):
      The process cannot access the file because it is being used by another process.
and referenced by '//path/some:target'
```

The same error also happens with other local_repository rules

WORKSPACE:

```
local_repository(
    name = "grpc",
    path = "third_party/grpc",
)
```

Note that in our build we do `bazel build` followed by `bazel test`, and a workaround that seems to be effective is using --batch.

### What operating system are you running Bazel on?

Windows 10

### What's the output of `bazel info release`?

0.14.0

###  Have you found anything relevant by searching the web?

#4508, but renaming our top-level "external" directory to "externals" did not fix the problem.

**Comment by sgreenstein** [comment] 2018-06-20 00:29
Using --batch didn't fix the issue after all

**Comment by jasharpe** [comment] 2018-06-22 18:33
We've encountered a very similar issue occasionally (it disappears randomly):

```
ERROR: error loading package '': Encountered error while reading extension file 'tools/cpp/cc_configure.bzl': no such package '@bazel_tools//tools/cpp':
Could not create symlink to repository C:/users/builder/_bazel_kbuilder/install/f911adec14ee69dc788922e4162d14f1/_embedded_binaries/embedded_tools:
Cannot create junction (name=C:\users\builder\_bazel_kbuilder\2ts5b4ke\external\bazel_tools, target=C:\users\builder\_bazel_kbuilder\install\f911adec14ee69dc788922e4162d14f1\_embedded_binaries\embedded_tools):
ERROR: src/main/native/windows/file-jni.cc(86): nativeCreateJunction(C:\users\builder\_bazel_kbuilder\2ts5b4ke\external\bazel_tools, C:\users\builder\_bazel_kbuilder\install\f911adec14ee69dc788922e4162d14f1\_embedded_binaries\embedded_tools):
ERROR: src/main/native/windows/file.cc(135): OpenDirectory(\\?\C:\users\builder\_bazel_kbuilder\2ts5b4ke\external\bazel_tools):
The process cannot access the file because it is being used by another process.
```

In our case it's a version of Bazel built from source at a320e4460f35767da7fc8eb824ce1f4b304b5e0f

We're just building a simple hello world C++ program:

```
#include <iostream>

int main(int argc, char** argv) {
  std::cout << "Hello, world!" << std::endl;
  std::cerr << "Howdy!" << std::endl;
  return 0;
}
```

BUILD:

```
cc_binary(
    name = "hello-world",
    srcs = ["hello-world.cc"],
)
```

**Comment by laszlocsomor** [comment] 2018-07-09 11:50
Though I could not repro the issue, I hope https://github.com/bazelbuild/bazel/commit/c2b70f1e28b8fbc002efbac16d555f941c7d59a3 fixes it.

If you see it again, please reopen.

**Comment by laszlocsomor** [comment] 2018-07-13 08:11
Unfortunately this is still not fixed. An internal team still reports similar errors from their CI.

**Comment by ozio85** [comment] 2021-04-13 19:00
Hmm. We see error quite frequently also in Bazel 4.0.0

**Comment by laszlocsomor** [comment] 2021-04-14 06:17
Unassigning, since I no longer actively work on Bazel.
/cc @meisterT

**Comment by meteorcloudy** [comment] 2021-04-14 07:31
@ozio85 Sounds like you are experiencing a different problem that this one, can you please fill another issue with some reproducing steps if possible? I'll close this one since the original issue was resolved.

**Closed by meteorcloudy** 2021-04-14 07:31 UTC
Labels: platform: windows
