### ISSUE TITLE
Build Encyclopedia should be versioned

### ISSUE THREAD

**Issue by cgrushko** [bazelbuild/bazel#3537] opened 2017-08-10 18:00 UTC
1. There's some evidence of the BE being updated from head, which is problematic for obvious reasons.
2. Not everyone can upgrade to the latest Bazel release the moment it's released. It's important to support customers who need access to previous BEs.

**Comment by davidzchen** [comment] 2017-08-22 20:09
Duplicate of #579

**Closed by davidzchen** 2017-08-22 20:09 UTC
Labels: bazel.build, P2, type: documentation
