### ISSUE TITLE
cc_binary(linkstatic=1) doesn't work in macOS Sierra

### ISSUE THREAD

**Issue by iainmerrick** [bazelbuild/bazel#2055] opened 2016-11-07 22:34 UTC
This code should fail to link, but it links happily with Bazel, even with linkstatic=1:

```
extern void missing_function();

int main(int argc, const char* argv[])
{
    if (argc > 1) {
        missing_function();
    }
    return 0;
}
```

I'm using macOS Sierra (10.12.1)

Compiling manually (`clang foo.c -o foo`) correctly fails with the expected link error.

Here's the full repro case: https://github.com/iainmerrick/bazel-playground/commit/fe4f447452af9308eb9631143245d662d9e46778

**Comment by mhlopko** [comment] 2016-11-08 11:36
Hi Iain, thanks for the report. I'll look into it tomorrow (left my mac at home today).

Cheers!

**Comment by mhlopko** [comment] 2016-11-11 14:18
So the answer is that we add -undefined dynamic_lookup flag to the link command line on osx here:
[cc_configure.bzl#L229](https://github.com/bazelbuild/bazel/blob/master/tools/cpp/cc_configure.bzl#L229). You can observe it yourself by using -s flag to show all the commands executed by bazel. If you need to customize the command line for C/C++ compilation, you have to provide your own crosstool file. Closing this issue as this is working as intended. Thank you for the report and a repro repo!

**Closed** 2016-11-11 14:18 UTC

**Comment by iainmerrick** [comment] 2016-11-11 16:01
Wow! But why is it intended? It seems like very strange default behaviour for C and C++ code.

**Comment by mhlopko** [comment] 2016-11-15 10:28
You can see the test for this behaviour [here](https://github.com/bazelbuild/bazel/blob/master/src/test/shell/bazel/bazel_rules_test.sh#L162). Roughly speaking, it makes osx linker to behave more like a linux linker. Bazel was built with certain assumptions and linux linker behavior was one of them. We will probably clean this up eventually, especially since we are working on improving our windows story, but not in the short run.

**Comment by iainmerrick** [comment] 2016-11-15 13:36
I see, so this is a side-effect of a Mac-specific workaround for a different bug.

This is very weird and unusual behaviour, and could itself lead to bugs in users' code -- it turns link-time errors into delayed runtime errors, so unless you have 100% test coverage you can't be sure your code will even run.

Would you mind reopening this issues? I can take a crack at fixing it.

**Comment by mhlopko** [comment] 2016-11-16 17:38
Hi Iain,

Thanks for the interest and good questions :) I'm learning a lot while looking for answers :)

So it does lead to errors, similarly to like dlopen leads to errors on linux. I don't think it causes much pain in the world, but I agree we should improve here. The right solution would be to provide all transitive dependencies on clang command line. But I still need to do more investigations so stay tuned :) Thanks again!

**Comment by iainmerrick** [comment] 2016-11-16 18:06
Exactly, it's equivalent to using dlopen the first time each function from another shared library is called.

I'm not sure how much pain it causes other developers, but it's certainly awkward for me! I rely on C++ catching errors at compile time rather than runtime, that's why I'm using C++ and not Python. :)

I imagine there's also a performance hit, which again is something C++ users in particular would want to avoid. I haven't measured this though. It may not be significantly different from normal shared library calls.

However, note that a cc_binary with linkstatic=1 would work just fine without the "-undefined dynamic_lookup" flag. With the flag, it works but you get the weird lazy-inking behavior. So it seems like there's an unnecessary performance hit for static binaries too (which I'm guessing is likely to be a common use case).

> The right solution would be to provide all transitive dependencies on clang command line.

Yep, I agree! I've been digging around the code trying to figure out how to do that, without success so far. :)

I was able to fix the command line for `cc_binary` targets by removing the special case for `CppFileTypes.SHARED_LIBRARY` at the end of `CppLinkActionBuilder.CppLinkVariablesExtension.addDynamicInputLinkOptions` (CppLinkActionBuilder.java, line 1570). But I can't figure out where the equivalent thing happens for `cc_library`.

**Comment by fbriggs** [comment] 2017-12-04 21:07
bazel 0.8.0 introduced an issue which breaks dynamic linking of the GLFW library on os x:
https://github.com/bazelbuild/bazel/issues/4211#issuecomment-349053506

I was hoping that static linking GLFW would be a workaround for that, but based on the discussion above, it seems that static linking on os x doesn't work with bazel (I get the lazy linking behavior).

so basically now the situation is:
1) static linking doesn't work on os x
2) as of bazel 0.8.0 dynamic linking doesn't work on os x for the glfw library
