### ISSUE TITLE
rules_python is broken with Bazel@HEAD

### ISSUE THREAD

**Issue by sgowroji** [bazelbuild/bazel#18170] opened 2023-04-21 10:44 UTC
https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/2972#0187a200-864b-46a7-987d-75766ba7fe83

```
ERROR: /Users/sgowroji/bazelci/bazelhead_downstream/rules_python/rules_python/docs/BUILD.bazel:36:12: no such target '@bazel_tools//tools/python:private/defs.bzl': target 'private/defs.bzl' not declared in package 'tools/python' defined by /private/var/tmp/_bazel_sgowroji/a5aaba8bdde99d8862842eaaed117753/external/bazel_tools/tools/python/BUILD (Tip: use `query "@bazel_tools//tools/python:*"` to see all the targets in that package) and referenced by '//docs:bazel_python_tools'
ERROR: Analysis of target '//docs:pip_install_bzl' failed; build aborted: 
INFO: Elapsed time: 0.666s
INFO: 0 processes.
ERROR: Build did NOT complete successfully
```

Steps followed to reproduce :

1. git clone -v https://github.com/bazelbuild/rules_python.git
2. git reset c72c7bcf4e0899c275042328e8233e3124ccae86 --hard
3. export USE_BAZEL_VERSION=d3ebbb7495e65747ac5f512c67a790e9dec12373
4.  bazel build ...

Culprit : https://github.com/bazelbuild/bazel/commit/18955851947002ea39854b5d2aa3e6fa81ef8bf3

CC @meteorcloudy

**Comment by rickeylev** [comment] 2023-04-24 16:26
I'm skeptical that https://github.com/bazelbuild/bazel/commit/18955851947002ea39854b5d2aa3e6fa81ef8bf3 is the actual cause. I suspect https://github.com/bazelbuild/bazel/pull/17545 is more likely the cause (it removed the `@bazel_tools//tools/python:private/defs.bzl` file that the error complains about).

This sounds like a dupe of #17874, too, but it's not clear.

On the rules_python side, bazelbuild/rules_python#1173 removed the reference to that removed file.

**Comment by meteorcloudy** [comment] 2023-04-24 16:31
SG, let's check if the downstream turns green for python tomorrow

**Comment by meteorcloudy** [comment] 2023-04-25 09:31
rules_python still fails in downstream: 
https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/2980#0187b697-43a4-4b00-9a8c-c3fb91364cbf

Looks like there are more places to fix:
https://github.com/bazelbuild/rules_python/blob/main/BUILD.bazel#L54-L59

**Comment by rickeylev** [comment] 2023-04-26 03:36
Ok, fixing that error revealed another. Both are fixed at rules_python head now. I ran all the rules_python tests with a build from head and it looked ok (I think; there were failures, but they also happen with non-bazel head, so I think my invocation just wasn't ignoring something it should have).

Let me know if the next downstream build has rules_python failures again.

**Comment by meteorcloudy** [comment] 2023-04-26 15:40
> Failures in downstream rules_python (latest pipeline ) : https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/2982#0187bb51-ca68-4dae-9701-608fcc7178b1

@sgowroji If you check the rules_python commit in the log, it was still building at ba2a903bc1e608c5847bb0b51fd60709b0a187f3, which is before the fix was submitted 600dbe1d10d7055a3fb0644e0cec5badbd5dd240

**Comment by meteorcloudy** [comment] 2023-04-27 12:19
The `@bazel_tools//tools/python:private/defs.bzl` issue has been fixed now. But rules_python is still failing with Bazel@HEAD with
```
(04:22:55) ERROR: /Users/buildkite/builds/bk-imacpro-10/bazel-downstream-projects/rules_python/tools/build_defs/python/tests/py_test/BUILD.bazel:18:19: in test_non_mac_doesnt_require_darwin_for_execution_test rule //tools/build_defs/python/tests/py_test:test_non_mac_doesnt_require_darwin_for_execution:
Traceback (most recent call last):
	File "/private/var/tmp/_bazel_buildkite/8e3e233c9482a5bb2bc225479d1df699/external/rules_testing/lib/analysis_test.bzl", line 191, column 13, in wrapped_impl
		impl(env, target)
	File "/Users/buildkite/builds/bk-imacpro-10/bazel-downstream-projects/rules_python/tools/build_defs/python/tests/py_test/py_test_tests.bzl", line 89, column 28, in _test_non_mac_doesnt_require_darwin_for_execution_impl
		).requirements().keys().not_contains("requires-darwin")
Error: 'struct' value has no field or method 'not_contains'
Available attributes: actual, contains, contains_at_least, contains_at_least_predicates, contains_exactly, contains_exactly_predicates, contains_none_of, contains_predicate, has_size, not_contains_predicate
```
looks like more API changes we need to adapt?

**Comment by meteorcloudy** [comment] 2023-04-27 12:19
@sgowroji Can you file an issue against rules_python and close this one?

**Closed** 2023-04-27 13:38 UTC
Labels: type: bug, P1, breakage, team-Rules-Python

**Comment by rickeylev** [comment] 2023-04-27 23:17
Thanks, I've sent https://github.com/bazelbuild/rules_python/pull/1183 to fix that failure. How it's manifesting is a bit weird, but the bug is indeed on rules_python's side.
