### ISSUE TITLE
non-external files missing from external sandbox on OSX

### ISSUE THREAD

**Issue by bedmondsatgoogle** [bazelbuild/bazel#1738] opened 2016-09-07 17:33 UTC
I have a number of third_party packages which build via new_http_archive rules in my WORKSPACE, but which pull in pre-configured files from third_party to avoid having to run configure. This works on Linux, and worked on OSX before sandboxing, but now fails on current git HEAD builds with sandboxing.

For example, I have in my WORKSPACE:

```
new_http_archive(
    name = "zlib_v1_2_8",
    url = "http://zlib.net/zlib-1.2.8.tar.gz",
    sha256 = "36658cb768a54c1d4dec43c3116c27ed893e88b02ecfcb44f2166f9c0b7f2a0d",
    strip_prefix = "zlib-1.2.8",
    build_file = "//third_party/zlib/v1.2.8:zlib_v1_2_8.BUILD",
)
```

I'll attach the build_file:
[zlib_v1_2_8.BUILD.txt](https://github.com/bazelbuild/bazel/files/459875/zlib_v1_2_8.BUILD.txt)

I've added a couple lines to the copy genrule to list the files in the sandbox before doing the copy, and here is what I see when I attempt to build:

```
ERROR: /Volumes/MacWithCase/_bazel_bedmonds/488838ff2f4df9c43c18592c71f4aab6/external/zlib_v1_2_8/BUILD:16:1: Executing genrule @zlib_v1_2_8//:copy-configured-zconf.h failed: sandbox-exec failed: error executing command 
  (cd /Volumes/MacWithCase/_bazel_bedmonds/488838ff2f4df9c43c18592c71f4aab6/bazel-sandbox/604b1cda-fe16-489e-a189-7233e1388fd0-0/execroot && \
  exec env - \
    PATH=/Users/bedmonds/bin:/usr/local/git/current/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin:/sbin \
    TMPDIR=/var/folders/xh/5xdht73d6w52f1hz7l036s4r0008d3/T/ \
  /usr/bin/sandbox-exec -f /Volumes/MacWithCase/_bazel_bedmonds/488838ff2f4df9c43c18592c71f4aab6/bazel-sandbox/604b1cda-fe16-489e-a189-7233e1388fd0-0/sandbox.sb /bin/bash -c 'source external/bazel_tools/tools/genrule/genrule-setup.sh;  set -x
        ls -lR third_party/zlib/v1.2.8/darwin-x86_64
        ls -lLR third_party/zlib/v1.2.8/darwin-x86_64
        cp "third_party/zlib/v1.2.8/darwin-x86_64/zconf.h" "bazel-out/local-dbg/genfiles/external/zlib_v1_2_8/zconf.h" ').
+ ls -lR third_party/zlib/v1.2.8/darwin-x86_64
total 8
lrwxr-xr-x  1 bedmonds  admin  175 Sep  7 10:25 zconf.h -> /Volumes/MacWithCase/_bazel_bedmonds/488838ff2f4df9c43c18592c71f4aab6/bazel-sandbox/604b1cda-fe16-489e-a189-7233e1388fd0-0/inputs/third_party/zlib/v1.2.8/darwin-x86_64/zconf.h
total 8
+ ls -lLR third_party/zlib/v1.2.8/darwin-x86_64
ls: zconf.h: No such file or directory
```

So, it appears that the sandbox is not being properly populated with the file from @//third_party.

**Comment by kchodorow** [comment] 2016-09-07 19:25
I'm still unable to reproduce. Does third_party/zlib/v1.2.8/darwin-x86_64/zconf.h exist? I'm faking a bunch of the inputs, though, can you put up a simple project with what I'd need to actually run your example (e.g., third_party/zlib, tools, WORKSPACE, BUILD files)?

**Comment by bedmondsatgoogle** [comment] 2016-09-07 20:54
Sure. Here's a little workspace that's just building zlib. It works on Linux (0.3.0), fails on OSX (as of head this morning, and late last week). Might fail on Linux at HEAD too, which I've not tested, but I'll still contend that's a bug. :)

[repro_1738.tar.gz](https://github.com/bazelbuild/bazel/files/460320/repro_1738.tar.gz)

**Comment by susinmotion** [comment] 2020-05-04 18:16
I'm going to close this since it's so old, but please feel free to reopen if it's still an issue, @bedmondsatgoogle .

**Closed by susinmotion** 2020-05-04 18:16 UTC
Labels: team-Local-Exec, under investigation, untriaged
