### ISSUE TITLE
Every few builds, kills server

### ISSUE THREAD

**Issue by abergmeier-dsfishlabs** [bazelbuild/bazel#3097] opened 2017-06-01 13:12 UTC
### Description of the problem / feature request / question:

Every few builds I start, I get the following error message:

    Killed non-responsive server process (pid=23873)

Since Bazel needs half an hour to reread all files, this is SUPER annoying. Is there any way to debug this?

### Environment info
* Operating System: Ubuntu 16.04
* Bazel version (output of `bazel info release`): 0.4.5

###  Have you found anything relevant by searching the web?
All other similar issues are closed.

**Comment by laszlocsomor** [comment] 2017-06-01 13:52
Sorry about that! Yes, you can debug this: check out 6c07525462062d491816a66a94c3db3b2dbc8f98, apply this patch [1] (it adds logging), build bazel, and use that binary. If you see this annoying message again, please paste the log messages here. Thanks!

https://gist.github.com/laszlocsomor/e1bc49e66149318896c69a15f3ee315a

**Comment by abergmeier-dsfishlabs** [comment] 2017-06-01 14:41
Thanks @laszlocsomor for the info. Will first upgrade to 0.5.0 and if it still shows with that version try to produce logs.

**Comment by mhlopko** [comment] 2017-06-26 12:44
Friendly ping, did the upgrade help?

**Comment by mhlopko** [comment] 2017-08-09 08:27
I will assume yes. Feel free to comment and I'll reopen if the issue is still present.

**Comment by abergmeier-dsfishlabs** [comment] 2017-08-09 08:38
Sorry for dropping this. Am on 0.5.3 and I still see it. It _seems_ to be related to (recursive) globbing. We slowly get our globbing minimized and this seems to at least minimize the occurrences.

**Comment by mhlopko** [comment] 2017-08-09 08:48
Hmm I'm wondering what we could do to debug this. Could you maybe try to create a mini repo that fails in some out of 1000 bazel runs? Laszlo, ideas?

**Comment by laszlocsomor** [comment] 2017-08-09 09:39
If creating a repro is too onerous, as I imagine it would be, can you try adding logging to Bazel [1] (based on current head, 3cb136d5), build your own Bazel binary and use that?
If you see the "killed non-responsive server" message again, paste here the log from that run, and also from the previous Bazel run, so I can compare.


[1] https://gist.github.com/laszlocsomor/ff454d2b8babead589b3d21109636ab2

**Comment by laszlocsomor** [comment] 2017-08-17 07:33
@abergmeier-dsfishlabs : did you have a chance to try adding the patch?

**Comment by abergmeier-dsfishlabs** [comment] 2017-08-17 07:34
@laszlocsomor Sorry, still busy with bugs from 0.5.3.

**Comment by mhlopko** [comment] 2017-10-10 15:37
Friendly ping?

**Comment by katre** [comment] 2017-10-31 19:51
Closing this due to the lack of updates. Please re-file the issue if it is still happening.

**Closed by katre** 2017-10-31 19:51 UTC
Labels: On hold: more data needed

**Comment by abergmeier-dsfishlabs** [comment] 2017-11-01 07:36
Sorry about the lack of update. The more we clean up our glob usage, the lesser this happens. So totally right to close this.
