### ISSUE TITLE
Strange test failure without explicitly setting -Dsun.jnu.encoding = UTF-8

### ISSUE THREAD

**Issue by davido** [bazelbuild/bazel#2705] opened 2017-03-18 21:39 UTC
I'm seeing strange junit_test failure, when UTF-8 chars are used in file name:

```
import java.io.File;
import java.nio.file.Path;
import org.junit.Test;
import java.util.Properties;
import java.util.Enumeration;

public class ReproTest {
    @Test
    public void test() {
        Properties p = System.getProperties();
	Enumeration keys = p.keys();
	while (keys.hasMoreElements()) {
	    String key = (String)keys.nextElement();
	    String value = (String)p.get(key);
	    System.out.println(key + ": " + value);
	}
        new File("straße").toPath();
    }
}
```

With this test rule:

```
java_test(
  name = "repro_java_test",
  srcs = [
      "src/main/java/org/mailformed/file/name/ReproTest.java",
      "src/main/java/org/mailformed/file/name/ReproTestSuite.java",
  ],
  test_class = "org.mailformed.file.name.ReproTestSuite",
  jvm_flags = ["-Dfile.encoding=UTF-8"]
)
```

This is failing here with this exception: [1]. Note, the value of `sun.jnu.encoding = ANSI_X3.4-1968`. I don't see that problem if I create `java_binary` with the same code and run it with: `bazel run foo`. I also do not see the problem with Buck or executing the test from Eclipse IDE.

Adding explicitly "-Dsun.jnu.encoding = UTF-8" fixed that:

```
java_test(
    name = "repro_java_test",
    srcs = [
        "src/main/java/org/mailformed/file/name/ReproTest.java",
        "src/main/java/org/mailformed/file/name/ReproTestSuite.java",
    ],
    test_class = "mailformed.file.name.ReproTestSuite",
    jvm_flags = ["-Dfile.encoding=UTF-8", "-Dsun.jnu.encoding=UTF-8"]
)
```

[1] http://paste.openstack.org/show/603285

**Comment by dpursehouse** [comment] 2017-03-19 04:08
@davido what platform are you using?  I'm on OSX and don't get the failure that you mentioned on [the jgit build](https://git.eclipse.org/r/#/c/93346/6).

I have not however tried it with the repro case in this issue.

**Comment by davido** [comment] 2017-03-19 05:47
I'm on Linux:

```
$ uname -a
Linux wizball 4.1.38-50-default #1 SMP PREEMPT Sun Feb 19 14:35:48 UTC 2017 (6b4d8cb) x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by hermione521** [comment] 2017-03-20 11:26
Hmm sorry, I don't think it's supported now. But we are actively working on it.
Duplicate of #2550

**Comment by meisterT** [comment] 2020-05-11 16:37
Closing as dupe of #2550

**Closed by meisterT** 2020-05-11 16:37 UTC
Labels: P3, category: misc > testing, type: bug
