### ISSUE TITLE
Using invalid --remote_cache crashes Bazel

### ISSUE THREAD

**Issue by lfpino** [bazelbuild/bazel#7478] opened 2019-02-20 14:10 UTC
$ bazel version
Starting local Bazel server and connecting to it...
INFO: Invocation ID: 047f5312-a9c5-480a-81e7-315438bdd5a8
Build label: 0.22.0
Build target: bazel-out/k8-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Mon Jan 28 12:58:08 2019 (1548680288)
Build timestamp: 1548680288
Build timestamp as int: 1548680288

$ bazel build --remote_http_cache=foo
Starting local Bazel server and connecting to it...
Internal error thrown during build. Printing stack trace: java.lang.RuntimeException: java.lang.NullPointerException
	at com.google.devtools.build.lib.remote.SimpleBlobStoreFactory.createRest(SimpleBlobStoreFactory.java:56)
	at com.google.devtools.build.lib.remote.SimpleBlobStoreFactory.create(SimpleBlobStoreFactory.java:73)
	at com.google.devtools.build.lib.remote.RemoteModule.beforeCommand(RemoteModule.java:261)
	at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.execExclusively(BlazeCommandDispatcher.java:295)
	at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.exec(BlazeCommandDispatcher.java:205)
	at com.google.devtools.build.lib.server.GrpcServerImpl.executeCommand(GrpcServerImpl.java:749)
	at com.google.devtools.build.lib.server.GrpcServerImpl.access$1600(GrpcServerImpl.java:103)
	at com.google.devtools.build.lib.server.GrpcServerImpl$2.lambda$run$0(GrpcServerImpl.java:818)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
	at com.google.devtools.build.lib.remote.blobstore.http.HttpBlobStore.<init>(HttpBlobStore.java:163)
	at com.google.devtools.build.lib.remote.blobstore.http.HttpBlobStore.create(HttpBlobStore.java:128)
	at com.google.devtools.build.lib.remote.SimpleBlobStoreFactory.createRest(SimpleBlobStoreFactory.java:53)
	... 10 more
java.lang.RuntimeException: java.lang.NullPointerException
	at com.google.devtools.build.lib.remote.SimpleBlobStoreFactory.createRest(SimpleBlobStoreFactory.java:56)
	at com.google.devtools.build.lib.remote.SimpleBlobStoreFactory.create(SimpleBlobStoreFactory.java:73)
	at com.google.devtools.build.lib.remote.RemoteModule.beforeCommand(RemoteModule.java:261)
	at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.execExclusively(BlazeCommandDispatcher.java:295)
	at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.exec(BlazeCommandDispatcher.java:205)
	at com.google.devtools.build.lib.server.GrpcServerImpl.executeCommand(GrpcServerImpl.java:749)
	at com.google.devtools.build.lib.server.GrpcServerImpl.access$1600(GrpcServerImpl.java:103)
	at com.google.devtools.build.lib.server.GrpcServerImpl$2.lambda$run$0(GrpcServerImpl.java:818)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
	at com.google.devtools.build.lib.remote.blobstore.http.HttpBlobStore.<init>(HttpBlobStore.java:163)
	at com.google.devtools.build.lib.remote.blobstore.http.HttpBlobStore.create(HttpBlobStore.java:128)
	at com.google.devtools.build.lib.remote.SimpleBlobStoreFactory.createRest(SimpleBlobStoreFactory.java:53)
	... 10 more

Instead Bazel should exit gracefully.

Encountered this while trying to debug https://github.com/bazelbuild/bazel/issues/7464

/CC @meisterT @meteorcloudy @ulfjack

**Comment by buchgr** [comment] 2019-02-26 12:46
duplicate of #5850

**Closed by buchgr** 2019-02-26 12:46 UTC
Labels: team-Remote-Exec, untriaged
