### ISSUE TITLE
Error occurred when trying to build with precompiled library on macOS

### ISSUE THREAD

**Issue by tianshilei1992** [bazelbuild/bazel#4794] opened 2018-03-08 06:19 UTC
### Description of the problem / feature request:

I'm trying to build the TensorFlow with Intel MKL on macOS, which depends on a precompiled library Intel MKL. The building process failed, and it told `dyld: Library not loaded: @rpath/libmklml.dylib`, which is the mentioned third party library. I've set the rule according to the [document](https://docs.bazel.build/versions/master/cpp-use-cases.html#adding-dependencies-on-precompiled-libraries) as following shows:
```Python
# third_party/mkl/BUILD
cc_library(
    name = "intel_binary_blob",
    srcs = [
        "@mkl//:libmklml",
        "@mkl//:libiomp5",
    ],
    hdrs = ["@mkl//:mkl_headers"],
    strip_include_prefix = "/external/mkl/include",
    visibility = ["//visibility:public"],
)
```
where `mkl_headers `, `libmklml` and `libimp5` are respectively:
```Python
# third_party/mkl/mkl.BUILD
# Note: This file will be symbol linked to the downloaded position
filegroup(
    name = "mkl_headers",
    srcs = glob(["include/*"]),
    visibility = ["//visibility:public"],
)

load("@org_tensorflow//tensorflow:tensorflow.bzl",
     "if_darwin",
     "if_linux_x86_64")

filegroup(
    name = "libmklml",
    srcs = if_darwin(["lib/libmklml.dylib"])
         + if_linux_x86_64(["lib/libmklml_intel.so"]),
    visibility = ["//visibility:public"],
)

filegroup(
    name = "libiomp5",
    srcs = if_darwin(["lib/libiomp5.dylib"])
         + if_linux_x86_64(["lib/libiomp5.so"]),
    visibility = ["//visibility:public"],
)
```

However, this building procedure can **work on Linux**. Considering the constraint of SIP on macOS, I've replaced the compiler with latest llvm installed with HomeBrew, and default Python too with the HomeBrew's version, but they seemed to be useless.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Error log:
```Shell
dyld: Library not loaded: @rpath/libmklml.dylib
  Referenced from: /private/var/tmp/_bazel_shilei/fe2ffd3189bc27eabf3757c054a2a694/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/python/gen_parsing_ops_py_wrappers_cc
  Reason: image not found
```

The easiest way to reproduce the problem is to execute the following command on macOS:
```Shell
bazel build --copt=-DINTEL_MKL_DNN --config=mkl -c opt //tensorflow/tools/pip_package:build_pip_package
```

### What operating system are you running Bazel on?

macOS 10.13.13

### What's the output of `bazel info release`?

`release 0.11.0-homebrew`

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

`brew install bazel`

###  Have you found anything relevant by searching the web?

Nope.

### Any other information, logs, or outputs that you want to share?

```Shell
ERROR: tensorflow/tensorflow/python/BUILD:1429:1: Executing genrule //tensorflow/python:parsing_ops_pygenrule failed (Aborted): bash failed: error executing command /bin/bash bazel-out/darwin-py3-opt/genfiles/tensorflow/python/parsing_ops_pygenrule.genrule_script.sh
dyld: Library not loaded: @rpath/libmklml.dylib
  Referenced from: /private/var/tmp/_bazel_shilei/fe2ffd3189bc27eabf3757c054a2a694/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/python/gen_parsing_ops_py_wrappers_cc
  Reason: image not found
bazel-out/darwin-py3-opt/genfiles/tensorflow/python/parsing_ops_pygenrule.genrule_script.sh: line 2: 21161 Abort trap: 6
```

**Comment by laszlocsomor** [comment] 2018-03-08 11:26
@mhlopko : could you please confirm that this is an issue with the C++ rules, and if so, comment on priority / best person to work on it / ETA?

**Comment by tianshilei1992** [comment] 2018-03-08 11:33
Actually, I'm pretty curious about the inconsistency of the building behavior on different platform, since this building rules can work well on Linux.

**Comment by tianshilei1992** [comment] 2018-03-12 07:09
Hi @laszlocsomor, in order to verify whether there is issue in the rules, I built a toy project, which only depends on the external library. Here is the project files structure:

```Shell
test_bazel
├── BUILD
├── WORKSPACE
├── main.cc
├── main.hpp
├── third_party
│   ├── BUILD
│   ├── mkl
│   │   ├── BUILD
│   │   ├── LICENSE
│   │   ├── build_defs.bzl
│   │   └── mkl.BUILD
│   └── repo.bzl
└── workspace.bzl
```

The contents in those relative files are:

```C++
// main.cc
#include "main.hpp"

int main() {
    func();
    return 0;
}
```

```C++
// main.hpp
#include "i_malloc.h" // This is a function in the external precompiled library mkl

#include <iostream>

void func() {
    std::cout << "Hello World from Bazel." << std::endl;
}
```

```Python
# BUILD
cc_binary(
    name = "main",
    srcs = [
        "main.cc",
        "main.hpp"
    ],
    deps = [
        "//third_party/mkl:intel_binary_blob"
    ],
)
```

where the `//third_party/mkl:intel_binary_blob` is same with those in #1.

Now build the project via `bazel build //:main`, it is ok.

```Shell
test_bazel > bazel build //:main
WARNING: /Users/shilei/Documents/codes/test_bazel/third_party/mkl/BUILD:15:12: in srcs attribute of cc_library rule //third_party/mkl:intel_binary_blob: please do not import '@mkl//:lib/libmklml.dylib' directly. You should either move the file to this package or depend on an appropriate rule there
WARNING: /Users/shilei/Documents/codes/test_bazel/third_party/mkl/BUILD:15:12: in srcs attribute of cc_library rule //third_party/mkl:intel_binary_blob: please do not import '@mkl//:lib/libiomp5.dylib' directly. You should either move the file to this package or depend on an appropriate rule there
WARNING: /Users/shilei/Documents/codes/test_bazel/third_party/mkl/BUILD:13:1: in linkstatic attribute of cc_library rule //third_party/mkl:intel_binary_blob: setting 'linkstatic=1' is recommended if there are no object files
INFO: Analysed target //:main (0 packages loaded).
INFO: Found 1 target...
Target //:main up-to-date:
  bazel-bin/main
INFO: Elapsed time: 1.173s, Critical Path: 1.00s
INFO: Build completed successfully, 3 total actions
```

And when I tried to execute the generated binary, it told me the same error that library not loaded.

```Shell
bazel-bin > ./main
dyld: Library not loaded: @rpath/libmklml.dylib
  Referenced from: /private/var/tmp/_bazel_shilei/197de9994dc99e0d9bcfa4519b2bf57e/execroot/test_bazel/bazel-out/darwin-fastbuild/bin/./main
  Reason: image not found
Abort trap: 6
```

However, there are some warinings I didn't notice before, `please do not import '@mkl//:lib/libiomp5.dylib' directly. You should either move the file to this package or depend on an appropriate rule there`. You could see in my rule that these two files are imported through the rule of `filegroup`:

```Python
filegroup(
    name = "libmklml",
    srcs = if_darwin(["lib/libmklml.dylib"])
         + if_linux_x86_64(["lib/libmklml_intel.so"]),
    visibility = ["//visibility:public"],
)

filegroup(
    name = "libiomp5",
    srcs = if_darwin(["lib/libiomp5.dylib"])
         + if_linux_x86_64(["lib/libiomp5.so"]),
    visibility = ["//visibility:public"],
)
```

Is there something wrong? If here is the key point, no doubt that it will tell me that the library could not be found.

**Comment by laszlocsomor** [comment] 2018-03-15 09:09
@tianshilei1992 , thank you for such a detailed bug report!

I started looking at it, but something I noticed and wanted point out, in hopes it would happen to be the solution: have you looked at the [`cc_import`](https://docs.bazel.build/versions/master/be/c-cpp.html#cc_import) rule to import the .so/.dylib instead of using a `cc_library`?

**Comment by laszlocsomor** [comment] 2018-03-15 09:53
@tianshilei1992 , I have good news and bad news.

The somewhat good news is that this is a known issue. The bad news is, as @mhlopko tells me, that fixing it is going to take more time.

The other somewhat good news is that I reduced your example to an even smaller one: https://github.com/laszlocsomor/projects/commit/c802b5953c4ca9046d1023ba59b4e6bcfb384ce2

**Comment by tianshilei1992** [comment] 2018-03-16 01:59
@laszlocsomor , thanks for your notification. It's really sad to hear that.

Thanks for your refinement. My original idea is to build the codes on different platforms with the same command, thus some conditional statements are involved.

**Comment by LossyRedgement** [comment] 2018-03-19 08:59
Hi @laszlocsomor ,
I have encountered a similar situation with that mentioned above. 

I am curious to know, if there would be a rough idea about when to expect this fixing? And if it might take quite a period, would there be a patch provided to almost solve this problem?

Thanks in advance!

**Comment by mhlopko** [comment] 2018-03-20 21:20
@tianshilei1992 I expect that this is caused by how @rpath works on darwin, I think we just have to patch the binary to find dylibs properly. https://github.com/bazelbuild/bazel/blob/master/tools/cpp/osx_cc_wrapper.sh.tpl shows what we do already. But I cannot repro because unsupported option '-fopenmp', do you build with clang or gcc? Which version? How did you install on mac?

Also can you try with bazel built@HEAD?  My latest fix to osx_cc_wrapper is not yet released (https://github.com/bazelbuild/bazel/commit/f98a7a2fedb3e714cef1038dcb85f83731150246) maybe you'll be lucky :) Also you can take a look at https://github.com/bazelbuild/bazel/issues/4594 and https://github.com/bazelbuild/bazel/issues/3811 and https://github.com/bazelbuild/bazel/issues/1576, might be duplicate of this one.

@laszlocsomor I'm not sure if your repo is a repro of this issue. The problem you observe is that you renamed `libmylib-macos.dylib` to smth else, and `main-with-lib` won't find it. If you rename it back, all is green. Or is that what's happening with libmkl too?

**Comment by opencici2006** [comment] 2018-03-21 03:26
@mhlopko We build with clang, you could install on Mac through 
`brew install llvm` and `brew install libomp` and then set the env `CC=/path/to/new/clang` and `CXX=/path/to/new/clang++`.

**Comment by mhlopko** [comment] 2018-03-22 09:45
In the meantime, can you try with bazel build from HEAD? See "Compiling bazel" from https://www.bazel.build/contributing.html.

**Comment by tianshilei1992** [comment] 2018-03-26 02:45
@mhlopko I'm tried to build the latest bazel (HEAD->master) using `bazel build //src:bazel`, and use the generated binary in `bazel-bin/src/bazel` to build the tensorflow, but it failed to detect the target CPU with the error `error: unknown target CPU 'armv7-a'`, actually I was building on the macOS. In addition to the tensorflow, I've also tried to build my toy project mentioned above with the generated binary through `bazel/bazel-bin/src/bazel build //:main`, unfortunately it failed too. The detailed error information is attached.

```Shell
test_bazel > ../../bazel/bazel-bin/src/bazel build //:main --verbose_failures
INFO: Analysed target //:main (0 packages loaded).
INFO: Found 1 target...
ERROR: /Users/shilei/Documents/codes/test_bazel/BUILD:1:1: Linking of rule '//:main' failed (Exit 1): cc_wrapper.sh failed: error executing command 
  (cd /private/var/tmp/_bazel_shilei/197de9994dc99e0d9bcfa4519b2bf57e/execroot/test_bazel && \
  exec env - \
    PWD=/proc/self/cwd \
  external/local_config_cc/cc_wrapper.sh -o bazel-out/darwin-fastbuild/bin/main -Wl,-rpath,@loader_path/_solib_darwin/_U_S_Sthird_Uparty_Smkl_Clibiomp5___Uexternal_Smkl_Slib -Wl,-rpath,@loader_path/_solib_darwin/_U_S_Sthird_Uparty_Smkl_Clibmklml___Uexternal_Smkl_Slib -Lbazel-out/darwin-fastbuild/bin/_solib_darwin/_U_S_Sthird_Uparty_Smkl_Clibiomp5___Uexternal_Smkl_Slib -Lbazel-out/darwin-fastbuild/bin/_solib_darwin/_U_S_Sthird_Uparty_Smkl_Clibmklml___Uexternal_Smkl_Slib bazel-out/darwin-fastbuild/bin/_objs/main/main.pic.o -liomp5 -lmklml -undefined dynamic_lookup -headerpad_max_install_names -lstdc++ -lm -Wl,-S)

Use --sandbox_debug to see verbose messages from the sandbox
clang-5.0: error: unable to execute command: Executable "ld" doesn't exist!
clang-5.0: error: linker command failed with exit code 1 (use -v to see invocation)
Target //:main failed to build
INFO: Elapsed time: 0.226s, Critical Path: 0.05s
FAILED: Build did NOT complete successfully
```

I don't know whether my bazel build is correct because I didn't bootstrap it before. According to https://docs.bazel.build/versions/master/install-compile-source.html#compiling-bazel-from-source-bootstrapping, I should run the `compile.sh` first with the release version and then build the development version. However, an error occurred when I tried to build the release version.

```Shell
ERROR: /Users/shilei/Documents/bazel-0/src/main/java/com/google/devtools/build/lib/BUILD:1177:1: Executing genrule //src/main/java/com/google/devtools/build/lib:merge_licenses failed (Exit 126): bash failed: error executing command 
  (cd /tmp/bazel_ZrLMMUQs/out/execroot/io_bazel && \
  exec env - \
    PATH=/usr/local/opt/python/bin:/usr/local/Cellar/llvm/5.0.1/bin:/Users/shilei/.local/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin \
  /bin/bash bazel-out/darwin-opt/genfiles/src/main/java/com/google/devtools/build/lib/merge_licenses.genrule_script.sh)
xargs: src/main/java/com/google/devtools/build/lib/merge_licenses.sh: Permission denied
Target //src:bazel failed to build
INFO: Elapsed time: 272.270s, Critical Path: 66.37s
FAILED: Build did NOT complete successfully
```

**Comment by mhlopko** [comment] 2018-03-26 06:37
This is super strange. Please verify following:

    bazel clean --expunge && bazel build //tensorflow:foo

works with bazel 0.11.0, and fails with bazel@HEAD. That would be very strange because we have tensorflow on our CI and it's green currently. No local changes? No extra options passed to bazel?

The same info would be useful for your toy project. The error message says that your C++ toolchain is not autodetected properly, but I don't remember any big changes there. Did you by chance upgrade clang recently? If you run `bazel clean --expunge && bazel build //:main` with released bazel, does it work? Can you send me contents of working and failing `$execroot/external/local_config_cc`? Do you have xcode installed? If yes, does anything change when exporting `BAZEL_USE_CPP_ONLY_TOOLCHAIN=1` environment variable?

Bootstrap procedure is only needed when you don't have bazel already

> You can build Bazel from source without using an existing Bazel binary by doing the following:

If you have bazel, then `bazel build //src:bazel` is the way to build.

Thanks!

**Comment by tianshilei1992** [comment] 2018-03-26 07:56
@mhlopko Yes, released bazel could build the toy project, only build, and the generated binary file failed to execute due to the @rpath problem.

Xcode was not installed. I used the clang installed via HomeBrew (`brew install llvm`) to support the OpenMP flags. The relative env `CC` and `CXX` have been set correctly.
```Shell
CC=/usr/local/Cellar/llvm/5.0.1/bin/clang
CXX=/usr/local/Cellar/llvm/5.0.1/bin/clang++
```

When using my built bazel, the contents of `$execroot/external/local_config_cc` are:
```Shell
test_bazel > ll /private/var/tmp/_bazel_shilei/197de9994dc99e0d9bcfa4519b2bf57e/external/local_config_cc/
total 136
drwxr-xr-x  9 shilei  wheel    306 Mar 26 15:41 ./
drwxr-xr-x  8 shilei  wheel    272 Mar 26 15:41 ../
-rwxr-xr-x  1 shilei  wheel   3085 Mar 26 15:41 BUILD*
-rwxr-xr-x  1 shilei  wheel  29272 Mar 26 15:41 CROSSTOOL*
-rw-r--r--  1 shilei  wheel    111 Mar 26 15:41 WORKSPACE
-rwxr-xr-x  1 shilei  wheel   3283 Mar 26 15:41 cc_wrapper.sh*
lrwxr-xr-x  1 shilei  wheel    114 Mar 26 15:41 dummy_toolchain.bzl@ -> /private/var/tmp/_bazel_shilei/197de9994dc99e0d9bcfa4519b2bf57e/external/bazel_tools/tools/cpp/dummy_toolchain.bzl
drwxr-xr-x  3 shilei  wheel    102 Mar 26 15:41 tools/
-rwxr-xr-x  1 shilei  wheel  19276 Mar 26 15:41 xcode-locator-bin*
```

As for the TensorFlow build, the command `$PATH/TO/BUILT/bazel build --copt=-DINTEL_MKL_DNN --config=mkl -c opt //tensorflow/tools/pip_package:build_pip_package` was executed to build the MKL-DNN version.

**Comment by tianshilei1992** [comment] 2018-04-13 02:09
Hi @laszlocsomor @mhlopko 
I noticed that the version of 0.12 has been released, and I've taken a try. The good news is that bazel 0.12 seems to fix the issue of @rpath on macOS. Our project could be built with the latest release.

**Comment by FrederickGeek8** [comment] 2018-04-13 12:16
Hi @tianshilei1992 
Did you figure out why the target architecture was detected as `armv7-a`? I am running into a similar issue and scratching my head. Feel free to contact me elsewhere if you want to continue this conversation outside of the issue...

**Comment by csarron** [comment] 2018-04-15 02:36
I also had the same problem, I think it's bazel's bug in version 0.12.0. I solved the problem by installing version 0.11.1 [here](https://github.com/bazelbuild/bazel/releases/download/0.11.1/bazel-0.11.1-installer-darwin-x86_64.sh).

**Comment by tianshilei1992** [comment] 2018-04-15 02:43
Hi @FrederickGeek8 @csarron , I don't know how you installed the bazel, but the false detection of platform didn't occur in the released version. I installed it with HomeBrew through `brew install bazel`. I guess you maybe built from sources because I found that problem when I built from sources before the 0.12 released.

**Comment by csarron** [comment] 2018-04-15 03:01
@tianshilei1992 I installed it from homebrew by `brew upgrade bazel` and it caused the problem. Anyway, if the release version works, it's not a big issue.

**Closed** 2018-04-16 10:43 UTC
Labels: category: rules > C++, type: bug
