### ISSUE TITLE
Bazel 0.1.5 now rejects maven jars with dots or dashes in their names

### ISSUE THREAD

**Issue by dfabulich** [bazelbuild/bazel#874] opened 2016-02-09 23:44 UTC
https://github.com/dfabulich/bazel_maven_jar builds successfully in bazel 0.1.4 but fails in bazel 0.1.5.

```
ERROR: /private/tmp/tp/bazel_maven_jar/WORKSPACE:1:1: maven_jar rule //external:javax.servlet_javax.servlet-api's name field must be a legal workspace name.
```

Here's the relevant WORKSPACE:
```
maven_jar (
	name = "javax.servlet_javax.servlet-api",
	artifact = "javax.servlet:javax.servlet-api:3.0.1",
)
```

**Comment by dfabulich** [comment] 2016-02-09 23:47
I guess this was called out in the release notes, but as an "important change" and not an "incompatible change."

> • Repository rules must use names that are valid workspace names.

Was it intended for this to be a breaking change? Was it intended for maven jars not to have dots in their names? (They ALL have dots in their names!)

**Comment by benley** [comment] 2016-02-09 23:54
would it break things if you changed the name of that target to "javax_servlet_javax_servlet_api"?

**Comment by ahumesky** [comment] 2016-02-09 23:55
Correct, this is intentional for compatibility with different languages. I believe that the motivation was that the name of the repository shows up in the name of the workspace for the repository, which in turn shows up in paths and imports.

You can change "javax.servlet_javax.servlet-api" to "javax_servlet_javax_servlet_api"

**Comment by ahumesky** [comment] 2016-02-10 00:00
I assigned damien to this in case there is a better motivation than what I list above, but otherwise this is WAI.

**Comment by dfabulich** [comment] 2016-02-10 00:04
1) At a minimum, this should be promoted to an "incompatible change" in the release notes.

2) I'm currently writing a Python script to try to fix all of it up, but it's not a happy task. :grimacing: 

3) I don't see any specification of what characters are allowed in a maven_jar name. I guess I'm only allowed to use letters, numerals, and underscores? It sure would be nice to have even _one_ more special character that I could use to distinguish between the Maven group ID and the artifact ID in the name, e.g. a pipe or a slash or _something_.

**Comment by ahumesky** [comment] 2016-02-10 00:11
For 2, I would hope that this is a one-time find and replace for your repository name rules. Note that I think you could use a bing() rule for indirection here, though I'm not sure how appealing that is.

Agreed that we need to update the documentation around this. The point about this is buried over here at the bottom: http://bazel.io/docs/be/functions.html#workspace

**Comment by dfabulich** [comment] 2016-02-10 00:13
@ahumesky What's a bing() rule? http://bazel.io/search.html?q=bing turns up nothing.

**Comment by ahumesky** [comment] 2016-02-10 00:14
whoops, that should be bind()

**Comment by dfabulich** [comment] 2016-02-10 00:16
What characters are allowed in a bind alias?

**Comment by ahumesky** [comment] 2016-02-10 00:21
That can be a normal label. The only name that is restricted are all the workspace rules that create a repository or workspace, which I believe are at most these:

git_repository
http_archive
http_file
http_jar
local_repository
maven_jar
new_git_repository
new_http_archive
new_local_repository

**Comment by damienmg** [comment] 2016-02-10 09:38
1/ Yes this should have been marked as an incompatible change. I guess I can edit the github notes but not the changelog nor the inlined release notes. (note: I moved the corresponding item to incompatible change in the workspace

2/ Sorry for that. we should have done a better job at announcing it (it was announced on bazel-discuss@ but that's all).

3/ Yes must start with letter and then numeric

/cc @kchodorow if she has more to add.

Closing as working as intended as there is no real action item we can do.

**Closed by damienmg** 2016-02-10 09:38 UTC

**Comment by kchodorow** [comment] 2016-02-10 14:44
See https://groups.google.com/forum/#!topic/bazel-discuss/hv5BUQtgumc for some details about this change.  I also wrote [a script](https://gist.github.com/kchodorow/450c6e0ab3eeab57e9d8) that might help (it finds illegal names in your WORKSPACE file, changes them to legal ones, and then goes through your build files and updates any references).
