### ISSUE TITLE
Java 9: Missing strict dependency is erroneously reported

### ISSUE THREAD

**Issue by davido** [bazelbuild/bazel#4812] opened 2018-03-09 08:12 UTC
### Description of the problem / feature request:

Bazel built with Java 9 from HEAD, with this [PR](https://github.com/bazelbuild/bazel/pull/4795) applied, is reporting missing strict dependency. The reported missing dependency is in place.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

- Apply this [PR](https://github.com/bazelbuild/bazel/pull/4795) on HEAD
- Build Bazel with Java 9 with this command:

```
$ bazel --host_javabase=/usr/lib64/jvm/java-9-openjdk build \
  --javacopt='--release 9' \
  --java_toolchain=@bazel_tools//tools/jdk:toolchain_jdk9 \
  src:bazel
```
- Clone [bazel_printy](https://github.com/davido/bazel_printy) test repository
- Try to build `printy_lib` rule with Bazel built with java 9

Expected: build is successful

Actual: build is failing:

```
$ bazel build :printy_lib
INFO: Analysed target //:printy_lib (0 packages loaded).
INFO: Found 1 target and 0 test targets...
ERROR: /home/davido/projects/bazel_printy/BUILD:9:1: Building libprinty_lib.jar (1 source file) failed (Exit 1)
src/main/java/org/gerritcon/mv2016/Printy.java:22: error: [strict] Using type com.google.common.base.Joiner from an indirect dependency (TOOL_INFO: "@guava//jar"). See command below **
    System.out.println(Joiner.on(' ').join(argv));
                       ^
 ** Please add the following dependencies: 
  @guava//jar  to //:printy_lib 
 ** You can use the following buildozer command: 
buildozer 'add deps @guava//jar ' //:printy_lib 

Target //:printy_lib failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 0.481s, Critical Path: 0.32s
FAILED: Build did NOT complete successfully
```

Note, that `printy_lib` already depends on `guava`:

https://github.com/davido/bazel_printy/blob/master/BUILD#L9-L14 

### What operating system are you running Bazel on?

Linux, Java 9.

### Related:

#4709

### Known workarounds:

All is fine if I build Bazel with Java 8.

**Comment by cushon** [comment] 2018-03-09 18:23
This is effectively a duplicate of #3410.

In particular, see:
* https://github.com/google/error-prone-javac/commit/9901a45ff63c1d7bc9263007147dc866272b7fdc
* https://github.com/bazelbuild/bazel/blob/9b79b00107949194911fba11a805fe0eb81fcb38/tools/jdk/default_java_toolchain.bzl#L32

**Closed by cushon** 2018-03-09 18:23 UTC
Labels: category: rules > java, type: bug

**Comment by davido** [comment] 2018-03-09 22:10
@cushon Thanks for the pointer. What is your recommendation to fix strict dependency problem when https://github.com/bazelbuild/bazel/pull/4795 (or equivalent) is merged and we sorted out gRpc issue? Do we really need to patch javac in Java 9 for strict dependency to work properly?

**Comment by davido** [comment] 2018-03-10 13:01
I'm asking, because for now, strict dependency is the last unresolved issue for building Bazel and Gerrit Code Review eco-system with Java 9 (Bazel, Gerrit, JGit and Gitiles).

There are two known workarounds for this problem:

- Pass `--strict_java_deps=OFF` to diable strict java deps feature
- Dynamically detect the Java runtime and disable that feature, because we do know, it doesn't work: [1]

* [1] http://paste.openstack.org/show/697836

**Comment by davido** [comment] 2018-04-05 06:56
Thanks for the fix. It works now. I see, that the custom javac is used now

```
"--patch-module=java.compiler=$(location //third_party/java/jdk/langtools:java_compiler_jar)",
"--patch-module=jdk.compiler=$(location //third_party/java/jdk/langtools:jdk_compiler_jar)"
```

Where are those files are coming from?
