### ISSUE TITLE
Bazel 0.16.1 throws java.util.logging.FileHandler error on Windows

### ISSUE THREAD

**Issue by gregbown** [bazelbuild/bazel#5916] opened 2018-08-16 19:35 UTC
Following the documented installation [here](https://docs.bazel.build/versions/master/install-windows.html) Installing bazel-0.16.1-windows-x86_64.exe

After setting windows environment path to installation directory directory:
```
C:\Windows\System32>bazel version
Can't load log handler "java.util.logging.FileHandler"
java.nio.file.NoSuchFileException: c:users\gbown\_bazel~1\u5mzpase\java.log.lck
java.nio.file.NoSuchFileException: c:users\gbown\_bazel~1\u5mzpase\java.log.lck
        at java.base/sun.nio.fs.WindowsException.translateToIOException(Unknown Source)
        at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
        at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
        at java.base/sun.nio.fs.WindowsFileSystemProvider.newFileChannel(Unknown Source)
        at java.base/java.nio.channels.FileChannel.open(Unknown Source)
        at java.base/java.nio.channels.FileChannel.open(Unknown Source)
        at java.logging/java.util.logging.FileHandler.openFiles(Unknown Source)
        at java.logging/java.util.logging.FileHandler.<init>(Unknown Source)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
        at java.base/java.lang.reflect.Constructor.newInstance(Unknown Source)
        at java.base/java.lang.Class.newInstance(Unknown Source)
        at java.logging/java.util.logging.LogManager.createLoggerHandlers(Unknown Source)
        at java.logging/java.util.logging.LogManager.access$1300(Unknown Source)
        at java.logging/java.util.logging.LogManager$4.run(Unknown Source)
        at java.logging/java.util.logging.LogManager$4.run(Unknown Source)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.logging/java.util.logging.LogManager.loadLoggerHandlers(Unknown Source)
        at java.logging/java.util.logging.LogManager.initializeGlobalHandlers(Unknown Source)
        at java.logging/java.util.logging.LogManager.access$1800(Unknown Source)
        at java.logging/java.util.logging.LogManager$RootLogger.accessCheckedHandlers(Unknown Source)
        at java.logging/java.util.logging.Logger.getHandlers(Unknown Source)
        at java.logging/java.util.logging.Logger.log(Unknown Source)
        at java.logging/java.util.logging.Logger.doLog(Unknown Source)
        at java.logging/java.util.logging.Logger.log(Unknown Source)
        at java.logging/java.util.logging.Logger.info(Unknown Source)
        at com.google.devtools.build.lib.analysis.BlazeVersionInfo.logVersionInfo(BlazeVersionInfo.java:64)
        at com.google.devtools.build.lib.analysis.BlazeVersionInfo.setBuildInfo(BlazeVersionInfo.java:79)
        at com.google.devtools.build.lib.bazel.Bazel.main(Bazel.java:65)
WARNING: --batch mode is deprecated. Please instead explicitly shut down your Bazel server using the command "bazel shutdown".
Build label: 0.16.1
Build target: bazel-out/x64_windows-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Mon Aug 13 13:42:55 2018 (1534167775)
Build timestamp: 1534167775
Build timestamp as int: 1534167775
```
### What operating system are you running Bazel on?
Windows 10 Pro
Version 1709 OS build 16299.551

My JDK and JRE are both 1.8.0_181
```
C:\Windows\System32>java -version
java version "1.8.0_181"
Java(TM) SE Runtime Environment (build 1.8.0_181-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.181-b13, mixed mode)
```
Reverting to version 0.15.2 as temporary solution since it works without any issues.

**Comment by meteorcloudy** [comment] 2018-08-17 10:52
This is a duplicate of https://github.com/bazelbuild/bazel/issues/5442
The error only happens outside of a workspace, you can still use it as normal.
Sorry for the breakage, it won't happen in the next release,

**Closed by meteorcloudy** 2018-08-17 10:52 UTC

**Comment by komputerboy** [comment] 2018-08-25 03:51
same error here
