### ISSUE TITLE
Cache is not stored/reused from previous builds

### ISSUE THREAD

**Issue by nordlow** [bazelbuild/bazel#3042] opened 2017-05-24 10:08 UTC
Bazel currently doesn't use caching in step 5 of

1. Build library X containing a.c
2. Modify contents of a.c
3. Build library X again
4. Revert changes of a.c
5. Build library X again (caching is not reused)

Test case (that generates 10000 files that are built to a static library) is here: https://github.com/nordlow/build-system-benchmark/blob/master/test_bazel.sh

This is a severe limitation in continous integration server clusters that continously switch between different features branches that differ only in a very small percentage of the code.

Buck doesn't have this limitation.

Is this a known issue?

I'm using bazel-0.4.5 on Ubuntu 17.04.

**Comment by nordlow** [comment] 2017-05-30 21:40
Is this perchance an expected behaviour and supposed to be solved in version 0.7 (P2) according to

https://bazel.build/roadmap.html

**Comment by ulfjack** [comment] 2017-06-26 15:49
No, it doesn't have anything to do with external repositories.

The reason is that the Bazel action cache does not store file contents, so we can't recover the content from the first step. @damienmg actually wants to get rid of the action cache (as it currently exists) and use a 'spawn cache' instead, which is more like the remote caching we're working on. However, it's unclear how we can avoid making copies of all the output files and generally preventing unbounded growth of the cache.

**Comment by jgavris** [comment] 2017-06-26 15:52
Can't the local cache look like the remote cache (content-addressable)? I imagine most remote cache implementations are using a bounded LRU / LFU.

**Comment by damienmg** [comment] 2017-06-26 15:54
That is my prototype to do a LRU disk based cache for spawn action. it is unclear if it would replace the action cache.

**Comment by ulfjack** [comment] 2017-06-26 16:42
@jgavris We could certainly make changes here, and that's exactly what @damienmg is proposing. And certainly, we'd want an appropriate eviction strategy. However, it'd have to be larger than the size of your output tree to be useful, so it'd at least double the disk space needed for Bazel, so this isn't a change to make lightly.

**Comment by rahul-malik** [comment] 2017-09-07 17:24
@ulfjack @damienmg - Is there a version of this LRU cache behind an experiment flag? I was thinking of rolling my own solution but would rather use one built into bazel itself.

**Comment by damienmg** [comment] 2017-09-07 18:08
Nope, only pending change that I need to rebase, would love to merge them
thus.

**Comment by davido** [comment] 2017-09-13 08:48
@damienmg The status of [the pending change](https://bazel-review.googlesource.com/#/c/bazel/+/8133/) is not clear to me. Does it work as is? Any comments if it could be used already today for earlier adopter.

I also disagree, with the priority here. From the user perspective, I would just expect sane local disk cache behaviour. That is exactly what Buck does per default here.

To make my POV even more clear: If I would be on Bazel team, I would stop working on anything else, until this bug is fixed and released.

**Comment by rahul-malik** [comment] 2017-09-13 14:30
I'd agree but it sounds like the discussion internally hasn't reached consensus?

I'm running a remote cache locally to get around this issue but I expected this behavior from the start and it was a shock to myself and my team that it didn't work this way. The local remote cache is not an ideal solution since I'm also setting up a true remote cache on another cluster and I can't configure more than one cache per bazel invocation

**Comment by ulfjack** [comment] 2017-09-14 07:26
I don't think at this point anyone is opposing adding support for a local cache, but we're not actively working on it. It should be fairly straightforward to add support for a local cache at this point. @damienmg's change is outdated - most of the classes have been refactored.

I'd go about it by moving the LruCache to a more generic location, and possibly refactoring its API. The most straightforward way to do it seems to be to reuse RemoteActionCache, and implement SimpleBlobStore. Ideally, we'd move any code that's independent of remote / local into a generic class (AbstractSpawnCache?), although it might use some protos from the remote protocol to represent action keys and whatnot.

**Comment by rahul-malik** [comment] 2017-09-15 01:32
@ulfjack - While not completely familiar with the code, it seems like we might be able to use `OnDiskBlobStore` and make `SimpleBlobStoreActionCache` conform to `ActionCache`? Please correct if I'm wrong in my interpretation

**Comment by ulfjack** [comment] 2017-09-15 06:51
We have two interfaces: ActionCache and RemoteActionCache

Implementing ActionCache is a lot more complicated and a lot more difficult to get right, so I do not recommend doing that. Implementing RemoteActionCache is much simpler and easier to get right. Ignore the "Remote" prefix, it doesn't have any meaning at this point. Similarly, the "Remote" prefix of RemoteSpawnCache has no meaning (sorry about that).

The SimpleBlobStoreActionCache implements RemoteActionCache. You can use a RemoteSpawnCache with a SimpleBlobStoreActionCache with a OnDiskBlobStore to implement local caching - prototyping this should be trivial.

There are two problems with doing it that way:
 1. the RemoteSpawnCache is hard-coded to use some of the --remote_* options - I'd suggest to inject the two necessary flags in the constructor - and
 2. the OnDiskBlobStore has no eviction strategy - I'd suggest to generalize the existing LruCache, but if you don't care about eviction, the OnDiskBlobStore would work just fine, too.

**Comment by rahul-malik** [comment] 2017-09-16 01:06
Thanks for the tips. I'll look into prototyping something next week. Would it be reasonable to say that the usage of ActionCache would be replaced with SpawnCache or are there reasons to keep ActionCache around?

**Comment by davido** [comment] 2017-09-16 14:15
> [...] You can use a RemoteSpawnCache with a SimpleBlobStoreActionCache with a OnDiskBlobStore to implement local caching - prototyping this should be trivial.

Indeed: https://bazel-review.googlesource.com/16810.

**Comment by rahul-malik** [comment] 2017-09-16 21:54
@davido - Thanks for putting this together! That is a lot more straightforward than what I was thinking of doing (replacing all usage of ActionCache with SpawnCache).

I think this is a good start and will likely benefit from a few additions:
- Use `LRUDiskCache` vs `OnDiskBlobStore` to support eviction. Will require adding a new option similar to the `dir_max_size` option in Buck. The default `max_size` in @damienmg PR is `-1` which implies an unbounded cache anyways.
- Since this effectively replaces the default local action cache, introduce a composite cache that allows for falling back from the local disk cache to a REST / Hazelcast cache. The composite cache would just be the composition of existing caches. The way this is implemented currently means that you can only have a local disk cache OR a rest cache rather than utilizing both.

Thoughts? Happy to help build these changes on top of your PR.

@ulfjack - Given this is behind an experimental flag, will this be able to land before having eviction implemented or is that required for this to merge?

**Comment by davido** [comment] 2017-09-17 07:49
@rahul-malik 

Yeah, eviction strategy is definitely something that would need to be added at some point. I'm not sure i understand your second point about replacement of action cache? There is no action cache right now for non remote execution strategy.

I've thoroughly  tested my CL and while I see cache hits, while building in the same workspace and switching across different branches, i still see cache misses when switching across different workspaces:

```
  $ git clone https://gerrit.googlesource.com/gerrit gerrit
  $ cd gerrit
  $ bazel build gerrit --experimental_local_disk_cache_path=/home/davido/.gerritcodereview/bazel-cache/cas --experimental_local_disk_cache
  $ cd ..
  $ git clone https://gerrit.googlesource.com/gerrit gerrit2
  $ bazel build gerrit --experimental_local_disk_cache_path=/home/davido/.gerritcodereview/bazel-cache/cas --experimental_local_disk_cache
```

I would expect the cache hits in the last steps, but I'm seeing that everythinng gets recompiled and the cache directory content was expanded with new cache entries.

Just a WAG: this is because exec root contributes to the digest algorithm and is the part of they cache key, so that this requirement can't work atm? Can we tweak key computation here to make this work?

**Comment by rahul-malik** [comment] 2017-09-18 06:22
> We have two interfaces: ActionCache and RemoteActionCache
> The reason is that the Bazel action cache does not store file contents, so we can't recover the content from the first step - it gets overwritten in step 3. @damienmg actually wants to get rid of the action cache (as it currently exists) and use a 'spawn cache' instead, which is more like the remote caching we're working on.

@davido - My second point was mainly around the fact that this PR provides the behavior we expected by default for the local cache. To enable this behavior you have to use the remote strategy but given the code snippet below, you would be unable to utilize this local disk cache in combination with a REST / Hazelcast cache.
```
  public static SimpleBlobStore create(RemoteOptions options) throws IOException {
    if (isHazelcastOptions(options)) {
      return createHazelcast(options);
    }
    if (isRestUrlOptions(options)) {
      return createRest(options);
    }
    if (isLocalDiskCache(options)) {
      return createLocalDisk(options);
    }
    throw new IllegalArgumentException(
        "Unrecognized concurrent map RemoteOptions: must specify "
            + "either Hazelcast or Rest URL options or local cache.");
  }
```

**Comment by ulfjack** [comment] 2017-09-18 08:02
@davido Are you aware of #2574? Try setting --experimental_strict_action_env.

**Comment by davido** [comment] 2017-09-18 08:27
@ulfjack Ah, right, i saw that, but forgot. Thanks, for pointing this out. I will re-test it later today.

**Comment by rahul-malik** [comment] 2017-09-18 15:00
@davido - Another thought also: Does the cache file path need to be absolute? It would be easier to share the change with other developers if we were able to put it under the home directory for instance.

**Comment by davido** [comment] 2017-09-18 15:07
@rahul-malik Yeah, exactly! Right now it's not possible, but I'm planning to add another change on top of this, [something, similar, to what I did 4 years ago in Buck](https://github.com/facebook/buck/commit/a1ba00118666c39f87354e3c0f2226e6f87c6970), as Gerrit Code Review was using Buck. We *must* support "$HOME/.gerritcodereview/bazel-cache/cas".

**Comment by ittaiz** [comment] 2017-09-18 15:35
+1

**Comment by davido** [comment] 2017-09-19 08:02
@ulfjack 

> Are you aware of #2574? Try setting --experimental_strict_action_env.

Passing `--experimental_strict_action_env` fixed this. Caching across different workspaces works like a charm now!

**Comment by davido** [comment] 2017-09-19 08:04
> Right now it's not possible, but I'm planning to add another change on top of this CL, something similar, to what I did 4 years ago in Buck, as Gerrit Code Review was using Buck. We must support "~/.gerritcodereview/bazel-cache/cas" and commit it under GIT in <gerrit_project>/tools/bazel.rc

This was fixed in the latest patch set of my CL. Now you can pass in generic path using home directory. This command works for gerrit code review:

```
  $ bazel build gerrit --experimental_local_disk_cache_path=~/.gerritcodereview/bazel-cache/cas --experimental_local_disk_cache --experimental_strict_action_env
```

**Comment by nordlow** [comment] 2017-09-19 12:42
@davido : do you mean with latest patchset of the CL? Is this on Bazel git master?

**Comment by rahul-malik** [comment] 2017-09-19 16:56
@nordlow - The CL he's referring to is on Gerrit right now. You can see the patch here: https://bazel-review.googlesource.com/c/bazel/+/16810

**Comment by davido** [comment] 2017-09-19 19:15
@nordlow Can you apply [this CL](https://bazel-review.googlesource.com/c/bazel/+/16810), build custom version of Bazel and repeat your benchmark?

**Comment by rahul-malik** [comment] 2017-09-22 15:20
@davido - did this end up merging? Looks like the PR is approved?

**Comment by davido** [comment] 2017-09-22 15:22
@rahul-malik I think it should be merged in the next days.

**Comment by damienmg** [comment] 2017-09-22 15:33
I send the CR for internal review but @ulfjack is away today and there seems to be internal test failure (which should not) so I Monday afternoon probably, tuesday at worse.

**Comment by davido** [comment] 2017-09-28 07:26
@damienmg this can be closed now with 82859b0c969f84fe49ec7fd1c8702461e847890c, right?

**Comment by damienmg** [comment] 2017-09-28 07:30
Not until it is the default I think.

**Comment by rahul-malik** [comment] 2017-10-12 06:55
@damienmg @davido - Did this not make it into 0.6.1? I just updated and was hoping to have this feature.

**Comment by damienmg** [comment] 2017-10-12 07:07
Nope 0.6.1 was a patch release. You can try 0.7 release candidate.

**Comment by davido** [comment] 2017-10-15 10:18
Confirmed, that this feature is included in 0.7, e.g.: https://storage.googleapis.com/bazel/0.7.0/rc2/index.html .

**Comment by Globegitter** [comment] 2018-02-12 14:52
@davido just tried
`build --experimental_local_disk_cache_path=~/.gerritcodereview/bazel-cache/cas --experimental_local_disk_cache --experimental_strict_action_env` with bazel 0.10.0 and it seems the home directory is not resolved. Is home directory resolution now supposed to work, or is that still something coming?

**Comment by davido** [comment] 2018-02-12 19:50
@Globegitter Unfortunately, home directory resolution (`~`) was undone in the latest versions of my patch. So you can only say:

```
$ cat ~/.bazelrc | grep cas
build --experimental_local_disk_cache_path=/home/davido/.gerritcodereview/bazel-cache/cas
```

Note, that's why we cannot add this line to Gerrit Code Review's own [tools/bazelr.c](https://github.com/GerritCodeReview/gerrit/blob/master/tools/bazel.rc) file, so that this will be enabled per default:

```
cat tools/bazel.rc
build --experimental_local_disk_cache_path=~/.gerritcodereview/bazel-cache/cas
```

**Comment by davido** [comment] 2018-03-14 21:38
@ittaiz @Globegitter home directory resolution (~) should be supported now, see https://github.com/bazelbuild/bazel/pull/4852.

**Comment by davido** [comment] 2018-03-14 22:12
@ulfjack 

> I'd go about it by moving the LruCache to a more generic location, and possibly refactoring its API.

What LruCache are you referencing? Buck triggers cache directory clean after checking on each store operation if dir cache max size was configured and whether or not the current directory size exceeds this limit:

https://github.com/facebook/buck/blob/master/src/com/facebook/buck/artifact_cache/DirArtifactCache.java#L198-L203

Where `deleteOldFiles` is:

https://github.com/facebook/buck/blob/master/src/com/facebook/buck/artifact_cache/DirArtifactCache.java#L317-L332

And directory cleaner is [here](https://github.com/facebook/buck/blob/master/src/com/facebook/buck/util/DirectoryCleaner.java) with this builder:
```
  private DirectoryCleaner newDirectoryCleaner() {
    DirectoryCleanerArgs cleanerArgs =
        DirectoryCleanerArgs.builder()
            .setPathSelector(getDirectoryCleanerPathSelector())
            .setMaxTotalSizeBytes(maxCacheSizeBytes.get())
            .setMaxBytesAfterDeletion((long) (maxCacheSizeBytes.get() * MAX_BYTES_TRIM_RATIO))
            .setMinAmountOfEntriesToKeep(0)
            .build();
```

**Comment by ulfjack** [comment] 2018-03-15 08:33
Apparently I misremembered - I thought we had a LruCache class for the repository cache. Sorry for the confusion.

**Comment by jmmv** [comment] 2020-05-11 18:51
I think this feature is now available via `--disk_cache`? At least the behavior I observe experimentally is what was being asked for here.

**Closed by jmmv** 2020-05-11 18:51 UTC
Labels: P3, team-Local-Exec, type: feature request
