### ISSUE TITLE
ERROR: /usr/local/tensorflow/tensorflow/core/BUILD:853:1: C++ compilation of rule

### ISSUE THREAD

**Issue by nishanthgs** [bazelbuild/bazel#1662] opened 2016-08-19 06:02 UTC
Hi,

I am trying to build tensorflow from source without git clone (cannot have http_proxy)
Following is the error:
# /usr/local/bazel-0.3.0/bazel build -c opt --config=cuda --spawn_strategy=standalone //tensorflow/cc:tutorials_example_trainer --verbose_failures
WARNING: Config values are not defined in any .rc file: cuda
WARNING: Sandboxed execution is not supported on your system and thus hermeticity of actions cannot be guaranteed. See http://bazel.io/docs/bazel-user-manual.html#sandboxing for more information. You can turn off this warning via --ignore_unsupported_sandboxing.
WARNING: /root/.cache/bazel/_bazel_root/e86f6fce5559de9e3e13fb6adb66b858/external/protobuf/WORKSPACE:1: Workspace name in /root/.cache/bazel/_bazel_root/e86f6fce5559de9e3e13fb6adb66b858/external/protobuf/WORKSPACE (@__main__) does not match the name given in the repository's definition (@protobuf); this will cause a build error in future versions.
WARNING: /root/.cache/bazel/_bazel_root/e86f6fce5559de9e3e13fb6adb66b858/external/re2/WORKSPACE:1: Workspace name in /root/.cache/bazel/_bazel_root/e86f6fce5559de9e3e13fb6adb66b858/external/re2/WORKSPACE (@com_googlesource_code_re2) does not match the name given in the repository's definition (@re2); this will cause a build error in future versions.
INFO: Found 1 target...
INFO: From Unknown tensorflow/core/kernels/reader_base.pb.h:
bazel-out/local-opt/genfiles/external/protobuf/src: warning: directory does not exist.
INFO: From Unknown tensorflow/core/example/example.pb.h:
bazel-out/local-opt/genfiles/external/protobuf/src: warning: directory does not exist.
INFO: From Unknown tensorflow/core/example/example.pb.h [for host]:
bazel-out/host/genfiles/external/protobuf/src: warning: directory does not exist.

ERROR: /usr/local/tensorflow/tensorflow/core/BUILD:853:1: undeclared inclusion(s) in rule '//tensorflow/core:lib_internal':
this rule is missing dependency declarations for the following files included by 'tensorflow/core/lib/jpeg/jpeg_handle.cc':
  '/usr/local/jpeg-9a/include/jerror.h'
  '/usr/local/jpeg-9a/include/jinclude.h'
  '/usr/local/jpeg-9a/include/jconfig.h'
  '/usr/local/jpeg-9a/include/jpeglib.h'
  '/usr/local/jpeg-9a/include/jmorecfg.h'
  '/usr/local/jpeg-9a/include/transupp.h'.
Target //tensorflow/cc:tutorials_example_trainer failed to build

Is there any guide/steps on how to include the above to avoid getting into undeclared inclusion(s)

**Comment by davidzchen** [comment] 2016-08-19 07:58
The cause of this error is likely that `/usr/local/jpeg-9a/include` is not one of the builtin include directories configured in the CROSSTOOL config.

Can you try adding a `cxx_builtin_include_directory` for `/usr/local/jpeg-9a/include` to `third_party/gpus/crosstool/CROSSTOOL`?

The eventual fix for this is to implement autodetection for dependent libraries that are installed on the system.

**Comment by nishanthgs** [comment] 2016-08-19 15:39
Hi,

I already had the following in  "third_party/gpus/crosstool/CROSSTOOL"
# TODO(bazel-team): In theory, the path here ought to exactly match the path
  # used by gcc. That works because bazel currently doesn't track files at
  # absolute locations and has no remote execution, yet. However, this will need
  # to be fixed, maybe with auto-detection?
  cxx_builtin_include_directory: "/usr/lib/gcc/"
  cxx_builtin_include_directory: "/usr/local/include"
  cxx_builtin_include_directory: "/usr/include"
  cxx_builtin_include_directory: "/usr/local/cuda-7.5/include"
  cxx_builtin_include_directory: "/usr/local/jpeg-9a/include"
  cxx_builtin_include_directory: "/usr/local/giflib-5.1.4/include"
  cxx_builtin_include_directory: "/usr/local/libpng-1.2.53/include"

**Comment by davidzchen** [comment] 2016-08-22 05:26
This line seems curious:

```
WARNING: Config values are not defined in any .rc file: cuda
```

This seems to suggest that your build is not using TensorFlow's bazel.rc file (which is generated from `tools/bazel.rc.template` by the `./configure` script (specifically, by `util/python/python_config.sh`, which is run by the `./configure` script). Since TensorFlow's `bazel.rc` file specifies to use `third_party/gpus/crosstool/CROSSTOOL` for `--config=cuda`, in your case, the `CROSSTOOL` file that Bazel is actually using is likely Bazel's own `CROSSTOOL` file, which does not have the additional `cxx_builtin_include_directory` entries.

Did you not run the `./configure` script before running your build?

**Comment by nishanthgs** [comment] 2016-08-22 21:24
I was working in a different workspace and overlooked the ./configure, now I go past the above error but stuck with protobuf

ERROR: /usr/local/tensorflow/tensorflow/core/BUILD:927:1: C++ compilation of rule '//tensorflow/core:framework_internal' failed: crosstool_wrapper_driver_is_not_gcc failed: error executing command 
  (cd /root/.cache/bazel/_bazel_root/e86f6fce5559de9e3e13fb6adb66b858/execroot/tensorflow && \
  exec env - \
    PATH=/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/home/ngoshike/bin \
  third_party/gpus/crosstool/clang/bin/crosstool_wrapper_driver_is_not_gcc -U_FORTIFY_SOURCE '-D_FORTIFY_SOURCE=1' -fstack-protector -fPIE -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 -DNDEBUG -ffunction-sections -fdata-sections '-std=c++11' '-frandom-seed=bazel-out/local_linux-opt/bin/tensorflow/core/_objs/framework_internal/tensorflow/core/example/feature_util.o' -iquote . -iquote bazel-out/local_linux-opt/genfiles -iquote external/protobuf -iquote bazel-out/local_linux-opt/genfiles/external/protobuf -iquote external/bazel_tools -iquote bazel-out/local_linux-opt/genfiles/external/bazel_tools -iquote external/highwayhash -iquote bazel-out/local_linux-opt/genfiles/external/highwayhash -iquote external/re2 -iquote bazel-out/local_linux-opt/genfiles/external/re2 -iquote external/eigen_archive -iquote bazel-out/local_linux-opt/genfiles/external/eigen_archive -isystem external/protobuf/src -isystem bazel-out/local_linux-opt/genfiles/external/protobuf/src -isystem external/bazel_tools/tools/cpp/gcc3 -isystem external/highwayhash -isystem bazel-out/local_linux-opt/genfiles/external/highwayhash -isystem external/eigen_archive -isystem bazel-out/local_linux-opt/genfiles/external/eigen_archive -isystem third_party/gpus/cuda/include -isystem bazel-out/local_linux-opt/genfiles/third_party/gpus/cuda/include -fno-exceptions -DEIGEN_AVOID_STL_ARRAY '-DGOOGLE_CUDA=1' -pthread '-DGOOGLE_CUDA=1' -no-canonical-prefixes -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' -fno-canonical-system-headers -MD -MF bazel-out/local_linux-opt/bin/tensorflow/core/_objs/framework_internal/tensorflow/core/example/feature_util.d -c tensorflow/core/example/feature_util.cc -o bazel-out/local_linux-opt/bin/tensorflow/core/_objs/framework_internal/tensorflow/core/example/feature_util.o): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.
tensorflow/core/example/feature_util.cc: In function 'const typename tensorflow::internal::RepeatedFieldTrait<FeatureType>::Type& tensorflow::GetFeatureValues(const string&, const tensorflow::Example&) [with FeatureType = long long int; typename tensorflow::internal::RepeatedFieldTrait<FeatureType>::Type = google::protobuf::RepeatedField<long long int>; std::string = std::basic_string<char>]':
tensorflow/core/example/feature_util.cc:54:67: error: invalid initialization of reference of type 'const google::protobuf::RepeatedField<long long int>&' from expression of type 'const google::protobuf::RepeatedField<long int>'
   return example.features().feature().at(name).int64_list().value();
                                                                   ^
tensorflow/core/example/feature_util.cc: In function 'typename tensorflow::internal::RepeatedFieldTrait<FeatureType>::Type* tensorflow::GetFeatureValues(const string&, tensorflow::Example*) [with FeatureType = long long int; typename tensorflow::internal::RepeatedFieldTrait<FeatureType>::Type = google::protobuf::RepeatedField<long long int>; std::string = std::basic_string<char>]':
tensorflow/core/example/feature_util.cc:62:23: error: cannot convert 'google::protobuf::RepeatedField<long int>*' to 'google::protobuf::RepeatedField<long long int>*' in return
       ->mutable_value();
                       ^
tensorflow/core/example/feature_util.cc: In function 'const typename tensorflow::internal::RepeatedFieldTrait<FeatureType>::Type& tensorflow::GetFeatureValues(const string&, const tensorflow::Example&) [with FeatureType = long long int; typename tensorflow::internal::RepeatedFieldTrait<FeatureType>::Type = google::protobuf::RepeatedField<long long int>; std::string = std::basic_string<char>]':
tensorflow/core/example/feature_util.cc:55:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
tensorflow/core/example/feature_util.cc: In function 'typename tensorflow::internal::RepeatedFieldTrait<FeatureType>::Type* tensorflow::GetFeatureValues(const string&, tensorflow::Example*) [with FeatureType = long long int; typename tensorflow::internal::RepeatedFieldTrait<FeatureType>::Type = google::protobuf::RepeatedField<long long int>; std::string = std::basic_string<char>]':
tensorflow/core/example/feature_util.cc:63:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
Target //tensorflow/cc:tutorials_example_trainer failed to build

**Comment by davidzchen** [comment] 2016-08-31 01:42
de-duping with #1706

**Closed by davidzchen** 2016-08-31 01:42 UTC

**Comment by parth126** [comment] 2017-02-09 07:53
@davidzchen I installed tensorflow using pip and hence did not have an option to run ./configure
How do I solve the problem of "WARNING: Config values are not defined in any .rc file: cuda"

**Comment by NiallC** [comment] 2017-02-18 18:34
I have the same question: Can I enable these optimizations if I installed using pip (and how)?
