### ISSUE TITLE
Compiling on Jetson TX1 aarch64 kernel with arm32 userspace fails

### ISSUE THREAD

**Issue by wtfuzz** [bazelbuild/bazel#1264] opened 2016-05-14 07:09 UTC
```
ubuntu@tegra-ubuntu:~$ uname -a
Linux tegra-ubuntu 3.10.67-g458d45c #1 SMP PREEMPT Mon Feb 8 17:44:18 PST 2016 aarch64 aarch64 aarch64 GNU/Linux
```

protobuf 3.0.0-beta-2 was compiled with --enable-shared=no, and static protoc copied into ~/bazel/third-party/protobuf/protoc-linux-arm32.exe

```
ubuntu@tegra-ubuntu:~/bazel-0.2.2$ ./compile.sh
INFO: You can skip this first step by providing a path to the bazel binary as second argument:
INFO:    ./compile.sh compile /path/to/bazel
🍃  Building Bazel from scratch......
🍃  Building Bazel with Bazel.
ERROR: No toolchain found for cpu 'arm'. Valid cpus are: [
  k8,
  armeabi-v7a,
].
INFO: Elapsed time: 5.387s

Building output/bazel
```

**Comment by kchodorow** [comment] 2016-05-16 13:56
This sounds similar to #1251, based on https://github.com/bazelbuild/bazel/blob/master/tools/cpp/CROSSTOOL#L26-L27 I'm guess we need to make "arm" return k8, too, but assigning to @damienmg for followup since I'm not too familiar with the CROSSTOOL stuff.

**Comment by wtfuzz** [comment] 2016-05-16 14:13
I did get it work. There were a few things that needed to be done. 

This fork compiles on arm:
https://github.com/wtfuzz/bazel

**Comment by wtfuzz** [comment] 2016-05-16 14:22
The main culprit was cc_configure.bzl which defaults to returning "k8" (i386) when it doesn't recognize any other arch.

https://github.com/wtfuzz/bazel/commit/ddc37b2a69b53e54a0664719fe9326925c909422

**Comment by kchodorow** [comment] 2016-05-16 16:08
Great! Would you like to submit it as a pull request?

**Comment by wtfuzz** [comment] 2016-05-16 16:49
I'm traveling this week, but I'll get a PR submitted when I can.

**Comment by damienmg** [comment] 2016-05-17 07:22
Nice! ping me when you send it.

**Comment by syed-ahmed** [comment] 2016-07-05 21:28
Hi,
I ran into a similar error on a Jetson TX1 board. It says "ERROR: No toolchain found for cpu 'unknown'". I will try rebuilding with this change by @wtfuzz. Do I still need to do this step: protobuf 3.0.0-beta-2 was compiled with --enable-shared=no, and static protoc copied into ~/bazel/third-party/protobuf/protoc-linux-arm32.exe? is bazel build limited to arm32 only?

**Comment by dat-ai** [comment] 2017-01-21 06:03
I confirmed that by adding the following lines in `tools/cpp/cc_configure.bzl` helped me fixed the `Error: NO tool-chain found for 'arm'.` 

My hardware is NVIDIA Jetson TK1. (linux armv7l)
```shell
# Add an if statement to  _get_cpu_value()
result = repository_ctx.execute(["uname", "-m"])
machine_cpu = result.stdout.strip()
if machine_cpu in ["arm", "armv7l", "aarch64"]:
	return "arm"
return "k8" if machine in ["amd64", "x86_64", "x64"] else "piii"
```

**Comment by damienmg** [comment] 2017-01-23 09:18
FYI: From the Bazel side, we would be happy to accept those patch as pull request to make your use case work better out of the box :)

**Comment by spidi123q** [comment] 2017-09-29 15:42
download the binary for armv7l(pi 3) with this link below
https://drive.google.com/open?id=0B7NeIJaVzSxIZmZHUnVzZjBjVDg

**Comment by aiuto** [comment] 2020-06-08 16:10
Closing for staleness. We can still take a patch, but so much has changed in 3 years that this might not even be applicable any more.

**Closed by aiuto** 2020-06-08 16:10 UTC
Labels: P3, team-Configurability, type: bug
