### ISSUE TITLE
`'test.log' was not created error` when running Rust example test

### ISSUE THREAD

**Issue by alex** [bazelbuild/bazel#572] opened 2015-11-08 06:16 UTC
The code in `hello_lib/src/lib.rs` doesn't compile:

Specifically the line `assert_eq!("Hi Rust", hello.greeting("Rust"));` is wrong, since `Greeter::greet` doesn't have a return value, it prints.

**Comment by davidzchen** [comment] 2015-11-08 09:23
Thanks for reporting this, @alex!

I don't think the problem is caused by this line:

```rust
assert_eq!("Hi Rust", hello.greeting("Rust"));
```

In this line, `Greeter::greeting()` is called, which returns a `String`. The only test that is known to fail currently is the `rust_bench_test` in `examples/rust/fibonacci` since `Bencher` in `libtest` is unstable. Perhaps I should disable that test for now.

What's curious is that when I run `bazel test //examples/rust/hello_lib:all` on Linux, the tests all pass:

```
❯❯❯ bazel test //examples/rust/hello_lib:all
.....
INFO: Found 2 targets and 3 test targets...
INFO: Elapsed time: 18.917s, Critical Path: 2.23s
//examples/rust/hello_lib:greeting_test                                  PASSED in 0.1s
//examples/rust/hello_lib:hello_lib_doc_test                             PASSED in 0.2s
//examples/rust/hello_lib:hello_lib_test                                 PASSED in 0.2s

Executed 3 out of 3 tests: 3 tests pass.
There were tests whose specified size is too big. Use the --test_verbose_timeout_warnings command line option to see which ones these are.
```

However, on OS X, there are a number of build errors:

```
❯❯❯ bazel clean --expunge && bazel test //examples/rust/hello_lib:all
INFO: Starting clean (this may take a while). Consider using --expunge_async if the clean takes more than several minutes.
......
INFO: Found 2 targets and 3 test targets...
INFO: From Compiling Rust library hello_lib (2 files):
mkdir: bazel-out/local_darwin-fastbuild/bin/examples/rust/hello_lib/hello_lib.deps: File exists
ERROR: /Volumes/Ocean/Projects/google/bazel/examples/rust/hello_lib/BUILD:11:1: error executing shell command: 'set -e; rm -rf bazel-out/local_darwin-fastbuild/bin/examples/rust/hello_lib/hello_lib.deps; mkdir bazel-out/local_darwin-fastbuild/bin/examples/rust/hello_lib/hello_lib.deps
 LD_LIBRARY_PATH=extern...' failed: bash failed: error executing command /bin/bash -c ... (remaining 1 argument(s) skipped): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.
Error reading log file /private/var/tmp/_bazel_dzc/a4c09a1fcefb8b21c5b0e7d7db6f08ba/bazel/bazel-out/local_darwin-fastbuild/testlogs/examples/rust/hello_lib/hello_lib_doc_test/test.log: /private/var/tmp/_bazel_dzc/a4c09a1fcefb8b21c5b0e7d7db6f08ba/bazel/bazel-out/local_darwin-fastbuild/testlogs/examples/rust/hello_lib/hello_lib_doc_test/test.log
FAIL: //examples/rust/hello_lib:hello_lib_doc_test (see /private/var/tmp/_bazel_dzc/a4c09a1fcefb8b21c5b0e7d7db6f08ba/bazel/bazel-out/local_darwin-fastbuild/testlogs/examples/rust/hello_lib/hello_lib_doc_test/test.log).
ERROR: /Volumes/Ocean/Projects/google/bazel/examples/rust/hello_lib/BUILD:35:1: output 'examples/rust/hello_lib/hello_lib_doc_test/test.log' was not created.
ERROR: /Volumes/Ocean/Projects/google/bazel/examples/rust/hello_lib/BUILD:35:1: not all outputs were created.
INFO: Elapsed time: 29.038s, Critical Path: 1.39s
//examples/rust/hello_lib:hello_lib_doc_test                             FAILED in 0.0s

Executed 1 out of 3 tests: 2 fail to build and 1 fails locally.
```

Though, when I run `bazel test //examples/rust/...` on Linux, I also see the error where `test.log` is not getting created but only intermittently.

This seems to be a problem in the rule implementation. I will investigate further.

+ @laurentlb for FYI.

**Comment by davidzchen** [comment] 2015-11-08 23:44
I checked the rule implementation, and the `.deps` dirs are `rm -rf`'ed before they are created. However, it looks like there is some kind of permission issue:

```
rm: bazel-out/local_darwin-fastbuild/bin/examples/rust/hello_lib/hello_lib.deps: Operation not permitted
ERROR: /Volumes/Ocean/Projects/google/bazel/examples/rust/hello_lib/BUILD:19:1: error executing shell command: 'set -e; rm -rf bazel-out/local_darwin-fastbuild/bin/examples/rust/hello_lib/hello_lib.deps; mkdir bazel-out/local_darwin-fastbuild/bin/examples/rust/hello_lib/hello_lib.deps
```

@laurentlb - Have you seen this issue before?

**Comment by kchodorow** [comment] 2015-11-10 16:38
Isn't the output directory non-writable?  Your rules shouldn't be putting stuff there directly (afaik).  working_dir != output_dir.

**Comment by davidzchen** [comment] 2015-11-24 11:09
It turns out the cause of this is that some of the `.deps` dirs created by the test targets have conflicting names and were trying to overwrite each other.

I have a fix for this currently in review.

**Closed** 2015-11-25 10:03 UTC
Labels: bug, P3
