### ISSUE TITLE
Bazel no perms to execute wrapped_ar build error

### ISSUE THREAD

**Issue by vihanb** [bazelbuild/bazel#5346] opened 2018-06-07 20:02 UTC
### Description of the problem / feature request:
When building bazel from the [0.14.0](https://github.com/bazelbuild/bazel/releases/tag/0.14.0) release `bazel-0.14.0-dist.zip`, I run `bash ./configure.sh`  and installation goes well until this happens:

```
🍃  Building Bazel from scratch......
🍃  Building Bazel with Bazel.
INFO: Analysed target //src:bazel (218 packages loaded).
INFO: Found 1 target...
INFO: From Compiling third_party/protobuf/3.4.0/src/google/protobuf/compiler/js/embed.cc [for host]:
third_party/protobuf/3.4.0/src/google/protobuf/compiler/js/embed.cc:37:12: warning: unused variable 'output_file' [-Wunused-const-variable]
const char output_file[] = "well_known_types_embed.cc";
           ^
1 warning generated.
ERROR: /Users/vihan/Downloads/bazel-0/src/main/cpp/BUILD:118:1: Linking of rule '//src/main/cpp:option_processor' failed (Exit -1). Note: Remote connection/protocol failed with: execution failed: wrapped_ar failed: error executing command
  (cd /tmp/bazel_aSZOS8mM/out/execroot/io_bazel && \
  exec env - \
    APPLE_SDK_PLATFORM='' \
    APPLE_SDK_VERSION_OVERRIDE='' \
    PATH=/Users/vihan/lib:/usr/local/cuda/lib:/usr/local/cuda/extras/CUPTI/lib::/usr/local/opt/gpg-agent/bin:/usr/local/opt/findutils/libexec/gnubin:/opt/local/bin:/opt/local/sbin:/usr/local/texlive/2017/bin/x86_64-darwin:/Users/vihan/.cargo/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/share/dotnet:/opt/X11/bin:/Library/Frameworks/Mono.framework/Versions/Current/Commands \
    XCODE_VERSION_OVERRIDE=9.3.0 \
  external/local_config_cc/wrapped_ar rcs bazel-out/darwin-opt/bin/src/main/cpp/liboption_processor.a bazel-out/darwin-opt/bin/src/main/cpp/_objs/option_processor/src/main/cpp/option_processor.o)
Action failed to execute: java.io.IOException: Cannot run program "/tmp/bazel_aSZOS8mM/out/execroot/io_bazel/external/local_config_cc/wrapped_ar" (in directory "/tmp/bazel_aSZOS8mM/out/execroot/io_bazel"): error=13, Permission denied
Target //src:bazel failed to build
INFO: Elapsed time: 66.225s, Critical Path: 10.39s
INFO: 499 processes, local.
FAILED: Build did NOT complete successfully
```

After the build it looks like `/tmp/bazel_aSZOS8mM/out/execroot/io_bazel/external/local_config_cc/wrapped_ar` doesn't exist but that might be due to it getting cleaned up. Since issue was with permissions running with sudo gives same error.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Haven't made any modifications, running on macOS where compiler is clang-5

### What operating system are you running Bazel on?

macos 10.13.4

### What's the output of `bazel info release`?

issue is with building so cannot build bazel.

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

see above

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

building from the release .zip so no git tracking but version 0.14.0 seems to be 5c3f5c9be7fa40d4fb3c35756891fab8483ca406

**Comment by aehlig** [comment] 2018-06-08 07:19
The problem seems OSX specific, as `wrappend_ar` is only used there.

**Comment by meteorcloudy** [comment] 2018-06-08 09:35
@aehlig I don't have a mac machine to reproduce this bug, can you assign this issue to someone more familiar with the mac build?

**Comment by laurentlb** [comment] 2018-06-19 13:17
Can we have an update on this? Does it really block the release of Bazel 0.15?

**Comment by mhlopko** [comment] 2018-06-25 14:02
Friendly ping, plus I can help if needed, this is close to my usual playground :)

**Comment by buchgr** [comment] 2018-06-26 10:54
@mhlopko you can have it :P. I think @c-parsons would be right person to take a look at this.

**Comment by c-parsons** [comment] 2018-06-26 16:07
This looks weird (so I don't know off the top of my head) -- is it that the tool itself doesn't have appropriate permissions, or that the tool is run and doesn't have appropriate permissions to complete its operations?

**Comment by philwo** [comment] 2018-07-03 12:57
This looks like the spurious "Permission denied" error that we have seen on our Mac CI.

@vihanb Can you reproduce this, or did it only happen once?

**Comment by mhlopko** [comment] 2018-07-03 14:39
Welcome back @philwo  :)

**Comment by jin** [comment] 2018-08-01 02:06
We're going into 0.17.0, is this still a blocker for the release?

**Comment by philwo** [comment] 2018-08-01 10:30
I haven't seen it happening on CI anymore.

@buchgr Do you think this is solved, or are we just avoiding triggering it on CI somehow?

**Comment by buchgr** [comment] 2018-08-02 08:54
I believe it disappeared after upgrading to the iMac Pros.

**Comment by philwo** [comment] 2018-08-02 09:19
@buchgr Looks like that money was well invested then :D

**Comment by jin** [comment] 2018-08-02 15:56
I'll remove this from the list of release blockers.

**Comment by jin** [comment] 2019-05-02 17:30
Please reopen or make a new issue if this is still a problem on the latest release.

**Closed by jin** 2019-05-02 17:30 UTC
Labels: breakage, platform: macOS, team-EngProd
