### ISSUE TITLE
Unicode in external repo filenames causes uncaught exception

### ISSUE THREAD

**Issue by AustinSchuh** [bazelbuild/bazel#4084] opened 2017-11-13 21:25 UTC
```
java.lang.RuntimeException: Unrecoverable error while evaluating node 'REPOSITORY_DIRECTORY:@openocd' (requested by nodes 'REPOSITORY:@openocd')
        at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:413)
        at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:352)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.nio.file.InvalidPathException: Malformed input or input contains unmappable characters: /home/austin/.cache/bazel/_bazel_austin/dd758a6cc6943296d5c6a65e2c252c63/external/openocd/usr/share/openocd/scripts/target/к1879xб1я.cfg
        at sun.nio.fs.UnixPath.encode(UnixPath.java:147)
        at sun.nio.fs.UnixPath.<init>(UnixPath.java:71)
        at sun.nio.fs.UnixFileSystem.getPath(UnixFileSystem.java:281)
        at java.io.File.toPath(File.java:2234)
        at com.google.devtools.build.lib.bazel.repository.CompressedTarFunction.decompress(CompressedTarFunction.java:83)
        at com.google.devtools.build.lib.bazel.repository.DecompressorValue.decompress(DecompressorValue.java:76)
        at com.google.devtools.build.lib.bazel.repository.NewHttpArchiveFunction.fetch(NewHttpArchiveFunction.java:74)
        at com.google.devtools.build.lib.rules.repository.RepositoryDelegatorFunction.compute(RepositoryDelegatorFunction.java:190)
        at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:338)
        ... 4 more
```

**Comment by j3parker** [comment] 2017-11-14 02:16
Duplicate of https://github.com/bazelbuild/bazel/issues/1653

**Comment by dslomov** [comment] 2018-01-09 10:45
Closing in favor of #1653

**Closed by dslomov** 2018-01-09 10:45 UTC
Labels: P2, category: extensibility > external repositories, type: bug
