### ISSUE TITLE
Bazel v0.20.0 build fails on s390x 

### ISSUE THREAD

**Issue by Nayana-ibm** [bazelbuild/bazel#7542] opened 2019-02-26 14:38 UTC
### Description of the problem / feature request:

Bazel v0.20.0 build fails on s390x . Until v0.19.0 bazel build successful on s390x

### Feature requests: what underlying problem are you trying to solve with this feature?
We need to build TensorFlow from source hence requires Bazel to be build first on s390x 

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.
On s390x platform , execute: 
 ```
wget https://github.com/bazelbuild/bazel/releases/download/0.20.0/bazel-0.20.0-dist.zip
 unzip bazel-0.20.0-dist.zip
 bash ./compile.sh
```

### What operating system are you running Bazel on?

Ubuntu 18.04 s390x 

### Any other information, logs, or outputs that you want to share?
Error: 
```
ERROR: No toolchain found for cpu 's390x'. Valid toolchains are: [
  stub_armeabi-v7a: --cpu='armeabi-v7a' --compiler='compiler',
  local: --cpu='piii' --compiler='compiler',
  msys_x64_mingw: --cpu='x64_windows' --compiler='mingw-gcc',
  msvc_x64: --cpu='x64_windows' --compiler='msvc-cl',
]
```

Looks like lot of changes are done in v0.20.0 w.r.t. to toolchains .

**Comment by katre** [comment] 2019-03-01 16:27
This is not a configurability issue, it's related to the auto-defined cc toolchains. Re-assigning to teams-cpp.

@Nayana-ibm The 0.20.0 release is a while ago, 0.23.0 was just released. Can you try again with that version?

**Comment by scentini** [comment] 2019-03-01 17:42
@Nayana-ibm Can you try setting `BAZEL_TARGET_CPU` to "s390x" ?

**Comment by Nayana-ibm** [comment] 2019-03-05 08:44
@scentini I have tried setting the s390x however same issue

**Comment by Nayana-ibm** [comment] 2019-03-05 08:44
@katre Tried building latest version 0.23.0, same issue

**Comment by Nayana-ibm** [comment] 2019-03-27 10:10
Today I tried building Bazel v0.24.0 on s390x architecture however build is failing with below error: 

```
ERROR: /out/external/local_config_cc/BUILD:45:1: in cc_toolchain_suite rule @local_config_cc//:toolchain: cc_toolchain_suite '**@local_config_cc//:toolchain' does not contain a toolchain for cpu 's390x'**
[32mAnalyzing:[0m target //src:bazel_nojdk (96 packages loaded, 949 targets configure\
d)
    Fetching @remote_java_tools; fetching
```


Can you please provide commit id through which toolchain code changes are introduced for particular arch like amd64/ppc64le.   so, I can check for code changes on similar lines for s390x. 

(Earlier, until v0.19.0 Bazel build was successful on s390x without any code change)

**Comment by katre** [comment] 2019-03-27 14:06
@local_config_cc//:toolchain from Bazel 0.24.0:
```
$ USE_BAZEL_VERSION=latest bazelisk query --output=build @local_config_cc//:toolchain
2019/03/27 10:02:17 Downloading https://releases.bazel.build/0.24.0/release/bazel-0.24.0-linux-x86_64...
cc_toolchain_suite(
  name = "toolchain",
  toolchains = {"k8|compiler": "@local_config_cc//:cc-compiler-k8", "k8": "@local_config_cc//:cc-compiler-k8", "armeabi-v7a|compiler": "@local_config_cc//:cc-compiler-armeabi-v7a", "armeabi-v7a": "@local_config_cc//:cc-compiler-armeabi-v7a"},
)
```

And from 0.19.0:
```
$ USE_BAZEL_VERSION=0.19.0 bazelisk query --output=build @local_config_cc//:toolchain
2019/03/27 10:03:17 Downloading https://releases.bazel.build/0.19.0/release/bazel-0.19.0-linux-x86_64...
cc_toolchain_suite(
  name = "toolchain",
  toolchains = {"k8|compiler": "@local_config_cc//:cc-compiler-k8", "k8": "@local_config_cc//:cc-compiler-k8", "armeabi-v7a|compiler": "@local_config_cc//:cc-compiler-armeabi-v7a", "armeabi-v7a": "@local_config_cc//:cc-compiler-armeabi-v7a"},
)
```

They look substantially similar, and neither has an entry for s390x.

**Comment by katre** [comment] 2019-03-27 14:11
Without an s390x environment to test in, I'm not sure how to try and reproduce the successful compilation at release 0.19.0. It clearly is getting a valid `cc_toolchain` from somewhere, but even checking out 0.19.0 and grepping the source, I don't see any additional `cc_toolchain_suite` entries for s390x:

```
$ git checkout 0.19.0
...
HEAD is now at f0c844c77a Release 0.19.0 (2018-10-29)
$ git grep -l s390x
scripts/bootstrap/buildenv.sh
site/docs/platforms.md
src/main/java/com/google/devtools/build/lib/analysis/config/AutoCpuConverter.java
src/main/java/com/google/devtools/build/lib/util/CPU.java
src/test/java/com/google/devtools/build/lib/bazel/rules/android/ndkcrosstools/ndk12bfiles.txt
src/test/java/com/google/devtools/build/lib/rules/cpp/CrosstoolConfigurationHelper.java
src/test/shell/testenv.sh
third_party/BUILD
third_party/protobuf/3.6.1/config.guess
third_party/protobuf/3.6.1/config.sub
third_party/protobuf/3.6.1/configure
third_party/protobuf/3.6.1/m4/libtool.m4
third_party/protobuf/3.6.1/third_party/googletest/googlemock/aclocal.m4
third_party/protobuf/3.6.1/third_party/googletest/googlemock/build-aux/config.guess
third_party/protobuf/3.6.1/third_party/googletest/googlemock/build-aux/config.sub
third_party/protobuf/3.6.1/third_party/googletest/googlemock/configure
third_party/protobuf/3.6.1/third_party/googletest/googletest/build-aux/config.guess
third_party/protobuf/3.6.1/third_party/googletest/googletest/build-aux/config.sub
third_party/protobuf/3.6.1/third_party/googletest/googletest/configure
third_party/protobuf/3.6.1/third_party/googletest/googletest/m4/libtool.m4
tools/cpp/BUILD
tools/cpp/CROSSTOOL
tools/cpp/CROSSTOOL.tpl
tools/platforms/BUILD
tools/platforms/platforms.BUILD
```

Unfortunately, a lot of things in the C++ toolchains have changed in the interval from 0.19.0 to 0.24.0.

**Comment by katre** [comment] 2019-03-27 14:18
Okay, I do have a way to reproduce this, which means I can set up to bisect for where the error started, at least.

This works:
```
$ git checkout 0.19.0
...
HEAD is now at f0c844c77a Release 0.19.0 (2018-10-29)
$ USE_BAZEL_VERSION=0.19.0 bazelisk build --cpu=s390x //src:bazel
...
Target //src:bazel up-to-date:
  bazel-bin/src/bazel
INFO: Elapsed time: 250.529s, Critical Path: 239.46s, Remote (0.00% of the time): [queue: 0.00%, setup: 0.00%, process: 0.00%]
INFO: 1774 processes: 1455 linux-sandbox, 1 local, 318 worker.
INFO: Build completed successfully, 1845 total actions
```

And this fails:
```
$ git checkout master
Previous HEAD position was f0c844c77a Release 0.19.0 (2018-10-29)
Switched to branch 'master'
Your branch is up to date with 'origin/master'.
$ USE_BAZEL_VERSION=latest bazelisk build --cpu=s390x //src:bazel
Starting local Bazel server and connecting to it...
ERROR: /usr/local/google/home/jcater/.cache/bazel/_bazel_jcater/a85a0dacd9e20e18c47928db0f1530e0/external/local_config_cc/BUILD:45:1: in cc_toolchain_suite rule @local_config_cc//:toolchain: cc_toolchain_suite '@local_config_cc//:toolchain' does not contain a toolchain for cpu 's390x'
WARNING: errors encountered while analyzing target '//src:bazel': it will not be built
INFO: Analysed target //src:bazel (213 packages loaded, 10318 targets configured).
INFO: Found 0 targets...
ERROR: command succeeded, but not all targets were analyzed
INFO: Elapsed time: 4.988s, Critical Path: 0.02s
INFO: 0 processes.
FAILED: Build did NOT complete successfully
```

Starting a bisect, this will take a while.

**Comment by katre** [comment] 2019-03-27 14:59
Bisect shows the error starts with commit c3fb1db9e4e817e8a911f5b347b30f2674a82f7c, which certainly looks like a likely candidate.

@Nayana-ibm, can you confirm this? On a linux machine, check out bazel at commit c3fb1db9e4e817e8a911f5b347b30f2674a82f7c and also at c3fb1db9e4e817e8a911f5b347b30f2674a82f7c^ (the parent of c3fb1db9e4e817e8a911f5b347b30f2674a82f7c, which is 11642e9d12453357987f645649c75984f96a4f45). In these checkouts, run:

```
$ USE_BAZEL_VERSION=0.19.0 bazelisk build //:bazel-distfile
...
Target //:bazel-distfile up-to-date:
  bazel-genfiles/bazel-distfile.zip
```

And then try using the two distfiles to bootstrap on an actual s390x system.

(Bazelisk install directions are here: https://github.com/philwo/bazelisk, or you can just use a manual install of 0.19.0.)

**Comment by hlopko** [comment] 2019-03-29 07:01
I guess we need to teach autoconfigured C++ toolchain about s390x.

**Comment by Nayana-ibm** [comment] 2019-04-01 12:50
@katre  Thanks for your inputs.  I am trying suggested approach on s390x platform. 

I have cloned the code for commit c3fb1db and tried executing below command : 
`USE_BAZEL_VERSION=0.19.0 bazelisk build //:bazel-distfile`

However getting an error: ` bazelisk: command not found`
 
Then tried getting bazelisk from [here](https://github.com/philwo/bazelisk) but facing issue there too: 
```
go get github.com/philwo/bazelisk
github.com/philwo/bazelisk
src/github.com/philwo/bazelisk/bazelisk.go:460: undefined: os.UserCacheDir

```
On the other hand, tried building code with commit c3fb1db using steps:
```
git clone https://github.com/bazelbuild/bazel
cd bazel 
git checkout c3fb1db9e4e817e8a911f5b347b30f2674a82f7c
bash ./compile.sh
```

But this also gives an error:
`echo 'ERROR: Must specify PROTOC if not bootstrapping from the distribution artifact`

Investigating more on this. 
Could you also let me know if I am missing anything here.

**Comment by katre** [comment] 2019-04-01 14:28
Sorry, the use of bazelisk was just my testing: you shouldn't need to run it.

For calling compile.sh, as you discovered, you can not directly checkout the code and run compile.sh, you first need to create a distribution archive (on a system with a working Bazel), and then use the generated distribution archive to call compile.sh (on your s390x system):

```
user@working-system$ bazel build //:bazel-distfile
...
Target //:bazel-distfile up-to-date:
  bazel-genfiles/bazel-distfile.zip
```

Then copy `bazel-genfiles/bazel-distfile.zip` to the target s390x system:
```
user@s390x-system$ unzip bazel-distfile.zip
user@s390x-system$ ./compile.sh
```

**Comment by srajmane** [comment] 2019-04-12 12:12
@katre I have followed above steps, tried building bazel for suggested commit id   c3fb1db9e4e817e8a911f5b347b30f2674a82f7c using steps mentioned in your comment .
I am facing same issue of **_ERROR: No toolchain found for cpu 's390x'._**
**Could you please suggest us what all changes required to support s390x ?**

**Comment by katre** [comment] 2019-04-12 13:06
Thank you, this confirms that the error started with c3fb1db.

Assigning to @hlopko to suggest the proper fix.

**Comment by guirish** [comment] 2019-04-12 13:11
I observed that the cross compiler support was missing for s390x in below listed files, I added respective changes and could proceed with the build .

Files Modified were:
1) /bazel/tools/cpp/BUILD
2) /bazel/tools/cpp/lib_cc_configure.bzl

But now I am observing other build issue, I am working on a s390x VM having configuration of 4 core CPU and 64GB RAM.

Bazel version : v0.24.1

Build command : 
`env EXTRA_BAZEL_ARGS="--verbose_failures --sandbox_debug --spawn_strategy=standalone --genrule_strategy=standalone --host_javabase=@local_jdk//:jdk" JRE_HOME=/usr/lib/jvm/java-8-openjdk-s390x/jre JAVA_HOME=/usr/lib/jvm/java-8-openjdk-s390x  bash  ./compile.sh`

Issue observed is:

```
Slow read: a 1384856-byte read from /tmp/bazel_s41PzgDb/out/execroot/io_bazel/bazel-out/s390x-opt/bin/src/main/tools/process-wrapper took 6637 ms.
ERROR: /home/test/bazel/src/java_tools/buildjar/java/com/google/devtools/build/buildjar/BUILD:153:1: error executing shell command: '/bin/bash -c set -e;rm -rf bazel-out/host/bin/src/java_tools/buildjar/java/com/google/devtools/build/buildjar/libskylark-deps.jar.build_output bazel-out/host/bin/src/java_tools/buildjar/java/com/go...' failed (Exit 1): bash failed: error executing command
  (cd /tmp/bazel_s41PzgDb/out/execroot/io_bazel && \
  exec env - \
    PATH=/usr/lib/jvm/java//bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin \
  /bin/bash -c 'set -e;rm -rf bazel-out/host/bin/src/java_tools/buildjar/java/com/google/devtools/build/buildjar/libskylark-deps.jar.build_output bazel-out/host/bin/src/java_tools/buildjar/java/com/google/devtools/build/buildjar/libskylark-deps.jar.build_java bazel-out/host/bin/src/java_tools/buildjar/java/com/google/devtools/build/buildjar/libskylark-deps.jar.build_java_list
mkdir bazel-out/host/bin/src/java_tools/buildjar/java/com/google/devtools/build/buildjar/libskylark-deps.jar.build_output bazel-out/host/bin/src/java_tools/buildjar/java/com/google/devtools/build/buildjar/libskylark-deps.jar.build_java
external/local_jdk/bin/javac  -classpath '\''third_party/auto/auto-value-1.6.3rc1.jar:third_party/auto/auto-value-annotations-1.6.3rc1.jar:third_party/error_prone/error_prone_annotations-2.2.0.jar:third_party/guava/guava-25.1-jre.jar:third_party/jcip_annotations/jcip-annotations-1.0-1.jar:third_party/jsr305/jsr-305.jar:third_party/protobuf/3.6.1/libprotobuf_java.jar:third_party/java/jacoco/org.jacoco.core-0.7.5.201505241946.jar:third_party/grpc/grpc-auth-1.10.0.jar:third_party/grpc/grpc-context-1.10.0.jar:third_party/grpc/grpc-core-1.10.0.jar:third_party/grpc/grpc-netty-1.10.0.jar:third_party/grpc/grpc-protobuf-1.10.0.jar:third_party/grpc/grpc-protobuf-lite-1.10.0.jar:third_party/grpc/grpc-stub-1.10.0.jar:third_party/tomcat_annotations_api/tomcat-annotations-api-8.0.5.jar:third_party/java/jdk/langtools/javac-9+181-r4173-1.jar'\'' -d bazel-out/host/bin/src/java_tools/buildjar/java/com/google/devtools/build/buildjar/libskylark-deps.jar.build_output @bazel-out/host/bin/src/java_tools/buildjar/java/com/google/devtools/build/buildjar/libskylark-deps.jar-2.params
external/local_jdk/bin/jar cf bazel-out/host/bin/src/java_tools/buildjar/java/com/google/devtools/build/buildjar/libskylark-deps.jar -C bazel-out/host/bin/src/java_tools/buildjar/java/com/google/devtools/build/buildjar/libskylark-deps.jar.build_output .
touch bazel-out/host/bin/src/java_tools/buildjar/java/com/google/devtools/build/buildjar/libskylark-deps.jar.build_output
')
Execution platform: @bazel_tools//platforms:host_platform
Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
        at java.util.jar.Manifest$FastInputStream.<init>(Manifest.java:367)
        at java.util.jar.Manifest$FastInputStream.<init>(Manifest.java:362)
        at java.util.jar.Manifest.read(Manifest.java:230)
        at java.util.jar.Manifest.<init>(Manifest.java:81)
        at java.util.jar.Manifest.<init>(Manifest.java:73)
        at java.util.jar.JarFile.getManifestFromReference(JarFile.java:199)
        at java.util.jar.JarFile.getManifest(JarFile.java:180)
        at sun.misc.URLClassPath$JarLoader$2.getManifest(URLClassPath.java:992)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:451)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at com.sun.tools.javac.main.Main.resourceMessage(Main.java:610)
        at com.sun.tools.javac.main.Main.compile(Main.java:543)
        at com.sun.tools.javac.main.Main.compile(Main.java:381)
        at com.sun.tools.javac.main.Main.compile(Main.java:370)
        at com.sun.tools.javac.main.Main.compile(Main.java:361)
        at com.sun.tools.javac.Main.compile(Main.java:56)
        at com.sun.tools.javac.Main.main(Main.java:42)
Target //src:bazel_nojdk failed to build
INFO: Elapsed time: 4225.408s, Critical Path: 1939.30s
INFO: 1391 processes: 1391 local.
FAILED: Build did NOT complete successfully

ERROR: Could not build Bazel
```


Any pointer on this will be very helpful. 

Also when I try to rebuild bazel with above command, the build fails as there are existing sym links and I cannot map all these sym links. Can any one suggest on how can I rebuild the same project by deleting the created symlinks.

**Comment by guirish** [comment] 2019-04-15 11:53
> I observed that the cross compiler support was missing for s390x in below listed files, I added respective changes and could proceed with the build .
> 
> Files Modified were:
> 
> 1. /bazel/tools/cpp/BUILD
> 2. /bazel/tools/cpp/lib_cc_configure.bzl
> 
> But now I am observing other build issue, I am working on a s390x VM having configuration of 4 core CPU and 64GB RAM.
> 
> Bazel version : v0.24.1
> 
> Build command :
> `env EXTRA_BAZEL_ARGS="--verbose_failures --sandbox_debug --spawn_strategy=standalone --genrule_strategy=standalone --host_javabase=@local_jdk//:jdk" JRE_HOME=/usr/lib/jvm/java-8-openjdk-s390x/jre JAVA_HOME=/usr/lib/jvm/java-8-openjdk-s390x bash ./compile.sh`
> 
> Issue observed is:
> 
> ```
> Slow read: a 1384856-byte read from /tmp/bazel_s41PzgDb/out/execroot/io_bazel/bazel-out/s390x-opt/bin/src/main/tools/process-wrapper took 6637 ms.
> ERROR: /home/test/bazel/src/java_tools/buildjar/java/com/google/devtools/build/buildjar/BUILD:153:1: error executing shell command: '/bin/bash -c set -e;rm -rf bazel-out/host/bin/src/java_tools/buildjar/java/com/google/devtools/build/buildjar/libskylark-deps.jar.build_output bazel-out/host/bin/src/java_tools/buildjar/java/com/go...' failed (Exit 1): bash failed: error executing command
>   (cd /tmp/bazel_s41PzgDb/out/execroot/io_bazel && \
>   exec env - \
>     PATH=/usr/lib/jvm/java-8-openjdk-s390x/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin \
>   /bin/bash -c 'set -e;rm -rf bazel-out/host/bin/src/java_tools/buildjar/java/com/google/devtools/build/buildjar/libskylark-deps.jar.build_output bazel-out/host/bin/src/java_tools/buildjar/java/com/google/devtools/build/buildjar/libskylark-deps.jar.build_java bazel-out/host/bin/src/java_tools/buildjar/java/com/google/devtools/build/buildjar/libskylark-deps.jar.build_java_list
> mkdir bazel-out/host/bin/src/java_tools/buildjar/java/com/google/devtools/build/buildjar/libskylark-deps.jar.build_output bazel-out/host/bin/src/java_tools/buildjar/java/com/google/devtools/build/buildjar/libskylark-deps.jar.build_java
> external/local_jdk/bin/javac  -classpath '\''third_party/auto/auto-value-1.6.3rc1.jar:third_party/auto/auto-value-annotations-1.6.3rc1.jar:third_party/error_prone/error_prone_annotations-2.2.0.jar:third_party/guava/guava-25.1-jre.jar:third_party/jcip_annotations/jcip-annotations-1.0-1.jar:third_party/jsr305/jsr-305.jar:third_party/protobuf/3.6.1/libprotobuf_java.jar:third_party/java/jacoco/org.jacoco.core-0.7.5.201505241946.jar:third_party/grpc/grpc-auth-1.10.0.jar:third_party/grpc/grpc-context-1.10.0.jar:third_party/grpc/grpc-core-1.10.0.jar:third_party/grpc/grpc-netty-1.10.0.jar:third_party/grpc/grpc-protobuf-1.10.0.jar:third_party/grpc/grpc-protobuf-lite-1.10.0.jar:third_party/grpc/grpc-stub-1.10.0.jar:third_party/tomcat_annotations_api/tomcat-annotations-api-8.0.5.jar:third_party/java/jdk/langtools/javac-9+181-r4173-1.jar'\'' -d bazel-out/host/bin/src/java_tools/buildjar/java/com/google/devtools/build/buildjar/libskylark-deps.jar.build_output @bazel-out/host/bin/src/java_tools/buildjar/java/com/google/devtools/build/buildjar/libskylark-deps.jar-2.params
> external/local_jdk/bin/jar cf bazel-out/host/bin/src/java_tools/buildjar/java/com/google/devtools/build/buildjar/libskylark-deps.jar -C bazel-out/host/bin/src/java_tools/buildjar/java/com/google/devtools/build/buildjar/libskylark-deps.jar.build_output .
> touch bazel-out/host/bin/src/java_tools/buildjar/java/com/google/devtools/build/buildjar/libskylark-deps.jar.build_output
> ')
> Execution platform: @bazel_tools//platforms:host_platform
> Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
>         at java.util.jar.Manifest$FastInputStream.<init>(Manifest.java:367)
>         at java.util.jar.Manifest$FastInputStream.<init>(Manifest.java:362)
>         at java.util.jar.Manifest.read(Manifest.java:230)
>         at java.util.jar.Manifest.<init>(Manifest.java:81)
>         at java.util.jar.Manifest.<init>(Manifest.java:73)
>         at java.util.jar.JarFile.getManifestFromReference(JarFile.java:199)
>         at java.util.jar.JarFile.getManifest(JarFile.java:180)
>         at sun.misc.URLClassPath$JarLoader$2.getManifest(URLClassPath.java:992)
>         at java.net.URLClassLoader.defineClass(URLClassLoader.java:451)
>         at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
>         at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
>         at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
>         at java.security.AccessController.doPrivileged(Native Method)
>         at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
>         at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
>         at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
>         at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
>         at com.sun.tools.javac.main.Main.resourceMessage(Main.java:610)
>         at com.sun.tools.javac.main.Main.compile(Main.java:543)
>         at com.sun.tools.javac.main.Main.compile(Main.java:381)
>         at com.sun.tools.javac.main.Main.compile(Main.java:370)
>         at com.sun.tools.javac.main.Main.compile(Main.java:361)
>         at com.sun.tools.javac.Main.compile(Main.java:56)
>         at com.sun.tools.javac.Main.main(Main.java:42)
> Target //src:bazel_nojdk failed to build
> INFO: Elapsed time: 4225.408s, Critical Path: 1939.30s
> INFO: 1391 processes: 1391 local.
> FAILED: Build did NOT complete successfully
> 
> ERROR: Could not build Bazel
> ```
> Any pointer on this will be very helpful.
> 
> Also when I try to rebuild bazel with above command, the build fails as there are existing sym links and 

Above mentioned issue seams to have resolved after using AdoptJDK 11 version. In the prerequisite [Documentation](https://docs.bazel.build/versions/0.24.0/install-compile-source.html) it states to use JDK version 8 , is it OK to use JDK version >8 ?

**Comment by guirish** [comment] 2019-04-18 13:53
@katre @hlopko 

I am listing below the changes that were required to provide cross compilation support for s390x. Do you want me to raise a PR for same?

* Edit `./tools/cpp/BUILD` file
  ```diff 
  --- ./tools/cpp/BUILD   1980-01-01 00:00:00.000000000 +0000
  +++ ../tools/cpp/BUILD  2019-04-13 10:55:41.967252563 +0000
  @@ -93,7 +93,8 @@
         "x64_windows|compiler": ":cc-compiler-x64_windows",
         "x64_windows_msvc|compiler": ":cc-compiler-x64_windows_msvc",
         "ppc|compiler": ":cc-compiler-ppc",
  -        "k8": ":cc-compiler-local",
  +        "s390x|compiler": ":cc-compiler-s390x",
  +       "k8": ":cc-compiler-local",
         "piii": ":cc-compiler-local",
         "arm": ":cc-compiler-local",
         "aarch64": ":cc-compiler-local",
  @@ -169,6 +170,35 @@
   )

  +cc_toolchain(
  +    name = "cc-compiler-s390x",
  +    all_files = ":empty",
  +    ar_files = ":empty",
  +    as_files = ":empty",
  +    compiler_files = ":empty",
  +    cpu = "s390x",
  +    dwp_files = ":empty",
  +    linker_files = ":empty",
  +    objcopy_files = ":empty",
  +    strip_files = ":empty",
  +    supports_param_files = 1,
  +    toolchain_config = ":local_linux",
  +    toolchain_identifier = "local_linux",
  +)
  +
  +toolchain(
  +    name = "cc-toolchain-s390x",
  +    exec_compatible_with = [
  +        "@bazel_tools//platforms:s390x",
  +    ],
  +    target_compatible_with = [
  +        "@bazel_tools//platforms:s390x",
  +    ],
  +    toolchain = ":cc-compiler-s390x",
  +    toolchain_type = ":toolchain_type",
  +)
  +
  +
  cc_toolchain(
     name = "cc-compiler-armeabi-v7a",
     all_files = ":empty",
     ar_files = ":empty",

  ``` 

* Edit `./tools/cpp/lib_cc_configure.bzl` file

```diff
--- ./tools/cpp/lib_cc_configure.bzl    1980-01-01 00:00:00.000000000 +0000
+++ ../tools/cpp/lib_cc_configure.bzl   2019-04-13 10:56:30.517252563 +0000
@@ -188,6 +188,8 @@
     result = repository_ctx.execute(["uname", "-m"])
     if result.stdout.strip() in ["power", "ppc64le", "ppc", "ppc64"]:
         return "ppc"
+    if result.stdout.strip() in ["s390x"]:
+        return "s390x"
     if result.stdout.strip() in ["arm", "armv7l"]:
         return "arm"
     if result.stdout.strip() in ["aarch64"]:

```

**Comment by katre** [comment] 2019-04-18 13:59
Yes, please feel free to send this as a PR, I'm happy to review it.

It would be nice to also figure out a way to test this so we don't accidentally remove the functionality again, but we can address that separately from your PR.

**Comment by hlopko** [comment] 2019-04-24 08:10
Related, I'm just importing https://github.com/bazelbuild/bazel/pull/8079.

**Comment by Nayana-ibm** [comment] 2019-04-26 09:13
@hlopko Thanks for PR. 
I tried building Bazel current master as well as commit 21941fec589439d5476d2e3899b49917fdc06ea6 using steps below on s390x Ubuntu 16.04:
1. Build Bazel v0.19.0 
 ```
wget https://github.com/bazelbuild/bazel/releases/download/0.19.0/bazel-0.19.0-dist.zip
 unzip bazel-0.19.0-dist.zip
 chmod -R +w .  
 bash ./compile.sh   =>  this builds Bazel and provides binary for v0.19.0.
```

2. Then build latest using steps mentioned in contributing to Bazel [document](https://bazel.build/contributing.html):
```
git clone https://github.com/bazelbuild/bazel.git
cd bazel 
git checkout 21941fec589439d5476d2e3899b49917fdc06ea6  ==> skipped in case of master clone
bazel build //src:bazel
```

Tried  to run `bazel build //:bazel-distfile` as well.

Getting below errors:
```
ERROR: bazel/BUILD:136:1: //:default_host_platform: no such attribute 'parents' in 'platform' rule
ERROR: bazel/BUILD:145:1: //:rbe_ubuntu1604_default: no such attribute 'parents' in 'platform' rule
ERROR: bazel/BUILD:166:1: //:rbe_ubuntu1604_highcpu: no such attribute 'parents' in 'platform' rule
ERROR: error loading package '': Package '' contains errors
```

JDK used: 
```
openjdk version "1.8.0_191"
OpenJDK Runtime Environment (build 1.8.0_191-8u191-b12-2ubuntu0.16.04.1-b12)
OpenJDK 64-Bit Zero VM (build 25.191-b12, interpreted mode)
```

gcc --version
`gcc (Ubuntu 5.4.0-6ubuntu1~16.04.11) 5.4.0 20160609`

Am I missing anything here? Please let me know.

**Comment by hlopko** [comment] 2019-04-26 09:29
Can you bootstrap Bazel v0.24.1 and use that to build Bazel@HEAD? 0.19 is too old, we don't support building Bazel with old Bazel versions, only with the latest one.

**Comment by Nayana-ibm** [comment] 2019-04-26 09:41
@hlopko Unfortunately Bazel build fails on s390x for v0.24.1 as it doesn't have toolchain code support for s390x. The PR got merged 2 days ago. 
Btw I can try building v0.24.1 by manually applying patch which merged through this commit https://github.com/bazelbuild/bazel/commit/21941fec589439d5476d2e3899b49917fdc06ea6

Will share my findings.

**Comment by hlopko** [comment] 2019-04-26 09:47
So the build would also fail with 0.19 :)

You can also create a distribution archive on a supported platform for Bazel@HEAD and use that to bootstrap on s390x. Just run `bazel build //:bazel-distfile`.

**Comment by Nayana-ibm** [comment] 2019-04-26 09:51
Actually build is good with v0.19.0 as toochain changes were introduced later through this commit: https://github.com/bazelbuild/bazel/commit/c3fb1db9e4e817e8a911f5b347b30f2674a82f7c
This was confirmed by @katre 

So my plan was to create a distribution archive for Bazel@HEAD using Bazel v0.19.0 
Now am trying to build v0.24.1 by applying patch manually.

**Comment by Nayana-ibm** [comment] 2019-04-26 11:05
@hlopko 

Build of v0.24.1 failed with below error: 
```
Building Bazel with Bazel.
ERROR: /tmp/bazel_n4dju30y/out/external/bazel_tools/tools/jdk/BUILD:443:14: Configurable attribute "actual" doesn't match this configuration: Could not find a JDK for host execution environment, please explicitly provide one using `--host_javabase.`
ERROR: Analysis of target '//src:bazel_nojdk' failed; build aborted:

/tmp/bazel_n4dju30y/out/external/bazel_tools/tools/jdk/BUILD:443:14: Configurable attribute "actual" doesn't match this configuration: Could not find a JDK for host execution environment, please explicitly provide one using `--host_javabase.`

FAILED: Build did NOT complete successfully (68 packages loaded, 489 targets c\
onfigured)
ERROR: Could not build Bazel
```

JDK used:

```
openjdk version "1.8.0_191"
OpenJDK Runtime Environment (build 1.8.0_191-8u191-b12-2ubuntu0.16.04.1-b12)
OpenJDK 64-Bit Zero VM (build 25.191-b12, interpreted mode)
```
JAVA_HOME and PATH is all set 

Now, trying with `env EXTRA_BAZEL_ARGS="--host_javabase=@local_jdk//:jdk" bash ./compile.sh`
Is it correct?

**Comment by hlopko** [comment] 2019-12-06 14:22
This is probably quite obsolete. Please open a new bug with Bazel > 1.0 if this is still a problem.

**Closed by hlopko** 2019-12-06 14:22 UTC
Labels: P3, team-Rules-CPP, type: feature request
