### ISSUE TITLE
Regression: bazel 3.2.0 + glob allow_empty=false + android ndk fails

### ISSUE THREAD

**Issue by iphydf** [bazelbuild/bazel#11518] opened 2020-05-28 13:25 UTC
### Description of the problem:

As of bazel 3.2.0, passing `--incompatible_disallow_empty_glob` fails for android builds using NDK r16b:

```
glob pattern 'ndk/sources/third_party/vulkan/src/build-android/jniLibs/armeabi/libVkLayer_*.so' didn't match anything, but allow_empty is set to False.
```

There is armeabi-v7a, but no armeabi. This works fine with bazel 3.1.0.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

I don't have a minimal repro, but essentially: pass `--incompatible_disallow_empty_glob` and have an android_ndk_repository.

### What operating system are you running Bazel on?

Debian GNU/Linux.

### What's the output of `bazel info release`?

release 3.2.0

###  Have you found anything relevant by searching the web?

No (I did look, but nothing so far).

### Any other information, logs, or outputs that you want to share?

I have not found a workaround for this. I tried `--fat_apk_cpu=armeabi-v7a`, but that doesn't fix it.

**Comment by jin** [comment] 2020-05-29 07:06
While this is something that should be fixed before enabling the breaking change in https://github.com/bazelbuild/bazel/issues/8195, I don't think it's recommended to use an un-flipped `--incompatible` flag for day to day use. Usually, it's because we haven't provided migration tooling or fixed breaking changes with Bazel's own code (like this issue).

**Comment by laurentlb** [comment] 2020-07-16 19:57
Who should look at this?
This issue will prevent the flag flip planed for Bazel 4.0.

**Comment by laurentlb** [comment] 2020-07-22 12:28
@ahumesky

This breaks the Examples repository (see https://buildkite.com/bazel/bazelisk-plus-incompatible-flags/builds/571#58b644b5-222b-4768-93d3-f23f9397d6ca).

**Comment by laurentlb** [comment] 2020-08-11 12:35
ping?

**Comment by laurentlb** [comment] 2020-09-01 15:10
@jin @ahumesky @timpeut
Do you know anyone who could look at this?

**Comment by ahumesky** [comment] 2020-12-03 17:31
#8195 has been moved to 5.0, so we can look at this for next quarter

**Comment by limdor** [comment] 2022-04-24 17:59
The problem is still present and it is in this line https://github.com/bazelbuild/bazel/pull/15330/files#diff-ac45a531edff6b8e6694f669184fc3625c869c84710142175e2caae08e159a9dL197

**Comment by ahumesky** [comment] 2024-12-13 21:39
`--incompatible_disallow_empty_glob` has been rolled out

**Closed by ahumesky** 2024-12-13 21:39 UTC
Labels: type: bug, P2, team-Android
