### ISSUE TITLE
Platform/toolchain support for Java rules

### ISSUE THREAD

**Issue by gregestren** [bazelbuild/bazel#6521] opened 2018-10-25 20:14 UTC
Tracking issue on [Bazel Configurability Roadmap](https://bazel.build/roadmaps/configuration.html)

Goal:
* Java toolchains can be defined with Bazel's generic [toolchain machinery](https://docs.bazel.build/versions/master/toolchains.html)
* Java rules read these toolchains
* Java rules resolve properly against [platforms](https://docs.bazel.build/versions/master/platforms.html)

**Comment by gregestren** [comment] 2018-10-25 20:16
@katre / @aituo . - can you provide better info about the path forward?

**Comment by hlopko** [comment] 2019-02-06 13:04
CC @hlopko :)

**Comment by gregestren** [comment] 2019-04-26 21:51
**April '19 update:**:

I think all three items above are now ready with `--experimental_disallow_legacy_java_toolchain_flags`. Is there anything left for this issue aside from having appropriate toolchain and platform instances defined in good places?

Also, what's the path for this being available non-experimentally?

@iirina @cushon

**Comment by cushon** [comment] 2019-04-26 23:23
> Is there anything left for this issue aside from having appropriate toolchain and platform instances defined in good places?

Not as far as I know. We're using it internally and I'm going to flip `--experimental_disallow_legacy_java_toolchain_flags` soon.

I think @iirina owns the migration for bazel.

**Comment by katre** [comment] 2020-05-11 17:01
This is a duplicate of #4592, closing it in favor of that issue.

**Closed by katre** 2020-05-11 17:01 UTC
Labels: P1, team-Configurability
