### ISSUE TITLE
IllegalArgumentException if no local jdk installed

### ISSUE THREAD

**Issue by buchgr** [bazelbuild/bazel#7953] opened 2019-04-05 08:13 UTC
Trying to build Bazel on a system without a local jdk installed makes the server crash with an `IllegalArgumentException`. I used bazel 0.24.1 on Ubuntu 16.04.
```
bazel build src:bazel
Extracting Bazel installation...
Starting local Bazel server and connecting to it...
INFO: Invocation ID: 4949c21e-daca-423f-962c-5291aafff93b
INFO: Analysed target //src:bazel (209 packages loaded, 10205 targets configured).
INFO: Found 1 target...
ERROR: /root/.cache/bazel/_bazel_root/51c0732f028c406d4dede835941e8efd/external/bazel_tools/tools/jdk/BUILD:299:1: SkylarkAction external/bazel_tools/tools/jdk/platformclasspath.jar failed (Exit 1) java failed: error executing command external/remotejdk10_linux/bin/java -XX:+IgnoreUnrecognizedVMOptions '--add-exports=jdk.compiler/com.sun.tools.javac.platform=ALL-UNNAMED' -cp ... (remaining 4 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
Exception in thread "main" java.lang.IllegalArgumentException: external/local_jdk
        at jdk.compiler/com.sun.tools.javac.file.Locations$SystemModulesLocationHandler.isCurrentPlatform(Unknown Source)
        at jdk.compiler/com.sun.tools.javac.file.Locations$SystemModulesLocationHandler.update(Unknown Source)
        at jdk.compiler/com.sun.tools.javac.file.Locations$SystemModulesLocationHandler.handleOption(Unknown Source)
        at jdk.compiler/com.sun.tools.javac.file.Locations.handleOption(Unknown Source)
        at jdk.compiler/com.sun.tools.javac.file.BaseFileManager.handleOption(Unknown Source)
        at jdk.compiler/com.sun.tools.javac.file.BaseFileManager$2.handleFileManagerOption(Unknown Source)
        at jdk.compiler/com.sun.tools.javac.main.Option.process(Unknown Source)
        at jdk.compiler/com.sun.tools.javac.main.Option.handleOption(Unknown Source)
        at jdk.compiler/com.sun.tools.javac.file.BaseFileManager.handleOption(Unknown Source)
        at jdk.compiler/com.sun.tools.javac.main.Arguments.doProcessArgs(Unknown Source)
        at jdk.compiler/com.sun.tools.javac.main.Arguments.processArgs(Unknown Source)
        at jdk.compiler/com.sun.tools.javac.main.Arguments.init(Unknown Source)
        at jdk.compiler/com.sun.tools.javac.api.JavacTool.getTask(Unknown Source)
        at DumpPlatformClassPath.dumpJDK9AndNewerBootClassPath(DumpPlatformClassPath.java:106)
        at DumpPlatformClassPath.main(DumpPlatformClassPath.java:67)
Caused by: java.nio.file.NoSuchFileException: external/local_jdk
        at java.base/sun.nio.fs.UnixException.translateToIOException(Unknown Source)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(Unknown Source)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(Unknown Source)
        at java.base/sun.nio.fs.UnixFileSystemProvider.isSameFile(Unknown Source)
        at java.base/java.nio.file.Files.isSameFile(Unknown Source)
        ... 15 more
Target //src:bazel failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 21.169s, Critical Path: 8.74s
INFO: 15 processes: 14 linux-sandbox, 1 local.
FAILED: Build did NOT complete successfully
```

**Comment by cushon** [comment] 2019-04-05 20:19
This is a dupe of #6118.

**Closed by cushon** 2019-04-05 20:19 UTC

**Comment by chickenandpork** [comment] 2020-07-13 19:03
If google sent you here because you've hit this issue, note that bazelbuild/bazel#7324 was not merged.

bazelbuild/bazel#6993 (https://github.com/bazelbuild/bazel/issues/6993#issuecomment-452954429) recommends either `--javabase=@embedded_jdk//:jdk` or `--javabase=@bazel_tools//tools/jdk:remote_jdk`

I found `bazel coverage --javabase=@bazel_tools//tools/jdk:remote_jdk11 //...` (s/remote_jdk/remote_jdk11/) works 2020-07-13.

**Comment by ittaiz** [comment] 2022-10-30 10:51
FYI what helped me with both IJWB and java-tutorial in the examples was `--tool_java_runtime_version=remotejdk_11 --java_runtime_version=remotejdk_11 --java_language_version=8 --tool_java_language_version=11`.
It's a shame a simple bazel build fails and one needs to deep dive into google...

**Comment by fmeum** [comment] 2022-10-30 11:19
@ittaiz In a clean docker container, I get the following error message when running `bazel build --define=ij_product=intellij-2021.2 //ijwb:ijwb_bazel_zip` in the IntelliJ plugin repo:
```
ERROR: /root/.cache/bazel/_bazel_root/7ea648a2bbff69b0d649932276a3d0ed/external/local_jdk/BUILD.bazel:2:10: in fail_rule rule @local_jdk//:jdk: 
Traceback (most recent call last):
	File "/root/.cache/bazel/_bazel_root/7ea648a2bbff69b0d649932276a3d0ed/external/bazel_tools/tools/jdk/fail_rule.bzl", line 19, column 13, in _fail_rule_impl
		fail("%s %s" % (ctx.attr.header, ctx.attr.message))
Error in fail: Auto-Configuration Error: Cannot find Java binary bin/java in /root/.cache/bazel/_bazel_root/install/cbf972266931ad9fad1857441b832915/embedded_tools/tools/jdk/nosystemjdk; either correct your JAVA_HOME, PATH or specify Java from remote repository (e.g. --java_runtime_version=remotejdk_11
```

That looks pretty decent. Is it possible that you are seeing https://github.com/bazelbuild/bazel/issues/15452 instead?

**Comment by ittaiz** [comment] 2022-10-30 11:27
It's possible.
It's a bit long so I'll try and skim it again to see if I can tell if I'm indeed like that person or not.
Thanks.

**Comment by ittaiz** [comment] 2022-10-30 11:35
@fmeum which version are you using? I'm using 5.3.2
and indeed `JAVA_HOME` isn't set

**Comment by fmeum** [comment] 2022-10-30 11:36
Try with 6.0.0rc1, which includes one further improvement to this error message. If that still raises an exception without any additional info, that would be a new issue.
