### ISSUE TITLE
Installation became corrupt on Windows

### ISSUE THREAD

**Issue by benvanik** [bazelbuild/bazel#2833] opened 2017-04-16 21:57 UTC
Running release 0.4.5 on Windows 8.1.
I've been using bazel without issue for a few weeks. I last invoked it successfully ~24hrs earlier and then when I went to invoke it just now got the following error:

```
λ bazel [...]
Error: corrupt installation: file 'C:\Users\Ben\AppData\Local\Temp/_bazel_Ben/install/90e1e9f8d81688fd3cc9a8cf18c2ad4e/_embedded_binaries/A-server.jar' missing. Please remove 'C:\Users\Ben\AppData\Local\Temp/_bazel_Ben/install/90e1e9f8d81688fd3cc9a8cf18c2ad4e' and try again.
```

Unfortunately I followed the directions without hesitating and deleted the path without first checking what it looked like. It fixed the issue and bazel was able to re-extract itself and function however now I can't say what the state of the install folder was.

I see a few other issues that have been filed with this error message but were closed/fixed. Wanted to open something up in case there was either a new variant or an unfixed underlying issue.

**Comment by laszlocsomor** [comment] 2017-04-24 08:34
Thanks for reporting this issue!

Bazel reports this error when the last modification time (mtime) of a file in the installation directory changes. When bazel installs itself by extracting the embedded files, bazel also sets the files' timestamps to a time in the future. If the files are modified the mtime will be set to the present. This is a simple way to detect accidental changes to these files.

Could you have possibly modified `A-server.jar`?

**Comment by laszlocsomor** [comment] 2017-09-04 07:37
Duplicate of https://github.com/bazelbuild/bazel/issues/3618

**Closed by laszlocsomor** 2017-09-04 07:37 UTC
Labels: category: multi-platform > windows, type: bug, Under investigation

**Comment by ccyyy** [comment] 2018-03-06 14:01
Is there a solution to this problem?

**Comment by laszlocsomor** [comment] 2018-03-06 14:15
@ccyyy : Deleting the directory, as the error message advises, will get Bazel working again.

**Comment by laszlocsomor** [comment] 2018-03-06 14:16
You can also change the output directory with `--output_user_root`.
