### ISSUE TITLE
Installing java jdk1.8.0_131.jdk on mac results in bazel failing to run

### ISSUE THREAD

**Issue by paladox** [bazelbuild/bazel#3009] opened 2017-05-15 17:26 UTC
Please provide the following information. The more we know about your system and use case, the more easily and likely we can help.

### Description of the problem / feature request / question:
Install the latest java 8 from oracles websites for mac OS X 10.12.4.

_If asking a question or requesting a feature, also tell us about the underlying problem you're trying to solve._

### Environment info
* Operating System:
mac osx 10.12.4

* Bazel version (output of `bazel info release`):
0.4.5

* If `bazel info release` returns "development version" or "(@non-git)", please tell us what source tree you compiled Bazel from; git commit hash is appreciated (`git rev-parse HEAD`):

###  Have you found anything relevant by searching the web?
(e.g. [StackOverflow answers](http://stackoverflow.com/questions/tagged/bazel),
[GitHub issues](https://github.com/bazelbuild/bazel/issues),
email threads on the [`bazel-discuss`](https://groups.google.com/forum/#!forum/bazel-discuss) Google group)

### Anything else, information or logs or outputs that would be helpful?
(If they are large, please upload as attachment or provide link).

i get this error

bazel build release
WARNING: Sandboxed execution is not supported on your system and thus hermeticity of actions cannot be guaranteed. See http://bazel.build/docs/bazel-user-manual.html#sandboxing for more information. You can turn off this warning via --ignore_unsupported_sandboxing.
ERROR: in target '@bazel_tools//tools/jdk:jdk': no such package '@local_jdk//': Expected directory at /Library/Java/JavaVirtualMachines/jdk1.8.0_112.jdk/Contents/Home but it does not exist.
which is true as i removed that directory as i updated java but java -version shows the correct version.

**Comment by philwo** [comment] 2017-05-15 18:48
I think your running Bazel server might still refer to the old, removed JDK. If you do "bazel shutdown" in your workstation (or reboot your computer) and run the command again, it should work.

Please report back if that helped!

**Comment by paladox** [comment] 2017-05-15 19:07
Oh. I just did a symlink. Didn't know there was a bagel shutdown.

**Comment by ittaiz** [comment] 2017-05-16 06:50
Philipp,
So by design when one upgrades java they will need to shutdown the Bazel
server?

**Comment by philwo** [comment] 2017-05-16 09:18
@damienmg @ulfjack I have a feeling this is related to bugs like "I upgraded my Xcode version and now Bazel can't build anything", which we discussed on the mailing list some time ago. Do we have a tracking bug for that?

**Comment by damienmg** [comment] 2017-05-16 11:36
I don't think we have a tracking bug for it. The local_jdk repository predate the environment work and even the Skylark repository work. Maybe we should rewrite it in Skylark to allow to do detection of the jdk with correct invalidation, /cc @kchodorow.

I also believe a shutdown might not be enough (but it is certainly necessary because java.home is not going to be updated). A Wipeout of the cache might be needed.

**Comment by ulfjack** [comment] 2017-05-16 12:55
@ittaiz I would call it a bug, not a feature, so I wouldn't say that this is 'by design'. :-)

**Comment by philwo** [comment] 2019-07-29 12:50
@iirina I think this has been fixed in the meantime, but maybe you could give it a quick look?

**Comment by meisterT** [comment] 2020-05-15 10:32
Closing since there was no response.

**Closed by meisterT** 2020-05-15 10:32 UTC
Labels: P3, team-Rules-Java, type: bug
