### ISSUE TITLE
.bzl file will be loaded twice if using @<workspace_name>label  from the external repo

### ISSUE THREAD

**Issue by dslomov** [bazelbuild/bazel#3493] opened 2017-08-02 20:55 UTC
Consider:
```python
bar$ cat WORKSPACE 
workspace(name = "bar")

new_local_repository(
    name = "foo",
    build_file = "foo.BUILD",
    path = "../foo"
)

$ cat foo.BUILD 
load("@bar//:sum.bzl", "sum")

package(default_visibility = ["//visibility:public"])

sum(
    name = "value",
    number = 3,
)

```
Now we are in the situation where there are two different labels for sum.bzl within the same workspace (`//:sum.bzl` and `@bar//:sum.bzl), so we actually load the same .bzl file twice, oblivious to the fact that it is one and the same file.

That causes e.g. declared providers to no be equal.

See also https://groups.google.com/d/msg/bazel-discuss/7ZCPvG3pXns/YgEZfiJRAAAJ

**Comment by dslomov** [comment] 2017-08-09 09:48
Easy workaround: use `load("@//:sum.bzl", "sum")` instead of  `load("@bar//:sum.bzl", "sum")` to reference things in the main workspace.

I am sure there is more bugs than this one related to the fact that we have two different labels that should be logically equivalent. I think we should just eliminate 'reference main workspace by its name in labels' mechanism.

**Comment by dslomov** [comment] 2017-08-09 09:49
Lowering pri.

**Comment by abergmeier-dsfishlabs** [comment] 2017-08-10 14:43
>  I think we should just eliminate 'reference main workspace by its name in labels' mechanism.

IIUC this mechanism is needed for `load`s in `bzl`-files to work even if these are getting pulled in from another workspace. At least that is what we use it for extensively.

**Comment by evanj** [comment] 2018-04-23 13:16
I ran into this while working on [our own Python rules](https://github.com/TriggerMail/rules_pyz). Thanks for the workaround! For future searchability, the error message this caused was:

```
<target @pypi_asn1crypto//:lib> (rule 'pyz_library') doesn't contain declared provider 'PyZProvider'
```

**Comment by evanj** [comment] 2018-06-06 13:19
I believe this is a duplicate of #3115

**Comment by dkelmer** [comment] 2018-07-12 20:57
Duplicate of #3115

**Closed by dkelmer** 2018-07-12 20:57 UTC
Labels: P2, category: extensibility > skylark, type: bug
