### ISSUE TITLE
cquery returns incorrect cached results

### ISSUE THREAD

**Issue by cmumford** [bazelbuild/bazel#15967] opened 2022-07-25 12:22 UTC
### Description of the bug:

Subsequent runs of `bazel cquery` do not always return the same results as the first run.

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Run the following script:

```sh
#!/bin/bash -e

git clone https://skia.googlesource.com/skia
cd skia
python3 tools/git-sync-deps

echo ""
echo "first query"
bazel cquery --noimplicit_deps 'kind("rule", deps(//:skia_public))' --output textproto > query1.pb.txt

echo ""
echo "second query"
bazel cquery --noimplicit_deps 'kind("rule", deps(//:skia_public) + deps(//src/...) + deps(//modules/...))' --output textproto > query2.pb.txt

echo ""
echo "third query"
bazel cquery --noimplicit_deps 'kind("rule", deps(//:skia_public))' --output textproto > query3.pb.txt

echo ""
echo "Query results:"
ls -l *.txt
```

Here is the query script output:

```
first query
Starting local Bazel server and connecting to it...
Loading: 
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
    currently loading: 
Loading: 0 packages loaded
    currently loading: 
Loading: 0 packages loaded
    currently loading: 
Loading: 0 packages loaded
    currently loading: 
Analyzing: target //:skia_public (1 packages loaded, 0 targets configured)
Analyzing: target //:skia_public (36 packages loaded, 10 targets configured)
Analyzing: target //:skia_public (36 packages loaded, 10 targets configured)
Analyzing: target //:skia_public (83 packages loaded, 1292 targets configured)
Analyzing: target //:skia_public (83 packages loaded, 1297 targets configured)
Analyzing: target //:skia_public (83 packages loaded, 1297 targets configured)
Analyzing: target //:skia_public (83 packages loaded, 1297 targets configured)
INFO: Analyzed target //:skia_public (84 packages loaded, 9334 targets configured).
INFO: Found 1 target...
INFO: Elapsed time: 60.307s
INFO: 0 processes.
INFO: Build completed successfully, 0 total actions
INFO: Build completed successfully, 0 total actions

second query
Loading: 
Loading: 0 packages loaded
Loading: 82 packages loaded
    currently loading: modules/canvaskit
Loading: 82 packages loaded
    currently loading: modules/canvaskit
Loading: 82 packages loaded
    currently loading: modules/canvaskit
Analyzing: 331 targets (83 packages loaded, 0 targets configured)
Analyzing: 331 targets (152 packages loaded, 18498 targets configured)
Analyzing: 331 targets (159 packages loaded, 18914 targets configured)
Analyzing: 331 targets (298 packages loaded, 22199 targets configured)
Analyzing: 331 targets (298 packages loaded, 22199 targets configured)
INFO: Analyzed 331 targets (299 packages loaded, 24711 targets configured).
INFO: Found 331 targets...
INFO: Elapsed time: 52.243s
INFO: 0 processes.
INFO: Build completed successfully, 0 total actions
INFO: Build completed successfully, 0 total actions

third query
Loading: 
Loading: 0 packages loaded
Analyzing: target //:skia_public (0 packages loaded, 0 targets configured)
INFO: Analyzed target //:skia_public (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
INFO: Elapsed time: 0.268s
INFO: 0 processes.
INFO: Build completed successfully, 0 total actions
INFO: Build completed successfully, 0 total actions

Query results:
-rw-r--r--  1 cmumford  primarygroup    47501 Jul 25 05:10 RELEASE_NOTES.txt
-rw-r--r--  1 cmumford  primarygroup   777450 Jul 25 05:15 query1.pb.txt
-rw-r--r--  1 cmumford  primarygroup  9624567 Jul 25 05:16 query2.pb.txt
-rw-r--r--  1 cmumford  primarygroup  3865825 Jul 25 05:16 query3.pb.txt
-rw-r--r--  1 cmumford  primarygroup      793 Jul 25 05:10 requirements.txt
-rw-r--r--  1 cmumford  primarygroup      437 Jul 25 05:10 whitespace.txt
```

### Which operating system are you running Bazel on?

macOS Monterey 12.4 (on Apple silicon)

### What is the output of `bazel info release`?

release 5.2.0

### What's the output of `git remote get-url origin; git rev-parse master; git rev-parse HEAD` ?

```text
https://skia.googlesource.com/skia
5999b4e5381098e1834d5bfab453b0f1a0f73f88
5999b4e5381098e1834d5bfab453b0f1a0f73f88

Note Skia's default branch is "main".
```

### Have you found anything relevant by searching the web?

No

### Any other information, logs, or outputs that you want to share?

It looks like prior results are being inserted into the current query response. If `bazel shutdown` is run before each cquery then the third query returns the same response as the first.

**Comment by gregestren** [comment] 2022-07-25 19:31
Quick feedback:

- Could this be the *Non-deterministic output* limitation mentioned at https://bazel.build/docs/cquery#known-issues?

**Comment by cmumford** [comment] 2022-07-25 20:30
Yep - that sure sounds like it. Do you know if there is an open issue on that? This does appear to be a duplicate.

**Comment by gregestren** [comment] 2022-07-25 20:38
I'm not sure what the right end state is.

This is a user-confusing working by design. `cquery` gets its results from the Skyframe cache, which intentionally persists across builds for performance. The tradeoff is the inconsistency you see.

Would querying with `--discard_analysis_cache` suffice?

https://github.com/bazelbuild/bazel/blob/f22e63deef43141f08b63cc0210fc9b9e2fded1d/src/main/java/com/google/devtools/build/lib/analysis/AnalysisOptions.java#L49-L50

That's basically telling bazel that you want the consistency and are okay with the performance hit.

**Comment by cmumford** [comment] 2022-07-25 21:02
I'm new to Bazel, but I found this behavior quite confusing and spent more than a few hours trying to figure out what was wrong with my query. It doesn't seem correct to return rules outside of the bounds of the query. I would favor correctness over performance.

Does query retrieve its results from elsewhere - i.e. not the Skyframe cache?

My preference would be to not add a `--discard_analysis_cache` as this seems like an issue that will be addressed at some point in the future. I didn't understand the docs recommended workaround to:

> add `--test_arg=&lt;whatever&gt;` to your build command

So I'm working around this by doing a `bazel shutdown` (which is a big hammer).

**Comment by gregestren** [comment] 2022-07-25 21:15
I agree this behavior is subtle and confusing. All things being equal we don't want two identical `bazel` invocations to produce different results. That's usually true, but this is a glaring exception.

`query` indeed has its own process that it runs anew each time you invoke it, `query` can be slower because of that.

This is a resources tradeoff issue. Resolving this for `cquery` would necessarily slow down builds in general.

Would a line in your bazelrc like

    cquery  --discard_analysis_cache

hide the nuance well enough? That would mean it would apply automatically without having to remember it.

**Comment by cmumford** [comment] 2022-07-26 20:34
Sure, that's a fine option - as long as I don't need to:

```
if (bazel version >= XXX) {
   use --discard_analysis_cache
} else {
  stop bazel server
}
```

If I didn't have to deal with the version then I'd use your proposed option - otherwise I'd stick with stopping bazel.

**Comment by sdtwigg** [comment] 2022-07-26 20:56
Do you see consistent behavior when the `--universe_scope` flag is explicitly used?

In my mental model of cquery, the use of `--universe_scope` is essentially required; however, as a performance and slight UX optimization (e.g. debugging/looking at a previous build) allow it to be omitted and essentially presume a value based on the previous build.

**Comment by cmumford** [comment] 2022-07-27 14:16
@sdtwigg I didn't fully grok the docs on `--universe_scope`. I ran it with an empty string as well as `//:skia_public`. Both worked, but the second query still included cached results from the prior query.

**Comment by gregestren** [comment] 2022-07-27 15:11
FYI I wouldn't expect you to have to gate `--discard_analysis_cache` on the bazel version.

**Comment by gregestren** [comment] 2022-08-01 18:34
Adjusted the tags - not to dismiss the value of your report but because this bug is more of a design conversation now vs. a clear issue to fix. Always happy to adjust again depending on how the conversation goes. I do understand the confusion.

**Closed** 2022-08-19 15:29 UTC
Labels: P4, type: support / not a bug (process), team-Configurability, untriaged
