### ISSUE TITLE
[7.1.0] Remove flag guarding for the AndroidIdeInfo provider

### ISSUE THREAD

**Issue by mai93** [bazelbuild/bazel#20927] opened 2024-01-18 01:16 UTC
### Commit IDs

916c3f5a649926f07a8390893539b560646a192e

### Category

team-Android

### Reviewers

@iancha1992

**Comment by bazel-io** [comment] 2024-01-18 02:06
Cherry-pick was attempted, but failed to push. Please check if the branch, cp_ondemand_20927-7.1.0, already exists
cc: @bazelbuild/triage

**Comment by iancha1992** [comment] 2024-01-18 02:30
Dupe of https://github.com/bazelbuild/bazel/issues/20931

**Closed** 2024-01-18 02:29 UTC
