### ISSUE TITLE
3.1.0 compiles, but fails to copy the executable

### ISSUE THREAD

**Issue by rokstrnisa** [bazelbuild/bazel#1585] opened 2016-07-29 15:10 UTC
In the snippet below, `/home/rok/bazel/output/bazel` version is `3.0.0`.

    $ ./compile.sh compile /home/rok/bazel/output/bazel
    ...
    Target //src:bazel.exe up-to-date:
      C:/tools/msys64/var/tmp/Bazel/-kBpKhQY/execroot/bazel/bazel-out/local_windows_msys64-fastbuild/bin/src/bazel.exe
    INFO: Elapsed time: 94.226s, Critical Path: 92.09s
    cp: cannot stat ‘bazel-bin/src/bazel.exe’: No such file or directory

Manually copying `C:/tools/msys64/var/tmp/Bazel/-kBpKhQY/execroot/bazel/bazel-out/local_windows_msys64-fastbuild/bin/src/bazel.exe` to `/home/rok/bazel/output/` completes the process.

**Comment by damienmg** [comment] 2016-07-29 15:13
I am betting it is because it fails to create the convenience symlinks. /cc @dslomov @meteorcloudy

**Comment by dslomov** [comment] 2016-08-02 10:58
Where does `bazel-bin` point to? (it should be a junction) If you delete it, does the build succeed?

**Comment by rokstrnisa** [comment] 2016-08-02 11:30
Before making changes, `bazel-bin` pointed to `/tmp/bazel.kOJU1LOP/out/execroot/bazel/bazel-out/local_windows_msys64-fastbuild/bin`.

Deleting `bazel-bin` and re-running the build (with 0.3.0 and of 0.3.0, since it was failing the same way with re-build of 0.3.0) worked, with some warnings:

    WARNING: failed to create one or more convenience symlinks for prefix 'bazel-':
      cannot create symbolic link bazel-out -> C:/tools/msys64/var/tmp/Bazel/-kBpKhQY/execroot/bazel/bazel-out:  Command failed cmd.exe /c mklink /J "C:\tools\msys64\home\rok\bazel\bazel-out" "C:\tools\msys64\var\tmp\Bazel\-kBpKhQY\execroot\bazel\bazel-out"
      cannot create symbolic link bazel-bazel -> C:/tools/msys64/var/tmp/Bazel/-kBpKhQY/execroot/bazel:  Command failed cmd.exe /c mklink /J "C:\tools\msys64\home\rok\bazel\bazel-bazel" "C:\tools\msys64\var\tmp\Bazel\-kBpKhQY\execroot\bazel"
      cannot create symbolic link bazel-testlogs -> C:/tools/msys64/var/tmp/Bazel/-kBpKhQY/execroot/bazel/bazel-out/local_windows_msys64-fastbuild/testlogs:  Command failed cmd.exe /c mklink /J "C:\tools\msys64\home\rok\bazel\bazel-testlogs" "C:\tools\msys64\var\tmp\Bazel\-kBpKhQY\execroot\bazel\bazel-out\local_windows_msys64-fastbuild\testlogs"
      cannot create symbolic link bazel-genfiles -> C:/tools/msys64/var/tmp/Bazel/-kBpKhQY/execroot/bazel/bazel-out/local_windows_msys64-fastbuild/genfiles:  Command failed cmd.exe /c mklink /J "C:\tools\msys64\home\rok\bazel\bazel-genfiles" "C:\tools\msys64\var\tmp\Bazel\-kBpKhQY\execroot\bazel\bazel-out\local_windows_msys64-fastbuild\genfiles".
    Target //src:bazel.exe up-to-date:
      C:/tools/msys64/var/tmp/Bazel/-kBpKhQY/execroot/bazel/bazel-out/local_windows_msys64-fastbuild/bin/src/bazel.exe

After the build, `bazel-bin` pointed to `/var/tmp/Bazel/-kBpKhQY/execroot/bazel/bazel-out/local_windows_msys64-fastbuild/bin`.

**Comment by meteorcloudy** [comment] 2016-09-16 09:18
We are constantly getting this bug on ci slaves. Although it's not blocking anything, we should fix it.

**Comment by meteorcloudy** [comment] 2016-09-16 09:56
https://github.com/bazelbuild/bazel/blob/master/src/main/java/com/google/devtools/build/lib/vfs/WindowsFileSystem.java#L66
We are still using this hacky way to create junction, we should switch to JNI.

**Comment by laszlocsomor** [comment] 2016-09-29 08:37
Duplicate of #1829

**Closed** 2016-09-29 08:37 UTC
Labels: category: multi-platform > windows, P1, type: bug
