### ISSUE TITLE
--experimental_output_paths=strip cannot be disabled for built-in mnemonics

### ISSUE THREAD

**Issue by DavidANeil** [bazelbuild/bazel#21092] opened 2024-01-26 22:01 UTC
### Description of the feature request:

When this flag is enabled, it doesn't respect the execution requirements for a hardcoded list of `SUPPORTED_MNEMONICS`, meaning they cannot be disabled by the end user if they are misbehaving.

### Which category does this issue belong to?

Java Rules

### What underlying problem are you trying to solve with this feature?

Our custom starlark actions work great with this flag, so we would like to use it for those, but the built-in rules are misbehaving (see #21091)

**Comment by iancha1992** [comment] 2024-01-26 22:14
Dupe of https://github.com/bazelbuild/bazel/issues/21091?

**Comment by fmeum** [comment] 2024-01-26 22:38
@iancha1992 It's not a dupe, these are two separate bugs affecting the same feature.

**Comment by fmeum** [comment] 2024-01-26 23:40
I submitted https://github.com/bazelbuild/bazel/pull/21093 to fix this.

**Closed** 2024-02-21 19:26 UTC
Labels: type: bug, P2, team-Configurability

**Comment by iancha1992** [comment] 2024-02-22 21:29
A fix for this issue has been included in [Bazel 7.1.0 RC1](https://releases.bazel.build/7.1.0/rc1/index.html). Please test out the release candidate and report any issues as soon as possible. Thanks!
