### ISSUE TITLE
Bazel 1.2.1 with Xcode CLT is broken

### ISSUE THREAD

**Issue by philwo** [bazelbuild/bazel#10328] opened 2019-11-28 06:32 UTC
### Description of the problem / feature request:

Bazel 1.2.1 with Xcode CLT is broken.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

This works:
```
philwo@takaramono:src/bazel ‹master›$ sudo xcode-select -s /Applications/Xcode.app

philwo@takaramono:src/bazel ‹master›$ xcode-select -p
/Applications/Xcode.app/Contents/Developer

philwo@takaramono:src/bazel ‹master›$ gcc --version
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/4.2.1
Apple clang version 11.0.0 (clang-1100.0.33.12)
Target: x86_64-apple-darwin19.0.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

philwo@takaramono:src/bazel ‹master›$ bazel clean && bazel shutdown && bazel build //src:bazel
```

This fails:
```
philwo@takaramono:src/bazel ‹master›$ sudo xcode-select -s /Library/Developer/CommandLineTools 

philwo@takaramono:src/bazel ‹master›$ xcode-select -p
/Library/Developer/CommandLineTools

philwo@takaramono:src/bazel ‹master›$ gcc --version
Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/4.2.1
Apple clang version 11.0.0 (clang-1100.0.33.12)
Target: x86_64-apple-darwin19.0.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin

philwo@takaramono:src/bazel ‹master›$ bazel clean && bazel shutdown && bazel build //src:bazel
INFO: Starting clean.
Starting local Bazel server and connecting to it...
DEBUG: /private/var/tmp/_bazel_philwo/7a01905b4627ca044e5e3f5ad5b14d26/external/bazel_toolchains/rules/rbe_repo/checked_in.bzl:103:9: rbe_ubuntu1804_java11 not using checked in configs as detect_java_home was set to True 
DEBUG: /private/var/tmp/_bazel_philwo/7a01905b4627ca044e5e3f5ad5b14d26/external/bazel_toolchains/rules/rbe_repo/checked_in.bzl:103:9: rbe_ubuntu1604_java8 not using checked in configs as detect_java_home was set to True 
ERROR: /private/var/tmp/_bazel_philwo/7a01905b4627ca044e5e3f5ad5b14d26/external/local_config_cc/BUILD:63:5: in apple_cc_toolchain rule @local_config_cc//:cc-compiler-darwin_x86_64: Xcode version must be specified to use an Apple CROSSTOOL. If your Xcode version has changed recently, verify that "xcode-select -p" is correct and then try: "bazel shutdown" to re-run Xcode configuration
ERROR: Analysis of target '//src:bazel' failed; build aborted: Analysis of target '@local_config_cc//:cc-compiler-darwin_x86_64' failed; build aborted
INFO: Elapsed time: 2.411s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (130 packages loaded, 1028 targets configured)
    currently loading: third_party/protobuf/3.6.1
```

### What operating system are you running Bazel on?

macOS 10.15.1

### What's the output of `bazel info release`?

release 1.2.1

**Comment by keith** [comment] 2019-11-28 11:48
This might not be a regression? If you look in the generated BUILD file what is the content? I submitted a related fix months ago https://github.com/bazelbuild/bazel/pull/8975

**Comment by philwo** [comment] 2019-11-28 11:51
Oh wow, it has been broken for that long? :sweat_smile: 

It definitely used to work in the past, but because we don't test that config on CI, it tends to break every now and then and then we have to fix it again. :| I'll see if we can at least test with `xcode-select` pointing to CLT, but I remember some breakages in the past where it would work if you had both Xcode and CLT installed and used xcode-select to point to CLT, but it would break if you *only* had CLT installed. That config is unfortunately something we can't test, because it would require to keep workers without Xcode around, which we don't have the resources for.

**Comment by hlopko** [comment] 2019-12-06 13:42
You're not running bazel clean --expunge after changing the default Xcode, is that intentional? Can you repro with --expunge? If not, I'd close this issue as WAI.

Since Bazel external repositories are not recomputed with bazel clean, cc_configure will not try to re-detect Xcode and will result in the failure you observe. --expunge will also clear repositories, will force cc_configure, and should build correctly.

Recently we added bazel reconfigure command, that should fix this as well (but I haven't tried it yet).

**Comment by hlopko** [comment] 2020-02-04 07:45
Actually I think we can close this one, philwo please complain if that's not right.

**Closed by hlopko** 2020-02-04 07:45 UTC
Labels: P1, team-Rules-Server, type: bug
