### ISSUE TITLE
Error using CPU constraints doesn't give useful guidance.

### ISSUE THREAD

**Issue by AustinSchuh** [bazelbuild/bazel#3900] opened 2017-10-13 00:34 UTC
I've got a cc_binary marked with restricted_to = ["@//tools:armhf-debian"]

When I try to explicitly build it, I get an error which doesn't help me understand what to do.  (ie, this target can't be built for k8, so don't try) .  I guess I'd also expect this to be an ERROR since I'm explicitly asking for something that makes no sense, but that's not a huge deal.

```
austin[114440] aschuh-debian-z620 (bazel-0.6.0) ~/local/peloton-tech/vehicle
$ bazel build -c opt //vehicle/radio:echo_arm --cpu=k8 --verbose_failures
INFO: Analysed target //vehicle/radio:echo_arm.
INFO: Found 1 target...
INFO: Writing explanation of rebuilds to '/tmp/bazel_explain.log'
Target //vehicle/radio:echo_arm failed to build
Target //vehicle/radio:echo_arm failed to build
INFO: Elapsed time: 1.275s, Critical Path: 0.06s
INFO: Build completed successfully, 1 total action
```

**Comment by mhlopko** [comment] 2017-10-18 09:02
Duplicate of https://github.com/bazelbuild/bazel/issues/3898

**Closed by mhlopko** 2017-10-18 09:02 UTC
Labels: category: rules > C++
