### ISSUE TITLE
I/O error during sandboxed execution (Directory not empty)

### ISSUE THREAD

**Issue by ekuefler** [bazelbuild/bazel#2235] opened 2016-12-13 20:22 UTC
### Description of the problem:

I'm trying to update the [Groovy](https://github.com/bazelbuild/rules_groovy) rules for Bazel 0.4.2 (I last tried with Bazel 0.3.1). I'm now getting an error that seems to happen when extracting `groovy_sdk_artifact` (created via `new_http_artifact`):

```
+ bazel build //...
____Loading package: @bazel_tools//tools/cpp
____Loading package: @bazel_tools//tools/jdk
____Loading package: @local_jdk//
____Loading package: @local_config_cc//
____Loading complete.  Analyzing...
____Loading package: @bazel_tools//third_party/java/jdk/langtools
____Downloading http://bazel-mirror.storage.googleapis.com/dl.bintray.com/groovy/maven/apache-groovy-binary-2.4.4.zip: 11,419,648 bytes
____Downloading http://bazel-mirror.storage.googleapis.com/dl.bintray.com/groovy/maven/apache-groovy-binary-2.4.4.zip: 32,472,463 bytes
____Loading package: @groovy_sdk_artifact//
____Found 3 targets...
____Building...
____[0 / 5] BazelWorkspaceStatusAction stable-status.txt
____[1 / 7] Writing file example/src/main/hello/Hello.jar-2.params
____[5 / 7] Groovyc example/src/main/hello/libHello-lib-impl.jar
ERROR: /home/ci/workspace/PR-rules_groovy/BAZEL_VERSION/latest/PLATFORM_NAME/ubuntu_15.10-x86_64/example/src/main/hello/BUILD:3:1: error executing shell command: 'set -e;rm -rf bazel-out/local-fastbuild/bin/example/src/main/hello/libHello-lib-impl.jar.build_output
mkdir -p bazel-out/local-fastbuild/bin/example/src/main/hello/libHello-lib-impl.jar.build_outpu...' failed: I/O error during sandboxed execution: /home/ci/.cache/bazel/_bazel_ci/231d4ae62e8244366f92a9298de2f8ba/bazel-sandbox/417a70b1-80c0-437c-8a44-ff80966a7f69-0/execroot/ubuntu_15.10-x86_64/external/groovy_sdk_artifact/groovy-2.4.4/indy (Directory not empty).
____Building complete.
____Elapsed time: 5.326s, Critical Path: 0.33s
```

It seems like it's trying to extract a directory that already exists and that's creating a conflict for some reason. I don't think this is due to the logic in my Groovy rules (I get the same error if I make my script a no-op by replacing [this line](https://github.com/bazelbuild/rules_groovy/blob/master/groovy/groovy.bzl#L79) with an empty string), it looks like it has to do with setting up the external artifact in the sandbox.

### If possible, provide a minimal example to reproduce the problem:

I created a pull request in the groovy repro, you can see the error in Jenkins: https://github.com/bazelbuild/rules_groovy/pull/7. Should work if you patch in that same PR locally, which just creates a minimal Hello World target to run the Groovy rules.

### Environment info
* Operating System: Ubuntu Linux

* Bazel version (output of `bazel info release`): `release 0.4.2` (not present in 0.3.1)

###  Have you found anything relevant by searching the web? (e.g. GitHub issues, email threads in the [bazel-discuss@googlegroups.com](https://groups.google.com/forum/#!forum/bazel-discuss) archive)

Maybe related to https://github.com/bazelbuild/bazel/issues/2226? Fix to that doesn't look like it will address this problem though.

### Anything else, information or logs or outputs that would be helpful?

See [Jenkins output](http://ci.bazel.io/job/PR-rules_groovy/2/BAZEL_VERSION=latest,PLATFORM_NAME=ubuntu_15.10-x86_64/console)

**Comment by ashishpant** [comment] 2016-12-23 22:58
I am having the same issue as well.

```
> bazel build com/test:GroovyDemo 
INFO: Found 1 target...
ERROR: /home/ashish/Bhawisya/java/com/test/BUILD:10:1: error executing shell command: 'set -e;rm -rf bazel-out/local-fastbuild/bin/com/test/libGroovyDemo-impl.jar.build_output
mkdir -p bazel-out/local-fastbuild/bin/com/test/libGroovyDemo-impl.jar.build_output
export JAVA_HOME=externa...' failed: I/O error during sandboxed execution: /home/ashish/.cache/bazel/_bazel_ashish/6498e5ab91011605b049315d6b91209b/bazel-sandbox/d1b64c35-d5ba-47f8-8050-9fa46a68a030-0/execroot/java/external/groovy_sdk_artifact/groovy-2.4.4/indy (Directory not empty).
Target //com/test:GroovyDemo failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 0.121s, Critical Path: 0.01s
```

Trying to use bazel with groovy for the first time.
bazel with java and cpp work perfectly fine.

```
> bazel info release
release 0.4.3

> lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.1 LTS
Release:	16.04
Codename:	xenial
```

The code i am trying to compile is a helloworld program in groovy.

**Comment by ashishpant** [comment] 2016-12-24 03:56
bazel however works with scala with the following workspace config.

```
git_repository(
    name = "io_bazel_rules_scala",
    remote = "git://github.com/bazelbuild/rules_scala",
    commit = "5dbb873654aa8cd706aec802745c157da057ceb5"
)
```
So I think the problem above may be related to the bzl file itself.

**Comment by mattmoor** [comment] 2017-02-17 19:12
@steren This looks like the same issue I just opened on the groovy repo: https://github.com/bazelbuild/rules_groovy/issues/8

**Comment by ekuefler** [comment] 2017-02-20 19:11
Yeah, this is breaking the Groovy rules, it would be great if someone could prioritize checking into this

**Comment by philwo** [comment] 2017-02-20 19:42
I'll investigate tomorrow. I know nothing about Groovy, but hope I can reproduce on my machine using the example provided (thanks for that!).

**Comment by ekuefler** [comment] 2017-02-20 19:56
Thanks - pretty sure the problems are happening before anything Groovy-specific goes on, but I'm happy to look further if you can help narrow it a bit.

**Comment by ekuefler** [comment] 2017-03-04 23:08
Friendly ping :)

**Comment by philwo** [comment] 2017-03-08 15:22
@ekuefler I didn't have time to check this out yet, but it's the next thing I'll focus on. I have to get one feature for Bazel ready and a failure on Windows has been holding me up for over a week now. It's close to completion now though. Sorry for the delay :(

**Comment by ekuefler** [comment] 2017-03-09 05:58
No problem, I'll watch here for updates.

**Comment by philwo** [comment] 2017-03-22 12:55
FYI, I've started on Monday to work through all open sandbox bugs and will try to fix them during this week.

**Comment by robbiexperiel** [comment] 2017-05-10 23:14
Friendly ping. I just tested against bazel master and I'm still seeing the issue. Let me know there's anything I can do to help investigate.

**Comment by philwo** [comment] 2018-07-19 12:38
Closing, because I'm pretty sure this was fixed a long time ago.

**Closed by philwo** 2018-07-19 12:38 UTC
Labels: P3, category: sandboxing, type: bug
