### ISSUE TITLE
rules_closure is failing with OS X sandbox even with network allowed

### ISSUE THREAD

**Issue by damienmg** [bazelbuild/bazel#1715] opened 2016-09-02 14:02 UTC
So there is no way to bind a service locally. "requires-network" does not work on genrule.

**Comment by philwo** [comment] 2016-09-02 16:41
Communication with localhost should work even when sandboxed. Not sure why it doesn't work here, the log is not very verbose.

If it turns out that disabling network access by default is unfeasible, I propose to make it opt-in instead. (After all, you rarely use the network "accidentally" and usually know what you're getting into regarding hermeticity and reproducibility.)

**Comment by hermione521** [comment] 2016-09-05 08:18
Please explain which test tries to bind a service locally and how. It would be easier for me to debug, since I see no action denied in my system log.

**Comment by hermione521** [comment] 2016-09-05 08:48
I tried with all network allowed, and still get the same error. It seems the bug belongs to phantomjs: https://github.com/ariya/phantomjs/issues/13876
If we want to make it work, I think we have to disable sandbox for these tests. (Also ask rust users to disable sandbox :( )

**Comment by damienmg** [comment] 2016-09-05 09:07
Ok in which case we should file a bug to rules_closure, ping @jart on it.

**Comment by jart** [comment] 2016-09-05 19:00
Closure Rules starts up a local web server inside PhantomJS when doing web testing. It seems that if only a port is specified, it will bind to 0.0.0.0 by default. If I changed it to bind to 127.0.0.1, would that fix the sandbox issue?

**Comment by jart** [comment] 2016-09-05 19:14
Jenkins is reporting no issue with my pull request that attempts to fix this. So I'm going to assume this is fixed once I submit. If that's not the case, please re-open.

**Comment by jart** [comment] 2016-09-05 20:14
Nope. It seems changing to 127.0.0.1 didn't help 😢

**Comment by philwo** [comment] 2016-09-05 21:01
If it's a bug in PhantomJS, we'll have to find a workaround in Bazel. I think "requires-network" should work for genrules - we should investigate this tomorrow.

**Comment by hermione521** [comment] 2016-09-06 09:16
It's not related to "requires-network", because it fails with network allowed.

**Comment by damienmg** [comment] 2016-09-06 09:17
What about just setting that genrule to local for now. Since it seems like the problem is from PhatomJS, there is not much we can do, is there?

**Comment by jart** [comment] 2016-09-06 21:11
Just to make sure we're clear, this only applies to the genrule? It doesn't apply to my test rules which use PhantomJS?

**Closed** 2016-09-09 16:39 UTC
Labels: category: sandboxing, P1, type: bug
