### ISSUE TITLE
bazel test fails: generate-xml.sh failed

### ISSUE THREAD

**Issue by hhmitchell** [bazelbuild/bazel#20620] opened 2023-12-20 07:38 UTC
### Description of the bug:

I am just setting up some toy examples to use with bazel, and a very basic python unittest fails with `bazel test`. If I run the binary that is built, it seems fine and running directly with `python` also works.

I encounter the same error in setting up an example C++ unittest, so this is not specific to python.

### Which category does this issue belong to?

Core

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

```
$ bazel test python/...
Starting local Bazel server and connecting to it...
INFO: Analyzed target //python:foo_test (71 packages loaded, 624 targets configured).
ERROR: /tmp/code/python/BUILD:1:8: Testing //python:foo_test failed: (Exit 1): generate-xml.sh failed: error executing TestRunner command (from target //python:foo_test) external/bazel_tools/tools/test/generate-xml.sh bazel-out/k8-fastbuild/testlogs/python/foo_test/test.log bazel-out/k8-fastbuild/testlogs/python/foo_test/test.xml 0 1

Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
Target //python:foo_test up-to-date:
  bazel-bin/python/foo_test
INFO: Elapsed time: 8.364s, Critical Path: 0.06s
INFO: 7 processes: 7 internal.
ERROR: Build did NOT complete successfully
//python:foo_test                                                     NO STATUS

Executed 0 out of 1 test: 1 was skipped.

$ cat MODULE.bazel
module(
  name = "newcode",
  repo_name = "newcode",
)

$ cat python/BUILD 
py_test(
    name = "foo_test",
    srcs = ["foo_test.py"],
)

$ cat python/foo_test.py 
import unittest

class FooTest(unittest.TestCase):
    def test_me(self):
        self.assertEqual(False, True)


if __name__ == '__main__':
    unittest.main()

$ ./bazel-bin/python/foo_test
F
======================================================================
FAIL: test_me (__main__.FooTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/code/./bazel-bin/python/foo_test.runfiles/_main/python/foo_test.py", line 5, in test_me
    self.assertEqual(False, True)
AssertionError: False != True

----------------------------------------------------------------------
Ran 1 test in 0.000s

FAILED (failures=1)

$ python python/foo_test.py 
F
======================================================================
FAIL: test_me (__main__.FooTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/code/python/foo_test.py", line 5, in test_me
    self.assertEqual(False, True)
AssertionError: False != True

----------------------------------------------------------------------
Ran 1 test in 0.000s

FAILED (failures=1)
```

### Which operating system are you running Bazel on?

Linux Mint 21.2

### What is the output of `bazel info release`?

release 7.0.0

### If `bazel info release` returns `development version` or `(@non-git)`, tell us how you built Bazel.

N/A

### What's the output of `git remote get-url origin; git rev-parse master; git rev-parse HEAD` ?

```text
N/A
```

### Have you found anything relevant by searching the web?

No

**Comment by tjgq** [comment] 2023-12-20 14:06
Do you get any interesting output if you manually run

```$(bazel info output_base)/external/bazel_tools/tools/test/generate-xml.sh bazel-out/k8-fastbuild/testlogs/python/foo_test/test.log bazel-out/k8-fastbuild/testlogs/python/foo_test/test.xml 0 1```

after the test has failed?

**Comment by hhmitchell** [comment] 2023-12-21 07:04
I don't know if it's interesting, but this is what I get:
```
$ $(bazel info output_base)/external/bazel_tools/tools/test/generate-xml.sh bazel-out/k8-fastbuild/testlogs/python/foo_test/test.log bazel-out/k8-fastbuild/testlogs/python/foo_test/test.xml 0 1
/tmp/bazel/2e33a927fc55645f1b587fb14bd1a5e5/external/bazel_tools/tools/test/generate-xml.sh: line 102: TEST_BINARY: unbound variable
```

**Comment by hhmitchell** [comment] 2023-12-22 04:57
FWIW, it works with `USE_BAZEL_VERSION=7.0.0-pre.20231018.3 bazel test python/...`. But I don't see `generate-xml.sh` having changed in a long time.

**Comment by tjgq** [comment] 2024-01-03 13:10
@hhmitchell If it works with 7.0.0-pre.20231018.3, can you use `bazelisk --bisect=7.0.0-pre.20231018.3..7.0.0 test python/...` to identify the Bazel commit where it broke?

**Comment by hhmitchell** [comment] 2024-01-12 17:56
@tjgq Thanks -- bisect fingered this commit: https://github.com/bazelbuild/bazel/commit/fe85936f7d38c4a279eec78eee7371b37f800000

I don't really understand what this is about sufficiently, but I can say toggling `--incompatible_sandbox_hermetic_tmp` does fix this for me:

```
$ bazel test --cache_test_results=no  python/...                                        
INFO: Analyzed target //python:foo_test (0 packages loaded, 0 targets configured).
ERROR: /home/henry/temp/bazel/python/BUILD:1:8: Testing //python:foo_test failed: (Exit 1): generate-xml.sh failed: error executing TestRunner command (from target //python:foo_test) external/bazel_tools/tools/test/generate-xml.sh bazel-out/k8-fastbuild/testlogs/python/foo_test/test.log bazel-out/k8-fastbuild/testlogs/python/foo_test/test.xml 0 1

Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
Target //python:foo_test failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 0.090s, Critical Path: 0.02s
INFO: 2 processes: 2 internal.
ERROR: Build did NOT complete successfully
//python:foo_test                                                     NO STATUS

Executed 0 out of 1 test: 1 was skipped.

$ bazel test --cache_test_results=no --incompatible_sandbox_hermetic_tmp=true python/...
INFO: Analyzed target //python:foo_test (0 packages loaded, 0 targets configured).
ERROR: /home/henry/temp/bazel/python/BUILD:1:8: Testing //python:foo_test failed: (Exit 1): generate-xml.sh failed: error executing TestRunner command (from target //python:foo_test) external/bazel_tools/tools/test/generate-xml.sh bazel-out/k8-fastbuild/testlogs/python/foo_test/test.log bazel-out/k8-fastbuild/testlogs/python/foo_test/test.xml 0 1

Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
Target //python:foo_test failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 0.094s, Critical Path: 0.02s
INFO: 2 processes: 2 internal.
ERROR: Build did NOT complete successfully
//python:foo_test                                                     NO STATUS

Executed 0 out of 1 test: 1 was skipped.

$ bazel test --cache_test_results=no --incompatible_sandbox_hermetic_tmp=false python/...
INFO: Analyzed target //python:foo_test (0 packages loaded, 0 targets configured).
INFO: Found 1 test target...
Target //python:foo_test up-to-date:
  bazel-bin/python/foo_test
INFO: Elapsed time: 0.194s, Critical Path: 0.11s
INFO: 2 processes: 2 linux-sandbox.
INFO: Build completed successfully, 2 total actions
//python:foo_test                                                        PASSED in 0.1s

Executed 1 out of 1 test: 1 test passes.
There were tests whose specified size is too big. Use the --test_verbose_timeout_warnings command line option to see which ones these are.

$ bazel test --cache_test_results=no --incompatible_sandbox_hermetic_tmp=true python/... 
INFO: Analyzed target //python:foo_test (0 packages loaded, 0 targets configured).
ERROR: /home/henry/temp/bazel/python/BUILD:1:8: Testing //python:foo_test failed: (Exit 1): generate-xml.sh failed: error executing TestRunner command (from target //python:foo_test) external/bazel_tools/tools/test/generate-xml.sh bazel-out/k8-fastbuild/testlogs/python/foo_test/test.log bazel-out/k8-fastbuild/testlogs/python/foo_test/test.xml 0 1

Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
Target //python:foo_test failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 0.096s, Critical Path: 0.02s
INFO: 2 processes: 2 internal.
ERROR: Build did NOT complete successfully
//python:foo_test                                                     NO STATUS

Executed 0 out of 1 test: 1 was skipped.
```

**Comment by fmeum** [comment] 2024-01-12 19:08
@hhmitchell Could you test with `USE_BAZEL_VERSION=476e183da5a1d41bb83f2bace5f078864c406f6e`? This is the latest commit on the `release-7.0.1`, which has many fixes for issues caused by this flag.

**Comment by hhmitchell** [comment] 2024-01-12 20:31
Yes, that works -- thanks! Looking forward to that release.

**Comment by fmeum** [comment] 2024-01-12 20:44
Thanks for the confirmation! I will close this as a duplicate then.

**Closed** 2024-01-12 20:44 UTC
Labels: type: bug, untriaged, team-Core
