### ISSUE TITLE
http://bazel.io/contributing.html is totally messed-up

### ISSUE THREAD

**Issue by damienmg** [bazelbuild/bazel#880] opened 2016-02-11 15:27 UTC
could it be related to the switch of Github to jekyll 3?

**Comment by davidzchen** [comment] 2016-02-11 20:51
This was caused by the recent change that was submitted to switch the Markdown renderer to Kramdown. Seems that Kramdown behaves differently for fenced code blocks inside of lists.

**Comment by davidzchen** [comment] 2016-02-11 22:40
I have rolled back the change that switched the renderer to Markdown and pushed the changes. This is now fixed.

**Closed by davidzchen** 2016-02-11 22:40 UTC
Labels: bug, Documentation, P1
