### ISSUE TITLE
Release - March 2018 - Target RC date: 2018-03-01 - name: 0.12.0

### ISSUE THREAD

**Issue by dslomov** [bazelbuild/bazel#4582] opened 2018-02-05 15:20 UTC

**Comment by dslomov** [comment] 2018-02-05 15:27
@philwo lmk if you are unavailable on those dates

**Comment by philwo** [comment] 2018-02-05 15:29
@dslomov Should work fine for me :)

**Comment by or-shachar** [comment] 2018-03-05 09:59
Hey fellows! Do we have an updated date for this RC?

**Comment by philwo** [comment] 2018-03-08 15:56
The current baseline looks pretty good. I'll likely cut an RC today.

**Comment by philwo** [comment] 2018-03-08 15:57
We should investigate whether we should point this out in the release notes, in case others have the same issue:

https://github.com/tensorflow/tensorflow/pull/17508

**Comment by laszlocsomor** [comment] 2018-03-08 16:30
@philwo: would it be possible to wait for https://github.com/bazelbuild/bazel/pull/4806 ?

**Comment by laszlocsomor** [comment] 2018-03-09 09:19
Thanks @philwo for waiting! My PR was merged as https://github.com/bazelbuild/bazel/commit/b961b0ad6cc2578b98d0a307581e23e73392ad02, I'd love to have this in the RC.

**Comment by laszlocsomor** [comment] 2018-03-09 09:20
Also, note to self and to @philwo: I'd like to write about https://github.com/bazelbuild/bazel/commit/b961b0ad6cc2578b98d0a307581e23e73392ad02 in the release notes.

**Comment by philwo** [comment] 2018-03-12 13:54
This looks like a good baseline to me: https://github.com/bazelbuild/bazel/commit/b33e5afa313322a7048044c44d854cbb666b988e

**Comment by philwo** [comment] 2018-03-12 13:55
```
$ scripts/release/release.sh create 0.12.0 b33e5afa313322a7048044c44d854cbb666b988e
$ scripts/release/release.sh push
```

**Comment by philwo** [comment] 2018-03-12 18:14
Release has been successfully cut, branch has been pushed (https://github.com/bazelbuild/bazel/tree/release-0.12.0) and I managed to convince Buildkite to build our release artifacts with the correctly embedded version number:

https://buildkite.com/bazel/release/builds/20

Tomorrow I'll work on the release scripts to finish the Buildkite support and will then do the rest of the release process (verifying produced artifacts, signing, pushing to GCS / APT repository / GitHub and sending the announcement mail).

**Comment by philwo** [comment] 2018-03-14 12:04
This seems like a potential release blocker: https://github.com/bazelbuild/bazel/issues/4846

**Comment by laszlocsomor** [comment] 2018-03-14 12:14
https://github.com/bazelbuild/bazel/issues/4734 is also a potential blocker, though I doubt it's a regression.

**Comment by laszlocsomor** [comment] 2018-03-14 12:24
@philwo : where can we download the RC1 binary?

**Comment by laszlocsomor** [comment] 2018-03-14 12:40
Another possible blocker: https://github.com/bazelbuild/bazel/issues/4847
I'm looking for its culprit now.

**Comment by philwo** [comment] 2018-03-14 13:11
@laszlocsomor You can download the binaries here: https://buildkite.com/bazel/release/builds/20 (check the "Artifacts" tab for each platform).

I'm right now working on getting it out via the usual channels as well.

**Comment by laszlocsomor** [comment] 2018-03-14 15:25
Please cherrypick https://github.com/bazelbuild/bazel/commit/369409995bd75eeb0683fd24f7585d2a90320796 to fix 
https://github.com/bazelbuild/bazel/issues/4847.

**Comment by philwo** [comment] 2018-03-14 18:46
I got the release stuff working at last and just sent out the announcement to bazel-discuss@. Binaries are available on [our website](https://releases.bazel.build/0.12.0/rc1/index.html) and via apt-get in the testing branch.

Note that I had to rebuild the binaries one more time, because the release notes embedded in the installers were wrong due to an error in the release pipeline script. If you downloaded the binaries from the above Buildkite link, please don't be surprised. There were no functional changes and both the binaries above and the ones in the announcement I just sent out were built from the exactly same Git commit. :)

**Comment by cushon** [comment] 2018-03-15 02:02
@philwo can you cherry-pick dbf779869751cc893ba240402d352c6e70be2978 for #4846?

**Comment by laszlocsomor** [comment] 2018-03-15 15:15
@philwo please cherrypick 4c3098cfa6f00f90c7530b6f40d3e93062931c1d to fix https://github.com/bazelbuild/bazel/issues/4734

**Comment by steeve** [comment] 2018-03-16 22:33
Please cherry-pick https://github.com/bazelbuild/bazel/pull/4866, fixes Android's `libc++`

**Comment by laszlocsomor** [comment] 2018-03-20 15:28
Please cherry-pick https://github.com/bazelbuild/bazel/commit/b1be5816ec1bf8e1172c1bed4f29b4e6c6bb7202 to fix #4879, and also remove the following "New features" relnotes entry: "python,runfiles: You can now ..."

**Comment by philwo** [comment] 2018-03-21 15:24
Trying to create 0.12.0rc2 now:

$ scripts/release/release.sh create 0.12.0 b33e5afa313322a7048044c44d854cbb666b988e \
  369409995bd75eeb0683fd24f7585d2a90320796 \
  dbf779869751cc893ba240402d352c6e70be2978 \
  4c3098cfa6f00f90c7530b6f40d3e93062931c1d \
  a1068c44a700ec2cff84cbd12592e9bfea25d754 \
  b1be5816ec1bf8e1172c1bed4f29b4e6c6bb7202

**Comment by philwo** [comment] 2018-03-21 15:38
Will also cherrypick @meteorcloudy's https://github.com/bazelbuild/bazel/commit/0a4622012ff796429220fe57d3217f262cc208a8 and https://github.com/bazelbuild/bazel/commit/3c5373c50c7c492842f8a468906eda2c0bc90787

**Comment by philwo** [comment] 2018-03-21 15:41
```
$ scripts/release/release.sh push
```

**Comment by ittaiz** [comment] 2018-03-21 16:10
@philwo rc2 will include the junit fix, right? (Meaning you won’t cherry
pick the revert)

**Comment by philwo** [comment] 2018-03-21 16:21
@ittaiz The revert hasn't been cherrypicked, so rc2 should be fine. :)

**Comment by ittaiz** [comment] 2018-03-21 16:27
Thanks!

**Comment by philwo** [comment] 2018-03-21 21:42
RC2 pushed: https://releases.bazel.build/0.12.0/rc2/index.html

**Comment by philwo** [comment] 2018-03-28 11:51
Last known release blocker:
- https://github.com/bazelbuild/bazel/issues/4904

**Comment by laszlocsomor** [comment] 2018-03-29 06:58
I just noticed this entry in the release notes:

> New features:
>
> ...
> - The new "--local_tmp_root=<path>" flag allows specifying the temp
>    directory for locally executed actions.

Please remove it, the feature was rolled back in cfe5994540f20901906ce0c39d6f57d3ad02d677.

**Comment by philwo** [comment] 2018-03-29 07:09
FYI, the Bazel release 0.12.0 will be delayed until April 9th due to one remaining release blocker and me being on vacation from tomorrow. I think that's better than rushing it out only to find out that there's an issue and then I'm not there to fix it :)

Bazel 0.12.0rc2 should be pretty much what goes out as final, as I'm not aware of any other known issues, except for the remote caching on Windows issue (#4904).

**Comment by ittaiz** [comment] 2018-03-29 07:39
Will this mean 0.13.0 will also be delayed?

**Comment by philwo** [comment] 2018-03-29 08:08
@ittaiz I think we can cut 0.13.0-rc1 as planned.

**Comment by petemounce** [comment] 2018-03-30 01:39
0.12.0-rc1 and rc2 have been pushed to chocolatey.

**Comment by xingao267** [comment] 2018-04-06 18:36
I'm seeing TF build failure with version >= Bazel 0.12.0rc2 both locally and remotely. Please take a look at https://github.com/tensorflow/tensorflow/issues/17816.

**Comment by philwo** [comment] 2018-04-09 14:25
I'm creating rc3 now with the additional cherrypick https://github.com/bazelbuild/bazel/commit/f54d7e5293cc40ce3507a9adef530e46ab817585 to fix https://github.com/bazelbuild/bazel/issues/4904.

Thanks @meteorcloudy!

**Comment by philwo** [comment] 2018-04-09 16:16
Bazel 0.12.0rc3 has been pushed.

https://groups.google.com/d/msg/bazel-discuss/j7ozGl-I7oE/PsdytIfyBwAJ
https://releases.bazel.build/0.12.0/rc3/index.html

**Comment by philwo** [comment] 2018-04-09 21:52
We have three failures on a full downstream test run:
- rules_docker: https://github.com/bazelbuild/rules_docker/issues/363
- rules_python: https://github.com/bazelbuild/rules_python/issues/67
- TensorFlow Serving: https://github.com/tensorflow/serving/issues/825

Considering that fixes are available upstream and just not merged yet, I don't consider these a blocker.

**Comment by meteorcloudy** [comment] 2018-04-09 21:56
Just confirmed with @xingao267 , tensorflow/tensorflow#17816 is also not a regression. 
I tested remote cache on Windows with TensorFlow, it also worked. I think rc3 looks quite good!

**Comment by petemounce** [comment] 2018-04-10 10:53
rc3 is on chocolatey.

**Comment by steeve** [comment] 2018-04-11 13:09
Can we cherry-pick https://github.com/bazelbuild/bazel/commit/cb16c5089953127690c8971d32dc3d4cf01b7620 please pretty please ?

**Comment by philwo** [comment] 2018-04-11 14:44
@steeve I'm releasing 0.12.0 and cannot add any more cherry-picks... sorry! But 0.13.0 is just around the corner. Please ping its release bug regarding this: https://github.com/bazelbuild/bazel/issues/4583 :)

**Comment by steeve** [comment] 2018-04-11 15:19
Sure thing, thank you !

**Comment by petemounce** [comment] 2018-04-22 22:06
0.12.0 is up on chocolatey. Apologies for delay!

**Comment by philwo** [comment] 2018-04-23 07:34
Thank you @petemounce :)

**Closed** 2018-06-07 10:01 UTC
Labels: release
