### ISSUE TITLE
Windows compile script is broken

### ISSUE THREAD

**Issue by kchodorow** [bazelbuild/bazel#3001] opened 2017-05-12 16:39 UTC
It looks like it's stripping one of the /s?

```
+ /c/tools/msys64/usr/bin/bash -l -c 'cd /c/jenkins/workspace/Bazel/JAVA_VERSION/1.8/PLATFORM_NAME/windows-x86_64; source env.sh; exec ./scripts/ci/windows/compile_windows.sh'
.............
ERROR: not a valid absolute pattern (absolute target patterns must start with exactly two slashes): '/src:bazel'.
```

http://ci.bazel.io/view/Bazel%20bootstrap%20and%20maintenance/job/Bazel/JAVA_VERSION=1.8,PLATFORM_NAME=windows-x86_64/1497/console

**Comment by kchodorow** [comment] 2017-05-12 16:40
Ah, looks like this is the RC build, fwiw

**Comment by laszlocsomor** [comment] 2017-05-15 08:42
This is caused by MSYS's path translation heuristic. I changed the bootstrap bazel to be 0.5.0rc6-msvc so it is now a non-msys binary, so MSYS will translate its path-looking arguments, e.g.:
```
$ /c/work/app1/Debug/app1.exe --bazelrc=${BAZELRC:-/dev/null} --nomaster_bazelrc build //src:bazel //src:bazel_with_jdk
argc=6
argv[0]=(C:\work\app1\Debug\app1.exe)
argv[1]=(--bazelrc=nul)
argv[2]=(--nomaster_bazelrc)
argv[3]=(build)
argv[4]=(/src:bazel)
argv[5]=(/src:bazel_with_jdk)
```

But fortunately this can be turned of with MSYS2_ARG_CONV_EXCL="*" (http://stackoverflow.com/questions/7250130/how-to-stop-mingw-and-msys-from-mangling-path-names-given-at-the-command-line/34386471#34386471)

```
$ export MSYS2_ARG_CONV_EXCL="*"

$ /c/work/app1/Debug/app1.exe --bazelrc=${BAZELRC:-/dev/null} --nomaster_bazelrc build //src:bazel //src:bazel_with_jdk
argc=6
argv[0]=(C:\work\app1\Debug\app1.exe)
argv[1]=(--bazelrc=/dev/null)
argv[2]=(--nomaster_bazelrc)
argv[3]=(build)
argv[4]=(//src:bazel)
argv[5]=(//src:bazel_with_jdk)
```

**Comment by laszlocsomor** [comment] 2017-05-15 09:00
MSYS-ful binaries aren't affected by the `MSYS2_ARG_CONV_EXCL` envvar, so this is safe to add to our CI scripts.

**Comment by laszlocsomor** [comment] 2017-05-15 09:18
We may also be interested in `MSYS2_ENV_CONV_EXCL`.

And it turns out @gintas already asked the MSYS devs about this 2.5 years ago: https://github.com/Alexpux/MSYS2-packages/issues/84

**Comment by laszlocsomor** [comment] 2017-05-15 09:22
In this comment: https://github.com/Alexpux/MSYS2-packages/issues/84#issuecomment-58522726
"Second, you can disable mangling some arguments with MSYS2_ARG_CONV_EXCL environment variable. This variable can contain semicolon separated list of arguments started with values that don't need to be converted." -- So all we need is `MSYS2_ARG_CONV_EXCL="//"`

**Comment by laszlocsomor** [comment] 2017-06-06 14:52
This was fixed by https://github.com/bazelbuild/bazel/commit/866ecc8c3d5e0b899e3f0c9c6b2265f16daae842.

**Closed by laszlocsomor** 2017-06-06 14:52 UTC
Labels: breakage, category: multi-platform > windows, P1

**Comment by improbablekeren** [comment] 2017-11-30 14:11
I checked out bazel official example on window `git clone https://github.com/bazelbuild/examples/` and got this issue when I built it:
`bazel build //...`

It's fixed with MSYS2_ARG_CONV_EXCL="//". Should this fix be a part of bazel build? my bazel version is 0.7.0

**Comment by laszlocsomor** [comment] 2017-11-30 14:28
@improbablekeren : Try running Bazel from cmd.exe, not from MSYS Bash.

This is an issue outside of Bazel's control: MSYS converts Unix-path-looking arguments to Windows paths, and its heuristic thinks "//..." is a Unix path. The workaround you found should disable this heuristic for this path.

**Comment by improbablekeren** [comment] 2017-11-30 14:29
got it. very helpful, thanks
