### ISSUE TITLE
Uncaught exception in CppLinkActionBuilder

### ISSUE THREAD

**Issue by laszlocsomor** [bazelbuild/bazel#1806] opened 2016-09-21 12:00 UTC
See https://groups.google.com/forum/#!msg/bazel-discuss/YpGzj5e6J5A/WXWEOZwgAgAJ

**Comment by laszlocsomor** [comment] 2016-09-21 12:03
@calpeyser - Are you the right assignee?

**Comment by mhlopko** [comment] 2016-09-21 12:38
I guess I should fix this :)

**Comment by mhlopko** [comment] 2016-12-02 13:40
(status update: asked Michiel for project sources so I can reproduce)

**Comment by mhlopko** [comment] 2016-12-19 13:23
Closing due to the lack of information.

**Closed by mhlopko** 2016-12-19 13:23 UTC
Labels: category: rules > C++, P2, type: bug
