### ISSUE TITLE
support for py_library to link to a cc_library

### ISSUE THREAD

**Issue by hermione521** [bazelbuild/bazel#1366] opened 2016-06-10 13:30 UTC
Mentioned by Fred:

In bazel, it is not possible for a py_library to link to a cc_library.

The workaround is to create a dynamically linked .so file and load that in the py_library. (I'm not sure what happens in Windows.)

**Comment by ulfjack** [comment] 2016-06-15 06:59
Duplicate of #701.

**Closed by ulfjack** 2016-06-15 06:59 UTC
Labels: category: rules > python, P3, type: feature request
