### ISSUE TITLE
--per_file_copt requires argument changes with bzlmod

### ISSUE THREAD

**Issue by keith** [bazelbuild/bazel#17132] opened 2023-01-04 01:20 UTC
If you passed something like `--per_file_copt=external/com_google_protobuf/.*.cpp@-Wno-type-limits`, and try to move to bzlmod, the flag no longer works because the repository name is taken literally and doesn't contain the version info. In this case you likely need something like `external/protobuf~.*/`, but ideally your existing flags would keep working and this wouldn't be taken so literally. I'm sure there are other flags with a similar issue

**Comment by brentleyjones** [comment] 2023-02-17 03:46
cc @Wyverald 

(And not stale)

**Comment by Wyverald** [comment] 2023-07-12 22:11
I _believe_ this is just a dupe of https://github.com/bazelbuild/bazel/issues/15553. Let me know if that's not true!

**Closed by Wyverald** 2023-07-12 22:11 UTC
Labels: type: feature request, P3, team-ExternalDeps, area-Bzlmod
