### ISSUE TITLE
rules_apple is failing with Bazel release 6.3.0 

### ISSUE THREAD

**Issue by sgowroji** [bazelbuild/bazel#18987] opened 2023-07-19 08:56 UTC
[https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/3176#01896c1f-112a-4ba3-abd3-2133458ad1d5](https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/3176#01896c1f-112a-4ba3-abd3-2133458ad1d5)

Platform : MacOS

Logs :  

```
 FAIL: //examples/ios/HelloWorldSwift:UnitTestsWithCoverageManifest 
 FAIL: //examples/multi_platform/Buttons:ButtonsLogicTests 
 FAIL: //examples/multi_platform/MixedLib:MixedTests 
 FAIL: //examples/ios/HelloWorldSwift:UnitTests
 FAIL: //examples/ios/Squarer:SquarerTests
 FAIL: //examples/ios/PrenotCalculator:PrenotCalculatorTests
 12 tests are getting failed.
```

Steps :  

```
git clone https://github.com/bazelbuild/rules_apple.git
git reset 8f2cd030532d930b597cc45ed3fc1ed0d0ce4181 --hard
Export USE_BAZEL_VESION=fa77401686b3f7cd050601d99b3bacdc43a84bf4
bazel test --test_tag_filters=-skipcic tools/... test/... examples/...
```

CC Greenteam @meteorcloudy

**Comment by meteorcloudy** [comment] 2023-07-19 08:59
@keith Can you take a look and try to identify which commit broke rules_apple? It's a bit hard for us to reproduce the issue. https://github.com/bazelbuild/bazelisk#--bisect might be helpful.

**Comment by keertk** [comment] 2023-07-19 14:34
Hey @keith it actually seems to be consistently failing. We've retried a bunch of times.

**Comment by meteorcloudy** [comment] 2023-07-19 15:16
The existing runs are indeed on "bk-imacpro-11". Let's wait for https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/3176#01896eb7-7937-4b7f-b651-11e12d5974f4, which is assigned to "bk-imacpro-2".

**Comment by keith** [comment] 2023-07-19 15:59
it passed there. it would be great if you could take the other machine out of the rotation until someone can debug.

**Comment by keith** [comment] 2023-07-19 16:25
I agree

**Comment by meteorcloudy** [comment] 2023-07-20 08:18
Let's close this one since it's due to an infra issue.

**Closed by meteorcloudy** 2023-07-20 08:18 UTC
Labels: type: bug, breakage, untriaged, team-Rules-ObjC
