### ISSUE TITLE
Cannot run docs site

### ISSUE THREAD

**Issue by steren** [bazelbuild/bazel#3300] opened 2017-06-30 11:11 UTC
I get this error when running `./scripts/serve-docs.sh`:
```
steren-macbookpro2:bazel steren$ ./scripts/serve-docs.sh
expr: syntax error
ERROR: /Users/steren/work/bazel/tools/build_rules/utilities.bzl:22:11: name 'DefaultInfo' is not defined.
ERROR: /Users/steren/work/bazel/src/main/java/com/google/devtools/build/lib/BUILD:731:1: error loading package 'src/main/protobuf': Extension 'tools/build_rules/utilities.bzl' has errors and referenced by '//src/main/java/com/google/devtools/build/lib:bazel-main'.
ERROR: Analysis of target '//site:jekyll-tree.tar' failed; build aborted.
INFO: Elapsed time: 0.234s
steren-macbookpro2:bazel steren$ 
```

**Comment by jin** [comment] 2018-11-06 23:39
I can't reproduce on HEAD now. Closing.

**Closed by jin** 2018-11-06 23:39 UTC
Labels: P2, type: bug, type: documentation
