### ISSUE TITLE
Spawn standard error doesn't seems to be reported when doing C++ compilation

### ISSUE THREAD

**Issue by damienmg** [bazelbuild/bazel#1010] opened 2016-03-04 12:46 UTC
We have many case where the C++ compilation where failing without error message from the subcommand. I have a 100% repro case, just trying to clean it.

Here an example of full output:

```
INFO: You can skip this first step by providing a path to the bazel binary as second argument:
INFO:    /opt/workspace/compile.sh compile /path/to/bazel
🍃  Building Bazel from scratch......
🍃  Building Bazel with Bazel.
INFO: Found 1 target...
ERROR: /opt/workspace/src/main/cpp/util/BUILD:24:1: C++ compilation of rule '//src/main/cpp/util:md5' failed: gcc failed: error executing command 
  (cd /tmp/bazel.ubW73u4T/out/workspace && \
  exec env - \
    PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin \
  /usr/bin/gcc -U_FORTIFY_SOURCE '-D_FORTIFY_SOURCE=1' -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -Wl,-z,-relro,-z,now -fcolor-diagnostics -fno-omit-frame-pointer '-std=c++0x' -iquote . -iquote bazel-out/local-fastbuild/genfiles -iquote external/bazel_tools -iquote bazel-out/local-fastbuild/genfiles/external/bazel_tools -isystem external/bazel_tools/tools/cpp/gcc3 -no-canonical-prefixes -fno-canonical-system-headers -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' '-frandom-seed=bazel-out/local-fastbuild/bin/src/main/cpp/util/_objs/md5/src/main/cpp/util/md5.pic.o' -MD -MF bazel-out/local-fastbuild/bin/src/main/cpp/util/_objs/md5/src/main/cpp/util/md5.pic.d -fPIC -c src/main/cpp/util/md5.cc -o bazel-out/local-fastbuild/bin/src/main/cpp/util/_objs/md5/src/main/cpp/util/md5.pic.o): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.
Target //src:bazel failed to build
INFO: Elapsed time: 7.539s, Critical Path: 1.26s
```

**Comment by damienmg** [comment] 2016-03-04 13:30
And the missing error is: `gcc: error: unrecognized command line option '-fcolor-diagnostics'`

Cannot come up with a smaller repro...

I have a theory though: the line got deleted. So it might be fixed by latest @aehlig changes

**Comment by aehlig** [comment] 2016-03-04 15:52
> Cannot come up with a smaller repro...

Can you somehow share the big example, so that I can have a look
(maybe privately, if it contains confidential content)?

> I have a theory though: the line got deleted.

There is an easy way to verify this: just script(1) the invocation
of bazel and look at the typescript in a binary-aware text editor.
This is a generally good way of debugging curses applications.

> So it might be fixed by latest @aehlig changes

That would be even better, if the problem was already fixed.

Thanks,
Klaus


-- 
Klaus Aehlig
Google Germany GmbH, Erika-Mann-Str. 33, 80636 Muenchen
Registergericht und -nummer: Hamburg, HRB 86891
Sitz der Gesellschaft: Hamburg
Geschaeftsfuehrer: Matthew Scott Sucherman, Paul Terence Manicle

**Comment by damienmg** [comment] 2016-03-04 15:55
No confidential content. I am merging the fix that was triggering the error. Then I can share a repro but that implies spawning a docker container.

**Comment by damienmg** [comment] 2016-03-04 15:59
I cced you on the changes.

Reverting the first one and `./output/bazel test tools/cpp/test:test_cc_configure-ubuntu-15.04-fastbuild` was triggering the problem.

To test it independently:
```
bazel run tools/cpp/test:bazel_cc_configure-ubuntu-15.10-fastbuild bazel/docker_test:tools_cpp_test_bazel_cc_configure-ubuntu-15.10-fastbuild
docker run --rm -t -i --entrypoint=/bin/bash bazel/docker_test:tools_cpp_test_bazel_cc_configure-ubuntu-15.04-fastbuild
```

will get you a shell where you can simple ./compile.sh

**Comment by damienmg** [comment] 2016-03-05 02:03
(note it stills happen at head)

**Comment by damienmg** [comment] 2016-03-07 16:28
This is coming from ./compile.sh. So we probably missing some arguments when we invoke bazel server.

**Comment by damienmg** [comment] 2016-03-08 03:57
Ulf said he saw it on some random action too.

Assigning to Klaus so he can work on it when back.

**Comment by aehlig** [comment] 2016-03-15 10:47
> Assigning to Klaus so he can work on it when back.

Simple way to reproduce: randomly break a *.cc or *.h file that
bazel depends on, e.g., by adding a #error cpp(1) directive. Then,
interestingly enough, ./compile.sh will not report the error message
(but, of course, the fact that the build failed, which makes it hard
to debug in the bootstrap phase).

Interestingly enough, a `bazel build` will correctly report the error;
`bazel build --experimental_ui --experimental_ui_debug_all_events`,
shows that the order of reported events is first the ERROR event, then
the STDERR event.

-- 
Klaus Aehlig
Google Germany GmbH, Erika-Mann-Str. 33, 80636 Muenchen
Registergericht und -nummer: Hamburg, HRB 86891
Sitz der Gesellschaft: Hamburg
Geschaeftsfuehrer: Matthew Scott Sucherman, Paul Terence Manicle

**Comment by aehlig** [comment] 2016-03-16 10:47
The error is in the bootstrap process-wrapper. Basically, it does not
support '-' to mean stdout/stderr untouched. The following quick hack
gets the error message back relying on the fact that during bootstrap
we always use a StandaloneSpawnStrategy.

```
diff --git a/scripts/bootstrap/compile.sh b/scripts/bootstrap/compile.sh
index b7a5f3f..d23f777 100755
--- a/scripts/bootstrap/compile.sh
+++ b/scripts/bootstrap/compile.sh
@@ -199,7 +199,7 @@ stdout="$1"
 stderr="$2"
 shift 2
 
-"$@" 2>"$stderr" >"$stdout"
+"$@"
 exit $?
 EOF
 chmod 0755 ${ARCHIVE_DIR}/_embedded_binaries/process-wrapper${EXE_EXT}
```

Will work on a proper fix.

-- 
Klaus Aehlig
Google Germany GmbH, Erika-Mann-Str. 33, 80636 Muenchen
Registergericht und -nummer: Hamburg, HRB 86891
Sitz der Gesellschaft: Hamburg
Geschaeftsfuehrer: Matthew Scott Sucherman, Paul Terence Manicle

**Comment by aehlig** [comment] 2016-03-16 13:03
Currently under review: https://bazel-review.googlesource.com/#/c/3081/

-- 
Klaus Aehlig
Google Germany GmbH, Erika-Mann-Str. 33, 80636 Muenchen
Registergericht und -nummer: Hamburg, HRB 86891
Sitz der Gesellschaft: Hamburg
Geschaeftsfuehrer: Matthew Scott Sucherman, Paul Terence Manicle

**Comment by aehlig** [comment] 2016-03-21 10:30
The patch is now pushed as b2973419c9b018064bbc45f9fdf5c135ee304758. I believe the issue is fixed now.

**Closed by aehlig** 2016-03-21 10:30 UTC
Labels: Bug, P1
