### ISSUE TITLE
Bazel builds hang on high sierra

### ISSUE THREAD

**Issue by nbutko** [bazelbuild/bazel#3269] opened 2017-06-26 21:29 UTC
After upgrading to OSX 10.13 High Sierra Beta, and migrating HFS+ to APFS, Bazel appears to have some issues on my machine. Are there any known fixes or workarounds? If not, it might be good to investigate prior to High Sierra GA. For now, I'll try reverting to HFS+ to see if that improves things.

First, every time I try to build or test, bazel hangs for ~10 minutes after the build is finished, waiting to shut down.  After ~10 mins, it shuts down cleanly.

In addition, I'm seeing some amount of errors like:

"Couldn't build file a/b/c/_objs/d/a/b/c/d.o: C++ compilation of rule '//a/b/c:d' failed: Could not move output artifacts from sandboxed execution: Unable to delete /private/var/tmp/_bazel_$USER/7bd56105914d3ecdb8f27fe2051e25e7/execroot/repo/bazel-out/android-arm-linux-androideabi-clang3.8-v7a-libcpp-opt/bin/a/b/c/_objs/d/a/b/c/d.o."

**Comment by nbutko** [comment] 2017-06-27 04:04
After switching to HFS+ on High Sierra (OSX 10.13 beta) I still see the same two symptoms (difficulty with sandbox, and hanging builds). The former appear to only show up for certain build targets, and the latter appear to come on progressively and get worse over time.

I'll try to characterize this more fully including a minimal repro and update the thread again with my findings.

**Comment by philwo** [comment] 2017-06-27 11:16
@ulfjack I think we need a developer machine with High Sierra in the office to debug this and prepare for the final release in time.

**Comment by ulfjack** [comment] 2017-06-27 11:41
Haha.

**Comment by philwo** [comment] 2017-06-27 12:04
I acquired a Mac (thanks Ulf ;)) and will turn it into our High Sierra development env to try to reproduce and fix this.

**Comment by nbutko** [comment] 2017-06-27 23:29
For now, I've totally reverted from High Sierra back to Sierra, but we still have a high sierra system if you need help with a repro.

Some things I observed:
1) bazel clean --expunge fails when sources owned by root (e.g. jdk) are required to be pulled in.
2) some errors about unfound files are for files that exist, and rebuilding picks up from where it left off, so that after about four failed builds, the fifth succeeds. It's almost like blaze is querying for a file moments before the OS thinks it's present.
3) Problematic build rules tend to be large globs of nested code trees.
4) Building for iOS and Android is much more likely to have an issue than building for OSX.
5) State gets corrupted in really weird and sticky ways, for example even after clean expunge, one build target was parsing as "nothing to build" on a clean repo checkout, but on another identically configured laptop it would build fine.

**Comment by philwo** [comment] 2017-06-28 09:40
I've installed macOS High Sierra Beta 2 and Xcode 9.0 Beta 2 on my testing Mac Pro and upgraded the filesystem to APFS. Let's see how it goes.

**Comment by philwo** [comment] 2017-06-28 10:49
I tried this out on my system now :)

Unfortunately (?) I can't reproduce any of the problems you kindly wrote down in so much detail. It all works fine on my system, even with sandboxing enabled. This is what I tried:

```bash
# Preparations:
# Install clean macOS 10.12.5 on Mac Pro (Late 2013) via recovery mode.
# Upgrade to macOS High Sierra Beta 2 (10.13 Beta (17A291j)).
# Install Xcode Version 9.0 beta 2 (9M137d).
# Start Xcode, go to Preferences > Locations, choose "Xcode 9.0" as Command Line Tools.
# Install Homebrew (just for fun).
# Download (bazel-0.5.2-installer-darwin-x86_64.sh)[https://github.com/bazelbuild/bazel/releases/download/0.5.2/bazel-0.5.2-installer-darwin-x86_64.sh].
# Install Bazel:
bash bazel-0.5.2-installer-darwin-x86_64.sh --user
git clone https://github.com/bazelbuild/bazel.git
cd bazel
~/bin/bazel build //src:bazel_with_jdk
cp bazel-bin/src/bazel_with_jdk ~/bin
~/bin/bazel_with_jdk clean --expunge
~/bin/bazel_with_jdk build //src:bazel_with_jdk
```

Now running the tests to make sure they still pass.

**Comment by damienmg** [comment] 2017-06-29 09:00
Could we have VM images of the various version of macOS that Homebrew support so we could do debug on all of them?

**Comment by nbutko** [comment] 2017-06-29 17:18
I've been having some trouble getting a good simple repro case isolated from the complexity of our codebase. I'll send some more detailed examples of what I'm seeing to Phillip directly, and we can determine next steps from there.

**Comment by philwo** [comment] 2017-07-05 08:29
@nbutko I received your mail but I'm currently OOO. Will get to it next week!

**Comment by philwo** [comment] 2018-07-19 14:22
I think this was fixed in macOS High Sierra final version - we haven't seen any issues with APFS or High Sierra since then.

**Closed by philwo** 2018-07-19 14:22 UTC
Labels: category: sandboxing, type: bug, under investigation

**Comment by nbutko** [comment] 2018-07-19 20:35
Thanks for closing the thread here, I can confirm that we have not seen this issue on any final release version of high sierra.
