### ISSUE TITLE
Build file from git_repository not found

### ISSUE THREAD

**Issue by wolfgangmeyers** [bazelbuild/bazel#1075] opened 2016-03-23 18:06 UTC
I've attached a zip file of a reproduction project with a readme that has the same content as below:

## Build file not found

Currently (as of 2b8ae5b58ae03a0e90a19cf966e0467e8c7dac59) there seems to be a problem with dependencies on projects that depend on external archives. Provided here is an example
project that can reproduce the problem.

### Summary

* Project A (this project) depends on project B (rules_closure) using a git_repository rule.
* Project B depends on project C (closure_library) using a new_http_archive rule.
* Project B has build file for project C (closure/library/closure_library.BUILD) in its source tree and points to it in the new_http_archive rule.
* When project A builds, bazel sees the reference to the build file for project C
	in the workspace file of project B. It then looks for this build file in
	the source tree of project A, and does not find it. The build fails because
	the build file for project C cannot be found.

Run the following command to reproduce the issue:

`bazel build //:main`

[missing_closure_library.zip](https://github.com/bazelbuild/bazel/files/186571/missing_closure_library.zip)

**Comment by wolfgangmeyers** [comment] 2016-03-23 18:07
This resulted from investigation of https://github.com/bazelbuild/rules_closure/issues/9

**Comment by kchodorow** [comment] 2016-03-23 18:13
This is kind of a duplicate of https://github.com/bazelbuild/bazel/issues/855.  Rules should generally be updated to use `build_file_content` instead of `build_file` as a workaround.

**Closed by kchodorow** 2016-03-23 18:13 UTC

**Comment by damienmg** [comment] 2016-03-24 08:43
I think we can replace build_file to use label now that the machinery is
there (we use it for repository_ctx.template)
