### ISSUE TITLE
Release - July 2018 - name: 0.16.1

### ISSUE THREAD

**Issue by c-parsons** [bazelbuild/bazel#5792] opened 2018-08-07 17:34 UTC
Patch release on top of release 0.16.0 (#5058)

Baseline:  4f64b77a3dd8e4ccdc8077051927985f9578a3a5

Previous Cherrypicks (for release 0.16.0): 
    4c9a0c82d308d5df5c524e2a26644022ff525f3e
   d3228b61f633cdc5b3f740b641a0836f1bd79abd
   8ff87c164f48dbabe3b20becd00dde90c50d46f5
   c4622ac9205d2f1b42dac8c598e83113d39e7f11
   10219659f58622d99034288cf9f491865f818218
    ab1f269017171223932e0da9bb539e8a17dd99ed
    68e92b45a37f2142c768a56eb7ecfa484b8b22df
    f45c22407e6b00fcba706eb62141cb9036bd38d7
    bca1912853086b8e9a28a85a1b144ec0dc9717cc
    3842bd39e10612c7eef36c6048407e81bcd0a8fb

Cherrypicks so far for 0.16.1:
   To fix #5777 and #5792:  c4670dbf9ca04f2f9ac54a05c6bb6f2fc6e54ea0 1c8133764f8c7ccf3c5cb39a0dbe1a2081384eef e4277c79fbd6b4e8a778bdbf4a5822e40bcf664e 28dfe3169d506cd426df2ff1e13d20f36a073562 b0e8d0a15c8020568cbfed9e3ccd5f69d4d4c25c
   To fix #5683: 6bd0bdf5140525cb33dc2db068b210261d9df271 f330439fb970cfa17c70fc59c1458bb1c31c9522

Still unresolved: #5730

**Comment by c-parsons** [comment] 2018-08-07 17:35
Update: Holding off on cherrypicks for #5777, as it seems patch in #5760 might suffice. Waiting for investigation.

**Comment by c-parsons** [comment] 2018-08-08 16:02
You're absolutely correct. I've edited the cherrypick list above to fix my mistake. Thanks for the notice!

**Comment by c-parsons** [comment] 2018-08-08 18:00
OK, with #5760 being fixed, the list of cherrypicks for 0.16.1 becomes:

To fix #5777 (and #5730 ?) : 366da4c c56699d 30c601d
To fix #5683: 6bd0bdf f330439

**Comment by cushon** [comment] 2018-08-08 18:05
> OK, with #5760 being fixed,

#5760 was the PR, #5744 is the bug that it fixes. Don't forge the cherry-picks for that one:

To fix #5744: 366da4c c56699d 30c601d

**Comment by c-parsons** [comment] 2018-08-08 19:16
I've generated 0.16.1rc1. (I needed to resolve several merge conflicts around JDK BUILD/bzl files, hope I did so correctly:))

https://storage.googleapis.com/bazel/0.16.1/rc1/index.html

**Comment by dslomov** [comment] 2018-08-09 11:45
Let's document what is the state of 0.16.1 as proposed here (roll forward fixes to enable compilation on JDK 9) w.r.t. the following issues:
* https://github.com/bazelbuild/bazel/issues/5741
* https://github.com/bazelbuild/bazel/issues/5766
* Annotation processors (https://groups.google.com/forum/#!msg/bazel-discuss/1116GHzkNm0/AYWnvEK_AAAJ)

(Ideally they are all fixed with @cushon's fixes for #5744)

**Comment by cushon** [comment] 2018-08-09 16:55
* #5741 will not by fixed by my change, I commented on the bug: https://github.com/bazelbuild/bazel/issues/5741#issuecomment-411823309
* #5766 is a dupe of #5744 and is fixed by my change
* the annotation processor thing will not be fixed by my change, I commented on the thread

**Comment by petemounce** [comment] 2018-08-11 08:36
rc1 and rc2 are on chocolatey

**Comment by buchgr** [comment] 2018-08-13 16:13
0.16.1 has been released! https://releases.bazel.build/0.16.1/release/index.html

I have sent out a patch to homebrew: https://github.com/Homebrew/homebrew-core/pull/31066

cc @vbatts @oetemounce @ilovezfs

**Comment by vbatts** [comment] 2018-08-13 16:38
build kicked 
https://copr.fedorainfracloud.org/coprs/vbatts/bazel/build/787547/

**Comment by petemounce** [comment] 2018-08-13 21:37
chocolatey is published.

**Closed** 2018-08-22 20:10 UTC
Labels: release

**Comment by katre** [comment] 2018-09-11 17:12
Users are still seeing issues with JDK version in 0.16.1 (see #6072). Can we cut a 0.16.2 with the fixes needed to unblock them?

**Comment by laurentlb** [comment] 2018-09-12 10:16
What needs to be cherrypicked in 0.16.2 exactly?
Is it just https://github.com/bazelbuild/bazel/commit/282b8839ef114aa70e18d98a3e6f5fa8dbed4ef9?

@cushon @lberki @katre @davido
