### ISSUE TITLE
About file with non-ascii characters.

### ISSUE THREAD

**Issue by ddwolf** [bazelbuild/bazel#3247] opened 2017-06-22 14:00 UTC
in java_library srcs should be list of labels, and because labels cannot be non-ascii, so file names cannot contain non-ascii characters?

This is too bad ... is there any workaround?

**Comment by alexeagle** [comment] 2018-05-03 18:39
I think it's a duplicate of #374

**Comment by iirina** [comment] 2018-07-24 11:16
Closing as duplicate.

**Closed by iirina** 2018-07-24 11:16 UTC
Labels: P3, category: rules > java, type: feature request
