### ISSUE TITLE
The method name looks quite ambiguous

### ISSUE THREAD

**Issue by namvdo** [bazelbuild/bazel#11952] opened 2020-08-15 03:42 UTC
https://github.com/bazelbuild/bazel/blob/77895614a9d23f6ea0d87ef86db03507b03693a0/src/main/java/com/google/devtools/build/lib/rules/cpp/CppLinkActionBuilder.java#L551

**Comment by laurentlb** [comment] 2020-08-15 11:52
Duplicate of https://github.com/bazelbuild/bazel/issues/11950 :)

**Closed by laurentlb** 2020-08-15 11:52 UTC
