### ISSUE TITLE
Why does `@remotejdk_linux` depend on the current workspace?

### ISSUE THREAD

**Issue by Monnoroch** [bazelbuild/bazel#11512] opened 2020-05-27 23:09 UTC
### Description of the problem / feature request:

`@remotejdk_linux` appears to somehow depend on the current workspace.

### Feature requests: what underlying problem are you trying to solve with this feature?

Using remote JDK to run software inside a `repository_rule`. Note that the way I'm trying to achieve this might not be the right way, but the question of an unexpected dependency still holds.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

```py
# WORKSPACE.bazel:

workspace(name = "test_cycle")

load(":repo.bzl", "repo_rule")

repo_rule(
    name = "repo_rule",
)

load("@repo_rule//:output.bzl", "VALUE")
```

```py
# BUILD.bazel:

# empty
```

```py
# repo.bzl:

def _repo_rule_impl(repo_ctx):
    jdk_path = "/".join(str(repo_ctx.path(Label("@remotejdk11_linux//:WORKSPACE"))).split("/")[:-1])

    # Use JDK path as JAVA_HOME:
    result = repo_ctx.execute(
        ["/bin/true"],
        environment = {"JAVA_HOME": jdk_path},
        quiet = True,
    )

    repo_ctx.file(
        "output.bzl",
        "VALUE = " + str(result),
        executable = False,
    )

    repo_ctx.file(
        "BUILD.bazel",
        "exports_files([\"output.bzl\"])",
        executable = False,
    )

repo_rule = repository_rule(
    implementation = _repo_rule_impl,
    local = False,
    attrs = {},
)
```

As a result I get:

```sh
$ bazel --nosystem_rc --nohome_rc --noworkspace_rc  build //:all
ERROR: Failed to load Starlark extension '@repo_rule//:output.bzl'.
Cycle in the workspace file detected. This indicates that a repository is used prior to being defined.
The following chain of repository dependencies lead to the missing definition.
 - @repo_rule
 - @remotejdk11_linux
This could either mean you have to add the '@remotejdk11_linux' repository with a statement like `http_archive` in your WORKSPACE file (note that transitive dependencies are not added automatically), or move an existing definition earlier in your WORKSPACE file.
INFO: Repository repo_rule instantiated at:
  no stack (--record_rule_instantiation_callstack not enabled)
Repository rule repo_rule defined at:
  ${HOME}/dev/test_cycle/repo.bzl:22:13: in <toplevel>
ERROR: cycles detected during target parsing
INFO: Elapsed time: 0.026s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
    Fetching @repo_rule; Restarting.
```

Note how Bazel tells me that `Cycle in the workspace file detected`. When I remove the `load()` in the `WORKSPACE.bazel` the build passes.  This tells me that the cycle is `@test_cycle -> @repo_rule -> @remotejdk11_linux -> @test_cycle`. This last link `@remotejdk11_linux -> @test_cycle` is unexpected to me.

Also note that even though I never define `@remotejdk11_linux` it should be fine as it's being used [here](https://github.com/bazelbuild/bazel/blob/6255cb1b918f6af750fef4e306fac44b6d351c25/tools/jdk/BUILD#L500) and is working without me defining it in my workspace file when I build with remote JDK using `--host_javabase=@bazel_tools//tools/jdk:remote_jdk11` on Linux.

### What operating system are you running Bazel on?

Linux.

### What's the output of `bazel info release`?

```
$ bazel info release
release 3.1.0
```

###  Have you found anything relevant by searching the web?

Nope.

**Comment by lberki** [comment] 2020-09-23 11:13
This isn't really related to Java. The dependency cycle is as follows:

1. The meaning of the implicit `@remotejdk11_linux` repository added at the end of the WORKSPACE file depends on the contents of the WORKSPACE file
2. The contents of the WORKSPACE file depends on what `output.bzl` contains
3. The contents of `output.bzl` depend on what `repo_rule()` does
4. What `repo_rule()` does depends on the contents of the `repo_rule` repository 

Highly unintuitive (another weird WORKSPACE bug...), but by design.

**Comment by Monnoroch** [comment] 2020-09-23 11:32
Thanks for explaining it! Is there a good way to work around this issue? Currently I manually create a `@remotejdk11_linux_for_repo_rule` repository with the copy of `@remotejdk11_linux` and it's working just fine. But I have to download the same archive twice, plus I have to remember to update my copy whenever the original updates, which is especially tricky considering it is implicit and not very transparent.

**Comment by lberki** [comment] 2020-09-23 11:47
Paging @philwo 

I can't think of anything other than manually copy-pasting the `remotejdk11_linux` stanza from `jdk.WORKSPACE` at the beginning of your WORKSPACE file. But you'd still need to update that manually.

Philipp, maybe you have a better idea?

**Comment by Monnoroch** [comment] 2020-09-23 11:55
Also it could be that I'm not using Java in my rule the right way. I approached it naively, but perhaps there's a better way.

**Comment by philwo** [comment] 2020-09-23 12:22
@Wyverald, could you have a look at this?

Even if we have no current solution rather than to clone the JDK definition and thus extract it twice, we should make sure that we don't accidentally recreate the problem with our new design for external dependency management.

**Comment by Wyverald** [comment] 2020-09-24 09:32
Do I understand correctly that the surprising dependency link `@remotejdk11_linux -> @test_cycle` is only because the `remotejdk11_linux` declaration comes _after_ the `test_cycle` declaration?

If so, then yeah, manually copying the `remotejdk11_linux` definition at the top would work.

I _am_ a bit worried about the fact that `@test_cycle` can depend on `@remotejdk11_linux` at all, though. In the current new design, a module rule's resolve_fn cannot see any repo other than those from Bazel module dependencies, since there's no knowing which module rule generates which repos without, well, executing those module rules' resolve_fns. That does leave the question of "how do I get the JAVA_HOME of a remote JDK" unanswered. I'll have to think more on this -- thanks @philwo for flagging.

**Comment by Wyverald** [comment] 2020-09-24 12:49
Actually, thinking about this again, this is fine in the new setup. You can actually use `@remotejdk11_linux` from `@test_cycle`'s fetch_fn with no problem -- you just can't use it in the resolve_fn. What @Monnoroch tried to do in the OP (somehow use the path to the remote JDK to generate a .bzl file) is okay since it's equivalent to what you'd do in a fetch_fn in the new setup. The surprising dependency link of `@remotejdk11_linux -> @test_cycle` does not exist because there's no ordered evaluation of a WORKSPACE file.

Given that, I'll go ahead and close this issue. This is basically WAI -- you can't use `@remotejdk11_linux` before it's defined -- and there is a mitigation, albeit an imperfect one. And I'm fairly sure the new design actually enables you to do this.

**Closed by Wyverald** 2020-09-24 12:49 UTC
Labels: team-XProduct, untriaged

**Comment by philwo** [comment] 2020-09-24 12:58
@Monnoroch Hope this helps, feel free to comment if there's anything unclear!

If you copy & paste without renaming, it should work and not do the duplicate extraction. Also, the definition of remotejdk11_linux should be pretty stable, so the risk of copying it over is IMHO low. We might bump the patch level version of that JDK in the future, but so far we've been rather conservative with that. I'll keep in mind that if I bump the version, I'll add a notice to the release notes that we updated it.

**Comment by Monnoroch** [comment] 2020-09-24 13:32
Thanks, will try that!
