### ISSUE TITLE
0.19.1: `@bazel_tools//tools/cpp:cc-compiler-local-k8' is not a cc_toolchain rule`

### ISSUE THREAD

**Issue by scottmin0r** [bazelbuild/bazel#6662] opened 2018-11-12 19:13 UTC
### Description of the problem / feature request:

C++ builds fail with:

```
ERROR: The label '@bazel_tools//tools/cpp:cc-compiler-local-k8' is not a cc_toolchain rule
```

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

On Linux/amd64, in an otherwise empty workspace with an empty WORKSPACE file, run:

```
bazel build --crosstool_top=@bazel_tools//tools/cpp:default-toolchain //...
```

### What operating system are you running Bazel on?

Linux (Debian variant)

### What's the output of `bazel info release`?

```
release 0.19.1
```

###  Have you found anything relevant by searching the web?

In the file https://github.com/bazelbuild/bazel/blob/0.19.1/tools/cpp/BUILD:

On the 0.19.0 tag, [this line](https://github.com/bazelbuild/bazel/blob/f0c844c77a2406518c4e75c49188390d5e281d3d/tools/cpp/BUILD#L100) refers to `cc-compiler-local`, a `cc_toolchain` rule that exists.

On the 0.19.1 tag, [this line](https://github.com/bazelbuild/bazel/blob/eb2af0f699350ad187048bf814a95af23f562c77/tools/cpp/BUILD#L100) refers to `cc-compiler-local-k8`, a `cc_toolchain` rule that does not exist.

This appears to be the cause of the issue, although I am not sure why this was changed.

**Comment by nlopezgi** [comment] 2018-11-12 21:17
https://github.com/bazelbuild/bazel/issues/6665 might be related. Perhaps this is also due to https://github.com/bazelbuild/bazel/commit/6bc452874ddff69cbf7f66186238032283f1195f not being included in 0.19.1

**Comment by gelrom** [comment] 2018-11-13 14:57
Could the following output have the same underlying cause?
...`in cc_toolchain rule @local_config_cc//:cc-compiler-k8: Error while selecting cc_toolchain: Toolchain identifier 'local' was not found, valid identifiers are`...
This break occurs at 0.19.1. I've been unable to determine if it also occurs at 0.19, but 0.18 was definitely working. Note that this still breaks even if all backward breaking flags that were flipped in 0.19 are set to false.

**Comment by scentini** [comment] 2018-11-13 15:12
@gelrom can you share the build command? Seems close enough, but not quite the same.

**Comment by scentini** [comment] 2018-11-13 15:17
@gelrom also, could you please provide the list of valid identifiers in the error message?

**Comment by scentini** [comment] 2018-11-13 15:30
@scottminor-google, we've confirmed that @bazel_tools//tools/cpp:default-toolchain is in error.
Why do you need to set --crosstool_top=@bazel_tools//tools/cpp:default-toolchain ?  I'm trying to determine the scope of the issue.
Thanks.

**Comment by gelrom** [comment] 2018-11-13 15:33
@scentini bazel build --crosstool_top=//lib/bazel:toolchain //...
the list of identifiers is of each of our toolchain's toolchain_identifier

**Comment by scottminor-google** [comment] 2018-11-13 15:51
We have a long-ish bazelrc that is explicit about each `crosstool_top` and `host_crosstool_top` that is used for each config that we define, to keep the toolchain selection as obvious and understandable as possible. `default-toolchain` is what we use mostly for `host_crosstool_top` (although that will change shortly, as we don't want to rely on a user-installed toolchain in any part of the build by default).

Is there a different spelling for the same behavior/toolchain as `default-toolchain` that works in 0.19.1 and is backwards-compatible to at least 0.18.0 that we should be using instead?

**Comment by scottminor-google** [comment] 2018-11-14 00:51
Thanks for the fix! I rebuilt bazel from `94d51fc` to test/verify this fix against our codebase. Unfortunately, I'm running into another error:

```
ERROR: /usr/local/google/home/minors/.cache/bazel/_bazel_minors/32b2ee46dce03a213358bafd92f1c3ce/external/local_config_cc/BUILD:57:1: in cc_toolchain rule @local_config_cc//:cc-compiler-k8: Error while selecting cc_toolchain: Toolchain identifier 'local' was not found, valid identifiers are [stub_armeabi-v7a, local_linux, local_darwin, local_freebsd, local_windows_mingw, local_windows_msys64_mingw64, local_windows_clang, local_windows_msys64, vc_14_0_x64]
ERROR: Analysis of target '//:hello_world' failed; build aborted: Analysis of target '@local_config_cc//:cc-compiler-k8' failed; build aborted
```

This is reproduced in a workspace with:
* an empty `WORKSPACE` file
* `//hello_world.cpp`:
    ```
    #include <iostream>

    int main() {
      std::cout << "Hello, world!" << std::endl;
      return 0;
    }
* `//BUILD`:
    ```
    cc_binary(
        name = "hello_world",
        srcs = ["hello_world.cpp"],
    )
    ```

Bazel builds successfully when doing:

```
bazel build //...
```

but fails with the above error when specifying `default-toolchain`:

```
bazel build //... --crosstool_top=@bazel_tools//tools/cpp:default-toolchain
```

**Comment by scottminor-google** [comment] 2018-11-14 00:58
In our codebase, the error is a little different - it still complains about `@local_config_cc//:cc-compiler-k8`, but the available toolchain identifiers is one element - the toolchain_identifier specified in our custom CROSSTOOL. I have no idea why that would be interacting with `@local_config_cc` (or even what that is supposed to be).

Is there anything I can read up on to better understand C/C++ toolchain resolution and what best practices are? I feel woefully uneducated when it comes to this area of Bazel.

**Comment by wjywbs** [comment] 2018-11-14 04:19
I'm encountering an issue similar to this. I took some time to make a minimal repro in https://github.com/wjywbs/bazel-cc-toolchain-bug, and posted the outputs of bazel 0.18.1, 0.19.0 and 0.19.1 in there.

**Comment by scentini** [comment] 2018-11-14 08:37
Thanks for the repro, looking into it.

**Comment by katre** [comment] 2018-11-14 18:11
I've pushed the cherrypick into the RC, please let me know if there are still issues.

**Comment by scottminor-google** [comment] 2018-11-14 18:48
I built bazel from `f2be11dda2` and it successfully builds a C++ target from our codebase with no additional flags. Thanks for the fix!

**Comment by katre** [comment] 2018-11-19 16:16
Closing since 0.19.2 will be released shortly.

**Closed by katre** 2018-11-19 16:16 UTC
Labels: P0, release blocker, team-Rules-CPP, type: bug
