### ISSUE TITLE
Allow new_git_repository rule to take 'strip_prefix' parameter.

### ISSUE THREAD

**Issue by nuh-temp** [bazelbuild/bazel#2616] opened 2017-03-01 19:09 UTC
Currently only 'http_archive' and 'new_http_archive' rules supports 'strip_prefix' parameter which allows to restructure sources from given archive by cutting off a part of a path to avoid extra nesting and have all sources/libraries in a top-level folder.
For instance when there is a repository of following structure:
```
repo1/
  lib/
    __init__.py
    lib1.py
  README.md
  setup.py
```
It would be great to have `__init__.py` and `lib1.py` in `workspace/external/repo1` instead of `workspace/external/repo1/lib`.

**Comment by hermione521** [comment] 2017-03-03 11:40
@kchodorow what do you think?

**Comment by kchodorow** [comment] 2017-03-03 13:52
Duplicate of #1332.  

FWIW, new_git_repository (and git_repository) aren't that great to use: I'd recommend downloading the zip at the commit you want (most git repositories support that) and using new_http_archive.

Alternatively, you might be able to use a Skylark repository rule (https://bazel.build/versions/master/docs/skylark/repository_rules.html) to strip off the part you don't want.

**Closed** 2017-03-03 13:52 UTC
Labels: Under investigation
