### ISSUE TITLE
query and build invalidate each other's external repositories

### ISSUE THREAD

**Issue by lightyang** [bazelbuild/bazel#11895] opened 2020-08-05 09:06 UTC
### Description of the problem / feature request:

Running `bazel query` will invalidate the external repositories of `bazel build` and vice versa.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

1. Run `bazel build` in a project with external repos.
2. Run `bazel query`, all repos will be fetched again. They will come from local cache but this still take a few seconds.
3. Run `bazel build`, again all repos will be invalidated and fetched.

### What operating system are you running Bazel on?

Ubuntu 16.04

### What's the output of `bazel info release`?

2.2.0 and all later version.

### Any other information, logs, or outputs that you want to share?

Tracked this down to a3a22159. The newly added "STARLARK_SEMANTICS" in marker data is likely the cause. In `bazel build`, STARLARK_SEMANTICS is set while in `bazel query` it is empty so the market data is different.

**Comment by benjaminp** [comment] 2020-08-06 03:53
Yep, see #10961.

**Comment by jin** [comment] 2020-08-06 06:40
Thanks @benjaminp, closing as dupe of #10961.

**Closed by jin** 2020-08-06 06:40 UTC
