### ISSUE TITLE
Inscrutable error message: "Bad magic <hash>"

### ISSUE THREAD

**Issue by petemounce** [bazelbuild/bazel#2028] opened 2016-11-02 20:31 UTC
### Description of the problem / feature request / question:

When compiling some code, an error is shown and I've no idea the cause or resolution.

```
[20:13:04][build-bazel.sh] ERROR: /ci/yet-another-thing/BUILD:80:1: Couldn't build file yet-another-thing/_ijar/java_export/yet-another-thing/yet-another-thing_deploy-ijar.jar: Extracting interface //yet-another-thing:java_export failed: ijar failed: error executing command external/bazel_tools/tools/jdk/ijar/ijar bazel-out/local-fastbuild/bin/yet-another-thing/yet-another-thing_deploy.jar bazel-out/local-fastbuild/genfiles/yet-another-thing/_ijar/java_export/yet-another-thing/yet-another-thing_deploy-ijar.jar: com.google.devtools.build.lib.shell.AbnormalTerminationException: Process terminated by signal 6.
[20:13:04][build-bazel.sh] Bad magic 1ad12e74
```

### If possible, provide a minimal example to reproduce the problem:
Sorry; private repo.

### Environment info
* Operating System: OSX 10.11

* Bazel version (output of `bazel info release`):

0.3.2

* If `bazel info release` returns "development version" or "(@non-git)", please tell us what source tree you compiled Bazel from; git commit hash is appreciated (`git rev-parse HEAD`):

### Anything else, information or logs or outputs that would be helpful?
(If they are large, please upload as attachment or provide link).

teamcity build log excerpt, paths and labels obfuscated:
```
[20:12:31][build-bazel.sh] ERROR: /ci/my-thing/configuration/BUILD:22:1: Couldn't build file my-thing/configuration/_ijar/as_java/my-thing/configuration/configuration_deploy-ijar.jar: Extracting interface //my-thing/configuration:as_java failed: ijar failed: error executing command external/bazel_tools/tools/jdk/ijar/ijar bazel-out/local-fastbuild/bin/my-thing/configuration/configuration_deploy.jar ... (remaining 1 argument(s) skipped): com.google.devtools.build.lib.shell.AbnormalTerminationException: Process terminated by signal 6.
[20:12:31][build-bazel.sh] Bad magic 1e657b98
[20:12:40][build-bazel.sh] ____[1,535 / 1,682] scala //my-other-thing/serialization:test
[20:12:45][build-bazel.sh] ____From scala //my-thing/core/distributeddata:distributeddata:
[20:12:45][build-bazel.sh] warning: there were three deprecation warnings; re-run with -deprecation for details
[20:12:45][build-bazel.sh] one warning found
[20:12:56][build-bazel.sh] ____[1,536 / 1,682] Still waiting for 9 jobs to complete:
[20:12:56][build-bazel.sh]       Running (standalone):
[20:12:56][build-bazel.sh]         scala deployable //yet-another-thing:yet-another-thing, 272 s
[20:12:56][build-bazel.sh]         scala deployable //my-thing/util:util, 271 s
[20:12:56][build-bazel.sh]         scala deployable //my-thing/core/io:io, 51 s
[20:12:56][build-bazel.sh]         scala deployable //my-third-thing/protocol:protocol, 49 s
[20:12:56][build-bazel.sh]         scala //fourth-thing:lib, 41 s
[20:12:56][build-bazel.sh]         scala deployable //my-thing/gsim/chunk/rectanglechunk:rectanglechunk, 34 s
[20:12:56][build-bazel.sh]         scala //GeneratedCodeTest:test, 16 s
[20:12:56][build-bazel.sh]         scala //my-other-thing/serialization:test, 16 s
[20:12:56][build-bazel.sh]         scala //fifth-thing/testing/entity/behaviour:behaviour, 16 s
[20:13:02][build-bazel.sh] ____[1,538 / 1,682] Extracting interface //yet-another-thing:java_export
[20:13:04][build-bazel.sh] ERROR: /ci/yet-another-thing/BUILD:80:1: Couldn't build file yet-another-thing/_ijar/java_export/yet-another-thing/yet-another-thing_deploy-ijar.jar: Extracting interface //yet-another-thing:java_export failed: ijar failed: error executing command external/bazel_tools/tools/jdk/ijar/ijar bazel-out/local-fastbuild/bin/yet-another-thing/yet-another-thing_deploy.jar bazel-out/local-fastbuild/genfiles/yet-another-thing/_ijar/java_export/yet-another-thing/yet-another-thing_deploy-ijar.jar: com.google.devtools.build.lib.shell.AbnormalTerminationException: Process terminated by signal 6.
[20:13:04][build-bazel.sh] Bad magic 1ad12e74
[20:13:06][build-bazel.sh] ____[1,584 / 1,682] Extracting interface //my-thing/util:java_export
[20:13:08][build-bazel.sh] ERROR: /ci/my-thing/util/BUILD:24:1: Couldn't build file my-thing/util/_ijar/java_export/my-thing/util/util_deploy-ijar.jar: Extracting interface //my-thing/util:java_export failed: ijar failed: error executing command external/bazel_tools/tools/jdk/ijar/ijar bazel-out/local-fastbuild/bin/my-thing/util/util_deploy.jar ... (remaining 1 argument(s) skipped): com.google.devtools.build.lib.shell.AbnormalTerminationException: Process terminated by signal 6.
[20:13:08][build-bazel.sh] Bad magic a80f0a9c
```

**Comment by laszlocsomor** [comment] 2016-11-03 07:26
"bad magic" doesn't appear anywhere in our code base. Could it be coming from `build-bazel.sh` or something else it calls? Without seeing that file I can't say anything educated :/

**Comment by petemounce** [comment] 2016-11-03 07:41
@laszlocsomor in fact, that appears in https://github.com/bazelbuild/bazel/blob/master/third_party/ijar/classfile.cc

**Comment by laszlocsomor** [comment] 2016-11-03 08:00
Ah, shame on me, I didn't check the third_party directory. Let's investigate then.

**Comment by petemounce** [comment] 2016-11-03 09:00
It's ok. It IS bad magic... I'm expecting an entertaining yak!

**Comment by laszlocsomor** [comment] 2016-11-03 12:16
- Is this a reproducible (deterministic) error or intermittent?
- If you build with `--verbose_failures`, does Bazel show you the failing command?
- If so, can you run that command? What happens? You may have to edit output paths because `bazel-out` is normally read-only for the user.

**Comment by petemounce** [comment] 2016-11-03 12:19
It has happened once so far, on a build agent, and I haven't been able to repro there so far, sorry :(

**Comment by laszlocsomor** [comment] 2016-11-03 12:23
I see, so it's intermittent. :(
Let me close this bug for now then, and reopen if you see it again. Just from reading Ijar's code, it seems somehow it got a corrupt jar file, but without a stable repro we can only guess how that happened.

**Closed by laszlocsomor** 2016-11-03 12:23 UTC
Labels: Under investigation

**Comment by improbablejan** [comment] 2016-11-07 13:58
```
[build-bazel.sh] ERROR: /Applications/BuildAgent/work/d143067dc0196591/ArchUtil/BUILD:88:1: Couldn't build file ArchUtil/_ijar/java_export/ArchUtil/ArchUtil_deploy-ijar.jar: Extracting interface //ArchUtil:java_export failed: ijar failed: error executing command external/bazel_tools/tools/jdk/ijar/ijar bazel-out/local-fastbuild/bin/ArchUtil/ArchUtil_deploy.jar bazel-out/local-fastbuild/genfiles/ArchUtil/_ijar/java_export/ArchUtil/ArchUtil_deploy-ijar.jar: com.google.devtools.build.lib.shell.AbnormalTerminationException: Process terminated by signal 6.
[build-bazel.sh] Bad magic f8fcffff
```

I have observed the same thing using Bazel 0.4.0 on OSX 10.11.

**Comment by laszlocsomor** [comment] 2016-11-07 13:58
@improbablejan : Thanks for reporting it. Is it reproducible?

**Comment by improbablejan** [comment] 2016-11-07 14:00
I have only observed it once so far.
