### ISSUE TITLE
Tensorflow not compiling with current bazel

### ISSUE THREAD

**Issue by philbinj** [bazelbuild/bazel#698] opened 2015-12-08 20:13 UTC
I've tried compiling tensorflow with the latest version of Bazel and get the following error:

```
$ bazel build -c opt --config=cuda //tensorflow/cc:tutorials_example_trainer
.......
INFO: Found 1 target...
INFO: From Compiling external/re2/util/stringprintf.cc:
src/main/tools/namespace-sandbox.c:633: execvp(argv[0], argv): No such file or directory
ERROR: /home/zoox/.cache/bazel/_bazel_zoox/111e93cf3df3e7e66024debaa46e7801/external/re2/BUILD:9:1: C++ compilation of rule '@re2//:re2' failed: crosstool_wrapper_driver_is_not_gcc failed: error executing command third_party/gpus/crosstool/clang/bin/crosstool_wrapper_driver_is_not_gcc -U_FORTIFY_SOURCE '-D_FORTIFY_SOURCE=1' -fstack-protector -fPIE -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object ... (remaining 34 argument(s) skipped).
Target //tensorflow/cc:tutorials_example_trainer failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 10.202s, Critical Path: 0.93s
```

Seems to be a problem with tensorflow's cuda crosstool wrapper.

**Comment by davidzchen** [comment] 2015-12-09 11:36
Hi @philbinj - Can you paste the output of running your build command with the `--verbose_failures` flag?

**Comment by philbinj** [comment] 2015-12-09 17:22
Yes, here is the --verbose_failures output:
```
$ bazel build --verbose_failures -c opt --config=cuda //tensorflow/cc:tutorials_example_trainer                                                                                                                                                       
INFO: Found 1 target...
INFO: From Compiling external/re2/re2/nfa.cc:
src/main/tools/namespace-sandbox.c:633: execvp(argv[0], argv): No such file or directory
ERROR: /home/zoox/.cache/bazel/_bazel_zoox/111e93cf3df3e7e66024debaa46e7801/external/re2/BUILD:9:1: C++ compilation of rule '@re2//:re2' failed: crosstool_wrapper_driver_is_not_gcc failed: error executing command 
  (cd /home/zoox/.cache/bazel/_bazel_zoox/111e93cf3df3e7e66024debaa46e7801/tensorflow && \
  exec env - \
    PATH=/home/zoox/code/bazel/output:/usr/local/cuda-7.0/bin:/home/zoox/code/zoox_ros_ws/devel/bin:/home/zoox/zoox_ros_ws/devel/bin:/opt/ros/indigo/bin:/home/zoox/code/bazel/output:/usr/local/cuda-7.0/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games \
  third_party/gpus/crosstool/clang/bin/crosstool_wrapper_driver_is_not_gcc -U_FORTIFY_SOURCE '-D_FORTIFY_SOURCE=1' -fstack-protector -fPIE -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 -DNDEBUG -ffunction-sections -fdata-sections '-std=c++11' -iquote external/re2 -iquote bazel-out/local_linux-opt/genfiles/external/re2 -iquote external/bazel_tools -iquote bazel-out/local_linux-opt/genfiles/external/bazel_tools -isystem external/re2 -isystem bazel-out/local_linux-opt/genfiles/external/re2 -isystem external/bazel_tools/tools/cpp/gcc3 -no-canonical-prefixes -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' '-frandom-seed=bazel-out/local_linux-opt/bin/external/re2/_objs/re2/external/re2/re2/nfa.o' -MD -MF bazel-out/local_linux-opt/bin/external/re2/_objs/re2/external/re2/re2/nfa.d -c external/re2/re2/nfa.cc -o bazel-out/local_linux-opt/bin/external/re2/_objs/re2/external/re2/re2/nfa.o): crosstool_wrapper_driver_is_not_gcc failed: error executing command 
  (cd /home/zoox/.cache/bazel/_bazel_zoox/111e93cf3df3e7e66024debaa46e7801/tensorflow && \
  exec env - \
    PATH=/home/zoox/code/bazel/output:/usr/local/cuda-7.0/bin:/home/zoox/code/zoox_ros_ws/devel/bin:/home/zoox/zoox_ros_ws/devel/bin:/opt/ros/indigo/bin:/home/zoox/code/bazel/output:/usr/local/cuda-7.0/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games \
  third_party/gpus/crosstool/clang/bin/crosstool_wrapper_driver_is_not_gcc -U_FORTIFY_SOURCE '-D_FORTIFY_SOURCE=1' -fstack-protector -fPIE -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 -DNDEBUG -ffunction-sections -fdata-sections '-std=c++11' -iquote external/re2 -iquote bazel-out/local_linux-opt/genfiles/external/re2 -iquote external/bazel_tools -iquote bazel-out/local_linux-opt/genfiles/external/bazel_tools -isystem external/re2 -isystem bazel-out/local_linux-opt/genfiles/external/re2 -isystem external/bazel_tools/tools/cpp/gcc3 -no-canonical-prefixes -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' '-frandom-seed=bazel-out/local_linux-opt/bin/external/re2/_objs/re2/external/re2/re2/nfa.o' -MD -MF bazel-out/local_linux-opt/bin/external/re2/_objs/re2/external/re2/re2/nfa.d -c external/re2/re2/nfa.cc -o bazel-out/local_linux-opt/bin/external/re2/_objs/re2/external/re2/re2/nfa.o).
Target //tensorflow/cc:tutorials_example_trainer failed to build
INFO: Elapsed time: 7.399s, Critical Path: 2.44s
```

So nothing very useful there. Here is the sandbox_debug output, though:
```
$ bazel build --sandbox_debug -c opt --config=cuda //tensorflow/cc:tutorials_example_trainer
INFO: Found 1 target...
INFO: From Compiling external/gemmlowp/eight_bit_int_gemm/eight_bit_int_gemm.cc:
src/main/tools/namespace-sandbox.c:689: sandbox root is /home/zoox/.cache/bazel/_bazel_zoox/111e93cf3df3e7e66024debaa46e7801/tensorflow/bazel-sandbox/c298e7cd-786d-4cc2-acef-9ee1e661c448-0
src/main/tools/namespace-sandbox.c:691: working dir is /home/zoox/.cache/bazel/_bazel_zoox/111e93cf3df3e7e66024debaa46e7801/tensorflow
src/main/tools/namespace-sandbox.c:377: unshare succeeded after 1 tries
src/main/tools/namespace-sandbox.c:495: createdir: /tmp
src/main/tools/namespace-sandbox.c:495: createdir: /nonexistent
src/main/tools/namespace-sandbox.c:511: mount: /bin
src/main/tools/namespace-sandbox.c:511: mount: /etc
src/main/tools/namespace-sandbox.c:511: mount: /home/zoox/.cache/bazel/_bazel_zoox/111e93cf3df3e7e66024debaa46e7801/tensorflow/external/gemmlowp/eight_bit_int_gemm/eight_bit_int_gemm.cc
src/main/tools/namespace-sandbox.c:511: mount: /home/zoox/.cache/bazel/_bazel_zoox/111e93cf3df3e7e66024debaa46e7801/tensorflow/external/gemmlowp/eight_bit_int_gemm/eight_bit_int_gemm.h
src/main/tools/namespace-sandbox.c:511: mount: /home/zoox/.cache/bazel/_bazel_zoox/111e93cf3df3e7e66024debaa46e7801/tensorflow/external/gemmlowp/internal/allocator.h
src/main/tools/namespace-sandbox.c:511: mount: /home/zoox/.cache/bazel/_bazel_zoox/111e93cf3df3e7e66024debaa46e7801/tensorflow/external/gemmlowp/internal/block_params.h
src/main/tools/namespace-sandbox.c:511: mount: /home/zoox/.cache/bazel/_bazel_zoox/111e93cf3df3e7e66024debaa46e7801/tensorflow/external/gemmlowp/internal/common.h
src/main/tools/namespace-sandbox.c:511: mount: /home/zoox/.cache/bazel/_bazel_zoox/111e93cf3df3e7e66024debaa46e7801/tensorflow/external/gemmlowp/internal/compute.h
src/main/tools/namespace-sandbox.c:511: mount: /home/zoox/.cache/bazel/_bazel_zoox/111e93cf3df3e7e66024debaa46e7801/tensorflow/external/gemmlowp/internal/kernel.h
src/main/tools/namespace-sandbox.c:511: mount: /home/zoox/.cache/bazel/_bazel_zoox/111e93cf3df3e7e66024debaa46e7801/tensorflow/external/gemmlowp/internal/kernel_SSE.h
src/main/tools/namespace-sandbox.c:511: mount: /home/zoox/.cache/bazel/_bazel_zoox/111e93cf3df3e7e66024debaa46e7801/tensorflow/external/gemmlowp/internal/kernel_default.h
src/main/tools/namespace-sandbox.c:511: mount: /home/zoox/.cache/bazel/_bazel_zoox/111e93cf3df3e7e66024debaa46e7801/tensorflow/external/gemmlowp/internal/kernel_neon.h
src/main/tools/namespace-sandbox.c:511: mount: /home/zoox/.cache/bazel/_bazel_zoox/111e93cf3df3e7e66024debaa46e7801/tensorflow/external/gemmlowp/internal/kernel_reference.h
src/main/tools/namespace-sandbox.c:511: mount: /home/zoox/.cache/bazel/_bazel_zoox/111e93cf3df3e7e66024debaa46e7801/tensorflow/external/gemmlowp/internal/multi_thread_gemm.h
src/main/tools/namespace-sandbox.c:511: mount: /home/zoox/.cache/bazel/_bazel_zoox/111e93cf3df3e7e66024debaa46e7801/tensorflow/external/gemmlowp/internal/pack.h
src/main/tools/namespace-sandbox.c:511: mount: /home/zoox/.cache/bazel/_bazel_zoox/111e93cf3df3e7e66024debaa46e7801/tensorflow/external/gemmlowp/internal/pack_neon.h
src/main/tools/namespace-sandbox.c:511: mount: /home/zoox/.cache/bazel/_bazel_zoox/111e93cf3df3e7e66024debaa46e7801/tensorflow/external/gemmlowp/internal/single_thread_gemm.h
src/main/tools/namespace-sandbox.c:511: mount: /home/zoox/.cache/bazel/_bazel_zoox/111e93cf3df3e7e66024debaa46e7801/tensorflow/external/gemmlowp/internal/unpack.h
src/main/tools/namespace-sandbox.c:511: mount: /home/zoox/.cache/bazel/_bazel_zoox/111e93cf3df3e7e66024debaa46e7801/tensorflow/external/gemmlowp/internal/unpack_neon.h
src/main/tools/namespace-sandbox.c:511: mount: /home/zoox/.cache/bazel/_bazel_zoox/111e93cf3df3e7e66024debaa46e7801/tensorflow/external/gemmlowp/profiling/instrumentation.h
src/main/tools/namespace-sandbox.c:511: mount: /home/zoox/.cache/bazel/_bazel_zoox/111e93cf3df3e7e66024debaa46e7801/tensorflow/external/gemmlowp/profiling/profiler.h
src/main/tools/namespace-sandbox.c:511: mount: /home/zoox/.cache/bazel/_bazel_zoox/111e93cf3df3e7e66024debaa46e7801/tensorflow/external/gemmlowp/public/bit_depth.h
src/main/tools/namespace-sandbox.c:511: mount: /home/zoox/.cache/bazel/_bazel_zoox/111e93cf3df3e7e66024debaa46e7801/tensorflow/external/gemmlowp/public/gemmlowp.h
src/main/tools/namespace-sandbox.c:511: mount: /home/zoox/.cache/bazel/_bazel_zoox/111e93cf3df3e7e66024debaa46e7801/tensorflow/external/gemmlowp/public/map.h
src/main/tools/namespace-sandbox.c:511: mount: /home/zoox/.cache/bazel/_bazel_zoox/install/139c7272ae5924b242fb67979ea76cae/_embedded_binaries/build-runfiles
src/main/tools/namespace-sandbox.c:511: mount: /lib
src/main/tools/namespace-sandbox.c:511: mount: /lib32
src/main/tools/namespace-sandbox.c:511: mount: /lib64
src/main/tools/namespace-sandbox.c:511: mount: /sbin
src/main/tools/namespace-sandbox.c:511: mount: /usr/bin
src/main/tools/namespace-sandbox.c:511: mount: /usr/etc
src/main/tools/namespace-sandbox.c:511: mount: /usr/games
src/main/tools/namespace-sandbox.c:511: mount: /usr/include
src/main/tools/namespace-sandbox.c:511: mount: /usr/lib
src/main/tools/namespace-sandbox.c:511: mount: /usr/lib32
src/main/tools/namespace-sandbox.c:511: mount: /usr/sbin
src/main/tools/namespace-sandbox.c:511: mount: /usr/share
src/main/tools/namespace-sandbox.c:511: mount: /usr/src
src/main/tools/namespace-sandbox.c:619: arg: third_party/gpus/crosstool/clang/bin/crosstool_wrapper_driver_is_not_gcc
src/main/tools/namespace-sandbox.c:619: arg: -U_FORTIFY_SOURCE
src/main/tools/namespace-sandbox.c:619: arg: -D_FORTIFY_SOURCE=1
src/main/tools/namespace-sandbox.c:619: arg: -fstack-protector
src/main/tools/namespace-sandbox.c:619: arg: -fPIE
src/main/tools/namespace-sandbox.c:619: arg: -Wall
src/main/tools/namespace-sandbox.c:619: arg: -Wunused-but-set-parameter
src/main/tools/namespace-sandbox.c:619: arg: -Wno-free-nonheap-object
src/main/tools/namespace-sandbox.c:619: arg: -fno-omit-frame-pointer
src/main/tools/namespace-sandbox.c:619: arg: -g0
src/main/tools/namespace-sandbox.c:619: arg: -O2
src/main/tools/namespace-sandbox.c:619: arg: -DNDEBUG
src/main/tools/namespace-sandbox.c:619: arg: -ffunction-sections
src/main/tools/namespace-sandbox.c:619: arg: -fdata-sections
src/main/tools/namespace-sandbox.c:619: arg: -std=c++11
src/main/tools/namespace-sandbox.c:619: arg: -iquote
src/main/tools/namespace-sandbox.c:619: arg: external/gemmlowp
src/main/tools/namespace-sandbox.c:619: arg: -iquote
src/main/tools/namespace-sandbox.c:619: arg: bazel-out/local_linux-opt/genfiles/external/gemmlowp
src/main/tools/namespace-sandbox.c:619: arg: -iquote
src/main/tools/namespace-sandbox.c:619: arg: external/bazel_tools
src/main/tools/namespace-sandbox.c:619: arg: -iquote
src/main/tools/namespace-sandbox.c:619: arg: bazel-out/local_linux-opt/genfiles/external/bazel_tools
src/main/tools/namespace-sandbox.c:619: arg: -isystem
src/main/tools/namespace-sandbox.c:619: arg: external/bazel_tools/tools/cpp/gcc3
src/main/tools/namespace-sandbox.c:619: arg: -no-canonical-prefixes
src/main/tools/namespace-sandbox.c:619: arg: -Wno-builtin-macro-redefined
src/main/tools/namespace-sandbox.c:619: arg: -D__DATE__="redacted"
src/main/tools/namespace-sandbox.c:619: arg: -D__TIMESTAMP__="redacted"
src/main/tools/namespace-sandbox.c:619: arg: -D__TIME__="redacted"
src/main/tools/namespace-sandbox.c:619: arg: -frandom-seed=bazel-out/local_linux-opt/bin/external/gemmlowp/_objs/eight_bit_int_gemm/external/gemmlowp/eight_bit_int_gemm/eight_bit_int_gemm.o
src/main/tools/namespace-sandbox.c:619: arg: -MD
src/main/tools/namespace-sandbox.c:619: arg: -MF
src/main/tools/namespace-sandbox.c:619: arg: bazel-out/local_linux-opt/bin/external/gemmlowp/_objs/eight_bit_int_gemm/external/gemmlowp/eight_bit_int_gemm/eight_bit_int_gemm.d
src/main/tools/namespace-sandbox.c:619: arg: -c
src/main/tools/namespace-sandbox.c:619: arg: external/gemmlowp/eight_bit_int_gemm/eight_bit_int_gemm.cc
src/main/tools/namespace-sandbox.c:619: arg: -o
src/main/tools/namespace-sandbox.c:619: arg: bazel-out/local_linux-opt/bin/external/gemmlowp/_objs/eight_bit_int_gemm/external/gemmlowp/eight_bit_int_gemm/eight_bit_int_gemm.o
src/main/tools/namespace-sandbox.c:633: execvp(argv[0], argv): No such file or directory
ERROR: /home/zoox/.cache/bazel/_bazel_zoox/111e93cf3df3e7e66024debaa46e7801/external/gemmlowp/BUILD:77:1: C++ compilation of rule '@gemmlowp//:eight_bit_int_gemm' failed: crosstool_wrapper_driver_is_not_gcc failed: error executing command third_party/gpus/crosstool/clang/bin/crosstool_wrapper_driver_is_not_gcc -U_FORTIFY_SOURCE '-D_FORTIFY_SOURCE=1' -fstack-protector -fPIE -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object ... (remaining 30 argument(s) skipped).
Target //tensorflow/cc:tutorials_example_trainer failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 1.074s, Critical Path: 0.49s
```

From my reading of `namespace-sandbox.c` it seems like bazel is not able to find the crosstool_wrapper_driver_is_not_gcc wrapper.

**Comment by damienmg** [comment] 2015-12-11 20:33
Try with `--genrule_strategy=standalone --spawn_strategy=standalone`

**Comment by philbinj** [comment] 2015-12-11 20:43
It works! So is this a bug with the sandboxing or with Tensorflow?

Thanks,
James

On Fri, Dec 11, 2015 at 12:33 PM, Damien Martin-Guillerez <
notifications@github.com> wrote:

> Try with --genrule_strategy=standalone --spawn_strategy=standalone
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bazelbuild/bazel/issues/698#issuecomment-164041244>.
>



-- 
James Philbin | Senior Director of Computer Vision I Zoox.com I +1 310 279
8029

**Comment by damienmg** [comment] 2015-12-11 20:47
Where is bash on your system?

I guess this is more on Bazel side.

**Comment by philbinj** [comment] 2015-12-11 20:50
$ which bash
/bin/bash

I suppose the question really is: how does cc_toolchain work, and how does it know to find files referenced in CROSSTOOL (this stuff is completely undocumented AFAICT).

**Comment by damienmg** [comment] 2015-12-11 20:52
`readlink $(which bash)`?

Also
`readlink $(env python2)`?

Because https://github.com/tensorflow/tensorflow/blob/master/third_party/gpus/crosstool/clang/bin/crosstool_wrapper_driver_is_not_gcc is looking for python2

**Comment by damienmg** [comment] 2015-12-11 20:53
and yeah sorry for the mess with crosstool, this is undocumented and highly versatile :(

**Comment by philbinj** [comment] 2015-12-11 20:55
All seems ok I think:
===
$ readlink -f $(which bash)
/bin/bash
$ readlink -f $(which python2)                                                                                                                                                                                                                        
/usr/bin/python2.7
===

**Comment by damienmg** [comment] 2015-12-11 21:06
yes both are mounted in the sandbox. I guess `env python2` returns you the correct thing too. It will take more time to investigate

I wonder if the crosstool script is correctly mounted. It doesn't seem like it from the log but I don't really know.

@lberki, @philwo or @ulfjack might have more ideas.

**Comment by philbinj** [comment] 2015-12-11 21:30
> and yeah sorry for the mess with crosstool, this is undocumented and highly versatile :(

No need to apologize: actually i've found Bazel to be extremely well documented for the most part. Every big system has some dark corners... :)

**Comment by philbinj** [comment] 2015-12-11 21:32
Another datapoint: only `--spawn_strategy=standalone` is required for things to work.

**Comment by vrv** [comment] 2015-12-11 22:07
Just to give some further info: this was working fine at 0.1.1 but broke in 0.1.2.  --spawn_strategy=standalone is the only workaround for me too.

(After that, 0.1.2 is also causing undeclared inclusion errors, but that's a problem on our side that I'm fixing right now).

**Comment by bsilver8192** [comment] 2015-12-12 20:20
Looks to me like the problem is that `third_party/gpus/crosstool/clang/bin/crosstool_wrapper_driver_is_not_gcc` isn't included in the correct place(s) in [third_party/gpus/crosstool/BUILD](https://github.com/tensorflow/tensorflow/blob/master/third_party/gpus/crosstool/BUILD). It should definitely show up in the list of mounted files with `--sandbox_debug`.

I've found it necessary to add various files to `:toolchain` and the filegroups used in `cc-compiler-<CPU>:*_files` to get custom compilers not in /usr working under sandboxing. I don't know what "should" go where, so I basically add files that aren't getting mounted until it works (#59 has updates on fixing that).

Some helpful hints from my experience doing this: things in `all-files` are mounted into the sandbox when compiling but not when linking, and test that everything builds after a `bazel clean` before calling it done because Bazel tends to cache outputs built without sandboxing even after you start using sandboxing for newly executed actions.

**Comment by lberki** [comment] 2015-12-15 12:34
My guess is that either env of python2 links to a library that's not present in the sandbox. Can you try this?

```
touch WORKSPACE
cat > BUILD <<EOF
sh_binary(
    name = "ldd",
    srcs = ["ldd.sh"],
)

genrule(
    name = "gen_ldd",
    srcs = [],
    outs = ["gen_ldd_out"],
    cmd = "$(location :ldd)",
    tools = [":ldd"],
)

sh_binary(
    name = "envpy",
    srcs = ["envpy.sh"],
)

genrule(
    name = "gen_envpy",
    srcs = [],
    outs = ["gen_envpy_out"],
    cmd = "$(location :envpy)",
    tools = [":envpy"],
)
EOF

cat > envpy.sh <<EOF
#!/usr/bin/env python2
print "HELLO"
EOF

cat > ldd.sh <<EOF
#!/bin/bash
echo $(whch python2)
ldd $(which python2)
ldd /usr/bin/env
EOF

chmod +x *.sh
bazel build :gen_ldd
bazel build :gen_envpy
```

Each of these Bazel command should fail with "not all outputs were created", but output something interesting.

**Comment by philbinj** [comment] 2015-12-15 18:55
OK, I tried lberki's suggestion above. For `gen_ldd`:
```
$ bazel build :gen_ldd
INFO: Found 1 target...
INFO: From Executing genrule //:gen_ldd:
/usr/bin/python2
        linux-vdso.so.1 =>  (0x00007ffdf1d46000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007ff8b9f97000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007ff8b9bd2000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007ff8b99ce000)
        libutil.so.1 => /lib/x86_64-linux-gnu/libutil.so.1 (0x00007ff8b97cb000)
        libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007ff8b95b2000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007ff8b92ac000)
        /lib64/ld-linux-x86-64.so.2 (0x00007ff8ba1b5000)
        linux-vdso.so.1 =>  (0x00007fff01afc000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f2803e4e000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f2804213000)
ERROR: /home/zoox/code/delme/BUILD:6:1: declared output 'gen_ldd_out' was not created by genrule. This is probably because the genrule actually didn't create this output, or because the output was a directory and the genrule was run remotely (note that only the contents of declared file outputs are copied from genrules run remotely).
ERROR: /home/zoox/code/delme/BUILD:6:1: not all outputs were created.
Target //:gen_ldd failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 0.212s, Critical Path: 0.12s
```

For `gen_envpy`:
```
$ bazel build :gen_envpy
INFO: Found 1 target...
INFO: From Executing genrule //:gen_envpy:
HELLO
ERROR: /home/zoox/code/delme/BUILD:19:1: declared output 'gen_envpy_out' was not created by genrule. This is probably because the genrule actually didn't create this output, or because the output was a directory and the genrule was run remotely (note that only the contents of declared file outputs are copied from genrules run remotely).
ERROR: /home/zoox/code/delme/BUILD:19:1: not all outputs were created.
Target //:gen_envpy failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 0.186s, Critical Path: 0.10s
```

Is this helpful?

**Comment by lberki** [comment] 2015-12-15 20:46
This was done *without* `--*_strategy=standalone`, right? This indicates that contrary to my expectations, the problem is not with not finding `env` or some weird dynamic linking issue with `python2`. I'll sleep over this, because ATM I have no idea.

**Comment by philbinj** [comment] 2015-12-15 21:01
Yes, without --strategy=standalone.

Isn't bsilver's point correct? crosstool_wrapper_driver_is_not_gcc is
simply not being mounted in the sandbox, so bazel can't run it? The
question is where to include that file in cc_crosstool?

James

On Tue, Dec 15, 2015 at 12:47 PM, lberki <notifications@github.com> wrote:

> This was done *without* --*_strategy=standalone, right? This indicates
> that contrary to my expectations, the problem is not with not finding env
> or some weird dynamic linking issue with python2. I'll sleep over this,
> because ATM I have no idea.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bazelbuild/bazel/issues/698#issuecomment-164891858>.
>



-- 
James Philbin | Senior Director of Computer Vision I Zoox.com I +1 310 279
8029

**Comment by bsilver8192** [comment] 2015-12-15 21:06
I would start with adding it to the srcs of //third_party/gpus/crosstool:crosstool and a newly created `filegroup` in //third_party/gpus/crosstool that you set `all_files` and `compiler_files` of `:cc-compiler-local` to.

**Comment by philwo** [comment] 2015-12-15 21:08
Yes, @bsilver8192 is correct - crosstool_wrapper_driver_is_not_gcc is simply missing from the mounts. If it's needed during compilation, it should go into the "compiler_files" filegroup (which should be part of the "all_files" filegroup) of the cc_toolchain. (AFAIU - but I'm not very experienced with our cc_toolchain rule.)

**Comment by philbinj** [comment] 2015-12-15 21:59
Yup, this seems to work, I changed `all_files`, `compiler_files` and `linker_files` to point to a filegroup target that contains both the script and nvcc. Here's a patch for tensorflow:
```
diff --git a/third_party/gpus/crosstool/BUILD b/third_party/gpus/crosstool/BUILD
index eac4dc7..32b6af7 100644
--- a/third_party/gpus/crosstool/BUILD
+++ b/third_party/gpus/crosstool/BUILD
@@ -8,14 +8,22 @@ filegroup(
     output_licenses = ["unencumbered"],
 )
 
+filegroup(
+    name = "toolchain",
+    srcs = [
+        "clang/bin/crosstool_wrapper_driver_is_not_gcc",
+        "//third_party/gpus/cuda:nvcc",
+    ],
+)
+
 cc_toolchain(
     name = "cc-compiler-local",
-    all_files = ":empty",
-    compiler_files = ":empty",
+    all_files = ":toolchain",
+    compiler_files = ":toolchain",
     cpu = "local",
     dwp_files = ":empty",
     dynamic_runtime_libs = [":empty"],
-    linker_files = ":empty",
+    linker_files = ":toolchain",
     objcopy_files = ":empty",
     static_runtime_libs = [":empty"],
     strip_files = ":empty",
diff --git a/third_party/gpus/cuda/BUILD b/third_party/gpus/cuda/BUILD
index 40c0486..89b9004 100644
--- a/third_party/gpus/cuda/BUILD
+++ b/third_party/gpus/cuda/BUILD
@@ -4,6 +4,11 @@ load("/tensorflow/tensorflow", "if_cuda")
 
 package(default_visibility = ["//visibility:public"])
 
+filegroup(
+    name = "nvcc",
+    srcs = ["bin/nvcc"],
+)
+
 config_setting(
     name = "cuda_crosstool_condition",
     values = {"crosstool_top": "//third_party/gpus/crosstool"},
@@ -31,6 +36,7 @@ cc_library(
     name = "cuda_headers",
     hdrs = glob([
         "**/*.h",
+        "**/*.hpp",
     ]),
     includes = [".", "include"],
     visibility = ["//visibility:public"],
```

Compiling still fails, but I think it is unrelated to this issue (to do with missing includes).

**Comment by kevchin** [comment] 2015-12-31 04:51
I adapted CUDA install using AMI instructions from here:
https://gist.github.com/erikbern/78ba519b97b440e10640

But still have this bazel compile failing:

`bazel build --sandbox_debug -c opt --config=cuda --spawn_strategy=standalone //tensorflow/cc:tutorials_example_trainer
INFO: Found 1 target...
ERROR: /mnt/tmp/tensorflow/tensorflow/stream_executor/BUILD:5:1: undeclared inclusion(s) in rule '//tensorflow/stream_executor:stream_executor':
this rule is missing dependency declarations for the following files included by 'tensorflow/stream_executor/cuda/cuda_rng.cc':
  '/usr/local/cuda-7.0/include/cuda_runtime.h'
  '/usr/local/cuda-7.0/include/host_config.h'
  '/usr/local/cuda-7.0/include/builtin_types.h'
  '/usr/local/cuda-7.0/include/device_types.h'
  '/usr/local/cuda-7.0/include/driver_types.h'
  '/usr/local/cuda-7.0/include/surface_types.h'
  '/usr/local/cuda-7.0/include/texture_types.h'
  '/usr/local/cuda-7.0/include/vector_types.h'
  '/usr/local/cuda-7.0/include/channel_descriptor.h'
  '/usr/local/cuda-7.0/include/cuda_runtime_api.h'
  '/usr/local/cuda-7.0/include/host_defines.h'
  '/usr/local/cuda-7.0/include/cuda_device_runtime_api.h'
  '/usr/local/cuda-7.0/include/driver_functions.h'
  '/usr/local/cuda-7.0/include/vector_functions.h'
  '/usr/local/cuda-7.0/include/vector_functions.hpp'.
Target //tensorflow/cc:tutorials_example_trainer failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 5.428s, Critical Path: 4.71s.
`
Is this the 'include' error? Anyone have better luck yet? If so, what steps/flags did you use?

thanks

### Using notes from: https://gist.github.com/erikbern/78ba519b97b440e10640
#### Install CUDA 7.0 (note – don't use any other version)
wget http://developer.download.nvidia.com/compute/cuda/7_0/Prod/local_installers/cuda_7.0.28_linux.run
chmod +x cuda_7.0.28_linux.run
./cuda_7.0.28_linux.run -extract=`pwd`/nvidia_installers
cd nvidia_installers
sudo ./NVIDIA-Linux-x86_64-346.46.run 
sudo modprobe nvidia
sudo ./cuda-linux64-rel-7.0.28-19326674.run 
cd

#### Install CUDNN 6.5 (note – don't use any other version)
tar -xzf cudnn-6.5-linux-x64-v2.tgz 
sudo cp cudnn-6.5-linux-x64-v2/libcudnn* /usr/local/cuda/lib64
sudo cp cudnn-6.5-linux-x64-v2/cudnn.h /usr/local/cuda/include/

#### At this point the root mount is getting a bit full (work-around follows)
#### Make sure you don't run out of disk space when building Tensorflow!
sudo mkdir /mnt/tmp
sudo chmod 777 /mnt/tmp
sudo rm -rf /tmp
sudo ln -s /mnt/tmp /tmp

#### Install Bazel
cd /mnt/tmp
git clone https://github.com/bazelbuild/bazel.git
cd bazel
git checkout tags/0.1.0
./compile.sh
sudo cp output/bazel /usr/bin

#### Install TensorFlow
cd /mnt/tmp
export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:/usr/local/cuda/lib64"
export CUDA_HOME=/usr/local/cuda
git clone --recurse-submodules https://github.com/tensorflow/tensorflow
cd tensorflow

### EDIT: Fails to compile with this first 'bazel' command
TF_UNOFFICIAL_SETTING=1 ./configure
bazel build -c opt --config=cuda --spawn_strategy=standalone //tensorflow/cc:tutorials_example_trainer

#### Build Python package
#### Note: you have to specify --config=cuda here - this is not mentioned in the official docs
bazel build -c opt --config=cuda --spawn_strategy=standalone //tensorflow/tools/pip_package:build_pip_package
bazel-bin/tensorflow/tools/pip_package/build_pip_package /tmp/tensorflow_pkg
sudo pip install /tmp/tensorflow_pkg/tensorflow-0.5.0-cp27-none-linux_x86_64.whl

#### Test it!
cd tensorflow/models/image/cifar10/
python cifar10_multi_gpu_train.py

**Comment by lberki** [comment] 2016-01-04 13:37
@kevchin which gcc version are you using and which Linux version? This seems to mirror an issue with gcc whereupon it dereferences symlinks in .d files and thus confuses Bazel. I tried doing this on my workstation with gcc 4.8.4, and it works alright, but I have seen similar issues in the past.

Could you try installing CUDA at a location whose path is longer (no, this is not a joke, really)? I have seen cases when gcc would dereferences symlinks if the path of the target of the symlink was *short*, as strange as that might seem.

**Comment by lberki** [comment] 2016-01-04 13:50
I spoke too early! I can reproduce this issue with if I install CUDA at a short path (`/opt/cuda` and `/opt/cuda-7.0` in particular) with the same gcc. So, barring fixing gcc, install CUDA at a longer path (no kidding!), and it will work. I don't know why.

**Comment by lberki** [comment] 2016-01-04 15:44
Oh, actually, this C++ compilation takes place not with the system gcc, but the CUDA gcc. Then, I suppose the system your are using is irrelevant.

**Comment by lberki** [comment] 2016-01-07 10:37
Surprisingly enough, this the same bug as #714 and is fixed by adding `-fno-canonical-system-headers` to the gcc command line. So I'm closing this as a duplicate of that one.

**Closed** 2016-01-07 10:37 UTC
Labels: bug, P2
