### ISSUE TITLE
Bug: bazel mod show_repo crashes

### ISSUE THREAD

**Issue by thesayyn** [bazelbuild/bazel#23736] opened 2024-09-24 16:25 UTC
### Description of the bug:

When running `bazel mod show_repo @distroless` it crashes bazel. I am probably running the command in a wrong way but bazel still shouldn't crash.

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

```
git clone  https://github.com/GoogleContainerTools/distroless
bazel mod show_repo @distroless
```

### Which operating system are you running Bazel on?

darwin/arm64

### What is the output of `bazel info release`?

release 7.2.0

### Any other information, logs, or outputs that you want to share?

```
Starting local Bazel server and connecting to it...
 checking cached actions
    Fetching module extension pip_internal in @@rules_python~//python/private/pypi:pip.bzl; starting
    Fetching https://pypi.org/simple/cryptography/
    Fetching https://pypi.org/simple/docutils/
FATAL: bazel crashed due to an internal error. Printing stack trace:
java.lang.RuntimeException: Unrecoverable error while evaluating node 'BZLMOD_REPO_RULE:@@' (requested by nodes )
        at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:550)
        at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:414)
        at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinPool.scan(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
Caused by: java.lang.NullPointerException
        at java.base/java.util.Objects.requireNonNull(Unknown Source)
        at java.base/java.util.Optional.of(Unknown Source)
        at com.google.devtools.build.lib.skyframe.BzlmodRepoRuleFunction.checkRepoFromBazelModules(BzlmodRepoRuleFunction.java:161)
        at com.google.devtools.build.lib.skyframe.BzlmodRepoRuleFunction.compute(BzlmodRepoRuleFunction.java:111)
        at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:461)
        ... 7 more

```

**Comment by fmeum** [comment] 2024-09-25 10:06
This is a duplicate of https://github.com/bazelbuild/bazel/issues/22587. I requested a cherry-pick to 7.4.0.

**Closed by fmeum** 2024-09-25 10:06 UTC
Labels: type: bug, untriaged, team-Core, team-OSS
