### ISSUE TITLE
Bazel fail to connect to the server

### ISSUE THREAD

**Issue by AlvinChen13** [bazelbuild/bazel#1636] opened 2016-08-12 00:49 UTC
Hi all,

I just try to build tensorflow by bazel, but I get the following error, anyone can help on it?
Thanks!

alvin@hal-dev:~/tensorflow-r0.9$ bazel build -c opt --config=cuda //tensorflow/cc:tutorials_example_trainer
Found stale PID file (pid=29629). Server probably died abruptly, continuing...
.
unexpected pipe read status: Connection refused
Server presumed dead. Now printing '/home/alvin/.cache/bazel/_bazel_alvin/098c27509f757cf22af83c9a7d1d8ec7/server/jvm.out':
java.lang.AssertionError: java.security.NoSuchAlgorithmException: MD5 MessageDigest not available
at com.google.common.hash.MessageDigestHashFunction.getMessageDigest(MessageDigestHashFunction.java:79)
at com.google.common.hash.MessageDigestHashFunction.(MessageDigestHashFunction.java:40)
at com.google.common.hash.Hashing$Md5Holder.(Hashing.java:191)
at com.google.common.hash.Hashing.md5(Hashing.java:187)
at com.google.devtools.build.lib.analysis.BlazeDirectories.checkMD5(BlazeDirectories.java:95)
at com.google.devtools.build.lib.analysis.BlazeDirectories.(BlazeDirectories.java:74)
at com.google.devtools.build.lib.runtime.BlazeRuntime.newRuntime(BlazeRuntime.java:926)
at com.google.devtools.build.lib.runtime.BlazeRuntime.createBlazeRPCServer(BlazeRuntime.java:781)
at com.google.devtools.build.lib.runtime.BlazeRuntime.serverMain(BlazeRuntime.java:726)
at com.google.devtools.build.lib.runtime.BlazeRuntime.main(BlazeRuntime.java:519)
at com.google.devtools.build.lib.bazel.BazelMain.main(BazelMain.java:56)
Caused by: java.security.NoSuchAlgorithmException: MD5 MessageDigest not available
at sun.security.jca.GetInstance.getInstance(GetInstance.java:159)
at java.security.Security.getImpl(Security.java:695)
at java.security.MessageDigest.getInstance(MessageDigest.java:167)
at com.google.common.hash.MessageDigestHashFunction.getMessageDigest(MessageDigestHashFunction.java:77)

**Comment by hermione521** [comment] 2016-08-12 09:29
The same to your another issue. Your JRE version?

**Comment by kchodorow** [comment] 2016-08-12 14:16
Duplicate of #1638.

**Closed by kchodorow** 2016-08-12 14:16 UTC
Labels: Duplicate, Under investigation
