### ISSUE TITLE
Strict determinism mode

### ISSUE THREAD

**Issue by alexeagle** [bazelbuild/bazel#5877] opened 2018-08-13 18:04 UTC
Discussed with @philwo - I'd like to be able to test that my rules are deterministic. This would probably require Bazel to run actions multiple times and assert that the output hashes match. Perhaps it could be exposed with a flag like `--verify_deterministic_outputs` or similar. I'd use this on my CI.

**Comment by ittaiz** [comment] 2018-08-13 19:19
Sounds great!
We currently use bazel-integration-testing to write such tests. We mainly
verify the time aspect this way.

**Comment by jmmv** [comment] 2019-03-14 10:33
Hah, funny enough I had to troubleshoot a non-deterministic rule recently and it was incredibly painful to do so.

That said, I'm not sure this feature belongs within Bazel itself. The case I was investigating, for example, was caused by different remote execution environments used when invoking Bazel from different "locations": running Bazel from CI and locally would result in different action outputs, but running Bazel from either of these would produce deterministic outputs. In other words: Bazel itself wouldn't have caught the nondeterminism problem on its own.

Maybe having a mechanism to compare the contents of the local action cache across two different builds would be a better way of achieving this? I think all the information we need is stored there.

**Comment by jmmv** [comment] 2020-05-11 19:44
I still think this belongs outside of Bazel. It's fairly easy to build a script that builds the same thing twice, records output digests or something, and compares them. (That's what we do at Google actually, with some ad-hoc scripts.) So... I'm going to close this for now and move it out of local execution; has nothing to do with it. Please let us know if you disagree.

**Closed by jmmv** 2020-05-11 19:44 UTC
Labels: P3, team-Local-Exec, type: feature request
