### ISSUE TITLE
[7.1.0] Update java_tools v13.4 / rules_java 7.4.0

### ISSUE THREAD

**Issue by bazel-io** [bazelbuild/bazel#21358] opened 2024-02-14 21:44 UTC
Forked from #21222

**Comment by bazel-io** [comment] 2024-02-14 21:44
Cherry-pick was attempted, but there may be merge conflict(s). Please resolve manually.
cc: @bazelbuild/triage

**Comment by iancha1992** [comment] 2024-02-14 21:45
Dupe of https://github.com/bazelbuild/bazel/issues/21160

**Closed by iancha1992** 2024-02-14 21:45 UTC
