### ISSUE TITLE
Log filegroups only once in execution_log_json_file and reference them in all the spawns where they are used

### ISSUE THREAD

**Issue by abdulsattar** [bazelbuild/bazel#19628] opened 2023-09-25 23:17 UTC
### Description of the feature request:

filegroups are an easy way of grouping files together and using them across several spawns. If a filegroup is used across several spawns (especially if those are executed as persistent workers thousands of times), it increases the size of execution_log_json_file.

We run into this when we use rules_js with:
```
js_binary(
    name = "bin",
    data = [
        "//:node_modules/react",
        "//:node_modules/eslint",
        "...",
    ],
    entry_point = "index.js",
)
```
These node_modules collectively can be hundreds of thousands of files, which multipled with thousands of persistent worker invocations runs easily into millions of lines in execution_log_json_file with the same repeating inputs.

One simple way to address this is to use filegroup *if a filegroup appears only once in the execution_log*:
```
filegroup(
  name = "node_modules_group",
  srcs = [
        "//:node_modules/react",
        "//:node_modules/eslint",
        "...",
  ]
)

js_binary(
    name = "bin",
    data = [":node_modules_group"],
    entry_point = "index.js",
)
```

### Which category does this issue belong to?

Performance

### What underlying problem are you trying to solve with this feature?

Reduce the size of execution_log_json_file in cases where several filegroups are used.

### Which operating system are you running Bazel on?

MacOS

### What is the output of `bazel info release`?

release 6.1.0

**Comment by tjgq** [comment] 2023-09-26 10:18
We are planning to address the shortcomings of the execution log format in Q4 (specifically, by designing a leaner format that avoids storing duplicate information). Therefore I'm going to close this in favor of https://github.com/bazelbuild/bazel/issues/18643.

**Closed by tjgq** 2023-09-26 10:18 UTC
Labels: type: feature request, team-Performance
