### ISSUE TITLE
Support systemwide installations to arbitrary directory

### ISSUE THREAD

**Issue by eiennohito** [bazelbuild/bazel#592] opened 2015-11-12 02:04 UTC
Currently the blocker is hardcoded path for default bazelrc
https://github.com/bazelbuild/bazel/blob/master/src/main/cpp/blaze_startup_options.cc#L177

If it would be possible to change it at the compile time, it would be very nice.

**Comment by damienmg** [comment] 2015-11-12 07:10
This file is not mandatory and you have several other way to specify master bazelrc:  see http://bazel.io/blog/2015/07/01/Configuration-File.html. Can you be more specific on what you are trying to do?

**Comment by eiennohito** [comment] 2015-11-12 08:02
Thank you for the reply.

I did not understand about the location of alongside bazel rc file from that blog post.

I wanted to intstall bazel into Homebrew's /usr/local/Cellar/bazel/<version>/.
Simple installation worked, but obviously it wasn't able to find bazel.bazelrc in /usr/local/Cellar/bazel/0.1.1/lib/bazel/etc

After copying slightly modified one to ~/.bazelrc everything worked, but it would be nice to be able specify non-default location for system-wide configuration and installation.

**Comment by damienmg** [comment] 2015-11-12 09:30
Let say your bazel binary is at /usr/local/Cellar/bazel/0.1.1/bin/bazel
Then you can store your system-wide bazelrc at /usr/local/Cellar/bazel/0.1.1/bin/bazel.bazelrc

I agree we could upgrade the /etc/bazel.bazelrc location but it is here for standard system to put in /etc where it is standard. In the other case the "alongside" master bazelrc is more logical.

I would recommend not to use ~/.bazelrc and let this file for user specific configuration. Note that incoming change will get rid of the base workspace all together and you will no longer need all those settings.

**Comment by eiennohito** [comment] 2015-11-12 09:50
I agree that /etc is a standard location, but sometimes you want to change default hardcoded paths.

Looking forward to incoming changes.

**Comment by jmmv** [comment] 2016-02-29 19:37
I just encountered this same issue when writing a Bazel package for [pkgsrc](http://pkgsrc.org/) so here are my two cents.

`/etc` is not a standard location and assuming so is a very Linux-centric view on the issue.

For example: the default location for configuration files installed via packages under FreeBSD is `/usr/local/etc/` and the default for NetBSD is `/usr/pkg/etc/`. Packages that do not follow these conventions are considered to be *broken* and they need to be fixed. I'm sure the same applies to other BSDs.

In particular, this also applies to OS X where there is no native packaging system that integrates with the base OS. Some of these packaging systems allow you to build packages as non-root, and they intend the built packages to look up files in the location they were installed, not outside. For example, I use pkgsrc on OS X to install my software under `~/pkg/` and I expect any software installed in this manner to look for its configuration under `~/pkg/etc/`. Asking the user in these circumstances to edit a system-wide file in `/etc` is not a valid path because the user may not have root privileges. I think the same applies to Homebrew (as discussed in this bug), MacPorts, Fink, nixpkgs...

Additionally, asking users to put a configuration file in `.../bin/bazel.bazelrc` is just not a valid alternative because this violates the file hierarchy of any Unix system, and *that* is standard.

More on the purity side of things, this whole thing is about hermeticity: if a system wants to install software under a prefix, said software should not leak outside of it. And considering that Bazel praises itself about hermetic builds, it'd be good if Bazel could respect the OS's choices on this topic :)

I'm not sure how this could be fixed in Bazel though. Allowing customizing the location of the configuration file requires build-time configuration... For the time being, I'm adding a local patch to that package for pkgsrc to fix up the location of the configuration file during the build.

**Comment by ulfjack** [comment] 2016-03-01 08:14
We don't necessarily need a system-wide bazel.bazelrc, at least not as part
of the basic installation. If we want to keep one, we could have the shell
installer modify the bazel binary on the fly to reconfigure it. Although at
some point we may have to ship platform-specific binary packages...

**Comment by helenalt** [comment] 2018-03-05 15:12
@cvcal Is this related to the work you're doing in #4502

**Comment by cvcal** [comment] 2018-03-06 03:49
Definitely related.
I think it is a duplicate of the same concern: the /etc/ location is probably staying, for the reasons mentioned above. The per-workspace location and /etc/ location, combined, probably are enough to address this, since bazelrcs can import other files from arbitrary paths. 

Unfortunately, I don't think we will be making it possible to modify the system-wide location: these paths need to be set somewhere, and asking users to set a custom path for each build is unsustainable. We could imagine using environment variables to handle the customization, but I'm not sure that's much better than having the /etc/ or workspace-relative file import another bazelrc. If, @eiennohito, this does not seem like it addresses the old bug, could you let me know?

**Comment by jmmv** [comment] 2018-03-06 15:22
How is setting a path for the build unsustainable? Pretty much every other piece of software out there supports customizing the layout of installed files—and we must do as well if we want Bazel to play well with the variety of Unix-like systems that exist out there. If we cannot do this (when the most trivial autoconf-based project can), it highlights more of a problem in Bazel than in the request itself.

Environment variables are a bad solution. If you expose these as environment variables, you are basically telling users that they need to tweak their shell startup scripts to define variables they are not responsible for setting. E.g. if the operator has installed Bazel under, say, `/opt/google/bazel/` and placed the `bazelrc` file in `/opt/google/bazel/etc/bazelrc`, the user should not have to do *anything* for this to work. But with environment variables, they must.

O possible solution could be to have a `Config.java` file with all these hardcoded locations in one place. We could tell users to modify that single file to match the layout of their system prior building and installing Bazel. Not ideal but better than nothing.

A slightly-nicer solution could be to have a top-level `config.bzl` file with these constants and make our build rules inject the values into whichever source file needs them. Still not ideal, but many projects out there follow this same style: they have a top-level `config.mk` file of some form where overrides can be set.

Note that when I say "user" I primarily mean packagers. Most end users won't care at all about this so the defaults should be sensible. But the people that maintain native binary packages for their OS will be the ones most needing and caring about this feature. Those people *already* have custom build machinery to generate packages so telling them to patch a `config.bzl` file before the build is only a minor annoyance.

**Comment by cvcal** [comment] 2018-03-06 15:34
> How is setting a path for the build unsustainable? 
What I meant is that requiring the path to be passed on the command line for every build is not good. It shouldn't be copied every time.

The next-to-bazel-binary location of the bazelrc file is one of the proposed rc locations that we just read, so in the install location case this is fine. I meant that having a custom masterrc path that is neither in a standard location or in the install location requires an additional input. 

We cannot have .java or .bzl files that define the location of bazelrcs since bazelrcs are loaded before the server, and the client has no knowledge of skylark. This is a limitation of the way bazelrcs work, I agree. I've suggested in the past that we split startup and command option configuration, since the server could be a lot smarter, but then that doubles the number of config files, which is bad in its own way. I'd also argue that having a file that sets the path for other files only spreads the problem out - people will then complain about the location of the path-defining file.

**Comment by cvcal** [comment] 2018-03-06 16:02
Talked with Julio offline, I didn't realize that he meant the default location should be modified at compile-time. That sounds better than what I was imagining.

**Comment by eiennohito** [comment] 2018-03-06 23:15
I was proposing to set the global config location at the installation time as well, if possible, so the downloaded binary versions of bazel would still work without rebuilding everything from source.

**Comment by cvcal** [comment] 2018-03-07 00:42
I'm not sure how that would work - the value needs to be somewhere, either in the source code, in a file, or in the environment. Envvars aren't great, source needs the value at compilation time, and file leaves the where-does-the-file-live problem exactly where we left it. I'm unfamiliar with how other projects get configured though, is there a fourth option I'm missing?

**Comment by eiennohito** [comment] 2018-03-07 01:46
Binary patching :p

One option would be to pass that value from the wrapper script, I believe.
About files: maybe searching global relative to (but not neccesary in the same dir as) the bazel-real. Placing configs in bin directory does not look good for me.

**Comment by jmmv** [comment] 2018-03-07 22:02
In my opinion the **binaries** that **we** ship are fine as they are. We, as the Bazel team, have to decide how our preferred installation looks like and ship that. There is no need for us to provide fancy mechanisms to tune those binaries (like the binary patching idea). If you get our binary, you get what we have decided and thus what we commit to supporting; period.

For example, if users don't like that **our** Bazel binaries look for configuration under `/etc`, they are free to download the source, reconfigure, and rebuild. And that's fine; that's pretty much how every other project operates.

The location of these files is **system-dependent** and we can't predict what system we are targeting. For macOS and Windows, this is not a problem: these systems are "unique" in that there is only a variant of them and there are conventions on where things go, so our binaries can just follow that. The problem comes when supporting Linux distributions—but that should **not** be our problem. We should just delegate the problem of shipping binaries for those to the distribution maintainers, and then those maintainers can preconfigure Bazel as they need to match the file layout of their systems. Of course, we have to provide a mechanism to tune these settings at build time (which is what I was alluding to in the previous post).

Note that I'm picking on `/etc` but the problem goes beyond that. For example, if we stop shipping Bazel as a self-extracting binary, our installer may need to place extra files in the system and we will face a similar issue with those. I know I've also seen other hardcoded paths within Bazel that wouldn't work on FreeBSD. And we also hardcode the value of environment variables like `PATH` whose default values need to differ depending on the platform we are on.

**Comment by aiuto** [comment] 2022-01-23 01:44
I am closing this.
- What we build and ship works in the general case
- People packaging for systems where /etc/bazelrc is not appropriate could do that with a small patch
- Using a systemwide bazelrc is generally not the right idea anyway

**Closed by aiuto** 2022-01-23 01:44 UTC
Labels: type: feature request, P3, team-XProduct
