### ISSUE TITLE
Stop bazel fetching unused dependencies when using `bazel build //...`

### ISSUE THREAD

**Issue by finn-ball** [bazelbuild/bazel#11027] opened 2020-03-26 16:46 UTC
### Description of the problem / feature request:

When using `bazel build //...`, it seems to fetch dependencies even if they aren't used.

This is a problem when we have external dependencies which are toolchains or libraries for different architectures. We don't wish to fetch those dependencies which aren't going to be used in this build.

### Feature requests: what underlying problem are you trying to solve with this feature?

To not download huge toolchains which aren't used for the build.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

https://github.com/codificasolutions/bazel-cross-compile-example/tree/finn/example

Clone this repo, checkout the `finn/example` branch and do:

```
bazel build //...
```
You'll notice it will fetch a cross compilation toolchain, even though it isn't used.

### What operating system are you running Bazel on?
Linux
### What's the output of `bazel info release`?

2.2.0

**Comment by finn-ball** [comment] 2020-03-31 08:50
Related, a possible workaround:

https://groups.google.com/forum/#!topic/bazel-discuss/bLRIEclhD4E

**Comment by Riatre** [comment] 2020-04-10 23:52
Related: https://github.com/bazelbuild/bazel/issues/10641

**Comment by gregestren** [comment] 2020-05-04 22:30
@katre I saw you commented extensively in the linked groups post. Any thoughts on how to route this issue accordingly?

**Comment by katre** [comment] 2020-05-05 13:07
Thanks for the repro project, it's very helpful. I attempted to reproduce this with Bazel 2.2.0 and 3.1.0, and I don't see the cross-compile toolchain (the one from https://developer.arm.com, right) download. How are you verifying that?

**Comment by finn-ball** [comment] 2020-05-05 13:19
Hi,
I figured out a workaround for it not to download the toolchain so I'm guessing you used the master branch. I left up in another branch, you can try it by:

```
git clone https://github.com/codificasolutions/bazel-cross-compile-example.git
git checkout finn/example
bazel build //...
```

**Comment by katre** [comment] 2020-05-05 13:27
It looks like the difference is that in master the cc_toolchain for the cross-compile toolchain is in the actual repository you create? That is the best way to handle this. The problem is that when you execute "bazel build //...", everything is built, and that includes your `//:gcc-aarch64-gnu` toolchain, so it's dependencies need to be fetched. This triggers your observed download behavior.

In general, you should probably always have the configuration for remote toolchains in the same repository that defines the remote toolchains, in order to avoid this behavior.

**Comment by finn-ball** [comment] 2020-05-05 13:31
Shouldn't this be made really clear in the documentation?

This is in the root `BUILD` file still, why does it not download `gnu_aarch64_gcc//:compiler_components`?:
```
cc_toolchain_config(name = "gcc_aarch64_toolchain_config",
                    tool_paths = "@gnu_aarch64_gcc//:compiler_components",
)

cc_toolchain(
    name = "gcc-aarch64-gnu",
    toolchain_config = ":gcc_aarch64_toolchain_config",
    all_files = ":all",
    ar_files = ":all",
    as_files = ":all",
    compiler_files = ":all",
    dwp_files = ":all",
    linker_files = ":all",
    objcopy_files = ":all",
    strip_files = ":all",
    supports_param_files = 0,
)
```

**Comment by katre** [comment] 2020-05-05 13:40
That's in the finn/example branch that shows the problem? I don't see it in master. In that branch, that's basically the target that causes the `@gnu_aarch64_gcc` repository to be downloaded. In the master branch, those targets aren't present, the only reference to the remote repositories are from the `toolchain` targets. With the `toolchain` rule, the `toolchain` attribute is explicitly marked as not creating a dependency relation, which is what allows Bazel to load toolchain definitions without resolving the toolchain implementation.

It's a good point to clarify in the documentation. I'll see if there's a good place to add it as a note for other users.

**Comment by finn-ball** [comment] 2020-05-05 13:58
Apologies, I sent an example from the wrong branch.

So why doesn't this line trigger a download?
https://github.com/codificasolutions/bazel-cross-compile-example/blob/master/BUILD#L28

**Comment by katre** [comment] 2020-05-05 14:00
From my previous comment:
> With the toolchain rule, the toolchain attribute is explicitly marked as not creating a dependency relation, which is what allows Bazel to load toolchain definitions without resolving the toolchain implementation.

**Comment by philwo** [comment] 2020-12-08 18:39
@katre Can we close this?

**Comment by katre** [comment] 2020-12-08 18:48
Yes, we can.

**Closed by katre** 2020-12-08 18:48 UTC
Labels: P2, area-ExternalDeps, team-XProduct, type: documentation (cleanup)
