### ISSUE TITLE
Multithreaded download_and_extract (http_archive) buggy on retry

### ISSUE THREAD

**Issue by moroten** [bazelbuild/bazel#21773] opened 2024-03-22 17:27 UTC
### Description of the bug:

Occationally, we observe that `download_and_extract` fails with
```
ERROR: /.../WORKSPACE:40:13: fetching http_archive rule //external:redacted: java.io.IOException: /.../external/redacted (Directory not empty)
```
Looking at the attached profile, shows that the download first fails and then all 16 download threads are retrying in parallel, resulting in some of them not being able to clean up properly. All processes 1691-1738 look the same, lots of retries.

![download_and_extract_zoom](https://github.com/bazelbuild/bazel/assets/5401799/787c894e-b29f-4e96-b049-ec7811f1f925)
![download_manager](https://github.com/bazelbuild/bazel/assets/5401799/f705e29b-fa9e-4ed5-9d51-3a71939e5970)

We have in other cases also observed temporary download directories inside a fetched external repository (`temp1234...`), sometimes one and sometimes ten directories. This results in cache miss when using a `glob` which picks up the temporary download directories.

```

.../external/redacted$ ls -la
drwxr-xr-x    Mar 18 10:52 .
drwxr-xr-x    Mar 18 10:55 ..
-rwxr-xr-x    Mar 18 10:52 BUILD.bazel
drwxr-xr-x    Mar 18 10:52 something
drwxr-xr-x    Mar 18 10:50 temp9248233320309694695
-rwxr-xr-x    Mar 18 10:52 WORKSPACE
.../external/redacted$ stat temp9248233320309694695
  File: temp9248233320309694695
  Size: 4096            Blocks: 8          IO Block: 4096   directory
Device: fd00h/64768d    Inode: 16384054    Links: 2
Access: (0755/drwxr-xr-x)  Uid: ( )   Gid: ( )
Access: 2024-03-18 10:52:47.218611936 +0100
Modify: 2024-03-18 10:50:04.623888785 +0100
Change: 2024-03-18 10:50:04.623888785 +0100
Birth: 2024-03-18 10:50:04.623888785 +0100
.../external/redacted$ stat .
  File: .
  Size: 4096            Blocks: 8          IO Block: 4096   directory
Device: fd00h/64768d    Inode: 16384333    Links: 4
Access: (0755/drwxr-xr-x)  Uid: ( )   Gid: ( )
Access: 2024-03-18 10:52:47.214611868 +0100
Modify: 2024-03-18 10:52:47.210611802 +0100
Change: 2024-03-18 10:52:47.210611802 +0100
Birth: 2024-03-18 10:49:38.239446336 +0100
```

### Which category does this issue belong to?

External Dependency

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

It is a race condition, haven't been able to reproduce locally but I see in the logs that it happens daily.

### Which operating system are you running Bazel on?

Linux

### What is the output of `bazel info release`?

release 7.1.0rc2 (patched)

### If `bazel info release` returns `development version` or `(@non-git)`, tell us how you built Bazel.

Some internal patches unrelated to repository handling.

### Have you found anything relevant by searching the web?

No

**Comment by meteorcloudy** [comment] 2024-03-26 15:53
@moroten Can you please create a minimal reproducible case so that we can debug into this more easily?

**Comment by moroten** [comment] 2024-03-26 17:10
I suspect this comes when a download is allowed due to memory pressure. I can make a try, probably next week.

**Comment by moroten** [comment] 2024-04-07 22:04
I tried to abort downloads from repository server side and also send invalid `.tar.gz` files, but that does not trigger the code path.

Looking at the profile, I can see that there is a minor GC finishing 5 ms before each of the cancelled Starlark functions. What in the GC is triggering the cancellation? What is actually cancelled and how?

`--experimental_worker_for_repo_fetching` was enabled by default in Bazel 7.1.0 which explains why we haven't seen it previously.

There are no memory pressure tests with `--experimental_worker_for_repo_fetching` in the code base and I did not create any either in the end.

Looking more at the profiles above, it looks like the download manager is not cancelled when the repository fetch is cancelled. The fetch even starts after the caller has been cancelled: https://github.com/bazelbuild/bazel/blob/9b39ccaa33069c9f5688bef477abcd75e4378f04/src/main/java/com/google/devtools/build/lib/bazel/repository/downloader/DownloadManager.java#L130

The handling of `CancellationException` talks about memory pressure as the reason in which case a recursive reattempt is made. Is this the reason why all the `//external: ... -> _http_archive_impl -> download_and_extract` ends up in new threads?
https://github.com/bazelbuild/bazel/blob/9b39ccaa33069c9f5688bef477abcd75e4378f04/src/main/java/com/google/devtools/build/lib/bazel/repository/starlark/StarlarkRepositoryFunction.java#L192-L200

 I don't see why because the code below together with `result = workerFuture.get();` looks okay.
https://github.com/bazelbuild/bazel/blob/9b39ccaa33069c9f5688bef477abcd75e4378f04/src/main/java/com/google/devtools/build/lib/bazel/repository/starlark/StarlarkRepositoryFunction.java#L147-L161

**Comment by moroten** [comment] 2024-04-16 07:39
@Wyverald Do you know from where the `CancellationException` is raised?

**Comment by fmeum** [comment] 2024-06-14 12:05
@moroten Could you check whether this is fixed by https://github.com/bazelbuild/bazel/pull/22748?

**Comment by moroten** [comment] 2024-06-14 14:32
Unfortunately, it did not work (see #22748).

**Comment by fmeum** [comment] 2024-10-02 13:08
@bazel-io fork 7.4.0

**Comment by fmeum** [comment] 2024-10-02 13:17
@moroten I'm trying to understand https://github.com/bazelbuild/bazel/pull/23837 better. Could you describe the situation in which you are still seeing the issue with Bazel 7.3.1 in more detail? How are the downloads cancelled? Where do the retries come from? Is this related to `--experimental_worker_for_repo_fetching` or does it also reproduce with workers disabled?

I am asking for details because `PendingDownload#cancel` is only called in `StarlarkBaseExternalContext#close` and that method calls `ExecutorService#close` right after, which should wait for all interrupted download threads to terminate before returning. That's why I don't understand why https://github.com/bazelbuild/bazel/pull/23837 would fix any issues you are seeing.

**Comment by moroten** [comment] 2024-10-02 13:57
> @moroten I'm trying to understand #23837 better. Could you describe the situation in which you are still seeing the issue with Bazel 7.3.1 in more detail? How are the downloads cancelled? Where do the retries come from? Is this related to `--experimental_worker_for_repo_fetching` or does it also reproduce with workers disabled?

I can trigger the problem with memory pressure, I don't know if something else might trigger it. The problem exists for both `--experimental_worker_for_repo_fetching=off` and `--experimental_worker_for_repo_fetching=auto`.

> I am asking for details because `PendingDownload#cancel` is only called in `StarlarkBaseExternalContext#close` and that method calls `ExecutorService#close` right after, which should wait for all interrupted download threads to terminate before returning. That's why I don't understand why #23837 would fix any issues you are seeing.

`PendingDownload#cancel` calls `future.cancel(true)` where `future` is the return value from `DownloadManager#startDownload` which has simply run `java.util.concurrent.ExecutorService#submit`. I guess that `future.cancel(true)` calls `Thread#interrupt` which triggers an `InterruptedException`, but as it is a different thread, there are no timing guarantees (which the profiling picture shows). Therefore, `ExecutorService#close` is there to wait for the threads to terminate.

Does `ExecutorService#close` actually do its job? I'll try to add some profiling data and see if I can prove something.

**Comment by fmeum** [comment] 2024-10-02 14:21
> Does `ExecutorService#close` actually do its job? I'll try to add some profiling data and see if I can prove something.

The relevant implementation is https://github.com/openjdk/jdk/blob/890adb6410dab4606a4f26a942aed02fb2f55387/src/java.base/share/classes/java/util/concurrent/ThreadPerTaskExecutor.java#L188-L213. Note that this can't return before `awaitTermination` has returned `true` (not even through an interrupt) and that in turn can only happen when the `threads` set is empty (https://github.com/openjdk/jdk/blob/890adb6410dab4606a4f26a942aed02fb2f55387/src/java.base/share/classes/java/util/concurrent/ThreadPerTaskExecutor.java#L117-L118). It looks to me as if this confirms that yes, the `close` method does live up to the docs here.

**Comment by fmeum** [comment] 2024-10-02 14:22
> I can trigger the problem with memory pressure, I don't know if something else might trigger it. The problem exists for both --experimental_worker_for_repo_fetching=off and --experimental_worker_for_repo_fetching=auto.

This is very interesting as with worker disabled repo fetching shouldn't use Skyframe's state cache and thus shouldn't react to memory pressure (@Wyverald Can you confirm this?).

**Comment by moroten** [comment] 2024-10-02 14:40
Here is the result from `bazel-dev --host_jvm_args=-Xmx128m test ... --incompatible_strict_action_env=true --profile=prof.json --slim_profile=false --repository_cache=../repo_cache_delete --experimental_worker_for_repo_fetching=off` built from https://github.com/meroton/bazel/commit/538be78de78af04b47c0221d31225296d6e4c017:
![worker-is-off-profile](https://github.com/user-attachments/assets/0db8d96b-431b-4041-a2de-881f8090a892)

Now I can't understand why `inner fetching` is continuing after the `doneSignal.wait()` without getting the `InterruptedException` inside `ExecutorService#close`.

**Comment by fmeum** [comment] 2024-10-02 14:45
`ExecutorService#close` by itself doesn't interrupt the threads, that what `#shutdownNow` would be for (but we don't call it). Instead, the intention is that the `future.cancel(true)` calls do this for all registered tasks.

**Comment by fmeum** [comment] 2024-10-02 14:50
In that profile, does `inner fetching` continue indefinitely? It could lag behind the latch because ending a profiling task takes some time and under heavy memory pressure profiler events may delayed even further.

**Comment by moroten** [comment] 2024-10-02 14:52
> In that profile, does `inner fetching` continue indefinitely? It could lag behind the latch because ending a profiling task takes some time and under heavy memory pressure profiler events may delayed even further.

It ends a few milliseconds later. I tried to have that double scope to force the end time of `inner fetching` before `doneSignal.countDown()`. Doesn't that work?

**Comment by fmeum** [comment] 2024-10-02 15:05
AFAIK the profiler internally uses a concurrent queue that buffers events, which can result in "happens-before" relations to not be reflected in the profile. Could you try something like this instead?

```diff
diff --git a/src/main/java/com/google/devtools/build/lib/bazel/repository/downloader/DownloadManager.java b/src/main/java/com/google/devtools/build/lib/bazel/repository/downloader/DownloadManager.java
index 0626f1e9e9..eab56fd231 100644
--- a/src/main/java/com/google/devtools/build/lib/bazel/repository/downloader/DownloadManager.java
+++ b/src/main/java/com/google/devtools/build/lib/bazel/repository/downloader/DownloadManager.java
@@ -48,6 +48,7 @@ import java.util.Optional;
 import java.util.concurrent.ExecutionException;
 import java.util.concurrent.ExecutorService;
 import java.util.concurrent.Future;
+import java.util.concurrent.atomic.AtomicBoolean;
 import javax.annotation.Nullable;

 /**
@@ -123,7 +124,8 @@ public class DownloadManager {
       Path output,
       ExtendedEventHandler eventHandler,
       Map<String, String> clientEnv,
-      String context) {
+      String context,
+      AtomicBoolean isDone) {
     return executorService.submit(
         () -> {
           try (SilentCloseable c = Profiler.instance().profile("fetching: " + context)) {
@@ -138,6 +140,8 @@ public class DownloadManager {
                 eventHandler,
                 clientEnv,
                 context);
+          } finally {
+            isDone.set(true);
           }
         });
   }
diff --git a/src/main/java/com/google/devtools/build/lib/bazel/repository/starlark/StarlarkBaseExternalContext.java b/src/main/java/com/google/devtools/build/lib/bazel/repository/starlark/StarlarkBaseExternalContext.java
index aae70a6dfe..dd19a6ec6f 100644
--- a/src/main/java/com/google/devtools/build/lib/bazel/repository/starlark/StarlarkBaseExternalContext.java
+++ b/src/main/java/com/google/devtools/build/lib/bazel/repository/starlark/StarlarkBaseExternalContext.java
@@ -90,6 +90,7 @@ import java.util.Optional;
 import java.util.concurrent.ExecutorService;
 import java.util.concurrent.Executors;
 import java.util.concurrent.Future;
+import java.util.concurrent.atomic.AtomicBoolean;
 import javax.annotation.Nullable;
 import net.starlark.java.annot.Param;
 import net.starlark.java.annot.ParamType;
@@ -153,6 +154,7 @@ public abstract class StarlarkBaseExternalContext implements AutoCloseable, Star
   private final List<AsyncTask> asyncTasks;
   private final boolean allowWatchingPathsOutsideWorkspace;
   private final ExecutorService executorService;
+  private final List<AtomicBoolean> status = new ArrayList<>();

   private boolean wasSuccessful = false;

@@ -204,6 +206,9 @@ public abstract class StarlarkBaseExternalContext implements AutoCloseable, Star
     // This is necessary because downloads may still be in progress and could end up writing to the
     // working directory during deletion, which would cause an error.
     executorService.close();
+    if (!status.stream().allMatch(AtomicBoolean::get)) {
+      throw new IllegalStateException("Not all downloads done after executor shutdown");
+    }
     if (shouldDeleteWorkingDirectoryOnClose(wasSuccessful)) {
       workingDirectory.deleteTree();
     }
@@ -769,6 +774,8 @@ When <code>sha256</code> or <code>integrity</code> is user specified, setting an
               thread.getCallerLocation());
     }
     if (download == null) {
+      AtomicBoolean isDone = new AtomicBoolean();
+      status.add(isDone);
       Future<Path> downloadFuture =
           downloadManager.startDownload(
               executorService,
@@ -781,7 +788,8 @@ When <code>sha256</code> or <code>integrity</code> is user specified, setting an
               outputPath.getPath(),
               env.getListener(),
               envVariables,
-              identifyingStringForLogging);
+              identifyingStringForLogging,
+              isDone);
       download =
           new PendingDownload(
               executable,
@@ -996,6 +1004,8 @@ the same path on case-insensitive filesystems.
       downloadDirectory =
           workingDirectory.getFileSystem().getPath(tempDirectory.toFile().getAbsolutePath());

+      AtomicBoolean isDone = new AtomicBoolean();
+      status.add(isDone);
       Future<Path> pendingDownload =
           downloadManager.startDownload(
               executorService,
@@ -1008,7 +1018,8 @@ the same path on case-insensitive filesystems.
               downloadDirectory,
               env.getListener(),
               envVariables,
-              identifyingStringForLogging);
+              identifyingStringForLogging,
+              isDone);
       // Ensure that the download is cancelled if the repo rule is restarted as it runs in its own
       // executor.
       PendingDownload pendingTask =
```

**Comment by moroten** [comment] 2024-10-02 15:33
I'll do that tomorrow, it's evening time in Sweden now. Thank you for spending time on this.

**Comment by moroten** [comment] 2024-10-03 07:42
@fmeum The patch above only gives me "Out Of Memory" exceptions. Changing `throw new IllegalStateException` to a profiling point, see https://github.com/meroton/bazel/commit/3422df59f973e3c12d3166d5979805c9cf32cc8b, gives me
```
    {"cat":"general information","name":"Before executorService.close","ph":"X","ts":44020789,"dur":4,"pid":1,"tid":1000182},
    {"cat":"general information","name":"After executorService.close","ph":"X","ts":44020806,"dur":3,"pid":1,"tid":1000182},
```
I get the lines above with both `--experimental_worker_for_repo_fetching=auto` and `--experimental_worker_for_repo_fetching=off`.

**Comment by fmeum** [comment] 2024-10-03 08:32
@moroten Could you try to check whether every `downloadManager.startDownload` call is matched by a registered `AsyncTask`, e.g. by adding the `identifyingStringForLogging` to a `Set` before the call to `downloadManager.startDownload` and then verify that its size matches the number of `AsyncTasks` when closing (also print the strings in that case)?

**Comment by moroten** [comment] 2024-10-03 09:04
@fmeum The number of `AsyncTasks` are matching when I get the error. I ran https://github.com/meroton/bazel/commit/e030caa279a8271151f8dc2acce8ff0130bcd429 and saw `asyncTasks 0 0` up to `asyncTasks 3 3` but without any `asyncTask <id>` line.

**Comment by fmeum** [comment] 2024-10-03 09:46
Are you using a custom Bazel or a custom JDK? I just want to rule out other causes.

If you can provide a reproducer I can run locally, that would be very helpful. The frontend example project doesn't seem to run into this case even when heavily memory constrained.

**Comment by moroten** [comment] 2024-10-03 17:42
I've been building the exact commits I've posted using `bazel-7.3.1 build -c opt src:bazel --incompatible_strict_action_env=true` on Ubuntu 22.04 amd64, with `--default_system_javabase=/usr/lib/jvm/java-11-openjdk-amd64`. Toolchain resolution shows
```
@@bazel_tools//tools/jdk:toolchain_type -> @@rules_java+//toolchains:toolchain_jdk_21
@@bazel_tools//tools/jdk:runtime_toolchain_type -> @@rules_java++toolchains+remotejdk21_linux//:jdk
@@rules_java+//toolchains:bootstrap_runtime_toolchain_type -> @@rules_java++toolchains+remotejdk21_linux//:jdk
```

I've been building https://github.com/buildbarn/bb-storage/commit/a889bc06a4070e34f5b7d85073dabaa37bfc3027 with with both `--experimental_worker_for_repo_fetching=auto/off` using
```
while ! grep 'After executorService' prof.json; do
    path/to/bazel --host_jvm_args=-Xmx128m clean --expunge --repository_cache=../repo_cache_delete
    rm -rf ../repo_cache_delete/
    path/to/bazel --host_jvm_args=-Xmx128m test ... --incompatible_strict_action_env=true --profile=prof.json --slim_profile=false --repository_cache=../repo_cache_delete --experimental_worker_for_repo_fetching=auto
done
```

**Comment by fmeum** [comment] 2024-10-03 18:31
@moroten Could you try printing `Thread.getAllStackTraces()` in the "impossible" state where not all futures are done but `executorService.close()` has returned? That could give us an idea what's happening.

**Comment by moroten** [comment] 2024-10-03 18:58
This is an example from `Thread.getAllStackTraces()`: [stack-trace.txt](https://github.com/user-attachments/files/17248746/stack-trace.txt)
Bazel built with https://github.com/meroton/bazel/commit/a3d018a0666efb673786264cf517cba26221d63b

**Comment by fmeum** [comment] 2024-10-03 19:13
Could you run the values through Arrays.toString so that we see the individual stack frames?

**Comment by moroten** [comment] 2024-10-03 19:19
I realised that, here is a better one: [stack-trace-pretty.txt](https://github.com/user-attachments/files/17248979/stack-trace-pretty.txt)
Bazel built with https://github.com/meroton/bazel/commit/76e4f245f899771d407032548ac1b509c890a866

**Comment by fmeum** [comment] 2024-10-03 19:35
I didn't find any interesting stack trace in the log. Could you try replacing `keySet().stream().map(Thread::getStackTrace)` with `values().stream()`? That's more efficient and could give us a better chance at winning the race to see something interesting. 

Could you also check whether the condition still holds after the stack traces have been printed? That would allow us to know that collecting the traces wasn't too slow.

**Comment by moroten** [comment] 2024-10-03 19:52
Here is a stack trace from before the call to `executorService.close()`, when there are downloads left afterwards: [stack-trace-before-close.txt](https://github.com/user-attachments/files/17249351/stack-trace-before-close.txt)
I cannot find any reference to `StarlarkBaseExternalContext.java` or the word `download`.
Bazel built with https://github.com/meroton/bazel/commit/8cd0ec63bdcabda1a6d0455bf2be580c813e7408

**Comment by moroten** [comment] 2024-10-10 07:12
> > Does `ExecutorService#close` actually do its job? I'll try to add some profiling data and see if I can prove something.
> 
> The relevant implementation is https://github.com/openjdk/jdk/blob/890adb6410dab4606a4f26a942aed02fb2f55387/src/java.base/share/classes/java/util/concurrent/ThreadPerTaskExecutor.java#L188-L213. Note that this can't return before `awaitTermination` has returned `true` (not even through an interrupt) and that in turn can only happen when the `threads` set is empty (https://github.com/openjdk/jdk/blob/890adb6410dab4606a4f26a942aed02fb2f55387/src/java.base/share/classes/java/util/concurrent/ThreadPerTaskExecutor.java#L117-L118). It looks to me as if this confirms that yes, the `close` method does live up to the docs here.

The thread is removed from `ThreadPerTaskExecutor.threads` in [`ThreadPerTaskExecutor.taskComplete`](https://github.com/openjdk/jdk/blob/890adb6410dab4606a4f26a942aed02fb2f55387/src/java.base/share/classes/java/util/concurrent/ThreadPerTaskExecutor.java#L231), called by [`ThreadBoundFuture.done`](https://github.com/openjdk/jdk/blob/890adb6410dab4606a4f26a942aed02fb2f55387/src/java.base/share/classes/java/util/concurrent/ThreadPerTaskExecutor.java#L345) <- [`FutureTask.finishCompletion`](https://github.com/openjdk/jdk/blob/890adb6410dab4606a4f26a942aed02fb2f55387/src/java.base/share/classes/java/util/concurrent/FutureTask.java#L434) <- [`FutureTask.cancel=ThreadBoundFuture.cancel`](https://github.com/openjdk/jdk/blob/890adb6410dab4606a4f26a942aed02fb2f55387/src/java.base/share/classes/java/util/concurrent/FutureTask.java#L179) (deduced by reading the code). Note that there is nothing waiting for the thread to actually finish [between calling `Thread.interrupt` and `FutureTask.finishCompletion`](https://github.com/openjdk/jdk/blob/890adb6410dab4606a4f26a942aed02fb2f55387/src/java.base/share/classes/java/util/concurrent/FutureTask.java#L169-L179).

I think Bazel needs to manually wait for the completion. @fmeum What is your conclusion?

**Comment by fmeum** [comment] 2024-10-10 07:52
Thanks for the deep dive, I agree that [this](https://github.com/openjdk/jdk/blob/890adb6410dab4606a4f26a942aed02fb2f55387/src/java.base/share/classes/java/util/concurrent/FutureTask.java#L169-L179) explains the race and that it isn't specific to any particular `ExecutorService`. Tasks are simply considered completed essentially immediately after canceling them.

I will work on a fix now.

**Comment by fmeum** [comment] 2024-10-10 09:08
Sent [a PR](https://github.com/meroton/bazel/pull/1) to your PR branch.

**Closed** 2024-10-15 18:25 UTC
Labels: type: bug, P2, team-ExternalDeps

**Comment by iancha1992** [comment] 2024-10-16 15:52
@bazel-io fork 8.0.0

**Comment by iancha1992** [comment] 2024-10-17 18:04
A fix for this issue has been included in [Bazel 7.4.0 RC3](https://github.com/bazelbuild/bazel/releases/tag/7.4.0rc3). Please test out the release candidate and report any issues as soon as possible.
If you're using Bazelisk, you can point to the latest RC by setting `USE_BAZEL_VERSION=7.4.0rc3`. Thanks!

**Comment by fmeum** [comment] 2025-01-15 12:44
@moroten FYI, this has now been fixed in the JDK: https://github.com/openjdk/jdk/pull/23036

**Comment by moroten** [comment] 2025-01-16 07:14
> @moroten FYI, this has now been fixed in the JDK: https://github.com/openjdk/jdk/pull/23036

Cool, I didn't even think of it being a bug in the JDK. Shall the patch be reverted to simplify Bazel once the JDK is updated?
