### ISSUE TITLE
labels are incorrectly resolved in external repositories

### ISSUE THREAD

**Issue by hanwen** [bazelbuild/bazel#700] opened 2015-12-11 16:07 UTC
note how the compilation below has github.com/hanwen/test2/pkg/ all over the place, while the external repository declares itself to be go_prefix("github.com/hanwen/bazel_gotest").

This means that //:go_prefix references in the external test/ repository resolve to the main repository, rather than the external one.

$ pwd
/home/hanwen/vc/test2

$ cat WORKSPACE
local_repository(
    name = "test",
    path = "/home/hanwen/vc/test",
)

$ cat BUILD
load("/tools/build_rules/go/def", "go_prefix")

go_prefix("github.com/hanwen/test2")

$ cat ../test/BUILD
load("/tools/build_rules/go/def", "go_prefix")

go_prefix("github.com/hanwen/bazel_gotest")

$ cat sub/BUILD
sh_test(
  name = "x_test",
  srcs = [ "x_test.sh"] ,
  data = [ "@test//pkg:b"])

$ bazel test -s --nocheck_visibility sub/x_test
ERROR: Error sending results to http://localhost:8082: Connection to http://localhost:8082 refused.
WARNING: /home/hanwen/vc/test2/sub/BUILD:1:1: in sh_test rule //sub:x_test: Target '//sub:x_test' violates visibility of target '@test//pkg:b'. Continuing because --nocheck_visibility is active.
INFO: Found 1 test target...
>>>>> # @test//pkg:b [action 'GoCompile external/test/pkg/b.a']
(cd /home/hanwen/.cache/bazel/_bazel_hanwen/6433d2bba0e406fe672e2326d722746b/test2 && \
  exec env - \
    GOARCH=amd64 \
    GOOS=linux \
  /bin/bash -c 'rm -rf bazel-out/local_linux-fastbuild/bin/external/test/pkg/b.a.dir && mkdir -p bazel-out/local_linux-fastbuild/bin/external/test/pkg/b.a.dir && mkdir -p bazel-out/local_linux-fastbuild/bin/external/test/pkg/b.a.dir/github.com/hanwen/test2/external/test/pkg && ln -s ../../../../../../../../../../../../../bazel-out/local_linux-fastbuild/bin/external/test/pkg/go_default_library.a bazel-out/local_linux-fastbuild/bin/external/test/pkg/b.a.dir/github.com/hanwen/test2/external/test/pkg/go_default_library.a && mkdir -p bazel-out/local_linux-fastbuild/bin/external/test/pkg/b.a.dir/github.com/hanwen/test2/external/test/pkg && ln -s ../../../../../../../../../../../../../external/test/pkg/b.go bazel-out/local_linux-fastbuild/bin/external/test/pkg/b.a.dir/github.com/hanwen/test2/external/test/pkg/b.go && export GOROOT=$(pwd)/external/golang-linux-amd64/go/bin/.. && cd  bazel-out/local_linux-fastbuild/bin/external/test/pkg/b.a.dir && ../../../../../../../external/golang-linux-amd64/go/bin/go tool compile -o ../../../../../../../bazel-out/local_linux-fastbuild/bin/external/test/pkg/b.a -pack -I . -importmap=github.com/hanwen/test2/pkg=github.com/hanwen/test2/pkg/go_default_library github.com/hanwen/test2/external/test/pkg/b.go')
INFO: From GoCompile external/test/pkg/b.a:
github.com/hanwen/test2/external/test/pkg/b.go:3: can't find import: "github.com/hanwen/bazel_gotest/pkg"

**Comment by lberki** [comment] 2015-12-11 16:11
Ha-ha! Here is the problem:

https://github.com/bazelbuild/bazel/blob/master/src/main/java/com/google/devtools/build/lib/packages/AbstractAttributeMapper.java#L170

Apparently, we redirect labels within implicit and late-bound attributes to the main repository. This can be fixed now that we have the `@//a/b:c` label syntax that always points to the main repository. Let me jus take a look on Monday (hopefully I won't forget it)

**Comment by lberki** [comment] 2015-12-11 16:24
To quote our excellent manager, _I have a CL for that!_ It was actually just a small amount of work and there is even a chance that the tests pass :)

**Comment by davidsantiago** [comment] 2015-12-14 08:34
If you don't get your CL in for this today and it's not too much trouble, can you post the patch you had so far, so that I could use to start working on the rules for how this will work when the CL is complete? Thanks.

**Closed** 2015-12-14 12:59 UTC
Labels: external repositories

**Comment by hanwen** [comment] 2015-12-14 13:04
fwiw, the go_rules should be changed to not use //external:go_prefix, but
just //:go_prefix

On Mon, Dec 14, 2015 at 9:35 AM, David Santiago <notifications@github.com>
wrote:

> If you don't get your CL in for this today and it's not too much trouble,
> can you post the patch you had so far, so that I could use to start working
> on the rules for how this will work when the CL is complete? Thanks.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bazelbuild/bazel/issues/700#issuecomment-164377734>.
>



-- 
Han-Wen Nienhuys
Google Munich
hanwen@google.com

**Comment by chin33z** [comment] 2016-01-20 06:32
Hi,

My Bazel project can select the cross toolchain base on my customize --config option in bazel build command.
My select() is based on config_setting() is broken due to this fix [https://github.com/bazelbuild/bazel/commit/0c8049f5fc866d785dd83769fa6c38ecf771ba96].

The error message is:
```
ERROR: /root/.cache/bazel/_bazel_root/71572a3fe51dedb8bc0ce983c11fa0da/external/rlog-1.4/BUILD:28:1: every rule of type cc_binary implicitly depends upon the target '@rlog-1.4//target:arm',  but this target could not be found. If this is an integration test, maybe you forgot to add a mock for your new tool?
```
The rlog-1.4 is an external repository.

Here is my project layout:
```
ws/
    WORKSPACE
    BUILD
    tools/
        CROSSTOOL
        BUILD
    target/
        BUILD
```

$ws> cat target/BUILD
```
package(default_visibility = ["//visibility:public"])

config_setting(
    name = "arm",
    values = {
        "cpu": "armeabi-v7a",
        "crosstool_top": "//tools:toolchain",
    },
)
config_setting(
    name = "i686",
    values = {
        "cpu": "i686",
        "crosstool_top": "//tools:toolchain",
    },
)
config_setting(
    name = "x86_64",
    values = {
        "cpu": "x86_64",
        "crosstool_top": "//tools:toolchain",
    },
)
```

snippet of ws/BUILD
```
...select({
           "//target:x86_64": ["cfg_inc_hdr/x86_64"],
           "//target:arm":    ["cfg_inc_hdr/arm"],
          }),
```
I guess I should change the **"//target:x86_64"** & **"//target:arm"** but I don't know how to fix it properly. Can anyone help me? Thanks.

**Comment by hanwen** [comment] 2016-01-20 11:17
@lberki - lukacs, can you comment?

**Comment by lberki** [comment] 2016-01-20 12:16
How come cc_binary rules depend on //target:arm? Do you use
--crosstool_top=//target:arm? In that case, try
--crosstool_top=@//target:arm so that cc_binaries will always look in the
main repository for the cc_toolchain rule.

If I misunderstood, please a give more data. Ideally, a repository I can
clone and a Bazel command line I can run.

On Wed, Jan 20, 2016 at 12:17 PM, Han-Wen Nienhuys <notifications@github.com
> wrote:

> @lberki <https://github.com/lberki> - lukacs, can you comment?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bazelbuild/bazel/issues/700#issuecomment-173175268>.
>



-- 
Lukács T. Berki | Software Engineer | lberki@google.com |

Google Germany GmbH | Maximillianstr. 11-15 | 80539 München | Germany
| Geschäftsführer: Matthew
Scott Sucherman, Paul Terence Manicle | Registergericht und -nummer:
Hamburg, HRB 86891

**Comment by chin33z** [comment] 2016-01-20 12:34
I just craft a simplify workspace that could repro my problem.

Please check my latest comment in the thread. Thanks.

Bazel-discuss [https://groups.google.com/forum/m/?utm_medium=email&utm_source=footer#!msg/bazel-discuss/W5hTP4EiO9E/9lINybf1FwAJ]

**Comment by chin33z** [comment] 2016-01-21 03:51
Here you can clone an example of my issue.

select()/config_setting() works fine if the repository is under workspace.
However, it fails with the external repository case.

Not sure if this is a bug or not. Thanks.

https://github.com/chin33z/example

**Comment by lberki** [comment] 2016-01-21 09:59
Works for me. What I tried:

```
git clone https://github.com/chin33z/example
cd example/workspace
# Adjust the path in the new_local_repository in the WORKSPACE file to point to the directory the WORKSPACE file itself is in (I just replaced it with the empty string)
cp main2.c main1.c  # (it seems that you accidentally didn't commit that file)
bazel build @//:hello2 --define main=x   # works
bazel build @ext_src//:hello1  --define main=x # also works
```

Did I misunderstand something?

Which version of Bazel are you using? 85834ad seems like it should have something to do with this bug, but I checked with a Bazel just before that commit and it fails differently than you described.
Are you using Bazel at HEAD? I could

**Comment by chin33z** [comment] 2016-01-21 10:41
Sorry, I'm not sure if I misunderstand the purpose of [new_local_repository](http://bazel.io/docs/be/workspace.html#new_local_repository). I think I could import any local directory by this rule, right?

What I want to do in my example is, import the src/ to workspace/ by new_local_repository. Thus, the BUILD file can access the main2.c correctly. The main2.c is placed in src/ not workspace/ intentionally. You don't have to copy main1.c.

The only thing need to adjust is the path in WORKSPACE. We should let it point to the absolute path of src/ after git clone. Should not leave it with empty string.

After all, under the ~/example/workspace
**bazel build --define main=x //:hello2**  (succeeded)
**bazel build --define main=x @ext_src//:hello1**  (failed)

**Comment by lberki** [comment] 2016-01-21 12:13
My bad. I can reproduce this now. The fix is, unfortunately, not trivial
and requires some careful thought. Let me see if I can get around doing it
later today...

On Thu, Jan 21, 2016 at 11:42 AM, David Hu <notifications@github.com> wrote:

> Sorry, I'm not sure if I misunderstand the purpose of new_local_repository
> <http://bazel.io/docs/be/workspace.html#new_local_repository>. I think I
> could import any local directory by this rule, right?
>
> What I want to do in my example is, import the src/ to workspace/ by
> new_local_repository. Thus, the BUILD file can access the main2.c
> correctly. The main2.c is placed in src/ not workspace/ intentionally. You
> don't have to copy main1.c.
>
> The only thing need to adjust is the path in WORKSPACE. We should let it
> point to the absolute path of src/ after git clone. Should not leave it
> with empty string.
>
> After all, under the ~/example/workspace
> *bazel build --define main=x //:hello2* (succeeded)
> *bazel build --define main=x @ext_src//:hello1* (failed)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bazelbuild/bazel/issues/700#issuecomment-173533447>.
>



-- 
Lukács T. Berki | Software Engineer | lberki@google.com |

Google Germany GmbH | Maximillianstr. 11-15 | 80539 München | Germany
| Geschäftsführer: Matthew
Scott Sucherman, Paul Terence Manicle | Registergericht und -nummer:
Hamburg, HRB 86891

**Comment by lberki** [comment] 2016-01-21 15:07
....aand, I didn't. I'll try again tomorrow.

**Comment by chin33z** [comment] 2016-01-22 03:34
Thanks for the help. Should we reopen this or open another tickets?

**Comment by lberki** [comment] 2016-01-22 11:52
https://github.com/bazelbuild/bazel/issues/811 filed. I have a change out, let's see if I can get it submitted today.
