### ISSUE TITLE
generate_workspace is generating invalid shas

### ISSUE THREAD

**Issue by kchodorow** [bazelbuild/bazel#1131] opened 2016-04-07 14:26 UTC
It's including the rest of the .sha1 file it downloaded, not cutting it off after the sha.  See https://groups.google.com/d/msg/bazel-discuss/gu8RbSdD0xY/YvI3f9azAQAJ.

**Comment by tfarina** [comment] 2016-04-07 16:36
So the problem is at https://github.com/bazelbuild/bazel/blob/master/src/tools/generate_workspace/src/main/java/com/google/devtools/build/workspace/maven/Resolver.java#L275?

**Comment by jin** [comment] 2019-08-18 00:58
Closing this as generate_workspace is no longer maintained. Please open Maven-related issues on [rules_jvm_external](https://github.com/bazelbuild/rules_jvm_external) instead.

rules_jvm_external supports pinning artifacts with their SHA256 values encoded in a version-controllable `maven_install.json` file.

**Closed by jin** 2019-08-18 00:58 UTC
Labels: P2, team-ExternalDeps, type: bug
