### ISSUE TITLE
compile tensorflow , version `GLIBCXX_3.4.18' not found

### ISSUE THREAD

**Issue by zhang-jian** [bazelbuild/bazel#898] opened 2016-02-15 09:32 UTC
Hi all,

I followed https://github.com/bazelbuild/bazel/issues/629 post, but still can not compile tensorflow. 

I can compile bazel, and I also modified CROSSTOOL in bazel to pickup a locally installed gcc (gcc version 4.8.2 (GCC))

When compile tensorflow (bazel build --verbose_failures -c opt //tensorflow/cc:tutorials_example_trainer), I got 

`bazel-out/host/bin/google/protobuf/protoc: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.18' not found (required by bazel-out/host/bin/google/protobuf/protoc)`

Looking at bazel-out/host/bin/google/protobuf/protoc (ldd bazel-out/host/bin/google/protobuf/protoc):

`bazel-out/host/bin/google/protobuf/protoc: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.18' not found (required by bazel-out/host/bin/google/protobuf/protoc)
	linux-vdso.so.1 (0x00007ffff57d4000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007fc9dd898000)
	libstdc++.so.6 => /usr/lib64/libstdc++.so.6 (0x00007fc9dd591000)
	libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007fc9dd37b000)
	libc.so.6 => /lib64/libc.so.6 (0x00007fc9dcfd6000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fc9ddab4000)
	libm.so.6 => /lib64/libm.so.6 (0x00007fc9dccdf000)
`

Any help would be greatly appreciated!!

Jian

**Comment by damienmg** [comment] 2016-02-15 10:49
Do you have the link opt in your CROSSTOOL file?

**Comment by zhang-jian** [comment] 2016-02-15 11:56
Hi @damienmg :

The last error is solved after I did:
`$ export GCC=`which gcc`
$ sed -i -e "s=/usr/bin/gcc=$GCC=g" tools/cpp/CROSSTOOL`

	linux-vdso.so.1 (0x00007fffd65ff000)
	librt.so.1 => /lib64/librt.so.1 (0x00007f13c9144000)
	libz.so.1 => /lib64/libz.so.1 (0x00007f13c8f2e000)
	libstdc++.so.6 => /home/jian/tools/gcc/gcc/lib64/libstdc++.so.6 (0x00007f13c8c26000)
	libgcc_s.so.1 => /home/jian/tools/gcc/gcc/lib64/libgcc_s.so.1 (0x00007f13c8a0f000)
	libc.so.6 => /lib64/libc.so.6 (0x00007f13c866a000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f13c844e000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f13c934c000)
	libm.so.6 => /lib64/libm.so.6 (0x00007f13c8157000)


But I got a new error, 

ERROR: /home/jian/tensorflow-test/install/tensorflow/tensorflow/core/BUILD:358:1: C++ compilation of rule '//tensorflow/core:kernel_lib' failed: gcc failed: error executing command 
  (cd /home/jian/.cache/bazel/_bazel_jian/e739cb5bf6ee62949e7bfd69f783a958/tensorflow && \
  exec env - \
    PATH=/home/jian/bin:/home/jian/tools/jdk1.8.0_74//bin:/home/jian/tools/questTagger/cmd:/home/jian/tools/questTagger/bin:/home/jian/tools/gcc/gcc/bin:/home/jian/maven/bin:/home/jian/python_virtualenv/bin:/home/jian/bin:/home/jian/tools/jdk1.8.0_74//bin:/home/jian/perl5/bin:/home/jian/maven/bin:/usr/lib64/mpi/gcc/openmpi/bin:/home/jian/bin:/usr/local/bin:/usr/bin:/bin:/usr/bin/X11:/usr/X11R6/bin:/usr/games:/usr/lib/mit/bin:.:/usr/local/share/torque/bin:/usr/local/share/maui/bin:/home/jian/tools/questTagger/cmd:/home/jian/tools/questTagger/bin \
  /home/jian/tools/gcc/gcc/bin/gcc -U_FORTIFY_SOURCE '-D_FORTIFY_SOURCE=1' -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 -DNDEBUG -ffunction-sections -fdata-sections '-std=c++0x' -iquote . -iquote bazel-out/local_linux-opt/genfiles -iquote external/bazel_tools -iquote bazel-out/local_linux-opt/genfiles/external/bazel_tools -iquote external/jpeg_archive -iquote bazel-out/local_linux-opt/genfiles/external/jpeg_archive -iquote external/png_archive -iquote bazel-out/local_linux-opt/genfiles/external/png_archive -iquote external/re2 -iquote bazel-out/local_linux-opt/genfiles/external/re2 -iquote external/eigen_archive -iquote bazel-out/local_linux-opt/genfiles/external/eigen_archive -isystem google/protobuf/src -isystem bazel-out/local_linux-opt/genfiles/google/protobuf/src -isystem external/bazel_tools/tools/cpp/gcc3 -isystem external/jpeg_archive/jpeg-9a -isystem bazel-out/local_linux-opt/genfiles/external/jpeg_archive/jpeg-9a -isystem external/png_archive/libpng-1.2.53 -isystem bazel-out/local_linux-opt/genfiles/external/png_archive/libpng-1.2.53 -isystem external/re2 -isystem bazel-out/local_linux-opt/genfiles/external/re2 -isystem third_party/eigen3 -isystem bazel-out/local_linux-opt/genfiles/third_party/eigen3 -isystem external/eigen_archive/eigen-eigen-70505a059011 -isystem bazel-out/local_linux-opt/genfiles/external/eigen_archive/eigen-eigen-70505a059011 -isystem third_party/gpus/cuda -isystem bazel-out/local_linux-opt/genfiles/third_party/gpus/cuda -isystem third_party/gpus/cuda/include -isystem bazel-out/local_linux-opt/genfiles/third_party/gpus/cuda/include -fno-exceptions -DEIGEN_AVOID_STL_ARRAY -pthread -no-canonical-prefixes -fno-canonical-system-headers -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' '-frandom-seed=bazel-out/local_linux-opt/bin/tensorflow/core/_objs/kernel_lib/tensorflow/core/kernels/matrix_solve_ls_op.o' -MD -MF bazel-out/local_linux-opt/bin/tensorflow/core/_objs/kernel_lib/tensorflow/core/kernels/matrix_solve_ls_op.d -c tensorflow/core/kernels/matrix_solve_ls_op.cc -o bazel-out/local_linux-opt/bin/tensorflow/core/_objs/kernel_lib/tensorflow/core/kernels/matrix_solve_ls_op.o): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1: gcc failed: error executing command 
  (cd /home/jian/.cache/bazel/_bazel_jian/e739cb5bf6ee62949e7bfd69f783a958/tensorflow && \
  exec env - \
    PATH=/home/jian/bin:/home/jian/tools/jdk1.8.0_74//bin:/home/jian/tools/questTagger/cmd:/home/jian/tools/questTagger/bin:/home/jian/tools/gcc/gcc/bin:/home/jian/maven/bin:/home/jian/python_virtualenv/bin:/home/jian/bin:/home/jian/tools/jdk1.8.0_74//bin:/home/jian/perl5/bin:/home/jian/maven/bin:/usr/lib64/mpi/gcc/openmpi/bin:/home/jian/bin:/usr/local/bin:/usr/bin:/bin:/usr/bin/X11:/usr/X11R6/bin:/usr/games:/usr/lib/mit/bin:.:/usr/local/share/torque/bin:/usr/local/share/maui/bin:/home/jian/tools/questTagger/cmd:/home/jian/tools/questTagger/bin \
  /home/jian/tools/gcc/gcc/bin/gcc -U_FORTIFY_SOURCE '-D_FORTIFY_SOURCE=1' -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 -DNDEBUG -ffunction-sections -fdata-sections '-std=c++0x' -iquote . -iquote bazel-out/local_linux-opt/genfiles -iquote external/bazel_tools -iquote bazel-out/local_linux-opt/genfiles/external/bazel_tools -iquote external/jpeg_archive -iquote bazel-out/local_linux-opt/genfiles/external/jpeg_archive -iquote external/png_archive -iquote bazel-out/local_linux-opt/genfiles/external/png_archive -iquote external/re2 -iquote bazel-out/local_linux-opt/genfiles/external/re2 -iquote external/eigen_archive -iquote bazel-out/local_linux-opt/genfiles/external/eigen_archive -isystem google/protobuf/src -isystem bazel-out/local_linux-opt/genfiles/google/protobuf/src -isystem external/bazel_tools/tools/cpp/gcc3 -isystem external/jpeg_archive/jpeg-9a -isystem bazel-out/local_linux-opt/genfiles/external/jpeg_archive/jpeg-9a -isystem external/png_archive/libpng-1.2.53 -isystem bazel-out/local_linux-opt/genfiles/external/png_archive/libpng-1.2.53 -isystem external/re2 -isystem bazel-out/local_linux-opt/genfiles/external/re2 -isystem third_party/eigen3 -isystem bazel-out/local_linux-opt/genfiles/third_party/eigen3 -isystem external/eigen_archive/eigen-eigen-70505a059011 -isystem bazel-out/local_linux-opt/genfiles/external/eigen_archive/eigen-eigen-70505a059011 -isystem third_party/gpus/cuda -isystem bazel-out/local_linux-opt/genfiles/third_party/gpus/cuda -isystem third_party/gpus/cuda/include -isystem bazel-out/local_linux-opt/genfiles/third_party/gpus/cuda/include -fno-exceptions -DEIGEN_AVOID_STL_ARRAY -pthread -no-canonical-prefixes -fno-canonical-system-headers -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' '-frandom-seed=bazel-out/local_linux-opt/bin/tensorflow/core/_objs/kernel_lib/tensorflow/core/kernels/matrix_solve_ls_op.o' -MD -MF bazel-out/local_linux-opt/bin/tensorflow/core/_objs/kernel_lib/tensorflow/core/kernels/matrix_solve_ls_op.d -c tensorflow/core/kernels/matrix_solve_ls_op.cc -o bazel-out/local_linux-opt/bin/tensorflow/core/_objs/kernel_lib/tensorflow/core/kernels/matrix_solve_ls_op.o): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.
tensorflow/core/kernels/matrix_solve_ls_op.cc: In member function 'void tensorflow::MatrixSolveLsOp<Scalar, SupportsBatchOperationT>::ComputeMatrix(tensorflow::OpKernelContext*, const typename tensorflow::BinaryLinearAlgebraOp<Scalar, SupportsBatchOperationT>::ConstMatrixMap&, const typename tensorflow::BinaryLinearAlgebraOp<Scalar, SupportsBatchOperationT>::ConstMatrixMap&, typename tensorflow::BinaryLinearAlgebraOp<Scalar, SupportsBatchOperationT>::MatrixMap*)':
tensorflow/core/kernels/matrix_solve_ls_op.cc:111:41: error: 'Matrix' is not a class, namespace, or enumeration
               (Scalar(l2_regularizer) * Matrix::Ones(cols, 1)).asDiagonal();
                                         ^
tensorflow/core/kernels/matrix_solve_ls_op.cc:131:41: error: 'Matrix' is not a class, namespace, or enumeration
               (Scalar(l2_regularizer) * Matrix::Ones(rows, 1)).asDiagonal();
                                         ^
In file included from ./tensorflow/core/framework/op_kernel.h:22:0,
                 from tensorflow/core/kernels/matrix_solve_ls_op.cc:23:
./tensorflow/core/framework/allocator.h: In member function 'virtual std::size_t tensorflow::Allocator::RequestedSize(void*)':
./tensorflow/core/framework/allocator.h:128:3: warning: control reaches end of non-void function [-Wreturn-type]
   }
   ^
In file included from ./tensorflow/core/framework/op_kernel.h:25:0,
                 from tensorflow/core/kernels/matrix_solve_ls_op.cc:23:
./tensorflow/core/framework/device_base.h: In member function 'virtual tensorflow::Allocator* tensorflow::DeviceBase::GetAllocator(tensorflow::AllocatorAttributes)':
./tensorflow/core/framework/device_base.h:149:3: warning: control reaches end of non-void function [-Wreturn-type]
   }
   ^
./tensorflow/core/framework/device_base.h: In member function 'virtual const tensorflow::DeviceAttributes& tensorflow::DeviceBase::attributes() const':
./tensorflow/core/framework/device_base.h:179:3: warning: control reaches end of non-void function [-Wreturn-type]
   }
   ^
Target //tensorflow/cc:tutorials_example_trainer failed to build
INFO: Elapsed time: 201.940s, Critical Path: 199.63s


Thanks again,

Jian

**Comment by damienmg** [comment] 2016-02-15 12:31
What is your command?

If you are building with `--config cuda`, you need to edit the Tensorflow wrapper at https://github.com/tensorflow/tensorflow/blob/master/third_party/gpus/crosstool/clang/bin/crosstool_wrapper_driver_is_not_gcc#L49

**Comment by zhang-jian** [comment] 2016-02-15 12:47
@damienmg , I am not using GPU, 
`bazel build -c opt //tensorflow/cc:tutorials_example_trainer`

**Comment by damienmg** [comment] 2016-02-15 12:55
@martinwicke: this probably an issue with the gcc configuration but I cannot seems to make sense of the error, it cannot find Matrix but I don't know where it is defined (I guess in Eigen but I don't see any reason it would fails).

**Comment by zhang-jian** [comment] 2016-02-15 14:23
@damienmg 

Not sure if I did the right thing, I replaced line 66 ~ 70  at tensorflow/core/kernels/matrix_solve_ls_op.cc with
'''
using Matrix = typename BinaryLinearAlgebraOp<Scalar, SupportsBatchOperationT>::Matrix;
using MatrixMap = typename BinaryLinearAlgebraOp<Scalar,
                                       SupportsBatchOperationT>::MatrixMap;
using ConstMatrixMap = typename BinaryLinearAlgebraOp<Scalar,
                                       SupportsBatchOperationT>::ConstMatrixMap;
'''
 and I got 
'''
Target //tensorflow/cc:tutorials_example_trainer up-to-date:
  bazel-bin/tensorflow/cc/tutorials_example_trainer
INFO: Elapsed time: 60.643s, Critical Path: 56.80s

'''

Then I ran 
'''
bazel build --verbose_failures -c opt //tensorflow/tools/pip_package:build_pip_package
'''

and I got

'''
Target //tensorflow/tools/pip_package:build_pip_package up-to-date:
  bazel-bin/tensorflow/tools/pip_package/build_pip_package
INFO: Elapsed time: 71.412s, Critical Path: 66.05s
'''

**Comment by damienmg** [comment] 2016-03-31 12:12
The problem is no longer on Bazel side, the TensorFlow build can be adapted to work with 0.2.1. Closing this issue.

**Closed by damienmg** 2016-03-31 12:12 UTC
Labels: Bug, Configurability, P2

**Comment by kheuton** [comment] 2016-06-09 03:04
@zhang-jian or   @damienmg  how did you fix the error from your first post? I can't quite figure out what was meant by the link opt. I know I need to edit CROSSTOOL, but I'm not sure how

**Comment by damienmg** [comment] 2016-06-09 09:36
@kheuton which version of Bazel are you using? Can you file a separate bug with the reproduction step (bazel version, gcc version, system and output of the build)
