### ISSUE TITLE
Allow using workspace name in labels

### ISSUE THREAD

**Issue by kchodorow** [bazelbuild/bazel#1248] opened 2016-05-10 13:29 UTC
Right now, to refer to a label "in this repository," you refer to it as //foo:bar.  If the WORKSPACE defines `workspace(name = 'repo')`, perhaps we should also allow referring to it as `@repo//foo:bar`.

This came up in https://github.com/bazelbuild/rules_rust/pull/7.

**Comment by PiotrSikora** [comment] 2016-07-13 02:49
I would very much like to see this implemented...

I'm working on a modular project, with each 3rd-party module in its own workspace (i.e. `@project`, `@moduleA`, `@moduleB`, etc.). All modules need to depend on `@project//:core`, but when they are imported as external repositories, I cannot build `@project//:main` (which depends on `@moduleA` and `@moduleB`), because `@project`'s workspace cannot resolve `@project` to itself. 

Is self-referencing local repository an acceptable workaround for now? i.e.

    workspace(name = "project")

    local_repository(
        name = "project",
        path = __workspace_dir__,
    )

I've built `@project//:main` using this solution as well as by replacing `@project//:core` with `@//:core` in modules, and while both binaries have the same filesize and work, their checksums are different, which worries me a bit.

Also, when using the self-referencing solution, `project-2.params` file lists `libcore.a` twice (once from main directory and once from `external/project`)... `libcore.a` is exactly the same in both cases, so hopefully linker is smart enough about it, but again, this worries me a bit.

**Comment by kchodorow** [comment] 2016-07-13 11:07
Yeah, self-referencing local repo is the recommended workaround for now.

Just some notes about implementing this: there are two changes needed for this.

1. At the moment, execution root put the local workspace under `$(basename workspace-dir)`, not the workspace name. I have a change in progress to fix this.
2. Then update labels in the "main" repository to be workspace-aware.

**Comment by PiotrSikora** [comment] 2016-07-13 18:10
Hey Kristina, thanks for the notes... Hopefully workspace-aware labels in the "main" repository are only needed in the meantime, before this is properly fixed?

**Comment by kchodorow** [comment] 2016-07-14 08:57
Right now labels either include a workspace name (e.g., when you say `deps = ["@foo//bar"]`), they use the _default workspace_, i.e., whatever workspace they happen to be in (e.g., `//bar` resolves to `@foo//bar` in `@foo`, but `@baz//bar` if it were in `@baz`), or the _main workspace_, which means they don't know their workspace name but are referring to the workspace where the build is happening.  Right now the main workspace is required all over the place.  I think there still might be some call for it after this change goes in, but hopefully it'll be needed in fewer places.

**Comment by damienmg** [comment] 2016-09-26 19:43
This is done for a long time, no? @kchodorow?

**Comment by kchodorow** [comment] 2016-10-03 13:56
@damienmg this has not been done, see my comment on #1866.

**Comment by steven-johnson** [comment] 2016-10-11 19:04
The local_repository() workaround doesn't work (AFAICT) if you have targets that produce generated files, because there seems to be confusion over which genfiles paths are permitted (e.g., "bazel-out/local-fastbuild/genfiles/Halide.h" vs "bazel-genfiles/external/halide/Halide.h").

**Comment by kchodorow** [comment] 2016-10-11 19:48
Reopening, since I just noticed that this was rolled back.  

@steven-johnson, can you elaborate/give a more complete example?  Using it on genrule output works for me.

**Comment by steven-johnson** [comment] 2016-10-11 19:54
@kchodorow, I'm trying to track it down right now -- it may be a case of user error (mixing prefixed and non-prefixed paths), but I'm not sure yet. Stay tuned.

**Comment by steven-johnson** [comment] 2016-10-11 20:01
What seems to be happening is: 
-- there's a generated file ("Halide.h")
-- This can end up generated in two places:
    -- blaze build :halide_h -> bazel-out/local-fastbuild/genfiles/Halide.h
    -- blaze build @halide//:halide_h -> bazel-genfiles/external/halide/Halide.h

my internal target is depending on this via the second syntax (fake-external-repo hack); however, the include paths passed to the C++ compiler search bazel-out/local-fastbuild/genfiles first, so it finds the "other" Halide.h... which it shouldn't see.

why the extra include paths are present is not clear to me. again, I'm assuming I'm doing something wrong, but it could also be just that this is a weird hack that I've found the broken edges of...

**Comment by PiotrSikora** [comment] 2016-10-31 09:05
Any update after the rollback?

**Comment by steven-johnson** [comment] 2016-11-03 17:30
I presume this is still unfixed in 0.4.0?

**Comment by kchodorow** [comment] 2016-11-07 15:29
Still unfixed.  The go rules have updated the change that caused the rollback, though, so I should be able to roll forward when I get a chance.

**Comment by steven-johnson** [comment] 2016-11-29 22:07
Looks like this is still going to be unfixed in 0.4.1?

**Comment by kchodorow** [comment] 2016-11-29 22:31
Ugh, yes, sorry.

**Comment by jart** [comment] 2016-12-23 19:21
Progress on this?

**Comment by jart** [comment] 2016-12-23 19:23
Once this is fixed, I would recommend deprecating `@//...` labels since they break when another repository depends on that repository.

**Comment by steven-johnson** [comment] 2017-01-05 00:45
What are the chances of this being fixed in 0.5? (I have dozens of TODOs in my BUILD files that I'd love to be able to scrub...)

**Comment by steven-johnson** [comment] 2017-01-25 01:39
So is this closed-fixed or closed-unfixed? (I tried building Bazel from tip and trying this out in a local repo and either it's still broken or I'm doing something wrong...)

**Comment by steven-johnson** [comment] 2017-01-25 01:49
Update: as of ce7c4de, whether this works or not depends on how I invoke `bazel test`.

Say I have a test with a dep like this:

    # This rule is in the @halide//test/generator package
    cc_test(
        name = "gpu_object_lifetime_aottest",
        deps = ["@halide//test/common:gpu_object_lifetime_tracker"],
        # irrelevant details omitted
    )

If I invoke via `bazel test @halide//test/generator:gpu_object_lifetime_aottest` then all is well.

If, however, I am in the toplevel directory, and am lazy, and omit the `@halide`, i.e. `bazel test //test/generator:gpu_object_lifetime_aottest`, I fail with

    Target '@halide//test/common:gpu_object_lifetime_tracker' is not visible from target '//test/generator:gpu_object_lifetime_aottest'

**Comment by damienmg** [comment] 2017-01-25 17:38
Argh obviously because the labels are not equivalent. I would call for fixing it by actually making both label equivalent instead of a creating a local repo pointing to the main one.

Keeping the release blocker tag so we will include it in the release, not really blocking though.

**Comment by steven-johnson** [comment] 2017-02-16 01:41
Can someone update the status of this? AFAICT it's still broken; whether it's intended to be fixed for 0.5 or not is not clear.

**Comment by damienmg** [comment] 2017-02-16 07:12
@kchodorow: do you have the bandwidth to do it?

**Comment by kchodorow** [comment] 2017-02-17 15:35
Sorry, missed the update from @steven-johnson.  I'm taking a guess that `@halide//test/common:gpu_object_lifetime_tracker` isn't globally visible (correct me if I'm wrong). For the near future, the case you ran into is WAI: Bazel does not "dedup" //test and @halide//test, so it thinks that they're different repositories.  //test/generator:etc isn't publicly visible, so it cannot be used from a different repository.

**Comment by steven-johnson** [comment] 2017-02-17 18:59
>  I'm taking a guess that @halide//test/common:gpu_object_lifetime_tracker isn't globally visible

Correct: it's restricted to @halide//test:__subpackages__

> For the near future, the case you ran into is WAI

:-(  That's unfortunate. I hope it will be improved at some point.

**Comment by mhlopko** [comment] 2017-04-10 10:57
Hello Kristina, is this still expected to be fixed in 0.5? Is this a release blocker?

**Comment by kchodorow** [comment] 2017-04-10 14:55
It is not a release blocker.  The remaining issues will not be fixed in time for 0.5.

**Comment by mhlopko** [comment] 2017-04-11 08:30
Hi Kristina, thanks for the info and the move to 0.6!

**Comment by steven-johnson** [comment] 2017-11-29 23:11
Cycling back to this after many months: I'm assuming this isn't gonna be fixed anytime soon?

**Comment by mhlopko** [comment] 2017-11-30 10:01
@dslomov @damienmg

**Comment by dslomov** [comment] 2019-03-21 17:25
Duplicate of #7130

**Closed by dslomov** 2019-03-21 17:25 UTC
Labels: P2, category: extensibility > external repositories, external-repos-triaged, type: feature request
