### ISSUE TITLE
Too many unrelated "xcode version must be specified" errors

### ISSUE THREAD

**Issue by ittaiz** [bazelbuild/bazel#6056] opened 2018-09-01 19:30 UTC
### Description of the problem / feature request:
I've been working the past few days on rules_scala and its toolchain and I got several times the following message:
```
ERROR: /private/var/tmp/.../.../external/local_config_cc/BUILD:50:5: in apple_cc_toolchain rule @local_config_cc//:cc-compiler-darwin_x86_64: Xcode version must be specified to use an Apple CROSSTOOL. If your Xcode version has changed recently, try: "bazel clean --expunge" to re-run Xcode configuration
```
rules_scala has no c/cpp code of itself but maybe the toolchain triggers something.
Additionally I did not change anything about my Xcode version and in fact I'm pretty certain it's not fully installed since when I open the app it says something about needing to install additional components.

If I run clean expunge it fixes the problem but I don't think this is a valid solution.

### What operating system are you running Bazel on?

OS X Sierra

### What's the output of `bazel info release`?

release 0.15.0-homebrew

**Comment by tetromino** [comment] 2018-09-04 15:07
We have also encountered this problem internally on some users' macs, and there seem to be several mechanisms that can trigger it. We don't have a good solution yet.

If you see the error again, could you please upload your java.log?

Also, which version(s) of XCode command line tools do you have installed, and where? (see `xcode-select -p`, `which clang`, and `clang --version` from the command line)

**Comment by ittaiz** [comment] 2018-09-04 20:09
`/Applications/Xcode.app/Contents/Developer`
`/usr/bin/clang`
```
Apple LLVM version 8.0.0 (clang-800.0.38)
Target: x86_64-apple-darwin16.7.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```
where is the java.log?

**Comment by ittaiz** [comment] 2018-09-04 20:11
also, may I ask why you think this is P3? Having to do bazel clean expunge periodically sounds like it should be P1

**Comment by sergiocampama** [comment] 2018-09-05 14:19
can you provide the output of this command?

`cat $(bazel info execution_root)/external/local_config_xcode/BUILD`

**Comment by ittaiz** [comment] 2018-09-13 05:46
Happened again after "fiddling" with toolchains (specifically java_toolchain/host_java_toolchain/javabase/host_javabase)
```
package(default_visibility = ['//visibility:public'])

xcode_config(name = 'host_xcodes')
# Error: Running xcodebuild -version failed, return code 256, stderr: Process terminated by signal 15, stdout:
```
package(default_visibility = ["//visibility:public"])

load(":osx_archs.bzl", "OSX_TOOLS_ARCHS")

CC_TOOLCHAINS = [(
    cpu + "|compiler",
    ":cc-compiler-" + cpu,
) for cpu in OSX_TOOLS_ARCHS]

cc_library(
    name = "malloc",
)

cc_library(
    name = "stl",
)

filegroup(
    name = "empty",
    srcs = [],
)

filegroup(
    name = "cc_wrapper",
    srcs = ["cc_wrapper.sh"],
)

cc_toolchain_suite(
    name = "toolchain",
    toolchains = dict(CC_TOOLCHAINS),
)

[
    filegroup(
        name = "osx_tools_" + arch,
        srcs = [
          ":cc_wrapper",
          ":libtool",
          ":make_hashed_objlist.py",
          ":wrapped_clang",
          ":wrapped_clang_pp",
          ":wrapped_ar",
          ":xcrunwrapper.sh",
        ],
    )
    for arch in OSX_TOOLS_ARCHS
]

[
    apple_cc_toolchain(
        name = "cc-compiler-" + arch,
        all_files = ":osx_tools_" + arch,
        compiler_files = ":osx_tools_" + arch,
        cpu = arch,
        dwp_files = ":empty",
        dynamic_runtime_libs = [":empty"],
        linker_files = ":osx_tools_" + arch,
        objcopy_files = ":empty",
        static_runtime_libs = [":empty"],
        strip_files = ":osx_tools_" + arch,
        supports_param_files = 0,
    )
    for arch in OSX_TOOLS_ARCHS
]

[
    toolchain(
        name = "cc-toolchain-" + arch,
        exec_compatible_with = [
            # This toolchain will only work with the local autoconfigured
            # platforms.
            "@bazel_tools//platforms:autoconfigured",
            # TODO(katre): add autodiscovered constraints for host CPU and OS.
        ],
        target_compatible_with = [
            # TODO(katre): add autodiscovered constraints for host CPU and OS.
        ],
        toolchain = ":cc-compiler-" + arch,
        toolchain_type = "@bazel_tools//tools/cpp:toolchain_type",
    )
    for arch in OSX_TOOLS_ARCHS
]
```

**Comment by ittaiz** [comment] 2018-09-13 05:46
Also I'd really appreciate understanding why you think this is P3.

**Comment by helenalt** [comment] 2018-10-16 13:30
@sergiocampama could you elevate the priority of this? It's not urgent but would be good to get done within a quarter.

**Comment by phb** [comment] 2018-11-20 01:47
This happens to me pretty much weekly and is really annoying. We don't have any C/C++ code in our project so it's quite unclear why this is happening at all.

**Comment by ittaiz** [comment] 2018-11-20 06:16
Just happened to me yesterday. Obviously no CPP code.
Bazel itself recommending clean expunge is awful IMHO

**Comment by dslomov** [comment] 2018-11-27 14:40
@sergiocampama ping?

**Comment by sergiocampama** [comment] 2018-11-27 15:00
I'm sorry, but I don't have the bandwidth to look into this issue. AFAIA, this is part of the bazel infrastructure setup, so the bazel team should have way more insight into the details on how this works.

**Comment by dslomov** [comment] 2018-11-28 13:01
@aragos @jmmv who is the right person to look at this?

**Comment by jmmv** [comment] 2018-11-28 17:39
I can take a look at why Xcode selection fails (not at why rules_scala needs C++), but I'm afraid this doesn't have enough data for me to reproduce the issue.

The fact that `xcodebuild -version` was terminated by a signal is very suspicious though.

Is there a deterministic reproduction process for this bug?

Are you running Santa and/or VSCode by any chance?

The next time this happens, could you check if a simple `bazel shutdown` is sufficient to correct the issue? There were some changes back in April (3a292efa55075e020d60daeeb7566b7e2ea721c2) to remove an on-disk cache of Xcode locations. The suggestion to run `clean --expunge` may be stale but I'm not sure.

Lastly it looks like you use Bazel 0.15. Is there any chance you could upgrade to at least 0.18? There have been various fixes to the `xcode_locator` tool since then to make it more reliable and they may actually fix this problem. (Or in any case, some of those fixes was to add extra logging in case of problems, which could be very helpful here.)

**Comment by ittaiz** [comment] 2018-11-28 18:39
This happened with 0.19.2 (first reported when I used 15 but upgraded a few
versions since).
I’ll try shutdown.
Btw,
I think that rules_scala isn’t relevant here and that any starlark rule
with toolchains can cause this but I’m not really sure

**Comment by phb** [comment] 2018-11-28 22:42
Just had this happen again with 0.18.1.
$ bazel build //... --nobuild
DEBUG: /private/var/tmp/_bazel_me/60a181658afb41895a4dba3b821290b1/external/bazel_tools/tools/osx/xcode_configure.bzl:87:9: Invoking xcodebuild failed, developer dir: /Applications/Xcode.app/Contents/Developer ,return code 256, stderr: Process terminated by signal 15, stdout:
<normal build output after this>

I still don't have a clear idea when it's happening, possibly something fairly unique with my workflow is that I'm using a lot of different bazel workspaces often at the same time.

**Comment by ittaiz** [comment] 2018-11-29 04:39
Did shutdown help? Also are you doing changes related to toolchains?

**Comment by phb** [comment] 2018-11-29 04:52
Yes shutdown helped.

We do register a custom toolchain (internal compiler). 

It looks vaguely like this
```
toolchain_type(name = "compiler")

toolchain(
    name = "darwin_compiler",
    exec_compatible_with = [
        "@bazel_tools//platforms:osx",
        "@bazel_tools//platforms:x86_64",
    ],
    toolchain = ":darwin_compiler_impl",
    toolchain_type = ":compiler",
)

toolchain(
    name = "linux_compiler",
    exec_compatible_with = [
        "@bazel_tools//platforms:linux",
        "@bazel_tools//platforms:x86_64",
    ],
    toolchain = ":linux_compiler_impl",
    toolchain_type = ":compiler",
)

compiler_toolchain(
    name = "darwin_compiler_impl",
    compiler = select({
        ":local_build": "//:local_compiler_jar_macos",
        ":s3_build": ":compiler_jar_macos",
        "//conditions:default": ":compiler_jar_macos",
    }),
    service = select({
        ":local_build": "//:local_compiler_service_jar_macos",
        ":s3_build": ":compiler_service_jar_macos",
        "//conditions:default": ":compiler_service_jar_macos",
    }),
)
# provider details for the various jars skipped
```

**Comment by pcj** [comment] 2019-01-21 19:06
If this happens to me it's often temporally-related to running gazelle: `bazel run //:gazelle` (I don't know why, just leaving a breadcrumb in case someone is investigating this).  

`bazel shutdown` always solves the problem.

**Comment by phb** [comment] 2019-02-06 00:35
Still happens for us with bazel 0.22. Please let me know if there is any other information that would be helpful as it reproduces pretty regularly for me.

**Comment by jmmv** [comment] 2019-02-11 11:33
The reason I asked about VSCode is because of: https://github.com/bazelbuild/bazel/issues/4603. We troubleshot similar problems there but eventually traced them to a bug in Santa. I wonder if something similar is going on here.

Again, the fact that `xcodebuild` seems to have crashed is strange and is likely the trigger here. You could try using the startup `--unlimit_coredumps` option in all your builds so, the next time this hits, you might get a useful coredump under `/cores/`.

**Comment by phb** [comment] 2019-02-12 02:08
Ah, no VSCode or Santa here. I'll enable coredumps and will let you know if something appears

**Comment by keith** [comment] 2019-02-22 21:57
One way to easily reproduce the original issue here is by ctrl-c'ing while bazel is `Fetching @local_config_xcode; fetching`:

```
% ./bazelw build --config=debug Modules/PassengerApp:Lyft
INFO: Invocation ID: 4d6704d8-a396-48a0-98db-16537ed62162
Analyzing: target //Modules/PassengerApp:Lyft (19 packages loaded, 23 targets configured)
    Fetching @local_config_xcode; fetching
^C
ERROR: build interrupted
INFO: Elapsed time: 2.878s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (19 packages loaded, 23 targets configured)
% ./bazelw build --config=debug Modules/PassengerApp:Lyft
INFO: Invocation ID: 6e7d8c6f-c3c1-46b3-a19b-a89450214c33
ERROR: /private/var/tmp/_bazel_ksmiley/c8513c989333be3c89713e16206869b2/external/local_config_cc/BUILD:58:5: in apple_cc_toolchain rule @local_config_cc//:cc-compiler-watchos_x86_64: Xcode version must be specified to use an Apple CROSSTOOL. If your Xcode version has changed recently, try: "bazel clean --expunge" to re-run Xcode configuration
ERROR: Analysis of target '//Modules/PassengerApp:Lyft' failed; build aborted: Analysis of target '@local_config_cc//:cc-compiler-watchos_x86_64' failed; build aborted
INFO: Elapsed time: 1.510s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (9 packages loaded, 106 targets configured)
    Fetching @go_sdk; fetching
```

The contents of `local_config_xcode/BUILD` in this state end up having error messages about how `xcodebuild` or `xcode_locator` failed to run (depending on when you cancelled)

**Comment by keith** [comment] 2019-02-22 21:57
We've worked around this currently by checking in our own Xcode config and passing `--xcode_version_config=//:host_xcodes` so that bazel never fetches this. Although it can still happen if you ctrl-c out of `local_config_cc` as well.

**Comment by keith** [comment] 2019-02-22 23:26
This PR https://github.com/bazelbuild/bazel/pull/7519 fixes the ctrl-c issue (and likely other issues where this comes up naturally)

**Comment by keith** [comment] 2019-02-25 18:20
Another repro case that @ob pointed out:

> I think if bazel fails in the loading phase (before analysis) you get this error

**Comment by keith** [comment] 2019-02-25 19:15
The analysis repro case isn't fixed by my PR. The easiest way for me to repro is by adding an invalid label to the `extensions` of an `ios_application` rule, and then:

```
bazel clean --expunge
bazel build //:ios-app
# Fix the invalid extension label
bazel build //:ios-app
```

And you'll end up with this error. For some reason I can't easily reproduce this by breaking a `dep`.

**Closed** 2019-02-27 22:53 UTC
Labels: P2, platform: macOS, team-Apple

**Comment by keith** [comment] 2019-02-27 22:54
Because of this known issue https://github.com/bazelbuild/bazel/issues/6056#issuecomment-467142752 we might want to leave this open, up to you all

**Comment by keith** [comment] 2019-02-28 19:17
FYI https://github.com/bazelbuild/bazel/issues/7592

**Comment by Unknown9527** [comment] 2020-02-22 05:45
When you meet this problem, enter " xcode-select". Then follow the "reset" step, this problem will never happen. 
```
sudo xcode-select --reset
```
