### ISSUE TITLE
[8.0.0rc4] Programatic error in cc_shared_library

### ISSUE THREAD

**Issue by jsharpe** [bazelbuild/bazel#24518] opened 2024-11-27 23:41 UTC
### Description of the bug:

I'm hitting this error with 8.0.0rc4, the same code is ok in 7.4.1.
```
ERROR: /home/james.sharpe/.cache/bazel/_bazel_james.sharpe/120360a4609c561725b4ef03d7bc710f/external/esp/BUILD.bazel:135:18: in cc_shared_library rule @@esp//:egads-shared:
Traceback (most recent call last):
        File "/virtual_builtins_bzl/common/cc/cc_shared_library.bzl", line 675, column 114, in _cc_shared_library_impl
        File "/virtual_builtins_bzl/common/cc/cc_shared_library.bzl", line 532, column 44, in _filter_inputs
        File "/virtual_builtins_bzl/common/cc/cc_shared_library.bzl", line 81, column 28, in _sort_linker_inputs
        File "/virtual_builtins_bzl/common/cc/cc_shared_library.bzl", line 57, column 9, in _programmatic_error
Error in fail: Your build has triggered a programmatic error in the cc_shared_library rule. Please file an issue in https://github.com/bazelbuild/bazel : @@esp//:egads,@@esp//:egads_lib,@@esp//:emp,@@esp//:egads_util,@@esp//:opencascade,@@esp//:uvmap,@@//src/logging:redirect_printf,@@//src/logging:logging,@@esp//:opencascade-shared vs 17
```

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

It can be reproduced using the following:

```
cc_shared_library(
    name = "a-shared",
    shared_lib_name = "liba.so",
    deps = [":a"],
)

cc_shared_library(
    name = "b-shared",
    dynamic_deps = [":a-shared"],
    deps = [":b"],
)

cc_library(
    name = "b",
    visibility = ["//visibility:public"],
    deps = [
        ":a",
    ],
)

cc_library(
    name = "test",
)

cc_library(
    name = "a",
    deps = [":test"]
)
```

### Which operating system are you running Bazel on?

Linux

### What is the output of `bazel info release`?

8.0.0rc4

**Comment by jsharpe** [comment] 2024-11-28 00:00
Bug was present in 7.4.0, 7.4.1 was fixed. Believe its a patch from @fmeum that is the root cause of this issue.

**Comment by fmeum** [comment] 2024-11-28 08:02
@meteorcloudy While the cherry-pick attempt at https://github.com/bazelbuild/bazel/pull/24002 was canceled due to the regression, there was another at https://github.com/bazelbuild/bazel/pull/24005 that went through.

**Comment by fmeum** [comment] 2024-11-28 08:02
@bazel-io fork 8.0.0

**Comment by fmeum** [comment] 2024-11-28 08:03
https://github.com/bazelbuild/bazel/pull/24522

**Comment by meteorcloudy** [comment] 2024-11-28 14:16
rc6 was just released with a fix for this: https://github.com/bazelbuild/bazel/releases/tag/8.0.0rc6

**Closed by meteorcloudy** 2024-11-28 14:16 UTC
Labels: type: bug, team-Rules-CPP, untriaged

**Comment by jsharpe** [comment] 2024-11-28 14:21
rc6 fixes this for me.
