### ISSUE TITLE
bazel build with  -c dbg,  but " value has been optimized out"

### ISSUE THREAD

**Issue by yuimo** [bazelbuild/bazel#8239] opened 2019-05-05 09:50 UTC
hi, i have builded my program with "bazel build -c dbg mytarget"
however, when i debug it using gdb to print some variables
it always display "value has been optimized out"
any ideas?
thanks a lot.

**Comment by hlopko** [comment] 2019-05-09 16:32
Hi @yuimo, can you share more information? 

1) What OS are you running Bazel on?
2) What version of Bazel do you use?
3) What kind and version of C++ compiler do you use?
3) What is the version of gdb? How do you invoke dbg?
3) What version what is the minimal reproduction case to see the issue?

**Comment by scentini** [comment] 2019-07-23 09:06
Closing due to lack of information, please reopen when more information is available.

**Closed by scentini** 2019-07-23 09:06 UTC
Labels: more data needed, team-Rules-CPP, untriaged
