### ISSUE TITLE
Remote execution: java_*.exec_properties not included in execute request

### ISSUE THREAD

**Issue by laszlocsomor** [bazelbuild/bazel#13845] opened 2021-08-13 14:47 UTC
### Description of the problem / feature request:

Bazel doesn't include Java rules' `exec_properties` in remote execution requests.

This affects 4.1.0 and also 5.0.0-pre.20210802.5

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

I have an empty `WORKSPACE`, a trivial `Y.java` (`public class Y {}`), and this `BUILD` file:

```
EXEC_PROP = {"container-image": "docker://docker.io/library/openjdk:11-slim"}

genrule(
    name = "x",
    outs = ["x.out"],
    cmd = "date > $@",
    exec_properties = EXEC_PROP,
)

java_library(
    name = "y",
    srcs = ["Y.java"],
    exec_properties = EXEC_PROP,
)
```

I also have a remote execution service running on `localhost:5300`.

You can use any remote executor to repro this, I happen to run a simple dummy implementation that just prints the request. Its execute method looks like this:

```java
  private final class Exec extends build.bazel.remote.execution.v2.ExecutionGrpc.ExecutionImplBase {
    @Override
    public void execute(ExecuteRequest request, StreamObserver<Operation> responseObserver) {
      // Print the action proto's digest.
      System.out.printf(
          "Execute %s/%d%n",
          request.getActionDigest().getHash(), request.getActionDigest().getSizeBytes());

      try {
        // Download the action proto from the CAS, print the exec_properties.
        Action action = Action.parseFrom(cas.get(request.getActionDigest()));
        System.out.println("  exec_platform (from action) {");
        for (Platform.Property p : action.getPlatform().getPropertiesList()) {
          System.out.printf("    \"%s\" = \"%s\"%n", p.getName(), p.getValue());
        }
        System.out.println("  }");

        // Download the command proto from the CAS, print the exec_properties.
        Command cmd = Command.parseFrom(cas.get(action.getCommandDigest()));
        System.out.println("  exec_platform (from command) {");
        for (Platform.Property p : cmd.getPlatform().getPropertiesList()) {
          System.out.printf("    \"%s\" = \"%s\"%n", p.getName(), p.getValue());
        }
        System.out.println("  }");
      } catch (InvalidProtocolBufferException e) {
        ...
```

Then:

```
  $ bazel --ignore_all_rc_files build --remote_executor=grpc://localhost:5300 //:x
```

This succeeds, and I see:

```
Execute 5be683f891c9063a0351e8f9c5f9f04607191f5a2230f86dad22085f5209cb84/206
  exec_platform (from action) {
    "container-image" = "docker://docker.io/library/openjdk:11-slim"
  }
  exec_platform (from command) {
    "container-image" = "docker://docker.io/library/openjdk:11-slim"
  }
```

Then I try building `//:y`, which fails, and apparently the request doesn't have the container image:

```
Execute b6bb09898b864e8a8eb7910d9a596ab408ec4b483273fc51c3c691ec14039cf4/143
  exec_platform (from action) {
  }
  exec_platform (from command) {
  }
```

I can partially get it to work with `--host_platform` and `--host_java_toolchain` (but only on Bazel 5.0.0-prerelease, see https://github.com/bazelbuild/bazel/issues/13844). Then the request contains the platform rule's `exec_properties`, but still not those from the java rule.

Here's the new BUILD file:

```
...

platform(
    name = "my_platform",
    constraint_values = [
        "@bazel_tools//platforms:x86_64",
        "@bazel_tools//platforms:linux",
    ],
    exec_properties = EXEC_PROP,
)

java_library(
    name = "y",
    srcs = ["Y.java"],
    exec_properties = {"dummy": "dummy"},
)

java_runtime(
    name = "jdk11",
    java_home = "/usr/local/openjdk-11",
)
```

```
  $ ~/Downloads/bazel-5.0.0-pre.20210802.5-linux-x86_64 --ignore_all_rc_files build --remote_executor=grpc://localhost:5300 --host_platform=//:my_platform --host_java_toolchain=//:jdk11 -- //:y
```

and my remote executor prints:

```
Execute ab14a1be398045ded4f0cbb802ad2b343e290d78f36fb214a86a09cece514900/206
  exec_platform (from action) {
    "container-image" = "docker://docker.io/library/openjdk:11-slim"
  }
  exec_platform (from command) {
    "container-image" = "docker://docker.io/library/openjdk:11-slim"
  }
```

The `container-image` is now there (from the `platform` rule), but `dummy: dummy` isn't.

### What operating system are you running Bazel on?

Ubuntu 20.04

### What's the output of `bazel info release`?

```
release 4.1.0
```

**Comment by benjaminp** [comment] 2021-08-13 17:20
I can't reproduce this exactly. But, I wonder if you're seeing the "internal" `java` invocations done by Bazel's builtin Java toolchain rather than actually building the top-level target library.
```
$ bazel version
Build label: 4.1.0
Build target: bazel-out/k8-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Fri May 21 11:11:34 2021 (1621595494)
Build timestamp: 1621595494
Build timestamp as int: 1621595494
$ bazel build --execution_log_json_file=log.json //:y
INFO: Analyzed target //:y (23 packages loaded, 435 targets configured).
INFO: Found 1 target...
Target //:y up-to-date:
  bazel-bin/liby.jar
INFO: Elapsed time: 4.363s, Critical Path: 3.83s
INFO: 4 processes: 1 internal, 2 linux-sandbox, 1 worker.
INFO: Build completed successfully, 4 total actions
$ jq  -r '.progressMessage, "Primary output: " + .listedOutputs[0], "Properties: ", .platform.properties, ""' log.json
Action external/bazel_tools/tools/jdk/platformclasspath_classes/DumpPlatformClassPath.class
Primary output: bazel-out/k8-fastbuild/bin/external/bazel_tools/tools/jdk/platformclasspath_classes/DumpPlatformClassPath.class
Properties: 
[]

Action external/bazel_tools/tools/jdk/platformclasspath.jar
Primary output: bazel-out/k8-fastbuild/bin/external/bazel_tools/tools/jdk/platformclasspath.jar
Properties: 
[]

Building liby.jar (1 source file)
Primary output: bazel-out/k8-fastbuild/bin/liby-native-header.jar
Properties: 
[
  {
    "name": "container-image",
    "value": "docker://docker.io/library/openjdk:11-slim"
  }
]
```

**Comment by coeuvre** [comment] 2022-04-08 10:19
Closing. Feel free to reopen it with more information.

**Closed by coeuvre** 2022-04-08 10:19 UTC
Labels: type: bug, more data needed, team-Remote-Exec
