### ISSUE TITLE
--spawn_strategy=remote doesn't seem to be recognized

### ISSUE THREAD

**Issue by xynny** [bazelbuild/bazel#1026] opened 2016-03-08 22:12 UTC
Hi,  I attempted to follow the readme here to set up Hazelcast:  https://github.com/bazelbuild/bazel/tree/master/src/main/java/com/google/devtools/build/lib/remote

I was able to get the Hazelcast server up and then I attempted to connect to it with a version of bazel built from HEAD:

ubuntu@ip-10-1-0-54:~/bazel$ bazel help
                                                 [bazel release head (@c5a5d90)]
Usage: bazel <command> <options> ...

This was built with ./compile.sh

I followed the README and attempted to connect:

ubuntu@ip-10-1-0-54:~/bazel$ sudo /home/ubuntu/bazel/output/bazel build --hazelcast_node=localhost:5701 --spawn_strategy=remote src/tools/generate_workspace:all

INFO: Waiting for response from Bazel server (pid 94173)...
ERROR: 'remote' is an invalid value for spawn strategy. Valid values are: local, sandboxed, standalone, worker.

For some reason it says that the "remote" strategy is invalid.  Is there a step I am missing here?

**Comment by davidzchen** [comment] 2016-03-10 00:17
@philwo, @hhclam - Can you take a look?

**Comment by philwo** [comment] 2016-03-10 04:42
@xynny I wonder if there's a little bug in the code that only activates the remote strategy when its configuration (--hazelcast_node) has been provided.

Could you please try to do a normal build like this first (no --spawn_strategy and no target on the command-line, just like this):
bazel build --hazelcast_node=localhost:5701

And then run your full command-line again:
bazel build --hazelcast_node=localhost:5701 --spawn_strategy=remote src/tools/generate_workspace:all

Does it work then? If yes, I know where the bug is and can send a fix tomorrow or on Friday.
If not, I'll have to check this out in detail when I'm back in the office next week. :)

**Comment by xynny** [comment] 2016-03-10 19:57
oh okay I rebuilt bazel master and then did the two steps and it no longer throws the  'remote' is an invalid value for spawn strategy error.  The previous comment was using the 0.2.0 release.  This is what happened with master:
ubuntu@ip-10-1-0-176:~/bazel$ sudo /home/ubuntu/bazel/output/bazel  build --hazelcast_node=localhost:5701
Extracting Bazel installation...
Sending SIGTERM to previous Bazel server (pid=28471)... done.
.......
INFO: Found 0 targets...
INFO: Elapsed time: 4.620s, Critical Path: 0.01s
ubuntu@ip-10-1-0-176:~/bazel$ sudo /home/ubuntu/bazel/output/bazel build --hazelcast_node=localhost:5701 --spawn_strategy=remote src/tools/generate_workspace:all 
INFO: Found 2 targets...
ERROR: /home/ubuntu/bazel/src/main/native/BUILD:13:1: Executing genrule //src/main/native:copy_link_jni_header failed: namespace-sandbox failed: error executing command /home/ubuntu/.cache/bazel/_bazel_root/ffdf15b7269c0b208fa140f8b561f825/bazel/_bin/namespace-sandbox ... (remaining 5 argument(s) skipped).
src/main/tools/namespace-sandbox.c:507: mount(opt->sandbox_root, opt->sandbox_root, NULL, MS_BIND | MS_NOSUID, NULL): Permission denied
INFO: Elapsed time: 3.360s, Critical Path: 3.16s

**Comment by xynny** [comment] 2016-03-11 00:48
another datapoint.  I got this to work on a mac by just following the readme, but on my ubuntu machines the behavior is broken as described above.  It is probably because sandboxing is on by default on the linux machine.

**Comment by hhclam** [comment] 2016-03-18 19:28
xynny: I think the reason that it complains about namespace-sandbox has nothing to do with remote spawn strategy. For a non-remotable task it just uses other spawn strategies such as linux sandbox or local. The issue seems to be that namespace sandbox doesn't work on your linux box.

There's an actual bug that 'remote' spawn strategy is not available if --hazelcast_node is not specified. We're working on a fix for the latter issue.

**Comment by glinscott** [comment] 2016-05-03 20:37
Ping on this issue -- any workaround we can apply in the source in the meantime?

**Comment by hhclam** [comment] 2016-05-03 20:41
glinscott: what's the issue you are referring to? "remote" strategy is invalid or the sandbox complaining?

**Comment by trainman419** [comment] 2016-05-03 20:51
I'm able to reproduce this on bazel 0.2.1 on Linux.

The proposed workaround (`bazel build --hazelcast_node=localhost:5701` and then `bazel build --hazelcast_node=localhost:5701 --spawn_strategy=remote ...`) does not work either.

**Comment by hhclam** [comment] 2016-05-03 20:52
@trainman419: what's the error message?

**Comment by glinscott** [comment] 2016-05-03 20:54
@hhclam:

This is the error message:
```
$ bazel build --spawn_strategy=remote --hazelcast_node=170.0.0.1:5701 ...
INFO: Waiting for response from Bazel server (pid 23277)...
ERROR: 'remote' is an invalid value for spawn strategy. Valid values are: local, sandboxed, standalone, worker.
INFO: Elapsed time: 10.258s
```

**Comment by trainman419** [comment] 2016-05-03 20:55
Same error message as above:

```
INFO: Waiting for response from Bazel server (pid 9797)...
ERROR: 'remote' is an invalid value for spawn strategy. Valid values are: local, sandboxed, standalone, worker.
INFO: Elapsed time: 10.119s
```

Of particular note, the hazelcast node is running on a machine that doesn't appear to be reachable from my computer. (but bazel doesn't report that as the error)

**Comment by trainman419** [comment] 2016-05-03 22:04
I've confirmed that this was a network issue; once I resolved my network connectivity issue I was able to use `bazel build --hazelcast_node=remote_host:5701 --spawn_strategy=remote ...`

Please provide an error message when the remote hazelcast node is unreachable.

**Comment by adamhowardprice** [comment] 2016-05-04 18:39
When I try the above, I get `INFO: Waiting for response from Bazel server (pid 16771)...` which hangs forever, or at least a few minutes before I Ctrl-C out of it.

```
bazel build --hazelcast_node=127.0.0.1:5701 src/tools/generate_workspace:all
Extracting Bazel installation...
Sending SIGTERM to previous Bazel server (pid=11899)... done.
.
INFO: Waiting for response from Bazel server (pid 16771)...
```

**Comment by hhclam** [comment] 2016-05-04 19:32
@adamhowardprice: if you don't have --spawn_strategy=remote and just having --hazelcast_node has no added value. You can do a bazel shutdown to tell bazel to shutdown, so you don't need to rely on ctr-c. I think the problem is there's some issues connecting to the hazelcast server that caused an unchecked exception and bazel dies. I noticed you're using hazelcast server 3.6.2, have you tried the version that comes with bazel source tree, this maybe a backward compability issue with hazelcast. I'll update both the hazelcast soon.

@trainman419: you're right that it doesn't warn against an invalid hazelcast host. something should be fixed.

@glinscott: have you checked if it is a connectivity issue? @trainman419 is right: if there's a connectivity issue then "remote" strategy is not available.

**Comment by glinscott** [comment] 2016-05-04 20:08
@hhclam - it was the same issue, thanks!

**Comment by adamhowardprice** [comment] 2016-05-04 20:21
@hhclam The version of hazelcast that Bazel uses worked for me. Thanks!

**Comment by philwo** [comment] 2016-12-09 14:44
Just to summarize what's left to be done here: From reading the history of this bug, I think the remaining work is to improve error messages on connectivity failures, so that Bazel doesn't just print "'remote' is an unknown strategy" (or something like that).

**Comment by ulfjack** [comment] 2017-05-10 08:57
I'm going to close this bug - I know that we still need to improve our error handling, but I always do a double-take when I see this issue.

**Closed by ulfjack** 2017-05-10 08:57 UTC
Labels: category: service APIs, P2, type: bug

**Comment by excitoon** [comment] 2019-03-05 08:58
Still an issue in 0.19.2.

**Comment by philwo** [comment] 2019-03-05 09:32
@excitoon What exactly?

This bug is very old (and Bazel 0.19.2, too). If you can reproduce this with the latest release, please feel free to open a new issue so that we can investigate.

**Comment by excitoon** [comment] 2019-03-05 09:45
Poor error handling. 0.23.1:
```
C:\Users\Chebotarev_V\Documents\src\bazel>bazel build //src:bazel --spawn_strategy=remote
WARNING: detected http_proxy set in env, setting no_proxy for localhost.
Starting local Bazel server and connecting to it...
WARNING: C:/users/chebotarev_v/documents/src/bazel/src/main/native/windows/BUILD:65:1: in linkstatic attribute of cc_
library rule //src/main/native/windows:resources: setting 'linkstatic=1' is recommended if there are no object files
INFO: Analysed target //src:bazel (210 packages loaded, 10114 targets configured).
INFO: Found 1 target...
ERROR: 'remote' is an invalid value for remote spawn strategy. Valid values are: local, standalone, worker
INFO: Elapsed time: 84.460s
INFO: 0 processes.
FAILED: Build did NOT complete successfully
```

I would expect an explanation what exactly is needed for `remote` (for example, URL missing or bad connectivity).

**Comment by excitoon** [comment] 2019-03-05 09:48
@philwo I'm not 100% sure it does require a fix, that is why I only take your attention to this problem by upvoting (because we just bumped into it here).
