### ISSUE TITLE
compile.sh appears broken in MSYS2

### ISSUE THREAD

**Issue by mrdomino** [bazelbuild/bazel#328] opened 2015-07-24 21:17 UTC
This is on a clean install of MSYS2 plus the dependencies listed on the windows page. It's on Windows 8.1 Pro. Tested on 3fe87d7b as well as a couple earlier commits. Fwiw that file does exist (with the slashes the other way around, from msys's perspective) in the tmp directory.

```
$ ./compile.sh
INFO: You can skip this first step by providing a path to the bazel binary as second argument:
INFO:    ./compile.sh build /path/to/bazel
🍃  Building Bazel from scratch..
Compiling Bazel Java code...
/c/Program Files/Java/jdk1.8.0_45//bin/javac -classpath third_party/aether/aether-api-1.0.0.v20140518.jar;third_party/aether/aether-connector-basic-1.0.0.v20140518.jar;third_party/aether/aether-impl-1.0.0.v20140518.jar;third_party/aether/aether-spi-1.0.0.v20140518.jar;third_party/aether/aether-transport-classpath-1.0.0.v20140518.jar;third_party/aether/aether-transport-file-1.0.0.v20140518.jar;third_party/aether/aether-transport-http-1.0.0.v20140518.jar;third_party/aether/aether-transport-wagon-1.0.0.v20140518.jar;third_party/aether/aether-util-1.0.0.v20140518.jar;third_party/android_common/com.android.tools.build_builder-model_0.13.3.jar;third_party/android_common/com.android.tools.build_builder_0.13.3.jar;third_party/android_common/com.android.tools.build_manifest-merger_23.1.3.jar;third_party/android_common/com.android.tools.layoutlib_layoutlib_23.1.3.jar;third_party/android_common/com.android.tools_common_23.1.3.jar;third_party/android_common/com.android.tools_sdk-common_23.1.3.jar;third_party/android_common/com.android.tools_sdklib_23.1.3.jar;third_party/apache_commons_collections/commons-collections-3.2.1.jar;third_party/apache_commons_compress/apache-commons-compress-1.9.jar;third_party/apache_commons_logging/commons-logging-1.1.1.jar;third_party/apache_commons_pool2/commons-pool2-2.3.jar;third_party/apache_httpclient/httpclient-4.2.5.jar;third_party/apache_httpcore/httpcore-4.2.4.jar;third_party/apache_velocity/velocity-1.7.jar;third_party/asm/asm-5.0.3.jar;third_party/auto/auto-common-0.3.jar;third_party/auto/auto-service-1.0-rc2.jar;third_party/auto/auto-value-1.0.jar;third_party/checker_framework_dataflow/dataflow-1.8.10.jar;third_party/error_prone/error_prone_annotations-2.0.5-20150630-51ec2fd.jar;third_party/error_prone/error_prone_core-2.0.5-20150630-51ec2fd.jar;third_party/gson/gson-2.2.4.jar;third_party/guava/guava-18.0.jar;third_party/guava/guava-testlib.jar;third_party/hamcrest/hamcrest-core-1.3.jar;third_party/ijar/test/libwrongcentraldir.jar;third_party/java/jarjar/jarjar-1.4.jar;third_party/java/jdk/langtools/javac.jar;third_party/jformatstring/jFormatString-3.0.0.jar;third_party/jgit/org.eclipse.jgit-4.0.1.201506240215-r.jar;third_party/joda-time/joda-time-2.3.jar;third_party/joda_time/joda-time-2.3.jar;third_party/jsr305/jsr-305.jar;third_party/jsr330_inject/javax.inject.jar;third_party/junit/junit-4.11.jar;third_party/maven_model/maven-aether-provider-3.2.3.jar;third_party/maven_model/maven-model-3.2.3.jar;third_party/maven_model/maven-model-builder-3.2.3.jar;third_party/maven_model/maven-repository-metadata-3.2.3.jar;third_party/mockito/mockito-all-1.10.19.jar;third_party/plexus_component_annotations/plexus-component-annotations-1.6.jar;third_party/plexus_interpolation/plexus-interpolation-1.22.jar;third_party/plexus_utils/plexus-utils-3.0.21.jar;third_party/protobuf/protobuf-java-3.0.0-alpha-3.jar;third_party/slf4j/slf4j-api-1.7.7.jar;third_party/slf4j/slf4j-jdk14-1.7.7.jar;third_party/tomcat_annotations_api/tomcat-annotations-api-8.0.5.jar;third_party/truth/truth-0.27.jar;: -sourcepath src/java_tools/singlejar/java/com/google/devtools/build/zip;src/main/java;src/tools/xcode-common/java/com/google/devtools/build/xcode/common;src/tools/xcode-common/java/com/google/devtools/build/xcode/util;/tmp/bazel.1ztwQv9G/src -d /tmp/bazel.1ztwQv9G/classes -source 1.7 -target 1.7 @/tmp/bazel.93befIeb/param
javac: file not found: \tmp\bazel.1ztwQv9G\src\com\google\devtools\build\buildjar\proto\JavaCompilation.java
Usage: javac <options> <source files>
use -help for a list of possible options
```

**Comment by dslomov** [comment] 2015-08-10 16:19
A workaround is to do smth like:
  export TMPDIR=c:/temp
then msys's path mangling^W "correction" will not kick in.

**Comment by ulfjack** [comment] 2015-09-03 17:03
I'll claim that this is a duplicate of #276.

**Closed by ulfjack** 2015-09-03 17:03 UTC
Labels: bug, P2
