### ISSUE TITLE
Release - February 2018 - Target RC date: 2018-02-01 - name: 0.11.0

### ISSUE THREAD

**Issue by damienmg** [bazelbuild/bazel#3959] opened 2017-10-24 13:11 UTC
Release tracking bug for February 2018:

- Target cut should be 1st of February (first business day of January) but it is close to FOSDEM so we might want to delay
- Name: 0.11.0

RM if we follow the rotation should be @katre: can you take it?

**Comment by dslomov** [comment] 2018-01-08 11:39
@katre - assigning to you for Feb 1. Please lmk if that does not work.

**Comment by katre** [comment] 2018-01-08 14:47
I can manage it.

**Comment by iirina** [comment] 2018-01-31 19:12
@katre can you make sure 223ed93582dbb730eb92c80cc6350dcec116ec0a will be included in the RC? I think if you cut from the nightly it should be..

**Comment by katre** [comment] 2018-01-31 20:07
I will. I plan to check tomorrow's nightly and cut then.

**Comment by katre** [comment] 2018-02-01 18:11
Taking 00d781ae78a8bd51d3c61b621d79f0bb095aff9e as the baseline (from last night's nightly run: https://ci.bazel.build/view/Dashboard/job/bazel/job/nightly/212/)

Next step is to build the RC, then start filing bugs on the test failures.

**Comment by katre** [comment] 2018-02-01 18:13
Release note edits:
None.

**Comment by katre** [comment] 2018-02-01 18:17
Release is pushed, waiting for https://ci.bazel.build/job/bazel/job/release/1282/ to finish

**Comment by laszlocsomor** [comment] 2018-02-06 17:34
@katre : Please replace the following in the release notes:

> * java,runfiles: You can now depend on `@bazel\_tools//tools/runfiles:java-runfiles` to get a platform-independent runfiles library for Java. See JavaDoc of https://github.com/bazelbuild/bazel/blob/master/src/tools/runfiles /java/com/google/devtools/build/runfiles/Runfiles.java for usage information.

With this:

> * java,runfiles: You can now depend on `@bazel_tools//tools/runfiles:java-runfiles` to get a platform-independent runfiles library for Java. See JavaDoc of https://github.com/bazelbuild/bazel/blob/master/src/tools/runfiles/java/com/google/devtools/build/runfiles/Runfiles.java for usage information.

**Comment by laszlocsomor** [comment] 2018-02-06 17:45
Actually, @katre , please remove [that entry I mentioned](https://github.com/bazelbuild/bazel/issues/3959#issuecomment-363501840) altogether. I discovered a bug about it, filing it now, will update this comment with the  bug number.

**Comment by katre** [comment] 2018-02-06 17:59
How long will the fix be? I'd prefer to edit the release notes and get your fix cherrypicked along with the fix for #4562 in the next RC.

**Comment by laszlocsomor** [comment] 2018-02-06 18:01
I can write the fix tomorrow and, if all goes well, get it submitted tomorrow or the day after.

**Comment by katre** [comment] 2018-02-06 18:05
SGTM, thanks.

**Comment by laszlocsomor** [comment] 2018-02-07 15:00
@katre : bugfix is out for review (https://bazel-review.googlesource.com/c/bazel/+/37190), we'll need a cherrypick.

**Comment by laszlocsomor** [comment] 2018-02-07 16:05
#4598 is a blocker, will need a cherrypick.

**Comment by laszlocsomor** [comment] 2018-02-08 15:07
Please cherrypick https://github.com/bazelbuild/bazel/commit/d855d8133f4efb73ebd5e82c54a9afb4c7565d46 into RC2.

**Comment by ola-rozenfeld** [comment] 2018-02-08 15:56
We need to cherrypick https://github.com/bazelbuild/bazel/commit/56aeb04a064218b845ecc193d530c341c6ec854d, ideally into 0.10.1.

**Comment by katre** [comment] 2018-02-08 16:02
@ola-rozenfeld I'll add that to the cherrypick list for 0.11.0rc2. For 0.10.1 you'll need to ping the release issue for 0.10.0, which is #4325 .

**Comment by katre** [comment] 2018-02-08 18:34
Current release blocking bugs for 0.11.0:
- #4585 - orphaned remote cached actions fallback broken
  - 56aeb04a064218b845ecc193d530c341c6ec854d
  - The issue is still open: @ola-rozenfeld are there more commits coming?
- #4608 - test stdout is sometimes missing
  - There is a fix in the works
- #4598 - runfiles library should not pick up TEST_SRCDIR
  - There appear to be several commits, but the issue is still open. @laszlocsomor are there more commits coming?
  - d855d8133f4efb73ebd5e82c54a9afb4c7565d46
    - Does not reference the issue, I assume it is related?
  - d7b6a7790eb2f1fb25616c3f76b9ef04d636c979
  - 13c337340cc8904c421d73c685aabe17eeede25b
- #4562 - Fixed
  - ea2d4c4

I'll need to verify the sequencing when all cherrypicks are collected.

**Comment by ola-rozenfeld** [comment] 2018-02-08 18:51
Commit  56aeb04
<https://github.com/bazelbuild/bazel/commit/56aeb04a064218b845ecc193d530c341c6ec854d>
 fixed #4585 <https://github.com/bazelbuild/bazel/issues/4585>, not sure
why it didn't auto-close. Closing now.

**Comment by petemounce** [comment] 2018-02-08 20:40
Pushed
* https://chocolatey.org/packages/bazel/0.11.0-rc1
* https://chocolatey.org/packages/bazel/0.11.0-rc2

**Comment by katre** [comment] 2018-02-08 20:57
Thanks @petemounce!

**Comment by laszlocsomor** [comment] 2018-02-09 08:07
>   - There appear to be several commits, but the issue is still open. @laszlocsomor are there more commits coming?

No.

>   - d855d8133f4efb73ebd5e82c54a9afb4c7565d46
>    - Does not reference the issue, I assume it is related?

Cherry-pick this please.

Bummer. It should reference the bug. That *is* the bugfix.

>  - d7b6a7790eb2f1fb25616c3f76b9ef04d636c979

No cherry-pick.

This is related, but I don't need you to cherry-pick it; it just adds tests for the bugfix.

>  - 13c337340cc8904c421d73c685aabe17eeede25b

No cherry-pick.

This is distantly related; it fixes the same bug in the Python runfiles library as d855d8133f4efb73ebd5e82c54a9afb4c7565d46 did in the Java runfiles library. However 0.11.0 does not contain the original commits for the Py runfils library, so this commit needs not be cherry-picked.

**Comment by katre** [comment] 2018-02-09 13:59
Thanks for clarifying!

**Comment by katre** [comment] 2018-02-09 14:11
Creating RC2.

``
$ release.sh create 0.11.0 \
  00d781ae78a8bd51d3c61b621d79f0bb095aff9e \
  ea2d4c4 \
  d855d81 \
  56aeb04
```

Release note edits: removed section of java runfiles (as per https://github.com/bazelbuild/bazel/issues/3959#issuecomment-363505459).

**Comment by laszlocsomor** [comment] 2018-02-09 14:13
> Release note edits: removed section of java runfiles (as per https://github.com/bazelbuild/bazel/issues/3959#issuecomment-363505459).

Oh, now I fixed the bug, the section could've stayed! Could you please restore it? I believe you don't need to create a new RC for that.

**Comment by buchgr** [comment] 2018-02-09 18:33
@katre please cherry-pick cf3f81aef7c32019d70cbce218a64a03276268f0 - this is a regression from 0.10.0. HTTP Basic Auth for Remote Caching used to work there and users are relying on it.

**Comment by katre** [comment] 2018-02-12 15:49
Creating RC2, adding cherrypicks cf3f81aef7c32019d70cbce218a64a03276268f0 and 28bd997c1c8793973f63dcae4c22bbae49e7d8b7.

**Comment by katre** [comment] 2018-02-12 15:54
Command:
```
$ release.sh create 0.11.0 \
  00d781ae78a8bd51d3c61b621d79f0bb095aff9e \
  ea2d4c4 \
  d855d81 \
  56aeb04 \
  cf3f81a \
  28bd997
```

Note: Cherrypick of cf3f81a required manual fixes due to changes to recently-added remote caching doc.

Release note edits: none.

**Comment by katre** [comment] 2018-02-12 17:56
After checking the output of tests, I've filed the following issues. Some of these probably are not release blockers, I will review further.

- https://github.com/bazelbuild/bazel/issues/4625
- https://github.com/bazelbuild/bazel/issues/4626
- https://github.com/bazelbuild/bazel/issues/4627
- https://github.com/bazelbuild/bazel-integration-testing/issues/17
- https://github.com/bazelbuild/rules_rust/issues/68
- https://github.com/bazelbuild/continuous-integration/issues/179

**Comment by laszlocsomor** [comment] 2018-02-13 08:33
I found another release blocker with the Java runfiles library. I'll file a bug as soon as I have a simple repro and fix.

**Comment by laszlocsomor** [comment] 2018-02-13 09:56
Never mind, the bug I found isn't release-critical.

For the record, the problem is that if Bazel builds a java_binary on Linux, and runfiles tree building is enabled, then the java_binary cannot run with just a runfiles manifest and without a runfiles tree. In other words, the Java launcher stub cannot use `$RUNFILES_MANIFEST_FILE` and `$RUNFILES_MANIFEST_ONLY` from the environment unless Bazel built it assuming no runfiles trees.

I don't think this is a problem in practice, so far I only hit it in tests, when a test built a java_binary with runfiles tree generation enabled, but then running it with a mock runfiles manifest and RUNFILES_MANIFEST_ONLY=1.

**Comment by mhlopko** [comment] 2018-02-19 14:11
As we discussed internally, would you be so kind to include b3d52b1 in 0.11.0?

**Comment by ola-rozenfeld** [comment] 2018-02-20 17:30
https://github.com/bazelbuild/bazel/commit/1001141f0674ff4b611814edcb00a5183680ef4a
is now in (again) and as discussed earlier, this needs to go into 0.11.0 as
well.
Thank you!

**Comment by katre** [comment] 2018-02-20 18:39
Preparing RC4.

Command:
```
$ release.sh create 0.11.0 \
  00d781ae78a8bd51d3c61b621d79f0bb095aff9e \
  ea2d4c4 \
  d855d81 \
  56aeb04 \
  cf3f81a \
  28bd997 \
  109e4b4 \
  b3d52b1 \
  1001141
```

**Comment by katre** [comment] 2018-02-20 21:47
Open issues in 0.11.0rc4:
- Tensorflow is red. Will triage more tomorrow, although it might be related to #4652.
- bazel-toolchains is broken, see #4658

**Comment by katre** [comment] 2018-02-22 20:46
Assuming no new release blockers appears overnight I plan to release 0.11.0 tomorrow.

**Comment by katre** [comment] 2018-02-23 16:27
Pushed release:

https://github.com/bazelbuild/bazel/releases/tag/0.11.0
https://releases.bazel.build/0.11.0/release/index.html
@petemounce : Could you please update Chocolatey? Thanks!
@ilovezfs : Could you please update Homebrew?

**Comment by ilovezfs** [comment] 2018-02-23 18:35
Build failed on all 3 CI nodes:
https://jenkins.brew.sh/job/Homebrew%20Core%20Pull%20Requests/19148/version=el_capitan/consoleFull
https://jenkins.brew.sh/job/Homebrew%20Core%20Pull%20Requests/19148/version=sierra/consoleFull
https://jenkins.brew.sh/job/Homebrew%20Core%20Pull%20Requests/19148/version=high_sierra/consoleFull

**Comment by katre** [comment] 2018-02-23 18:46
@ilovezfs Ugh, that's weird. I'll try it on my mac and see if I can reproduce it. I don't actually know how Homebrew works, can you point me to the configuration or build script that is being run?

**Comment by ilovezfs** [comment] 2018-02-23 18:50
It's running the install method https://github.com/ilovezfs/homebrew-core/blob/32d75a3bdcbe63aa11341dc79650b53fdccceae4/Formula/bazel.rb#L17-L32

```
/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
brew pull https://github.com/Homebrew/homebrew-core/pull/24479
brew install --debug --verbose bazel
```

**Comment by katre** [comment] 2018-02-23 19:09
@ilovezfs The problem is the ```"--output_user_root", buildpath/"output_user_root"``` section. It looks like something related to having the output root in the same directory as the bazel source is causing this.

I'm going to bisect and find the cause (since this worked in 0.10.1, looks like). However, how necessary is it that the output_user_root be in the same directory? Could it be possible to, inside the buildpath, create separate directories for work (the BAZEL_WRKDIR env variable), output_user_root, and bazel (the actual source), which in my tests seems to avoid this problem?

**Comment by ilovezfs** [comment] 2018-02-23 19:24
```
diff --git a/Formula/bazel.rb b/Formula/bazel.rb
index 3554c25..bd50770 100644
--- a/Formula/bazel.rb
+++ b/Formula/bazel.rb
@@ -19,16 +19,22 @@ class Bazel < Formula
     # Force Bazel ./compile.sh to put its temporary files in the buildpath
     ENV["BAZEL_WRKDIR"] = buildpath/"work"
 
-    system "./compile.sh"
-    system "./output/bazel", "--output_user_root", buildpath/"output_user_root",
-           "build", "scripts:bash_completion"
+    (buildpath/"sources").install buildpath.children
 
-    bin.install "scripts/packages/bazel.sh" => "bazel"
-    bin.install "output/bazel" => "bazel-real"
-    bin.env_script_all_files(libexec/"bin", Language::Java.java_home_env("1.8"))
+    cd "sources" do
+      system "./compile.sh"
+      system "./output/bazel", "--output_user_root",
+             buildpath/"output_user_root", "build", "scripts:bash_completion"
 
-    bash_completion.install "bazel-bin/scripts/bazel-complete.bash"
-    zsh_completion.install "scripts/zsh_completion/_bazel"
+      bin.install "scripts/packages/bazel.sh" => "bazel"
+      bin.install "output/bazel" => "bazel-real"
+      bin.env_script_all_files(libexec/"bin", Language::Java.java_home_env("1.8"))
+
+      bash_completion.install "bazel-bin/scripts/bazel-complete.bash"
+      zsh_completion.install "scripts/zsh_completion/_bazel"
+
+      prefix.install_metafiles
+    end
   end
 
   test do
```
should work, though it's not pretty.

**Comment by katre** [comment] 2018-02-23 19:26
Okay, thanks. I've regressed back to the 0.9.0 release, and I see the same error when output_user_root is in the same directory as Bazel sources, so I'm confused that this ever worked.

**Comment by ilovezfs** [comment] 2018-02-23 19:27
It's been working fine like that for a while …

**Comment by katre** [comment] 2018-02-23 19:29
It's also possibly a bug in my bisect script, grump grump...

**Comment by ilovezfs** [comment] 2018-02-23 20:23
0.11.0 shipped in Homebrew.

**Comment by katre** [comment] 2018-02-23 20:28
@ilovezfs Thanks! I appreciate you working with me to help resolve the issue.

**Comment by ilovezfs** [comment] 2018-02-23 20:30
You're welcome!

**Comment by buchgr** [comment] 2018-02-23 20:42
@ilovezfs big thanks ! awesome!

**Comment by petemounce** [comment] 2018-02-23 22:44
I think the automation I wrote is affected by https://githubengineering.com/crypto-removal-notice/. I'll fix and push soonest, but not around this weekend.

**Comment by petemounce** [comment] 2018-02-25 09:40
Up now at https://chocolatey.org/packages/bazel/0.11.0 via a manual hack.

**Comment by buchgr** [comment] 2018-02-25 10:02
thanks so much @petemounce ... ur work is awesome

**Comment by petemounce** [comment] 2018-02-25 11:29
My pleasure :)

**Comment by katre** [comment] 2018-02-25 21:20
Thanks very much @petemounce!

With this finished, I am closing the issue for this release.

**Comment by katre** [comment] 2018-02-28 15:24
Re-opening to create RC for 0.11.1, cherrypicking fc98b44 to deal with #4736 .

**Comment by katre** [comment] 2018-02-28 18:20
Release command:
```
release.sh create 0.11.1 \
  00d781ae78a8bd51d3c61b621d79f0bb095aff9e \
  ea2d4c4 \
  d855d81 \
  56aeb04 \
  cf3f81a \
  28bd997 \
  109e4b4 \
  b3d52b1 \
  1001141 \
  fc98b44
```

**Comment by katre** [comment] 2018-02-28 18:21
The release branch is created, but given the current state of our CI system I do not know if Buildkite can create the release artifacts. @philwo and @buchgr , can you comment?

**Comment by katre** [comment] 2018-03-01 14:53
Release branch is https://github.com/bazelbuild/bazel/tree/release-0.11.1

**Comment by buchgr** [comment] 2018-03-02 20:21
cc: @vbatts

**Comment by vbatts** [comment] 2018-03-02 20:43
hey hey! Been a while since you CC'ed, but usually blogtrottr.com does a good job emailing as soon as you tag the releases but didn't get notification of 0.11.0 :thinking: 

https://copr.fedorainfracloud.org/coprs/vbatts/bazel/builds/ has up to 0.10.1

**Comment by vbatts** [comment] 2018-03-02 20:44
perhaps i'll just jump to 0.11.1 once it's out?

**Comment by buchgr** [comment] 2018-03-02 20:59
@vbatts I apologize. I have just noticed this myself a few hours ago and that's why I pinged you :-). It's up to you. 0.11.1 should be out next week.

We are currently working on a new release process and we'll be able to set it up so that we can automatically send you an e-mail. Again, apologies for not pinging you.

**Comment by vbatts** [comment] 2018-03-02 21:44
Right on. I'll wait til 0.11.1 :-)

**Comment by philwo** [comment] 2018-03-06 18:20
I'm working to get this pushed as a release, but am currently fighting with our scripts a bit. Sorry for the delay! Hope to get it out by tomorrow.

**Comment by philwo** [comment] 2018-03-06 18:35
I had to recreate the release branch on my machine, as otherwise the script wouldn't let me release it.

Steps:
```
release.sh create 0.11.1 \
  00d781ae78a8bd51d3c61b621d79f0bb095aff9e \
  ea2d4c4 \
  d855d81 \
  56aeb04 \
  cf3f81a \
  28bd997 \
  109e4b4 \
  b3d52b1 \
  1001141 \
  fc98b44

# Resolve first conflict:
git rm site/docs/remote-caching.md
git cherry-pick --continue; exit

# Resolve second conflict:
vi tools/test/test-setup.sh  # Pick the second version of the conflicting diff.
git add tools/test/test-setup.sh
git cherry-pick --continue; exit

# Edit release notes to read:
Important changes:
  - Fixes regression building Android rules on Windows.

# Push
release.sh push

# Release
release.sh release
```

Now waiting for CI to build the binaries, will verify that they're fine and will run the release steps for GitHub, GCS and the apt repository then.

**Comment by philwo** [comment] 2018-03-07 15:12
Release was built successfully: https://buildkite.com/bazel/release/builds/11
and released: https://groups.google.com/d/msg/bazel-discuss/lmuaMaYiY-o/r8CCYqO6AAAJ 🎉

**Comment by vbatts** [comment] 2018-03-07 15:42
fedora and centos build is kicked off:
https://copr.fedorainfracloud.org/coprs/vbatts/bazel/build/725354/

**Comment by buchgr** [comment] 2018-03-07 16:51
tyvm @vbatts

**Comment by buchgr** [comment] 2018-03-08 14:43
ty @petemounce !

**Closed** 2018-03-21 17:10 UTC
Labels: release
