### ISSUE TITLE
Bazel is not telling where target was mentioned (when there are more than one bad packages)

### ISSUE THREAD

**Issue by excitoon** [bazelbuild/bazel#6998] opened 2018-12-26 10:13 UTC
### Description of the problem / feature request:

Bazel is not telling where target was mentioned when there are more than one bad packages.

https://github.com/excitoon/bazel-issues/tree/master/not-telling-where-mentioned

```
C:\Users\Chebotarev_V\Documents\src\bazel-issues\not-telling-where-mentioned>bazel build hello-world
INFO: Invocation ID: 23c775f6-50a7-438f-8d23-6b476560f26f
ERROR: Analysis of target '//:hello-world' failed; build aborted: no such package 'find_me': BUILD file not found on package path
INFO: Elapsed time: 0.682s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (9 packages loaded, 45 targets configured)
```

`BUILD`:
```
package(default_visibility = ["//visibility:public"])

cc_library(
    name = "hello-world",
    srcs = [
        "hello-world.cpp",
    ],
    deps = [
        "//a:a",
        "//b:b",
        "//c:c"
    ]
)
```

Which dependency is erroneous? Your guesses. :)

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

https://github.com/excitoon/bazel-issues/tree/master/not-telling-where-mentioned

### What operating system are you running Bazel on?

Windows x64

### What's the output of `bazel info release`?

```
Build label: 0.21.0
Build target: bazel-out/x64_windows-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Wed Dec 19 12:58:16 2018 (1545224296)
Build timestamp: 1545224296
Build timestamp as int: 1545224296
```

Also works on 0.20.0

### Any other information, logs, or outputs that you want to share?

If I make only one erroneous package:
```
cc_library(
    srcs = ["//c:c.h", "//a:a.h", #"//seek_me:e.h",
                     "//b:b.h", "//find_me:d.h"]
)
```
problem disappears and Bazel produces normal output:
```
C:\Users\Chebotarev_V\Documents\src\bazel-issues\not-telling-where-mentioned>bazel build hello-world
INFO: Invocation ID: 62186c62-7cc7-48d5-97c3-cdc9fef46c02
ERROR: C:/users/chebotarev_v/documents/src/bazel-issues/not-telling-where-mentioned/<SPOILER>/BUILD:3:1: no such package 'find_me': BUILD file not found on package path and referenced by <SPOILER>
ERROR: Analysis of target '//:hello-world' failed; build aborted: no such package 'find_me': BUILD file not found on package path
INFO: Elapsed time: 0.495s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (2 packages loaded, 9 targets configured)
```

### Merry Christmas!

**Comment by janakdr** [comment] 2020-08-24 19:37
Sorry for the long delay in responding to this! I can't reproduce:

```
$ bazel build :hello-world
Extracting Bazel installation...
Starting local Bazel server and connecting to it...
ERROR: /usr/local/google/home/janakr/bazel-example/not-telling-where-mentioned/c/BUILD:3:11: no such package 'find_me': BUILD file not found in any of the following directories. Add a BUILD file to a directory to mark it as a package.
 - /usr/local/google/home/janakr/bazel-example/not-telling-where-mentioned/find_me and referenced by '//c:c'
ERROR: Analysis of target '//:hello-world' failed; build aborted: Analysis failed
INFO: Elapsed time: 6.308s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (17 packages loaded, 29 targets configured)
```

This is with Bazel 3.4.1. Closing, please reopen if you are still seeing this issue.

**Closed by janakdr** 2020-08-24 19:37 UTC
Labels: bad error messaging, team-Core, untriaged
