### ISSUE TITLE
Bazel should get rid of stale _cache 

### ISSUE THREAD

**Issue by yaroslavvb** [bazelbuild/bazel#1628] opened 2016-08-10 22:51 UTC
My `bazel build` just ran out of disk space, and it turned out that there was 75GB under `~/.cache/bazel`

I've been using bazel 0.2.3 and 0.3 for the last couple of months building TensorFlow on Ubuntu 16.04

**Comment by jin** [comment] 2018-11-06 20:36
Closing this as a duplicate of https://github.com/bazelbuild/bazel/issues/1035

**Closed by jin** 2018-11-06 20:36 UTC
Labels: P3, category: performance, type: feature request
