### ISSUE TITLE
CI: rules_docker failing on macOS

### ISSUE THREAD

**Issue by laszlocsomor** [bazelbuild/bazel#4173] opened 2017-11-27 14:10 UTC
bazel-nightly's downstream project "rules_docker " is failing:

https://ci.bazel.io/job/Global/job/rules_docker/294/consoleFull

```
[variation=,node=darwin-x86_64] FAILED: Build did NOT complete successfully (75 packages loaded)
[variation=,node=darwin-x86_64] FAILED: Build did NOT complete successfully (75 packages loaded)
[variation=,node=darwin-x86_64] java.lang.RuntimeException: Unrecoverable error while evaluating node 'CONFIGURED_TARGET://testdata:java_bin_as_lib_image e4509483ce5a4ed4ff6e50c5e4b8b8b6 (1167560220 1611918777)' (requested by nodes )
[variation=,node=darwin-x86_64] 	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:414)
[variation=,node=darwin-x86_64] 	at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:352)
[variation=,node=darwin-x86_64] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[variation=,node=darwin-x86_64] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[variation=,node=darwin-x86_64] 	at java.lang.Thread.run(Thread.java:748)
[variation=,node=darwin-x86_64] Caused by: java.lang.IllegalArgumentException: Invalid EvalException:
[variation=,node=darwin-x86_64] java.lang.NullPointerException
[variation=,node=darwin-x86_64] 	at com.google.devtools.build.lib.rules.java.JavaInfo.getTransitiveRuntimeJars(JavaInfo.java:213)
[variation=,node=darwin-x86_64] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[variation=,node=darwin-x86_64] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[variation=,node=darwin-x86_64] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[variation=,node=darwin-x86_64] 	at java.lang.reflect.Method.invoke(Method.java:498)
[variation=,node=darwin-x86_64] 	at com.google.devtools.build.lib.syntax.FuncallExpression.callMethod(FuncallExpression.java:297)
[variation=,node=darwin-x86_64] 	at com.google.devtools.build.lib.syntax.DotExpression.eval(DotExpression.java:115)
[variation=,node=darwin-x86_64] 	at com.google.devtools.build.lib.syntax.DotExpression.doEval(DotExpression.java:54)
[variation=,node=darwin-x86_64] 	at com.google.devtools.build.lib.syntax.Expression.eval(Expression.java:67)
[variation=,node=darwin-x86_64] 	at com.google.devtools.build.lib.syntax.FuncallExpression.evalArguments(FuncallExpression.java:686)
[variation=,node=darwin-x86_64] 	at com.google.devtools.build.lib.syntax.FuncallExpression.callFunction(FuncallExpression.java:746)
[variation=,node=darwin-x86_64] 	at com.google.devtools.build.lib.syntax.FuncallExpression.doEval(FuncallExpression.java:719)
[variation=,node=darwin-x86_64] 	at com.google.devtools.build.lib.syntax.Expression.eval(Expression.java:67)
[variation=,node=darwin-x86_64] 	at com.google.devtools.build.lib.syntax.LValue.assignAugmented(LValue.java:177)
[variation=,node=darwin-x86_64] 	at com.google.devtools.build.lib.syntax.Eval.execAugmentedAssignment(Eval.java:57)
[variation=,node=darwin-x86_64] 	at com.google.devtools.build.lib.syntax.Eval.execDispatch(Eval.java:185)
[variation=,node=darwin-x86_64] 	at com.google.devtools.build.lib.syntax.Eval.exec(Eval.java:173)
[variation=,node=darwin-x86_64] 	at com.google.devtools.build.lib.syntax.Eval.execStatements(Eval.java:221)
[variation=,node=darwin-x86_64] 	at com.google.devtools.build.lib.syntax.Eval.execIfBranch(Eval.java:62)
[variation=,node=darwin-x86_64] 	at com.google.devtools.build.lib.syntax.Eval.execDispatch(Eval.java:188)
[variation=,node=darwin-x86_64] 	at com.google.devtools.build.lib.syntax.Eval.exec(Eval.java:173)
[variation=,node=darwin-x86_64] 	at com.google.devtools.build.lib.syntax.Eval.execIf(Eval.java:119)
[variation=,node=darwin-x86_64] 	at com.google.devtools.build.lib.syntax.Eval.execDispatch(Eval.java:204)
[variation=,node=darwin-x86_64] 	at com.google.devtools.build.lib.syntax.Eval.exec(Eval.java:173)
[variation=,node=darwin-x86_64] 	at com.google.devtools.build.lib.syntax.UserDefinedFunction.call(UserDefinedFunction.java:88)
[variation=,node=darwin-x86_64] 	at com.google.devtools.build.lib.syntax.BaseFunction.call(BaseFunction.java:430)
[variation=,node=darwin-x86_64] 	at com.google.devtools.build.lib.syntax.FuncallExpression.callFunction(FuncallExpression.java:747)
[variation=,node=darwin-x86_64] 	at com.google.devtools.build.lib.syntax.FuncallExpression.doEval(FuncallExpression.java:719)
[variation=,node=darwin-x86_64] 	at com.google.devtools.build.lib.syntax.Expression.eval(Expression.java:67)
[variation=,node=darwin-x86_64] 	at com.google.devtools.build.lib.syntax.LValue.assignAugmented(LValue.java:177)
[variation=,node=darwin-x86_64] 	at com.google.devtools.build.lib.syntax.Eval.execAugmentedAssignment(Eval.java:57)
[variation=,node=darwin-x86_64] 	at com.google.devtools.build.lib.syntax.Eval.execDispatch(Eval.java:185)
[variation=,node=darwin-x86_64] 	at com.google.devtools.build.lib.syntax.Eval.exec(Eval.java:173)
[variation=,node=darwin-x86_64] 	at com.google.devtools.build.lib.syntax.UserDefinedFunction.call(UserDefinedFunction.java:88)
[variation=,node=darwin-x86_64] 	at com.google.devtools.build.lib.syntax.BaseFunction.call(BaseFunction.java:430)
[variation=,node=darwin-x86_64] 	at com.google.devtools.build.lib.analysis.skylark.SkylarkRuleConfiguredTargetUtil.buildRule(SkylarkRuleConfiguredTargetUtil.java:92)
[variation=,node=darwin-x86_64] 	at com.google.devtools.build.lib.analysis.ConfiguredTargetFactory.createRule(ConfiguredTargetFactory.java:347)
[variation=,node=darwin-x86_64] 	at com.google.devtools.build.lib.analysis.ConfiguredTargetFactory.createConfiguredTarget(ConfiguredTargetFactory.java:233)
[variation=,node=darwin-x86_64] 	at com.google.devtools.build.lib.skyframe.SkyframeBuildView.createConfiguredTarget(SkyframeBuildView.java:500)
[variation=,node=darwin-x86_64] 	at com.google.devtools.build.lib.skyframe.ConfiguredTargetFunction.createConfiguredTarget(ConfiguredTargetFunction.java:589)
[variation=,node=darwin-x86_64] 	at com.google.devtools.build.lib.skyframe.ConfiguredTargetFunction.compute(ConfiguredTargetFunction.java:245)
[variation=,node=darwin-x86_64] 	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:340)
[variation=,node=darwin-x86_64] 	at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:352)
[variation=,node=darwin-x86_64] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[variation=,node=darwin-x86_64] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[variation=,node=darwin-x86_64] 	at java.lang.Thread.run(Thread.java:748)
[variation=,node=darwin-x86_64] 
[variation=,node=darwin-x86_64] 	at com.google.devtools.build.lib.syntax.EvalException.<init>(EvalException.java:112)
[variation=,node=darwin-x86_64] 	at com.google.devtools.build.lib.syntax.EvalException$EvalExceptionWithJavaCause.<init>(EvalException.java:209)
[variation=,node=darwin-x86_64] 	at com.google.devtools.build.lib.syntax.EvalException$EvalExceptionWithJavaCause.<init>(EvalException.java:217)
[variation=,node=darwin-x86_64] 	at com.google.devtools.build.lib.syntax.FuncallExpression.callMethod(FuncallExpression.java:330)
[variation=,node=darwin-x86_64] 	at com.google.devtools.build.lib.syntax.DotExpression.eval(DotExpression.java:115)
[variation=,node=darwin-x86_64] 	at com.google.devtools.build.lib.syntax.DotExpression.doEval(DotExpression.java:54)
[variation=,node=darwin-x86_64] 	at com.google.devtools.build.lib.syntax.Expression.eval(Expression.java:67)
[variation=,node=darwin-x86_64] 	at com.google.devtools.build.lib.syntax.FuncallExpression.evalArguments(FuncallExpression.java:686)
[variation=,node=darwin-x86_64] 	at com.google.devtools.build.lib.syntax.FuncallExpression.callFunction(FuncallExpression.java:746)
[variation=,node=darwin-x86_64] 	at com.google.devtools.build.lib.syntax.FuncallExpression.doEval(FuncallExpression.java:719)
[variation=,node=darwin-x86_64] 	at com.google.devtools.build.lib.syntax.Expression.eval(Expression.java:67)
[variation=,node=darwin-x86_64] 	at com.google.devtools.build.lib.syntax.LValue.assignAugmented(LValue.java:177)
[variation=,node=darwin-x86_64] 	at com.google.devtools.build.lib.syntax.Eval.execAugmentedAssignment(Eval.java:57)
[variation=,node=darwin-x86_64] 	at com.google.devtools.build.lib.syntax.Eval.execDispatch(Eval.java:185)
[variation=,node=darwin-x86_64] 	at com.google.devtools.build.lib.syntax.Eval.exec(Eval.java:173)
[variation=,node=darwin-x86_64] 	at com.google.devtools.build.lib.syntax.Eval.execStatements(Eval.java:221)
[variation=,node=darwin-x86_64] 	at com.google.devtools.build.lib.syntax.Eval.execIfBranch(Eval.java:62)
[variation=,node=darwin-x86_64] 	at com.google.devtools.build.lib.syntax.Eval.execDispatch(Eval.java:188)
[variation=,node=darwin-x86_64] 	at com.google.devtools.build.lib.syntax.Eval.exec(Eval.java:173)
[variation=,node=darwin-x86_64] 	at com.google.devtools.build.lib.syntax.Eval.execIf(Eval.java:119)
[variation=,node=darwin-x86_64] 	at com.google.devtools.build.lib.syntax.Eval.execDispatch(Eval.java:204)
[variation=,node=darwin-x86_64] 	at com.google.devtools.build.lib.syntax.Eval.exec(Eval.java:173)
[variation=,node=darwin-x86_64] 	at com.google.devtools.build.lib.syntax.UserDefinedFunction.call(UserDefinedFunction.java:88)
[variation=,node=darwin-x86_64] 	at com.google.devtools.build.lib.syntax.BaseFunction.call(BaseFunction.java:430)
[variation=,node=darwin-x86_64] 	at com.google.devtools.build.lib.syntax.FuncallExpression.callFunction(FuncallExpression.java:747)
[variation=,node=darwin-x86_64] 	at com.google.devtools.build.lib.syntax.FuncallExpression.doEval(FuncallExpression.java:719)
[variation=,node=darwin-x86_64] 	at com.google.devtools.build.lib.syntax.Expression.eval(Expression.java:67)
[variation=,node=darwin-x86_64] 	at com.google.devtools.build.lib.syntax.LValue.assignAugmented(LValue.java:177)
[variation=,node=darwin-x86_64] 	at com.google.devtools.build.lib.syntax.Eval.execAugmentedAssignment(Eval.java:57)
[variation=,node=darwin-x86_64] 	at com.google.devtools.build.lib.syntax.Eval.execDispatch(Eval.java:185)
[variation=,node=darwin-x86_64] 	at com.google.devtools.build.lib.syntax.Eval.exec(Eval.java:173)
[variation=,node=darwin-x86_64] 	at com.google.devtools.build.lib.syntax.UserDefinedFunction.call(UserDefinedFunction.java:88)
[variation=,node=darwin-x86_64] 	at com.google.devtools.build.lib.syntax.BaseFunction.call(BaseFunction.java:430)
[variation=,node=darwin-x86_64] 	at com.google.devtools.build.lib.analysis.skylark.SkylarkRuleConfiguredTargetUtil.buildRule(SkylarkRuleConfiguredTargetUtil.java:92)
[variation=,node=darwin-x86_64] 	at com.google.devtools.build.lib.analysis.ConfiguredTargetFactory.createRule(ConfiguredTargetFactory.java:347)
[variation=,node=darwin-x86_64] 	at com.google.devtools.build.lib.analysis.ConfiguredTargetFactory.createConfiguredTarget(ConfiguredTargetFactory.java:233)
[variation=,node=darwin-x86_64] 	at com.google.devtools.build.lib.skyframe.SkyframeBuildView.createConfiguredTarget(SkyframeBuildView.java:500)
[variation=,node=darwin-x86_64] 	at com.google.devtools.build.lib.skyframe.ConfiguredTargetFunction.createConfiguredTarget(ConfiguredTargetFunction.java:589)
[variation=,node=darwin-x86_64] 	at com.google.devtools.build.lib.skyframe.ConfiguredTargetFunction.compute(ConfiguredTargetFunction.java:245)
[variation=,node=darwin-x86_64] 	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:340)
[variation=,node=darwin-x86_64] 	... 4 more
[variation=,node=darwin-x86_64] java.lang.RuntimeException: Unrecoverable error while evaluating node 'CONFIGURED_TARGET://testdata:java_bin_as_lib_image e4509483ce5a4ed4ff6e50c5e4b8b8b6 (1167560220 1611918777)' (requested by nodes )
[variation=,node=darwin-x86_64] 	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:414)
[variation=,node=darwin-x86_64] 	at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:352)
[variation=,node=darwin-x86_64] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[variation=,node=darwin-x86_64] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[variation=,node=darwin-x86_64] 	at java.lang.Thread.run(Thread.java:748)
[variation=,node=darwin-x86_64] Caused by: java.lang.IllegalArgumentException: Invalid EvalException:
[variation=,node=darwin-x86_64] java.lang.NullPointerException
[variation=,node=darwin-x86_64] 	at com.google.devtools.build.lib.rules.java.JavaInfo.getTransitiveRuntimeJars(JavaInfo.java:213)
[variation=,node=darwin-x86_64] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[variation=,node=darwin-x86_64] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[variation=,node=darwin-x86_64] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[variation=,node=darwin-x86_64] 	at java.lang.reflect.Method.invoke(Method.java:498)
[variation=,node=darwin-x86_64] 	at com.google.devtools.build.lib.syntax.FuncallExpression.callMethod(FuncallExpression.java:297)
[variation=,node=darwin-x86_64] 	at com.google.devtools.build.lib.syntax.DotExpression.eval(DotExpression.java:115)
[variation=,node=darwin-x86_64] 	at com.google.devtools.build.lib.syntax.DotExpression.doEval(DotExpression.java:54)
[variation=,node=darwin-x86_64] 	at com.google.devtools.build.lib.syntax.Expression.eval(Expression.java:67)
[variation=,node=darwin-x86_64] 	at com.google.devtools.build.lib.syntax.FuncallExpression.evalArguments(FuncallExpression.java:686)
[variation=,node=darwin-x86_64] 	at com.google.devtools.build.lib.syntax.FuncallExpression.callFunction(FuncallExpression.java:746)
[variation=,node=darwin-x86_64] 	at com.google.devtools.build.lib.syntax.FuncallExpression.doEval(FuncallExpression.java:719)
[variation=,node=darwin-x86_64] 	at com.google.devtools.build.lib.syntax.Expression.eval(Expression.java:67)
[variation=,node=darwin-x86_64] 	at com.google.devtools.build.lib.syntax.LValue.assignAugmented(LValue.java:177)
[variation=,node=darwin-x86_64] 	at com.google.devtools.build.lib.syntax.Eval.execAugmentedAssignment(Eval.java:57)
[variation=,node=darwin-x86_64] 	at com.google.devtools.build.lib.syntax.Eval.execDispatch(Eval.java:185)
[variation=,node=darwin-x86_64] 	at com.google.devtools.build.lib.syntax.Eval.exec(Eval.java:173)
[variation=,node=darwin-x86_64] 	at com.google.devtools.build.lib.syntax.Eval.execStatements(Eval.java:221)
[variation=,node=darwin-x86_64] 	at com.google.devtools.build.lib.syntax.Eval.execIfBranch(Eval.java:62)
[variation=,node=darwin-x86_64] 	at com.google.devtools.build.lib.syntax.Eval.execDispatch(Eval.java:188)
[variation=,node=darwin-x86_64] 	at com.google.devtools.build.lib.syntax.Eval.exec(Eval.java:173)
[variation=,node=darwin-x86_64] 	at com.google.devtools.build.lib.syntax.Eval.execIf(Eval.java:119)
[variation=,node=darwin-x86_64] 	at com.google.devtools.build.lib.syntax.Eval.execDispatch(Eval.java:204)
[variation=,node=darwin-x86_64] 	at com.google.devtools.build.lib.syntax.Eval.exec(Eval.java:173)
[variation=,node=darwin-x86_64] 	at com.google.devtools.build.lib.syntax.UserDefinedFunction.call(UserDefinedFunction.java:88)
[variation=,node=darwin-x86_64] 	at com.google.devtools.build.lib.syntax.BaseFunction.call(BaseFunction.java:430)
[variation=,node=darwin-x86_64] 	at com.google.devtools.build.lib.syntax.FuncallExpression.callFunction(FuncallExpression.java:747)
[variation=,node=darwin-x86_64] 	at com.google.devtools.build.lib.syntax.FuncallExpression.doEval(FuncallExpression.java:719)
[variation=,node=darwin-x86_64] 	at com.google.devtools.build.lib.syntax.Expression.eval(Expression.java:67)
[variation=,node=darwin-x86_64] 	at com.google.devtools.build.lib.syntax.LValue.assignAugmented(LValue.java:177)
[variation=,node=darwin-x86_64] 	at com.google.devtools.build.lib.syntax.Eval.execAugmentedAssignment(Eval.java:57)
[variation=,node=darwin-x86_64] 	at com.google.devtools.build.lib.syntax.Eval.execDispatch(Eval.java:185)
[variation=,node=darwin-x86_64] 	at com.google.devtools.build.lib.syntax.Eval.exec(Eval.java:173)
[variation=,node=darwin-x86_64] 	at com.google.devtools.build.lib.syntax.UserDefinedFunction.call(UserDefinedFunction.java:88)
[variation=,node=darwin-x86_64] 	at com.google.devtools.build.lib.syntax.BaseFunction.call(BaseFunction.java:430)
[variation=,node=darwin-x86_64] 	at com.google.devtools.build.lib.analysis.skylark.SkylarkRuleConfiguredTargetUtil.buildRule(SkylarkRuleConfiguredTargetUtil.java:92)
[variation=,node=darwin-x86_64] 	at com.google.devtools.build.lib.analysis.ConfiguredTargetFactory.createRule(ConfiguredTargetFactory.java:347)
[variation=,node=darwin-x86_64] 	at com.google.devtools.build.lib.analysis.ConfiguredTargetFactory.createConfiguredTarget(ConfiguredTargetFactory.java:233)
[variation=,node=darwin-x86_64] 	at com.google.devtools.build.lib.skyframe.SkyframeBuildView.createConfiguredTarget(SkyframeBuildView.java:500)
[variation=,node=darwin-x86_64] 	at com.google.devtools.build.lib.skyframe.ConfiguredTargetFunction.createConfiguredTarget(ConfiguredTargetFunction.java:589)
[variation=,node=darwin-x86_64] 	at com.google.devtools.build.lib.skyframe.ConfiguredTargetFunction.compute(ConfiguredTargetFunction.java:245)
[variation=,node=darwin-x86_64] 	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:340)
[variation=,node=darwin-x86_64] 	at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:352)
[variation=,node=darwin-x86_64] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[variation=,node=darwin-x86_64] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[variation=,node=darwin-x86_64] 	at java.lang.Thread.run(Thread.java:748)
[variation=,node=darwin-x86_64] 
[variation=,node=darwin-x86_64] 	at com.google.devtools.build.lib.syntax.EvalException.<init>(EvalException.java:112)
[variation=,node=darwin-x86_64] 	at com.google.devtools.build.lib.syntax.EvalException$EvalExceptionWithJavaCause.<init>(EvalException.java:209)
[variation=,node=darwin-x86_64] 	at com.google.devtools.build.lib.syntax.EvalException$EvalExceptionWithJavaCause.<init>(EvalException.java:217)
[variation=,node=darwin-x86_64] 	at com.google.devtools.build.lib.syntax.FuncallExpression.callMethod(FuncallExpression.java:330)
[variation=,node=darwin-x86_64] 	at com.google.devtools.build.lib.syntax.DotExpression.eval(DotExpression.java:115)
[variation=,node=darwin-x86_64] 	at com.google.devtools.build.lib.syntax.DotExpression.doEval(DotExpression.java:54)
[variation=,node=darwin-x86_64] 	at com.google.devtools.build.lib.syntax.Expression.eval(Expression.java:67)
[variation=,node=darwin-x86_64] 	at com.google.devtools.build.lib.syntax.FuncallExpression.evalArguments(FuncallExpression.java:686)
[variation=,node=darwin-x86_64] 	at com.google.devtools.build.lib.syntax.FuncallExpression.callFunction(FuncallExpression.java:746)
[variation=,node=darwin-x86_64] 	at com.google.devtools.build.lib.syntax.FuncallExpression.doEval(FuncallExpression.java:719)
[variation=,node=darwin-x86_64] 	at com.google.devtools.build.lib.syntax.Expression.eval(Expression.java:67)
[variation=,node=darwin-x86_64] 	at com.google.devtools.build.lib.syntax.LValue.assignAugmented(LValue.java:177)
[variation=,node=darwin-x86_64] 	at com.google.devtools.build.lib.syntax.Eval.execAugmentedAssignment(Eval.java:57)
[variation=,node=darwin-x86_64] 	at com.google.devtools.build.lib.syntax.Eval.execDispatch(Eval.java:185)
[variation=,node=darwin-x86_64] 	at com.google.devtools.build.lib.syntax.Eval.exec(Eval.java:173)
[variation=,node=darwin-x86_64] 	at com.google.devtools.build.lib.syntax.Eval.execStatements(Eval.java:221)
[variation=,node=darwin-x86_64] 	at com.google.devtools.build.lib.syntax.Eval.execIfBranch(Eval.java:62)
[variation=,node=darwin-x86_64] 	at com.google.devtools.build.lib.syntax.Eval.execDispatch(Eval.java:188)
[variation=,node=darwin-x86_64] 	at com.google.devtools.build.lib.syntax.Eval.exec(Eval.java:173)
[variation=,node=darwin-x86_64] 	at com.google.devtools.build.lib.syntax.Eval.execIf(Eval.java:119)
[variation=,node=darwin-x86_64] 	at com.google.devtools.build.lib.syntax.Eval.execDispatch(Eval.java:204)
[variation=,node=darwin-x86_64] 	at com.google.devtools.build.lib.syntax.Eval.exec(Eval.java:173)
[variation=,node=darwin-x86_64] 	at com.google.devtools.build.lib.syntax.UserDefinedFunction.call(UserDefinedFunction.java:88)
[variation=,node=darwin-x86_64] 	at com.google.devtools.build.lib.syntax.BaseFunction.call(BaseFunction.java:430)
[variation=,node=darwin-x86_64] 	at com.google.devtools.build.lib.syntax.FuncallExpression.callFunction(FuncallExpression.java:747)
[variation=,node=darwin-x86_64] 	at com.google.devtools.build.lib.syntax.FuncallExpression.doEval(FuncallExpression.java:719)
[variation=,node=darwin-x86_64] 	at com.google.devtools.build.lib.syntax.Expression.eval(Expression.java:67)
[variation=,node=darwin-x86_64] 	at com.google.devtools.build.lib.syntax.LValue.assignAugmented(LValue.java:177)
[variation=,node=darwin-x86_64] 	at com.google.devtools.build.lib.syntax.Eval.execAugmentedAssignment(Eval.java:57)
[variation=,node=darwin-x86_64] 	at com.google.devtools.build.lib.syntax.Eval.execDispatch(Eval.java:185)
[variation=,node=darwin-x86_64] 	at com.google.devtools.build.lib.syntax.Eval.exec(Eval.java:173)
[variation=,node=darwin-x86_64] 	at com.google.devtools.build.lib.syntax.UserDefinedFunction.call(UserDefinedFunction.java:88)
[variation=,node=darwin-x86_64] 	at com.google.devtools.build.lib.syntax.BaseFunction.call(BaseFunction.java:430)
[variation=,node=darwin-x86_64] 	at com.google.devtools.build.lib.analysis.skylark.SkylarkRuleConfiguredTargetUtil.buildRule(SkylarkRuleConfiguredTargetUtil.java:92)
[variation=,node=darwin-x86_64] 	at com.google.devtools.build.lib.analysis.ConfiguredTargetFactory.createRule(ConfiguredTargetFactory.java:347)
[variation=,node=darwin-x86_64] 	at com.google.devtools.build.lib.analysis.ConfiguredTargetFactory.createConfiguredTarget(ConfiguredTargetFactory.java:233)
[variation=,node=darwin-x86_64] 	at com.google.devtools.build.lib.skyframe.SkyframeBuildView.createConfiguredTarget(SkyframeBuildView.java:500)
[variation=,node=darwin-x86_64] 	at com.google.devtools.build.lib.skyframe.ConfiguredTargetFunction.createConfiguredTarget(ConfiguredTargetFunction.java:589)
[variation=,node=darwin-x86_64] 	at com.google.devtools.build.lib.skyframe.ConfiguredTargetFunction.compute(ConfiguredTargetFunction.java:245)
[variation=,node=darwin-x86_64] 	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:340)
[variation=,node=darwin-x86_64] 	... 4 more
```

**Comment by mattmoor** [comment] 2017-11-28 23:14
What's going on with this?

**Comment by laszlocsomor** [comment] 2017-11-29 08:44
@mattmoor : Do you need more information? I was going to assign this bug to someone who maintains https://github.com/bazelbuild/rules_docker but I see you are one. :)

**Comment by Capstan** [comment] 2017-11-29 13:24
I don't think this is rules_docker's fault. It was caused in-between commits to that repo, and coincided with the most recent release of bazel. If I go back to 0.7.0, it doesn't break the same way.

**Comment by Capstan** [comment] 2017-11-29 13:27
This is also not MacOS-specific.

**Comment by Capstan** [comment] 2017-11-29 22:23
Moreover I think this was one of the cherrypicks into 0.8, since I had put a travis build of a early testing release of 0.8-rc2 and it didn't have the same problem (https://github.com/bazelbuild/rules_docker/pull/214#issuecomment-343106692)

**Comment by Capstan** [comment] 2017-11-29 22:31
https://travis-ci.org/bazelbuild/rules_docker/builds/299556420 is the run against the then-testing 0.8.0 release plus my changes that succeeded.

**Comment by mattmoor** [comment] 2017-11-29 23:07
@laszlocsomor As @Capstan indicates, this is almost certainly a Bazel 0.8 bug.

If there is a workaround in `rules_docker`, I'm happy to apply it, but I don't even know where to begin parsing that monstrous stack trace.

@damienmg FYI

**Comment by davido** [comment] 2017-11-30 06:57
@mattmoor As always, try to create a minimal reproducer fot this problem.

**Comment by damienmg** [comment] 2017-11-30 07:09
@dslomov: Can you investigate and cherrypick a fix in 0.8.1? I saw the failure on the release candidate: https://ci.bazel.io/view/Bazel%20bootstrap%20and%20maintenance/job/bazel/job/release/328/Downstream_projects/

**Comment by dslomov** [comment] 2017-11-30 16:00
The problematic commit in Bazel is this 7c605cf6ea9755a06e5abb16a631faac8ebe2937, which is old but only got released in 0.8.0. I suspect something happened is rules_docker or their dependencies to trigger this. Assigning to @iirina for triage: can we make a fix that can be cherry-picked to 0.8.0?

**Comment by dslomov** [comment] 2017-11-30 16:07
the commit where this started to fail in rules_docker is https://github.com/bazelbuild/rules_docker/commit/2bfd21e83a8947a15398fe140e806ed5737aa032

**Comment by dslomov** [comment] 2017-11-30 16:08
repro is:
```bash
git clone git@github.com:bazelbuild/rules_docker.git
cd rules_docker
bazel build //...
```

**Comment by mattmoor** [comment] 2017-11-30 16:09
(shameless plug) @iirina is the reviewer on [the Groovy version of this PR](https://github.com/bazelbuild/rules_docker/pull/233), which needs love too :)

**Comment by mattmoor** [comment] 2017-11-30 21:19
Ugh, CI for `rules_docker` is just dead.  How do we avoid this in the future?  Are there Bazel CI legs that can be added to test against HEAD?

What's the timeline on a fix?  I'm guessing not the 0.9 RC since that cuts tomorrow... :(

**Comment by dslomov** [comment] 2017-11-30 21:52
We will block cutting 0.9 RC on fixing this.

**Comment by damienmg** [comment] 2017-12-01 06:40
Ftr we should do a patch release. Also we do test with head and we have the
breakage on ci too.

**Comment by dslomov** [comment] 2017-12-01 08:17
https://github.com/bazelbuild/bazel/issues/4196 (see above) tracks a potential patch release.

**Comment by damienmg** [comment] 2017-12-01 08:35
Thanks!

**Comment by iirina** [comment] 2017-12-01 10:12
Hi,

I'm working on a fix. I tried to reproduce the issue with my custom bazel but ran into another error:

```
ERROR: /home/elenairina/testnpe/rules_docker/testdata/BUILD:131:1: ImageLayer testdata/base_with_entrypoint-layer.tar failed (Exit 1)
Traceback (most recent call last):
  File "/home/elenairina/.cache/bazel/_bazel_elenairina/0c66a61696353126ad55bd3793c13ec8/bazel-sandbox/6324190021707892768/execroot/io_bazel_rules_docker/bazel-out/host/bin/container/build_tar.runfiles/io_bazel_rules_docker/container/build_tar.py", line 23, in <module>
    from third_party.py import gflags
  File "/home/elenairina/.cache/bazel/_bazel_elenairina/0c66a61696353126ad55bd3793c13ec8/bazel-sandbox/6324190021707892768/execroot/io_bazel_rules_docker/bazel-out/host/bin/container/build_tar.runfiles/bazel_tools/third_party/py/gflags/__init__.py", line 1, in <module>
    from gflags import *
  File "/home/elenairina/.cache/bazel/_bazel_elenairina/0c66a61696353126ad55bd3793c13ec8/bazel-sandbox/6324190021707892768/execroot/io_bazel_rules_docker/bazel-out/host/bin/container/build_tar.runfiles/bazel_tools/third_party/py/gflags/gflags/__init__.py", line 871, in <module>
    _helpers.SPECIAL_FLAGS)
  File "/home/elenairina/.cache/bazel/_bazel_elenairina/0c66a61696353126ad55bd3793c13ec8/bazel-sandbox/6324190021707892768/execroot/io_bazel_rules_docker/bazel-out/host/bin/container/build_tar.runfiles/bazel_tools/third_party/py/gflags/gflags/__init__.py", line 560, in DEFINE_string
    DEFINE(parser, name, default, help, flag_values, serializer, **args)
  File "/home/elenairina/.cache/bazel/_bazel_elenairina/0c66a61696353126ad55bd3793c13ec8/bazel-sandbox/6324190021707892768/execroot/io_bazel_rules_docker/bazel-out/host/bin/container/build_tar.runfiles/bazel_tools/third_party/py/gflags/gflags/__init__.py", line 392, in DEFINE
    flag_values, module_name)
  File "/home/elenairina/.cache/bazel/_bazel_elenairina/0c66a61696353126ad55bd3793c13ec8/bazel-sandbox/6324190021707892768/execroot/io_bazel_rules_docker/bazel-out/host/bin/container/build_tar.runfiles/bazel_tools/third_party/py/gflags/gflags/__init__.py", line 413, in DEFINE_flag
    fv[flag.name] = flag
  File "/home/elenairina/.cache/bazel/_bazel_elenairina/0c66a61696353126ad55bd3793c13ec8/bazel-sandbox/6324190021707892768/execroot/io_bazel_rules_docker/bazel-out/host/bin/container/build_tar.runfiles/bazel_tools/third_party/py/gflags/gflags/flagvalues.py", line 442, in __setitem__
    raise exceptions.DuplicateFlagError.from_flag(name, self)
gflags.exceptions.DuplicateFlagError: The flag 'flagfile' is defined twice. First from third_party.py.gflags.gflags, Second from third_party.py.gflags.  Description from first occurrence: Insert flag definitions from the given file into the command line.
```

Any thoughts how I can test that I fixed this with rules_docker?

**Comment by Capstan** [comment] 2017-12-01 10:40
Hm. That looks like https://github.com/gflags/python-gflags/issues/9, but like gflags self-hosed. Given this is pulling from bazel_tools (i.e., the bazel you've built), perhaps there's another issue recently introduced? (e.g., https://github.com/bazelbuild/bazel/commit/8fd0f4a038ad49f77cc2ae0c1e789df7391be467)

**Comment by Capstan** [comment] 2017-12-01 10:41
Or rather https://github.com/bazelbuild/bazel/commit/fb15f0f4e4885243d354a14997d09463594385bf#diff-3189aae2901c56b0748876200a1d7a3c

**Comment by iirina** [comment] 2017-12-01 13:24
@Capstan thanks! I reverted fb15f0f4e4885243d354a14997d09463594385bf locally before I built bazel and I managed to build `rules_docker` succesfully! Fix will land anytime now.

**Comment by Capstan** [comment] 2017-12-01 13:34
Is there something tracking the gflags weirdness yet? (is it known outside of the `rules_docker` issue?)

**Comment by iirina** [comment] 2017-12-01 13:35
Not that I know of. I will open a new bug about it now.

**Closed** 2017-12-01 13:53 UTC
Labels: breakage, P1, Release blocker, type: bug

**Comment by mattmoor** [comment] 2017-12-01 14:58
thanks for getting this resolved!
