### ISSUE TITLE
Runfiles tree is not updated correctly

### ISSUE THREAD

**Issue by buchgr** [bazelbuild/bazel#3919] opened 2017-10-18 16:04 UTC
http://ci.bazel.io/job/bazel-tests/1091/testReport/(root)/(empty)/test_cc_binary_2/

```
-- Test log: -----------------------------------------------------------
Exception in thread "main" java.lang.NoClassDefFoundError: com/google/common/collect/ListMultimap
	at com.google.devtools.build.remote.RemoteWorker.main(RemoteWorker.java:176)
Caused by: java.lang.ClassNotFoundException: com.google.common.collect.ListMultimap
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 1 more
------------------------------------------------------------------------
test_cc_binary FAILED: Timed out waiting for remote worker to start. .
/private/var/tmp/_bazel_ci/e238dab0092a26635782fe338f37014d/bazel-sandbox/8901049137663422655/execroot/io_bazel/bazel-out/darwin_x86_64-fastbuild/bin/src/test/shell/bazel/remote_execution_test.runfiles/io_bazel/src/test/shell/bazel/remote_execution_test:48: in call to set_up
```

**Comment by buchgr** [comment] 2017-10-19 16:50
We can reproduce the error on mac slave 5, by using the same output base
```
~/.bazel/latest/bin/bazel --bazelrc=/Users/ci/workspace/bazel-tests-node=darwin-x86_64/bazel.bazelrc --output_base=/private/var/tmp/_bazel_ci/e238dab0092a26635782fe338f37014d/ test //src/test/shell/bazel:remote_execution_test
```

The tests started failing with this commit: https://github.com/bazelbuild/bazel/commit/bc1cdd311da5aec80b805a4486421392cf2c999e

Looking through the output base we found that the java launcher script correctly sets up the class path to contain the new guava java (guava-23.1.jar), but the runfiles tree only contains the old guava jar (guava-21.jar). So that seems clearly like a bug in Bazel.

**Comment by buchgr** [comment] 2017-10-19 16:57
```
darwin-x86-64-5:bazel-tests ci$ ls -l /private/var/tmp/_bazel_ci/e238dab0092a26635782fe338f37014d/execroot/io_bazel/bazel-out/darwin_x86_64-fastbuild/bin/src/tools/remote_worker/remote_worker.runfiles/io_bazel/third_party/guava/
total 8
lrwxr-xr-x  1 ci  wheel  83 Sep  7 10:27 guava-21.0.jar -> /Users/ci/workspace/bazel-tests-node=darwin-x86_64/third_party/guava/guava-21.0.jar
```

./bin/src/tools/remote_worker/remote_worker
```
CLASSPATH="...:${RUNPATH}third_party/guava/guava-23.1-jre.jar:...
````

**Comment by katre** [comment] 2017-10-19 17:00
I saw that and wasn't able to reproduce it, I didn't realize it was tied to a specific worker.

The guava 21 jars have been removed, did that improve the situation, or do we need to actually clean the runfiles on that worker?

**Comment by buchgr** [comment] 2017-10-19 17:04
The problem seems to happen on every worker. The old guava files have actually not been removed as of right now [1]. (It just says in the commit message that a follow up commit will delete them :D ).

[1] https://github.com/bazelbuild/bazel/tree/master/third_party/guava

**Comment by katre** [comment] 2017-10-19 17:05
That's real bad, because I thought I pushed the change last night to do that, and I updated the GoB hash internally to match it.

**Comment by buchgr** [comment] 2017-10-19 17:07
That's great! So I probably just haven't exported it :). Either way, I will wait with the export until I can pin down the error. It's certainly a bug in Bazel.

**Comment by katre** [comment] 2017-10-19 17:07
No, it's a third-party change. Taking this to chat.

**Comment by buchgr** [comment] 2017-10-19 17:24
So I figured I would just delete the `remote_worker` output directory and re-run the test. In fact Bazel re-creates the directory and its contents, but NOT the .runfiles directory. However, the test now actually passes?!

```
darwin-x86-64-5:bazel-tests-node=darwin-x86_64 ci$ rm -rf /private/var/tmp/_bazel_ci/e238dab0092a26635782fe338f37014d/execroot/io_bazel/bazel-out/darwin_x86_64-fastbuild/bin/src/tools/
darwin-x86-64-5:bazel-tests-node=darwin-x86_64 ci$ ls -l /private/var/tmp/_bazel_ci/e238dab0092a26635782fe338f37014d/execroot/io_bazel/bazel-out/darwin_x86_64-fastbuild/bin/src/tools/remote_worker/
total 64
drwxr-xr-x  3 ci  wheel    102 Oct 19 19:16 _javac
-r-xr-xr-x  1 ci  wheel  24350 Oct 19 19:16 remote_worker
-r-xr-xr-x  1 ci  wheel    284 Oct 19 19:16 remote_worker.jar
-r-xr-xr-x  1 ci  wheel   1446 Oct 19 19:16 remote_worker.jar-2.params
-r-xr-xr-x  1 ci  wheel      0 Oct 19 19:16 remote_worker.jar_manifest_proto
drwxr-xr-x  3 ci  wheel    102 Oct 19 19:16 src
```

**Comment by buchgr** [comment] 2017-10-19 17:26
Explicitly running the `//src/tools/remote_worker:remote_worker` target then also re-creates the runfiles directory.

**Comment by buchgr** [comment] 2017-10-19 17:31
I tried switching back and forth between commits before the guava update and after the guava update and then running `//src/tools/remote_worker:remote_worker` and that actually works and correctly recreates the runfiles tree.

**Comment by buchgr** [comment] 2017-10-19 17:44
Ha! So it seems like I can reliably trigger the bug.

0) bazel clean --expunge
1) Checkout a commit that comes before `bc1cdd3`.
2) bazel test //src/test/shell/bazel:remote_execution_test <-- this will succeed
3) Checkout commit `bc1cdd3` or later.
4) bazel test //src/test/shell/bazel:remote_execution_test <-- this will fail
5) bazel run //src/tools/remote_worker:remote_worker <-- this will succeed
6) bazel test //src/test/shell/bazel:remote_execution_test <-- this will succeed

So it seems that when we depend on the `remote_worker` in a test, the runfiles tree is not correctly updated but when we build / run this target explicitly then it is.

**Comment by katre** [comment] 2017-10-19 17:46
Is remote_worker a genrule output? I have seen recently, but not reproducibly, errors where "bazel build :genrule-output" did not trigger a rebuild of the actual genrule.

**Comment by buchgr** [comment] 2017-10-19 18:16
No it's a java_binary

**Comment by buchgr** [comment] 2017-10-20 08:36
Both the runfiles tree and the runfiles manifest are not updated. The java launcher script is.

**Comment by buchgr** [comment] 2017-10-20 08:50
Just found out that Linux has the same problem, but that did not show up on our CI.

**Comment by buchgr** [comment] 2017-10-20 08:50
cc: @ulfjack

**Comment by buchgr** [comment] 2017-10-20 13:42
Another instance of this bug might be https://ci.bazel.build/job/bazel-tests/1093/testReport/com.google.devtools.build.android.dexer/DexFileSplitterTest/testSingleInputMultidexOutput/

This class was recently added too.

**Comment by benjaminp** [comment] 2017-10-23 18:10
It seems to me that the problem is that the shell wrapper for the `remote_worker` resolves the `JAVA_RUNFILES` path into the runfiles of `remote_worker` itself rather than the runfiles tree of `remote_execution_test` (which is a supserset of the former).

**Comment by benjaminp** [comment] 2017-10-27 07:28
https://bazel-review.googlesource.com/c/bazel/+/19590 is a proposed fix.

**Comment by benjaminp** [comment] 2017-11-10 02:49
I suppose we can close this now?

**Closed** 2017-11-28 13:12 UTC
Labels: category: misc > misc, P1, type: bug
