### ISSUE TITLE
bazel coverage fails with sandboxfs

### ISSUE THREAD

**Issue by Mathiasdm** [bazelbuild/bazel#12121] opened 2020-09-17 14:35 UTC
### Description of the problem / feature request:

Running 'bazel coverage' with sandboxfs results in a failure in the execution of remote_coverage_tools. We had this issue in our tests, but it occurs with a simple example as well.

Error output from our build (with irrelevant directories replaced)
```
+ [[ -n '' ]]
+ JAVA_RUNFILES=
+ exec bazel-out/buildroot-dbg/bin/external/remote_coverage_tools/Main --coverage_dir=/repo/mdemare/bazel-cache/sw/sandbox/sandboxfs/3/__main__/_coverage/<...>/test --output_file=/repo/mdemare/bazel-cache/sw/sandbox/sandboxfs/3/__main__/bazel-out/buildroot-dbg/testlogs/<...>/coverage.dat --filter_sources=/usr/bin/.+ --filter_sources=/usr/lib/.+ --filter_sources=/usr/include.+ '--filter_sources=.*external/.+' --source_file_manifest=/repo/mdemare/bazel-cache/sw/sandbox/sandboxfs/3/__main__/bazel-out/buildroot-dbg/bin/<...>.instrumented_files --sources_to_replace_file=/repo/mdemare/bazel-cache/sw/sandbox/sandboxfs/3/__main__/bazel-out/buildroot-dbg/bin/<...>/_coverage_helpers/<...>/reported_to_actual_sources.txt
/repo/mdemare/bazel-cache/sw/sandbox/sandboxfs/3/__main__/bazel-out/buildroot-dbg/bin/external/remote_coverage_tools/Main: Cannot locate runfiles directory. (Set $JAVA_RUNFILES to inhibit searching.)
```

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Environment:

- CentOS 7
- Bazel 3.5.0
- sandboxfs 0.2.0

Files in the example test:

WORKSPACE: `(empty)`
BUILD:
```
cc_test(
    name = "hello_test",
    srcs = ["test.cc"],
)
```
test.cc:
```
#include <stdio.h>

int main() {
    printf("test\n");
}
```

### What operating system are you running Bazel on?

Linux, CentOS 7

### What's the output of `bazel info release`?

release 3.5.0

###  Have you found anything relevant by searching the web?

No
### Any other information, logs, or outputs that you want to share?

If I go into the sandbox directory and check what the files are there, I see:
```
[builder@]$ ls -lh bazel-out/buildroot-dbg/bin/external/remote_coverage_tools/    
total 0
-r-xr-xr-x 1 builder builder 13K Sep 17 10:14 Main
-r-xr-xr-x 1 builder builder 329 Sep 17 14:26 Main.jar
```

If I run the same from the workspace root, I see:
```
[builder@]$ ls -lh /repo/builder/repo/bazel-out/buildroot-dbg/bin/external/remote_coverage_tools/    
total 60K
-r-xr-xr-x 1 builder builder  13K Sep 17 10:14 Main
-r-xr-xr-x 1 builder builder  284 Sep 17 14:26 Main-native-header.jar
-r-xr-xr-x 1 builder builder  329 Sep 17 14:26 Main.jar
-rw-rw-r-- 1 builder builder 1.1K Sep 17 14:26 Main.jar-0.params
-rw-rw-r-- 1 builder builder  180 Sep 17 14:26 Main.jar-1.params
-r-xr-xr-x 1 builder builder    0 Sep 17 14:26 Main.jar_manifest_proto
drwxrwxr-x 6 builder builder 4.0K Sep 17 10:14 Main.runfiles
-r-xr-xr-x 1 builder builder  21K Sep 17 10:14 Main.runfiles_manifest
```

So it looks like the runfiles are not properly added to the sandbox. When running without sandboxfs, bazel-out/buildroot-dbg/bin/external/remote_coverage_tools/Main is a symlink, which I guess is used to 'escape' the sandbox and find the other files in the same directory.

**Comment by benjaminp** [comment] 2020-09-17 15:18
This is #4033.

**Comment by Mathiasdm** [comment] 2020-09-21 04:53
Indeed. Using the changes to the coverage output generator listed [here](https://github.com/bazelbuild/bazel/issues/4685) works to get around this bug.

**Comment by susinmotion** [comment] 2020-09-22 17:00
Closing this as a duplicate of #4033.

**Closed by susinmotion** 2020-09-22 17:00 UTC
Labels: team-Local-Exec, type: bug, untriaged
