### ISSUE TITLE
Toolchain resolution in cross architecture remote execution with `no-remote-exec`

### ISSUE THREAD

**Issue by sfc-gh-mhazy** [bazelbuild/bazel#22848] opened 2024-06-21 13:30 UTC
### Description of the bug:

Hi,
I don't know if this is a bug / missing feature or if I'm doing something incorrectly. I'm seeking for advice. The scenario is a bit complex, so wanted to grab some initial feedback first, but I'm happy to create a repository with minimal repro.

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

**The setup is the following:**

1. host_platform != exec_platform (host=darwin_arm64, exec=linux_x86_64 in my case)
2. I have some test rules that must be executed locally. So I'm setting `no-remote-exec` tag for them.
3. I have toolchains that set `exec_compatible_with` and register toolchains for both platforms.

**I call bazel with** 
```
bazel test --config=remote --extra_execution_platforms=linux_x86_64
```

where linux_86_64 constraints os and cpu.

**What happens**

The local only tests fail with various exec format errors. After debugging toolchain resolution, the rules choose the toolchains that are exec_compatible_with linux_x86_64 platform.

**What I would want**

Ideally the toolchain resolution would be aware that the rule will be executed locally.  And here is where I got stuck:
1. Is there any way to make the platform definition incompatible with local execution?
2. Is there any way this can be done without modifying the rule implementations and toolchain declarations? I'm not author of some of the rules in question nor some of the toolchains. But I control platforms.

**Additional notes**

The similar scenario happens when trying to build with `--spawn_strategy=docker`. For example executing [copy_to_directory](https://github.com/aspect-build/bazel-lib/blob/main/docs/copy_to_directory.md) chooses incompatible binary due to setting [no-sandbox](https://github.com/aspect-build/bazel-lib/blob/3330c38904270c871a4f868d1e11eb9649840306/lib/private/copy_common.bzl#L13) execution requirement. 

Note: I don't want to focus too much on this particular example, as it could be fixed in the rule implementation. But it is a good candidate for testing, if one has the docker image already.

### Which operating system are you running Bazel on?

Various: darwin_arm64, darwin_amd64, linux_amd64, linux_arm64.

### What is the output of `bazel info release`?

release 6.3.2, but I'm using bazel 7.2.0 as well with same results. 

### Any other information, logs, or outputs that you want to share?

I can wrap rules as 

```
def local_only_rule(rule, name, tags = [], **kwargs):
    rule(
        name = name,
        exec_compatible_with = [
            host_cpu_constraint(),
            host_os_constraint(),
        ],
        tags = tags + ["no-remote-exec"],
        **kwargs
    )
```

and this solves the problem, but this seems to me like a hack. Additionally, it's not great if I operate on third party macros that compose multiple rules and only one of them needs to be local.

**Comment by gregestren** [comment] 2024-10-01 22:16
I think I'm missing some nuance, but why can't you just set `exec_compatible_with` directly on the tests that you tag `no-remote-exec`?

**Comment by sfc-gh-mhazy** [comment] 2024-10-03 20:38
@gregestren This is the workaround I used with the `local_only_rule` wrapper. But I don't think such workaround should be needed. IMHO, if the action runs on local platform, it should not choose toolchains for remote execution platform.

**Comment by katre** [comment] 2024-12-20 16:45
The core issue here is https://github.com/bazelbuild/bazel/issues/11432: execution strategies (like local and remote) don't interact well with execution platforms. The workaround with `local_only_rule` is the best way forward for now.

Since this is a dupe of #11432 I'm closing it, please follow that issue (but know that I'm not sure we have availability to tackle this soon).

**Closed by katre** 2024-12-20 16:45 UTC
Labels: type: bug, team-Configurability, untriaged
