### ISSUE TITLE
Share bazel's cache between differing platforms

### ISSUE THREAD

**Issue by matts1** [bazelbuild/bazel#19965] opened 2023-10-27 08:24 UTC
### Description of the feature request:

I talked to the bazel team yesterday, and he said that apparently bazel is unable to cache anything between platforms, even if they're completely independent of the platform.

In our case (ChromeOS), we have many different platforms (>200) that each differ in small ways (eg. one might have a fingerprint sensor while another might not). The constraint setting for fingerprint sensor is one that very few things will actually depend on.

This cannot be done with regular flags, since we anticipate a need for something like `cc_test(name = "fingerprint_integration_tests", exec_compatible_with = ["//constraints:fingerprint_sensor"])`

### What underlying problem are you trying to solve with this feature?

If I were to execute an action on two platforms which differ in a single contsraint, and that action was independent of that constraint, at the moment, it would be unable to be cached.

So if I had an action, for example, that executed a shell script to generate some text file, that action should have nothing to do with the processor architecture.

I'm not sure if this applies to transitions as well, but if they're not already, it would be very useful to share a cache between transitions.

### Which operating system are you running Bazel on?

linux

### What is the output of `bazel info release`?

6,2,0

**Comment by fmeum** [comment] 2023-10-27 08:44
> This cannot be done with regular flags, since we anticipate a need for something like cc_test(name = "fingerprint_integration_tests", exec_compatible_with = ["//constraints:fingerprint_sensor"])

You should be able to select between an empty list of constraints and one containing `@platforms//: incompatible` based on a regular flag.

**Comment by matts1** [comment] 2023-10-27 10:25
Oh, that's a good point. This is still quite relevant for other things though (eg. architecture-independent actions)

**Comment by gregestren** [comment] 2023-11-03 19:59
Hi @matts1 .

I can't tell if you're referring to execution platforms or target platforms or both.

I imagine by 200+ platforms you're referring to target platforms, where built binaries run?

If you're concerned about a shell action running on an execution platform, as I'm reading, there's a good chance that will cache. More severe execution platform differences like Mac vs. Linux are unlikely to cache since they'll have different compilers, paths, etc. But "mostly unimportant" platform differences i think wouldn't trigger that.

Doubly so if the shell action is its own target that doesn't fork `exec_compatible_with`.

Switching *target* platforms by setting `--platforms` differently absolutely breaks caching. This is what path mapping as described by @fmeum , @aranguyen , and I addresses.

**Comment by fmeum** [comment] 2024-05-26 14:43
@matts1 This looks like a duplicate of #6526. Is there any aspect that's import to you and not covered by that issue?

**Comment by matts1** [comment] 2024-05-26 14:51
I believe it should be pretty much covered. At the moment our bazel builds aren't yet configured for multiple target platforms, so let's just mark this as a duplicate and I can file any more specific issues if / when they find up.

**Closed** 2024-05-26 14:51 UTC
Labels: type: feature request, P3, team-Configurability
