### ISSUE TITLE
Make variables defined using `--define` accessible in macros

### ISSUE THREAD

**Issue by shs96c** [bazelbuild/bazel#9458] opened 2019-10-01 13:33 UTC
### Description of the problem / feature request:

Bazel provides the ability to define variables on the command line using the `--define` flag. However, within a macro there's no way to access these variables. which makes using them without defining an entire rule impossible.

### Feature requests: what underlying problem are you trying to solve with this feature?

Consider a project that wants to publish artifacts to a user-configurable location. The general publishing may be encapsulated with a binary, and then exposed like so in a macro:

```py
native.java_binary(
  name = "%s-publish" % name,
  main_class = "com.example.Publisher",
  args = [
    "$(location :%s)" % name,
    "publish_to=$(define publish_target)",
  ],
  runtime_deps = [
    "@//path/to:publisher",
  ],
)
```

And then called like so: `bazel run //my:rule-publish --define publish_target=https://repo` or `bazel run //my:rule-publish --define publish_target=file:///$HOME/.m2/repository`

### Any other information, logs, or outputs that you want to share?

This would allow us to replace a custom publishing rule with a simple java_binary in the selenium project. This is required, since Windows users can't run the bash script that our current custom rule generates.

**Comment by gregestren** [comment] 2019-10-02 09:47
Can you just pass your arg directly to the java_binary (and update the binary to expect that arg at the command line)?

`$ bazel run //my:rule-publish --publish_target=https://repo`

(also see [here](https://docs.bazel.build/versions/0.29.1/user-manual.html#run)).

About your general question, macros by definition can't read args like `--define` because macros are evaluated in the loading phase, before flags are parsed.  More details [here](https://docs.bazel.build/versions/master/configurable-attributes.html#why-doesnt-select-work-in-macros)  (it's about `select` but it's the same thing).

**Comment by gregestren** [comment] 2019-10-02 09:47
I'm going to close this as infeasible. Feel free to re-open if you still see worthwhile work here.

**Closed by gregestren** 2019-10-02 09:47 UTC
Labels: P2, team-Configurability, type: feature request

**Comment by shs96c** [comment] 2019-10-02 12:32
I think `$(define var)` would work, no? It must be like `$(location)` where the output path can very definitely be modified by flags from the user (using `--symlink_prefix`).

We use the variables defined using `--define` to pass through security credentials when pushing releases in Selenium. Hard-coding those into build files seems like an unwise move.

**Comment by gregestren** [comment] 2019-10-02 13:28
I meant, can you make the java binary expect a command line parameter called `publish_target`, then pass its value at the command line in the form I suggested above? That should be equivalent to what you're suggesting.

**Comment by errangutan** [comment] 2020-04-12 13:21
@shs96c Your post suggests there is a way to access the ```--define```s  from within a rule implementation function, is that correct? I'm creating a rule set for some tool, but can't figure out how to pass the defines to the tool. I'm interested in specifically using the native Bazel ```--define``` flag.

I would really appreciate your help, thanks.

**Comment by gregestren** [comment] 2020-04-13 22:33
@errangutan you could also try a custom-defined flag (which is equivalent to `--define` but gives you more control over how it works). See https://github.com/gregestren/snippets/tree/master/read_custom_flag_in_starlark_rule for a simple example.

**Comment by errangutan** [comment] 2020-04-13 23:01
Hey Greg,
The problem is I have multiple targets, each of which can set their own set
of defines, and any rule they depend on couldn't know which set of configs
to depend on.
