### ISSUE TITLE
[bazel.build] Problem with /install/redhat

### ISSUE THREAD

**Issue by Tre2878** [bazelbuild/bazel#18877] opened 2023-07-10 09:51 UTC
### Page link:

https://bazel.build/install/redhat

### Problem description (include actual vs expected text, if applicable):

There is no description of bazel5 and bazel6 installed on centos7

**Comment by sgowroji** [comment] 2023-07-11 04:49
Duplicate of https://github.com/bazelbuild/bazel/issues/18550

**Closed** 2023-07-13 09:53 UTC
Labels: type: documentation (cleanup), untriaged, duplicate, team-Documentation
