### ISSUE TITLE
Aliases don't correctly destination targets that contain a /

### ISSUE THREAD

**Issue by achew22** [bazelbuild/bazel#4205] opened 2017-12-01 07:17 UTC
Aliases don't correctly destination targets that contain a /

### If possible, provide a minimal example to reproduce the problem:

```
sh_test(
  name = "demo/foryou",
  srcs = ["test.sh"],
)

alias(
  name = "test",
  actual = ":demo/foryou",
)
```

```
$ bazel test :test
...
ERROR: missing input file :demo/foryou'
...
```

### Environment info
* Operating System: Linux
* Bazel version (output of `bazel info release`): release 0.8.0

###  Have you found anything relevant by searching the web?
Nope

**Comment by iirina** [comment] 2017-12-04 15:25
I tried to reproduce but did not get the same error. When I run `bazel test :test` I get `ERROR: No test targets were found, yet testing was requested`, because `alias` is not a test rule. If I run `bazel run :test` everything works fine. Can you add more details about your setup?

**Comment by benjaminp** [comment] 2020-03-04 02:09
Probably at most this is a duplicate of #10856 10893.

**Comment by meisterT** [comment] 2020-05-18 20:35
Closing as duplicate.

**Closed by meisterT** 2020-05-18 20:35 UTC
Labels: P3, more data needed, team-XProduct, type: bug
