### ISSUE TITLE
//src/test/shell/bazel:bazel_bootstrap_distfile_test fails on Windows

### ISSUE THREAD

**Issue by meteorcloudy** [bazelbuild/bazel#3129] opened 2017-06-06 07:56 UTC
http://ci.bazel.io/job/bazel-tests/BAZEL_VERSION=HEAD,PLATFORM_NAME=windows-x86_64/801/console

```
Build successful! Binary is here: /c/temp/32ae0615895d663f1d36ea71ec70930b/bazelbootstrap.HuQ4umhi/output/bazel.exe
INFO: $TEST_TMPDIR defined: output root default is 'c:/temp/32ae0615895d663f1d36ea71ec70930b'.
Extracting Bazel installation...
.....................................................................
Build label: 0.5.0- (@non-git)
Build target: bazel-out/msys_x64-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Mon Jun 5 18:19:30 2017 (1496686770)
Build timestamp: 1496686770
Build timestamp as int: 1496686770
INFO: $TEST_TMPDIR defined: output root default is 'c:/temp/32ae0615895d663f1d36ea71ec70930b'.
PASSED: test_bootstrap

** 1 / 1 tests passed. *********************************************************
rm: cannot remove 'C:/temp/32ae0615895d663f1d36ea71ec70930b/root/install/306f63951bd63e02ba66b3eb093fd19a/_embedded_binaries/A-server.jar': Device or resource busy
-- Test log: -----------------------------------------------------------
INFO: Reading 'startup' options from c:/temp/32ae0615895d663f1d36ea71ec70930b/bazelrc: --output_user_root=c:/temp/32ae0615895d663f1d36ea71ec70930b/root --host_javabase=C:/bazel_ci/temp/_bazel_system/vzgwz1gf/external/local_jdk
INFO: $TEST_TMPDIR defined: output root default is 'c:/temp/32ae0615895d663f1d36ea71ec70930b'.
...............................................................
____Starting clean (this may take a while). Consider using --async if the clean takes more than several minutes.
------------------------------------------------------------------------
test_bootstrap FAILED: terminated because this command returned a non-zero status:
/c/jenkins/workspace/bazel-tests/bazel_version/head/platform_name/windows-x86_64/src/test/shell/testenv.sh:432: in call to cleanup
```

The actual bootstrap succeeded, but the test failed during cleanup.

**Comment by laszlocsomor** [comment] 2017-06-06 08:36
Duplicate of https://github.com/bazelbuild/bazel/issues/2326

**Comment by laszlocsomor** [comment] 2017-06-06 08:37
I've working on a fix for this since last week.

**Closed by laszlocsomor** 2017-06-06 08:36 UTC
Labels: category: multi-platform > windows, P1, type: bug
