### ISSUE TITLE
Custom --repository_cache directory not being used for some initial downloads

### ISSUE THREAD

**Issue by gmishkin** [bazelbuild/bazel#7710] opened 2019-03-13 16:07 UTC
### Description of the problem / feature request:

I've tried setting `--repository_cache` to a custom location in the workspace `.bazelrc` as well as a global one that I pass as a startup option. It does seem to be used for downloads that are specific to the workspace, but not for some things that are related to startup perhaps.

The reason I think this is because even though my custom path is getting populated with cached things, I see messages like this in the build output as well. It's not that I care that there's a slow read but that it's using the wrong path.

> `Slow read: a 73289132-byte read from /root/.cache/bazel/_bazel_root/6b79dcc852364003d676ef7deafa6f2f/external/local_jdk/jre/lib/rt.jar took 10218 ms.`

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

```
echo 'build --repository_cache=/path/to/cache' > /path/to/bazelrc
bazel --bazelrc=/path/to/bazelrc build [something with JVM]
```

Unfortunately it doesn't happen every time because sometimes the read is fast enough, I guess. If you can tell me a way to report the repository cache location it thinks it's using in all cases, I can try to reproduce that way.

### What operating system are you running Bazel on?

Linux

### What's the output of `bazel info release`?

`release 0.23.0`

###  Have you found anything relevant by searching the web?

Searched for `repository_cache` and different ways to set bazelrc but nothing related to this issue.

**Comment by dslomov** [comment] 2019-03-21 12:09
So the `--repository_cache` is only used for things that are downloaded. It not used for local files, such as `rt.jar` from your local JDK (it makes no sense do do that since both are disk reads). What is the problem you are trying to solve?

**Comment by gmishkin** [comment] 2019-03-21 13:31
Just saw there were files in /root even though I was trying to put the cache elsewhere; the way our CI system is set up we’re not really supposed to put stuff there, it’s on a partition that doesn’t have a lot of free space, etc.

**Comment by aehlig** [comment] 2019-03-21 14:28
See [Bazel's documentation of the directory structure](https://docs.bazel.build/versions/master/output_directories.html); maybe you're trying to set `--output_user_root`?

Closing as working as intended; Please reopen with more details, if the linked documentation does not explain the behavior you've seen.

**Closed by aehlig** 2019-03-21 14:28 UTC
Labels: team-ExternalDeps
