### ISSUE TITLE
Regression: Bzlmod failing to pick up some aspect of transitive dependencies

### ISSUE THREAD

**Issue by cpsauer** [bazelbuild/bazel#20537] opened 2023-12-14 03:36 UTC
### Description of the bug:

Hi wonderful Bazelers,

I was helping out with some maintenance for [google/google-toolbox-for-mac](https://github.com/google/google-toolbox-for-mac) and noticed some odd behavior in 7.0.0 and the latest rolling (8.0.0-pre.20231030.2). Everything works as I'd expect in 6.4.0.

In particular, builds were failing to pick up Apple CC toolchains unless a transitive dependency was specified at the top level.

In more detail:
HEAD started failing with
```
ERROR: /Users/cs/Developer/google-toolbox-for-mac/BUILD:4:13: in objc_library rule //:Defines: 
Traceback (most recent call last):
        File "/virtual_builtins_bzl/common/objc/objc_library.bzl", line 61, column 52, in _objc_library_impl
        File "/virtual_builtins_bzl/common/objc/semantics.bzl", line 54, column 13, in _check_toolchain_supports_objc_compile
Error in fail: Compiling objc_library targets requires the Apple CC toolchain which can be found here: https://github.com/bazelbuild/apple_support#toolchain-setup
```

Module.bazel brings in (only) rules_apple, which should be sufficient (and was previously in 6.4.0).
`bazel_dep(name = "rules_apple", version = "3.1.1", repo_name = "build_bazel_rules_apple")`

rules_apple already depends transitively on apple_support 1.11.1, but adding in an explicit dependency mysteriously fixes the issue
`bazel_dep(name = "apple_support", version = "1.11.1", repo_name = "build_bazel_apple_support")`

Strange, right?

Thanks again for all you do,
Chris

### Which category does this issue belong to?

bzlmod

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Try building [google/google-toolbox-for-mac](https://github.com/google/google-toolbox-for-mac) w/ 7.0.0 or the latest rolling (8.0.0-pre.20231030.2). Note error as above. Then add superfluous `bazel_dep(name = "apple_support", version = "1.11.1", repo_name = "build_bazel_apple_support")` to MODULE.bazel and note that error resolves.

You may also have to remove `includes = ["."],` from `//BUILD`, depending on the Bazel version.

### Which operating system are you running Bazel on?

macOS

### Is this a regression? If yes, please try to identify the Bazel commit where the bug was introduced.

It says: first bad commit is https://github.com/bazelbuild/bazel/commit/ffcf0fdc9a09ec240df39f1db35511e730366a31

But this was from a Bazel crash, like the following, of which there were significant numbers in intermediate commits.
```
FATAL: bazel crashed due to an internal error. Printing stack trace:
java.lang.RuntimeException: Unrecoverable error while evaluating node 'com.google.devtools.build.lib.bazel.bzlmod.BazelLockFileValue$$Lambda$219/0x00000009002a0c40@12948f4a' (requested by nodes 'com.google.devtools.build.lib.bazel.bzlmod.BazelDepGraphValue$$Lambda$346/0x00000009004d8040@62c3027d')
        at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:633)
        at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:365)
        at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinPool.scan(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
Caused by: java.lang.IllegalArgumentException: com.google.devtools.build.lib.cmdline.LabelSyntaxException: invalid label 'rules_apple~3.1.1': absolute label must begin with '@' or '//'
        at com.google.devtools.build.lib.cmdline.Label.parseCanonicalUnchecked(Label.java:136)
        at com.google.devtools.build.lib.bazel.bzlmod.AttributeValuesAdapter.deserializeStringToObject(AttributeValuesAdapter.java:154)
        at com.google.devtools.build.lib.bazel.bzlmod.AttributeValuesAdapter.deserializeObject(AttributeValuesAdapter.java:105)
        at com.google.devtools.build.lib.bazel.bzlmod.AttributeValuesAdapter.read(AttributeValuesAdapter.java:56)
        at com.google.devtools.build.lib.bazel.bzlmod.AttributeValuesAdapter.read(AttributeValuesAdapter.java:40)
        at com.google.devtools.build.lib.bazel.bzlmod.RepoSpec_GsonTypeAdapter.read(RepoSpec_GsonTypeAdapter.java:105)
        at com.google.devtools.build.lib.bazel.bzlmod.RepoSpec_GsonTypeAdapter.read(RepoSpec_GsonTypeAdapter.java:11)
        at com.google.devtools.build.lib.bazel.bzlmod.Module_GsonTypeAdapter.read(Module_GsonTypeAdapter.java:226)
        at com.google.devtools.build.lib.bazel.bzlmod.Module_GsonTypeAdapter.read(Module_GsonTypeAdapter.java:14)
        at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41)
        at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:187)
        at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:145)
        at com.google.devtools.build.lib.bazel.bzlmod.DelegateTypeAdapterFactory$1.read(DelegateTypeAdapterFactory.java:133)
        at com.google.devtools.build.lib.bazel.bzlmod.BazelLockFileValue_GsonTypeAdapter.read(BazelLockFileValue_GsonTypeAdapter.java:159)
        at com.google.devtools.build.lib.bazel.bzlmod.BazelLockFileValue_GsonTypeAdapter.read(BazelLockFileValue_GsonTypeAdapter.java:13)
        at com.google.gson.Gson.fromJson(Gson.java:932)
        at com.google.gson.Gson.fromJson(Gson.java:897)
        at com.google.gson.Gson.fromJson(Gson.java:846)
        at com.google.gson.Gson.fromJson(Gson.java:817)
        at com.google.devtools.build.lib.bazel.bzlmod.BazelLockFileFunction.getLockfileValue(BazelLockFileFunction.java:101)
        at com.google.devtools.build.lib.bazel.bzlmod.BazelLockFileFunction.compute(BazelLockFileFunction.java:79)
        at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:562)
        ... 7 more
Caused by: com.google.devtools.build.lib.cmdline.LabelSyntaxException: invalid label 'rules_apple~3.1.1': absolute label must begin with '@' or '//'
        at com.google.devtools.build.lib.cmdline.LabelParser.syntaxErrorf(LabelParser.java:208)
        at com.google.devtools.build.lib.cmdline.LabelParser$Parts.checkPkgIsAbsolute(LabelParser.java:194)
        at com.google.devtools.build.lib.cmdline.Label.parseCanonical(Label.java:125)
        at com.google.devtools.build.lib.cmdline.Label.parseCanonicalUnchecked(Label.java:134)
        ... 28 more
```

**Comment by Wyverald** [comment] 2023-12-14 17:09
This might be due to cc rules enabling toolchain resolution in 7.0. I can try to confirm that in a bit, but if so, this is indeed WAI.

**Comment by Wyverald** [comment] 2023-12-14 21:46
So it was not that; my bisect points to https://github.com/bazelbuild/bazel/commit/d56dc18e1978102e35fbcf92c5d63f9f9eef37cd, which indeed looks like the culprit.

cc @keith to confirm, but it looks like this is an intentional change.

**Comment by keith** [comment] 2023-12-14 21:49
It's intentional that the toolchain was moved out and that it's required to use the apple_support toolchain to build objc, but if that's being registered but fighting against the builtin toolchain that might be what fabian is referring to. we just had another issue where someone was registering the default toolchain first, and therefore that was taking precedence

**Comment by Wyverald** [comment] 2023-12-14 22:27
I feel like we've had this discussion somewhere else, so apologies if I'm just rehashing arguments. But is the current state desirable? `apple_support`'s [README page](https://github.com/bazelbuild/apple_support?tab=readme-ov-file#incompatible-toolchain-resolution) says this:

> NOTE: If you're using bzlmod and depend on both `apple_support` and `rules_cc` in your MODULE.bazel, `apple_support`'s `bazel_dep` must come before `rules_cc` in order to take precedence over the default CC toolchains.

In the case of this issue, the root MODULE.bazel has no dependency on either `apple_support` or `rules_cc`. However, `bazel_tools` itself depends on both of them, but `apple_support` comes last, way after `rules_cc` (see [MODULE.tools](https://cs.opensource.google/bazel/bazel/+/master:src/MODULE.tools;drc=674265ae920fed6ec6da201d7db5fcec5942079d)). Should we move `apple_support` to the beginning or something?

cc @meteorcloudy @comius

**Comment by keith** [comment] 2023-12-15 18:06
My hope is that we can drop the apple_support dependency from bazel entirely. The only reason it's there I'm hoping we can eliminate https://github.com/bazelbuild/bazel/pull/20084/

**Comment by cpsauer** [comment] 2023-12-16 07:19
^ But we'd still want to try for rules_apple leading to the toolchain taking preference over the default, right?

**Comment by keith** [comment] 2023-12-16 15:20
The problem is currently the Apple toolchain requires Xcode. So in the case you want to only use the command line tools to only build C++ you have to use the unix toolchain

**Comment by cpsauer** [comment] 2023-12-16 20:38
That I got--but do we expect people to want to use the unix toolchain if also using rules_apple? (And if so, do we want that to be the default behavior when Xcode is installed.)

**Comment by keith** [comment] 2023-12-18 17:34
One of the cases filed last week was that the user had rules_apple registered via a transitive dependency (grpc) but they didn't actually want to require Xcode, so in their case yes. Also if you have a multi-platform repo you might want that toolchain to at least exist for Linux builds (when not building your Apple targets)

**Comment by keith** [comment] 2023-12-18 20:29
actually looks to me like even with my change apple_support is already coming through bazel's bzlmod deps, so I guess we won't be able to rely on it being removed ever

**Comment by Wyverald** [comment] 2023-12-18 20:32
> actually looks to me like even with my change apple_support is already coming through bazel's bzlmod deps, so I guess we won't be able to rely on it being removed ever

Sorry, what do you mean by "coming through bazel's bzlmod deps"? I was under the impression that we can remove `apple_support` from `bazel_tools` once `objc_library` is moved out of Bazel.

**Comment by keith** [comment] 2023-12-18 20:35
If you run `bazel mod graph` you can see apple_support is depended on by other dependencies, so I think the general issue of the toolchain being registered by _something_ by default, but maybe not in the order we want is going to continue to be an issue? Which I think means we have to find some way to differentiate the toolchains so that the apple_support toolchain is correctly picked up in the cases where it is required?

**Comment by keith** [comment] 2023-12-18 20:37
Specifically from `rules_graalvm`. So while we can remove the direct dependency I think this issue will still exist? And the other issue where the user wanted the opposite behavior of defaulting to the C++ toolchain instead of the apple_support toolchain 🙃

**Comment by Wyverald** [comment] 2023-12-18 20:44
I see. I admit I still don't quite understand the nuance here, but it sounds like having the default unix C++ toolchain and the Apple-specific one share the same toolchain type is causing some issues? I'm guessing it's not so easy (or just conceptually wrong) to split the toolchain type or something.

At the end of the day, the user _is_ able to control the toolchain registration order by adding/reordering some things in their MODULE.bazel file, although this is bordering on magic again. Do you see a more user-friendly resolution? Or alternatively, what would be the ideal UX, present status quo aside?

**Comment by keith** [comment] 2023-12-18 20:49
Yea I guess saying "you have to add this dependency directly" isn't the worst thing in the world, but it's a bit weird given they never explicitly reference anything from the dependency, and they're pulling it in transitively themselves (as well as through bazel_tools), while they're not pulling in rules_cc at all (except through bazel_tools).

I think this example would be solved by https://github.com/bazelbuild/bazel/issues/11454, the problem is that macOS target constraints are matched by both toolchains, even though apple_support's would be a "better" match since there are some apple specific constraints in there. Maybe it's possible without this change we could introduce some new arbitrary requirement that would make sure it used the apple_support toolchain?

**Comment by Wyverald** [comment] 2023-12-18 20:57
cc @katre 

Just to confirm, this is not a new behavior that came with Bzlmod, right? If we have to rely on toolchain registration order, then the same problem should have been present in WORKSPACE.

**Comment by keith** [comment] 2023-12-18 21:02
yes, but i think that was less likely because previously everyone was enumerating their transitives so they would have ended up with a call to something from apple_support which registered the toolchain as well

**Comment by katre** [comment] 2023-12-18 21:11
As @keith said, this isn't new, but it's exposed by bzlmod. Would adding a more explicit priority for toolchain registration help this any?

**Comment by fmeum** [comment] 2023-12-18 21:13
Either toolchain can be "the right one" in different situations. I think we should rather have a knob like `--java_runtime_version` than numeric priorities.

**Comment by keith** [comment] 2023-12-18 21:17
The more I think about it the weirder this case is related to https://github.com/bazelbuild/bazel/issues/11454

The target platform is defined by these constraints https://github.com/bazelbuild/apple_support/blob/cf5b18dc2a2b8aba5e0470a5fe5208ad8f8a8149/configs/platforms.bzl#L4-L9

The default CC toolchain takes the host constraints and therefore just has:

```
        "@platforms//os:macos",
        "@platforms//cpu:arm64",
```

but is still preferred over the apple_support toolchain which satisfies all 4. I guess this means we couldn't just add another arbitrary constraint to disambiguate because we already have

**Comment by katre** [comment] 2023-12-18 21:20
Hmm, in that case the proposed "best match" would make sense. Anyone have time to mock that up and see how it works?

**Comment by keith** [comment] 2023-12-18 22:04
Here's a quick example that would fix it https://github.com/bazelbuild/bazel/pull/20596 _if_ I also removed the default values from our custom constraints: https://github.com/bazelbuild/apple_support/blob/cf5b18dc2a2b8aba5e0470a5fe5208ad8f8a8149/constraints/BUILD#L37

But I realized while doing this that this might be too aggressive, as with this change now cc_binary targets would default to the builtin toolchain and not the one from apple_support, which would also be wrong.

**Comment by keith** [comment] 2023-12-18 22:10
I'm back to "first registered toolchain wins" being fine

**Comment by Wyverald** [comment] 2023-12-19 21:08
OK, unless there's something actionable here, I'm going to close this as WAI. If anyone has suggestions to improve the situation, please shout.

**Closed by Wyverald** 2023-12-19 21:08 UTC
Labels: type: bug, P2, team-ExternalDeps, area-Bzlmod

**Comment by cpsauer** [comment] 2023-12-20 01:08
Hmm, still does seem like a bummer to export this to the user interface. Same as Keith said in https://github.com/bazelbuild/bazel/issues/20537#issuecomment-1861605914. Let me think...

Might one actionable possibility be having user-specified toolchains (transitive included) take precedence over implicitly pulled-in ones? That's one source of surprise, here and generally, I think.

More directly, I feel like the user desire would be something like: If Xcode available, use it when building for Apple platforms, and otherwise fall back. I agree that's not particularly a general graph operation--it's conditional on Xcode availability--but maybe it's doable automatically if we indeed don't think apple_support will be pulled out. (I'm sure you all know better how this case is currently handled.)

**Comment by keith** [comment] 2023-12-22 18:52
Here's another case of this which feels worse because the implication is all rules_rust and rules_go users would have to manually specify their apple_support dependency to get the toolchain registered  https://github.com/bazelbuild/bazel/issues/20638
