### ISSUE TITLE
CI failure: //src/test/shell/bazel/android:android_integration_test is failing

### ISSUE THREAD

**Issue by meteorcloudy** [bazelbuild/bazel#2465] opened 2017-02-01 11:17 UTC
http://ci.bazel.io/job/bazel-tests/BAZEL_VERSION=latest,PLATFORM_NAME=ubuntu_15.10-x86_64/530/console

Tutorials is failing probably due to the same reason.
```
** test_android_sdk_repository_build_tools_version_detection *******************
INFO: Reading 'startup' options from /home/ci/.cache/bazel/_bazel_ci/4131105e3d289c33347e080a29411dfe/bazel-sandbox/a3d72aab-d53f-4991-a820-f20cda91240d-146/execroot/ubuntu_15.10-x86_64/_tmp/android_integration_test_1/bazelrc: --output_user_root=/home/ci/.cache/bazel/_bazel_ci/4131105e3d289c33347e080a29411dfe/bazel-sandbox/a3d72aab-d53f-4991-a820-f20cda91240d-146/execroot/ubuntu_15.10-x86_64/_tmp/android_integration_test_1/root --host_javabase=/home/ci/.cache/bazel/_bazel_ci/4131105e3d289c33347e080a29411dfe/bazel-sandbox/a3d72aab-d53f-4991-a820-f20cda91240d-146/execroot/ubuntu_15.10-x86_64/bazel-out/local-fastbuild/bin/src/test/shell/bazel/android/android_integration_test.runfiles/local_jdk
INFO: $TEST_TMPDIR defined: output root default is '/home/ci/.cache/bazel/_bazel_ci/4131105e3d289c33347e080a29411dfe/bazel-sandbox/a3d72aab-d53f-4991-a820-f20cda91240d-146/execroot/ubuntu_15.10-x86_64/_tmp/android_integration_test_1'.
...................................................
ERROR: no such package '@androidsdk//': com.google.devtools.build.lib.skyframe.InconsistentFilesystemException: Inconsistent filesystem operations. /home/ci/.cache/bazel/_bazel_ci/4131105e3d289c33347e080a29411dfe/bazel-sandbox/a3d72aab-d53f-4991-a820-f20cda91240d-146/execroot/ubuntu_15.10-x86_64/_tmp/android_integration_test_1/workspace.YD5FuTqU/androidsdk/system-images is no longer an existing directory. Did you delete it during the build? The results of the build are not guaranteed to be correct. You should probably run 'blaze clean' and investigate the filesystem inconsistency (likely due to filesytem updates concurrent with the build).
```

I suspect https://github.com/bazelbuild/bazel/commit/06072c557290b97cb2d2e4fd255b647a9208cb5c, trying to confirm it.

**Comment by meteorcloudy** [comment] 2017-02-01 11:42
//cc @aj-michael Do you think it's your change that caused this? I couldn't reproduce this on my Linux workstation...

**Comment by meteorcloudy** [comment] 2017-02-01 13:13
OK, it's confirmed here : http://ci.bazel.io/job/Gerrit-bazel-tests/347/
by https://bazel-review.googlesource.com/#/c/8571/

I'm gonna rollback it

**Comment by aj-michael** [comment] 2017-02-01 14:33
Yikes, I'm sorry about this. Were you able to reproduce this on your Linux workstation? These tests were definitely passing on my workstation yesterday

**Comment by aj-michael** [comment] 2017-02-01 17:07
Ah ok, I can repro locally and am preparing a fix and rollforward. This has also identified a bug in android_integration_test.sh where the android sdk that is set up is being persisted between test runs.

**Comment by aj-michael** [comment] 2017-02-01 17:07
Closing the issue since the rollback was committed.

**Closed by aj-michael** 2017-02-01 17:07 UTC
Labels: breakage, category: rules > android, P1, type: bug
