### ISSUE TITLE
android_library aar target does not include jni so files

### ISSUE THREAD

**Issue by lilac** [bazelbuild/bazel#1547] opened 2016-07-22 01:18 UTC
Bazel version: 0.2.3
1. Add an android_library rule
2. Make the rule depends on a cc_library, which wraps a cc_binary that outputs a so file.
3. Build the aar target, but the aar does not include the dependent so files.

If I change the `android_library` to `android_binary`, then the generated apk contains the so file without any problem.

**Comment by ahumesky** [comment] 2016-07-22 16:30
This is because, currently, the aar output of android_library contains the output of only that target, not the transitive closure:
http://www.bazel.io/docs/be/android.html#android_library_implicit_outputs
Additionally, if you had an android_library A depend on an android_library B, the aar of A will not contain anything from B. We'd like to make it possible to output the transitive closure for the aars, but there are resource processing issues, and we won't likely get to it for a while.

**Comment by lilac** [comment] 2016-07-26 14:11
@ahumesky Thanks for the explanation. Is there any workarounds for it at the moment?

**Comment by ahumesky** [comment] 2016-07-26 19:08
You might be able to get pretty far by wrapping the android_library in an android_binary rule, then using the _deploy.jar implicit output of android_binary to get the classes.jar, and extracting the native libs and resources and assets from the apk, and putting that together in a genrule or a skylark rule. The tricky part is getting R.txt and the AndroidManifest, because those are not implicit outputs of andorid_binary. R.txt is an implicit output of android_library, but I don't think it's going to include transitive dependencies. You might have to write a wrapper script that will take the right things out of bazel-bin and assemble the aar.

**Comment by aj-michael** [comment] 2017-03-17 14:48
This is a duplicate of #348.

**Closed by aj-michael** 2017-03-17 14:48 UTC
Labels: category: rules > android, P2, type: feature request
