### ISSUE TITLE
Bazel is slow to exit after a build

### ISSUE THREAD

**Issue by endobson** [bazelbuild/bazel#1174] opened 2016-04-22 04:57 UTC
I am seeing bazel take half a second to a second to exit after it completes a build.

```
endobson@yggdrasil () ~/proj/racket/yaspl2 % time bazel build //libraries:thread-example
INFO: Found 1 target...
Target //libraries:thread-example up-to-date:
  bazel-bin/libraries/thread-example.s
  bazel-bin/libraries/thread-example.o
  bazel-bin/libraries/thread-example
INFO: Elapsed time: 0.105s, Critical Path: 0.00s
bazel build //libraries:thread-example  0.01s user 0.01s system 2% cpu 0.909 total
```

So bazel thinks the entire build took .1 seconds but the process took .9 seconds according to time.

OS: OS X
Bazel version:
Build label: 0.2.0-2016-03-30 (@a64b119)
Build target: bazel-out/local_darwin-fastbuild/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Wed Mar 30 07:12:11 2016 (1459321931)
Build timestamp: 1459321931
Build timestamp as int: 1459321931

**Comment by damienmg** [comment] 2016-04-22 10:03
Yes there is a bit of problems for darwin: we don't have a correct file watching system yet (see #1074) and we have to wait for the file system granularity, see https://bazel-review.googlesource.com/#/c/3421/2

**Comment by damienmg** [comment] 2016-05-30 11:32
The actual solution is a bit longer. Won't be done by 0.3

**Comment by philwo** [comment] 2016-12-09 14:39
@ulfjack @damienmg Any suggestion who I could assign this to? Or did we fix this in the meantime?

**Comment by ulfjack** [comment] 2016-12-09 14:52
If the root cause is the file system granularity monitor, which is likely, then no, this is not fixed. I'm also not as confident as Damien that we can fix this quickly. MacOS by default stores mtime with second accuracy.

**Comment by ulfjack** [comment] 2016-12-09 14:52
This is a dupe of #857.

**Closed by ulfjack** 2016-12-09 14:52 UTC
Labels: category: performance, P2, type: bug

**Comment by talios** [comment] 2016-12-12 00:32
I remember Maven users reported a similar issue under OS/X that came down to GC getting locked or something on short lived VM processes. From memory it was a JVM specific bug. I'll see if I can dig up some references.
