### ISSUE TITLE
Cache external artifacts across workspaces

### ISSUE THREAD

**Issue by meteorcloudy** [bazelbuild/bazel#1376] opened 2016-06-13 09:18 UTC
For example, if I have two unrelated workspaces that both use app engine, they'll both download and unzip the appengine sdk, which seems wasteful. It would be nice if these could be shared.

(Although for appengine, we could alternatively implement an appengine_sdk_repository rule like the android rules)

Internal ref: b/27201943

**Comment by damienmg** [comment] 2016-06-13 09:25
Duplicate of https://github.com/bazelbuild/bazel/issues/1266

**Closed** 2016-06-13 09:25 UTC
Labels: P2, type: feature request
