### ISSUE TITLE
Modifications to bazel-[workspace] files do not invalidate bazel caches on Windows

### ISSUE THREAD

**Issue by benvanik** [bazelbuild/bazel#3393] opened 2017-07-15 19:06 UTC
Bazel version 0.5.2 on Windows 10.

If you modify a file under the symlinked bazel-[workspace] execroot path the bazel file watcher will not detect the changes. This can lead to very confusing runtime bugs as builds will succeed but be using partially complete object files that will still link but produce incorrect results.

The scenario where I hit this frequently is when modifying files from the Visual Studio debugger, which due to the way bazel passes sources to cl.exe resolves files to the symlinked workspace output paths instead of their original paths. If the original file is `c:\my_workspace\source.h` the pdb will reference the file as `C:\Users\Ben\AppData\Local\Temp\_bazel_Ben\4qe-y0H3\execroot\my_workspace\source.h`. The debugger will then open that file for display and allow me to modify it. If I do, bazel will not detect me changing the file (as it's just a copy of the original file). If I then change a file bazel does track (such as c:\my_workspace\source.cc) bazel will recompile but *not* recopy the source.h file, resulting in a build that contains some objects with the old c:\my_workspace\source.h and new objects with the modified one under the execroot. Only sadness ensues and a bazel clean is required to get the state right again.

The fast fix to at least prevent this corruption would be to mark all files copied to the execroot as readonly (I believe that bazel does this on some platforms? I recall seeing read-only files on linux internally at some point). This would prevent accidental modification of the files that bazel is not tracking. The ideal fix (for developer workflows) would be either a way to have the pdbs reference the original files such that the debugger would open those or for bazel to also check on startup/watch for modification file times/etc in its execroot.

**Comment by aehlig** [comment] 2017-07-18 06:26
I believe it is not supported to modify bazel's internal files, e.g., those in the exec root. Assigning to @laszlocsomor to comment on what a proper way of debugging under Windows is.

**Comment by laszlocsomor** [comment] 2017-07-18 06:52
Sadly, this is again a bug caused by Bazel copying files instead of symlinking. We've had correctness bugs because of this before.

@aehlig : In this case there's no user error and @benvanik isn't modifying internal files -- on Linux/MacOS he'd be opening a file in the source tree via a symlink in the output tree (because the debug info contains the path of the symlink).

@dslomov : FYI

@meteorcloudy : What was the fix for a similar bug with repository rule invalidations? Is that applicable here?

**Comment by meteorcloudy** [comment] 2017-07-18 07:09
@benvanik Are you using `local_repository` or `new_local_repository` rule?
Is this [issue](https://github.com/bazelbuild/bazel/issues/3374) related?

**Comment by laszlocsomor** [comment] 2017-07-18 08:02
I tried repro'ing this using a genrule and editing the source file in the execroot, but I'm seeing correct behavior. @benvanik : Are you sure you see stale object files when editing the sources in VC++?

## Repro files

```
  $ cat foo/BUILD
genrule(
    name = "foo",
    srcs = ["foo-in.txt"],
    outs = ["foo-out.txt"],
    cmd = "( cat $< ; date +%s ; ) > $@",
)

  $ cat foo/foo-in.txt 
hello
```

## Linux (Bazel 0.5.2)

On Linux, there's a directory symlink into my source tree. The file isn't even symlinked; it's the same file via a symlink to its parent directory.

```
  $ bazel --output_user_root=/tmp/bzl build //foo >&/dev/null && cat bazel-genfiles/foo/foo-out.txt 
hello
1500364235

  $ ls -l $(bazel --output_user_root=/tmp/bzl info execution_root)/foo
lrwxrwxrwx 1 laszlocsomor eng 53 Jul 18 09:51 /tmp/bzl/372300afcdcce99ca9a5ee9708130021/execroot/io_bazel/foo -> /usr/local/google/home/laszlocsomor/gitroot/bazel/foo

  $ ls -l $(bazel --output_user_root=/tmp/bzl info execution_root)/foo/foo-in.txt
-rw-r----- 1 laszlocsomor eng 6 Jul 18 09:50 /tmp/bzl/372300afcdcce99ca9a5ee9708130021/execroot/io_bazel/foo/foo-in.txt
```

Of course updating the contents of file causes a rebuild.

```
  $ echo world > foo/foo-in.txt

  $ bazel --output_user_root=/tmp/bzl build //foo >&/dev/null && cat bazel-genfiles/foo/foo-out.txt 
world
1500364477
```


## Windows (Bazel 0.5.2)

On Windows, it's actually the same: there's a junction to my source directory:

```
C:\work\bazel>c:\work\bazel-0.5.2\bazel.exe --output_user_root=c:\tmp3 build //foo
(...)
INFO: Found 1 target...
Target //foo:foo up-to-date:
  C:/tmp3/o6hbs7n0/execroot/io_bazel/bazel-out/msvc_x64-fastbuild/genfiles/foo/foo-out.txt
INFO: Elapsed time: 0.679s, Critical Path: 0.01s

C:\work\bazel>type bazel-genfiles\foo\foo-out.txt
hello
1500364610

C:\work\bazel>dir c:\tmp3\o6Hbs7N0\execroot\io_bazel
 Volume in drive C has no label.
 Volume Serial Number is AE28-2A26

 Directory of c:\tmp3\o6Hbs7N0\execroot\io_bazel

2017-07-18  09:57    <DIR>          .
2017-07-18  09:57    <DIR>          ..
2017-07-18  09:57    <DIR>          bazel-out
2017-07-18  09:57    <DIR>          external
2017-07-18  09:57    <JUNCTION>     foo [C:\work\bazel\foo]
2017-07-18  09:56    <DIR>          _bin
               0 File(s)              0 bytes
               6 Dir(s)  854,647,709,696 bytes free
```

So updating the file on Windows should also cause a rebuild:
```
C:\work\bazel>echo world > c:\tmp3\o6Hbs7N0\execroot\io_bazel\foo\foo-in.txt

C:\work\bazel>c:\work\bazel-0.5.2\bazel.exe --output_user_root=c:\tmp3 build //foo
(...)
INFO: Found 1 target...
Target //foo:foo up-to-date:
  C:/tmp3/o6hbs7n0/execroot/io_bazel/bazel-out/msvc_x64-fastbuild/genfiles/foo/foo-out.txt
INFO: Elapsed time: 0.793s, Critical Path: 0.22s

C:\work\bazel>type bazel-genfiles\foo\foo-out.txt
world
1500364843
```

**Comment by laszlocsomor** [comment] 2017-07-18 08:19
Clarification: in my [first comment](https://github.com/bazelbuild/bazel/issues/3393#issuecomment-315974440) I made a mere assumption that we're seeing a symlink-related problem. In my latest comment I'm seeing evidence contrary to that.

**Comment by meteorcloudy** [comment] 2017-07-18 09:39
> If I then change a file bazel does track (such as c:\my_workspace\source.cc) bazel will recompile but not recopy the source.h file

I doubt this is true, from my experiment, on Windows, Bazel always copies files or creates junctions for directories from `C:/my_workspace` to `<output_user_root>/execroot/my_workspace` whenever file changes.

**Comment by benvanik** [comment] 2017-07-18 15:03
Thanks for looking into this!
I'm definitely seeing issues here, or at least differing behavior from what's mentioned.

Here's a minimal example, in an empty repo (`bzlrepro` in my case). I believe it's important these all be placed under a subdirectory under the workspace root (`pkg/` is what I went with):
https://gist.github.com/benvanik/a38ae821d6ccfdb5b4a206d2ef11cf09

```
λ bazel clean
λ bazel build //pkg:c
λ bazel-bin\pkg\c.exe
7
```

Now from an editor (I've tested with both Sublime Text and VS) I modify `C:\Users\Ben\AppData\Local\Temp\_bazel_Ben\uDmzpaYe\execroot\__main__\pkg\a.h` to have kReallyX = 8 and save the file.

```
λ bazel build //pkg:c
λ bazel-bin\pkg\c.exe
7
```

:bomb::bomb::bomb: It still prints 7! The most shocking part is that if I check the non-execroot `c:\bzlrepro\pkg\a.h` file **it has kReallyX = 8**.

```
λ cat pkg\a.h   
#ifndef A_H_    
#define A_H_    
constexpr int kReallyX = 8;
class A {       
 public:        
  A();          
  ~A();         
  int QueryX(); 
  int x = kReallyX;    
};              
#endif  // A_H_ 
```

Now, try building //pkg:d, which will pick up the new a.h with `kReallyX = 8` in it but still use the existing cached //pkg:a with x = 7:
```
λ bazel build //pkg:d
λ bazel-bin\pkg\d.exe
kReallyX = 8
B.QueryY() = 7
```

This is what keeps making my stuff explode, and I'm pretty sure is not intended behavior :)
It gets especially difficult to track down when parts of the code are inlined such that two files may see different values for the same thing, or (as what caused me to find the problem) vtables change and one object ends up calling random functions because of it.

Hopefully this helps repro the issue, and if not I can try some more!

**Comment by benvanik** [comment] 2017-07-18 15:05
(oh I'm not sure `:b` is required - I'll try removing it now)

**Comment by benvanik** [comment] 2017-07-18 15:09
Did an additional quick test: the `:b` cc_library is required to demonstrate `:d` producing the differing values. If there is just cc_library `:a` and cc_binary `:d` the caching issue will still occur, but `:d` will not be rebuilt (as bazel does not detect a change to a.h) and still print both 7's even if the a.h in the workspace path has changed.

**Comment by benvanik** [comment] 2017-07-18 15:10
Oh, and @meteorcloudy: I am using new_local_repository a bunch and have actually hit that issue, but it's unrelated to this one (maybe? :)

**Comment by laszlocsomor** [comment] 2017-07-18 15:11
Thanks for the detailed repro! I can look at it tomorrow.

**Comment by laszlocsomor** [comment] 2017-07-19 08:39
Whoa. I can cleanly repro this on Windows. Works correctly on Linux.
This is a correctness bug indeed. Let me dig into it. Thanks for the excellent repro btw, that saved me a lot of work!

**Comment by laszlocsomor** [comment] 2017-07-19 08:50
Yay, good news! This is correct with Bazel built off HEAD!

**Comment by meteorcloudy** [comment] 2017-07-19 08:58
Could be related to https://github.com/bazelbuild/bazel/issues/3202

**Comment by laszlocsomor** [comment] 2017-07-19 08:58
Yay, even better news: this is also correct with the [0.5.3 rc2](https://storage.googleapis.com/bazel/0.5.3/rc2/index.html).

**Comment by laszlocsomor** [comment] 2017-07-19 09:09
@meteorcloudy : correct! I verified that 
https://github.com/bazelbuild/bazel/commit/22187a32b6b147758ac7a6d5158b4b12dee2eea0 fixed this bug.

**Closed by laszlocsomor** 2017-07-19 09:09 UTC
Labels: category: multi-platform > windows, P1, type: bug, Under investigation
