### ISSUE TITLE
bazel_test_test timeout flaked on FreeBSD [flake]

### ISSUE THREAD

**Issue by damienmg** [bazelbuild/bazel#3630] opened 2017-08-28 08:15 UTC
I saw only one instance so far:

http://ci.bazel.io/job/bazel-tests/984/artifact/tests-node=freebsd-12-variation=/src/test/shell/bazel/bazel_test_test/shard_1_of_3/test.log/*view*/

**Comment by damienmg** [comment] 2017-08-28 08:16
Forgot to say: this is a time out, 361.0s execution

**Comment by aehlig** [comment] 2017-08-28 08:44
Actually a very interesting timeout, as the linked log states `4 / 4 tests passed.` Will have a look nevertheless.

**Comment by damienmg** [comment] 2017-08-28 08:52
Arf normal, I got the test log wrong:
http://ci.bazel.io/blue/rest/organizations/jenkins/pipelines/bazel-tests/runs/984/nodes/29/log/?start=0

See the log should be the shard 2 not 1:

http://ci.bazel.io/job/bazel-tests/984/artifact/tests-node=freebsd-12-variation=/src/test/shell/bazel/bazel_test_test/shard_2_of_3/test.log/*view*/

**Comment by aehlig** [comment] 2017-08-28 13:09
Thanks. With that shard, it is undertandable that something went wrong. Nevertheless, the issue is hard to reproduce. Just run the test successfully a hundred times.

```
Target //src/test/shell/bazel:bazel_test_test up-to-date:
  bazel-bin/src/test/shell/bazel/bazel_test_test
INFO: Elapsed time: 1916.558s, Critical Path: 159.23s
INFO: Build completed successfully, 303 total actions
//src/test/shell/bazel:bazel_test_test                                   PASSED in 157.9s
  Stats over 300 runs: max = 157.9s, min = 50.9s, avg = 99.4s, dev = 17.7s

Executed 1 out of 1 test: 1 test passes.
```

So probably we have to wait and see if the flake occurs again.

**Comment by aehlig** [comment] 2017-09-14 07:13
flakyness hasn't reappeared, so closing for now

**Closed by aehlig** 2017-09-14 07:13 UTC
Labels: breakage, On hold: more data needed, P1, type: bug, Under investigation

**Comment by aehlig** [comment] 2017-09-14 07:18
Probably superseded by issue #3727 anyway.
