### ISSUE TITLE
Add deps & runtime_deps sections to maven_jar

### ISSUE THREAD

**Issue by kchodorow** [bazelbuild/bazel#438] opened 2015-09-09 23:43 UTC

**Comment by ittaiz** [comment] 2017-01-08 10:43
#1733 sounds like a duplicate of this one. If I'm not mistaken and seeing as it has more participants and conversation maybe this should be the one closed.

**Comment by jart** [comment] 2017-03-30 01:12
Respectfully closing this issue, because it's a subset of #1733 and I might already have a Skylark solution to the superset.

**Closed by jart** 2017-03-30 01:12 UTC
Labels: category: extensibility > external repositories, P4, type: feature request
