### ISSUE TITLE
java/scala interoperability

### ISSUE THREAD

**Issue by barlevalon** [bazelbuild/bazel#500] opened 2015-10-11 10:34 UTC
Currently, as I understand, the only way to build/package mixed java/scala projects is into two separate jars (with separate targets) for each language.
This means that dependencies between the two can only be one-way. This is currently a major hurdle for us at Wix as we try to adopt Bazel. We have many mixed java-scala projects with bi-directional dependencies, currently being built with Maven.
Perhaps I'm missing something and there is a way to build the java and scala classes "together"? If not, any plans to increase interoperability in the future? I'd be glad to work on it myself, just need to be pointed in the right direction.

**Comment by laszlocsomor** [comment] 2015-10-16 08:44
Do you mean you'd want a library rule with both `.java` and `.scala` files in the `srcs`?

You've probably seen these, but just in case:

- Example use of the Scala rules and how they to interop with `java_*` rules: https://github.com/bazelbuild/bazel/blob/15e9a506118b4067655e5e7f72ff852be5b797ca/tools/build_defs/scala/test/BUILD

- Implementation of Scala rules: https://github.com/bazelbuild/bazel/blob/15e9a506118b4067655e5e7f72ff852be5b797ca/tools/build_defs/scala/scala.bzl

- My first guess where you'll need to start tinkering with the Scala rules' implementation: https://github.com/bazelbuild/bazel/blob/15e9a506118b4067655e5e7f72ff852be5b797ca/tools/build_defs/scala/scala.bzl#L32

**Comment by damienmg** [comment] 2015-11-17 13:40
As I suggested in another issue, we could wrap scala file into a java_import or do something similar than the protobuf rules to avoid having too much of the java support to copy

**Comment by iirina** [comment] 2017-03-13 12:28
I'll close this as duplicate of #970.

**Closed by iirina** 2017-03-13 12:28 UTC
Labels: category: rules > java, P3, type: feature request
