### ISSUE TITLE
Bazel wants full dependency graph for incompatible targets - why aren't they just skipped?

### ISSUE THREAD

**Issue by carlosgalvezp** [bazelbuild/bazel#14132] opened 2021-10-19 13:44 UTC
### Description of the problem / feature request:

Hi!

I have a target that is only compatible with the `aarch64` platform:

```
cc_binary( 
    name = "foo",
    target_compatible_with = ["@platforms//cpu:aarch64"], 
    deps = [ "//foo:bar", ] 
)
```

Now, the `bar` dependency comes in two flavors, so I have an alias:

```
alias(
      name = "bar",
      actual = select({ 
            # Simplified syntax here 
            "aarch64_linux" : ":bar_linux",
            "aarch64_qnx": ":bar_qnx", 
       }) 
)
```

Now, my problem is that when I build for `x86` using wildcard, Bazel complains that it cannot find any `bar` for x86. And that's of course expected - there's no `bar` or x86! However why is Bazel complaining here? I specified that this target is incompatible with `x86`, so it shouldn't need to analyze it. Why is it doing that?

If I remove the `bar` dependency, Bazel just skips the target and exits gracefully without errors.

I could solve this problem adding a default condition for `bar`, but I don't want that. It will silence a useful warning. If I ever want to support a 3rd `aarch64` version, the default condition will silence the warning without prompting me to add a 3rd `aarch64` version of `bar`.

I also don't want to add a `select` in the `deps` field of the `cc_binary` either - it's redundant and adds noise. I already specify that the target is only compatible with`aarch64`. I don't need to add the `deps` only for `aarch64`.

Is this expected? Is there any other way I could solve this problem?

Thanks!

### Feature requests: what underlying problem are you trying to solve with this feature?

I want Bazel to ignore incompatible targets, without it trying to find its dependencies (which may not exist at all for an incompatible platform)

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

See above.

### What operating system are you running Bazel on?

Ubuntu 18.04

### What's the output of `bazel info release`?

release 5.0.0-pre.20210907.1

###  Have you found anything relevant by searching the web?

Nothing on the web. Asked in [bazel-discuss](https://groups.google.com/g/bazel-discuss/c/NNlN2Jl_bWI) without answer.

**Comment by gregestren** [comment] 2021-11-18 20:53
@carlosgalvezp - I see there's followup discussion on the bazel-discuss thread. Which parts of this issue are still pending?

**Comment by gregestren** [comment] 2021-11-29 22:25
I think https://github.com/bazelbuild/bazel/pull/14096 will fix this, although it's a work in progress (still under review, which will tak a few more iterations to land). That fixes https://github.com/bazelbuild/bazel/issues/12897. I'll mark this a dupe for issue queue cleanliness.

Duplicate of #12897.

**Comment by gregestren** [comment] 2021-11-29 22:26
Duplicate of #12897

**Closed** 2021-11-29 22:26 UTC
Labels: type: support / not a bug (process), team-Configurability, untriaged
