### ISSUE TITLE
Coverage fails with -lgcov library not found on Bazel darwin (clang) even when testing a java_test target

### ISSUE THREAD

**Issue by damienmg** [bazelbuild/bazel#2275] opened 2016-12-21 19:34 UTC
```
$ bazel coverage //src/test/java/com/google/devtools/common/options:options_test 
INFO: Using default value for --instrumentation_filter: "//src/main/java/com/google/devtools/common/options".
INFO: Override the above default with --instrumentation_filter
INFO: Found 1 test target...
ERROR: /Users/dmarting/git/bazel/src/main/tools/BUILD:19:1: Linking of rule '//src/main/tools:linux-sandbox' failed: sandbox-exec failed: error executing command /usr/bin/sandbox-exec -f /private/var/tmp/_bazel_dmarting/fd98b88c9ddd01e9b99b057d5d085004/bazel-sandbox/5f4a9e66-73c4-4c7c-add2-36a323784a15-15/sandbox.sb external/local_config_cc/cc_wrapper.sh -o ... (remaining 10 argument(s) skipped).
ld: library not found for -lgcov
clang: error: linker command failed with exit code 1 (use -v to see invocation)
Target //src/test/java/com/google/devtools/common/options:options_test failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 5.627s, Critical Path: 3.63s

Executed 0 out of 1 test: 1 fails to build.
```

* Operating System: macOS Sierra
* Bazel version (output of `bazel info release`): 0.4.3rc5

**Comment by damienmg** [comment] 2016-12-21 20:00
Even with some filter, it fails the same way (`bazel coverage //src/java_tools/singlejar:tests --instrumentation_filter=-//src/main,-//tools/,-//src/test`)

**Comment by ulfjack** [comment] 2017-01-09 12:08
Wait, what? We compile linux-sandbox in the target configuration, and as part of the build?

**Comment by ulfjack** [comment] 2017-01-09 12:11
Oh, I see. We need to update cc_configure to generate a coverage section for clang.

**Comment by ulfjack** [comment] 2017-01-09 12:15
The dependency on linux_sandbox may be unintentional, but it doesn't matter - if there's any C++ code in the transitive closure, we try to link it with -lgcov, and that needs to be fixed to make it work.

See https://github.com/bazelbuild/bazel/blob/master/src/main/java/com/google/devtools/build/lib/rules/cpp/CppConfiguration.java#L965

**Comment by mhlopko** [comment] 2017-02-21 13:26
Was this fixed in the meantime? Cannot reproduce :/

**Comment by mhlopko** [comment] 2017-02-22 10:42
Nevermind, just repro'd :)

**Closed** 2017-02-24 08:32 UTC
Labels: category: rules > misc native, P1, type: bug
