### ISSUE TITLE
setup env variable on Windows 10

### ISSUE THREAD

**Issue by spincraft** [bazelbuild/bazel#13204] opened 2021-03-11 04:02 UTC
> ATTENTION! Please read and follow:
> - if this is a _question_ about how to build / test / query / deploy using Bazel, or a _discussion starter_, send it to bazel-discuss@googlegroups.com
> - if this is a _bug_ or _feature request_, fill the form below as best as you can.

### Description of the problem / feature request:

> I'm having trouble with setting up the env. variable for Bazel on Windows 10.

### Feature requests: what underlying problem are you trying to solve with this feature?

> not a new feature

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

> Bazel doesn't show in start menu.

### What operating system are you running Bazel on?

> Windows 10

### What's the output of `bazel info release`?

> not running

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

> n/a

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

> not yet running Bazel.

###  Have you found anything relevant by searching the web?

> https://docs.bazel.build/versions/1.0.0/install-windows.html#installing-bazel-on-windows
>

**Comment by aiuto** [comment] 2021-03-31 04:12
Can you provide more information. There is no problem described here.

**Comment by spincraft** [comment] 2021-04-09 03:06
thanks for your reply.
open RUN and type bazel, gives the error dialog;
Windows can not find Bazel
From the Command Prompt bazel gives
bazel is not a recognized internal or external command
So, I suspect the PATH env. variable needs to be setup.
C:\Users\DP\AppData\Local\Programs\Microsoft VS Code\bin

your comments are welcome.

**Comment by aiuto** [comment] 2021-04-09 03:16
Have you followed the installation instructions at https://docs.bazel.build/versions/4.0.0/install-windows.html

**Comment by jin** [comment] 2021-04-14 12:15
Closing as not a bug/FR. Please direct usage questions to slack.bazel.build, bazel-discuss mailing list or StackOverflow.

**Closed by jin** 2021-04-14 12:15 UTC
Labels: type: support / not a bug (process)
