### ISSUE TITLE
Bazel crash (java.lang.IllegalStateException) with _grep_includes attr in aspect

### ISSUE THREAD

**Issue by nnmm** [bazelbuild/bazel#18286] opened 2023-05-02 14:05 UTC
### Description of the bug:

```
FATAL: bazel crashed due to an internal error. Printing stack trace:
java.lang.RuntimeException: Unrecoverable error while evaluating node '[]#//:reproducer_aspect.bzl%my_aspect ConfiguredTargetKey{label=//:simple_binary, config=BuildConfigurationKey[07847e57cec3668083aff5908290be9848cb5ff2050c41b2199bd781ee3253de]} {}' (requested by nodes 'com.google.devtools.build.lib.skyframe.AspectKeyCreator$TopLevelAspectsKey@4c29c582')
        at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:591)
        at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:399)
        at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinPool.scan(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
Caused by: java.lang.IllegalStateException: //:reproducer_aspect.bzl%my_aspect aspect on cc_binary attribute $grep_includes is not configured to be executable
        at com.google.common.base.Preconditions.checkState(Preconditions.java:821)
        at com.google.devtools.build.lib.analysis.RuleContext.getExecutablePrerequisite(RuleContext.java:1015)
        at com.google.devtools.build.lib.analysis.starlark.StarlarkAttributesCollection$Builder.addAttribute(StarlarkAttributesCollection.java:178)
        at com.google.devtools.build.lib.analysis.starlark.StarlarkRuleContext.<init>(StarlarkRuleContext.java:277)
        at com.google.devtools.build.lib.analysis.RuleContext.initStarlarkRuleContext(RuleContext.java:1110)
        at com.google.devtools.build.lib.skyframe.StarlarkAspectFactory.create(StarlarkAspectFactory.java:59)
        at com.google.devtools.build.lib.analysis.ConfiguredTargetFactory.createAspect(ConfiguredTargetFactory.java:604)
        at com.google.devtools.build.lib.skyframe.AspectFunction.createAspect(AspectFunction.java:865)
        at com.google.devtools.build.lib.skyframe.AspectFunction.compute(AspectFunction.java:360)
        at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:501)
        ... 7 more
```

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

**my_aspect.bzl**:

```
def _my_aspect_impl(target, ctx):
    return []

my_aspect = aspect(
    attr_aspects = ["*"],
    required_providers = [[CcInfo]],
    implementation = _my_aspect_impl,
    attrs = {
        "_grep_includes": attr.label(
            allow_files = True,
            executable = True,
            cfg = "exec",
            default = Label("@bazel_tools//tools/cpp:grep-includes"),
        ),
    },
)
```

**BUILD**:
```
cc_binary(
        name = "simple_binary",
        srcs = ["simple_binary.cpp"]
)
```

**simple_binary.cpp**:
```
int main() {}
```

**Command line**:
```
bazel build --aspects my_aspect.bzl%my_aspect //:simple_binary
```

### Which operating system are you running Bazel on?

Ubuntu

### What is the output of `bazel info release`?

release 7.0.0-pre.20230420.2

### Any other information, logs, or outputs that you want to share?

Doesn't happen when I rename the attr.

**Comment by meisterT** [comment] 2023-05-09 09:20
cc @oquenchil @mai93

**Comment by mai93** [comment] 2023-05-09 11:36
I think the root cause of this is that aspects merge their private attributes with the private attributes of the target they are running on. I've a plan to fix this.

**Comment by kotlaja** [comment] 2023-05-18 16:13
From the next release `_grep_includes` will be inside `cc_toolchain` and there will be no need to specify it on the rule/aspect itself so this particular error can be ignored. 

Please just wait for the next release, which will be very soon, and just delete `_grep_includes` from the aspect.

**Closed by kotlaja** 2023-05-18 16:13 UTC
Labels: type: bug, P2, team-Rules-API
