### ISSUE TITLE
"Cycle in the workspace file detected" breakage when consuming java rules from Starlark

### ISSUE THREAD

**Issue by davido** [bazelbuild/bazel#9291] opened 2019-08-30 09:07 UTC
After loading all occurences of java rules from Starlark (`--incompatible_load_java_rules_from_bzl` option) gerrit build is failing with:

```
 Loading: 0 packages loaded
ERROR: Failed to load Starlark extension '@rules_java//java:defs.bzl'.
Cycle in the workspace file detected. This indicates that a repository is used prior to being defined.
The following chain of repository dependencies lead to the missing definition.
 - @rules_java
This could either mean you have to add the '@rules_java' repository with a statement like `http_archive` in your WORKSPACE file (note that transitive dependencies are not added automatically), or move an existing definition earlier in your WORKSPACE file.
ERROR: cycles detected during target parsing
```

Note, that we ran the latest buildifier version with `--lint=fix` option to make the changes.

Interestingly, java rules are used in a number of Starlark files in gerrit build tool chain, but the problem occurs with `java_import` only in one Starlark file: `cm.bzl`. The workaround was to move `java_import` invocation from Starlark file in `BUILD` file, but this should be investigated why the problem occurs in the first place.

To reproduce the above failure, fetch the patch set number 4 of this change: [1] and run `bazel build :release`. The workaround was implemented on the latest patch set (e.g. patch set 6) of the same change: [2].

* [1] https://gerrit-review.googlesource.com/c/gerrit/+/232534/4
* [2] https://gerrit-review.googlesource.com/c/gerrit/+/232534

**Comment by iirina** [comment] 2019-09-03 12:37
Interesting case. Thanks for flagging it! I'll take a look.

**Comment by davido** [comment] 2019-09-03 15:18
Thanks @iirina!

Just to let you know, that you wouldn't be able to reproduce the problem easily, because the mentioned CL was merged today. I could upload a change to gerrit, that reverts the woraround part from that CL, so that you could reproduce the problem. Please, let me know, it you need this.

**Comment by iirina** [comment] 2019-09-17 11:34
@davido I got around to this issue now. You are using the `rules_java` repository defined by default in bazel, right? You're not adding anything to the `WORKSPACE` file?

**Comment by davido** [comment] 2019-09-17 12:10
@iirina Yes, exactly.

It seems to work in mostly all cases, even without it. But in that specific place, where we used java_import in Starlark file, it caused "Cycle in the workspace file detected" error. Note, that a workaround was merged to unblock the migration for fliping of --incompatible_load_java_rules_from_bzl option.

**Comment by iirina** [comment] 2019-09-17 13:40
OK, I managed to reproduce it \o/ I checked out the stable-2.14 branch, reverted the workaround and added the culprit locally. I'll start investigating now.

**Comment by iirina** [comment] 2019-09-17 14:40
I realized what's going on. The troubling bzl file (`//lib/codemirror:cm.bzl`) is loaded in gerrit's WORKSPACE file before `@rules_java` is defined. Because gerrit is using the `@rules_java` definition provided by bazel, the definition is actually appended at the end of gerrit's WORKSPACE file, which is too late.

The solution here is to add the rules_java definition before loading `//lib/codemirror:cm.bzl` in the `WORKSPACE`:

```
http_archive(
    name = "rules_java",
    url = "https://github.com/bazelbuild/rules_java/releases/download/0.1.0/rules_java-0.1.0.tar.gz",
    sha256 = "52423cb07384572ab60ef1132b0c7ded3a25c421036176c0273873ec82f5d2b2",
)
load("@rules_java//java:repositories.bzl", "rules_java_dependencies", "rules_java_toolchains")
rules_java_dependencies()
rules_java_toolchains()
```

I'll close this as WAI, let me know if I can help further.

**Closed** 2019-09-17 14:44 UTC
Labels: P2, team-Rules-Java

**Comment by davido** [comment] 2019-09-17 14:55
Thanks a lot for looking into it. We are planning to explicitly add `rules_java` in near future anyway (on master branch). Thanks again.
