### ISSUE TITLE
objc_library has stopped working due to ` missing input file '@bazel_tools//tools/objc:make_hashed_objlist.py'`

### ISSUE THREAD

**Issue by mikelikespie** [bazelbuild/bazel#1833] opened 2016-09-26 19:40 UTC
Getting this error...

```
ERROR: missing input file '@bazel_tools//tools/objc:make_hashed_objlist.py'.
ERROR: /private/var/tmp/_bazel_lewis/5db86e18828888feeffdaf5f3b199462/external/bazel_tools/tools/objc/BUILD:66:1: @bazel_tools//tools/objc:libtool: missing input file '@bazel_tools//tools/objc:make_hashed_objlist.py'.
ERROR: /private/var/tmp/_bazel_lewis/5db86e18828888feeffdaf5f3b199462/external/bazel_tools/tools/objc/BUILD:66:1 1 input file(s) do not exist.
```

Guessing 48859c1daeb931313f7b7e6cae447699b07d997e broke it.

**Comment by katre** [comment] 2016-09-27 00:26
Duplicate of #1828 .

**Closed** 2016-09-27 00:26 UTC
