### ISSUE TITLE
Native support for label_list_flag

### ISSUE THREAD

**Issue by alexander-shiryaev** [bazelbuild/bazel#18723] opened 2023-06-20 12:05 UTC
### Description of the feature request:

I [have implemented](https://github.com/alexander-shiryaev/bazel_issue/tree/main/feature_request/label_list_flag/emulation) the `label_list_flag` using the existing API, but the implementation has several issues:

1. It is divided into two parts - `label_list_flag_emulation` and `label_list_flag_emulation_implementation` because rules cannot be used as lambda functions (https://github.com/bazelbuild/bazel/issues/14673).
2. Users are required to know the exact absolute label of the created `label_list_flag`, which is not ideal.
3. Applying an aspect to targets in this label_list_flag is very difficult. While technically possible, the aspect needs to have knowledge of the specific implementation of the `label_list_flag` to access the referred targets.
4. The transition that changes the `label_list_flag` requires operating on strings instead of labels. This demonstrates that the abstraction is leaky.

Having a native implementation will resolve all the aforementioned issues.

### What underlying problem are you trying to solve with this feature?

I want to have a user-configurable list of targets.

### What is the output of `bazel info release`?

release 6.1.0

### Have you found anything relevant by searching the web?

https://github.com/bazelbuild/bazel/issues/17477
https://github.com/bazelbuild/bazel/issues/17828

### Any other information, logs, or outputs that you want to share?

Working example: https://github.com/alexander-shiryaev/bazel_issue/blob/main/feature_request/label_list_flag/example/BUILD.bazel

**Comment by gregestren** [comment] 2023-06-26 15:04
@katre for triage.

**Comment by katre** [comment] 2023-06-26 15:40
Thanks for your proposed implementation. This issue seems to be to be a duplicate of https://github.com/bazelbuild/bazel/issues/17828, since it's the same underlying request: we'd like to have a build setting that is a list of labels.

Your proposed implementation is interesting and I encourage you to use it (and anyone else to copy it). Ideally we'd implement this in the native Bazel codebase (as you suggest, and as I attempted in https://github.com/bazelbuild/bazel/issues/17828), but that is currently not feasible.

If you'd like to try to update Bazel's code to add this, that sounds great, please attach any future PRs to https://github.com/bazelbuild/bazel/issues/17828 for tracking. I'm going to close this as a dupe.

**Closed by katre** 2023-06-26 15:40 UTC
Labels: type: feature request, team-Configurability, untriaged
