### ISSUE TITLE
ZIP error when building bazel from scratch on Allwinner H3 (Orange Pi+ 2e) Raspberry Pi Clone

### ISSUE THREAD

**Issue by pczekalski** [bazelbuild/bazel#2825] opened 2017-04-13 21:23 UTC
### Description of the problem / feature request / question:
Compilation fails around step 1392 presenting some error regarding some problem with creating a zip package (I believe?).
I do not think it is a memory/storage error as there is plenty of free storage (I'm compiling on 32GB reliable Sandisk card) and extra a large swap area on USB drive is also declared.
Details on falire below:
```
ERROR: /home/pczekalski/tf/bazel/src/BUILD:178:2: Executing genrule //src:package-zip failed: bash failed: error executing command 
  (cd /tmp/bazel_Sv7av573/out/execroot/bazel && \
  exec env - \
    PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin \
  /bin/bash -c 'source external/bazel_tools/tools/genrule/genrule-setup.sh; src/package-bazel.sh bazel-out/local-opt/genfiles/src/package.zip  bazel-out/local-opt/genfiles/src/embedded_tools.zip bazel-out/local-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar bazel-out/local-opt/genfiles/src/install_base_key bazel-out/local-opt/bin/src/main/cpp/client bazel-out/local-opt/bin/src/main/native/libunix.so bazel-out/local-opt/bin/src/main/tools/build-runfiles bazel-out/local-opt/bin/src/main/tools/process-wrapper src/main/tools/jdk.BUILD bazel-out/local-opt/bin/src/main/tools/linux-sandbox bazel-out/local-opt/bin/tools/osx/xcode-locator bazel-out/local-opt/genfiles/src/java.version'): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 14.

zip error: Output file write failure (write error on zip file)
Target //src:bazel failed to build
```

### Environment info
* Operating System:
Armbian,
`Linux orangepiplus2e 3.4.113-sun8i #10 SMP PREEMPT Thu Feb 23 19:55:00 CET 2017 armv7l armv7l armv7l GNU/Linux`

Df:
```
pczekalski@orangepiplus2e:~$ df -a
Filesystem     1K-blocks    Used Available Use% Mounted on
sysfs                  0       0         0    - /sys
proc                   0       0         0    - /proc
udev              897544       0    897544   0% /dev
devpts                 0       0         0    - /dev/pts
tmpfs             206264    5860    200404   3% /run
/dev/mmcblk0p1  30070732 3476192  26261536  12% /
securityfs             0       0         0    - /sys/kernel/security
tmpfs            1031304   17928   1013376   2% /dev/shm
tmpfs               5120       4      5116   1% /run/lock
tmpfs            1031304       0   1031304   0% /sys/fs/cgroup
cgroup                 0       0         0    - /sys/fs/cgroup/systemd
cgroup                 0       0         0    - /sys/fs/cgroup/memory
cgroup                 0       0         0    - /sys/fs/cgroup/perf_event
cgroup                 0       0         0    - /sys/fs/cgroup/cpu,cpuacct
cgroup                 0       0         0    - /sys/fs/cgroup/devices
cgroup                 0       0         0    - /sys/fs/cgroup/freezer
cgroup                 0       0         0    - /sys/fs/cgroup/cpuset
cgroup                 0       0         0    - /sys/fs/cgroup/blkio
systemd-1              -       -         -    - /proc/sys/fs/binfmt_misc
mqueue                 0       0         0    - /dev/mqueue
debugfs                0       0         0    - /sys/kernel/debug
fusectl                0       0         0    - /sys/fs/fuse/connections
tmpfs            1031304     332   1030972   1% /tmp
/dev/mmcblk0p1  30070732 3476192  26261536  12% /var/log.hdd
log2ram            51200    1900     49300   4% /var/log
tmpfs             206264       8    206256   1% /run/user/1000
gvfsd-fuse             0       0         0    - /run/user/1000/gvfs
binfmt_misc            0       0         0    - /proc/sys/fs/binfmt_misc
/dev/mmcblk1p1  14876944 3645664  10475576  26% /media/pczekalski/d545fee3-ca76-4226-8f17-b73885e23891
```

The Java compiler version is 
javac 1.8.0_121

**Comment by aehlig** [comment] 2017-04-18 07:30
It is hard for us the reproduce this error, as we don't have access to this architecture. So I'll classify it as a feature request to support this architecture.

**Comment by pczekalski** [comment] 2017-04-18 14:39
Dear Klaus,

Thank you for the reply. Actually I'd really suggest to support Orange platform as they tend to be much more powerful comparing to RPi. It is essential i.e. when using Tensorflow.
Anyway thank you very much for your all effort.
Let me know if I can help you.

Regards,

P.

**Comment by damienmg** [comment] 2017-04-21 11:48
dupe of #2808

**Comment by damienmg** [comment] 2017-04-21 11:48
(Closing, please follow up on #2808)

**Closed by damienmg** 2017-04-21 11:48 UTC
Labels: category: multi-platform > other, type: feature request
