### ISSUE TITLE
Bazel 0.22.0 error: Unable to load package for '//tensorflow/tools/def_file_filter:def_file_filter_configure.bzl'

### ISSUE THREAD

**Issue by AliceDinh** [bazelbuild/bazel#7501] opened 2019-02-22 03:19 UTC
### Description of the problem / feature request:
I run bazel to convert tf model to tflite model according to this tutorial [Running on mobile with TensorFlow Lite](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/running_on_mobile_tensorflowlite.md)
ERROR: error loading package '': in F:/card-details-recognition-android-version2/tensorflow/tensorflow/workspace.bzl: Unable to load package for '//tensorflow/tools/def_file_filter:def_file_filter_configure.bzl': BUILD file not found on package path

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

bazel run -c opt tensorflow/lite/toco:toco -- --input_file=F:/ssd_mobilenet_v1_coco_2018_01_28/lite/tflite_graph.pb --output_file=F:/ssd_mobilenet_v1_coco_2018_01_28/lite/detect.tflite --input_shapes=1,300,300,3 --input_arrays=normalized_input_image_tensor --output_arrays='TFLite_Detection_PostProcess','TFLite_Detection_PostProcess:1','TFLite_Detection_PostProcess:2','TFLite_Detection_PostProcess:3' --inference_type=QUANTIZED_UINT8 --mean_values=128 --std_values=128 --change_concat_input_ranges=false --allow_custom_ops
The error is:
ERROR: error loading package '': in F:/tensorflow/tensorflow/workspace.bzl: Unable to load package for '//tensorflow/tools/def_file_filter:def_file_filter_configure.bzl': BUILD file not found on package path

### What operating system are you running Bazel on?
Window10
### What's the output of `bazel info release`?
release 0.22.0

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?
git remote get-url origin
https://github.com/ixuexi/bazel.git
git rev-parse master
edeebd8d5d07e70e8340f3b62f732a40891765e8
git rev-parse HEAD
edeebd8d5d07e70e8340f3b62f732a40891765e8

###  Have you found anything relevant by searching the web?
[bazel build fails with `error loading package ''` when invoked in a `git submodule foreach` command](https://github.com/bazelbuild/bazel/issues/6358)

**Comment by aehlig** [comment] 2019-02-22 10:08
I'm a bit confused, what this issue is about. First of all, the bazel commit you point at...

> git remote get-url origin
> https://github.com/ixuexi/bazel.git
> git rev-parse master
> [edeebd8](https://github.com/bazelbuild/bazel/commit/edeebd8d5d07e70e8340f3b62f732a40891765e8)
> git rev-parse HEAD
> [edeebd8](https://github.com/bazelbuild/bazel/commit/edeebd8d5d07e70e8340f3b62f732a40891765e8)

is from September 2017 wheras bazel 0.22.0 is from January 2019; that's more than a year off.

Secondly, you quote the error message
```
ERROR: error loading package '': in F:/card-details-recognition-android-version2/tensorflow/tensorflow/workspace.bzl: Unable to load package for '//tensorflow/tools/def_file_filter:def_file_filter_configure.bzl': BUILD file not found on package path
```
Now, it complains that it didn't find a `BUILD` in the directory `tensorflow/tools/def_file_filter`. Does such a file exist? Does the directory even exist? If the `BUILD` file exists, please provide more information on how the source tree looks like (how can we obtain it?). If the `BUILD` file does not exist, the error message is legitimate and it is not a `bazel` problem, but an issue with the repository you're trying to build.

Closing for now as a duplicate of https://github.com/tensorflow/tensorflow/issues/25997. Please reopen if it actually turns out to be a bazel issue.

**Closed by aehlig** 2019-02-22 10:08 UTC
