### ISSUE TITLE
marker file sensitivity to repo mapping causes cycles for legacy WORKSPACE

### ISSUE THREAD

**Issue by benjaminp** [bazelbuild/bazel#21372] opened 2024-02-15 21:51 UTC
Since 9edaddd6273de776a3f60245f5c56f82f9622caf, we have the following failure:
```
$ touch requirements_lock.txt
$ cat > WORKSPACE
load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
    name = "rules_python",
    sha256 = "c68bdc4fbec25de5b5493b8819cfc877c4ea299c0dcb15c244c5a00208cde311",
    strip_prefix = "rules_python-0.31.0",
    url = "https://github.com/bazelbuild/rules_python/releases/download/0.31.0/rules_python-0.31.0.tar.gz",
)

load("@rules_python//python:repositories.bzl", "py_repositories")

py_repositories()

load("@rules_python//python:pip.bzl", "pip_parse")
pip_parse(
   name = "my_deps",
   requirements_lock = "//:requirements_lock.txt",
)
load("@my_deps//:requirements.bzl", "install_deps")
install_deps()
$ bazel build --noenable_bzlmod
$ bazel shutdown
$ bazel build  --noenable_bzlmod
Starting local Bazel server and connecting to it...
ERROR: Failed to load Starlark extension '@@my_deps//:requirements.bzl'.
Cycle in the workspace file detected. This indicates that a repository is used prior to being defined.
The following chain of repository dependencies lead to the missing definition.
 - @@my_deps
This could either mean you have to add the '@@my_deps' repository with a statement like `http_archive` in your WORKSPACE file (note that transitive dependencies are not added automatically), or move an existing definition earlier in your WORKSPACE file.
ERROR: Error computing the main repository mapping: cycles detected during computation of main repo mapping
Computing main repo mapping: 
```

**Comment by Wyverald** [comment] 2024-02-15 21:59
dupe of https://github.com/bazelbuild/bazel/issues/21289

**Closed by Wyverald** 2024-02-15 21:59 UTC
