### ISSUE TITLE
Query will not show error when circular dependencies is found

### ISSUE THREAD

**Issue by fa93hws** [bazelbuild/bazel#15654] opened 2022-06-10 06:58 UTC
### Description of the bug:

When there is circular dependencies, `bazel build` will fail. However, `bazel query` seems to be fine with circular dependencies. Is that expected behavior? I think if a target can not be built, it's probably better to throw error as soon as possible.

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Have some sort of circular dependey, run bazel query, it pass.

### Which operating system are you running Bazel on?

Mac

### What is the output of `bazel info release`?

release 4.2.2- (@non-git)

### If `bazel info release` returns `development version` or `(@non-git)`, tell us how you built Bazel.

@non-git

### What's the output of `git remote get-url origin; git rev-parse master; git rev-parse HEAD` ?

```text
org-2562356@github.com:Canva/canva.git
537b736cbef566c68b9b4f16272ebc3db6b29b80
94baf5ee271428a09b89729c2c727115a272acba
```

### Have you found anything relevant by searching the web?

No

### Any other information, logs, or outputs that you want to share?

No

**Comment by sgowroji** [comment] 2022-06-10 12:10
Hello @fa93hws, Could you please provide reproducing steps for the above issue. Thanks!

**Comment by benjaminp** [comment] 2022-06-10 14:48
#12204

**Comment by haxorz** [comment] 2022-06-13 14:27
@[benjaminp](https://github.com/benjaminp) is correct this is a dupe of https://github.com/bazelbuild/bazel/issues/12204.

Unfortunately, both folks I tagged in that issue no longer work on Bazel. I'll find another assignee.

**Closed** 2022-06-15 00:40 UTC
Labels: type: bug, untriaged, team-Core
