### ISSUE TITLE
Override_repository silently fails if the repository previously didn't exist in bazel 6

### ISSUE THREAD

**Issue by matts1** [bazelbuild/bazel#16644] opened 2022-11-03 02:15 UTC
### Description of the bug:

It apppears that bazel 6.0 changed the API so that override_repository silently fails if the repository did not previously exist, while in bazel 5.3.2, it worked.

This is especially relevant, because the bazel intellij plugin relies on this feature to sync by adding a repository for the bazel aspect:
`--override_repository=intellij_aspect=/opt/intellij-ue-2021.3/plugins/g3plugins/aspect`

When attempting to sync with bazel 6, I get the following error:
`ERROR: Unable to find package for @[unknown repo 'intellij_aspect' requested from @]//:intellij_info_bundled.bzl: The repository '@[unknown repo 'intellij_aspect' requested from @]' could not be resolved: Repository '@intellij_aspect' is not visible from repository '@'.`

The sync works fine if I  add the following to my WORKSPAPCE.bazel:
`http_archive(name = "intellij_aspect")`

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

* Open any project with intellij with the bazel plugin installed (or the g3plugin if you're a googler)
* Put 6.0.0-pre.20221012.2 in your .bazelversion.
* Run bazel > sync 

### Which operating system are you running Bazel on?

Debian 5.18.16-1rodete4 x86-64

### What is the output of `bazel info release`?

release 6.0.0-pre.20221012.2

### What's the output of `git remote get-url origin; git rev-parse master; git rev-parse HEAD` ?

```text
N/A
```

**Comment by sgowroji** [comment] 2022-11-03 04:01
Hello @matts1, can you raise the issue in https://github.com/bazelbuild/intellij repo. As soon t is more related bazel plugin. Thanks!

**Comment by matts1** [comment] 2022-11-03 06:04
Just filed https://github.com/bazelbuild/intellij/issues/4067. However, I don't believe it's an issue on their end.

IMO, this is an issue with bazel itself, since bazel should either explicitly provide an error like "unable to override repository becauase it doesn't exist" or it should succeed. Additionally, this is a mechanism people were relying upon, and I suspect not just intellij, but plugins for every editor, will be depending on this feature.

**Comment by fmeum** [comment] 2022-11-03 07:34
@matts1 In order to hit this issue (a repo visibility error), you probably have to have `--enable_blzmod` (or `--experimental_enable_bzlmod`) somewhere in your `.bazelrc`, which is an important detail

I can reproduce this with any Bzlmod project with `common --enable_bzlmod` in `.bazelrc` and `last_green` in `.bazelversion`. In my case, the failing command line is:
```
bazel build --tool_tag=ijwb:IDEA:ultimate --keep_going --build_event_binary_file=/tmp/intellij-bep-c6f5f954-3b61-482f-ab4b-33159ed5db95 --nobuild_event_binary_file_path_conversion --curses=no --color=yes --progress_in_terminal_title=no --noexperimental_run_validations --aspects=@intellij_aspect//:intellij_info_bundled.bzl%intellij_info_aspect --override_repository=intellij_aspect=/home/fhenneke/.local/share/JetBrains/Toolbox/apps/IDEA-U/ch-0/222.4345.14.plugins/ijwb/aspect --output_groups=intellij-resolve-java-direct-deps,intellij-info-generic,intellij-info-java-direct-deps -- //native_loader/src/main/native/com/example/math:math //native_loader/src/main/native/com/example/os:impl/os //analysis/cc_jni_library:tests //analysis/jni_headers:tests //libjvm_stub:HelloFromJava //native_loader/src/test/java/com/example:JniLoaderTest
```

If I replace `@intellij_aspect//:intellij_info_bundled.bzl%intellij_info_aspect` with `@@intellij_aspect//:intellij_info_bundled.bzl%intellij_info_aspect`, the aspect run succeeds both with and without Bzlmod. But this will only works with Bazel 6, so the decision which label type to use would have to depend on a version check.

**Comment by meteorcloudy** [comment] 2022-11-03 09:28
@matts1 This is WAI due to strict deps check if you did enable Bzlmod. Therefore, the problem should be fixed from the intellij plugin side, we can follow up this in https://github.com/bazelbuild/intellij/issues/4067

**Closed by meteorcloudy** 2022-11-03 09:28 UTC
Labels: type: bug, P2, team-OSS, area-Bzlmod
