### ISSUE TITLE
ctx.expand_location() fails when resolving java_binary targets

### ISSUE THREAD

**Issue by shahms** [bazelbuild/bazel#12616] opened 2020-12-03 16:51 UTC
### Description of the problem / feature request:

When asked to expand a string containing "$(location //path/to/java:binary)" ctx.expand_location() complains that the rule produces two files: the executable script and the .jar file.  While technically true, it doesn't leave many good options for expanding the location of tool dependencies.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

```
load("@bazel_skylib//rules:run_binary.bzl", "run_binary")

java_binary(
  name = "hello_world",
  ...
)

run_binary(
  name = "run_hello_world",
  args = ["$(location :hello_world)"],
  tool = ":hello_world",
  outs = ["hello_world.txt"],
)
```

### What operating system are you running Bazel on?

Linux

### What's the output of `bazel info release`?

release 3.7.0

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

> Replace this line with your answer.

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

git@github.com:shahms/kythe.git
f4bf8d3f6859ac5336a6ac78813f4d2a51fdb6e4
f4bf8d3f6859ac5336a6ac78813f4d2a51fdb6e4

###  Have you found anything relevant by searching the web?

I haven't found any other reference.

**Comment by comius** [comment] 2020-12-04 10:52
Duplicate of https://github.com/bazelbuild/bazel/issues/10067

**Closed by comius** 2020-12-04 10:52 UTC
Labels: team-Rules-Java, untriaged
