### ISSUE TITLE
Forbid the + operator on skylark dictionaries

### ISSUE THREAD

**Issue by c-parsons** [bazelbuild/bazel#5820] opened 2018-08-08 22:29 UTC
This is a tracking issue for offering a migration solution for
`--incompatible_dict_plus`

This flag would forbid the + operator on dictionaries.

**Comment by laurentlb** [comment] 2019-02-20 19:23
Duplicate of https://github.com/bazelbuild/bazel/issues/6461

**Closed by laurentlb** 2019-02-20 19:23 UTC
Labels: P1, incompatible-change, team-Starlark
