### ISSUE TITLE
Google-internal Blaze genrule details leaking in docs

### ISSUE THREAD

**Issue by attilaolah** [bazelbuild/bazel#13523] opened 2021-05-27 11:30 UTC
### Description of the problem / feature request:

The [documentation on genrules](https://docs.bazel.build/versions/master/be/general.html) contains the rather confusing phrase "Bazel (but not Bazel)":

![image](https://user-images.githubusercontent.com/196617/119818280-4b04d080-beef-11eb-974f-0fec2cd52cf0.png)

Obviously the second part is meant to be Blaze, but the overly-zealous Copybara rule replaces each word when exporting.

Ideally the parenthesised part `(but not Blaze)` should not be exported.

**Comment by communikit** [comment] 2021-09-16 21:51
Closing as duplicate of #13885

**Closed by communikit** 2021-09-16 21:51 UTC
Labels: untriaged, team-Documentation
