### ISSUE TITLE
Long file path names are not supported by MSVS

### ISSUE THREAD

**Issue by excitoon** [bazelbuild/bazel#4550] opened 2018-01-31 13:32 UTC
### Description of the problem / feature request:

Unfortunately MSVS (specifically 2015) cannot handle paths longer that 260 symbols. This is well-known problem and it is not gonna be solved. Bazel on its hand does two things greatly increasing path names:
1) it works in temp folder which looks like: `C:\Users\Username\AppData\Local\Temp\_bazel_username\iwggwcit\execroot\__main__`;
2) it doubles path from workspace to package in objects like that: `some-directory-not-even-very-long/not-trivial-module/not-trivial-submodule/project/_objs/hello-world/some-directory-not-even-very-long/not-trivial-module/not-trivial-submodule/project/sources`.

I've created an example of failing build:
https://github.com/excitoon/bazel-issues/tree/master/windows-long-file-paths-of-objects

I think it can be solved on bazel side by making shorter symlinks of long paths (right in python wrapper) or making internal directory structure more plain.

Bazel output:
```
C:\...aths-of-objects\some-directory-not-even-very-long\not-trivial-module\not-trivial-submodule\project>bazel build ...
INFO: Analysed target //some-directory-not-even-very-long/not-trivial-module/not-trivial-submodule/project:hello-world (1 packages loaded).
INFO: Found 1 target...
ERROR: C:/users/chebotarev_v/documents/bazel-issues/windows-long-file-paths-of-objects/some-directory-not-even-very-long/not-trivial-module/not-trivial-submodule/project/BUILD:3:1: C++ compilation of rule '//som
e-directory-not-even-very-long/not-trivial-module/not-trivial-submodule/project:hello-world' failed (Exit 1)
C:\t\_bazel_chebotarev_v\iwggwcit\execroot\__main__\some-directory-not-even-very-long\not-trivial-module\not-trivial-submodule\project\sources\hello-world.cpp : fatal error C1083: Cannot open compiler generated
file: '': Invalid argument
Target //some-directory-not-even-very-long/not-trivial-module/not-trivial-submodule/project:hello-world failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 2.385s, Critical Path: 0.15s
FAILED: Build did NOT complete successfully
```

### Feature requests: what underlying problem are you trying to solve with this feature?

That is required to build large repositories on Windows.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

https://github.com/excitoon/bazel-issues/tree/master/windows-long-file-paths-of-objects
```
bazel build ...
```

### What operating system are you running Bazel on?

Windows 10 x64

### What's the output of `bazel info release`?

Build label: 0.9.0
Build target: bazel-out/x64_windows-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Tue Dec 19 09:32:04 2017 (1513675924)
Build timestamp: 1513675924
Build timestamp as int: 1513675924

###  Have you found anything relevant by searching the web?

Nothing.

**Comment by meteorcloudy** [comment] 2018-01-31 14:04
This is a duplicate of https://github.com/bazelbuild/bazel/issues/4149, I'm working on it!

**Closed by meteorcloudy** 2018-01-31 14:04 UTC
