### ISSUE TITLE
Upgrade root module MVS not matching from warning to error

### ISSUE THREAD

**Issue by matts1** [bazelbuild/bazel#22102] opened 2024-04-24 01:26 UTC
### Description of the feature request:

Currently, when the root module declares an explicit dependency on an explicit version, bazel performs MVS and outputs a warning if it transitively depends on a version higher than that. For example, if my root module contains:
```py
bazel_dep(name = "bazel_skylib", version = "1")
bazel_dep(name = "foo", version = "1")
```
And foo's module.bazel contains
```py
bazel_dep(name = "bazel_skylib", version = "2")
```
Then I will get the warning `WARNING: For repository 'bazel_skylib', the root module requires module version bazel_skylib@1, but got bazel_skylib@2 in the resolved dependency graph.`

However, I believe that this warning should in fact be an error, and ideally we'd add an auto-fix for this to `bazel mod tidy` to automatically deal with this problem. I think that there's no reason to leave it as a warning, since it just creates spooky action at a distance, and I think it's strictly better to have your MODULE.bazel file contain a correct set of version numbers.

I don't believe this is a developer experience issue, since:
* This should only ever affect a user precisely when they change the version number of a `bazel_dep` in their root MODULE.bazel
* The user will get told explicitly what to do to fix the problem.

### Which category does this issue belong to?

External Dependency

### What underlying problem are you trying to solve with this feature?

At the moment, reading the root MODULE.bazel file does not tell you what versions you're actually using, and is subject to spooky action at a distance.

### Which operating system are you running Bazel on?

linux

### What is the output of `bazel info release`?

7.1.1

**Comment by keith** [comment] 2024-04-24 03:18
You can pass --check_direct_dependencies=error to get this behavior. Still a fair question of defaults

**Comment by matts1** [comment] 2024-04-24 03:27
Ah, wasn't aware of that, thanks. IMO it'd be a good idea to flip the default to true on the next major revbump.

**Comment by fmeum** [comment] 2024-04-24 07:58
I am supportive of this change. We could cherry-pick the `bazel mod tidy` support into Bazel 7 and flip the default in Bazel 8.

@matts1 Would you be interested in contributing the `bazel mod tidy` fixups? `buildozer` can already operate on `bazel_dep`, so this would only require changes in Bazel. I could help along the way.

**Comment by matts1** [comment] 2024-04-24 08:20
I can take a look at it next week. I don't appear to have permissions to change assignee, so could someone set the assignee to me?

**Comment by Wyverald** [comment] 2024-04-24 21:57
this is a dupe of https://github.com/bazelbuild/bazel/issues/21794

**Closed by Wyverald** 2024-04-24 21:57 UTC
Labels: type: feature request, P3, team-ExternalDeps
