### ISSUE TITLE
Bazel doesn't ignore its own symlinks when running 'bazel --output_base=/tmp query ...:* --output=package'

### ISSUE THREAD

**Issue by chiahsingyu** [bazelbuild/bazel#15867] opened 2022-07-13 13:36 UTC
### Description of the bug:

When running 'bazel --output_base=/tmp query ...:* --output=package' (which is the command vscode Bazel extension uses to list the packages), Bazel goes into its own bazel-<workspace> symlink and fails with some error like:

ERROR: error loading package 'bazel-foo/external/bazel_tools/third_party/def_parser': Label '//tools/python:private/defs.bzl' is invalid because 'tools/python' is not a package; perhaps you meant to put the colon here: '//:tools/python/private/defs.bzl'?

An workaround is to add the symlink to .bazelignore.

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

mkdir foo
cd foo
touch WORKSPACE
echo 'cc_binary(name = "a", srcs = ["a.c"])' > BUILD
echo 'int main() {return 0;}' > a.c
bazel build ...
bazel --output_base=/tmp query ...:* --output=package

Fix:

echo 'bazel-foo' > .bazelignore
bazel --output_base=/tmp query ...:* --output=package

### Which operating system are you running Bazel on?

Ubuntu

### What is the output of `bazel info release`?

release 5.2.0

### Any other information, logs, or outputs that you want to share?

Starting local Bazel server and connecting to it...
ERROR: error loading package 'bazel-foo/external/bazel_tools/src/conditions': Label '//tools/windows:windows_config.bzl' is invalid because 'tools/windows' is not a package; perhaps you meant to put the colon here: '//:tools/windows/windows_config.bzl'?
Loading: 43 packages loaded
    currently loading: bazel-foo/external/bazel_tools/src/conditions ... (17 packages)
    Fetching @rules_cc; fetching
    Fetching @rules_proto; fetching

**Comment by haxorz** [comment] 2022-07-28 16:54
Is this related to #3268? Is the `--output_base=/tmp` essential for your repro?

**Comment by chiahsingyu** [comment] 2022-08-01 01:24
It seems to be related, but the flags are different.

The command is actually invoked by vscode bazel extension, so one potential workaround is to fix that extension

**Comment by Wyverald** [comment] 2022-09-20 12:30
Looks like a dupe of #3268 indeed.

**Closed by Wyverald** 2022-09-20 12:30 UTC
Labels: type: bug, untriaged, team-OSS
