### ISSUE TITLE
Running docker_build fails if file is at root

### ISSUE THREAD

**Issue by jschaf** [bazelbuild/bazel#2831] opened 2017-04-16 09:02 UTC
### Description of the problem / feature request / question:

Trying to `bazel run` a docker_build.

### If possible, provide a minimal example to reproduce the problem:

Minimal repo: https://gist.github.com/jschaf/5fbdc65730fe9cdf7dcf5ddd9c95e0da

```shell
bazel run //:hello
```

### Environment info
* Operating System:

`uname -a`
Linux 4.10.9-1-ARCH #1 SMP PREEMPT Sat Apr 8 12:39:59 CEST 2017 x86_64 GNU/Linux

* Bazel version (output of `bazel info release`):

release 0.4.5- (@non-git)

* If `bazel info release` returns "development version" or "(@non-git)", please tell us what source tree you compiled Bazel from; git commit hash is appreciated (`git rev-parse HEAD`):

From [Arch Linux AUR](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=bazel), it's downloading 4.5 from the github releases.

###  Have you found anything relevant by searching the web?

Nothing found.

### Anything else, information or logs or outputs that would be helpful?

```
INFO: Found 1 target...
Target //:hello up-to-date:
  bazel-bin/hello-layer.tar
INFO: Elapsed time: 0.052s, Critical Path: 0.00s

INFO: Running command line: bazel-bin/hello
Skipping 24c4a0933bbd2f6c65ed283d84502fed4d22c77bacd109353929fea482da6025, already loaded.
Tagging 24c4a0933bbd2f6c65ed283d84502fed4d22c77bacd109353929fea482da6025 as bazel/:hello
Error parsing reference: "bazel/:hello" is not a valid repository/tag: invalid reference format
ERROR: Non-zero return code '1' from command: Process exited with status 1.
```

**Comment by aehlig** [comment] 2017-04-18 07:51
The reference `"bazel/:hello"` looks suspiciously like wrong string operations; however, I'm not an expert in this area. Assigning to Damien for further triage.

**Comment by damienmg** [comment] 2017-04-18 08:03
Dupe of #616

**Closed by damienmg** 2017-04-18 08:03 UTC
Labels: category: skylark > cloud / docker, type: bug
