### ISSUE TITLE
Inconsistent default character encoding across sandboxes

### ISSUE THREAD

**Issue by StephenAmar** [bazelbuild/bazel#4277] opened 2017-12-12 01:13 UTC
The default encoding seems to be different between darwin-sandbox and linux-sandbox.
I wrote a small test to demonstrate:

```java
public class UtfTest {
  @Test
  public void testCharset() throws Exception {
    assertEquals(Charset.defaultCharset(), Charsets.UTF_8);
  }
```

If I run this test on mac os, it succeeds.
If I run it on linux, it fails:

There was 1 failure:
1) testCharset(com.foo.bar.UtfTest)
java.lang.AssertionError: expected:US-ASCII but was:UTF-8
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:743)
	at org.junit.Assert.assertEquals(Assert.java:118)
	at org.junit.Assert.assertEquals(Assert.java:144)

A workaround I found is to specifically pass `--test_env=LC_ALL="en_US.UTF-8"` to bazel.
Is that expected?

### Environment info
* Operating System:
OS X Sierra / Ubuntu 14.04

* Bazel version (output of `bazel info release`):
release 0.8.1

**Comment by laszlocsomor** [comment] 2017-12-12 15:26
> A workaround I found is to specifically pass `--test_env=LC_ALL="en_US.UTF-8"` to bazel.
Is that expected?

According to this comment, Bazel tries to use the platform default encoding:
https://github.com/bazelbuild/bazel/blob/94c5c05383284cd96defb75f2fa54dab2346f9b5/src/main/cpp/blaze.cc#L1296-L1302

However I'm confused by that information, I don't see how ISO-8859-1 would select the platform default, especially if the default would be e.g. UTF-8.
/cc @dslomov : do you have any thoughts on this?

@StephenAmar : as a workaround, keep passing the `--test_env` flag, that at least looks good to me.

**Comment by StephenAmar** [comment] 2017-12-12 17:36
It's a bit weirder. The default encoding returned by the JVM in linux-sandbox seems to be US-ASCII

**Comment by laszlocsomor** [comment] 2017-12-13 09:19
@StephenAmar : what are the values of the `$LANG`, `$LANGUAGE`, `$LC_ALL`, and `$LC_CTYPE` environment variables:
- in linux-sandbox if you **don't** use the `--test_env` flag?
- in a normal Bash session on your Linux machine?

I'm trying to understand where that `US-ASCII` is coming from.

**Comment by StephenAmar** [comment] 2017-12-13 18:34
On a normal Bash session:
`[18:32:41] ~/code/b/javatests/sample $ locale
LANG=en_US.UTF-8
LANGUAGE=
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=`

In the sandbox (I used a sh_test in a brand new workspace):
`LANG=
LANGUAGE=
LC_CTYPE="POSIX"
LC_NUMERIC="POSIX"
LC_TIME="POSIX"
LC_COLLATE="POSIX"
LC_MONETARY="POSIX"
LC_MESSAGES="POSIX"
LC_PAPER="POSIX"
LC_NAME="POSIX"
LC_ADDRESS="POSIX"
LC_TELEPHONE="POSIX"
LC_MEASUREMENT="POSIX"
LC_IDENTIFICATION="POSIX"
LC_ALL=`

**Comment by ittaiz** [comment] 2018-06-06 06:17
We just hit this. Is this on anyone's radar or do we need to use the workaround?

**Comment by jmmv** [comment] 2019-01-24 21:50
Well well, from https://openjdk.java.net/jeps/8187041:

> The default charset is currently determined when the Java virtual machine starts. On macOS it is UTF-8, on other platforms it depends on the user's locale and the default encoding.

So this seems to be "working as intended". The sandbox sets `LC_*=POSIX` which, on Linux, is inherited by the JVM and thus selects US-ASCII, and on macOS is ignored and UTF-8 is used. The rationale seems to be historical compatibility.

I don't think we can fix this ourselves:

1.   If Java is really ignoring the environment variables on macOS, we could change our rules that pass flags to the JVM to change the default (assuming that this is possible). But doing this is a time bomb: someone will have rules that also launch the JVM without being aware of this, and they'll hit this at a later stage.

1.   So if we cannot change macOS, we could change Linux. But doing this implies setting all local settings to UTF-8 for all actions (and dropping the previous `C` value), which I think is a big no-no. This would have backwards-compatibility effects and would break arbitrary command lines (e.g. because sorting order changes).

1.   Further, based on the documentation, people will make assumptions about what the default encoding is -- especially if that documentation claims that the default is UTF-8 on macOS regardless of the environment. Finding that the default is something else would be surprising.

So... I think you'll just need to account for this platform inconsistency in your tests.

**Comment by jmmv** [comment] 2019-01-24 21:50
Given this, rerouting to the Java rules team. They are the ones to make the final call here.

**Comment by lberki** [comment] 2019-03-14 14:18
Agreed with @jmmv . So closing this as Working as Intended.

**Closed by lberki** 2019-03-14 14:18 UTC
Labels: team-Rules-Java, untriaged
