### ISSUE TITLE
platform_mappings file repo mapping is literal in some cases

### ISSUE THREAD

**Issue by keith** [bazelbuild/bazel#17171] opened 2023-01-09 16:51 UTC
### Description of the bug:

I have a repo with platforms defined:

https://github.com/bazelbuild/apple_support/blob/f2be7660d083eeb14e52134e60308411b6c9e74a/platforms/BUILD

For everyone consuming this repo I want to recommend a platform_mappings file like:

```
  @build_bazel_apple_support//platforms:ios_sim_arm64
    --cpu=ios_sim_arm64
    --apple_platform_type=ios

...
```

where `build_bazel_apple_support` is included in the platform label. But when building in the apple_support repo itself with this file, and passing something like `--platforms=@build_bazel_apple_support//platforms:ios_sim_arm64` as the platform, the platform_mappings file isn't taken into account. In the output of `bazel config SHA` you can see the platform is set correctly:

```
  platforms: [//platforms:ios_sim_arm64]
```

But the flags are not:

```
  apple_platform_type: macos
```

If I change the platform_mappings file to remove the repo name it works:

```
  //platforms:ios_sim_arm64
    --cpu=ios_sim_arm64
    --apple_platform_type=ios
```

### Which operating system are you running Bazel on?

macOS

### What is the output of `bazel info release`?

89d34ac23a8f46b3b89ac4730d7a20da375f5fae

**Comment by keith** [comment] 2023-01-09 17:02
ah ok great, i didn't think of this as just a subset of https://github.com/bazelbuild/bazel/issues/17127

**Comment by katre** [comment] 2023-01-09 17:12
Closing this as a dupe of #17127.

**Closed by katre** 2023-01-09 17:12 UTC
Labels: type: bug, P2, team-Configurability
