### ISSUE TITLE
bazel merges android resource problem

### ISSUE THREAD

**Issue by leozwang-google** [bazelbuild/bazel#3980] opened 2017-10-27 16:12 UTC
I ran into android resource problems, the errors are
#1. undefined app elevation
#2. undefined some material items, for example widget.design.textinputlayout

The code is attached in this issue.

The code is straightforward, however, it depends on firebase-UI project https://github.com/firebase/FirebaseUI-Android which also depends on faceback and twitter login aars.

[fire.zip](https://github.com/bazelbuild/bazel/files/1422671/fire.zip)

**Comment by aj-michael** [comment] 2017-11-10 22:02
/cc @jin @ahumesky @dkelmer 

Sorry about the delay on this, I'll try to sort this out early next week.

**Comment by aj-michael** [comment] 2017-11-13 17:57
Did some digging, the issue is when Bazel is parsing this stylable attribute:

https://android.googlesource.com/platform/frameworks/support/+/master/design/res/values/attrs.xml#282

Since it doesn't define a format, we assume it a reference instead of a definition. But Bazel can't find an actual definition for it (and neither can I...).

**Comment by aj-michael** [comment] 2017-11-13 18:11
Oh, it's inherited from a styleable in appcompat-v7:

https://android.googlesource.com/platform/frameworks/support/+/master/v7/appcompat/res/values/attrs.xml#500

The problem is that maven_aar generates aar_import rules, but there are no deps between those aar_import rules.

This is an ugly manifestation of the fact that Bazel does not have a good solution for transitive maven dependencies.

I'll try and whip up a workaround.

**Comment by aj-michael** [comment] 2017-11-13 20:48
so, this issue is a duplicate of https://github.com/bazelbuild/bazel/issues/2863.

https://bazel-review.googlesource.com/c/bazel/+/20771 will add a `deps` attribute to maven_aar that will fix this. However, it will require maintaining the graph of dependencies between the AARs, as opposed to the flat list in the deps of an android_library.

**Closed** 2017-11-14 18:23 UTC
Labels: category: rules > android, P1, type: bug
