### ISSUE TITLE
Release 0.6.0

### ISSUE THREAD

**Issue by mhlopko** [bazelbuild/bazel#3286] opened 2017-06-28 15:46 UTC
Is it time for our next major release?

**Comment by mhlopko** [comment] 2017-06-29 15:02
First release blocker: #3293

**Comment by buchgr** [comment] 2017-07-13 07:57
0.5.3 first :) #3375

**Comment by damienmg** [comment] 2017-07-25 14:01
@vladmos since Jakob is doing 0.5.3, you are the next in line, and since you wanted to have some breaking change in 0.6.0 I guess being the RM will help :)

@helenalt is going to help scope 0.6

**Comment by abergmeier-dsfishlabs** [comment] 2017-08-09 06:51
> you wanted to have some breaking change in 0.6.0

Well there were breaking changes in 0.5.3 already. IMO breaking anything before 1.0 is fair game (although I do grind my teeth ever time 😄 ).

**Comment by ittaiz** [comment] 2017-09-08 06:47
Hi,
Any idea when this release will roll out?

**Comment by buchgr** [comment] 2017-09-08 07:24
@ittaiz I believe next week since @vladmos is on vacation this week.

**Comment by vladmos** [comment] 2017-09-13 11:35
The first release candidate has been created: https://github.com/bazelbuild/bazel/tree/release-0.6.0 (baseline 87cc92e5df35d02a7c9bc50b229c513563dc1689).

**Comment by petemounce** [comment] 2017-09-13 13:49
https://chocolatey.org/packages/bazel/0.6.0-rc1 is available.

**Comment by petemounce** [comment] 2017-09-13 13:50
One of the release note bullets is just `fixes #3552`?

**Comment by vladmos** [comment] 2017-09-13 14:02
Yes, it came from 65e0f78e71ef91f95186471d1d82f5cc33084e53. I'll remove this item manually if there's another RC.

**Comment by abergmeier-dsfishlabs** [comment] 2017-09-18 09:48
> - Python is now required to build bazel

So Python2 and/or Python3?

**Comment by vladmos** [comment] 2017-09-18 13:24
Created an RC2 with cherry-picked a615d288b008c36c659fdc17965207bb62d95d8d.

**Comment by petemounce** [comment] 2017-09-18 14:19
https://chocolatey.org/packages/bazel/0.6.0-rc2 is available.

**Comment by iirina** [comment] 2017-09-19 13:17
Sorry for crashing the party so late, but do you have room for another cherry pick? 655a529db693e0d3c89a68ca81fc4858147b90f0 It's an incompatible change and I would like to get it into this release.

**Comment by dslomov** [comment] 2017-09-19 13:43
We should try to not cherry-pick features into release candidates, and  655a529 is a feature. 
Moreover, since if it is an incompatible change, we should ideally be protecting it with a flag.

**Comment by davido** [comment] 2017-09-19 18:40
What about [this issue](https://github.com/bazelbuild/bazel/issues/3042) fixed by [this non-intrusive change](https://bazel-review.googlesource.com/#/c/bazel/+/16810/), protected by two innocent experimental flags, that are disabled by default?

**Comment by damienmg** [comment] 2017-09-19 18:47
This is also a FR, we decided to enforce a no exception policy: we only
cherry-pick fixes for regression. On previous release we were pretty lax on
that policy and this created a lot of difficulties.

We are also making some more changes to improve our releases, the next
release will be cut around October 2nd and will be 0.7 for instance.

**Comment by davido** [comment] 2017-09-19 19:07
@damienmg Thanks for explanation. Let's hope that a fix for #3042 will make it in upcoming 0.7 release then.

**Comment by meteorcloudy** [comment] 2017-09-20 09:25
Can we cherrypick 213a52a29ac445781f0cd55d1909eecce0f29fd5? It fixes https://github.com/bazelbuild/bazel/issues/3717

**Comment by damienmg** [comment] 2017-09-20 09:29
Not a regression so no.

**Comment by meteorcloudy** [comment] 2017-09-20 09:30
Cool, let's wait for the next release.

**Comment by grandseiken** [comment] 2017-09-21 10:43
On 0.6 our custom crosstool needed updated to replace `copts` to `user_compile_flags`, but I don't see a release note about this currently.

**Comment by mhlopko** [comment] 2017-09-21 14:25
@grandseiken correct, there is no release note, but neither was about copts availability. I tried to keep my changes under the radar so people will only start using it when I'm fully done. I didn't know that improbable.io has a custom crosstool with 'no_legacy_features'. I can ping you with next changes (I only expect 3 more coming).

**Comment by damienmg** [comment] 2017-09-22 10:32
https://github.com/bazelbuild/bazel/commit/7b091c1397a82258e26ab5336df6c8dae1d97384 to cherrypick

**Comment by grandseiken** [comment] 2017-09-22 10:50
@mhlopko no worries, that stuff is all undocumented anyway. If you have the chance to ping me that'd be great but no biggie.

**Comment by vladmos** [comment] 2017-09-22 12:02
Created RC3
Baseline: 87cc92e5df35d02a7c9bc50b229c513563dc1689
Cherry-pick: a615d288b008c36c659fdc17965207bb62d95d8d
Cherry-pick: 7b091c1397a82258e26ab5336df6c8dae1d97384

**Comment by petemounce** [comment] 2017-09-22 15:35
https://chocolatey.org/packages/bazel/0.6.0-rc3 is available.

**Comment by vladmos** [comment] 2017-09-25 16:31
I had to cherry-pick another commit because otherwise there was a regression in tracebacks.

Created RC3
Baseline: 87cc92e5df35d02a7c9bc50b229c513563dc1689
Cherry-pick: a615d288b008c36c659fdc17965207bb62d95d8d
Cherry-pick: 7b091c1397a82258e26ab5336df6c8dae1d97384
Cherry-pick: 95b0467e3eb42a8ce8d1179c0c7e1aab040e8120

**Comment by vladmos** [comment] 2017-09-26 10:34
Created RC5
Baseline: 87cc92e5df35d02a7c9bc50b229c513563dc1689
Cherry-pick: a615d288b008c36c659fdc17965207bb62d95d8d
Cherry-pick: 7b091c1397a82258e26ab5336df6c8dae1d97384
Cherry-pick: 95b0467e3eb42a8ce8d1179c0c7e1aab040e8120
Cherry-pick: cc9c2f07127a832a88f27f5d72e5508000b53429

**Comment by petemounce** [comment] 2017-09-26 20:56
https://chocolatey.org/packages/bazel/0.6.0-rc5 is available now (so is 4, belatedly). It's lovely in Kefalonia right now, highly recommend. ;)

**Comment by ola-rozenfeld** [comment] 2017-09-27 13:49
Hi!
We really need to have 7744b86e9c7950da62e87bfff3967c67477a1620 and https://github.com/bazelbuild/bazel/commit/6f32d5a7d75ff46de6efc557c1ea95777ea813ca in the release. First is a bugfix for BES, and second enables logging on our end, which is crucial for us.
Thank you!

**Comment by dslomov** [comment] 2017-09-27 14:01
Next release is 0.7, cut on Oct 2nd. We can also consider a patch release, 0.6.1, with these cherrypicks; but none of commits  7744b86 and 6f32d5a fix regressions from 0.5.4 afaics.

**Comment by ola-rozenfeld** [comment] 2017-09-27 14:05
You mean 0.7 will be out on Oct 7? If so, we can wait for that. https://github.com/bazelbuild/bazel/commit/7744b86e9c7950da62e87bfff3967c67477a1620 actually does fix a previous regression, introduced in https://github.com/bazelbuild/bazel/commit/562fcf9f5dfd14daea718f77da95b43b1400689b. willsc@ has asked me to ask you to patch it in, please, unless it's too much trouble. They are using my patched version instead of the release for this reason.

**Comment by dslomov** [comment] 2017-09-27 14:12
I suggest that you wait for 0.7. RC will be available on Oct 2, and then you can use that.

**Comment by ola-rozenfeld** [comment] 2017-09-27 14:37
OK, we will do that, thank you! Btw, when will the release 0.6.0 come out?

**Comment by damienmg** [comment] 2017-09-27 15:00
Tomorrow unless we discover a regression.

**Comment by vladmos** [comment] 2017-09-29 12:27
0.6.0 is released. @petemounce please upload it to Chocolatey.

**Comment by petemounce** [comment] 2017-09-29 13:08
https://chocolatey.org/packages/bazel/0.6.0 is available now.

**Comment by vladmos** [comment] 2017-09-29 13:26
Thanks!
It's also available on Homebrew.

**Closed by vladmos** 2017-09-29 13:26 UTC
Labels: category: misc > release / binary, P1, release, Release blocker, type: process
