### ISSUE TITLE
Faulty visibility usage gives hard to understand errors when the build graph contains constraints that are not supported by the host platform

### ISSUE THREAD

**Issue by burkpojken** [bazelbuild/bazel#13176] opened 2021-03-08 15:32 UTC
### Description of the problem / feature request:

Faulty visibility targets are analyzed with host tool chain.
If the visibility is set to a real target instead of a package it is normally detected and an error is printed with a good explanation.
So if  visibility = ["//test_visibility:dummy"], the error will be
`//test_visibility:dummy' does not refer to a package group`

If the target target use constraints for selecting e.g. headers and the constraint is not fulfilled by the host platform you get an error that is hard to understand. The error can be caused by a fault deep down in the build graph which makes it even harder to understand what the actual fault is.

Example of error:
```
Configurable attribute "hdrs" doesn't match this configuration (would a default condition help?).
Conditions checked:
 //test_visibility:my_os
```

BUILD file example:
```
config_setting(
    name = "my_os",
    constraint_values = ["@my_platforms//platforms/os:my_os"],
)

cc_library(
    name = "lib",
    visibility = ["//test_visibility:dummy"],
)

cc_library(
    name = "dummy",
    hdrs = select({
        ":my_os": glob([
            "*.h",
        ]),
    }),
)
```

Build command that gives a hard to understand error
`bazel build :lib --platforms=@my_platforms//platforms:my_platform`

If the host platform is specified the correct error is seen
`bazel build :lib --platforms=@my_platforms//platforms:my_platform --host_platform=@my_platforms//platforms:my_platform
`
If the checking of the sanity of visibility was done earlier the correct error could be printed instead

### Feature requests: what underlying problem are you trying to solve with this feature?
Better error message for faulty visibility.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

See description

### What operating system are you running Bazel on?

Linux

### What's the output of `bazel info release`?

4.0.0

###  Have you found anything relevant by searching the web?

No

**Comment by gregestren** [comment] 2021-05-03 20:08
Thanks for this report, @burkpojken .

I'm not sure the other error is because of visibility. It looks to me like that error means `//test_visibility:my_os` simply doesn't match the target platform specified with `--platforms`.

Would you mind including your `BUILD` and `WORKSPACE` definitions in `@my_platforms` to make a complete reproduction? Or ideally share a branch I can simply patch in? That could get us a more precise answer.

Also, while this doesn't answer your question, note https://github.com/bazelbuild/bazel/commit/3d33d7b2dea8b4ea92162cc18b1ed2c7c31ad6e6  which tries to make the error message you see more informative.

**Comment by burkpojken** [comment] 2021-05-10 06:07
The problem is not the platform, I have tried to reduce the problem to not involve platform below.
The problem I try to highlight is that  you get an error pointing at a dependency and not where the actual fault is.

New example:
```
config_setting(
    name = "fastbuild",
    values = {"compilation_mode": "fastbuild"}
)

cc_library(
    name = "lib",
    deps = ["//:dummy"],
    visibility = ["//:dummy"], # Faulty visibility
    # visibility = ["//:__pkg__"], # Correct visibility
)

cc_library(
    name = "dummy",
   hdrs = select({
       ":fastbuild": glob([
           "*.h",
       ]),
   }),
)
```
Build with: 
bazel build :lib
Gives the error:
```
BUILD:15:11: Configurable attribute "hdrs" doesn't match this configuration (would a default condition help?).
Conditions checked:
 //:fastbuild
ERROR: Analysis of target '//:lib' failed; build aborted: Configurable attribute "hdrs" doesn't match this configuration (would a default condition help?).
Conditions checked:
 //:fastbuild
```
Note It does not matter if I add --compilation_mode=fastbuild

If the visibility is corrected the build is successful.

**Comment by gregestren** [comment] 2021-05-10 20:10
Thanks for the clarification.

Nice catch! This is an interesting falling between the API cracks. The problem is that Bazel tries to evaluate `//:dummy` under the `visibility` attribute, which includes resolving the `select()`, *before* it goes through the standard error checking that says "you can't set visibility to an arbitrary target".

`visibility` configures its deps in the `host` configuration: https://github.com/bazelbuild/bazel/blob/ea3fc394a867784f325147cb31c78934bd656956/src/main/java/com/google/devtools/build/lib/analysis/BaseRuleClasses.java#L292

which sets `--compilation_mode=opt`: https://github.com/bazelbuild/bazel/blob/e5a170ff21acbbe7cd889055c406e7dc10182b9b/src/main/java/com/google/devtools/build/lib/analysis/config/CoreOptions.java#L231

So the `config_setting` doesn't match and you get the reported error. I'd expect the same result for the original platforms-based version.

So yes, this is a legit error. Thanks for reporting.

**Comment by aranguyen** [comment] 2021-12-16 15:17
fixed by this commit https://github.com/bazelbuild/bazel/commit/e10873ce52ca81822dbeec8b49baf775f9c28a80 in 6.0.0-pre.20211117.1

**Closed by aranguyen** 2021-12-16 15:17 UTC
Labels: type: bug, P1, team-Configurability
