### ISSUE TITLE
baseline_coverage.dat is not a valid lcov file

### ISSUE THREAD

**Issue by engineerCYB** [bazelbuild/bazel#8324] opened 2019-05-15 00:30 UTC
### Description of the problem / feature request:

The "baseline_coverage.dat" file created by "bazel coverage" does not appear to be a valid lcov coverage file. It contains only "SF:" tags, but at least "DA:" tags are also required.

### Feature requests: what underlying problem are you trying to solve with this feature?

I am trying to generate an html coverage report. Baseline files are required in order to ensure that files that have zero coverage (and therefore don't generate a gcda file) still show up in the report.

#### First demonstrate that baseline_coverage.dat is broken:
```
$ cat mypackage/BUILD 
cc_library(
    name="my_lib",
    srcs=["lib.c"],
    hdrs=["lib.h"],
)

cc_test(
    name="my_test",
    srcs=["test.c"],
    deps=[":my_lib"],
)

$ bazel coverage //mypackage:my_test
//mypackage:my_test                                                      PASSED in 0.5s

$ cat bazel-testlogs/mypackage/my_test/baseline_coverage.dat 
SF:mypackage/lib.c
end_of_record
SF:mypackage/lib.h
end_of_record

$ lcov --list bazel-testlogs/mypackage/my_test/baseline_coverage.dat 
Reading tracefile bazel-testlogs/mypackage/my_test/baseline_coverage.dat
lcov: ERROR: no valid records found in tracefile bazel-testlogs/mypackage/my_test/baseline_coverage.dat

$ genhtml bazel-testlogs/mypackage/my_test/baseline_coverage.dat 
Reading data file bazel-testlogs/mypackage/my_test/baseline_coverage.dat
Resolved relative source file path "mypackage/lib.c" with CWD to "/src/apollo/mypackage/lib.c".
genhtml: ERROR: no valid records found in tracefile bazel-testlogs/mypackage/my_test/baseline_coverage.dat
```

#### Now show what a working baseline file should look like:
```
$ lcov --capture --initial --directory bazel-bin/mypackage/ --output-file baseline_working.dat
Capturing coverage data from bazel-bin/mypackage/
Found gcov version: 4.8.4
Scanning bazel-bin/mypackage/ for .gcno files ...
Found 2 graph files in bazel-bin/mypackage/
Processing my_test/test.gcno
Processing my_lib/lib.gcno
Finished .info-file creation

$ cat baseline_working.dat 
TN:
SF:/src/workspace/mypackage/test.c
FN:3,main
FNDA:0,main
FNF:1
FNH:0
DA:3,0
DA:4,0
DA:5,0
DA:7,0
DA:9,0
LF:5
LH:0
end_of_record
TN:
SF:/src/workspace/mypackage/lib.c
FN:3,fib
FNDA:0,fib
FNF:1
FNH:0
DA:3,0
DA:4,0
DA:5,0
DA:6,0
DA:7,0
DA:9,0
DA:11,0
LF:7
LH:0
end_of_record

$ lcov --list baseline_working.dat 
Reading tracefile baseline_working.dat
            |Lines       |Functions  |Branches    
Filename    |Rate     Num|Rate    Num|Rate     Num
==================================================
[/src/workspace/mypackage/]
lib.c       | 0.0%      7| 0.0%     1|    -      0
test.c      | 0.0%      5| 0.0%     1|    -      0
==================================================
      Total:| 0.0%     12| 0.0%     2|    -      0

$ genhtml --output-directory coverage baseline_working.dat 
Reading data file baseline_working.dat
Found 2 entries.
Found common filename prefix "/src/workspace"
Writing .css and .png files.
Generating output.
Processing file mypackage/lib.c
Processing file mypackage/test.c
Writing directory view page.
Overall coverage rate:
  lines......: 0.0% (0 of 12 lines)
  functions..: 0.0% (0 of 2 functions)
```
### What operating system are you running Bazel on?

Ubuntu 14.04

### What's the output of `bazel info release`?

release 0.25.0

### Any other information, logs, or outputs that you want to share?

I'm not totally clear on the purpose of the baseline_coverage.dat file if the current contents are expected to be correct. How should I use this file when generating a coverage report?

**Comment by hlopko** [comment] 2019-06-07 08:47
CC @iirina can you pls shed some light there? Thank you!

**Comment by iirina** [comment] 2019-06-24 12:40
@engineerCYB thanks for the report!

The baseline coverage format is:

```
SF:File1
end_of_record
SF:File2
end_of_record
...
```

which is a valid lcov format. The error you're getting is because genthml doesn't find any coverage data so it can't create a report. The baseline coverage report is an intermediate artifact and its purpose is to make sure all the files are included in the final coverage report. I assume it doesn't include all the `DA:` lines with zero coverage because it's not useful information to bazel. I'm not sure why it's included in the output artifacts. IIRC baseline coverage is included for Java, but not yet for C++. See #5716. Can you describe why you're generating html report from baseline coverage and how does it fit into your computing coverage workflow? 

In theory the users shouldn't parse the baseline report themselves, but leave it up to bazel to deal with it in the final coverage report. I'll close this as a duplicate of #5716.

**Closed by iirina** 2019-06-24 12:40 UTC
Labels: P3, team-Rules-Server, type: bug

**Comment by engineerCYB** [comment] 2019-07-11 16:53
@iirina 

This issue should not be closed. The file format is invalid as a baseline file for any lcov tools that expect a baseline file that I know of. The main usage of baseline files is with the "--baseline-file" option to "genhtml". My example above was simplified, but you will see that even conventional baseline-file usage fails with the same error. For example, from above:

```
$ bazel coverage //mypackage:my_test
//mypackage:my_test                                                      PASSED in 0.5s

# Let's try to generate a real coverage report
$ genhtml --baseline-file bazel-testlogs/mypackage/my_test/baseline_coverage.dat bazel-testlogs/mypackage/my_test/coverage.dat

Reading data file bazel-testlogs/mypackage/my_test/coverage.dat
Reading baseline file bazel-testlogs/mypackage/my_test/baseline_coverage.dat
Reading data file bazel-testlogs/mypackage/my_test/baseline_coverage.dat
genhtml: ERROR: no valid records found in tracefile baseline_coverage.dat
```

The primary purpose of baseline files that I know of is to get a "0 coverage" report. If you have files that are not invoked by any test, then they won't show up in the coverage.dat file. When you generate an html report, these files won't even show up at all, and the reported coverage % will be artificially high. Including "--baseline-file" (or just passing baseline_coverage.dat as another coverage file) allows genhtml to include all files and produce the proper report. Not including a baseline is a particularly insidious mistake because it hides the thing that you often care about the most: "which files are not covered at all"?

From the lcov man page:

> --initial
>               Capture initial zero coverage data.
> 
>               Run lcov with -c and this option on the directories containing .bb, .bbg or .gcno files before running any test case. The result is a "baseline" coverage data file that contains  zero  coverage  for  every
>               instrumented  line.   **Combine this data file (using lcov -a) with coverage data files captured after a test run to ensure that the percentage of total lines covered is correct even when not all source code
>               files were loaded during the test.**
> ```

**Comment by limdor** [comment] 2020-10-12 18:36
@iirina @hlopko I am aware that this is closed, but would it be possible to set the coverage label? It is just to make it easy to find all related code coverage issues. Thanks
