### ISSUE TITLE
`sh_binary()` / `sh_test()` do not quote arguments

### ISSUE THREAD

**Issue by dgp1130** [bazelbuild/bazel#13072] opened 2021-02-20 06:54 UTC
### Description of the problem / feature request:

`sh_binary()` and `sh_test()` do not quote their arguments. This means any argument with a space in it is treated as multiple arguments to the script. This is unintuitive and error prone.

### Feature requests: what underlying problem are you trying to solve with this feature?

I originally ran into this bug while making an `sh_test()` that includes some arguments. When I attempted this, I was getting an "unterminated quotation" error which I eventually traced back to using the word `I'm` in an `sh_test()` argument. This argument was not being quoted, requiring me to escape it before passing into `args`, which is awkward and brittle.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

My original error came from using one single quote character in an `args` attribute. However, the issue is a little more clear if we instead use a space. Consider the following shell script and `sh_binary()`:

```shell
# echo.sh

# Print all arguments, one per line.
for ARG in $@; do
    echo "${ARG}"
done
```

```python
# BUILD.bazel

sh_binary(
    name = "echo",
    srcs = ["echo.sh"],
    args = ["foo", "bar baz"],
)
```

What do you expect this to print? The script prints each argument on its own line, and two arguments are provided, so I expect it to print:

```
foo
bar baz
```

However, when you actually run this, you will find that it prints:

```
$ bazel run //:echo
foo
bar
baz
```

Changing the `sh_binary()` to `sh_test()` and using `blaze aquery` makes the problem more clear:

```
$ bazel aquery //:echo
# ...
Command Line: (exec external/bazel_tools/tools/test/test-setup.sh \
    echo \
    foo \
    bar \
    baz)
```

Note that the echo command is passed three arguments, with `bar` and `baz` separated. I would expect this command to be `echo foo "bar baz"`.

If you update the BUILD file to include a single quote and run it, you will see an "unterminated quotation" error:

```
# BUILD.bazel

sh_test(
    name = "echo",
    srcs = ["echo.sh"],
    args = ["foo", "I'm"],
)
```

```
$ bazel test //:echo
ERROR: /home/dparker/Source/rules_prerender/BUILD.bazel:18:1: in args attribute of sh_test rule //:echo: unterminated quotation
```

### What operating system are you running Bazel on?

Ubuntu 20.04 via WSL2 on Windows 10

### What's the output of `bazel info release`?

release 3.0.0

### Any other information, logs, or outputs that you want to share?

It's possible this is intended behavior, but I have a hard time thinking this is more intuitive than the alternative. At the very least we could do a better job of [documenting this behavior](https://docs.bazel.build/versions/master/be/shell.html).

**Comment by aiuto** [comment] 2021-02-21 02:50
This is essentially a duplicate of #12313   Let's keep the discussion there.

**Closed by aiuto** 2021-02-21 02:50 UTC
Labels: untriaged
