### ISSUE TITLE
Source forest creation failed

### ISSUE THREAD

**Issue by abergmeier-dsfishlabs** [bazelbuild/bazel#2454] opened 2017-01-31 11:07 UTC
### Description of the problem / feature request / question:
Running `bazel build foo` leads to error:

    ERROR: Source forest creation failed: C:/tools/msys64/tmp/_bazel_a.bergmeier/dXgGrvqy/execroot/tools/external/org_python (Directory not empty).

### If possible, provide a minimal example to reproduce the problem:
I had Bazel started with:

    BAZEL_PYTHON = "C:/great/path/python2/python.exe"

Then I changed it to:

    BAZEL_PYTHON = "C:/great/path/python3/python.exe"

This after that, `bazel build` produced the error. As @meteorcloudy pointed out might be totally unrelated, though.

### Environment info
* Operating System: Windows 10

* Bazel version (output of `bazel info release`): 855fbe9ee447b7b37fd8c73dbc047d69b7ceffcf

###  Have you found anything relevant by searching the web? (e.g. GitHub issues, email threads in the [bazel-discuss@googlegroups.com](https://groups.google.com/forum/#!forum/bazel-discuss) archive)
Nope

**Comment by meteorcloudy** [comment] 2017-01-31 12:26
`BAZEL_PYTHON` is only used in cc_configure.bzl, are you sure this error is causing by changing it?
And what is `org_python`?

**Comment by abergmeier-dsfishlabs** [comment] 2017-01-31 13:30
> BAZEL_PYTHON is only used in cc_configure.bzl, are you sure this error is causing by changing it?
And what is org_python?

`org_python` is just a Python installation which we gather as an external repo.
Might not be related. Sorry for the bad description. Updated the issue.

**Comment by abergmeier-dsfishlabs** [comment] 2017-01-31 13:31
Only happened once. Clearing `execroot` made it go away.

**Comment by dslomov** [comment] 2017-02-14 11:14
Closing because not reproducible

**Closed by dslomov** 2017-02-14 11:14 UTC
Labels: category: multi-platform > windows, category: rules > python, Under investigation
