### ISSUE TITLE
`bazel query //external:` is not consistent with what Bazel actually does

### ISSUE THREAD

**Issue by lberki** [bazelbuild/bazel#13288] opened 2021-04-01 07:33 UTC
If one overrides a repository in the `WORKSPACE` file that is also present in the default workspace suffix, `bazel query` will report the definition in the default workspace suffix but Bazel will use the version in the WORKSPACE file.

Example WORKSPACE file:

```
local_repository(name="rules_cc", path="/somewhere/where/there/is/a/rules_cc/tree")
```

`bazel query --output=build //external:rules_cc` will report that the repository is a `http_archive()` because that's how it's defined in `cc_configure.WORKSPACE`, but when running `bazel query @rules_cc//...` and inspecting `$OUTPUT_BASE/external`, it's apparent that the `local_repository` took effect.

This is because:
* `BazelRulesModule.initializeRuleClasses()` adds a definition for `@rules_cc` in `cc_configure.WORKSPACE` that's not guarded by a `maybe()` statement 
* `bazel query` works by looking at `ExternalPackageFunction`, which runs every chunk and reports the state of the package at the end
* `RepositoryDelegatorFunction.getRepository()` works by finding the first chunk that contains the desired repository

Ideally, one would simply disallow redefinition of repositories like that (I'm surprised that we allow it in the first place). Absent that, symptomatic treatment would be to wrap the definition of `@rules_cc` in `cc_configure.WORKSPACE` in a `maybe()` call.

**Comment by Wyverald** [comment] 2021-04-07 12:22
This is essentially a dupe of https://github.com/bazelbuild/bazel/issues/12947.

Your description of the cause of the bug is exactly as I understand it, but the fix should probably be that we fix `blaze query` to behave according to what is fetched (ie. like RepositoryDelegatorFunction). We probably allow redefinition of repositories because of the deps.bzl pattern (only guessing here). We _do_ disallow redefinition of `local_repository` as far as I know.

**Closed by Wyverald** 2021-04-07 12:22 UTC
Labels: area-ExternalDeps, untriaged
