### ISSUE TITLE
Bazel should not make remote connections for non-build-related commands

### ISSUE THREAD

**Issue by illicitonion** [bazelbuild/bazel#18967] opened 2023-07-18 09:15 UTC
### Description of the bug:

Right now, if you run `bazel info --remote_executor=grpcs://blah` Bazel will execute a GetCapabilities request against the server.

`bazel info` doesn't actually need to be able to perform remote execution.

Bazel should avoid doing this, as it slows down the command (and may fail).

### What is the output of `bazel info release`?

release 6.2.0

**Comment by tjgq** [comment] 2023-07-18 11:22
I believe https://github.com/bazelbuild/bazel/pull/18794 would also address this issue.

**Comment by stagnation** [comment] 2023-08-25 14:57
Good, I once realized that a misconfigured RBE will fail before `--announce_rc` prints which RBE it tries to connect to, and where the flag comes from. But never got around to writing a report for that.

**Comment by coeuvre** [comment] 2023-08-28 12:23
Duplicate of #18760.

**Closed by coeuvre** 2023-08-28 12:23 UTC
Labels: type: bug, P3, team-Remote-Exec, help wanted
