### ISSUE TITLE
repository_ctx.download and download_and_extract should use `.netrc`

### ISSUE THREAD

**Issue by shs96c** [bazelbuild/bazel#18851] opened 2023-07-06 15:02 UTC
### Description of the feature request:

A frequent way of providing necessary credentials for accessing remote resources is to use a `.netrc` and add entries to that.

Utility macros like `http_archive` and `http_file` have extra code that read the user's `.netrc` and automatically adds the auth credentials, leading many to believe that `repository_ctx.download` does this already. It does not, but it would be nice if it did.

### What underlying problem are you trying to solve with this feature?

Network access should use the credentials provided by the user where possible, and do so automatically.

### Which operating system are you running Bazel on?

macOS

### What is the output of `bazel info release`?

6.2.0

**Comment by Wyverald** [comment] 2023-07-11 20:54
dupe of https://github.com/bazelbuild/bazel/issues/13709

**Closed by Wyverald** 2023-07-11 20:54 UTC
Labels: type: feature request, team-ExternalDeps, untriaged
