### ISSUE TITLE
sh_test siblings are available to shell script even if not listed in data attribute of sh_test rule

### ISSUE THREAD

**Issue by rightfold** [bazelbuild/bazel#7000] opened 2018-12-26 20:56 UTC
### Description of the problem / feature request:

With the following example:

```
$ cat WORKSPACE
$ cat BUILD
sh_test(
    name = "integration_test",
    srcs = [":integration_test.rb"],
)
$ cat integration_test.rb
#!/usr/bin/env ruby
require_relative 'foo.rb'
$ cat foo.rb
print 'hi'
```

The test passes, even though foo.rb is not listed anywhere in the BUILD file. The test should fail because the file doesn't exist and can't be sourced, but it passes because Bazel puts foo.rb in the execroot nonetheless.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

See above. Make sure integration_test.rb is executable.

And indeed: Bazel will not pick up changes to foo.rb, and thus caching problems will occur. For example:

 1. Run the test and observe that it succeeds.
 2. Change foo.rb contents to "exit 1" but do not touch other files.
 3. Run the test again and observe that it is cached/succeeds.
 4. bazel clean
 5. Run again and observe that the test fails.

If you list :foo.rb in the sh_test data attribute, and repeat the above steps, you will see that the behavior is as expected: changes to foo.rb are picked up and the cache eviction happens as needed.

### What operating system are you running Bazel on?

Linux 4.14.74 NixOS SMP x86_64 GNU/Linux

### What's the output of `bazel info release`?

release 0.16.1

###  Have you found anything relevant by searching the web?

It is very hard to find anything relating to making Bazel builds fail due to dependencies not being explicitly listed. It's a subtle issue that is hard to overlook since things seem to work the first time.

### Any other information, logs, or outputs that you want to share?

I had a hard time finding documentation about which files are available in the execroot, or what the execroot really is. This could be improved.

**Comment by jmmv** [comment] 2019-01-18 19:24
If you do not enable sandboxing, then the test runs from its original location and, as you can imagine, it can find other files. This is working as intended.

If you do enable sandboxing (the default in Bazel), then the test should fail as you expect.

Unfortunately... the current sandbox implementation is not strong enough. The way the current sandbox works is by creating a tree of symlinks that matches your source tree for the declared files. If you run with `--sandbox_debug` and inspect the sandbox directory location under the output base, you'll see that Bazel only put `integration_test.rb` within it. But... that's a symlink to the original file. When the program gets run, Ruby actually thinks it's running from the source tree and therefore it can find the import.

There is no possible solution to this in the current symlink-based sandbox implementation.

If you use the new `--experimental_use_sandboxfs` feature, which implements a stricter and faster form of sandboxing, the test fails as you expect. (Confirmed locally.)

Strictly speaking, we could investigate using AFPS' COW on macOS instead of symlinks, which would fix this problem too. I'm not sure how we'd expose this because the sandbox's behavior would be subject to the underlying file system and configured mount points, which might make its functionality even more obscure. Further I don't know if there is anything similar on Linux and the myriad file systems there. I don't think it's worth going this route so I'll close this for now... but if you disagree, please let me know.

**Closed by jmmv** 2019-01-18 19:24 UTC
Labels: team-Local-Exec, untriaged
