### ISSUE TITLE
"foo-bar is not a legal workspace name" error is reported on Bazel@HEAD

### ISSUE THREAD

**Issue by davido** [bazelbuild/bazel#11837] opened 2020-07-25 13:45 UTC
It seems that on Bazel@HEAD (e6cce762d846f3915b834c278fcb7fa0072ea530) hyphen character is not accepted any more in workspace name?

```java
/** A collection of global Starlark build API functions that apply to WORKSPACE files. */
public class WorkspaceGlobals implements WorkspaceGlobalsApi {

  // Must start with a letter and can contain letters, numbers, and underscores
  private static final Pattern LEGAL_WORKSPACE_NAME = Pattern.compile("^\\p{Alpha}\\w*$");

```
Am I missing something? I see these errors:

```bash
 $ bazel build org.eclipse.jgit.ssh.apache/...
[...]
ERROR: /home/davido/.cache/bazel/_bazel_davido/e1ee1c2b4d81e57e5c4b6fbb219eece8/external/sshd-osgi/WORKSPACE:2:10: sshd-osgi is not a legal workspace name
ERROR: /home/davido/.cache/bazel/_bazel_davido/e1ee1c2b4d81e57e5c4b6fbb219eece8/external/sshd-sftp/WORKSPACE:2:10: sshd-sftp is not a legal workspace name
ERROR: /home/davido/.cache/bazel/_bazel_davido/e1ee1c2b4d81e57e5c4b6fbb219eece8/external/log-api/WORKSPACE:2:10: log-api is not a legal workspace name
INFO: Analyzed target //org.eclipse.jgit.ssh.apache:ssh-apache (28 packages loaded, 1339 targets configured).
INFO: Found 1 target...
```

The error is reported for the `workspace` line, e.g. in `external/log-api/WORKSPACE:2:10`:

```python
# DO NOT EDIT: automatically generated WORKSPACE file for maven_jar rule
workspace(name = "log-api")
```

The build still succeeds.

**Comment by thii** [comment] 2020-07-27 00:57
It looks like the hyphen character has never been accepted in a workspace name. But for some reason, Bazel didn't error out in some cases; for instance, new workspaces declared with `new_git_repository`.

**Comment by davido** [comment] 2020-07-27 04:59
> It looks like the hyphen character has never been accepted in a workspace name.

Gerrit Code Review and JGit projects are using hyphen character in workspace names for years, started from Bazel 0.6.

**Comment by laurentlb** [comment] 2020-08-13 10:01
Do you have a repro for this? I'd like to understand what changed exactly.

I had the same error with Bazel 3.4.1 (and previous versions):
```
$ cat WORKSPACE
workspace(name = "log-api")
$ bazel --version
bazel 3.4.1
$ bazel build :all
ERROR: /tmp/bzl/WORKSPACE:1:10: log-api is not a legal workspace name
```

**Comment by laurentlb** [comment] 2020-08-13 10:11
Repro:

```
$ cat WORKSPACE
local_repository(
    name = "busybox",
    path = "sub",
)

$ cat sub/WORKSPACE 
workspace(name = "busybox_1.25.0")

$ USE_BAZEL_VERSION=3.4.1 bazelisk build @busybox//...
INFO: Analyzed 0 targets (0 packages loaded, 0 targets configured).
INFO: Found 0 targets...
INFO: Elapsed time: 0.300s, Critical Path: 0.01s
INFO: 0 processes.
INFO: Build completed successfully, 1 total action

$ USE_BAZEL_VERSION=3.5.0rc2 bazelisk build @busybox//...
Starting local Bazel server and connecting to it...
ERROR: Traceback (most recent call last):
	File "/usr/local/google/home/laurentlb/.cache/bazel/_bazel_laurentlb/1cf9e271f53a4fcee3da31675bf7c3a0/external/busybox/WORKSPACE", line 1, column 10, in <toplevel>
		workspace(name = "busybox_1.25.0")
Error in workspace: busybox_1.25.0 is not a legal workspace name
INFO: Analyzed 0 targets (1 packages loaded, 0 targets configured).
INFO: Found 0 targets...
INFO: Elapsed time: 2.521s, Critical Path: 0.03s
INFO: 0 processes.
INFO: Build completed successfully, 1 total action
```

**Comment by davido** [comment] 2020-08-13 10:16
Yes. Try to build gerrit project from HEAD:

```
  $ bazel build :gerrit
```

With 3.4.1 it worked, no errors reported even with "foo-bar" project names.
In 3.5.1rc1 it is reporting errors. I haven't bisected that regression though.

**Comment by laurentlb** [comment] 2020-08-13 10:58
Root cause: https://github.com/bazelbuild/bazel/commit/2436a358f464ea75b6308dd530c5cce0adde2ebc

cc @michajlo

**Comment by michajlo** [comment] 2020-08-13 14:13
https://github.com/bazelbuild/bazel/issues/11837#issuecomment-664066558 is correct, it appears allowing hyphens was a misbug.

**Comment by aiuto** [comment] 2020-08-13 16:02
@davido: This looks like log spam rather than a build failure.  

There seem to be entirely different paths forward
1. Revert the change to allow hyphens, people ignore the error messages for now. (with variations on maybe adding an ability to silence the message).
2. Change the api to allow hyphens and dots.

We will need  @alandonovan to weigh in on the choice.

**Comment by davido** [comment] 2020-08-13 17:22
> There seem to be entirely different paths forward

I see another option:

Revert the root cause for this regression: 2436a35 and accept dot and hyphens in point release 3.5.

Announce that starting from Bazel 4.0 dot and hyphens are not supported any more in workspace names and roll forward: 2436a35. Moreover change the API and make it no only log spam but a real build breakage.

**Comment by ulfjack** [comment] 2020-08-15 22:25
TensorFlow also uses hyphens in workspace names, at least in some cases:
```
ERROR: Traceback (most recent call last):
	File "/home/ulfjack/.cache/bazel/_bazel_ulfjack/e1ebd4c707b223a2af1441f90d605454/external/ubuntu16.04-manylinux2010-py3_config_platform/WORKSPACE", line 2, column 10, in <toplevel>
		workspace(name = "ubuntu16.04-manylinux2010-py3_config_platform")
Error in workspace: ubuntu16.04-manylinux2010-py3_config_platform is not a legal workspace name
ERROR: Traceback (most recent call last):
	File "/home/ulfjack/.cache/bazel/_bazel_ulfjack/e1ebd4c707b223a2af1441f90d605454/external/ubuntu16.04-manylinux2010-py3_config_python/WORKSPACE", line 2, column 10, in <toplevel>
		workspace(name = "ubuntu16.04-manylinux2010-py3_config_python")
Error in workspace: ubuntu16.04-manylinux2010-py3_config_python is not a legal workspace name
```

**Comment by davido** [comment] 2020-08-16 07:02
> TensorFlow also uses hyphens in workspace names, at least in some cases:

Note, that in latest rc the hyphen char is accepted. In the error message you pasted: `ubuntu16.04-manylinux2010-py3_config_python` the problematic char is dot and not the hyphen.

**Comment by alandonovan** [comment] 2020-08-17 14:11
I agree that we should allow hyphens; this is now done. I would go a step further and say we should allow any printable character except '@', ':', and '/'.  (These are the minimal restrictions for label processing.)

(I regard Blaze's totalitarian inspection of every string it accepts as a youthful mistake.)

**Comment by michajlo** [comment] 2020-08-17 14:35
> ... we should allow any printable character except the three required for label parsing: @, :, and /.

Let's keep it to just the things we need for now... As we've observed here it's a lot easier to allow a new char than realize we made a mistake and try to take it back.

**Comment by davido** [comment] 2020-08-17 15:00
> Let's keep it to just the things we need for now...

That would mean that we should allow dot character and we are done, right (hyphen was already added in my recent PR)?

**Comment by michajlo** [comment] 2020-08-17 15:02
Correct.

**Comment by aiuto** [comment] 2020-08-17 15:15
I'm counting this as concensus.
- I will shortly send a PR to allow dot in the name.
- When it lands I will cherrypick into the next Bazel 3.5 rc.

**Comment by laurentlb** [comment] 2020-08-17 15:22
I'm not sure this cherrypick is necessary. The root cause is that Bazel will evaluate and report errors from workspace files when it shouldn't.

The use of dot and dashes is just one example from the bug report above. That doesn't mean anything regarding what symbols the other projects are using.

**Comment by aiuto** [comment] 2020-08-18 13:42
@davido This should be resolved in 3.5.0rc3 in 2 ways.
- Hyphens and dots are both allowed
- We no longer parse external WORKSPACE files just to find their name (and then ignore it).

I've done my own local tests on the candidate. Please LMK if you still see this issue with that.

**Comment by davido** [comment] 2020-08-18 14:19
@aiuto Thanks. Will test 3.5.0rc3 later today and let you know the result.

**Comment by aiuto** [comment] 2020-08-18 18:40
You're the best.

**Comment by davido** [comment] 2020-08-19 04:58
> Will test 3.5.0rc3 later today and let you know the result.

Confirmed, that 3.5.0rc3 works as expected. Thanks again for your help.

**Closed** 2020-08-26 02:30 UTC
Labels: release blocker, team-XProduct, type: feature request, untriaged
