### ISSUE TITLE
0.2.3 doesn't run on ubuntu 12.04

### ISSUE THREAD

**Issue by colinmarc** [bazelbuild/bazel#1336] opened 2016-06-03 21:03 UTC
After installing on a fairly clean system with `bazel-0.2.3-installer-linux-x86_64.sh`:

```
$ bazel help
/usr/local/bin/bazel: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.18' not found (required by /usr/local/bin/bazel)
/usr/local/bin/bazel: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.19' not found (required by /usr/local/bin/bazel)
```

**Comment by meteorcloudy** [comment] 2016-06-06 08:31
Hi, Damien. Can you take a look at this error. I can reproduce this error in docker, but have no idea how to solve it. /cc @damienmg

**Comment by damienmg** [comment] 2016-06-06 08:34
We do not support 12.04 with the installer, please compile from source.

**Comment by colinmarc** [comment] 2016-06-06 15:29
Compilation doesn't work on 12.04, either:

```
$ ./compile.sh
INFO: You can skip this first step by providing a path to the bazel binary as second argument:
INFO:    ./compile.sh compile /path/to/bazel
🍃  Building Bazel from scratch......
🍃  Building Bazel with Bazel.
.WARNING: /tmp/bazel.m39r9fI4/out/external/bazel_tools/WORKSPACE:1: Workspace name in /tmp/bazel.m39r9fI4/out/external/bazel_tools/WORKSPACE (@io_bazel) does not match the name given in the repository's definition (@bazel_tools); this will cause a build error in future versions.
WARNING: /home/colin/bazel/src/main/native/BUILD:46:16: in includes attribute of cc_binary rule //src/main/native:libunix.so: '.' resolves to 'src/main/native' not in 'third_party'. This will be an error in the future.
WARNING: /home/colin/bazel/src/main/protobuf/BUILD:37:1: in includes attribute of cc_library rule //src/main/protobuf:command_server_cc_proto: '.' resolves to 'src/main/protobuf' not in 'third_party'. This will be an error in the future. Since this rule was created by the macro 'cc_grpc_library', the error might have been caused by the macro implementation in /home/colin/bazel/tools/build_rules/genproto.bzl:104:18.
INFO: Found 1 target...
ERROR: /home/colin/bazel/src/main/cpp/BUILD:7:1: C++ compilation of rule '//src/main/cpp:blaze_util' failed: gcc failed: error executing command
  (cd /tmp/bazel.m39r9fI4/out/bazel && \
  exec env - \
    PATH=/usr/lib/rbenv/shims:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games \
  /usr/bin/gcc -U_FORTIFY_SOURCE '-D_FORTIFY_SOURCE=1' -fstack-protector -Wall -Wl,-z,-relro,-z,now -B/usr/bin -B/usr/bin -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer '-std=c++0x' -DBLAZE_OPENSOURCE -iquote . -iquote bazel-out/local-fastbuild/genfiles -iquote external/bazel_tools -iquote bazel-out/local-fastbuild/genfiles/external/bazel_tools -isystem external/bazel_tools/tools/cpp/gcc3 -no-canonical-prefixes -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' '-frandom-seed=bazel-out/local-fastbuild/bin/src/main/cpp/_objs/blaze_util/src/main/cpp/blaze_util_posix.pic.o' -MD -MF bazel-out/local-fastbuild/bin/src/main/cpp/_objs/blaze_util/src/main/cpp/blaze_util_posix.pic.d -fPIC -c src/main/cpp/blaze_util_posix.cc -o bazel-out/local-fastbuild/bin/src/main/cpp/_objs/blaze_util/src/main/cpp/blaze_util_posix.pic.o): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.
src/main/cpp/blaze_util_posix.cc:106:21: error: expected ';' at end of member declaration
src/main/cpp/blaze_util_posix.cc:106:23: error: 'override' does not name a type
src/main/cpp/blaze_util_posix.cc: In function 'std::string blaze::RunProgram(const string&, const std::vector<std::basic_string<char> >&)':
src/main/cpp/blaze_util_posix.cc:199:1: warning: control reaches end of non-void function [-Wreturn-type]
At global scope:
cc1plus: warning: unrecognized command line option "-Wno-free-nonheap-object" [enabled by default]
Target //src:bazel failed to build
INFO: Elapsed time: 4.988s, Critical Path: 0.93s

**Comment by damienmg** [comment] 2016-06-06 15:33
Which version of gcc is this? I think we are not supporting old gcc either...

Sorry for that :(

**Comment by colinmarc** [comment] 2016-06-06 15:38
I have the system installed gcc: `gcc version 4.6.3 (Ubuntu/Linaro 4.6.3-1ubuntu5)`.

@ianoc determined that the following patch gets it to build:

```
diff --git a/src/main/cpp/blaze.cc b/src/main/cpp/blaze.cc
index f5eaa74..906b48e 100644
--- a/src/main/cpp/blaze.cc
+++ b/src/main/cpp/blaze.cc
@@ -247,11 +247,11 @@ class AfUnixBlazeServer : public BlazeServer {
   AfUnixBlazeServer();
   virtual ~AfUnixBlazeServer() {}

-  bool Connect() override;
-  void Disconnect() override;
-  unsigned int Communicate() override;
-  void KillRunningServer() override;
-  void Cancel() override;
+  bool Connect();
+  void Disconnect();
+  unsigned int Communicate();
+  void KillRunningServer();
+  void Cancel();

  private:
   int server_socket_;
@@ -264,11 +264,11 @@ class GrpcBlazeServer : public BlazeServer {
   GrpcBlazeServer();
   virtual ~GrpcBlazeServer() {}

-  bool Connect() override;
-  void Disconnect() override;
-  unsigned int Communicate() override;
-  void KillRunningServer() override;
-  void Cancel() override;
+  bool Connect();
+  void Disconnect();
+  unsigned int Communicate();
+  void KillRunningServer();
+  void Cancel();

  private:
   enum CancelThreadAction { NOTHING, JOIN, CANCEL };
diff --git a/src/main/cpp/blaze_util_posix.cc b/src/main/cpp/blaze_util_posix.cc
index 112731f..ed37c1e 100644
--- a/src/main/cpp/blaze_util_posix.cc
+++ b/src/main/cpp/blaze_util_posix.cc
@@ -103,7 +103,7 @@ class PipeBlazeServerStartup : public BlazeServerStartup {
  public:
   PipeBlazeServerStartup(int pipe_fd);
   virtual ~PipeBlazeServerStartup();
-  bool IsStillAlive() override;
+  bool IsStillAlive();

  private:
   int pipe_fd;
```

**Comment by damienmg** [comment] 2016-06-06 15:39
So you get it to work?

**Comment by colinmarc** [comment] 2016-06-06 15:40
Well, yes, but it'd be nice to be running an official version =)

**Comment by damienmg** [comment] 2016-06-06 15:43
I know I'll see if we can get a version of this patch merged.

/cc @lberki because he touched that code last: according to the style guide, we are allowed to use virtual instead of override, do you see any blocker in doing so?

**Comment by lberki** [comment] 2016-06-07 06:27
No, it's fine. In theory, we are not bound by the style guide anyway :)

**Closed** 2016-06-07 12:41 UTC
Labels: P2, type: feature request, Under investigation
