### ISSUE TITLE
'remote' is an invalid value for spawn strategy

### ISSUE THREAD

**Issue by schroederc** [bazelbuild/bazel#1256] opened 2016-05-11 17:19 UTC
The instructions at https://github.com/bazelbuild/bazel/blob/79adf59e2973754c8c0415fcab45cd58c7c34697/src/main/java/com/google/devtools/build/lib/remote/README.md no longer work.  `--spawn_strategy=remote` is not recognized.

```
$ bazel build --hazelcast_node=127.0.0.1:5701 --spawn_strategy=remote //...
ERROR: 'remote' is an invalid value for spawn strategy. Valid values are: local, sandboxed, standalone, worker.
```

**Comment by hhclam** [comment] 2016-05-12 13:33
Probably a duplicate of this: https://github.com/bazelbuild/bazel/issues/1026

**Closed** 2016-05-16 17:03 UTC
Labels: Duplicate, type: documentation
