### ISSUE TITLE
[bazel.build] Problem with /install/compile-source

### ISSUE THREAD

**Issue by Dadudidas** [bazelbuild/bazel#17047] opened 2022-12-18 19:06 UTC
kompromitiert

**Comment by sgowroji** [comment] 2022-12-19 03:13
Hello @Dadudidas, Could you please provide complete details on your issue. Like link or page your using, any error logs, reproducing steps.

**Comment by sgowroji** [comment] 2022-12-22 06:07
Due to lack of information we are closing this issue. Please reach us if you can provide complete details on the above request. Thanks!

**Closed by sgowroji** 2022-12-22 06:07 UTC
Labels: more data needed
