### ISSUE TITLE
Build event file creation fails with symlinks when using --remote_download_minimal

### ISSUE THREAD

**Issue by exoson** [bazelbuild/bazel#11942] opened 2020-08-13 13:06 UTC
### Description of the problem / feature request:

If generating build event file for a target which creates a file and a symlink to this file with `--remote_download_minimal` and the target exists in remote cache, BEP upload code will fail with `ERROR: Unable to write all BEP events to file due to 'java.io.FileNotFoundException: /home/exoson/.cache/dazel/_dazel_exoson/5d75fbbb8d44bec03b8dc3734a1ad976/execroot/test_repo/bazel-out/k8-py3-fastbuild/bin/asdf_link (No such file or directory)'`

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Have symlink.bzl
```
def _symlink_impl(ctx):
    out = ctx.actions.declare_file(ctx.label.name)
    ctx.actions.run_shell(
        command = "echo 'test' > $@",
        arguments = [out.path],
        outputs = [out],
    )
    link = ctx.actions.declare_symlink(ctx.label.name + "_link")
    ctx.actions.symlink(
        output = link,
        target_path = out.path,
    )
    return DefaultInfo(files = depset([link, out]))

symlink = rule(
    implementation = _symlink_impl,
)
```
and BUILD
```
load("//:symlink.bzl", "symlink")

symlink(
    name = "asdf",
)
```

Run 
```
# First build the target and cache everything remotely
dazel build --experimental_allow_unresolved_symlinks --remote_cache=grpc://127.0.0.1:8980 //:asdf

# Clean so the files won't exist locally anymore
dazel clean

# Run the build with --remote_download_minimal while generating a build even file.
dazel build --experimental_allow_unresolved_symlinks --remote_cache=grpc://127.0.0.1:8980 --build_event_json_file=be.json  --remote_download_minimal //:asdf
```

### What operating system are you running Bazel on?

Ubuntu 18.04

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

Ran the installation script built with this
```
git checkout master
git pull
bazel build //scripts/packages:with-jdk/install.sh
```

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

https://github.com/bazelbuild/bazel.git
40e763682ec2b03d3330fd0ffbd0099febbd4140
40e763682ec2b03d3330fd0ffbd0099febbd4140

###  Have you found anything relevant by searching the web?

https://github.com/bazelbuild/bazel/issues/6862#issuecomment-638766534
https://github.com/bazelbuild/bazel/issues/11119

### Any other information, logs, or outputs that you want to share?

Seems like when using `--remote_download_minimal` symlinks are created while the file linked to isn't and thus BEP upload code will fail when trying to compute the digest for the symlinked file. https://github.com/bazelbuild/bazel/blob/40e763682ec2b03d3330fd0ffbd0099febbd4140/src/main/java/com/google/devtools/build/lib/remote/ByteStreamBuildEventArtifactUploader.java#L129

**Comment by coeuvre** [comment] 2020-08-19 08:50
The example fails in the second build because:

1. There are two actions required to run for target `//:asdf`:
    1. `actions.run_shell` which output `asdf` and can be executed remotely;
    2. `actions.symlink` which output `asdf_link`.
2. When remote cache enabled with minimal mode, it
    >  Generally don't download remote action outputs. The only outputs that are being downloaded are: stdout, stderr and .d and .jdeps files for C++ and Java compilation actions.

    `asdf` is not download in this case.
3. A [`TargetCompleteEvent`](https://github.com/bazelbuild/bazel/blob/8874477c9ec5700efe9b924a3be76099ebd6ede7/src/main/java/com/google/devtools/build/lib/analysis/TargetCompleteEvent.java#L70) is posted which will [upload referenced local files](https://github.com/bazelbuild/bazel/blob/064d15dd8dca19fa9fdf5736f422c2fc99b33cef/src/main/java/com/google/devtools/build/lib/buildeventstream/transports/FileTransport.java#L284), in this case `asdf` and `asdf_link`, by [reading the metadata]() of those files, in this case, using [`RemoteActionFileSystem`](https://github.com/bazelbuild/bazel/blob/03be73edcf5d41bbef31220f9ebf86f1ee629103/src/main/java/com/google/devtools/build/lib/remote/RemoteActionFileSystem.java#L45).
4. The `RemoteActionFileSystem` 
    > mostly delegates to the local file system except for the case where an action input is a remotely stored action output.
5. For `asdf`, it read the metadata from remote cache, but for `asdf_link` it delegates to local file system which fellows the symlink. The file `asdf` is not downloaded, so `FileNotFoundException`.

Symlinks in action outputs are not yet supported with `--remote_download_minimal`. I am not sure the right solution to this.

**Comment by ulfjack** [comment] 2020-08-19 10:48
I think this might be a duplicate of #11532, for which I have a pending PR.

**Comment by exoson** [comment] 2020-08-19 11:05
> I think this might be a duplicate of #11532, for which I have a pending PR.

I think this would be different as this problem exists even when the symlinks are not toplevel.

**Comment by ulfjack** [comment] 2020-08-20 09:04
@exoson, you're probably right. I am thinking that RemoteActionFS should not delegate to the underlying file system in this case because that can't resolve symlinks. Or maybe we shouldn't be creating dangling symlinks on the underlying file system, but instead create them in RemoteActionFS?

**Comment by tjgq** [comment] 2022-10-21 15:08
This became a warning instead of an error at some point between 4.x and 5.x (likely in e855a26).

**Closed** 2023-06-12 09:30 UTC
Labels: type: bug, P2, team-Remote-Exec
