### ISSUE TITLE
conflicting documentation re: naming standards of externally hosted java dependencies and requests for comments

### ISSUE THREAD

**Issue by erickj** [bazelbuild/bazel#4825] opened 2018-03-11 13:08 UTC
while this issue may be a discussion starter appropriate for bazel-discuss@ it seems more appropriate as a github issue since it's due to claims made in https://github.com/bazelbuild/bazel/blob/master/tools/build_defs/repo/java.bzl vs public documentation.

*tldr; bazel/tools/build_defs/repo/java.bzl actively contradicts public documentation*

`java_import_external` claims to be replacing maven_jar in the source since Aug 2017, that was prior to release 0.5.4. Since then there has been no *substantive* mention on this AFAICT, either in [bazel-discuss@](https://groups.google.com/forum/#!searchin/bazel-discuss/java_import_external%7Csort:date), [bazel blog](https://www.google.com/search?q=site%3Ablog.bazel.build+"java_import_external"), or [bazel release notes](https://github.com/bazelbuild/bazel/releases). Nor is there a single mention of `java_import_external` on any of the following public documentation pages:

* https://docs.bazel.build/versions/master/generate-workspace.html
* https://docs.bazel.build/versions/master/external.html
* https://docs.bazel.build/versions/master/tutorial/java.html
* https://docs.bazel.build/versions/master/be/java.html

However, major bazel [projects like grpc-java seem to acknowledge this switch over](https://github.com/grpc/grpc-java/issues/4181).

What is the official bazel plan for externally hosted maven java dependencies? What is the release timeline for this? What is the plan for updating documentation? Is maven_jar deprecated?

**My biggest issue are the claims `java_import_external` makes regarding naming**. 

First the algorithm it mentions is hosted a [personal gist](https://gist.github.com/jart/41bfd977b913c2301627162f1c038e55), rather than a primary source in bazelbuild/bazel or bazel documentation. Secondly it directly contradicts the naming convention already documented in [public documentation for maven_jar](https://docs.bazel.build/versions/master/be/workspace.html#maven_jar) and elsewhere. Perhaps there are good reasons for this, but the only one given is to eliminate redundancies. While this seems reasonable in isolation, appears capricious given the existing recommendation and ultimately in conflict with maven artifact naming. A change in best practice recommendation of this nature needs to be subject to wider discussion.

From [public documentation](https://docs.bazel.build/versions/master/be/workspace.html#maven_jar):
```
For example, a rule with artifact = "org.apache.commons:commons-lang3:3.4" should have name = "org_apache_commons_commons_lang3"

Examples
Suppose that the current repostory contains a java_library target that needs to depend on Guava. Using Maven, this dependency would be defined in the pom.xml file as:

<dependency>
    <groupId>com.google.guava</groupId>
    <artifactId>guava</artifactId>
    <version>18.0</version>
</dependency>

With Bazel, add the following lines to the WORKSPACE file:

maven_jar(
    name = "com_google_guava_guava",
    artifact = "com.google.guava:guava:18.0",
    sha1 = "cce0823396aa693798f8882e64213b1772032b09",
)
```

From comments in `java_import_external`:
```
- com.google.guava:guava becomes com_google_guava
- commons-logging:commons-logging becomes commons_logging
- junit:junit becomes junit
Adopting this naming convention will help maximize the chances that your
codebase will be able to successfully interoperate with other Bazel codebases
using Java.
```

Naming external Java dependencies has already been a consistent source of confusion for projects with first tier bazel support:

* [gerrit](https://github.com/bazelbuild/rules_closure/issues/200)
* [java-grpc](https://github.com/grpc/grpc-java/pull/3338)

**The primary issue appears to be inconsistency and lack of  direction on standards such as naming convention.** The inconsistency already lead to painful fractures in the bazel ecosystem when loading multiple external workspaces and leads to the current irony that it's arbuably easier to include non-bazel projects into a bazel workspace than it is existing bazel workspaces. e.g. Try to load grpc-java and rules_closure into the same WORKSPACE (bazelbuild/rules_closure#257). This only leads to each project inventing its own incompatible patterns, similar to [what has happened in the javascript community resulting in laborious transitions back towards common packaging standards](https://github.com/dherman/defense-of-dot-js/blob/master/proposal.md#typical-usage) around package.module, package.main, package.jsnext:main, and index.js. The source of this pain in the JS world was the lack of a clear naming standard years ago, leading to competing and incompatible implementations.

The bazel developers have a chance to stop this from happening with external Java dependencies by laying out clearer standards for providing common dependencies to external workspaces. Both in rule names and kind. Whether the mechanism to download and import jars is `maven_jar` or `java_import_external` seems irrelevant, however whether `@com_google_guava_guava//jar` is expected to be consumed by remote workspace as a java_import or `@com_google_guava:com_google_guava` is expected seems to be the core issue.

Of course this standard may evolve while the community continues to learn and discuss best practices (e.g. [creating java_imports or not](https://groups.google.com/forum/#!searchin/bazel-discuss/java_import_external/bazel-discuss/t0BOBD9UYn0/Hyjrk0PYAAAJ)), but it could happen in standard and transparent process.

So what am i proposing:

1. at the very lest, public documentation should be updated to mention `java_import_external` OR comments in bazelbuild/bazel/blob/master/tools/build_defs/repo/java.bzl should be made consistent with public documentation. Inconsistency is unacceptable.

2. clarifying the issue at hand, i.e. supplying dependencies when importing externally hosted repositories. Currently there seems to be 2 primary contenders laying the groundwork here, both appearing identical to start, but are actually incompatible: 1. [closure_repositories style from rules_closure/closure/repositories.bzl](https://github.com/bazelbuild/rules_closure/blob/master/closure/repositories.bzl) 2. [grpc_java_repositories from grpc/grpc-java](https://github.com/grpc/grpc-java/blob/master/repositories.bzl)

Both implementations allow the importing workspace to omit previously loaded common dependencies. The incompatibility arises in that each method is opinionated about the names expected of the dependency and how its used internally.

One approach to solve the incompatibility would be to set a naming & rule convention, e.g. so that grpc-java expects guava to be supplied as a java_import at `@com_google_guava_guava//jar`. However this is probably problematic and fragile in practice.

Possibly better would be able to tell `grpc_java_repositories` that guava is available at `@com_google_guava_guava//jar` or `@my_really_bad//:name_for_guava`. Internally grpc_java_repositories could then alias the supplied dependency, given that it's the correct rule type. This model of supplying dependencies to external workspaces rather than claiming one can be omitted would allow greater flexibility.

There are certainly other options. The important issue is recognizing that there is a missing standard and clarifying a recommendation could circumvent lots of future pain with integrating remote bazel repositories.

3. longer term it would be wonderful if there was a community process for proposing and accepting standards affecting remote workspace interop.

Do others feel similarly?

Here are excerpts from the documentation at https://github.com/bazelbuild/bazel/blob/master/tools/build_defs/repo/java.bzl#L17:

```
java_import_external() replaces `maven_jar` and `http_jar`. It is the
recommended solution for defining third party Java dependencies that are
obtained from web servers.

This solution offers high availability, low latency, and repository
scalability at the cost of simplicity....

The default target in this BUILD file will always have the same name as
the repository itself. This means that other Bazel rules can depend on
it as `@repo//:repo` or `@repo` for short.

...

### Best Practices

The recommended best practices for downloading Maven jars are as follows:
1. Always follow release versions or pinned revisions.
2. Permanently mirror all dependencies to GCS or S3 as the first URL
3. Put the original URL in the GCS or S3 object name
4. Make the second URL the original repo1.maven.org URL
5. Make the third URL the maven.ibiblio.org mirror, if it isn't 404
6. Always specify the sha256 checksum

....

### Naming
Bazel repository names must match the following pattern: `[_0-9A-Za-z]+`. To
choose an appropriate name based on a Maven group and artifact ID, we recommend
an algorithm https://gist.github.com/jart/41bfd977b913c2301627162f1c038e55 which
can be best explained by the following examples:
- com.google.guava:guava becomes com_google_guava
- commons-logging:commons-logging becomes commons_logging
- junit:junit becomes junit
Adopting this naming convention will help maximize the chances that your
codebase will be able to successfully interoperate with other Bazel codebases
using Java.
```

**Comment by davido** [comment] 2018-03-11 15:50
There are currently a number of out of the box ways in Bazel to consume external dependencies:

- Native `maven_jar` rule
- Skylark based `maven_jar` rule:

```
load("@bazel_tools//tools/build_defs/repo:maven_rules.bzl", "maven_jar")
```

- Skylark based `java_import_external` rule:

```
load("@bazel_tools//tools/build_defs/repo:java.bzl", "java_import_external")
```

I would expect that all three different rules provided by Bazel are compatible with each other. This is currently not the case.

This unnecessary complicates the integration of different external projects. Consider Gerrit Code Review project, that implements its own `curl` based `maven_jar` Skylark based rule, and also depends on `rules_closure`, that utilizes downstream version of `java_import_external`. The problem is, that the naming convention differs between internal and external `maven_jar` and `java_import_external` rules. So that I was forced to extend Gerrit internal `maven_jar` rule implementation to adapt the downloaded locations of the external dependencies to those exposed by `java_import_external`: [1].

This seriously complicates the integration of different Bazel repositories and is quite unexpected. My call would be to agree on the standard naming convention and the locations of the downloaded external dependencies across different rules, and force all internal Bazel rules for handling external dependencies to comply with this standard.

[1] https://github.com/GerritCodeReview/gerrit/commit/b5099530084deb61fcb9e60314579dd0daed79b5

**Comment by erickj** [comment] 2018-03-11 23:48
Thanks @davido 

In writing a reply to you I've realized that I'm simply rediscovering suggestions that have already been made in this very long thread on deprecating bind:

https://github.com/bazelbuild/bazel/issues/1952#issuecomment-272222888

which became sidetracked primarily in a discussion on standardizing naming conventions betwen @jart and @johnynek where I believe the conversation on maven artifact naming mostly ended around here: https://github.com/bazelbuild/bazel/issues/1952#issuecomment-297877876

@pcj also made provided pointers to the pubref/rules_maven implementations here https://github.com/bazelbuild/bazel/issues/1952#issuecomment-272598747 that sound similar to the suggestions I made above re: supplying target names to macros like `closure_repository`, which ironically would depend on `bind()`

However, given there is so much more context on that thread regarding naming conventions I suggest any further discussion on the standardized naming topic is moved there

I still feel this issue has merit on it's own in clarifying the long term plans for switching to `java_import_external` given the unique maven pkg naming conventions it enforces.

**Comment by buchgr** [comment] 2018-03-16 14:24
cc: @aehlig @dslomov @cgrushko

**Comment by pauldraper** [comment] 2018-04-07 14:49
The tl;dr of #1952 is that no one follows a standard, not even Google (especially not Google?).  

bind() can be used to resolve this fresh instance of dependency hell.

**Comment by erickj** [comment] 2018-04-07 14:56
@pauldraper Google doesn't use Maven packages internally. All external dependencies are generally imported to a third party subdirectory of the primary repository

**Comment by pauldraper** [comment] 2018-04-07 14:58
I was thinking Closure, Gerrit, GWT, TensorFlow.

**Comment by ittaiz** [comment] 2018-04-07 18:04
There’s also #4038 which is actually solely on standardizing the naming
convention (where we also couldn’t reach a conclusion).
Re java_import_external: I think there is a gap between it and maven_jar.
java_import_external pros:
allows defining deps/runtime_deps/neverlink/exports(?)
enables redundancy
maven_jar pros:
higher level of abstraction by using maven artifact coordinates
Supports maven_server and so removes duplication and clutter

My colleague, @natansil, is working on a scala_maven_import_external
repository rule which is aimed at combining the pros of all of the above
plus use scala_import since we need to be able to turn off ijar creation
for some use-cases (currently it’s always off but we plan to change it and
have ijar be opt-out)

Most of this can definitely be sent upstream back to Bazel itself as
maven_import_external.

In my opinion the current state of java_import_external is too rough edged
to replace maven_jar.

One small additional advantage of maven_import_external is that it can
encode a library rule which has a MavenCoordinates provider. This provider
can use people wanting to export bazel code to maven and needing to
synthesize their POMs

**Comment by pcj** [comment] 2018-09-18 23:39
I share this pain now that I'm trying to use both `io_grpc_grpc_java` and `rules_closure.closure_repositories` in the same workspace.  Aargh.  

So now I am brainstorming how to solve this.  Apologies in advance if my ideas here are not fully threshed out.

My first thread of thought is about recursive workspaces.  I don't know where we are with the recursive workspace implementation in bazel, but the only way I can see it working if bazel has the capability of:

1. Building a transitive tree of external dependencies via crawling the WORKSPACE (and external workspaces, recursively)
2. Collapsing the tree to a minimal one by bubbling up leaves where hashes are identical (two external workspaces have the same maven_jar version/hash? Bubble that up so they refer to the same one).  This is similar to how npm/yarn works, if I understand correctly.
3. Rename artifacts in the minimal tree to a flat namespace, like `com_google_guava_19` and `com_google_guava_21`.
4. Have bazel to alias the label to the renamed one internally.  

The core capability there would be to express a renaming map to bazel (4) such that if it encounters "<java_import_external>com_google_code_findbugs_jsr305//:com_google_code_findbugs_jsr305" anywhere during analysis, replace it with "<maven_jar>com_google_code_findbugs_jsr305//jar".  

This is kind of like the reverse of `bind()`, more like `inject()`.  

I suppose this could be done statically with buildozer.  Perhaps if I had a `buildozer_http_archive` rule, I could manually re-write the dependencies when pulling the dependency.  But then I need to have intimate knowledge of the internals of the external repository, and would likely be quite brittle.

Did anyone solve this cleanly?  (using `io_grpc_grpc_java` and `io_bazel_rules_closure//closure:repositories.bzl` together)

**Comment by jart** [comment] 2018-09-19 12:59
People tend not to agree on names in the absence of a registry service (e.g. DNS, NPM) that enforces them.  Proposals for doing that haven't received much support in the past.  I encourage folks to do what they want.  I don't have plans at this time to continue being a part of that conversation.

**Comment by jin** [comment] 2020-05-30 05:24
> What is the official bazel plan for externally hosted maven java dependencies? What is the release timeline for this? What is the plan for updating documentation? Is maven_jar deprecated?

This is now supported primarily through https://github.com/bazelbuild/rules_jvm_external.

Closing.

**Closed by jin** 2020-05-30 05:24 UTC
Labels: P2, team-ExternalDeps, type: documentation
