### ISSUE TITLE
force refetch http_archive rule

### ISSUE THREAD

**Issue by xytan0056** [bazelbuild/bazel#14058] opened 2021-09-29 01:41 UTC
### Description of the problem / feature request:

any invalidation of the fingerprint or folder in `$(bazel info output_base)/external` should auto invalidate cache and make fetch to redownload.

### Feature requests: what underlying problem are you trying to solve with this feature?

Despite of solution mentioned here #974 and [here](https://bazel.build/designs/2016/10/18/repository-invalidation.html), there's no obvious option to invalidate cache for http_file rules, except `bazel sync --only=my_rule`.  If `$(bazel info output_base)/external` is the directory that remote repositories are downloaded/symlinked into, changing files in any folders in there should invalidate the corresponding rule.

We are trying to pre-warm our CI machines with the external folder and need bazel to be smart enough to notice content mismatch between existing package and expected rule, then refetch.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

```
    http_file(
        name = "target",
        executable = False,
        sha256 = "1234",
        urls = "http://....",
    )
```
then `rm $(bazel info output_base)/external/@target.marker` and `bazel fetch @target` doesn't trigger a refetch.

### What operating system are you running Bazel on?

mac, linux

### What's the output of `bazel info release`?

release 4.2.1

**Comment by Wyverald** [comment] 2022-02-07 14:20
> there's no obvious option to invalidate cache for http_file rules, except `bazel sync --only=my_rule`

What's wrong with using that then? We don't expect users to mess with the outputBase/external directory, and that assumption is built into the code, which means that 

> We are trying to pre-warm our CI machines with the external folder and need bazel to be smart enough to notice content mismatch between existing package and expected rule, then refetch.

Bazel _will_ notice if the marker file doesn't match the rule definition, *on server startup*. (Again, because we don't expect users to mess with the external directory, this should only ever happen if the rule definition changed.) The reproduction scenario you outlined is not supported. But that should still not be a problem if you simply want to pre-warm your CI machines?

**Comment by ElectricRCAircraftGuy** [comment] 2022-03-01 04:51
@Wyverald , I find myself also manually editing the content of the `"$(bazel info output_base)/external"` folder occasionally in order to test un-merged/uncommitted changes in the sub-repo which the main repo requires to build. See my full example below. Therefore, I agree with @xytan0056 and feel that `bazel fetch //path/to/some:target` should be a little smarter and automatically fix things and redownload the dependency if I've manually changed it in the `external` dir.

@xytan0056 , here is a work-around meanwhile. If you've manually edited some external dependency at path `"$(bazel info output_base)/external/my_dependency"`, you can **force it to re-download** like this:

```bash
BUILD_TARGET="//some/path/to/a/build/target/which:requires_my_dependency"
# manually delete the "external" folder you've edited, once you're done editing it and want to restore it to how it was originally
rm -rf "${EXTERNAL_DEPS_ROOT}/${EXTERNAL_DEP}"
# force bazel to re-download this dependency!:
# Note: this is a bit of a hack, but it works. 
# See: https://github.com/bazelbuild/bazel/issues/14058#issuecomment-1031520021
time bazel sync --only=$BUILD_TARGET
time bazel fetch $BUILD_TARGET

## Full demonstration of editing contents of dependencies in the `external` dir, then restoring them to normal

Let's assume you have a `main_repo` which depends upon some sub-repo. The scenario is that you want to test some changes in sub-repo which have not yet merged, and you want `main_repo` to use these unmerged changes. Therefore, we are going to manually edit the `external/sub_repo` dir to make it into a symbolic link which points to that local copy of the repo where the unmerged changes are which you'd like to test. Once done testing those changes in the `main_repo`, we call the above `bazel sync --only` and `bazel fetch` commands to restore the `main_repo`'s copy of the `sub_repo` dependency to how it's supposed to be.

----

NB: Ensure you have cloned the two repos (one which has Bazel dependencies upon the other) to the same dir at the same level! Ex: to:

```bash
$HOME/repos/main_repo
# and
$HOME/repos/some-dependency-repo-name  # a sub-repo required by `main_repo`
```

Now, here are some commands to run to have the `main_repo` build the `BUILD_TARGET` below, which requires in-work changes within the sub-repo named `some-dependency-repo-name`:


```bash
# ==================================================================================================
# 1. SETUP
# ==================================================================================================

# Name of the source repo which Bazel downloads into the `"${EXTERNAL_DEPS_ROOT}/${EXTERNAL_DEP}"`
# dir. ie: When you manually `git clone` this repo to your computer, this is the dirname it creates
# and clones the repo into.
EXTERNAL_DEP_SRC_REPO_DIR="some-dependency-repo-name"  # the sub-repo which the main repo needs
# name of the dependency directory of interest in "${EXTERNAL_DEPS_ROOT}" (defined below).
EXTERNAL_DEP="some_dependency_repo_name" 
BUILD_TARGET="//some/path/to/a/build/target/which:requires_the_dependency_above"

# First, MANUALLY cd into your $EXTERNAL_DEP_SRC_REPO_DIR repo and `git checkout` whatever branch
# you want. Then, cd into the repo which uses Bazel and depends upon that external dependency 
# repo, and run the following:

# ==================================================================================================
# 2. RUN THE BAZEL TARGET WHICH DEPENDS UPON $EXTERNAL_DEP_SRC_REPO_DIR
# ==================================================================================================

# Obtain path to where external dependencies and repos are stored by Bazel. Example path:
# "$HOME/.cache/bazel/_bazel_gabriel/1234567890abcdef1234567890abcdef/external"
{EXTERNAL_DEPS_ROOT}="$(bazel info output_base)/external"
echo "{EXTERNAL_DEPS_ROOT} = ${EXTERNAL_DEPS_ROOT}"
# Back up the old "${EXTERNAL_DEP}" dependency 
mv "${EXTERNAL_DEPS_ROOT}/${EXTERNAL_DEP}" "${EXTERNAL_DEPS_ROOT}/${EXTERNAL_DEP}.bak" 
# Find the main repo's root dir full path.
SOURCE_REPO_ROOT="$(git rev-parse --show-toplevel)"
# Create a symlink to the $EXTERNAL_DEP_SRC_REPO_DIR repo you have cloned at the location where
# Bazel will use it in its external dependencies path
ln -s "$SOURCE_REPO_ROOT/../$EXTERNAL_DEP_SRC_REPO_DIR" "${EXTERNAL_DEPS_ROOT}/${EXTERNAL_DEP}"
# copy over the needed bazel "BUILD.bazel" and "WORKSPACE" build files to the
# $EXTERNAL_DEP_SRC_REPO_DIR repo 
cp "${EXTERNAL_DEPS_ROOT}/${EXTERNAL_DEP}.bak/BUILD.bazel" "${EXTERNAL_DEPS_ROOT}/${EXTERNAL_DEP}"  
cp "${EXTERNAL_DEPS_ROOT}/${EXTERNAL_DEP}.bak/WORKSPACE" "${EXTERNAL_DEPS_ROOT}/${EXTERNAL_DEP}"  

# ignore these files locally so that `git status` in the `EXTERNAL_DEP_SRC_REPO_DIR` sub-repo won't 
# show them.
# Usage:
#       ignore_files "file1" "file2" "file3" ...
ignore_files() {
    # See: https://stackoverflow.com/a/70572787/4561887
    files=("$@")
    for file in "${files[@]}"; do
        if ! grep "/$file" "${EXTERNAL_DEPS_ROOT}/${EXTERNAL_DEP}/.git/info/exclude"; then
            echo "/$file" >> "${EXTERNAL_DEPS_ROOT}/${EXTERNAL_DEP}/.git/info/exclude"
        fi
    done
}
ignore_files "BUILD.bazel" "WORKSPACE"


# Now run the build target in the main repo which depends upon the content of the sub-repo as a 
# dependency.
time bazel build $BUILD_TARGET


# ==================================================================================================
# 3. UNDO CHANGES
# ==================================================================================================

# If you ever need to UNDO the symlink above, to put back the original ${EXTERNAL_DEP} dir, 
# 1st (required), delete the symlinked folder:
rm "${EXTERNAL_DEPS_ROOT}/${EXTERNAL_DEP}"

# Then:

# A (ok). rename the backed-up folder back to how it was
mv "${EXTERNAL_DEPS_ROOT}/${EXTERNAL_DEP}.bak" "${EXTERNAL_DEPS_ROOT}/${EXTERNAL_DEP}"

# OR, B (PREFERRED!). just force bazel to re-download this dependency!:
# Note: this is a bit of a hack, but it works. 
# See: https://github.com/bazelbuild/bazel/issues/14058#issuecomment-1031520021
time bazel sync --only=$BUILD_TARGET
time bazel fetch $BUILD_TARGET


# ==================================================================================================
# NOTE:
# ==================================================================================================
# If you ever want to manually delete the "${EXTERNAL_DEPS_ROOT}/${EXTERNAL_DEP}" dir, that's fine:
rm -rf "${EXTERNAL_DEPS_ROOT}/${EXTERNAL_DEP}"
# When done, just run the "B." cmds just above to re-fetch that dependency!
```

```

**Comment by sgowroji** [comment] 2022-06-10 06:38
Hello @xytan0056, Wanted to check wether you are still looking resolution for the above FR and you can also go through the workaround mentioned in the above comment. Please feel free to reopen, if you have any further queries on the same. Thanks!

**Closed by sgowroji** 2022-06-10 06:38 UTC
Labels: type: feature request, P4, more data needed, team-ExternalDeps
