### ISSUE TITLE
Skylark tests is timeout flaky [flake]

### ISSUE THREAD

**Issue by damienmg** [bazelbuild/bazel#3628] opened 2017-08-28 08:08 UTC
3 instances, all on ubuntu 16.04:

http://ci.bazel.io/job/bazel-tests/984/artifact/tests-node=ubuntu_16.04-x86_64-variation=/src/test/java/com/google/devtools/build/lib/skylark/SkylarkTests/test.log

http://ci.bazel.io/job/Global/job/bazel-tests/200/artifact/tests-node=ubuntu_16.04-x86_64-variation=/src/test/java/com/google/devtools/build/lib/skylark/SkylarkTests/test.log

http://ci.bazel.io/job/Global/job/bazel-tests/198/artifact/tests-node=ubuntu_16.04-x86_64-variation=/src/test/java/com/google/devtools/build/lib/skylark/SkylarkTests/test.log

Laurent, please triage further

**Comment by damienmg** [comment] 2017-09-22 09:08
Ping? This bug is stalled for 25 days...

**Comment by vladmos** [comment] 2017-09-22 11:24
Duplicate of #3774.

**Closed by vladmos** 2017-09-22 11:24 UTC
Labels: breakage, category: extensibility > skylark, P1, type: bug, Under investigation
