### ISSUE TITLE
bazel build :* doesn't work for examples/java-native/src/main/java/com/example/myproject

### ISSUE THREAD

**Issue by Nan-Zhang** [bazelbuild/bazel#3532] opened 2017-08-09 23:05 UTC
Please provide the following information. The more we know about your system and use case, the more easily and likely we can help.

### Description of the problem / feature request / question:

_If asking a question or requesting a feature, also tell us about the underlying problem you're trying to solve._
"bazel build :*" under examples/java-native got broken.

### If possible, provide a minimal example to reproduce the problem:
cd examples/java-native/src/main/java/com/example/myproject && output/bazel build :*
it gave me the error:
ERROR: /usr/local/google/home/nanzhang/android/bazel/examples/java-native/src/main/java/com/example/myproject/BUILD:29:1: Building examples/java-native/src/main/java/com/example/myproject/libhello-error-prone.jar (1 source file) failed: Worker process sent response with exit code: 1.
examples/java-native/src/main/java/com/example/myproject/HelloErrorProne.java:8: error: [ComparisonOutOfRange] bytes may have a value in the range -128 to 127; therefore, this comparison to 255 will always evaluate to false
    result = b == 255;
               ^
    (see http://errorprone.info/bugpattern/ComparisonOutOfRange)
  Did you mean 'result = b == -1;'?
INFO: Elapsed time: 0.522s, Critical Path: 0.23s

### Environment info
* Operating System: Linux x86-64

* Bazel version (output of `bazel info release`): 0.5.2

* If `bazel info release` returns "development version" or "(@non-git)", please tell us what source tree you compiled Bazel from; git commit hash is appreciated (`git rev-parse HEAD`):
it's non-git version; I directly downloaded bazel-0.5.2-dist.zip from https://github.com/bazelbuild/bazel/releases/tag/0.5.2

###  Have you found anything relevant by searching the web?
(e.g. [StackOverflow answers](http://stackoverflow.com/questions/tagged/bazel),
[GitHub issues](https://github.com/bazelbuild/bazel/issues),
email threads on the [`bazel-discuss`](https://groups.google.com/forum/#!forum/bazel-discuss) Google group)
I searched the error online; it seems the error was not raised before. 

### Anything else, information or logs or outputs that would be helpful?
(If they are large, please upload as attachment or provide link).

**Comment by mhlopko** [comment] 2017-08-10 14:58
Interesting, I didn't know we support :* :) Anyway, I tried with bazel@HEAD using bazel 0.5.3, and using bazel@HEAD, and couldn't reproduce. Can you update to bazel 0.5.3 and try again please?

**Comment by Nan-Zhang** [comment] 2017-08-10 18:18
It seems only 0.5.2 has this issue. I will switch to 0.5.3...

**Comment by mhlopko** [comment] 2017-08-11 09:09
Ok, it's very likely it's fixed in 0.5.3. I'll close this issue now, please comment here to reopen if the issue is still present. Thanks!

**Closed by mhlopko** 2017-08-11 09:09 UTC
Labels: On hold: more data needed
