### ISSUE TITLE
embedded_tools_deps_test is failing at Bazel@HEAD

### ISSUE THREAD

**Issue by sgowroji** [bazelbuild/bazel#19569] opened 2023-09-20 05:42 UTC
https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/3319#018ab077-ccbc-4104-8923-09febf8fa00e

Platform : Ubuntu

Logs:
```
//src/test/shell/bazel:embedded_tools_deps_test                          FAILED
```

Steps:
```
git clone -v https://github.com/bazelbuild/bazel.git
git reset 1447f2422ba345e57511a246a58e485422fa2f93 --hard
export USE_BAZEL_VERSION=81b4b91bc98acc404690cd833cd6a1a592f3ee17
bazel test -- //scripts/... //src/java_tools/... //src/main/starlark/tests/builtins_bzl/... //src/test/... //src/tools/execlog/... //src/tools/singlejar/... //src/tools/workspacelog/... //third_party/ijar/... //tools/android/... //tools/aquery_differ/... //tools/python/... //tools/bash/... -//src/java_tools/import_deps_checker/... -//src/test/shell/bazel/android:android_instrumentation_test_integration_test -//src/test/shell/bazel/android:android_instrumentation_test_integration_test_with_head_android_tools -//src/test/shell/bazel/android:android_instrumentation_test_integration_test_with_platforms -//src/test/shell/bazel/android:aapt_integration_test -//src/test/shell/bazel/android:aapt_integration_test_with_head_android_tools -//src/test/shell/bazel/android:aapt_integration_test_with_platforms

```
Assuming culprit : https://github.com/bazelbuild/bazel/commit/9d3084938d6f8e015e7b77812371dcbf2662b02c

CC Greenteam @comius

**Comment by comius** [comment] 2023-09-21 08:19
cc @meteorcloudy

**Comment by meteorcloudy** [comment] 2023-09-21 11:55
This test is:
- Green at https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/3316
- Red at https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/3319

`bazel --bisect=657e01c92b849c48df96eff37d814e426ae49c9a..81b4b91bc98acc404690cd833cd6a1a592f3ee17 test //src/test/shell/bazel:embedded_tools_deps_test` actually gives
https://github.com/bazelbuild/bazel/commit/20cdacc22ab4f3ec8ae4337d535a1846bcbfd382

Let me take a closer look

**Comment by meteorcloudy** [comment] 2023-09-21 11:56
Since that change is backported to 6.4.0, the downstream is also failing for 6.4.0: https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/3322#_

**Comment by meteorcloudy** [comment] 2023-09-21 11:58
@iancha1992 this might be a release blocker for 6.4.0

**Comment by meteorcloudy** [comment] 2023-09-21 12:03
@fmeum https://github.com/bazelbuild/bazel/blob/e51f26e07a63727df038e7f8dcd9a6ef9c5761bc/src/test/shell/bazel/BUILD#L664-L668

The result of this rule might be different after https://github.com/bazelbuild/bazel/commit/20cdacc22ab4f3ec8ae4337d535a1846bcbfd382, is this an unexpected behaviour?

**Comment by meteorcloudy** [comment] 2023-09-21 12:27
Turns out `genquery` output with Bzlmod enabled changed after https://github.com/bazelbuild/bazel/commit/20cdacc22ab4f3ec8ae4337d535a1846bcbfd382, it is an intended behaviour, so I'm fixing the test forward.

**Comment by sgowroji** [comment] 2023-11-14 06:33
Hi @meteorcloudy, This issue is shown at Bazel@HEAD https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/3459#018bcb95-9d16-4ca4-bc87-a53e88d718e7. Can you take a look.?

**Comment by meteorcloudy** [comment] 2023-11-14 10:14
Yes, this time it's due to a different reason, but it should be fixed by https://github.com/bazelbuild/bazel/commit/22346aec65e66dfb904bd3cb3016b1680bce6248

**Closed by meteorcloudy** 2023-11-14 10:14 UTC
Labels: type: bug, P1, team-ExternalDeps
