### ISSUE TITLE
Crash with 4.2.0rc1: Unrecoverable error while evaluating node

### ISSUE THREAD

**Issue by brentleyjones** [bazelbuild/bazel#13711] opened 2021-07-19 15:21 UTC
### Description of the problem / feature request:

```
FATAL: bazel crashed due to an internal error. Printing stack trace:
--
  | java.lang.RuntimeException: Unrecoverable error while evaluating node 'ActionLookupData{actionLookupKey=ConfiguredTargetKey{label=//tools/assetgen:integrationtests.generate, config=BuildConfigurationValue.Key[7ac4abd0f87beddbd890bc163597cde47a77bb2e332b3b82043bca1b9ce51b2f]}, actionIndex=0}' (requested by nodes 'TargetCompletionKey{topLevelArtifactContext=com.google.devtools.build.lib.analysis.TopLevelArtifactContext@524aae23, actionLookupKey=ConfiguredTargetKey{label=//tools/assetgen:integrationtests.generate, config=BuildConfigurationValue.Key[7ac4abd0f87beddbd890bc163597cde47a77bb2e332b3b82043bca1b9ce51b2f]}, willTest=false}', 'ArtifactNestedSetKey{rawChildren=[File:[[<execution_root>]bazel-out/k8-fastbuild/bin]tools/assetgen/integrationtests-test.sh, File:[[<execution_root>]bazel-out/k8-fastbuild/bin]tools/assetgen/integrationtests-generated, File:[/build[source]]tools/assetgen/expected.swift]}')
  | at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:563)
  | at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:398)
  | at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
  | at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
  | at java.base/java.lang.Thread.run(Unknown Source)
  | Caused by: java.lang.UnsupportedOperationException: empty virtual artifact doesn't have an execpath
  | at com.google.devtools.build.lib.actions.cache.VirtualActionInput$EmptyActionInput.getExecPathString(VirtualActionInput.java:64)
  | at com.google.devtools.build.lib.exec.SpawnLogContext.logSpawn(SpawnLogContext.java:94)
  | at com.google.devtools.build.lib.exec.AbstractSpawnStrategy.exec(AbstractSpawnStrategy.java:170)
  | at com.google.devtools.build.lib.exec.AbstractSpawnStrategy.exec(AbstractSpawnStrategy.java:106)
  | at com.google.devtools.build.lib.actions.SpawnStrategy.beginExecution(SpawnStrategy.java:47)
  | at com.google.devtools.build.lib.exec.SpawnStrategyResolver.beginExecution(SpawnStrategyResolver.java:65)
  | at com.google.devtools.build.lib.analysis.actions.SpawnAction.beginExecution(SpawnAction.java:331)
  | at com.google.devtools.build.lib.actions.Action.execute(Action.java:127)
  | at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$5.execute(SkyframeActionExecutor.java:855)
  | at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$ActionRunner.continueAction(SkyframeActionExecutor.java:1016)
  | at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$ActionRunner.run(SkyframeActionExecutor.java:975)
  | at com.google.devtools.build.lib.skyframe.ActionExecutionState.runStateMachine(ActionExecutionState.java:129)
  | at com.google.devtools.build.lib.skyframe.ActionExecutionState.getResultOrDependOnFuture(ActionExecutionState.java:81)
  | at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.executeAction(SkyframeActionExecutor.java:472)
  | at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.checkCacheAndExecuteIfNeeded(ActionExecutionFunction.java:834)
  | at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.compute(ActionExecutionFunction.java:307)
  | at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:477)
  | ... 4 more
```

### What operating system are you running Bazel on?

Linux

**Comment by katre** [comment] 2021-07-19 15:23
Can you give directions on how to reproduce this? Was this the 4.2.0rc1, or Bazel head?

**Comment by brentleyjones** [comment] 2021-07-19 15:34
4.2.0rc1. Works in 4.1.0. I'm not sure how to repo right now, I just switched our bazel version on CI to test the RC.

**Comment by brentleyjones** [comment] 2021-07-19 17:02
This is dup of https://github.com/bazelbuild/bazel/issues/13713, closing.

**Comment by brentleyjones** [comment] 2021-07-19 17:02
Maybe not, I didn't notice the inner error was different. I'll wait to see if #13713's fix fixes this though.

**Comment by katre** [comment] 2021-07-19 17:33
This is very different from #13713, the crash is in entirely different code.

Please try to get a repro if you can.

**Comment by katre** [comment] 2021-07-19 17:38
This appears to be a dupe of #12816, I'll see if I can apply the fix for that.

**Comment by katre** [comment] 2021-07-19 18:15
This should now be fixed. I'm going to wait for other release blockers and then I'll cut a RC2.

**Closed** 2021-07-19 18:16 UTC
Labels: P1, release blocker, team-Local-Exec, type: bug
