### ISSUE TITLE
Bazel v2.0 on Linux with --jobs=N runs 2*N actions concurrently if remote cache is enabled

### ISSUE THREAD

**Issue by DarkDimius** [bazelbuild/bazel#10559] opened 2020-01-10 05:21 UTC
### Description of the problem / feature request:
Running `bazel test //... --jobs=X --remote_cache=grpc://127.0.0.1:9092` runs bazel with 2X actions concurrently.
```
$ bazel test //test:* --jobs=10 --remote_cache=grpc://127.0.0.1:9092
INFO: Invocation ID: 16fdb3cb-46d9-4eda-8c55-941d53b8f1f1
INFO: Analyzed 102 targets (0 packages loaded, 0 targets configured).
INFO: Found 2 targets and 100 test targets...
[18 / 30] 20 actions running
```

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

`git clone git@github.com:DarkDimius/bazel-bug-repro.git`

```
$ cat test/BUILD 
[sh_test(
    name = "test_{}".format(ii),
    srcs = ["test.sh"],
    data = ["//data:data_{}.txt".format(ii)],
) for ii in range(100)]
$ cat data/BUILD 
[genrule(
    name = "data_{}".format(ii),
    outs = ["data_{}.txt".format(ii)],
    cmd = "sleep 5; touch $@",
    visibility = ["//visibility:public"],
) for ii in range(100)]

$ cat test/test.sh
#!/bin/bash

sleep 5
```

and run `bazel test //test:* --jobs=10 --remote_cache=grpc://127.0.0.1:9092`

### What operating system are you running Bazel on?

```
$ cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.6 LTS"
```

### What's the output of `bazel info release`?

```
$ bazel info release
INFO: Invocation ID: 6eeaf70f-bee0-47d5-a30b-fcaf637d1ab8
release 2.0.0
```
###  Have you found anything relevant by searching the web?

No

### Any other information, logs, or outputs that you want to share?
This is running on `AMD Ryzen Threadripper 3970X 32-Core Processor` cpu, with plenty of memory(128G) so if bazel does any heuristic on if it can use more resources, it would think it can.

Also, if I don't specify `--jobs` it runs 128 of them in parallel, which slows down compilation compared to running less(this was the original cause of me trying to figure out why the build became slow).

If `--remote_cache=grpc://127.0.0.1:9092` is omitted, it runs correct number of actions.

**Comment by jmillikin** [comment] 2020-01-10 10:47
As promised I did some testing, and I think this may be a UI bug with progress reporting rather than anything in the action spawner.

Notes:
* Setting the `--disk_cache` flag exhibits the same behavior.
* Setting `--ui_actions_shown=100` never goes above the `--jobs=` setting, even though the "actions running" message is consistently too high.
* Each line in the progress UI looks like `Testing //test:test_74; 0s linux-sandbox, remote-cache` -- if both `linux-sandbox` and `remote-cache` are considered actions, and being counted separately, then the number will ~always be double the actual action count.
* I was able to reproduce the bad counts on a macOS machine after setting the cache flag.

Since the original manifestation of this bug appeared to you as 2x the number of expected `clang` processes, you might want to double-check that there really were that many being spawned. Either with plain `ps` (simple), or with a Bazel profile generated by `--experimental_generate_json_trace_profile --profile=$PWD/profile.json`. Then you can load that profile into Chrome and verify the number of concurrent action spawns.

**Comment by aiuto** [comment] 2021-04-01 20:45
closing for lack of action

**Closed by aiuto** 2021-04-01 20:45 UTC
Labels: P3, more data needed, team-Remote-Exec, type: bug

**Comment by jwnimmer-tri** [comment] 2023-03-16 17:23
> Setting the --disk_cache flag exhibits the same behavior.

FYI I think the UI bug for progress reporting in this case still exists (in 6.0.0).  I suppose I'll try to write up a new bug report for that.
