### ISSUE TITLE
warnings while building Bazel's Java

### ISSUE THREAD

**Issue by benjaminp** [bazelbuild/bazel#6286] opened 2018-10-01 21:21 UTC
For a while now, building Bazel spits out warnings like this:
```
INFO: From Building src/main/java/com/google/devtools/build/lib/libconfig-matching-provider.jar (1 source file) and running annotation processors (AutoCodecProcessor):
warning: unknown enum constant FlagIdentifier.NONE
  reason: class file for com.google.devtools.build.lib.syntax.SkylarkSemantics not found
warning: unknown enum constant FlagIdentifier.NONE
warning: unknown enum constant FlagIdentifier.NONE
  reason: class file for com.google.devtools.build.lib.syntax.SkylarkSemantics not found
warning: unknown enum constant FlagIdentifier.NONE
warning: unknown enum constant FlagIdentifier.NONE
  reason: class file for com.google.devtools.build.lib.syntax.SkylarkSemantics not found
warning: unknown enum constant FlagIdentifier.NONE
warning: unknown enum constant FlagIdentifier.NONE
  reason: class file for com.google.devtools.build.lib.syntax.SkylarkSemantics not found
warning: unknown enum constant FlagIdentifier.NONE
INFO: From Building src/main/java/com/google/devtools/build/lib/buildeventstream/libbuildeventstream.jar (27 source files) and running annotation processors (AutoCodecProcessor, OptionProcessor):
warning: unknown enum constant FlagIdentifier.NONE
  reason: class file for com.google.devtools.build.lib.syntax.SkylarkSemantics not found
warning: unknown enum constant FlagIdentifier.NONE
warning: unknown enum constant FlagIdentifier.NONE
  reason: class file for com.google.devtools.build.lib.syntax.SkylarkSemantics not found
warning: unknown enum constant FlagIdentifier.NONE
warning: unknown enum constant FlagIdentifier.NONE
  reason: class file for com.google.devtools.build.lib.syntax.SkylarkSemantics not found
warning: unknown enum constant FlagIdentifier.NONE
INFO: From Building src/main/java/com/google/devtools/build/lib/causes/libcauses.jar (5 source files):
warning: unknown enum constant FlagIdentifier.NONE
  reason: class file for com.google.devtools.build.lib.syntax.SkylarkSemantics not found
warning: unknown enum constant FlagIdentifier.NONE
INFO: From Building src/main/java/com/google/devtools/build/lib/libconfig-transitions.jar (8 source files) and running annotation processors (AutoCodecProcessor, OptionProcessor):
warning: unknown enum constant FlagIdentifier.NONE
  reason: class file for com.google.devtools.build.lib.syntax.SkylarkSemantics not found
warning: unknown enum constant FlagIdentifier.NONE
warning: unknown enum constant FlagIdentifier.NONE
  reason: class file for com.google.devtools.build.lib.syntax.SkylarkSemantics not found
warning: unknown enum constant FlagIdentifier.NONE
```
Do these need to be fixed?

**Comment by cushon** [comment] 2018-10-01 22:43
This is related to #5985.

We should fix the warning spam, but they're harmless.

**Comment by cushon** [comment] 2018-10-02 18:49
Closing as a duplicate of #5985.

**Closed by cushon** 2018-10-02 18:49 UTC
Labels: team-Rules-Java, untriaged
