### ISSUE TITLE
Colored output not working anymore in cmd.exe

### ISSUE THREAD

**Issue by haferburg** [bazelbuild/bazel#3108] opened 2017-06-02 14:07 UTC
Here's the output I see when I call bazel-0.5.0-windows-x86_64.exe from cmd.exe:

```
G:\src\test_projects\bazel_tutorial>bazel build main:hello-world
←[32mINFO: ←[0mLoading complete.  Analyzing...
←[1A←[K←[32mINFO: ←[0mFound 1 target...
←[32m[0 / 3] ←[0mLinking main/hello-world.exe
```

When I run the same with 0.4.5, it's working fine. The `INFO` is green, and the lines are deleted and replaced by the following lines.
But in 0.5.0, all the lines are printed one after the other, nothing gets deleted.

**Comment by laszlocsomor** [comment] 2017-06-02 14:17
This is still the MSYS version you're running. Try the MSVC version, that handles the terminal correctly.
I acknowledge this is a bug but we'll phase out the MSYS version by 0.6.0, so I don't plan to fix this.

**Comment by haferburg** [comment] 2017-06-02 14:41
I retried with bazel-msvc-0.5.0-windows-msvc-x86_64.exe. The control characters are gone, but I still don't see any colors.

**Comment by laszlocsomor** [comment] 2017-06-02 14:46
Hmm, you aren't redirecting the output anywhere, right? Just running from cmd.exe?
Try building with `--color=yes --curses=yes`. Does that help?

**Comment by haferburg** [comment] 2017-06-02 15:07
Then the control characters are back:
```
G:\src\test_projects\bazel_tutorial>bazel build main:hello-world --verbose_failures --color=yes --curses=yes
←[32mINFO: ←[0mLoading complete.  Analyzing...
←[1A←[K←[32mINFO: ←[0mFound 1 target...
```

**Comment by haferburg** [comment] 2017-06-02 15:12
Ran `bazel build main:hello-world --verbose_failures --color=yes --curses=yes > out.txt  2>&1`, here's VIM's hex output of the first chars:
```
00000000: 1b5b 3332 6d49 4e46 4f3a 201b 5b30 6d4c  .[32mINFO: .[0mL
00000010: 6f61 6469 6e67 2063 6f6d 706c 6574 652e  oading complete.
00000020: 2020 416e 616c 797a 696e 672e 2e2e 0d0a    Analyzing.....
00000030: 0d1b 5b31 411b 5b4b 1b5b 3332 6d49 4e46  ..[1A.[K.[32mINF
00000040: 4f3a 201b 5b30 6d46 6f75 6e64 2031 2074  O: .[0mFound 1 t
00000050: 6172 6765 742e 2e2e 0d0a 1b5b 3331 6d1b  arget......[31m.
00000060: 5b31 6d45 5252 4f52 3a20 1b5b 306d 473a  [1mERROR: .[0mG:
```

**Comment by laszlocsomor** [comment] 2017-06-02 15:12
Just to make sure, you tried the MSVC version (with the --color/--curses flags) right?

**Comment by laszlocsomor** [comment] 2017-06-02 15:14
Ok, let's try something else:
```
>bazel-msvc-0.5.0-windows-msvc-x86_64.exe --nomaster_bazelrc --bazelrc=NUL build main:hello-world --verbose_failures --color=yes --curses=yes
```

**Comment by haferburg** [comment] 2017-06-02 15:16
Yes, it's the MSVC version.
```
G:\src\test_projects\bazel_tutorial>bazel-msvc-0.5.0-windows-msvc-x86_64.exe --nomaster_bazelrc --bazelrc=NUL build main:hello-wor
ld --verbose_failures --color=yes --curses=yes
←[32mINFO: ←[0mLoading complete.  Analyzing...
←[1A←[K←[32mINFO: ←[0mFound 1 target...
```

**Comment by laszlocsomor** [comment] 2017-06-02 15:27
Can you try building this please and running it from the same cmd.exe window where you've been experimenting?

```
#include <windows.h>
#include <stdio.h>

void diag(HANDLE handle) {
  printf("  handle valid: %d\n", handle == INVALID_HANDLE_VALUE ? 0 : 1);
  DWORD mode = 0;
  if (handle != INVALID_HANDLE_VALUE) {
    if (!GetConsoleMode(handle, &mode)) {
      printf("  GetConsoleMode fail, err: %d\n", GetLastError());
      return;
    }
    printf("  mode: %08x\n", mode);
  }
}

int main(int, char**) {
  printf("stdout:\n");
  diag(GetStdHandle(STD_OUTPUT_HANDLE));
  printf("stderr:\n");
  diag(GetStdHandle(STD_ERROR_HANDLE));
  return 0;
}
```

**Comment by laszlocsomor** [comment] 2017-06-02 15:29
(I mean build it with VC++ of course)

**Comment by haferburg** [comment] 2017-06-02 15:38
```
G:\src\test_projects\bazel_tutorial\console_test>main
stdout:
  handle valid: 1
  mode: 00000003
stderr:
  handle valid: 1
  mode: 00000003
```

**Comment by laszlocsomor** [comment] 2017-06-02 15:47
Good! It should be 00000007.
Let's try this now:
```
#include <windows.h>
#include <stdio.h>

#ifndef ENABLE_PROCESSED_OUTPUT
// From MSDN about BOOL SetConsoleMode(HANDLE, DWORD).
#define ENABLE_PROCESSED_OUTPUT 0x0001
#endif  // not ENABLE_PROCESSED_OUTPUT

#ifndef ENABLE_WRAP_AT_EOL_OUTPUT
// From MSDN about BOOL SetConsoleMode(HANDLE, DWORD).
#define ENABLE_WRAP_AT_EOL_OUTPUT 0x0002
#endif  // not ENABLE_WRAP_AT_EOL_OUTPUT

#ifndef ENABLE_VIRTUAL_TERMINAL_PROCESSING
// From MSDN about BOOL SetConsoleMode(HANDLE, DWORD).
#define ENABLE_VIRTUAL_TERMINAL_PROCESSING 0x0004
#endif  // not ENABLE_VIRTUAL_TERMINAL_PROCESSING

void diag(HANDLE handle) {
  printf("  handle valid: %d\n", handle == INVALID_HANDLE_VALUE ? 0 : 1);
  DWORD mode = 0;
  if (handle != INVALID_HANDLE_VALUE) {
    if (!GetConsoleMode(handle, &mode)) {
      printf("  GetConsoleMode 1 fail, err: %d\n", GetLastError());
      return;
    }
    printf("  mode 1: %08x\n", mode);
    if (!SetConsoleMode(handle, mode | ENABLE_PROCESSED_OUTPUT | ENABLE_WRAP_AT_EOL_OUTPUT | ENABLE_VIRTUAL_TERMINAL_PROCESSING)) {
      printf("  SetConsoleMode fail, err: %d\n", GetLastError());
      return;
    }
    if (!GetConsoleMode(handle, &mode)) {
      printf("  GetConsoleMode 2 fail, err: %d\n", GetLastError());
      return;
    }
    printf("  mode 2: %08x\n", mode);
  }
}

int main(int, char**) {
  printf("stdout:\n");
  diag(GetStdHandle(STD_OUTPUT_HANDLE));
  printf("stderr:\n");
  diag(GetStdHandle(STD_ERROR_HANDLE));
  return 0;
}
```

**Comment by haferburg** [comment] 2017-06-02 15:49
```
stdout:
  handle valid: 1
  mode 1: 00000003
  SetConsoleMode fail, err: 87
stderr:
  handle valid: 1
  mode 1: 00000003
  SetConsoleMode fail, err: 87
```

**Comment by laszlocsomor** [comment] 2017-06-02 15:51
Thanks! 87 is ERROR_INVALID_PARAMETER.
Which version of Windows is it? Run winver.exe to find out.

**Comment by laszlocsomor** [comment] 2017-06-02 15:52
I'm guessing your version of cmd.exe doens't support ENABLE_VIRTUAL_TERMINAL_PROCESSING.

**Comment by haferburg** [comment] 2017-06-02 15:56
Windows 7 Ultimate
Version 6.1 (Build 7601: Service Pack 1)

It does work with the 0.4.5 executable, though.

**Comment by haferburg** [comment] 2017-06-02 15:58
You seem to right. When I remove ENABLE_VIRTUAL_TERMINAL_PROCESSING flag, the output changes to:
```
stdout:
  handle valid: 1
  mode 1: 00000003
  mode 2: 00000003
stderr:
  handle valid: 1
  mode 1: 00000003
  mode 2: 00000003
```

**Comment by haferburg** [comment] 2017-06-02 16:01
https://stackoverflow.com/questions/38772468/setconsolemode-and-enable-virtual-terminal-processing
> It was added in the Win10 SDK. Your SDK is older, 8.1 probably. I'd assume you'll also need Win10 to use it.

**Comment by laszlocsomor** [comment] 2017-06-02 16:02
Ah, good find! We build Bazel with the Win10 SDK, so maybe Win7 itself doesn't know about this mode yet.

**Comment by laszlocsomor** [comment] 2017-06-02 16:04
> It does work with the 0.4.5 executable, though.

0.4.5 was not using native Windows API yet.  So this is clearly a bug in Bazel.  We can fix that in the next version (0.5.2 or 0.6.0).

**Comment by haferburg** [comment] 2017-06-02 16:08
Cool! To be fair, the MSDN documentation is a bit lacking.

Reopen?

**Comment by pbos** [comment] 2017-06-05 07:21
Just in case this changes anything, I'm seeing this in Microsoft Windows [Version 10.0.15063] (so it doesn't look tied to running under Win 7).

**Comment by laszlocsomor** [comment] 2017-06-06 05:57
@pbos : Thanks, that's good to know! What's the output of my second program on your machine? (https://github.com/bazelbuild/bazel/issues/3108#issuecomment-305826516)

**Comment by pbos** [comment] 2017-06-06 06:05
[32mINFO: [0mElapsed time: 7.731s, Critical Path: 2.22s

C:\Users\msft\Dev\foo>.\bazel-bin\main\foo.exe
stdout:
  handle valid: 1
  mode 1: 00000003
  mode 2: 00000007
stderr:
  handle valid: 1
  mode 1: 00000007
  mode 2: 00000007

**Comment by pbos** [comment] 2017-06-06 06:13
With the following snippet added (for me to be able to compile at all):

#ifndef ENABLE_VIRTUAL_TERMINAL_PROCESSING
// From MSDN about BOOL SetConsoleMode(HANDLE, DWORD).
#define ENABLE_VIRTUAL_TERMINAL_PROCESSING 0x0004
#endif  // not ENABLE_VIRTUAL_TERMINAL_PROCESSING

I get color from the example program in https://msdn.microsoft.com/en-us/library/windows/desktop/mt638032(v=vs.85).aspx (under Samples). Is wprintf and x64 a hint here? Taking random stabs in the air.

**Comment by pbos** [comment] 2017-06-06 06:16
Didn't see that there were more than one sample on that page. The first sample (Example of SGR terminal sequences) is the one I get working with the above patch added.

**Comment by laszlocsomor** [comment] 2017-06-06 06:54
@pbos : 
> Is wprintf and x64 a hint here?

I don't think so. Since you're on Win10 and SetConsoleMode succeeded, color output will work for you if we fix Bazel to call SetConsoleMode. ([Currently it doesn't](https://github.com/bazelbuild/bazel/blob/76555482873ffcf1d32fb40106f89231b37f850a/src/main/cpp/blaze_util_windows.cc#L1366-L1380).)

**Comment by pbos** [comment] 2017-06-06 18:41
This is pretty much a stock choco install bazel installation, on a x64 Win10 build, can you reproduce that on your end? Otherwise let me know if there's something useful I can run/test, but I think this'll be faster if you can repro.

**Comment by laszlocsomor** [comment] 2019-02-28 14:31
I just tried Bazel 0.23.0 in cmd.exe on a clean Windows 10 install (version 1607) and the output looks fine. Please reopen if you see this bug with current Bazel versions.

**Comment by laszlocsomor** [comment] 2019-03-19 14:22
Colored output doesn't work in Windows 7's cmd.exe with Bazel 0.23.2

**Comment by laszlocsomor** [comment] 2019-07-08 09:13
Still a bug on Windows 7's terminal with Bazel 0.27

**Comment by konste** [comment] 2019-11-16 20:37
@laszlocsomor The bug is still present in Bazel 1.1.0 and Windows 10 1809. I even tried this workaround ```[HKEY_CURRENT_USER\Console]
"VirtualTerminalLevel"=dword:00000001``` but still get no color output in cmd.exe console. Bazel command line is --color=yes. It affects Bazel command line usability substantially. Could somebody please look into it?

**Comment by laszlocsomor** [comment] 2019-11-20 09:19
Sorry, I cannot look at it any time soon. Is this causing any problems beyond colorless output?

**Comment by konste** [comment] 2019-11-20 16:25
No, just colorless output. I guess it can wait, unless somebody else would agree to look into it.

**Comment by konste** [comment] 2019-11-27 16:50
Let me take that back - Bazel output in Windows console DOES use color when configured. Errors definitely come out in red. When there are no errors the output is not colored, that's what made me think the color does not work. I guess this issue may be closed.

**Comment by laszlocsomor** [comment] 2019-11-28 07:04
@konste : Thanks for writing that!

I'll leave it open though, the bug is not fixed on Windows 7.

**Comment by konste** [comment] 2019-11-28 13:39
Microsoft ends support for Windows 7 on January 14, 2020 which lowers priority of this issue to practically zero.

**Closed** 2020-05-12 09:44 UTC
Labels: P4, platform: windows, team-Windows, type: bug
