### ISSUE TITLE
Format elapsed time and critical path time

### ISSUE THREAD

**Issue by marekkrk** [bazelbuild/bazel#22331] opened 2024-05-11 07:53 UTC
### Description of the feature request:

Bazel currently formats elapsed build time and critical path time in seconds. Example:
Elapsed time: 23120.370s, Critical Path: 131.10s

It would be good to use human friendly formatting, for example:
Elapsed time: 6h 25m 20.370s, Critical Path: 2m 11.10s

### Which category does this issue belong to?

CLI

### What underlying problem are you trying to solve with this feature?

Usability

### Which operating system are you running Bazel on?

Linux

### What is the output of `bazel info release`?

release 7.1.2

**Comment by brentleyjones** [comment] 2024-05-11 13:41
@katre most recently (iirc) tried to address this.

**Comment by nikhilkalige** [comment] 2024-05-11 20:25
Similar request  #17137

**Comment by katre** [comment] 2024-05-13 21:05
I took a look at this a few months ago and didn't make much progress. The underlying issue was mostly down to code complexity: in various places we're using `Duration`, `int`, `long`, and `double` to hold data that is either `Duration`, seconds, or milliseconds, and trying to resolve it all was too complex.

I'd love to see better progress here, so don't let me discourage you, but there aren't any quick fixes to be had, unfortunately.

**Comment by oquenchil** [comment] 2024-05-14 09:18
Duplicate of https://github.com/bazelbuild/bazel/issues/17137

**Closed by oquenchil** 2024-05-14 09:18 UTC
Labels: type: feature request, untriaged, team-CLI
