### ISSUE TITLE
Old versions of Bazel can't be installed from the apt repo

### ISSUE THREAD

**Issue by drigz** [bazelbuild/bazel#3884] opened 2017-10-10 16:26 UTC
Old versions of Bazel can't be installed from the apt repo. At time of writing, only 0.6.1 can be installed. Even though the old debs are still in the pool/ directory, only 0.6.1 is listed in [Packages](http://storage.googleapis.com/bazel-apt/dists/stable/jdk1.8/binary-amd64/Packages).

We ran in to this because we use a Dockerfile (based on [dazel's](https://github.com/nadirizr/dazel/blob/master/Dockerfile)) that installs a fixed release of Bazel to provide a stable build environment.

If this is working as intended, what is the recommended way to install a fixed binary release of Bazel?

### Reproduction

```
echo "deb [arch=amd64] http://storage.googleapis.com/bazel-apt stable jdk1.8" > \
         /etc/apt/sources.list.d/bazel.list \
 && curl https://storage.googleapis.com/bazel-apt/doc/apt-key.pub.gpg | apt-key add - \
 && apt-get update \
 && apt-get install -y --no-install-recommends bazel=0.5.4
```

### Workaround

Manually install the dependencies then install the .deb from GitHub:

```
apt-get install -y --no-install-recommends \
   bash-completion \
   g++ \
   zlib1g-dev \
 && curl -LO "https://github.com/bazelbuild/bazel/releases/download/${BAZEL_VERSION}/bazel_${BAZEL_VERSION}-linux-x86_64.deb" \
 && dpkg -i bazel_*.deb
```

### Environment info
* Operating System: Debian Jessie
* Bazel version: 0.5.4

**Comment by damienmg** [comment] 2017-10-11 09:06
Duplicate of https://github.com/bazelbuild/continuous-integration/issues/128

**Closed by damienmg** 2017-10-11 09:06 UTC
Labels: category: misc > release / binary, P2, type: feature request
