### ISSUE TITLE
TMP: gtest doesn't work without `--test_env TMP=/tmp` on Windows

### ISSUE THREAD

**Issue by rokstrnisa** [bazelbuild/bazel#1590] opened 2016-08-01 09:33 UTC
Running `bazel test --cpu='x64_windows_msvc' --verbose_failures` with gtest given the following error

```
...
[ FATAL ] C:\tools\msys64\var\tmp\Bazel\$KNt4ZiP\execroot\everything\external\gtest\src\gtest-port.cc(526):: Condition success != 0 failed. Unable to create a temporary file in C:\Windows\
...
```

However, adding `--test_env TMP=/tmp` to the command fixes the problem.

Context: Bazel 0.3.0.

**Comment by dslomov** [comment] 2016-08-02 10:55
There is nothing to investigate, we should figure out how to provide a sensible TMP location to rlues

**Comment by laszlocsomor** [comment] 2016-08-18 14:51
@dslomov: We can implement a native `mktemp -d` utility using `GetTempPath` and `GetTempFileName. Do you see any problems with that?

**Comment by laszlocsomor** [comment] 2016-08-24 09:20
I also ran into problems lately with handing `$TMP`. See https://github.com/bazelbuild/bazel/issues/1589#issuecomment-241803557

**Comment by laszlocsomor** [comment] 2016-09-06 07:50
@rokstrnisa : What target were you testing? Can you repro with bazel built at HEAD (say, https://github.com/bazelbuild/bazel/commit/ff122f34ca4be2c05a011431d11b50252530c84a)?

**Comment by rokstrnisa** [comment] 2016-09-22 14:14
On ff122f3, it fails due to a different issue, both with or without the `--text_env` argument.

    $ /home/rok/bazel/output/bazel.exe version
    Build label: 0.3.1-2016-09-22 (@ff122f3)
    $ /home/rok/bazel/output/bazel.exe test --verbose_failures --cpu='x64_windows_msvc' --host_cpu='x64_windows_msvc' --test_env TMP=/tmp cpp/protocgenfabric/...
    INFO: Found 2 targets and 1 test target...
    ERROR: C:/tools/msys64/var/tmp/Bazel/$KNt4ZiP/external/protobuf/BUILD:29:1: C++ compilation of rule '@protobuf//:protobuf_lite' failed: msvc_cl.bat failed: error executing command
      cd C:/tools/msys64/var/tmp/Bazel/$KNt4ZiP/execroot/everything
      SET PATH=external/local_config_cc/wrapper/bin
      external/local_config_cc/wrapper/bin/msvc_cl.bat -m64 /D__inline__=__inline /DOS_WINDOWS=OS_WINDOWS /DCOMPILER_MSVC /DNOGDI /DNOMINMAX /DPRAGMA_SUPPORTED /D_WIN32_WINNT=0x0600 /D_CRT_SECURE_NO_DEPRECATE /D_CRT_SECURE_NO_WARNINGS /D_SILENCE_STDEXT_HASH_DEPRECATION_WARNINGS /D_USE_MATH_DEFINES /nologo /bigobj /Zm500 /J /Gy /GF /W3 /EHsc /wd4351 /wd4291 /wd4250 /wd4996 /DNDEBUG /Od -Xcompilation-mode=fastbuild /Iexternal/protobuf /Ibazel-out/vc_14_0_x64-fastbuild/genfiles/external/protobuf /Iexternal/bazel_tools /Ibazel-out/vc_14_0_x64-fastbuild/genfiles/external/bazel_tools /Iexternal/protobuf/src /Ibazel-out/vc_14_0_x64-fastbuild/genfiles/external/protobuf/src /Iexternal/bazel_tools/tools/cpp/gcc3 /DEPENDENCY_FILE bazel-out/vc_14_0_x64-fastbuild/bin/external/protobuf/_objs/protobuf_lite/external/protobuf/src/google/protobuf/io/coded_stream.d /c external/protobuf/src/google/protobuf/io/coded_stream.cc /Fobazel-out/vc_14_0_x64-fastbuild/bin/external/protobuf/_objs/protobuf_lite/external/protobuf/src/google/protobuf/io/coded_stream.o -DHAVE_PTHREAD -Wall -Wwrite-strings -Woverloaded-virtual -Wno-sign-compare -Wno-error=unused-function: com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.
    The system cannot find the path specified.

**Comment by laszlocsomor** [comment] 2017-09-06 18:46
Duplicate of #2870 and #2349.

**Comment by petemounce** [comment] 2017-09-07 10:00
I'm affected by this on bazel 0.5.3.

**Comment by laszlocsomor** [comment] 2017-11-14 14:55
Closing because actions now always have a temp directory.

**Closed** 2017-11-14 14:54 UTC
Labels: category: multi-platform > windows, P2, type: bug
