### ISSUE TITLE
sandboxed rules broken on macos when output_base and workspace have differing case sensitivity

### ISSUE THREAD

**Issue by znull** [bazelbuild/bazel#2610] opened 2017-03-01 01:23 UTC
* Operating System:

macOS Sierra 10.12.3 (16D32)

* Bazel version (output of `bazel info release`):
```
➤ bazel info release
release 0.4.5rc2
```

```
➤ grep . WORKSPACE BUILD input.txt
BUILD:genrule(
BUILD:	name = 'foo',
BUILD:	outs = ['foo.txt'],
BUILD:	cmd = '''perl -ne 's/bar/foo/' < $(location :input.txt) > $@''',
BUILD:	tools = [':input.txt'],
BUILD:)
input.txt:bar
[lunz](0)➤ bazel build //:foo
INFO: Found 1 target...
ERROR: /Volumes/dev/code/bug/BUILD:1:1: Executing genrule //:foo failed: Process exited with status 1 [sandboxed].
/bin/bash: ./input.txt: Operation not permitted
Use --strategy=Genrule=standalone to disable sandboxing for the failing actions.
Target //:foo failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 0.227s, Critical Path: 0.03s
```

**Comment by hermione521** [comment] 2017-03-01 12:02
Sorry I can't reproduce it. Can you confirm it only happens for 0.4.5-rc2?

**Comment by katre** [comment] 2017-03-01 12:06
input.txt should be listed under "srcs", not "tools", since it's acting as an input and not as something being executed. I suspect that's the cause of the error you're seeing, please try and let us know.

**Comment by znull** [comment] 2017-03-01 18:21
It was originally `srcs` but I switched it to `tools` in an effort to get things working. The original bug was with a `srcs` input.

**Comment by znull** [comment] 2017-03-01 18:23
Also, I've discovered that this doesn't just affect genrules. The full set of flags I need to get my macos build working is: `--strategy=Genrule=standalone  --strategy=CppCompile=standalone --strategy=Generating=standalone --strategy=Turbine=standalone --strategy=WAR=standalone --s
trategy=TestRunner=standalone`

**Comment by znull** [comment] 2017-03-01 18:24
@hermione521 I can confirm that bazel 0.4.4 worked fine. I haven't checked `0.4.5-rc1`.

**Comment by znull** [comment] 2017-03-01 18:38
I just tried this on a different mac and it doesn't repro there at all.

**Comment by znull** [comment] 2017-03-01 22:31
I figured out what was going on here:
- the workspace is on a case-sensitive partition
- normally, I use a `~/.bazelrc` that contains `startup --output_user_root=/Volumes/dev/tmp/bazel` so that the `output_base` is also on the case-sensitive partition

however, the installer script renamed my `~/.bazelrc` to `~/.bazelrc.bak`, so the `output_base` reverted to `/tmp`, which is case-insensitive. In that configuration, most macos sandboxing is apparently broken.

**Comment by katre** [comment] 2017-03-02 08:49
I don't have access to a Mac until next week, I can investigate this then if no one can look before Monday.

**Comment by katre** [comment] 2017-03-06 19:55
I'm not able to reproduce this, but I did need to change your BUILD file to work on my Mac.

Here's the updated BUILD file. Note that I had to change "perl -ne" to "perl -pe" (perl -n doesn't automatically print lines as they are matched):
```
genrule(
        name = 'foo',
        outs = ['foo.txt'],
        cmd = '''perl -pe "s/bar/foo/" < $(location :input.txt) > $@''',
        srcs = [':input.txt'],
)
```

Also, what are the permissions on your input.txt? "Operation not permitted" is a surprising error.

**Comment by susinmotion** [comment] 2020-04-15 20:24
@znull , is this still an issue?

**Comment by znull** [comment] 2020-04-15 20:50
I'm afraid this time I'm the one without access to a mac, so I'm unable to say. Thanks for looking into it.

**Comment by jmmv** [comment] 2020-04-16 19:55
Sandboxed builds work fine on a Mac so the problem here, if still present, is likely due to some case preserving issue when moving files into and out of the sandbox.

Given that this is very unlikely to surface, previous attempts at reproducing this failed, and we don't know if it's still a problem 3 years later... I think we should close this.

**Closed by jmmv** 2020-04-16 19:55 UTC
Labels: team-Local-Exec, under investigation, untriaged
