### ISSUE TITLE
Top-level test rules execute wrong binaries

### ISSUE THREAD

**Issue by yugui** [bazelbuild/bazel#1443] opened 2016-06-24 01:32 UTC
The test driver `//tools/test/test-setup.sh` executes commands on `$PATH` instead of the actual test targets when the target test rule is defined in the top level package in the main workspace.
# How to reproduce
1. Put the following `BULID` file and `true.sh` into a top level package in a main workspace.
   - `BUILD`:
     
     ``` bzl
     sh_test(
      name = "false",
      srcs = ["true.sh"],
     )
     ```
   - `true.sh`:
     
     ``` sh
     #!/bin/sh -eu
     true
     ```
2. run the test
   
   ``` console
   $ bazel test -s --curses=no --show_progress_rate_limit 0 //:false
   ```
# Expected result

The test succeeds.
# Actual result

The test fails.

``` console
$ bazel test -s --curses=no --show_progress_rate_limit 0 //:false
INFO: Loading...
INFO: Loading package: @bazel_tools//tools/cpp
INFO: Loading package: @bazel_tools//tools/objc
INFO: Loading package: @bazel_tools//tools/android
INFO: Loading package: @bazel_tools//tools/jdk
INFO: Loading package: @local_jdk//
INFO: Loading package: @local_config_cc//
INFO: Loading complete.  Analyzing...
INFO: Loading package: @bazel_tools//tools/test
INFO: Found 1 test target...
INFO: Building...
[0 / 1] BazelWorkspaceStatusAction stable-status.txt
[1 / 4] Symlinking //:false
[2 / 4] Creating source manifest for //:false
[3 / 4] Creating runfiles tree bazel-out/local-fastbuild/bin/false.runfiles
>>>>> # //:false [action 'Creating runfiles tree bazel-out/local-fastbuild/bin/false.runfiles']
(cd /home/vagrant/.cache/bazel/_bazel_vagrant/f8b1624e52e29221ef8ba6d384abb939/execroot/t && \
  exec env - \
    PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/local/go/bin:/opt/go/bin \
  /home/vagrant/.cache/bazel/_bazel_vagrant/f8b1624e52e29221ef8ba6d384abb939/execroot/t/_bin/build-runfiles bazel-out/local-fastbuild/bin/false.runfiles_manifest bazel-out/local-fastbuild/bin/false.runfiles)
[4 / 5] Testing //:false
>>>>> # //:false [action 'Testing //:false']
(cd /home/vagrant/.cache/bazel/_bazel_vagrant/f8b1624e52e29221ef8ba6d384abb939/execroot/t && \
  exec env - \
    JAVA_RUNFILES=/home/vagrant/.cache/bazel/_bazel_vagrant/f8b1624e52e29221ef8ba6d384abb939/execroot/t/bazel-out/local-fastbuild/bin/false.runfiles \
    PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/local/go/bin:/opt/go/bin \
    PYTHON_RUNFILES=/home/vagrant/.cache/bazel/_bazel_vagrant/f8b1624e52e29221ef8ba6d384abb939/execroot/t/bazel-out/local-fastbuild/bin/false.runfiles \
    TEST_SIZE=medium \
    TEST_SRCDIR=/home/vagrant/.cache/bazel/_bazel_vagrant/f8b1624e52e29221ef8ba6d384abb939/execroot/t/bazel-out/local-fastbuild/bin/false.runfiles \
    TEST_TIMEOUT=300 \
    TEST_TMPDIR=/home/vagrant/.cache/bazel/_bazel_vagrant/f8b1624e52e29221ef8ba6d384abb939/execroot/t/_tmp/false_1 \
    TEST_WORKSPACE=__main__ \
    TZ=UTC \
    XML_OUTPUT_FILE=/home/vagrant/.cache/bazel/_bazel_vagrant/f8b1624e52e29221ef8ba6d384abb939/execroot/t/bazel-out/local-fastbuild/testlogs/false/test.xml \
  external/bazel_tools/tools/test/test-setup.sh false)
FAIL: //:false (see /home/vagrant/.cache/bazel/_bazel_vagrant/f8b1624e52e29221ef8ba6d384abb939/execroot/t/bazel-out/local-fastbuild/testlogs/false/test.log).
INFO: Building complete.
Target //:false up-to-date:
  bazel-bin/false
INFO: Elapsed time: 2.395s, Critical Path: 0.05s
//:false                                                                 FAILED in 0.0s
  /home/vagrant/.cache/bazel/_bazel_vagrant/f8b1624e52e29221ef8ba6d384abb939/execroot/t/bazel-out/local-fastbuild/testlogs/false/test.log

Executed 1 out of 1 test: 1 fails locally.
$ cat /home/vagrant/.cache/bazel/_bazel_vagrant/f8b1624e52e29221ef8ba6d384abb939/execroot/t/bazel-out/local-fastbuild/testlogs/false/test.log 
exec ${PAGER:-/usr/bin/less} "$0" || exit 1
-----------------------------------------------------------------------------
```

Contrarily, the test binary returns a status code 0 if I `run` it instead of `test`.

``` console
$ bazel run -s --curses=no --show_progress_rate_limit 0 //:false
INFO: Loading...
INFO: Loading complete.  Analyzing...
INFO: Found 1 target...
INFO: Building...
[0 / 1] BazelWorkspaceStatusAction stable-status.txt
INFO: Building complete.
Target //:false up-to-date:
  bazel-bin/false
INFO: Elapsed time: 0.423s, Critical Path: 0.00s

INFO: Running command line: bazel-bin/false
$ echo $?
0
```
## Investigation

In my understanding, the test driver `//tools/test/test-setup.sh` executes `/bin/false` instead of `bazel-bin/false`.  That's why the test fails.
# Platforms reproduced
- Ubuntu 14.04 / Bazel 0.3.0
  
  ``` console
  $ uname -a
  Linux master 3.13.0-86-generic #131-Ubuntu SMP Thu May 12 23:33:13 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
  $ cat /etc/lsb-release
  DISTRIB_ID=Ubuntu
  DISTRIB_RELEASE=14.04
  DISTRIB_CODENAME=trusty
  DISTRIB_DESCRIPTION="Ubuntu 14.04.4 LTS"
  $ bazel version
  Build label: 0.3.0
  Build target: bazel-out/local-fastbuild/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
  Build time: Fri Jun 10 11:38:23 2016 (1465558703)
  Build timestamp: 1465558703
  Build timestamp as int: 1465558703
  ```
- Mac OS X 10.11.5 / Bazel 0.3.0
  
  ``` console
  $ uname -a
  Darwin yugui-macbookpro-3.local 15.5.0 Darwin Kernel Version 15.5.0: Tue Apr 19 18:36:36 PDT 2016; root:xnu-3248.50.21~8/RELEASE_X86_64 x86_64
  $ sw_vers
  ProductName:    Mac OS X
  ProductVersion: 10.11.5
  BuildVersion:   15F34
  $ bazel version
  Build label: 0.3.0
  Build target: bazel-out/local-fastbuild/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
  Build time: Fri Jun 10 11:38:43 2016 (1465558723)
  Build timestamp: 1465558723
  Build timestamp as int: 1465558723
  ```

**Comment by philwo** [comment] 2016-06-24 06:48
Thanks for the thorough description and investigation! This sounds like a pretty bad bug to me.

**Comment by damienmg** [comment] 2016-06-27 11:10
Why was I assigned to that bug?

**Comment by philwo** [comment] 2016-06-27 11:32
@damienmg Why not? :) Someone should look into this and I remember that you worked on our shell test framework in the past. Do you have a better person to assign this to?

**Comment by damienmg** [comment] 2016-06-27 11:41
This is loosely connected to our test framework, we have another related bug somewhere about not having ./ prefix on top level target in location expansion.

All tests target that are in the top-level package will not work.

**Comment by ulfjack** [comment] 2016-12-08 16:44
I cannot reproduce this at head. It looks like a148b4c2 fixed this as a side effect.

**Closed by ulfjack** 2016-12-08 16:44 UTC
Labels: category: misc > testing, P2, type: bug
