### ISSUE TITLE
cc_test failed to compile with a binary in deps which can be compiled successfully alone

### ISSUE THREAD

**Issue by tanglrHello** [bazelbuild/bazel#7507] opened 2019-02-22 12:10 UTC
I have a project depending on a third-party library [libcarla](https://github.com/carla-simulator/carla/tree/master/LibCarla).

To simplify the problem, my BUILD file is someting like this:

cc_library(
  name = "myservice",
  srcs = [...],
  hdrs = [...],
  deps = [
     @libcarla//:libcarla
  ]
)

cc_test(
  name = "mytest",
  srcs = [...],
  hdrs = [...],
  deps = [
    "myservice",      // line AAA
    "@gtest//:main"
  ]
)

With "bazel build myservice", compilation succeeded.
But when I run "bazel build mytest", there are some link errors. 

ERROR: BUILD:76:1: Linking of rule '//:mytest' failed (Exit 1).
bazel-out/local-fastbuild/bin/_solib_k8/libexternal_Slibcarla_Sliblibcarla.so: error: undefined reference to 'boost::filesystem::detail::create_directories(boost::filesystem::path const&, boost::system::error_code*)'
bazel-out/local-fastbuild/bin/_solib_k8/libexternal_Slibcarla_Sliblibcarla.so: error: undefined reference to 'boost::filesystem::path::extension() const'
bazel-out/local-fastbuild/bin/_solib_k8/libexternal_Srpclib_Slibrpclib_Udependencies.so: error: undefined reference to 'SSL_CTX_ctrl'
bazel-out/local-fastbuild/bin/_solib_k8/libexternal_Srpclib_Slibrpclib_Udependencies.so: error: undefined reference to 'SSL_ctrl'
bazel-out/local-fastbuild/bin/_solib_k8/libexternal_Srpclib_Slibrpclib_Udependencies.so: error: undefined reference to 'OPENSSL_add_all_algorithms_noconf'
bazel-out/local-fastbuild/bin/_solib_k8/libexternal_Srpclib_Slibrpclib_Udependencies.so: error: undefined reference to 'CONF_modules_unload'
bazel-out/local-fastbuild/bin/_solib_k8/libexternal_Srpclib_Slibrpclib_Udependencies.so: error: undefined reference to 'ENGINE_cleanup'
collect2: error: ld returned 1 exit status
Target //:mytest failed to build

If line AAA is removed,  bazel build mytest will succeed. If I replace "myservice" with "@libcarla//:libcarla" in line AAA, the compilation complains even more similar errors.

What might be the problem and is there any way to solve it ?  Looking forward to any advice. Thanks!

**Comment by tanglrHello** [comment] 2019-02-26 06:17
Refer to https://github.com/bazelbuild/bazel/issues/2944 and add linkstatic = 1 in cc_test ruls, the problem is solved.

**Comment by scentini** [comment] 2019-02-26 09:03
Duplicate of #2944, closing.

**Closed by scentini** 2019-02-26 09:03 UTC
Labels: team-Rules-CPP, type: support / not a bug
