### ISSUE TITLE
_lcov_merger late-bound test attribute

### ISSUE THREAD

**Issue by keith** [bazelbuild/bazel#10642] opened 2020-01-23 19:07 UTC
I went to add `_lcov_merger` as an attribute for iOS tests here https://github.com/bazelbuild/rules_apple/pull/691 and there was some discussion about making this tool a late-bound attribute so we wouldn't incur overhead for this tool always. It doesn't seem like there's an API that currently allows us to do this.

There was also some discussion of if the attribute makes sense to be on every test rule or if it should be more global, maybe with a flag like `--lcov_merger` with this tool as the default.

I wanted to file this here so we could discuss this and unblock iOS tests supporting coverage.

**Comment by ulfjack** [comment] 2021-07-14 15:01
This looks like a dupe of #8736.

**Closed** 2022-03-08 10:11 UTC
Labels: type: feature request, P3, coverage, team-Rules-Server
