### ISSUE TITLE
Allow .bazel extension for the WORKSPACE file

### ISSUE THREAD

**Issue by mgechev** [bazelbuild/bazel#7829] opened 2019-03-25 17:19 UTC
### Description of the problem / feature request:

Allow `.bazel` extension on the `WORKSPACE` file.

### Feature requests: what underlying problem are you trying to solve with this feature?

Similarly to `BUILD` and `BUILD.bazel` files, for consistency allow `WORKSPACE` to have a `.bazel` extension.

// cc @alexeagle

**Comment by jin** [comment] 2019-03-25 22:18
This is a dupe of https://github.com/bazelbuild/bazel/issues/3885.

**Closed by jin** 2019-03-25 22:18 UTC
Labels: team-Product, untriaged
