### ISSUE TITLE
Symbolic link in new_http_archive causes error

### ISSUE THREAD

**Issue by iansimon** [bazelbuild/bazel#1997] opened 2016-10-27 18:38 UTC
This error occurs in 0.3.2 but not 0.3.1.

Here's an example that triggers it:

```
    new_http_archive(
      name = "music21",
      build_file = "music21.BUILD",
      url = "https://github.com/cuthbertLab/music21/releases/download/v3.0.3-alpha/music21-3.0.3.tar.gz",
      sha256 = "4c0cc1e1fa3638c53ecf45ec13301174114dcf59f93faffc6586c5b94ae065e3",
      strip_prefix = "music21-3.0.3/music21",
    )
```

When building, the following error occurs:

> File "LICENSE" linked from "LICENSE" does not exist and referenced by '//path/to:target'.

There are "LICENSE" symlinks in both music21-3.0.3 and music21-3.0.3/music21; presumably this has something to do with the error.

**Comment by laszlocsomor** [comment] 2016-10-31 10:49
I can't repro this because I'm missing `music21.BUILD`, but regardless, try renaming or removing the symlink and see if the error goes away.

**Comment by cghawthorne** [comment] 2016-10-31 16:58
In this case, we can't change the symlink because it exists in the music21 repo, which we don't control.

To repro, you can try building the Magenta repo at https://github.com/tensorflow/magenta. Our music21.BUILD file is here: https://github.com/tensorflow/magenta/blob/master/music21.BUILD

**Comment by jellysquider** [comment] 2016-11-06 09:53
Does the same issue persist in bazel 0.4.0?

**Comment by cghawthorne** [comment] 2016-11-07 18:59
I no longer see the problem with 0.4.0.

**Comment by laszlocsomor** [comment] 2016-11-08 09:36
Thanks! Please reopen the bug if it comes up again.

**Comment by jellysquider** [comment] 2016-11-14 09:10
When I asked my question previously I was still in the process of installing tensorflow, so today I was finally able to set up everything, but ` bazel test //magenta/...` failed to run with the aforementioned error.

> 
/anaconda/envs/magenta/magenta/music/BUILD:44:1: no such package '@music21//': File "LICENSE" linked from "LICENSE" does not exist and referenced by '//magenta/music:chord_symbols_lib'.

[For some people downgrading to 0.3.1 helped.](https://groups.google.com/a/tensorflow.org/forum/#!topic/magenta-discuss/lO2Hd2aQkQQ)

Please reopen the case.

**Comment by kchodorow** [comment] 2016-11-14 18:23
Okay, reproduced.  music21-3.0.3/music21/LICENSE is a hard link to music21-3.0.3/LICENSE. Because of the `strip_prefix = "music21-3.0.3/music21"`, music21-3.0.3/LICENSE doesn't exist.

**Comment by kchodorow** [comment] 2016-11-14 18:31
A possible solution is to extract archives in a series of steps:

1. Extract everything to a temp dir, keeping a list of symbolic links.
2. Move the directory specified by strip_prefix into its place under external, thus preserving all hard links. 
3. Check each soft link on the list and, if it no longer resolves, copy over the actual content of the symlinked file.
4. Delete the temp dir.

**Comment by hazelnusse** [comment] 2017-03-09 02:45
I've created a minimal working example of this problem here:
https://github.com/hazelnusse/bazel-tests

I see this problem whenever there is a symlink that points to a file that is higher in the directory tree than the symlink is.

**Comment by hazelnusse** [comment] 2017-03-09 02:46
Possible duplicate of:
https://github.com/bazelbuild/bazel/issues/2656

**Comment by dslomov** [comment] 2018-01-11 17:10
Closing in favor of #2656

**Closed by dslomov** 2018-01-11 17:10 UTC
Labels: P2, category: extensibility > external repositories, type: bug
