### ISSUE TITLE
Bazel on Alpine Linux

### ISSUE THREAD

**Issue by pspeter3** [bazelbuild/bazel#1492] opened 2016-07-08 18:53 UTC
I've been thinking about developing with Bazel inside of docker containers so that way I can have sandboxing on Mac. Is it possible to use Bazel with Alpine Linux or is Ubuntu required?

**Comment by kchodorow** [comment] 2016-07-11 13:41
I don't think anyone's tried it, but we'd love to hear how it goes.

**Comment by pspeter3** [comment] 2016-07-12 05:49
So I tried running it with this Dockerfile and get the below error. My best guess is that `unzip` does not work with the self extracting archive.

```Dockerfile
FROM alpine:3.4
RUN apk add --no-cache \
  bash=4.3.42-r3 \
  bash-completion=2.1-r2 \
  ca-certificates=20160104-r4 \
  g++=5.3.0-r0 \
  openjdk8=8.92.14-r1 \
  pkgconf=0.9.12-r0 \
  unzip=6.0-r1 \
  wget=1.17.1-r1 \
  zip=3.0-r4 \
  zlib-dev=1.2.8-r2
ENV JAVA_HOME /usr/lib/jvm/default-jvm
RUN wget -O bazel-installer.sh -q \
  https://github.com/bazelbuild/bazel/releases/download/0.3.0/bazel-0.3.0-installer-linux-x86_64.sh \
  && bash bazel-installer.sh \
  && rm bazel-installer.sh
```

```sh
bash-4.3$ bazel
/usr/local/bin/bazel: line 86: /usr/local/lib/bazel/bin/bazel-real: No such file or directory
```

**Comment by AmandaCameron** [comment] 2016-07-22 19:19
I did some digging into this today, specifically to see why bazel can't build under alpine, and I believe it's failing in the protoc step, because the grpc protoc plugin isn't statically compiled, so it's failing to find a shared object it needs.

However I can't be sure, because it just dies instantly after printing "Building bazel from scratch."

**Comment by kchodorow** [comment] 2016-07-22 19:22
You can add set -x to compile.sh and it'll print each line as it executes.

**Comment by AmandaCameron** [comment] 2016-07-22 19:27
Yup, added that to compile.sh and can confirm it'e dying in the protoc step. Full log can be uploaded if wanted.

**Comment by pspeter3** [comment] 2016-07-22 21:27
Is there a way to ensure the shared object is in the Alpine container?

**Comment by bsilver8192** [comment] 2016-08-15 09:01
I have no experience with Alpine Linux or Docker, but I thought this looked interesting and got it working.

I think using the installer built for a different libc is pretty hopeless, but I did get building from scratch working with just a few tweaks.

I assume you tried to compile an older Bazel version before 168031d21624741411ac238373cbd8544b8948df, because I didn't see any issues with protoc shared libraries.

`third_party/grpc/protoc-gen-grpc-java-0.15.0-linux-x86_64.exe` is dynamically linked (but not to libstdc++), so I followed the directions in the README.md of [sgerrand/alpine-pkg-glibc](https://github.com/sgerrand/alpine-pkg-glibc) to install glibc.

I've sent out a few fixes, and there's something else going on that I think is busybox `env` handling a `--` in the arguments list differently. For now, removing the `commandLineArgs.add("--");` line from `src/main/java/com/google/devtools/build/lib/sandbox/LinuxSandboxRunner.java` makes it work on Alpine but breaks it on my Debian system.

I submitted grpc/grpc#7730 and [I2bd5ec198522ea1ea19df0aaa1eb7c6977217eb3](https://bazel-review.googlesource.com/#/q/I2bd5ec198522ea1ea19df0aaa1eb7c6977217eb3) to fix a few musl libc incompatibilities.

**Comment by r351574nc3** [comment] 2017-01-29 07:59
@bsilver8192 How did you get `./compile.sh` to use the `glibc-compat` from sgerrand/alpine-pkg-glibc? I added it to my docker image, but it didn't seem to solve anything for me. FYI, I added: `/usr/glibc-compat/bin:/usr/glibc-compat/sbin` to the front of my `PATH` as well as added `/usr/glibc-compat/lib` to `LD_LIBRARY_PATH`

**Comment by r351574nc3** [comment] 2017-01-29 08:00
I am trying to build **bazel-4.3** on **alpine-3.5**. I am running into the following compile error I believe is connected to libc compatibility:
```
  /tmp/bazel_XXGIjcLb/out/execroot/bazel_build/_bin/process-wrapper -1 5 - - /usr/bin/gcc -U_FORTIFY_SOURCE '-D_FORTIFY_SOURCE=1' -fstack-protector -Wall -Wl,-z,-relro,-z,now -B/usr/bin -B/usr/bin -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-canonical-system-headers -fno-omit-frame-pointer -g0 -O2 -DNDEBUG -ffunction-sections -fpermissive -fdata-sections '-std=c++0x' -MD -MF bazel-out/local-opt/bin/third_party/ijar/_objs/platform_utils/third_party/ijar/platform_utils.d '-frandom-seed=bazel-out/local-opt/bin/third_party/ijar/_objs/platform_utils/third_party/ijar/platform_utils.o' -iquote . -iquote bazel-out/local-opt/genfiles -iquote external/bazel_tools -iquote bazel-out/local-opt/genfiles/external/bazel_tools -isystem external/bazel_tools/tools/cpp/gcc3 -fno-canonical-system-headers -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' -c third_party/ijar/platform_utils.cc -o bazel-out/local-opt/bin/third_party/ijar/_objs/platform_utils/third_party/ijar/platform_utils.o).
In file included from third_party/ijar/platform_utils.cc:15:0:
./third_party/ijar/platform_utils.h:31:3: error: 'mode_t' does not name a type
   mode_t file_mode;
   ^~~~~~
./third_party/ijar/platform_utils.h: In function 'devtools_ijar::u4 devtools_ijar::stat_to_zipattr(const devtools_ijar::Stat&)':
./third_party/ijar/platform_utils.h:38:26: error: 'const struct devtools_ijar::Stat' has no member named 'file_mode'
   return (((u4)file_stat.file_mode) << 16) |
                          ^~~~~~~~~
./third_party/ijar/platform_utils.h: At global scope:
./third_party/ijar/platform_utils.h:51:35: error: 'mode_t' has not been declared
 bool write_file(const char* path, mode_t perm, const void* data, size_t size);
                                   ^~~~~~
./third_party/ijar/platform_utils.h:68:34: error: 'mode_t' has not been declared
 bool make_dirs(const char* path, mode_t perm);
                                  ^~~~~~
third_party/ijar/platform_utils.cc: In function 'bool devtools_ijar::stat_file(const char*, devtools_ijar::Stat*)':
third_party/ijar/platform_utils.cc:47:11: error: 'struct devtools_ijar::Stat' has no member named 'file_mode'
   result->file_mode = statst.st_mode;
           ^~~~~~~~~
third_party/ijar/platform_utils.cc: In function 'bool devtools_ijar::write_file(const char*, mode_t, const void*, size_t)':
third_party/ijar/platform_utils.cc:67:29: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   if (write(fd, data, size) != size) {
       ~~~~~~~~~~~~~~~~~~~~~~^~~~~~~
Target //src:bazel failed to build
```

Any ideas?

**Comment by kchodorow** [comment] 2017-04-06 17:14
It looks like mode_t is defined in a different header than on other systems.  Maybe try grepping to find where mode_t is defined in /usr/include.  third_party/ijar/platform_utils.cc is already including all of the places I'd expect to find it.  Maybe sys/file.h?

**Comment by dimpavloff** [comment] 2017-04-06 17:52
You can see a workaround in this Dockerfile which builds Bazel and TF with `musl` instead of `glibc`:
https://github.com/tatsushid/docker-alpine-py3-tensorflow-jupyter/blob/master/Dockerfile#L46

**Comment by davido** [comment] 2017-11-08 21:30
It seems, that those workarounds are not needed any more. Here is the working Dockerfile that is building Bazel on Alpine Linux.

Moreover, I'm looking in creating native bazel package for Alpine Linux, so that something like that:

```
apk add bazel
```

just work.

**Comment by pspeter3** [comment] 2017-11-08 21:31
Thanks! This should mean lighter docker containers for all

**Comment by davido** [comment] 2017-11-08 22:08
> Moreover, I'm looking in creating native bazel package for Alpine Linux, so that something like that:

Native Bazel package for Alpine Linux is [here](https://github.com/davido/bazel-alpine-package/blob/master/APKBUILD).

**Comment by perezd** [comment] 2017-11-09 00:54
NICE!!

**Comment by akofman** [comment] 2017-12-06 01:54
Hello all,
I think that as it is explained [here](https://bugs.alpinelinux.org/issues/8121), the issue is actually not from Bazel but from Buzybox. So imho the best and simplest solution is to add the `coreutils` dependency in your Dockerfiles.
As an example I did this Docker image and it works perfectly: https://hub.docker.com/r/alexiskofman/bazel-alpine/

**Comment by davido** [comment] 2017-12-06 05:52
> So imho the best and simplest solution is to add the coreutils dependency in your Dockerfiles.

Sure, but why are you worried about this diff line:
https://github.com/davido/bazel-alpine-package/blob/master/APKBUILD#L22

In the end users should be able to just say:

```
apk add bazel
```

BTW, the Bazel native package 0.8.0 is here: https://github.com/davido/bazel-alpine-package/releases/tag/0.8.0

**Comment by mhlopko** [comment] 2018-03-21 17:17
Closing since this is not really an issue anymore?

**Closed by mhlopko** 2018-03-21 17:17 UTC
Labels: P4, platform: other

**Comment by grzesuav** [comment] 2018-10-25 11:28
@davido @mhlopko abovementioned builds are not up to date (0.15.2 is latest there, yet we have 0.18.0). Is there any alternative way to get those binaries on alpine?

**Comment by KEINOS** [comment] 2019-09-04 01:35
[F.Y.I.] For those who're looking for the latest Bazel Alpine package (apk file like I do), check:

https://github.com/davido/bazel-alpine-package/releases

- Currently (2019/09/04) available Bazel versions: 
  - PreRelease: Bazel v0.26.1
  - Latest: Bazel v0.22.0

**Comment by kevinsimper** [comment] 2019-09-20 13:06
> apk add bazel

Just to anyone landing here from Google Search, you can't add bazel like that anymore.

**Comment by findmyname666** [comment] 2023-01-12 09:43
The last month I was using bazel binary downloaded from releases and it seems to work in Alpine.
For some reason it doesn't work now :(
Did anybody figure-out some process for it ?

**Comment by strophy** [comment] 2023-01-30 05:25
Thanks @yesudeep! I was able to use this to set up Bazel 6.0.0 on Alpine 3.17 for both amd64 and arm64 with a slightly more minimal Dockerfile as follows:
```
FROM alpine:3.17
RUN apk add --no-cache \
    bash \
    build-base \
    curl \
    linux-headers \
    openjdk11-jdk \
    python3 \
    unzip \
    zip

ARG BAZEL_VERSION=6.0.0
RUN mkdir -p /tmp/bazel-release
WORKDIR /tmp/bazel-release
RUN curl -sSLO https://github.com/bazelbuild/bazel/releases/download/${BAZEL_VERSION}/bazel-${BAZEL_VERSION}-dist.zip && unzip -q bazel-${BAZEL_VERSION}-dist.zip
RUN env EXTRA_BAZEL_ARGS="--tool_java_runtime_version=local_jdk" bash ./compile.sh
RUN install -D output/bazel /usr/local/bin/bazel
```

I noticed there are [packages for Alpine edge testing](https://pkgs.alpinelinux.org/packages?name=bazel*&branch=edge&repo=testing&arch=&maintainer=), but 4.2.2 suffers from [this bug](https://github.com/bazelbuild/bazel/pull/14391) which probably won't be fixed, and 5.3.2 is not available for aarch64, so building bazel from source using the above steps is the only way I know to be able to use it in QEMU.

**Comment by mowoe** [comment] 2023-05-09 08:09
Hi @strophy, thank you for the instructions! I am trying to build bazel in alpine on arm64 and was wondering how long you build roughly takes. While i can get the container to build, it takes ages, while building bazel on the host machine (M2 Air) takes 3-4 minutes.

**Comment by mowoe** [comment] 2023-05-09 13:44
Thank you @strophy,
i must have somehow overlooked the mentioned issue. 
Actually i only needed bazel to compile some tensorflow stuff, but as there are no bazel builds working with alpine, i tried building it in an alpine container.
This is until i realized that bazel *does* supply an arm64 build, but unfourtunately it is dynamically linked, which breaks libc stuff, as alpine uses `musl libc` and bazel uses `glibc`. 

I came across [these](https://github.com/sgerrand/alpine-pkg-glibc) glibc builds build for alpine, which unfourtunately do not include arm64 ones, however there is a [fork](https://github.com/SatoshiPortal/alpine-pkg-glibc) which does (being behind 1 minor version).

While certainly not optimal (you definetely notice the libc issues and i would not use it for production stuff), i got it to work in the end and for what im trying to do, it is working fine.

Here is the Dockerfile:
```Dockerfile
FROM python:3.10-alpine

RUN wget https://github.com/SatoshiPortal/alpine-pkg-glibc/releases/download/2.31-r0/glibc-bin-2.31-r0-aarch64.apk
RUN wget https://github.com/SatoshiPortal/alpine-pkg-glibc/releases/download/2.31-r0/glibc-2.31-r0-aarch64.apk
RUN apk add --force-overwrite --allow-untrusted glibc-2.31-r0-aarch64.apk
RUN apk add --force-overwrite --allow-untrusted glibc-bin-2.31-r0-aarch64.apk
RUN wget https://github.com/bazelbuild/bazel/releases/download/4.2.4/bazel-4.2.4-linux-arm64
RUN chmod +x ./bazel-4.2.4-linux-arm64
RUN apk add libstdc++6 libstdc++-dev libstdc++
CMD ["./bazel-4.2.4-linux-arm64","--version"]
```
```bash
$ docker build . -t bazel-arm
$ docker run --rm bazel-arm
./bazel-4.2.4-linux-arm64: /usr/lib/libstdc++.so.6: no version information available (required by ./bazel-4.2.4-linux-arm64)
bazel 4.2.4
$
```
The error about libstdc++ is described [here](https://github.com/sgerrand/alpine-pkg-glibc/issues/80), i havent had time to really look into it, but as far as i can see, everything seems to work fine anyway.
I know all of this has nothing to do with the actual issue, but i thought that it may help someone.
