### ISSUE TITLE
bazel-0.24.1-windows-x86_64 can't find vs 2019 build tools

### ISSUE THREAD

**Issue by raulftang** [bazelbuild/bazel#8031] opened 2019-04-14 14:12 UTC
### Description of the problem / feature request:

> I downloaded bazel-0.24.1-windows-x86_64 and build example as https://docs.bazel.build/versions/master/windows.html, but it gave following error
```
E:\Workspace\bazel>bazel build //examples/cpp:hello-world
INFO: Analysed target //examples/cpp:hello-world (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
ERROR: E:/workspace/bazel/examples/cpp/BUILD:3:1: C++ compilation of rule '//examples/cpp:hello-lib' failed (Exit 1)

The target you are compiling requires Visual C++ build tools.
Bazel couldn't find a valid Visual C++ build tools installation on your machine.

Visual C++ build tools seems to be installed at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC
But Bazel can't find the following tools:
    VCVARSALL.BAT, cl.exe, link.exe, lib.exe, ml64.exe

Please check your installation following https://docs.bazel.build/versions/master/windows.html#using

Target //examples/cpp:hello-world failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 0.218s, Critical Path: 0.06s
INFO: 0 processes.
FAILED: Build did NOT complete successfully
```
My VS 2019 installition do have VCVARSALL.BAT in 
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build

And cl.exe, link.exe, lib.exe, ml64.exe in
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.20.27508\bin\Hostx64\x64
### Feature requests: what underlying problem are you trying to solve with this feature?

> No error.

### What operating system are you running Bazel on?

> Windows 10 64 bit.

### What's the output of `bazel info release`?

> release 0.24.1.

###  Have you found anything relevant by searching the web?

> Nothing.
>
> Places to look:
> - StackOverflow: http://stackoverflow.com/questions/tagged/bazel
> - GitHub issues: https://github.com/bazelbuild/bazel/issues
> - email threads on https://groups.google.com/forum/#!forum/bazel-discuss

**Comment by jin** [comment] 2019-04-14 15:41
Duplicate of https://github.com/bazelbuild/bazel/issues/8028

**Closed by jin** 2019-04-14 15:41 UTC

**Comment by zuoyuwei** [comment] 2023-02-17 07:37
download and install 2019 build tools:https://blog.csdn.net/kl1411/article/details/128742533
