### ISSUE TITLE
Documentation issue: General Rules

### ISSUE THREAD

**Issue by bedbad** [bazelbuild/bazel#15110] opened 2022-03-24 07:18 UTC
Documentation URL: https://docs.bazel.build/versions/main/be/general.html
"
However, Bazel (but not Bazel) passes through the value of the user's PATH environment variable.

?

**Comment by sgowroji** [comment] 2022-03-24 08:24
Hi @bedbad, Could you please share more details with respect to your above query. Thanks!

**Comment by bedbad** [comment] 2022-03-24 08:31
That part of documentation is incomprehensible.

**Comment by pizzaz93** [comment] 2022-05-13 18:11
Duplicate of #13426 but the branch/link has been updated to `main`.

**Comment by sgowroji** [comment] 2022-05-27 11:50
Closing w.r.t Dupe https://github.com/bazelbuild/bazel/issues/13426#issuecomment-1139545181.

**Closed by sgowroji** 2022-05-27 11:50 UTC
Labels: type: documentation (cleanup), untriaged, team-Documentation
