### ISSUE TITLE
ios/arm platform resolves to armeabi-v7a instead of ios_armv7 with enable_cc_toolchain_resolution

### ISSUE THREAD

**Issue by steeve** [bazelbuild/bazel#9078] opened 2019-08-05 14:54 UTC
### Description of the problem / feature request:

When using `--incompatible_enable_cc_toolchain_resolution` and constraining on the following:
```
@platforms//os:ios
@platforms//cpu:arm
```

It seems the toolchain used is `armeabi-v7a` instead of `ios_armv7`.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

- Enable `--incompatible_enable_cc_toolchain_resolution`
- Create a platform with the following constraints:
```
@platforms//os:ios
@platforms//cpu:arm
```
or
```
@bazel_tools//platforms:ios
@bazel_tools//platforms:arm
```
- Build any `cc_binary` with it, watch it select the `armeabi-v7a` instead of `ios_armv7`.

### What operating system are you running Bazel on?

macos

### What's the output of `bazel info release`?
```
release 0.28.1
```

Tested with latest `master` too.

### Any other information, logs, or outputs that you want to share?

Looking at `osx_archs.bzl` I see:
```python
OSX_TOOLS_CONSTRAINTS = {
    "darwin_x86_64": ["@platforms//os:osx", "@platforms//cpu:x86_64"],
    "ios_i386": ["@platforms//os:ios", "@platforms//cpu:x86_32"],
    "ios_x86_64": ["@platforms//os:ios", "@platforms//cpu:x86_64"],
    "watchos_i386": ["@platforms//os:ios", "@platforms//cpu:x86_32"],
    "watchos_x86_64": ["@platforms//os:ios", "@platforms//cpu:x86_64"],
    "tvos_x86_64": ["@platforms//os:ios", "@platforms//cpu:x86_64"],
    "armeabi-v7a": ["@platforms//cpu:arm"],
    "ios_armv7": ["@platforms//os:ios", "@platforms//cpu:arm"],
    "ios_arm64": ["@platforms//os:ios", "@platforms//cpu:aarch64"],
    "ios_arm64e": ["@platforms//os:ios", "@platforms//cpu:aarch64"],
    "watchos_armv7k": ["@platforms//os:ios", "@platforms//cpu:arm"],
    "watchos_arm64_32": ["@platforms//os:ios", "@platforms//cpu:aarch64"],
    "tvos_arm64": ["@platforms//os:ios", "@platforms//cpu:aarch64"],
}
```

Which seems to indicate that the constraints are ok, but somehow it seems `@platforms//os:ios` is ignored ?

Note that the other platforms are ok, only `arm` fails.

**Comment by scentini** [comment] 2019-08-12 09:51
@katre can you please take a look / point to a person who can take a look?

**Comment by katre** [comment] 2019-08-12 15:20
Which `cc_toolchain` is the `ios_armv7` toolchain? I see that name is referenced in `tools/osx/crosstool/osx_archs.bzl`, but I am not sure where that is turned into an actual `cc_toolchain` target.

In order for toolchains to be used when `--incompatible_enable_cc_toolchain_resolution` is enabled, they need to be registered. By default, when cc autoconfigured toolchains are enabled, the toolchains found in `@local_config_cc//:all` are registered (see [cc_configure.bzl](https://source.bazel.build/bazel/+/master:tools/cpp/cc_configure.bzl;l=177?q=cc_configure.bzl)).

My theory is that either:
1. The toolchain is not being created. If you can tell me the package and target for the expected toolchain, I can verify this (or you can, via `bazel query`).
2. If the toolchain exists, it is not being registered. You can verify this by adding it at the command line with `--extra_toolchains=//package/path/to:ios_armv7`.

Finally, as to why the `armeabi-v7a` toolchain is being selected:
Your platform appears to be:
```
platform(
    name = "ios_armv7",
    constraint_values = [
        "@platforms//os:ios",
        "@platforms//cpu:arm",
    ],
)
```

The toolchain definition for `armeabi-v7a` is:
```
toolchain(
  name = "cc-toolchain-armeabi-v7a",
  toolchain_type = "@bazel_tools//tools/cpp:toolchain_type",
  exec_compatible_with = ["@platforms//cpu:x86_64", "@platforms//os:linux"],
  target_compatible_with = ["@platforms//cpu:arm", "@platforms//os:android"],
  toolchain = "@local_config_cc//:cc-compiler-armabi-v7a",
)
```

The constraint values `ios` and `android` are both `os` constraints, so I am surprised by this. Do you have a minimal reproduction I can clone and test with?

**Comment by scentini** [comment] 2019-08-12 16:19
@katre osx toolchains are defined [here](https://source.bazel.build/bazel/+/master:tools/osx/crosstool/BUILD.toolchains) and corresponding cc_toolchains [here](https://source.bazel.build/bazel/+/master:tools/osx/crosstool/BUILD.tpl;l=63).

We use these definitions when Xcode is installed (see logic [here](https://source.bazel.build/bazel/+/master:tools/cpp/cc_configure.bzl;l=71)), otherwise we fall back to the ones defined [here](https://source.bazel.build/bazel/+/master:tools/cpp/BUILD.toolchains.tpl) and [here](https://source.bazel.build/bazel/+/master:tools/cpp/BUILD.tpl).

**Comment by katre** [comment] 2019-08-12 17:10
Thanks for the pointers. Checking on my debug Mac machine, I see:
```
toolchain(
  name = "cc-toolchain-ios_armv7",
  toolchain_type = "@bazel_tools//tools/cpp:toolchain_type",
  exec_compatible_with = ["@platforms//os:osx", "@platforms//cpu:x86_64"],
  target_compatible_with = ["@platforms//os:ios", "@platforms//cpu:arm"],
  toolchain = "@local_config_cc//:cc-compiler-ios_armv7",
)
```

This looks like it should match, and also should be registered. With a full reproduction, I can debug the toolchain resolution and see what is happening.

**Comment by steeve** [comment] 2019-08-14 11:10
@katre do you need a sample repo ?

**Comment by katre** [comment] 2019-08-14 14:03
@steeve Yes, if you can that would be very helpful.

**Comment by steeve** [comment] 2019-08-15 22:15
@katre here you go: https://github.com/steeve/bazel_issue_9078

**Comment by steeve** [comment] 2019-08-16 10:28
For the record, this is blocking us from upgrading to 0.28 (at least), because we ship a framework with `arm` inside. That said, a per workspace workaround would be fine to us.

**Comment by steeve** [comment] 2019-08-16 10:31
Here is the output of the sample project:
```
bazel build //:test --toolchain_resolution_debug
INFO: Build option --platforms has changed, discarding analysis cache.
INFO: ToolchainResolution: Looking for toolchain of type @bazel_tools//tools/cpp:toolchain_type...
INFO: ToolchainResolution:   Considering toolchain @local_config_cc//:cc-compiler-armeabi-v7a...
INFO: ToolchainResolution:   Considering toolchain @local_config_cc//:cc-compiler-darwin_x86_64...
INFO: ToolchainResolution:     Toolchain constraint @platforms//os:os has value @platforms//os:osx, which does not match value @platforms//os:ios from the target platform //:ios_arm
INFO: ToolchainResolution:     Toolchain constraint @platforms//cpu:cpu has value @platforms//cpu:x86_64, which does not match value @platforms//cpu:arm from the target platform //:ios_arm
INFO: ToolchainResolution:   Rejected toolchain @local_config_cc//:cc-compiler-darwin_x86_64, because of target platform mismatch
INFO: ToolchainResolution:   Considering toolchain @local_config_cc//:cc-compiler-ios_arm64...
INFO: ToolchainResolution:     Toolchain constraint @platforms//cpu:cpu has value @platforms//cpu:aarch64, which does not match value @platforms//cpu:arm from the target platform //:ios_arm
INFO: ToolchainResolution:   Rejected toolchain @local_config_cc//:cc-compiler-ios_arm64, because of target platform mismatch
INFO: ToolchainResolution:   Considering toolchain @local_config_cc//:cc-compiler-ios_arm64e...
INFO: ToolchainResolution:     Toolchain constraint @platforms//cpu:cpu has value @platforms//cpu:aarch64, which does not match value @platforms//cpu:arm from the target platform //:ios_arm
INFO: ToolchainResolution:   Rejected toolchain @local_config_cc//:cc-compiler-ios_arm64e, because of target platform mismatch
INFO: ToolchainResolution:   Considering toolchain @local_config_cc//:cc-compiler-ios_armv7...
INFO: ToolchainResolution:   Considering toolchain @local_config_cc//:cc-compiler-ios_i386...
INFO: ToolchainResolution:     Toolchain constraint @platforms//cpu:cpu has value @platforms//cpu:x86_32, which does not match value @platforms//cpu:arm from the target platform //:ios_arm
INFO: ToolchainResolution:   Rejected toolchain @local_config_cc//:cc-compiler-ios_i386, because of target platform mismatch
INFO: ToolchainResolution:   Considering toolchain @local_config_cc//:cc-compiler-ios_x86_64...
INFO: ToolchainResolution:     Toolchain constraint @platforms//cpu:cpu has value @platforms//cpu:x86_64, which does not match value @platforms//cpu:arm from the target platform //:ios_arm
INFO: ToolchainResolution:   Rejected toolchain @local_config_cc//:cc-compiler-ios_x86_64, because of target platform mismatch
INFO: ToolchainResolution:   Considering toolchain @local_config_cc//:cc-compiler-tvos_arm64...
INFO: ToolchainResolution:     Toolchain constraint @platforms//cpu:cpu has value @platforms//cpu:aarch64, which does not match value @platforms//cpu:arm from the target platform //:ios_arm
INFO: ToolchainResolution:   Rejected toolchain @local_config_cc//:cc-compiler-tvos_arm64, because of target platform mismatch
INFO: ToolchainResolution:   Considering toolchain @local_config_cc//:cc-compiler-tvos_x86_64...
INFO: ToolchainResolution:     Toolchain constraint @platforms//cpu:cpu has value @platforms//cpu:x86_64, which does not match value @platforms//cpu:arm from the target platform //:ios_arm
INFO: ToolchainResolution:   Rejected toolchain @local_config_cc//:cc-compiler-tvos_x86_64, because of target platform mismatch
INFO: ToolchainResolution:   Considering toolchain @local_config_cc//:cc-compiler-watchos_arm64_32...
INFO: ToolchainResolution:     Toolchain constraint @platforms//cpu:cpu has value @platforms//cpu:aarch64, which does not match value @platforms//cpu:arm from the target platform //:ios_arm
INFO: ToolchainResolution:   Rejected toolchain @local_config_cc//:cc-compiler-watchos_arm64_32, because of target platform mismatch
INFO: ToolchainResolution:   Considering toolchain @local_config_cc//:cc-compiler-watchos_armv7k...
INFO: ToolchainResolution:   Considering toolchain @local_config_cc//:cc-compiler-watchos_i386...
INFO: ToolchainResolution:     Toolchain constraint @platforms//cpu:cpu has value @platforms//cpu:x86_32, which does not match value @platforms//cpu:arm from the target platform //:ios_arm
INFO: ToolchainResolution:   Rejected toolchain @local_config_cc//:cc-compiler-watchos_i386, because of target platform mismatch
INFO: ToolchainResolution:   Considering toolchain @local_config_cc//:cc-compiler-watchos_x86_64...
INFO: ToolchainResolution:     Toolchain constraint @platforms//cpu:cpu has value @platforms//cpu:x86_64, which does not match value @platforms//cpu:arm from the target platform //:ios_arm
INFO: ToolchainResolution:   Rejected toolchain @local_config_cc//:cc-compiler-watchos_x86_64, because of target platform mismatch
INFO: ToolchainResolution:   For toolchain type @bazel_tools//tools/cpp:toolchain_type, possible execution platforms and toolchains: {@bazel_tools//platforms:host_platform -> @local_config_cc//:cc-compiler-armeabi-v7a}
INFO: ToolchainResolution: Selected execution platform @bazel_tools//platforms:host_platform, type @bazel_tools//tools/cpp:toolchain_type -> toolchain @local_config_cc//:cc-compiler-armeabi-v7a
INFO: ToolchainResolution: Selected execution platform @bazel_tools//platforms:host_platform,
INFO: ToolchainResolution: Selected execution platform @bazel_tools//platforms:host_platform,
DEBUG: /Users/steeve/go/src/github.com/steeve/bazel_cc_toolchains/cpp.bzl:8:5: cpu = armeabi-v7a
DEBUG: /Users/steeve/go/src/github.com/steeve/bazel_cc_toolchains/cpp.bzl:9:5: target_gnu_system_name = armeabi-v7a
DEBUG: /Users/steeve/go/src/github.com/steeve/bazel_cc_toolchains/cpp.bzl:10:5:
DEBUG: /Users/steeve/go/src/github.com/steeve/bazel_cc_toolchains/cpp.bzl:11:5: struct(all_files = depset([<source file external/local_config_cc/cc_wrapper.sh>, <source file external/local_config_cc/libtool>, <source file external/local_config_cc/make_hashed_objlist.py>, <source file external/local_config_cc/wrapped_ar>, <source file external/local_config_cc/wrapped_clang>, <source file external/local_config_cc/wrapped_clang_pp>, <source file external/local_config_cc/xcrunwrapper.sh>]), ar_executable = "/bin/false", built_in_include_directories = ["/usr/local/include", "/Applications/Xcode-10.2.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1", "/Applications/Xcode-10.2.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/10.0.1/include", "/Applications/Xcode-10.2.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include", "/Applications/Xcode-10.2.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include", "/Applications/Xcode-10.2.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks", "/Applications/Xcode.app/Contents/Developer", "/Applications/Xcode-10.2.1.app/Contents/Developer", "/Applications"], compiler = "compiler", compiler_executable = "/bin/false", cpu = "armeabi-v7a", ld_executable = "/bin/false", libc = "armeabi-v7a", nm_executable = "/bin/false", objcopy_executable = "/bin/false", objdump_executable = "/bin/false", preprocessor_executable = "/bin/false", strip_executable = "/bin/false", sysroot = None, target_gnu_system_name = "armeabi-v7a")
INFO: Analyzed target //:test (0 packages loaded, 121 targets configured).
INFO: Found 1 target...
Target //:test up-to-date (nothing to build)
INFO: Elapsed time: 0.169s, Critical Path: 0.01s
INFO: 0 processes.
INFO: Build completed successfully, 1 total action
```

The weird thing is that it doesn't matter if I enable or disable the `:ios` constraint for arm, `armeabi-v7a` is always selected. If I do this on the `ios_arm64` platform, it fails (as it should).

**Comment by katre** [comment] 2019-08-16 16:03
Thanks for the repo, investigating now.

**Comment by katre** [comment] 2019-08-16 16:40
Okay, found the problem, it's in [osx_archs.bzl](https://source.bazel.build/bazel/+/master:tools/osx/crosstool/osx_archs.bzl;l=27):

1. This defines architectures for `armeabi-v7a`, `ios_armv7`, and many others.
2. The order is defined by `OSX_TOOL_ARCHS`, which means that `armeabi-v7a` has higher precedence than `ios_armv7`.
  1. Also, `armeabi-v7a` doesn't define an os constraint, which is weird but wouldn't help, because of the next point.
3. Several of the devices defined have the same constraints, and therefore are considered as equivalent to the toolchain resolution system.
  1. I assume they are actually different toolchains once defined, but they look the same to toolchain resolution.
  2. Specifically for the constraints you are interested in, `ios_v7a` and `watchos_armv7k` match, and `armeabi_v7a` probably should, since I think it should have an os constraint on ios.

So I am re-assigning this to the apple tools team to decide what should happen next to distinguish between these different toolchains.

**Comment by katre** [comment] 2019-08-16 16:40
Also pinging @sergiocampama directly.

**Comment by steeve** [comment] 2019-08-16 18:08
@katre why is it ignoring the ios constraint? armeabi shouldn't be equivalent to a perfect match, should it?

**Comment by katre** [comment] 2019-08-16 18:12
Toolchains are matched if every constraint present in the toolchain is present and the same value in the platform. This allows platforms to define new constraints that the toolchains are not aware of. For example, rules_go could define a new `:use_cgo` constraint, and users could add it to their platforms. This shouldn't stop apple toolchains from being used, because apple toolchains aren't aware of the constraint.

In this case, the `armeabi-v7a` toolchain should be setting the `:ios` constraint, because it will only produce code for an ios device. It doesn't solve your problem, however, which is that you need a way to specify that you want ios-v7a, not armeabi-v7a. This needs a change in the toolchain definitions: possibly removing the armeabi toolchain, or addition additional constraints sufficient to distinguish the target devices.

**Comment by steeve** [comment] 2019-08-16 21:05
Super clear, thank you!

That said, that seems a pretty dangerous thing, if I define a toolchain that matches on "Linux", then it can steal all matches to it, even if another has other matches.

I would wager that a toolchain matching all constraints should win over another having a partial match because of missing ones.

I'm trying to find a way to override this in my current workspace. I'm using toolchains from a platform transition in rules_go and I find toolchains resolution to be very elegant so far...

**Comment by katre** [comment] 2019-08-16 21:12
We've discussed changing toolchain resolution from "first match" to "best match", where "best" means "most constraint values match". Unfortunately in discussions with users this isn't always easy to follow, and toolchain resolution is already complicated enough. We're definitely open to revisiting the idea, however.

**Comment by jmmv** [comment] 2020-05-13 19:40
Given that this issue fell through the cracks and that there have been no further updates... I'm assuming that you have a local patch to workaround it? Could you share how it looks like?

**Comment by steeve** [comment] 2020-05-13 22:16
Indeed, we just stopped shipping arm32 binaries :)

**Comment by jmmv** [comment] 2020-05-15 14:18
Cool... then I'll leave it up to the configuration folks to decide how toolchain resolution ought to best work here (if it needs any changes).

**Comment by katre** [comment] 2020-05-20 19:23
I've opened #11454 to track the desire for a different toolchain resolution model, so I'm going to close this issue in favor of that. Note that we aren't prioritizing any work related to that: the issue is just so we don't lose track of the request.

**Closed by katre** 2020-05-20 19:23 UTC
Labels: team-Configurability, type: feature request, untriaged

**Comment by keith** [comment] 2022-04-29 00:14
This specific case is actually fixed by https://github.com/bazelbuild/bazel/pull/15248 because I added the android constraint
