### ISSUE TITLE
Bazel CI flaky error testConflictErrorAndUnfinishedAspectAnalysis_mergedAnalysisExecution
master



### ISSUE THREAD

**Issue by sgowroji** [bazelbuild/bazel#22009] opened 2024-04-16 06:11 UTC
CI: https://buildkite.com/organizations/bazel/analytics/suites/bazel-bazel/tests/018e5734-1d39-7ed5-ad3c-bb404bdadb34?branch=master

 Platform: 

 Logs: 
```
bazel test //src/test/java/com/google/devtools/build/lib/buildtool:OutputArtifactConflictTest --test_filter=testConflictErrorAndUnfinishedAspectAnalysis_mergedAnalysisExecution[skymeld=true,minimizeMemory=false,keepGoing=false]


expected to contain any of: [//x:y, //x/y:y, //x:fail_analysis]
but was                   : []
	at com.google.devtools.build.lib.buildtool.OutputArtifactConflictTest.testConflictErrorAndUnfinishedAspectAnalysis_mergedAnalysisExecution(OutputArtifactConflictTest.java:556)
``` 
 Culprit: 

 Steps:
  ``` 
  
 ``` 
 CC Greenteam @meteorcloudy

**Comment by gregestren** [comment] 2024-04-29 15:25
@katre for triage.

**Comment by katre** [comment] 2024-04-29 19:12
This was changed by @joeleba in 12aa54e527eafb8db74fdf9a5eae69db97b21fa5. This isn't configurability, re-assigning to local exec.

**Comment by joeleba** [comment] 2024-05-28 08:49
Interesting. I couldn't reproduce this internally even with `--runs_per_test=100`.

**Closed** 2024-05-28 09:28 UTC
Labels: type: bug, P2, team-Performance, flaky test
