### ISSUE TITLE
Builds without the Bytes fails to fetch tree artifact inputs

### ISSUE THREAD

**Issue by thii** [bazelbuild/bazel#15010] opened 2022-03-09 04:49 UTC
### Description of the problem / feature request:

We're trying to enable `--remote_download_minimal`/`--remote_download_toplevel` for our builds (which use disk cache and remote cache), and encountered this error:

```
ERROR: /path/to/BUILD:71:12: Bundling App failed: Exec failed due to IOException: 181 errors during bulk transfer
com.google.devtools.build.lib.vfs.FileAccessException: /path/to/bazel-output-base/execroot/__main__/bazel-out/applebin_ios-ios_x86_64-dbg-ST-1f63e7a63487/bin/App/App-intermediates/nibs/Bundle.bundle/ViewController/ViewController.nib (Permission denied)
(a lot other similar logs)
```

(a Bazel release that includes https://github.com/bazelbuild/bazel/commit/113eaca5862c48797654ae2a3acbb6e15d761485 is needed to see the underlying errors)

Upon some investigation, looks like the exception was thrown somewhere between `SpawnExecutionContext.prefetchInputsAndWait`.

https://github.com/bazelbuild/bazel/blob/88499f615bc03d1b6a3e4e38f2890a4e987a954d/src/main/java/com/google/devtools/build/lib/exec/SpawnRunner.java#L168

Another pattern I noticed is that inputs that were failed to fetch were all tree artifacts.

The build would succeed if I run the same `bazel build` again, but would fail again if I make some change and rebuild.

### Feature requests: what underlying problem are you trying to solve with this feature?

Using `--remote_download_minimal`/`--remote_download_toplevel` for local builds.

### What operating system are you running Bazel on?

macOS

### What's the output of `bazel info release`?

release 6.0.0-pre.20220105.5

**Comment by thii** [comment] 2022-03-09 13:03
cc @coeuvre

**Comment by coeuvre** [comment] 2022-03-10 11:01
> Upon some investigation, looks like the exception was thrown somewhere between SpawnExecutionContext.prefetchInputsAndWait.

If you have actions that are tagged locally, or dynamic execution is enabled, this is the place where Bazel fetch inputs from remote for local actions.

Would you please also share the details of the thrown IOException?

**Comment by thii** [comment] 2022-03-10 11:41
Bazel didn't crash, but this is the stack trace when I force-crashed it at https://github.com/bazelbuild/bazel/blob/88499f615bc03d1b6a3e4e38f2890a4e987a954d/src/main/java/com/google/devtools/build/lib/exec/SpawnRunner.java#L168

```
(18:09:22) FATAL: bazel crashed due to an internal error. Printing stack trace:
java.lang.RuntimeException: Unrecoverable error while evaluating node 'ActionLookupData{actionLookupKey=ConfiguredTargetKey{label=//foo:foo, config=BuildConfigurationKey[9239a84b20e29ac956755c7f9f46fed647b6f078a00cac71b14fa2f61570a932]}, actionIndex=202}' (requested by nodes 'ActionLookupData{actionLookupKey=ConfiguredTargetKey{label=//foo:foo, config=BuildConfigurationKey[9239a84b20e29ac956755c7f9f46fed647b6f078a00cac71b14fa2f61570a932]}, actionIndex=204}')
        at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:663)
        at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:382)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.RuntimeException: Force crash
        at com.google.devtools.build.lib.exec.SpawnRunner$SpawnExecutionContext.prefetchInputsAndWait(SpawnRunner.java:168)
        at com.google.devtools.build.lib.remote.RemoteSpawnCache.lookup(RemoteSpawnCache.java:158)
        at com.google.devtools.build.lib.exec.AbstractSpawnStrategy.exec(AbstractSpawnStrategy.java:144)
        at com.google.devtools.build.lib.exec.AbstractSpawnStrategy.exec(AbstractSpawnStrategy.java:111)
        at com.google.devtools.build.lib.actions.SpawnStrategy.beginExecution(SpawnStrategy.java:47)
        at com.google.devtools.build.lib.exec.SpawnStrategyResolver.beginExecution(SpawnStrategyResolver.java:68)
        at com.google.devtools.build.lib.analysis.actions.SpawnAction.beginExecution(SpawnAction.java:343)
        at com.google.devtools.build.lib.actions.Action.execute(Action.java:133)
        at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$5.execute(SkyframeActionExecutor.java:917)
        at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$ActionRunner.continueAction(SkyframeActionExecutor.java:1084)
        at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$ActionRunner.run(SkyframeActionExecutor.java:1042)
        at com.google.devtools.build.lib.skyframe.ActionExecutionState.runStateMachine(ActionExecutionState.java:152)
        at com.google.devtools.build.lib.skyframe.ActionExecutionState.getResultOrDependOnFuture(ActionExecutionState.java:91)
        at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.executeAction(SkyframeActionExecutor.java:490)
        at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.checkCacheAndExecuteIfNeeded(ActionExecutionFunction.java:822)
        at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.computeInternal(ActionExecutionFunction.java:315)
        at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.compute(ActionExecutionFunction.java:162)
        at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:589)
        ... 4 more
```

**Comment by coeuvre** [comment] 2022-03-10 12:21
Sorry for didn't make this clear, I was looking for the stack trace of the underlying IOExceptions wrapped inside the `BulkTransferException`.

I think you can get this by including their stack trace in `BulkTransferException#getMessage()`. Similar to https://github.com/bazelbuild/bazel/commit/113eaca5862c48797654ae2a3acbb6e15d761485, where you include messages of IOExceptions into BulkTransferException's message.

**Comment by thii** [comment] 2022-03-11 02:10
This is included in the issue description:

> com.google.devtools.build.lib.vfs.FileAccessException: /path/to/bazel-output-base/execroot/__main__/bazel-out/applebin_ios-ios_x86_64-dbg-ST-1f63e7a63487/bin/App/App-intermediates/nibs/Bundle.bundle/ViewController/ViewController.nib (Permission denied)

We got hundreds of similar message. When I checked `bazel-out`, those files didn't exist.

Is this what you're looking for?

**Comment by thii** [comment] 2022-03-11 03:28
```
com.google.devtools.build.lib.vfs.FileAccessException: /path/to/bazel-output-base/execroot/__main__/bazel-out/applebin_ios-ios_x86_64-dbg-ST-1f63e7a63487/bin/App/App-intermediates/xcassets/AppIcon60x60@2x.png (Permission denied)
        at com.google.devtools.build.lib.unix.NativePosixFiles.openWrite(Native Method)
        at com.google.devtools.build.lib.unix.UnixFileSystem.createFileOutputStream(UnixFileSystem.java:494)
        at com.google.devtools.build.lib.vfs.AbstractFileSystem.getOutputStream(AbstractFileSystem.java:174)
        at com.google.devtools.build.lib.vfs.AbstractFileSystem.getOutputStream(AbstractFileSystem.java:188)
        at com.google.devtools.build.lib.vfs.Path.getOutputStream(Path.java:408)
        at com.google.devtools.build.lib.vfs.Path.getOutputStream(Path.java:396)
        at com.google.devtools.build.lib.remote.common.LazyFileOutputStream.ensureOpen(LazyFileOutputStream.java:66)
        at com.google.devtools.build.lib.remote.common.LazyFileOutputStream.write(LazyFileOutputStream.java:42)
        at com.google.devtools.build.lib.remote.RemoteCache$ReportingOutputStream.write(RemoteCache.java:467)
        at com.google.common.io.ByteStreams.copy(ByteStreams.java:118)
        at com.google.devtools.build.lib.remote.disk.DiskCacheClient.download(DiskCacheClient.java:75)
        at com.google.devtools.build.lib.remote.disk.DiskCacheClient.downloadBlob(DiskCacheClient.java:89)
        at com.google.devtools.build.lib.remote.disk.DiskAndRemoteCacheClient.downloadBlob(DiskAndRemoteCacheClient.java:165)
        at com.google.devtools.build.lib.remote.RemoteCache.downloadFile(RemoteCache.java:336)
        at com.google.devtools.build.lib.remote.RemoteCache.downloadFile(RemoteCache.java:302)
        at com.google.devtools.build.lib.remote.RemoteActionInputFetcher.lambda$downloadFileAsync$5(RemoteActionInputFetcher.java:177)
        at com.google.devtools.build.lib.remote.util.RxFutures$OnceCompletableOnSubscribe.subscribe(RxFutures.java:79)
        at io.reactivex.rxjava3.internal.operators.completable.CompletableCreate.subscribeActual(CompletableCreate.java:40)
        at io.reactivex.rxjava3.core.Completable.subscribe(Completable.java:2859)
        at io.reactivex.rxjava3.internal.operators.completable.CompletablePeek.subscribeActual(CompletablePeek.java:51)
        at io.reactivex.rxjava3.core.Completable.subscribe(Completable.java:2859)
        at io.reactivex.rxjava3.internal.operators.completable.CompletablePeek.subscribeActual(CompletablePeek.java:51)
        at io.reactivex.rxjava3.core.Completable.subscribe(Completable.java:2859)
        at io.reactivex.rxjava3.internal.operators.completable.CompletablePeek.subscribeActual(CompletablePeek.java:51)
        at io.reactivex.rxjava3.core.Completable.subscribe(Completable.java:2859)
        at io.reactivex.rxjava3.internal.operators.completable.CompletableToSingle.subscribeActual(CompletableToSingle.java:37)
        at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4855)
        at com.google.devtools.build.lib.remote.util.AsyncTaskCache$Execution.subscribeActual(AsyncTaskCache.java:156)
        at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4855)
        at com.google.devtools.build.lib.remote.util.AsyncTaskCache.lambda$execute$1(AsyncTaskCache.java:291)
        at io.reactivex.rxjava3.internal.operators.single.SingleCreate.subscribeActual(SingleCreate.java:40)
        at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4855)
        at io.reactivex.rxjava3.internal.operators.completable.CompletableFromSingle.subscribeActual(CompletableFromSingle.java:29)
        at io.reactivex.rxjava3.core.Completable.subscribe(Completable.java:2859)
        at io.reactivex.rxjava3.internal.operators.completable.CompletableDefer.subscribeActual(CompletableDefer.java:43)
        at io.reactivex.rxjava3.core.Completable.subscribe(Completable.java:2859)
        at io.reactivex.rxjava3.internal.operators.completable.CompletableToSingle.subscribeActual(CompletableToSingle.java:37)
        at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4855)
        at io.reactivex.rxjava3.internal.operators.single.SingleResumeNext.subscribeActual(SingleResumeNext.java:39)
        at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4855)
        at io.reactivex.rxjava3.internal.operators.flowable.FlowableFlatMapSingle$FlatMapSingleSubscriber.onNext(FlowableFlatMapSingle.java:131)
        at io.reactivex.rxjava3.internal.operators.flowable.FlowableFromIterable$IteratorSubscription.fastPath(FlowableFromIterable.java:185)
        at io.reactivex.rxjava3.internal.operators.flowable.FlowableFromIterable$BaseRangeSubscription.request(FlowableFromIterable.java:129)
        at io.reactivex.rxjava3.internal.operators.flowable.FlowableFlatMapSingle$FlatMapSingleSubscriber.onSubscribe(FlowableFlatMapSingle.java:106)
        at io.reactivex.rxjava3.internal.operators.flowable.FlowableFromIterable.subscribe(FlowableFromIterable.java:69)
        at io.reactivex.rxjava3.internal.operators.flowable.FlowableFromIterable.subscribeActual(FlowableFromIterable.java:47)
        at io.reactivex.rxjava3.core.Flowable.subscribe(Flowable.java:15917)
        at io.reactivex.rxjava3.internal.operators.flowable.FlowableFlatMapSingle.subscribeActual(FlowableFlatMapSingle.java:53)
        at io.reactivex.rxjava3.core.Flowable.subscribe(Flowable.java:15917)
        at io.reactivex.rxjava3.internal.operators.flowable.FlowableCollectSingle.subscribeActual(FlowableCollectSingle.java:53)
        at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4855)
        at io.reactivex.rxjava3.internal.operators.single.SingleFlatMapCompletable.subscribeActual(SingleFlatMapCompletable.java:44)
        at io.reactivex.rxjava3.core.Completable.subscribe(Completable.java:2859)
        at io.reactivex.rxjava3.internal.operators.completable.CompletableResumeNext.subscribeActual(CompletableResumeNext.java:41)
        at io.reactivex.rxjava3.core.Completable.subscribe(Completable.java:2859)
        at io.reactivex.rxjava3.internal.operators.completable.CompletableUsing.subscribeActual(CompletableUsing.java:83)
        at io.reactivex.rxjava3.core.Completable.subscribe(Completable.java:2859)
        at com.google.devtools.build.lib.remote.util.RxFutures.toListenableFuture(RxFutures.java:195)
        at com.google.devtools.build.lib.remote.RemoteActionInputFetcher.prefetchFiles(RemoteActionInputFetcher.java:120)
        at com.google.devtools.build.lib.exec.AbstractSpawnStrategy$SpawnExecutionContextImpl.prefetchInputs(AbstractSpawnStrategy.java:245)
        at com.google.devtools.build.lib.exec.SpawnRunner$SpawnExecutionContext.prefetchInputsAndWait(SpawnRunner.java:162)
        at com.google.devtools.build.lib.remote.RemoteSpawnCache.lookup(RemoteSpawnCache.java:158)
        at com.google.devtools.build.lib.exec.AbstractSpawnStrategy.exec(AbstractSpawnStrategy.java:144)
        at com.google.devtools.build.lib.exec.AbstractSpawnStrategy.exec(AbstractSpawnStrategy.java:111)
        at com.google.devtools.build.lib.actions.SpawnStrategy.beginExecution(SpawnStrategy.java:47)
        at com.google.devtools.build.lib.exec.SpawnStrategyResolver.beginExecution(SpawnStrategyResolver.java:68)
        at com.google.devtools.build.lib.analysis.actions.SpawnAction.beginExecution(SpawnAction.java:343)
        at com.google.devtools.build.lib.actions.Action.execute(Action.java:133)
        at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$5.execute(SkyframeActionExecutor.java:917)
        at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$ActionRunner.continueAction(SkyframeActionExecutor.java:1084)
        at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$ActionRunner.run(SkyframeActionExecutor.java:1042)
        at com.google.devtools.build.lib.skyframe.ActionExecutionState.runStateMachine(ActionExecutionState.java:152)
        at com.google.devtools.build.lib.skyframe.ActionExecutionState.getResultOrDependOnFuture(ActionExecutionState.java:91)
        at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.executeAction(SkyframeActionExecutor.java:490)
        at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.checkCacheAndExecuteIfNeeded(ActionExecutionFunction.java:822)
        at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.computeInternal(ActionExecutionFunction.java:315)
        at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.compute(ActionExecutionFunction.java:162)
        at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:589)
        at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:382)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
```

**Comment by coeuvre** [comment] 2022-03-14 10:58
Thanks for the stack trace. It seems that Bazel cannot open the file for write due to permission issue when downloading inputs. I may need more time to locate the root cause. In the mean time, if you can provide a minimal repro, that would be very helpful!

**Comment by thii** [comment] 2022-03-15 01:28
Will try to reduce this to a minimal repro. 

Do you think this has anything to do with the empty directory tree that Bazel creates before executing local actions? I noticed that those don't have 'w' permission at all.

**Comment by matthewjh** [comment] 2022-03-23 17:05
I am suffering the same problem.

**Comment by eric-skydio** [comment] 2022-04-07 23:54
This also seems to affect `--remote_download_toplevel`, in particular if the "toplevel" output includes a tree artifact it will not be downloaded correctly, and instead an empty directory will be created. We are on `5.0.0`.

**Comment by BalestraPatrick** [comment] 2022-05-11 07:24
We're seeing the same issue on our CI for the same exact action. If [280ef69](https://github.com/bazelbuild/bazel/commit/280ef6915b0f507218a073974825d6aa7effddee) fixes it, do you think we can cherry-pick it to 5.2?

**Comment by coeuvre** [comment] 2022-05-11 08:08
Yes, I have another change to commit and will include them in 5.2.

**Comment by bjackr** [comment] 2022-06-06 03:13
We also encountered this issue, although rebuilding would fail with or without changes. Is this still slated to make it into 5.2?

**Comment by coeuvre** [comment] 2022-06-07 12:03
The fix is included in 5.2, closing.

**Comment by lukaciko** [comment] 2022-06-09 12:56
For anyone else that might be searching for it, the cherry picked fix for 5.2 is in 4d900ceea12919ad62012830a95e51f9ec1a48bb.

**Comment by keith** [comment] 2022-06-10 19:47
We're still seeing this with bazel @ HEAD 100% of the time when using toplevel downloads, the error for the files is slightly different:

```
java.io.FileNotFoundException: /private/var/tmp/_bazel_iosci/3f342d1abc53880540a7b4585792c0dd/execroot/lyftios/bazel-out/ios-arm64-min12.0-applebin_ios-ios_arm64-fastbuild-ST-f2da0a02a7d5/bin/Modules/x/x-intermediates/Base.lproj_storyboardc/x.storyboardc/xZw-Tz-rIp-view-uTW-fX-tP4.nib/objects-13.0+.nib (No such file or directory)
 ```

should I file a new issue or should we reopen this one? I can share the grpc log directly if you would like @coeuvre

**Comment by coeuvre** [comment] 2022-06-13 08:26
Please share grpc log as well as stack trace of above error.

**Comment by Bencodes** [comment] 2022-06-13 16:12
Can also confirm that we are still seeing this 100 percent of the time using `6.0.0-pre.20220526.1`. The error looks like this for us:

```
(16:02:46) ERROR: /root/.cache/bazel/_bazel_root/7b7747ec045ae606eb720a1222f56098/external/maven/BUILD:11105:11: Compiling Android resources for @maven//:com_jakewharton_rxbinding3_rxbinding_core failed: Exec failed due to IOException: /root/.cache/bazel/_bazel_root/7b7747ec045ae606eb720a1222f56098/execroot/instantandroid/bazel-out/android-arm64-v8a-dbg/bin/external/maven/_aar/unzipped/resources/com_jakewharton_rxbinding3_rxbinding_core/res/values/empty.xml (No such file or directory)
```

**Comment by coeuvre** [comment] 2022-06-23 12:54
I haven't had time to look into the log yet but https://github.com/bazelbuild/bazel/commit/ffc560d77329b8e84f45eed48266009799f7fa07 might be related.

**Comment by Bencodes** [comment] 2022-06-25 19:20
@coeuvre https://github.com/bazelbuild/bazel/commit/ffc560d77329b8e84f45eed48266009799f7fa07 seems to have fixed the issue for us.

**Comment by brentleyjones** [comment] 2022-06-26 00:09
Can we get that cherry-picked into 5.3?

**Comment by coeuvre** [comment] 2022-06-27 09:04
> @coeuvre [ffc560d](https://github.com/bazelbuild/bazel/commit/ffc560d77329b8e84f45eed48266009799f7fa07) seems to have fixed the issue for us.

Cool! Thanks for confirming.


> Can we get that cherry-picked into 5.3?

Main and 5.2 branch drifted too far apart, I am afraid we could introduce other bugs if we adapt this change on top of 5.2. But I can give it a try later.

**Comment by coeuvre** [comment] 2022-07-28 10:08
Unfortunately, there are 10+ direct dependences for this commit are missing in 5.3 and there are even more if we count transitive deps. I would say its to risky to cherry pick it into 5.3 and fix the merge conflicts. Closing.

**Closed by coeuvre** 2022-07-28 10:08 UTC
Labels: type: bug, P1, team-Remote-Exec
