### ISSUE TITLE
bazel fetches fail randomly on Kokoro + macOS

### ISSUE THREAD

**Issue by devjgm** [bazelbuild/bazel#11520] opened 2020-05-29 01:21 UTC
I got a bazel error that told me to file an issue here.

### Description of the problem / feature request:

Our CI build, running on macOS in Kokoro. The [build log is here](https://source.cloud.google.com/results/invocations/d77fd19f-24ea-46c0-a3c1-da34656f63be/targets/cloud-cpp%2Fgithub%2Fgoogle-cloud-cpp%2Fmaster%2Fmacos%2Fbazel/log).

Here's a snippet of the relevant bazel error:

```
ERROR: An error occurred during the fetch of repository 'local_config_cc':
   Traceback (most recent call last):
	File "/Volumes/BuildData/tmpfs/tmp/bazel/external/bazel_tools/tools/cpp/cc_configure.bzl", line 123
		configure_osx_toolchain(<2 more arguments>)
	File "/Volumes/BuildData/tmpfs/tmp/bazel/external/bazel_tools/tools/cpp/osx_cc_configure.bzl", line 138, in configure_osx_toolchain
		fail(<1 more arguments>)
wrapped_clang failed to generate. Please file an issue at https://github.com/bazelbuild/bazel/issues with the following:
return code 256, stderr: Timed out, stdout:
INFO: Call stack for the definition of repository 'remote_java_tools_darwin' which is a http_archive (rule definition at /Volumes/BuildData/tmpfs/tmp/bazel/external/bazel_tools/tools/build_defs/repo/http.bzl:292:16):
 - /Volumes/BuildData/tmpfs/tmp/bazel/external/bazel_tools/tools/build_defs/repo/utils.bzl:205:9
 - /DEFAULT.WORKSPACE.SUFFIX:280:1
```

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

No easy way to reproduce. We occasionally see errors like this on our Kokoro CI builds (usually? always? on macOS).

### What operating system are you running Bazel on?

macOS. not sure what version.

### What's the output of `bazel info release`?

Maybe this:
```
Build label: 2.0.0
Build target: bazel-out/darwin-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Thu Dec 19 12:33:30 2019 (1576758810)
Build timestamp: 1576758810
Build timestamp as int: 1576758810
```

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

Our repo is here: https://github.com/googleapis/google-cloud-cpp

The issue happens on any number of commits, but not consistently. It happens on our Kokoro CI runs.

###  Have you found anything relevant by searching the web?

No.

### Any other information, logs, or outputs that you want to share?

The full error log:
https://source.cloud.google.com/results/invocations/d77fd19f-24ea-46c0-a3c1-da34656f63be/targets/cloud-cpp%2Fgithub%2Fgoogle-cloud-cpp%2Fmaster%2Fmacos%2Fbazel/log

**Comment by jmmv** [comment] 2020-06-01 15:02
I think this is just being caused by the 30 second timeout we have in tools/cpp/osx_cc_configure.bzl to run wrapped_clang.

Based on the full logs, Bazel is taking a minute to start the server, which seems to indicate that the machine is struggling to keep up. If that's the case, running over the 30 seconds seems plausible...

I don't know much about the environment you are running the tests under. Is it possible for you to give that more resources as a test? Or could you build a custom Bazel binary with a higher timeout in https://cs.opensource.google/bazel/bazel/+/master:tools/cpp/osx_cc_configure.bzl;l=127;drc=ba2ccb151672216113c1a700b2ac8ce302bb6210 and use that?

**Comment by jmmv** [comment] 2020-06-25 01:53
Closing due to lack of information. Please reply if there is any chance you'd try what was asked in the last reply, because if that works, we'd fix this rather easily.

**Closed by jmmv** 2020-06-25 01:53 UTC
Labels: P2, more data needed, team-Apple, type: bug

**Comment by mr-salty** [comment] 2020-12-21 07:44
This has happened to us twice more, on 7/28 and 12/14.

looking at the most recent [log](https://source.cloud.google.com/results/invocations/01bb3e86-c6ef-4942-9fe5-c3b0d993f1c4/targets/cloud-cpp%2Fgithub%2Fgoogle-cloud-cpp%2Fmaster%2Fmacos%2Fbazel/log) the two timestamps around the first error differ by 30 *minutes*.  Is there some additional debugging we could enable? Although, the rate of 3 failures in ~7 months makes things kind of tough, but we're trying to at least understand if not eliminate any sources of flakiness.
