### ISSUE TITLE
config_setting should be able to express "OS = linux"

### ISSUE THREAD

**Issue by alandonovan** [bazelbuild/bazel#11107] opened 2020-04-09 13:46 UTC
As far as I can tell there is no way to write a config_setting that expresses the constraint "the target operating system is Linux". You can write one for for Windows, or for Darwin. You can write one for the pair of constraints "the operating system is Linux and the processor architecture is x86-64". But you can't do it for Linux. This means every place you want to write a linux-specific select case, you must enumerate all the possible CPU architectures on which Linux runs, which is confusing, verbose, inconsistent, and fragile.

**Comment by keith** [comment] 2020-04-09 14:59
We use

```
config_setting(
    name = "linux",
    constraint_values = [
        "@bazel_tools//platforms:linux",
    ],
)
```

For this but we only run on one distro ever so I'm not sure if it works for all cases

**Comment by juliexxia** [comment] 2020-04-17 13:24
Assigning to John for comment/triage

**Comment by katre** [comment] 2020-04-20 13:08
This can be done with constraints, but not the legacy "--cpu" based system. The resolution to this is to move as many things as we can to use platforms.

**Closed by katre** 2020-04-20 13:08 UTC
Labels: team-Configurability, untriaged

**Comment by alandonovan** [comment] 2020-04-20 13:22
John, excuse my ignorance of the toolchains mechanism, but does this mean it cannot be used to express a select case meaning OS=linux?

**Comment by katre** [comment] 2020-04-20 13:43
Toolchains and platforms absolutely can:
```
config_setting(
    name = "is_linux",
    constraint_values = ["@bazel_tools//platforms:linux"],
)
```

The problem is that this is only useful if the build is using a target platform (ie, the user sets `--platforms`, or the platform mapping converts a `--cpu` flag to a target platform, or in Bazel that the default target platform is correct).

However, since many rules are not using platforms currently (most notably, cc, android, and apple), we can't be sure the target platform actually expresses the user's intent, because those rules still rely on the legacy `--cpu` flag. As you note, there is no way to do a `config_setting` based on thr `--cpu` flag that expresses that the target OS is linux.

**Comment by alandonovan** [comment] 2020-04-20 14:47
I see; thanks for the explanation. When do you imagine the remaining rule sets might use platforms?

**Comment by katre** [comment] 2020-04-20 14:50
That's up to the rule owners. We plan to work with Android and Apple in the near future to enable migrations and make it attractive to them.
