### ISSUE TITLE
ArrayIndexOutOfBoundsException in CompactHashSet

### ISSUE THREAD

**Issue by siddharthab** [bazelbuild/bazel#5166] opened 2018-05-06 04:01 UTC
### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

With this WORKSPACE file:
```
http_archive(
    name = "io_bazel_rules_go",
    sha256 = "f70c35a8c779bb92f7521ecb5a1c6604e9c3edd431e50b6376d7497abc8ad3c1",
    url = "https://github.com/bazelbuild/rules_go/releases/download/0.11.0/rules_go-0.11.0.tar.gz",
)

load("@io_bazel_rules_go//go:def.bzl", "go_rules_dependencies", "go_register_toolchains")

go_rules_dependencies()

go_register_toolchains(go_version = "1.10")

load("@bazel_gazelle//:deps.bzl", "gazelle_dependencies")

gazelle_dependencies()
```
If I run,
```
bazel --bazelrc=/dev/null build @go_sdk//:files
```

I get an an exception almost consistently (sometimes there is no error).

```
java.lang.RuntimeException: Unrecoverable error while evaluating node '@go_sdk//:files com.google.devtools.build.lib.skyframe.BuildConfigurationValue$Key@99896fcf false (238769105)' (requested by nodes '@io_bazel_rules_go//:go_context_data com.google.devtools.build.lib.skyframe.BuildConfigurationValue$Key@99896fcf false (2026549981)')
        at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:424)
        at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:355)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(java.base@9-internal/ThreadPoolExecutor.java:1158)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(java.base@9-internal/ThreadPoolExecutor.java:632)
        at java.lang.Thread.run(java.base@9-internal/Thread.java:804)
Caused by: java.lang.ArrayIndexOutOfBoundsException: -396572904
        at com.google.devtools.build.lib.collect.compacthashset.CompactHashSet.add(CompactHashSet.java:302)
        at com.google.devtools.build.lib.collect.nestedset.NestedSetBuilder.addTransitive(NestedSetBuilder.java:121)
        at com.google.devtools.build.lib.skyframe.ConfiguredTargetFunction.resolveConfiguredTargetDependencies(ConfiguredTargetFunction.java:670)
        at com.google.devtools.build.lib.skyframe.ConfiguredTargetFunction.computeDependencies(ConfiguredTargetFunction.java:466)
        at com.google.devtools.build.lib.skyframe.ConfiguredTargetFunction.compute(ConfiguredTargetFunction.java:278)
        at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:347)
        ... 4 more
```

### What operating system are you running Bazel on?

Ubuntu

### What's the output of `bazel info release`?

release 0.13.0

###  Have you found anything relevant by searching the web?

No.

### Any other information, logs, or outputs that you want to share?

[hs_err_pid16220.log](https://github.com/bazelbuild/bazel/files/1977290/hs_err_pid16220.log)

**Comment by dslomov** [comment] 2018-05-14 11:38
This is Java 9 issue

**Comment by siddharthab** [comment] 2018-05-14 17:48
Is it possible to detect and warn users? That will be an acceptable interim resolution.

**Comment by philwo** [comment] 2018-05-15 11:54
@dslomov and others: Please don't assign issues to me while I'm on leave, unless it can wait 2 months without any action :) This seems like a potential blocker for our "embedded Java 9 launch", which is scheduled to happen very soon.

Reassigned to @cushon to have a look, other potentially good candidates for stuff that I usually work on would be @lberki or @buchgr.

**Comment by cushon** [comment] 2018-06-18 17:12
Is this still causing problems? I can't reproduce with Bazel built @ 7c49bd9c73385db84e678469aa7e6a5bb801c28a.

**Comment by siddharthab** [comment] 2018-06-19 03:48
Yes, bazel built at this commit does not have this issue with openjdk-9, whereas bazel 0.14.1 still crashes with the same error.

**Closed** 2018-08-21 22:26 UTC
Labels: category: misc > release / binary
