### ISSUE TITLE
Starlark type checking of select() behaves inconsistently

### ISSUE THREAD

**Issue by clintharrison** [bazelbuild/bazel#6643] opened 2018-11-09 15:37 UTC
### Description of the problem / feature request:

Selectors behave oddly in the type checker: they can be used in place of a string, label, or list, but they cannot be used as a string or label _in_ a list.

### Feature requests: what underlying problem are you trying to solve with this feature?

We currently use a `requirement()` function to map a short name to a more complex `py_library()` in an external workspace. (This comes from the standard `rules_python` Pip repository rules.)

```py
py_binary(
    name = "example",
    srcs = ["example.py"],
    deps = [
        "//:dep_a",
        requirement("absl-py")
    ],
)
```

Changing the underlying implementation of `requirement()` to support multiple platforms with a `select()` in place of the simple string it currently returns is not possible. All users of the `requirement()` function need to be changed, for example as:

```py
py_binary(
    name = "example",
    srcs = ["example.py"],
    deps = [
        "//:dep_a",
    ] + requirement("absl-py"),
)
```

This is a potentially large undertaking, touching many BUILD files to work around a limitation in type checking.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

```py
py_library(
    name = "lib",
    srcs = [],
)

py_binary(
    name = "example_a",
    srcs = ["example.py"],
    main = "example.py",
    deps = [
        ":lib",
    ],
)

py_binary(
    name = "example_b",
    srcs = ["example.py"],
    main = "example.py",
    deps = select({
        "//conditions:default": [":lib"]
    }),
)

# This is not possible:
# BUILD:26:1: //:example_c: expected value of type 'string' for element 0 of attribute
# 'deps' in 'py_binary' rule, but got select({"//conditions:default": ":lib"}) (select)
py_binary(
    name = "example_c",
    srcs = ["example.py"],
    main = "example.py",
    deps = [
        select({"//conditions:default": ":lib"}),
    ],
)
```

### What operating system are you running Bazel on?
macOS 10.12

### What's the output of `bazel info release`?
release 0.18.0

###  Have you found anything relevant by searching the web?
All examples of `select()` seem to assume this behavior, or only use it in a non-list context.

**Comment by gregestren** [comment] 2018-11-12 19:03
Duplicate of https://github.com/bazelbuild/bazel/issues/1623

Feel free to unduplicate if you disagree.

The short story is that `select`s today *always* bind to the attribute's type. So if the attribute is a label list the `select` **must** expand to a label list. https://github.com/bazelbuild/bazel/issues/1623
 talks about loosening that up some, I think to your satisfaction. There's already a prototype for it but it would take some more (still undone) work to make it production-ready.

**Closed** 2018-11-12 19:04 UTC
Labels: team-Configurability, type: bug, untriaged
