### ISSUE TITLE
tools/jdk/TestRunner_deploy.jar pollutes the classpath for java_test targets

### ISSUE THREAD

**Issue by jleyba** [bazelbuild/bazel#1634] opened 2016-08-11 17:57 UTC
tools/jdk/TestRunner_deploy.jar includes guava 19.0, which creates conflicts for any workspaces that attempt to use a different version of guava (i.e. 20.0-SNAPSHOT).

I've put together a sample project that can reproduce the problem with bazel 0.3.1:

https://github.com/jleyba/bazel-classpath

**Comment by hermione521** [comment] 2016-08-12 09:18
I think @iirina is working on this.

**Comment by ulfjack** [comment] 2016-08-16 11:01
Let's consider this a dupe of #1150.

**Closed by ulfjack** 2016-08-16 11:01 UTC
Labels: category: rules > java, P2, type: bug
