### ISSUE TITLE
load() in *.bzl failed with new_local_repository() packages

### ISSUE THREAD

**Issue by chin33z** [bazelbuild/bazel#721] opened 2015-12-17 03:31 UTC
I update to the latest HEAD of Bazel.
The load() in *.bzl works when the package dir is under %workspace%.
But it fails when the package is imported from new_local_repository().
A simple example could show the problem.

````
--------layout---------
workspace
    WORKSPACE
    BUILD
    ext.bzl
src (empty dir)
````

```
[WORKSPACE]
new_local_repository(
    name = "src",
    path = "/root/src",
    build_file = 'BUILD',
)
```

```
[BUILD]
load("/ext", "tar")
tar()
```

```
[ext.bzl]
load("/tools/build_defs/pkg/pkg", "pkg_tar")
def tar(hdrs = []):
    pkg_tar(
         name = 'hdrs',
         files = hdrs,
         extension = "tar.gz",
)
```

`$> bazel build //:hdrs`   will success
`$> bazel build @src//:hdrs`    will fail

Here is the error message:
**ERROR:** /root/.cache/bazel/_bazel_root/0ad3a1308b10afb9d4a36f7a97ce8ee8/external/src/BUILD:2:1: every rule of type pkg_tar implicitly depends upon the target '@src//tools/build_defs/pkg:build_tar',  but this target could not be found. If this is an integration test, maybe you forgot to add a mock for your new tool?
**ERROR:** Loading failed; build aborted.

Do I miss anything?

**Comment by kchodorow** [comment] 2015-12-17 19:07
You didn't miss anything, although this behavior is "working as intended" for some value of intended.  `//<some target>` is resolved local to the repository, so when pkg.bzl refers to //tools/build_defs/pkg:build_tar and you're loading pkg.bzl from a target in @src, it assumes that you want the //tools/build_defs/pkg:build_tar from under @src.

To some extent this will be taken care of by @jhfield's upcoming change to make load() take labels.  I'm not sure if there are any other improvements to make beyond that.

**Comment by chin33z** [comment] 2015-12-18 03:04
Thanks for the explanation.

So, I cannot use the pkg_tar() via Skylark module (*.bzl) with new_local_repository() so far?

**Comment by kchodorow** [comment] 2015-12-18 14:48
You can... if the new_local_repository contains its own tools/build_defs/pkg directory :-/

**Comment by AustinSchuh** [comment] 2015-12-23 07:23
Fingers crossed that it doesn't get reverted, but 1ea7fc370f0605be2185868f9371f6e04c26a502 just landed in the repo, so it looks like label based loads are supported.

**Closed** 2016-01-05 20:14 UTC
Labels: bug, external repositories, P2

**Comment by kersson** [comment] 2017-04-10 19:18
How do label-based loads solve this issue? Would love to load extensions for `new_local_repository`.

**Comment by mthiffau** [comment] 2023-06-23 19:39
To anyone looking for the answer to this question after all this time:

In the repo which is using new_local_repository(), ensure the WORKSPACE file includes something like:
workspace(name = "myproject")

And then in the BUILD file specified by the build_file parameter passed to new_local_repository, load using:
load("@myproject//path/to:rule.bzl", "rule_i_want")
