### ISSUE TITLE
Bazel 0.3.0 now fails to compile on Windows

### ISSUE THREAD

**Issue by rokstrnisa** [bazelbuild/bazel#1691] opened 2016-08-26 09:19 UTC
Due to #1589, I cannot use Bazel 0.3.1 on Windows, so the only stable alternative is to use 0.3.0. This used to work fine, but now somehow fails to compile.

    $ git checkout 0.3.0
    HEAD is now at da8331d... Upfated CHANGELOG with source cherry-picks
    $ ./compile.sh
    INFO: You can skip this first step by providing a path to the bazel binary as second argument:
    INFO:    ./compile.sh compile /path/to/bazel
    🍃  Building Bazel from scratch..C:/Program Files/Java/jdk1.8.0_91/bin/javac -classpath third_party/aether/aether-api-1.0.0.v20140518.jar;third_party/aether/aether-connector-basic-1.0.0.v20140518.jar;third_party/aether/aether-impl-1.0.0.v20140518.jar;third_party/aether/aether-spi-1.0.0.v20140518.jar;third_party/aether/aether-transport-classpath-1.0.0.v20140518.jar;third_party/aether/aether-transport-file-1.0.0.v20140518.jar;third_party/aether/aether-transport-http-1.0.0.v20140518.jar;third_party/aether/aether-transport-wagon-1.0.0.v20140518.jar;third_party/aether/aether-util-1.0.0.v20140518.jar;third_party/android_common/com.android.jack_api_0.9.0.jar;third_party/android_common/com.android.jill_api_0.9.0.jar;third_party/android_common/com.android.tools.build_builder-model_0.13.3.jar;third_party/android_common/com.android.tools.build_builder-model_2.0.0.jar;third_party/android_common/com.android.tools.build_builder-test-api_2.0.0.jar;third_party/android_common/com.android.tools.build_builder_0.13.3.jar;third_party/android_common/com.android.tools.build_builder_2.0.0.jar;third_party/android_common/com.android.tools.build_manifest-merger_23.1.3.jar;third_party/android_common/com.android.tools.build_manifest-merger_25.0.0.jar;third_party/android_common/com.android.tools.layoutlib_layoutlib_23.1.3.jar;third_party/android_common/com.android.tools.layoutlib_layoutlib_25.0.0.jar;third_party/android_common/com.android.tools_common_23.1.3.jar;third_party/android_common/com.android.tools_common_25.0.0.jar;third_party/android_common/com.android.tools_ddmlib_25.0.0.jar;third_party/android_common/com.android.tools_dvlib_25.0.0.jar;third_party/android_common/com.android.tools_repository_25.0.0.jar;third_party/android_common/com.android.tools_sdk-common_23.1.3.jar;third_party/android_common/com.android.tools_sdk-common_25.0.0.jar;third_party/android_common/com.android.tools_sdklib_23.1.3.jar;third_party/android_common/com.android.tools_sdklib_25.0.0.jar;third_party/android_common/com.android_annotations_25.0.0.jar;third_party/apache_commons_codec/commons-codec-1.9.jar;third_party/apache_commons_collections/commons-collections-3.2.2.jar;third_party/apache_commons_compress/apache-commons-compress-1.9.jar;third_party/apache_commons_lang/commons-lang-2.6.jar;third_party/apache_commons_logging/commons-logging-1.1.1.jar;third_party/apache_commons_pool2/commons-pool2-2.3.jar;third_party/apache_httpclient/httpclient-4.2.5.jar;third_party/apache_httpcore/httpcore-4.2.4.jar;third_party/apache_velocity/velocity-1.7.jar;third_party/asm/asm-5.0.3.jar;third_party/asm/asm-5.0.4.jar;third_party/asm/asm-commons-5.0.4.jar;third_party/asm/asm-util-5.0.4.jar;third_party/auto/auto-common-0.3.jar;third_party/auto/auto-service-1.0-rc2.jar;third_party/auto/auto-value-1.2.jar;third_party/bytebuddy/byte-buddy-dep-0.7-rc6.jar;third_party/checker_framework_dataflow/dataflow-1.8.10.jar;third_party/dagger/dagger-2.4.jar;third_party/dagger/dagger-compiler-2.4.jar;third_party/dagger/dagger-producers-2.4.jar;third_party/error_prone/error_prone_annotation-2.0.9-20160129.jar;third_party/error_prone/error_prone_annotations-2.0.9-20160129.jar;third_party/error_prone/error_prone_core-2.0.9-20160129.jar;third_party/grpc/grpc-all-0.13.2.jar;third_party/gson/gson-2.2.4.jar;third_party/guava/guava-19.0.jar;third_party/guava/guava-testlib.jar;third_party/guice/guice-4.0-no_aop.jar;third_party/guice/guice-multibindings-4.0.jar;third_party/hamcrest/hamcrest-core-1.3.jar;third_party/hazelcast/hazelcast-3.5.4.jar;third_party/hazelcast/hazelcast-client-3.5.4.jar;third_party/ijar/test/libwrongcentraldir.jar;third_party/java/dd_plist/libdd_plist.jar;third_party/java/jarjar/jarjar-1.4.jar;third_party/jcip_annotations/jcip-annotations-1.0-1.jar;third_party/jgit/org.eclipse.jgit-4.0.1.201506240215-r.jar;third_party/jimfs/jimfs-1.1-rc1.jar;third_party/joda_time/joda-time-2.3.jar;third_party/jsch/jsch-0.1.51.jar;third_party/jsr305/jsr-305.jar;third_party/jsr330_inject/javax.inject.jar;third_party/junit/junit-4.11.jar;third_party/maven/maven-builder-support-3.3.3.jar;third_party/maven/maven-settings-3.3.3.jar;third_party/maven/maven-settings-builder-3.3.3.jar;third_party/maven_model/maven-aether-provider-3.2.3.jar;third_party/maven_model/maven-model-3.2.3.jar;third_party/maven_model/maven-model-builder-3.2.3.jar;third_party/maven_model/maven-repository-metadata-3.2.3.jar;third_party/mockito/mockito-all-1.10.19.jar;third_party/netty/netty-all-4.1.0.CR6.jar;third_party/pcollections/pcollections-2.1.2.jar;third_party/plexus_component_annotations/plexus-component-annotations-1.6.jar;third_party/plexus_interpolation/plexus-interpolation-1.22.jar;third_party/plexus_utils/plexus-utils-3.0.21.jar;third_party/protobuf/protobuf-java-3.0.0-beta-1.jar;third_party/slf4j/slf4j-api-1.7.7.jar;third_party/slf4j/slf4j-jdk14-1.7.7.jar;third_party/tomcat_annotations_api/tomcat-annotations-api-8.0.5.jar;third_party/truth/truth-0.28.jar;third_party/xz/xz-1.5.jar;:/tmp/bazel.v0ja61bM -sourcepath src/java_tools/singlejar/java/com/google/devtools/build/zip;src/main/java;src/tools/xcode-common/java/com/google/devtools/build/xcode/common;src/tools/xcode-common/java/com/google/devtools/build/xcode/util;/tmp/bazel.v0ja61bM/src -d /tmp/bazel.v0ja61bM/classes -source 1.8 -target 1.8 -encoding UTF-8 @/tmp/bazel.gYkkFoh1/param
    javac: file not found: \tmp\bazel.v0ja61bM\src\com\google\devtools\build\buildjar\proto\JavaCompilation.java
    Usage: javac <options> <source files>
    use -help for a list of possible options

    Compiling Bazel Java code...

**Comment by petemounce** [comment] 2016-08-26 10:08
That error has happened to me as well. I was able to compile `0.3.0` _after_ compiling `0.3.1` or HEAD (but I don't know what sha HEAD was at the time, sorry).

**Comment by rokstrnisa** [comment] 2016-08-26 11:51
@petemounce: The workaround of building 0.3.0 using HEAD (0b701b2) with `./compile.sh compile bazel-0b701b2.exe` worked for me. Thanks.

**Comment by laszlocsomor** [comment] 2016-08-29 09:16
Duplicate of #1444.

Workaround:
```
$ export TMPDIR=c:/tempdir
```

Fixed by https://github.com/bazelbuild/bazel/commit/19fd76f4376fab4f11e11099aeaf34d36e1d44df, fixed in 0.3.1.

**Comment by laszlocsomor** [comment] 2016-08-29 09:17
Reopening because we need to fix this in 0.3.0 too and update the git tag.

**Comment by laszlocsomor** [comment] 2016-08-29 09:32
@rokstrnisa : I believe the reason you could previously build 0.3.0 but not anymore is because `$TMPDIR` is no longer set in your env, because https://www.bazel.io/docs/windows.html no longer tells you to, because with 0.3.1 you no longer have to.

Sorry about the confusion. We're working on having historical docs on bazel.io along with the latest docs.

**Closed by laszlocsomor** 2016-08-29 09:32 UTC
Labels: category: misc > bootstrap / installation, category: multi-platform > windows, Duplicate, P2, type: bug, Under investigation
