### ISSUE TITLE
Unrecoverable error while evaluating node 'REPOSITORY_DIRECTORY:@some_repo'

### ISSUE THREAD

**Issue by vrv** [bazelbuild/bazel#2535] opened 2017-02-15 22:51 UTC
Please provide the following information. The more we know about your system and use case, the more easily and likely we can help.

### Description of the problem / feature request / question:

Bazel occasionally fails with the following output:

```
13:21:32 java.lang.RuntimeException: Unrecoverable error while evaluating node 'REPOSITORY_DIRECTORY:@org_polymer_paper_behaviors' (requested by nodes 'REPOSITORY:@org_polymer_paper_behaviors')
13:21:32 	at com.google.devtools.build.skyframe.ParallelEvaluator$Evaluate.run(ParallelEvaluator.java:429)
13:21:32 	at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:501)
13:21:32 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
13:21:32 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
13:21:32 	at java.lang.Thread.run(Thread.java:745)
13:21:32 Caused by: java.lang.IllegalArgumentException: Invalid EvalException:
``` 

I suspect this is due to some kind of timeout or lack of ability to contact some target -- if that's the case, I think we might be able to provide a mirror, but it would be good to know to confirm that network availability of an external dependency is the problem this error message is referring to.

### If possible, provide a minimal example to reproduce the problem:
It seems to happen only very occasionally, so I can't really provide a reproducible case easily, but it causes our Jenkins bazel CI tests to fail.  If you need reproducibility to debug this particular problem, feel free to close, but hopefully this is good enough to know what's happening.

### Environment info
* Operating System:
Docker / Ubuntu 16.04

* Bazel version (output of `bazel info release`):
I believe our CI machines are on 0.4.2 right now 

* If `bazel info release` returns "development version" or "(@non-git)", please tell us what source tree you compiled Bazel from; git commit hash is appreciated (`git rev-parse HEAD`):

### Anything else, information or logs or outputs that would be helpful?
(If they are large, please upload as attachment or provide link).

http://ci.tensorflow.org/job/tensorflow-cl-cpu-python3-pip/5929/console

**Comment by cpietsch** [comment] 2017-03-18 10:15
having the same error when trying to compile guetzli with ``bazel build -c opt //:guetzli``

**Comment by dslomov** [comment] 2018-01-11 13:19
I'll have to close this since it is really not actionable :(
In particular, the log is cut after `13:21:32 Caused by: java.lang.IllegalArgumentException: Invalid EvalException:` and without specifics on what the exception was I have no clue what went astray

**Closed by dslomov** 2018-01-11 13:19 UTC
Labels: category: extensibility > external repositories, type: bug
