### ISSUE TITLE
##An illegal reflective access operation has occurred ##

### ISSUE THREAD

**Issue by leiminray** [bazelbuild/bazel#6331] opened 2018-10-07 15:14 UTC
After install Bazel, I run " bazel version ", encounter below WARNING, is any abnormal ? and how to fix? thks

leimins-MBP-2:~ leimin$ bazel version
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.protobuf.UnsafeUtil (file:/private/var/tmp/_bazel_leimin/install/ab3f5a92193ce7d9503f32b8ce350934/_embedded_binaries/A-server.jar) to field java.lang.String.value
WARNING: Please consider reporting this to the maintainers of com.google.protobuf.UnsafeUtil
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
WARNING: --batch mode is deprecated. Please instead explicitly shut down your Bazel server using the command "bazel shutdown".
Build label: 0.17.2
Build target: bazel-out/darwin-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Fri Sep 21 11:19:02 2018 (1537528742)
Build timestamp: 1537528742
Build timestamp as int: 1537528742

**Comment by cushon** [comment] 2018-10-07 19:29
This is a duplicate of #6151.

**Closed by cushon** 2018-10-07 19:29 UTC
