### ISSUE TITLE
Bazel CI failure: //src/test/java/com/google/devtools/build/lib/skylark:SkylarkTests failing on ubuntu_16.04-x86_64

### ISSUE THREAD

**Issue by meteorcloudy** [bazelbuild/bazel#3686] opened 2017-09-05 08:40 UTC
http://ci.bazel.io/blue/rest/organizations/jenkins/pipelines/bazel-tests/runs/1008/nodes/27/steps/348/log/?start=0
```
INFO: Encountered an external path [/]/[bazel_tools_workspace/tools/jdk/jdk]
Sep 05, 2017 8:07:01 AM com.google.devtools.build.lib.skyframe.ExternalFilesHelper maybeHandleExternalFile
INFO: Encountered an external path [/]/[bazel_tools_workspace/tools/cpp/CROSSTOOL]
Sep 05, 2017 8:07:01 AM com.google.devtools.build.lib.skyframe.FilesystemValueChecker$4 accept
INFO: Spent 132 ms checking 37 filesystem nodes (166 scanned)
Sep 05, 2017 8:07:01 AM com.google.devtools.build.lib.skyframe.SkyframeBuildView setConfigurations
INFO: Discarding analysis cache: configurations have changed.
Sep 05, 2017 8:07:01 AM com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate run
WARNING: Aborting evaluation due to com.google.devtools.build.lib.skyframe.ConfiguredTargetFunction$ConfiguredTargetFunctionException: com.google.devtools.build.lib.skyframe.ConfiguredTargetFunction$ConfiguredValueCreationException: Analysis of target '//test:main' failed; build aborted while evaluating CONFIGURED_TARGET://test:main 303baa66308f0fbdb538bc1aaa87cdf9 (1443262715 2006889251)
Sep 05, 2017 8:07:01 AM com.google.devtools.build.lib.concurrent.AbstractQueueVisitor maybeSaveUnhandledThrowable
WARNING: Found critical error in queue visitor
java.lang.AssertionError: ERROR /workspace/test/BUILD:3:1: in main_rule rule //test:main: 
Traceback (most recent call last):
	File "/workspace/test/BUILD", line 3
		main_rule(name = 'main')
	File "/workspace/test/rules.bzl", line 4, in _main_impl
		dep.dep_ctx.attr
cannot access field or method 'attr' of rule context for '//test:dep' outside of its own rule implementation function
	at org.junit.Assert.fail(Assert.java:88)
	at com.google.devtools.build.lib.testutil.FoundationTestCase$1.handle(FoundationTestCase.java:58)
	at com.google.devtools.build.lib.events.Reporter.handle(Reporter.java:110)
	at com.google.devtools.build.skyframe.ParallelEvaluatorContext$NestedSetEventReceiver.accept(ParallelEvaluatorContext.java:236)
	at com.google.devtools.build.skyframe.ParallelEvaluatorContext$NestedSetEventReceiver.accept(ParallelEvaluatorContext.java:224)
	at com.google.devtools.build.lib.collect.nestedset.NestedSetVisitor.visitRaw(NestedSetVisitor.java:76)
	at com.google.devtools.build.lib.collect.nestedset.NestedSetVisitor.visit(NestedSetVisitor.java:64)
	at com.google.devtools.build.skyframe.SkyFunctionEnvironment.commit(SkyFunctionEnvironment.java:593)
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:399)
	at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:352)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

This test is timeout on ubuntu_16.04-x86_64 but passing on linux-x86_64,

**Comment by meteorcloudy** [comment] 2017-09-05 08:40
//cc @vladmos, since looks like you wrote the test.

**Comment by vladmos** [comment] 2017-09-05 09:28
That's strange, this test was written in March and was last updated two months ago. Maybe SkylarkTests in general became too large so that it timeouts now, can we increase the timeout for it if the problem persists?

**Comment by meteorcloudy** [comment] 2017-09-05 09:37
But, the same test only takes about 90s on linux-x86_64.
And there is an `AssertionError` in the output log, do you have any idea what caused it, can you reproduce this?

**Comment by vladmos** [comment] 2017-09-22 11:23
Duplicate of #3774.

**Closed by vladmos** 2017-09-22 11:23 UTC
Labels: breakage, category: extensibility > skylark, P1
