### ISSUE TITLE
Bazel includes symlinks in glob at top-level

### ISSUE THREAD

**Issue by mattmoor** [bazelbuild/bazel#3297] opened 2017-06-29 22:16 UTC
For more details see: https://github.com/google/containerregistry/issues/11

... and the original issue to which it links.

@damienmg FYI

**Comment by mattmoor** [comment] 2017-06-29 22:16
@duggelz FYI

**Comment by damienmg** [comment] 2017-06-30 07:53
dupe of #1293

**Closed by damienmg** 2017-06-30 07:53 UTC
