### ISSUE TITLE
Directory outputs contain symlinks in 0.17.1rc1

### ISSUE THREAD

**Issue by jayconrod** [bazelbuild/bazel#5971] opened 2018-08-23 19:00 UTC
### Description of the problem / feature request:

Originally reported by @mhlopko in bazelbuild/rules_go#1669

rules_go has a rule called `go_path` which can produce a directory tree in a couple of different modes. In `copy` mode, the contents of the directory are expected to be regular files and subdirectories. They are written as regular files, but other rules that consume this output see them as symbolic links in the sandbox.

This can break tools like `tar` if rule authors aren't careful to dereference symbolic links. This is new behavior in 0.17.1rc1, and I don't see any mention of it in the release notes, so I think it's a regression. If this is intended behavior going forward, I'll likely need to remove `copy` mode from `go_path`.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

This [gist](https://gist.github.com/jayconrod/d6c7006199fcc79b39b3534bfcc84f21) defines a very simple rule that reproduces the problem and consumes the output of the rule in a test.

### What operating system are you running Bazel on?

Linux, amd64

### What's the output of `bazel info release`?

0.17.1rc1

### Any other information, logs, or outputs that you want to share?

@mhlopko pointed to #5721 as the point where this issue came up, but it happens for me locally without using a Docker image and doesn't seem related.

cc @philwo

**Comment by philwo** [comment] 2018-08-27 14:04
I ran a git bisect with your repro example (thanks!) and found this commit as the culprit: https://github.com/bazelbuild/bazel/commit/d4d3d506f4cf6cfaafaeeb717d681ff7784e2384

@buchgr Any idea?

**Comment by philwo** [comment] 2018-08-28 13:32
I had a look at this. The difference in behavior is basically: Where Bazel's sandbox before the change would symlink the directory of runfiles, it now traverses the directory structure and symlinks each file individually. For Bazel without sandboxing this doesn't make a difference and indeed, the repro works fine with Bazel HEAD with disabled sandboxing.

The fact that Bazel's sandbox represents input files as symbolic links is absolutely not great, but working as intended (because we don't know of any better mechanism to make input files appear in a sandbox directory) and has always been the case (except for this edge case where Bazel would not know the contents of certain directories). It's known that this is risky - e.g. your example of "tar" above. The solution is to write rules and tools that can correctly deal with symlinks.

See this, for example:
```bash
$ touch WORKSPACE

$ cat > BUILD <<'EOF'
genrule(
    name = "tar",
    srcs = glob(["inputs/*"]),
    outs = ["output.tar"],
    cmd = "tar cvf \"$@\" $(SRCS)",
)
EOF

$ mkdir inputs
$ touch inputs/{1,2,3}.txt

$ bazel clean; bazel build :tar
INFO: Clean command is running, shutting down worker pool...
INFO: Starting clean (this may take a while). Consider using --async if the clean takes more than several minutes.
INFO: Analysed target //:tar (7 packages loaded).
INFO: Found 1 target...
INFO: From Executing genrule //:tar:
inputs/1.txt
inputs/2.txt
inputs/3.txt
Target //:tar up-to-date:
  bazel-genfiles/output.tar
INFO: Elapsed time: 2.648s, Critical Path: 0.10s
INFO: 1 process: 1 linux-sandbox.
INFO: Build completed successfully, 2 total actions

$ tar tvf bazel-genfiles/output.tar 
lrwxrwxrwx philwo/primarygroup 0 2018-08-28 15:26 inputs/1.txt -> /usr/local/google/home/philwo/.cache/bazel/_bazel_philwo/292af7c156526bec758bef1eb31303e3/execroot/__main__/inputs/1.txt
lrwxrwxrwx philwo/primarygroup 0 2018-08-28 15:26 inputs/2.txt -> /usr/local/google/home/philwo/.cache/bazel/_bazel_philwo/292af7c156526bec758bef1eb31303e3/execroot/__main__/inputs/2.txt
lrwxrwxrwx philwo/primarygroup 0 2018-08-28 15:26 inputs/3.txt -> /usr/local/google/home/philwo/.cache/bazel/_bazel_philwo/292af7c156526bec758bef1eb31303e3/execroot/__main__/inputs/3.txt
```

We might be able to revert to the previous behavior for the "I have a directory in my runfiles" case. I'll investigate, but also wanted to point out that the symlink stuff is (and has always been) like this for normal inputs.

**Comment by jayconrod** [comment] 2018-08-28 23:41
@philwo Thanks for looking into this. I opened this issue because I wasn't sure this change was intended. Since it is, I'll consider this resolved, but I'll leave the issue open if you want to investigate further.

I'll disable the failing test in bazelbuild/rules_go#1669 for now, and I'll reconsider the `copy` mode in `go_path`.

**Comment by laurentlb** [comment] 2018-08-29 12:06
If a change in Bazel is breaking existing rules, shall we roll it back?

**Comment by philwo** [comment] 2018-08-29 12:16
I still don't know what the right thing to do is. I think it's possible to symlink directories instead of the files that they contain in the sandbox. This would even give us a performance boost (because creating potentially lots of individual symlinks is slow). We have a nice repro here thanks to @jayconrod that we can also turn into an integration test.

I have to think about it a few more days and look at the code. I don't think we should rollback the culprit commit unless we think that it's wrong in general. AFAIK it's an improvement for other things - we just didn't think about the impact on the sandboxing code.

**Comment by jayconrod** [comment] 2018-08-29 23:51
> I just want to point out again that you cannot rely on files in the sandbox being regular files. It's not in the API contract. Files in a sandbox (or remote) environment could be anything. Symlinks. Hardlinks. Bind mounts. The whole thing could be a FUSE filesystem. They could be read-only. I have no clue. There are simply no guarantees and we even have multiple strategies implementing various of the just mentioned.

This is the part that was unclear to me before. I think this may be a case of Hiram's law. :)

**Comment by buchgr** [comment] 2018-08-30 10:45
This seems all fine and not a release blocker. The only action item would be to add some documentation for skylark rules authors that they any file in Bazel may actually be a symlink.

**Comment by philwo** [comment] 2018-08-30 10:57
@jayconrod Thanks a lot for your patience and helpful comments here :)

I had another look at the code and discussed this issue with @buchgr and @lberki. If it's OK for you, we think it's better to keep it as it is now (all files are symlinks in the current sandbox implementation) instead of the previous behavior (all files are symlinks, except TreeArtifacts in runfiles) for consistency reasons. We think that files should ideally be represented the same way, no matter how they happen to be pulled into the inputs of an action.

If we find out or get the feedback that this is a performance problem, we're considering changing the sandbox code so that *all* TreeArtifacts (not just in runfiles, but also in inputs) are symlinked via their directory. This would reduce the number of symlinks that have to be created, which directly translates to increased performance. (FYI @AustinSchuh, who I remember has hit this performance issue in the past).

However, this should be treated as an implementation detail - for example, on macOS we might actually switch to using the APFS copy-on-write feature (if available) to put files into the sandbox, which would improve hermeticity and maybe even performance, in which case all input files would then appear as regular files. On the other side we have remote execution, where backends often represent files as symlinks to some shared network filesystem (e.g. myfile.txt -> /cas/e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855).

Another case: If people use [sandboxfs](https://blog.bazel.build/2018/04/13/preliminary-sandboxfs-support.html), then all files in the sandbox would also appear as regular files, even today.

I really wish we could just provide regular files on all platforms all the time, but unfortunately we aren't there yet due to platform-specific limitations and performance concerns. :|

**Comment by laurentlb** [comment] 2018-08-30 11:16
Is there any reason we don't try to provide a smoother rollout of the change?

My understanding is that:
 - We may break an undetermined number of users
 - Users can't know in advance whether the new release will break them or not
 - Users can't know if they rely on "implementation details"
 - The behavior and the guarantees we provide don't seem to be documented (are they?)
 - There's no flag to switch off the new behavior (so this may force users to rollback their Bazel upgrade)
 - There's no informative error message, so users might get confused

As mentioned in the first message, it will probably look like a bug to a user.
Are we okay will all of this? Or is there something I am missing?

**Comment by philwo** [comment] 2018-08-30 11:45
In general, I think that if a change doesn't break our tests and we don't get feedback during the RC phase that a change is blocking users from upgrading, then it should be fine.

Proposal for this time, as we have identified a possible performance issue with the new behavior: I'll add a flag that allows users to revert to the previous behavior for the sandbox and if no one tells us that they need to use it, we can remove it again in 0.18.

**Comment by laurentlb** [comment] 2018-08-30 13:40
For this specific change, a bug was reported with the CI, even before the RC phase. RC phase is not 
 even complete and I suspect very few people try the RC. So I think it's fair to provide a workaround.

If it's not too much trouble to add the flag, I think it's great! Thanks a lot!
Ideally, we would keep the old behavior by default (to leave time to users to update their code before a Bazel release breaks them by default) and follow the [incompatible changes](https://docs.bazel.build/versions/master/skylark/backward-compatibility.html) workflow, but maybe it's too annoying for this specific change?

**Comment by philwo** [comment] 2018-09-03 14:46
I've committed a change that disables this behavior in 0.17 to give users time to upgrade their code in case this would break them.

It can be enabled in 0.17 via the flag --incompatible_symlinked_sandbox_expands_tree_artifacts_in_runfiles_tree and will probably become the default in 0.18 if we don't hear about performance issues or other problems. :)

**Comment by laurentlb** [comment] 2018-09-03 15:42
Thanks!
Added to the cherrypick list.

**Closed by laurentlb** 2018-09-03 15:42 UTC
Labels: release blocker, team-Execution, untriaged
