### ISSUE TITLE
All tests fail with `--spawn_strategy=remote`

### ISSUE THREAD

**Issue by schroederc** [bazelbuild/bazel#942] opened 2016-02-19 17:34 UTC
Given `build --hazelcast_node=127.0.0.1:5701 --spawn_strategy=remote` in the `.bazelrc` config, all tests run with `bazel test` will report failures (even though the log suggests they succeeded).  On the other hand, `bazel build //...` completes successfully with the same options.  Adding `test --spawn_strategy=sandboxed` to `.bazelrc` will allow the tests to succeed again.

**Comment by ulfjack** [comment] 2017-03-14 17:45
Let me mark this as a dupe of #1413.

**Closed by ulfjack** 2017-03-14 17:45 UTC
Labels: category: service APIs, P2, type: bug
