### ISSUE TITLE
Inconsistent failback versioning when bootstrapping bazel 2.0.0 and 2.2.0 

### ISSUE THREAD

**Issue by settle** [bazelbuild/bazel#11037] opened 2020-03-27 23:14 UTC
### Description of the problem / feature request:

Bootstrapping bazel 2.0.0 says it "not a release version and one was not defined explicitly in rbe_autoconfig target. Falling back to '0.28.1'", but bootstrapping bazel 2.2.0 says it "is not a release version and one was not defined explicitly in rbe_autoconfig target. Falling back to '2.0.0'", not 0.28.1 as expected according to the prior message.

### Feature requests: what underlying problem are you trying to solve with this feature?

Bootstrap bazel build for arm64v8/ubuntu:18.04 build fails.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Bootstrapping Bazel 2.0.0 -- Following the provided bootstrap bazel [instructions](https://docs.bazel.build/versions/2.0.0/install-compile-source.html), only substituting python3 for python, results in the following build messages.

Building Bazel from scratch......
Building Bazel with Bazel.
DEBUG: /tmp/bazel_PBpXnsLZ/out/external/bazel_toolchains/rules/rbe_repo/version_check.bzl:59:9: 
Current running Bazel is not a release version and one was not defined explicitly in rbe_autoconfig target. Falling back to '0.28.1'
DEBUG: /tmp/bazel_PBpXnsLZ/out/external/bazel_toolchains/rules/rbe_repo/checked_in.bzl:103:9: rbe_ubuntu1804_java11 not using checked in configs as detect_java_home was set to True 
DEBUG: /tmp/bazel_PBpXnsLZ/out/external/bazel_toolchains/rules/rbe_repo/version_check.bzl:59:9: 
Current running Bazel is not a release version and one was not defined explicitly in rbe_autoconfig target. Falling back to '0.28.1'
DEBUG: /tmp/bazel_PBpXnsLZ/out/external/bazel_toolchains/rules/rbe_repo/checked_in.bzl:103:9: rbe_ubuntu1604_java8 not using checked in configs as detect_java_home was set to True 
DEBUG: /tmp/bazel_PBpXnsLZ/out/external/build_bazel_rules_nodejs/internal/common/check_bazel_version.bzl:49:5: 
Current Bazel is not a release version, cannot check for compatibility.
DEBUG: /tmp/bazel_PBpXnsLZ/out/external/build_bazel_rules_nodejs/internal/common/check_bazel_version.bzl:51:5: Make sure that you are running at least Bazel 0.17.1.

Bootstrapping Bazel 2.2.0 -- Following the provided bootstrap bazel [instructions](https://docs.bazel.build/versions/2.2.0/install-compile-source.html), only substituting python3 for python, results in the following build messages.

Building Bazel from scratch......
Building Bazel with Bazel.
DEBUG: /tmp/bazel_Op4k0fLX/out/external/bazel_toolchains/rules/rbe_repo/version_check.bzl:59:9: 
Current running Bazel is not a release version and one was not defined explicitly in rbe_autoconfig target. Falling back to '2.0.0'
DEBUG: /tmp/bazel_Op4k0fLX/out/external/bazel_toolchains/rules/rbe_repo/checked_in.bzl:103:9: rbe_ubuntu1804_java11 not using checked in configs as detect_java_home was set to True 
DEBUG: /tmp/bazel_Op4k0fLX/out/external/bazel_toolchains/rules/rbe_repo/version_check.bzl:59:9: 
Current running Bazel is not a release version and one was not defined explicitly in rbe_autoconfig target. Falling back to '2.0.0'
DEBUG: /tmp/bazel_Op4k0fLX/out/external/bazel_toolchains/rules/rbe_repo/checked_in.bzl:103:9: rbe_ubuntu1604_java8 not using checked in configs as detect_java_home was set to True 
DEBUG: /tmp/bazel_Op4k0fLX/out/external/build_bazel_rules_nodejs/internal/common/check_bazel_version.bzl:49:5: 
Current Bazel is not a release version, cannot check for compatibility.
DEBUG: /tmp/bazel_Op4k0fLX/out/external/build_bazel_rules_nodejs/internal/common/check_bazel_version.bzl:51:5: Make sure that you are running at least Bazel 0.17.1.

### What operating system are you running Bazel on?

arm64v8/ubuntu:18.04

**Comment by rajeev921** [comment] 2020-04-20 22:40
I having the same issue. Scratching my head after trying 2.0.0 and 2.1.0. Getting the same error again and again.

**Comment by Emmaka9** [comment] 2020-11-01 15:20
were you guys able to solve it? What did you guys do about it?

**Comment by philwo** [comment] 2020-12-08 18:12
This is just a debug message and not the cause for any build error. I assume that this is fixed in recent Bazel versions (earlier ones did not have arm64 support yet).

**Closed by philwo** 2020-12-08 18:12 UTC
Labels: team-XProduct, untriaged

**Comment by einzigsue** [comment] 2021-08-16 01:25
Is it the bug coming back? it can still be compiled but I have to use 4.1.0 to build new jax as it needs a new feature in Bazel not available in 3.1.0.

I am compiling 4.1.0 from the file https://github.com/bazelbuild/bazel/releases/download/4.1.0/bazel-4.1.0-dist.zip 
and encountered this issue again. Please see details below. 
"""
OS: CentOS 8.4.2105
Message: 
DEBUG: /tmp/bazel_OeW1uwhe/out/external/bazel_toolchains/rules/rbe_repo/version_check.bzl:59:14: 
Current running Bazel is not a release version and one was not defined explicitly in rbe_autoconfig target. Falling back to '3.1.0'
DEBUG: /tmp/bazel_OeW1uwhe/out/external/bazel_toolchains/rules/rbe_repo/checked_in.bzl:103:14: rbe_ubuntu1804_java11 not using checked in configs as detect_java_home was set to True 
DEBUG: /tmp/bazel_OeW1uwhe/out/external/bazel_toolchains/rules/rbe_repo/version_check.bzl:59:14: 
Current running Bazel is not a release version and one was not defined explicitly in rbe_autoconfig target. Falling back to '3.1.0'
DEBUG: /tmp/bazel_OeW1uwhe/out/external/bazel_toolchains/rules/rbe_repo/checked_in.bzl:103:14: rbe_ubuntu1604_java8 not using checked in configs as detect_java_home was set to True 
INFO: Analyzed target //src:bazel_nojdk (334 packages loaded, 9419 targets configured).
...
"""
