### ISSUE TITLE
.bazelrc parsing should be more strict

### ISSUE THREAD

**Issue by keith** [bazelbuild/bazel#21360] opened 2024-02-14 23:06 UTC
### Description of the bug:

There are some interesting cases of `.bazelrc` file parsing that seem like they should throw an error. Each of these examples is the entire file:

```
--copt=-invalid
```

```
build --copt=-v \
  # some comment \
  --copt=-invalid
```

```
build --copt=-v \
```

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Create a `.bazelrc` with any of the examples above, run a build passing `--announce_rc`, note the flags passed may not contain what you'd expect. Ideally these should error.	

### Which operating system are you running Bazel on?

macOS

### What is the output of `bazel info release`?

release 7.0.2

**Comment by Wyverald** [comment] 2024-02-14 23:54
dupe of https://github.com/bazelbuild/bazel/issues/15245

**Closed by Wyverald** 2024-02-14 23:54 UTC
Labels: type: bug, untriaged
