### ISSUE TITLE
wrong command args when building remotely on Windows using non-Windows host

### ISSUE THREAD

**Issue by sluongng** [bazelbuild/bazel#22169] opened 2024-04-29 11:00 UTC
### Description of the bug:

My setup has the host machine being MacOS and Windows laptops and remote execution environment (exec) being Windows.

Given a toolchain with tool_paths like this
```
  tool_paths = {
    "ar": "C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.39.33519/bin/HostX64/x64/lib.exe",
    "ml": "C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.39.33519/bin/HostX64/x64/ml64.exe",
    "cpp": "C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.39.33519/bin/HostX64/x64/cl.exe",
    "gcc": "C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.39.33519/bin/HostX64/x64/cl.exe",
    "gcov": "wrapper/bin/msvc_nop.bat",
    "ld": "C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.39.33519/bin/HostX64/x64/link.exe",
    "nm": "wrapper/bin/msvc_nop.bat",
    "objcopy": "wrapper/bin/msvc_nop.bat",
    "objdump": "wrapper/bin/msvc_nop.bat",
    "strip": "wrapper/bin/msvc_nop.bat",
  },
```

With host being Windows, Bazel would produce the command with correct arguments. However, when I switched to a MacOS host, the argument was rendered incorrectly like this:

```
external/buildbuddy_toolchain/C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.39.33519/bin/HostX64/x64/cl.exe
@bazel-out/windows-fastbuild/bin/_objs/main/main.obj.params
```

### Which category does this issue belong to?

Remote Execution

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

I have a simple example provided in https://github.com/buildbuddy-io/buildbuddy-toolchain/pull/23

### Which operating system are you running Bazel on?

MacOS

### What is the output of `bazel info release`?

7.1.1

### Any other information, logs, or outputs that you want to share?

I discussed this with @fmeum about this has it seems like this was caused by PathFragment depending on host's OS to determine the right normalized path. I think a potential fix here is to detect Windows RBE being used to change the path to Windows instead.

**Comment by tjgq** [comment] 2024-04-29 11:15
Duplicate of https://github.com/bazelbuild/bazel/issues/19208 (where some potential solutions are discussed).

**Closed by tjgq** 2024-04-29 11:15 UTC
Labels: type: bug, untriaged, team-Remote-Exec
