### ISSUE TITLE
7.0.0rc2 regression from 6.4.0 (new throw_linked_but_not_exported_errors)

### ISSUE THREAD

**Issue by peakschris** [bazelbuild/bazel#19920] opened 2023-10-23 14:43 UTC
### Description of the bug:

I have a number of header-file-only libraries, and link these into a number of our shared libraries:

Since upgrading from bazel 6.4.0 to bazel 7.0.0rc2, I am getting this error:

```
ERROR: D:/units/cb_bazel/src/path/to/BUILD.bazel:3:21: in cc_shared_library rule //src/path/to/z:libz:
Traceback (most recent call last):
        File "/virtual_builtins_bzl/common/cc/cc_shared_library.bzl", line 661, column 114, in _cc_shared_library_impl
        File "/virtual_builtins_bzl/common/cc/cc_shared_library.bzl", line 527, column 42, in _filter_inputs
        File "/virtual_builtins_bzl/common/cc/cc_shared_library.bzl", line 545, column 9, in _throw_linked_but_not_exported_errors
Error in fail: The following libraries were linked statically by different cc_shared_libraries but not exported:
cc_shared_library @@//src/path/to/lib:lib:
  "@@//src/path/to:include_root",
  "@@x//:libx_headers",
  "@@cpputils//:cpputils",
If you are sure that the previous libraries are exported by the cc_shared_libraries because:
  1. You have visibility declarations in the source code
  2. Or you are passing a visibility script to the linker to export symbols from them
then add those libraries to roots or exports_filter for each cc_shared_library.
```

what these dependent libraries have in common is that they are include-only:

```
cc_library(
    name = "cpputils",
    hdrs = glob(["include/cpputils/fmt/*.h", "include/cpputils/*.hxx"]),
    includes = ["include"],
)
```

### Which category does this issue belong to?

C++/Objective-C Rules

### Which operating system are you running Bazel on?

Windows

### What is the output of `bazel info release`?

release 7.0.0rc2

### Is this a regression? If yes, please try to identify the Bazel commit where the bug was introduced.

Yes, 6.4.0 did not have this issue

**Comment by fmeum** [comment] 2023-10-23 15:38
Could you check whether this is fixed with `USE_BAZEL_VERSION=d15ea929e2382b7354cb900b89fc22480b60ff4d`? Could be the same root cause as https://github.com/bazelbuild/bazel/issues/19822.

**Comment by peakschris** [comment] 2023-10-23 15:41
No, unfortunately USE_BAZEL_VERSION=d15ea929e2382b7354cb900b89fc22480b60ff4d does not fix it, exactly the same error message is produced.

```
D:\udu\units\cb_1012_bazel>bazel info release
2023/10/23 16:41:15 Using unreleased version at commit d15ea929e2382b7354cb900b89fc22480b60ff4d
WARNING: Option 'experimental_remote_build_event_upload' is deprecated: Use --remote_build_event_upload instead
WARNING: Option 'experimental_remote_cache_compression' is deprecated: Use --remote_cache_compression instead
INFO: Invocation ID: b90d014e-9200-45cf-ae56-2a2b3812852e
development version
```

**Comment by fmeum** [comment] 2023-10-25 12:34
@bazel-io flag

**Comment by iancha1992** [comment] 2023-10-25 18:05
@bazel-io fork 7.0.0

**Comment by layus** [comment] 2023-10-30 12:36
Hitting the exact same issue here, with the only (potential) difference that I disable bzlmod. How can we help debugging this ?

**Comment by fmeum** [comment] 2023-10-30 13:42
CC @oquenchil

**Comment by oquenchil** [comment] 2023-10-30 14:42
Fix is on the way

@bazel-io fork 7.0.0

**Comment by iancha1992** [comment] 2023-10-30 17:31
@bazel-io fork 7.0.0

**Comment by fmeum** [comment] 2023-11-03 18:43
Reopening since this has been rolled back.

**Comment by keertk** [comment] 2023-11-10 19:31
Hi all, is this still on track for 7.0? We're trying to close out the open release blockers and prepare for the final RC on Wed.

**Comment by fmeum** [comment] 2023-11-10 19:50
Cc @buildbreaker2021

**Comment by buildbreaker2021** [comment] 2023-11-14 16:13
@peakschris I have a potential fix, however it would be nice to have a minimal example to reproduce this to make sure that the fix is correct.

**Closed** 2023-11-16 15:13 UTC
Labels: type: bug, team-Rules-CPP, untriaged

**Comment by meteorcloudy** [comment] 2023-11-16 15:22
@peakschris We have the potential fix submitted, we will backport it into 7.0 and have a new rc today.

**Comment by Ryang20718** [comment] 2024-03-15 00:24
@meteorcloudy 

Let me know if you'd like for me to open a new issue for this, but I'm still hitting errors on 7.1.0.

I've created a small repro here: https://github.com/Ryang20718/repro-cpp-linker

if you clone it and run `bazelisk test //rust:rust_example_test` you'll hit a similar error 

```
Error in fail: The following libraries were linked statically by different cc_shared_libraries but not exported:
cc_shared_library @proj//:proj_so:
```

**Comment by fmeum** [comment] 2024-03-15 08:03
@Ryang20718 Yes, please file a separate issue.

@meteorcloudy I suspect that some of the issues could be due to the `--enable_bzlmod` flip and its effect on Label stringification. https://github.com/bazelbuild/bazel/pull/21622 would fix that.
