### ISSUE TITLE
cquery returns references to SOURCE_FILE targets which don't exist

### ISSUE THREAD

**Issue by illicitonion** [bazelbuild/bazel#14611] opened 2022-01-20 17:44 UTC
Running the following query:
```
% bazel cquery 'deps(//java/example:ExampleTest)' --output=label_kind 2>/dev/null | grep -E '@bazel_tools//tools/test:(tw|xml) ' 
source file @bazel_tools//tools/test:xml (null)
source file @bazel_tools//tools/test:tw (null)
```

These two source files don't exist, but are reported in the cquery results.

These appear to be referenced here:

https://github.com/bazelbuild/bazel/blob/4aad372fc2452d160b36d81864671ffca13aae89/tools/test/BUILD.tools#L46-L67

Having these files be reported, but not exist at their reported location, makes it harder to consistently programatically interpret cquery output. In general, referencing files which don't exist is an error - it would be great to avoid these pseudo-files needing to exist.

**Comment by katre** [comment] 2022-01-28 18:08
This is actually very simple to reproduce:

In BUILD:
```
filegroup(
    name = "files",
    srcs = [
        "does_not_exist",
    ],
)
```

Then run:
```
$ bazel query //:*
//:BUILD
//:does_not_exist
//:files
Loading: 1 packages loaded
```

The real question is, why does this happen? The answer is, that Bazel is lazy. Specifically, it's lazy during BUILD file evaluation: [`Package.Builder.createInputFile`](https://cs.opensource.google/bazel/bazel/+/master:src/main/java/com/google/devtools/build/lib/packages/Package.java;drc=a6c3f2327df424e56674a6bd758566d2757afdc7;l=1565) does not actually check that a real file exists when creating the `InputFile` for a referenced Label!

This is to support ["assumed input files"](https://cs.opensource.google/bazel/bazel/+/master:src/main/java/com/google/devtools/build/lib/packages/Package.java;drc=d99f8fe2d797e4c58cd4526f77feed12863174eb;l=1786):
```
          // All labels mentioned by a rule that refer to an unknown target in the current package
          // are assumed to be InputFiles, so let's create them. We add them to a temporary map
          // to avoid concurrent modification to this.targets while iterating (via getRules()).
```

This looks like a variable but I can't find a call path where it isn't set.

**Comment by katre** [comment] 2022-01-28 18:11
The fix would either be for `query` to not set this, or for `QueryCommand` to check whether input files exist when outputting them. The issue then is what happens in your example?

Given this:
```
 filegroup( 
     name = "test_wrapper", 
     srcs = select({ 
         "@bazel_tools//src/conditions:windows": ["tw.exe"], 
         "//conditions:default": ["tw"], 
     }), 
 ) 
```

The [docs for `query` and `select` ](https://docs.bazel.build/versions/main/query.html) state fairly clearly:
```
Traditional Bazel query runs on the post-loading phase target graph and therefore has no concept of configurations and their related concepts. Notably, this means it does not correctly resolve select statements and rather returns all possible resolutions of selects.
```

This means that, according to the target graph (and, therefore, to `query`), the target `test_wrapper` does in fact depend on both `tw.exe` and `tw`, and which one to use will be selected when the target is analyzed. For query to then either ignore one, or drop one, seems like a violation of the implied contract in the docs.

On the other hand, I've been testing query but you asked about cquery, so let's do some further debugging.

```

**Comment by katre** [comment] 2022-01-28 18:15
Slightly more complex BUILD file:
```
config_setting(
    name = "cpu_arm64",
    values = {
        "cpu": "arm64",
    },
)

filegroup(
    name = "files",
    srcs = select({
        "//:cpu_arm64": ["does_not_exist_arm64"],
        "//conditions:default": ["does_not_exist_default"],
    }),
)
```

In this case, I would expect the `cquery` to only have one input file dependency, since only one is used. Instead, it seems to have both:
```
$ bazel cquery //:*
//:BUILD (null)
//:cpu_arm64 (28ff575)
//:does_not_exist_arm64 (null)
//:does_not_exist_default (null)
//:files (28ff575)

$ bazel cquery --cpu=arm64 //:*
//:BUILD (null)
//:cpu_arm64 (e924cb0)
//:does_not_exist_arm64 (null)
//:does_not_exist_default (null)
//:files (e924cb0)
```

Time to debug that select, I think.

**Comment by katre** [comment] 2022-01-28 18:35
Deleted my earlier comments because I was doing the wrong thing in the wrong way, and now am re-starting from scratch.

**Comment by katre** [comment] 2022-01-28 18:42
To repeat some of what I said earlier:

1. Bazel assumes that [anything label-shaped that isn't actually defined in a BUILD file must be an input file](https://cs.opensource.google/bazel/bazel/+/master:src/main/java/com/google/devtools/build/lib/packages/Package.java;drc=d99f8fe2d797e4c58cd4526f77feed12863174eb;l=1786)
2. As a performance measure, Bazel doesn't pre-emptively check whether these actually exist
   1. It's assumed that if the file is accessed by the rule, the error can be detected and reported then.
3. This means, however, that cases like this where a file is referenced but never used will slip through the cracks.

**Comment by katre** [comment] 2022-01-28 18:59
It looks like `@bazel_tools//tools/test:test_wrapper` is only referenced from native rules:
- [TestBaseRule's `$test_wrapper` attribute](https://cs.opensource.google/bazel/bazel/+/master:src/main/java/com/google/devtools/build/lib/analysis/BaseRuleClasses.java;drc=4dd74020e8067fb228a0439f0887723c8ec8772e;l=225)
- [The `$test_wrapper` attribute added to Starlark test rules](https://cs.opensource.google/bazel/bazel/+/master:src/main/java/com/google/devtools/build/lib/analysis/starlark/StarlarkRuleClassFunctions.java;drc=fc13ba271f138c804869d0f99d751e25518b5326;l=218)

However, these wrappers are [only used on Windows](https://cs.opensource.google/bazel/bazel/+/master:src/main/java/com/google/devtools/build/lib/analysis/test/TestActionBuilder.java;drc=d99f8fe2d797e4c58cd4526f77feed12863174eb;l=198), so the files are never accessed on another host, leading to the issue mentioned above.

**Comment by katre** [comment] 2022-01-28 19:02
We could add a flag to cquery that validates that all input files actually exist, but I'm not sure how much slower all the extra stat calls would make the execution. I'm going to keep these notes but I don't think we can prioritize the work.

I've created #14663 to at least fix these two files, if it passes tests and helps you I'll see about getting it merged.

**Comment by illicitonion** [comment] 2022-01-31 13:54
Sounds good - thanks for the investigation!

**Comment by katre** [comment] 2022-02-15 17:21
As for the idea of adding a flag for query/cquery that tries to stat files and be sure they exist: we don't have plans to work on this, but I'll be happy to review a PR if anyone wants to send one.

**Comment by katre** [comment] 2022-12-02 20:49
Closing this since we aren't planning on making any changes, feel free to file a PR if anyone is interested.

**Closed by katre** 2022-12-02 20:49 UTC
Labels: type: bug, P3, team-Configurability
