### ISSUE TITLE
zsh completion does not work

### ISSUE THREAD

**Issue by jck** [bazelbuild/bazel#3218] opened 2017-06-20 01:54 UTC
Please provide the following information. The more we know about your system and use case, the more easily and likely we can help.

### Description of the problem / feature request / question:
I'm using bazel `0.5.1`, and zsh `5.3.2`

This is the error I get when I try to invoke tab completion:
```
..._bazel_get_options:10: command not found: b                                    
_get_commands:5: command not found: b
```

**Comment by philwo** [comment] 2017-06-21 10:06
I don't think we have a clear owner for this... assigning to @aehlig just to have a look, as he knows the most about shells in our team :)

**Comment by aehlig** [comment] 2017-06-30 08:00
Sorry, I need more information about how you set up your `zsh` completion. I verified with various versions of `zsh`, inclduding 5.3.1,  that following the [instructions to set up `zsh` completion for bazel](https://docs.bazel.build/versions/master/install.html#zsh) works as described. So I can't reproduce your issue.

**Comment by aehlig** [comment] 2017-07-31 14:21
Closing as obsolete; feel free to reopen with more instructions on how to reproduce the issue.

**Closed by aehlig** 2017-07-31 14:21 UTC
Labels: category: misc > misc, Under investigation

**Comment by marcusjwhelan** [comment] 2018-05-24 20:25
@aehlig  Still an issue on mac. Mac High. Install bazel using the binary installer. Used commands just as described. 

However after adding to bashrc it works for the first time(Sometimes) then once you close and re-open a new shell, bazel no longer is a known command.
