### ISSUE TITLE
[C++] Exclusion markers not working during run bazel coverage

### ISSUE THREAD

**Issue by Changqing-JING** [bazelbuild/bazel#16718] opened 2022-11-09 09:57 UTC
### Description of the bug:

In a C++ project, // LCOV_EXCL_START and // LCOV_EXCL_STOP not working when run bazel coverage.

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Build and Run a simple C++ project with bazel coverage
Full code is pushed to github https://github.com/Changqing-JING/BazelCoverageBugCandidate.git

# Bazel project layout
src/lib1.h
```cpp
int foo();
```
src/lib1.cpp
```cpp
#include "lib1.h"
int a = 10;

int foo(){
    if(a>1){
        return 1;
    }
    // LCOV_EXCL_START
    else{
        return 2;
    }
    // LCOV_EXCL_STOP
}
```

src/test.cpp
```cpp
#include "lib1.h"

int main(){
    foo();
    return 0;
}
```

src/BUILD
```python
cc_library(
    name = "lib1",
    srcs = ["lib1.cpp"],
    hdrs = ["lib1.h"]
)

cc_test(
    name = "test_lib1",
    srcs = ["test.cpp"],
    deps = [
        ":lib1"
    ],
)
```

# Run bazel coverage
```shell
bazel coverage //src:test_lib1 --combined_report=lcov  && genhtml "$(bazel info output_path)/_coverage/_coverage_report.dat" -o bazel-coverage
```
In the html report, the lines between // LCOV_EXCL_START and // LCOV_EXCL_STOP are not ingored
![image](https://user-images.githubusercontent.com/59640930/200799152-aa6d0f13-398a-4eb9-b626-6705c930b15e.png)

### Which operating system are you running Bazel on?

Ubuntu 22.04, Linux ubuntu 5.15.0-25-generic #25-Ubuntu SMP Wed Mar 30 15:54:22 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### What is the output of `bazel info release`?

release 5.3.0

**Comment by sgowroji** [comment] 2022-11-09 10:00
Dupe of https://github.com/bazelbuild/bazel/issues/16716

**Comment by c-mita** [comment] 2022-11-15 15:23
I believe that these markers are specific to the lcov tool (`geninfo`), which I believe parses the original source files to identify these markers and then exclude ranges from its output.

The compiler, `gcov`, etc, do not do anything special with these markers AFAICT, so the inputs to Bazel's coverage management is exactly the same, and Bazel does not parse the source files at this stage.

**Comment by Changqing-JING** [comment] 2022-11-16 05:03
@c-mita I'm sorry it's not the case.
geninfo is not reasonable of filter out // LCOV_EXCL_START. The filter is done by lcov command on linux.
For example:
main.c
```c
#include <assert.h>

int a = 1;

int main(){
    
    while(a<10){
        a++;
    }
    
/*LCOV_EXCL_START*/
    assert(a == 10);
/*LCOV_EXCL_STOP*/
    return 0;
}
```

Makefile
````
bin:
	gcc -g -fprofile-arcs -ftest-coverage -o main main.c

run:bin
	./main

gcov:run
	gcov -b main.c

lcov:gcov
	lcov --rc lcov_branch_coverage=1 --capture --directory . --output-file main_coverage.info

html:lcov
	genhtml --branch-coverage -o coverage_reports/ main_coverage.info
``` 
The command "lcov --rc lcov_branch_coverage=1 --capture --directory . --output-file main_coverage.info" will proceed the gcov output and filter out  // LCOV_EXCL_START

But when executing bazel coverage, the lcov is not used. Instead, bazel used its own Lcov parser https://github.com/bazelbuild/bazel/blob/master/tools/test/CoverageOutputGenerator/java/com/google/devtools/coverageoutputgenerator/LcovParser.java

This parser didn't process the // LCOV_EXCL_START marker.

To solve this problem, // LCOV_EXCL_START processing need to be added into this Java module.

**Comment by c-mita** [comment] 2022-11-16 16:57
`geninfo` is part of `lcov`; it's just a pile of perl, a wrapper around a bunch of tools.

A little experimentation shows that `lcov` is able to respect these flags because it receives textual output from `gcov`.
In your example above:

```
$ gcov main.gcda
File 'main.c'
Lines executed:100.00% of 5
Creating 'main.c.gcov'

Lines executed:100.00% of 5
$ cat main.c.gcov
        -:    0:Source:main.c
        -:    0:Graph:main.gcno
        -:    0:Data:main.gcda
        -:    0:Runs:1
        -:    1:#include <assert.h>
        -:    2:
        -:    3:int a = 1;
        -:    4:
        1:    5:int main() {
        -:    6:
       10:    7:    while(a<10){
        9:    8:        a++;
        -:    9:    }
        -:   10:
        -:   11:/*LCOV_EXCL_START*/
       1*:   12:    assert(a == 10);
        -:   13:/*LCOV_EXCL_STOP*/
        1:   14:    return 0;
        -:   15:}
```
The textual output includes the source and so the markers can be seen and respected.

But Bazel receives "intermediate" outputs, the nature of which has changed over time, but today come in the form of JSON files which do not include these source file markers, so no filtering can be done (and crucially, do not require the source files themselves to create).

```
$ gcov main.gcda --json
File 'main.c'
Lines executed:100.00% of 5

Creating 'main.gcov.json.gz'
Lines executed:100.00% of 5

$ gzip -c -d main.gcov.json.gz
{"gcc_version": "12.2.0", "files": [{"lines": [{"branches": [], "count": 2, "line_number": 5, "unexecuted_block": false, "function_name": "main"}, {"branches": [], "count": 20, "line_number": 7, "unexecuted_block": false, "function_name": "main"}, {"branches": [], "count": 18, "line_number": 8, "unexecuted_block": false, "function_name": "main"}, {"branches": [], "count": 2, "line_number": 12, "unexecuted_block": true, "function_name": "main"}, {"branches": [], "count": 2, "line_number": 14, "unexecuted_block": false, "function_name": "main"}], "functions": [{"blocks": 7, "end_column": 1, "start_line": 5, "name": "main", "blocks_executed": 6, "execution_count": 2, "demangled_name": "main", "start_column": 5, "end_line": 15}], "file": "main.c"}], "format_version": "1", "current_working_directory": "/tmp/lcov_demo", "data_file": "main.gcda"}
```

These are processed by `GcovJsonParser` (and previously `GcovParser`). `LcovParser` can also process the final output of `geninfo` (the so-called "lcov format") but this again does not include any source file markings and is just raw "coverage data".

So I don't think this is something that we can support in Bazel, certainly not easily.

**Comment by Changqing-JING** [comment] 2022-11-17 02:11
@c-mita 
Thank you very much for your very detailed explanation. 

In my research, it seems that genhtml is a pure visualization tool, which can't process the // LCOV_EXCL_START marker.

As a solution or workaround, we can create a filter of the "lcov format" to exclude DA and BRDA which are in side  // LCOV_EXCL_START marker.
```
TN:
SF:/home/jcq/workspace/LearningProjects/LCovTest/main.c
FN:5,main
FNDA:1,main
DA:5,1
DA:7,10
BRDA:7,0,0,9
BRDA:7,0,1,1
DA:8,9
DA:12,1
BRDA:12,0,0,0
BRDA:12,0,1,1
DA:14,1
end_of_record
```

But I still want to know, is there an existing open source solution?
Since bazel is a very popular, I think I would not be the first person who find this issue. 
Do you know if there is something I can reuse?

**Comment by oquenchil** [comment] 2023-01-20 11:36
@c-mita can you please add a priority and remove the untriaged label?

**Comment by c-mita** [comment] 2023-01-20 15:03
>But I still want to know, is there an existing open source solution?
>Since bazel is a very popular, I think I would not be the first person who find this issue.
>Do you know if there is something I can reuse?

I am not aware of anything.

Closing because this is not a Bazel issue, or something that I believe Bazel can work around or provide.

**Closed by c-mita** 2023-01-20 15:03 UTC
Labels: type: bug, coverage, team-Rules-CPP, untriaged

**Comment by abksdev** [comment] 2023-05-18 02:31
@oquenchil Did you got any workaround for making the Exclusion Markers work with ```bazel cover```

**Comment by Changqing-JING** [comment] 2023-05-18 13:42
@abksdev one workaround could be: 
After bazel converage executed, it generated a lcov file. This lcov file can be filtered by a python script, then the lines are ignored in coverage reported.
https://github.com/Schleifner/lcov_filer_for_bazel

**Comment by abksdev** [comment] 2023-05-18 21:47
> @abksdev one workaround could be: 
> After bazel converage executed, it generated a lcov file. This lcov file can be filtered by a python script, then the lines are ignored in coverage reported.
> https://github.com/Schleifner/lcov_filer_for_bazel

@oquenchil Thanks for the reference 😀
