### ISSUE TITLE
3.7 release broke JavaBuilder errors; please create patch release

### ISSUE THREAD

**Issue by ulfjack** [bazelbuild/bazel#12959] opened 2021-02-03 12:54 UTC
### Description of the problem / feature request:

JavaBuilder doesn't reliably flush stderr when *not* using persistent workers.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Build a `java_binary` rule with a source file that has a compile error, like so:
```
public class Main {
  public static void main(String[] args) {
    System.out.println("hello")
  }
}
```

```
java_binary(
    name = "main",
    srcs = ["Main.java"],
    main_class = "Main",
)
```

```
$ bazel-3.7.2 build :main --stategy=Javac=local
```

### What operating system are you running Bazel on?

Linux.

### What's the output of `bazel info release`?

release 3.7.2

###  Have you found anything relevant by searching the web?

The error was introduced by @larsrc-google in https://github.com/bazelbuild/bazel/commit/c2ca81dc445ba15da5ddb5e90c97fefc6d1fd411.

It was fixed by @benjaminp in https://github.com/bazelbuild/bazel/commit/56f506c09facdac840db5b94821e9d507926440a.

### Any other information, logs, or outputs that you want to share?

This typically breaks remote execution, which *doesn't* use persistent workers, while not affecting local execution, which uses persistent workers by default.

**Comment by ulfjack** [comment] 2021-02-03 12:56
I'd like to request a patch release 3.7.3 with the fix (does this require a release of JavaBuilder?). If that is not going to happen, then we'll have to recommend avoiding 3.7.x (or create our own patch release).

**Comment by larsrc-google** [comment] 2021-02-03 13:56
Thanks for bringing this to my attention! That fix looks fine, I'll bring
it in and get a patch out.

-Lars

**Comment by meisterT** [comment] 2021-02-05 20:28
Cc @katre

**Comment by katre** [comment] 2021-02-08 13:21
I see that 56f506c doesn't introduce a test. Let me see if I can reproduce the problem with 3.7.3 so that I can verify whether it's fixed after.

I will try to produce a 3.7.4 with the fix, but given the age, if the cherrypick doesn't apply cleanly I may not be able to proceed.

**Comment by katre** [comment] 2021-02-08 13:49
Okay, I created a candidate for 3.7.3 which cherry-picks 56f506c09facdac840db5b94821e9d507926440a, and that does not fix the observed error:

```
$ ../bazel-release-3.7.3/bazel-bin/src/bazel build :main --strategy=Javac=local
Extracting Bazel installation...
Starting local Bazel server and connecting to it...
INFO: Analyzed target //:main (20 packages loaded, 373 targets configured).
INFO: Found 1 target...
ERROR: /usr/local/google/home/jcater/repos/java-worker-test/BUILD.bazel:1:12: Couldn't build file main.jar: Building main.jar (1 source file) failed (Exit 1): java failed: error executing command external/remotejdk11_linux/bin/java -XX:+UseParallelOldGC -XX:-CompactStrings '--add-exports=jdk.compiler/com.sun.tools.javac.api=ALL-UNNAMED' ... (remaining 15 argument(s) skipped)
Target //:main failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 8.063s, Critical Path: 1.12s
INFO: 2 processes: 2 internal.
FAILED: Build did NOT complete successfully
```

Testing with Bazel 4.0.0 does correctly show the syntax error, however. Is there another commit that needs to be included?

**Comment by ulfjack** [comment] 2021-02-10 17:09
I'm not sure how JavaBuilder releases work - it's possible that cherry-picking and compiling Bazel doesn't actually pick up the fix if it doesn't build JavaBuilder as part of the normal build process.

**Comment by katre** [comment] 2021-02-10 17:12
Paging @comius to discuss JavaBuilder releases.

**Comment by comius** [comment] 2021-02-10 17:41
JavaBuilder is part of java_tools, so you need to upgrade which java_tools are used for the fix to have an effect.

bazel 3.7.2 is using java_tools 10.4, however that version **does** contain the @benjaminp's 56f506c.
bazel 4.0.0 is using java_tools 10.5, which should be compatible with 10.4 and contains a turbine fix (see https://github.com/bazelbuild/java_tools/issues/39)

So if java_tools 10.4 is the problem, you can try cherry-picking https://github.com/bazelbuild/bazel/commit/4e5d0fdf067c1f7116c22a2699d7a1941e536886, which was used in bazel 4.0.0.

**Comment by katre** [comment] 2021-02-11 14:49
Thanks, @comius, I tried adding that cherrypick (which needed manual resolution, but it was fairly straightforward), but there's still an unexpected error:

```
$ ../bazel-release-3.7.3/bazel-bin/src/bazel build :main --strategy=Javac=local
Extracting Bazel installation...
Starting local Bazel server and connecting to it...
INFO: Analyzed target //:main (20 packages loaded, 373 targets configured).
INFO: Found 1 target...
ERROR: /usr/local/google/home/jcater/repos/java-worker-test/BUILD.bazel:1:12: Couldn't build file main.jar: Building main.jar (1 source file) failed (Exit 1): java failed: error executing command external/remotejdk11_linux/bin/java -XX:+UseParallelOldGC -XX:-CompactStrings '--patch-module=java.compiler=external/remote_java_tools_linux/java_tools/java_compiler.jar' ... (remaining 15 argument(s) skipped)
BazelJavaBuilder threw exception: unknown option : '--classdir'
Target //:main failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 13.472s, Critical Path: 2.66s
INFO: 7 processes: 5 internal, 2 linux-sandbox.
FAILED: Build did NOT complete successfully
```

Is there some other commit I need to cherrypick to use java tools 10.5 properly?

**Comment by cushon** [comment] 2021-02-11 15:41
@katre the --classdir changes are related to https://github.com/bazelbuild/bazel/commit/5085d68c173de5881d10eed18aba8b429bec86dd, https://github.com/bazelbuild/bazel/commit/2350239c39841a67162c1c3de042397d6c3771e4, https://github.com/bazelbuild/bazel/commit/e16f4d72067cb1ce97c71eb74e967c92978aa487.

It might be easier to use and older baseline for javabuilder to match what 3.7 was using?

**Comment by katre** [comment] 2021-02-11 16:13
This has turned into a fairly complicated patch for a three-month-old non-LTS release.

@ulfjack: This appears to be fixed in 4.0.0. I assume that you have other issues keeping you from upgrading to that, but at this point I'm going to have to ask you to handle determining what needs to be patched to fix 3.7.2, because I don't have the knowledge and this release is out of date.

**Comment by sventiffe** [comment] 2021-05-07 11:41
Ivo, this bug hasn't got updated since being reopened and still is marked as P0 bug. Is this accurate?

**Comment by comius** [comment] 2021-05-07 14:35
> @ulfjack: This appears to be fixed in 4.0.0. I assume that you have other issues keeping you from upgrading to that, but at this point I'm going to have to ask you to handle determining what needs to be patched to fix 3.7.2, because I don't have the knowledge and this release is out of date.

Considering this, I'm changing to P3 (will be accepting patches). @ulfjack please close if it's already irrelevant.

**Closed** 2021-11-09 18:32 UTC
Labels: type: bug, P3, team-Rules-Java

**Comment by ablyes** [comment] 2021-11-11 01:06
Hello, i can't follow or may be i'm stupid. 
3.7.3 doesn't exist. 
The fix exists on 4.0.0 ... is there a way to get a fix for 3.7 branch ?

**Comment by comius** [comment] 2021-11-11 08:15
I didn't close the issue because it was resolved.

I closed it because it's fixed in 4.0.0, 3.7 is non-LTS and there seems to be lack of interest from the community to fix this on 3.7 branch.

**Comment by ablyes** [comment] 2021-11-11 08:34
Ok, thank you @comius 
How can I fix it by my own ? Because i seems to be very expensive task to migrate from 3.X branch to 4.

**Comment by comius** [comment] 2021-11-11 08:57
Make a branch with suggested cherry-picks, analize if you need additional ones, make a local release of java_tools on top of that and test with it. The last part is undocumented, there is a target in //src that builds a java_tools_linux zip (or a different os) for you and you can test it with --override_repository. 

If your manual tests work, I can review your branch, release java_tools properly, then you can update java_tools pins in your branch and we can make 3.7.3 release.

Alternatively there might be a released java_tools that already works, perhaps you can try that. I don't keep track of incompatible changes between java_tools and Bazel, that far back, so I can't tell you off my mind what could be a problem there.
