### ISSUE TITLE
Cannot delete path '/dev/null' on Windows

### ISSUE THREAD

**Issue by moroten** [bazelbuild/bazel#12728] opened 2020-12-17 22:12 UTC
### Description of the problem:

```
ERROR: C:/git/my_project/BUILD.bazel:30:8: Executing genrule //:stuff failed: Exec failed due to IOException: Cannot delete path '/dev/null': ERROR: src/main/native/windows/file-jni.cc(156): nativeDeletePath(\\?\\dev\null): ERROR: src/main/native/windows/file.cc(624): DeletePath(\\?\\dev\null): expected an absolute Windows path 
```

I suspect the `.exe` file extension on the tools is causing problems but that is just a guess.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Run the following under Windows:

```
touch tool_binary.py
cat > BUILD.bazel <<EOF
py_binary(
    name = "tool_binary",
    srcs = ["tool_binary.py"],
)

genrule(
    name = "stuff",
    tools = [":tool_binary"],
    outs = ["stuff.txt"],
    cmd = "echo stuff > $@",
)
EOF

# The following will fail
./bazelw build --remote_instance_name=buildbarn --remote_cache=grpc://my-buildbarn:8980 --remote_download_toplevel //:stuff
# The following will succeed
./bazelw build --remote_instance_name=buildbarn --remote_cache=grpc://my-buildbarn:8980 //:stuff
```

### What operating system are you running Bazel on?

Windows 10

### What's the output of `bazel info release`?

Patched build based on 4.0.0rc6.

###  Have you found anything relevant by searching the web?

Discussed by @Gormo and @meteorcloudy in #12455.

### Any other information, logs, or outputs that you want to share?

I might have lots more flags in my `.bazelrc`, but hopefully above is enough to reproduce.

**Comment by moroten** [comment] 2020-12-17 22:18
@philwo Can you set the `Release blocker` label, please?

**Comment by benjaminp** [comment] 2020-12-18 01:16
probably fixed by a87d7ed2411d5382bac58a20b79e09c464ad13b9

**Comment by meteorcloudy** [comment] 2021-01-05 10:45
@moroten Can you help confirm this issue is fixed by a87d7ed? Thanks for the reproduce case, but I cannot verify it because I don't have the setup for the remote build.

**Comment by moroten** [comment] 2021-01-07 10:27
[a87d7ed](https://github.com/bazelbuild/bazel/commit/a87d7ed2411d5382bac58a20b79e09c464ad13b9) fixes this issue, but there are more problems which were previously hidden, according to @gormo. He is still on vacation so I will try to track it down in the afternoon.

**Comment by meteorcloudy** [comment] 2021-01-07 10:54
OK, I'll close this one now, feel free to file new issues for other problems.

**Closed by meteorcloudy** 2021-01-07 10:54 UTC
Labels: P1, area-Windows, release blocker, team-XProduct, type: bug

**Comment by moroten** [comment] 2021-01-07 14:20
@meteorcloudy I created #12785 for the new problem.
