### ISSUE TITLE
Actions using ctx.actions.declare_directory() are never cached

### ISSUE THREAD

**Issue by srdjanstipic** [bazelbuild/bazel#20899] opened 2024-01-15 13:43 UTC
### Description of the bug:

Actions using ctx.actions.declare_directory() are never cached.

### Which category does this issue belong to?

Core

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

I am using bazel with remote caching enabled.
First I will show an example that uses `declare_file()` and is remote cacheable.
Second, I will modify the example to use `declare_directory()`
and I will show that bazel never caches modified example (even thought it should).
Before each `bazel build` I will clean all bazel data.

Remote cacheable example:

```bash
> ls non_cacheable_target
BUILD  defs.bzl

> cat non_cacheable_target/BUILD
load(":defs.bzl", "generate_output_files_rule")

generate_output_files_rule(name = "output_files")

> cat non_cacheable_target/defs.bzl
def _generate_output_files_rule_impl(ctx):
    generated_output = ctx.actions.declare_file(ctx.attr.name + "/file.txt")
    file_path = generated_output.path

    ctx.actions.run_shell(
        outputs = [generated_output],
        command = "echo Hola1 > " + file_path,
    )

    return [DefaultInfo(files = depset(direct = [generated_output]))]

generate_output_files_rule = rule(
    implementation = _generate_output_files_rule_impl,
)
```

I build the target like this (first invocation is not cached `1 processwrapper-sandbox`):
```bash
> bazel clean --expunge; bazel shutdown
> sudo rm -rf external /home/dockeruser/.cache/bazel /home/dockeruser/.cache/bazel_disk_cache/
> bazel build //non_cacheable_target/...
INFO: Starting clean (this may take a while). Consider using --async if the clean takes more than several minutes.
Extracting Bazel installation...
Starting local Bazel server and connecting to it...
INFO: Analyzed target //non_cacheable_target:output_files (8 packages loaded, 14 targets configured).
INFO: Found 1 target...
Target //non_cacheable_target:output_files up-to-date:
  bazel-bin/non_cacheable_target/output_files/file.txt
INFO: Elapsed time: 7.775s, Critical Path: 0.18s
INFO: 2 processes: 1 internal, 1 processwrapper-sandbox.
```

I build the same target again (second invocation is cached `1 remote cache hit`):
```bash
> bazel clean --expunge; bazel shutdown
> sudo rm -rf external /home/dockeruser/.cache/bazel /home/dockeruser/.cache/bazel_disk_cache/
> bazel build //non_cacheable_target/...
INFO: Starting clean (this may take a while). Consider using --async if the clean takes more than several minutes.
Extracting Bazel installation...
Starting local Bazel server and connecting to it...
INFO: Analyzed target //non_cacheable_target:output_files (8 packages loaded, 14 targets configured).
INFO: Found 1 target...
Target //non_cacheable_target:output_files up-to-date:
  bazel-bin/non_cacheable_target/output_files/file.txt
INFO: Elapsed time: 8.140s, Critical Path: 0.07s
INFO: 2 processes: 1 remote cache hit, 1 internal.
```

Now I modify the example to use `declare_directory()`:
```
diff --git a/non_cacheable_target/defs.bzl b/non_cacheable_target/defs.bzl
--- a/non_cacheable_target/defs.bzl
+++ b/non_cacheable_target/defs.bzl
@@ -1,6 +1,6 @@
 def _generate_output_files_rule_impl(ctx):
-    generated_output = ctx.actions.declare_file(ctx.attr.name + "/file.txt")
-    file_path = generated_output.path
+    generated_output = ctx.actions.declare_directory(ctx.attr.name)
+    file_path = generated_output.path + "/file.txt"

     ctx.actions.run_shell(
         outputs = [generated_output],
```

I build the modified example (first invocation is not cached `1 processwrapper-sandbox`):
```bash
> bazel clean --expunge; bazel shutdown
> sudo rm -rf external /home/dockeruser/.cache/bazel /home/dockeruser/.cache/bazel_disk_cache/
> bazel build //non_cacheable_target/...
INFO: Starting clean (this may take a while). Consider using --async if the clean takes more than several minutes.
Extracting Bazel installation...
Starting local Bazel server and connecting to it...
INFO: Analyzed target //non_cacheable_target:output_files (8 packages loaded, 14 targets configured).
INFO: Found 1 target...
Target //non_cacheable_target:output_files up-to-date:
  bazel-bin/non_cacheable_target/output_files
INFO: Elapsed time: 7.891s, Critical Path: 0.18s
INFO: 2 processes: 1 internal, 1 processwrapper-sandbox.
```

I build the modified example again (and it is not cached even thought it should be `1 processwrapper-sandbox`):

```
> bazel clean --expunge; bazel shutdown
> sudo rm -rf external /home/dockeruser/.cache/bazel /home/dockeruser/.cache/bazel_disk_cache/
> bazel build //non_cacheable_target/...
INFO: Starting clean (this may take a while). Consider using --async if the clean takes more than several minutes.
Extracting Bazel installation...
Starting local Bazel server and connecting to it...
INFO: Analyzed target //non_cacheable_target:output_files (8 packages loaded, 14 targets configured).
INFO: Found 1 target...
Target //non_cacheable_target:output_files up-to-date:
  bazel-bin/non_cacheable_target/output_files
INFO: Elapsed time: 7.388s, Critical Path: 0.15s
INFO: 2 processes: 1 internal, 1 processwrapper-sandbox.
```

This is the `execution_json_log_file` of the last `bazel build`:
```
{
  "commandArgs": ["/bin/bash", "-c", "echo Hola1 \u003e bazel-out/k8-dbg/bin/non_cacheable_target/output_files/file.txt"],
  "environmentVariables": [],
  "platform": {
    "properties": []
  },
  "inputs": [],
  "listedOutputs": ["bazel-out/k8-dbg/bin/non_cacheable_target/output_files"],
  "remotable": true,
  "cacheable": true,
  "timeoutMillis": "0",
  "progressMessage": "Action non_cacheable_target/output_files",
  "mnemonic": "Action",
  "actualOutputs": [{
    "path": "bazel-out/k8-dbg/bin/non_cacheable_target/output_files/file.txt",
    "digest": {
      "hash": "9bea9f5b70eb77cb7dc82b9515c68aaa91b7c0cb50122389713fe0c155fd4626",
      "sizeBytes": "6",
      "hashFunctionName": "SHA-256"
    },
    "isTool": false
  }],
  "runner": "processwrapper-sandbox",
  "remoteCacheHit": false,
  "status": "",
  "exitCode": 0,
  "remoteCacheable": true,
  "walltime": "0.005973s",
  "targetLabel": "//non_cacheable_target:output_files"
}
```

Bazel says that the target is `remoteCacheable` but it is never cached
and this is the bug.

### Which operating system are you running Bazel on?

Linux 4e32033cbff8 5.4.0-1109-azure #115~18.04.1-Ubuntu SMP Mon May 22 20:06:37 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

### What is the output of `bazel info release`?

INFO: Invocation ID: 84276203-854f-4133-80c3-44552407c4a0 release 6.4.0

### Have you found anything relevant by searching the web?

This bug might be related: https://github.com/bazelbuild/bazel/issues/17162

**Comment by tjgq** [comment] 2024-01-15 14:01
I can't reproduce it following your instructions (I'm not using Docker, which may or may not be related).

Mind trying with Bazel 7.0.0 and sharing the execution log for *both* invocations? In 7.0.0 there's a new `digest` field in the execution log (the lookup key for the remote or disk cache). This would tells us whether Bazel does indeed consider the actions to be distinct for the two invocations.

**Comment by srdjanstipic** [comment] 2024-01-15 16:32
I want to provide some context.

I am doing local development inside of docker image and
I am mounting a folder containing bazel project.
I use docker compose to start docker.

First invocation:
```
> bazel clean --expunge; bazel shutdown
> sudo rm -rf external /home/dockeruser/.cache/bazel /home/dockeruser/.cache/bazel_disk_cache/
> USE_BAZEL_VERSION=7.0.0 bazel build //non_cacheable_target/... \
    --execution_log_json_file out.txt --action_env=A=9


Extracting Bazel installation...
Starting local Bazel server and connecting to it...
INFO: Starting clean (this may take a while). Consider using --async if the clean takes more than several minutes.
Extracting Bazel installation...
Starting local Bazel server and connecting to it...
INFO: Analyzed target //non_cacheable_target:output_files (8 packages loaded, 14 targets configured).
INFO: Found 1 target...
Target //non_cacheable_target:output_files up-to-date:
  bazel-bin/non_cacheable_target/output_files
INFO: Elapsed time: 7.132s, Critical Path: 0.12s
INFO: 2 processes: 1 internal, 1 processwrapper-sandbox.
INFO: Build completed successfully, 2 total actions
```
Log:
```
> cat out.txt
{
  "commandArgs": ["/bin/bash", "-c", "echo Hola1 \u003e bazel-out/k8-dbg/bin/non_cacheable_target/output_files/file.txt"],
  "environmentVariables": [],
  "platform": {
    "properties": []
  },
  "inputs": [],
  "listedOutputs": ["bazel-out/k8-dbg/bin/non_cacheable_target/output_files"],
  "remotable": true,
  "cacheable": true,
  "timeoutMillis": "0",
  "mnemonic": "Action",
  "actualOutputs": [{
    "path": "bazel-out/k8-dbg/bin/non_cacheable_target/output_files/file.txt",
    "digest": {
      "hash": "9bea9f5b70eb77cb7dc82b9515c68aaa91b7c0cb50122389713fe0c155fd4626",
      "sizeBytes": "6",
      "hashFunctionName": "SHA-256"
    },
    "isTool": false
  }],
  "runner": "processwrapper-sandbox",
  "cacheHit": false,
  "status": "",
  "exitCode": 0,
  "remoteCacheable": true,
  "targetLabel": "//non_cacheable_target:output_files",
  "digest": {
    "hash": "08cb13fcf3049eea1914e9b8d15c94a3f63ae4586c4e7e6157a60414775c5833",
    "sizeBytes": "147",
    "hashFunctionName": "SHA256"
  },
  "metrics": {
    "totalTime": "0.006s",
    "executionWallTime": "0.006s",
    "inputBytes": "0",
    "inputFiles": "0",
    "memoryEstimateBytes": "0",
    "inputBytesLimit": "0",
    "inputFilesLimit": "0",
    "outputBytesLimit": "0",
    "outputFilesLimit": "0",
    "memoryBytesLimit": "0"
  }
}
```

Second invocation:
```
> bazel clean --expunge; bazel shutdown
> sudo rm -rf external /home/dockeruser/.cache/bazel /home/dockeruser/.cache/bazel_disk_cache/
> USE_BAZEL_VERSION=7.0.0 bazel build //non_cacheable_target/... \
    --execution_log_json_file out.txt --action_env=A=9


Extracting Bazel installation...
Starting local Bazel server and connecting to it...
INFO: Starting clean (this may take a while). Consider using --async if the clean takes more than several minutes.
Extracting Bazel installation...
Starting local Bazel server and connecting to it...
INFO: Analyzed target //non_cacheable_target:output_files (8 packages loaded, 14 targets configured).
INFO: Found 1 target...
Target //non_cacheable_target:output_files up-to-date:
  bazel-bin/non_cacheable_target/output_files
INFO: Elapsed time: 7.379s, Critical Path: 0.12s
INFO: 2 processes: 1 internal, 1 processwrapper-sandbox.
INFO: Build completed successfully, 2 total actions
```
Log:
```
{
  "commandArgs": ["/bin/bash", "-c", "echo Hola1 \u003e bazel-out/k8-dbg/bin/non_cacheable_target/output_files/file.txt"],
  "environmentVariables": [],
  "platform": {
    "properties": []
  },
  "inputs": [],
  "listedOutputs": ["bazel-out/k8-dbg/bin/non_cacheable_target/output_files"],
  "remotable": true,
  "cacheable": true,
  "timeoutMillis": "0",
  "mnemonic": "Action",
  "actualOutputs": [{
    "path": "bazel-out/k8-dbg/bin/non_cacheable_target/output_files/file.txt",
    "digest": {
      "hash": "9bea9f5b70eb77cb7dc82b9515c68aaa91b7c0cb50122389713fe0c155fd4626",
      "sizeBytes": "6",
      "hashFunctionName": "SHA-256"
    },
    "isTool": false
  }],
  "runner": "processwrapper-sandbox",
  "cacheHit": false,
  "status": "",
  "exitCode": 0,
  "remoteCacheable": true,
  "targetLabel": "//non_cacheable_target:output_files",
  "digest": {
    "hash": "08cb13fcf3049eea1914e9b8d15c94a3f63ae4586c4e7e6157a60414775c5833",
    "sizeBytes": "147",
    "hashFunctionName": "SHA256"
  },
  "metrics": {
    "totalTime": "0.006s",
    "executionWallTime": "0.006s",
    "inputBytes": "0",
    "inputFiles": "0",
    "memoryEstimateBytes": "0",
    "inputBytesLimit": "0",
    "inputFilesLimit": "0",
    "outputBytesLimit": "0",
    "outputFilesLimit": "0",
    "memoryBytesLimit": "0"
  }
}
```

**Comment by tjgq** [comment] 2024-01-15 17:13
Ok, we have established that the two builds are running the exact same action.

Can you share all of the Bazel flags you're using?

Which remote cache implementation are you using? Can you capture gRPC logs for the two invocations (`--experimental_remote_grpc_log=log.txt`) to see what Bazel is sending to and receiving from the remote cache server? The log will be in protocol buffer format; feel free to attach it to this issue as-is.

**Comment by srdjanstipic** [comment] 2024-01-15 21:45
> Which remote cache implementation are you using?

I am using build buddy.

> Can you capture gRPC logs for the two invocations

Here are the attached protobuf logs.
[log1.txt](https://github.com/bazelbuild/bazel/files/13943154/log1.txt)
[log2.txt](https://github.com/bazelbuild/bazel/files/13943155/log2.txt)

Effective command line (with some parameters omited):
```
bazel
build
//non_cacheable_target/...
--enable_bzlmod
--verbose_failures
--incompatible_enforce_config_setting_visibility
--incompatible_config_setting_private_default_visibility
--incompatible_struct_has_no_methods
--experimental_action_resource_set
--experimental_cc_shared_library
--experimental_cc_implementation_deps
--experimental_ui_max_stdouterr_bytes=10485760
--repo_env=BAZEL_DO_NOT_DETECT_CPP_TOOLCHAIN=1
--incompatible_enable_cc_toolchain_resolution
--compilation_mode=opt
--remote_cache=grpc://<REDACTED>
--bes_results_url=https://buildbuddy.<REDACTED>/invocation/
--bes_upload_mode=fully_async
--bes_backend=grpc://buildevents-internal<REDACTED>
--remote_download_outputs=minimal
--reuse_sandbox_directories
--remote_local_fallback
--remote_retries=1
--remote_timeout=7200
--grpc_keepalive_time=60s
--grpc_keepalive_timeout=300s
--remote_grpc_log=log1.txt
```

**Comment by tjgq** [comment] 2024-01-16 11:22
Human-readable versions of the logs
[log1human.txt](https://github.com/bazelbuild/bazel/files/13948980/log1human.txt)
[log2human.txt](https://github.com/bazelbuild/bazel/files/13948981/log2human.txt)

The logs look somewhat reasonable. Ignoring the initial `GetCapabilities` message:

First invocation:
- calls `GetActionResult` and gets `NOT_FOUND`
- calls `FindMissingBlobs` for 4 blobs (output file + ActionResult + Command + input merkle tree) and gets 3 missing (because the 4th is empty, and thus implicitly present)
- calls `ByteStream/Write` 3 times to upload the blobs
- calls `UploadActionResult` to upload the action result

Second invocation:
- calls `GetActionResult`, gets the previously uploaded action result (i.e., a cache hit)
- Does not download any blobs (because of `--remote_download_minimal`)

However, there are two things I don't understand:
- The `ActionResult` message has an `output_files` field, but a `declare_directory` should produce an `output_directory` field. (Did you capture logs for the `declare_file` rule by mistake?)
- The SHA-256 hash for the `bazel-out/k8-opt/bin/non_cacheable_target/output_files/file.txt` blob is `7fafa1e071d6a88a0b988b1d6a32782297523fa48b81ea0a1a3bdfbdea029f1e`, which does *not* correspond to the string `Hola1\n`; that would be `9bea9f5b70eb77cb7dc82b9515c68aaa91b7c0cb50122389713fe0c155fd4626`. (Did you change the string that gets printed relative to the repro instructions above?)

**Comment by srdjanstipic** [comment] 2024-01-16 11:32
I am using BuildBuddy: v2.12.43
I don't know if this is BuildBuddy bug.
I have open the issue in BuildBuddy here: https://github.com/buildbuddy-io/buildbuddy/issues/5727

**Comment by srdjanstipic** [comment] 2024-01-16 11:32
@tjgq I will generate a new logs for `decalre_directory()`.

**Comment by srdjanstipic** [comment] 2024-01-16 11:40
I am having this git diff:
```
diff --git a/non_cacheable_target/defs.bzl b/non_cacheable_target/defs.bzl
index 4307405fa72..c367696614a 100644
--- a/non_cacheable_target/defs.bzl
+++ b/non_cacheable_target/defs.bzl
@@ -1,10 +1,10 @@
 def _generate_output_files_rule_impl(ctx):
-    generated_output = ctx.actions.declare_file(ctx.attr.name + "/file.txt")
-    file_path = generated_output.path
+    generated_output = ctx.actions.declare_directory(ctx.attr.name)
+    file_path = generated_output.path + "/file.txt"

     ctx.actions.run_shell(
         outputs = [generated_output],
-        command = "echo Hola8 > " + file_path,
+        command = "echo Hola10 > " + file_path,
     )

     return [DefaultInfo(files = depset(direct = [generated_output]))]
```

Fist invocation:
```
> bazel clean --expunge; bazel shutdown
> sudo rm -rf external /home/dockeruser/.cache/bazel /home/dockeruser/.cache/bazel_disk_cache/
> USE_BAZEL_VERSION=7.0.0 bazel build  //non_cacheable_target/... --remote_grpc_log=log1.txt
INFO: Invocation ID: 7e8d923e-440b-4e2b-91ad-9f9211fa7ebc
INFO: Starting clean (this may take a while). Consider using --async if the clean takes more than several minutes.
Extracting Bazel installation...
Starting local Bazel server and connecting to it...
INFO: Analyzed target //non_cacheable_target:output_files (8 packages loaded, 14 targets configured).
INFO: Found 1 target...
Target //non_cacheable_target:output_files up-to-date:
  bazel-bin/non_cacheable_target/output_files
INFO: Elapsed time: 7.689s, Critical Path: 0.13s
INFO: 2 processes: 1 internal, 1 processwrapper-sandbox.
INFO: Build completed successfully, 2 total actions
```

Second invocation:
```
> bazel clean --expunge; bazel shutdown
> sudo rm -rf external /home/dockeruser/.cache/bazel /home/dockeruser/.cache/bazel_disk_cache/
> USE_BAZEL_VERSION=7.0.0 bazel build  //non_cacheable_target/... --remote_grpc_log=log2.txt
Extracting Bazel installation...
Starting local Bazel server and connecting to it...
INFO: Invocation ID: 96c51576-4c33-47b7-8a41-e5872e220737
INFO: Starting clean (this may take a while). Consider using --async if the clean takes more than several minutes.
Extracting Bazel installation...
Starting local Bazel server and connecting to it...
INFO: Analyzed target //non_cacheable_target:output_files (8 packages loaded, 14 targets configured).
INFO: Found 1 target...
Target //non_cacheable_target:output_files up-to-date:
  bazel-bin/non_cacheable_target/output_files
INFO: Elapsed time: 7.730s, Critical Path: 0.11s
INFO: 2 processes: 1 internal, 1 processwrapper-sandbox.
INFO: Build completed successfully, 2 total actions
```

Logs:

[log1.txt](https://github.com/bazelbuild/bazel/files/13949320/log1.txt)
[log2.txt](https://github.com/bazelbuild/bazel/files/13949321/log2.txt)

**Comment by tjgq** [comment] 2024-01-16 11:50
Ok, that looks more reasonable. In the log for the 2nd invocation, the `GetActionResult` request fails with:

```
status: {
  code   : 5
  message: "Combined size of all output directories exceeds maximum limit of 0 bytes"
}
```

Status code 5 is `NOT_FOUND`, so Bazel treats it as a cache miss and runs the action locally.

At this point, I'd like to hear from BuildBuddy on what the error message means; I don't see Bazel doing anything obviously wrong at the protocol level.

**Comment by srdjanstipic** [comment] 2024-01-16 12:01
@tjgq Thanks a lot for the help. :)

**Comment by srdjanstipic** [comment] 2024-01-16 12:24
I think that the issue is not in buildbuddy but in my BuildBarn settings.
I think that I didn't enable upload of `REv2 Directory objects` in BuildBarn.

Once I am able to find the correct setting, I will update this ticket.

P.S.
BuildBarn version:
```
    bbSchedulerImage: 'ghcr.io/buildbarn/bb-scheduler:20231212t221000z-fb20d59',
    bbFrontendImage: 'ghcr.io/buildbarn/bb-storage:20231205t110558z-8de3263',
    bbFrontendWithAuthImage: 'ghcr.io/buildbarn/bb-storage:20231205t110558z-8de3263',
    bbStorageImage: 'ghcr.io/buildbarn/bb-storage:20231205t110558z-8de3263',
    bbBrowserImage: 'ghcr.io/buildbarn/bb-browser:20231103t134227z-794e380',
    bbRunnerInstallerImage: 'ghcr.io/buildbarn/bb-runner-installer:20231212t221000z-fb20d59',
    bbWorkerImage: 'ghcr.io/buildbarn/bb-worker:20231212t221000z-fb20d59',
```

**Comment by EdSchouten** [comment] 2024-01-21 15:44
You likely have this config option set to zero, or not set at all:

https://github.com/buildbarn/bb-storage/blob/b14f4ae4a8572b23343a22deadaf9aab35ded750/pkg/proto/configuration/blobstore/blobstore.proto#L662

**Comment by tjgq** [comment] 2024-01-24 10:47
It looks like we've concluded that the problem is not in Bazel. Feel free to reopen if you disagree.

**Closed by tjgq** 2024-01-24 10:47 UTC
Labels: type: bug, team-Remote-Exec
