### ISSUE TITLE
Feature Request: Private Includes

### ISSUE THREAD

**Issue by adamhowardprice** [bazelbuild/bazel#2747] opened 2017-03-27 15:03 UTC
cc @dflems, plz fill in more info

**Comment by dflems** [comment] 2017-03-28 03:47
Basically, this is to request the same functionality provided by `includes`, but to add relative header search paths to the compiler flags *only* for the current library and not export the flag to any libraries that depend on it. Right now, this can be accomplished by manually adding `copts` like `-Ipath/too/foo`, but that's not exactly compiler independent, and the flag must be relative to the workspace root rather than the current `BUILD` file.

If this cannot be added for whatever reason, it would be nice to have a make substitution value that expands to the workspace-relative directory the current `BUILD` file is in so one could set `copts` like `-I$(HERE)/foo` instead of `-Ipath/to/foo`

**Comment by dflems** [comment] 2017-03-28 04:40
This actually appears to be a dupe of #2670 (I thought I had commented on this matter before, but couldn't find it in a search)

**Comment by steren** [comment] 2017-03-28 16:40
Let's mark it as duplicate of #2670 and close it

**Closed by steren** 2017-03-28 16:40 UTC
