### ISSUE TITLE
cc_library should support copts and cxxopts both

### ISSUE THREAD

**Issue by xiedeacc** [bazelbuild/bazel#18986] opened 2023-07-19 08:32 UTC
### Description of the feature request:

some project contain both .c and .cc file， like jemalloc，.c need a set of compile flags, but .cc need another, can cc_library support cxxopts option?

**Comment by Pavank1992** [comment] 2023-07-19 08:42
Hi @xiedeacc, Could you please elaborate the requested feature and its use case?

**Comment by thii** [comment] 2023-07-19 11:53
If this is accepted, please consider adding `conlyopts` too.

**Comment by xiedeacc** [comment] 2023-07-24 09:34
> Hi @xiedeacc, Could you please elaborate the requested feature and its use case?

what? I think request described clearly enough

**Comment by xiedeacc** [comment] 2023-07-29 07:50
I cannot understand why need more data

**Comment by fmeum** [comment] 2023-07-29 09:30
@xiedeacc This has been moved to the "untrusted" stage, which means that no more data is needed - instead, a team member will triage it at some point.

**Comment by snakethatlovesstaticlibs** [comment] 2024-10-19 19:02
This is possibly a dupe of https://github.com/bazelbuild/bazel/issues/22041

**Closed** 2024-10-19 19:42 UTC
Labels: type: feature request, P3, team-Rules-CPP
