### ISSUE TITLE
Nightly bazel builds should have a build label

### ISSUE THREAD

**Issue by bergsieker** [bazelbuild/bazel#6002] opened 2018-08-27 17:03 UTC
> ATTENTION! Please read and follow:
> - if this is a _question_ about how to build / test / query / deploy using Bazel, ask it on StackOverflow instead: https://stackoverflow.com/questions/tagged/bazel
> - if this is a _discussion starter_, send it to bazel-discuss@googlegroups.com
> - if this is a _bug_ or _feature request_, fill the form below as best as you can.

### Description of the problem / feature request:

Nightly bazel builds should have an appropriate build label, something like "nightly" or "bazel_nightly". Ideally this would apply to all "official" builds that are built and distributed via Bazel infrastructure. (I don't know if there are any such builds beyond the nightly builds.)

### Feature requests: what underlying problem are you trying to solve with this feature?

When collecting usage metrics of Bazel versions in RBE, it's useful to be able to separate "bazel nightly builds" from "private builds." It's not possible to do this via the build timestamp.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Download the nightly build, run "bazel version," see that the output does not include a build label.

### What operating system are you running Bazel on?

Linux, but this probably applies across all OSes.

**Comment by philwo** [comment] 2018-09-10 12:47
I agree that this would be very nice to have.

**Comment by ittaiz** [comment] 2019-03-20 06:33
duplicate of #4275?

**Comment by meisterT** [comment] 2020-05-15 13:14
closing as duplicate

**Closed by meisterT** 2020-05-15 13:14 UTC
Labels: P1, team-EngProd, type: feature request
