### ISSUE TITLE
Bad error messaging for toolchain target with toolchain attr pointing to invalid target

### ISSUE THREAD

**Issue by nlopezgi** [bazelbuild/bazel#7597] opened 2019-03-01 06:08 UTC
### Description of the problem / feature request:

I created a toolchain target pointing to an invalid toolchain. My build failed without providing any clear error messaging. It was super hard to find what was wrong in my toolchain target. It seems some better error messaging is required for this case, as all I get back is:
`WARNING: errors encountered while analyzing target '<some target>': it will not be built`

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

create a toolchain target. e.g., 
```
toolchain(
  name = "cc-toolchain",
  toolchain_type = "@bazel_tools//tools/cpp:toolchain_type",
  exec_compatible_with = [],
  target_compatible_with = [],
  toolchain = "<some invalid target>",
)
```

try to build any targets passing 
`--extra_toolchains=<some package>:cc-toolchain`
You can also include the `--toolchain_resolution_debug` flag (to see if any additional errors show up, I saw none)

### What operating system are you running Bazel on?

BuildKite CI - rbe_ubuntu1604 config
Sample error log:
https://buildkite.com/bazel/bazel-toolchains/builds/1326#18fd04f6-caba-4c36-8054-8bddebf055a2

In this specific error log, this was the problematic toolchain target:
```
toolchain(
  name = "cc-toolchain",
  toolchain_type = "@bazel_tools//tools/cpp:toolchain_type",
  exec_compatible_with = ["@bazel_tools//platforms:x86_64", "@bazel_tools//platforms:linux", "@bazel_tools//tools/cpp:clang"],
  target_compatible_with = ["@bazel_tools//platforms:linux", "@bazel_tools//platforms:x86_64"],
  toolchain = "@bazel_toolchains//configs/ubuntu16_04_clang/9.0.0/bazel_0.23.0:cc-compiler-k8",
)
```

Correct toolchain target that resulted in successful run (https://buildkite.com/bazel/bazel-toolchains/builds/1328#66f647b1-545a-430f-bb12-5a4878e4cddb):
```
toolchain(
  name = "cc-toolchain",
  toolchain_type = "@bazel_tools//tools/cpp:toolchain_type",
  exec_compatible_with = ["@bazel_tools//platforms:x86_64", "@bazel_tools//platforms:linux", "@bazel_tools//tools/cpp:clang"],
  target_compatible_with = ["@bazel_tools//platforms:linux", "@bazel_tools//platforms:x86_64"],
  toolchain = "@bazel_toolchains//configs/ubuntu16_04_clang/9.0.0/bazel_0.23.0/cc:cc-compiler-k8",
)
```

### What's the output of `bazel info release`?

Buildkite is currently using 0.22.0

**Comment by katre** [comment] 2019-03-01 15:54
This exact case is tested here: https://source.bazel.build/bazel/+/master:src/test/shell/bazel/toolchain_test.sh;l=717?q=toolchain_test.sh

In that test, we see the error message:
```
Target '//demo:use' depends on toolchain '//toolchain:does_not_exist', which cannot be found: no such target '//toolchain:does_not_exist': target 'does_not_exist' not declared in package 'toolchain'
```

So,:
1. Are you sure the invalid toolchain is the one being selected for your target
1. Are you sure the error you're seeing is due to toolchains and not something else in your target?

**Comment by nlopezgi** [comment] 2019-03-01 16:08
Thanks for the clarifications. 
I am not sure in this case the invalid toolchain was being selected. I am almost sure that once I fixed the invalid toolchain all targets started working. I'll double check the error messaging to see if I missed it and to double check if something else was wrong.

**Comment by nlopezgi** [comment] 2019-03-01 16:32
I double checked in https://github.com/bazelbuild/bazel-toolchains/pull/329.
In this case the invalid toolchain should have been selected and that is all that changes between a failed and building execution of CI. I did not see the error message you mentioned. Should be fairly easy for you to reproduce the error as this is occurring reliably on buildKite CI runs with the commits in the PR above.

**Comment by katre** [comment] 2019-03-01 17:00
Here's what I tried: https://gist.github.com/katre/5bc4049785d6e4c675c9cbe80473fd22

I see the error showing up correctly. I'm not sure what you are doing that is different.

**Comment by katre** [comment] 2019-03-05 15:58
@nlopezgi Any further ideas? I still can't reproduce in a test case.

**Comment by nlopezgi** [comment] 2019-03-05 16:38
I'll try to get a local repro case that shows the same behavior to see what I'm doing differently. Sorry I have not been able to get back yet to this.

**Comment by katre** [comment] 2019-07-08 17:42
Closing until you can find a reproducible test case.

**Closed by katre** 2019-07-08 17:42 UTC
Labels: P1, team-Configurability, type: bug
