### ISSUE TITLE
--test_env HEAPCHECK=normal not work while run bazel test

### ISSUE THREAD

**Issue by xiedeacc** [bazelbuild/bazel#17178] opened 2023-01-10 05:05 UTC
### Description of the bug:

I want to detect memory leak while run unit test use tcmalloc, I define a test:unit_test --test_env HEAPCHECK=normal in bazelrc, then I run bazel 
```
bazel test --config=unit_test //...
```
but output not contain tcmalloc memory detect info,  but manually run unit test binary, output contain these info
```
HEAPCHECK=normal ./bazel-bin/src/file_util_test
```

how to make bazel test output memory leak detect info?

### Which operating system are you running Bazel on?

ubuntu 22.04

### What is the output of `bazel info release`?

release 6.0.0

### Any other information, logs, or outputs that you want to share?

log

```
➜  /root/src/zenmen/ranking git:(master) ✗ HEAPCHECK=normal ./bazel-bin/src/file_util_test
WARNING: Perftools heap leak checker is active -- Performance may suffer
[==========] Running 3 tests from 1 test suite.
[----------] Global test environment set-up.
[----------] 3 tests from FileUtilTest
[ RUN      ] FileUtilTest.IsDirectory
[       OK ] FileUtilTest.IsDirectory (0 ms)
[ RUN      ] FileUtilTest.FileIsExists
[       OK ] FileUtilTest.FileIsExists (0 ms)
[ RUN      ] FileUtilTest.DoCompare
[       OK ] FileUtilTest.DoCompare (0 ms)
[----------] 3 tests from FileUtilTest (0 ms total)

[----------] Global test environment tear-down
[==========] 3 tests from 1 test suite ran. (0 ms total)
[  PASSED  ] 3 tests.
Have memory regions w/o callers: might report false leaks
No leaks found for check "_main_" (but no 100% guarantee that there aren't any): found 243 reachable heap objects of 85932 bytes
➜  /root/src/zenmen/ranking git:(master) ✗ bazel test --config=unit_test //...
INFO: Build option --test_env has changed, discarding analysis cache.
INFO: Analyzed 9 targets (0 packages loaded, 4772 targets configured).
INFO: Found 8 targets and 1 test target...
INFO: Elapsed time: 0.652s, Critical Path: 0.02s
INFO: 1 process: 1 internal.
INFO: Build completed successfully, 1 total action
//src:file_util_test                                            (cached) PASSED in 0.5s

Executed 0 out of 1 test: 1 test passes.
There were tests whose specified size is too big. Use the --test_verbose_timeout_warnings command line option to see which ones these are.

```

**Comment by sgowroji** [comment] 2023-01-10 07:27
Hello @xiedeacc, Can you provide complete steps and code example to reproduce the above issue. Thanks!

**Comment by xiedeacc** [comment] 2023-01-11 01:40
> Hello @xiedeacc, Can you provide complete steps and code example to reproduce the above issue. Thanks!

later I will provide a small demo project

**Comment by xiedeacc** [comment] 2023-01-14 09:28
@sgowroji here is demo, https://github.com/xiedeacc/bazel_demo
test command
```
bazel test --config=unit_test //...
HEAPCHECK=normal ./bazel-bin/src/file_util_test
```

here is log
```

➜  /root/src/cpp/bazel_demo git:(master) ✗ HEAPCHECK=normal ./bazel-bin/src/file_util_test
WARNING: Perftools heap leak checker is active -- Performance may suffer
[==========] Running 3 tests from 1 test suite.
[----------] Global test environment set-up.
[----------] 3 tests from FileUtilTest
[ RUN      ] FileUtilTest.IsDirectory
[       OK ] FileUtilTest.IsDirectory (0 ms)
[ RUN      ] FileUtilTest.FileIsExists
[       OK ] FileUtilTest.FileIsExists (0 ms)
[ RUN      ] FileUtilTest.DoCompare
[       OK ] FileUtilTest.DoCompare (0 ms)
[----------] 3 tests from FileUtilTest (0 ms total)

[----------] Global test environment tear-down
[==========] 3 tests from 1 test suite ran. (0 ms total)
[  PASSED  ] 3 tests.
Have memory regions w/o callers: might report false leaks
No leaks found for check "_main_" (but no 100% guarantee that there aren't any): found 243 reachable heap objects of 85932 bytes
➜  /root/src/cpp/bazel_demo git:(master) ✗ bazel test --config=unit_test //...
INFO: Build options --define and --test_env have changed, discarding analysis cache.
INFO: Analyzed 9 targets (0 packages loaded, 4772 targets configured).
INFO: Found 8 targets and 1 test target...
INFO: Elapsed time: 1.570s, Critical Path: 0.63s
INFO: 2 processes: 1 internal, 1 local.
INFO: Build completed successfully, 2 total actions
//src:file_util_test                                                     PASSED in 0.5s

Executed 1 out of 1 test: 1 test passes.
There were tests whose specified size is too big. Use the --test_verbose_timeout_warnings command line option to see which ones these are.
```

**Comment by xiedeacc** [comment] 2023-01-19 05:31
it seems must use bazel run, not bazel test

**Comment by fmeum** [comment] 2023-01-19 07:38
Have you tried running with `--test_output=streamed` and perhaps `-t-` to disable test caching? When I do that, I see the exact same output as when running the binary directly with the variable set.

There should never be a reason to `bazel run` a test. It does work reasonably well in a pinch, but using the flags I mentioned above is usually better.

**Comment by haxorz** [comment] 2023-01-19 22:38
@xiedeacc Thanks for providing all these details!

@fmeum Thanks for trying this out yourself. I had the same thought from reading the initial comment, so thanks for saving me time trying out the demo.

------

> [@xiedeacc] I want to detect memory leak while run unit test use tcmalloc, I define a test:unit_test --test_env HEAPCHECK=normal in bazelrc, then I run bazel... but output not contain tcmalloc memory detect info

I think you're misinterpreting Bazel's commandline output.

Bazel is telling you your test passed. Your test passed (read: didn't fail) because it *didn't* have a memory leak.

By default, Bazel doesn't print out the contents of test logs for tests that pass. You can control this with the `--test_output` option ([docs](https://bazel.build/docs/user-manual#test-output)). @fmeum's suggestion of `--test_output=streamed` is *one* way to see the test output for a successful test.

----

Since there's no bug here, I'm going to close this.

In the future, you could consider going through user support channels (https://bazel.build/help) before filing a GitHub issue.

**Closed by haxorz** 2023-01-19 22:38 UTC
Labels: type: bug, untriaged, team-Core
