### ISSUE TITLE
document the ability to get bazel version from a WORKSPACE macro

### ISSUE THREAD

**Issue by davidstanke** [bazelbuild/bazel#3819] opened 2017-09-26 15:38 UTC
In a workspace macro, native.bazel_version will return the version of the host Bazel.

This is undocumented. Can we add it?

**Comment by meisterT** [comment] 2020-05-11 17:12
Closing as dupe of https://github.com/bazelbuild/bazel/issues/8305

**Closed by meisterT** 2020-05-11 17:12 UTC
Labels: P2, type: documentation
