### ISSUE TITLE
Exception when trying to test in a folder named external

### ISSUE THREAD

**Issue by Utsav2** [bazelbuild/bazel#4448] opened 2018-01-13 00:32 UTC
> ATTENTION! Please read and follow:
> - if this is a _question_ about how to build / test / query / deploy using Bazel, ask it on StackOverflow instead: https://stackoverflow.com/questions/tagged/bazel
> - if this is a _discussion starter_, send it to bazel-discuss@googlegroups.com
> - if this is a _bug_ or _feature request_, fill the form below as best as you can.

### Description of the problem / feature request:

Exception from bazel

```
(16:22:50) FAILED: Build did NOT complete successfully (0 packages loaded)
java.lang.RuntimeException: Unrecoverable error while evaluating node 'external/...' (requested by nodes '[external/...] DETERMINE_TESTScom.google.devtools.build.lib.pkgcache.TestFilter@e17a1')
    at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:414)
    at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:352)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalArgumentException: No such attribute tags in maven_jar rule //external:antlr_antlr
    at com.google.devtools.build.lib.packages.AbstractAttributeMapper.getIndexWithTypeCheck(AbstractAttributeMapper.java:251)
    at com.google.devtools.build.lib.packages.AbstractAttributeMapper.get(AbstractAttributeMapper.java:58)
    at com.google.devtools.build.lib.packages.NonconfigurableAttributeMapper.get(NonconfigurableAttributeMapper.java:45)
    at com.google.devtools.build.lib.packages.TargetUtils.hasConstraint(TargetUtils.java:201)
    at com.google.devtools.build.lib.packages.TargetUtils.hasManualTag(TargetUtils.java:81)
    at com.google.devtools.build.lib.pkgcache.FilteringPolicies$FilterManual.shouldRetain(FilteringPolicies.java:73)
    at com.google.devtools.build.lib.pkgcache.FilteringPolicies$AndFilteringPolicy.shouldRetain(FilteringPolicies.java:105)
    at com.google.devtools.build.lib.skyframe.RecursivePackageProviderBackedTargetPatternResolver$3.call(RecursivePackageProviderBackedTargetPatternResolver.java:324)
    at com.google.devtools.build.lib.skyframe.RecursivePackageProviderBackedTargetPatternResolver$3.call(RecursivePackageProviderBackedTargetPatternResolver.java:309)
    at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:124)
    at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:57)
    at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:77)
    at com.google.common.util.concurrent.MoreExecutors$DirectExecutorService.execute(MoreExecutors.java:260)
    at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:134)
    at com.google.common.util.concurrent.AbstractListeningExecutorService.submit(AbstractListeningExecutorService.java:66)
    at com.google.devtools.build.lib.skyframe.RecursivePackageProviderBackedTargetPatternResolver.findTargetsBeneathDirectoryAsyncImpl(RecursivePackageProviderBackedTargetPatternResolver.java:308)
    at com.google.devtools.build.lib.skyframe.RecursivePackageProviderBackedTargetPatternResolver.findTargetsBeneathDirectory(RecursivePackageProviderBackedTargetPatternResolver.java:225)
    at com.google.devtools.build.lib.cmdline.TargetPattern$TargetsBelowDirectory.eval(TargetPattern.java:594)
    at com.google.devtools.build.lib.skyframe.TargetPatternFunction.compute(TargetPatternFunction.java:72)
    at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:340)
    ... 4 more
```

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

mkdir external
bazel test external/...

### What operating system are you running Bazel on?

Ubuntu

### What's the output of `bazel info release`?

development

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

built bazel at c69dbf8ed

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

https://github.com/bazelbuild/bazel.git
c69dbf8ed4893066d0474f87c0a8ddae00e4ee58
c69dbf8ed4893066d0474f87c0a8ddae00e4ee58

###  Have you found anything relevant by searching the web?

no

>
> Places to look:
> - StackOverflow: http://stackoverflow.com/questions/tagged/bazel
> - GitHub issues: https://github.com/bazelbuild/bazel/issues
> - email threads on https://groups.google.com/forum/#!forum/bazel-discuss

### Any other information, logs, or outputs that you want to share?

> Replace these lines with your answer.
>
> If the files are large, upload as attachment or provide link.

**Comment by jin** [comment] 2019-02-20 17:20
This is still reproducible with the latest Bazel.

**Comment by meisterT** [comment] 2020-05-15 13:30
Dupe of #4508

**Comment by janakdr** [comment] 2020-09-15 19:17
This is still an issue, easily reproducible.

**Comment by jin** [comment] 2020-09-16 01:38
Closing as dupe of #4508 - the "external" directory and package are special cased for external repositories, which means that BUILD targets in this package would have unexpected behavior. See the linked main issue for details.

**Closed by jin** 2020-09-16 01:38 UTC
Labels: team-Core, type: bug, untriaged

**Comment by janakdr** [comment] 2020-09-16 03:41
It's always a Bazel bug if we crash hard. That's never the desired state of
affairs: no user input should cause that.

**Comment by jin** [comment] 2020-09-16 03:47
I agree that it's a Bazel bug, but the root cause is #4508 and it's being worked on (cc @gyias)
