### ISSUE TITLE
Building bazel master prints warnings

### ISSUE THREAD

**Issue by werkt** [bazelbuild/bazel#6302] opened 2018-10-04 02:29 UTC
### Description of the problem / feature request:

Warnings are being printed on several build targets from a recent master:

```
INFO: From Building src/main/java/com/google/devtools/build/lib/causes/libcauses.jar (5 source files):
warning: unknown enum constant FlagIdentifier.NONE
  reason: class file for com.google.devtools.build.lib.syntax.SkylarkSemantics not found
warning: unknown enum constant FlagIdentifier.NONE
INFO: From Building src/main/java/com/google/devtools/build/lib/libconfig-matching-provider.jar (1 source file) and running annotation processors (AutoCodecProcessor):
warning: unknown enum constant FlagIdentifier.NONE
  reason: class file for com.google.devtools.build.lib.syntax.SkylarkSemantics not found
warning: unknown enum constant FlagIdentifier.NONE
warning: unknown enum constant FlagIdentifier.NONE
  reason: class file for com.google.devtools.build.lib.syntax.SkylarkSemantics not found
warning: unknown enum constant FlagIdentifier.NONE
warning: unknown enum constant FlagIdentifier.NONE
  reason: class file for com.google.devtools.build.lib.syntax.SkylarkSemantics not found
warning: unknown enum constant FlagIdentifier.NONE
warning: unknown enum constant FlagIdentifier.NONE
  reason: class file for com.google.devtools.build.lib.syntax.SkylarkSemantics not found
warning: unknown enum constant FlagIdentifier.NONE
```

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

`bazel build src:bazel` with an installed bazel 0.16.0 or later

### What operating system are you running Bazel on?

ubuntu 14.04

### What's the output of `bazel info release`?

0.17.2

@laurentlb

**Comment by cushon** [comment] 2018-10-04 02:49
This is a duplicate of #5985.

**Closed by cushon** 2018-10-04 02:49 UTC
