### ISSUE TITLE
incompatible_use_platforms_repo_for_constraints: Don't use constraints from @bazel_tools, use @platforms instead

### ISSUE THREAD

**Issue by hlopko** [bazelbuild/bazel#8622] opened 2019-06-13 08:48 UTC
Available since: 0.28
Tracking issue: https://github.com/bazelbuild/bazel/issues/6516

### Motivation

Bazel currently provides common constraints for [platforms](https://docs.bazel.build/versions/master/platforms.html) and [toolchains](https://docs.bazel.build/versions/master/toolchains.html) in `@bazel_tools//platforms`. We are migrating these out of the Bazel binary to a principled, standalone repository over at https://github.com/bazelbuild/platforms which can be released independently from the Bazel binary and which defines a process for adding more constraints.

### Migration

Ideally, declare an explicit dependency on https://github.com/bazelbuild/platforms, name the repository as `@platforms`, and use constraints from this repository. In cases where you cannot depend on https://github.com/bazelbuild/platforms (please tell us the reason in the comment), you can use the snapshot of https://github.com/bazelbuild/platforms in Bazel - Bazel implicitly provides this repository for Bazel's needs.

The actual migration in BUILD files is simple - use `@platforms//setting:value` instead of `@bazel_tools//platforms:value`:

```
sed 's$@bazel_tools//platforms:(linux|osx|windows|android|freebsd|ios|os)$@platforms//os:\1$' -E -i **/*
sed 's$@bazel_tools//platforms:(cpu|x86_32|x86_64|ppc|arm|aarch64|s390x)$@platforms//cpu:\1$' -i -E **/*
```

**Comment by dslomov** [comment] 2019-09-02 11:27
What is the status of this for 1.0?

**Comment by hlopko** [comment] 2019-09-02 11:36
Not flipping in time for 1.0

**Comment by ittaiz** [comment] 2020-02-15 20:06
maybe migration can be added to https://github.com/bazelbuild/buildtools/blob/master/WARNINGS.md ?

**Comment by katre** [comment] 2020-02-19 15:49
No one is currently working on this (it's, unfortunately, too low-priority and isn't currently hurting anything).

Once someone starts addressing the migration updating buildtools definitely makes sense.

**Comment by ittaiz** [comment] 2020-02-19 17:37
👍 @philwo its a bit annoying that the bazel flag bot adds a non actionable issue.
I like the concept a lot but I think the implementation needs to change

**Comment by alexeagle** [comment] 2020-10-25 22:26
This fails in rules_nodejs with
```
(02:17:05) ERROR: /workdir/toolchains/node/BUILD.bazel:146:1: no such target '@platforms//os:s390x': target 's390x' not declared in package 'os' defined by /var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/ec321eb2cc2d0f8f91b676b6d4c66c29/external/platforms/os/BUILD and referenced by '//toolchains/node:node_linux_s390x_toolchain'
```

is s390x missing from Bazel? Could that be easily added so we keep all our platforms?
(rules_nodejs does not want to take any dependencies)

**Comment by katre** [comment] 2020-10-26 13:13
s390x is a CPU, not an OS, so the constraint should be `@platforms/./cpu:s390x`.

**Comment by sventiffe** [comment] 2020-11-16 12:48
Per offline discussion, this change will not make it into 4.0. Please update the issue if this assumption is incorrect.

**Comment by martis42** [comment] 2022-02-23 03:54
This is labeled with `breaking-change-5.0`, which I interpret as the intention to flip this with Bazel 5.0.0.
The flag is however still inactive by default: 
https://github.com/bazelbuild/bazel/blob/5.0.0/src/main/java/com/google/devtools/build/lib/analysis/config/CoreOptions.java#L83

Please update the issue status.

**Comment by katre** [comment] 2022-02-28 14:58
We're not currently actively working on this. I'll raise it with the other platforms owners and we'll decide what to do, but it's clearly not going to happen in a near-term release.

All of the `breaking-change-X` labels are essentially obsolete at this point, by my understanding.

**Comment by limdor** [comment] 2022-03-02 13:35
> All of the breaking-change-X labels are essentially obsolete at this point, by my understanding.

If that is the case, what is the way the path to prepare a bazel upgrade migration? We had initially --all_incompatible_flags and this was removed as considered not the way to do it. Then we have bazelisk --migrate, but afaik this relies on the breaking-change-X label. Isn't bazelisk --migrate the oficial way?

**Comment by katre** [comment] 2022-03-02 15:50
I don't know what the current practices are. Please send an email to [bazel-dev](https://groups.google.com/g/bazel-dev) to discuss this, since it's a bigger question than this issue can manage.

**Comment by philwo** [comment] 2022-03-03 15:16
Bazelisk's `--migrate` no longer relies on GitHub labels: https://github.com/bazelbuild/bazelisk/pull/248

I would recommend to build / test your project with Bazel's rolling releases (in addition to the latest LTS, if you need to provide backwards compatibility) and also run a regular build / test with Bazelisk's `--migrate` feature to detect whether any existing `--incompatible_*` would break you.

In that case, feel free to provide feedback to the author of the flag and/or file a bug, so that the team is aware and can take this into account prior to flipping.

**Comment by gregestren** [comment] 2022-03-07 23:47
Can I remove all the migration labels to avoid this kind of confusion? Or do you still want them for historical record?

**Comment by gregestren** [comment] 2022-03-07 23:56
I see a lot of references to `@bazel_tools//platforms`: https://github.com/search?p=1&q=bazel_tools+platforms&type=Code, but only a small amount in @bazelbuild: https://github.com/bazelbuild/bazel/search?q=bazel_tools+platforms  (note that not every match is valid). For the latter it looks like it's mostly test mocks.

Even with the larger numbers, the migration is straightforward and there's a clear history of migrations in this bug with no reports of problems. This is something where the longer we persist it the more the legacy dependencies will entrench. 

Given all that, I think the right approach is to flip the flag and only backtrack if we encounter real problems (besides lots of projects having to migrate).

And vet that there are no remaining production references in @bazelbuild.

**Comment by aiuto** [comment] 2022-04-21 05:06
Quick analysis.  There are only about 10 instances of @bazel_tools//platforms in the code, so this should no be that hard to fix.

It actually looks like most of the work is done, so it might be as simple as flipping the flag, then eliminating the tests.

**Comment by aranguyen** [comment] 2022-09-06 15:58
The flag is now flipped but I'm reopening the issue for the actual flag removal before closing.

**Comment by meteorcloudy** [comment] 2022-09-21 08:58
Actually flipped in https://github.com/bazelbuild/bazel/commit/f137e640303486b52e39b4d4edee088f895b6b00 after previous temporary rollback for fixing downstream.

**Closed by meteorcloudy** 2022-09-21 08:58 UTC
Labels: P1, type: process, team-Configurability, incompatible-change, migration-ready, breaking-change-6.0

**Comment by schwehr** [comment] 2022-12-19 17:56
```
bazel run //checker:ee_stac_check
ERROR: /private/var/tmp/_bazel_schwehr/157f2da64734466b98b89a1fde104b92/external/bazel_tools/platforms/BUILD:29:6: in alias rule @bazel_tools//platforms:arm: Constraints from @bazel_tools//platforms have been removed. Please use constraints from @platforms repository embedded in Bazel, or preferably declare dependency on https://github.com/bazelbuild/platforms. See https://github.com/bazelbuild/bazel/issues/8622 for details.
ERROR: /private/var/tmp/_bazel_schwehr/157f2da64734466b98b89a1fde104b92/external/bazel_tools/platforms/BUILD:29:6: Analysis of target '@bazel_tools//platforms:arm' failed
ERROR: /Users/schwehr/earthengine-catalog/checker/BUILD:5:10: While resolving toolchains for target //checker:ee_stac_check: invalid registered toolchain '@go_sdk//:go_android_arm_cgo': 
ERROR: Analysis of target '//checker:ee_stac_check' failed; build aborted: 
```

Seeing this on brew and here https://github.com/google/earthengine-catalog/actions/runs/3733503946/jobs/6334381112

There are lots of places likely hitting the same/similar issue, so hopefully I'll figure this out and reply with directions on how to fix.

And sadly, I don't have issues enabled in https://github.com/google/earthengine-catalog, so more noise here.

**Comment by smolkaj** [comment] 2022-12-19 19:06
We are also seeing regression of the form reported by @schwehr with Bazel 6.0.
For people using Bazelisk, as a temporary workaround, you can add a file called `.bazelversion` with the contents
```
5.4.0
```
to the root of your repo, to keep using Bazel 5.

**Comment by smolkaj** [comment] 2022-12-19 19:22
It seems taht clearing the bazel cache fixes the issue.

**Comment by smolkaj** [comment] 2023-06-21 01:27
What's the status on this?
It seems that many teams are not upgrading to Bazel 6 since it breaks their build due to this issue.
My team included.

**Comment by aiuto** [comment] 2023-06-21 01:32
What is breaking in you build?  Is it because some rules still depend on bazel providing platforms via bazel_tools?

@aranguyen Do you have a list of what is breaking downstream?

**Comment by smolkaj** [comment] 2023-06-21 01:55
For one, it is braking protobuf's build, and we depend on protobuf: https://github.com/protocolbuffers/protobuf/issues/12509

**Comment by aranguyen** [comment] 2023-06-21 04:48
@aiuto All downstream projects that are tracked by our CI are all green. For other untracked projects, users need to migrate their code away from using contraints from bazel_tools. 

https://github.com/protocolbuffers/protobuf/issues/12509#issuecomment-1538358227 mentioned that https://github.com/protocolbuffers/protobuf is green and the error doesn't seem to be related to this flag. Have you tried updating your protobuf dependency to latest version which should have been migrated.

**Comment by aiuto** [comment] 2023-06-22 01:12
Now that the flag is in the graveyard. Can you delete tools/platforms/...
I'm not sure if there is a distinct issue for that, but it should happen before bazel 7.

**Comment by mgarbade** [comment] 2023-08-04 10:40
This is breaking my build. I was trying to compile an older version of MediaPipeUnityPlugin (which I was able to do successfully 2 years ago) and now I'm getting into a dependcy hell, apparantly due to the above change. 

What is the point of having bazel to fight against the dependency hell and then changing bazel itself throwing people into another dependency hell?

**Comment by aiuto** [comment] 2023-08-06 00:23
> What is the point of having bazel to fight against the dependency hell and then changing bazel itself throwing people into another dependency hell?

That's a good question, and I appreciate that this is difficult for some users. That is one of the reasons this has taken so long to roll out. This particular change is specifically to decouple bazel versions from the ability to build for new hardware. Let's say Bazel 6 had a set of CPUs built in based on what was made in 2022, and rules depend on that version of platforms. You want to use Bazel 6 for a 5 year long project, but new hardware keeps being developed. So you want to build the 3rd generation of your device with a new RISC-V variant. You don't want to have to update Bazel to pick up a new CPU name. Instead, you just want to pick up a new version of platforms.

**Comment by martis42** [comment] 2023-08-06 15:35
I am quite happy Bazel is performing breaking changes. Imho the workflow based on incompatibility flags is working well and giving each project the possibility to adjust in its own pace.
I am working a lot with C++ and would hate to see Bazel running into the same problem of ever growing complexity and need for best practices and linters just because nothing is ever deprecated.

**Comment by mgarbade** [comment] 2023-08-07 16:37
- If I grep for "bazel_tools//platforms" in my clean project. I does not find anything
- once I start building with bazel the above mentioned error (Constraints from @bazel_tools//platforms have been removed) appears
- checking with "grep" all files containing the string "bazel_tools//platforms" are in a newly created folder called ".cache" so it's been created during build process

I guess there is not point in find/replace anything inside these cache files. I have to make it earlier, I guess.

Can someone tell me how to fix this?

Are there some lines I should add to WORKSPACE to avoid these deprecated .cache files from being checked out?

**Comment by cleebp** [comment] 2024-02-04 21:52
Ran into this error (below) when building the tensorflow suite of packages with conda, if you hit this when trying to bazel build tflite-support specifically just make sure to use `bazel<6`. 

`ERROR: /home/user/.cache/bazel/_bazel_user/0e16d8232bb98776571a500cc0c256cb/external/bazel_tools/platforms/BUILD:64:6: Analysis of target '@bazel_tools//platforms:ios' failed`

**Comment by yjianpen** [comment] 2024-06-16 02:14
This breaks my repo: /private/var/tmp/_bazel_javieryu/aa8e4725bf9c05d07d76211f768b2ac1/external/local_execution_config_platform/BUILD:17:9: no such package '@@bazel_tools//platforms': BUILD file not found in directory 'platforms' of external repository @@bazel_tools.

Any idea to find where this error message come from?

**Comment by katre** [comment] 2024-06-17 12:20
From the error, looks like the problem is `local_execution_config_platform/BUILD`. I don't know what defines this, you'll need to check your WORKSPACE or MODULE.bazel file and see.
