### ISSUE TITLE
cc_library incorrectly errors out when given empty filegroup

### ISSUE THREAD

**Issue by konste** [bazelbuild/bazel#11424] opened 2020-05-17 04:19 UTC
### Description of the problem / feature request:

cc_library correctly accepts **srcs** attribute being **None** or set to empty list, as it can be headers only library. Unfortunately when given an empty filegroup it gives the same error as when it sees the file type it does not understand. 

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

[Here is the repro.](https://github.com/Bazel-snippets/cc_library_repro_1) It shows three cases when cc_library behaves correctly and one when it gives the incorrect error.

Why this error is bad: it does not only happen with the empty filegroup - this is just the easiest repro. When cc_library sources are generated by other rules the list of source files generated can be empty and it is fine. Unfortunately cc_library does not accept it and we have to resort to the ugly workaround of giving it meaningless header file instead of the empty list just to prevent it from stopping the build.

### What operating system are you running Bazel on?

Linux, Mac, Windows

### What's the output of `bazel info release`?

3.1.0

**Comment by aiuto** [comment] 2020-05-19 01:52
@konste Is this a problem for just cc_library, or for other libraries where you specify a filegroup for the srcs.

**Comment by konste** [comment] 2020-05-19 17:43
At this time we try to move C++ parts of the build to Bazel (although consider converting other used languages in the longer term). Therefore cc_library is our primary rule and we have not tried any other.

**Comment by oquenchil** [comment] 2020-08-25 09:38
This happens for every rule type not just C++. This is a duplicate of #3099.

**Closed by oquenchil** 2020-08-25 09:38 UTC
Labels: P3, duplicate, team-Rules-CPP, type: bug
