### ISSUE TITLE
Open-source path mapping shell test

### ISSUE THREAD

**Issue by gregestren** [bazelbuild/bazel#19525] opened 2023-09-14 19:10 UTC
See:

- https://github.com/bazelbuild/bazel/pull/18098#issuecomment-1726528187
- https://github.com/bazelbuild/bazel/pull/18098#discussion_r1202669750
- https://gist.github.com/gregestren/cfcdd55a7620b6c6ce3d5e40f633ce88

**Comment by aranguyen** [comment] 2023-09-21 19:15
https://github.com/bazelbuild/bazel/pull/18098#issuecomment-1726528187 explaining why our aquery-based test is not working

**Comment by gregestren** [comment] 2023-09-22 22:59
@fmeum given the above I'll plan to prioritize this issue?

**Comment by fmeum** [comment] 2023-09-23 21:16
@gregestren I identified the cause (a change to the Java action since I first submitted the PR) and also added a test on the PR.

I personally found a Java analysis test to be more ergonomic than an aquery-based shell test, especially for debugging. I will still add end-to-end integration tests after the PR is merged.

**Comment by gregestren** [comment] 2023-09-25 16:53
For reference, we already have the internal test code. It's just not integrated into CI: https://gist.github.com/gregestren/cfcdd55a7620b6c6ce3d5e40f633ce88

@fmeum are you suggesting both Java analysis tests and Java end-to-end tests? Or still shell end-to-end? How would you like to integrate https://gist.github.com/gregestren/cfcdd55a7620b6c6ce3d5e40f633ce88? I want to ensure we keep the coverage and I'm happy to do what's necessary for this coverage to be openly available.

**Comment by fmeum** [comment] 2023-09-25 19:48
@gregestren I think we should have both Java analysis tests as well as end-to-end tests in whatever setup is simpler (probably shell). 

When my PRs have been merged, we can make your existing shell test work in Bazel with very minor modifications. I will also add more Java analysis tests as part of the follow-up PRs.

**Comment by gregestren** [comment] 2023-09-25 20:04
Got it.

Right now I'm trying to export the existing shell test as follows:

1) If running with Bazel, fail as a no-op (no supported executors yet)
2) Else proceed with original logic.

It's not very interesting from a Bazel perspective. But at least it makes the code officially open , and ready to upgrade / merge into something better when Bazel executor support lands.

**Closed** 2023-10-03 22:45 UTC
Labels: type: bug, P1, team-Configurability

**Comment by gregestren** [comment] 2023-10-03 22:56
Note in https://github.com/bazelbuild/bazel/commit/2052573151790880ac2b21400eab97f702d3bf69 these tests are still disabled for Bazel. 

@aranguyen  suggested I try them after merging https://github.com/bazelbuild/bazel/pull/18098 but they still fail.

I didn't diagnose deeply. But @fmeum is that expected as executor support still isn't merged?

See:

- https://github.com/bazelbuild/bazel/blob/2052573151790880ac2b21400eab97f702d3bf69/src/test/shell/integration/config_stripped_outputs_test.sh#L98-L99
- https://github.com/bazelbuild/bazel/blob/2052573151790880ac2b21400eab97f702d3bf69/src/test/shell/integration/config_stripped_outputs_test.sh#L183-L184

**Comment by fmeum** [comment] 2023-10-04 11:33
As these tests are executing the commands, this is expected since there is no executor support (yet). I will run the tests with support enabled.

**Comment by fmeum** [comment] 2023-10-04 12:06
I enabled the tests in https://github.com/bazelbuild/bazel/pull/18155/commits/e4743cb415fe50f9eb5482b35e4109d8a5042c30 and they pass if the `Javac` action is running on a supported executor. Unfortunately the default is `multiplex-worker`, which isn't supported, hence the additional setup code.

**Comment by fmeum** [comment] 2023-10-04 12:27
Update: There seem to be some failures in the test that don't lead to the test itself failing. I will investigate this.

**Comment by gregestren** [comment] 2023-10-04 18:46
> I enabled the tests in [e4743cb](https://github.com/bazelbuild/bazel/commit/e4743cb415fe50f9eb5482b35e4109d8a5042c30) and they pass if the `Javac` action is running on a supported executor. Unfortunately the default is `multiplex-worker`, which isn't supported, hence the additional setup code.

And re:

https://github.com/bazelbuild/bazel/pull/18159#issuecomment-1516519843

>  Is support for multiplexed sandboxing something that has been considered for the Javac worker? 

Which defaults do you mean? I'm reading that `--strategy=Javac=worker` doesn't work with `--experimental_worker_multiplex`. Is `--strategy=Javac=worker`  also the default? If not, why are these settings needed to get the tests to pass?




Also https://github.com/bazelbuild/bazel/pull/19719#issuecomment-1746744623 for reference.

**Comment by fmeum** [comment] 2023-10-04 18:54
At least in Bazel an unsandboxed multiplex worker is the default strategy for Javac, but path mapping requires sandboxed execution. That's why, in the absence of support for a sandboxed multiplex worker, the next best mode is a sandboxed non-multiplexed worker.
