### ISSUE TITLE
Logo on homepage isn't showing up

### ISSUE THREAD

**Issue by kchodorow** [bazelbuild/bazel#1862] opened 2016-09-29 21:52 UTC
https://www.bazel.io/images/bazel-logo.png is giving permission denied!

**Comment by kchodorow** [comment] 2016-09-29 21:52
```
<Error>
<Code>AccessDenied</Code>
<Message>Access denied.</Message>
<Details>
Anonymous users does not have storage.objects.get access to object www.bazel.io/images/bazel-logo.png.
</Details>
</Error>
```

**Comment by damienmg** [comment] 2016-09-30 09:38
For future reference, the fix is the following command line: `gsutil -m acl ch -R -u AllUsers:R gs://www.bazel.io`

**Comment by damienmg** [comment] 2016-09-30 09:39
Ok this is now fixed, now looking at CI if I can figure out what when wrong

**Comment by damienmg** [comment] 2016-09-30 09:40
Nothing. we have this line in the ACL update: `No changes to gs://www.bazel.io/images/bazel-logo.png`. I'll try to follow up with the GCS people.

**Closed by damienmg** 2016-09-30 09:40 UTC
Labels: P1, type: bug

**Comment by damienmg** [comment] 2016-09-30 11:08
For future reference also the ci log: http://ci.bazel.io/view/Bazel%20bootstrap%20and%20maintenance/job/Bazel-Publish-Site/221/console

**Comment by damienmg** [comment] 2016-09-30 16:39
`gsutil defacl ch -u AllUsers:R gs://www.bazel.io` is setting the correct permission to the bucket so we should see it as intended :)
