### ISSUE TITLE
Wrong configuration transition settings used, if multiple configured targets are used as runfiles

### ISSUE THREAD

**Issue by FaBrand** [bazelbuild/bazel#10276] opened 2019-11-20 09:03 UTC
### Description of the problem:

Bazel seems to compile a dependency with the wrong configuration.
This happens if a binary depends on more then one different binaries, that implement transitions, through runfiles.

Scenario description:

Two binary rules that define a configuration transition for copts. (Referred to as `a` and `b`)

Two library rules defining the same file as srcs. `a` and `b` depend on and compile differently via transitions. (Referred to as `c_a` and `c_b`)

`c_a` Has header.h in hdrs, `c_b` doesn't.

One binary rule that depends on the executables of `a` and `b` as runfiles. (Referred to as d)
```
       /-> c_a  -> a \
code.c                 -- runfiles--> d
       \-> c_b  -> b /
```

```cpp
// code.c
#ifdef FLAGA
#include header.h
#endif

#ifdef FLAGB
// No Include
#endif
```

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

I set up a minimal example here: https://github.com/FaBrand/bazel_runfiles_transitions 

### What operating system are you running Bazel on?

Windows 10 Enterprise / WSL1 - Ubuntu

### What's the output of `bazel info release`?

release 1.1.0

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

```
https://github.com/FaBrand/bazel_runfiles_transitions.git
8822e7ba31477013d30cf3f1c12e0d3f2f20c112
8822e7ba31477013d30cf3f1c12e0d3f2f20c112
```

###  Have you found anything relevant by searching the web?

Unfortunately not

### Any other information, logs, or outputs that you want to share?

All information should be available here:

**Comment by katre** [comment] 2019-11-27 15:36
Assigning to greg to investigate how transitions should interact here.

**Comment by gregestren** [comment] 2019-11-28 00:13
I'm not sure I'm reproducing this (on Linux). In the `master` branch running works for me with both `variant_a` and `variant_b` listed in the runfiles.

On `without_runfiles`, it doesn't run (as I'd expect). On `only_one_dependency` it runs.

In every branch it builds without errors.

Can you clarify the explicit build errors you see?

**Comment by FaBrand** [comment] 2019-11-28 18:05
@gregestren I checked again, and with version `1.2.0` everything seems to work just fine.
Seems like i just missed the release of the newer version by a few hours when reporting 🙈 
So i guess it is not relevant anymore as it works in the latest release.

(with using bazelisk)
with `1.1.0` i get (as expected):
```
$ USE_BAZEL_VERSION=1.1.0 bazel run consumer
[...]
ERROR: /bazel_runfiles_transitions/BUILD:17:1: C++ compilation of rule '//:library_b' failed (Exit 1) gcc failed: error executing command /usr/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -MD -MF ... (remaining 17 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
code.c:3:10: fatal error: include/header.h: No such file or directory
 #include "include/header.h"
          ^~~~~~~~~~~~~~~~~~
compilation terminated.
Target //:consumer failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 10.482s, Critical Path: 0.21s
```

with `1.2.0`
```
$ USE_BAZEL_VERSION=1.2.0 bazel run consumer
Target //:consumer up-to-date:
  bazel-bin/consumer
INFO: Elapsed time: 5.390s, Critical Path: 0.07s
INFO: 0 processes.
INFO: Build completed successfully, 4 total actions
INFO: Build completed successfully, 4 total actions
Hello Bazel
Hello Bazel
```

**Closed** 2019-11-29 13:31 UTC
Labels: P2, team-Configurability, type: bug

**Comment by gregestren** [comment] 2019-12-02 21:23
No worries. Thanks for such a clear original report, and happy the fix was so easy! :)
