### ISSUE TITLE
[Fatal Error] :1:1: Content is not allowed in prolog

### ISSUE THREAD

**Issue by skyred** [bazelbuild/bazel#2446] opened 2017-01-29 14:03 UTC
### Description of the problem / feature request / question:

I was trying to do the Bazel Build Mobile Application Tutorial. I did't want to install Bazel and Java on my Ubuntu directly, because I have many dev projects on my laptop; so I built a [Docker image](https://github.com/INsReady/docker-bazel/blob/master/Dockerfile) to let Bazel and its dependency run in a container. But, I ran into a road blocker, when I run bazel built //android:android, I always got this error: 
````
ERROR: /usr/src/app/WORKSPACE:1:1: no such package '@androidsdk//': org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 1; Content is not allowed in prolog. and referenced by '//external:android/sdk'.
````

I thought there was something wrong with the Docker image, however, I can use the same image to run the Bazel [Hello World](https://bazel.build/versions/master/docs/getting-started.html) fine 

### If possible, provide a minimal example to reproduce the problem:

The docker command I used to run/build the example android app:

`docker run --rm -v "$PWD":/usr/src/app -v /media/skyred/OS/android-sdk:/android-sdk insready/bazel bazel build //android:android`

I ran the above command at my /path/examples/tutorial folder. From the above command, you can tell, that I mount my Android SDK at `/android-sdk` inside the container. 

My /path/examples/tutorial/WORKSPACE file looks like:

````
android_sdk_repository(
    name = "androidsdk",
    # Replace with path to Android SDK on your system
    path = "/android-sdk",
    # Replace with the Android SDK API level
    api_level = 25,
    # Replace with the version in sdk/build-tools/
    build_tools_version="25.0.2"
)
````

The /path/examples/tutorial/android/BUILD file looks exactly like the one provided by the example git master version

### Environment info
* Operating System:
Ubuntu 15.10

* Bazel version (output of `bazel info release`):
release 0.4.3

###  Have you found anything relevant by searching the web? (e.g. GitHub issues, email threads in the [bazel-discuss@googlegroups.com](https://groups.google.com/forum/#!forum/bazel-discuss) archive)

I searched for hours; couldn't find any report exact like mine. 

### Anything else, information or logs or outputs that would be helpful?
My `/media/skyred/OS/android-sdk` is at a Windows drive, while I was doing above tutorial on Ubuntu 15.10; not sure if this would make any difference.

**Comment by aj-michael** [comment] 2017-01-29 18:24
I suspect the issue is not in your Android build code but in the Bazel code for 'android_sdk_repository'. I believe you may have a file in your Android SDK that is confusing Bazel. can you try 'bazel build --verbose_failures @androidsdk//:files' and post the output here?

**Comment by skyred** [comment] 2017-01-30 11:21
I ran
`bazel build //android:android --verbose_failures @androidsdk//:files`

Below is the full return:

```
WARNING: Sandboxed execution is not supported on your system and thus hermeticity of actions cannot be guaranteed. See http://bazel.build/docs/bazel-user-manual.html#sandboxing for more information. You can turn off this warning via --ignore_unsupported_sandboxing.
[Fatal Error] :1:1: Content is not allowed in prolog.
ERROR: no such package '@androidsdk//': org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 1; Content is not allowed in prolog.
INFO: Elapsed time: 1.338s
```

**Comment by aj-michael** [comment] 2017-01-30 21:38
Ah, I was hoping that `--verbose_failures` would show more of the failure but alas.

I suspect that this is an encoding issue with files in your Android SDK due to the fact that it is on a Windows drive. Bazel Windows support is in the works, but we have not begun to attempt Windows Android builds.

http://stackoverflow.com/questions/2599919/java-parsing-xml-document-gives-content-not-allowed-in-prolog-error points towards an encoding problem.


Is there any reason in particular that you are using an Android SDK on a windows drive instead of a linux SDK? The Windows Android SDK contains binaries (dx, aapt, zipalign) that will not run on Linux, so even if you did not encounter this issue, the build would still fail.

**Comment by skyred** [comment] 2017-01-31 10:09
The only reason I put android-sdk folder on a Windows drive was that my Linux partition was out of space. The version of the android-sdk I was using is for Linux/Ubuntu.

Anyway, I copied the android-sdk to `/home/skyred/android-sdk`

Then, ran the command below at `workspace/examples/tutorial/` folder

```
docker run --name bazel -ti -v "$PWD":/usr/src/app -v /home/skyred/android-sdk:/android-sdk insready/bazel bazel build //android:android
```

The error I ran into was exactly same as https://github.com/bazelbuild/bazel/issues/2446#issuecomment-276038122

Shall I delete my android-sdk and re-download?

**Comment by aj-michael** [comment] 2017-01-31 16:14
Hmm, I should clarify, did you download the Windows Android SDK or the Linux Android SDK?

I would suggest redownloading. It's hard for me to diagnose this without access to your Android SDK.

**Comment by aj-michael** [comment] 2017-01-31 16:15
Oops, I see that you said that you downloaded the android SDK for Linux/Ubuntu. Hmmm.

I would still suggest redownloading, although I am less confident in my assessment now.

**Comment by skyred** [comment] 2017-02-01 04:01
1. I deleted my /android-sdk on my Linux drive, (but still using the /android-studio on my Windows drive) then re-downloaded /android-sdk onto my Linux drive.

2. re-run the build process above, then **it works!** 

3. I copied the /android-sdk back to my Windows drive

4. re-run the build process above, it works again.

So, I guess the root of the process was the file corruption on my old /android-sdk?

**Comment by aj-michael** [comment] 2017-02-02 17:20
@skyred I'm glad to hear that the problem is solved. I agree with your diagnosis. 👍 

There is possibly still a bug here, in that android_sdk_repository function should provide a more helpful error message, but I am going to close this issue since your problem is resolved.

**Closed by aj-michael** 2017-02-02 17:20 UTC
Labels: category: rules > android, Under investigation
