### ISSUE TITLE
Windows: crash when test is killed due to timeout

### ISSUE THREAD

**Issue by laszlocsomor** [bazelbuild/bazel#6853] opened 2018-12-06 12:01 UTC
### Description of the problem / feature request:

Bazel at HEAD crashes after killing a test that timed out.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

See https://github.com/laszlocsomor/projects/tree/04e4749626dd76b04227e30739050643aefba813/bazel/sleepy_test

Output:

```
C:\src\my-projects\bazel\sleepy_test>\src\bazel\bazel-bin\src\bazel.exe test //:sleepy_test --test_timeout=2
WARNING: The following rc files are no longer being read, please transfer their contents or import their path into one of the standard rc files:
C:\Users\laszlocsomor/.bazelrc
Starting local Bazel server and connecting to it...
INFO: Invocation ID: c19887f4-47da-442f-8bb8-b372872c2f04
INFO: Reading 'startup' options from c:\users\laszlocsomor\.bazelrc: --output_user_root=c:/_bazel
INFO: Options provided by the client:
  Inherited 'common' options: --isatty=1 --terminal_columns=120
INFO: Options provided by the client:
  Inherited 'build' options: --python_path=C:/python_27_amd64/files/python.exe
INFO: Reading rc options for 'test' from c:\users\laszlocsomor\.bazelrc:
  Inherited 'build' options: --verbose_failures --announce_rc
INFO: Analysed target //:sleepy_test (15 packages loaded, 592 targets configured).
INFO: Found 1 test target...
Target //:sleepy_test up-to-date:
  C:/_bazel/fs6jzbi6/execroot/__main__/bazel-out/x64_windows-fastbuild/bin/sleepy_test.exe
Internal error thrown during build. Printing stack trace: java.lang.RuntimeException: Unrecoverable error while evaluating node 'ActionLookupData{actionLookupKey=//:sleepy_test BuildConfigurationValue.Key[4c0e6114b54508c68c67c1f61b308baa] false, actionIndex=9}' (requested by nodes 'TestCompletionKey{configuredTargetKey=//:sleepy_test BuildConfigurationValue.Key[4c0e6114b54508c68c67c1f61b308baa] false, topLevelArtifactContext=com.google.devtools.build.lib.analysis.TopLevelArtifactContext@4ff827c3, exclusiveTesting=false}')
        at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:499)
        at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:368)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.RuntimeException: Unhandled exception running a local spawn
        at com.google.devtools.build.lib.exec.local.LocalSpawnRunner$SubprocessHandler.run(LocalSpawnRunner.java:195)
        at com.google.devtools.build.lib.exec.local.LocalSpawnRunner.exec(LocalSpawnRunner.java:152)
        at com.google.devtools.build.lib.exec.SpawnRunner.execAsync(SpawnRunner.java:218)
        at com.google.devtools.build.lib.exec.AbstractSpawnStrategy.exec(AbstractSpawnStrategy.java:107)
        at com.google.devtools.build.lib.exec.AbstractSpawnStrategy.exec(AbstractSpawnStrategy.java:76)
        at com.google.devtools.build.lib.exec.SpawnActionContextMaps$ProxySpawnActionContext.exec(SpawnActionContextMaps.java:369)
        at com.google.devtools.build.lib.exec.StandaloneTestStrategy.executeTestAttempt(StandaloneTestStrategy.java:343)
        at com.google.devtools.build.lib.exec.StandaloneTestStrategy.exec(StandaloneTestStrategy.java:143)
        at com.google.devtools.build.lib.rules.test.ExclusiveTestStrategy.exec(ExclusiveTestStrategy.java:47)
        at com.google.devtools.build.lib.analysis.test.TestRunnerAction.execute(TestRunnerAction.java:743)
        at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$ActionRunner.executeAction(SkyframeActionExecutor.java:818)
        at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$ActionRunner.call(SkyframeActionExecutor.java:792)
        at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$ActionRunner.call(SkyframeActionExecutor.java:726)
        at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
        at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.executeAction(SkyframeActionExecutor.java:488)
        at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.checkCacheAndExecuteIfNeeded(ActionExecutionFunction.java:557)
        at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.compute(ActionExecutionFunction.java:217)
        at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:422)
        ... 4 more
Caused by: java.lang.IllegalStateException: ERROR: src/main/native/windows/processes-jni.cc(639): nativeTerminate(4488): Access is denied.

        at com.google.devtools.build.lib.windows.WindowsSubprocess.exitValue(WindowsSubprocess.java:195)
        at com.google.devtools.build.lib.shell.FutureCommandResultImpl.waitForProcess(FutureCommandResultImpl.java:95)
        at com.google.devtools.build.lib.shell.FutureCommandResultImpl.get(FutureCommandResultImpl.java:42)
        at com.google.devtools.build.lib.shell.Command.execute(Command.java:248)
        at com.google.devtools.build.lib.exec.local.LocalSpawnRunner$SubprocessHandler.start(LocalSpawnRunner.java:337)
        at com.google.devtools.build.lib.exec.local.LocalSpawnRunner$SubprocessHandler.run(LocalSpawnRunner.java:186)
        ... 21 more

INFO: Elapsed time: 6.505s, Critical Path: 3.24s
INFO: 2 processes: 2 local.
FAILED: Build did NOT complete successfully
Internal error thrown during build. Printing stack trace: java.lang.RuntimeException: Unrecoverable error while evaluating node 'ActionLookupData{actionLookupKey=//:sleepy_test BuildConfigurationValue.Key[4c0e6114b54508c68c67c1f61b308baa] false, actionIndex=9}' (requested by nodes 'TestCompletionKey{configuredTargetKey=//:sleepy_test BuildConfigurationValue.Key[4c0e6114b54508c68c67c1f61b308baa] false, topLevelArtifactContext=com.google.devtools.build.lib.analysis.TopLevelArtifactContext@4ff827c3, exclusiveTesting=false}')
        at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:499)
        at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:368)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.RuntimeException: Unhandled exception running a local spawn
        at com.google.devtools.build.lib.exec.local.LocalSpawnRunner$SubprocessHandler.run(LocalSpawnRunner.java:195)
        at com.google.devtools.build.lib.exec.local.LocalSpawnRunner.exec(LocalSpawnRunner.java:152)
        at com.google.devtools.build.lib.exec.SpawnRunner.execAsync(SpawnRunner.java:218)
        at com.google.devtools.build.lib.exec.AbstractSpawnStrategy.exec(AbstractSpawnStrategy.java:107)
        at com.google.devtools.build.lib.exec.AbstractSpawnStrategy.exec(AbstractSpawnStrategy.java:76)
        at com.google.devtools.build.lib.exec.SpawnActionContextMaps$ProxySpawnActionContext.exec(SpawnActionContextMaps.java:369)
        at com.google.devtools.build.lib.exec.StandaloneTestStrategy.executeTestAttempt(StandaloneTestStrategy.java:343)
        at com.google.devtools.build.lib.exec.StandaloneTestStrategy.exec(StandaloneTestStrategy.java:143)
        at com.google.devtools.build.lib.rules.test.ExclusiveTestStrategy.exec(ExclusiveTestStrategy.java:47)
        at com.google.devtools.build.lib.analysis.test.TestRunnerAction.execute(TestRunnerAction.java:743)
        at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$ActionRunner.executeAction(SkyframeActionExecutor.java:818)
        at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$ActionRunner.call(SkyframeActionExecutor.java:792)
        at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$ActionRunner.call(SkyframeActionExecutor.java:726)
        at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
        at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.executeAction(SkyframeActionExecutor.java:488)
        at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.checkCacheAndExecuteIfNeeded(ActionExecutionFunction.java:557)
        at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.compute(ActionExecutionFunction.java:217)
        at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:422)
        ... 4 more
Caused by: java.lang.IllegalStateException: ERROR: src/main/native/windows/processes-jni.cc(639): nativeTerminate(4488): Access is denied.

        at com.google.devtools.build.lib.windows.WindowsSubprocess.exitValue(WindowsSubprocess.java:195)
        at com.google.devtools.build.lib.shell.FutureCommandResultImpl.waitForProcess(FutureCommandResultImpl.java:95)
        at com.google.devtools.build.lib.shell.FutureCommandResultImpl.get(FutureCommandResultImpl.java:42)
        at com.google.devtools.build.lib.shell.Command.execute(Command.java:248)
        at com.google.devtools.build.lib.exec.local.LocalSpawnRunner$SubprocessHandler.start(LocalSpawnRunner.java:337)
        at com.google.devtools.build.lib.exec.local.LocalSpawnRunner$SubprocessHandler.run(LocalSpawnRunner.java:186)
        ... 21 more
java.lang.RuntimeException: Unrecoverable error while evaluating node 'ActionLookupData{actionLookupKey=//:sleepy_test BuildConfigurationValue.Key[4c0e6114b54508c68c67c1f61b308baa] false, actionIndex=9}' (requested by nodes 'TestCompletionKey{configuredTargetKey=//:sleepy_test BuildConfigurationValue.Key[4c0e6114b54508c68c67c1f61b308baa] false, topLevelArtifactContext=com.google.devtools.build.lib.analysis.TopLevelArtifactContext@4ff827c3, exclusiveTesting=false}')
        at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:499)
        at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:368)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.RuntimeException: Unhandled exception running a local spawn
        at com.google.devtools.build.lib.exec.local.LocalSpawnRunner$SubprocessHandler.run(LocalSpawnRunner.java:195)
        at com.google.devtools.build.lib.exec.local.LocalSpawnRunner.exec(LocalSpawnRunner.java:152)
        at com.google.devtools.build.lib.exec.SpawnRunner.execAsync(SpawnRunner.java:218)
        at com.google.devtools.build.lib.exec.AbstractSpawnStrategy.exec(AbstractSpawnStrategy.java:107)
        at com.google.devtools.build.lib.exec.AbstractSpawnStrategy.exec(AbstractSpawnStrategy.java:76)
        at com.google.devtools.build.lib.exec.SpawnActionContextMaps$ProxySpawnActionContext.exec(SpawnActionContextMaps.java:369)
        at com.google.devtools.build.lib.exec.StandaloneTestStrategy.executeTestAttempt(StandaloneTestStrategy.java:343)
        at com.google.devtools.build.lib.exec.StandaloneTestStrategy.exec(StandaloneTestStrategy.java:143)
        at com.google.devtools.build.lib.rules.test.ExclusiveTestStrategy.exec(ExclusiveTestStrategy.java:47)
        at com.google.devtools.build.lib.analysis.test.TestRunnerAction.execute(TestRunnerAction.java:743)
        at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$ActionRunner.executeAction(SkyframeActionExecutor.java:818)
        at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$ActionRunner.call(SkyframeActionExecutor.java:792)
        at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$ActionRunner.call(SkyframeActionExecutor.java:726)
        at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
        at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.executeAction(SkyframeActionExecutor.java:488)
        at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.checkCacheAndExecuteIfNeeded(ActionExecutionFunction.java:557)
        at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.compute(ActionExecutionFunction.java:217)
        at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:422)
        ... 4 more
Caused by: java.lang.IllegalStateException: ERROR: src/main/native/windows/processes-jni.cc(639): nativeTerminate(4488): Access is denied.

        at com.google.devtools.build.lib.windows.WindowsSubprocess.exitValue(WindowsSubprocess.java:195)
        at com.google.devtools.build.lib.shell.FutureCommandResultImpl.waitForProcess(FutureCommandResultImpl.java:95)
        at com.google.devtools.build.lib.shell.FutureCommandResultImpl.get(FutureCommandResultImpl.java:42)
        at com.google.devtools.build.lib.shell.Command.execute(Command.java:248)
        at com.google.devtools.build.lib.exec.local.LocalSpawnRunner$SubprocessHandler.start(LocalSpawnRunner.java:337)
        at com.google.devtools.build.lib.exec.local.LocalSpawnRunner$SubprocessHandler.run(LocalSpawnRunner.java:186)
        ... 21 more
java.lang.RuntimeException: Unrecoverable error while evaluating node 'ActionLookupData{actionLookupKey=//:sleepy_test BuildConfigurationValue.Key[4c0e6114b54508c68c67c1f61b308baa] false, actionIndex=9}' (requested by nodes 'TestCompletionKey{configuredTargetKey=//:sleepy_test BuildConfigurationValue.Key[4c0e6114b54508c68c67c1f61b308baa] false, topLevelArtifactContext=com.google.devtools.build.lib.analysis.TopLevelArtifactContext@4ff827c3, exclusiveTesting=false}')
        at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:499)
        at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:368)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.RuntimeException: Unhandled exception running a local spawn
        at com.google.devtools.build.lib.exec.local.LocalSpawnRunner$SubprocessHandler.run(LocalSpawnRunner.java:195)
        at com.google.devtools.build.lib.exec.local.LocalSpawnRunner.exec(LocalSpawnRunner.java:152)
        at com.google.devtools.build.lib.exec.SpawnRunner.execAsync(SpawnRunner.java:218)
        at com.google.devtools.build.lib.exec.AbstractSpawnStrategy.exec(AbstractSpawnStrategy.java:107)
        at com.google.devtools.build.lib.exec.AbstractSpawnStrategy.exec(AbstractSpawnStrategy.java:76)
        at com.google.devtools.build.lib.exec.SpawnActionContextMaps$ProxySpawnActionContext.exec(SpawnActionContextMaps.java:369)
        at com.google.devtools.build.lib.exec.StandaloneTestStrategy.executeTestAttempt(StandaloneTestStrategy.java:343)
        at com.google.devtools.build.lib.exec.StandaloneTestStrategy.exec(StandaloneTestStrategy.java:143)
        at com.google.devtools.build.lib.rules.test.ExclusiveTestStrategy.exec(ExclusiveTestStrategy.java:47)
        at com.google.devtools.build.lib.analysis.test.TestRunnerAction.execute(TestRunnerAction.java:743)
        at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$ActionRunner.executeAction(SkyframeActionExecutor.java:818)
        at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$ActionRunner.call(SkyframeActionExecutor.java:792)
        at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$ActionRunner.call(SkyframeActionExecutor.java:726)
        at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
        at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.executeAction(SkyframeActionExecutor.java:488)
        at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.checkCacheAndExecuteIfNeeded(ActionExecutionFunction.java:557)
        at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.compute(ActionExecutionFunction.java:217)
        at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:422)
        ... 4 more
Caused by: java.lang.IllegalStateException: ERROR: src/main/native/windows/processes-jni.cc(639): nativeTerminate(4488): Access is denied.

        at com.google.devtools.build.lib.windows.WindowsSubprocess.exitValue(WindowsSubprocess.java:195)
        at com.google.devtools.build.lib.shell.FutureCommandResultImpl.waitForProcess(FutureCommandResultImpl.java:95)
        at com.google.devtools.build.lib.shell.FutureCommandResultImpl.get(FutureCommandResultImpl.java:42)
        at com.google.devtools.build.lib.shell.Command.execute(Command.java:248)
        at com.google.devtools.build.lib.exec.local.LocalSpawnRunner$SubprocessHandler.start(LocalSpawnRunner.java:337)
        at com.google.devtools.build.lib.exec.local.LocalSpawnRunner$SubprocessHandler.run(LocalSpawnRunner.java:186)
FAILED: Build did NOT complete successfully
```

### What operating system are you running Bazel on?

Windows 10

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

built my own Bazel at 5f8ac349b6ba5b6be3b4aef07719087c4d192088

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

```
$ git remote get-url origin ; git rev-parse master ; git rev-parse HEAD
https://bazel.googlesource.com/bazel
5f8ac349b6ba5b6be3b4aef07719087c4d192088
5f8ac349b6ba5b6be3b4aef07719087c4d192088
```

**Comment by laszlocsomor** [comment] 2018-12-06 12:20
Bisecting points at https://github.com/bazelbuild/bazel/commit/bdf7a6bdd51df38e0a38ac338404bef151b27cce as the culprit.

/cc @philwo

**Comment by philwo** [comment] 2018-12-06 19:34
Thanks for debugging and rolling back! :) I'll fix it in a rollforward PR.

The cause is relatively simple - due to us terminating the job object and setting `result->job_` to `INVALID_HANDLE_VALUE` in `nativeWaitFor` now, the `nativeTerminate` method that is [called explicitly](https://source.bazel.build/bazel/+/e1b99081813319da729eab84ec8f6d37a8e01572:src/main/java/com/google/devtools/build/lib/windows/WindowsSubprocess.java;drc=5f8ac349b6ba5b6be3b4aef07719087c4d192088;bpv=;bpt=1;l=159) only in the case of a timeout now believes that there was never a job object and that it has to call TerminateProcess instead.

This fails, because the process is obviously long gone at this point. I actually think this is also a race condition - if the process exits on its own just after we decided that it's a timeout, then the terminate method would have failed in the same way (because you can't call TerminateProcess on an already exited process). However that would be quite difficult to trigger ^^

Fixing this in a clean way is maybe not so simple - I think some refactoring is in order to make the flow more clear in the various cases. I'll send you a PR soon where I break this down into small steps so that you can follow along and then apply the real fix for this with a rollforward at the end.

**Comment by laszlocsomor** [comment] 2018-12-07 08:42
> Thanks for debugging and rolling back! :) I'll fix it in a rollforward PR.
> 
> The cause is relatively simple - due to us terminating the job object and setting `result->job_` to `INVALID_HANDLE_VALUE` in `nativeWaitFor` now, the `nativeTerminate` method that is [called explicitly](https://source.bazel.build/bazel/+/e1b99081813319da729eab84ec8f6d37a8e01572:src/main/java/com/google/devtools/build/lib/windows/WindowsSubprocess.java;drc=5f8ac349b6ba5b6be3b4aef07719087c4d192088;bpv=;bpt=1;l=159) only in the case of a timeout now believes that there was never a job object and that it has to call TerminateProcess instead.
> 
> This fails, because the process is obviously long gone at this point. I actually think this is also a race condition - if the process exits on its own just after we decided that it's a timeout, then the terminate method would have failed in the same way (because you can't call TerminateProcess on an already exited process). However that would be quite difficult to trigger ^^

Can we use `GetExitCodeProcess(handle, &exitcode); if (exitcode == STILL_ACTIVE) {...}`? That still has a race condition (what if the process exist just *after* GetExitCodeProcess returned) but at least the race window would be narrower than now.

> Fixing this in a clean way is maybe not so simple - I think some refactoring is in order to make the flow more clear in the various cases. I'll send you a PR soon where I break this down into small steps so that you can follow along and then apply the real fix for this with a rollforward at the end.

Thank you!

**Comment by ulfjack** [comment] 2019-01-28 19:46
Can this be closed now?

**Comment by philwo** [comment] 2019-01-28 19:47
I think so. In the unlikely case that it isn't, we will definitely observe it on CI and I can reopen this.

**Closed by philwo** 2019-01-28 19:47 UTC
Labels: P0, team-Windows, type: bug
