### ISSUE TITLE
External repositories with same name as a bind rule causes internal error

### ISSUE THREAD

**Issue by endobson** [bazelbuild/bazel#636] opened 2015-11-21 07:23 UTC
The error message.
```
ndobson@yggdrasil () ~/proj/racket/racket-grpc % bazel build @grpc//:grpc                                                                                                                                                             (1)
Unhandled exception thrown during build; message: Unrecoverable error while evaluating node 'WORKSPACE_FILE:[/Users/endobson/proj/racket/racket-grpc]/[WORKSPACE]' (requested by nodes 'PACKAGE:external')
INFO: Elapsed time: 0.074s.
java.lang.RuntimeException: Unrecoverable error while evaluating node 'WORKSPACE_FILE:[/Users/endobson/proj/racket/racket-grpc]/[WORKSPACE]' (requested by nodes 'PACKAGE:external')
        at com.google.devtools.build.skyframe.ParallelEvaluator$Evaluate.run(ParallelEvaluator.java:976)
        at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$2.run(AbstractQueueVisitor.java:495)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalStateException: Got a name conflict for new_git_repository rule //external:zlib, which can't happen: new_git_repository rule 'zlib' in package 'external' conflicts with existing bind rule
        at com.google.devtools.build.lib.packages.ExternalPackageBuilder.build(ExternalPackageBuilder.java:42)
        at com.google.devtools.build.lib.packages.Package$Builder.finishBuild(Package.java:1286)
        at com.google.devtools.build.lib.packages.Package$Builder.build(Package.java:1317)
        at com.google.devtools.build.lib.skyframe.WorkspaceFileFunction.compute(WorkspaceFileFunction.java:90)
        at com.google.devtools.build.skyframe.ParallelEvaluator$Evaluate.run(ParallelEvaluator.java:940)
        ... 4 more
Caused by: com.google.devtools.build.lib.packages.Package$NameConflictException: new_git_repository rule 'zlib' in package 'external' conflicts with existing bind rule
        at com.google.devtools.build.lib.packages.Package$Builder.nameConflict(Package.java:1423)
        at com.google.devtools.build.lib.packages.Package$Builder.checkForConflicts(Package.java:1351)
        at com.google.devtools.build.lib.packages.Package$Builder.addRule(Package.java:1202)
        at com.google.devtools.build.lib.packages.ExternalPackageBuilder.build(ExternalPackageBuilder.java:39)
        ... 8 more
```

WORKSPACE (important parts)
```
new_git_repository(
  name = "zlib",
  remote = "https://github.com/madler/zlib.git",
  commit = "50893291621658f355bc5b4d450a8d06a563053d",
  build_file = "BUILD.zlib",
)

bind(
  name = "zlib",
  actual = "@trunk//third_party/zlib",
)
```

**Comment by davidzchen** [comment] 2015-11-21 08:45
It seems that it is by-design that all names must be unique. However, we should display an error message and handle it gracefully and not dump a stack trace.

**Comment by kchodorow** [comment] 2015-11-30 17:03
This is a duplicate of #168, agreed that this should be handled more gracefully!

**Closed by kchodorow** 2015-11-30 17:03 UTC

**Comment by odellus** [comment] 2016-02-04 00:44
+1 for dumping a stack trace. It seems like you're handling it so gracefully I can see what the heck is happening.
