### ISSUE TITLE
BUILD and WORKSPACE files not captured by data

### ISSUE THREAD

**Issue by blackliner** [bazelbuild/bazel#10387] opened 2019-12-08 20:48 UTC
### Description of the problem:

I want to write some tests for the bazel-to-cmake project, and for that i need to grab some BUILD and WORKSPACE files as input testdata. I guess for obvious reasons, some special filenames are excluded, because usually no one needs them. But in this case i do, and not even naming them helps:
```
py_test(
    name = "test1",
    srcs = ["test1.py"],
    data = glob([
        "input/BUILD",
        "input/WORKSPACE",
        "expected/*",
    ]),
)
```
everything within the expected directory is caught and visible in *.runfiles.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

```
git clone git@github.com:blackliner/bazel-to-cmake.git
cd bazel-to-cmake
git reset --hard 8bfb4ced3e599f578f8c6e0a8c29966f8c6e5a9f
bazel test ... --test_output=all
```
see error message: `FileNotFoundError: [Errno 2] No such file or directory: 'input/'`

### What operating system are you running Bazel on?

Ubuntu 18.04@WSL2 on Windows10

### What's the output of `bazel info release`?

release 1.2.1

**Comment by jwnimmer-tri** [comment] 2019-12-09 21:31
Perhaps the problem is that _"glob does not match files in subpackages"_  -- https://docs.bazel.build/versions/master/be/functions.html#glob.  I assume `//mysomething/input` is being identified as a separate package, since it has a BUILD file.  Maybe rename to `input/BUILD.txt` or similar?

**Comment by blackliner** [comment] 2019-12-10 20:31
I used _BUILD for now and then those files are brought to the runfiles, where i rename them within the py_test script. But thats so ugly, i was hoping there is a clean solution for that...

**Comment by iirina** [comment] 2019-12-16 14:31
Hi @blackliner, I took a look at your fork and the test you're trying to write. Here's what I found was not exactly correct in your BUILD files.

- the use of `glob()` shouldn't include the `BUILD` and `WORKSPACE` files because in this case they are targets, not regular files.
-  the `input/BUILD` file must export `WORKSPACE` and have the proper package visibility so it can be read from `//test/test1`

Here's how I rewrote them:

**//test/test1/BUILD**
```
py_test(
    name = "test1",
    srcs = ["test1.py"],
    data = ["//test/test1/input:BUILD", "//test/test1/input:WORKSPACE",] 
             + glob(["expected/*"]),
)
```
**//test/test1/input/BUILD**
```
package(default_visibility = ["//visibility:public"])
exports_files(["WORKSPACE"])

cc_library(name = "main",
           srcs = ["main.h"])
```

The test still fails because you're trying to access `test/test1/input/test` which doesn't exist, in the sense that it's not a declared dependency on your test. How is this file created? Can you check it in and declare it as a data dependency which gets rewritten for every test?

**Comment by blackliner** [comment] 2019-12-16 19:42
Hi @iirina , thanks for your time. You say:

> the use of glob() shouldn't include the BUILD and WORKSPACE files because in this case they are targets, not regular files.

In this case, they are actually supposed to be treated as "regular files" for the test. The idea is to provide a test bazel-workspace for each test, run the python script, and assert on the output file. So everything within the input directory is not supposed to be part of the bazel environment, but rather be the input for the python script. Thats also why there are no `main` or `main.h` sourcefiles around, because that's not in focus here.

The idea is to work on the python script the TDD way.

**Comment by janakdr** [comment] 2020-05-12 14:01
Hi @blackliner , I'm not sure what the issue is that you're raising in your last update. Referring to a specific file in Bazel is generally done with the label syntax, so the label syntax @iirina suggested shouldn't be too strange: depending on a "foo.h" file could be specified similarly.

If you want the BUILD and WORKSPACE files to not be treated specially by Bazel, you'll need to rename them, since Bazel uses filenames to determine what files are special to it.

I'm closing for now since it seems like there's a reasonable way to do what you want, but please reopen if there is something I've missed.

**Closed by janakdr** 2020-05-12 14:01 UTC
Labels: more data needed, team-Core, untriaged

**Comment by blackliner** [comment] 2020-05-13 09:43
> If you want the BUILD and WORKSPACE files to not be treated specially by Bazel, you'll need to rename them, since Bazel uses filenames to determine what files are special to it.

That was what i wanted to find out: how to de-specialize those two files. If that is not possible, workarounds are always a thing of course.

Thanks, can be kept closed.
