### ISSUE TITLE
bazel sync gives unhelpful error message for custom repository rule

### ISSUE THREAD

**Issue by smukherj1** [bazelbuild/bazel#7946] opened 2019-04-04 19:08 UTC
### Description of the problem / feature request:

When running `bazel sync --experimental_repository_resolved_file=resolved.bzl` on bazelbuild/bazel-toolchains at commit 1cae40ee4802c786414efa1ecdcb9478ddfb0e7b I get the following error:
```
DEBUG: Rule 'io_bazel_rules_docker' indicated that a canonical reproducible form can be obtained by modifying arguments shallow_since = "1554389575 -0400"            
DEBUG: Rule 'io_bazel_rules_go' indicated that a canonical reproducible form can be obtained by modifying arguments shallow_since = "1553812085 -0400"                    
DEBUG: Rule 'com_google_protobuf' indicated that a canonical reproducible form can be obtained by modifying arguments shallow_since = "1551387314 -0800"                                        
DEBUG: Rule 'official_xenial' indicated that a canonical reproducible form can be obtained by modifying arguments digest = "sha256:d7d4f38deab29555ed2a9f13f4cb71f33e6f8788529512401d4e0638f2c3ba51"                                   
DEBUG: Rule 'official_jessie' indicated that a canonical reproducible form can be obtained by modifying arguments digest = "sha256:c8025c4656ab14225df172d5995afbe727830ef6b20d594e6278af15ec573f42"
DEBUG: /usr/local/google/home/suvanjan/.cache/bazel/_bazel_suvanjan/c24292d98ef42293e1b2a6a0fe4c4f08/external/bazel_toolchains/rules/rbe_repo.bzl:220:5: Bazel 0.24.1 is used in rbe_autoconfig.
DEBUG: /usr/local/google/home/suvanjan/.cache/bazel/_bazel_suvanjan/c24292d98ef42293e1b2a6a0fe4c4f08/external/bazel_toolchains/rules/rbe_repo.bzl:378:5: Pulling image l.gcr.io/google/rbe-ubuntu16-04@sha256:bc6a2ad47b24d01a73da315dd
288a560037c51a95cc77abb837b26fef1408798.                                                                                                                                                     
DEBUG: /usr/local/google/home/suvanjan/.cache/bazel/_bazel_suvanjan/c24292d98ef42293e1b2a6a0fe4c4f08/external/bazel_toolchains/rules/rbe_repo.bzl:381:5: Image pulled.                          
DEBUG: /usr/local/google/home/suvanjan/.cache/bazel/_bazel_suvanjan/c24292d98ef42293e1b2a6a0fe4c4f08/external/bazel_toolchains/rules/rbe_repo.bzl:556:5: Running container                                                             
DEBUG: Rule 'base_images_docker' indicated that a canonical reproducible form can be obtained by modifying arguments shallow_since = "1552504525 -0700"
ERROR: Traceback (most recent call last):                                                                                                                             
        File "/usr/local/google/home/suvanjan/.cache/bazel/_bazel_suvanjan/c24292d98ef42293e1b2a6a0fe4c4f08/external/bazel_toolchains/rules/rbe_repo.bzl", line 298       
                _run_and_extract(ctx, bazel_version = ctx.attr.baze..., <5 more arguments>)                                                                                                  
        File "/usr/local/google/home/suvanjan/.cache/bazel/_bazel_suvanjan/c24292d98ef42293e1b2a6a0fe4c4f08/external/bazel_toolchains/rules/rbe_repo.bzl", line 558, in _run_and_extract        
                _print_exec_results("run_and_extract", result, fail_on_e...)                                                                                                                                             
        File "/usr/local/google/home/suvanjan/.cache/bazel/_bazel_suvanjan/c24292d98ef42293e1b2a6a0fe4c4f08/external/bazel_toolchains/rules/rbe_repo.bzl", line 325, in _print_exec_results
                fail(((("Failed to run:" + prefix) + ...))
Failed to run:run_and_extract:+++ realpath /usr/local/google/home/suvanjan/.cache/bazel/_bazel_suvanjan/c24292d98ef42293e1b2a6a0fe4c4f08/external/bazel_toolchains/rules/cc-sample-project
++ docker run -d --env ABI_LIBC_VERSION=glibc_2.19 --env ABI_VERSION=clang --env BAZEL_COMPILER=clang --env BAZEL_HOST_SYSTEM=i686-unknown-linux-gnu --env BAZEL_TARGET_CPU=k8 --env BAZEL_TARGET_LIBC=glibc_2.19 --env BAZEL_TARGET_SY
STEM=x86_64-unknown-linux-gnu --env CC=clang --env CC_TOOLCHAIN_NAME=linux_gnu_x86 -v /usr/local/google/home/suvanjan/repos/github-bazelbuild/bazel-toolchains/rules/cc-sample-project:/rbe_autoconf/project_src -v /usr/local/google/h
ome/suvanjan/.cache/bazel/_bazel_suvanjan/c24292d98ef42293e1b2a6a0fe4c4f08/external/rbe_default_no_checked_in_confs/container:/rbe_autoconf/container l.gcr.io/google/rbe-ubuntu16-04@sha256:bc6a2ad47b24d01a73da315dd288a560037c51a95c
c77abb837b26fef1408798 /rbe_autoconf/container/run_in_container.sh
+ id=bf3f994542c998b4085e88e1b9645a8e644f575c61931ec36de0d7637e2289ec
+ docker wait bf3f994542c998b4085e88e1b9645a8e644f575c61931ec36de0d7637e2289ec
+ docker cp bf3f994542c998b4085e88e1b9645a8e644f575c61931ec36de0d7637e2289ec:/rbe_default_no_checked_in_confs_out.tar /usr/local/google/home/suvanjan/.cache/bazel/_bazel_suvanjan/c24292d98ef42293e1b2a6a0fe4c4f08/external/rbe_defaul
t_no_checked_in_confs/output.tar
Error: No such container:path: bf3f994542c998b4085e88e1b9645a8e644f575c61931ec36de0d7637e2289ec:/rbe_default_no_checked_in_confs_out.tar
```

This failure is due to [target](https://github.com/bazelbuild/bazel-toolchains/blob/1cae40ee4802c786414efa1ecdcb9478ddfb0e7b/WORKSPACE#L108). In trying to create a small reproducible test case, I created a separated repository and imported the rbe_autoconfig rule from bazel-toolchains and ran bazel sync in there. Surprisingly, the error I got there was different:
```
DEBUG: /usr/local/google/home/suvanjan/.cache/bazel/_bazel_suvanjan/17df4c30a8675c58b40dbf27ce88ecf3/external/bazel_toolchains/rules/rbe_repo.bzl:220:5: Bazel 0.24.1 is used in rbe_autoconfig.                                      
DEBUG: Rule 'io_bazel_rules_docker' indicated that a canonical reproducible form can be obtained by modifying arguments shallow_since = "1554389575 -0400"                                                                            
DEBUG: Rule 'io_bazel_rules_go' indicated that a canonical reproducible form can be obtained by modifying arguments shallow_since = "1553812085 -0400"                                                                                
DEBUG: Rule 'base_images_docker' indicated that a canonical reproducible form can be obtained by modifying arguments shallow_since = "1552504525 -0700"                                                                               
ERROR: RBE_AUTOCONF_ROOT env variable must be set for rbe_autoconfig to function properly when output_base is set
Loading: loading...
```

now, this error is emitted by the fail statement [here](https://github.com/bazelbuild/bazel-toolchains/blob/1cae40ee4802c786414efa1ecdcb9478ddfb0e7b/rules/rbe_repo.bzl#L244). When I set this variable, the error goes away both in my small test case as well as in bazelbuild/bazel-toolchains. So my question is, why wasn't this fail message executed when running bazel sync in bazelbuild/bazel-toolchains?

### Feature requests: what underlying problem are you trying to solve with this feature?

bazel sync should emit the message from the fail statement [here](https://github.com/bazelbuild/bazel-toolchains/blob/1cae40ee4802c786414efa1ecdcb9478ddfb0e7b/rules/rbe_repo.bzl#L244) regardless of whether it's running in the repository that defined the rbe_autoconfig rule or in a different repository that's importing the rbe_autoconfig rule.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.
Run
`bazel sync --experimental_repository_resolved_file=resolved.bzl` on bazelbuild/bazel-toolchains at commit 1cae40ee4802c786414efa1ecdcb9478ddfb0e7b

### What operating system are you running Bazel on?

gLinux

### What's the output of `bazel info release`?

release 0.24.1

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

N/A

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?
git@github.com:smukherj1/bazel-toolchains.git
1cae40ee4802c786414efa1ecdcb9478ddfb0e7b
1cae40ee4802c786414efa1ecdcb9478ddfb0e7b

###  Have you found anything relevant by searching the web?
No

### Any other information, logs, or outputs that you want to share?
N/A

**Comment by aehlig** [comment] 2019-04-11 13:37
> This failure is due to [target](https://github.com/bazelbuild/bazel-toolchains/blob/1cae40ee4802c786414efa1ecdcb9478ddfb0e7b/WORKSPACE#L108).  [...]
> bazel sync should emit the message from the fail statement [here](https://github.com/bazelbuild/bazel-toolchains/blob/1cae40ee4802c786414efa1ecdcb9478ddfb0e7b/rules/rbe_repo.bzl#L244) [...]

I fail to see why this even is expected; the quoted `fail` statement is under the condition `if ctx.attr.output_base:` and the quoted call (which is a marcro calling `_rbe_autoconfig`) calls the function with this attribute set to `None`. Since you did not provide any information on the "a small reproducible test case", I cannot tell, why the `output_base` attribute was set there.

Closing as working as intended. Please reopen with enough information to reproduce a case where the behavior is not the expected one.

**Closed by aehlig** 2019-04-11 13:37 UTC
Labels: P2, bad error messaging, team-ExternalDeps, type: bug
