### ISSUE TITLE
0.9.0 build error with io_bazel_rules_closure defs.bzl

### ISSUE THREAD

**Issue by gongwei** [bazelbuild/bazel#4337] opened 2017-12-20 20:42 UTC
Please provide the following information. The more we know about your system and use case, the more easily and likely we can help.
linux, use bazel to build tensorflow
### Description of the problem / feature request / question:

_If asking a question or requesting a feature, also tell us about the underlying problem you're trying to solve._

### Environment info
* Operating System:
Linux

* Bazel version (output of `bazel info release`):
0.9.0

* If `bazel info release` returns "development version" or "(@non-git)", please tell us what source tree you compiled Bazel from; git commit hash is appreciated (`git rev-parse HEAD`):

###  Have you found anything relevant by searching the web?
(e.g. [StackOverflow answers](http://stackoverflow.com/questions/tagged/bazel),
[GitHub issues](https://github.com/bazelbuild/bazel/issues),
email threads on the [`bazel-discuss`](https://groups.google.com/forum/#!forum/bazel-discuss) Google group)

### Anything else, information or logs or outputs that would be helpful?
(If they are large, please upload as attachment or provide link).
ERROR: /root/.cache/bazel/_bazel_root/9b01a0ef3440cb5c004aa6585481a46e/external/io_bazel_rules_closure/closure/private/defs.bzl:27:16: The function 'set' has been removed in favor of 'depset', please use the latter. You can temporarily refer to the old 'set' constructor from unexecuted code by using --incompatible_disallow_uncalled_set_constructor=false
ERROR: error loading package '': Extension file 'closure/private/defs.bzl' has errors
ERROR: error loading package '': Extension file 'closure/private/defs.bzl' has errors
INFO: Elapsed time: 1.553s
FAILED: Build did NOT complete successfully (0 packages loaded)

**Comment by davidstanke** [comment] 2017-12-20 22:26
Hi! This appears to be caused by the deprecation of 'set' in favor of 'depset.' Are you using the latest version of the closure rules? They have been updated with 'depset,' as of a few months ago: https://github.com/bazelbuild/rules_closure/commit/47f9d28b5d10f6fd1c706ab609a5e0acf9d97d3f#diff-e3311118d2f3fca5bf859c4f100153edL27

If you're using up-to-date closure rules and are still seeing this error, let us know. Thanks!

**Comment by davido** [comment] 2017-12-21 09:53
Yeah, I can confirm, that the latest released `rules_closure``version works as expected with Bazel 0.9.0.

**Comment by davidstanke** [comment] 2017-12-21 14:52
Thanks, @davido! @gongwei: i'm closing this issue; feel free to reopen if updating to the newest rules_closure doesn't fix it.

**Closed by davidstanke** 2017-12-21 14:52 UTC

**Comment by caiosuzuki** [comment] 2018-01-17 18:14
Hi, I am experiencing the same errors @gongwei had. I then got the defs.bzl file that @davidstanke linked and replaced mine.

I'm trying to build tensorflow with GPU support and I got the following error:

> ERROR: Skipping '//tensorflow/tools/pip_package:build_pip_package': error loading package 'tensorflow/tools/pip_package': Encountered error while reading extension file 'cuda/build_defs.bzl': no such package '@local_config_cuda//cuda': Traceback (most recent call last):
> 	File "/home/tracker/tensorflow/third_party/gpus/cuda_configure.bzl", line 958
> 		_create_cuda_repository(repository_ctx)
> 	File "/home/tracker/tensorflow/third_party/gpus/cuda_configure.bzl", line 915, in _create_cuda_repository
> 		_host_compiler_includes(repository_ctx, cc)
> 	File "/home/tracker/tensorflow/third_party/gpus/cuda_configure.bzl", line 144, in _host_compiler_includes
> 		get_cxx_inc_directories(repository_ctx, cc)
> 	File "/home/tracker/tensorflow/third_party/gpus/cuda_configure.bzl", line 119, in get_cxx_inc_directories
> 		set
> The function 'set' has been removed in favor of 'depset', please use the latter. You can temporarily refer to the old 'set' constructor from unexecuted code by using --incompatible_disallow_uncalled_set_constructor=false
> WARNING: Target pattern parsing failed.
> ERROR: error loading package 'tensorflow/tools/pip_package': Encountered error while reading extension file 'cuda/build_defs.bzl': no such package '@local_config_cuda//cuda': Traceback (most recent call last):
> 	File "/home/tracker/tensorflow/third_party/gpus/cuda_configure.bzl", line 958
> 		_create_cuda_repository(repository_ctx)
> 	File "/home/tracker/tensorflow/third_party/gpus/cuda_configure.bzl", line 915, in _create_cuda_repository
> 		_host_compiler_includes(repository_ctx, cc)
> 	File "/home/tracker/tensorflow/third_party/gpus/cuda_configure.bzl", line 144, in _host_compiler_includes
> 		get_cxx_inc_directories(repository_ctx, cc)
> 	File "/home/tracker/tensorflow/third_party/gpus/cuda_configure.bzl", line 119, in get_cxx_inc_directories
> 		set
> The function 'set' has been removed in favor of 'depset', please use the latter. You can temporarily refer to the old 'set' constructor from unexecuted code by using --incompatible_disallow_uncalled_set_constructor=false
> INFO: Elapsed time: 1.756s
> FAILED: Build did NOT complete successfully (0 packages loaded)
>     currently loading: tensorflow/tools/pip_package
>
