### ISSUE TITLE
Sometimes bazel crashes on BES timeouts when using --bes_upload_mode=fully_async

### ISSUE THREAD

**Issue by danny-kuminov** [bazelbuild/bazel#10164] opened 2019-11-04 22:12 UTC
### Description of the problem / feature request:

We have a CI script that runs multiple "bazel test" invocations sequentially, with --bes_upload_mode=fully_async (which, as a side effect, allows the invocation to complete before the BES upload is done). Sometimes, when the BES upload eventually times out, we see that the *next* invocation after the problematic one crashes with:

+ bazel test [redacted]
INFO: Invocation ID: [redacted]
WARNING: The background upload of the Build Event Protocol for the previous invocation failed with the following exception: 'io.grpc.StatusRuntimeException: DEADLINE_EXCEEDED: deadline exceeded after 59999912500ns'. Ignoring the failure and starting a new invocation...
INFO: Streaming Build Event Protocol to 'grpcs://buildeventservice.googleapis.com' with build_request_id: [redacted] and invocation_id: [redacted]
INFO: Streaming build results to: [redacted]
ERROR: bazel crash in async thread:
io.grpc.StatusRuntimeException: DEADLINE_EXCEEDED: deadline exceeded after 59999912500ns
	at io.grpc.Status.asRuntimeException(Status.java:523)
	at com.google.devtools.build.lib.remote.ByteStreamUploader$AsyncUpload$1.onClose(ByteStreamUploader.java:515)
	at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
	at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
	at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
	at io.grpc.internal.CensusStatsModule$StatsClientInterceptor$1$1.onClose(CensusStatsModule.java:700)
	at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
	at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
	at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
	at io.grpc.internal.CensusTracingModule$TracingClientInterceptor$1$1.onClose(CensusTracingModule.java:398)
	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:459)
	at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:63)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:546)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$600(ClientCallImpl.java:467)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:584)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

Server terminated abruptly (error code: 14, error message: 'Socket closed', log file: '/tmpfs/b/server/jvm.out')

### Feature requests: what underlying problem are you trying to solve with this feature?

N/A

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Unfortunately, there is no reproducible way (that I know of) to trigger this bug

### What operating system are you running Bazel on?

Linux

### What's the output of `bazel info release`?

Not exactly what you asked, but "bazel version" returns

Extracting Bazel installation...
Starting local Bazel server and connecting to it...
Build label: 0.28.0
Build target: bazel-out/k8-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Wed Jul 10 16:14:08 2019 (1562775248)
Build timestamp: 1562775248
Build timestamp as int: 1562775248

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

N/A

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

N/A

###  Have you found anything relevant by searching the web?

Nope (note that this flag is not documented)

**Comment by michaeledgar** [comment] 2020-04-26 20:52
I've written a Java integration test that induces DEADLINE_EXCEEDED for the ByteStreamUploader. I found that the exception is now correctly caught without crashing an async thread.

I noticed the age of the bug report, and looked further back in the source history. It looks like this issue was fixed by commit 142d7d4b9dcc069b9e3fa9359a5ef4b905ec309d authored by @buchgr.

I'll close this issue now, and submit the test this week to prevent regressions and simplify testing other remote caching failure scenarios.

**Closed by michaeledgar** 2020-04-26 20:52 UTC
Labels: team-Core
