### ISSUE TITLE
Linux sandbox prevents action childs from writing files

### ISSUE THREAD

**Issue by abergmeier-dsfishlabs** [bazelbuild/bazel#2612] opened 2017-03-01 13:54 UTC
### Description of the problem / feature request / question:

When spawning child processes from within actions, these child processes do not have the same write rights the action process has.
E.g. when trying to write a file it works fine from the action process but fails in a child process.

### If possible, provide a minimal example to reproduce the problem:

    import multiprocess
    def _write_file(name):
        with open(name, "w") as file: # Fails with read only filesystem error
            file.write("FOO")
    def main():
        files = ["a", "b"]
        with open("c", "w") as file:
            file.write("FOO")
        with multiprocess.Pool() as pool:
            pool.map(_write_file, files)
    if __name__ == "__main__":
	main()

### Environment info
* Operating System: Ubuntu 16.04.2
* Bazel version (output of `bazel info release`): 0.4.3

###  Have you found anything relevant by searching the web? (e.g. GitHub issues, email threads in the [bazel-discuss@googlegroups.com](https://groups.google.com/forum/#!forum/bazel-discuss) archive)
Nope

**Comment by abergmeier-dsfishlabs** [comment] 2017-03-01 16:40
There might be a similar problem with MacOS. Not sure yet.

**Comment by philwo** [comment] 2017-03-01 16:44
This is what I get when I try your program (had to make rename multiprocess to multiprocessing though) as a py_test with the latest released Bazel:

```
philwo@philwo:~/src/philwo$ bazel test :test
INFO: Reading 'startup' options from /usr/local/google/home/philwo/.bazelrc: --command_port=0 --watchfs
INFO: Analysed target //:test (0 packages loaded).
INFO: Found 1 test target...
FAIL: //:test (see /usr/local/google/home/philwo/.cache/bazel/_bazel_philwo/d3aa5f187115f489e28d3b5979a5fadd/execroot/philwo/bazel-out/local-fastbuild/testlogs/test/test.log)
INFO: From Testing //:test:
==================== Test output for //:test:
Traceback (most recent call last):
  File "/usr/local/google/home/philwo/.cache/bazel/_bazel_philwo/d3aa5f187115f489e28d3b5979a5fadd/bazel-sandbox/64c44634-e44b-4320-b0b4-bc70f2f9c441-0/execroot/philwo/bazel-out/local-fastbuild/bin/test.runfiles/__main__/test.py", line 15, in <module>
    main()
  File "/usr/local/google/home/philwo/.cache/bazel/_bazel_philwo/d3aa5f187115f489e28d3b5979a5fadd/bazel-sandbox/64c44634-e44b-4320-b0b4-bc70f2f9c441-0/execroot/philwo/bazel-out/local-fastbuild/bin/test.runfiles/__main__/test.py", line 11, in main
    pool = multiprocessing.Pool()
  File "/usr/lib/python2.7/multiprocessing/__init__.py", line 232, in Pool
    return Pool(processes, initializer, initargs, maxtasksperchild)
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 138, in __init__
    self._setup_queues()
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 234, in _setup_queues
    self._inqueue = SimpleQueue()
  File "/usr/lib/python2.7/multiprocessing/queues.py", line 352, in __init__
    self._rlock = Lock()
  File "/usr/lib/python2.7/multiprocessing/synchronize.py", line 147, in __init__
    SemLock.__init__(self, SEMAPHORE, 1, 1)
  File "/usr/lib/python2.7/multiprocessing/synchronize.py", line 75, in __init__
    sl = self._semlock = _multiprocessing.SemLock(kind, value, maxvalue)
OSError: [Errno 30] Read-only file system
Use --strategy=TestRunner=standalone to disable sandboxing for the failing actions.
================================================================================
Target //:test up-to-date:
  bazel-bin/test
INFO: Elapsed time: 0.252s, Critical Path: 0.12s
INFO: Build completed, 1 test FAILED, 2 total actions
//:test                                                                  FAILED in 1 out of 2 in 0.1s
    ERROR   .test

Executed 1 out of 1 test: 1 fails locally.
```

I think this is caused by multiprocessing not being able to create a semaphore. Maybe we have to mount tmpfs somewhere in the sandbox for that to work? Let me check...

**Comment by philwo** [comment] 2017-03-01 16:48
Yeah, you'll have to mount a tmpfs on /dev/shm (or /run/shm, depending on your system):

```
philwo@philwo:~/src/philwo$ bazel test --sandbox_tmpfs_path=/run/shm :test
INFO: Reading 'startup' options from /usr/local/google/home/philwo/.bazelrc: --command_port=0 --watchfs
INFO: Analysed target //:test (0 packages loaded).
INFO: Found 1 test target...
Target //:test up-to-date:
  bazel-bin/test
INFO: Elapsed time: 0.363s, Critical Path: 0.24s
INFO: Build completed successfully, 2 total actions

Executed 1 out of 1 test: 1 test passes.
```

I thought that we do this automatically by now, but it looks like I forgot to implement that. The flag will help you out though for now and you can safely put it into your ~/.bazelrc. :)

**Comment by philwo** [comment] 2017-03-01 16:49
Closing this for now, as it's essentially a duplicate of the earlier https://github.com/bazelbuild/bazel/issues/2056 - I'll make sure that this is fixed asap.

**Closed by philwo** 2017-03-01 16:49 UTC
Labels: category: sandboxing, P2, type: bug
