### ISSUE TITLE
Binary releases for arm?

### ISSUE THREAD

**Issue by ghost** [bazelbuild/bazel#6872] opened 2018-12-08 07:33 UTC
Can we get a bazel binary release for arm? Compiling from source takes ages and fails in many cases where memory is limited.

**Comment by aiuto** [comment] 2019-02-21 04:33
For any particular OS?

**Comment by philwo** [comment] 2019-07-29 12:15
Duplicate of https://github.com/bazelbuild/bazel/issues/8833, will track progress there.

**Closed by philwo** 2019-07-29 12:15 UTC
Labels: P4, type: feature request, xProduct
