### ISSUE TITLE
Bad UX: Stuck with corrupt bazel on Windows

### ISSUE THREAD

**Issue by alexeagle** [bazelbuild/bazel#4975] opened 2018-04-06 18:49 UTC
This has happened a couple of times, I'll add repro steps if I can figure out what triggers it.

Error looks like:
```
λ bazel info
DEBUG: corrupt installation: file 'C:\Users\ALEXEA~1\AppData\Local\Temp/_bazel_alexeagle/install/2050d0e869ddb9ea1fa4502f5f29fdd4/_embedded_binaries/build-runfiles.exe' missing. Dumping debug data.
DEBUG: p=(C:\Users\ALEXEA~1\AppData\Local\Temp/_bazel_alexeagle/install/2050d0e869ddb9ea1fa4502f5f29fdd4/_embedded_binaries/build-runfiles.exe), exists=0, isdir=0, canread=0
DEBUG: p=(C:\Users\ALEXEA~1\AppData\Local\Temp/_bazel_alexeagle/install/2050d0e869ddb9ea1fa4502f5f29fdd4/_embedded_binaries), exists=1, isdir=1, canread=0
DEBUG: p=(C:\Users\ALEXEA~1\AppData\Local\Temp/_bazel_alexeagle/install/2050d0e869ddb9ea1fa4502f5f29fdd4), exists=1, isdir=1, canread=0
DEBUG: p=(C:\Users\ALEXEA~1\AppData\Local\Temp/_bazel_alexeagle/install), exists=1, isdir=1, canread=0
DEBUG: p=(C:\Users\ALEXEA~1\AppData\Local\Temp/_bazel_alexeagle), exists=1, isdir=1, canread=0
DEBUG: p=(C:\Users\ALEXEA~1\AppData\Local\Temp), exists=1, isdir=1, canread=0
DEBUG: p=(C:\Users\ALEXEA~1\AppData\Local), exists=1, isdir=1, canread=0
DEBUG: p=(C:\Users\ALEXEA~1\AppData), exists=1, isdir=1, canread=0
DEBUG: p=(C:\Users\ALEXEA~1), exists=1, isdir=1, canread=0
DEBUG: p=(C:\Users), exists=1, isdir=1, canread=0
DEBUG: p=(C:\), exists=1, isdir=1, canread=0
Error: corrupt installation: file 'C:\Users\ALEXEA~1\AppData\Local\Temp/_bazel_alexeagle/install/2050d0e869ddb9ea1fa4502f5f29fdd4/_embedded_binaries/build-runfiles.exe' missing. Please remove 'C:\Users\ALEXEA~1\AppData\Local\Temp/_bazel_alexeagle/install/2050d0e869ddb9ea1fa4502f5f29fdd4' and try again.
```

I then use Windows Explorer to try to remove the directory as indicated by the error message. This fails because "the folder or a file in is in open in another program".
I suppose there is still a Bazel server process running in this install_base.

I open Windows Task Manager and try to find Bazel, but there is no search box, and I don't know whether to look for Bazel or Java.

I lookup how to find process and kill it on the command line, http://tweaks.com/windows/39559/kill-processes-from-command-prompt/
`Taskkill /PID 10756 /F`

Now I can delete the directory and run Bazel again.

It seems like when Bazel is corrupt, the server should shut down on its own?

**Comment by Reflexe** [comment] 2018-04-07 13:26
Isn't it a duplicate of #4775?

**Comment by laszlocsomor** [comment] 2018-04-09 06:58
Duplicate of #4775.
The error message is gone in Bazel 0.11.0

**Closed** 2018-04-09 07:04 UTC
Labels: platform: windows, type: bug
