### ISSUE TITLE
Recompiles dependants when changing copts

### ISSUE THREAD

**Issue by abergmeier-dsfishlabs** [bazelbuild/bazel#2483] opened 2017-02-03 14:06 UTC
### Description of the problem / feature request / question:

If I change `copts` of a `cc_library` `foo`, it also will recompile `bar` (if `bar` depends on `foo`), although `copts` are not propagated.

### Environment info
* Operating System: Windows 10
* Bazel version (output of `bazel info release`): 0.4.4

**Comment by lberki** [comment] 2017-02-10 12:19
I tried with the following setup and also with `b.cc` being a `cc_binary` and I'm changing `-DFOO=2` to a different integer:

a.cc:
```
int a() {
	return FOO;
}
```

b.cc:
```
int a();

int main(void) {
	return a();
}
```

BUILD:
```
cc_library(
    name = "a",
    srcs = ["a.cc"],
    copts = ["-DFOO=3"],
)

cc_library(
    name = "b",
    srcs = ["b.cc"],
    deps = [":a"],
)
```

and it seems to be working as expected. @meteorcloudy , can you try it on Windows? 

We may have some issues with the action cache. @ulfjack also fixed an embarrassing bug in action caching recently which may by in play, although that should only come in play when the Bazel server is restarted.

**Comment by meteorcloudy** [comment] 2017-02-10 12:50
Tried the example given by @lberki on Windows, everything is working expected.
`b.cc` didn't get recompiled, only `b.exe` got re-linked which is expected.

```
pcloudy@pcloudy0-w MSYS ~/workspace/test
$ bazel run :b -s
INFO: Found 1 target...
>>>>> # //:b [action 'Compiling b.cc']
cd C:/tmp/_bazel_pcloudy/b_VqltPL/execroot/test
  SET PATH=external/local_config_cc/wrapper/bin
  external/local_config_cc/wrapper/bin/msvc_cl.bat -m64 /D__inline__=__inline /DOS_WINDOWS=OS_WINDOWS /DCOMPILER_MSVC /DNOGDI /DNOMINMAX /DPRAGMA_SUPPORTED /D_WIN32_WINNT=0x0600 /D_CRT_SECURE_NO_DEPRECATE /D_CRT_SECURE_NO_WARNINGS /D_SILENCE_STDEXT_HASH_DEPRECATION_WARNINGS /D_USE_MATH_DEFINES /nologo /bigobj /Zm500 /J /Gy /GF /W3 /EHsc /wd4351 /wd4291 /wd4250 /wd4996 /DNDEBUG /Od -Xcompilation-mode=fastbuild /I. /Ibazel-out/vc_14_0_x64-fastbuild/genfiles /Iexternal/bazel_tools /Ibazel-out/vc_14_0_x64-fastbuild/genfiles/external/bazel_tools /Iexternal/bazel_tools/tools/cpp/gcc3 /DEPENDENCY_FILE bazel-out/vc_14_0_x64-fastbuild/bin/_objs/b/b.d /c b.cc /Fobazel-out/vc_14_0_x64-fastbuild/bin/_objs/b/b.o
>>>>> # //:a [action 'Compiling a.cc']
cd C:/tmp/_bazel_pcloudy/b_VqltPL/execroot/test
  SET PATH=external/local_config_cc/wrapper/bin
  external/local_config_cc/wrapper/bin/msvc_cl.bat -m64 /D__inline__=__inline /DOS_WINDOWS=OS_WINDOWS /DCOMPILER_MSVC /DNOGDI /DNOMINMAX /DPRAGMA_SUPPORTED /D_WIN32_WINNT=0x0600 /D_CRT_SECURE_NO_DEPRECATE /D_CRT_SECURE_NO_WARNINGS /D_SILENCE_STDEXT_HASH_DEPRECATION_WARNINGS /D_USE_MATH_DEFINES /nologo /bigobj /Zm500 /J /Gy /GF /W3 /EHsc /wd4351 /wd4291 /wd4250 /wd4996 /DNDEBUG /Od -Xcompilation-mode=fastbuild /I. /Ibazel-out/vc_14_0_x64-fastbuild/genfiles /Iexternal/bazel_tools /Ibazel-out/vc_14_0_x64-fastbuild/genfiles/external/bazel_tools /Iexternal/bazel_tools/tools/cpp/gcc3 /DEPENDENCY_FILE bazel-out/vc_14_0_x64-fastbuild/bin/_objs/a/a.d /c a.cc /Fobazel-out/vc_14_0_x64-fastbuild/bin/_objs/a/a.o -DFOO=3
>>>>> # //:a [action 'Linking liba.a']
cd C:/tmp/_bazel_pcloudy/b_VqltPL/execroot/test
  SET PATH=external/local_config_cc/wrapper/bin
  external/local_config_cc/wrapper/bin/msvc_link.bat @bazel-out/vc_14_0_x64-fastbuild/bin/liba.a-2.params
>>>>> # //:b [action 'Linking b.exe']
cd C:/tmp/_bazel_pcloudy/b_VqltPL/execroot/test
  SET PATH=external/local_config_cc/wrapper/bin
  external/local_config_cc/wrapper/bin/msvc_cl.bat /OUT:bazel-out/vc_14_0_x64-fastbuild/bin/b.exe -m64 -Wl,-S -Xcompilation-mode=fastbuild -Wl,@bazel-out/vc_14_0_x64-fastbuild/bin/b.exe-2.params
Target //:b up-to-date:
  C:/tmp/_bazel_pcloudy/b_VqltPL/execroot/test/bazel-out/vc_14_0_x64-fastbuild/bin/b.exe
INFO: Elapsed time: 5.995s, Critical Path: 0.97s

INFO: Running command line: C:/tmp/_bazel_pcloudy/b_VqltPL/execroot/test/bazel-out/vc_14_0_x64-fastbuild/bin/b.exe
3

pcloudy@pcloudy0-w MSYS ~/workspace/test
$ bazel run :b -s
INFO: Found 1 target...
>>>>> # //:a [action 'Compiling a.cc']
cd C:/tmp/_bazel_pcloudy/b_VqltPL/execroot/test
  SET PATH=external/local_config_cc/wrapper/bin
  external/local_config_cc/wrapper/bin/msvc_cl.bat -m64 /D__inline__=__inline /DOS_WINDOWS=OS_WINDOWS /DCOMPILER_MSVC /DNOGDI /DNOMINMAX /DPRAGMA_SUPPORTED /D_WIN32_WINNT=0x0600 /D_CRT_SECURE_NO_DEPRECATE /D_CRT_SECURE_NO_WARNINGS /D_SILENCE_STDEXT_HASH_DEPRECATION_WARNINGS /D_USE_MATH_DEFINES /nologo /bigobj /Zm500 /J /Gy /GF /W3 /EHsc /wd4351 /wd4291 /wd4250 /wd4996 /DNDEBUG /Od -Xcompilation-mode=fastbuild /I. /Ibazel-out/vc_14_0_x64-fastbuild/genfiles /Iexternal/bazel_tools /Ibazel-out/vc_14_0_x64-fastbuild/genfiles/external/bazel_tools /Iexternal/bazel_tools/tools/cpp/gcc3 /DEPENDENCY_FILE bazel-out/vc_14_0_x64-fastbuild/bin/_objs/a/a.d /c a.cc /Fobazel-out/vc_14_0_x64-fastbuild/bin/_objs/a/a.o -DFOO=2
>>>>> # //:a [action 'Linking liba.a']
cd C:/tmp/_bazel_pcloudy/b_VqltPL/execroot/test
  SET PATH=external/local_config_cc/wrapper/bin
  external/local_config_cc/wrapper/bin/msvc_link.bat @bazel-out/vc_14_0_x64-fastbuild/bin/liba.a-2.params
>>>>> # //:b [action 'Linking b.exe']
cd C:/tmp/_bazel_pcloudy/b_VqltPL/execroot/test
  SET PATH=external/local_config_cc/wrapper/bin
  external/local_config_cc/wrapper/bin/msvc_cl.bat /OUT:bazel-out/vc_14_0_x64-fastbuild/bin/b.exe -m64 -Wl,-S -Xcompilation-mode=fastbuild -Wl,@bazel-out/vc_14_0_x64-fastbuild/bin/b.exe-2.params
Target //:b up-to-date:
  C:/tmp/_bazel_pcloudy/b_VqltPL/execroot/test/bazel-out/vc_14_0_x64-fastbuild/bin/b.exe
INFO: Elapsed time: 1.506s, Critical Path: 0.89s

INFO: Running command line: C:/tmp/_bazel_pcloudy/b_VqltPL/execroot/test/bazel-out/vc_14_0_x64-fastbuild/bin/b.exe
2

```

**Comment by ulfjack** [comment] 2017-02-10 14:27
The action cache issue also affects re-analysis, not just server restart. Note that it is only reproducible if you have header files in the cc_library. E.g.:

    cc_library(name = "foo", srcs = ["foo.cc", "foo.h", "bar.h"])

**Comment by lberki** [comment] 2017-02-10 16:15
Erm, my bad. I actually had some headers in the `cc_library`, but only when I couldn't reproduce it without them.

**Comment by ulfjack** [comment] 2017-02-10 16:18
There's a good chance this is a dupe of #2490.

**Comment by ulfjack** [comment] 2017-09-25 09:17
Closing as a likely dupe. Let me know if this still happens.

**Closed by ulfjack** 2017-09-25 09:17 UTC
Labels: category: rules > C++, P2, type: bug
