### ISSUE TITLE
Cross compilation: explicitly exclude package / rule from a toolchain

### ISSUE THREAD

**Issue by guibou** [bazelbuild/bazel#6043] opened 2018-08-30 20:39 UTC
### Description of the problem / feature request:

The rules in my repository can be built by a few of the `--compiler` / `--cpu` combinations available. For example:

- Most of my "desktop" programs can accept all the `--compiler` (e.g. `clang`, `gcc`), but only the `--cpu` `default`.
- Some rules are only compatibles with some `--cpu` / `--compiler` tuples. For example, I have rules which only works for `arm32bit` / `gcc`.

I cannot use `bazel build //...` because it will try to use the default `--compiler` / `--cpu` to build all my targets. I must explicitly list all target I want to build.

The only workaround I'm aware of is to, for each rule, add a `tags = ["manual"]` conditionally using a `select` query. That's painful.

Could you add a way to, per package, tags rules by the list of toolchain (i.e. the `--cpu` / `--compiler`) for which these rules can be built.

### Feature requests: what underlying problem are you trying to solve with this feature?

I'm trying to simplify my workflow which involves a lot of boilerplate external scripts which call bazel and a lot of boilerplate inside. Mostly, I have a continuous integration process which fails to test a few rules each time I forget to list these new rules explicitly in the build process.

### What operating system are you running Bazel on?

Linux.

### What's the output of `bazel info release`?

I'm using a patched bazel 0.15, but I have seen nothing on the release note of 0.16 or 0.17rc related to this issue.

**Comment by gregestren** [comment] 2018-10-04 17:52
This should be addressed pretty effectively by the [configurability roadmap](https://bazel.build/roadmaps/configuration.html) in the sections on flagless multiplatform builds.

We also have precedent for [skipping](https://groups.google.com/forum/#!msg/bazel-discuss/U6sFbPWiXGM/_hjddzwdFwAJ) targets under `//...` that don't match the current platform.

**Comment by guibou** [comment] 2018-10-05 13:45
@gregestren I saw the configurability roadmap and I'm looking forward for this `plateforms` attribute. Thank you.

**Comment by aiuto** [comment] 2020-06-08 15:58
This is essentially a duplicate of #3780

**Closed by aiuto** 2020-06-08 15:58 UTC
Labels: P2, team-Configurability
