### ISSUE TITLE
Feature request: hide remote execution time if remote execution is not enabled

### ISSUE THREAD

**Issue by wjywbs** [bazelbuild/bazel#6672] opened 2018-11-14 03:26 UTC
### Description of the feature request:

```
INFO: Elapsed time: 0.327s, Critical Path: 0.00s, Remote (N/A of the time): [queue: N/A, setup: N/A, process: N/A]
INFO: Elapsed time: 1.256s, Critical Path: 0.84s, Remote (0.00% of the time): [queue: 0.00%, setup: 0.00%, process: 0.00%]
```

Can these `Remote (0.00% of the time): [queue: 0.00%, setup: 0.00%, process: 0.00%]` outputs be hidden when remote execution is not enabled?

bazel 0.19.0

**Comment by benjaminp** [comment] 2018-11-14 04:19
Duplicate of #6208.

**Closed as completed** 2018-11-14 04:23 UTC
