### ISSUE TITLE
Windows: `bazel clean --expunge` sometimes causes Bazel server to crash

### ISSUE THREAD

**Issue by meteorcloudy** [bazelbuild/bazel#3956] opened 2017-10-24 08:55 UTC
When I run `bazel clean --expunge` on Windows, I sometimes get
```
INFO: Starting clean (this may take a while). Consider using --expunge_async if the clean takes more than several minutes.

Server terminated abruptly (error code: 14, error message: '', log file: 'c:\tmp\_bazel_pcloudy\2a_d8ear/server/jvm.out')
```
Both errror_message and log file are empty.

Bazel version: HEAD

**Comment by meteorcloudy** [comment] 2017-10-24 14:02
Possible culprit: https://github.com/bazelbuild/bazel/commit/4869c4e17d5b1410070a1570f3244148d8f97b5d

**Comment by meteorcloudy** [comment] 2017-10-24 14:23
git bisect confirmed my suspicion.

**Comment by meteorcloudy** [comment] 2017-10-24 15:02
@kush-c @lberki Could you take a look please?

**Comment by meteorcloudy** [comment] 2017-10-24 15:17
I can reproduce this when running `bazel build src:bazel && bazel clean --expunge` on Windows.

**Comment by BenTheElder** [comment] 2017-10-24 23:30
I think we've actually been seeing this in an ubuntu based docker image https://github.com/kubernetes/test-infra/pull/5137, and also now with `bazel version` too.

**Comment by meteorcloudy** [comment] 2017-10-25 08:42
@BenTheElder Which Bazel version are you using?

**Comment by BenTheElder** [comment] 2017-10-25 16:09
0.7.0, I haven't seen this with previous releases.

On Oct 25, 2017 01:43, "Yun Peng" <notifications@github.com> wrote:

@BenTheElder <https://github.com/bentheelder> Which Bazel version are you
using?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/bazelbuild/bazel/issues/3956#issuecomment-339258567>,
or mute the thread

**Comment by BenTheElder** [comment] 2017-10-28 01:06
Using `--batch` seems like it might be working as a mitigation at least in our case, I'm not sure yet but so far since switching that on we haven't seen a bazel failure. cc @ixdy

**Comment by znull** [comment] 2017-11-06 19:01
I just started seeing this with bazel 0.8.0rc1 on linux (ubuntu). We hadn't seen it previously.

**Comment by meteorcloudy** [comment] 2017-11-06 19:07
Adding this issue to release blocker cause it's in 0.8.0rc1
@lberki @kush-c Could you take a look?

**Comment by kush-c** [comment] 2017-11-11 00:05
I wasn't able to reproduce it on my linux box after multiple runs of the loop for i in {1..10}; do bazel build src:bazel && bazel clean --expunge && bazel shutdown; done
If I can't reproduce on Monday as well, we'll probably have to consider a rollback again :(

**Comment by BenTheElder** [comment] 2017-11-11 00:30
@kush-c we're fairly confident it's related to memory pressure since we only sometimes saw it in our CI but never locally with 0.7 (and the CI nodes are heavily loaded). My best guess is that it was triggered when the job landed on a node under extra memory pressure, though we did not see this with previous bazel versions as far as I know.

At a suggestion from @ixdy we tried flipping on `--batch` with 0.7 and have not seen any similar issues for about two weeks now since turning it on. This is in an ubuntu based docker image running on kubernetes for the [kuberentes/test-infra](github.com/kubernetes/test-infra) CI.

**Comment by kush-c** [comment] 2017-11-13 15:35
That's very helpful @BenTheElder. So the issue was present with 0.7 but has just been worsened at HEAD? Commit [4869c4e](https://github.com/bazelbuild/bazel/commit/4869c4e17d5b1410070a1570f3244148d8f97b5d) certainly may be responsible, since it tries to kill the server when the system is low on memory, and perhaps we ran into a race condition when a `bazel clean` is issued when bazel is in the process of killing itself.

That also explains why I wasn't able reproduce this issue even at HEAD on my 48G linux box, any why `--batch` solves the problem since commit [4869c4e](https://github.com/bazelbuild/bazel/commit/4869c4e17d5b1410070a1570f3244148d8f97b5d) shouldn't affect `--batch` invocations.

@meteorcloudy Given this issue did also occur rarely with 0.7, and using `--batch` may be a reasonable workaround for workflows which wish to use `bazel clean --expunge` anyways, does this need to be a release blocker? Given that I don't have a local repro yet, if this is a release blocker, we'll probably need to rollback the commit and hence the important functionality of bazel shutting down itself, on a system running low on memory.

**Comment by meteorcloudy** [comment] 2017-11-14 10:30
Hmm..  I doubt they are the same issue on Linux and Windows.
Because on Windows, I can always repro after 3~5 runs in 0.8.0rc, but not in 0.7.0. So it does look like a regression to me.
Can you try to use one of the CI windows slaves to repo?

**Closed** 2017-11-15 18:49 UTC
Labels: category: multi-platform > windows, P1, Release blocker, type: bug
