### ISSUE TITLE
Symlink to the binary created from a py_binary rule does not work

### ISSUE THREAD

**Issue by hhclam** [bazelbuild/bazel#4022] opened 2017-11-04 17:55 UTC
Please provide the following information. The more we know about your system and use case, the more easily and likely we can help.

I'm using Bazel version 0.7.0

Say I have these files:
$ cat BUILD
py_binary(
    name = "test",
    srcs = ["test.py"]
)

$ cat test.py
print "Hello world!"

$ bazel build :test
INFO: Found 1 target...
Target //:test up-to-date:
  bazel-bin/test

$ bazel-bin/test
Hello world!

$ ln -s bazel-bin/test bazel_link

$ ./bazel_link
Traceback (most recent call last):
  File "./bazel_link", line 178, in <module>
    Main()
  File "./bazel_link", line 117, in Main
    module_space = FindModuleSpace()
  File "./bazel_link", line 91, in FindModuleSpace
    sys.argv[0])
AssertionError: Cannot find .runfiles directory for ./bazel_link

The problem is this line that does not consider the realpath of the argv[0].
https://github.com/bazelbuild/bazel/blob/master/src/main/java/com/google/devtools/build/lib/bazel/rules/python/python_stub_template.txt#L82

**Comment by hhclam** [comment] 2017-11-04 17:56
Please feel free to assign this me as I have a fix.

**Comment by damienmg** [comment] 2017-11-08 19:01
:) Thanks for taking that on :)

**Comment by hhclam** [comment] 2017-11-09 19:32
This turns out to a bit tricker as my description is not entirely correct. I have 2 use cases:
1. Symlink to the Bazel-built binary of py_binary.
2. Copy and deference the runfiles tree of the py_binary and then symlink to the py_binary in the runfiles tree.

Both use cases fails for me. However java_binary works for both use cases. Using realpath will only fix case (2) but not case (1).

**Comment by drigz** [comment] 2017-11-24 12:53
@hhclam Does it work if you use realpath on [L74](https://github.com/bazelbuild/bazel/blob/9ee4073a0e6a2f92cd325e4441fc2b74b1fda299/src/main/java/com/google/devtools/build/lib/bazel/rules/python/python_stub_template.txt#L74) as well? I would have expected L74 to handle case 1 and L82 to handle case 2.

**Comment by hhclam** [comment] 2017-11-24 14:23
realpath doesn't work. There are a couple cases when the symlink belongs to a runfiles tree but not the real file. The correct solution is to follow the symlink step by step, similar to the java stub. I have an open review for this.

**Comment by mmcloughlin** [comment] 2018-02-08 05:54
For what it's worth, I'd love to see a fix of this issue. I'm currently using a "horrific hack" to work around it... using a `genrule` to build a bash script to call the python stub. This way `sys.argv[0]` is correct.

**Comment by mfarrugi** [comment] 2018-09-21 00:49
Any chance this is forthcoming?

cc: @damienmg

**Comment by mfarrugi** [comment] 2018-09-21 22:39
Similarly https://github.com/bazelbuild/bazel/blob/c361da0cb8b02e9616a13ffced10ef091a1f6219/src/main/java/com/google/devtools/build/lib/bazel/rules/python/python_stub_template.txt#L125-L127 is also incorrect, L125  should be `  runfiles = module_space` ...  or  L127 should be `return ('RUNFILES_MANIFEST_FILE', runfiles)` and a check like the former should be added..

I am not sure what the intended API here is, so I am hesitant to make the changes myself.

**Comment by brown** [comment] 2018-09-25 03:07
The HEAD of branch
    https://github.com/brown/bazel/commits/python-find-runfiles
has a commit that fixes this problem for me.

**Comment by mfarrugi** [comment] 2018-10-15 17:55
^ #6228

**Comment by drigz** [comment] 2018-12-03 15:38
This is fixed in Bazel 0.20.0.

**Comment by brandjon** [comment] 2019-03-13 21:32
Confirmed that this was indeed fixed with 4fbeabdb5da1a22e2f0e69c1349176e65f9aa093 (the above PR) and no longer repros. Closing.

**Closed by brandjon** 2019-03-13 21:32 UTC
Labels: P3, team-Rules-Python, type: bug

**Comment by zhuwsh** [comment] 2021-01-19 12:34
> The HEAD of branch
> https://github.com/brown/bazel/commits/python-find-runfiles
> has a commit that fixes this problem for me.

hello, I'm using the bazel version of 0.27.0, but I meet this issue again. 
can anyone help me?thanks.
