### ISSUE TITLE
https://bazel.io isn't loading

### ISSUE THREAD

**Issue by kchodorow** [bazelbuild/bazel#1563] opened 2016-07-25 13:56 UTC
https://twitter.com/ittaiz/status/757281651726614528

**Comment by damienmg** [comment] 2016-07-25 14:18
dupe of https://github.com/bazelbuild/bazel/issues/47

**Closed by damienmg** 2016-07-25 14:18 UTC
Labels: category: skylark > cloud / docker, P2, type: documentation

**Comment by kchodorow** [comment] 2016-07-25 14:54
I thought this was working for a while.

**Comment by damienmg** [comment] 2016-07-25 15:03
Not yet :(
