### ISSUE TITLE
Recursive http_archive

### ISSUE THREAD

**Issue by lshamis** [bazelbuild/bazel#3941] opened 2017-10-20 20:44 UTC
I'm using `http_archive` to add https://github.com/abseil/abseil-cpp to my WORKSPACE.
When trying to use one of their BUILD rules, I get the following error:

    .../external/com_google_absl/absl/time/BUILD.bazel:27:1: no such package '@com_googlesource_code_cctz//': The repository could not be resolved and referenced by '@com_google_absl//absl/time:time'

`com_googlesource_code_cctz` is defined abseil's WORKSPACE as an `http_archive`.

**Comment by buchgr** [comment] 2017-10-23 14:32
cc @damienmg

**Comment by damienmg** [comment] 2017-10-25 12:48
Blocked by #1943

**Comment by dslomov** [comment] 2018-01-09 13:04
This is actually a duplicate of #1943, closing

**Closed by dslomov** 2018-01-09 13:04 UTC
Labels: P2, category: extensibility > external repositories, type: feature request
