### ISSUE TITLE
Certain combination of commands and user actions results in internal Bazel error

### ISSUE THREAD

**Issue by alexander-scott** [bazelbuild/bazel#15380] opened 2022-05-01 18:01 UTC
### Description of the bug:

The following steps seem to consistently result in an internal Bazel error:

1. Run a Bazel AQuery //...
2. Delete a file which is an input to a target using a glob.
3. Run a Bazel CQuery rdeps.

There also needs to be an aspect in the workspace.

When running in the reproduce repo linked below it returns the following error:

```
FATAL: bazel crashed due to an internal error. Printing stack trace:
java.lang.IllegalStateException: query-requested node 'ConfiguredTargetKey{label=//glob_scenario:2_test, config=BuildConfigurationValue.Key[34d644865e8d917fb1eedd0aab1d74fa538b46a81393be52c11048b3cc0c9f80]}' was unavailable in the query environment graph. If you come across this error, please ping b/150301500 or contact the blaze configurability team.
        at com.google.common.base.Preconditions.checkState(Preconditions.java:591)
        at com.google.devtools.build.lib.query2.PostAnalysisQueryEnvironment.targetifyValues(PostAnalysisQueryEnvironment.java:428)
        at com.google.devtools.build.lib.query2.PostAnalysisQueryEnvironment.targetifyValues(PostAnalysisQueryEnvironment.java:476)
        at com.google.devtools.build.lib.query2.PostAnalysisQueryEnvironment.getReverseDeps(PostAnalysisQueryEnvironment.java:296)
        at com.google.devtools.build.lib.query2.PostAnalysisQueryEnvironment.getReverseDeps(PostAnalysisQueryEnvironment.java:101)
        at com.google.devtools.build.lib.query2.engine.AllRdepsFunction$1.process(AllRdepsFunction.java:106)
        at com.google.devtools.build.lib.query2.engine.AbstractQueryEnvironment$1.call(AbstractQueryEnvironment.java:135)
        at com.google.devtools.build.lib.query2.engine.AbstractQueryEnvironment$1.call(AbstractQueryEnvironment.java:132)
        at com.google.common.util.concurrent.CombinedFuture$CallableInterruptibleTask.runInterruptibly(CombinedFuture.java:183)
        at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:69)
        at com.google.common.util.concurrent.DirectExecutor.execute(DirectExecutor.java:30)
        at com.google.common.util.concurrent.CombinedFuture$CombinedFutureInterruptibleTask.execute(CombinedFuture.java:104)
        at com.google.common.util.concurrent.CombinedFuture.handleAllCompleted(CombinedFuture.java:62)
        at com.google.common.util.concurrent.AggregateFuture.processCompleted(AggregateFuture.java:283)
        at com.google.common.util.concurrent.AggregateFuture.decrementCountAndMaybeComplete(AggregateFuture.java:265)
        at com.google.common.util.concurrent.AggregateFuture.access$200(AggregateFuture.java:42)
        at com.google.common.util.concurrent.AggregateFuture$1.run(AggregateFuture.java:147)
        at com.google.common.util.concurrent.DirectExecutor.execute(DirectExecutor.java:30)
        at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:1213)
        at com.google.common.util.concurrent.AbstractFuture.addListener(AbstractFuture.java:724)
        at com.google.common.util.concurrent.FluentFuture$TrustedFuture.addListener(FluentFuture.java:110)
        at com.google.devtools.build.lib.query2.engine.AbstractQueryEnvironment$QueryTaskFutureImpl.addListener(AbstractQueryEnvironment.java:78)
        at com.google.common.util.concurrent.AggregateFuture.init(AggregateFuture.java:128)
        at com.google.common.util.concurrent.CombinedFuture.<init>(CombinedFuture.java:52)
        at com.google.common.util.concurrent.Futures$FutureCombiner.call(Futures.java:719)
        at com.google.devtools.build.lib.query2.engine.AbstractQueryEnvironment.whenAllSucceedCall(AbstractQueryEnvironment.java:183)
        at com.google.devtools.build.lib.query2.engine.AbstractQueryEnvironment.whenSucceedsCall(AbstractQueryEnvironment.java:160)
        at com.google.devtools.build.lib.query2.engine.AbstractQueryEnvironment.eval(AbstractQueryEnvironment.java:130)
        at com.google.devtools.build.lib.query2.engine.AllRdepsFunction.eval(AllRdepsFunction.java:88)
        at com.google.devtools.build.lib.query2.engine.RdepsFunction.lambda$evalWithBoundedDepth$0(RdepsFunction.java:130)
        at com.google.devtools.build.lib.query2.engine.AbstractQueryEnvironment.lambda$transformAsync$0(AbstractQueryEnvironment.java:192)
        at com.google.common.util.concurrent.AbstractTransformFuture$AsyncTransformFuture.doTransform(AbstractTransformFuture.java:213)
        at com.google.common.util.concurrent.AbstractTransformFuture$AsyncTransformFuture.doTransform(AbstractTransformFuture.java:202)
        at com.google.common.util.concurrent.AbstractTransformFuture.run(AbstractTransformFuture.java:118)
        at com.google.common.util.concurrent.DirectExecutor.execute(DirectExecutor.java:30)
        at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:1213)
        at com.google.common.util.concurrent.AbstractFuture.addListener(AbstractFuture.java:724)
        at com.google.common.util.concurrent.AbstractFuture$TrustedFuture.addListener(AbstractFuture.java:126)
        at com.google.devtools.build.lib.query2.engine.AbstractQueryEnvironment$QueryTaskFutureImpl.addListener(AbstractQueryEnvironment.java:78)
        at com.google.common.util.concurrent.AbstractTransformFuture.create(AbstractTransformFuture.java:39)
        at com.google.common.util.concurrent.Futures.transformAsync(Futures.java:446)
        at com.google.devtools.build.lib.query2.engine.AbstractQueryEnvironment.transformAsync(AbstractQueryEnvironment.java:190)
        at com.google.devtools.build.lib.query2.engine.RdepsFunction.evalWithBoundedDepth(RdepsFunction.java:132)
        at com.google.devtools.build.lib.query2.engine.RdepsFunction.eval(RdepsFunction.java:75)
        at com.google.devtools.build.lib.query2.engine.FunctionExpression.eval(FunctionExpression.java:55)
        at com.google.devtools.build.lib.query2.engine.AbstractQueryEnvironment.eval(AbstractQueryEnvironment.java:129)
        at com.google.devtools.build.lib.query2.common.AbstractBlazeQueryEnvironment.evalTopLevelInternal(AbstractBlazeQueryEnvironment.java:115)
        at com.google.devtools.build.lib.query2.common.AbstractBlazeQueryEnvironment.evaluateQuery(AbstractBlazeQueryEnvironment.java:155)
        at com.google.devtools.build.lib.query2.PostAnalysisQueryEnvironment.evaluateQuery(PostAnalysisQueryEnvironment.java:152)
        at com.google.devtools.build.lib.buildtool.PostAnalysisQueryBuildTool.doPostAnalysisQuery(PostAnalysisQueryBuildTool.java:182)
        at com.google.devtools.build.lib.buildtool.PostAnalysisQueryBuildTool.postProcessAnalysisResult(PostAnalysisQueryBuildTool.java:78)
        at com.google.devtools.build.lib.buildtool.BuildTool.buildTargets(BuildTool.java:227)
        at com.google.devtools.build.lib.buildtool.BuildTool.processRequest(BuildTool.java:443)
        at com.google.devtools.build.lib.buildtool.BuildTool.processRequest(BuildTool.java:411)
        at com.google.devtools.build.lib.runtime.commands.CqueryCommand.exec(CqueryCommand.java:152)
        at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.execExclusively(BlazeCommandDispatcher.java:585)
        at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.exec(BlazeCommandDispatcher.java:231)
        at com.google.devtools.build.lib.server.GrpcServerImpl.executeCommand(GrpcServerImpl.java:550)
        at com.google.devtools.build.lib.server.GrpcServerImpl.lambda$run$1(GrpcServerImpl.java:614)
        at io.grpc.Context$1.run(Context.java:579)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
```

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

A minimal example that reproduces the error is provided here https://github.com/alexander-scott/bazel_bug_reproduce_1. It has a shell script [`break_bazel.sh`](https://github.com/alexander-scott/bazel_bug_reproduce_1/blob/main/break_bazel.sh) that performs the steps that cause the error.

The shell script does the following:

```
touch glob_scenario/2_test.cpp
bazel aquery //...
rm glob_scenario/2_test.cpp
bazel cquery  -- 'rdeps(//..., //...)'
```

To reproduce this error you can run the following:

```
git clone https://github.com/alexander-scott/bazel_bug_reproduce_1.git
cd bazel_bug_reproduce_1
./break_bazel.sh
```

### Which operating system are you running Bazel on?

Ubuntu 20.04

### What is the output of `bazel info release`?

release 5.1.1

### Have you found anything relevant by searching the web?

The problem looks similar to what was mentioned here https://github.com/bazelbuild/bazel/issues/15079, however the user didn't manage to create an example which reliably reproduces  the error.

**Comment by gregestren** [comment] 2022-05-02 16:55
Interesting! I haven't tried to repro yet, but if this in facts lets us reliably repro that's an enormously helpful clue. Thanks so much for this report!

**Comment by gregestren** [comment] 2022-05-09 21:14
Reproed on my side - thanks again.

Not that adding `--noinclude_aspects` to the cquery call prevents the crash. Nothing decisive but I suspect aspect traversals are related.

I'm going to close this as a dupe for https://github.com/bazelbuild/bazel/issues/15079 and keep this as a reproduction reference.

**Comment by gregestren** [comment] 2022-05-09 21:15
Duplicate of https://github.com/bazelbuild/bazel/issues/15079

**Closed by gregestren** 2022-05-09 21:15 UTC
Labels: type: bug, team-Configurability, untriaged
