### ISSUE TITLE
windows: Source forest creation failed ... Permission denied [duplicate of #7458]

### ISSUE THREAD

**Issue by philwo** [bazelbuild/bazel#7679] opened 2019-03-09 02:24 UTC
Initially reported by @cushon in our Google issue tracker. I'm moving it here, because it's a Bazel bug, not an infrastructure issue.

From: https://buildkite.com/bazel/bazelisk-plus-incompatible-flags/builds/29#fac23b9c-190d-4e1e-a364-0c5a7e5573e2
...
Bazel (:windows: (JDK 8))
...
Running Bazel with --incompatible_use_toolchain_providers_in_java_common
...
ERROR: Source forest creation failed: D:/b/arv5wp3s/execroot/io_bazel/external/remote_java_tools/JavaBuilder_deploy.jar (Permission denied)

The `JavaBuilder_deploy.jar (Permission denied)` looks like it might be a transient IO issue; I don't see any obvious way --incompatible_use_toolchain_providers_in_java_common could have caused that error.

**Comment by lberki** [comment] 2019-03-14 13:07
I seem to remember that @laszlocsomor had this issue before, so it's a dupe?

**Comment by laszlocsomor** [comment] 2019-03-14 13:10
Dupe of https://github.com/bazelbuild/bazel/issues/7458.

`JavaBuilder_deploy.jar` is in the root of the repository, so Bazel on Windows copies (rather than symlinks) it, then running it as a persistent worker yields an open file handle, so re-fetching the repository cannot overwrite the file, hence "Permission denied".

Solution: put the file in a subdirectory, so Bazel can symlink to the directory.

**Comment by lberki** [comment] 2019-03-14 13:41
Closing as dupe then.

**Closed by lberki** 2019-03-14 13:41 UTC
Labels: P2, category: extensibility > external repositories, platform: windows, team-Windows, type: bug
