### ISSUE TITLE
no debugging symbols found on mac

### ISSUE THREAD

**Issue by is03wlei** [bazelbuild/bazel#2573] opened 2017-02-23 03:13 UTC
Please provide the following information. The more we know about your system and use case, the more easily and likely we can help.

### Description of the problem / feature request / question:
#ggdb main
GNU gdb (GDB) 7.9.1
Copyright (C) 2015 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-apple-darwin15.3.0".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from main...(no debugging symbols found)...done.

### If possible, provide a minimal example to reproduce the problem:
###BUILD
cc_binary(
    name = "main",
    srcs = glob(["*.cpp", "*.h", "*.hpp"]),
    copts = [
        "-c",
        "-w",
        "-fPIC",
    ],
    visibility = ["//visibility:public"],
)

bazel build --copt="-g" source:all
I also tried to add -g to copts in BUILD. But it didn't work either.

### Environment info
* Operating System:
OS X EI Capitan
version 10.11.6

* Bazel version (output of `bazel info release`):
[bazel release 0.4.4]

* If `bazel info release` returns "development version" or "(@non-git)", please tell us what source tree you compiled Bazel from; git commit hash is appreciated (`git rev-parse HEAD`):

###  Have you found anything relevant by searching the web? (e.g. GitHub issues, email threads in the [bazel-discuss@googlegroups.com](https://groups.google.com/forum/#!forum/bazel-discuss) archive)
https://github.com/bazelbuild/bazel/issues/2537

### Anything else, information or logs or outputs that would be helpful?
(If they are large, please upload as attachment or provide link).

**Comment by iirina** [comment] 2017-02-23 12:26
What is the output of `bazel build --copt="-g" source:all`?

**Comment by is03wlei** [comment] 2017-02-24 06:42
Previously, it reported as following:
WARNING: Stripping enabled, but '--copt=-g' (or --per_file_copt=...@-g) specified. Debug information will be generated and then stripped away. This is probably not what you want! Use '-c dbg' for debug mode, or use '--strip=never' to disable stripping.

Then I tried both "bazel build -c dbg source:all" and "bazel build --strip=never --copt="-g" source:all", but it didn't work either.

**Comment by biolee** [comment] 2017-02-24 08:34
as https://github.com/bazelbuild/bazel/issues/2537

bazel do generate dSYM file but it ls empty, https://github.com/bazelbuild/bazel/issues/2537#issuecomment-281497449 hava a init sollution

and 
bazel do not generate debug info for lldb for mac and linux

**Comment by mhlopko** [comment] 2017-02-24 08:52
Just to be sure it is #2537, the correct command to build target with debugging symbols is `bazel build -c dbg source:all`, is it still broken for you?

**Comment by iirina** [comment] 2017-02-24 08:53
@is03wlei  Can you please also paste the output of the other command you mentioned?

@mhlopko Can you take a look at this? Thanks!

**Comment by is03wlei** [comment] 2017-02-28 03:05
build -c dbg source:all
.................
INFO: Found 2 targets...
INFO: From Compiling xxx.cpp:

...bunch of warnings...

74 warnings generated.
INFO: Elapsed time: 17.249s, Critical Path: 6.37s


bazel build --strip=never --copt="-g" source:all
INFO: Found 2 targets...
INFO: From Compiling xx.cpp:

...bouch of warning...

21 warnings generated.
INFO: Elapsed time: 6.128s, Critical Path: 5.67s

**Comment by mhlopko** [comment] 2017-03-10 08:10
Let me close this one as it is a duplicate of #2537, let's continue the discussion there

**Closed by mhlopko** 2017-03-10 08:10 UTC
Labels: category: multi-platform > other, category: rules > C++, P3, type: bug
