### ISSUE TITLE
skyframe tests should not depend on java rules

### ISSUE THREAD

**Issue by janakdr** [bazelbuild/bazel#1005] opened 2016-03-03 18:11 UTC
$ bazel query 'somepath(//src/test/java/com/google/devtools/build/skyframe:skyframe_base_test,//src/main/java/com/google/devtools/build/lib:java-rules)'
//src/test/java/com/google/devtools/build/skyframe:skyframe_base_test
//src/test/java/com/google/devtools/build/lib:testutil
//src/main/java/com/google/devtools/build/lib:bazel-rules
//src/main/java/com/google/devtools/build/lib:java-rules

Why does //src/test/java/com/google/devtools/build/lib:testutil pull in so much?

**Comment by ulfjack** [comment] 2016-03-03 19:48
I don't know. Probably because we don't have a tool to automatically remove
unused deps? From a quick glance, that dependency looks unnecessary to me.

On Thu, Mar 3, 2016 at 7:12 PM, Janak Ramakrishnan <notifications@github.com

**Comment by aiuto** [comment] 2020-05-13 04:54
Closing as obsolete. I can not reproduce (after finding the moved targets).

**Closed by aiuto** 2020-05-13 04:54 UTC
Labels: P3, category: misc > testing, team-Core, type: feature request
