### ISSUE TITLE
macos installer does not warn you that you don't have the right JDK installed

### ISSUE THREAD

**Issue by aiuto** [bazelbuild/bazel#9143] opened 2019-08-12 02:15 UTC
> ATTENTION! Please read and follow:
> - if this is a _question_ about how to build / test / query / deploy using Bazel, or a _discussion starter_, send it to bazel-discuss@googlegroups.com
> - if this is a _bug_ or _feature request_, fill the form below as best as you can.

### Description of the problem / feature request:

> Replace this line with your answer.

### Feature requests: what underlying problem are you trying to solve with this feature?

> Replace this line with your answer.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

> Replace this line with your answer.

### What operating system are you running Bazel on?

> Replace this line with your answer.

### What's the output of `bazel info release`?

> Replace this line with your answer.

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

> Replace this line with your answer.

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

> Replace this line with your answer.

###  Have you found anything relevant by searching the web?

> Replace these lines with your answer.
>
> Places to look:
> - StackOverflow: http://stackoverflow.com/questions/tagged/bazel
> - GitHub issues: https://github.com/bazelbuild/bazel/issues
> - email threads on https://groups.google.com/forum/#!forum/bazel-discuss

### Any other information, logs, or outputs that you want to share?

> Replace these lines with your answer.
>
> If the files are large, upload as attachment or provide link.

**Comment by tetromino** [comment] 2019-08-12 21:03
Please describe the error you are getting in more detail, the exact command line you are running, your bazelrc options (if any), and the Bazel version.

I am fairly sure we are shipping an embedded JDK with Bazel, so I don't understand the circumstances under which you encountered this error.

**Comment by aiuto** [comment] 2019-08-22 17:12
Aggh.  This is a botched issue entry.

The root cause was
1. Follow instructions here: https://docs.bazel.build/versions/master/install-os-x.html
bazel-0.28.1-installer-darwin-x86_64.sh
../bazel-0.28.1-installer-darwin-x86_64.sh --user
   Failure about jdks

But this was on my laptop at home, so I can not repo now.  I'll try tonight and either close the bug or edit the description to make sense.

**Comment by tetromino** [comment] 2019-08-22 20:34
Please check if you have a .bazelrc - you might be accidentally passing in an invalid javabase.

**Comment by susinmotion** [comment] 2019-09-06 18:03
I'm not able to reproduce this on my laptop. 
There's been a recent fix by Alex that lets you know where your JDK is being set, which I think should solve this problem in the next release, so I'm closing even though I can't test it.

**Closed by susinmotion** 2019-09-06 18:03 UTC
Labels: more data needed, team-Apple, type: bug, untriaged
