### ISSUE TITLE
Configuration transition causes very long output paths

### ISSUE THREAD

**Issue by tomlu** [bazelbuild/bazel#11598] opened 2020-06-16 14:04 UTC
### Description of the problem / feature request:

Transitions causes a 256-bit hash to be tacked onto the output path: https://github.com/bazelbuild/bazel/blob/master/src/main/java/com/google/devtools/build/lib/analysis/skylark/FunctionTransitionUtil.java#L394

This turns into a 64-char string suffix, consuming about 25% of available PATH_MAX on Windows.

### Feature requests: what underlying problem are you trying to solve with this feature?

I don't think we really need 256 bit collision avoidance? Assuming we would only have a handful of output directories, 64 bits might do. This would save 48 chars. Or maybe even just a 32-bit hash, saving even more?

It would also improve the ergonomics of the output by decreasing the amount of noise in reported output paths.

Once there is consensus I can go ahead and make the change.

### What operating system are you running Bazel on?

Windows 10

**Comment by juliexxia** [comment] 2020-06-22 20:08
Greg do you have intuition on if you think a smaller hash would be sufficient? 

The main motivation of this code was that the output directory just be different than the output directory without the starlark transition so historically there hasn't been a need for super granular output directories so this seems plausibly fine to me. 

Note to self that if we do this, we should warn internal allowlisted users. We've made a point not to guarantee output path structure ever, but I know some users are doing hacks to handle the output path of starlark transitions so it would be nice to warn them.

**Comment by juliexxia** [comment] 2020-06-22 20:09
Follow up question - if we're going to decrease the granularity of our hashing, do we have a way to notice if it does start breaking? AKA artifacts are overwriting each other?

**Comment by gregestren** [comment] 2020-06-22 20:53
I agree. I can't think of any reason why even 32 bits isn't more than we practically need.

Thanks for bringing this up, Tom.

**Comment by juliexxia** [comment] 2020-06-22 21:09
Tom, I'm happy to review PRs from you for this

**Comment by tomlu** [comment] 2020-06-23 23:31
I submitted a PR internally that made the path 48 bits. At 12 characters (a 52 character reduction) that seemed like a good balance between output ergonomics, Windows path length, and assuring we never collide.

**Comment by v3n** [comment] 2020-11-17 23:04
Is there a planned release for this fix?

```
C:/tmp/y7ddnrh6/execroot/__main__/bazel-out/x64_windows-opt-exec-2B5CBBC6-ST-c3a8cc05bdea9a638dbef813eeba1ffe0dfa7d81daedbab406d39b734127c092/bin/external/com_github_grpc_ecosystem_grpc_gateway_v2/protoc-gen-grpc-gateway/internal/gengateway/go_default_library.x
```

This path is 261 characters, which is unfortunately 1 character longer than is allowed.

**Comment by gregestren** [comment] 2020-11-18 17:29
@tomlu's commit was https://github.com/bazelbuild/bazel/commit/8350681fc900e9ee22ba62db2c5fdeb1e239321a, from June 24. According to https://github.com/bazelbuild/bazel/compare/3.3.1...3.4.0 this should be in Bazel 3.40 or newer.

Which version of Bazel produced that? Do you consistently see that for all your outputs?

**Comment by v3n** [comment] 2020-11-18 21:11
This was produced by `3.0`. I've upgraded to `3.4` and confirmed that it fixes this issue.

Thanks for the help, I had assumed that it hadn't been merged publicly since there were no status updates on the issue!

**Comment by gregestren** [comment] 2020-11-18 21:17
No worries. Agreed that in general you should expect to see a status update from the commit.

**Closed by gregestren** 2020-11-18 21:17 UTC
Labels: P2, platform: windows, team-Configurability
