### ISSUE TITLE
[bazel.build] Problem with /start/cpp

### ISSUE THREAD

**Issue by jotken** [bazelbuild/bazel#20607] opened 2023-12-19 13:55 UTC
### Page link:

https://bazel.build/start/cpp

### Problem description (include actual vs expected text, if applicable):

"bazel build //main:hello-world" fails from the C++ stage1 tutorial on a Dell XPS13 running Ubuntu 20.04.

### Where do you see this issue? (include link to specific section of the page, if applicable)

Bazel Tutorial: Build a C++ Project: https://bazel.build/start/cpp

### Any other information you'd like to share?

~/git/examples/cpp-tutorial/stage1$ bazel --version
bazel 7.0.0
~/git/examples/cpp-tutorial/stage1$ bazel build //main:hello-world
WARNING: --enable_bzlmod is set, but no MODULE.bazel file was found at the workspace root. Bazel will create an empty MODULE.bazel file. Please consider migrating your external dependencies from WORKSPACE to MODULE.bazel. For more details, please refer to https://github.com/bazelbuild/bazel/issues/18958.
WARNING: Build option --crosstool_top has changed, discarding analysis cache (this can be expensive, see https://bazel.build/advanced/performance/iteration-speed).
INFO: Analyzed target //main:hello-world (69 packages loaded, 6447 targets configured).
ERROR: /home/john/git/examples/cpp-tutorial/stage1/main/BUILD:3:10: Compiling main/hello-world.cc failed: (Exit 127): gcc failed: error executing CppCompile command (from target //main:hello-world) external/gcc_toolchain_x86_64/bin/gcc -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer '-std=c++0x' -MD -MF ... (remaining 32 arguments skipped)

Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
external/gcc_toolchain_x86_64/bin/gcc: line 45: /tmp/external/gcc_toolchain_x86_64_files/bin/x86_64-linux-gcc: No such file or directory
Target //main:hello-world failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 1.362s, Critical Path: 0.06s
INFO: 2 processes: 2 internal.
ERROR: Build did NOT complete successfully

**Comment by fmeum** [comment] 2023-12-19 14:00
Duplicate of https://github.com/bazelbuild/bazel/issues/20533, please take a look at that one instead.

**Closed by fmeum** 2023-12-19 14:00 UTC
Labels: type: documentation (cleanup), untriaged, team-Documentation
