### ISSUE TITLE
Release notes: missed a release note from 0.4.2 -- bug in script?

### ISSUE THREAD

**Issue by laszlocsomor** [bazelbuild/bazel#2216] opened 2016-12-09 07:19 UTC
### Description of the problem / feature request / question:

The release notes generator failed to include the relnotes of https://github.com/bazelbuild/bazel/commit/ed7ced0018dc5c5ebd6fc8afc7158037ac1df00d in the relnotes of [0.4.2](https://github.com/bazelbuild/bazel/releases/tag/0.4.2), I don't know why.

**Comment by damienmg** [comment] 2016-12-12 10:27
0.4.2 had several issues with the relnotes. Let's follow-up closely 0.4.3. Also ed7ced0 was rolled-back and rolled-forward, maybe the rollback detection got messed-up.

**Comment by damienmg** [comment] 2016-12-12 10:28
Marking as release blocker so we follow-up during the release.

**Comment by laszlocsomor** [comment] 2016-12-13 10:02
@iirina: FYI @damienmg's first comment

**Comment by damienmg** [comment] 2016-12-21 14:28
Closing as can't reproduce.

**Closed by damienmg** 2016-12-21 14:28 UTC
Labels: category: misc > release / binary, P2, Release blocker, type: process
