### ISSUE TITLE
macOS: Cannot delete sandbox directory after action execution

### ISSUE THREAD

**Issue by bendowski** [bazelbuild/bazel#2371] opened 2017-01-18 15:53 UTC
### Description of the problem / feature request / question:

After running tests, I see this warning:

WARNING: Cannot delete sandbox directory after action execution: /private/var/tmp/_bazel_user/81e2f173210dcd47c26dbf4a42147a8b/bazel-sandbox/2551a3b4-abe3-4c34-a39d-37b44153e291-0 (java.io.IOException: /private/var/tmp/_bazel_user/81e2f173210dcd47c26dbf4a42147a8b/bazel-sandbox/2551a3b4-abe3-4c34-a39d-37b44153e291-0/execroot/master/_tmp/tests_2 (Directory not empty)).

Please let me know how I can provide more debugging information.

### Environment info
* Operating System:
macOS Sierra 10.12.2

* Bazel version (output of `bazel info release`):
release 0.4.3-homebrew

**Comment by hermione521** [comment] 2017-01-19 10:22
We used to have this problem although I don't remember the reason. I remember @philwo had a fix https://github.com/bazelbuild/bazel/commit/95b16a89001014c48e77e5c38c4ca17bd28d3ebb. I'm not sure if this should happen now...

**Comment by laszlocsomor** [comment] 2017-01-23 12:16
@benol : Thanks for the bug report! I'm trying to collect some hopefully useful data:
- Do you see this warning consistently or just intermittently?
- Have you seen it with just this target or with other tests too?
- Is the directory left behind after Bazel finished? Are you able to list the contents of it does it indeed look non-empty?
- Are you aware of any workaround?

**Comment by benol** [comment] 2017-01-24 13:42
- I can see it consistently for one target that creates a lot of files in TEST_TMPDIR and runs other processes from within the test.
- Only in this target.
- It's left on disk and it's non-empty. 

In our case we spawn a new JVM to run the Gradle build system, inside the sandbox, on files in the TEST_TMPDIR directory. Among other things in `execroot/studio-master-dev/_tmp/tests_N`, we also configure the Gradle daemon to use a directory there as "gradle user home" [1]. After Bazel fails to clean up the sandbox, I can see this directory left there, with a file called `registry.bin.lock`.

So it's possible that Bazel fails to kill all child processes before deleting sandbox. Is that possible?

We don't have this problem on Linux.

[1] https://docs.gradle.org/current/userguide/build_environment.html

**Comment by laszlocsomor** [comment] 2017-01-25 09:19
Thanks, that's great info.

So it sounds like the sandbox cleanup is broken -- it doesn't kill all child processes and fails to clean up all directories.

@hermione521 : does that sound like a plausible root cause? I think we could repro this with an action that spawns a process which holds on to a file descriptor and doesn't terminate.

**Comment by hermione521** [comment] 2017-01-27 13:09
I tried several things but still can't reproduce. It would be much helpful if you can provide a minimal example to reproduce. Thank you!

**Comment by ittaiz** [comment] 2017-01-27 13:17
I actually got a similar message but I'm not sure it was deterministic.
I was wading through several issues so ignored it for the time being but if it will surface again I'll try and triage and generate a minimal example.

**Comment by hermione521** [comment] 2017-01-27 13:41
@ittaiz that would be very helpful! Thank you in advance!

**Comment by ittaiz** [comment] 2017-03-12 14:21
@hermione521 happened again to me today but since I'm generating a big bazel codebase (rather generating hundreds of builds files via a migration tool from maven) I don't think I can generate a minima example. Mainly since I don't know why this happens.
Any chance you can give me a few concrete steps you'd like me to take when this occurs to capture the state of the workshop?

**Comment by ittaiz** [comment] 2017-03-20 15:23
@hermione521 ping? happened to me again. a small repro isn't likely but maybe I can dig some more details if you point me to the right direction

**Comment by hermione521** [comment] 2017-03-21 12:59
Hmm.. I don't have any idea except clean them manually.. Let's ping @philwo to see if it helps.

**Comment by philwo** [comment] 2017-03-21 13:57
I'm currently doing a big round of bug-fixes and will try to fix whatever might cause this. I'll specifically look into whether there are any race conditions in Bazel's process management on macOS.

I'll follow up on this, but if I don't, please ping this bug in ~1 week and I'll send a status update. :)

**Comment by ittaiz** [comment] 2017-03-29 07:51
Ping :)

**Comment by philwo** [comment] 2017-04-06 14:48
Hi @ittaiz,

I've been working on a fix for this over the last days, hope to get it submitted tomorrow. Will ping this bug then!

Philipp

**Comment by ulfjack** [comment] 2017-06-29 19:51
@philwo can we close this now?

**Comment by philwo** [comment] 2017-07-10 15:04
The fix has been rolled back, so maybe we should keep it open. On the other hand... did this happen to someone in the last month? If not, we can also close it, I don't mind.

**Comment by ittaiz** [comment] 2017-07-10 15:37
We used to get this from time to time. Don't remember if recently. But if
the fix has been rolled back then why not keep it open?

**Closed** 2018-07-19 12:39 UTC
Labels: category: sandboxing, under investigation
