### ISSUE TITLE
iOS build crash on the Tutorial on ci.bazel.io with latest

### ISSUE THREAD

**Issue by damienmg** [bazelbuild/bazel#1764] opened 2016-09-13 11:28 UTC
See http://ci.bazel.io/job/Tutorial/BAZEL_VERSION=latest,PLATFORM_NAME=darwin-x86_64/477/console

It is passing with HEAD so probably an issue with the setup.

Strangely enough it was passing on ci-staging.bazel.io. Maybe an issue with the slave?

**Comment by damienmg** [comment] 2016-09-15 14:13
ping @c-parsons: can you have a look at the error, I cannot understand it.

**Comment by c-parsons** [comment] 2016-09-15 21:54
I'm not 100% sure, but it looks like it's inspecting an Xcode directory under /Volumes/ .. It might have an xcode image that's not installed but mounted as an image pre-installation, that was never ejected?

This is probably something we can fix in the new xcode_config repository rule (blacklisting xcodes under /Volumes/), but the root cause is likely that system state.

**Comment by laszlocsomor** [comment] 2016-09-22 14:54
I tested this on my corp macbook and got a "Yay!" at the end, so I think it's an issue with the CI machine.

**Comment by damienmg** [comment] 2016-09-22 21:16
Confirmed it worked. Deprioritizing since there is an easy workaround.

**Comment by jin** [comment] 2018-11-06 20:56
Closing as we've moved to another CI system.

**Closed by jin** 2018-11-06 20:56 UTC
Labels: P2, category: rules > ObjC / iOS / J2ObjC, type: bug
