### ISSUE TITLE
Receive "no such package 'tools/objc': BUILD file not found on package path." on Bazel queries

### ISSUE THREAD

**Issue by thomasmarsh** [bazelbuild/bazel#2748] opened 2017-03-27 18:09 UTC
We don't have the root cause isolated, but we experience the following error:

```
ERROR: /private/var/tmp/_bazel_tmarsh/e04175512e2ea0cad2046ce58e484c7d/external/BinaryCore/BUILD.bazel:61:1: every rule of type objc_library implicitly depends upon the target '//tools/objc:header_scanner', but this target could not be found because of: no such package 'tools/objc': BUILD file not found on package path.
```

It is possible to get past these by using the "--keep-going" and these aren't too hard to ignore, but it did cause us some initial difficulties as we mistook this as the cause of build failure.

### Environment info
* Operating System:
macOS 

* Bazel version (output of `bazel info release`): release 0.4.5

**Comment by buchgr** [comment] 2017-04-10 16:14
@thomasmarsh thanks for reporting the bug! Could you please share the query command that you are using? Also, on what repository are you executing this command?

**Comment by StevenEWright** [comment] 2017-05-21 04:29
Is this a duplicate of https://github.com/bazelbuild/bazel/issues/2723 ?

**Comment by jmmv** [comment] 2020-04-16 15:22
I'm sorry but, given the age of this bug and the lack of extra information... I'll have to close this as unfeasible for now. Please reply if you think something else should be done.

**Closed by jmmv** 2020-04-16 15:22 UTC
Labels: category: rules > ObjC / iOS / J2ObjC, team-Apple, untriaged
