### ISSUE TITLE
bazel mod graph whitespaces broken on Windows

### ISSUE THREAD

**Issue by Vertexwahn** [bazelbuild/bazel#22858] opened 2024-06-22 15:09 UTC
### Description of the bug:

bazel mod graph leads to the following output on my Windows system:

```
e) PS G:\dev\project1> bazel mod graph
Starting local Bazel server and connecting to it...
<root> (de_vertexwahn@0.0.0)
Ôö£ÔöÇÔöÇÔöÇabseil-cpp@_ 
Ôöé   Ôö£ÔöÇÔöÇÔöÇbazel_skylib@_ (*) 
Ôöé   Ôö£ÔöÇÔöÇÔöÇgoogletest@1.14.0.bcr.1 (*) 
Ôöé   ÔööÔöÇÔöÇÔöÇplatforms@0.0.10 (*) 
Ôö£ÔöÇÔöÇÔöÇapple_support@1.15.1 
Ôöé   Ôö£ÔöÇÔöÇÔöÇbazel_skylib@_ (*) 
Ôöé   ÔööÔöÇÔöÇÔöÇplatforms@0.0.10 (*) 
Ôö£ÔöÇÔöÇÔöÇautodiff@_ 
Ôöé   ÔööÔöÇÔöÇÔöÇeigen@3.4.0 (*) 
Ôö£ÔöÇÔöÇÔöÇbazel_skylib@_ 
Ôöé   Ôö£ÔöÇÔöÇÔöÇplatforms@0.0.10 (*) 
Ôöé   ÔööÔöÇÔöÇÔöÇrules_license@0.0.8 (*) 
Ôö£ÔöÇÔöÇÔöÇboost.algorithm@1.83.0.bcr.1 
Ôöé   Ôö£ÔöÇÔöÇÔöÇplatforms@0.0.10 (*) 
Ôöé   Ôö£ÔöÇÔöÇÔöÇboost@1.83.0.bcr.1 
Ôöé   Ôöé   Ôö£ÔöÇÔöÇÔöÇboost.asio@1.83.0.bcr.1 (*) 
```

### Which operating system are you running Bazel on?

Windows 11

### What is the output of `bazel info release`?

release 7.2.0

**Comment by peakschris** [comment] 2024-06-23 13:45
I've also been seeing this, windows 10, regardless of shell (cmd, bash, powershell)

**Comment by sgowroji** [comment] 2024-06-24 07:26
Hi @Vertexwahn, Could you please provide complete steps to reproduce this issue?

**Comment by peakschris** [comment] 2024-06-24 09:59
For me, on windows:

```
git clone https://github.com/bazelbuild/bazel.git
cd bazel
git checkout release-7.2.1 _specific release unimportant_
bazel mod graph
```

displays:
```
Starting local Bazel server and connecting to it...
<root> (bazel@_)
Γö£ΓöÇΓöÇΓöÇabseil-cpp@20230125.1
Γöé   Γö£ΓöÇΓöÇΓöÇbazel_skylib@1.6.1 (*)
Γöé   Γö£ΓöÇΓöÇΓöÇplatforms@0.0.9 (*)
Γöé   ΓööΓöÇΓöÇΓöÇrules_cc@0.0.9 (*)
<snip>
```

**Comment by fmeum** [comment] 2024-06-24 11:14
What happens if you pass `--charset=ascii`? Does your terminal support UTF-8?

**Comment by peakschris** [comment] 2024-06-24 11:26
`--charset=ascii` shows the tables, albeit less nicely:
![image](https://github.com/bazelbuild/bazel/assets/77508021/39fa88fa-187e-4232-9452-626ffb932030)

The terminal does support UTF-8:
```
wget https://www.cl.cam.ac.uk/~mgk25/ucs/examples/UTF-8-demo.txt
cat UTF-8-demo.txt
```
shows:
![image](https://github.com/bazelbuild/bazel/assets/77508021/f629fe88-5da4-4974-9ec1-d9782a41976d)

**Comment by fmeum** [comment] 2024-06-24 11:41
Sounds like Windows requires special API usage for printing UTF-8 to the console: https://stackoverflow.com/a/9337400/297261

If you are interested, you could try integrating `WriteConsoleW` here:
https://cs.opensource.google/bazel/bazel/+/master:src/main/cpp/util/file_posix.cc;l=330;drc=b5c273acbbaea9dbf6c218ec98b1310e0dde442e

**Comment by peakschris** [comment] 2024-06-24 14:14
I added this one line to file_windows.cc:

![image](https://github.com/bazelbuild/bazel/assets/77508021/7070d545-ca82-4386-9598-08f7ff0dc901)

bazel mod graph now outputs:
![image](https://github.com/bazelbuild/bazel/assets/77508021/3abc86dd-f69a-438b-a567-166c35611b92)

I think SetConsoleOutputCP could just be called once somewhere from main(), as long as it is not reset elsewhere.

Sorry, I can't submit this as a PR due to CLA.

Chris

**Comment by fmeum** [comment] 2024-06-24 14:20
@bazel-io fork 7.3.0

**Comment by Wyverald** [comment] 2024-07-08 19:07
Fixed in https://github.com/bazelbuild/bazel/commit/4a5fe6207eb596effc13fe6b8e862727dc03eda6

**Closed by Wyverald** 2024-07-08 19:07 UTC
Labels: type: bug, more data needed, area-Windows, team-ExternalDeps, untriaged, area-Bzlmod
