### ISSUE TITLE
experimental_replay_action_out_err causes out of order execution

### ISSUE THREAD

**Issue by ARodov** [bazelbuild/bazel#11365] opened 2020-05-11 22:02 UTC
A test which already exist, but was modified, is executed first, and compiled second, from the bazel test command if the .bazelrc contains build --experimental_replay_action_out_err=true

> ATTENTION! Please read and follow:
> - if this is a _question_ about how to build / test / query / deploy using Bazel, or a _discussion starter_, send it to bazel-discuss@googlegroups.com
> - if this is a _bug_ or _feature request_, fill the form below as best as you can.

### Description of the problem / feature request:

> Replace this line with your answer.

### Feature requests: what underlying problem are you trying to solve with this feature?

> Replace this line with your answer.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

> Replace this line with your answer.

### What operating system are you running Bazel on?

> Replace this line with your answer.

### What's the output of `bazel info release`?

> Replace this line with your answer.

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

> Replace this line with your answer.

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

> Replace this line with your answer.

###  Have you found anything relevant by searching the web?

> Replace these lines with your answer.
>
> Places to look:
> - StackOverflow: http://stackoverflow.com/questions/tagged/bazel
> - GitHub issues: https://github.com/bazelbuild/bazel/issues
> - email threads on https://groups.google.com/forum/#!forum/bazel-discuss

### Any other information, logs, or outputs that you want to share?

> Replace these lines with your answer.
>
> If the files are large, upload as attachment or provide link.

**Comment by jin** [comment] 2020-05-13 13:52
FYI @ulfjack

**Comment by jwnimmer-tri** [comment] 2020-05-13 13:57
To help clear the record (the bug report is extremely poorly written) -- the problem is not that any actions are executed out of order, but rather that the output from the prior run of the test is printed again, even though we're about to re-run it again.

I think the desired behavior is that either the test is re-run xor its prior output (if any) is displayed if we're not going to re-run it, but not both.

I can work up a repro if that helps?

**Comment by ulfjack** [comment] 2020-05-13 19:05
If you have a repro, that'd be great. It definitely shouldn't be printed twice.

**Comment by jwnimmer-tri** [comment] 2020-05-18 12:10
I've been unable to get in contact with the user who experienced this.  I also tried a few simple tests from scratch locally, and everything is working as expected.  So it must be something related to the more complicated remote execution configuration used by the project in question.

I think you should close this issue for now.

If / when I'm able to get a reproduction recipe, I'll open a new issue with all of the details.

**Comment by michajlo** [comment] 2020-08-18 18:28
I've run into some flavor of this.

    # Initial run...
    $ bazel test --experimental_replay_action_out_err //some:test --test_output=all
    ...
    <all the test output>

    # Run test again without --test_output=all
    $ bazel test --experimental_replay_action_out_err //some:test
    ...
    <still get all the test output>

    # Run test again _with_ --test_output=all
    $ bazel test --experimental_replay_action_out_err //some:test --test_output=all
    ...
    <all the test output>
    ...
    <then all the test output a second time!>

**Comment by janakdr** [comment] 2020-09-21 20:23
@ulfjack it seems like @michajlo has a repro of at least the more limited issue around --test_output?

**Comment by ulfjack** [comment] 2020-09-22 14:06
I can repro the issue with `experimental_replay_action_out_err` in combination with `test_output`. There is an even simpler repro:
```
$ bazel test --experimental_replay_action_out_err //some:test --test_output=all
$ bazel test --experimental_replay_action_out_err //some:test --test_output=all
<all the test output>
<then all the test output a second time!>
```

This is because the `TerminalTestResultNotifier` is not aware of `experimental_replay_action_out_err` and unconditionally prints the test log for *cached passing* tests when `test_output=all` is set (with default setting of `cache_test_results`), or of *cached passing or failing* tests if `--cache_test_results=true`:
```
$ bazel test --experimental_replay_action_out_err //foo:failing_test --test_output=all --cache_test_results=true
$ bazel test --experimental_replay_action_out_err //foo:failing_test --test_output=all --cache_test_results=true
<all the test output>
<then all the test output a second time!>
```

There are two problems here:

1. Enabling `experimental_replay_action_out_err` bakes in the value of `test_output` from the first (cached) run because the TestStrategy also checks the `test_output` flag. Checking that flag in TestStrategy is non-hermetic because it is not declared as a Skyframe input. The `TerminalTestResultNotifier` assumes that the log is not replayed by Skyframe, which is incorrect if `experimental_replay_action_out_err` is enabled, which exposes the non-hermeticity.

2. This is in addition to having the interesting side effect of printing the log twice if the cached value is to print the log *and* the run is cached *and* the `test_output` flag indicates printing the log on this run.

The original test infrastructure uses the `test_output` flag in a non-hermetic way, and the `experimental_replay_action_out_err` enforces caching, which is at odds with the non-hermeticity.

I think there are three options here:
a) Fix the hermeticity. This is not straightforward because we typically don't want to rerun passing tests if 'only' `test_output` changes. We could split the test run and its output into separate Skyframe nodes, and then only have the output node depend on the `test_output` flag, but that seems tricky at first glance.

b) Give up on `test_output` when `experimental_replay_action_out_err` is enabled. I.e., force-enable test log printing in TestStrategy regardless of the setting of `test_output` and suppress it unconditionally from `TerminalTestResultNotifier`. This would effectively make it `--test_output=all` except that it only prints the log once. We could *maybe* control test log output through appropriate settings for `--output_filter` (potentially automatically rolling the value of `test_output` into `output_filter` internally).

c) Disable `experimental_replay_action_out_err` for tests, and apply `test_output` as we currently do.

It seems like both a and c require special-casing TestRunnerAction in SkyframeExecutionFunction.

Any preferences?

**Comment by janakdr** [comment] 2020-09-22 18:23
Intuitively, seems like (c) makes the most sense, since test output is
already pretty special.

However, this flag doesn't appear to be widely used. We're considering
removing it internally. Are there any known widespread usages?

**Comment by michajlo** [comment] 2020-09-23 18:23
Another option would be to stop pretending the test log is stdout/err in skyframe and do all of the reporting via `TerminalTestResultNotifier` or whatever else is responsible for printing test logs now. This could lead to other simplifications like removing `Action#showsOutputUnconditionally()`, which seems like it only still exists as a workaround for `TestRunnerAction` + `test_output`.

**Comment by ulfjack** [comment] 2020-10-05 20:33
I added this before I left Google for some people who had repeatedly asked for it (for years). Personally, I also think this makes more sense than the haphazard semantics of 'if it happens to be cached, we don't print the output'.

**Closed** 2022-11-22 08:48 UTC
Labels: type: bug, P2, team-Core
