### ISSUE TITLE
java binary uses the wrong version of runtime dependency

### ISSUE THREAD

**Issue by is03wlei** [bazelbuild/bazel#1798] opened 2016-09-20 06:42 UTC
java_binary(
    name = "GmmEM",
    srcs = [
        "MlUtil.java",
        "Instance.java",
        "InputFormat.java",
        "GmmEM.java",
    ],
    deps = [
        "//java:org_apache_spark_spark_core_2_10",
        "//java:org_apache_spark_spark_mllib_2_10",
        "//java:log4j_log4j",
        "@commons_cli//jar",
        "//java:org_scala_lang_scala_library",
        "//java:org_scalanlp_breeze_2_10",
        "//java:org_scala_lang_scala_reflect",
        "//java:org_scala_lang_scala_compiler",
        "//java:org_scala_lang_scala_actors",
    ],
    runtime_deps = [
        "@commons_cli//jar",
        "@akka_actor//jar",
        "@akka_remote//jar",
        "@akka_slf4j//jar",
        "@com_google_protobuf//jar",
        "@commons_lang//jar",
        "@commons_collections//jar",
        "@typesafe_config//jar",
        "@apache_commons_logging//jar",
        "@commons_configuration//jar",
        "@google_guava//jar",
        "@hadoop_common//jar",
        "@hadoop_client//jar",
        "@hadoop_auth//jar",
        "@javax_servlet_api//jar",
        "@javax_ws_rs_api//jar",
        "@metrics_core//jar",
        "@netty//jar",
        "@org_apache_hadoop_hadoop_mapreduce_client_core//jar",
    ]
)

I can build the project successfully. But I got the following runtime error:
Exception in thread "main" java.lang.NoSuchMethodError: org.apache.commons.cli.Option.builder()Lorg/apache/commons/cli/Option$Builder;
    at com.didi.anomaly.GmmEM.getOptions(GmmEM.java:68)
    at com.didi.anomaly.GmmEM.gmmRun(GmmEM.java:117)
    at com.didi.anomaly.GmmEM.main(GmmEM.java:104)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:731)
    at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:181)
    at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:206)
    at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:121)
    at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)

There are two versions of commons-cli in WORKSPACE which include class org.apache.commons.cli.Option

http_jar(
    name = "commons_cli",
    url = "http://central.maven.org/maven2/commons-cli/commons-cli/1.3.1/commons-cli-1.3.1.jar",
)
# org.apache.hadoop:hadoop-yarn-client:jar:2.6.0

maven_jar(
    name = "commons_cli_commons_cli",
    artifact = "commons-cli:commons-cli:1.2",
    sha1 = "2bf96b7aa8b611c177d329452af1dc933e14501c",
)

The first version contains org.apache.commons.cli.Option.builder() while the second not.

How to let bazel use the correct version of jar?

**Comment by laszlocsomor** [comment] 2016-09-21 11:45
Indeed, it seems the older version is in runtime deps, the newer version is in normal deps, and the runtime deps have priority at runtime. Repro:

`BUILD` file:
```
# The target that I employed to build the v1 and v2 jars
#java_binary(
#    name = "lib-v2",
#    srcs = ["Lib.java"],
#    main_class = "dummy",
#)

java_binary(
    name = "main",
    srcs = ["Main.java"],
    main_class = "issue1798.Main",
    deps = [":lib-v2"],
    # runtime_deps = [":lib-v1"], # *** uncomment this line to see the bug ***
)

java_import(
    name = "lib-v1",
    jars = ["lib-v1_deploy.jar"],
)

java_import(
    name = "lib-v2",
    jars = ["lib-v2_deploy.jar"],
)
```

`Main.java`:
```
package issue1798;

public final class Main {
  public static void main(String[] args) {
    System.out.printf(
        "Classpath=%s\nLib version=%d\n",
        System.getProperty("java.library.path"),
        new Lib().version());
  }
}
```

`Lib.java`:
```
package issue1798;

public final class Lib {
  public int version() {
    return 2;  // was 1 for the v1 jar
  }
}
```

If I bazel run the binary, it prints "version=2". If I uncomment the `runtime_deps` line, it prints "version=1".

**Comment by laszlocsomor** [comment] 2016-09-21 11:48
@ahumesky : I'm not sure if this is your domain, please feel free to reassign or send back to me.

**Comment by ahumesky** [comment] 2016-09-21 16:15
Does taking the old version out of the deps of the java_binary fix it?

**Comment by is03wlei** [comment] 2016-09-22 04:19
But in my BUILD, it doesn't include old version as dependency. The old version is a transitive dependency of one of my runtime dependency.

By the way, is it a bug for sure? If yes, when could you fix it?

**Comment by ahumesky** [comment] 2016-09-22 18:24
I see, so it doesn't look like a bug in bazel. Can you try removing version 1.2 and have the transitive dependency depend on 1.3.1? You could also remove 1.3.1 and have your code use 1.2. Ultimately it comes down to the classpath, and one version has to win, otherwise you'll have to play tricks like using Jar Jar

**Comment by is03wlei** [comment] 2016-09-23 03:00
I think it's very common for transitive dependencies conflict. It should be reasonable for bazel supporting this. And maven support this also.

**Comment by ahumesky** [comment] 2016-09-23 20:20
It's not clear to me what's not supported here. I'm assuing these rules came from generate_workspace. If it sees two versions of the same library, it can't know which one will work. Worse, it's possible that neither choice will work. I suggest trying to converge on one version. As far as I know, maven resolves conflicts the same way: it picks one of the versions. You otherwise have to manually configure which version to use.

**Comment by ulfjack** [comment] 2016-12-01 11:44
You can override at the java_binary level which version should win by manually adding a dependency on the right version. Bazel has a specific order of how it arranges the classpath, and in the presence of multiple versions of the same library, a specific one will win. Unless you have a better proposal, I'm closing this as working as intended.

**Closed by ulfjack** 2016-12-01 11:44 UTC
Labels: Under investigation
