### ISSUE TITLE
`query --output build` prints macro definition line instead of actual target location

### ISSUE THREAD

**Issue by schroederc** [bazelbuild/bazel#227] opened 2015-06-04 18:20 UTC
This may be working as intended, but I think it should be possible for `bazel query --output build` to list the actual target definition location in the BUILD file vs. where a macro generates the underlying native target.

For instance, the first target below is a macro leading back to `tools/build_rules/genproto.bzl` instead of `kythe/proto/BUILD`.

```
bazel query --output build 'set(//kythe/proto:claim_proto //kythe/java/com/google/devtools/kythe/util)'
# <redacted>/tools/build_rules/genproto.bzl:141:3
proto_package(
  name = "claim_proto",
  src = "//kythe/proto:claim.proto",
  deps = ["//kythe/proto:storage_proto"],
)

# <redacted>/kythe/java/com/google/devtools/kythe/util/BUILD:3:1
java_library(
  name = "util",
  deps = ["//kythe/proto:storage_proto_java", "//third_party/guava:guava", "//third_party/proto:protobuf_java"],
  srcs = ["//kythe/java/com/google/devtools/kythe/util:DeleteRecursively.java", "//kythe/java/com/google/devtools/kythe/util:KytheURI.java", "//kythe/java/com/google/devtools/kythe/util:Span.java"],
)
```

**Comment by damienmg** [comment] 2015-06-09 09:55
Laurent: is that a bug or WAI? It should be documented if WAI.

**Comment by damienmg** [comment] 2015-06-19 12:07
laurentlb: ping?

**Comment by laurentlb** [comment] 2015-06-22 14:18
Working as intended. Printing the macro definition line instead is a feature.

**Comment by schroederc** [comment] 2015-06-22 15:38
Can we get the other feature as well?  With a flag?

**Comment by laurentlb** [comment] 2015-06-22 16:12
We want to avoid having too many flags. We can show both locations in the output.

**Comment by schroederc** [comment] 2015-06-22 16:12
That sounds even better to me.  Thanks! :-)

**Comment by dslomov** [comment] 2016-12-08 19:06
"Improve error messages" drive

**Comment by meisterT** [comment] 2020-05-14 16:33
This should be fixed with the flag `--record_rule_instantiation_callstack`.
https://docs.bazel.build/versions/master/command-line-reference.html#flag--record_rule_instantiation_callstack

**Closed by meisterT** 2020-05-14 16:33 UTC
Labels: P3, team-Starlark, type: feature request
