### ISSUE TITLE
minimal download breaks stable-status

### ISSUE THREAD

**Issue by aherrmann** [bazelbuild/bazel#8385] opened 2019-05-17 16:29 UTC
### Description of the problem:

The minimal download flags
```
build --experimental_inmemory_jdeps_files
build --experimental_inmemory_dotd_files
build --experimental_remote_download_outputs=minimal
```
on Bazel 0.25.2 seem to break the stable-status feature. I'm observing the following error

```
ERROR: Failed to run workspace status command bazel_tools/workspace_status.sh: /home/aj/.cache/bazel/_bazel_aj/10d2a8446c92e5dc655eb18c02f185fb/execroot/com_github_digital_asset_daml/bazel-out/stable-status.txt (Permission denied)
```

(Forcefully removing the file temporarily resolves the problem.)

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Checkout https://github.com/digital-asset/daml/pull/442/commits/f6642ffcb61ceb3227d5ca0be6025cc935b878a3 and execute the following commands

```
. .envrc
bazel run //:buildifier
echo >> WORKSPACE
git add WORKSPACE
git commit -m 'dummy change'
bazel run //:buildifier
```

### What operating system are you running Bazel on?

OpenSUSE Tumbleweed 20190510

### What's the output of `bazel info release`?

release 0.25.2- (@non-git)

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

[Using Nix](https://github.com/digital-asset/daml/blob/78505ebbab06c0ebe62924a4c32da905ad7ba40f/nix/overrides/bazel/default.nix)

### Any other information, logs, or outputs that you want to share?

Not sure if related or not, but `bazel run` seems to be not working on some targets when using minimal downloads. E.g. on the same commit as above

```
$ bazel run damlc
...
ERROR: Non-existent or non-executable /home/aj/.cache/bazel/_bazel_aj/10d2a8446c92e5dc655eb18c02f185fb/execroot/com_github_digital_asset_daml/bazel
```

**Comment by mattklein123** [comment] 2019-08-15 23:10
FYI I'm still hitting this issue on bazel 0.28.1. Is there anything I can do to provide more info? When I manually delete the workspace file everything works fine.

**Comment by mattklein123** [comment] 2019-08-16 03:15
I verified that the above fix is in 0.28.1 so I guess it's some other issue. @buchgr LMK if you would like me to open a fresh issue on this.

**Comment by buchgr** [comment] 2019-08-16 08:06
Do you have a reproducer or is it the same as the initial bug report?

**Comment by mattklein123** [comment] 2019-08-16 15:17
@buchgr I don't have an exact reproducer, but the symptom is exactly the same as the original bug report. Let me know if there is any info I can provide. I've gotten around it right now by just deleting the stable-status.txt file before I run any build commands. I can remove that hack and help debug if you tell me what to look for.

**Comment by aherrmann** [comment] 2019-08-20 10:03
@buchgr I can still reproduce the issue with the same steps given in the original issue above on current master of digital-asset/daml@f11e09f60f. This is using 
```
$ bazel version
Build label: 0.28.1- (@non-git)
Build target: bazel-out/k8-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Tue Jan 1 00:00:00 1980 (315532800)
Build timestamp: 315532800
Build timestamp as int: 315532800
```
built with Nix as defined in the same repository.

**Comment by emfree** [comment] 2019-08-25 05:06
We ran into this as well. Not very familiar with the internals here, but it looks like the issue possibly goes like this:
- The `BazelWorkspaceStatusModule` calls `FileSystemUtils.maybeUpdateContent` on the `stable-status` file: https://github.com/bazelbuild/bazel/blob/4ba404f7ed0473df3f0effa016c107ef677464f6/src/main/java/com/google/devtools/build/lib/bazel/BazelWorkspaceStatusModule.java#L193-L197
- This in turn is a delete-plus-create on the file: https://github.com/bazelbuild/bazel/blob/4ba404f7ed0473df3f0effa016c107ef677464f6/src/main/java/com/google/devtools/build/lib/vfs/FileSystemUtils.java#L766-L770
- But when you have `experimental_remote_download_actions=minimal`, the delete doesn't actually happen. 
- This is because the delete is being handled by the `RemoteActionFileSystem`, which looks to have a simple typo in its `delete()` method, fixed with this patch:
```
diff --git a/src/main/java/com/google/devtools/build/lib/remote/RemoteActionFileSystem.java b/src/main/java/com/google/devtools/build/lib/remote/RemoteActionFileSystem.java
index 0491c2d954..6157b413a5 100644
--- a/src/main/java/com/google/devtools/build/lib/remote/RemoteActionFileSystem.java
+++ b/src/main/java/com/google/devtools/build/lib/remote/RemoteActionFileSystem.java
@@ -69,7 +69,7 @@ public class RemoteActionFileSystem extends DelegateFileSystem {
   @Override
   public boolean delete(Path path) throws IOException {
     RemoteFileArtifactValue m = getRemoteInputMetadata(path);
-    if (m != null) {
+    if (m == null) {
       return super.delete(path);
     }
     return true;
```

@buchgr does this seem reasonable?

**Closed** 2019-08-29 12:32 UTC
Labels: team-Remote-Exec, type: bug
