### ISSUE TITLE
#17545 might have broken bazel_tools in downstream pipelines

### ISSUE THREAD

**Issue by fweikert** [bazelbuild/bazel#17874] opened 2023-03-23 19:49 UTC
### Description of the bug:

The downstream pipeline (https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/2921) has several failures due to files in @bazel_tools failing to load `@rules_python//python:proto.bzl`:

- [Buildfarm Unit Tests](https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/2921#01870c3d-d701-4d1a-9a49-06e297100a81)
- [rules_kotlin](https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/2921#01870c3d-e30d-4f76-aa6b-51535ef68dfe)
- [rules_python](https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/2921#01870c3d-c7a2-499a-8ba3-2d274e4f9769)

The problems started in [#2895](https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/2895), which coincides with https://github.com/bazelbuild/bazel/pull/17545

**Comment by comius** [comment] 2023-03-27 12:59
The issue looks related to non-bzlmod usage and a requirement to load rules_python in some cases. Possible fix is to update WORKSPACE suffixes to load rules_python.

**Comment by comius** [comment] 2023-04-17 12:12
The problem is created because of an older rules_python imported through WORKSPACE in various project. I produced PRs to upgrade the version.

[ ] TODO: upgrade version in buildfarm when rules_oss_audit PR is accepted and released

**Comment by meteorcloudy** [comment] 2023-04-21 10:21
Bazel@HEAD + rules_kotlin@https://github.com/bazelbuild/rules_kotlin/commit/395a525429571f9af28b1c9bc0a545cb3fd4cae6 still failing:
https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/2972#0187a200-7f56-482d-a970-d0f12847ec3e

maybe more fixes are needed?

**Comment by comius** [comment] 2023-04-21 12:50
> maybe more fixes are needed?

rules_kotlin are still failing because they get an old version of rules_python from rules_proto... it's no-bzlmod dependency hell. Any advice how to fix this, without adding more mess into the system?

**Comment by meteorcloudy** [comment] 2023-04-21 12:53
Oh, do you mean the upgrade in https://github.com/bazelbuild/rules_kotlin/pull/958/files#diff-def3077745bf807244580cf012e9d27574b9f337415a6734a186572b424c3badR103 didn't actually take affect because rules_proto introduces an older python version in WORKSPACE first? If so, rules_kotlin needs to figure out a way to prefer the dependencies they declared.

**Comment by werkt** [comment] 2023-04-22 03:14
I'm late to this, but for buildfarm's front, it looks like we're not able to depend upon bazel_tools as a result of this change without drastic changes that incorporate bzlmod (which I'm just learning about) or specifying both rules_python and rules_proto, both of which we did without before this.

Am I missing something? Is there supposed to be an easier migration for us not using an experimental system?

**Comment by werkt** [comment] 2023-04-22 06:03
Some followup on this. I got local builds to work by importing your indicated rules_python versions, but those versions break python3.6 compatibility indicated https://github.com/bazelbuild/rules_python/issues/818, and this is the python version available on the support-indicated ubuntu1804 version matching bazel CI validation. Attempting to use the hermetic toolchain does not resolve the problem, and fails on our integration tests, which run as root under CI containers.

This is a pretty big headache for the invalidation of a previously working toolset under bazel_tools, which only indicates that it needs rules_python 0.4.0 under its MODULE, in disagreement with the requirement for @rules_python//python:proto.bzl, nonexistent at 0.4.0.

**Comment by werkt** [comment] 2023-04-22 15:00
I've removed the reference to @bazel_tools//src/main/protobuf. We will not be using it going forward due to this break and the forced obsolescence/explicit rules_python dependency for a target+language we are not using. Buildfarm should be passing in the disabled stream.

**Comment by meteorcloudy** [comment] 2023-05-03 12:50
https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/2995
I can confirm this issue has been fixed in rules_kotlin

**Closed by meteorcloudy** 2023-05-03 12:50 UTC
Labels: type: bug, P2, team-Rules-Python
