### ISSUE TITLE
bazel build failed in mac

### ISSUE THREAD

**Issue by liumilan** [bazelbuild/bazel#13833] opened 2021-08-12 07:58 UTC
mac version is 
Darwin-Pro.local 20.3.0 Darwin Kernel Version 20.3.0: Thu Jan 21 00:06:51 PST 2021; root:xnu-7195.81.3~1/RELEASE_ARM64_T8101 arm64
bazel version is bazel 4.1.0-homebrew
and when using bazel to build c++ code,it report Target '//:common_featurer' depends on toolchain '@local_config_cc//:cc-compiler-darwin_arm64', which cannot be found: no such target '@local_config_cc//:cc-compiler-darwin_arm64': target 'cc-compiler-darwin_arm64' not declared in package
how to fix it ?

**Comment by keith** [comment] 2021-08-12 18:41
Probably a duplicate of https://github.com/bazelbuild/bazel/issues/13514, you can test with the 4.2 RC to verify https://releases.bazel.build/4.2.0/rc3/index.html

**Closed** 2021-08-20 13:37 UTC
Labels: duplicate
