### ISSUE TITLE
Bazel does not respect http_proxy environment variable in respect to remote rest cache

### ISSUE THREAD

**Issue by bhuga** [bazelbuild/bazel#6428] opened 2018-10-17 21:37 UTC
### Description of the problem / feature request:

Bazel does not respect http_proxy environment variable in respect to remote rest cache

### Feature requests: what underlying problem are you trying to solve with this feature?

Use a HTTP proxy for a bazel remote cache

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

The smallest way to demonstrate the issue is to point the http proxy to one invalid server and the remote cache to another invalid server. I expect to see an error connecting to the proxy server, but instead I see an error connecting to the cache server. In this example, both ports 4445 and 4444 are closed on localhost.

Expected:
 Error connecting to localhost:4445
Actual:
 Error connecting to localhost:4444

```
$ http_proxy=http://localhost:4445 bazel build //proto/... --remote_rest_cache=http://127.0.0.1:4444
INFO: Analysed target //proto:foo_proto (13 packages loaded).
INFO: Found 1 target...
WARNING: Error reading from the remote cache:
Connection refused: localhost/127.0.0.1:4444
WARNING: Error writing to the remote cache:
Connection refused: localhost/127.0.0.1:4444
```

### What operating system are you running Bazel on?

Happens on both linux and darwin

### What's the output of `bazel info release`?

`release 0.17.2`

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

0.17.2 release

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

n/a

###  Have you found anything relevant by searching the web?

Not in regards to the remote cache explicitly. There seems to be a lot of info q&a floating around for http proxying of dependencies and transitive dependencies, but nothing about the remote cache.

### Any other information, logs, or outputs that you want to share?

> Replace these lines with your answer.
>
> If the files are large, upload as attachment or provide link.

**Comment by weixiao-huang** [comment] 2018-10-18 10:06
Do not use localhost for bazel's http_proxy. Because bazel will run in sandbox, localhost may be pointed to sandbox instead of local machine's localhost. Try to use local machine's ip to set http_proxy instead of localhost

**Comment by bhuga** [comment] 2018-10-18 14:58
>  Try to use local machine's ip to set http_proxy instead of localhost

This doesn't help. Bazel still tries to connect to the cache directly, instead of to the proxy.

```
$ http_proxy=http://192.168.0.18:4445 ./bazel build //proto/... --remote_rest_cache=http://192.168.0.18:4444
INFO: Analysed target //proto:test_proto (13 packages loaded).
INFO: Found 1 target...
WARNING: Error reading from the remote cache:
Connection refused: /192.168.0.18:4444
WARNING: Error writing to the remote cache:
Connection refused: /192.168.0.18:4444
```

If it's helpful, this test case is a minimization of a problem I found in a real-world situation where the proxy was not on the same host.

**Comment by weixiao-huang** [comment] 2018-10-18 15:17
Is your http_proxy listen on `0.0.0.0` rather than `localhost` ?

**Comment by bhuga** [comment] 2018-10-18 15:40
> Is your http_proxy listen on 0.0.0.0 rather than localhost ?

There's no proxy in this example. The example shows that bazel does not try to connect to the proxy at all. It should never attempt to connect to the remote cache at port 4444, only to the proxy at port 4445.

It's trying to connect to the wrong server. The example replicates if the proxy is on a different machine. I used this example because if the server is on another machine, a "minimal test case" involves TCP logs showing there is no attempt to connect to the proxy.

**Comment by pamgluss-slack** [comment] 2023-01-27 21:01
Hello, are there any updates on this issue? My team is still encountering it

**Comment by coeuvre** [comment] 2023-10-20 12:07
This feature request is about using address from env `HTTP_PROXY` for Http Cache. We currently only do it for repository fetching (see `ProxyHelper`). We could probably do similar thing in src/main/java/com/google/devtools/build/lib/remote/http/HttpCacheClient.java.

**Comment by coeuvre** [comment] 2023-10-20 12:50
Duplicate of https://github.com/bazelbuild/bazel/issues/11374.

**Closed by coeuvre** 2023-10-20 12:50 UTC
Labels: type: feature request, P3, team-Remote-Exec, help wanted
