### ISSUE TITLE
Make rlocation function works with wildcard [duplicate of #4334]

### ISSUE THREAD

**Issue by meteorcloudy** [bazelbuild/bazel#1533] opened 2016-07-19 14:55 UTC
For example, `junit_jar=$(rlocation io_bazel/third_party/junit/junit-*.jar)` should return the right result.

**Comment by dslomov** [comment] 2016-08-12 19:06
Is this still blocking 0.4?

**Comment by meteorcloudy** [comment] 2016-09-05 11:44
No

**Comment by laszlocsomor** [comment] 2018-03-28 14:45
Duplicate of https://github.com/bazelbuild/bazel/issues/4334

**Closed by laszlocsomor** 2018-03-28 14:45 UTC
Labels: P3, category: misc > misc, platform: windows, type: feature request
