### ISSUE TITLE
Allow specifying single target label for target visibility

### ISSUE THREAD

**Issue by alex-torok** [bazelbuild/bazel#17064] opened 2022-12-21 22:34 UTC
### Description of the feature request:

I would like to be able to specify that a target is only visible to a single other target. Currently, specifying a full target label in the target visibility yields the following error:

```
ERROR: Label '//path/to/single:target' does not refer to a package group.
```

The [visibility docs](https://bazel.build/versions/6.0.0/concepts/visibility#load-visibility) correctly note that only certain forms of labels are allowed.

### What underlying problem are you trying to solve with this feature?

A common pattern that I have seen to reduce duplication is to define a macro that handles creating multiple targets, setting up dependencies between them with the goal of the macro caller to end up with a single usable target.

A simple rough example of something this could be a macro that creates a proto target and a go proto library from a single call:

```python
def my_go_proto_lib(name, ...):
  proto_lib_name = name + "_proto"
  proto_library(
    name = proto_lib_name,
    srcs = [...],
    visibility = [":"+name], # This is not currently allowed!
  )
  go_proto_library(
    name = name,
    proto = ":" + proto_lib_name,
    ...
)
```

In this example, the `proto_library` target only exists to achieve the goal of creating the `go_proto_library`. I would like to be able to restrict its visibility _only_ to the created `go_proto_library` and not any other target in its package.

This is relevant, as callers to the macro can set up dependencies on these "macro-private" targets, which may go against the intent of the macro author and lead to it being more difficult to refactor the implementation of the macro. Changing the details of the macro-private targets could break consumers who were never supposed to know they existed in the first place.

This example of using a `go_proto_library` may be a bit contrived, but I hope it gets the point across.

### Which operating system are you running Bazel on?

linux

### What is the output of `bazel info release`?

release 5.3.1

### Have you found anything relevant by searching the web?

I searched the following terms through the bazel docs, only to find the note about visibility specifications being restricted to group-like target labels. I also searched through the github issues pages, the bazel slack, and the mailing list.

* "visibility Label does not refer to a package group" 
* "visibility specify single target label"
* "restrict visibility to one target"

The only relevant issue I was able to find was #7377, which is not quite relevant for my stated problem.

**Comment by brandjon** [comment] 2022-12-27 17:24
@comius fyi

So you're looking to restrict visibility at a sub-package-level granularity, so that macros can create macro-private targets.

We've considered the idea of macro-friendly visibility controls, such as

* macro-private targets, as described in this thread
* targets that are not created by the macro, but are visible to all targets that are created by the macro. This would help for an "implicit dependency" of the macro, like a compiler.

The problem is that it gets pretty complicated to define a model for how this kind of visibility would work in general. (I'd like to write a doc about it sometime.) For instance, the conversion from strings to labels gets pretty gnarly when you have to consider that the location where the conversion occurs impacts visibility permissions. A per-target visibility mechanism would be better in that regard but not support the implicit dep use case, and it would still be a complication compared to the package-level granularity we support today (for instance, you couldn't easily express this kind of visibility in a `package_group`).

For the moment I'm going to close this FR since it's not immediately on the agenda, but we are aware of the need for tighter visibility controls for macros in general. In the near future we'll be looking at ways to make rules more expressive and better serve some of the cases that macros are better at. This might reduce the need for macros and therefore make solving the macro visibility problem moot.

**Closed by brandjon** 2022-12-27 17:24 UTC
Labels: type: feature request, untriaged, team-Loading-API
