### ISSUE TITLE
java 1.8.0_162: java.util.MissingResourceException: Can't find bundle for base name com.google.errorprone.errors, locale en_US

### ISSUE THREAD

**Issue by roblg** [bazelbuild/bazel#4483] opened 2018-01-19 17:15 UTC
### Description of the problem / feature request:

On OSX, with java 1.8.0_162-b12 from Oracle, running bazel 0.9.0 `-without-jdk` installed via self-extractor or homebrew fails with an error. Earlier Java update versions work fine (e.g. u131). Bazel 0.9.0 with bundled JDK also works fine.

Error:

```
(09:04:29) ERROR: /Volumes/code/redfin/main/redfin.core.enums/BUILD:4:1: Building redfin.core.enums/libredfin.core.enums.jar (533 source files) failed (Exit 1): java failed: error executing command
  (cd /private/var/tmp/_bazel_robert.gay/69746c6b963d631c63554f7e842731c0/execroot/redfin_main && \
  exec env - \
    LC_CTYPE=en_US.UTF-8 \
  external/local_jdk/bin/java -XX:+TieredCompilation '-XX:TieredStopAtLevel=1' -Xbootclasspath/p:external/bazel_tools/third_party/java/jdk/langtools/javac-9-dev-r4023-3.jar -jar external/bazel_tools/tools/jdk/JavaBuilder_deploy.jar @bazel-out/darwin-fastbuild/bin/redfin.core.enums/libredfin.core.enums.jar-2.params)
java.lang.InternalError: Cannot find requested resource bundle for locale en_US
        at com.sun.tools.javac.util.JavacMessages.getBundles(JavacMessages.java:128)
        at com.sun.tools.javac.util.JavacMessages.getLocalizedString(JavacMessages.java:147)
        at com.sun.tools.javac.util.JavacMessages.getLocalizedString(JavacMessages.java:140)
        at com.sun.tools.javac.util.Log.localize(Log.java:788)
        at com.sun.tools.javac.util.Log.printLines(Log.java:586)
        at com.sun.tools.javac.api.JavacTaskImpl.handleExceptions(JavacTaskImpl.java:170)
        at com.sun.tools.javac.api.JavacTaskImpl.doCall(JavacTaskImpl.java:96)
        at com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:90)
        at com.google.devtools.build.buildjar.javac.BlazeJavacMain.compile(BlazeJavacMain.java:107)
        at com.google.devtools.build.buildjar.SimpleJavaLibraryBuilder$1.invokeJavac(SimpleJavaLibraryBuilder.java:105)
        at com.google.devtools.build.buildjar.ReducedClasspathJavaLibraryBuilder.compileSources(ReducedClasspathJavaLibraryBuilder.java:54)
        at com.google.devtools.build.buildjar.SimpleJavaLibraryBuilder.compileJavaLibrary(SimpleJavaLibraryBuilder.java:108)
        at com.google.devtools.build.buildjar.SimpleJavaLibraryBuilder.run(SimpleJavaLibraryBuilder.java:116)
        at com.google.devtools.build.buildjar.BazelJavaBuilder.processRequest(BazelJavaBuilder.java:105)
        at com.google.devtools.build.buildjar.BazelJavaBuilder.runPersistentWorker(BazelJavaBuilder.java:67)
        at com.google.devtools.build.buildjar.BazelJavaBuilder.main(BazelJavaBuilder.java:45)
Caused by: java.util.MissingResourceException: Can't find bundle for base name com.google.errorprone.errors, locale en_US
        at java.util.ResourceBundle.throwMissingResourceException(ResourceBundle.java:1573)
        at java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1396)
        at java.util.ResourceBundle.getBundle(ResourceBundle.java:854)
        at com.sun.tools.javac.util.JavacMessages.lambda$add$0(JavacMessages.java:106)
        at com.sun.tools.javac.util.JavacMessages.getBundles(JavacMessages.java:125)
        ... 15 more
```

* Install bazel 0.9.0-without-jdk, or via homebrew
* Install Java 1.8_162
* Set JAVA_HOME to 1.8_162
* `bazel shutdown` (just to ensure bazel is started w/ Java 1.8_162 in the next step)
* `bazel build <any java_* target>` fails with the above error.

bazel shutdown + switching JAVA_HOME back to an earlier Java update + bazel build will succeed.

### What operating system are you running Bazel on?

OSX Sierra

### What's the output of `bazel info release`?

`release 0.9.0`

###  Have you found anything relevant by searching the web?

Nothing obviously relevant to bazel

**Comment by ubrandt** [comment] 2018-01-20 18:03
I'm hitting the same problem on RHEL6 with the same version of Java and bazel.
Switching back to jdk1.8.0_152 solved the issue.

**Comment by duelinmarkers** [comment] 2018-01-22 15:52
Ditto on Debian Jessie. `bazel info release` -> `release 0.9.0`. `java -version` -> 
```
java version "1.8.0_161"
Java(TM) SE Runtime Environment (build 1.8.0_161-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.161-b12, mixed mode)
```

**Comment by ittaiz** [comment] 2018-01-25 10:00
@cushon why did you re-open it? If I use Bazel HEAD then it's resolved?

**Comment by werkt** [comment] 2018-01-25 17:52
This hit ubuntu 14.04 as well. The instructions for installing bazel which include the webupd8team reference to install the `oracle-java8-installer` will be subject to this and fail to successfully build jarfiles until this is fixed. 0.9.1 with 860af5be10b6bad68144d9d2d34173e86b40268c is probably justified to present a working release.

**Comment by cushon** [comment] 2018-01-25 18:51
It's fixed a head. I re-opened to make sure we included the fix in 0.10, which we have.

@iirina for the question about a patch release, but I think 0.10 is coming soon so that's probably sufficient.

Also - this is only an issue with the `-without-jdk` binaries, right? The built in jvm doesn't have this problem.

**Comment by ittaiz** [comment] 2018-01-25 19:00
Don't know. But I can say we hit this in the "without" version.

**Comment by werkt** [comment] 2018-01-25 19:19
Based on the description of `-without-jdk` and the behavior of the ubuntu ppa bazel installer and it depending upon a jdk from another package provider, it would seem that this is `-without-jdk` (not sure if there is a deb release with the `built in jvm`)

**Comment by paladox** [comment] 2018-01-25 23:28
We are also hitting this @ gerrit when testing some changes to allows us to update ci. I found it failing on my mac.

with

java.lang.InternalError: Cannot find requested resource bundle for locale en_GB
	at com.sun.tools.javac.util.JavacMessages.getBundles(JavacMessages.java:128)
	at com.sun.tools.javac.util.JavacMessages.getLocalizedString(JavacMessages.java:147)
	at com.sun.tools.javac.util.JavacMessages.getLocalizedString(JavacMessages.java:140)
	at com.sun.tools.javac.util.Log.localize(Log.java:788)
	at com.sun.tools.javac.util.Log.printLines(Log.java:586)
	at com.sun.tools.javac.api.JavacTaskImpl.handleExceptions(JavacTaskImpl.java:170)
	at com.sun.tools.javac.api.JavacTaskImpl.doCall(JavacTaskImpl.java:96)
	at com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:90)
	at com.google.devtools.build.buildjar.javac.BlazeJavacMain.compile(BlazeJavacMain.java:107)
	at com.google.devtools.build.buildjar.SimpleJavaLibraryBuilder$1.invokeJavac(SimpleJavaLibraryBuilder.java:105)
	at com.google.devtools.build.buildjar.ReducedClasspathJavaLibraryBuilder.compileSources(ReducedClasspathJavaLibraryBuilder.java:54)
	at com.google.devtools.build.buildjar.SimpleJavaLibraryBuilder.compileJavaLibrary(SimpleJavaLibraryBuilder.java:108)
	at com.google.devtools.build.buildjar.SimpleJavaLibraryBuilder.run(SimpleJavaLibraryBuilder.java:116)
	at com.google.devtools.build.buildjar.BazelJavaBuilder.processRequest(BazelJavaBuilder.java:105)
	at com.google.devtools.build.buildjar.BazelJavaBuilder.runPersistentWorker(BazelJavaBuilder.java:67)
	at com.google.devtools.build.buildjar.BazelJavaBuilder.main(BazelJavaBuilder.java:45)
Caused by: java.util.MissingResourceException: Can't find bundle for base name com.google.errorprone.errors, locale en_GB
	at java.util.ResourceBundle.throwMissingResourceException(ResourceBundle.java:1573)
	at java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1396)
	at java.util.ResourceBundle.getBundle(ResourceBundle.java:854)
	at com.sun.tools.javac.util.JavacMessages.lambda$add$0(JavacMessages.java:106)
	at com.sun.tools.javac.util.JavacMessages.getBundles(JavacMessages.java:125)
	... 15 more

https://gerrit-review.googlesource.com/#/c/gerrit/+/152792/

**Comment by iirina** [comment] 2018-01-26 09:00
The fix is cherry picked for bazel 0.10.0. It will be released next week.

**Comment by paladox** [comment] 2018-01-26 10:59
Hi, if I install Basel 0.10 rc on the Mac, will it update to the stable release from home brew next week when it’s released please?

**Comment by barlevalon** [comment] 2018-01-29 20:10
> Also - this is only an issue with the -without-jdk binaries, right? The built in jvm doesn't have this problem.
Is that verified? We seem to be hitting this with the jdk-bundled version as well.

**Comment by paladox** [comment] 2018-01-29 20:39
bazel 0.10 rc6 fixes this for me.

**Comment by ryanphung** [comment] 2018-01-30 07:25
I'm hitting the same issue as well, on MacOS Sierra `10.21.6`, bazel `0.9.0-homebrew`, and different versions of JDK `jdk1.8.0_131.jdk`, `jdk1.8.0_152.jdk`, `jdk1.8.0_161.jdk`.

**Comment by ryanphung** [comment] 2018-01-30 08:06
Actually I realize that even though I have set `$JAVA_HOME` to the different versions of jdk, and `java -version` gives the correct version, `bazel info` still gives the wrong jdk version. Does anyone have any idea if there are some settings missing?

```
$ java -version
java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)
```

```
$ bazel info
....................................................................
bazel-bin: /private/var/tmp/_bazel_ryanphung/dddf2bc98ad4db4ca33c334424ab7c5f/execroot/org_tensorflow/bazel-out/darwin-opt/bin
bazel-genfiles: /private/var/tmp/_bazel_ryanphung/dddf2bc98ad4db4ca33c334424ab7c5f/execroot/org_tensorflow/bazel-out/darwin-opt/genfiles
bazel-testlogs: /private/var/tmp/_bazel_ryanphung/dddf2bc98ad4db4ca33c334424ab7c5f/execroot/org_tensorflow/bazel-out/darwin-opt/testlogs
character-encoding: file.encoding = ISO-8859-1, defaultCharset = ISO-8859-1
command_log: /private/var/tmp/_bazel_ryanphung/dddf2bc98ad4db4ca33c334424ab7c5f/command.log
committed-heap-size: 253MB
execution_root: /private/var/tmp/_bazel_ryanphung/dddf2bc98ad4db4ca33c334424ab7c5f/execroot/org_tensorflow
gc-count: 5
gc-time: 119ms
install_base: /var/tmp/_bazel_ryanphung/install/003b889e46a233098219d1a802cd397d
java-home: /Library/Java/JavaVirtualMachines/jdk1.8.0_161.jdk/Contents/Home/jre
java-runtime: Java(TM) SE Runtime Environment (build 1.8.0_161-b12) by Oracle Corporation
java-vm: Java HotSpot(TM) 64-Bit Server VM (build 25.161-b12, mixed mode) by Oracle Corporation
max-heap-size: 3817MB
message_log: /private/var/tmp/_bazel_ryanphung/dddf2bc98ad4db4ca33c334424ab7c5f/message.log
output_base: /private/var/tmp/_bazel_ryanphung/dddf2bc98ad4db4ca33c334424ab7c5f
output_path: /private/var/tmp/_bazel_ryanphung/dddf2bc98ad4db4ca33c334424ab7c5f/execroot/org_tensorflow/bazel-out
package_path: %workspace%
release: release 0.8.1-homebrew
server_pid: 89268
used-heap-size: 94MB
workspace: /Users/ryanphung/Projects/Learning/TensorFlow/tensorflow
```

**Comment by beeva-franciscoescribano** [comment] 2018-01-30 08:32
Test bazel shutdown and rebuild the project. It worked for me

**Comment by ryanphung** [comment] 2018-01-30 08:40
Thanks, I tried `bazel shutdown` but it doesn't work and `bazel info java-home` still shows the wrong version of jdk.

**Comment by YURIJTJ** [comment] 2018-01-30 08:43
where can i get old version of jdk?  I can't find it.

**Comment by ryanphung** [comment] 2018-01-30 08:44
You can get old version of JDK8 from here: http://www.oracle.com/technetwork/java/javase/downloads/java-archive-javase8-2177648.html

**Comment by ryanphung** [comment] 2018-01-30 09:26
Alright, I managed to resolved it, here is what I did:

1. Uninstall `jdk1.8.0_161.jdk`
2. Install `jdk1.8.0_152.jdk`
3. Uninstall `bazel 0.9.0`
4. Reinstall `bazel 0.9.0`
5. It doesn't matter what `JAVA_HOME` is set to, it seems when bazel is installed it set `java-home` to the latest version of jdk.
6. Try to run `bazel info java-home`:

```
$ bazel info java-home
/Library/Java/JavaVirtualMachines/jdk1.8.0_152.jdk/Contents/Home/jre
```

**Comment by oswcab** [comment] 2018-02-01 12:30
Does 0.10 solve this?

**Comment by davido** [comment] 2018-02-01 13:42
@oswcab Yes. Check @paladox comment: "bazel 0.10 rc6 fixes this for me."

**Closed** 2018-02-01 17:24 UTC
Labels: category: rules > java

**Comment by davido** [comment] 2018-02-02 04:43
[Yes](https://github.com/bazelbuild/bazel/releases/tag/0.10.0).

**Comment by tongchao199** [comment] 2018-03-18 14:55
### my  env, reslove this problesm  
* CentOS Linux release 7.4.1708 (Core)
* 3.10.0-693.5.2.el7.x86_64
* glibc-2.17-196.el7_4.2.x86_64
* gcc-4.8.5-16.el7_4.2.x86_64
* gcc-c++-4.8.5-16.el7_4.2.x86_64
* java-1.8.0-openjdk-1.8.0.151-1.b12.el7_4.x86_64
