### ISSUE TITLE
Protobuf documentation is empty

### ISSUE THREAD

**Issue by endobson** [bazelbuild/bazel#608] opened 2015-11-16 03:42 UTC
There are no rules documented in the protocol buffer section of the docs. If there are none, then it probably shouldn't be on the left hand nav.

http://bazel.io/docs/be/protocol-buffer.html

**Comment by damienmg** [comment] 2015-11-16 09:18
Duplicate of #52

**Closed by damienmg** 2015-11-16 09:18 UTC
