### ISSUE TITLE
Bazel CI: Envoy fails with Bazel@HEAD

### ISSUE THREAD

**Issue by meteorcloudy** [bazelbuild/bazel#9464] opened 2019-10-02 07:51 UTC
https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/1217#4b8bdfb8-d066-49b4-a8a7-28267558bbcf
```

ERROR: An error occurred during the fetch of repository 'envoy_api':
--
  | Traceback (most recent call last):
  | File "/var/lib/buildkite-agent/builds/bk-docker-3f8k/bazel-downstream-projects/envoy/bazel/api_binding.bzl", line 13
  | ctx.symlink(ctx.path(ctx.attr.api).dirname.g...), ...)
  | File "/var/lib/buildkite-agent/builds/bk-docker-3f8k/bazel-downstream-projects/envoy/bazel/api_binding.bzl", line 13, in ctx.symlink
  | ctx.path(ctx.attr.api)
  | Unable to load package for //api:BUILD: Package is considered deleted due to --deleted_packages
  | ERROR: no such package '@envoy_api//bazel': Traceback (most recent call last):
  | File "/var/lib/buildkite-agent/builds/bk-docker-3f8k/bazel-downstream-projects/envoy/bazel/api_binding.bzl", line 13
  | ctx.symlink(ctx.path(ctx.attr.api).dirname.g...), ...)
  | File "/var/lib/buildkite-agent/builds/bk-docker-3f8k/bazel-downstream-projects/envoy/bazel/api_binding.bzl", line 13, in ctx.symlink
  | ctx.path(ctx.attr.api)
  | Unable to load package for //api:BUILD: Package is considered deleted due to --deleted_packages


```

Culprit Finder:
https://buildkite.com/bazel/culprit-finder/builds/217#55acd441-93e2-46bb-8f59-1a421fd91a6b

Suspected culprit: f371448bf047b294557f6fc1ecec04dcefc62f93

**Comment by aehlig** [comment] 2019-10-02 09:45
In my opinion, the failure is working as intended and the fact that this ever worked was a bug fixed by https://github.com/bazelbuild/bazel/commit/f371448bf047b294557f6fc1ecec04dcefc62f93.

Envoy, at the tested commit https://github.com/envoyproxy/envoy/commit/abb14cdd7aa50d0a54a9288420a098314581782a does the following.
- It has a `.bazelrc` that [tells bazel to pretend the directory `api` does not exist](https://github.com/envoyproxy/envoy/blob/abb14cdd7aa50d0a54a9288420a098314581782a/.bazelignore#L1)
- It [declares `envoy` as the name of the main repository](https://github.com/envoyproxy/envoy/blob/abb14cdd7aa50d0a54a9288420a098314581782a/WORKSPACE#L1)
- It uses a [label `@envoy//api:BUILD`](https://github.com/envoyproxy/envoy/blob/abb14cdd7aa50d0a54a9288420a098314581782a/bazel/api_binding.bzl#L18).
However, by the instructions in the `.bazelignore` bazel must not resolve that label, as it has to pretend that the directory `api` of the main repository does not exist.

So, from bazel side the error is actually correct; this should be handled as a bug in envoy.

**Comment by aehlig** [comment] 2019-10-02 09:48
Over to envoy as https://github.com/envoyproxy/envoy/issues/8455

**Comment by meteorcloudy** [comment] 2019-10-02 09:48
Thanks for the explanation and filing the bug to Envoy!

**Closed by aehlig** 2019-10-02 09:48 UTC
