### ISSUE TITLE
$(location) and $(locations) do not properly quote file paths

### ISSUE THREAD

**Issue by BranLwyd** [bazelbuild/bazel#3475] opened 2017-07-30 05:32 UTC
### Description of the problem / feature request / question:
When using `$(locations)` [or `$(location)`] to e.g. build the command to use in a `genrule` target, the expanded locations are not quoted. This means that it is not possible to use paths that contain spaces with `$(locations)` when building commands, since they can't be correctly parsed by the tool you are calling.

### If possible, provide a minimal example to reproduce the problem:
Create a repository like:
```
dir with spaces/foo
dir with spaces/bar
WORKSPACE
BUILD
```

...with a BUILD file like:
```
filegroup(
  name = "files",
  srcs = glob(["dir with spaces/**/*"]),
)

genrule(
  name = "example",
  srcs = [":files"],
  outs = ["foo"],
  cmd = "echo FILES: $(locations //:files) | tee $@",
)
```

Running `bazel build //:example`, I would expect to get `FILES: "dir with spaces/foo" "dir with spaces/bar"`, but instead I get `FILES: dir with spaces/foo dir with spaces/bar`. Were I running some command that was expecting to receive file paths as an argument, the command would not be able to parse these paths correctly.

### Environment info
* Operating System:
Linux (Ubuntu 16.10)

* Bazel version (output of `bazel info release`):
release 0.5.3

###  Have you found anything relevant by searching the web?
No (I found https://github.com/bazelbuild/bazel/issues/374 but that issue is about allowing arbitrary characters in file names, not quoting of names)

**Comment by katre** [comment] 2017-07-31 15:08
Looks like the issue is in LocationExpander, specifically here: https://github.com/bazelbuild/bazel/blob/639bba946ea01f5cf0a2cdb51c46012a602814a1/src/main/java/com/google/devtools/build/lib/analysis/LocationExpander.java#L197

Should be a simple fix (and some added tests).

**Comment by katre** [comment] 2017-08-03 14:21
Should be fixed in https://github.com/bazelbuild/bazel/commit/aacc305ba5a2035155cdc9afc9a300c739282829.

**Closed by katre** 2017-08-03 14:21 UTC
Labels: category: extensibility > skylark, P2, type: bug

**Comment by BranLwyd** [comment] 2017-08-03 15:28
Thanks for the quick fix!

**Comment by ensonic** [comment] 2018-05-09 13:47
Thanks indeed for the fix, can we also do the quoting if the files contain '$'/'@'. We have a case where a node module defines a file called '$data.json'.

**Comment by katre** [comment] 2018-05-09 13:48
This issue is very old. Please open a new issue (feel free to reference this one), and we can see what can be done.
