### ISSUE TITLE
py_binary on Linux uses system Python despite explicit Python toolchain specified

### ISSUE THREAD

**Issue by konste** [bazelbuild/bazel#14159] opened 2021-10-24 13:45 UTC
### Description of the problem / feature request:

`py_binary` rule creates self-extracting Python executables. By default it uses system Python, which is not hermetic. Explicitly specified Python toolchain pointing to particular interpreter supposed to fix that. It totally works on Mac and Windows. Does not work on Linux.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

I have created [relatively compact repro demonstrating the problem](https://github.com/Bazel-snippets/py_binary_without_system_python). Repro supports Mac, Windows and Linux. Command to run is `bazel run sample`. If you remove (or temporary disable) system Python the repro keeps functioning on Mac and Windows, but fails on Linux, because self-extracting executable is looking for `/usr/bin/env python3` ignoring registered Python toolchain.  

### What operating system are you running Bazel on?

OSX - works
Windows - works
Linux - fails

### What's the output of `bazel info release`?

5.0.0-pre.20211011.2

**Comment by Wyverald** [comment] 2021-11-02 11:22
cc @brandjon

**Comment by comius** [comment] 2021-11-24 13:00
As you said the cuprit is change https://github.com/bazelbuild/bazel/pull/11201/files which makes Python's stub template incompatible with systems that can only "bootstrap" with Python2.

Since Python2 is only used as a bootstrap to the hermetic version, I propose that change is rolled back.

**Comment by philwo** [comment] 2021-11-24 13:16
> Bazel 5 now requires Python 3 and we don't have it installed and that's how we got the failure switching to 5.0.

Then I would recommend to install Python 3 in addition or instead of Python 2 on your build agents. This seems like a much easier and less risky fix than rolling back this change? Rolling back this change would break systems that don't have a "python" binary anymore, but do have a "python3" binary. Newer Linux distributions no longer have a "python" binary installed by default.

The current implementation of py_binary requires a system Python. It sounds like fixing the root cause of your issue actually means not requiring any system Python in the stub script - which sounds great! Maybe we can write a hermetic Python launcher that does not require Python itself, I think I would really like that.

But falling back to Python 2 is not the solution here.

**Comment by meteorcloudy** [comment] 2021-11-24 13:32
@konste 
https://docs.bazel.build/versions/main/be/python.html#:~:text=no%20default%20value.-,stub_shebang,-String%3B%20optional%3B%20default
The `stub_shebang` attribute of `python_runtime` could probably help you.

**Comment by JayBazuzi** [comment] 2021-11-24 18:55
@comius I don't think that closing this issue is the right move.

The request was not "fall back to Python 2". The request was "fix the fact that py_binary on Linux uses system Python despite explicit Python toolchain specified" and I think that's still broken and still a legit request.

Can you please reactivate this issue?

**Comment by comius** [comment] 2021-11-25 06:25
As I understand how things work is, that py_binary is using a bootstrap/stub script, that uses system Python to start the Python that is defined by the toolchain.

There was a change to that bootstrap script to use Python 3 as the world is moving to it. And there is a workaround (the` --stub_shebang`), that lets you fall back to use Python 2 for bootstrapping.

So the issue should be called "py_binary uses Python to bootstrap". I believe the same thing happen on all operating system and that the Python defined by the toolchain is used.

It is possible to rewrite the stub script to for example use shell and avoid using Python for bootstrapping altogether. I'm guessing the script was written well before toolchainisation, and it is an understandable decision to use Python at the time.

**Comment by konste** [comment] 2021-11-25 12:40
But, but... it does work on Mac and Windows (uses Python from the toolchain for bootstrapping) only on Linux it is broken. That is why I suspect it to be a bug rather than a feature request. I doubt implementation is very different for Mac and Linux.

**Comment by comius** [comment] 2021-11-25 16:14
> But, but... it does work on Mac and Windows (uses Python from the toolchain for bootstrapping) only on Linux it is broken. That is why I suspect it to be a bug rather than a feature request. I doubt implementation is very different for Mac and Linux.

I don't see from the code how it could work on Mac on Windows; nothing different is going on - also system Python is needed. Perhaps I'm missing something. 

Is it possible that you have Python somehow available on the system on Windows and Mac (in the path or some kind of a system handler for py files) and the bootstrap script uses it?

**Comment by JayBazuzi** [comment] 2021-11-25 19:49
Looking at the code linked above, it seems clear that the Windows is quite different from the other operating systems, and I can confirm that the issue does not exist on Windows. 

I just ran this sequence on a brand new, clean Windows VM with no python, and it worked fine.

1. Install https://github.com/git-for-windows/git/releases/download/v2.34.1.windows.1/Git-2.34.1-64-bit.exe
2. git clone https://github.com/Bazel-snippets/py_binary_without_system_python.git
3. Download https://releases.bazel.build/5.0.0/rc2/bazel-5.0.0rc2-windows-x86_64.exe
4. bazel run sample

**Comment by meteorcloudy** [comment] 2021-11-26 08:53
@JayBazuzi Can you try to use the `stub_shebang` of `python_runtime`. The reason this is failing because we use [a Python script](https://cs.opensource.google/bazel/bazel/+/master:src/main/java/com/google/devtools/build/lib/bazel/rules/python/python_stub_template.txt) with a shebang to launch the actual Python program. On older systems, `python3` doesn't exist, on newer system `python` doesn't exist, but we decided to move to `python3` since python2 is deprecated. On Windows, this is no problem because we use a C++ binary to launch the python program.
On Linux, you can also probably solve this my making a symlink of `/usr/bin/python -> /usr/bin/python3` (or similar). This will not affect the actual python binary you use to launch your own python program, it's just to make sure the launcher script can run successful.

**Comment by JayBazuzi** [comment] 2021-11-26 20:15
Hi @meteorcloudy the workaround of `stub_shebang` was effective, which unblocks our adoption of Bazel 5. That's great!

I still think this issue should remain open because the underlying problem still exists and breaks hermeticity, but for now we will apply the workaround to make it work like Bazel 4.

Thanks!

**Comment by meteorcloudy** [comment] 2021-11-29 09:35
I don't think there is much else we can do from Bazel side, but when most systems have `/usr/bin/python3` installed, it's no longer a problem.

**Closed by meteorcloudy** 2021-11-29 09:35 UTC
Labels: type: bug, P4, team-Rules-Python

**Comment by JayBazuzi** [comment] 2021-11-29 14:56
Why does this work correctly on Windows (without requiring a machine-installed Python) but it can't be fixed for Mac and Linux?

**Comment by meteorcloudy** [comment] 2021-11-29 15:13
Let me try it again:

On Unix systems, we depend on the shebang to start the python launcher script, originally it was `/usr/bin/python`, but as the world moving to python3, more and more systems don't have `/usr/bin/python`, instead `/usr/bin/python3` is getting more popular. Eventually, no one would be using `/usr/bin/python`. The launcher script can either support `python` or `python3`, but not both. Our only option is to make the shebang configurable, which is the `stub_shebang` attribute for.

On Windows, we don't depend on any shebang (it doesn't exist), therefore it's not a problem.

**Comment by JayBazuzi** [comment] 2021-11-29 16:01
Pardon my naivete...

On Windows you don't depend on any Python. Why can't that be done on Mac
and Linux?
