### ISSUE TITLE
cc_inc_library does not work for sub-directory BUILD files.

### ISSUE THREAD

**Issue by Helcaraxan** [bazelbuild/bazel#2078] opened 2016-11-11 11:45 UTC
#### Description
When specifying a `cc_inc_library` target in a sub-directory of the project tree the necessary `-I<path>` includes are generated correctly for dependent targets but the library's files are copied to the wrong directory. The path between the project's root directory and the one of which the `BUILD` declares the `cc_inc_library` is still pre-pended after the rule's prefix has been removed.

#### Expected result
Project compiles without error.

#### Observed output
For the MWE given below the output is as follows:
```
 -> bazel build //:main --verbose_failures
INFO: Found 1 target...
ERROR: /b/p/bazel-mwe/BUILD:3:1: C++ compilation of rule '//:main' failed: namespace-sandbox failed: error executing command 
  (cd /home/duco/.cache/bazel/_bazel_duco/0779d66785f6d7eee218bee64e3f1737/bazel-mwe && \
  exec env - \
    PATH=/usr/local/go/bin:/improbable/spatial:/usr/local/go/bin:/improbable/it/bin:/opt/idea/bin:/improbable/spatial:/improbable/tools/latest/linux:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/puppetlabs/bin:/snap/bin:/usr/local/go/bin \
  /home/duco/.cache/bazel/_bazel_duco/0779d66785f6d7eee218bee64e3f1737/bazel-mwe/_bin/namespace-sandbox @/home/duco/.cache/bazel/_bazel_duco/0779d66785f6d7eee218bee64e3f1737/bazel-mwe/bazel-sandbox/2716fe97-1adb-43f8-a8ee-a925029dc0fc-0.params -- /usr/bin/gcc -U_FORTIFY_SOURCE '-D_FORTIFY_SOURCE=1' -fstack-protector -Wall -Wl,-z,-relro,-z,now -B/usr/bin -B/usr/bin -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -iquote . -iquote bazel-out/local-fastbuild/genfiles -iquote external/bazel_tools -iquote bazel-out/local-fastbuild/genfiles/external/bazel_tools -Ibazel-out/local-fastbuild/include/foo/_/mylib -isystem external/bazel_tools/tools/cpp/gcc3 -no-canonical-prefixes -fno-canonical-system-headers -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' '-frandom-seed=bazel-out/local-fastbuild/bin/_objs/main/main.pic.o' -MD -MF bazel-out/local-fastbuild/bin/_objs/main/main.pic.d -fPIC -c main.c -o bazel-out/local-fastbuild/bin/_objs/main/main.pic.o).
main.c:3:29: fatal error: mylib/library.h: No such file or directory
compilation terminated.
Target //:main failed to build
INFO: Elapsed time: 0.127s, Critical Path: 0.06s
```

Emphasis on `-Ibazel-out/local-fastbuild/include/foo/_/mylib`. This is correct and as expected.

But:
```
 -> ls -R bazel-out/local-fastbuild/include/foo/_/mylib/
bazel-out/local-fastbuild/include/foo/_/mylib/:
foo

bazel-out/local-fastbuild/include/foo/_/mylib/foo:
library.h
```

As described above the `bar` prefix is correctly removed from the header of the `mylib` target but the `foo` path between `<root>/WORKSPACE` and `<root>/foo/BUILD` is still pre-pended.

#### Project structure
* `foo`
  * `bar`
    * `library.h`
  * `BUILD`
* `main.c`
* `BUILD`
* `WORKSPACE`

#### Code
* `main.c`
```
#include <stdio.h>
#include <mylib/library.h>

int main() {
  std::cerr << myConstInt << std::endl;
  return 0;
}
```
* `foo/bar/library.h`
```
const int myConstInt = 4;
```
* `foo/BUILD`
```
package(default_visibility = ["//visibility:public"])

cc_inc_library(
  name = "mylib",
  hdrs = ["bar/library.h"],
  prefix = "bar",
)
```
* `BUILD`
```
package(default_visibility = ["//visibility:public"])

cc_binary(
  name = "main",
  srcs = ["main.c"],
  deps = [ "//foo:library" ],
)
```

### Environment info
Reproducible on both Windows and Linux (OSX not tested) with Bazel 0.4

### Misc
This is not a duplicate of #1596 but it might have the same root cause.

**Comment by aehlig** [comment] 2016-11-11 13:20
As far as I can see, this is working as intended. [`cc_inc_library`](https://bazel.build/versions/master/docs/be/c-cpp.html#cc_inc_library) is supposed to strip precisely one directory level out, the one containing the version number. Can you explain what you are trying to achieve, as `cc_inc_library` might not be the right tool for that job.

cc @lberki  FYI.

**Comment by lberki** [comment] 2016-11-11 13:21
FWIW, `cc_inc_library` got open sourced sort of accidentally. I don't think it has a legitimate use in Bazel. Let's see if we can remove it...

**Comment by Helcaraxan** [comment] 2016-11-11 14:30
Basically I have an external library, checked in to our own code-base (for other valid reasons) that has a weird folder structure, similar to versioning numbers (which is why we want to remove part of the prefix).

For yet other reasons this library should be checked in at a sub-directory level instead of the top-level of the project tree as it is only used by a particular part of the project. Hence we do have the initial path from the project root that is now remaining in the generated folder tree.

**Comment by petemounce** [comment] 2016-11-14 15:52
@lberki if you remove `cc_inc_library` how would we replace it, please?

**Comment by lberki** [comment] 2016-11-16 15:21
@petemounce : we are currently concocting a plan for replacing it. Apparently, it's too widely used to just be removed like that.

**Comment by lberki** [comment] 2016-11-22 15:53
We cooked up a plan. It involves replacing `cc_inc_library` with a few extra attributes on `cc_library` which, in the grand scheme of things, are much more consistent:

https://docs.google.com/document/d/18qUWh0uUiJBv6ZOySvp6DEV0NjVnBoEy-r-ZHa9cmhU

Please take a look and comment.

**Comment by Helcaraxan** [comment] 2016-11-22 16:22
@lberki Just went over the document and this does seem to be a solid approach to the issue. It will also help unifying `cc_inc_library` and `cc_library` as they do seem to be just two things that just have a different point-of-view on the same problem.

**Comment by damienmg** [comment] 2016-12-05 10:27
@lberki Feel free to close this issue if there is no specific action item to it or recategorize

**Comment by lberki** [comment] 2016-12-05 14:11
I think I'll just close this now since `cc_library` has the new `strip_include_prefix` and `include_prefix` attributes, so any use of `cc_inc_library` should be replaced with it.

Please file new bugs if these new attributes don't work well for some reason.

**Closed by lberki** 2016-12-05 14:11 UTC
Labels: category: rules > C++, Under investigation
