### ISSUE TITLE
Add an option to `cc_*` rules that lets one specify include directories only for the current rule

### ISSUE THREAD

**Issue by lberki** [bazelbuild/bazel#2670] opened 2017-03-13 10:03 UTC
Currently, this is done by `copts=["-I<dir>"]` .This has two problems:

* The actual include path depends on whether the rule is in the main repository or not (it shouldn't, but it'll take a lot of time to fix that)
* It encodes knowledge about the compiler used in the BUILD file.

Thus, it'd be better to express this in a compiler-independent way just like we have the `includes` and `defines` attributes.

**Comment by dflems** [comment] 2017-03-13 17:28
This would solve a lot of problems we're having migrating a large legacy library to build with bazel. Having an option like `private_includes` or something of that nature on `cc_*` rules would be enormously beneficial and make our current setup less fragile.

**Comment by c-parsons** [comment] 2017-06-21 18:22
Any work going on with this?
I've looked, and it doesn't look like there's a good workaround for this other than an actual native code change.

IIUC, it just looks like we need an alternate attribute which acts identically to "includes" except that it does not propagate these values up to dependents.

**Comment by dflems** [comment] 2017-06-21 19:08
@c-parsons: We could work around it pretty readily if we had a way to get the path to the directory represented by the current `BUILD` file. I know you can get that from a skylark rule, but we use some pretty simple macro wrappers and that feels a bit overkill.

**Comment by c-parsons** [comment] 2017-06-21 19:17
Correct -- You can get it from a rule context either natively or in skylark.
But skylark macros don't have a rule context object -- they are not actual rules but simple expansions.
So unfortunately I don't think there's a workaround within a macro.

I agree that writing a skylark rule for this is overkill, especially when it would be infeasible to emulate cc_library except with the added attribute.
We're better off fixing this natively, IMO

**Comment by dflems** [comment] 2017-06-26 13:47
I think I was able to figure out a (perhaps less-than-ideal) workaround for this.

In our wrapper for `objc_library`, I added a new field called `private_includes`. If our macro sees this field, it creates a header-only `objc_library` and adds it to `non_propagated_deps` so the includes aren't passed to anyone who depends upon the library:

```python
def my_objc_library(**args):
    include_dirs = args.pop('private_includes', None)
    if include_dirs:
        priv_name = args['name'] + '_incl_private'
        native.objc_library(
            name = priv_name,
            includes = include_dirs,
            hdrs = native.glob([dir + '/**/*.h' for dir in include_dirs]),
            visibility = ['//visibility:private'],
        )
        args['non_propagated_deps'] = args.pop('non_propagated_deps', []) + [':' + priv_name]

    native.objc_library(**args)
```

@c-parsons Do you think this could serve as an interim solution until we get support for this natively?

**Comment by c-parsons** [comment] 2017-06-26 17:17
This is a really nice idea, indeed. This workaround LGTM. Does it work for you?

**Comment by dflems** [comment] 2017-06-26 17:19
@c-parsons: Yup, already migrated everything to use this approach 😄

**Comment by silvester747** [comment] 2017-10-12 08:28
The workaround using objc_library looks pretty good, but there does not seem to be an equivalent for cc_library, or is there?

**Comment by mhlopko** [comment] 2017-10-12 08:39
Nope, with cc_library you still have to use `copts=["-I<dir>"]`. Current plan is that this will be fixes early 2018.

**Comment by dflems** [comment] 2018-03-01 17:53
@mhlopko Any updates on this? We have a clunky workaround that works for `cc` or `objc` rules, as opposed to the `non_propagated_deps` approach from above that only works for `objc` rules. We'd love if this functionality was built into the `cc`/`objc` rules in a way that's consistent and portable.

```py
def private_include_copts(includes):
    copts = []
    prefix = ''

    # convert "@" to "external/" unless in the main workspace
    repo_name = native.repository_name()
    if repo_name != '@':
        prefix = 'external/{}/'.format(repo_name[1:])

    for inc in includes:
        copts.append("-I{}{}/{}".format(prefix, native.package_name(), inc))

    return copts
```

**Comment by dflems** [comment] 2018-03-01 17:54
cc @c-parsons

**Comment by mhlopko** [comment] 2018-03-05 09:01
No progress on this so far. We're doing quite big refactorings for Skylark API for C++ rules, and Skylark API for C++ toolchain, and I don't plan to work on "includes" (there's a bunch of problems) before we're done with apis. Current estimate is ~Q4/2018 for includes.

**Comment by mhlopko** [comment] 2018-07-31 07:33
CC @oquenchil 
Tracking bug is https://github.com/bazelbuild/bazel/issues/4570. Bazel@HEAD accepts `--experimental_enable_cc_skylark_api` that will enable the current WIP version of the API. It's only for experimenting at this point, we break it daily, and we will not support users using it yet. But feedback is more than welcome

**Comment by alanfalloon** [comment] 2019-03-29 22:08
Does this work-around still work? I don't see a `non_propagated_deps` attribute on [`obc_library`](https://docs.bazel.build/versions/0.24.0/be/objective-c.html#objc_library). Any chance we will see a real option soon?

**Comment by meisterT** [comment] 2020-05-12 09:07
cc @oquenchil

**Comment by oquenchil** [comment] 2020-05-12 13:37
Duplicate of #6790

**Closed by oquenchil** 2020-05-12 13:37 UTC
Labels: P2, team-Rules-CPP, type: feature request
