### ISSUE TITLE
FDO broken with GCC

### ISSUE THREAD

**Issue by wesleyw72** [bazelbuild/bazel#10881] opened 2020-03-01 11:24 UTC
### Description of the problem / feature request:

FDO is broken when used with GCC.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

```
bazel build --fdo_instrument="/tmp/instrument" //cpp:main
./bazel-bin/cpp/main
zip -r /tmp/instrument.zip  /tmp/instrument/
bazel build --fdo_optimize="/tmp/instrument.zip" -c opt //cpp:main
```
```
INFO: Build options --compilation_mode, --copt, --fdo_instrument, and 1 more have changed, discarding analysis cache.
ERROR: /home/wesley/.cache/bazel/_bazel_wesley/2597046113bb94401c8e571ce0f5de66/external/local_config_cc/BUILD:47:1: in cc_toolchain_suite rule @local_config_cc//:toolchain: llvm-profdata not available with this crosstool, needed for profile conversion
ERROR: Analysis of target '//cpp:main' failed; build aborted: Analysis of target '@local_config_cc//:toolchain' failed; build aborted
INFO: Elapsed time: 0.151s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (1 packages loaded, 48 targets configured)

```

### What operating system are you running Bazel on?

Ubuntu 18.04
GCC 7.4.0

### What's the output of `bazel info release`?

release 1.2.1

**Comment by benjaminp** [comment] 2020-03-02 01:35
See #5960.

**Comment by oquenchil** [comment] 2020-03-13 14:24
Closing as duplicate of #5960.

**Closed by oquenchil** 2020-03-13 14:24 UTC
Labels: team-Rules-CPP
