### ISSUE TITLE
Building TensorFlow example APK - cannot locate Android SDK

### ISSUE THREAD

**Issue by nick-jonas** [bazelbuild/bazel#2739] opened 2017-03-25 21:54 UTC
I might be doing something really stupid as it's my first time using Bazel (in which case apologies), but when following [these instructions](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/examples/android) to build the TensorFlow Android examples, I run this command:

```bazel build -c opt //tensorflow/examples/android:tensorflow_demo```

And get the following error:

```
ERROR: /Users/njonas/Code/tensorflow/WORKSPACE:20:1: no such package '@androidsdk//': com.google.devtools.build.lib.skyframe.InconsistentFilesystemException: Inconsistent filesystem operations. /Users/njonas/Library/Android/sdk/system-images/.DS_Store is no longer an existing directory. Did you delete it during the build? The results of the build are not guaranteed to be correct. You should probably run 'blaze clean' and investigate the filesystem inconsistency (likely due to filesytem updates concurrent with the build) and referenced by '//external:android/sdk'.
ERROR: Analysis of target '//tensorflow/examples/android:tensorflow_demo' failed; build aborted.
INFO: Elapsed time: 1.110s
```

I'm not sure as to why I'm getting: ```.DS_Store is no longer an existing directory```, is this a problem with Bazel itself and how it traverses my Android SDK directory?

### Environment info
* Operating System: OSX Sierra 10.12.3

* Bazel version (output of `bazel info release`): release 0.4.5-homebrew

###  Have you found anything relevant by searching the web?  

I'm not totally sure but [Issue 2465](https://github.com/bazelbuild/bazel/issues/2465) might be relevant?

My SDK is located here (```/Users/njonas/Library/Android/sdk```):
![screen shot 2017-03-25 at 5 49 58 pm](https://cloud.githubusercontent.com/assets/805682/24326376/837b6000-1183-11e7-88e8-311205283f3e.png)

And here it is in my filesystem:

![screen shot 2017-03-25 at 5 51 04 pm](https://cloud.githubusercontent.com/assets/805682/24326383/acb02e10-1183-11e7-8224-d352f308b41b.png)

**Comment by coroner4817** [comment] 2017-03-26 05:06
I get the same issue here and what I did is version back TF to r1.1 and use bazel 0.4.3. Then you should build the app.

**Comment by gunan** [comment] 2017-03-26 05:52
Are you sure you uncommented the androidsdk fields in the WORKSPACE file in TF repository root?
TensorFlow CI seems to be happily building the android demo with bazel 0.4.5 without any problems:
http://ci.tensorflow.org/job/tensorflow-master-android/

**Comment by nick-jonas** [comment] 2017-03-26 18:51
@gunan yea, my WORKSPACE looks like this:

```
# Uncomment and update the paths in these entries to build the Android demo.
android_sdk_repository(
   name = "androidsdk",
   api_level = 23,
   build_tools_version = "25.0.1",
   path = "/Users/njonas/Library/Android/sdk",
)

# Android NDK r12b is recommended (higher may cause issues with Bazel)
android_ndk_repository(
   name="androidndk",
   path="/Users/njonas/Library/Android/android-ndk-r12b",
   api_level=14) 

```

You can tell it's looking down the right path, but then for some reasons errors on this:

```/Users/njonas/Library/Android/sdk/system-images/.DS_Store is no longer an existing directory.```

**Comment by nick-jonas** [comment] 2017-03-26 19:43
@coroner4817 I have those versions and I now get this error when running ```bazel build```:

```
(tensorflow)  njonas@njonas-macbookpro2  ~/Code/tensorflow   master ●  bazel build -c opt //tensorflow/examples/android:tensorflow_demo
Killed non-responsive server process (pid=26237)
.
ERROR: /Users/njonas/Code/tensorflow/third_party/gpus/cuda_configure.bzl:828:18: unexpected keyword 'environ' in call to repository_rule(implementation: function, *, attrs: dict or NoneType = None, local: bool = False).
ERROR: com.google.devtools.build.lib.packages.BuildFileContainsErrorsException: error loading package '': Extension file 'third_party/gpus/cuda_configure.bzl' has errors.
INFO: Elapsed time: 1.014s
```

I'm using ```pip install tensorflow==1.1.0rc0```, is it perhaps giving me a GPU instead of CPU version?  These are the versions offered up from pip: ```0.12.0rc0, 0.12.0rc1, 0.12.0, 0.12.1, 1.0.0, 1.0.1, 1.1.0rc0```

**Comment by coroner4817** [comment] 2017-03-26 19:54
@nick-jonas try to do this:
```
git clone -b r1.1 https://github.com/tensorflow/tensorflow.git
```
Then 
```
bazel version
```
If not 0.4.3, then try `brew switch bazel 0.4.3` or install bazel 0.4.3 from [Bazel release page](https://github.com/bazelbuild/bazel/releases/tag/0.4.3)

**Comment by nick-jonas** [comment] 2017-03-26 20:46
That worked!  Should I leave this open as it requires a rollback?

**Comment by aj-michael** [comment] 2017-03-26 21:07
@nick-jonas can you paste the output of `ls -al /Users/njonas/Library/Android/sdk/system-images` and `bazel version`?

Bazel 0.4.5 should work fine with this, so I would like to understand what's going wrong on your machine. FWIW, Bazel 0.4.5 is the first version that `android_sdk_repository` looks at your SDK's `system-images` directory (we are preparing some rules that allow for testing Android apps on a device specified in your BUILD files), so by going back to Bazel 0.4.3 we are just avoiding the problem.

My first guess is that if you have Android Studio open while running `bazel build`, Android Studio might be modifying the files in your SDK (`.DS_Store`) while Bazel is examining it, causing the exception that you saw.

**Comment by nick-jonas** [comment] 2017-03-27 15:04
@aj-michael 
```
(tensorflow)  ✘ njonas@njonas-macbookpro2  ~/Code/tensorflow   r1.1 ●  ls -al /Users/njonas/Library/Android/sdk/system-images
total 16
drwxr-xr-x   4 njonas  nonconf   136 Mar 25 16:07 .
drwxr-xr-x  16 njonas  nonconf   544 Feb  8 10:01 ..
-rw-r--r--@  1 njonas  nonconf  6148 Mar 25 17:32 .DS_Store
drwxr-xr-x   4 njonas  nonconf   136 Mar 25 16:19 android-23
```

I now installed Bazel 0.4.3 from the release page, so I get this with ```bazel version```:
```
(tensorflow)  njonas@njonas-macbookpro2  ~/Code/tensorflow   r1.1 ●  bazel version
...............
Build label: 0.4.3
Build target: bazel-out/local-fastbuild/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Thu Dec 22 12:31:39 2016 (1482409899)
Build timestamp: 1482409899
Build timestamp as int: 1482409899
```

I *did* have Android Studio open, so maybe I should try with it closed and with 0.4.5?

**Comment by aj-michael** [comment] 2017-03-27 15:08
I would suggest trying this:

1. Delete /Users/njonas/Library/Android/sdk/system-images/.DS_Store
2. Reinstall bazel 0.4.5
3. Paste the output of `bazel version` here
4. Try building the example app again

(To be clear, this definitely seems like a Bazel bug. I'm just not sure what's causing it and I cannot reproduce it.)

**Comment by aj-michael** [comment] 2017-03-27 15:27
Actually, I can reproduce this (but I am not sure if my repro case really constitutes a bug)

```
$ f=$ANDROID_HOME/system-images/.DS_Store

$ (while : ; do touch $f; rm $f; done) &
[1] 141446

$ bazel build @androidsdk//:files                                                                       
ERROR: no such package '@androidsdk//': com.google.devtools.build.lib.skyframe.InconsistentFilesystemException: Inconsistent filesystem operations. /usr/local/google/home/ajmichael/Android/Sdk/system-images/.DS_Store is no longer an existing directory. Did you delete it during the build? The results of the build are not guaranteed to be correct. You should probably run 'blaze clean' and investigate the filesystem inconsistency (likely due to filesytem updates concurrent with the build).
INFO: Elapsed time: 0.162s
```

**Comment by aj-michael** [comment] 2017-03-27 15:43
So @nick-jonas , I think something was just modifying the .DS_Store in your system-images directory while bazel was reading it. In fact, older versions of Bazel don't read system-images, but they do read other parts of the SDK (like the top level and build-tools). So even with bazel 0.4.3, you could encounter this same error if something wrote $ANDROID_HOME/.DS_Store or $ANDROID_HOME/build-tools/.DS_Store while you were doing a build.

**Comment by nick-jonas** [comment] 2017-03-27 19:04
Thanks @aj-michael , with Bazel 0.4.5 I confirmed that it still will throw an error on .DS_Store but simply deleting that file will result in a successful build:

```bazel version```:

```
Build label: 0.4.5-homebrew
Build target: bazel-out/local-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Thu Mar 16 13:39:33 2017 (1489671573)
Build timestamp: 1489671573
Build timestamp as int: 1489671573
```

I'm not sure if this is considered a bug? While very minor it seems like one a lot of people on OSX would encounter, no?

**Comment by aj-michael** [comment] 2017-03-27 19:35
I'm unsure of what needs to occur for someone to encounter this. My theory is that this will only happen if the following sequence of events happens:

1. Start a bazel build
2. Open /sdk/system-images in Finder for the first time (or when there is not a .DS_Store there) before bazel build finishes.

If the .DS_Store exists before the build, or is created after the build, everything should be fine.

@ahumesky can you help triage?

**Comment by hewei05** [comment] 2017-03-29 10:44
I got the same problem

ERROR: /Users/xxx/workspace/git-workspace/tensorflow/WORKSPACE:25:1: no such package '@androidsdk//': com.google.devtools.build.lib.skyframe.InconsistentFilesystemException: Inconsistent filesystem operations. /Users/xxx/AndroidSDK/sdk/system-images/.DS_Store is no longer an existing directory. Did you delete it during the build? The results of the build are not guaranteed to be correct. You should probably run 'blaze clean' and investigate the filesystem inconsistency (likely due to filesytem updates concurrent with the build) and referenced by '//external:android/sdk'.
ERROR: Analysis of target '//tensorflow/examples/android:tensorflow_demo' failed; build aborted.
INFO: Elapsed time: 12.208s


Build label: 0.4.5-homebrew
Build target: bazel-out/local-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Thu Mar 16 13:38:14 2017 (1489671494)
Build timestamp: 1489671494
Build timestamp as int: 1489671494

**Comment by aj-michael** [comment] 2017-03-29 16:51
Ah, I have found the problem. It was right there in the error message all along.

> .DS_Store is no longer an existing **directory**

Because .DS_Store was never a directory, it is a file. `android_sdk_repository` is making an assumption that all files under `/sdk/system-images` are directories, which is true in the official SDK distribution, but in practice anyone can write any files there whenever they want. (Such as the Mac Finder application writing .DS_Store.)

I have a fix for this that should be in the next Bazel release. Thanks for the reports, for now the only workaround is to delete `/sdk/system-images/.DS_Store`.

**Closed** 2017-03-31 15:15 UTC
Labels: category: rules > android, P1, type: bug
