### ISSUE TITLE
Error: LinkageError occurred while loading main class com.google.devtools.build.lib.bazel.Bazel 	java.lang.ExceptionInInitializerError: null

### ISSUE THREAD

**Issue by PanJinquan** [bazelbuild/bazel#6726] opened 2018-11-21 08:23 UTC
Hi, I follow the [tutorial](https://docs.bazel.build/versions/master/install-ubuntu.html)， 
`
$ chmod +x bazel-0.18.0-installer-linux-x86_64.sh 
$  ./bazel-0.18.0-installer-linux-x86_64.sh 
`
**but it gives me a new error like following,** 
`  [Commit](https://github.com/bazelbuild/bazel/commit/d13df47)
Uncompressing......Error: LinkageError occurred while loading main class com.google.devtools.build.lib.bazel.Bazel
	java.lang.ExceptionInInitializerError: null`

I wonder what is wrong and what should I do? Thanks for help.

**Comment by philwo** [comment] 2019-05-06 11:45
Sorry for not looking into this earlier. I guess this has been resolved in newer Bazel versions?

If not, can you share some more information about your environment - which kind and version of Linux are you running?

**Comment by DarkaMaul** [comment] 2019-06-27 16:19
Hi,

The problem is still present, even if the version of bazel is more recent.
As #2550 mention, the problem is occurring when a non-ascii character is present in path.

Step to reproduce:
```bash
 % ./bazel-0.27.0-linux-x86_64 --help                                                                                                                                                                      
Error: LinkageError occurred while loading main class com.google.devtools.build.lib.bazel.Bazel
	java.lang.ExceptionInInitializerError: null
```

Configuration:
```bash
% pwd
/home/builder/Téléchargements
% uname -a
Linux computer 4.9.0-9-amd64 #1 SMP Debian 4.9.168-1+deb9u2 (2019-05-13) x86_64 GNU/Linux
```

Workaround: Move the executable to another directory (path) with only ascii charachters inside name

**Comment by katre** [comment] 2020-05-13 13:56
Duplicate of #2550.

**Closed by katre** 2020-05-13 13:56 UTC
Labels: P1, team-EngProd, type: bug
