### ISSUE TITLE
Sandbox filesystem creation slow on OSX

### ISSUE THREAD

**Issue by DavidZbarsky-at** [bazelbuild/bazel#20489] opened 2023-12-11 15:43 UTC
### Description of the bug:

When using `rules_js` for JS projects, NPM packages are modeled as TreeArtifacts. This helps with analysis phase performance, but actions still have high overhead because TreeArtifacts are expanded, even with `--noenable_runfiles`.

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

https://github.com/DavidZbarsky-at/nodejs-repro shows a typical JS target using node_modules, as well as reproduces the slowness directly with simple TreeArtifacts of various sizes

### Which operating system are you running Bazel on?

OSX

### What is the output of `bazel info release`?

release 7.0.0-pre.20231011.2

### Is this a regression? If yes, please try to identify the Bazel commit where the bug was introduced.

From a long time ago :) See https://github.com/bazelbuild/bazel/issues/5971#issuecomment-417278360

### Have you found anything relevant by searching the web?

https://github.com/bazelbuild/bazel/issues/8230

**Comment by oquenchil** [comment] 2023-12-11 16:17
Duplicate of https://github.com/bazelbuild/bazel/issues/8230. We are working on it.

**Closed by oquenchil** 2023-12-11 16:17 UTC
Labels: type: bug, team-Performance, duplicate
