### ISSUE TITLE
No such package error, BUILD not found when doing load

### ISSUE THREAD

**Issue by lingz** [bazelbuild/bazel#1551] opened 2016-07-22 22:33 UTC
When I try to do `load("@org_tensorflow//tensorflow:tensorflow.bzl", "tf_copts")`, it gives me the following error:

```
no such package 'tensorflow': BUILD file not found on package path and referenced by '//lib/myapp'
```

But I am able to do this without problems:
`load("@org_tensorflow//tensorflow:workspace.bzl", "tf_workspace")`

Running bazel 0.3.0, my workspace looks like below:

```
workspace(name = "myapp")

local_repository(
    name =  "org_tensorflow",
    path =  __workspace_dir__ + "/tensorflow/"
)

load("@org_tensorflow//tensorflow:workspace.bzl", "tf_workspace")
tf_workspace(path_prefix="tensorflow/", tf_repo_name="@org_tensorflow")
\
```

**Comment by damienmg** [comment] 2016-07-25 13:51
What does the build file you are doing the load from looks like?

**Comment by lingz** [comment] 2016-07-25 14:02
Very minimal, just one cc_binary. Sure clarifying it's in a different workspace though, and I'm referring to it remotely as a local repository.

```
load("@org_tensorflow//tensorflow:tensorflow.bzl", "tf_copts")

cc_binary(
    name = "myapp",
    srcs = [
        "main.cc",
    ],
    copts = tf_copts(),
    linkopts = [
        "-lm"
    ],
    deps = [
        "@org_tensorflow//tensorflow/core:android_tensorflow_lib",
    ],
)
```

**Comment by damienmg** [comment] 2016-07-25 14:23
What is the WORKSPACE file of the workspace of the build file then? This workspace file needs to declare the tensorflow repository too.

**Comment by lingz** [comment] 2016-07-28 12:04
Yep I have a WORKSPACE file declaring the Tensorflow repo. Curiously, the load requesting `tf_workspace` here works without problems:

```
workspace(name = "myapp")

local_repository(
    name =  "org_tensorflow",
    path =  __workspace_dir__ + "/tensorflow/"
)

load("@org_tensorflow//tensorflow:workspace.bzl", "tf_workspace")
tf_workspace(path_prefix="tensorflow/", tf_repo_name="@org_tensorflow")
```

**Comment by lingz** [comment] 2016-07-28 12:04
And referring to `@tensorflow` in the context of dependencies works without a problem.

**Comment by damienmg** [comment] 2016-07-28 13:34
Ok I am lost, is the structure like that:
```
<dir>/WORKSPACE (with the workspace file as you pasted)
<dir>/tensorflow/... <-- tensorflow git clone
<dir>/lib/myapp/BUILD (with the build file with the problematic load statement)
```
And you try to `bazel build //lib/myapp/...` from `<dir>`?

**Comment by lingz** [comment] 2016-07-28 13:57
yep you got it exactly right.

**Comment by damienmg** [comment] 2016-07-28 14:06
I was able to repro.

**Comment by damienmg** [comment] 2016-07-28 14:07
Seems like tf_opts() macro is at fault

**Comment by lingz** [comment] 2016-07-28 14:09
You mean `tf_copts`? What about it is incompatible, it seems pretty small / straightforward macro to me.

**Comment by damienmg** [comment] 2016-07-28 14:09
```
[dmarting@trantor] /tmp/dir/lib/myapp$ bazel build :myapp
INFO: Reading 'startup' options from /usr/local/google/home/dmarting/.bazelrc: --watchfs

ERROR: /tmp/dir/lib/myapp/BUILD:4:1: no such package 'tensorflow': BUILD file not found on package path and referenced by '//lib/myapp:myapp'

ERROR: /tmp/dir/lib/myapp/BUILD:4:1: no such package 'tensorflow': BUILD file not found on package path and referenced by '//lib/myapp:myapp'

ERROR: /tmp/dir/lib/myapp/BUILD:4:1: no such package 'tensorflow': BUILD file not found on package path and referenced by '//lib/myapp:myapp'

ERROR: Analysis of target '//lib/myapp:myapp' failed; build aborted

INFO: Elapsed time: 0.178s
FAILED: Build did NOT complete successfully
[dmarting@trantor] /tmp/dir/lib/myapp$ bazel query --output=build :myapp
INFO: Reading 'startup' options from /usr/local/google/home/dmarting/.bazelrc: --watchfs
# /tmp/dir/lib/myapp/BUILD:4:1
cc_binary(
  name = "myapp",
  deps = ["@org_tensorflow//tensorflow/core:tensorflow"],
  srcs = ["//lib/myapp:main.cc"],
  linkopts = ["-lm"],
)
```

Pinging @kchodorow and @lberki to get more help, I cannot understand what is happening there.

**Comment by kchodorow** [comment] 2016-07-28 14:33
`tf_copts` is returning 

```
(["-fno-exceptions", "-DEIGEN_AVOID_STL_ARRAY"] +
          if_cuda(["-DGOOGLE_CUDA=1"]) +
          if_android_arm(["-mfpu=neon"]) +
          select({"//tensorflow:android": [
                    "-std=c++11",
                    "-DMIN_LOG_LEVEL=0",
                    "-DTF_LEAN_BINARY",
                    "-O2",
                  ],
                  "//tensorflow:darwin": [],
                  "//conditions:default": ["-pthread"]}))
```

This is put into your cc_binary rule wholesale, so it's trying to find `//tensorflow:whatever` in _your_ workspace, not tensorflow's. 

I'm not sure why bazel query doesn't show the copts.

**Comment by kchodorow** [comment] 2016-07-28 15:15
One workaround is you could make a tensorflow/BUILD file and copy https://github.com/tensorflow/tensorflow/blob/master/tensorflow/BUILD#L15-L36 into it.

**Comment by lingz** [comment] 2016-07-28 15:24
So my understanding is that config_setting does not cross WORKSPACE
boundaries and this is by design right? So if I want to support the same
workspaces I should just recreate all the same configs.

Also I have a question about the placement of these BUILD files with the
config_setting rule. Where can I place them such that they are globally
registered? Will a config_rule in a BUILD file in the same directory as my
WORKSPACE automatically get picked up across the entire workspace?

**Comment by kchodorow** [comment] 2016-07-28 15:35
You could use the workspace name prefix (e.g., @org_tensorflow//tensorflow:android) and it would work fine.  There is no "global" registry, every repository has its own namespace.  You have to refer to things by their namespace.  I think it's kind of a mistake for tensorflow to expose this to users without a workspace name, but they might not have had an option (Skylark does not support very much in terms of visibility.)

**Comment by damienmg** [comment] 2016-07-29 09:36
Ok so this is not a problem on our side.

There is the issue of query not understanding select but that's a different issue.
The underlying problem is that label for condition should include the repository name, using Label() around them should fix the issue on the TF side. /cc @martinwicke.

**Comment by damienmg** [comment] 2016-07-29 09:36
I am closing this bug since the issue is not on the Bazel side.

**Closed by damienmg** 2016-07-29 09:36 UTC
Labels: Under investigation
