### ISSUE TITLE
issue with bazel head - Unable to load package for '@local_config_cc//tools/build_rules:toolchain_category.bzl'

### ISSUE THREAD

**Issue by nlopezgi** [bazelbuild/bazel#3739] opened 2017-09-14 19:36 UTC
I was running some builds with bazel head and I started getting the following error:

ERROR: in target '//external:cc_toolchain': error loading package '@local_config_cc//': Extension file not found. Unable to load package for '@local_config_cc//tools/build_rules:toolchain_category.bzl': BUILD file not found on package path

I'm running bazel inside an ubuntu:trusty container with minimal packages installed, and bazel freshly obtained from head, and am trying to build a super simple project with this BUILD file:

package(default_visibility = ["//visibility:public"])
cc_test(
  name = "test",
  srcs = ["test.cc"],
)

test.cc:
#include <iostream>
int main() {
  std::cout << "Hello test!" << std::endl;
  return 0;
}

**Comment by katre** [comment] 2017-09-14 19:37
@calpeyser added that recently, assigning to him.

**Comment by philwo** [comment] 2017-09-14 19:39
What operating system?

**Comment by nlopezgi** [comment] 2017-09-14 19:41
thanks, ubuntu:trusty

**Comment by calpeyser** [comment] 2017-09-14 19:42
rolling back

**Comment by philwo** [comment] 2017-09-14 19:42
Considering that this affects more than just FreeBSD (for which @calpeyser made a fix just now), we're rolling back the root cause CL now and will possibly roll forward with a fix later.

**Comment by nlopezgi** [comment] 2017-09-14 19:43
thanks for the quick response!

**Closed** 2017-10-10 15:36 UTC
