### ISSUE TITLE
Results from removed source files not removed

### ISSUE THREAD

**Issue by heini** [bazelbuild/bazel#10057] opened 2019-10-17 15:19 UTC
### Description of the problem / feature request:

> Not sure whether this is a bug or feature, so treat it as you see fit ;-)
> 
> After removing/renaming a source file and running an incremental build, I would assume the results that stem from the removed source file to be removed too, especially so if the build tool tracks everything it does. See for example the [tup build tool](http://gittup.org/tup/).

### Feature requests: what underlying problem are you trying to solve with this feature?

> Compilation/link errors resulting from left-over objects whose source files have been removed.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

> 1. Take the stages of the C++ tutorial, but instead of storing them next to each other, create a new Git repository, import each one as its own revision and tag them accordingly (STAGE_N).
>  2. Checkout and build STAGE_3
>  3. Checkout STAGE_1 and rebuild
> 
> The object (*.o) and dependency (*.d) files for the - in stage 1 - non-existing source files `lib/hello-time.cc` and `main/hello-greet.cc` are still there.

### What operating system are you running Bazel on?

Debian Buster

### What's the output of `bazel info release`?

> release 1.0.0

**Comment by irengrig** [comment] 2019-10-23 08:21
Hi @heini , thank you for reporting the issue.

>The object (.o) and dependency (.d) files for the - in stage 1 - non-existing source files lib/hello-time.cc and main/hello-greet.cc are still there.

It is by design: Bazel does not clean the contents of the output directory, it is up to user to clean it with 'bazel clean' / 'bazel clean --expunge' (+ wipes the external repositories).

**Comment by irengrig** [comment] 2019-10-23 16:30
Yes, 'bazel clean' makes all the outputs disappear.
If the outputs are left after some not-used-any-more action, they are not involved into other build steps, so it does not induce incorrect behavior.
Please note that during the execution, we are creating the sandbox for running each action, and symlinking into the execroot only explicitly declared inputs, so the "stale" outputs, not declared as inputs explicitly, can not make it into the sandbox.

Vice versa, if we cleaned the output directory before the build, it would not be possible to build two sibling targets from a project and still have the results of both of them in the bazel-out.

**Comment by jin** [comment] 2019-12-20 20:13
Closing this issue for now - @heini, if you have any more queries, please don't hesitate to ping this issue and we'll reopen it.

**Closed by jin** 2019-12-20 20:13 UTC
Labels: more data needed
