### ISSUE TITLE
missing dependency declarations for standard library headers with --cpu=freebsd

### ISSUE THREAD

**Issue by filmil** [bazelbuild/bazel#615] opened 2015-11-17 07:52 UTC
I started getting the following error, when compiling with --cpu=freebsd:

ERROR: /home/f/work/bugs-bazel/BUILD:1:1: undeclared inclusion(s) in rule '//:strrev':
this rule is missing dependency declarations for the following files included by 'strrev.cc':
  '/usr/lib/clang/3.4/include/stddef.h'
  '/usr/lib/clang/3.4/include/stdarg.h'.

Not sure if it was intended that a standard library headers would produce it.

Here is a demo workspace that shows the problem.  The input command line is in the file INPUT; and the output I get is in the file OUTPUT

https://bitbucket.org/filmil/bugs-bazel/src/453cced452ad4f4e2f3ac41ee7abd9a032ed9374

8ff216d8e8a1c3fc5ed33453bb21b53381e295c9 is the first bad commit
commit 8ff216d8e8a1c3fc5ed33453bb21b53381e295c9
Author: Philipp Wollermann philwo@google.com
Date:   Mon Oct 19 12:28:03 2015 +0000

```
Quick workaround for #473 that reenables hdrs_check in Bazel to unblock the release. Note the following peculiarities of the current situation:

- Sandboxed execution still silently falls back to non-sandboxed execution due to LocalGccStrategy explicitly requesting local execution.
- However, builds are still correct due to local execution using hdrs_check.
- hdrs_check, even though it was intended to default to "strict" in Bazel from the start, is still set to "loose" by default, so you might accidentally be using non-declared header files in your cc_* targets. In this case, your builds will break when the default becomes hdrs_check=strict and sandboxing becomes available. It is recommended that you check whether your builds are affected, by specifying --hdrs_check=strict manually and fixing your BUILD files to explicitly list all used includes in the srcs / hdrs attributes of your cc_* targets.

These remaining issues will be fixed in an upcoming change.

This change also adds regression tests for the issue.

--
MOS_MIGRATED_REVID=105747212
```

**Comment by filmil** [comment] 2015-11-17 07:55
FWIW, my current master branch is at commit 50bf666652aacd274d534ad4ec4eadf8e8452e05

**Comment by damienmg** [comment] 2015-11-17 09:07
The problem comes from the tools/cpp/CROSSTOOL file that is missing the
correct include path for FreeBSD (can be hard to handle all case with our
current setup). I would classify this one as "another C++ configuration
issue".

Until we get a correct configuration system you can modify the CROSSTOOL
file in the FreeBSD part to match your include paths.

**Comment by damienmg** [comment] 2016-03-03 14:49
FWIW, we now have the configurability mechanisms (see https://groups.google.com/d/msg/bazel-discuss/MSunz2ZUOq0/U5tE7uQLJQAJ) and it does the header detection.

**Comment by damienmg** [comment] 2016-03-31 12:11
The mechanism is deactivated by default on FreeBSD but I think it shouldn't be too hard to activate it. I just cannot test it. @aehlig might (or might not) work on it.

**Comment by aehlig** [comment] 2017-09-14 07:23
Can't reproduce the original issue, but FreeBSD support has improved a lot since this bug was filed. Closing for now. Feel free to reopen with more details, if the issue reappears.

**Closed by aehlig** 2017-09-14 07:23 UTC
Labels: category: extensibility > configurability, P3, type: bug
