### ISSUE TITLE
undocumented usage of perl for cc_test

### ISSUE THREAD

**Issue by ahippler** [bazelbuild/bazel#4691] opened 2018-02-23 15:38 UTC
### Description of the problem / feature request:

cc_test uses a inline perl script for failed tests.
https://github.com/bazelbuild/bazel/blob/eb067ea88749a5635cc8ee8954cde2b767f1eb61/tools/test/test-setup.sh#L153

### Feature requests: what underlying problem are you trying to solve with this feature?

The usage of perl is not documented.
Windows does not have Perl installed by default.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

- execute a failing test on windows will print:

```
==================== Test output for //Test/Unit:Unit (shard 1 of 8):

[...]

external/bazel_tools/tools/test/test-setup.sh: line 152: perl: command not found
================================================================================
```

### What operating system are you running Bazel on?

Windows 10

### What's the output of `bazel info release`?

0.10.1

The perl script replaces invalid XML characters and invalid sequence in CDATA.
To get rid of perl bash or python could be used.

**Comment by aehlig** [comment] 2018-02-26 08:02
Categorizing as bug, as pulling in an documented run-time dependency can cause breakage for users not otherwise using perl. The main question is if we really need perl (then we should document it as a run-time dependency of bazel) or whether an appropriate set up can be achieved with more standard tools.

**Comment by aehlig** [comment] 2018-02-26 08:03
It's the actual test rules that are problematic.

**Comment by ulfjack** [comment] 2018-03-07 08:16
Note that this is the fallback code path, so if you make sure that your test framework generates a test.xml, that should workaround the issue.

Any suggestions on what to do here? We do need to escape the characters when generating the test.xml.

**Comment by benjaminp** [comment] 2018-03-08 07:46
Perhaps rewrite `test-setup.sh` in a language like C++ or Python where text processing is easy to do portably? That might also be helpful for solving subtle test-setup.sh issues like #4608. (I can't imagine bash is very fun to run on Windows either.)

Relatedly, I would like the ability to customize the test setup executable. One can usually use `--run_under`, but then the user loses the ability to usefully specify their own `--run_under`.

**Comment by ulfjack** [comment] 2018-03-08 09:32
We discussed that, but it means that we'd unconditionally need a C++ compiler in order to run tests. We could bundle a pre-compiled binary into Bazel, but what platform would it be compiled for? For cross-compilation, you need a binary for the target platform, not the host platform. We could bundle a binary and also ship the source, but then you still need a C++ compiler in order to do cross-compilation.

We could use Python, but then we require that everyone has python installed, even if they 'only' do web or C++ development.

We also discussed moving the fallback codepath into Bazel (i.e., have the test.xml generation in Bazel itself). However, that's also causing problems with remote execution, where we now would force test.xml generation onto the local machine. Except, of course, if we also require that remote execution provides X for some value of X.

It's not impossible to solve these problems, but there's no free lunch.

For now, I'd prefer we keep doing it in shell, but maybe there's a more standard tool than perl that we can use to do the escaping? awk? sed?

**Comment by benjaminp** [comment] 2018-03-13 00:13
FWIW, Bazel doesn't work at all without a C++ compiler on the system:
```
$ bazel build
ERROR: in target '//external:cc_toolchain': no such package '@local_config_cc//': Traceback (most recent call last):
    File "/home/benjamin/.cache/bazel/_bazel_root/887904812217cca9bc2b9adb875daf42/external/bazel_tools/tools/cpp/cc_configure.bzl", line 42
        configure_unix_toolchain(repository_ctx, cpu_value, overriden...)
    File "/home/benjamin/.cache/bazel/_bazel_root/887904812217cca9bc2b9adb875daf42/external/bazel_tools/tools/cpp/unix_cc_configure.bzl", line 416, in configure_unix_toolchain
        find_cc(repository_ctx, overriden_tools)
    File "/home/benjamin/.cache/bazel/_bazel_root/887904812217cca9bc2b9adb875daf42/external/bazel_tools/tools/cpp/unix_cc_configure.bzl", line 407, in find_cc
        fail(("Cannot find gcc or CC%s, eithe...))
Cannot find gcc or CC, either correct your path or set the CC environment variable
```

**Comment by ulfjack** [comment] 2018-03-13 07:44
That's true, and we should fix that independently of this problem. I'd rather not add another dependency on having a C++ compiler available.

**Comment by laszlocsomor** [comment] 2018-03-13 07:52
> That's true, and we should fix that independently of this problem.

+1

> I'd rather not add another dependency on having a C++ compiler available.

I'd give another +1 if I weren't out of them already.

**Comment by ahippler** [comment] 2018-03-13 11:41
> We could use Python, but then we require that everyone has python installed, even if they 'only' do web or C++ development.

python is already required as per documentation:
[https://docs.bazel.build/versions/master/install-ubuntu.html#1-install-required-packages](ubuntu)
[https://docs.bazel.build/versions/master/windows.html#software-requirements](windows)

**Comment by laszlocsomor** [comment] 2018-03-13 14:34
@ahippler : Like with C++, that's true and we should fix that independently of this problem. In fact it'd be best if Bazel would only require toolchains that it needs for the build, i.e. if you don't build Python rules then Bazel shouldn't require a Python installation.

Only exception (if you could call it an exception) should be Java: the JDK is always available because we bundle one with Bazel, because Bazel itself needs one in order to run.

**Comment by laszlocsomor** [comment] 2018-05-02 13:04
Thanks to @aehlig we now know what this command is supposed to do:

> It means, read the string as sequence of uni-code characters, and replace every non-empty sequence of characters in the given ranges by a question mark symbol. (That's the first line. The ranges come from the esoteric definition of which unicode characters are and are not allowed in XML documents.)
> The negation (^) makes sense. The allowed unicode characters are:
> x9 | xA | xD | [x20-xD7FF] | [xE000-xFFFD] | [x10000-x10FFFF]
> And every non-empty sequence of other charachters is replaced by a question mark symbol.
> The reason why perl was used was that the whitelist only applies after you interpreted the sequence of octets as a sequnce of (utf-8 encoded) unicode characters, and perl could do that on the fly (while the more traditional unix tools work on sequnce of octets).

**Comment by laszlocsomor** [comment] 2018-05-14 14:02
@ulfjack : True. Bazel could include a precompiled embedded binary for the host platform, and the remote execution platform author would have to provide one. Bazel would select the active one with toolchain rules. WDYT?

**Comment by ulfjack** [comment] 2018-05-14 14:04
That would make it much more difficult to change test-setup since all such changes would have to be rolled out to all remote execution systems.

**Comment by ulfjack** [comment] 2018-05-14 14:05
I think one option would be to fork test-setup, and have different implementations for Linux/Mac and Windows.

**Comment by laszlocsomor** [comment] 2018-05-14 14:06
Forking test-setup would also introduce the synchronization difficulty you alluded to.

**Comment by laszlocsomor** [comment] 2018-05-15 08:52
> (Note that any solution for test-setup needs to work with remote execution - this makes it very difficult to use pre-compiled binaries, because you don't know which platform the test action will actually run on.)

The options I see:
-   **Use precompiled binary.** Faster than a script and requires no runtime, but Bazel must either include the binary for all local and remote execution platforms, or the remote execution platform must provide its version of the binary and Bazel needs an appropriate toolchain rule. Need to maintain and keep in sync multiple source files.
-   **Use scripts.** Requires a runtime (Bash / Python / Powershell) but more portable than a precompiled binary. Need to maintain and keep in sync multiple script files.
-   **Use one script.** This is what we have now. Requires the same runtime (Bash / Python) on every platform (goes against #4319 ). Need to maintain just one script.

The second option seems to be the best tradeoff. WDYT?

**Comment by ulfjack** [comment] 2018-05-15 16:10
I agree.

Note that I've been working on splitting test-setup into two separate steps - right now it runs the test and then generates a test.xml file if there isn't one. The way it's done is triggering a code path on Linux and MacOS that has an inherent race condition. @agoulti proposed that we split up the two parts - run the test first and then run a separate action to generate the test.xml file if the test didn't generate one. That'll fix the race condition and potentially make the test-setup script a bit simpler.

**Comment by ulfjack** [comment] 2018-05-15 16:12
There's some background in #4608.

**Comment by laszlocsomor** [comment] 2018-05-16 08:10
@benjaminp : I forgot to add that option, thanks for mentioning it! I agree it's attractive for the reasons you listed, but the hard requirement on a C compiler conflicts with https://github.com/bazelbuild/bazel/issues/5133, so using scripts still seems to be the most advantageous (or least disadvantageous) approach. WDYT?

**Comment by laszlocsomor** [comment] 2018-05-16 11:27
Thanks for pointing these out!

@benjaminp: what do you think in light of what @ulfjack and I wrote?

**Comment by benjaminp** [comment] 2018-05-16 18:42
Is having a compiler toolchain harder than running a Bazel remote execution agent on a Windows or OSX machine? I think you should only have to deal with this installation problem if you're trying to use remote execution across incompatible platforms, which I suspect is a more advanced case.

At any rate, I don't want to get in the way—I would just like to see less bash in the world.

**Comment by laszlocsomor** [comment] 2018-05-17 07:44
> Is having a compiler toolchain harder than running a Bazel remote execution agent on a Windows or OSX machine?

Considering that the agent can be precompiled and embedded in Bazel (assuming you mean an agent for the host machine) and as such requires no action from the user, it is harder to install a compiler.

I agree in wanting less Bash, but in this case using scripts seems the lesser bad of the options.

It seems we converged on an agreement to reimplement `test-setup.sh` in a Windows-friendly script language such as Powershell and use that on Windows, and keep using the Bash script on Unixes.

**Comment by benjaminp** [comment] 2018-05-18 00:15
>> Is having a compiler toolchain harder than running a Bazel remote execution agent on a Windows or OSX machine?

> Considering that the agent can be precompiled and embedded in Bazel (assuming you mean an agent for the host machine) and as such requires no action from the user, it is harder to install a compiler.

I meant an agent for the machine the action is actually running on. ("host" is a bit ambiguous in this situation.) My claim is installing compilers on worker machines would only be a minor annoyance compared to actually running a remote execution cluster.

**Comment by ulfjack** [comment] 2018-05-18 07:39
I think you're proposing that we ship bazel with a binary for the same platform that bazel runs on, as well as the source code. When remote execution is enabled, we'd not use the binary, but instead compile it from source using a remotely installed compiler.

I am not sure how many people are actually going to run a remote execution cluster. It's more likely that this will be offered as a service, with a bring your own docker container story. In that case, we'd still require that all such docker containers contain - say - a C++ compiler (right now we require that they contain bash for both linux or windows containers; there's no docker for macos I believe).

**Comment by ulfjack** [comment] 2018-05-18 08:27
I'm not suggesting that it will automatically be available, but we could require that all remote execution images contain a certain minimum set of tools.

**Comment by laszlocsomor** [comment] 2018-05-18 08:39
Right, that's what I meant. Does that mean that moving to C++ instead of forking test-setup and reimplementing it in powershell sounds good to you?

**Comment by ulfjack** [comment] 2018-05-18 08:44
My preference is still shell + powershell, because it 'only' requires that a shell is installed in the execution images, which is almost always the case, including existing images (except for the distroless images that don't even come with a shell). I'm also concerned about divergence between Bazel and Blaze, and it's not obvious how difficult compiling the test wrapper binary at runtime will be - it's more difficult than you'd think.

**Comment by ulfjack** [comment] 2018-05-18 08:46
(Blaze doesn't currently use the same test-setup.sh, but I'd like to converge the two.)

**Comment by laszlocsomor** [comment] 2018-05-18 09:00
> My preference is still shell + powershell, because it 'only' requires that a shell is installed in the execution images, which is almost always the case, including existing images (except for the distroless images that don't even come with a shell).

I see. It's my understanding that distroless images don't have a compiler either and would require a binary. Is that correct?

> I'm also concerned about divergence between Bazel and Blaze,

I think introducing a Powershell version of test-setup with add to that problem. Replacing the existing shell scripts with C++ code would not worsen the situation. WDYT?

> and it's not obvious how difficult compiling the test wrapper binary at runtime will be - it's more difficult than you'd think.

Why? I reckon the test-setup were a single `cc_binary` in this model, compiled for the execution platform, as if it was in `genrule.tools`. Bazel can already do this well. Am I missing something?

**Comment by ulfjack** [comment] 2018-05-18 09:06
> I see. It's my understanding that distroless images don't have a compiler either and would require a binary. Is that correct?

I don't think we need to worry about the distroless images. They aren't suited for building, and I don't foresee anyone asking us to support those.

> I think introducing a Powershell version of test-setup with add to that problem. Replacing the existing shell scripts with C++ code would not worsen the situation. WDYT?

I don't think adding a Powershell version will make the divergence between Blaze and Bazel worse, per se. Making Bazel use a C++ binary while Blaze uses a shell script seems to increase divergence, not decrease it.

Let me also point out that shell is easier to extend at runtime - we may need to support company- or project-specific test configuration parts in order to be able to converge.

> Why? I reckon the test-setup were a single cc_binary in this model, compiled for the execution platform, as if it was in genrule.tools. Bazel can already do this well. Am I missing something?

If you use cc_binary, you also have to have a matching cc_toolchain rule, which means the user has to actively set up their workspace file correspondingly, which means that they have to be aware of it. Making it so that the cc_toolchain is only required if you do remote execution is also hard. The naive approach would go against our desire not to require a C++ toolchain if you don't work with C++.

**Comment by ulfjack** [comment] 2018-05-18 09:09
I think all the possible options are problematic in some way, and I prefer to stick with the status quo absent stronger reasons for changing. Certainly, we can't use bash on Windows, but I'm more inclined to treating that as a one-off than trying to unify all platforms and push the complexity on our users. Even if it's not a lot of complexity, it's a lot of users. A little bit of complexity times a lot of users = not ideal.

**Comment by laszlocsomor** [comment] 2018-05-18 09:16
> I don't think we need to worry about the distroless images. They aren't suited for building, and I don't foresee anyone asking us to support those.

Thanks. That resolves this subthread.

> I don't think adding a Powershell version will make the divergence between Blaze and Bazel worse, per se. Making Bazel use a C++ binary while Blaze uses a shell script seems to increase divergence, not decrease it.

I considered rewriting to also cover the Blaze-specific version of `test-setup.sh`. But in light of your next argument about needing a `cc_toolchain` and the complexity implied, we can resolve this subthread too.

> If you use cc_binary, you also have to have a matching cc_toolchain rule (...) Making it so that the cc_toolchain is only required if you do remote execution is also hard.

Good point.

> I think all the possible options are problematic in some way, and I prefer to stick with the status quo absent stronger reasons for changing.

I'm out of arguments. Then let's try the Powershell approach for now. SGTY?

**Comment by laszlocsomor** [comment] 2018-07-03 14:11
Related bug: #5508.

**Comment by jmillikin-stripe** [comment] 2018-07-06 22:50
Instead of Powershell, would it be practical to rewrite the wrapper in Java? As noted earlier that adds no additional dependencies, and it solves the problem for remote execution as well.

**Comment by laszlocsomor** [comment] 2018-07-11 13:04
@jmillikin-stripe : Which problem of remote execution do you mean, and how does using Java solve it? If we used Java, Bazel would need a JDK on the remote machine.

**Comment by jmillikin-stripe** [comment] 2018-07-11 16:22
The remote execution protocol doesn't copy binaries Bazel executes unless they're registered with Bazel as a tool. Since `perl` is being executed with a simple `$PATH` lookup, Bazel won't copy it to the worker and the command would fail with `perl: not found`.

If the wrapper was written as a `java_binary` or `cc_binary` and built on demand, Bazel would properly copy it to the remote worker. I assumed a Java binary would be easier to integrate since you could distribute the compiled `.jar` in the Bazel tarball (there are some other helpers in tools/ distributed in the same way).

Considering that the Bazel buildfarm worker itself is written in Java, having a JRE installed on the remote machine doesn't seem like a big hurdle.

**Comment by laszlocsomor** [comment] 2018-07-12 09:13
True, `perl` is an undeclared dependency. There's a bug for that (https://github.com/bazelbuild/bazel/issues/5265) but I'm currently not working. Since nobody else updated the bug, I guess nobody is working on it at the moment.

Indeed a `*_binary` rule is advantageous because Bazel recompiles it from source, but it also requires a (cross)compiler for the execution platform.

As for C++, @ulfjack (who is one of the most senior Bazel engineers and a technical leader) earlier [argued against depending on the C++ compiler](https://github.com/bazelbuild/bazel/issues/4691#issuecomment-389484230) for test execution.

As for Java the `jar` file is not enough: we also need a launcher that sets up the environment and the classpath for the jar file. The launcher is a shell script on Unixes and a C++ binary on Windows.

This is why we concluded that a PowerShell script, though not ideal, seems to be the best option comparatively.

WDYT?

**Comment by laszlocsomor** [comment] 2018-07-12 09:16
I [earlier wrote](https://github.com/bazelbuild/bazel/issues/4691#issuecomment-402171436) that https://github.com/bazelbuild/bazel/issues/5508 was a _related_ bug, but I now think it subsumes _this_ bug. Maybe we should merge the two. @jmillikin-stripe , @ahippler , what do you think?

**Comment by jmillikin-stripe** [comment] 2018-07-13 02:06
> As for Java the jar file is not enough: we also need a launcher that sets up the environment and the classpath for the jar file. The launcher is a shell script on Unixes and a C++ binary on Windows.

Maybe I'm misunderstanding how modern Java works, but can't you just compile a standalone `.jar` file that depends on only the standard library? The one-line Perl expression doesn't seem like something that would need a full CLASSPATH wrapper script to deal with. I know several of the java_binary targets I've used for helpers don't have any sort of special wrappers around them, just `java -jar path/to/whatever.jar`.

Sorry if this is going off into the weeds too much, it's just that I'm looking at the Perl command and then looking at the ~180 MB of Bazel installer and thinking there's got to be a way to solve this.

> I earlier wrote that #5508 was a related bug, but I now think it subsumes this bug. Maybe we should merge the two.

#5508 seems like a bigger challenge to solve, but could be solved at the same time if the entire test wrapper was rewritten. Up to you as to whether requiring Perl is a big enough blocker to justify fixing separately.

**Comment by laszlocsomor** [comment] 2018-07-13 06:53
I agree, replacing that single Perl call shouldn't be hard with Java. The whole time I was thinking about replacing the entire test-setup.sh with a Java program.

**Comment by laszlocsomor** [comment] 2018-07-13 11:57
> I agree, replacing that single Perl call shouldn't be hard with Java. The whole time I was thinking about replacing the entire test-setup.sh with a Java program.

@nlopezgi @ola-rozenfeld Could you confirm that a JRE is always available on remote execution machines, and if so, under which path would [`test-setup.sh`](https://github.com/bazelbuild/bazel/blob/master/tools/test/test-setup.sh) find it?

**Comment by ulfjack** [comment] 2018-07-16 07:21
There's no guarantee that a JRE is available on all remote machines.

**Comment by ulfjack** [comment] 2018-07-16 08:03
No, not that I'm aware of. IIUC, Buildfarm ships with an empty docker image by default, and our internal implementation is also bring-your-own-docker image. No guarantees on what's in there, and I don't see why a C++-only project (for example) would add a JRE to their remote execution docker images.

**Comment by jmillikin-stripe** [comment] 2018-07-16 15:19
The default buildfarm image is based on `gcr.io/distroless/java`, which does include a JRE. Notably it _doesn't_ include `/bin/bash` so it can't execute genrules. We (Stripe) use a different base image that includes Bash and Coreutils, and I expect all users of fully-remote builds will have similar custom images.

**Comment by ulfjack** [comment] 2018-07-17 07:37
Right. I expect that requiring bash is fine for Linux and MacOS images. I would prefer not to require any higher-level language (like Java or Python, or even C/C++) given that there will be projects who don't want that as an additional dependency for their images. I expect that PowerShell is fine for Windows as the minimal requirement. The downside is that we end up having to maintain two implementations.

@jmillikin-stripe do you currently have Java in your remote build images? If so, why?

**Comment by jmillikin-stripe** [comment] 2018-07-17 16:55
We have Java in our remote build images because https://github.com/bazelbuild/bazel-buildfarm is implemented in Java, and needs the JRE to run its `_deploy.jar` binaries.

**Comment by laszlocsomor** [comment] 2018-07-19 16:13
I thought about this more. Bazel requires at least Windows 7 / Server 2008 R2 as the host platform, so we could require that as a minimum execution platform too.

Compiled C++ binaries are portable but across Windows versions (at least within the same architecture), though linking against MSVCRTxx.DLL requires the right DLLs to be installed on the execution machine.

AFAIK Windows Server versions (at least the Core ones) don't come with these DLLs preinstalled, but there's another option -- Win 7 / Server 2008 R2 both have .NET 3.5 preinstalled.

I don't know how the compatibility matrix looks like for .NET applications built for one version of the framework running against another version, but it seems that a C# binary built for .NET 4.0 or 4.5 can happily run on Win Server 2008 R2 (which should only have .NET 3.5). At the some time a binary linked against .NET 3.5 didn't run on my Win Server 2016 VM without wanting to install the right framework first.

Either way, .NET seems like an option we should explore further: it doesn't require any extra DLLs, we can use any .NET language (including Java, which just compile it as J#), precompile `test-setup` in it, and bundle it with the Bazel binary.

WDYT?

**Comment by laszlocsomor** [comment] 2018-07-19 16:18
> (including Java, just compile it as J#)

I'm old and living under an old rock. Apparently J# is no longer a thing. (https://en.wikipedia.org/wiki/J_Sharp)

**Comment by nlopezgi** [comment] 2018-07-24 18:02
sorry for the late reply @laszlocsomor 
JRE is not always available on remote machines. For rules that need to use it, we recommend they do via toolchain rules - not via PATH or via a hardcoded path (https://docs.bazel.build/versions/master/remote-execution-rules.html#invoking-build-tools-through-toolchain-rules). 

My 2c on the wider conversation: 
- for SingleJar and iJar in remote execution, we have to compile them on the remote execution environment. This effectively means that, currently, to use any rules that require SingleJar or iJar, your remote container needs to have a C compiler installed. So unfortunately, a remote execution container to build e.g., only Java code, needs a C compiler.

- For the record, for remote execution we highly dis-recommend using pre-compiled binaries (https://docs.bazel.build/versions/master/remote-execution-rules.html#managing-platform-dependent-binaries) even for languages that you would typically think that binaries are compatible. e.g., we have found certain Linux binary versions of the jar tool can only be used on certain versions of Linux.

- All remote execution containers are expected to have bash

**Comment by laszlocsomor** [comment] 2018-07-25 06:50
@nlopezgi : thanks for the info!

FYI, meanwhile I finished the draft of my design doc on Bash-less (and Perl-less) test execution on Windows, see https://github.com/bazelbuild/proposals/pull/16. In that doc I argue for using a precompiled Windows binary, because Bazel only runs on x86_64 Windows and AFAIK remote execution also only runs x86_64 Windows, so binaries are portable.

Are you suggesting I could safely choose C++ as the implementation language, and ship the source code with Bazel, and a C++ compiler is always available on the remote execution machine to build it? If so, is that going to stay that way for the foreseeable future (say, 1 year)?

**Comment by nlopezgi** [comment] 2018-07-25 13:53
I think the decision to use pre-compiled binary incurs in some technical debt that someone might end up having to pay down the line (e.g., whenever we decide to allow something else other than x86_64 Windows), but I understand there might not be other feasible solutions.

wrt using C++, we do have a restriction of currently needing C++ compiler for any builds that require use of java rules. I'm not sure we want to extend that to also be a requirement for all test rules. I do think that _some_ language tools will always be needed to compile so called 'embedded tools' (which is a non-issue for local execution). These language tools thus will necessarily be required in remote execution containers, and a C++ compiler is a good choice as we offer a very stable and up to date one for use with remote execution containers (for Linux only, though).

**Comment by laszlocsomor** [comment] 2018-07-25 14:05
Thanks.

Re: technical debt: I hear you, but your point sounds rather speculative, so I'd not worry about non-x64 Windows platforms for the foreseeable future (say 1 year).

Re: compiler: since you don't want to require it for tests, which I also agree with, I think C++ is *not* the right language for the test wrapper on Linux. (It still seems like the right choice on Windows.)

But then I don't know what's the right choice for Linux, if only Bash is promised (without Perl). Maybe a clever `sed` program could help?

**Comment by laszlocsomor** [comment] 2018-07-25 15:44
@nlopezgi , another question: do you know how Bazel cancels a remotely running test action in case the user presses Ctrl+C? Does Bazel dispatch this to the remote service or does it just close the connection?

**Comment by nlopezgi** [comment] 2018-07-25 16:00
re: compiler: I did not state I did not want to require it for tests, just that I was not sure its the right choice and don't want to be the one to make it w/o at least conferring with some other folks (I'll get back to you once I've confirmed). imo, if some tool is to be required for all tests, i'd rather it is the c++ compiler (instead of perl or python), but not sure what the trade-offs (effort/maintenance) between c++ vs a clever sed program would be.

re: canceling a test: not sure, you'd want to ask @ola-rozenfeld about api details

**Comment by laszlocsomor** [comment] 2018-07-26 09:51
I was too optimistic with the "clever sed program". The task is to UTF-8-decode an octet-stream, test decoded characters if they fall into any of some disjoint ranges and replace them with "?", then UTF-8-encode the result again.

I'm not aware of an efficient way to do this without encoding and decoding.

**Comment by ulfjack** [comment] 2018-07-26 10:09
You don't need to decode and re-encode - you can simply test on the utf-8 representation using seds regexp support.

**Comment by laszlocsomor** [comment] 2018-07-26 10:18
How? Does `sed` support matching UTF-8 strings?

**Comment by ulfjack** [comment] 2018-07-26 11:47
After a lot of trial and error, I've come up with a sed script that - I think - does what we want:
```
cat test.log | LANG=C sed -E -e 's/.*/& /g' -e 's/(([\x9\xa\xd\x20-\x7f]|[\xc0-\xdf][\x80-\xbf]|[\xe0-\xec][\x80-\xbf][\x80-\xbf]|[\xed][\x80-\x9f][\x80-\xbf]|[\xee-\xef][\x80-\xbf][\x80-\xbf]|[\xf0][\x80-\x8f][\x80-\xbf][\x80-\xbf])*)./\1?/g' -e 's/(.*)\?/\1/g'
```

**Comment by ulfjack** [comment] 2018-07-26 11:50
First, add a single white space character (' ') to the end of each line. Second, replace all (possibly empty) sequences of legal characters followed by a character with the sequence of legal characters followed by a question mark character ('?'). Third, remove the trailing question mark character ('?') from each line.

**Comment by laszlocsomor** [comment] 2018-07-26 12:30
> you need to cover the entire 2-octet UTF-8 domain

Sorry that's wrong. I meant, you need to cover the U+80 .. U+7FF range, which covers the entire 2-octet range and part of the 3-octet range.

**Comment by laszlocsomor** [comment] 2018-07-26 12:31
Sorry, I got confused, gimme a minute to correct this.

**Comment by laszlocsomor** [comment] 2018-07-26 12:33
> you need to cover the entire 2-octet UTF-8 domain (U+80 .. U+7FF)

This is wrong. I meant to say: you need to cover the U+80..U+7FF (two UTF-8 octets) and U+800..U+D7FF (three UTF-8 octets) ranges. The 2-octet domain is covered correctly (`[\xc0-\xdf][\x80-\xbf]`), but I think the 3-octet-matching regex is wrong in your solution.

**Comment by ulfjack** [comment] 2018-07-26 12:42
Ok, how about this:
```
[\x9\xa\xd\x20-\x7f]                    <--- (9,A,D,20-7F)
[\xc0-\xdf][\x80-\xbf]                  <--- (0080-07FF)
[\xe0-\xec][\x80-\xbf][\x80-\xbf]       <--- (0800-CFFF)
[\xed][\x80-\x9f][\x80-\xbf]            <--- (D000-D7FF)
[\xf0][\x80-\x8f][\x80-\xbf][\x80-\xbf] <--- (010000-10FFFF)
```

**Comment by ulfjack** [comment] 2018-07-26 12:45
Wait, there's still one range missing. Gah!

**Comment by laszlocsomor** [comment] 2018-07-26 12:47
Ah I see where I was wrong, you are right to match 0800-CFFF and match D000-D7FF separately.

**Comment by ulfjack** [comment] 2018-07-26 13:00
Another try:
```
[\x9\xa\xd\x20-\x7f]                         <--- (9,A,D,20-7F)
[\xc0-\xdf][\x80-\xbf]                       <--- (0080-07FF)
[\xe0-\xec][\x80-\xbf][\x80-\xbf]            <--- (0800-CFFF)
[\xed][\x80-\x9f][\x80-\xbf]                 <--- (D000-D7FF)
[\xee][\x80-\xbf][\x80-\xbf]                 <--- (E000-EFFF)
[\xef][\x80-\xbe][\x80-\xbf]                 <--- (F000-FFEF)
[\xef][\xbf][\x80-\xbd]                      <--- (FFF0-FFFD)
[\xf0-\xf7][\x80-\xbf][\x80-\xbf][\x80-\xbf] <--- (010000-10FFFF)
```

**Comment by ulfjack** [comment] 2018-07-26 13:19
Ok, I wrote a small Java program to double-check the pattern, and it returned the expected ranges:
```
9-a,d-d,20-d7ff,e000-fffd,10000-10ffff
```

**Comment by laszlocsomor** [comment] 2018-07-26 13:20
I'm glad we are free now.

**Comment by ulfjack** [comment] 2018-07-26 13:41
Ok, I have a patch which conflicts with my other changes to test-setup.sh. Both are a bit risky, and we need to pick one to be merged first.

**Comment by laszlocsomor** [comment] 2018-07-26 13:42
If you have changes lined up, merge those first.
This bug has been open for a long time, it's OK to wait another day.

**Comment by ulfjack** [comment] 2018-08-03 08:54
Patch is here: https://bazel-review.googlesource.com/c/bazel/+/68711

There are still a couple possible issues with this that we need to look into.

My primary concern is what should happen if the default charset of the current machine is NOT UTF-8. The previous Perl solution was broken as well: it did a charset conversion from the default charset to UTF-8 on input, but also from UTF-8 to the default charset on output, which can actually re-introduce illegal characters (we might want to file a bug for that, or note it on the existing bug), breaking the resulting XML.

The new code intentionally does not perform any charset conversion.

Ideally, we'd do a charset conversion from the default charset to UTF-8 before running the sed script. Note that I override the LOCALE before running sed, which probably sets the default charset to ISO-8859-1 (this needs to be double-checked!).

- find a way to do charset conversion from the default charset to utf-8; we might be able to get sed to do that for us, but we need to prevent a charset conversion on *output*
- make sure to set the default charset temporarily to ISO-8859-1 for the sed invocation
- make sure that all copies of this code are updated

**Comment by ulfjack** [comment] 2018-08-03 08:54
(I'm on vacation for the rest of August, and won't be able to work on this until I'm back.)

**Comment by laszlocsomor** [comment] 2018-08-03 09:04
Thanks!

> The previous Perl solution was broken as well: it did a charset conversion from the default charset to UTF-8 on input, but also from UTF-8 to the default charset on output, which can actually re-introduce illegal characters (we might want to file a bug for that, or note it on the existing bug), breaking the resulting XML.

Please elaborate. How and where exactly are the conversions done?

> (I'm on vacation for the rest of August, and won't be able to work on this until I'm back.)

Do you intend to finish this task yourself or to appoint it to someone else (and if so, whom)?

**Comment by ulfjack** [comment] 2018-08-03 09:58
If it's still open when I'm back, I'll do it. If someone comes in and finishes my changes, I'm happy, too.

Perl does implicit charset conversion on every read and write from a file or stdin/stdout. I believe it converts from the platform default charset to UTF-8 internally. That's my reading of the docs, anyway.

**Comment by ulfjack** [comment] 2018-11-26 14:59
I have a pending patch.

**Comment by Profpatsch** [comment] 2018-12-19 13:35
Would be awesome to see that line go. It’s the last remaining use of `perl` in bazel from what I can see (I already removed the other use in https://github.com/bazelbuild/bazel/pull/5999).

Go @ulfjack! :running_man:

**Closed** 2019-01-22 10:44 UTC
Labels: P1, category: rules > misc native, platform: windows, type: bug
