### ISSUE TITLE
Unity Builds

### ISSUE THREAD

**Issue by nordlow** [bazelbuild/bazel#3226] opened 2017-06-20 16:53 UTC
Are there any plans to add unity-builds-support for library and program targets?

For instance, [Meson has builtin support for unity builds](http://mesonbuild.com/Unity-builds.html).

It would be really neat if the build system could automatically detect which source-files are so small in size (and in turn in compilation time) that they should be grouped together and compiled into a single object before being linked to a library or program.

**Comment by MarkusTeufelberger** [comment] 2017-06-20 21:50
Seems to hurt parallelism and artifact caching... maybe it could be enough to prefetch files that will be compiled? After all, Bazel should already know which files it will access during a build, so there might be a way to notify the OS about this fact.

This would still take a hit from spawning a full sandbox + compiler process etc. for each (tiny) file, but could already be a way to do what unity builds are doing.

I personally am not a big fan of unity builds, since they lead to large files only consisting of "#include" statements and can hide missing includes in the actual files (since the missing header is then included in the unity file). They seem to me like a hack to get around some problems in code layout, disk caching or compiler startup time, not so much like a good design pattern.

When developing, they seem to hurt your re-compile time and fill your cache with larger files - and when building a release you are probably not that concerned about build time anyways.

That all is just my personal opinion though, unity builds are not a feature I would use or recommend to be used, but they might have their merits for some people or projects.

**Comment by philwo** [comment] 2017-06-21 10:02
I don't think is on our roadmap and maybe not even a wanted feature for Bazel, but assigning to @lberki to have a look.

**Comment by lberki** [comment] 2017-06-21 11:22
@mhlopko 

I'd empathically advise *against* doing this, mainly because I have experience with it.

My experience is that if this is done, individual source files will inevitably influence each other through included files and `#define`s leaking from one to the other. A much more principled approach is modules. Then you avoid parsing and compiling a lot of header files and thus gain performance without compromises like the above.

If you *really* want to do this, you can always do it manually, but doing it automatically based on heuristics is asking for trouble.

**Closed by lberki** 2017-06-21 11:22 UTC
Labels: P4, type: feature request

**Comment by Bu11etmagnet** [comment] 2020-11-25 12:20
Nobody same uses unity builds during development (because those who do would have been driven insane by the build times caused by compiling every single source file), which means that includes leaking from one source to another is a strawman argument. The alleged bad practices enabled by unity build would break the daily dev builds.

Unfortunately, modules is not the solution, as long as the standard library is not fully modularized.

**Comment by aaron-michaux** [comment] 2024-09-09 20:47
The funny thing about these comments is:
 * Yes everyone should know that Unity builds rely on a certain level of coding hygine.
 * Unity builds can be orders of magnitude faster, because in C/C++, build time tends to grow quadratically with the number of files. With unity builds, it does not. So what would take 2-3 hours can be cut down to 5min.

**Comment by eli-schwartz** [comment] 2025-01-27 05:50
If you haven't read it before, take a look at https://engineering.leewinder.co.uk/2009/12/15/the-evils-of-unity-builds/ :)

**Comment by bsergean** [comment] 2025-10-04 00:30
cmake has support for unity build too, and for our projects which has tons of source files the speedup is massive.

You could argue that with a distributed build farm or whatnot (what big company like Google have, but most of the world doesn't) it isn't really an issue, but those farms typically only exist for Linux build, not for macOS or Windows.

So this is closed and my comment is a bit useless and a rant ... but making the point that big code base really benefit from this. I guess another option is to build through docker on Linux, but then debugging is slower or doesn't work, or is hard to setup, etc...
