### ISSUE TITLE
Lousy progress indicator

### ISSUE THREAD

**Issue by pauldraper** [bazelbuild/bazel#5983] opened 2018-08-25 04:55 UTC
Bazel has a lousy progress indicator. Example:

https://github.com/tensorflow/tensorflow/issues/14294

I'm sure there's some clever reason for the very....slowly....ever....increasing....upper bound.

But the fact remains that it is worthless or even less than worthless as a progress indicator, since it gives the illusion of having some useful meaning. In many cases like when building tensorflow it would be more truthful for just have a single number of the actions so far.

Anecdotally, this seems to be a problem more often with native C/C++ rules, but not Skylark rules.

**Comment by jin** [comment] 2018-08-25 17:28
That's because the minimum set of required actions to be executed is not known at the start of the execution phase. Please see @ulfjack's answer in https://github.com/bazelbuild/bazel/issues/3582#issuecomment-329405311

Also a relevant SO question: [bazel: why do targets keep increasing if build graph is known ](https://stackoverflow.com/questions/51484140/bazel-why-do-targets-keep-increasing-if-build-graph-is-known)

Closing this as a duplicate of https://github.com/bazelbuild/bazel/issues/3582.

**Closed by jin** 2018-08-25 17:28 UTC
