### ISSUE TITLE
CI, bazel-nightly: rules_go and bazel-watcher are failing

### ISSUE THREAD

**Issue by laszlocsomor** [bazelbuild/bazel#4232] opened 2017-12-05 14:54 UTC
https://ci.bazel.io/job/Global/job/rules_go/301/console
https://ci.bazel.io/job/Global/job/bazel-watcher/301/console

The tests ran with a Bazel binary built at https://github.com/bazelbuild/bazel/commit/ddd5ac16aeffa6c4693c348f73e7365240b1abc5.

https://ci.bazel.io/job/Global/job/rules_go/301/console example log:
```
[node=darwin-x86_64] [rules_go-node=darwin-x86_64] Running shell script
[node=darwin-x86_64] + /Users/ci/.bazel/custom/bazel_nightly/144/variation_/binary/bazel --bazelrc=/Users/ci/workspace/Global/rules_go-node=darwin-x86_64/bazel.bazelrc build //...
[node=darwin-x86_64] Loading: 
[node=darwin-x86_64] Loading: 0 packages loaded
[node=darwin-x86_64] ERROR: /Users/ci/workspace/Global/rules_go-node=darwin-x86_64/WORKSPACE:16:1: Traceback (most recent call last):
[node=darwin-x86_64] 	File "/Users/ci/workspace/Global/rules_go-node=darwin-x86_64/WORKSPACE", line 16
[node=darwin-x86_64] 		popular_repos()
[node=darwin-x86_64] 	File "/private/var/tmp/_bazel_ci/4f531c261ba18cae8a788132c5661380/external/io_bazel_rules_go/tests/popular_repos/popular_repos.bzl", line 30, in popular_repos
[node=darwin-x86_64] 		go_repository(name = "org_golang_x_net", importp...", ...")
[node=darwin-x86_64] Cannot redefine repository after any load statement in the WORKSPACE file (for repository 'org_golang_x_net')
[node=darwin-x86_64] ERROR: Error evaluating WORKSPACE file
[node=darwin-x86_64] ERROR: error loading package 'external': Package 'external' contains errors
[node=darwin-x86_64] INFO: Elapsed time: 0.841s
[node=darwin-x86_64] FAILED: Build did NOT complete successfully (0 packages loaded)
[node=darwin-x86_64] FAILED: Build did NOT complete successfully (0 packages loaded)
```

**Comment by laszlocsomor** [comment] 2017-12-05 14:54
Blocking: https://github.com/bazelbuild/bazel/issues/3773

**Comment by laszlocsomor** [comment] 2017-12-05 15:25
@iirina : please triage this

**Comment by iirina** [comment] 2017-12-05 16:20
cc: @katre Can you look at the `bazel-tests` failure? It looks like `src/test/shell/bazel/toolchain_test.sh` is failing.

**Comment by katre** [comment] 2017-12-05 16:23
Taking a look now.

**Comment by katre** [comment] 2017-12-05 17:12
Even logging into the failing node (freebsd-11-1), I cannot reproduce the failure. I suggest re-running to see if this is a flake.

**Comment by iirina** [comment] 2017-12-05 17:16
cc: @achew22 Could you take a look at the bazel-watcher failure?

**Comment by iirina** [comment] 2017-12-05 17:24
I rebuilt the nightly now.

**Comment by iirina** [comment] 2017-12-05 17:43
CC: @ianthehat Seems like the error in `rules_go` is caused by [this commit](https://github.com/bazelbuild/rules_go/commit/a62852fa5770d732065abc0a06d454a9ba7140b3#diff-9a44ab518ae793340ef94addf36bc22b)

**Comment by ianthehat** [comment] 2017-12-05 20:15
https://github.com/bazelbuild/rules_go/pull/1105 may or may not fix the
problem, I can't replicate it myself so this is pure guesswork.

**Comment by laszlocsomor** [comment] 2017-12-06 07:46
@iirina , @katre : actually, the "bazel-tests" failure is different from these ones, it's the same as https://github.com/bazelbuild/bazel/issues/4233. I'll update that bug by moving "bazel-tests" there.

**Comment by damienmg** [comment] 2017-12-06 14:09
As I said in the release bug, this problem is causing by 337f19cc54e77c45daa1d5f61bf0a8d3daf8268f (I double checked). Although we do want rules_go to well behave, updating bazel-watcher and buildtools needs a release of rules_go, and updating it.

We have the time to do the update or we can rollback 337f19cc54e77c45daa1d5f61bf0a8d3daf8268f and include it in the release, and ship the commit in the next release.

The advantage of the former is we don't need a cherry-pick.

/cc @achew22 @laurentlb for updating the two downstream repo.

**Comment by damienmg** [comment] 2017-12-06 14:13
Sorry I mess up, buildtools is not affected, so there is only one repo needed to update. @ianthehat: do you think we can a get a rules_go release?

**Comment by damienmg** [comment] 2017-12-06 15:06
Yes I tested with and without your change. Your change fix it.

**Comment by laszlocsomor** [comment] 2017-12-06 15:45
Thanks for following up. No Bazel cherrypick from this thread then. Can we close it?

**Comment by laszlocsomor** [comment] 2017-12-08 10:37
Can we close this bug?

**Comment by damienmg** [comment] 2017-12-08 11:48
Nightly and release are still broken, no?

**Comment by laszlocsomor** [comment] 2017-12-08 12:26
The projects are broken, yes, but not because of Bazel. But true, we shouldn't yet close this bug.

**Comment by laszlocsomor** [comment] 2017-12-11 10:27
@damienmg wrote 5 days ago:
> As I said in the release bug, this problem is causing by 337f19cc54e77c45daa1d5f61bf0a8d3daf8268f (I double checked). Although we do want rules_go to well behave, updating bazel-watcher and buildtools needs a release of rules_go, and updating it.

https://github.com/bazelbuild/bazel/commit/766ba8adc4487f17ebfc081aeba6f34b18b53d6c rolled back 337f19cc54e77c45daa1d5f61bf0a8d3daf8268f, and the former is cherrypicked into Bazel 0.9.0 RC3 (see https://github.com/bazelbuild/bazel/issues/3773#issuecomment-350276612), so I'm removing the "Release blocker" tag.

**Comment by mhlopko** [comment] 2018-01-03 15:06
Closing since it seems this is all resolved. Rules_go and bazel-watcher are green, 0.9.0 is released. Thank you all for working on this!

**Closed by mhlopko** 2018-01-03 15:06 UTC
Labels: breakage, P1
