### ISSUE TITLE
`repository_ctx.download_and_extract` should create necessary directories

### ISSUE THREAD

**Issue by colinmarc** [bazelbuild/bazel#1235] opened 2016-05-04 22:19 UTC
This is exactly the same as https://github.com/bazelbuild/bazel/issues/1078. `repository_ctx.download_and_extract` doesn't create the destination dir, so you have to do something like:

```
ctx.file(ctx.path("empty"), "")
ctx.download_and_extract(...)
```

**Comment by zaphar** [comment] 2016-05-07 15:35
This bug caused my no end of confusion while implementing mono as an external repository. Thanks for the workaround 👍

**Comment by damienmg** [comment] 2016-05-27 17:07
This is a duplicate of #1172

**Closed by damienmg** 2016-05-27 17:07 UTC
Labels: category: skylark remote repositories, P2, type: bug
