### ISSUE TITLE
Bazel strips ~/homebrew/bin out of PATH

### ISSUE THREAD

**Issue by girving** [bazelbuild/bazel#957] opened 2016-02-22 21:01 UTC
I am trying to build tensorflow on my Google Mac laptop.  Since `/usr/local` is taken, I installed homebrew to `~/homebrew`.  I then installed swig via homebrew:

```
shimura:~% type swig
swig is /Users/geoffreyi/homebrew/bin/swig
```

Unfortunately, bazel removes the `~/homebrew/bin` portion of my path, and therefore fails to find swig:

```
shimura:tensorflow% bazel build --spawn_strategy=standalone ...
INFO: Found 636 targets...
INFO: From SWIGing tensorflow/python/tensorflow.i:
bazel-out/host/bin/tensorflow/swig: line 17: swig: command not found
ERROR: /Users/geoffreyi/tensorflow/tensorflow/python/BUILD:899:1: SWIGing tensorflow/python/tensorflow.i failed: swig failed: error executing command bazel-out/host/bin/tensorflow/swig -c++ -python -module pywrap_tensorflow -ltensorflow/python/client/events_writer.i -ltensorflow/python/client/tf_session.i ... (remaining 153 argument(s) skipped): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 127.
INFO: Elapsed time: 1.512s, Critical Path: 0.80s
```

**Comment by jmmv** [comment] 2016-02-23 02:36
Because of the client/server nature of Bazel, I suspect the `PATH` is only read from the server's environment. Did you try to restart the server after changing the `PATH`?

If that works, that'd be an argument to say that the server should be restarted when the user's environment changes.

If that doesn't work, it's possible that the server is being spawned on a "clean" environment (but I doubt so).

**Comment by girving** [comment] 2016-02-23 04:56
Nope, that isn't the issue.  Restarting the server does nothing.

**Comment by ulfjack** [comment] 2016-02-23 08:23
Bazel ignores basically all external environment settings in order to
guarantee reproducible builds. Unfortunately, it sounds like tensorflow is
relying on certain binaries to be available on the path, which can fail if
they aren't on the default path. What does tensorflow/swig line 17 actually
say?

**Comment by girving** [comment] 2016-02-24 01:59
It just says `swig "$@"`: https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/swig/swig.sh

**Comment by philwo** [comment] 2016-02-26 09:33
According to their BUILD file, tensorflow indeed relies on swig just being present on the PATH:
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/BUILD#L27

Not sure what our proposed fix for this is - on the one hand, they should probably vendor swig, build it using Bazel and then use the resulting binary in their swig.sh tool, on the other hand this is hard, so people usually say "no, let's just disable the sandbox, rely on things being present in the PATH and everything will be fine". However, we only give them our idea of what an ideal PATH should look like, instead of what the user really has set as their own PATH.

**Comment by girving** [comment] 2016-02-26 16:21
Okay, I'll try to figure out some sort of ugly hack around the problem on our end.  It's unfortunate that not being able to build on my laptop is called a feature request instead of a bug, though.

**Comment by damienmg** [comment] 2016-02-26 16:25
The thing is Bazel does not currently have any sort of auto configuration, we are working on it but its a feature bazel did not had. See https://docs.google.com/document/d/1Ju74cmBCfYl8SEZT_tXhRmbi49ZLMzXgoQzzqve-dxI

**Comment by philwo** [comment] 2016-02-28 21:51
@damienmg Could you explain what the connection between this feature request and auto configuration is? I don't understand the relation between the linked doc and this request. AFAIK the request is to simply inherit and use the PATH from the environment that the user runs Bazel in for spawn actions that Bazel runs.

@girving We made a conscious choice of not doing that, for various reasons:

- Running binaries from $PATH is discouraged as opposed to checking them into a repository and running them from there, due to issues with Bazel not being able to track the checksums of binaries run from $PATH, not being able to pull them into its sandbox, not being able to ship them to remote execution servers.
- Environment variables like PATH are part of the build environment, which should be standardized as much as possible to make it easy to do bit-identical reproducible builds on a variety of machines. One might argue whether PATH should be standardized or not - we decided to do so and haven't run into issues so far, so please understand that we don't want to easily change this without having a good reason.
- The PATH is likely to vary among user systems (for example, I usually have a ~/bin folder in my PATH on my personal machines, and ~/homebrew where I can't use /usr/local). As the environment variables of a spawn action go into its caching key, this would mean that remote caching systems would cache multiple copies of the same spawn action, one for each variation of PATH seen.

Now, that said, I totally understand your frustration. And maybe we're wrong and Bazel should instead use your PATH. We'll discuss this and the implications of such a change. You can help us by supplying arguments why you think this is the right thing to do for a build system that has "reproducible builds" (see https://reproducible-builds.org/ for a nice explanation by a third party) as its highest goal.

(By the way, "feature request" does not mean "low priority" for us, but "requested change of deliberate behavior or design" as opposed to "fixing an issue where Bazel did not do what its specification / design said it is supposed to do". Priority P2 means "yep, this is important, we should work on this", which I think is appropriate, as P1 would make it a "drop all other stuff you're working on until this is done" issue, which I don't think this is, but feel free to correct me.)

**Comment by girving** [comment] 2016-02-28 22:53
If you think this is a TensorFlow bug, what would be the right way to solve it on our end?  Building swig as part of TensorFlow seems extreme: we already get other dependencies via homebrew or apt-get, and swig is easily available from there.  I filed on an issue for TensorFlow at https://github.com/tensorflow/tensorflow/issues/1329, and would appreciate any suggestions for how to resolve it.  Thanks!

**Comment by damienmg** [comment] 2016-02-28 22:55
@philwo: the way it works is that you can inherit the environment trough a custom repository in which case this will be part of an auto-configuration step.

**Comment by damienmg** [comment] 2016-02-28 22:56
(and in that precise case, I think swig should be discovered that way, Tensorflow shouldn't expect swig to be on the path)

**Comment by girving** [comment] 2016-02-28 22:57
@damienmg: Does that mean the correct way for TensorFlow to use swig is unavailable in Bazel today?  Is there an alternative that works now?

**Comment by damienmg** [comment] 2016-02-28 23:00
It was unavailable until last week at HEAD. I think we need to wait until next release before it can be used in TF.

**Comment by girving** [comment] 2016-02-28 23:03
We already have a configure script outside of Bazel, so we can always resort to manufacturing a script with a hard coded path.

**Comment by damienmg** [comment] 2016-02-28 23:15
Yes that would be the correct workaround until then.

(btw we are in MTV this week, we will arrive on Tuesday, I am meeting with Martin on Friday, ping if you wish to meet).

**Comment by girving** [comment] 2016-02-28 23:30
@damienmg: Thanks!  By way: I appreciate your reproducible build goals, and it's sad that we're not in a better position to take advantage of them instead of clashing.  I also appreciate the difficulty of trying to be principled in an unprincipled world: I once tried to make a build system that reconstructed the dependency dag by intercepting syscalls, and got hung up when I discovered that gas reads its own output files before writing them. :)

**Comment by jmmv** [comment] 2016-02-29 19:52
@philwo Could I convince you to add your great answer to the FAQ? There currently is an entry titled "*Why do I need to have a tools/ directory in my package path?*" but that does not seem to cover this topic in as detail as you did. Also, I would add a second question titled "*Why doesn't Bazel respect my PATH?*" which better illustrates what the user may think; both can point at the same answer though.

**Comment by tomwardio** [comment] 2016-05-11 12:23
I had the same problem. Issue was closed as is a bazel issue. https://github.com/tensorflow/tensorflow/issues/681

**Comment by philwo** [comment] 2016-05-31 11:01
FYI, as part of a project that will make sandboxing easier to use, we'll change the behavior of Bazel to not strip PATH from the environment by default. I'll update this bug when this is done.

**Comment by philwo** [comment] 2016-12-09 14:20
@aehlig I think this is another candidate for the default flip of use_default_shell_env to true.

**Comment by meisterT** [comment] 2020-05-15 06:26
@philwo is this done already?

**Comment by philwo** [comment] 2020-05-15 08:43
Yes, `PATH` is being passed through as is:

```
philwo@takaramono:src/bazeltest $ cat BUILD 
genrule(
    name = "env",
    srcs = [],
    outs = ["out.txt"],
    cmd = "env && touch \"$@\"",
)

philwo@takaramono:src/bazeltest $ bazel build :env
INFO: Analyzed target //:env (4 packages loaded, 7 targets configured).
INFO: Found 1 target...
INFO: From Executing genrule //:env:
TMPDIR=/var/folders/xd/hbs3lfxs1yx_fdn8ft_vchd00000gn/T/
__CF_USER_TEXT_ENCODING=0x1F5:0x0:0x0
PATH=/Users/philwo/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Users/philwo/Library/Python/3.7/bin:/Users/philwo/go/bin
PWD=/private/var/tmp/_bazel_philwo/4a364319fc3d8df0c065ab50c0bb07a6/sandbox/darwin-sandbox/1/execroot/__main__
SHLVL=1
_=/usr/bin/env
Target //:env up-to-date:
  bazel-bin/out.txt
INFO: Elapsed time: 0.755s, Critical Path: 0.19s
INFO: 1 process: 1 darwin-sandbox.
INFO: Build completed successfully, 2 total actions
```

**Closed by philwo** 2020-05-15 08:43 UTC
Labels: P2, category: sandboxing, type: feature request
