### ISSUE TITLE
Enable run_under for builds

### ISSUE THREAD

**Issue by abergmeier-dsfishlabs** [bazelbuild/bazel#1655] opened 2016-08-16 12:06 UTC
To test actions it would be great if we could have `run_under` also work for `build`. Currently tracing a buggy action is quite problematic.

**Comment by ulfjack** [comment] 2016-12-01 19:18
What should run_under do for build?

**Comment by abergmeier-dsfishlabs** [comment] 2016-12-02 08:17
IMO it should e.g. prepend the `action.executable` with the value of `run_under`. This way you could e.g. wrap an action in Valgrind.

**Comment by ulfjack** [comment] 2016-12-07 22:30
We have a similar feature request internally, and just discussed this offline. Unfortunately, making run_under work for normal actions is weird and will likely run into problems at scale. Note that our builds often have thousands or tens of thousands of actions, and printing even a single line from _every_ action would quickly break your terminal. As a result, we'd have to add filtering and whatnot. Also, run_under can refer to cc_binary rules (or similar), which would immediately introduce cycles if applied to (almost) any non-test rules.

However, we have a mechanism that solves a somewhat similar problem - extra actions. We're internally investigating whether extra actions can be made to work for our use case. I'll report back here if I don't forget it.

**Comment by ulfjack** [comment] 2017-02-15 09:49
@lberki, can you describe why we decided not to go with extra actions?

**Comment by lberki** [comment] 2017-02-15 10:27
My recollection is that because they wanted to have the exact command lines, which we don't provide for e.g. C++ and Java compile actions (we provide the extra action info in a more structured format). I don't remember, though, why the solution was not just to provide the command line (which Bazel knows).

**Comment by jmmv** [comment] 2020-05-14 15:00
Given the difficulty in doing this as said before, the possibility of using extra actions as a workaround, and the staleness of this request, I'll have to close this as "working as intended".

**Closed by jmmv** 2020-05-14 15:00 UTC
Labels: P3, team-Local-Exec, type: feature request
