### ISSUE TITLE
Have a --keep_test_tmpdir to keep the tmpdir of tests and delete it by default.

### ISSUE THREAD

**Issue by damienmg** [bazelbuild/bazel#1449] opened 2016-06-28 11:35 UTC
@philwo has cleaned the whole output trees but we should fix the underlying problem.

**Comment by damienmg** [comment] 2016-07-25 09:31
Reassigning to @philwo who has been doing work on it recently.

**Comment by philwo** [comment] 2016-07-25 09:37
I think this is "fixed" for the moment, because @lberki committed this interim solution: https://github.com/bazelbuild/bazel/commit/9cf8209e7f59354430f63a5999b80c55285a593e

Following up on this, we should make a decision whether this is working as intended (and we should fix it on the CI side, for example by deleting the _tmp directory after each run), or whether StandaloneTestStrategy should delete TEST_TMPDIR after a test completed (which would be https://github.com/bazelbuild/bazel/issues/1518).

We actually have people currently using TEST_TMPDIR after a test has completed, because they want to inspect the generated files when something went wrong or during development. But maybe they'd be happy with a flag like --keep_test_tmpdir.

**Comment by damienmg** [comment] 2016-07-25 09:45
my stake on that is to have the --keep_test_tmpdir :)

**Comment by lberki** [comment] 2016-07-25 09:49
Sounds like a plan. @philwo had aired that already and there weren't any objections.

**Comment by lberki** [comment] 2016-07-25 09:53
...also note that this issue stems from another, more subtle one, namely, that the name of the temp directory is a function of the number of tests run before in the same build:

https://github.com/bazelbuild/bazel/blob/master/src/main/java/com/google/devtools/build/lib/rules/test/TestStrategy.java#L300

Regardless of whether we go with `--keep_test_tmpdir` or not, it would be nice to fix this little piece of non-determinism.

**Comment by ulfjack** [comment] 2016-12-08 16:19
Note to future self: #1518 was marked a dupe of #1449.

**Comment by ulfjack** [comment] 2016-12-08 16:20
I have a (non-functional, at this time) patch to fix the standalone test strategy, which may fix the cleanup issue. Which would break the people who use TEST_TMP_DIR after a build... I hope I remember that when I'm back at my desk.

**Closed** 2018-07-19 12:29 UTC
Labels: P2, category: performance, type: feature request

**Comment by cnsgsz** [comment] 2018-12-07 18:20
Hi, what is the suggested way to switch between keeping the test tmp files or not?
1. os.environ.get("TEST_TMPDIR") does not seem to exist after test finishes.
2. --keep_test_tmpdir does not seem to be a valid argument to bazel.
3. os.environ.get("TEST_UNDECLARED_OUTPUTS_DIR") does not seem to exist after test finishes but becomes a zip in bazel-testlogs. So if I keep running the test with os.environ.get("TEST_UNDECLARED_OUTPUTS_DIR"), my disk will not fill up?

**Comment by philwo** [comment] 2018-12-08 08:50
I don't know anything about TEST_UNDECLARED_OUTPUTS_DIR, but can tell you about TEST_TMPDIR:

Bazel itself doesn't explicitly clean up the TEST_TMPDIR after execution (it just ensures that it's cleaned before a test runs, in case an old TEST_TMPDIR at the path still exists).

However when using sandboxing (which is the default), test TEST_TMPDIR is insides the sandbox for each test and the sandbox is deleted after the test completes, thus implicitly the TEST_TMPDIR will also be deleted.

If you need to retain the TEST_TMPDIR for debugging, maybe you can just run your test without sandboxing. Either add the tag "no-sandbox" to your test:

```
sh_test(
    name = "test",
    srcs = ["test.sh"],
    tags = ["no-sandbox"],
)
```

or disable sandboxing in general when you run tests:

```
bazel test --strategy=TestRunner=local //my:test
```

Hope this helps!

**Comment by cnsgsz** [comment] 2018-12-09 03:01
Thanks Philipp! Your suggestion works great.

**Comment by cnsgsz** [comment] 2018-12-17 01:50
Is there a default location (symlink location is fine) for TEST_TMPDIR?

An alternative is simply run bazel run xyz instead of bazel test xyz.
