### ISSUE TITLE
"Server crashed during startup" in CI environment

### ISSUE THREAD

**Issue by ixdy** [bazelbuild/bazel#4311] opened 2017-12-15 23:36 UTC
Please provide the following information. The more we know about your system and use case, the more easily and likely we can help.

### Description of the problem / feature request / question:

We're running Bazel in our CI environment (Prow, which runs Bazel inside Docker on GKE). Starting with Bazel 0.7.0, we noticed Bazel occasionally crashing during startup, and it seems to continue with Bazel 0.8.1.

Using `--batch` seems to mitigate the issue, but we make several successive Bazel calls, so would like to avoid its usage if possible.

### If possible, provide a minimal example to reproduce the problem:
No great repro steps yet. There were two recent failures after we upgraded to Bazel 0.8.1 and reverted the `--batch` mitigation:
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/57221/pull-kubernetes-bazel-build/20714/
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/57221/pull-kubernetes-bazel-test/22094/

In both cases, we were just running `bazel version`, but it crashed:
```
W1215 22:29:00.731] Run: ('bazel', 'version')
W1215 22:29:03.479] INFO: $TEST_TMPDIR defined: output root default is '/root/.cache/bazel'.
W1215 22:29:03.482] Extracting Bazel installation...
W1215 22:29:46.215] .
W1215 22:29:46.215] Server crashed during startup. Now printing '/root/.cache/bazel/_bazel_root/e9f728bbd90b3fba632eb31b20e1dacd/server/jvm.out':
```

(nothing was printed from jvm.out)

### Environment info
* Operating System: Linux / Docker / GKE

* Bazel version (output of `bazel info release`):
release 0.8.1

* If `bazel info release` returns "development version" or "(@non-git)", please tell us what source tree you compiled Bazel from; git commit hash is appreciated (`git rev-parse HEAD`):

###  Have you found anything relevant by searching the web?
https://github.com/bazelbuild/bazel/issues/3956 and https://github.com/bazelbuild/bazel/issues/4267 look somewhat related.

### Anything else, information or logs or outputs that would be helpful?
(If they are large, please upload as attachment or provide link).

**Comment by davidsmd** [comment] 2017-12-17 03:31
```

INFO: $TEST_TMPDIR defined: output root default is '/cache/bazel-cache'.
.
Server crashed during startup. Now printing '/cache/bazel-cache/_bazel_root/ab266b03d96d30adb25303391e4dd39d/server/jvm.out':

```

I've been running into something similar. I get "Serve crashed during startup" when building go 1.9.2 code on a gitlab-runner machine, linux, using the gitlab docker executor; but only with the gitlab cache enabled and set to match the bazel-cache path. If the cache is disabled on gitlab, or TEST_TMPDIR is set to different path than the gitlab cache (same as disabling it, effectively), bazel runs fine.

We use another gitlab-runner with go 1.8.3, docker executor, bazel 0.6.1, and cache enabled... which works (and cuts a good 12-14 minutes off of our test and build times).

I didn't find anything relevant until today; last time I looked was 9 Dec 2017, so neither this issue nor #4267 existed at the time. Did not come across the #3956 issue while looking for a solution,

**Comment by mhlopko** [comment] 2018-01-03 16:03
Can you test if this still happens with 0.9.0? Summoning heroes @philwo @laszlocsomor, do you have ideas? :)

**Comment by philwo** [comment] 2018-01-03 16:11
That sounds pretty bad, unfortunately I'm not sure how to debug it, if it happens on an automated machine somewhere inside a Docker container (which sounds like "hard to SSH into and poke around") and when Bazel doesn't log anything useful.

Pinging @lberki just in case, as he knows the C++ client quite well.

**Comment by laszlocsomor** [comment] 2018-01-04 08:21
@ixdy , @davidsmd : As for debugging, can you add `--client_debug` as a startup flag? (Between `bazel` and `build`.) Is there more useful output that way?

**Comment by lberki** [comment] 2018-01-08 12:08
In addition to `--client_debug`, trying `--batch` might yield more information. Then the JVM is `exec()`ed instead of trying to daemonize it, so it's one less layer of indirection where information can be lost.

I'm intrigued about the lack of logs in `jvm.out`, though. Maybe something outside of blaze kills the JVM process before it has a chance to do anything?

**Comment by astratto** [comment] 2018-02-13 11:58
I keep hitting this issue in a very similar scenario: Gitlab, Docker runner, caching enabled.

I've added `--client_debug` to my `bazel.rc` but the output is not very helpful:

```
INFO: $TEST_TMPDIR defined: output root default is '/cache/bazel-data-dir' and max_idle_secs default is '15'.
CLIENT: Debug logging active
CLIENT: Trying to connect to server (timeout: 30 secs)...
CLIENT: Connection to server failed: Deadline Exceeded
INFO: Reading 'startup' options from ...bazel.rc: --host_jvm_args=-Dbazel.DigestFunction=sha256 --client_debug

Server crashed during startup. Now printing '/cache/bazel-data-dir/.../server/jvm.out':
ERROR: Job failed: exit code 1
```

Adding `--batch` mitigates the problem, but it's adding overhead I'd like to remove.

Any ideas?

**Comment by lberki** [comment] 2018-02-13 16:25
Paging @buchgr @philwo  -- me and @scentini have seen crashes like this on our internal builds. Of course, a server crash at startup can caused by a lot of things, so these may or may not be related. But those are at least semi-reproducible within our environment.

**Comment by ola-rozenfeld** [comment] 2018-03-21 13:47
We have also seen some crashes with 0.10.1 and some nightly builds, last one on Feb 26. We're running on Ubuntu. I will try adding the --batch and --client_debug as well.

**Comment by buchgr** [comment] 2018-03-21 14:06
thanks @ola-rozenfeld 

I don't recall having seen these issues on our own CI.

**Comment by likan999** [comment] 2018-06-27 17:02
I am seeing the same issue when I tried to compile Bazel from source for arm64 within a docker container. It's running on x86_64 host and an aarch64 container using qemu-aarch64-static (user mode emulation). It's consistently reproducible by just download the Bazel source and `./compile.sh` then `output/bazel build -c opt scripts/packages:without-jdk/install.sh`. Adding `--batch` solves the problem.

My concern is `--batch` is now deprecated and will disappear very soon so I can't rely on it.

**Comment by burkpojken** [comment] 2018-08-21 05:26
We have also seen it sometimes in our CI, but never after we started to use --batch.
So please to do not remove --batch until this is corrected.

**Comment by dslomov** [comment] 2019-07-23 11:01
I am going to close this since it is not really actionable. Please post updates here if this is still happening.

**Closed by dslomov** 2019-07-23 11:01 UTC
Labels: P2, team-Product, type: bug

**Comment by plaird** [comment] 2020-01-31 18:51
I found one repro case, but I doubt it is the case referenced above. Just adding this note in case it helps others. This is with Bazel 1.0.0. Set a relative JAVA_HOME:

$ echo $JAVA_HOME
tools/jdk/Darwin/openjdk_11.0.1_x64

$ bazel info
Starting local Bazel server and connecting to it...
Server crashed during startup. Now printing /xyz/server/jvm.out
java.lang.IllegalArgumentException
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:127)
	at com.google.devtools.build.lib.vfs.FileSystem.getPath(FileSystem.java:78)
	at com.google.devtools.build.lib.runtime.BlazeRuntime.newRuntime(BlazeRuntime.java:1265)
	at com.google.devtools.build.lib.runtime.BlazeRuntime.serverMain(BlazeRuntime.java:1078)
	at com.google.devtools.build.lib.runtime.BlazeRuntime.main(BlazeRuntime.java:814)
	at com.google.devtools.build.lib.bazel.Bazel.main(Bazel.java:74)

The fix is to set an absolute path for JAVA_HOME.
