### ISSUE TITLE
Local repository not working as expected -- Adding Tensorflow as local_repository.

### ISSUE THREAD

**Issue by JonasRSV** [bazelbuild/bazel#12294] opened 2020-10-16 21:14 UTC
> ATTENTION! Please read and follow:
> - if this is a _question_ about how to build / test / query / deploy using Bazel, or a _discussion starter_, send it to bazel-discuss@googlegroups.com
> - if this is a _bug_ or _feature request_, fill the form below as best as you can.

### Description of the problem / feature request:

I added tensorflow https://github.com/tensorflow/tensorflow/tree/r1.14 as a local_repository to my project https://github.com/JonasRSV/friday-voice-assistant

I want to use //tensorflow/core:lib in my project, I can build this target if i use tensorflow as the main workspace. But if I try to add tensorflow as a local_repository I cannot build it.

If i just try to build my project with that dependency I get the error

```bash
RROR: /home/jonas/.cache/bazel/_bazel_jonas/f882173bb04895bcb83c04830ed51f60/external/org_tensorflow/third_party/gpus/cuda_configure.bzl:1421:40: in call to repository_rule(), parameter 'remotable' is experimental and thus unavailable with the current flags. It may be enabled by setting --experimental_repo_remote_exec
ERROR: in /home/jonas/.cache/bazel/_bazel_jonas/f882173bb04895bcb83c04830ed51f60/external/org_tensorflow/tensorflow/workspace.bzl: Extension file 'third_party/gpus/cuda_configure.bzl' has errors
INFO: Elapsed time: 0.071s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
```
If i add the experimental flag I get

```bash
ERROR: Failed to load Starlark extension '@io_bazel_rules_closure//closure:defs.bzl'.
Cycle in the workspace file detected. This indicates that a repository is used prior to being defined.
The following chain of repository dependencies lead to the missing definition.
 - @io_bazel_rules_closure
This could either mean you have to add the '@io_bazel_rules_closure' repository with a statement like `http_archive` in your WORKSPACE file (note that transitive dependencies are not added automatically), or move an existing definition earlier in your WORKSPACE file.
ERROR: cycles detected during target parsing
INFO: Elapsed time: 0.069s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
```

If I add that http_archive to my workspace I get

```bash
❯ bazel build friday:friday --experimental_repo_remote_exec
INFO: Repository local_execution_config_python instantiated at:
  no stack (--record_rule_instantiation_callstack not enabled)
Repository rule local_python_configure defined at:
  /home/jonas/.cache/bazel/_bazel_jonas/f882173bb04895bcb83c04830ed51f60/external/org_tensorflow/third_party/py/python_configure.bzl:275:41: in <toplevel>
ERROR: An error occurred during the fetch of repository 'local_execution_config_python':
   Traceback (most recent call last):
        File "/home/jonas/.cache/bazel/_bazel_jonas/f882173bb04895bcb83c04830ed51f60/external/org_tensorflow/third_party/py/python_configure.bzl", line 213
                _get_numpy_include(<2 more arguments>)
        File "/home/jonas/.cache/bazel/_bazel_jonas/f882173bb04895bcb83c04830ed51f60/external/org_tensorflow/third_party/py/python_configure.bzl", line 198, in _get_numpy_include
                execute(repository_ctx, [python_bin, "-c", "from __future__ import print_function;import numpy; print(numpy.get_include());"], error_msg = "Problem getting numpy include path.", error_details = "Is numpy installed?").stdout.splitlines()
        File "/home/jonas/.cache/bazel/_bazel_jonas/f882173bb04895bcb83c04830ed51f60/external/org_tensorflow/third_party/py/python_configure.bzl", line 187, in execute
                execute(repository_ctx, <3 more arguments>)
        File "/home/jonas/.cache/bazel/_bazel_jonas/f882173bb04895bcb83c04830ed51f60/external/org_tensorflow/third_party/remote_config/common.bzl", line 208, in execute
                fail(<1 more arguments>)
Problem getting numpy include path.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named numpy
Is numpy installed?
ERROR: Analysis of target '//friday:friday' failed; build aborted: Traceback (most recent call last):
        File "/home/jonas/.cache/bazel/_bazel_jonas/f882173bb04895bcb83c04830ed51f60/external/org_tensorflow/third_party/py/python_configure.bzl", line 213
                _get_numpy_include(<2 more arguments>)
        File "/home/jonas/.cache/bazel/_bazel_jonas/f882173bb04895bcb83c04830ed51f60/external/org_tensorflow/third_party/py/python_configure.bzl", line 198, in _get_numpy_include
                execute(repository_ctx, [python_bin, "-c", "from __future__ import print_function;import numpy; print(numpy.get_include());"], error_msg = "Problem getting numpy include path.", error_details = "Is numpy installed?").stdout.splitlines()
        File "/home/jonas/.cache/bazel/_bazel_jonas/f882173bb04895bcb83c04830ed51f60/external/org_tensorflow/third_party/py/python_configure.bzl", line 187, in execute
                execute(repository_ctx, <3 more arguments>)
        File "/home/jonas/.cache/bazel/_bazel_jonas/f882173bb04895bcb83c04830ed51f60/external/org_tensorflow/third_party/remote_config/common.bzl", line 208, in execute
                fail(<1 more arguments>)
Problem getting numpy include path.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named numpy
Is numpy installed?
INFO: Elapsed time: 0.314s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (11 packages loaded, 11 targets configured)
```

And I have not been able to resolve that, numpy is installed.. and I don't see how it is even relevant.. I only want to use the c++ code.

I get none of these errors if I just run the following command in the tensorflow directory.

```bash
bazel build //tensorflow/core:lib
```

What am I doing wrong? Is there a difference between building something as a local_repository vs building in it?

Any guidance would be super appreciated :)

### Feature requests: what underlying problem are you trying to solve with this feature?

Currently I have a .so file of tensorflow in my project, but I want to add tensorflow to be able to statically link it.

### What operating system are you running Bazel on?

```bash
NAME="Ubuntu"
VERSION="18.04.3 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.3 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```

### What's the output of `bazel info release`?

```bash
Starting local Bazel server and connecting to it...
INFO: Options provided by the client:
  Inherited 'common' options: --isatty=1 --terminal_columns=191
INFO: Reading rc options for 'info' from /home/jonas/dev/friday-voice-assistant/local_repositories/tensorflow/.bazelrc:
  Inherited 'common' options: --experimental_repo_remote_exec
INFO: Reading rc options for 'info' from /home/jonas/dev/friday-voice-assistant/local_repositories/tensorflow/.bazelrc:
  Inherited 'build' options: --apple_platform_type=macos --define framework_shared_object=true --define open_source_build=true --java_toolchain=//third_party/toolchains/java:tf_java_toolchain --host_java_toolchain=//third_party/toolchains/java:tf_java_toolchain --define=tensorflow_enable_mlir_generated_gpu_kernels=0 --define=use_fast_cpp_protos=true --define=allow_oversize_protos=true --spawn_strategy=standalone -c opt --announce_rc --define=grpc_no_ares=true --noincompatible_remove_legacy_whole_archive --noincompatible_prohibit_aapt1 --enable_platform_specific_config --config=short_logs --config=v2
INFO: Found applicable config definition build:short_logs in file /home/jonas/dev/friday-voice-assistant/local_repositories/tensorflow/.bazelrc: --output_filter=DONT_MATCH_ANYTHING
INFO: Found applicable config definition build:v2 in file /home/jonas/dev/friday-voice-assistant/local_repositories/tensorflow/.bazelrc: --define=tf_api_version=2 --action_env=TF2_BEHAVIOR=1
INFO: Found applicable config definition build:linux in file /home/jonas/dev/friday-voice-assistant/local_repositories/tensorflow/.bazelrc: --copt=-w --host_copt=-w --define=PREFIX=/usr --define=LIBDIR=$(PREFIX)/lib --define=INCLUDEDIR=$(PREFIX)/include --cxxopt=-std=c++14 --host_cxxopt=-std=c++14 --config=dynamic_kernels
INFO: Found applicable config definition build:dynamic_kernels in file /home/jonas/dev/friday-voice-assistant/local_repositories/tensorflow/.bazelrc: --define=dynamic_loaded_kernels=true --copt=-DAUTOLOAD_DYNAMIC_KERNELS
release 3.1.0
```

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

> Replace this line with your answer.

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

```bash
https://github.com/JonasRSV/friday-voice-assistant.git
8b78055e6e7509fd29aaffad89dd9feb9e071078
8b78055e6e7509fd29aaffad89dd9feb9e071078
```

###  Have you found anything relevant by searching the web?

Yes, so tensorflow serving uses tensorflow as dependency, https://github.com/tensorflow/serving/blob/master/WORKSPACE

but they are doing it as an external dependency, I have tried to copy what they are doing but end up with the same numpy error.

**Comment by aiuto** [comment] 2020-10-19 03:42
Have you tried asking in the tensforflow support channels?  You might find more people who know about the tensorflow dependencies. there.

**Comment by jin** [comment] 2020-10-21 10:14
Bazel does not support recursive WORKSPACES (yet). Adding TensorFlow as a local_repository doesn't mean that Bazel is reading and downloading TensorFlow's own dependencies in its WORKSPACE. 

Did you include the upstream dependencies like tensorflow_serving did, here? https://github.com/tensorflow/serving/blob/a134d752f525b9cd7bfa0bb3c2647908a148fbc8/WORKSPACE#L44-L65

**Comment by jin** [comment] 2020-10-21 10:15
(please use bazel-discuss@, StackOverflow or slack.bazel.build as support channels, I'll be closing this as it's not a bug)

**Closed by jin** 2020-10-21 10:15 UTC
Labels: type: support / not a bug
