### ISSUE TITLE
Documentation: startup class options in .bazelrc cannot be configured using ':' syntax

### ISSUE THREAD

**Issue by konste** [bazelbuild/bazel#11513] opened 2020-05-28 02:24 UTC
### Description of the problem / feature request:

When startup options are used in .bazelrc file and have config name added (`startup:config-name`) they get silently ignored. 

### Feature requests: what underlying problem are you trying to solve with this feature?

I was going to use `--windows_enable_symlinks` on dev machines, but not in CI. Unfortunately it is startup option and I cannot control it using special CI configuration in the same way as other options can be controlled.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

I tried to add a line `startup:teamcity --nowindows_enable_symlinks` to .bazelrc and figured that it is ignored regardless of `--config=teamcity` being present on the command line.
[This](https://blog.bazel.build/2018/01/19/config-parsing-order.html) blog post hinted me that this behaviour is probably by design. If this is indeed the case then it would be great to notice it somewhere in the [user guide](https://docs.bazel.build/versions/master/guide.html#bazelrc-the-bazel-configuration-file). Also when somebody tries to use configs with startup options it would be nice to issue a warning that it is not going to work regardless of the config settings on the command line.  

### What operating system are you running Bazel on?

Windows 10 1806

### What's the output of `bazel info release`?

3.2.0

###  Have you found anything relevant by searching the web?

https://blog.bazel.build/2018/01/19/config-parsing-order.html

**Comment by juliexxia** [comment] 2020-06-22 20:02
Apologies if I'm misunderstanding - the bazelrc syntax with the colon is `command:config-name` correct? I don't believe bazel has a `startup` command. 

https://docs.bazel.build/versions/master/guide.html#--config

I totally agree we should allow syntax like `build:my-config --some_startup_option=foo` if that's what we mean here.

**Comment by konste** [comment] 2020-06-22 20:29
My original issue was about `startup:config-name` being unsupported (apparently by design), but at the same time not complaining, but just silently not working.

I did not think what can be done to enable particular startup options for configurations. If it is possible at all then the syntax you proposed looks fine to me.

**Comment by juliexxia** [comment] 2020-06-22 21:32
What would be your expected behavior from adding `startup:config-name` to a blazerc file? IIUC, `build:foo --blah` would set `--blah` every time you blaze `build` with `--config=foo` so I'm not sure what `startup:config-name` would do since we don't have a `startup` command. 

I agree silently not working is not ideal and happy to update documentation! But want to make sure I'm understanding the issue first.

**Comment by konste** [comment] 2020-06-22 21:57
Example: just recently Bazel got a new configuration flag `--windows_enable_symlinks`. We want to specify it in .bazelrc, so we add a line `startup --windows_enable_symlinks` to .bazelrc. This is startup flag (among those to be specified before the command) and therefore it is the only way to add it to .bazelrc. Then we discovered that for some reason symlinks do not work in CI when the build is run by TeamCity. So the natural reaction was to add `startup:teamcity --nowindows_enable_symlinks` to .bazelrc. It silently does nothing and it caused some headbanging.

**Comment by juliexxia** [comment] 2020-06-23 14:25
Ah, got it. I'll mail a PR updating the documentation. From some quick digging, it'll take some time to disallow the `startup:config-name` syntax in a principled way. I'll put this in our icebox of issues that we agree should be taken care of but we aren't prioritizing right now and submit the new documentation. Thanks for bringing to our attention!

**Comment by katre** [comment] 2020-06-26 14:38
@juliexxia: Did your commit 9716d31 fix this? Should the issue be closed, or is there more to do?

**Comment by sventiffe** [comment] 2020-11-10 17:03
Closing this issue since there have been no follow ups since summer. Please reopen if you feel different about it.

**Closed by sventiffe** 2020-11-10 17:03 UTC
Labels: ice-box, team-Configurability, type: documentation
