### ISSUE TITLE
ImportError when external repository has same directory as main workspace

### ISSUE THREAD

**Issue by drigz** [bazelbuild/bazel#4036] opened 2017-11-07 14:30 UTC
If a py_binary depends on a py_library from an external repository, then the path to the external repository will be added to PYTHONPATH. If the external repository contains a directory of the same name as the directory containing the Python source in the main workspace (eg `src`), Python will not be able to find modules located inside this directory in the main workspace.

For example, if you depend on [rospkg](https://github.com/ros-infrastructure/rospkg), you cannot import a module in your main workspace with:

`import src.python.....`

Because Python will locate the `src` inside `rospkg` and stop looking for other `src` directories.

Repro: https://github.com/drigz/bazel_python_directory_conflict

```
> bazel run src/python/main:main_with_repo
[SNIP: build output]

INFO: Running command line: bazel-bin/src/python/main/main_with_repo
Traceback (most recent call last):
  File "/usr/local/google/home/rodrigoq/.cache/bazel/_bazel_rodrigoq/6d06dc949db619b9f460a7cf15a8ceac/execroot/__main__/bazel-out/local-fastbuild/bin/src/python/main/main_with_repo.runfiles/__main__/src/python/main/main.py", line 1, in <module>
    import src.python.lib.lib as lib
  File "/usr/local/buildtools/current/sitecustomize/sitecustomize.py", line 152, in SetupPathsAndImport
    return real_import(name, globals, locals, fromlist, level)
ImportError: No module named python.lib.lib
ERROR: Non-zero return code '1' from command: Process exited with status 1
```

### Workaround

Use `imports` to import your own modules without having `src` in the prefix - see [example](https://github.com/drigz/bazel_python_directory_conflict/blob/cf5b9f3cd19fe6214f514e65af8d9d389b819f13/src/python/lib/BUILD.bazel#L8).

### Possible solution

If `$RUNFILES/__main__` appeared before the external repos in PYTHONPATH, then you could still import your own modules with the absolute path. You'd have two options for importing from external repos:

* use `imports` in the external repo (this is probably required anyway if your code is to look like other code that uses the external library)
* instead of having an empty `src/__init__.py`, it could use [pkgutil.extend_path](https://docs.python.org/2/library/pkgutil.html#pkgutil.extend_path) to locate the other `src` directories.

However, there's a chance this could break people if they're relying on the current import order (eg that a directory within an `imports` value takes precedence over directories in the workspace root).

### Environment info
* Operating System: Ubuntu 14.04
* Bazel version: 0.7.0

**Comment by damienmg** [comment] 2017-11-08 19:20
Duplicate of #3998

Workaround: use `--noexperimental_python_import_all_repositories` and the `imports` attribute of `py_library`

**Closed by damienmg** 2017-11-08 19:20 UTC
