### ISSUE TITLE
`cquery --output=proto` crashes in ProtoOutputFormatterCallback.writeData: IllegalArgumentException: bufferSize must be >= 0

### ISSUE THREAD

**Issue by keithl-stripe** [bazelbuild/bazel#17743] opened 2023-03-11 14:20 UTC
### Description of the bug:
In a large monorepo with 45,000 Bazel packages, 300,000 targets, and 800,000 configured targets, `bazel cquery --output=proto` crashes because the field of `CqueryResult` proto is larger than the 2GB inherent limit in the proto wire format.

```
bazel cquery --output=proto --keep_going 'deps(...)'
INFO: Analysis succeeded for only 325040 of 325813 top-level targets
INFO: Analyzed 325813 targets (55049 packages loaded, 859577 targets configured).
INFO: Found 325040 targets...

FATAL: bazel crashed due to an internal error. Printing stack trace:
java.lang.IllegalArgumentException: bufferSize must be >= 0
        at com.google.protobuf.CodedOutputStream$AbstractBufferedEncoder.<init>(CodedOutputStream.java:2242)
        at com.google.protobuf.CodedOutputStream$OutputStreamEncoder.<init>(CodedOutputStream.java:2712)
        at com.google.protobuf.CodedOutputStream.newInstance(CodedOutputStream.java:105)
        at com.google.protobuf.AbstractMessageLite.writeTo(AbstractMessageLite.java:82)
        at com.google.devtools.build.lib.query2.cquery.ProtoOutputFormatterCallback.writeData(ProtoOutputFormatterCallback.java:109)
        at com.google.devtools.build.lib.query2.cquery.ProtoOutputFormatterCallback.close(ProtoOutputFormatterCallback.java:93)
        at com.google.devtools.build.lib.buildtool.PostAnalysisQueryBuildTool.doPostAnalysisQuery(PostAnalysisQueryBuildTool.java:188)
        at com.google.devtools.build.lib.buildtool.PostAnalysisQueryBuildTool.postProcessAnalysisResult(PostAnalysisQueryBuildTool.java:78)
        at com.google.devtools.build.lib.buildtool.BuildTool.buildTargets(BuildTool.java:227)
        at com.google.devtools.build.lib.buildtool.BuildTool.processRequest(BuildTool.java:443)
        at com.google.devtools.build.lib.buildtool.BuildTool.processRequest(BuildTool.java:411)
        at com.google.devtools.build.lib.runtime.commands.CqueryCommand.exec(CqueryCommand.java:152)
        at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.execExclusively(BlazeCommandDispatcher.java:585)
        at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.exec(BlazeCommandDispatcher.java:231)
        at com.google.devtools.build.lib.server.GrpcServerImpl.executeCommand(GrpcServerImpl.java:550)
        at com.google.devtools.build.lib.server.GrpcServerImpl.lambda$run$1(GrpcServerImpl.java:614)
        at io.grpc.Context$1.run(Context.java:579)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
```

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

bazel cquery --output=proto --keep_going 'deps(...)'

### Which operating system are you running Bazel on?

Linux Ubuntu 20.04.1 

### What is the output of `bazel info release`?

5.4.0

### Have you found anything relevant by searching the web?

This may be because a field is more than 2GB - see https://github.com/protocolbuffers/protobuf/issues/8075

### Any other information, logs, or outputs that you want to share?

A simple fix might be to add a new output format, perhaps `--output=proto-stream` which is simply a stream of `ConfiguredTarget`s. (Or if possible a stream of `ConfiguredTarget`s _and_ `Configuration`s – I don't know if protobuf makes it easy to parse a mixed stream of delimited protos)

**Comment by sgowroji** [comment] 2023-03-13 07:58
Hi @keithl-stripe, Is there a way we can reproduce the error/crash it our end.  Thanks!

**Comment by keithl-stripe** [comment] 2023-03-13 18:07
Sure, just create a Bazel workspace by creating the following files in an empty directory:

`WORKSPACE`
```bzl
# empty workspace
```

`BUILD`
```bzl
[
    genrule(name = "gen%d" % i, cmd = "echo hi", outs=["gen%d.txt" % i]) 
    for i in range(1000 * 1000 * 2)
]
```

Then type:
```sh
bazel --host_jvm_args=-Xmx40G cquery --output=proto :all > all-cquery.proto
```

You will see:
```

java.lang.IllegalArgumentException: bufferSize must be >= 0
        at com.google.protobuf.CodedOutputStream$AbstractBufferedEncoder.<init>(CodedOutputStream.java:2186)
        at com.google.protobuf.CodedOutputStream$OutputStreamEncoder.<init>(CodedOutputStream.java:2645)
        at com.google.protobuf.CodedOutputStream.newInstance(CodedOutputStream.java:108)
        at com.google.protobuf.AbstractMessageLite.writeTo(AbstractMessageLite.java:85)
        at com.google.devtools.build.lib.query2.ProtoOutputFormatterCallback.close(ProtoOutputFormatterCallback.java:70)
        at com.google.devtools.build.lib.query2.AbstractBlazeQueryEnvironment.evaluateQuery(AbstractBlazeQueryEnvironment.java:150)
        at com.google.devtools.build.lib.query2.ConfiguredTargetQueryEnvironment.evaluateQuery(ConfiguredTargetQueryEnvironment.java:216)
        at com.google.devtools.build.lib.buildtool.CqueryBuildTool.doConfiguredTargetQuery(CqueryBuildTool.java:152)
        at com.google.devtools.build.lib.buildtool.CqueryBuildTool.postProcessAnalysisResult(CqueryBuildTool.java:66)
        at com.google.devtools.build.lib.buildtool.BuildTool.buildTargets(BuildTool.java:237)
        at com.google.devtools.build.lib.buildtool.BuildTool.processRequest(BuildTool.java:350)
        at com.google.devtools.build.lib.runtime.commands.CqueryCommand.exec(CqueryCommand.java:121)
        at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.execExclusively(BlazeCommandDispatcher.java:472)
        at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.exec(BlazeCommandDispatcher.java:199)
        at com.google.devtools.build.lib.server.GrpcServerImpl.executeCommand(GrpcServerImpl.java:855)
        at com.google.devtools.build.lib.server.GrpcServerImpl.access$2100(GrpcServerImpl.java:111)
        at com.google.devtools.build.lib.server.GrpcServerImpl$2.lambda$run$0(GrpcServerImpl.java:924)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
java.lang.IllegalArgumentException: bufferSize must be >= 0
        at com.google.protobuf.CodedOutputStream$AbstractBufferedEncoder.<init>(CodedOutputStream.java:2186)
        at com.google.protobuf.CodedOutputStream$OutputStreamEncoder.<init>(CodedOutputStream.java:2645)
        at com.google.protobuf.CodedOutputStream.newInstance(CodedOutputStream.java:108)
        at com.google.protobuf.AbstractMessageLite.writeTo(AbstractMessageLite.java:85)
        at com.google.devtools.build.lib.query2.ProtoOutputFormatterCallback.close(ProtoOutputFormatterCallback.java:70)
        at com.google.devtools.build.lib.query2.AbstractBlazeQueryEnvironment.evaluateQuery(AbstractBlazeQueryEnvironment.java:150)
        at com.google.devtools.build.lib.query2.ConfiguredTargetQueryEnvironment.evaluateQuery(ConfiguredTargetQueryEnvironment.java:216)
        at com.google.devtools.build.lib.buildtool.CqueryBuildTool.doConfiguredTargetQuery(CqueryBuildTool.java:152)
        at com.google.devtools.build.lib.buildtool.CqueryBuildTool.postProcessAnalysisResult(CqueryBuildTool.java:66)
        at com.google.devtools.build.lib.buildtool.BuildTool.buildTargets(BuildTool.java:237)
        at com.google.devtools.build.lib.buildtool.BuildTool.processRequest(BuildTool.java:350)
        at com.google.devtools.build.lib.runtime.commands.CqueryCommand.exec(CqueryCommand.java:121)
        at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.execExclusively(BlazeCommandDispatcher.java:472)
        at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.exec(BlazeCommandDispatcher.java:199)
        at com.google.devtools.build.lib.server.GrpcServerImpl.executeCommand(GrpcServerImpl.java:855)
        at com.google.devtools.build.lib.server.GrpcServerImpl.access$2100(GrpcServerImpl.java:111)
        at com.google.devtools.build.lib.server.GrpcServerImpl$2.lambda$run$0(GrpcServerImpl.java:924)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
FAILED: Build did NOT complete successfully
```

**Comment by katre** [comment] 2023-03-31 16:57
This is pretty unfortunate.

A similar issue was fixed for query, in 68d2181faf3f5f411042c75fc9c02b2708a0dee2 (by @michajlo). You could do something similar here, streaming the `ConfiguredTarget` protos out instead of accumulating them. @michajlo's note was "if i could do it again i'd keep track of bytes written and throw when it got too big, for whatever reason i didn't do that on the first go, making it harder to fix later".

I'm marking this as low-priority, we won't be able to pick this up, but if you want to send a PR we'll review it.

**Comment by meisterT** [comment] 2023-04-03 07:30
cc @zhengwei143 who will look into streamed proto for aquery.

**Comment by zhengwei143** [comment] 2023-06-16 08:59
The fix has been commited in https://github.com/bazelbuild/bazel/commit/607d0f7335f95aa0ee236ba3c18ce2a232370cdb, which introduces `--output=streamed_proto` for `cquery`, containing a length-delimited stream of `CqueryResult`(s) each wrapping a single `ConfiguredTarget` or `Configuration` proto.

**Comment by zhengwei143** [comment] 2023-06-30 13:08
We rolled this back due to a bug, will submit a roll forward with a fix soon.

**Comment by zhengwei143** [comment] 2023-08-16 02:48
This has been reimplemented in https://github.com/bazelbuild/bazel/commit/aa8835753cbbed5a837fc10a37464ee4a84941ba.

**Closed by zhengwei143** 2023-08-16 02:48 UTC
Labels: type: bug, P3, team-Configurability
