### ISSUE TITLE
Windows, Android, CI: set up CI job to build Android Hello World on Windows

### ISSUE THREAD

**Issue by laszlocsomor** [bazelbuild/bazel#3663] opened 2017-09-01 13:08 UTC
Set up a CI job on ci.bazel.build that builds `//examples/android/java/bazel:hello_world` on Windows, in order to avoid https://github.com/bazelbuild/bazel/issues/3659 happening again.

**Comment by laszlocsomor** [comment] 2017-09-11 06:54
@aj-michael : Do you have any updates on this?

**Comment by aj-michael** [comment] 2017-09-11 13:53
I attempted to write a python test that would build it, however I am blocked by https://github.com/bazelbuild/bazel/issues/3674. There is a workaround proposed in that issue (use glob/** instead of glob on directories), however, to use that workaround would require waiting one Bazel release after the workaround is submitted, since the workaround is for the Bazel binary that *runs* the test (as opposed to the binary built from head that is being tested).

I am open to other ideas. java_test does not have the issue is #3674, however we don't have an open source java framework for integration tests afaik.

**Comment by laszlocsomor** [comment] 2017-09-11 15:51
If the only reason to use Java would be to ship this faster, and otherwise Python would allow simpler (and faster?) tests, then I suggest waiting for the release with the workaround.

Reading that bug (#3674) I get the impression that the workaround is actually the right way to glob a directory. I don't even know what `glob(["some_directory"])` should do as opposed to `glob(["some_directory/**"])`.

**Comment by aj-michael** [comment] 2017-09-11 16:52
The title of the bug is misleading, its not an issue with globs. The issue is that Bazel allows filegroups to contain directories (as opposed to globbing all the files within them), and py_test on Windows fails if such a filegroup is a data dependency.

**Comment by laszlocsomor** [comment] 2017-12-13 17:08
@aj-michael , do you have any updates on this bug?

**Comment by aj-michael** [comment] 2017-12-13 17:24
Thanks for reminding me of this. This was blocked on #3674 (which is still unresolved), but now that 95ce534 is in a release I think I have a workaround. I'll try and get back to this this week.

**Comment by laszlocsomor** [comment] 2017-12-13 17:28
Sounds great, thank you!

**Comment by jin** [comment] 2019-10-24 14:23
Closing as we have rules_jvm_external and Android Testing pipelines building an Android app on Windows on CI. 

https://buildkite.com/bazel/rules-jvm-external-examples/builds/732
https://buildkite.com/bazel/android-testing/builds/532

**Closed by jin** 2019-10-24 14:23 UTC
Labels: P2, category: misc > testing, platform: windows, team-Android, type: feature request
