### ISSUE TITLE
Java source file name may not contain '$'?

### ISSUE THREAD

**Issue by davido** [bazelbuild/bazel#2462] opened 2017-02-01 07:58 UTC
/CC @damienmg @spearce

I'm trying to implement Bazel build for Gerrit Code Review project [prolog-cafe](https://gerrit-review.googlesource.com/#/admin/projects/prolog-cafe), that is currently built with Buck and Bucklets.

And facing the problem, that source files contains '$':

```
java_library(
  name = 'lang',
  srcs = glob([
      SRC + 'exceptions/*.java',
      SRC + 'lang/*.java',
    ],
    exclude = REPL),
)
```

Build doesn't work at all:

```
$ bazel query --output=build :lang
ERROR: /home/davido/projects/prolog-cafe/BUILD:51:1: //:builtin: invalid label 'java/com/googlecode/prolog_cafe/builtin/PRED_$atom_type0_2.java' in element 0 of attribute 'srcs' in 'java_library' rule: invalid target name 'java/com/googlecode/prolog_cafe/builtin/PRED_$atom_type0_2.java': target names may not contain '$'.
WARNING: /home/davido/projects/prolog-cafe/BUILD:60:1: target 'builtin_srcs.am' is both a rule and a file; please choose another name for the rule.
WARNING: /home/davido/projects/prolog-cafe/BUILD:66:1: target 'system_srcs.am' is both a rule and a file; please choose another name for the rule.
ERROR: /home/davido/projects/prolog-cafe/BUILD:66:1: Label '//:src/builtin/system.pl' is duplicated in the 'srcs' attribute of rule 'system_srcs.am'.
WARNING: /home/davido/projects/prolog-cafe/BUILD:81:1: target 'io_srcs.am' is both a rule and a file; please choose another name for the rule.
WARNING: /home/davido/projects/prolog-cafe/BUILD:100:1: target 'pl2am_srcs.am' is both a rule and a file; please choose another name for the rule.
ERROR: /home/davido/projects/prolog-cafe/BUILD:100:1: Label '//:src/compiler/pl2am.pl' is duplicated in the 'srcs' attribute of rule 'pl2am_srcs.am'.
WARNING: /home/davido/projects/prolog-cafe/BUILD:106:1: target 'am2j_srcs.am' is both a rule and a file; please choose another name for the rule.
ERROR: /home/davido/projects/prolog-cafe/BUILD:124:1: //:cafeteria_lib: invalid label 'java/com/googlecode/prolog_cafe/builtin/PRED_$write_toString_2.java' in element 2 of attribute 'srcs' in 'java_library' rule: invalid target name 'java/com/googlecode/prolog_cafe/builtin/PRED_$write_toString_2.java': target names may not contain '$'.
WARNING: /home/davido/projects/prolog-cafe/BUILD:134:1: target 'cafeteria_srcs.am' is both a rule and a file; please choose another name for the rule.
ERROR: error loading package '': Package '' contains errors.
```

Now I'm wondering how this library is built at Google with Blaze?

Here is the `BUILD` file: [1], and here is the `prolog.bzl` fie content: [2].

After some investigation, I see, that the problem is not `java_library`, but `genrule` implementation that generate java from prolog code. After rmoving those generic rules, `:lang` can be built. So that needs further investigations:

```
davido@linux-ucwl:~/projects/prolog-cafe (master %=)$ bazel build :lang
INFO: Found 1 target...
INFO: From Building liblang.jar (48 source files):
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Target //:lang up-to-date:
  bazel-bin/liblang.jar
INFO: Elapsed time: 3.965s, Critical Path: 1.34s

```

* [1] http://paste.openstack.org/show/597134/
* [2] http://paste.openstack.org/show/597135/

**Comment by damienmg** [comment] 2017-02-01 09:18
Hi David,

This is a duplicate of #167. I have started working on supporting random characters in filename but this will take some time. I will close this ticket and you can follow the work on #167.

In the mean time, if Bazel does not see the file, there should be no issue. so my suggestion would be to zip the causing files and include them as srcjar (using a local genrule you can do that, it is kind of hacky and totally not recommended but you are hitting a major drawback of current Bazel).

Sorry for not having a better answer :(

**Closed by damienmg** 2017-02-01 09:18 UTC

**Comment by davido** [comment] 2017-02-01 09:54
Thanks, Damien.

For the record, it's tracked now in https://github.com/bazelbuild/bazel/issues/374.
