### ISSUE TITLE
`TreeFileValues` apparently contain their own root directories sometimes

### ISSUE THREAD

**Issue by lberki** [bazelbuild/bazel#9058] opened 2019-08-02 09:34 UTC
https://github.com/bazelbuild/bazel/issues/9054 is caused by an assertion that stipulates that `TreeFileArtifact`s only contain `RegularFileValue`s.

This is apparently not true -- the file the assertion fails on, `chromium.out` is the root directory of the associated `TreeArtifact`.

For now, I'll just relax the assertion, but it would be nice to know how any why this happens.

Surprisingly, this is only an issue on OS X.

**Comment by irengrig** [comment] 2019-08-02 12:30
Assigning to @lberki.

**Comment by lberki** [comment] 2019-08-02 12:36
I can't promise to do this in any foreseeable amount of time so I'll unassign myself.

**Comment by justinhorvitz** [comment] 2020-07-22 13:32
Looks like this was the root cause of https://github.com/bazelbuild/bazel/issues/11813

**Comment by justinhorvitz** [comment] 2020-07-22 15:02
Took a look into the chromium rules. It's creating a symlink to a directory within the tree artifact, and it's not actually the root directory. As far as I can tell, this is legal and should be supported. I also reproduced this on linux, so it's nothing mac-specific, just happens to be that the rule that does this is for mac.

**Closed** 2020-07-22 16:32 UTC
Labels: team-Core, untriaged
