### ISSUE TITLE
Question: what's the real cache strategy of bazel?

### ISSUE THREAD

**Issue by ddwolf** [bazelbuild/bazel#2674] opened 2017-03-14 07:38 UTC
when I modified a java file, and then set the mtime to the time before it's modified, then I found bazel doesn't actually found the diff -- when run `bazel run`, it used cached result.

the program that modify the utime:

```python
# filename: modifyMTime.py
import os,sys,time
from stat import *
filename='Main.java'
TimeForChange = '2007-01-10 07:51:21'
ConverTime = time.mktime(time.strptime( TimeForChange,'%Y-%m-%d %H:%M:%S') )
print TimeForChange+' after:'+str(ConverTime)

print '-------------before modify mtime----------------'
print 'ctime:  '+time.ctime(os.path.getctime(filename))
print 'mtime:  '+time.ctime(os.path.getmtime(filename))
print 'atime:  '+time.ctime(os.path.getatime(filename))

times=(ConverTime,ConverTime)
os.utime(filename, times)

print '-------------after modify mtime----------------'
print 'ctime:  '+time.ctime(os.path.getctime(filename))
print 'mtime:  '+time.ctime(os.path.getmtime(filename))
print 'atime:  '+time.ctime(os.path.getatime(filename))

```

my bazel version is : 0.4.4

**Comment by damienmg** [comment] 2017-03-14 08:42
This is the same root cause as https://github.com/bazelbuild/bazel/issues/1525

**Comment by dslomov** [comment] 2017-05-16 17:36
Duplicate of #1525

**Closed by dslomov** 2017-05-16 17:36 UTC
