### ISSUE TITLE
cc_proto_library transitively depending on `descriptor.proto` links same symbols twice (ODR violation)

### ISSUE THREAD

**Issue by jmillikin-stripe** [bazelbuild/bazel#4650] opened 2018-02-17 06:55 UTC
(originally reported at https://github.com/google/protobuf/issues/4311)

### Description of the problem:
Linking a `cc_proto_library` that transitively depends on `descriptor.proto` will create multiple definitions of several C++ symbols, violating the ODR rule.

It looks like `CcProtoAspect::areSrcsBlacklisted()` has logic to avoid double-generating code for specific protobufs that are already present in the symbol map as dependencies of `libprotobuf`. This code doesn't seem to be working, as of Bazel 0.10 and protobuf 3.5.1.

My suspicion is that the protobuf repo's use of a genrule to copy .proto files around is somehow causing the `ProtoSourceFileBlacklist` to fail the comparison. I tried tracing through `ProtoLangToolchain` to see where this data is coming from, but got lost among all the abstract interfaces.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Small buildable reproduction at nelhage/rules_proto_odr@69ecec3d7182499acc2fe7a807f99abf4f58aa5e , the Bazel part is:

```
proto_library(
    name = "hello_proto",
    srcs = ["hello.proto"],
    deps = ["@com_google_protobuf//:descriptor_proto"],
)

cc_proto_library(
    name = "hello_proto_cc",
    deps = [":hello_proto"],
)   

cc_binary(
    name = "main",
    srcs = ["main.cc"],
    linkstatic = 0,
    deps = [":hello_proto_cc"],
)
```

### What operating system are you running Bazel on?

x86-64 Linux

### What's the output of `bazel info release`?

release 0.10.0

**Comment by jmillikin** [comment] 2018-02-24 19:45
Hit this for a personal project today, so figured I'd get to the bottom of it. I found the `ProtoSourceFileBlacklist` data was coming not from Bazel, but from the Protobuf library!

Using a `com_google_protobuf` with https://github.com/google/protobuf/pull/4334 fixes the ODR violation for me, so this issue can be closed in favor of the original issue https://github.com/google/protobuf/issues/4311.

**Comment by aehlig** [comment] 2018-02-26 07:25
As suggested by @jmillikin, closing as duplicate of https://github.com/google/protobuf/issues/4311

**Closed by aehlig** 2018-02-26 07:25 UTC
