### ISSUE TITLE
Release 0.22 - January 2019

### ISSUE THREAD

**Issue by laurentlb** [bazelbuild/bazel#6494] opened 2018-10-24 11:16 UTC
Target RC date: January 7th

**Comment by aehlig** [comment] 2019-01-07 12:58
Looking at the nightly CI run, we can use deb028e3fb30b4e2953df16f35ab1f55a08ea8fa as a clean base line.

**Comment by aehlig** [comment] 2019-01-07 13:30
`scripts/release/release.sh create 0.22.0 deb028e3fb30b4e2953df16f35ab1f55a08ea8fa`

-- 
Klaus Aehlig
Google Germany GmbH, Erika-Mann-Str. 33, 80636 Muenchen
Registergericht und -nummer: Hamburg, HRB 86891
Sitz der Gesellschaft: Hamburg
Geschaeftsfuehrer: Paul Terence Manicle, Halimah DeLaine Prado

**Comment by aehlig** [comment] 2019-01-07 13:56
RC1 available at https://releases.bazel.build/0.22.0/rc1/index.html

**Comment by aehlig** [comment] 2019-01-07 17:10
`scripts/release/release.sh create --force_rc=2 0.22.0 deb028e3fb30b4e2953df16f35ab1f55a08ea8fa a3a5975dca3ad04c19dc7d063fcf490a8cd612fd`

-- 
Klaus Aehlig
Google Germany GmbH, Erika-Mann-Str. 33, 80636 Muenchen
Registergericht und -nummer: Hamburg, HRB 86891
Sitz der Gesellschaft: Hamburg
Geschaeftsfuehrer: Paul Terence Manicle, Halimah DeLaine Prado

**Comment by aehlig** [comment] 2019-01-07 17:23
RC2 is available at https://releases.bazel.build/0.22.0/rc2/index.html

**Comment by keith** [comment] 2019-01-14 21:09
I believe that [this file](https://github.com/bazelbuild/bazel/blob/f0e4811e5c1d824c8bb8d3fb2058b41f7ea6af60/tools/cpp/legacy_cc_starlark_api_shim.bzl) should be included in 0.22 otherwise the migration window for the new CcInfo provider https://github.com/bazelbuild/bazel/issues/7036 doesn't really include 0.22. Also if you're using this API currently, you'll have to use `--noincompatible_disable_legacy_cc_provider` in production until 0.23 is released.

**Comment by aehlig** [comment] 2019-01-15 09:33
> I believe that [this file](https://github.com/bazelbuild/bazel/blob/f0e4811e5c1d824c8bb8d3fb2058b41f7ea6af60/tools/cpp/legacy_cc_starlark_api_shim.bzl) should be included in 0.22 otherwise the migration window for the new CcInfo provider #7036 doesn't really include 0.22.

Since 3976d5835a8427cff4c805814227bda1772335c4 was committed after the cut-off date, our policy is to delay the migration window rather than to cherry-pick. I.e., #7036 would have use 0.23 as migration window and cannot flip the flag before 0.24.

**Comment by jmillikin** [comment] 2019-01-16 04:55
I'm seeing a Bazel crash from a java.lang.IllegalStateException when using the new C++ toolchains: https://github.com/bazelbuild/bazel/issues/7136

**Comment by aehlig** [comment] 2019-01-16 09:34
> I'm seeing a Bazel crash from a java.lang.IllegalStateException when using the new C++ toolchains: #7136

Do I understand correctly that this just means that the new C++ toolchains are not ready yet (hence, we probably have to postpone the migration window). Or does anything break that works on `bazel 0.21`?

**Comment by jmillikin** [comment] 2019-01-16 14:38
My code is newly written for the v0.22 toolchains. I expect code written to the existing API would work properly.

**Comment by lberki** [comment] 2019-01-17 08:09
@aehlig : can we add the following two flags to the "0.22 is the migration window for these flags" list?

```
--incompatible_disable_legacy_proto_provider
--incompatible_disable_proto_source_root
```

**Comment by lberki** [comment] 2019-01-17 08:19
Tracking bug for `--incompatible_disable_legacy_proto_provider`: https://github.com/bazelbuild/bazel/issues/7152

**Comment by aehlig** [comment] 2019-01-17 08:56
Thanks. Will add this to the release announcement.

**Comment by dslomov** [comment] 2019-01-18 09:21
> @aehlig : can we add the following two flags to the "0.22 is the migration window for these flags" list?
> 
> ```
> --incompatible_disable_legacy_proto_provider
> --incompatible_disable_proto_source_root
> ```

Suggestion: let's not list the individual migration window incompatible flags in the release announcement, instead let's only publish a link to [issues with migration-0.22 label](https://github.com/bazelbuild/bazel/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3Amigration-0.22) 
We should still list all breaking changes that have actually occurred in 0.22 in the release annoucement.

WDYT?

**Comment by aehlig** [comment] 2019-01-18 09:37
> Suggestion: let's not list the individual migration window incompatible flags in the release announcement, instead let's only publish a link to [issues with migration-0.22 label](https://github.com/bazelbuild/bazel/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3Amigration-0.22)
> [...]
> 
> WDYT?

I think that, if by the time of the release announcement, we cannot tell the users which migrations could/should be done, we cannot reasonably except them to act in this migration window. So there is some value in committing to saying which migrations we believe are ready&mdash;and in this way ensure there is no surprise of a retroactively added label saying "you should have migrated during the last releas".

**Comment by buchgr** [comment] 2019-01-18 10:00
We'll unfortunately need to rollback the `--incompatible_strict_action_env` flag flip from the 0.21 release (See https://github.com/bazelbuild/bazel/issues/7026). Also, we'll need to cherry-pick https://github.com/bazelbuild/bazel/pull/7174 which fixes a bug that introduces flakyness on our CI. I ll post the commits later today.

**Comment by dslomov** [comment] 2019-01-18 14:40
> > Suggestion: let's not list the individual migration window incompatible flags in the release announcement, instead let's only publish a link to [issues with migration-0.22 label](https://github.com/bazelbuild/bazel/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3Amigration-0.22)
> > [...]
> > WDYT?
> 
> I think that, if by the time of the release announcement, we cannot tell the users which migrations could/should be done, we cannot reasonably except them to act in this migration window. So there is some value in committing to saying which migrations we believe are ready—and in this way ensure there is no surprise of a retroactively added label saying "you should have migrated during the last releas".

Of course, we will never _add_ migrations after release is published (only the release manager should add migration-X.Y labels, and never do so after the release is out). But we might _remove_ migrations where things didn't pan out (because the bugs are discovered or whatnot)

**Comment by dslomov** [comment] 2019-01-18 14:47
> We kindly ask for the following cherry-picks:
> 
> * [b8d0e1b](https://github.com/bazelbuild/bazel/commit/b8d0e1b05c225a4b943ce498194d069d18093d9a)
> * [3759e38](https://github.com/bazelbuild/bazel/commit/3759e3895503aa2bbd6943c5b568b8c050b9448f)
> * [4473bb1](https://github.com/bazelbuild/bazel/commit/4473bb1a9ec4282aa8497b86580d68e82415df4a)
> * [9137fb9](https://github.com/bazelbuild/bazel/commit/9137fb940886aa516f32ca8a36feccedb545c99b)

I can haz justification? :)
Could you specify (briefly!), for the benefit of release manager, which commit fixes which issue (and, unless this is already discussed in the issue, why that issue is a blocker). Thanks!

**Comment by aehlig** [comment] 2019-01-18 14:53
`scripts/release/release.sh create --force_rc=3 0.22.0 deb028e a3a5975 b8d0e1b 3759e38 4473bb1 9137fb9`

-- 
Klaus Aehlig
Google Germany GmbH, Erika-Mann-Str. 33, 80636 Muenchen
Registergericht und -nummer: Hamburg, HRB 86891
Sitz der Gesellschaft: Hamburg
Geschaeftsfuehrer: Paul Terence Manicle, Halimah DeLaine Prado

**Comment by aehlig** [comment] 2019-01-18 15:42
rc3 available at https://releases.bazel.build/0.22.0/rc3/index.html

**Comment by buchgr** [comment] 2019-01-22 19:00
Unfortunately #7212 is a regression. I am rolling back the root cause of it: https://github.com/bazelbuild/bazel/pull/7216

**Comment by aehlig** [comment] 2019-01-23 10:59
> Unfortunately #7212 is a regression. I am rolling back the root cause of it: #7216

OK, so I'll wait till #7216 is committed and generate a new RC then, with that commit added as cherry-pick.

**Comment by aehlig** [comment] 2019-01-23 17:04
`scripts/release/release.sh create --force_rc=4 deb028e a3a5975 b8d0e1b 3759e38 4473bb1 9137fb9 12ab12e80ad1c9a3510aa4bbfdf3fddafc0bca00 6345c747d8cb1819e70c853becadbf8a989decf1`

-- 
Klaus Aehlig
Google Germany GmbH, Erika-Mann-Str. 33, 80636 Muenchen
Registergericht und -nummer: Hamburg, HRB 86891
Sitz der Gesellschaft: Hamburg
Geschaeftsfuehrer: Paul Terence Manicle, Halimah DeLaine Prado

**Comment by aehlig** [comment] 2019-01-23 17:29
Sorry, that, of course, should read 

`scripts/release/release.sh create --force_rc=4 0.22.0 deb028e a3a5975 b8d0e1b 3759e38 4473bb1 9137fb9 12ab12e 6345c74`

**Comment by aehlig** [comment] 2019-01-23 21:57
RC4 is available at https://releases.bazel.build/0.22.0/rc4/index.html

**Comment by aehlig** [comment] 2019-01-28 12:50
As no more issues were reported, will promote rc4 to release.

**Comment by aehlig** [comment] 2019-01-28 13:47
Released, see https://github.com/bazelbuild/bazel/releases/tag/0.22.0

**Closed by aehlig** 2019-01-28 13:47 UTC
Labels: release

**Comment by petemounce** [comment] 2019-01-28 23:01
Pushed to chocolatey

**Comment by davido** [comment] 2019-01-31 06:07
Bazel 0.22.0 Alpine Linux package is [here](https://github.com/davido/bazel-alpine-package/releases/tag/0.22.0).
