### ISSUE TITLE
Documentation issue: Bazel container

### ISSUE THREAD

**Issue by iangudger** [bazelbuild/bazel#15040] opened 2022-03-14 20:22 UTC
Documentation URL: https://docs.bazel.build/versions/5.0.0/bazel-container.html

The container (l.gcr.io/google/bazel:latest) is out of date and contains an old version of Bazel (3.5.0).

**Comment by meteorcloudy** [comment] 2022-03-22 13:31
Duplicate of https://github.com/bazelbuild/continuous-integration/issues/1060

**Closed by meteorcloudy** 2022-03-22 13:31 UTC
Labels: type: documentation (cleanup), untriaged, team-OSS
