### ISSUE TITLE
java_plugin stopped working after upgrading to bazel 4.0.0

### ISSUE THREAD

**Issue by slamdev** [bazelbuild/bazel#13305] opened 2021-04-06 18:31 UTC
### Description of the problem / feature request:

**java_plugin** stopped working after upgrading to bazel **4.0.0**. 

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

To display the issue, I created this repo: https://github.com/slamdev/bazel4-java-plugin-issue

When you run the code with bazel **3.7.2**, everything works fine, but switching to bazel **4.0.0** breaks it.

CI pipeline that shows it: https://github.com/slamdev/bazel4-java-plugin-issue/actions/runs/723478900

### What operating system are you running Bazel on?

Tested with both MacOS and Ubuntu

### What's the output of `bazel info release`?

```
release 4.0.0
```

###  Have you found anything relevant by searching the web?

I went through this issue: https://github.com/bazelbuild/bazel/issues/12837 but it doesn't look to be related since the setup is working with the older bazel version. 

### Any other information, logs, or outputs that you want to share?

```sh
$ ./baseliskw build //lib_b:lib_b
INFO: Analyzed target //lib_b:lib_b (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
ERROR: /Users/slam/workspace/slamdev/bazel4-java-plugin-issue/lib_b/BUILD:1:13: Building lib_b/liblib_b.jar (1 source file) failed: (Exit 1): java failed: error executing command external/remotejdk11_macos/bin/java -XX:+UseParallelOldGC -XX:-CompactStrings '--patch-module=java.compiler=external/remote_java_tools_darwin/java_tools/java_compiler.jar' ... (remaining 15 argument(s) skipped)
lib_b/B.java:8: error: cannot find symbol
        A a = A.builder().build();
               ^
  symbol:   method builder()
  location: class A
Target //lib_b:lib_b failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 0.223s, Critical Path: 0.10s
INFO: 3 processes: 3 internal.

$ echo 3.7.2 > .bazelversion

$ ./baseliskw build //lib_b:lib_b
Extracting Bazel installation...
Starting local Bazel server and connecting to it...
INFO: Analyzed target //lib_b:lib_b (20 packages loaded, 395 targets configured).
INFO: Found 1 target...
Target //lib_b:lib_b up-to-date:
  bazel-bin/lib_b/liblib_b.jar
INFO: Elapsed time: 45.722s, Critical Path: 4.72s
INFO: 7 processes: 1 internal, 4 darwin-sandbox, 2 worker.
INFO: Build completed successfully, 7 total actions
```

**Comment by cushon** [comment] 2021-04-07 06:28
This is a duplicate of https://github.com/bazelbuild/bazel/issues/12837.

Upgrading to lombok 1.18.20 shows the following error:

```diff
diff --git a/WORKSPACE b/WORKSPACE
index 4e839e6..123d8be 100644
--- a/WORKSPACE
+++ b/WORKSPACE
@@ -4,6 +4,6 @@ load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_jar")

 http_jar(
     name = "lombok",
-    sha256 = "601ec46206e0f9cac2c0583b3350e79f095419c395e991c761640f929038e9cc",
-    url = "https://repo1.maven.org/maven2/org/projectlombok/lombok/1.18.18/lombok-1.18.18.jar",
+    sha256 = "ce947be6c2fbe759fbbe8ef3b42b6825f814c98c8853f1013f2d9630cedf74b0",
+    url = "https://repo1.maven.org/maven2/org/projectlombok/lombok/1.18.20/lombok-1.18.20.jar",
 )
```
 
```
$ bazel build //lib_b
...
ERROR: ./bazel4-java-plugin-issue/lib_a/BUILD:1:13: Compiling Java headers lib_a/liblib_a-hjar.jar (1 source file) and running annotation processors (AnnotationProcessorHider$AnnotationProcessor) failed
...
<>: error: Turbine is not currently supported by lombok.
```

**Closed by cushon** 2021-04-07 06:28 UTC
Labels: team-Rules-Java, untriaged
