### ISSUE TITLE
Unable to build TensorFlow using installers 0.1.1-3

### ISSUE THREAD

**Issue by zer0n** [bazelbuild/bazel#802] opened 2016-01-20 21:39 UTC
Cross post from https://github.com/tensorflow/tensorflow/issues/772#issuecomment-171735296

I run into the same problem when running
```
bazel build -c opt --config=cuda //tensorflow/tools/pip_package:build_pip_package
```

bazel 0.1.1 and 0.1.3 give this error immediately
```
java.lang.NoClassDefFoundError: com/jcraft/jsch/JSchException
        at org.eclipse.jgit.transport.JschConfigSessionFactory.getSession(JschConfigSessionFactory.java:109)
        at org.eclipse.jgit.transport.SshTransport.getSession(SshTransport.java:136)
        at org.eclipse.jgit.transport.TransportGitSsh$SshFetchConnection.<init>(TransportGitSsh.java:262)
        at org.eclipse.jgit.transport.TransportGitSsh.openFetch(TransportGitSsh.java:161)
        at org.eclipse.jgit.transport.FetchProcess.executeImp(FetchProcess.java:136)
        at org.eclipse.jgit.transport.FetchProcess.execute(FetchProcess.java:122)
        at org.eclipse.jgit.transport.Transport.fetch(Transport.java:1138)
        at org.eclipse.jgit.api.FetchCommand.call(FetchCommand.java:130)
        at org.eclipse.jgit.api.CloneCommand.fetch(CloneCommand.java:193)
        at org.eclipse.jgit.api.CloneCommand.call(CloneCommand.java:133)
        at com.google.devtools.build.lib.bazel.repository.GitCloneFunction.compute(GitCloneFunction.java:127)
        at com.google.devtools.build.skyframe.ParallelEvaluator$Evaluate.run(ParallelEvaluator.java:933)
        at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:499)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
```

bazel 0.1.2 fails to build protobuf. 
```
INFO: Found 1 target...
INFO: From Compiling google/protobuf/src/google/protobuf/extension_set.cc [for host]:
src/main/tools/namespace-sandbox.c:633: execvp(argv[0], argv): No such file or directory
ERROR: /home/zer0n/src/tensorflow/google/protobuf/BUILD:29:1: C++ compilation of rule '//google/protobuf:protobuf_lite' failed: crosstool_wrapper_driver_is_not_gcc failed: error executing command
  (cd /home/zer0n/.cache/bazel/_bazel_zer0n/752539f897d4732a3a650ab733666abd/tensorflow && \
  exec env - \
    PATH=/home/zer0n/src/torch/install/bin:/usr/local/cuda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games \
  third_party/gpus/crosstool/clang/bin/crosstool_wrapper_driver_is_not_gcc -U_FORTIFY_SOURCE '-D_FORTIFY_SOURCE=1' -fstack-protector -fPIE -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 -DNDEBUG -ffunction-sections -fdata-sections -g0 '-std=c++11' -iquote . -iquote bazel-out/host/genfiles -iquote external/bazel_tools -iquote bazel-out/host/genfiles/external/bazel_tools -isystem google/protobuf/src -isystem bazel-out/host/genfiles/google/protobuf/src -isystem external/bazel_tools/tools/cpp/gcc3 -DHAVE_PTHREAD -Wall -Wwrite-strings -Woverloaded-virtual -Wno-sign-compare '-Wno-error=unused-function' -no-canonical-prefixes -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' -fno-canonical-system-headers '-frandom-seed=bazel-out/host/bin/google/protobuf/_objs/protobuf_lite/google/protobuf/src/google/protobuf/extension_set.o' -MD -MF bazel-out/host/bin/google/protobuf/_objs/protobuf_lite/google/protobuf/src/google/protobuf/extension_set.d -c google/protobuf/src/google/protobuf/extension_set.cc -o bazel-out/host/bin/google/protobuf/_objs/protobuf_lite/google/protobuf/src/google/protobuf/extension_set.o): crosstool_wrapper_driver_is_not_gcc failed: error executing command
  (cd /home/zer0n/.cache/bazel/_bazel_zer0n/752539f897d4732a3a650ab733666abd/tensorflow && \
  exec env - \
    PATH=/home/zer0n/src/torch/install/bin:/usr/local/cuda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games \
  third_party/gpus/crosstool/clang/bin/crosstool_wrapper_driver_is_not_gcc -U_FORTIFY_SOURCE '-D_FORTIFY_SOURCE=1' -fstack-protector -fPIE -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 -DNDEBUG -ffunction-sections -fdata-sections -g0 '-std=c++11' -iquote . -iquote bazel-out/host/genfiles -iquote external/bazel_tools -iquote bazel-out/host/genfiles/external/bazel_tools -isystem google/protobuf/src -isystem bazel-out/host/genfiles/google/protobuf/src -isystem external/bazel_tools/tools/cpp/gcc3 -DHAVE_PTHREAD -Wall -Wwrite-strings -Woverloaded-virtual -Wno-sign-compare '-Wno-error=unused-function' -no-canonical-prefixes -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' -fno-canonical-system-headers '-frandom-seed=bazel-out/host/bin/google/protobuf/_objs/protobuf_lite/google/protobuf/src/google/protobuf/extension_set.o' -MD -MF bazel-out/host/bin/google/protobuf/_objs/protobuf_lite/google/protobuf/src/google/protobuf/extension_set.d -c google/protobuf/src/google/protobuf/extension_set.cc -o bazel-out/host/bin/google/protobuf/_objs/protobuf_lite/google/protobuf/src/google/protobuf/extension_set.o).
Target //tensorflow/tools/pip_package:build_pip_package failed to build
INFO: Elapsed time: 1.338s, Critical Path: 0.33s.
```

**Comment by damienmg** [comment] 2016-01-21 12:26
Let's just 0.1.3 (or 0.1.4)
Can you reproduce without --config=cuda?

I cannot and cannot seems to be able to configure cuda correctly on my machine.

**Comment by zer0n** [comment] 2016-01-21 14:50
`bazel build -c opt //tensorflow/tools/pip_package:build_pip_package` gives the same error.

(tested with bazel 0.1.3).

**Comment by damienmg** [comment] 2016-01-21 14:52
pulling in @dzc if he knows more about that. It's probably a git config issue

**Comment by vrv** [comment] 2016-01-21 21:05
@zer0n: try adding --spawn_strategy=standalone

Also, I think as of this morning we now require bazel 0.1.4 because of internal changes made by the bazel team to start using labels for loading skylark extensions.

**Comment by zer0n** [comment] 2016-01-21 23:24
Thanks @vrv . Adding `--spawn_strategy=standalone` works.

FYI, bazel 0.1.4 also fails to build without the above option.

**Comment by vrv** [comment] 2016-01-21 23:26
@damienmg: is there a bug we can point people as to why --spawn_strategy=standalone is required, and when it might be fixed?

**Comment by vrv** [comment] 2016-01-21 23:30
Looks like https://github.com/bazelbuild/bazel/issues/753

**Comment by davidzchen** [comment] 2016-01-22 07:14
FYI The jsch NoClassDefFoundError was a known issue for Bazel 0.1.1 (see #596) and was fixed in 916370ec6195d7fc13812e64a65c2cd6ef9e36c9 and should not be occurring anymore in the latest release.

**Comment by zer0n** [comment] 2016-01-22 08:10
@davidzchen Apparently, there was a regression in `bazel 0.1.3`. 

I got around that issue by commenting out this line in my `.gitconfig` file.

```
[url "ssh://git@github.com/"]
	insteadOf = https://github.com/
```

**Comment by davidzchen** [comment] 2016-01-22 10:17
Interesting. I'll take a look.

**Comment by davidzchen** [comment] 2016-01-22 10:41
I found the problem. Commit 27760a6efefc64f9577ed1add120b60399203be3 inadvertently removed `//third_party/jsch` from the `runtime_deps`. I'll put together a patch for restoring that dependency.

**Comment by davidzchen** [comment] 2016-01-22 11:26
The patch that restores the jsch `runtime_dep` should be out with the next push. Note that this will only fix the `NoClassDefFoundError`; the Git workspace rules currently only support cloning via HTTP but not via SSH. I have opened #810 for adding support for cloning via SSH.

**Comment by davidzchen** [comment] 2016-01-22 21:41
The jsch NoClassDefFoundError is now fixed by cc9e445. The other issues seem to be separate problems.

**Comment by johnynek** [comment] 2016-02-05 22:27
@davidzchen is there a test for the jsch issue?

**Comment by damienmg** [comment] 2016-05-03 13:01
The commi

**Comment by davidzchen** [comment] 2016-05-05 20:20
+cc @kchodorow 

AFAIK there are no tests for git cloning over SSH yet, which is what jsch was required for.

**Comment by kchodorow** [comment] 2016-05-10 18:47
Yeah, there are no tests for SSH cloning.

**Comment by kchodorow** [comment] 2016-06-15 19:51
Going to close this in favor of #1408.

**Closed by kchodorow** 2016-06-15 19:51 UTC
Labels: category: extensibility > external repositories, P3, type: bug
