### ISSUE TITLE
Bzlmod: stardoc is broken by repo mappings

### ISSUE THREAD

**Issue by meteorcloudy** [bazelbuild/bazel#14140] opened 2021-10-20 15:05 UTC
When Bzlmod is enabled, building stardoc for a bzl_library which has external dependencies will fail.

This is discovered in https://github.com/bazelbuild/bazel-central-registry/pull/18, and the build failure can be found [here](https://buildkite.com/bazel/bcr-presubmit/builds/37#f4cbef4e-b3b4-41dd-acda-342d99acb790).

The root cause is that when Bzlmod is enabled, the canonical repo name for bazel_skylib is bazel_skylib.1.0.3, which now contains the version number. In the normal bazel build, we have repo mappings to make sure BUILD/bzl files can still access the targets under the repository with @bazel_skylib. However, when [stardoc](https://cs.opensource.google/bazel/bazel/+/master:src/main/java/com/google/devtools/build/skydoc/BUILD;l=27) is [parsing a label](https://cs.opensource.google/bazel/bazel/+/master:src/main/java/com/google/devtools/build/skydoc/SkydocMain.java;l=421), it's not doing any repo mapping to locate the canonical repo name. Which led to:

```
Stardoc documentation generation failed: File external/io_bazel_stardoc.0.5.0/stardoc/stardoc.bzl imported '@bazel_skylib//:bzl_library.bzl', yet external/bazel_skylib/bzl_library.bzl was not found, even at roots [., external/__main__].
```

Note that this is also an issue if you use the repo mapping feature in WORKSPACE file, but it's not widely used so no one has hit this problem before. Since we are embracing the repo mapping feature in Bzlmod to avoid conflicts and provide strict deps, we have to solve this problem. 

Related https://github.com/bazelbuild/bazel/issues/13316

**Comment by keith** [comment] 2022-01-24 17:20
Ah, I also filed https://github.com/bazelbuild/stardoc/issues/117 about this

**Comment by Wyverald** [comment] 2022-01-24 17:38
Is there a runfiles library for Java? I think @fmeum also had a rules_runfiles or something. (Sorry I've never really looked into runfiles) That's probably the best way to resolve this.

**Comment by fmeum** [comment] 2022-01-24 17:45
> Is there a runfiles library for Java? I think @fmeum also had a rules_runfiles or something. (Sorry I've never really looked into runfiles) That's probably the best way to resolve this.

The runfiles library at `@bazel_tools//tools/java/runfiles` (and my ruleset based on it) solves the somewhat orthogonal problem of getting the runtime path on disk of a runfile given its path under `external`, i.e. `internal_repo_name/path/to/pkg/file`. But if I understand the current issue correctly, the problem is that Stardoc is not repo mappings aware?

**Comment by Wyverald** [comment] 2022-01-24 17:53
Yeah Stardoc needs to convert a label into a runfile path (runtime path of a runfile?) and that's not so simple with repo mappings.

**Comment by comius** [comment] 2022-11-04 17:11
> Yeah Stardoc needs to convert a label into a runfile path (runtime path of a runfile?) and that's not so simple with repo mappings.

It's slightly worse. It needs to convert it to execpath. There are no runfiles (because render is packed separately than input .bzl files), and no repo_mapping because of this.

**Comment by fmeum** [comment] 2022-11-04 19:53
@comius I formated an alternative idea in https://github.com/bazelbuild/proposals/blob/main/designs/2022-07-21-locating-runfiles-with-bzlmod.md#4-make-stardoc-compatible-with-repository-mappings, do you think that could work? @tetromino is working on a rewrite of some parts of stardoc that would allow it to request bzl files from Skyframe (if I understood him correctly), which should also solve this issue.

**Comment by comius** [comment] 2022-11-05 09:35
Yes, that works. I was thinking of a slight alternative where macro would add a custom `java_binary` StardocMain with data runfiles. Maybe slightly less hacky, because you don't need a no-op executable.

Second alternative option is to add repository mapping information to `bzl_library` and dump it into a file in `stardoc` rule. I'm guessing you can collect the needed triples in `bzl_library` into a depset. And then you could use `args` trick to dump to a file neatly. But that would need a second implementation of reading repo mapping in StartdocMain similar to runfiles.

**Comment by fmeum** [comment] 2022-11-05 10:28
The custom StardocMain binary sounds better, yes.

I am not so sure you can actually collect the apparent names because the rule implementation typically only sees the canonical names. But even if you could, reusing the existing repository mapping logic even if by a small hack seems more reliable to me.

@tetromino Can you estimate when you would get to work on the improved bzl loading for Stardoc? Would the changes require a new Bazel version or could they be used independentl

**Comment by fmeum** [comment] 2023-04-25 19:24
@comius Saw the merge, thanks for that! Maybe we should keep this issue open until there is a BCR release of stardoc with the changes?

**Comment by tetromino** [comment] 2023-05-16 22:01
Fixed by https://github.com/bazelbuild/bazel-central-registry/pull/635

**Closed by tetromino** 2023-05-16 22:01 UTC
Labels: type: bug, P2, team-ExternalDeps, area-Bzlmod
