### ISSUE TITLE
Non-determinism of pkg_deb because of control.tar.gz

### ISSUE THREAD

**Issue by rlguarino** [bazelbuild/bazel#3723] opened 2017-09-11 20:48 UTC
### Description of the problem / feature request / question:

Building the same deb package twice results two packages with different hashes. Something similar happens here: https://github.com/bazelbuild/bazel/issues/1844. It seems that using gzip adds a timestamp which isn't zeroed. If we don't use gzip when building the control file then the package is deterministic. 

I can fix the issue with this patch:

``` diff
diff --git a/tools/build_defs/pkg/make_deb.py b/tools/build_defs/pkg/make_deb.py
index 99ae379..01f572f 100644
--- a/tools/build_defs/pkg/make_deb.py
+++ b/tools/build_defs/pkg/make_deb.py
@@ -120,7 +120,7 @@ def MakeDebianControlField(name, value, wrap=False):
 
 
 def CreateDebControl(extrafiles=None, **kwargs):
-  """Create the control.tar.gz file."""
+  """Create the control.tar file."""
   # create the control file
   controlfile = ''
   for values in DEBIAN_FIELDS:
@@ -130,7 +130,7 @@ def CreateDebControl(extrafiles=None, **kwargs):
       controlfile += MakeDebianControlField(fieldname, kwargs[key], values[2])
   # Create the control.tar file
   tar = StringIO()
-  with tarfile.open('control.tar.gz', mode='w:gz', fileobj=tar) as f:
+  with tarfile.open('control.tar', mode='w', fileobj=tar) as f:
     tarinfo = tarfile.TarInfo('control')
     tarinfo.size = len(controlfile)
     f.addfile(tarinfo, fileobj=StringIO(controlfile))
@@ -171,7 +171,7 @@ def CreateDeb(output,
   with open(output, 'w') as f:
     f.write('!<arch>\n')  # Magic AR header
     AddArFileEntry(f, 'debian-binary', '2.0\n')
-    AddArFileEntry(f, 'control.tar.gz', control)
+    AddArFileEntry(f, 'control.tar', control)
     # Tries to preserve the extension name
     ext = os.path.basename(data).split('.')[-2:]
     if len(ext) < 2:
```

Building the following pkg_deb shouild results in a .deb which has the same hash each time it's built.

### BUILD
``` 
pkg_tar(
    name = "data",
    package_dir = "/opt",
    files = [":test.txt"],
    mode = "0755"
)

pkg_deb(
   name="t",
   version="1",
   data=":data",
   package="test",
   maintainer="Ross",
   description="hello world"
)
```

### Environment info
* Operating System:
Ubuntu 16.10

* Bazel version (output of `bazel info release`):
```
$ bazel info release
release 0.5.4
```

**Comment by rlguarino** [comment] 2017-09-11 20:51
I'm not sure if that diff is acceptable, I'm not sure if people are relying on the `control.tar.gz` file name not, dpkg does not seem to care but that does not mean people haven't hard coded a script.

I'm also not sure what's more important backwards compatibility with the `control.tar.gz` filename or deterministic build results.

**Comment by philwo** [comment] 2017-09-12 12:46
That looks like the culprit: https://github.com/python/cpython/blob/3.6/Lib/tarfile.py#L427

Maybe we could workaround this by creating an uncompressed tar and then using the "gzip" module to compress it? I think that doesn't implicitly use a timestamp.

**Comment by damienmg** [comment] 2017-09-12 12:51
Could that be the same root cause as the github archive changing SHA?

I would accept the diff to just not gziping the control file.

**Comment by brian-peloton** [comment] 2017-09-18 22:50
Duplicate of #1844 I think.

@philsc has a nice way of fixing this for pkg_deb out for review at [I4ce38a317bb92481562b67075d1272f1aebdf9d6](https://bazel-review.googlesource.com/q/I4ce38a317bb92481562b67075d1272f1aebdf9d6) and is working on doing it for pkg_tar too I believe.

**Comment by philsc** [comment] 2017-09-19 00:39
@brian-peloton , not quite a duplicate I would say because control.tar.gz doesn't get creating using pkg_tar.

Meaning that there are two independent places in the code base where this needs to be fixed.

Currently working on fixing pkg_tar too, yeah.

**Closed** 2017-09-25 13:40 UTC
Labels: category: skylark > pkg build defs, P2, type: bug
