### ISSUE TITLE
Target names may not contain non-printable characters

### ISSUE THREAD

**Issue by Dig-Doug** [bazelbuild/bazel#8108] opened 2019-04-22 14:21 UTC
### Description of the problem / feature request:

I am trying to build boost 1.70.0, but I am getting the following error:

```bash
ERROR: /home/doug/.cache/bazel/_bazel_doug/ec7ee50e49190ad01e42da43d561d88d/external/boost/BUILD.bazel:1:1: @boost//:all: invalid label 'libs/wave/test/testwave/testfiles/utf8-test-ßµ™∃/file.hpp' in element 60163 of attribute 'srcs' in 'filegroup' rule: invalid target name 'libs/wave/test/testwave/testfiles/utf8-test-ßµ™∃/file.hpp': target names may not contain non-printable characters: '\x9F'
```

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

I've created a demo [here](https://github.com/Dig-Doug/bazel-boost-invalid-chars)

### What operating system are you running Bazel on?

Ubuntu 18.04.2 LTS

### What's the output of `bazel info release`?

INFO: Invocation ID: d095f408-53c3-4ae4-b633-f8014ad9d80b
release 0.25.0rc3

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

git@github.com:Dig-Doug/bazel-boost-invalid-chars.git
3ace7984f6feeff1f6b5df63ecca97b4bc175298
3ace7984f6feeff1f6b5df63ecca97b4bc175298

###  Have you found anything relevant by searching the web?

I originally got a different error with unmappable characters, but it was fixed recently so I'm trying with the rc.

### Any other information, logs, or outputs that you want to share?

I can work around this issue by excluding the files like this:

```python
filegroup(
    name = "all",
    srcs = glob(["**"],
        exclude = ["libs/wave/test/**/*"],
    ),
    visibility = ["//visibility:public"]
)
```

Though this isn't ideal -- If I needed this file (and I have no control over it since it's a third party dep), I wouldn't be able to use it.

**Comment by aiuto** [comment] 2019-04-22 18:13
This looks like a duplicate of #374

**Closed** 2019-04-22 18:14 UTC
Labels: duplicate

**Comment by dev-guy** [comment] 2019-09-14 16:37
Is there a workaround?

**Comment by mancini0** [comment] 2019-10-28 22:36
I run into this issue on ubuntu 18.04 but it works fine when building on fedora 29 or fedora 30. My .bazelrc is under source control so it is the same across all environments - I'm not sure why the issue only causes grief on ubuntu 18.04, but any insight would be appreciated.

**Comment by lrahmani** [comment] 2020-01-28 13:17
@mancini0 I run into similar issue with Ubuntu 18.04 (offical docker image).
If you are still interested, it is a locale issue, and runing the following solved my issue

```bash
apt install -y locales && \
locale-gen en_US.UTF-8 && \
export LANG=en_US.UTF-8 && \
echo "export LANG=en_US.UTF-8" >> ~/.bashrc
```
as apparently, bazel check these vars for encoding https://github.com/bazelbuild/bazel/commit/eae93f643ccfe19df24bb1dd837c45056a15c274#diff-720bb04a34f0bdcc76bd8f64a79e2f16R1431
