### ISSUE TITLE
Version our public documentation with Bazel releases

### ISSUE THREAD

**Issue by philwo** [bazelbuild/bazel#1429] opened 2016-06-20 11:10 UTC
Users are confused when we document something that is in Bazel HEAD, but not yet available in the latest released Bazel. See https://github.com/bazelbuild/bazel/issues/1418 for an example.

We should probably version our public documentation together with Bazel releases and allow people to switch between doc versions.

As an example for what I personally like in that regard, check https://docs.djangoproject.com/en/1.9/ (the version is in the URL and there's a switcher for the released versions and also the development branch in the lower right corner of the screen).

**Comment by damienmg** [comment] 2016-06-20 11:23
Duplicate of #1382

**Closed by damienmg** 2016-06-20 11:23 UTC
Labels: category: misc > release / binary, P3, type: documentation
