### ISSUE TITLE
Bazel Illegal char <*> at index [duplicate of #10331]

### ISSUE THREAD

**Issue by bigfluffycookie** [bazelbuild/bazel#10096] opened 2019-10-24 13:58 UTC
Hello, I am having an issue when trying to build a pipeline for Seurat. 
The error warnings that are most informative are the Illegal char <*> at index and that it can't fetch the openexr repository. 
 
Im running Bazel on Windows 10. 
Bazel realease 1.0.1
CMD with Visual Studio 2019 

I have found a few similar issues but none of the answers on there have helped me so far.

The files attached are the errors that I am getting and my seurat WORKSPACE file if that is of any use. If more information is needed I am happy to provide it. 

[Documents.zip](https://github.com/bazelbuild/bazel/files/3767872/Documents.zip)

**Comment by irengrig** [comment] 2019-10-28 09:35
Hi @bigfluffycookie , thank you for reporting the issue!
Seems like there is a problem when Bazel's @local_config_cc is trying to discover Visual Studio, and bumping into a command prompt:

INFO: Call stack for the definition of repository 'openexr' which is a http_archive (rule definition at C:/users/leyla/_bazel_leyla/yd6le3hf/external/bazel_tools/tools/build_defs/repo/http.bzl:262:16):
 - C:/users/leyla/documents/seurat/WORKSPACE:91:1
ERROR: An error occurred during the fetch of repository 'openexr':
   java.io.IOException: thread interrupted
Internal error thrown during build. Printing stack trace: java.lang.RuntimeException: Unrecoverable error while evaluating node 'REPOSITORY_DIRECTORY:@local_config_cc' (requested by nodes 'REPOSITORY:@local_config_cc')
        at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:531)
        at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:399)
        at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinPool.scan(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
Caused by: java.nio.file.InvalidPathException: Illegal char <*> at index 62: C:/users/leyla/_bazel_leyla/yd6le3hf/external/local_config_cc/**********************************************************************
** Visual Studio 2019 Developer Command Prompt v16.0
** Copyright (c) 2019 Microsoft Corporation
**********************************************************************
C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Auxiliary/Build/VCVARSALL.BAT
        at java.base/sun.nio.fs.WindowsPathParser.normalize(Unknown Source)
        at java.base/sun.nio.fs.WindowsPathParser.parse(Unknown Source)
        at java.base/sun.nio.fs.WindowsPathParser.parse(Unknown Source)
        at java.base/sun.nio.fs.WindowsPath.parse(Unknown Source)
        at java.base/sun.nio.fs.WindowsFileSystem.getPath(Unknown Source)
        at java.base/java.nio.file.Path.of(Unknown Source)

/cc @laszlocsomor @meteorcloudy

**Comment by laszlocsomor** [comment] 2019-10-28 09:38
Hi @bigfluffycookie , try setting `BAZEL_VC` environment variable to your VC directory as described on [docs.bazel.build > "Installing and Using Bazel" > "Installing on Windows" > "Troubleshooting" > "Problem: Bazel does not find Visual Studio or Visual C++"](https://docs.bazel.build/versions/master/install-windows.html#problem-bazel-does-not-find-visual-studio-or-visual-c).

**Comment by bigfluffycookie** [comment] 2019-10-28 09:47
@laszlocsomor Hi! I just tried that and nothing has changed, the error logged stayed the same.

**Comment by laszlocsomor** [comment] 2019-10-28 09:59
@bigfluffycookie : Try `bazel clean --expunge` first, then try the build again. It will ensure that Bazel re-fetches the `local_config_cc` repository, i.e. it re-runs the C++ toolchain autoconfig step.

Also, does anything from https://docs.bazel.build/versions/master/windows.html#build-c-with-msvc help?

**Comment by bigfluffycookie** [comment] 2019-10-28 10:28
Alright so quick update I switched to VS2017 In hope it would do anything and I used bazel clean, the error Log now Looks different. 

also just to make sure that the Issue isnt this I'd like to ask quickly if the http_archieve is actually correct. 

_http_archive(
    name = "openexr",
    build_file = "third_party/openexr.BUILD",
	strip_prefix = "openexr-2.3.0",
    urls = ["https://github.com/openexr/openexr/archive/v2.3.0.zip"],
)_





is different Starting local Bazel server and connecting to it...
INFO: Writing tracer profile to 'C:/users/leyla/_bazel_leyla/yd6le3hf/command.profile.gz'
INFO: SHA256 (https://github.com/gflags/gflags/archive/6d1c363dde8a4277f7f363446a82b2188fd94608.zip) = 8982f082a5b83d596b5d3b1992a7ba508e3054ca7a998a382031727968a2d123
DEBUG: Rule 'gflags' indicated that a canonical reproducible form can be obtained by modifying arguments sha256 = "8982f082a5b83d596b5d3b1992a7ba508e3054ca7a998a382031727968a2d123"
DEBUG: Call stack for the definition of repository 'gflags' which is a http_archive (rule definition at C:/users/leyla/_bazel_leyla/yd6le3hf/external/bazel_tools/tools/build_defs/repo/http.bzl:262:16):
 - C:/users/leyla/documents/seurat/WORKSPACE:86:1
INFO: SHA256 (https://github.com/openexr/openexr/archive/v2.3.0.zip) = 3a2524bf3c146941befeeed6d6df37ff95ace612bc3cb598b0e8bfca7b23cfcc
INFO: Call stack for the definition of repository 'openexr' which is a http_archive (rule definition at C:/users/leyla/_bazel_leyla/yd6le3hf/external/bazel_tools/tools/build_defs/repo/http.bzl:262:16):
 - C:/users/leyla/documents/seurat/WORKSPACE:92:1
ERROR: An error occurred during the fetch of repository 'openexr':
   Traceback (most recent call last):
        File "C:/users/leyla/_bazel_leyla/yd6le3hf/external/bazel_tools/tools/build_defs/repo/http.bzl", line 60
                workspace_and_buildfile(ctx)
        File "C:/users/leyla/_bazel_leyla/yd6le3hf/external/bazel_tools/tools/build_defs/repo/utils.bzl", line 61, in workspace_and_buildfile
                ctx.symlink(ctx.attr.build_file, "BUILD.bazel")
Not a regular file: C:/users/leyla/documents/seurat/external/third_party/openexr.BUILD
ERROR: C:/users/leyla/documents/seurat/seurat/pipeline/BUILD:78:1: //seurat/pipeline:seurat depends on @openexr//:ilm_imf in repository @openexr which failed to fetch. no such package '@openexr//': Traceback (most recent call last):
        File "C:/users/leyla/_bazel_leyla/yd6le3hf/external/bazel_tools/tools/build_defs/repo/http.bzl", line 60
                workspace_and_buildfile(ctx)
        File "C:/users/leyla/_bazel_leyla/yd6le3hf/external/bazel_tools/tools/build_defs/repo/utils.bzl", line 61, in workspace_and_buildfile
                ctx.symlink(ctx.attr.build_file, "BUILD.bazel")
Not a regular file: C:/users/leyla/documents/seurat/external/third_party/openexr.BUILD
ERROR: Analysis of target '//seurat/pipeline:seurat' failed; build aborted: no such package '@openexr//': Traceback (most recent call last):
        File "C:/users/leyla/_bazel_leyla/yd6le3hf/external/bazel_tools/tools/build_defs/repo/http.bzl", line 60
                workspace_and_buildfile(ctx)
        File "C:/users/leyla/_bazel_leyla/yd6le3hf/external/bazel_tools/tools/build_defs/repo/utils.bzl", line 61, in workspace_and_buildfile
                ctx.symlink(ctx.attr.build_file, "BUILD.bazel")
Not a regular file: C:/users/leyla/documents/seurat/external/third_party/openexr.BUILD
INFO: Elapsed time: 12.752s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (17 packages loaded, 19 targets configured)

**Comment by laszlocsomor** [comment] 2019-10-28 10:34
This error:

> Not a regular file: C:/users/leyla/documents/seurat/external/third_party/openexr.BUILD

Does `third_party/openexr.BUILD` exist and is it a regular file?

I think you must also fully qualify the `http_archive(build_file=)` label like so:

```diff
 http_archive(
     name = "openexr",
-    build_file = "third_party/openexr.BUILD",
+    build_file = "@//third_party/openexr.BUILD",
     strip_prefix = "openexr-2.3.0",
     urls = ["https://github.com/openexr/openexr/archive/v2.3.0.zip"],
 )
```

Reason:

> This attribute is an absolute label (use '@//' for the main repo).

(From https://docs.bazel.build/versions/master/repo/http.html#http_archive-build_file)

**Comment by bigfluffycookie** [comment] 2019-10-28 10:45
The file exists and it is a regular file, I had the http_archieve like you suggested previously and just changed it to check if it makes any difference which it doesn't. Error stays the same

**Comment by laszlocsomor** [comment] 2019-10-28 11:41
I now realize @irengrig discovered this was the C++ config step failing, and as such it's unrelated to `http_archive`. Let's verify that, could you create a directory with nothing but an empty WORKSPACE file and run `bazel info` there? If that succeeds, try adding a BUILD file with the content `cc_binary(name='x', srcs=['x.cc'])`, and add `x.cc` as well with some dummy C++ code and see if `bazel build //:x` works?

**Comment by bigfluffycookie** [comment] 2019-10-28 14:44
I have decided to retry everything on Linux and come back to Windows later. Incase I have any updates once it works on Windows I will post my solution here.

**Comment by laszlocsomor** [comment] 2019-10-28 14:45
SGTM, thanks for helping debugging!

**Comment by bigfluffycookie** [comment] 2019-10-28 18:20
Alright so quick update, I redid everything on Linux where it gave me the exact same error. So I went and removed bazel, downloaded version 0.17.2 and it works. It really seems to be the Issue with the WORKSPACE file from seurat. I am very new to this so I didn't realize earlier that in the newest Bazel version or well since the version 0.24.0 I think the http_archive got depricated  if my understanding of the Workspace rules site (https://docs.bazel.build/versions/1.1.0/be/workspace.html) is correct. I haven't tried the same yet on windows but I'll get to that tmrw.

**Comment by laszlocsomor** [comment] 2019-10-29 07:54
Thanks for the update! The built-in `http_archive` rule from old Bazel versions was indeed deprecated, but there's a drop-in replacement that you have to `load()`. See https://docs.bazel.build/versions/1.1.0/repo/http.html#http_archive for an example.

[Documents.zip](https://github.com/bazelbuild/bazel/files/3767872/Documents.zip) from your first message has a WORKSPACE file which correctly `load()`s http_archive.

**Comment by bigfluffycookie** [comment] 2019-10-29 09:05
Okay yea you're right, the part where I'm confused though is that in the original workspace file from seurat it was supposed to be "new_http_archive" instead of "http-archive" and well both are depricated but just http_archive doesn't actually take a build_file as far as I can see so I'm confused how I'm supposed to replace that. Would I have to use local_repository or something like that instead?

**Comment by laszlocsomor** [comment] 2019-10-29 09:15
You're right! Yes, the native rules "new_http_archive" and "http_archive" are both deprecated, but their functionality is also merged into the new "http_archive" rule (which is not a native rule but one written in Starlark, that's why you have to `load` it).

You can either define an arbitrarily named file that'll be used as the BUILD file (with the `build_file` attribute) or you can define the contents of the to-be BUILD file (with the `build_file_content` attribute) which Bazel will create in the directory where it extracted the archive. This a relevant topic: https://stackoverflow.com/a/58603801/7778502

local_repository and new_local_repository serve a slightly different purpose: instead of downloading and extracting an archive, they let you point to an existing directory and promote that to be a repository.

**Comment by laszlocsomor** [comment] 2019-12-18 09:14
Should be fixed by https://github.com/bazelbuild/bazel/commit/56568045c27285d54b52106486134efed31834bd.
See duplicate issue's comments https://github.com/bazelbuild/bazel/issues/10331#issuecomment-559725478 and https://github.com/bazelbuild/bazel/issues/10331#issuecomment-566943210.

**Closed by laszlocsomor** 2019-12-18 09:14 UTC
Labels: team-XProduct, untriaged
