### ISSUE TITLE
Sandbox returns "no such file or directory"

### ISSUE THREAD

**Issue by lberki** [bazelbuild/bazel#1063] opened 2016-03-21 09:56 UTC
I ran `scripts/setup-intellij.sh` at `4b2745c5` and this is what popped up:

```
ERROR: /usr/local/google/home/lberki/bazel/github/src/main/java/com/google/devtools/build/lib/BUILD:108:1: Extracting interface //src/main/java/com/google/devtools/build/lib:vfs failed: namespace-sandbox failed: error executing command /usr/local/google/home/lberki/.cache/bazel/_bazel_lberki/737f930c0b15836858bd51aa38e729ca/github/_bin/namespace-sandbox ... (remaining 5 argument(s) skipped).
src/main/tools/namespace-sandbox.c:583: mount(opt->mount_sources[i], full_sandbox_path, NULL, MS_REC | MS_BIND | MS_RDONLY, NULL): No such file or directory
```

**Comment by lberki** [comment] 2016-03-21 09:57
@hermione521

**Comment by hermione521** [comment] 2016-03-21 10:59
can't repro

**Comment by philwo** [comment] 2016-03-21 11:44
It fails when mounting something, which really looks like a bug in the sandbox, not the binary that was called or an issue with dependencies. We should try to reproduce this with --verbose_failures and --sandbox_debug. Maybe it's a bug in the recent work on sandboxing, because there were some changes to how it builds the list of files to mount.

Without a better error message though, we can't see what exactly failed here.

**Comment by shahms** [comment] 2016-03-21 15:19
This is due to commit 5b1fce59a09fe58548661e5247db455035827830

**Comment by shahms** [comment] 2016-03-21 15:20
If you run with --sandbox_debug you'll likely see that the failure is due to a path `/etc/nsscacheclient-candidate.<digits>`

**Comment by philwo** [comment] 2016-03-21 16:23
@shahms You're right. Thanks! :) I'm sending a fix for this in the next hour.

**Closed** 2016-03-21 18:46 UTC
Labels: Bug, P2, Sandboxing
