### ISSUE TITLE
Bzlmod is not fetching 'patches' using netrc credentials

### ISSUE THREAD

**Issue by daniel-eiland** [bazelbuild/bazel#18864] opened 2023-07-08 04:27 UTC
### Description of the bug:

Patches from a bzlmod registry are not being fetched with netrc credentials.

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Add netrc entry for the bazel registry and verify GETs for patch files do not include Authorization header.

### Which operating system are you running Bazel on?

Linux

### What is the output of `bazel info release`?

release 6.2.1

### What's the output of `git remote get-url origin; git rev-parse master; git rev-parse HEAD` ?

```text
N/A
```

### Is this a regression? If yes, please try to identify the Bazel commit where the bug was introduced.

No

### Have you found anything relevant by searching the web?

https://github.com/bazelbuild/bazel/blob/master/src/main/java/com/google/devtools/build/lib/bazel/bzlmod/IndexRegistry.java#L251

Credentials / netrc info don't seem to be passed along with the patches.

### Any other information, logs, or outputs that you want to share?

Some packets from internal server set as a registry (via --registry):
Patch file GET (no Authorization header):
```
04:16:23.533902 IP CLIENT.54130 > SERVER.80: Flags [P.], seq 15669:15945, ack 76109, win 841, length 276: HTTP: GET /bazel-central-registry-mirror/protobuf-patch-180/modules/platforms/0.0.6/patches/module_dot_bazel.patch HTTP/1.1
E..<.0@.@..B..Q(
        m..r.P.....w&<P..Iux..GET /bazel-central-registry-mirror/protobuf-patch-180/modules/platforms/0.0.6/patches/module_dot_bazel.patch HTTP/1.1
Accept: text/html, image/gif, image/jpeg, */*
User-Agent: Bazel/release 6.2.1
Accept-Encoding: gzip
Host: bazel.corp.lucid.lcl
Connection: keep-alive
```

Non-patch file GET (Authorization header):
```
04:16:16.090425 IP 172.18.81.40.54130 > 10.9.109.6.80: Flags [P.], seq 6385:6677, ack 32215, win 501, length 292: HTTP: GET /bazel-central-registry-mirror/protobuf-patch-180/modules/platforms/0.0.6/source.json HTTP/1.1
E..L..@.@..^..Q(
        m..r.P.....vz.P...u...GET /bazel-central-registry-mirror/protobuf-patch-180/modules/platforms/0.0.6/source.json HTTP/1.1
Accept: text/html, image/gif, image/jpeg, */*
User-Agent: Bazel/release 6.2.1
Authorization: Basic anVuazpqdW5r
Accept-Encoding: gzip
Host: bazel.corp.lucid.lcl
Connection: keep-alive
```

**Comment by Wyverald** [comment] 2023-07-11 20:54
dupe of https://github.com/bazelbuild/bazel/issues/13709 (once that's fixed, this will automatically get fixed)

**Closed by Wyverald** 2023-07-11 20:54 UTC
Labels: type: bug, team-ExternalDeps, untriaged, area-Bzlmod

**Comment by daniel-eiland** [comment] 2023-07-12 03:39
bzlmod is not usable with private repos until this is fixed.

**Comment by Wyverald** [comment] 2023-07-12 20:26
As a stop-gap, you could try the `NETRC` environment variable, or using the `--credential_helper` flag. See the integration test at https://github.com/bazelbuild/bazel/blob/62799ed724391ef3cd792fae0d81910c06daf245/src/test/py/bazel/bzlmod/bzlmod_credentials_test.py#L135
