### ISSUE TITLE
bash auto-completion error when expanding targets in package

### ISSUE THREAD

**Issue by immars** [bazelbuild/bazel#9981] opened 2019-10-10 08:46 UTC
when expanding targets in package after typing `:` in command line:
```
$ bazel build //stage3/main:<tab>
```
auto-completion will find rules in `stage3/main/BUILD`: `hello-greet` and `hello-world`, resulting next command line as:
```
$ bazel build //stage3/main:<tab>
hello-greet   hello-world
$ bazel build hello-
```
note that the absolute path part `//stage3/main:` is erased, leaving command line in illegal state and further `<tab>` invalid, which is very annoying.

After some digging, I found that change the following line:
 
https://github.com/bazelbuild/bazel/blob/50050ae4f4f88877241ebac4f515b487fda86f67/scripts/bazel-complete-template.bash#L232

into:

```
       echo "$result" | tr " " "\n" | awk -v cur="$package_name" '{print cur":"$0;}' | sed 's|$| |'
```

would solve the problem.

I am not sure whether it is the right solution?

thanks,

**Comment by immars** [comment] 2019-10-12 02:30
under macosx 10.15 catalina, bazel 1.0.0rc3

**Comment by immars** [comment] 2019-10-12 11:03
ubuntu 16.04 also

**Comment by katre** [comment] 2020-05-04 13:33
I can't reproduce this on my machine (based on Debian testing).

Can you provide more details such as an actual build file and the versions of bash you are using?

**Comment by katre** [comment] 2020-05-04 13:38
I see you've addressed this on the PR, apologies.

**Comment by philwo** [comment] 2020-12-09 13:18
Closing, because the associated PR was also closed.

**Closed** 2020-12-09 13:18 UTC
Labels: team-XProduct, untriaged
