### ISSUE TITLE
C++ bazel defines extra DEBUG preprocessor symbol

### ISSUE THREAD

**Issue by na-ka-na** [bazelbuild/bazel#3513] opened 2017-08-06 21:11 UTC
### Description of the problem / feature request / question:
```
$ bazel build :main
INFO: Found 1 target...
ERROR: /private/tmp/xx/BUILD:2:1: C++ compilation of rule '//:main' failed (Exit 1).
a.cc:3:3: error: expected identifier
  DEBUG=2,
  ^
<command line>:2:15: note: expanded from here
#define DEBUG 1
              ^
1 error generated.
Target //:main failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 0.237s, Critical Path: 0.09s
```

### If possible, provide a minimal example to reproduce the problem:
BUILD file:
```
cc_binary(
  name="main",
  srcs=["a.cc"],
)
```
a.cc file:
```
enum A {
  DEBUG=2,
};

int main() {
  return 0;
}
```

### Environment info
* Operating System:
Mac OS X

* Bazel version (output of `bazel info release`):
```
Build label: 0.5.3-homebrew
Build target: bazel-out/darwin_x86_64-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Thu Jul 27 19:30:37 2017 (1501183837)
Build timestamp: 1501183837
Build timestamp as int: 1501183837
```

###  Have you found anything relevant by searching the web?
Only found another such bug report: https://github.com/koth/kcws/issues/66

### Anything else, information or logs or outputs that would be helpful?
```g++ a.cc``` works fine

**Comment by na-ka-na** [comment] 2017-08-16 04:24
Any update on this?

**Comment by mhlopko** [comment] 2017-08-16 09:26
Not yet, sorry. I'll try to investigate this or next week.

**Comment by mhlopko** [comment] 2017-08-18 09:10
Ok, update, we really do pass -DDEBUG in fastbuild (https://github.com/bazelbuild/bazel/blob/master/tools/osx/crosstool/CROSSTOOL.tpl#L130). 

Workaround is to build in opt mode (pass -c opt to the bazel invocation), or use different name :)

@c-parsons is -DDEBUG needed in bazel osx crosstool?

**Comment by c-parsons** [comment] 2017-08-21 19:21
/shrug, this was included mostly for historic reasons. I don't see any issues (other than possible migration overhead) for changing this.

**Comment by mhlopko** [comment] 2017-08-23 08:25
Ok thanks, I'll try to get rid of it. When I find some cycles to spare (= O(weeks))

**Comment by mhlopko** [comment] 2017-09-07 12:44
So deeper investigation revealed that the DEBUG define is intentional,  Apple system headers check for 
DEBUG, and bazel's fastbuild and dbg modes match to what Apple describes as debug build. So I'll close this as working as intended.

**Closed by mhlopko** 2017-09-07 12:44 UTC
Labels: category: rules > C++, P3, type: bug
