### ISSUE TITLE
rules_closure and rules_scala broken

### ISSUE THREAD

**Issue by mhlopko** [bazelbuild/bazel#5483] opened 2018-06-27 11:35 UTC
Logs:
* rules_closure: https://buildkite.com/bazel/bazel-with-downstream-projects-bazel/builds/321#b0c136db-7c5b-4b18-bcaa-3e7b5901f5c6
* rules_scala: https://buildkite.com/bazel/bazel-with-downstream-projects-bazel/builds/321#e3d26df4-0aa7-481b-bcb0-ad109997f66e

Transitively breaks:
* BUILD_file_generator: https://buildkite.com/bazel/bazel-with-downstream-projects-bazel/builds/321#11dca332-2171-43dd-ad48-b6984fe4a7db
* rules_docker: https://buildkite.com/bazel/bazel-with-downstream-projects-bazel/builds/321#1c839c3b-816f-4554-a943-14736c465a3f

Git bisect found culprit: https://github.com/bazelbuild/bazel/commit/7c49bd9c73385db84e678469aa7e6a5bb801c28a

**Comment by mhlopko** [comment] 2018-06-27 11:36
CC @lberki

**Comment by mhlopko** [comment] 2018-06-27 12:35
Rules_kotlin affected as well: https://buildkite.com/bazel/bazel-with-downstream-projects-bazel/builds/321#066d88a1-5db6-4cbe-81bf-11ca7f9a8f71

**Comment by cushon** [comment] 2018-06-27 18:31
I think the `rules_closure` issue will be fixed by bazelbuild/rules_closure#276, can someone merge that one?

**Comment by cushon** [comment] 2018-06-27 19:06
I opened bazelbuild/rules_scala#545 for `rules_scala`.

**Comment by cushon** [comment] 2018-06-27 20:52
`rules_kotlin` doesn't appear to work with JDK 9 `--host_javabase`s. It's not obvious to me what the problem is, I filed: bazelbuild/rules_kotlin#81

**Comment by cushon** [comment] 2018-06-27 22:15
Update: bazelbuild/rules_scala#545 is merged, bazelbuild/rules_kotlin#81 is being investigated.

CC @dslomov can you help review bazelbuild/rules_closure#276?

**Comment by hsyed** [comment] 2018-06-29 04:42
I've fixed it. @buchgr would it be possible to get the CI system to run the tests with 1.8 and 1.9 as the host_javabase  ?  It would be ok if it ran on just one platform.

**Comment by cushon** [comment] 2018-06-29 17:04
@dslomov and @mhlopko thanks for reviewing bazelbuild/rules_closure#276, can you merge the PR?

**Comment by mhlopko** [comment] 2018-07-03 14:30
Already closed. Can I close this issue?

**Comment by hsyed** [comment] 2018-07-03 15:19
@mhlopko Waiting on a reply from @buchgr on testing with a 1.8 and 1.9 host javabase. I can see myself eventually regressing the kotlin rules.

**Comment by buchgr** [comment] 2018-07-03 17:47
So the embedded JDK is 1.9 and the installed JDK is 1.8 on the CI machines. So you should be able to configure this yourself in the .yml file?

**Comment by lfpino** [comment] 2018-07-04 14:53
Hi @cushon Bazel sheriff here, I'm still seeing failures for all the projects @mhlopko mentioned in the first comment: https://buildkite.com/bazel/bazel-with-downstream-projects-bazel/builds/330

Example: https://buildkite.com/bazel/bazel-with-downstream-projects-bazel/builds/330#cf73d6ae-6ba4-4cc6-b54a-64890ec0c115

When should we expect this to be fixed?

**Comment by cushon** [comment] 2018-07-04 18:12
@lfpino the rules_closure, rules_scala, and rules_kotlin results from that run are now green except on macs, where they're all failing with `reference repository '/usr/local/var/bazelbuild' is not a local repository`. There are a bunch of other mac failures with the same error, I don't think that's related to my change.

There are a couple of failures in projects downtream of rules_scala (BUILD_file_generator, rules_docker) that probably need to be updated to version of rules_scala that includes the fix.

**Comment by cushon** [comment] 2018-07-04 19:40
I opened bazelbuild/BUILD_file_generator#37 for BUILD_file_generator.

**Comment by cushon** [comment] 2018-07-04 19:45
And bazelbuild/rules_docker#444 for rules_docker.

**Comment by cushon** [comment] 2018-07-06 18:42
I think all known issues are now fixed. @lfpino can you confirm?

**Comment by lfpino** [comment] 2018-07-06 19:09
They're green now https://buildkite.com/bazel/bazel-with-downstream-projects-bazel/builds/334. Thanks @cushon !

**Closed** 2018-07-06 19:31 UTC
Labels: P1, breakage, category: misc > release / binary, type: bug
