### ISSUE TITLE
android_binary rules add undesired contents to assets/ in APK from new_http_archive rules

### ISSUE THREAD

**Issue by andrewharp** [bazelbuild/bazel#2334] opened 2017-01-04 18:02 UTC
Please provide the following information. The more we know about your system and use case, the more easily and likely we can help.

### Description of the problem / feature request / question:

In the Jenkins build of the Android TensorFlow demo, bazel packages the zip file of the archive and all associated meta-data files, resulting in an unnecessarily doubled APK size.

### If possible, provide a minimal example to reproduce the problem:

See [tensorflow_demo.apk](https://ci.tensorflow.org/view/Nightly/job/nightly-matrix-android/lastBuild/TF_BUILD_CONTAINER_TYPE=ANDROID,TF_BUILD_IS_OPT=OPT,TF_BUILD_IS_PIP=NO_PIP,TF_BUILD_PYTHON_VERSION=PYTHON2,label=android-slave/artifact/bazel-out/local_linux/bin/tensorflow/examples/android/tensorflow_demo.apk), which is the product of the [tensorflow_demo](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/examples/android/BUILD#L58) target.

The contents of the APK are:
```
    2916  Defl:N      937  68% 1980-01-01 00:00 075e74b7  AndroidManifest.xml
     222  Defl:N      149  33% 1980-01-01 00:00 8290b9ff  assets/BUILD
   11416  Defl:N     3976  65% 1980-01-01 00:00 c04c6f58  assets/LICENSE
     116  Stored      116   0% 1980-01-01 00:00 4de3ccdd  assets/WORKSPACE
   10492  Defl:N     5309  49% 1980-01-01 00:00 bdb9b97a  assets/imagenet_comp_graph_label_strings.txt
49937555  Stored 49937555   0% 1980-01-01 00:00 505f473d  assets/inception5h.zip
16632356  Stored 16632356   0% 1980-01-01 00:00 df9f36c1  assets/mobile_multibox_v1.zip
   39200  Defl:N     2640  93% 1980-01-01 00:00 9d2814fd  assets/multibox_location_priors.pb
18556306  Defl:N 16631228  10% 1980-01-01 00:00 cdeb207e  assets/multibox_model.pb
53884595  Stored 53884595   0% 1980-01-01 00:00 6d3b8d15  assets/tensorflow_inception_graph.pb
     583  Stored      583   0% 1980-01-01 00:00 8e9102d0  res/drawable-hdpi-v4/ic_action_info.png
    3845  Stored     3845   0% 1980-01-01 00:00 b7f22d8f  res/drawable-hdpi-v4/ic_launcher.png
     234  Stored      234   0% 1980-01-01 00:00 c560f719  res/drawable-hdpi-v4/tile.9.png
     395  Stored      395   0% 1980-01-01 00:00 6d1da940  res/drawable-mdpi-v4/ic_action_info.png
    2067  Stored     2067   0% 1980-01-01 00:00 5c911979  res/drawable-mdpi-v4/ic_launcher.png
     728  Stored      728   0% 1980-01-01 00:00 9be31f46  res/drawable-xhdpi-v4/ic_action_info.png
    5855  Stored     5855   0% 1980-01-01 00:00 284931e6  res/drawable-xhdpi-v4/ic_launcher.png
    1129  Stored     1129   0% 1980-01-01 00:00 02df764b  res/drawable-xxhdpi-v4/ic_action_info.png
   10714  Stored    10714   0% 1980-01-01 00:00 fcef8ddf  res/drawable-xxhdpi-v4/ic_launcher.png
     404  Defl:N      228  44% 1980-01-01 00:00 97e57137  res/layout/activity_camera.xml
     960  Defl:N      395  59% 1980-01-01 00:00 0df7a886  res/layout/camera_connection_fragment.xml
     664  Defl:N      307  54% 1980-01-01 00:00 866c3a0a  res/layout/camera_connection_fragment_tracking.xml
    4736  Stored     4736   0% 1980-01-01 00:00 4d4cff2b  resources.arsc
   72436  Defl:N    34186  53% 1980-01-01 00:00 873de08d  classes.dex
15465128  Defl:N  4498717  71% 1980-01-01 00:00 ea51eac2  lib/x86_64/libtensorflow_demo.so
13227592  Defl:N  4280397  68% 1980-01-01 00:00 1d1f2e6c  lib/armeabi-v7a/libtensorflow_demo.so
    2808  Defl:N     1371  51% 1980-01-01 00:00 f7285878  META-INF/CERT.SF
    1211  Defl:N     1061  12% 1980-01-01 00:00 1b845b42  META-INF/CERT.RSA
    2736  Defl:N     1329  51% 1980-01-01 00:00 2e9f2f41  META-INF/MANIFEST.MF
```

WORKSPACE, LICENSE, BUILD, and the .zip files are not intended to be included, and are not referred to by the [models.BUILD](https://github.com/tensorflow/tensorflow/blob/master/models.BUILD) file that our [WORKSPACE](https://github.com/tensorflow/tensorflow/blob/master/WORKSPACE#L25) uses for the new_http_archive targets.

I have not been able to reproduce this locally, where things work correctly.

### Environment info
* Operating System:

Linux

* Bazel version (output of `bazel info release`):

0.4.2

* If `bazel info release` returns "development version" or "(@non-git)", please tell us what source tree you compiled Bazel from; git commit hash is appreciated (`git rev-parse HEAD`):

Our bazel comes from https://github.com/bazelbuild/bazel/releases/download/0.4.2/bazel-0.4.2-installer-linux-x86_64.sh and is installed via [this script](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/ci_build/install/install_bazel.sh).

###  Have you found anything relevant by searching the web? (e.g. GitHub issues, email threads in the [bazel-discuss@googlegroups.com](https://groups.google.com/forum/#!forum/bazel-discuss) archive)

Nothing turned up in searches.

### Anything else, information or logs or outputs that would be helpful?
(If they are large, please upload as attachment or provide link).

The [log](http://ci.tensorflow.org/view/Nightly/job/nightly-matrix-android/lastBuild/TF_BUILD_CONTAINER_TYPE=ANDROID,TF_BUILD_IS_OPT=OPT,TF_BUILD_IS_PIP=NO_PIP,TF_BUILD_PYTHON_VERSION=PYTHON2,label=android-slave/consoleFull) from the nightly Android build contains:
```
CONFLICT: asset:WORKSPACE is provided with ambiguous priority from:
	external/mobile_multibox/WORKSPACE
	external/inception5h/WORKSPACE
```
Where the WORKSPACE file in the resulting APK is a generated file with the contents:
```
 # DO NOT EDIT: automatically generated WORKSPACE file for new_http_archive rule
workspace(name = "mobile_multibox")
```

**Comment by ahumesky** [comment] 2017-01-05 02:36
Is the jenkins build running on a mac, or does it run bazel without sandboxing?
I also didn't see this on linux, but turning off sandboxing with `--spawn_strategy=standalone` reproduces the problem:

```
  Length      Date    Time    Name
---------  ---------- -----   ----
     2916  1980-01-01 00:00   AndroidManifest.xml
      222  1980-01-01 00:00   assets/BUILD
    11416  1980-01-01 00:00   assets/LICENSE
      116  1980-01-01 00:00   assets/WORKSPACE
    10492  1980-01-01 00:00   assets/imagenet_comp_graph_label_strings.txt
 49937555  1980-01-01 00:00   assets/inception5h.zip
 16632356  1980-01-01 00:00   assets/mobile_multibox_v1.zip
    39200  1980-01-01 00:00   assets/multibox_location_priors.pb
 18556306  1980-01-01 00:00   assets/multibox_model.pb
.
.
.
```

I believe the problem here is that aapt only knows how to take directories, as opposed to lists of specific files, so bazel takes the list of assets files and finds all the directories the assets are in. Then when bazel invokes aapt in the sandbox, it puts only the assets the rule depends on in the sandbox, so aapt sees only the files it should in the directories it's given. But, with sandboxing off, aapt sees all the files in those directories, even the files the rule doesn't depend on.

**Comment by andrewharp** [comment] 2017-01-05 02:44
It's Linux, and apparently doesn't support sandboxing.

This section from the build log also seems relevant:
```
INFO: Reading 'startup' options from /var/lib/jenkins/workspace/nightly-matrix-android/TF_BUILD_CONTAINER_TYPE/ANDROID/TF_BUILD_IS_OPT/OPT/TF_BUILD_IS_PIP/NO_PIP/TF_BUILD_PYTHON_VERSION/PYTHON2/label/android-slave/bazel-ci_build-cache/.bazelrc: --batch
TF_BUILD_INFO = {container_type: "android", command: "/tmp/tf_build.sh", source_HEAD: "7c36309c37b04843030664cdc64aca2bb7d6ecaa", source_remote_origin: "https://github.com/tensorflow/tensorflow.git", OS: "Linux", kernel: "4.4.0-28-generic", architecture: "x86_64", processor: "Intel(R) Xeon(R) CPU @ 2.50GHz", processor_count: "16", memory_total: "30881892 kB", swap_total: "0 kB", Bazel_version: "Build label: 0.4.2", Java_version: "1.8.0_111", Python_version: "2.7.6", gpp_version: "g++ (Ubuntu 4.8.4-2ubuntu1~14.04.3) 4.8.4", swig_version: "", NVIDIA_driver_version: "", CUDA_device_count: "0", CUDA_device_names: "", CUDA_toolkit_version: ""}
INFO: Reading 'startup' options from /var/lib/jenkins/workspace/nightly-matrix-android/TF_BUILD_CONTAINER_TYPE/ANDROID/TF_BUILD_IS_OPT/OPT/TF_BUILD_IS_PIP/NO_PIP/TF_BUILD_PYTHON_VERSION/PYTHON2/label/android-slave/bazel-ci_build-cache/.bazelrc: --batch
WARNING: Sandboxed execution is not supported on your system and thus hermeticity of actions cannot be guaranteed. See http://bazel.build/docs/bazel-user-manual.html#sandboxing for more information. You can turn off this warning via --ignore_unsupported_sandboxing.
```

**Comment by andrewharp** [comment] 2017-01-05 02:51
Ok, if I run locally with --spawn_strategy=standalone I can reproduce the problem myself. Any idea why our Jenkins build might not support sandboxing?

@yifeif @gunan

**Comment by aj-michael** [comment] 2017-11-15 15:06
Closing this since the bug was just due to lack of sandboxing. The Bazel Android rules are known to not be hermetic without sandboxing due to limitations of tools that only accept directories as inputs. Without sandboxing, other things end up in the same directories and get consumed by tools that shouldn't have access to them.

**Closed by aj-michael** 2017-11-15 15:06 UTC
Labels: category: rules > android, category: sandboxing, type: bug
