### ISSUE TITLE
cc_test data is not copied to .runfiles on windows

### ISSUE THREAD

**Issue by ahippler** [bazelbuild/bazel#4102] opened 2017-11-16 17:21 UTC
### Description of the problem / feature request / question:

I need test data for an cc_test. i added a filegroup to data of the test. the test is execute, the MANIFEST file is created with references to the test data. However the test data is not linked/copied in to the .runfiles directory. And I also tested the exact same cc_test on Mac and Linux, everything works as expected. 

### If possible, provide a minimal example to reproduce the problem:
```
cc_test(
    name = "test",
    srcs = glob([
        "src/**/*.cpp",
        "src/**/*.h",
    ]),
    data = glob([
        "**/*.xml"
    ]),
)
```

### Environment info
* Operating System:
Windows10

* Bazel version (output of `bazel info release`):
0.7.0

**Comment by laszlocsomor** [comment] 2019-07-11 14:22
This is a duplicate of https://github.com/bazelbuild/bazel/issues/8843.
See that bug for solution.

**Closed by laszlocsomor** 2019-07-11 14:22 UTC
Labels: P2, team-Rules-CPP, type: bug
