### ISSUE TITLE
Compile from source failed on redhat 

### ISSUE THREAD

**Issue by panfengli** [bazelbuild/bazel#3392] opened 2017-07-15 18:07 UTC
```
[pfli@flux-login1 bazel]$ bash compile.sh 
INFO: You can skip this first step by providing a path to the bazel binary as second argument:
INFO:    compile.sh compile /path/to/bazel
🍃  Building Bazel from scratch.
......
🍃  Building Bazel with Bazel.
.WARNING: /tmp/bazel_ZbFMPgec/out/external/bazel_tools/WORKSPACE:1: Workspace name in /tmp/bazel_ZbFMPgec/out/external/bazel_tools/WORKSPACE (@io_bazel) does not match the name given in the repository's definition (@bazel_tools); this will cause a build error in future versions.
WARNING: /home/pfli/libraries/bazel/tools/build_defs/docker/docker.bzl:19:1: The docker_{build,bundle} rules bundled with Bazel are deprecated in favor of:
https://github.com/bazelbuild/rules_docker. Please change BUILD loads to reference: @io_bazel_rules_docker//docker:docker.bzl and add the following to your WORKSPACE:
git_repository(
    name = "io_bazel_rules_docker",
    remote = "https://github.com/bazelbuild/rules_docker.git",
    commit = "...",
)
load("@io_bazel_rules_docker//docker:docker.bzl", "docker_repositories")
docker_repositories().
INFO: Found 1 target...
INFO: From Compiling src/main/cpp/blaze_util_posix.cc:
src/main/cpp/blaze_util_posix.cc: In function 'void blaze::Daemonize(const char*)':
src/main/cpp/blaze_util_posix.cc:217:28: warning: ignoring return value of 'int dup(int)', declared with attribute warn_unused_result [-Wunused-result]
   (void) dup(STDOUT_FILENO);  // stderr (2>&1)
                            ^
src/main/cpp/blaze_util_posix.cc: In function 'void blaze::DieAfterFork(const char*)':
src/main/cpp/blaze_util_posix.cc:264:49: warning: ignoring return value of 'ssize_t write(int, const void*, size_t)', declared with attribute warn_unused_result [-Wunused-result]
   write(STDERR_FILENO, message, strlen(message));  // strlen should be OK
                                                 ^
src/main/cpp/blaze_util_posix.cc:265:32: warning: ignoring return value of 'ssize_t write(int, const void*, size_t)', declared with attribute warn_unused_result [-Wunused-result]
   write(STDERR_FILENO, ": ", 2);
                                ^
src/main/cpp/blaze_util_posix.cc:266:59: warning: ignoring return value of 'ssize_t write(int, const void*, size_t)', declared with attribute warn_unused_result [-Wunused-result]
   write(STDERR_FILENO, error_string, strlen(error_string));
                                                           ^
src/main/cpp/blaze_util_posix.cc:267:32: warning: ignoring return value of 'ssize_t write(int, const void*, size_t)', declared with attribute warn_unused_result [-Wunused-result]
   write(STDERR_FILENO, "\n", 1);
                                ^
src/main/cpp/blaze_util_posix.cc: In function 'uint64_t blaze::AcquireLock(const string&, bool, bool, blaze::BlazeLock*)':
src/main/cpp/blaze_util_posix.cc:615:30: warning: ignoring return value of 'int ftruncate(int, __off_t)', declared with attribute warn_unused_result [-Wunused-result]
   (void) ftruncate(lockfd, 0);
                              ^
src/main/cpp/blaze_util_posix.cc:620:47: warning: ignoring return value of 'ssize_t write(int, const void*, size_t)', declared with attribute warn_unused_result [-Wunused-result]
   (void) write(lockfd, msg.data(), msg.size());
                                               ^
INFO: From Compiling src/tools/singlejar/input_jar.cc:
src/tools/singlejar/input_jar.cc: In member function 'bool InputJar::Open(const string&)':
src/tools/singlejar/input_jar.cc:86:34: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     if (mapped_file_.offset(ecd) < cen_position) {
                                  ^
src/tools/singlejar/input_jar.cc:97:18: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     if (cen_size > mapped_file_.offset(ecd)) {
                  ^
INFO: From Compiling src/tools/singlejar/combiners.cc:
src/tools/singlejar/combiners.cc: In member function 'virtual bool XmlCombiner::Merge(const CDH*, const LH*)':
src/tools/singlejar/combiners.cc:150:14: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   while (end >= end_tag_.length() && std::isspace(buf[end - 1])) end--;
              ^
In file included from ./src/tools/singlejar/transient_bytes.h:24:0,
                 from ./src/tools/singlejar/combiners.h:21,
                 from src/tools/singlejar/combiners.cc:15:
./src/tools/singlejar/zip_headers.h: In member function 'virtual void* Concatenator::OutputEntry(bool)':
./src/tools/singlejar/zip_headers.h:143:51: warning: array subscript is above array bounds [-Warray-bounds]
   void attr64(int index, uint64_t v) { attr_[index] = htole64(v); }
                                                   ^
INFO: From Compiling src/tools/singlejar/output_jar.cc:
src/tools/singlejar/output_jar.cc: In member function 'int OutputJar::Doit(Options*)':
src/tools/singlejar/output_jar.cc:238:23: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   for (int ix = 0; ix < options_->input_jars.size(); ++ix) {
                       ^
src/tools/singlejar/output_jar.cc: In member function 'void OutputJar::AppendToDirectoryBuffer(const CDH*, off_t, uint16_t, bool)':
src/tools/singlejar/output_jar.cc:710:43: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     int copy_count = out_zip64_attr_count < zip64_attr_count
                                           ^
src/tools/singlejar/output_jar.cc: In member function 'ssize_t OutputJar::AppendFile(int, off_t, size_t)':
src/tools/singlejar/output_jar.cc:884:24: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   while (total_written < count) {
                        ^
INFO: From JavacBootstrap src/java_tools/buildjar/java/com/google/devtools/build/buildjar/libbootstrap_JarOwner.jar [for host]:
warning: Implicitly compiled files were not subject to annotation processing.
  Use -proc:none to disable annotation processing or -implicit to specify a policy for implicit compilation.
1 warning
INFO: From Generating Java (Immutable) proto_library @googleapis//:google_bytestream_bytestream_proto:
google/bytestream/bytestream.proto: warning: Import google/protobuf/wrappers.proto but not used.
INFO: From Generating external/googleapis/google_watch_v1_java_grpc_srcs.jar:
google/watcher/v1/watch.proto: warning: Import google/protobuf/empty.proto but not used.
INFO: From Generating external/googleapis/google_devtools_build_v1_publish_build_event_java_grpc_srcs.jar:
google/devtools/build/v1/publish_build_event.proto: warning: Import google/protobuf/any.proto but not used.
google/devtools/build/v1/publish_build_event.proto: warning: Import google/api/auth.proto but not used.
INFO: From Generating external/googleapis/google_bytestream_bytestream_java_grpc_srcs.jar:
google/bytestream/bytestream.proto: warning: Import google/protobuf/wrappers.proto but not used.
INFO: From Generating Java (Immutable) proto_library @googleapis//:google_devtools_build_v1_build_status_proto:
google/devtools/build/v1/build_status.proto: warning: Import google/protobuf/any.proto but not used.
INFO: From Generating Java (Immutable) proto_library @googleapis//:google_watch_v1_proto:
google/watcher/v1/watch.proto: warning: Import google/protobuf/empty.proto but not used.
INFO: From Generating Java (Immutable) proto_library @googleapis//:google_devtools_build_v1_publish_build_event_proto:
google/devtools/build/v1/publish_build_event.proto: warning: Import google/protobuf/any.proto but not used.
google/devtools/build/v1/publish_build_event.proto: warning: Import google/api/auth.proto but not used.
INFO: From JavacBootstrap src/java_tools/buildjar/java/com/google/devtools/build/buildjar/libskylark-deps.jar [for host]:
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
INFO: From Executing genrule //src/java_tools/junitrunner/java/com/google/testing/coverage:Jacoco_jarjar:
Jul 15, 2017 1:36:36 PM com.tonicsystems.jarjar.transform.JarTransformer transform
INFO: Transforming archive ZipArchive(/tmp/bazel_ZbFMPgec/out/execroot/io_bazel/bazel-out/local-opt/bin/src/java_tools/junitrunner/java/com/google/testing/coverage/JacocoCoverage_deploy.jar)
ERROR: /home/pfli/libraries/bazel/src/main/java/com/google/devtools/build/lib/BUILD:896:1: Building src/main/java/com/google/devtools/build/lib/libjava-rules.jar (40 source files) failed: Worker process did not return a WorkResponse:

---8<---8<--- Start of log, file at /tmp/bazel_ZbFMPgec/out/bazel-workers/worker-1-Javac.log ---8<---8<---
(empty)
---8<---8<--- End of log ---8<---8<---.
Target //src:bazel failed to build
INFO: Elapsed time: 200.566s, Critical Path: 71.04s

ERROR: Could not build Bazel
```

### Environment info
* Operating System: Red Hat

* Bazel version (output of `bazel info release`): Release 0.5.2, zip file

**Comment by panfengli** [comment] 2017-07-15 18:17
Currently in the BUILD file, it is `load("//tools/build_defs/pkg:pkg.bzl", "pkg_tar")`, should I change it to `load("@io_bazel_rules_docker//docker:docker.bzl", "pkg_tar")`?

**Comment by panfengli** [comment] 2017-07-15 18:20
add the following to your WORKSPACE:
```
git_repository(
    name = "io_bazel_rules_docker",
    remote = "https://github.com/bazelbuild/rules_docker.git",
    commit = "...",
)
load("@io_bazel_rules_docker//docker:docker.bzl", "docker_repositories")
docker_repositories()
```
Should I add them in the begining? Or after 
```
# For tools/cpp/test/...
load("//tools/cpp/test:docker_repository.bzl", "docker_repository")

docker_repository()
```

**Comment by panfengli** [comment] 2017-07-15 18:24
After I changed the WORKSPACE and BUILD file, it comes as
```
java.lang.RuntimeException: Unrecoverable error while evaluating node 'REPOSITORY_DIRECTORY:@io_bazel_rules_docker' (requested by nodes 'REPOSITORY:@io_bazel_rules_docker')
	at com.google.devtools.build.skyframe.ParallelEvaluator$Evaluate.run(ParallelEvaluator.java:474)
	at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:357)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.eclipse.jgit.errors.RevisionSyntaxException:...
	at org.eclipse.jgit.lib.Repository.resolve(Repository.java:700)
	at org.eclipse.jgit.lib.Repository.resolve(Repository.java:383)
	at org.eclipse.jgit.api.CreateBranchCommand.getStartPointObjectId(CreateBranchCommand.java:280)
	at org.eclipse.jgit.api.CreateBranchCommand.call(CreateBranchCommand.java:135)
	at org.eclipse.jgit.api.CheckoutCommand.call(CheckoutCommand.java:220)
	at com.google.devtools.build.lib.bazel.repository.GitCloner.clone(GitCloner.java:198)
	at com.google.devtools.build.lib.bazel.repository.GitRepositoryFunction.fetch(GitRepositoryFunction.java:54)
	at com.google.devtools.build.lib.rules.repository.RepositoryDelegatorFunction.compute(RepositoryDelegatorFunction.java:187)
	at com.google.devtools.build.skyframe.ParallelEvaluator$Evaluate.run(ParallelEvaluator.java:400)
	... 4 more
java.lang.RuntimeException: Unrecoverable error while evaluating node 'REPOSITORY_DIRECTORY:@io_bazel_rules_docker' (requested by nodes 'REPOSITORY:@io_bazel_rules_docker')
	at com.google.devtools.build.skyframe.ParallelEvaluator$Evaluate.run(ParallelEvaluator.java:474)
	at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:357)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.eclipse.jgit.errors.RevisionSyntaxException:...
	at org.eclipse.jgit.lib.Repository.resolve(Repository.java:700)
	at org.eclipse.jgit.lib.Repository.resolve(Repository.java:383)
	at org.eclipse.jgit.api.CreateBranchCommand.getStartPointObjectId(CreateBranchCommand.java:280)
	at org.eclipse.jgit.api.CreateBranchCommand.call(CreateBranchCommand.java:135)
	at org.eclipse.jgit.api.CheckoutCommand.call(CheckoutCommand.java:220)
	at com.google.devtools.build.lib.bazel.repository.GitCloner.clone(GitCloner.java:198)
	at com.google.devtools.build.lib.bazel.repository.GitRepositoryFunction.fetch(GitRepositoryFunction.java:54)
	at com.google.devtools.build.lib.rules.repository.RepositoryDelegatorFunction.compute(RepositoryDelegatorFunction.java:187)
	at com.google.devtools.build.skyframe.ParallelEvaluator$Evaluate.run(ParallelEvaluator.java:400)
	... 4 more

ERROR: Could not build Bazel
```

**Comment by panfengli** [comment] 2017-07-15 18:41
I just changed all things to the original ones, and it turns out right.

```
[pfli@flux-login1 bazel]$ bash compile.sh 
INFO: You can skip this first step by providing a path to the bazel binary as second argument:
INFO:    compile.sh compile /path/to/bazel
🍃  Building Bazel from scratch..
.....
🍃  Building Bazel with Bazel.
.WARNING: /tmp/bazel_hANM1naZ/out/external/bazel_tools/WORKSPACE:1: Workspace name in /tmp/bazel_hANM1naZ/out/external/bazel_tools/WORKSPACE (@io_bazel) does not match the name given in the repository's definition (@bazel_tools); this will cause a build error in future versions.
WARNING: /home/pfli/libraries/bazel/tools/build_defs/docker/docker.bzl:19:1: The docker_{build,bundle} rules bundled with Bazel are deprecated in favor of:
https://github.com/bazelbuild/rules_docker. Please change BUILD loads to reference: @io_bazel_rules_docker//docker:docker.bzl and add the following to your WORKSPACE:
git_repository(
    name = "io_bazel_rules_docker",
    remote = "https://github.com/bazelbuild/rules_docker.git",
    commit = "...",
)
load("@io_bazel_rules_docker//docker:docker.bzl", "docker_repositories")
docker_repositories().
INFO: Found 1 target...
INFO: From Compiling src/main/cpp/blaze_util_posix.cc:
src/main/cpp/blaze_util_posix.cc: In function 'void blaze::Daemonize(const char*)':
src/main/cpp/blaze_util_posix.cc:217:28: warning: ignoring return value of 'int dup(int)', declared with attribute warn_unused_result [-Wunused-result]
   (void) dup(STDOUT_FILENO);  // stderr (2>&1)
                            ^
src/main/cpp/blaze_util_posix.cc: In function 'void blaze::DieAfterFork(const char*)':
src/main/cpp/blaze_util_posix.cc:264:49: warning: ignoring return value of 'ssize_t write(int, const void*, size_t)', declared with attribute warn_unused_result [-Wunused-result]
   write(STDERR_FILENO, message, strlen(message));  // strlen should be OK
                                                 ^
src/main/cpp/blaze_util_posix.cc:265:32: warning: ignoring return value of 'ssize_t write(int, const void*, size_t)', declared with attribute warn_unused_result [-Wunused-result]
   write(STDERR_FILENO, ": ", 2);
                                ^
src/main/cpp/blaze_util_posix.cc:266:59: warning: ignoring return value of 'ssize_t write(int, const void*, size_t)', declared with attribute warn_unused_result [-Wunused-result]
   write(STDERR_FILENO, error_string, strlen(error_string));
                                                           ^
src/main/cpp/blaze_util_posix.cc:267:32: warning: ignoring return value of 'ssize_t write(int, const void*, size_t)', declared with attribute warn_unused_result [-Wunused-result]
   write(STDERR_FILENO, "\n", 1);
                                ^
src/main/cpp/blaze_util_posix.cc: In function 'uint64_t blaze::AcquireLock(const string&, bool, bool, blaze::BlazeLock*)':
src/main/cpp/blaze_util_posix.cc:615:30: warning: ignoring return value of 'int ftruncate(int, __off_t)', declared with attribute warn_unused_result [-Wunused-result]
   (void) ftruncate(lockfd, 0);
                              ^
src/main/cpp/blaze_util_posix.cc:620:47: warning: ignoring return value of 'ssize_t write(int, const void*, size_t)', declared with attribute warn_unused_result [-Wunused-result]
   (void) write(lockfd, msg.data(), msg.size());
                                               ^
INFO: From Compiling src/tools/singlejar/input_jar.cc:
src/tools/singlejar/input_jar.cc: In member function 'bool InputJar::Open(const string&)':
src/tools/singlejar/input_jar.cc:86:36: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     if (mapped_file_.offset(ecd) < cen_position) {
                                    ^
src/tools/singlejar/input_jar.cc:97:43: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     if (cen_size > mapped_file_.offset(ecd)) {
                                           ^
INFO: From Generating external/googleapis/google_bytestream_bytestream_java_grpc_srcs.jar:
google/bytestream/bytestream.proto: warning: Import google/protobuf/wrappers.proto but not used.
INFO: From Generating external/googleapis/google_devtools_build_v1_publish_build_event_java_grpc_srcs.jar:
google/devtools/build/v1/publish_build_event.proto: warning: Import google/api/auth.proto but not used.
google/devtools/build/v1/publish_build_event.proto: warning: Import google/protobuf/any.proto but not used.
INFO: From Generating external/googleapis/google_watch_v1_java_grpc_srcs.jar:
google/watcher/v1/watch.proto: warning: Import google/protobuf/empty.proto but not used.
INFO: From Compiling src/tools/singlejar/combiners.cc:
src/tools/singlejar/combiners.cc: In member function 'virtual bool XmlCombiner::Merge(const CDH*, const LH*)':
src/tools/singlejar/combiners.cc:150:33: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   while (end >= end_tag_.length() && std::isspace(buf[end - 1])) end--;
                                 ^
In file included from ./src/tools/singlejar/transient_bytes.h:24:0,
                 from ./src/tools/singlejar/combiners.h:21,
                 from src/tools/singlejar/combiners.cc:15:
./src/tools/singlejar/zip_headers.h: In member function 'virtual void* Concatenator::OutputEntry(bool)':
./src/tools/singlejar/zip_headers.h:143:51: warning: array subscript is above array bounds [-Warray-bounds]
   void attr64(int index, uint64_t v) { attr_[index] = htole64(v); }
                                                   ^
INFO: From Generating Java (Immutable) proto_library @googleapis//:google_bytestream_bytestream_proto:
google/bytestream/bytestream.proto: warning: Import google/protobuf/wrappers.proto but not used.
INFO: From Generating Java (Immutable) proto_library @googleapis//:google_devtools_build_v1_build_status_proto:
google/devtools/build/v1/build_status.proto: warning: Import google/protobuf/any.proto but not used.
INFO: From Generating Java (Immutable) proto_library @googleapis//:google_devtools_build_v1_publish_build_event_proto:
google/devtools/build/v1/publish_build_event.proto: warning: Import google/api/auth.proto but not used.
google/devtools/build/v1/publish_build_event.proto: warning: Import google/protobuf/any.proto but not used.
INFO: From Generating Java (Immutable) proto_library @googleapis//:google_watch_v1_proto:
google/watcher/v1/watch.proto: warning: Import google/protobuf/empty.proto but not used.
INFO: From Compiling src/tools/singlejar/output_jar.cc:
src/tools/singlejar/output_jar.cc: In member function 'int OutputJar::Doit(Options*)':
src/tools/singlejar/output_jar.cc:238:51: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   for (int ix = 0; ix < options_->input_jars.size(); ++ix) {
                                                   ^
src/tools/singlejar/output_jar.cc: In member function 'void OutputJar::AppendToDirectoryBuffer(const CDH*, off_t, uint16_t, bool)':
src/tools/singlejar/output_jar.cc:710:45: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     int copy_count = out_zip64_attr_count < zip64_attr_count
                                             ^
src/tools/singlejar/output_jar.cc: In member function 'ssize_t OutputJar::AppendFile(int, off_t, size_t)':
src/tools/singlejar/output_jar.cc:884:26: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   while (total_written < count) {
                          ^
INFO: From JavacBootstrap src/java_tools/buildjar/java/com/google/devtools/build/buildjar/libbootstrap_JarOwner.jar [for host]:
warning: Implicitly compiled files were not subject to annotation processing.
  Use -proc:none to disable annotation processing or -implicit to specify a policy for implicit compilation.
1 warning
INFO: From JavacBootstrap src/java_tools/buildjar/java/com/google/devtools/build/buildjar/libskylark-deps.jar [for host]:
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
INFO: From Executing genrule //src/java_tools/junitrunner/java/com/google/testing/coverage:Jacoco_jarjar:
Jul 15, 2017 2:36:48 PM com.tonicsystems.jarjar.transform.JarTransformer transform
INFO: Transforming archive ZipArchive(/tmp/bazel_hANM1naZ/out/execroot/io_bazel/bazel-out/local-opt/bin/src/java_tools/junitrunner/java/com/google/testing/coverage/JacocoCoverage_deploy.jar)
Target //src:bazel up-to-date:
  bazel-bin/src/bazel
INFO: Elapsed time: 216.906s, Critical Path: 112.74s
WARNING: /tmp/bazel_hANM1naZ/out/external/bazel_tools/WORKSPACE:1: Workspace name in /tmp/bazel_hANM1naZ/out/external/bazel_tools/WORKSPACE (@io_bazel) does not match the name given in the repository's definition (@bazel_tools); this will cause a build error in future versions.

Build successful! Binary is here: /home/pfli/libraries/bazel/output/bazel
```
Unknown reason.

**Comment by aehlig** [comment] 2017-07-18 06:22
So, did I understand correctly that the problem disappeared by itself, and we don't have a reproduction case? If so, we probably have to close the issue.

Adding @philwo, as the first message is worker-related.

**Comment by philwo** [comment] 2017-07-18 14:11
@panfengli Which version of Red Hat are you using?

Regarding the worker failure, unfortunately there's nothing in the logs that would help with debugging. I don't think we can do anything about it if it's not reproducible.

**Comment by panfengli** [comment] 2017-07-18 16:03
@philwo Yeah, the version is
```
Linux version 3.10.0-327.36.3.el7.x86_64 (builder@kbuilder.dev.centos.org) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-4) (GCC) )
```
This error is reproducible I think. I just download the latest zip file and unzip it then run the `compile.sh`, it shows the same error.

**Comment by mhlopko** [comment] 2017-10-10 15:38
Is this still reproducible? I seem to remember reading about some fine folks building bazel on redhat without issues.

**Comment by katre** [comment] 2017-10-31 19:51
Closing this due to the lack of updates. Please re-file the issue if it happens further.

**Closed by katre** 2017-10-31 19:51 UTC
Labels: On hold: more data needed

**Comment by rlrahulkanojia** [comment] 2020-02-26 20:18
INFO: From Building Java resource jar:
OpenJDK Client VM warning: TieredCompilation is disabled in this release.
ERROR: /home/pi/tf/bazel/src/main/protobuf/BUILD:24:2: Building src/main/protobuf/libextra_actions_base_java_proto.jar (1 source jar) failed: Worker process sent response with exit code: 1.
java.lang.InternalError: Cannot find requested resource bundle for locale en_US
	at com.sun.tools.javac.util.JavacMessages.getBundles(JavacMessages.java:128)
	at com.sun.tools.javac.util.JavacMessages.getLocalizedString(JavacMessages.java:147)
	at com.sun.tools.javac.util.JavacMessages.getLocalizedString(JavacMessages.java:140)
	at com.sun.tools.javac.util.Log.localize(Log.java:788)
	at com.sun.tools.javac.util.Log.printLines(Log.java:586)
	at com.sun.tools.javac.api.JavacTaskImpl.handleExceptions(JavacTaskImpl.java:170)
	at com.sun.tools.javac.api.JavacTaskImpl.doCall(JavacTaskImpl.java:96)
	at com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:90)
	at com.google.devtools.build.buildjar.javac.BlazeJavacMain.compile(BlazeJavacMain.java:103)
	at com.google.devtools.build.buildjar.SimpleJavaLibraryBuilder$1.invokeJavac(SimpleJavaLibraryBuilder.java:166)
	at com.google.devtools.build.buildjar.ReducedClasspathJavaLibraryBuilder.compileSources(ReducedClasspathJavaLibraryBuilder.java:52)
	at com.google.devtools.build.buildjar.SimpleJavaLibraryBuilder.compileJavaLibrary(SimpleJavaLibraryBuilder.java:169)
	at com.google.devtools.build.buildjar.SimpleJavaLibraryBuilder.run(SimpleJavaLibraryBuilder.java:181)
	at com.google.devtools.build.buildjar.BazelJavaBuilder.processRequest(BazelJavaBuilder.java:89)
	at com.google.devtools.build.buildjar.BazelJavaBuilder.runPersistentWorker(BazelJavaBuilder.java:66)
	at com.google.devtools.build.buildjar.BazelJavaBuilder.main(BazelJavaBuilder.java:44)
Caused by: java.util.MissingResourceException: Can't find bundle for base name com.google.errorprone.errors, locale en_US
	at java.util.ResourceBundle.throwMissingResourceException(ResourceBundle.java:1581)
	at java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1396)
	at java.util.ResourceBundle.getBundle(ResourceBundle.java:854)
	at com.sun.tools.javac.util.JavacMessages.lambda$add$0(JavacMessages.java:106)
	at com.sun.tools.javac.util.JavacMessages.getBundles(JavacMessages.java:125)
	... 15 more
Target //src:bazel failed to build
INFO: Elapsed time: 609.901s, Critical Path: 105.15s

ERROR: Could not build Bazel
pi@raspberrypi:~/tf/bazel $

**Comment by katre** [comment] 2020-02-26 20:30
This issue is different than the original issue, and it has been closed for two years. Please open a new issue to track this.

Without a chance to reproduce your problem I can't hazard much of a guess. Your command line makes it look like you are building on a raspberry pi (Are you running a redhat distribution on a raspberry pi?). Support for building bazel on 32-bit processors is poor, unfortunately, but you may be able to find other users on the bazel-discuss mailing list.

So, in order:
1. Please open a new issue.
2. Please fill out all data in the template, including clearly specifying what operating system and CPU architecture you are using.
3. And we will then be very happy to help triage and diagnose your issue.
