### ISSUE TITLE
Add support for .ar and .deb files to repository_ctx

### ISSUE THREAD

**Issue by kjlubick** [bazelbuild/bazel#15130] opened 2022-03-28 13:21 UTC
### Description of the problem / feature request:

I intend to add support for .ar archive files and .deb files (which are the same file format).

### Feature requests: what underlying problem are you trying to solve with this feature?

[download_and_extract](https://docs.bazel.build/versions/main/skylark/lib/repository_ctx.html#download_and_extract) supports many compressed or packaged file formats already. Adding .ar and .deb files will make it easier for toolchains to download and extract .deb files into their sysroot without requiring an external tool.

[Example hermetic toolchain](https://github.com/google/skia/blob/7527f901d1c551ec36e9b09af12707595870f163/toolchain/build_toolchain.bzl#L111) that downloads .deb files and extracts them.

###  Have you found anything relevant by searching the web?

Apache Commons Compress [already has support for .ar files](https://commons.apache.org/proper/commons-compress/apidocs/org/apache/commons/compress/archivers/ar/package-summary.html) and this package is already used by Bazel for [Compressed Tar files](https://github.com/bazelbuild/bazel/blob/45b225d5bdc5a1e2f1414d4a5a27ddf267dc4e15/src/main/java/com/google/devtools/build/lib/bazel/repository/CompressedTarFunction.java#L33) so we shouldn't need any additional third party dependencies.

**Comment by aiuto** [comment] 2022-03-30 14:24
I would like to find a way to do this by making it an external set of repository rules that can have it's own development team. The issue is that most of the core Bazel team never see .deb files. They won't be able to adequately maintain or enhance it.  I;m tied up this week and meteorcloudy@ is out on vacation. We can talk next week.

**Comment by aiuto** [comment] 2022-04-12 02:47
The more I think about it, the more I believe this belongs to a new rule set. That would follow the pattern of jvm_external, where we built new repository rules outside of bazel itself, so they can advance at different rates. Looking at your patch, you will decompress the .deb file, but a fully fleshed out rule could have so much more.  For example, installing a package and then making the libraries and headers available as a .so.

Since I have some  .deb file experience (on the building them side from rules_pkg), I can offer to help on parts of this, but what you need is a place to host it.  Could you create a repository under Skia's control? Then we can point to that as the recommended place for support of .deb install from the workspace.

**Comment by meteorcloudy** [comment] 2022-04-12 09:09
Hey Tony, this features is already implemented in **https://github.com/bazelbuild/bazel/pull/15132**. I don't think this belong to a new rule, just like we are not extracting .zip, .tar files using a ruleset (this is a totally different process as building archive with rule_pkg). This is an enhancement of the functionality in repository_ctx to decompress an archive, then the repository rule can do anything it wants. This works naturally with `http_archive`. 

I'm closing this since the feature has already been merged.

**Closed by meteorcloudy** 2022-04-12 09:09 UTC
Labels: type: feature request, P2, team-ExternalDeps

**Comment by uhthomas** [comment] 2022-06-23 14:39
'.deb' files usually contain additional archives which makes actually extracting information from `.deb` archives with `http_archive` awkward. The repository will end up with `debian_binary`, `control.tar` and `data.tar` files where `data.tar` needs to be extracted _again_ in another repository rule, or BUILD rule if you're feeling adventurous. Is there any way for the `data.tar` to be extracted automatically by `http_archive`?

**Comment by meteorcloudy** [comment] 2022-06-24 08:20
@uhthomas I think it's possible to write a custom starlark repository rule to keep extracting the *.tar files with the [repository_ctx.extract](https://bazel.build/rules/lib/repository_ctx#extract) API. Doing this in http_archive is probably not ideal, because how do you decide when to extract further?
