### ISSUE TITLE
android_sdk_repository set path using environment variable?

### ISSUE THREAD

**Issue by ScottPierce** [bazelbuild/bazel#746] opened 2015-12-29 23:16 UTC
From the tutorial I find the following in the WORKSPACE file:

``` python
# android_sdk_repository(
#     name = "androidsdk",
#     # Set the path to the directory the Android SDK was unzipped into.
#     path = "/path/to/android-sdk",
#     # Set the API level of the installed SDK Platform.
#     api_level = 22,
#     # Set the version of the build tools (a directory inside build-tools)
#     build_tools_version="22.0.1"
# )
```

I can't find any documentation for the `android_sdk_repository`, and I'm also encountering issues specifying the `path` with an environment variable. This is problematic, because developers have their android sdk installed in varying locations on their system, but the `path` variable seems to want an absolute path only, which is a bit problematic. 

Is there a way to maybe include the Android sdk inside the workspace under source control? If not, how would you recommend allowing devs to install the Android SDK where they want?

**Comment by kchodorow** [comment] 2015-12-30 15:07
Including the SDK in the workspace would be the preferred way, if possible.  There is no way to have varying locations in the WORKSPACE file, yet, although @damienmg is working on that.

**Comment by spierce7** [comment] 2015-12-31 00:36
How would I do that though? Every time I try, an error is thrown wanting an absolute path only:

```In android_sdk_repository rule //external:androidsdk the 'path' attribute must specify an absolute path and referenced by '//external:android/sdk'.```

**Comment by kchodorow** [comment] 2016-01-04 14:46
Use:

```
path = __workspace_dir__ + "/android_sdk_folder",
```

**Comment by philwo** [comment] 2016-01-05 15:20
If this works, maybe we can add it to the documentation?

**Comment by menny** [comment] 2016-01-05 18:10
using `__worksapce_dir__` is a workable solution, but it will require all developers in our organization (we have quite a few Android devs) to create a symlink in their workspace which points to the actual SDK path. And do the same for the NDK path.

A much less intrusive solution will be to somehow use the environment variable `ANDROID_HOME`, maybe by introducing a way to read system's environment values? (e.i, `sys_env("ANDROID_HOME)`)

A WORKSPACE/BUILD function that can read environment variables will be beneficial in many use-cases.

**Comment by spierce7** [comment] 2016-01-05 18:45
@menny the proposed solution wouldn't be to create a symlink, but instead, actually make the Android SDK a part of your build, and check it into source control. That way everyone is building off the same Android SDK files, and not having to manage their own Android SDK locally.

**Comment by zergtmn** [comment] 2016-01-05 19:36
@spierce7 I understand that Bazel is aimed at perfectly reproducible builds but that sounds quite unrealistic to store an additional 10+ GBs of files in every repository we have. It'd significantly increase the costs of storing the repositories in the cloud, updating Android SDK would bloat the repositories over time further increasing the costs and every developer in our team would have to upgrade his SSD.
Moreover, both linux and macosx versions would have to be stored in repositories because some devs use Macs.

**Comment by bsilver8192** [comment] 2016-01-05 19:43
What about being able to download the SDK over HTTP? That avoids bloating the repository itself, and allows versioning by changing the filename and keeping old versions around.

**Comment by spierce7** [comment] 2016-01-05 19:46
@zergtmn I don't imagine you'd need to check all android SDK versions and emulator images. You'd only check-in what you need to build the app (The current android SDK, and any other build tools / libraries you depend on from Android). Devs could still use their own private Android SDK repositories to run their emulators.

By only including the Android SDK needed to build that project, and leaving out the emulator system images / other stuff bazel wouldn't use, etc, you'd be checking in something that was very reasonable and manageable.

@bsilver8192 Is that possible? I noticed for other build rules that's how they get things, like j2objc.

**Comment by bsilver8192** [comment] 2016-01-05 19:52
I don't think downloading it over HTTP is possible right now, but I think that's a pretty easy change. I remember seeing code related to that before, but I couldn't figure out how to actually use it.

**Comment by spierce7** [comment] 2016-01-05 19:55
@bsilver8192 Something like http://bazel.io/docs/be/workspace.html#http_file might be able to be used? The trick would then be referencing that file from the `android_sdk_repository` declaration. @kchodorow would something like this be possible?

**Comment by menny** [comment] 2016-01-05 20:02
@spierce7

Given that we (at our company) develop Android on Mac, Linux and Windows, and we using GitHub Enterprise (which is not mono-repo friendly), checking in all the SDK and NDK files for all platforms is not an viable option. 
Also, downloading the SDK+NDK every time the developer `clean`, or clone to a new folder or simply when switching to an earlier branch.
Also, this means that if I participate in multiple projects, I'll have the SDK in multiple locations on my HD. 

Using an environment variable helps reduce much of the points above.

**Comment by spierce7** [comment] 2016-01-05 20:08
Good points. Being able to access an environment variable would be nice.

**Comment by kchodorow** [comment] 2016-01-05 20:11
I'm pretty sure there were licensing issues with downloading the SDK on the fly (because you aren't going through their license agreement first).  android_sdk_repository probably should allow you to specify a label where the SDK can be found, if it doesn't already (I don't know whether it does or not).

Summoning @damienmg, one of his many projects being adding configuration machinery for the WORKSPACE file (i.e., how bazel should find stuff on the local machine).

**Comment by damienmg** [comment] 2016-01-07 10:00
Ok I have passed quickly over that issue:
- Downloading the SDK over HTTP is a no for now because of the Android SDK licensing issue.
- The configuration thingy around the workspace should indeed make possible to create on the fly the android_sdk_repository without hard-coding the path in the workspace file.

**Comment by steven-johnson** [comment] 2016-11-17 19:39
I know this issue is closed, but I have questions/comments...

IIUC, the current best practice for an env-dependent Android SDK/NDK is outlined here; to make it work, you have to manually run the scripts/workspace_user.sh script (and re-run it any time your env var might have changed).

This is a little unsatisfying for the use-case I'm trying to handle: 

I have a git repo that includes a general library (Halide) and sample apps for many platforms (including Android). I need for the repo to be buildable without and Android SDK installed, but I'd like an easy way for clients to opt-in to build them.

If I use this technique, I can accomplish that... but only if I require that the user 
(1) set env vars correctly,
(2) manually run a script to create WORKSPACE.user.bzl
(3) uncomment some lines in her WORKSPACE file to load WORKSPACE.user.bzl 

this is workable but very fiddly. Surely there should be a better way?

Suggestion: if there was a way to conditionally load() a file without failing if it is missing, I could conditionalize the logic in my WORKSPACE to adapt to this, allowing step 3 to be elided entirely.

**Comment by kchodorow** [comment] 2016-11-17 19:54
> Surely there should be a better way?

There is!  Damien is working on a way to declare environment variables as dependencies of an external repository rule (see https://bazel-review.googlesource.com/c/6697/ for the design doc). Then a user will still have to set env vars correctly, but hopefully Bazel can take it from there.

**Comment by steven-johnson** [comment] 2016-11-17 19:59
That's great news! Is there an ETA for what version this might make it into?

**Comment by kchodorow** [comment] 2016-11-17 20:04
I think #1390 is the bug to track, which is scheduled for 0.5.0.

**Comment by damienmg** [comment] 2016-11-17 20:14
Current ETA is mid-december.

**Comment by aj-michael** [comment] 2016-12-09 15:40
Reopening, because the plan is to support reading from $ANDROID_HOME once #1390 is resolved.

**Comment by aj-michael** [comment] 2016-12-12 16:40
@kchodorow , @damienmg , I'm confused. The design doc in that bug appears to only be relevant to Skylark repository rules. `android_sdk_repository` is a native rule.

**Comment by ahumesky** [comment] 2017-01-27 20:26
we can close this out once https://bazel-review.googlesource.com/#/c/8224/ is submitted

**Closed** 2017-02-15 19:20 UTC
Labels: category: rules > android, P2, type: feature request
