### ISSUE TITLE
Bazel failing with VC++ compilers in "C:\Program Files"

### ISSUE THREAD

**Issue by PatrickLang** [bazelbuild/bazel#4496] opened 2018-01-22 08:04 UTC
### Description of the problem / feature request:

The default install of Visual Studio puts the C++ compiler in a subdirectory under "Program Files". When trying to build a project, it fails saying "c:\Program" does not exist:

```none
ERROR: C:/users/patrick/appdata/local/temp/_bazel_patrick/dmhbzmu0/external/go_stdlib_windows_amd64_cgo/BUILD.bazel:4:1: error executing shell command: 'export GOROOT="$(pwd)/bazel-out/x64_windows-fastbuild/bin/external/go_stdlib_windows_amd64_cgo" GOROOT_FINAL="GOROOT" GOOS="windows" GOARCH="amd64" CGO_ENABLED="1" CC="C:/Program Files (x86)/Micros...' failed (Exit 2)
# runtime/cgo
exec: "C:/Program": file does not exist
```

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Prerequisites

1. [Visual Studio 2017 community edition](https://www.visualstudio.com/vs/community/) - easiest way to get MS C++ compiler and SDK
  - Tick the boxes for at least *desktop development with C++*
2. [Chocolatey](https://chocolatey.org/)
3. [Bazel](https://docs.bazel.build/versions/master/install-windows.html)

Surprisingly, Go doesn't need to be preinstalled

## Code used

https://github.com/PatrickLang/iso9660wrap/tree/bazel-manual

be sure to use branch `bazel-manual`

## Build attempt

`bazel build //...`

Fails

```
Extracting Bazel installation...
............
DEBUG: C:/users/patrick/appdata/local/temp/_bazel_patrick/dmhbzmu0/external/bazel_tools/tools/cpp/lib_cc_configure.bzl:37:3:
Auto-Configuration Warning: 'BAZEL_VC' is not set, start looking for the latest Visual C++ installed.
DEBUG: C:/users/patrick/appdata/local/temp/_bazel_patrick/dmhbzmu0/external/bazel_tools/tools/cpp/lib_cc_configure.bzl:37:3:
Auto-Configuration Warning: Looking for VS%VERSION%COMNTOOLS environment variables,eg. VS140COMNTOOLS
DEBUG: C:/users/patrick/appdata/local/temp/_bazel_patrick/dmhbzmu0/external/bazel_tools/tools/cpp/lib_cc_configure.bzl:37:3:
Auto-Configuration Warning: Looking for Visual C++ through registry
DEBUG: C:/users/patrick/appdata/local/temp/_bazel_patrick/dmhbzmu0/external/bazel_tools/tools/cpp/lib_cc_configure.bzl:37:3:
Auto-Configuration Warning: Visual C++ build tools found at C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\\VC
INFO: Analysed 2 targets (167 packages loaded).
INFO: Found 2 targets...
ERROR: C:/users/patrick/appdata/local/temp/_bazel_patrick/dmhbzmu0/external/go_stdlib_windows_amd64_cgo/BUILD.bazel:4:1: error executing shell command: 'export GOROOT="$(pwd)/bazel-out/x64_windows-fastbuild/bin/external/go_stdlib_windows_amd64_cgo" GOROOT_FINAL="GOROOT" GOOS="windows" GOARCH="amd64" CGO_ENABLED="1" CC="C:/Program Files (x86)/Micros...' failed (Exit 2)
# runtime/cgo
exec: "C:/Program": file does not exist
INFO: Elapsed time: 129.897s, Critical Path: 31.18s
FAILED: Build did NOT complete successfully
```

### What operating system are you running Bazel on?

Windows 10 1709 (build 16299)

### What's the output of `bazel info release`?

release 0.9.0

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

https://github.com/PatrickLang/iso9660wrap.git
6129215f4acaa171e394fa3a90c09f71c308c0ac
e580362bc6eec0400f03a15557c42b19c150dc77

###  Have you found anything relevant by searching the web?

No

### Any other information, logs, or outputs that you want to share?

Entire build log from stdout/err is above

**Comment by PatrickLang** [comment] 2018-01-22 08:06
Also of note - this works fine with Bazel 0.9.0 on my Centos 7 VM. Seems to be a windows specific path problem. My best guess is that when paths are passed to msys2-built tools they need " " escaped to "\ "

**Comment by laszlocsomor** [comment] 2018-01-22 13:45
Thanks for filing this bug and especially for the easy repro.
I can also repro this, with Bazel 0.9.0 and 0.10.0rc2.
Let me take a closer look.

**Comment by laszlocsomor** [comment] 2018-01-22 14:48
I don't think this is a Bazel bug, because I can repro it by just running in MSYS the command that failed:

Some setup that the `stdlib` rule performs before the actual failing command:
```
$ cd C:/tmp3/gdswrbqp/execroot/__main__

$ export GOROOT="$(pwd)/bazel-out/x64_windows-fastbuild/bin/external/go_stdlib_windows_amd64_cgo" GOROOT_FINAL="GOROOT" GOOS="windows" GOARCH="amd64" CGO_ENABLED="1" CC="C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/amd64/cl.exe" CXX="C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/amd64/cl.exe" COMPILER_PATH="C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/amd64" CGO_CPPFLAGS="/DCOMPILER_MSVC /DNOMINMAX /D_WIN32_WINNT=0x0600 /D_CRT_SECURE_NO_DEPRECATE /D_CRT_SECURE_NO_WARNINGS /D_SILENCE_STDEXT_HASH_DEPRECATION_WARNINGS /bigobj /Zm500 /J /Gy /GF /EHsc /wd4351 /wd4291 /wd4250 /wd4996" CGO_LDFLAGS="/MACHINE:X64"

$ export PATH="$PATH:$(cd "$COMPILER_PATH" && pwd)"
```

Then the actual failure:
```
$ external/go_sdk/bin/go.exe install -asmflags "-trimpath $(pwd)"  std
# runtime/cgo
exec: "C:/Program": file does not exist
```

**Comment by laszlocsomor** [comment] 2018-01-22 14:56
@PatrickLang , could you please verify the same?
Run your build with the "--verbose_failures" flag, that'll yield something like:

```
C:\work\gh4496>c:\work\bazel-releases\0.10.0\rc2\bazel.exe --output_user_root=c:\tmp3 build //... --verbose_failures
INFO: Analysed 2 targets (43 packages loaded).
INFO: Found 2 targets...
ERROR: C:/tmp3/gdswrbqp/external/go_stdlib_windows_amd64_cgo/BUILD.bazel:4:1: error executing shell command: 'export GOROOT="$(pwd)/bazel-out/x64_windows-fastbuild/bin/external/go_stdlib_windows_amd64_cgo" GOROOT_FINAL="GOROOT" GOOS="windows" GOARCH="amd64" CGO_ENABLED="1" CC="C:/Program Files (x86)/Micros...' failed (Exit 2): bash.exe failed: error executing command
  cd C:/tmp3/gdswrbqp/execroot/__main__
C:/msys64/usr/bin/bash.exe -c export GOROOT="$(pwd)/bazel-out/x64_windows-fastbuild/bin/external/go_stdlib_windows_amd64_cgo" GOROOT_FINAL="GOROOT" GOOS="windows" GOARCH="amd64" CGO_ENABLED="1" CC="C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/amd64/cl.exe" CXX="C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/amd64/cl.exe" COMPILER_PATH="C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/amd64" CGO_CPPFLAGS="/DCOMPILER_MSVC /DNOMINMAX /D_WIN32_WINNT=0x0600 /D_CRT_SECURE_NO_DEPRECATE /D_CRT_SECURE_NO_WARNINGS /D_SILENCE_STDEXT_HASH_DEPRECATION_WARNINGS /bigobj /Zm500 /J /Gy /GF /EHsc /wd4351 /wd4291 /wd4250 /wd4996" CGO_LDFLAGS="/MACHINE:X64" && export PATH="$PATH:$(cd "$COMPILER_PATH" && pwd)" && mkdir -p bazel-out/x64_windows-fastbuild/bin/external/go_stdlib_windows_amd64_cgo/src && mkdir -p bazel-out/x64_windows-fastbuild/bin/external/go_stdlib_windows_amd64_cgo/pkg && cp -rf external/go_sdk/src/* bazel-out/x64_windows-fastbuild/bin/external/go_stdlib_windows_amd64_cgo/src/ && cp -rf external/go_sdk/pkg/tool bazel-out/x64_windows-fastbuild/bin/external/go_stdlib_windows_amd64_cgo/pkg/ && cp -rf external/go_sdk/pkg/include bazel-out/x64_windows-fastbuild/bin/external/go_stdlib_windows_amd64_cgo/pkg/ && external/go_sdk/bin/go.exe install -asmflags "-trimpath $(pwd)"  std && external/go_sdk/bin/go.exe install -asmflags "-trimpath $(pwd)"  runtime/cgo
# runtime/cgo
```

Then start cmd.exe, `cd` into the directory in the output log (something like `C:\users\patrick\appdata\local\temp\_bazel_patrick\dmhbzmu0\execroot`) and run the command from the error log, below the `cd` line, that starts with "C:/msys64/usr/bin/bash.exe -c export GOROOT=..." in my example log.

**Comment by PatrickLang** [comment] 2018-01-22 18:39
```none
bazel build //... --verbose_failures
.................................................
INFO: Analysed 2 targets (167 packages loaded).
INFO: Found 2 targets...
ERROR: C:/users/patrick/appdata/local/temp/_bazel_patrick/dmhbzmu0/external/go_stdlib_windows_amd64_cgo/BUILD.bazel:4:1: error executing shell command: 'export GOROOT="$(pwd)/bazel-out/x64_windows-fastbuild/bin/external/go_stdlib_windows_amd64_cgo" GOROOT_FINAL="GOROOT" GOOS="windows" GOARCH="amd64" CGO_ENABLED="1" CC="C:/Program Files (x86)/Micros...' failed (Exit 2): bash.exe failed: error executing command
  cd C:/users/patrick/appdata/local/temp/_bazel_patrick/dmhbzmu0/execroot/__main__
C:/Program Files/Git/usr/bin/bash.exe -c export GOROOT="$(pwd)/bazel-out/x64_windows-fastbuild/bin/external/go_stdlib_windows_amd64_cgo" GOROOT_FINAL="GOROOT" GOOS="windows" GOARCH="amd64" CGO_ENABLED="1" CC="C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.10.25017/bin/HostX64/x64/cl.exe" CXX="C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.10.25017/bin/HostX64/x64/cl.exe" COMPILER_PATH="C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.10.25017/bin/HostX64/x64" CGO_CPPFLAGS="/DCOMPILER_MSVC /DNOMINMAX /D_WIN32_WINNT=0x0600 /D_CRT_SECURE_NO_DEPRECATE /D_CRT_SECURE_NO_WARNINGS /D_SILENCE_STDEXT_HASH_DEPRECATION_WARNINGS /bigobj /Zm500 /J /Gy /GF /EHsc /wd4351 /wd4291 /wd4250 /wd4996" CGO_LDFLAGS="/MACHINE:X64" && export PATH=$PATH:$(cd "$COMPILER_PATH" && pwd) && mkdir -p bazel-out/x64_windows-fastbuild/bin/external/go_stdlib_windows_amd64_cgo/src && mkdir -p bazel-out/x64_windows-fastbuild/bin/external/go_stdlib_windows_amd64_cgo/pkg && cp -rf external/go_sdk/src/* bazel-out/x64_windows-fastbuild/bin/external/go_stdlib_windows_amd64_cgo/src/ && cp -rf external/go_sdk/pkg/tool bazel-out/x64_windows-fastbuild/bin/external/go_stdlib_windows_amd64_cgo/pkg/ && cp -rf external/go_sdk/pkg/include bazel-out/x64_windows-fastbuild/bin/external/go_stdlib_windows_amd64_cgo/pkg/ && external/go_sdk/bin/go.exe install -asmflags "-trimpath $(pwd)"  std && external/go_sdk/bin/go.exe install -asmflags "-trimpath $(pwd)"  runtime/cgo
# runtime/cgo
exec: "C:/Program": file does not exist
INFO: Elapsed time: 60.648s, Critical Path: 32.24s
FAILED: Build did NOT complete successfully
```

Something that's interesting here is appears to be calling Git's bash.exe - is that expected?

**Comment by laszlocsomor** [comment] 2018-01-23 14:55
> Something that's interesting here is appears to be calling Git's bash.exe - is that expected?

I guess Git appears sooner on your PATH than MSYS, and maybe cgo just calls `bash` somewhere? Try changing your PATH in cmd.exe to only have MSYS and the Windows directory on it:
```
set PATH=c:\msys64\bin;c:\msys64\usr\bin;c:\windows\system32
```
Does that help?

**Comment by PatrickLang** [comment] 2018-01-23 18:52
Interesting - `C:/Program Files/Git/usr/bin` is not in my PATH, only `C:/Program Files/Git/cmd`

I do have Windows Subsystem for Linux which has a `c:\windows\system32\bash.exe` though. I can't remove `c:\windows\system32` from my PATH without breaking a lot more

**Comment by PatrickLang** [comment] 2018-01-24 07:21
If I try the same cmd script and manually replace the git bash.exe path with msys2's, it gets further but still doesn't complete


```none
C:\Users\patrick\Source\iso9660wrap>bazel run ///:iso9660wrap
ERROR: No targets found to run
INFO: Elapsed time: 0.479s
FAILED: Build did NOT complete successfully (0 packages loaded)
ERROR: Build failed. Not running target

C:\Users\patrick\Source\iso9660wrap>bazel run //:iso9660wrap --verbose_failures
INFO: Analysed target //:iso9660wrap (0 packages loaded).
INFO: Found 1 target...
ERROR: C:/users/patrick/appdata/local/temp/_bazel_patrick/dmhbzmu0/external/go_stdlib_windows_amd64_cgo/BUILD.bazel:4:1: error executing shell command: 'export GOROOT="$(pwd)/bazel-out/host/bin/external/go_stdlib_windows_amd64_cgo" GOROOT_FINAL="GOROOT" GOOS="windows" GOARCH="amd64" CGO_ENABLED="1" CC="C:/Program Files (x86)/Microsoft Visual Studio...' failed (Exit 2): bash.exe failed: error executing command
  cd C:/users/patrick/appdata/local/temp/_bazel_patrick/dmhbzmu0/execroot/__main__
C:/Program Files/Git/usr/bin/bash.exe -c export GOROOT="$(pwd)/bazel-out/host/bin/external/go_stdlib_windows_amd64_cgo" GOROOT_FINAL="GOROOT" GOOS="windows" GOARCH="amd64" CGO_ENABLED="1" CC="C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.12.25827/bin/HostX64/x64/cl.exe" CXX="C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.12.25827/bin/HostX64/x64/cl.exe" COMPILER_PATH="C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.12.25827/bin/HostX64/x64" CGO_CPPFLAGS="/DCOMPILER_MSVC /DNOMINMAX /D_WIN32_WINNT=0x0600 /D_CRT_SECURE_NO_DEPRECATE /D_CRT_SECURE_NO_WARNINGS /D_SILENCE_STDEXT_HASH_DEPRECATION_WARNINGS /bigobj /Zm500 /J /Gy /GF /EHsc /wd4351 /wd4291 /wd4250 /wd4996" CGO_LDFLAGS="/MACHINE:X64" && export PATH=$PATH:$(cd "$COMPILER_PATH" && pwd) && mkdir -p bazel-out/host/bin/external/go_stdlib_windows_amd64_cgo/src && mkdir -p bazel-out/host/bin/external/go_stdlib_windows_amd64_cgo/pkg && cp -rf external/go_sdk/src/* bazel-out/host/bin/external/go_stdlib_windows_amd64_cgo/src/ && cp -rf external/go_sdk/pkg/tool bazel-out/host/bin/external/go_stdlib_windows_amd64_cgo/pkg/ && cp -rf external/go_sdk/pkg/include bazel-out/host/bin/external/go_stdlib_windows_amd64_cgo/pkg/ && external/go_sdk/bin/go.exe install -asmflags "-trimpath $(pwd)"  std && external/go_sdk/bin/go.exe install -asmflags "-trimpath $(pwd)"  runtime/cgo
# runtime/cgo
exec: "C:/Program": file does not exist
Target //:iso9660wrap failed to build
INFO: Elapsed time: 31.329s, Critical Path: 30.12s
FAILED: Build did NOT complete successfully
ERROR: Build failed. Not running target

C:\Users\patrick\Source\iso9660wrap>cd C:/users/patrick/appdata/local/temp/_bazel_patrick/dmhbzmu0/execroot/__main__

C:\Users\patrick\AppData\Local\Temp\_bazel_Patrick\dmhBzmu0\execroot\__main__>c:\tools\msys64\usr\bin\bash.exe -c export GOROOT="$(pwd)/bazel-out/host/bin/external/go_stdlib_windows_amd64_cgo" GOROOT_FINAL="GOROOT" GOOS="windows" GOARCH="amd64" CGO_ENABLED="1" CC="C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.12.25827/bin/HostX64/x64/cl.exe" CXX="C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.12.25827/bin/HostX64/x64/cl.exe" COMPILER_PATH="C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.12.25827/bin/HostX64/x64" CGO_CPPFLAGS="/DCOMPILER_MSVC /DNOMINMAX /D_WIN32_WINNT=0x0600 /D_CRT_SECURE_NO_DEPRECATE /D_CRT_SECURE_NO_WARNINGS /D_SILENCE_STDEXT_HASH_DEPRECATION_WARNINGS /bigobj /Zm500 /J /Gy /GF /EHsc /wd4351 /wd4291 /wd4250 /wd4996" CGO_LDFLAGS="/MACHINE:X64" && export PATH=$PATH:$(cd "$COMPILER_PATH" && pwd) && mkdir -p bazel-out/host/bin/external/go_stdlib_windows_amd64_cgo/src && mkdir -p bazel-out/host/bin/external/go_stdlib_windows_amd64_cgo/pkg && cp -rf external/go_sdk/src/* bazel-out/host/bin/external/go_stdlib_windows_amd64_cgo/src/ && cp -rf external/go_sdk/pkg/tool bazel-out/host/bin/external/go_stdlib_windows_amd64_cgo/pkg/ && cp -rf external/go_sdk/pkg/include bazel-out/host/bin/external/go_stdlib_windows_amd64_cgo/pkg/ && external/go_sdk/bin/go.exe install -asmflags "-trimpath $(pwd)"  std && external/go_sdk/bin/go.exe install -asmflags "-trimpath $(pwd)"  runtime/cgo
declare -x ALLUSERSPROFILE="C:\\ProgramData"
declare -x APPDATA="C:\\Users\\patrick\\AppData\\Roaming"
declare -x COMMONPROGRAMFILES="C:\\Program Files\\Common Files"
declare -x COMPUTERNAME="LAKE"
declare -x COMSPEC="C:\\Windows\\system32\\cmd.exe"
declare -x ChocolateyInstall="C:\\ProgramData\\chocolatey"
declare -x ChocolateyLastPathUpdate="Sun Jan 21 23:32:47 2018"
declare -x ChocolateyToolsLocation="C:\\tools"
declare -x CommonProgramW6432="C:\\Program Files\\Common Files"
declare -x HOME="/home/Patrick"
declare -x HOMEDRIVE="C:"
declare -x HOMEPATH="\\Users\\patrick"
declare -x LOCALAPPDATA="C:\\Users\\patrick\\AppData\\Local"
declare -x LOGONSERVER="\\\\WIN-CC4QUHMORO4"
declare -x NUMBER_OF_PROCESSORS="12"
declare -x OLDPWD
declare -x OS="Windows_NT"
declare -x OneDrive="C:\\Users\\patrick\\OneDrive"
declare -x PATH="/c/Python27:/c/Python27/Scripts:/c/Windows/system32:/c/Windows:/c/Windows/System32/Wbem:/c/Windows/System32/WindowsPowerShell/v1.0:/c/Program Files (x86)/NVIDIA Corporation/PhysX/Common:/c/ProgramData/chocolatey/bin:/c/Program Files (x86)/vim/vim80:/c/tools/go/bin:/c/Program Files (x86)/Windows Kits/10/Windows Performance Toolkit:/c/HashiCorp/Vagrant/bin:/c/Go/bin:/c/Program Files/Git/cmd:/c/Users/patrick/AppData/Local/Microsoft/WindowsApps:/c/Program Files/Microsoft VS Code/bin:/c/ProgramData/chocolatey/lib/msys2:/"
declare -x PATHEXT=".COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC"
declare -x PROCESSOR_ARCHITECTURE="AMD64"
declare -x PROCESSOR_IDENTIFIER="Intel64 Family 6 Model 158 Stepping 10, GenuineIntel"
declare -x PROCESSOR_LEVEL="6"
declare -x PROCESSOR_REVISION="9e0a"
declare -x PROGRAMFILES="C:\\Program Files"
declare -x PROMPT="\$P\$G"
declare -x PSModulePath="C:\\Program Files\\WindowsPowerShell\\Modules;C:\\Windows\\system32\\WindowsPowerShell\\v1.0\\Modules"
declare -x PUBLIC="C:\\Users\\Public"
declare -x PWD="/c/Users/patrick/AppData/Local/Temp/_bazel_Patrick/dmhBzmu0/execroot/__main__"
declare -x ProgramData="C:\\ProgramData"
declare -x ProgramW6432="C:\\Program Files"
declare -x SESSIONNAME="Console"
declare -x SHLVL="1"
declare -x SYSTEMDRIVE="C:"
declare -x SYSTEMROOT="C:\\Windows"
declare -x TEMP="/c/Users/patrick/AppData/Local/Temp"
declare -x TERM="cygwin"
declare -x TMP="/c/Users/patrick/AppData/Local/Temp"
declare -x USERDNSDOMAIN="coffee.local"
declare -x USERDOMAIN="COFFEE"
declare -x USERDOMAIN_ROAMINGPROFILE="COFFEE"
declare -x USERNAME="Patrick"
declare -x USERPROFILE="C:\\Users\\patrick"
declare -x VAGRANT_DEFAULT_PROVIDER="hyperv"
declare -x VAGRANT_HOME="c:\\.vagrant.d"
declare -x WINDIR="C:\\Windows"
'export' is not recognized as an internal or external command,
operable program or batch file.
```

**Comment by rongjiecomputer** [comment] 2018-01-27 03:33
@PatrickLang I had a lot issue in the past when Git was installed in `C:\Program Files\Git` due to the whitespace in the path name (long before Bazel was released). Many bash script in the real world assume no whitespace in the path name, you will easily get tripped by any POSIX projects.

I installed Git at `C:\Git` and have no issue since then. My advise is to always install POSIX tools at locations without whitespace.

**Comment by laszlocsomor** [comment] 2018-02-05 10:21
@rlguarino : 
> Would downgrading Bazel help?

Try it -- in case it's a regression in newer Bazel versions, then that might help. But @rongjiecomputer 's advice also looks sound: try reinstalling Git under `c:\git` instead of `c:\program files\git`.

**Comment by alan-agius4** [comment] 2018-04-04 06:16
I am getting the same error on Windows. 

Error
```
$ bazel build --verbose_failures --noshow_progress @com_github_bazelbuild_buildtools//buildifier
DEBUG: C:/users/alag/appdata/local/temp/_bazel_alag/btbwur4a/external/io_bazel_rules_go/go/private/rules/binary.bzl:54:5: DEPRECATED: linkstamp, please use x_def for all stamping now main
INFO: Analysed target @com_github_bazelbuild_buildtools//buildifier:buildifier (0 packages loaded).
INFO: Found 1 target...
ERROR: C:/users/alag/appdata/local/temp/_bazel_alag/btbwur4a/external/io_bazel_rules_go/BUILD.bazel:9:1: GoStdlib external/io_bazel_rules_go/windows_amd64_stripped/stdlib~/pkg failed (Exit 1): stdlib.exe failed: error executing command
  cd C:/users/alag/appdata/local/temp/_bazel_alag/btbwur4a/execroot/angular
bazel-out/host/bin/external/io_bazel_rules_go/go/tools/builders/windows_amd64_stripped/stdlib.exe -go external/go_sdk/bin/go.exe -root_file external/go_sdk/packages.txt -goos windows -goarch amd64 -cgo=1 -compiler_path C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/amd64 -cc C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/amd64/cl.exe -cpp_flag /DCOMPILER_MSVC -cpp_flag /DNOMINMAX -cpp_flag /D_WIN32_WINNT=0x0600 -cpp_flag /D_CRT_SECURE_NO_DEPRECATE -cpp_flag /D_CRT_SECURE_NO_WARNINGS -cpp_flag /D_SILENCE_STDEXT_HASH_DEPRECATION_WARNINGS -cpp_flag /bigobj -cpp_flag /Zm500 -cpp_flag /J -cpp_flag /Gy -cpp_flag /GF -cpp_flag /EHsc -cpp_flag /wd4351 -cpp_flag /wd4291 -cpp_flag /wd4250 -cpp_flag /wd4996 -ld_flag /MACHINE:X64 -out bazel-out/host/bin/external/io_bazel_rules_go/windows_amd64_stripped/stdlib~
# runtime/cgo
exec: "C:\\Program": file does not exist
2018/04/04 08:12:14 error running go install std: exit status 2
Target @com_github_bazelbuild_buildtools//buildifier:buildifier failed to build
INFO: Elapsed time: 29.609s, Critical Path: 27.49s
```
Workspace
```
http_archive(
    name = "io_bazel_rules_go",
    url = "https://github.com/bazelbuild/rules_go/releases/download/0.10.2/rules_go-0.10.2.tar.gz",
    sha256 = "4b2c61795ac2eefcb28f3eb8e1cb2d8fb3c2eafa0f6712473bc5f93728f38758",
)

load("@io_bazel_rules_go//go:def.bzl", "go_rules_dependencies", "go_register_toolchains")

go_rules_dependencies()
go_register_toolchains()
```

**Comment by dwatley** [comment] 2018-04-11 14:56
+1

@laszlocsomor - I got around this by using a symlink at C:\bazel_vc to point to the Program Files VC path. because it seems we can't specify the VC build tools install location from the Microsoft supported installer. The issue from there is an invalid argument is passed to the C++ compiler so the Go bits cannot be compiled. From what I gather compiling Go code on Windows is simply not working at all with bazel. Seemingly no issue compiling C++ code.

So two issues:
1. Somewhere in the process via commands executed with spaces in path for the VC tools blows up. Workaround is to symlink to a non-space path.

2. Compiling Go code on Windows doesn't work because of some bad arguments to the VC compiler. 
Happy to help further.

```
$ bazel build :hello --verbose_failures
INFO: Analysed target //hello:hello (0 packages loaded).
INFO: Found 1 target...
ERROR: C:/users/dominic/appdata/local/temp/_bazel_dominic/miiivhdk/external/io_bazel_rules_go/BUILD.bazel:9:1: GoStdlib external/io_bazel_rules_go/windows_amd64_stripped/stdlib~/pkg failed (Exit 1): stdlib.exe failed: error executing command
  cd C:/users/dominic/appdata/local/temp/_bazel_dominic/miiivhdk/execroot/__main__
bazel-out/host/bin/external/io_bazel_rules_go/go/tools/builders/windows_amd64_stripped/stdlib.exe -go external/go_sdk/bin/go.exe -root_file external/go_sdk/packages.txt -goos windows -goarch amd64 -cgo=1 -compiler_path C:/bazel_vc/bin/amd64 -cc C:/bazel_vc/bin/amd64/cl.exe -cpp_flag /DCOMPILER_MSVC -cpp_flag /DNOMINMAX -cpp_flag /D_WIN32_WINNT=0x0600 -cpp_flag /D_CRT_SECURE_NO_DEPRECATE -cpp_flag /D_CRT_SECURE_NO_WARNINGS -cpp_flag /D_SILENCE_STDEXT_HASH_DEPRECATION_WARNINGS -cpp_flag /bigobj -cpp_flag /Zm500 -cpp_flag /J -cpp_flag /Gy -cpp_flag /GF -cpp_flag /EHsc -cpp_flag /wd4351 -cpp_flag /wd4291 -cpp_flag /wd4250 -cpp_flag /wd4996 -ld_flag /MACHINE:X64 -out bazel-out/x64_windows-fastbuild/bin/external/io_bazel_rules_go/windows_amd64_stripped/stdlib~
# runtime/cgo
Microsoft (R) C/C++ Optimizing Compiler Version 19.00.24231 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.

cl : Command line error D8021 : invalid numeric argument '/Werror'
2018/04/10 22:45:39 error running go install std: exit status 2
Target //hello:hello failed to build
INFO: Elapsed time: 31.923s, Critical Path: 31.20s
FAILED: Build did NOT complete successfully
```

BUILD.bazel
```
load("@io_bazel_rules_go//go:def.bzl", "go_binary", "go_library", "go_test")

go_binary(
    name = "hello",
    srcs = ["hello.go"],
)
```

hello.go
```
package main

import (
	"fmt"
)

func main() {
	fmt.Println("Hello!")
}
```

**Comment by hlopko** [comment] 2019-01-11 06:41
So was it a git on windows problem at the end? Can we close this issue?

**Comment by laszlocsomor** [comment] 2019-01-11 09:20
@hlopko : That was one of the problems.

Is anyone still seeing this bug with newer Bazel versions? (Current release is 0.21)

**Comment by dwatley** [comment] 2019-01-12 22:09
I believe it was fixed at some point. I'm not getting path errors anymore without the symlink.

**Comment by laszlocsomor** [comment] 2019-01-14 07:00
Thanks!

**Closed by laszlocsomor** 2019-01-14 07:00 UTC
Labels: platform: windows, team-Rules-CPP, type: bug
