### ISSUE TITLE
Different sys.path between bazel test and bazel run

### ISSUE THREAD

**Issue by girving** [bazelbuild/bazel#753] opened 2016-01-04 21:21 UTC
One of our tensorflow tests is failing under `bazel test` on my machine, but not under `bazel run`.  The issue is that I have two versions of numpy installed, 1.8.2 in `/usr/lib/python3/dist-packages/numpy` and 1.10.2 in `/usr/local/lib/python3.4/dist-packages/numpy`.

When I run `python3` from the command line, or via `bazel run`, `sys.path` includes `/usr/local/lib/python3.4/dist-packages` before `/usr/lib/python3/dist-packages`, and importing numpy gets version 1.10.2 (the version I'd like).  However, when run via `bazel test`, the `/usr/local` entry is entirely missing from `sys.path`, Python gets the bad version of numpy, and importing numpy throws an error since it doesn't match the version I compiled against.

Do you know why the python path would differ between `test` and `run`?  The `bazel run` behavior seems correct, since it mimics what I get when I run `python3` from the command line.

**Comment by bsilver8192** [comment] 2016-01-05 06:34
I'm pretty sure the reason the entry is missing when using `bazel test` is because the sandbox doesn't include `/usr/local`, which is the correct behavior. If you want to use files in `/usr/local`, you have to do it through a `new_local_repository(path = '/usr')`.

If you really want to, you could disable sandboxing instead (`--spawn_strategy=standalone`), but sandboxing is generally really nice for making sure builds are hermetic.

**Comment by philwo** [comment] 2016-01-05 13:55
Yes, the sandbox by default does not mount /usr/local on purpose. I think Brian's suggestion should work.

In the long-term we will make the sandbox more configurable and/or be able to use standardized base images (maybe Docker containers) as a build environment, so that you don't run into these issues anymore.

**Comment by girving** [comment] 2016-01-05 16:17
The problem is that the thing that installed numpy into `/usr/local` is `/usr/bin/pip3`.  That is, my system default install path for python modules includes `/usr/local`, so bazel is broken by default on my system (my Google desktop machine).

**Comment by martinwicke** [comment] 2016-01-21 18:19
We have added `--spawn_strategy=standalone` for all bazel commands in the build instructions for TensorFlow. There are simply too many cases that fail without it, even on run off the mill systems. 

@bsilver8192: For my education, what effect does `new_local_repository(path = '/usr')` have? Will it make all programs under /usr available in the sandbox?

**Comment by damienmg** [comment] 2016-01-21 18:36
Yes if you make your targets depends on a new_local_repository(path =
'/usr', build_file = "big_glob.BUILD") and set "big_glob.BUILD" to have a
"filegroup(name = "big_glob", srcs = glob(["**"]))" then all the file of
/usr will get shiped in the sandbox.

That's going to be probably really really slow.

**Comment by kchodorow** [comment] 2016-01-21 18:40
However, if you just depend on what you need (don't glob everything!) then
it shouldn't be slow.

**Comment by philwo** [comment] 2016-12-09 14:24
Closing this as absolete, because the new sandbox mounts all directories including /usr/local. Please re-open if this is still an issue.

**Comment by excavador** [comment] 2018-01-03 16:27
```
➜ bazel version
Build label: 0.9.0-homebrew
Build target: bazel-out/darwin-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Sun Jul 12 12:24:01 +49936 (1513677414241)
Build timestamp: 1513677414241
Build timestamp as int: 1513677414241
```

Sometime bazel server insert incorrect PATH
```
PATH=/usr/bin:/bin:/usr/sbin:/sbin # incorrect PATH, does not reflect system PATH
PATH=/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/bin:/usr/local/bin:/usr/bin:/bin # correct PATH
```

"bazel clean" does not help, "bazel clean --expunge" helps.
Probably, bazel shutdown will help.

**Comment by excavador** [comment] 2018-01-04 22:13
can you reopen issue?

**Comment by brandjon** [comment] 2019-03-14 19:28
Reopening as per @excavador's request.

**Comment by meisterT** [comment] 2020-05-15 06:21
Is this still an issue with current Bazel?

**Comment by philwo** [comment] 2020-05-15 08:55
Cannot reproduce this anymore.

```
philwo@takaramono:src/bazeltest $ cat BUILD 
sh_test(
    name = "env_test",
    srcs = ["env_test.sh"],
)

philwo@takaramono:src/bazeltest $ cat env_test.sh 
#!/bin/bash

set -euo pipefail

echo "PATH=$PATH"

philwo@takaramono:src/bazeltest $ bazel test --test_output=all --nocache_test_results //:env_test  
PATH=.:/Users/philwo/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Users/philwo/Library/Python/3.7/bin:/Users/philwo/go/bin

philwo@takaramono:src/bazeltest $ bazel run -s //:env_test
PATH=.:/Users/philwo/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Users/philwo/Library/Python/3.7/bin:/Users/philwo/go/bin
```

**Closed by philwo** 2020-05-15 08:55 UTC
Labels: P3, category: sandboxing, type: feature request
