### ISSUE TITLE
pkg_tar does not respect strip_prefix when output is in workspace root

### ISSUE THREAD

**Issue by jasonchoimtt** [bazelbuild/bazel#1604] opened 2016-08-04 21:57 UTC
Repro:

```bash
touch WORKSPACE
cat > BUILD <<EOD
load("@bazel_tools//tools/build_defs/pkg:pkg.bzl", "pkg_tar")

pkg_tar(
    name = "repro",
    files = ["a/b/c.sh"],
    strip_prefix = "a/b",
)
EOD
mkdir -p a/b
touch a/b/c.sh
bazel build :repro
tar -tf bazel-bin/repro.tar
```

I believe the particular line is here:

https://github.com/bazelbuild/bazel/blob/master/tools/build_defs/pkg/path.bzl#L51

```python
else:  # Relative to a sub-directory
  return _short_path_dirname(out) + "/" + data_path
```

which fails to account for the fact that `_short_path_dirname` may return `""`. As a result, the returned `data_path` incorrectly includes a `/`.

**Comment by zhexuany** [comment] 2016-08-07 04:25
@jasonchoimtt  I could not reproduce the bug. The version I used is 0.3.1. It build project you provided correctly.

**Comment by jasonchoimtt** [comment] 2016-08-07 04:33
Sorry, I should have elaborated more. I expect the tarball to contain:

```
./
./c.sh
```

since I `strip_prefix` `a/b`.

But instead it produces a tarball with (I'm on 0.3.0):

```
./
./a/
./a/b/
./a/b/c.sh
```

Can you reproduce this? If not, I can test on 0.3.1 later to verify.

**Comment by zhexuany** [comment] 2016-08-07 04:38
The output I have is 
```
tar -tf bazel-bin/repro.tar   
./
./a/
./a/b/
./a/b/c.sh
```

**Comment by jasonchoimtt** [comment] 2016-08-07 04:52
That shows the problem I am reporting. If I am not mistaken, the intended behavior of `strip_prefix = "a/b"` is that it should remove `a/b` and so put `c.sh` at the root of the tarball. But as shown above this does not happen.

Am I right or did I misinterpret the documentation?

**Comment by zhexuany** [comment] 2016-08-07 04:55
You are absolutely right. I read too fast and missed some key info. If you provide `strip_prefix`, it should behave like you expecting. But `Bazel` did not.

**Comment by zhexuany** [comment] 2016-08-07 05:26
@jasonchoimtt  I just fixed it. I am preparing pull request now. Hopefully, my changes can be merged into mater in near future. :)

**Comment by jasonchoimtt** [comment] 2016-08-07 05:36
Thank you! Feel free to close this issue when you are done. :)

**Comment by zhexuany** [comment] 2016-08-08 13:56
@hermione521 Could you close this issue, I do not have the access to close it.

**Closed** 2016-08-09 08:35 UTC
Labels: P2, type: bug
