### ISSUE TITLE
C++ file changes cause stable inconsistent state

### ISSUE THREAD

**Issue by ZacVawterKodiak** [bazelbuild/bazel#6052] opened 2018-08-31 19:34 UTC
### Description of the problem / feature request:
Modifying 'changling.h' header does not cause a build, resulting in inconsistent state.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

1. Extract [broken.zip](https://github.com/bazelbuild/bazel/files/2341325/broken.zip)
2. bazel build ...
3. Add a z to changling.h::baz character array.
4. bazel build ...  [ NOTE there was no rebuild of any targets ]

### What operating system are you running Bazel on?
Ubuntu 18.04

### What's the output of `bazel info release`?
release 0.16.1

###  Have you found anything relevant by searching the web?
nope

### Any other information, logs, or outputs that you want to share?
Removing the 3 lines in the `bazel.rc` prevents this bug.

**Comment by mhlopko** [comment] 2018-09-06 16:09
Bazel gets the .d information from the compiler and doesn't trigger recompilation if the header was not used in the previous run. If you change your code and use the header in main.cpp, then everything works like expected.

**Comment by ZacVawterKodiak** [comment] 2018-09-06 18:09
@mhlopko how do I get the '.d information' from the compiler?  I changed the example to use a variable from the header, and the problem still exists.

Changing main.cpp to print `bar` and the bug exhibits.
[broken_with_usage_of_library_variable.zip](https://github.com/bazelbuild/bazel/files/2358240/broken_with_usage_of_library_variable.zip)

```
#include "changling.h"
#include <iostream>

int main()
{
  std::cout << global_in_library;
  return 0;
}
```

**Comment by ZacVawterKodiak** [comment] 2018-09-06 20:50
I'm not sure exactly which flags bazel is using to generate the dependency listing, but on both the original 'broken.zip' and the updated one running `cc -M main.cpp`, changling.h is included in the dependency list:
```
main.o: main.cpp /usr/include/stdc-predef.h changling.h \
  .... giant list of system includes ...
```

Is there a way to see the command bazel is using to generate the dependency list as some verbose output  (I am familiar with `-s` but that is only for actions that are executed AFAIK?

**Comment by ZacVawterKodiak** [comment] 2018-09-06 23:40
Running `bazel build ... --sandbox_debug`, I get "0d78b60f575cc34d2631e0a55e2f04d9" for my bazel cache, then search for `main.*d` and find: `.cache/bazel/_bazel_zac/0d78b60f575cc34d2631e0a55e2f04d9/execroot/__main__/bazel-out/k8-fastbuild/bin/_objs/broken/main.pic.d`

cat of ^ file does contain `changling.h`:
```
bazel-out/k8-fastbuild/bin/_objs/broken/main.pic.o: main.cpp \
 /usr/include/stdc-predef.h **changling.h** /usr/include/c++/7/string \
 /usr/include/x86_64-linux-gnu/c++/7/bits/c++config.h \
 /usr/include/x86_64-linux-gnu/c++/7/bits/os_defines.h \
...
```

**Comment by ZacVawterKodiak** [comment] 2018-09-07 19:14
Careful inspection of the bazel java.log shows some interesting things.  It suggests that bazel is detecting a modification, but 'building' takes 0.00s.  When I change main.cpp `bazel build ...`, it takes 0.49s.

Snippet from `java.log`:
```
180907 18:13:13.940:I 1050 [com.google.devtools.build.lib.skyframe.SkyframeExecutor.informAboutNumberOfModifiedFiles] Found 1 modified files from last build
180907 18:13:13.956:I 1050 [com.google.devtools.build.lib.profiler.AutoProfiler$LoggingElapsedTimeReceiver.log] Spent 0 milliseconds doing Saving action cache
180907 18:13:13.957:I 1050 [com.google.devtools.build.lib.runtime.BuildSummaryStatsModule.buildComplete] Critical Path: 0.00s
  0.00s action 'BazelWorkspaceStatusAction stable-status.txt'
180907 18:13:13.957:I 1050 [com.google.devtools.build.lib.runtime.BuildSummaryStatsModule.buildComplete] Slowest actions:
  0.00s action 'BazelWorkspaceStatusAction stable-status.txt'
  0.00s action 'Compiling main.cpp'
  0.00s action 'Compiling main.cpp'
  0.00s action 'Compiling main.cpp'
  0.00s null for //:changling
180907 18:13:13.959:I 1050 [com.google.devtools.build.lib.runtime.CacheFileDigestsModule.logStats] Accumulated cache stats after command: hit count=1332, miss count=5600, hit rate=0.19215233698788228, eviction count=0
180907 18:13:13.959:I 1050 [com.google.devtools.build.lib.runtime.CacheFileDigestsModule.logStats] Cache stats for finished command: hit count=8, miss count=2, hit rate=0.8, eviction count=0
180907 18:13:13.960:I 1050 [com.google.devtools.build.lib.server.GrpcServerImpl$RunningCommand.close] Finished command 57f6b0ff-b7cf-48dc-bf99-5f45a4f8a4b1 on thread grpc-command-1
```

**Comment by mhlopko** [comment] 2018-09-11 13:41
Can you reproduce without cuda? (I don't have cuda setup locally, and using normal C++ toolchain I still cannot repro).

**Comment by ZacVawterKodiak** [comment] 2018-09-11 15:45
Unfortunately I think it has something to do with tensorflow cuda messing with the crosstool.  I haven't fully understood what tensorflow bazel cuda package is doing, so I haven't been able to simplify that piece.

**Comment by ZacVawterKodiak** [comment] 2018-09-18 04:52
See linked tensorflow bug for a partial update.

It looks like the crosstool's `cxx_builtin_include_directory` was being set to `\`.  Which apparently silently breaks the earth!?!?

**Comment by mhlopko** [comment] 2018-09-25 16:54
Ouch. A lot of ouch.

**Comment by r4nt** [comment] 2018-09-29 19:58
I am working on a fix, but it's quite involved to test, as bazel doesn't realize that changes to symlinks need rebuilds, thus giving me both incorrect failures and incorrect successes.

**Comment by r4nt** [comment] 2018-10-15 15:33
Fix in TF waiting for reporter to validate.

**Comment by zoltanpillio** [comment] 2018-11-05 14:11
Is there any news here?

**Comment by r4nt** [comment] 2018-11-05 15:31
Yes, this should work now.

**Comment by jin** [comment] 2019-01-14 23:01
@scentini could you add a [priority](https://www.bazel.build/maintainers-guide.html#priority) to this issue, please?

**Comment by aiuto** [comment] 2020-05-22 15:12
Closing since the TF issue was fixed in Oct 2018. https://github.com/tensorflow/tensorflow/issues/22057

**Closed by aiuto** 2020-05-22 15:12 UTC
Labels: P2, team-Rules-CPP, type: support / not a bug
