### ISSUE TITLE
Java annotation processors appear hardcoded to JDK 8

### ISSUE THREAD

**Issue by zls88** [bazelbuild/bazel#12230] opened 2020-10-08 14:25 UTC
### Description of the problem / feature request:

It seems like the header generation step of annotation processors always uses JDK 8, even if the toolchain is set to, say, JDK 11. This is a problem because the annotation processor won't understand some language features that have been introduced since Java 8, and will fail.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

I've got an example repro here: https://github.com/zls88/bazel-playground/tree/main/annotation-processor-wrong-javac-source-version

In summary, I've set the Java toolchain in `.bazelrc` like so:
```
build \
    --java_toolchain=@bazel_tools//tools/jdk:toolchain_java11 \
    --host_java_toolchain=@bazel_tools//tools/jdk:toolchain_java11
```
Yet builds fail because an interface contains a Java 9 language feature. I've narrowed it down to this invocation in the sandbox:
```
external/remotejdk11_macos/bin/java \
-jar \
external/remote_java_tools_darwin/java_tools/turbine_deploy.jar \
@bazel-out/darwin-fastbuild/bin/libexample-hjar.jar-0.params \
@bazel-out/darwin-fastbuild/bin/libexample-hjar.jar-1.params
ExampleInterface.java:5: error: private interface methods are not supported in -source 8
  (use -source 9 or higher to enable private interface methods)
```
The selfsame code builds fine with Gradle.

### What operating system are you running Bazel on?

OSX Catalina 10.15.6

### What's the output of `bazel info release`?

```
release 3.4.1
```

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

```
 $ git remote get-url origin ; git rev-parse main ; git rev-parse HEAD
git@github.com:zls88/bazel-playground.git
9cb4ba4abebba676e1cfdb748fa91929135a7cb2
9cb4ba4abebba676e1cfdb748fa91929135a7cb2
```

###  Have you found anything relevant by searching the web?

No. I asked in `#debugging` in slack and sent an email to the list, but I didn't find any answers.

**Comment by cushon** [comment] 2020-10-08 19:56
This is a duplicate of #8585

**Closed by cushon** 2020-10-08 19:56 UTC
