### ISSUE TITLE
Should BazelPackageLoader support the ~new .bazelignore functionality?

### ISSUE THREAD

**Issue by haxorz** [bazelbuild/bazel#10428] opened 2019-12-16 22:44 UTC
BazelPackageLoader currently doesn't attempt to support .bazelignore. Look at AbstractPackageLoader#makeFreshSkyFunctions.

**Comment by meteorcloudy** [comment] 2019-12-17 17:32
Can you explain more about what BazelPackageLoader does and why the initial implementation of [ADDITIONAL_BLACKLISTED_PACKAGE_PREFIXES_FILE](https://github.com/bazelbuild/bazel/blob/7b2cb35d3499ead907df60df1dd1fbae9e74f0b3/src/main/java/com/google/devtools/build/lib/skyframe/BazelSkyframeExecutorConstants.java#L42) didn't take it into consideration?

**Comment by haxorz** [comment] 2019-12-17 17:43
BazelPackageLoader is Bazel's implementation of the com.google.devtools.build.lib.skyframe.packages.PackageLoader interface, which is an interface for a *library* that does package loading.

The initial open-sourcing of BlacklistedPackagePrefixesValue was actually dead code in Bazel (it was used only internally) [1]. BlacklistedPackagePrefixesValue was never intended to be used to implement .bazelignore [2], nor was it intended to be used by BazelPackageLoader. But, now that BlacklistedPackagePrefixesValue is being used to implement .bazelignore, I feel like we should try to polish things up.

[1] Also see https://github.com/bazelbuild/bazel/issues/10427#issuecomment-566283078 -- the same historical note applies there too.
[2] I made a GitHub comment years ago (https://github.com/bazelbuild/bazel/issues/2460#issuecomment-294078330) stating that BlacklistedPackagePrefixesValue *could* be used to *maybe* implement something kinda-sorta like current-day .bazelignore. I also said "let me know if you have any questions", and was surprised to see, years later, .bazelignore implemented without any consultation from the Core team.

**Comment by haxorz** [comment] 2019-12-17 17:45
@ericfelly

**Comment by meteorcloudy** [comment] 2019-12-17 19:29
@haxorz Thanks for the clarification. Indeed we should improve the error message and make BazelPackageLoader also support .bazelignore file. Can you give some hint how to test this? Because currently in normal bazel build, .bazelignore seems to work correctly. I wonder what is broken if we don't support .bazelignore in BazelPackageLoader.

Besides, the current idea for .bazelignore is that it should tell Bazel to ignores all BUILD files under given directories, but the files should still be accessible to Bazel in other BUILD files, similar to --deleted_packages. But I just found `glob` function will also ignore directories listed in .bazelignore (but not for packages listed by --deleted_packages). Should we change that? If we did, will that break anything internally?

**Comment by benjaminp** [comment] 2019-12-17 20:08
> Besides, the current idea for .bazelignore is that it should tell Bazel to ignores all BUILD files under given directories, but the files should still be accessible to Bazel in other BUILD files, similar to --deleted_packages.

That's not what the semantics of `--deleted_packages` are. If you reference a "deleted" package in anywhere, you'll get an error.

**Comment by haxorz** [comment] 2019-12-17 20:30
> [@meteorcloudy] Can you give some hint how to test this?

It should be pretty straightforward to add a test case to BazelPackageLoaderTest.java.

> [@meteorcloudy] I wonder what is broken if we don't support .bazelignore in BazelPackageLoader.

In generally, I have little insight into how folks are using Bazel externally. As for BazelPackageLoader, I can tell you that I implemented it years ago on request of the Kythe folks (https://github.com/kythe/kythe), since they wanted Bazel support. So I suppose the concrete impact for them is "Kythe ignores .bazelignore".

> [@meteorcloudy] Besides, the current idea for .bazelignore is that it should tell Bazel to ignores all BUILD files under given directories, but the files should still be accessible to Bazel in other BUILD files, similar to --deleted_packages.
> [@benjaminp] That's not what the semantics of --deleted_packages are. If you reference a "deleted" package anywhere, you'll get an error.

@meteorcloudy are you perhaps referring to the fact that `glob` respects package boundaries, so if a package *doesn't* exist due to --deleted_packages, then `glob` happily globs through that directory?

If so, yes, this is a difference. See below.

> [@meteorcloudy] But I just found glob function will also ignore directories listed in .bazelignore ...

In case you didn't see it, this behavior is very new and was added by @lberki in 7abdcb4. You might be interested in seeing some of the internal review comments.

> [@meteorcloudy] ... (but not for packages listed by --deleted_packages). Should we change that? If we did, will that break anything internally?

No, this seems WAI for me wrt --deleted_packages. See my comment above.

I didn't push back on 7abdcb4 because it's not my place to question the Bazel team's business logic goals of .bazelignore -- if you all think `glob` should *stop* at .bazelignore-ignored directories, then, yes, this is different than --deleted_packages. This observation is even more reason to improve the error message in https://github.com/bazelbuild/bazel/issues/10427 since right now it's conflating two different Bazel features.

**Comment by meteorcloudy** [comment] 2019-12-17 22:17
> That's not what the semantics of --deleted_packages are. If you reference a "deleted" package anywhere, you'll get an error.

I mean you can still have `//foo:ignored/file` in `foo/BUILD` with `--deleted_packages=//foo/ignored`. This won't be an error.

@haxorz @lberki I thought the only difference between .bazelignore and --deleted_packages is that .bazelignore tells Bazel to ignore all packages under a directory and --deleted_packages tells Bazel to ignore certain given packages (not their sub-packages). But I found the different behaviours on `glob` a bit confusing.

Consider the following repo:
```
$ tree .
.
├── foo
│   ├── bar
│   │   ├── a.txt
│   │   └── BUILD
│   ├── BUILD
│   └── ignored
│       ├── b.txt
│       └── BUILD
└── WORKSPACE

$ cat foo/BUILD 
filegroup(
  name = "all_files",
  srcs = glob(["**/*"]),
)

filegroup(
  name = "files",
  srcs = ["//foo/bar:a.txt", "//foo:ignored/b.txt"],
)
``` 

```
$ bazel query "deps(//foo:files)" --deleted_packages=//foo/ignored
```
and
```
$ echo "foo/ignored" > .bazelignore && bazel query "deps(//foo:files)"
```
give the same result
```
//foo:files
//foo/bar:a.txt
//foo:ignored/b.txt
```

But it's different when using `glob`,
```
$ bazel query "deps(//foo:all_files)" --deleted_packages=//foo/ignored
//foo:all_files
//foo:ignored/b.txt
//foo:ignored/BUILD
//foo:BUILD
$ echo "foo/ignored" > .bazelignore && bazel query "deps(//foo:all_files)" 
//foo:all_files
//foo:BUILD
```

IMO, `.bazelignore` should either prevent usage like `//foo:ignored/b.txt" or allow glob go into "ignored" packages like `--deleted_packages` does.
@lberki WDYT? Is there any specific reason we should not look into directories listed in .bazelignore in glob function?

**Comment by haxorz** [comment] 2019-12-17 22:37
@meteorcloudy To be clear, your last comment is exactly what I was referring to in my previous comment. The behavior you are complaining about was intentionally added by 7abdcb4.

**Comment by meteorcloudy** [comment] 2019-12-17 22:57
@haxorz Thanks! Yes, I understand ;) But I didn't completely understand why we made that change. Because I thought `.bazelignore` should only ignore packages, not actually make the whole directory as if not exist for Bazel. Maybe @lberki can clarify this.

**Comment by lberki** [comment] 2020-01-07 14:11
/cc @irengrig 

@meteorcloudy , that's not the intended behavior of `.bazelignore`; the idea is that it makes Bazel ignore that subdirectory from the source tree altogether. The above example by @meteorcloudy  is a good demonstration of this.

Note that when Bazel sees the label `//foo:ignored/b.txt`, it doesn't consult the file system to see whether the file is actually there; that will be figured out in the execution phase.

**Comment by philwo** [comment] 2020-12-08 20:54
@haxorz @meteorcloudy What's the status of this? Obsolete? Still important?

**Comment by haxorz** [comment] 2020-12-08 20:59
@philwo Afaik, it's still an issue. Probably has never been important though; I don't think any BazelPackageLoader users have actually complained about this yet.

**Comment by meteorcloudy** [comment] 2020-12-09 10:52
Yeah, it's still an issue, Angular had some use case related to this, but I don't hear anything back from them for a long time. I think we can close it, feel free to reopen if anyone wants to follow up.

**Closed by meteorcloudy** 2020-12-09 10:52 UTC
Labels: team-XProduct, untriaged
