### ISSUE TITLE
Remote Execution contains duplicate output_files

### ISSUE THREAD

**Issue by DaveGay** [bazelbuild/bazel#7500] opened 2019-02-21 22:16 UTC
As of the Bazel release stamped "21-02-2019 16:18" (earlier today), calls to Execute for our Java test targets are now including a duplicated "output_files" entry:

`output_files: "bazel-out/k8-fastbuild/bin/hello_world_test.jar"`
`output_files: "bazel-out/k8-fastbuild/bin/hello_world_test.jar_manifest_proto"`
`output_files: "bazel-out/k8-fastbuild/bin/hello_world_test.jdeps"`
`output_files: "bazel-out/k8-fastbuild/bin/hello_world_test.jdeps"`

Previous runs of the same test generated this list:

`output_files: "bazel-out/k8-fastbuild/bin/hello_world_test.jar"`
`output_files: "bazel-out/k8-fastbuild/bin/hello_world_test.jar_manifest_proto"`
`output_files: "bazel-out/k8-fastbuild/bin/hello_world_test.jdeps"`

**Comment by ulfjack** [comment] 2019-02-26 09:23
Duplicate of #7508.

**Closed by ulfjack** 2019-02-26 09:23 UTC
Labels: team-Remote-Exec, untriaged
