### ISSUE TITLE
Every projects on ci.bazel.io are red on Jenkins

### ISSUE THREAD

**Issue by damienmg** [bazelbuild/bazel#1168] opened 2016-04-21 11:42 UTC
Due to missing runfiles

**Comment by damienmg** [comment] 2016-04-21 11:43
I higly suspect https://github.com/bazelbuild/bazel/commit/857cda2c45a5cc68c3fa398311c48c571a64915d

This wasn't caught earlier because the JDK7 build breakage was preventing downstream project from being built

**Comment by damienmg** [comment] 2016-04-21 13:25
confirmed suspect.

**Comment by damienmg** [comment] 2016-04-21 13:45
Broken builds because jenkins cannot show them easily:
http://ci.bazel.io/job/rules_closure/55/
http://ci.bazel.io/job/rules_scala/79/
http://ci.bazel.io/job/skydoc/8/
http://ci.bazel.io/job/TensorFlow/179/
http://ci.bazel.io/job/TensorFlow_Serving/60/
http://ci.bazel.io/job/Tutorial/243/

**Comment by kchodorow** [comment] 2016-04-21 13:46
Thanks, on it.

**Comment by kchodorow** [comment] 2016-04-21 14:11
Verifying now, but I think this is caused by the SourceManifestAction caching issue, which I've got an LGTM'd CL to fix.

**Comment by kchodorow** [comment] 2016-04-21 14:22
Yup, that's it!  

Note that this won't fix everything, I think the AppEngine rules are just broken because they assume an empty workspace name.  But it should be much better.

**Comment by damienmg** [comment] 2016-04-21 14:23
the appengine rules where not broken by that change

**Comment by kchodorow** [comment] 2016-04-21 14:25
Well, they should have been. Guess they're not very well tested.

**Comment by damienmg** [comment] 2016-04-21 15:42
http://ci.bazel.io/job/skydoc/BAZEL_VERSION=HEAD,PLATFORM_NAME=linux-x86_64/11/console at least one breakage left. ci is still running :(

**Comment by damienmg** [comment] 2016-04-21 15:47
TensorFlow tests are still failing :( I need to go home now and probably will be offline. Feel free to push if you have more fixes for that.

**Comment by kchodorow** [comment] 2016-04-21 18:41
Happily, the TF failure looks like a flake (it passes for me locally).  However, I'm not sure why the other tests are failing, so I'm rolling back.  The failing tests are now:

* [TF Serving](http://ci.bazel.io/job/TensorFlow_Serving/63/BAZEL_VERSION=HEAD,PLATFORM_NAME=linux-x86_64/console)
* [SkyDoc](http://ci.bazel.io/job/skydoc/BAZEL_VERSION=HEAD,PLATFORM_NAME=linux-x86_64/11/console) - I couldn't actually figure out how to get to this failure.
* [Tutorial](http://ci.bazel.io/job/Tutorial/PLATFORM_NAME=linux-x86_64/246/console) - android rules are accessing the wrong path.
* [rules_rust](http://ci.bazel.io/job/rules_rust/BAZEL_VERSION=HEAD,PLATFORM_NAME=linux-x86_64/43/console)
* [rules_closure](http://ci.bazel.io/job/rules_closure/55/BAZEL_VERSION=HEAD,PLATFORM_NAME=linux-x86_64/console)

**Closed** 2016-04-22 12:01 UTC
Labels: category: testing, P0, type: bug
