### ISSUE TITLE
cc_inc_library doesn't work for external repositories

### ISSUE THREAD

**Issue by dfr** [bazelbuild/bazel#1596] opened 2016-08-02 11:15 UTC
I'm trying to use cc_inc_library to structure include files for a utility project. This works just fine within the project itself but fails when I try to use the utility project as an external dependency in some other workspace. The attached archive shows the problem:

$ unzip bazel-test.zip
$ cd bazel-test/sub
$ bazel build //a
... building in the nested workspace works fine ...
$ cd ..
$ bazel build //external:a
... build fails when referencing it as an external repository ...

[bazel-test.zip](https://github.com/bazelbuild/bazel/files/396844/bazel-test.zip)

**Comment by meteorcloudy** [comment] 2016-08-03 08:37
//cc @kchodorow Looks like a bug, can you take look?

**Comment by meteorcloudy** [comment] 2016-08-03 09:18
I figured the reason is because when referencing it as an external repository, `cc_inc_library` creates the headers under `bazel-out/local-fastbuild/include/external/sub/a/_/hdrs/external/sub/a` which should be `bazel-out/local-fastbuild/include/external/sub/a/_/hdrs/a`

**Comment by zhexuany** [comment] 2016-08-07 06:22
@meteorcloudy Could you assign this to me? I am pretty interested in fixing this bug.

**Comment by zhexuany** [comment] 2016-08-07 16:55
@meteorcloudy  I think the problem is in `CcIncLibrary.java`. The link is the following `bazel/src/main/java/com/google/devtools/build/lib/rules/cpp/CcIncLibrary.java`.

**Comment by meteorcloudy** [comment] 2016-08-08 08:02
@zhexuany Thank you so much! I'll review your change, but it seems I can only assign the issue to members from Bazel team. Sorry for that~

**Comment by zhexuany** [comment] 2016-08-08 14:00
@meteorcloudy I see. That is not a problem but how could I contribute code without doing duplicated work? In addition, I went through `test` directory. I could not find any test case for `cc_inc_library`.  Could you give me some guideline for writing this?

**Comment by meteorcloudy** [comment] 2016-08-08 15:14
Adding test to your change would be great! Please consider this one https://github.com/bazelbuild/bazel/blob/master/src/test/shell/bazel/cc_inc_library_test.sh

**Comment by zhexuany** [comment] 2016-08-08 16:22
@meteorcloudy  I plan to finish it tonight. Thanks for the guide.

**Comment by zhexuany** [comment] 2016-08-09 03:31
I am having trouble for running `test`. Even I specify the location of `TEST_SRCDIR`, it still prompt me `io_bazel` is not found. I went through the source code and found there are a lot of place using this. Could I directly change `io_bazel` to `bagel` since all `testing.sh` does is looking for `unittest.bask`.

**Comment by zhexuany** [comment] 2016-08-09 03:53
Especially, when I try to run `test-setup.sh` from bazel's root. My terminal promote as follow:
```
./src/test/shell/bazel/test-setup.sh
/Users/zhexuany/repo/bazel/src/test/shell/bazel/testenv.sh: line 34: ./io_bazel/src/test/shell/unittest.bash: No such file or directory
```
But project root name is `bazel'. I wish you could give me some guide about how to use bash test suite framework.

**Comment by meteorcloudy** [comment] 2016-08-09 08:15
You should use `bazel test //src/test/shell/bazel:cc_inc_library_test` to run the test. `io_bazel` is the workspace name defined in WORKSPACE file, the `io_bazel` directory will be created by Bazel under runfiles directory when it's building the target.

**Comment by zhexuany** [comment] 2016-08-09 18:41
That is really nice. I should be able to finish writing test file for my changes tonight. Thanks for the guide. :)

**Comment by meteorcloudy** [comment] 2016-08-10 11:04
You are welcome :)

**Comment by PiotrSikora** [comment] 2016-08-23 22:39
@zhexuany, did you ever open a pull request with your fix?

**Comment by zhexuany** [comment] 2016-08-23 23:41
I did not. But I already push my changes into grerrit code review system. In addition, I am still working on this. For some cease, I did not consider. 

I am working on it now. I hope I can come up with a correct solution soon.

**Comment by Lunarsong** [comment] 2016-11-04 07:54
Any update on this?

**Comment by zhexuany** [comment] 2016-11-05 08:54
I submitted my latest changes already for more than a month. But I have not
received any review from bazel member.

**Comment by mhlopko** [comment] 2016-11-07 14:20
@zhexuany I see quite some reviews here: https://bazel-review.googlesource.com/c/5411/ Can you take a look?

**Comment by Helcaraxan** [comment] 2016-11-10 12:11
Hey there. This issue is currently blocking me so I would also be very interested in knowing what the status is for the code review and if it will be merged soon.

**Comment by petemounce** [comment] 2016-11-10 12:38
This is also blocking me. Would it be possible to link to the PR/gerrit?

**Comment by mhlopko** [comment] 2016-11-10 12:45
The PR is reviewed here: https://bazel-review.googlesource.com/c/5411/
We're waiting for @zhexuany.

**Comment by zhexuany** [comment] 2016-11-10 15:11
Hi, Sorry for the late. I was pretty for my own development. I will take a look right now. Thanks for the waiting.

**Comment by zhexuany** [comment] 2016-11-10 18:13
I just checked the code review. I did some fixes right after the bazel member gave me some useful comments. But I am not sure why things stuck there. 
I am pretty willing devote some time on this, but not right now. I have some free time this weekend, may be I could start from there. 

zhexuany

**Comment by lberki** [comment] 2016-12-05 12:51
`cc_inc_library` is slated to be removed anyway. However, we just added the `include_prefix` and `strip_include_prefix` attributes to `cc_library`:

https://github.com/bazelbuild/bazel/commit/aa60e7dc6b7ab6252e09d58359f4e9680a8ab334

Design doc is here:

https://docs.google.com/document/d/18qUWh0uUiJBv6ZOySvp6DEV0NjVnBoEy-r-ZHa9cmhU

Does this help your use case?

**Comment by dfr** [comment] 2016-12-05 15:30
This looks like it will work for me

**Comment by lberki** [comment] 2016-12-09 15:03
Excellent! Closing this bug then. `cc_inc_library` will go away once we are certain enough that the new features of `cc_library` can take its place.

**Closed by lberki** 2016-12-09 15:03 UTC
Labels: category: extensibility > external repositories, P2, type: bug
