### ISSUE TITLE
OSX CC wrapper issues (RPATH, dynamic libraries)

### ISSUE THREAD

**Issue by k6project** [bazelbuild/bazel#1576] opened 2016-07-27 11:23 UTC
I have encountered a number of issues while building:
1. Multiple RPATH entries: when buildind cc_library and linking it against several pre-built third-party libraries (each library is provided as a cc_library rule with lib binary in "srcs" attribute), multiple "-Wl,-rpath" options are generated, but the CC wrapper for OSX seems to consider only one
2. CC wrapper seems not to look for .dylib files when searching libraries, only *.so
3. When substituting install names for libraries, wrapper fails in case install_name is not a pathname (for third party libraries can be simply libSomeLib.so). (might be better to just use otool -D <library file> | tail -1)

**Comment by damienmg** [comment] 2016-07-27 11:26
2. is a duplicate of #407 

1. is a known issue but weird enough I cannot find a bug for it.

3. is new to me.

**Comment by mhlopko** [comment] 2017-08-30 11:11
1) fixed in https://github.com/bazelbuild/bazel/commit/f426544e67170d31b9d228ecf4cdc4b6ce1ba00d

Next to come :)

**Comment by mhlopko** [comment] 2018-03-20 21:18
I declare 2. fixed :)
3 coming as soon as I have a free evening :)

**Comment by sgowroji** [comment] 2023-01-23 09:15
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.

**Closed by sgowroji** 2023-01-23 09:15 UTC
Labels: type: bug, P3, team-Rules-CPP
