### ISSUE TITLE
TensorFlow CI failing on Windows

### ISSUE THREAD

**Issue by kchodorow** [bazelbuild/bazel#2510] opened 2017-02-08 17:34 UTC
See http://ci.bazel.io/job/TensorFlow/BAZEL_VERSION=HEAD,PLATFORM_NAME=windows-x86_64/658/ and http://ci.bazel.io/job/TensorFlow/658/BAZEL_VERSION=latest,PLATFORM_NAME=windows-x86_64/console.  Looks like the failures are for different causes.

**Comment by laszlocsomor** [comment] 2017-02-08 17:36
Adding @meteorcloudy who is the expert in the domain.

**Comment by meteorcloudy** [comment] 2017-02-08 17:49
The failures on HEAD seems to be caused by their own changes. And latest is failing due to https://github.com/bazelbuild/bazel/issues/2494, which should be fixed by a workaround from https://github.com/tensorflow/tensorflow/commit/dcd90e5cb2cfe5bb7c73a16a31bff9a75f954826. Not sure what triggered it again.

I'll keep digging.

**Comment by damienmg** [comment] 2017-02-17 14:00
Removing from Release blocker: this is not Bazel's fault.

**Comment by meteorcloudy** [comment] 2017-03-08 17:28
TensorFlow with HEAD is already green again, latest will be green after having the release.

**Closed** 2017-03-27 09:53 UTC
Labels: category: multi-platform > windows, P1, type: bug
