### ISSUE TITLE
bazel looks for BUILD files under convenience symlinks and fails if `--output-user-root` was used earlier

### ISSUE THREAD

**Issue by mafanasyev-tri** [bazelbuild/bazel#3268] opened 2017-06-26 20:00 UTC
### Description of the problem / feature request / question:

Normally, Bazel ignores `bazel-*` links when searching for BUILD files, but this mechanism breaks if the links point to the wrong place, for example because a previous run was done with different value of output-user-root.
 
As a result, if you run builds with and without  `--output-user-root` option, you will get weird errors.

(this bug was discovered as we tried to run bazel in a container so we can freeze host libraries/compiler versions; however, it does not require containers for reproduction)

### If possible, provide a minimal example to reproduce the problem:

```
# Create a minimal bazel repo
rm -rf t1&& mkdir t1 
cd t1
touch WORKSPACE test.sh && chmod a+x test.sh
echo 'sh_test(name="test", size="small", srcs=["test.sh"])' > BUILD

# normal build
bazel test //...
# build with alternate root
bazel --output_user_root=/tmp/a1 test //...
```
Error message:
```
Extracting Bazel installation...
.
ERROR: error loading package 'bazel-t1/external/bazel_tools/tools/build_defs/pkg': Extension file not found. Unable to load package for '//tools/build_defs/pkg:pkg.bzl': BUILD file not found on package path.
ERROR: error loading package 'bazel-t1/external/bazel_tools/tools/build_defs/pkg': Extension file not found. Unable to load package for '//tools/build_defs/pkg:pkg.bzl': BUILD file not found on package path.
INFO: Elapsed time: 4.266s
ERROR: Couldn't start the build. Unable to run tests.
```

### Environment info
* Operating System:
Ubuntu 16.04.2 LTS x86_64

* Bazel version (output of `bazel info release`):
release 0.5.1

###  Have you found anything relevant by searching the web?
There are two related bugs in the bug tracker:
https://github.com/bazelbuild/bazel/issues/1083 (Bazel can't exclude directories)
https://github.com/bazelbuild/bazel/issues/2460 (Please let me exclude some directories when running `bazel test //...`)
Both of them recommend using ` --deleted_packages`. This option does not really work -- it is non-recursive, so it will be completely impractical in larger codebases (and I could not get it to work even for this toy example). Moreover, we may even have non-traversable hierarchies, for example one of our projects contains symlinks to / in bazel-src, which generate a symlink loop.

### Other information
There is a workaround, as only `//...` invocation seems to be affected. Running bazel with non-wildcard target does not trigger that error, and updates the links to the proper value. Still, it would be much cleaner if bazel would do this automatically.

**Comment by sgowroji** [comment] 2023-02-17 05:55
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen (or ping me to reopen) if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.

**Comment by mafanasyev-tri** [comment] 2023-02-27 21:08
For those who find this ticket: The original issue is still present, but there is a simple workaround now using `.bazelignore`. Create a file, commit into your repo, and it'll now work:
```
ls -d bazel-*/ > .bazelignore
```
(note that `*` do not work in `.bazelignore`, hence `ls` call)

**Comment by brentleyjones** [comment] 2023-02-27 22:55
@bazelbuild/triage not stale

**Comment by keertk** [comment] 2023-02-27 22:58
@meteorcloudy could you advise on how to proceed with this issue please?

**Comment by crt-31** [comment] 2023-12-13 02:07
Bump.
This is really needed. Otherwise output_path option is unusable (amongst other issues).

**Comment by fmeum** [comment] 2023-12-13 07:50
@meteorcloudy I think that this bug may be the cause of https://github.com/bazelbuild/bazel-central-registry/pull/1188, the nested Bazel invocation doesn't pick up the `--output_user_root` flag.

**Comment by meteorcloudy** [comment] 2023-12-13 10:39
I bumped the priority and added the `help wanted` label since I'm afraid the Bazel team currently doesn't have capacity to look into this.

**Comment by Wyverald** [comment] 2024-03-05 19:05
Looks like this was fixed by https://github.com/bazelbuild/bazel/commit/8f74acef5f394e2b4cbcbed9ea73ad2b4fbaede7

**Closed by Wyverald** 2024-03-05 19:05 UTC
Labels: type: bug, P2, team-OSS, help wanted
