### ISSUE TITLE
Change objc_enable_binary_stripping default value to "true"

### ISSUE THREAD

**Issue by rahul-malik** [bazelbuild/bazel#3731] opened 2017-09-13 23:36 UTC
Please provide the following information. The more we know about your system and use case, the more easily and likely we can help.

### Description of the problem / feature request / question:
Given that the flag has no effect on debug builds, it seems that stripping dead code / symbols should be the default to minimize the size of your objc binary. Without this you will be shipping much larger artifacts than you normally would intend to and can affect user acquisition of your product.

### If possible, provide a minimal example to reproduce the problem:
Build any large application and release it to the app store

### Environment info
* Operating System:
macOS Sierra

* Bazel version (output of `bazel info release`):
0.5.3

###  Have you found anything relevant by searching the web?
Nope.

### Anything else, information or logs or outputs that would be helpful?
(If they are large, please upload as attachment or provide link).

Enabling this flag has reduce the size of our application by roughly 50% and it was expected that release builds (compilation_mode opt) would have had this enabled by default. This caught my team by surprise so I'd like to prevent that from happening to other developers as well.

**Comment by laszlocsomor** [comment] 2017-09-19 16:35
@c-parsons , @aragos : WDYT?

**Comment by c-parsons** [comment] 2017-09-19 17:22
We shouldn't do this as is.
I have been following up in https://github.com/bazelbuild/bazel/pull/3756.
In short, flipping this to true will break ios_framework.

**Comment by laszlocsomor** [comment] 2017-09-20 06:07
Duplicate of https://github.com/bazelbuild/bazel/pull/3756

**Closed by laszlocsomor** 2017-09-20 06:07 UTC
Labels: category: rules > ObjC / iOS / J2ObjC
