### ISSUE TITLE
12ab12e80ad1c9a3510aa4bbfdf3fddafc0bca00 breaks testing bazel with bazel

### ISSUE THREAD

**Issue by hlopko** [bazelbuild/bazel#7344] opened 2019-02-04 15:42 UTC
Culprit finder found 12ab12e80ad1c9a3510aa4bbfdf3fddafc0bca00 as a cause of https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/770#50212246-b050-4b2b-8f0d-b9b2c4c224f3 (culprit finder run: https://buildkite.com/bazel/culprit-finder/builds/91#851af1f7-4cf2-4a17-8cf8-e69e74093b9a)

**Comment by buchgr** [comment] 2019-02-05 10:04
duplicate of https://github.com/bazelbuild/bazel/issues/4663

**Closed by buchgr** 2019-02-05 10:04 UTC
Labels: P1, breakage, category: remote execution / caching, team-Remote-Exec

**Comment by hlopko** [comment] 2019-02-05 10:07
Thanks for looking into it!
