### ISSUE TITLE
No way to tell .bazelignore to ignore all folders of the given name

### ISSUE THREAD

**Issue by gregmagolan** [bazelbuild/bazel#8106] opened 2019-04-21 20:28 UTC
### Description of the problem / feature request:

A `.bazelignore` pattern such as
```
node_modules
```
only ignores the `node_modules` folder at the root level where the `.bazelignore` file is. This means that in nodejs projects, every single `node_modules` folder needs to be explicitly listed in `.bazelignore`.

Not ignoring a node_modules folder can lead to unexpected build errors as these folders contain downloaded npm dependencies that may contain BUILD files that should be ignored. `node_modules` folders are almost always all untracked and ignored in `.gitignore` so there are often left around in subdirectories when changing git branches and these are not easily noticed as they are ignored by git.

### Feature requests: what underlying problem are you trying to solve with this feature?

Have `.bazelignore` patterns that don't start with `/` match in any directory. This would match the behavior of `.gitignore`. For example:

```
# ignore root /node_modules folder
/node_modules

# ignore all folders named node_modules in the root directory or in subdirectories
node_modules
```

### What operating system are you running Bazel on?

OSX

### What's the output of `bazel info release`?

release 0.24.0

### Any other information, logs, or outputs that you want to share?

For reference:

* Some good examples of how .gitignore patterns are interpreted: https://www.atlassian.com/git/tutorials/saving-changes/gitignore
* The official .gitignore docs that are harder to follow: https://git-scm.com/docs/gitignore

**Comment by gregmagolan** [comment] 2019-04-21 20:31
@alexeagle This issue will be a problem for rules_nodejs users after https://github.com/bazelbuild/rules_nodejs/pull/704 lands since every yarn_install & npm_install rule will create a node_modules folder somewhere in the user's WORKSPACE that will be ignored by git by default but not by bazel.

**Comment by kylecordes** [comment] 2019-10-24 18:22
Indeed, this is a problem.

Expected behavior, from working with other tools that have a ".ignore" file, would be that `node_modules` ignores that dir anywhere in the tree, while `/node_modules` ignores it only adjacent to the .ignore file.

**Comment by brandjon** [comment] 2021-02-17 22:31
This sounds like a reasonable request. I'm a bit worried that it might be too easy to accidentally exclude a directory, and wonder if the use of a wildcard syntax on anchored patterns might help make it more explicit. But then again, it's probably better to be consistent with .gitignore syntax.

**Comment by nkoroste** [comment] 2021-02-18 01:53
> better to be consistent with .gitignore syntax

+1 to this

**Comment by aiuto** [comment] 2022-01-11 19:30
This is a duplicate of #7093

**Comment by brandjon** [comment] 2022-11-04 19:28
Closing as dup of #7093.

**Closed by brandjon** 2022-11-04 19:28 UTC
Labels: type: feature request, P4, team-Build-Language
