### ISSUE TITLE
remote_download_outputs=toplevel doesn't download libraries in `cc_import` needed to run.

### ISSUE THREAD

**Issue by wesleyw72** [bazelbuild/bazel#11532] opened 2020-06-02 08:05 UTC
### Description of the problem / feature request:

I have a `cc_binary` target which depends on a DSO in the following way.

```
cc_binary(
  name = "my_binary",
  deps = [":stuff", ":import_lib"],
)

cc_library(
  name = "import_lib",
  deps = [":libfoo_lib", ":another_thing"]
)

cc_import(
  name = "libfoo_lib",
  shared_library = ":libfoo.so",
)

cc_binary(
  name = "libfoo.so",
  srcs = ["blah.cpp"],
  linkshared = 1,
  linkstatic = 1,
)
```

When a machine does `bazel run :my_binary`, it's not downloading `libfoo.so` and then producing an error like:
```
error while loading shared libraries: libfoo.so: cannot open shared object file: No such file or directory
```

It seems that it doesn't recognise that `libfoo.so` is necessary for execution.

### What operating system are you running Bazel on?

Ubuntu 16.04

### What's the output of `bazel info release`?

> Replace this line with your answer.

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

release 1.2.1

**Comment by ulfjack** [comment] 2020-06-02 12:20
I can reproduce the issue at HEAD. The reason is that `libfoo.so` in the `cc_binary` runfiles is a symlink to the actual `libfoo.so` file, and the code implementing the flag isn't aware of symlinks. I have a fix for this.

**Comment by ulfjack** [comment] 2020-06-02 12:21
@buchgr

**Comment by wesleyw72** [comment] 2020-06-04 19:27
Thanks @ulfjack for looking at this and proposing a fix so quickly!

**Closed** 2020-09-21 21:52 UTC
Labels: team-Rules-CPP, untriaged
