### ISSUE TITLE
Release 3.3 - June 2020

### ISSUE THREAD

**Issue by laurentlb** [bazelbuild/bazel#11358] opened 2020-05-11 17:37 UTC
Cut date: 2020-06-01

**Comment by katre** [comment] 2020-06-02 12:17
# Status of Bazel 3.3

- Target baseline: 2020/06/02
- Expected release date: 2020/06/16
- [List of release blockers](https://github.com/bazelbuild/bazel/labels/Release%20blocker)

To report a release-blocking bug, please file a bug using the `Release blocker` label, and cc me.

Task list:

- [ ] Update GitHub issues for incompatible changes
- [ ] Pick release baseline: c063b5caf776dee665497b64c5c17d4ed7e6750a
- [ ] Create release candidate:
- [ ] Check downstream projects:
- [ ] [Create draft release announcement](https://docs.google.com/document/d/1wDvulLlj4NAlPZamdlEVFORks3YXJonCjyuQMUQEmB0/edit)
- [ ] Send for review the release announcement PR:
- [ ] Push the release, notify package maintainers:
- [ ] Update the documentation
- [ ] Push the blog post
- [ ] Update the [release page](https://github.com/bazelbuild/bazel/releases/)

**Comment by katre** [comment] 2020-06-02 12:18
Using c063b5caf776dee665497b64c5c17d4ed7e6750a as the baseline, the only issue with the nightly is Envoy, which appears to be a longstanding configuration issue and not due to Bazel: https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/1512#_

**Comment by katre** [comment] 2020-06-02 13:34
Release is cut (candidate is at https://releases.bazel.build/3.3.0/rc1/index.html), waiting for downstream tests: https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/1513

**Comment by katre** [comment] 2020-06-02 14:34
Downstream tests all pass.

**Comment by keith** [comment] 2020-06-02 15:23
You might want to remove the `incompatible_objc_compile_info_migration` related points from the release notes since it was flipped and then reverted

**Comment by katre** [comment] 2020-06-02 15:28
It's removed from the [draft release notes](https://docs.google.com/document/d/1wDvulLlj4NAlPZamdlEVFORks3YXJonCjyuQMUQEmB0/edit#).

When the release is finalized I'll clean up the notes in Github.

**Comment by katre** [comment] 2020-06-11 13:25
I'm declaring #11581 as a release blocker, because incomplete documentation is a serious problem. The fix is in progress so I'll cherry-pick it to a new RC shortly.

**Comment by katre** [comment] 2020-06-11 18:18
Creating RC2:
```
$ scripts/release/release.sh create --force_rc=2 3.3.0 c063b5caf776dee665497b64c5c17d4ed7e6750a cb798a475eb54087e1e83f8aa1dc1c54550877b5
$ scripts/release/release.sh push
```

Release is available at https://releases.bazel.build/3.3.0/rc2/index.html, waiting for downstream tests.

**Comment by katre** [comment] 2020-06-11 19:06
Downstream tests: https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/1523

The failures in rules_python are the same at [Bazel HEAD](https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/1522), so I don't think the release is to blame.

**Comment by katre** [comment] 2020-06-17 13:18
Release is pushed: https://github.com/bazelbuild/bazel/releases/tag/3.3.0

@vbatts @petemounce @excitoon: can you update your packages?

**Comment by konste** [comment] 2020-06-17 13:30
New flag --experimental_windows_watchfs supposed to appear in 3.3.0 but I don't see it in release notes.

**Comment by katre** [comment] 2020-06-17 13:33
@konste It's from before the baseline, so should be in. However, the change author didn't add a RELNOTES, and we don't note every changed flag (especially for experimental flags) by default.

**Comment by katre** [comment] 2020-06-17 14:36
Documentation and homebrew are updated.

**Comment by jin** [comment] 2020-06-26 08:08
3.3.0 has a regression with Android rules' desugar actions in persistent worker mode: https://github.com/bazelbuild/bazel/issues/11618

I've submitted https://github.com/bazelbuild/bazel/commit/3b0439e37247a480e08337a6314d06231bdbafd3 to fix it, along with tests in it to increase the coverage. 

Could this be cherry-picked into 3.3.1 please?

**Comment by katre** [comment] 2020-06-26 15:39
I'll cherrypick this and start 3.3.1 today.

**Comment by katre** [comment] 2020-06-26 15:48
Creating release:
```
$ scripts/release/release.sh create --force_rc=1 3.3.1 3.3.0 3b0439e
```

**Comment by katre** [comment] 2020-06-26 16:46
RC1 is now available: https://releases.bazel.build/3.3.1/rc1/index.html

**Comment by katre** [comment] 2020-06-26 16:47
Downstream tests are running: https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/1541

**Comment by katre** [comment] 2020-06-26 18:02
Downstream tests are all green.

Assuming no further cherrypicks or blockers, I plan to release this next week.

**Comment by katre** [comment] 2020-06-30 15:13
FInalizing 3.3.1 today.

**Comment by katre** [comment] 2020-06-30 15:28
Release 3.3.1 is now available at https://github.com/bazelbuild/bazel/releases/tag/3.3.1

@vbatts @petemounce @excitoon: can you update your packages?

**Comment by vbatts** [comment] 2020-06-30 18:29
https://copr.fedorainfracloud.org/coprs/build/1515066

I totally missed pushing a build for 3.3.0 also, so I did that first

**Comment by jin** [comment] 2020-06-30 19:16
Thanks @katre!

**Comment by vbatts** [comment] 2020-06-30 19:20
hrm. Glad I did a build of 3.3.0 first, where only epel7-aarch64 failed (as it has).
So far on 3.3.1 it has also failed for fedora31-aarch64 and epel8-aarch64. (other aarch64 targets did succeed). Perhaps a memory constraint?
All other targets succeed.

**Closed** 2020-07-13 13:25 UTC
Labels: release
