### ISSUE TITLE
worker protocol seems to drop empty lines in argument file

### ISSUE THREAD

**Issue by johnynek** [bazelbuild/bazel#3329] opened 2017-07-06 02:27 UTC
### Description of the problem / feature request / question:
When using workers with an argument file, it seems empty lines are dropped. So, if you expect empty arguments and you are writing one argument per line, you get different behavior if you run in worker vs non-worker mode.

### If possible, provide a minimal example to reproduce the problem:
In the scala rules we have support for thrift using twitter scrooge. We have a worker implementation of this here: 

https://github.com/bazelbuild/rules_scala/blob/master/src/scala/scripts/TwitterScroogeGenerator.scala#L42

we set up our args file here:
https://github.com/bazelbuild/rules_scala/blob/master/twitter_scrooge/twitter_scrooge.bzl#L146

note we have 1 arg per line, and some may be empty strings, meaning the argument is optional.

When we run without worker we get, for instance, this argument file:
```
bazel-out/darwin_x86_64-fastbuild/bin/zoolander-thrift/src/main/thrift/com/stripe/thrift/api/libapi_srcjar.srcjar
bazel-out/darwin_x86_64-fastbuild/bin/zoolander-thrift/src/main/thrift/com/stripe/thrift/api/libpay_server_api_thrift_lib.jar


external/com_stripe_pay_server_api_thrift/jar/pay-server-api-thrift-0.0.1-SNAPSHOT.jar
```
when we run with worker, the created args looks like:
```
bazel-out/darwin_x86_64-fastbuild/bin/zoolander-thrift/src/main/thrift/com/stripe/thrift/api/libapi_srcjar.srcjar
bazel-out/darwin_x86_64-fastbuild/bin/zoolander-thrift/src/main/thrift/com/stripe/thrift/api/libpay_server_api_thrift_lib.jar
external/com_stripe_pay_server_api_thrift/jar/pay-server-api-thrift-0.0.1-SNAPSHOT.jar
```
note we have lost the empty lines. I *believe* bazel is in control of this, but maybe we have done something wrong.

we can work around by ensuring each line is non-empty:
https://github.com/bazelbuild/rules_scala/pull/245

### Environment info
* Operating System:
can see this behavior on linux and osx.

* Bazel version (output of `bazel info release`):
 `release 0.5.2-homebrew`

**Comment by philwo** [comment] 2017-07-10 15:07
This is caused by this check, which skips empty lines: https://github.com/bazelbuild/bazel/blob/4ca8b8f98f043ef624b2d1605d658aa39c2c63dc/src/main/java/com/google/devtools/build/lib/worker/WorkerSpawnStrategy.java#L275

I agree that this behavior is confusing. I'll send a fix for this.

**Closed** 2017-08-17 07:55 UTC
Labels: category: service APIs, P2, type: bug
