### ISSUE TITLE
//src/test/shell/bazel:rule_test_test fails on CI (OSX)

### ISSUE THREAD

**Issue by buchgr** [bazelbuild/bazel#2939] opened 2017-05-04 09:40 UTC
The test `test_local_rule_test_in_root` failed on OSX with

```
Server terminated abruptly (error code: 14, error message: '', log file: '...')
```

The error code maps to gRPC's `UNAVAILABLE` code, so this actually looks like the gRPC server crashed.

http://ci.bazel.io/job/Gerrit-bazel-tests/639/BAZEL_VERSION=latest,PLATFORM_NAME=darwin-x86_64/testReport/junit/(root)/(empty)/test_local_rule_test_in_root/

**Comment by buchgr** [comment] 2017-05-04 09:41
cc @damienmg

**Comment by damienmg** [comment] 2017-05-04 09:45
Probably a flake. /cc @lberki because gRPC.

**Comment by damienmg** [comment] 2017-05-04 16:30
This is irreproducible because we don't have access to the jvm.log file. We should probably output it if we are running under test.

Assigning to Lukacs to evaluate.

**Comment by lberki** [comment] 2017-05-05 07:15
Without a `jvm.log` there isn't a lot I can do.

**Comment by damienmg** [comment] 2017-05-05 07:21
I was actually asking for idea on what we could do to get the lot if that
happens again. Can we print it in certain case instead of just printing the
file path?

**Comment by damienmg** [comment] 2017-05-05 08:52
As discussed offline, in our test framework we should cat the jvm.log if we get that error.

**Closed** 2017-05-05 16:37 UTC
Labels: breakage, P2, Under investigation

**Comment by haxorz** [comment] 2017-05-20 02:12
fyi, this sounds possibly like a bug introduced by https://github.com/bazelbuild/bazel/commit/3e5edafa2a04a71cd3596e929e83222da725f3f9. it was diagnosed by @ericfelly internally. that commit was reverted in https://github.com/bazelbuild/bazel/commit/c4f271d1a68366b6fa5ff38ea7d951b6a22af044. @philwo fixed the underlying issue recently with https://github.com/bazelbuild/bazel/commit/67cea8f01e93b9723c8acfcd8ef9f83a7f025088 (see the third line of the commit message for the bug).

given that i'm pretty sure bazel.io was affected by another bug with the initial commit (see https://github.com/bazelbuild/bazel/issues/2985), it's likely you're also being affected by this bug.
