### ISSUE TITLE
Wrong Android NDK libcpp include path

### ISSUE THREAD

**Issue by renning22** [bazelbuild/bazel#3641] opened 2017-08-30 00:03 UTC
### If possible, provide a minimal example to reproduce the problem:
Build with --crosstool_top=@androidndk//:toolchain-libcpp, C++ headers can not be found.
I guess it's caused by wrong "-isystem" paths.

Bazel sets "external/androidndk/ndk/sources/cxx-stl/llvm-libc++/libcxx/include" but it should be "external/androidndk/ndk/sources/cxx-stl/llvm-libc++/include". (I inspected with NDK r13/r15.) 

### Environment info
* Operating System:
Ubuntu 14.04

* Bazel version (output of `bazel info release`):
0.5.2 (also tried with 0.4.5)

**Comment by aj-michael** [comment] 2017-08-30 16:46
This seems to have been a change between R12 and R13.

**Comment by aj-michael** [comment] 2017-08-31 16:03
@renning22 , can you give an example of a header that cannot be found and a full bazel command line?

**Comment by kangnak** [comment] 2017-09-13 06:15
I have the same issue. All C++ headers like <string> are not found. As Ning told, I verified the include dir is set wrong in bazel-<project>/external/androidndk/BUILD.bazel. I used this command to build:
bazel build <build rule>  --cpu=armeabi-v7a --crosstool_top=@androidndk//:toolchain-libcpp --host_crosstool_top=@bazel_tools//tools/cpp:toolchain

**Comment by aj-michael** [comment] 2017-09-15 19:32
workaround: @androidndk//:toolchain-stlport and @androidndk//:toolchaingnu-libstdcpp are correct in bazel 0.5.4. Working on fixing @androidndk//:toolchain-libcpp now.

**Comment by Qining** [comment] 2018-02-09 06:28
Same issue here when compiling gRPC with Bazel and NDK. Using `gnu-libstdcpp` and `stlport` results into `to_string is not a member of std`. Any workaround available?

**Comment by etnu** [comment] 2018-02-12 07:24
gnu-libstdcpp for android doesn't implement many basic standard library features correctly. It's not even supported by android anymore as far as I know.

Consequently, it's very difficult to have shared libraries between android and other platforms until this bug is fixed, so my project is stuck using cmake just for android.

Is there a workaround that lets us use the default standard library?

**Comment by ncouro** [comment] 2018-02-13 09:43
Same issue here, a few C++11 headers cannot be found when building using `toolchain-libcpp`.  

I got it to build by manually changing the include paths in the build file from the `androidndk` repository.  I've put the new build rule there: https://github.com/ncouro/bazel_ndk in case it's useful to anyone. 

I could try making the changes upstream with some guidance (I'm new to Android and Bazel).

**Comment by jin** [comment] 2018-02-13 21:22
@ncouro that is excellent! I have a change in progress internally for r15 support, but let me externalize that into a PR - give me some time to go through your code and see if we can get our efforts to converge.

The main NDK 16 support thread is here: https://github.com/bazelbuild/bazel/issues/4068

**Comment by farwayer** [comment] 2018-02-14 02:11
`-stlport` and `-gnu-libstdcpp` is not workaround in many cases...

**Comment by jin** [comment] 2018-02-20 18:29
Root cause: generated BUILD.bazel for r13 is incorrect.

```
jingwen@jingwen:~/code/tensorflow/bazel-tensorflow/external/androidndk
$ grep -o -E "ndk/sources.*\\+.*[^\*]\/" BUILD.bazel | xargs file | sort | uniq
ndk/sources/cxx-stl/gabi++/:                                     directory
ndk/sources/cxx-stl/gabi++/include/:                             directory
ndk/sources/cxx-stl/gnu-libstdc++/4.9/:                          directory
ndk/sources/cxx-stl/gnu-libstdc++/4.9/include/backward/:         directory
ndk/sources/cxx-stl/gnu-libstdc++/4.9/include/:                  directory
ndk/sources/cxx-stl/gnu-libstdc++/4.9/libs/arm64-v8a/:           directory
ndk/sources/cxx-stl/gnu-libstdc++/4.9/libs/arm64-v8a/include/:   directory
ndk/sources/cxx-stl/gnu-libstdc++/4.9/libs/armeabi/:             directory
ndk/sources/cxx-stl/gnu-libstdc++/4.9/libs/armeabi/include/:     directory
ndk/sources/cxx-stl/gnu-libstdc++/4.9/libs/armeabi-v7a/:         directory
ndk/sources/cxx-stl/gnu-libstdc++/4.9/libs/armeabi-v7a/include/: directory
ndk/sources/cxx-stl/gnu-libstdc++/4.9/libs/mips64/:              directory
ndk/sources/cxx-stl/gnu-libstdc++/4.9/libs/mips64/include/:      directory
ndk/sources/cxx-stl/gnu-libstdc++/4.9/libs/mips/:                directory
ndk/sources/cxx-stl/gnu-libstdc++/4.9/libs/mips/include/:        directory
ndk/sources/cxx-stl/gnu-libstdc++/4.9/libs/x86_64/:              directory
ndk/sources/cxx-stl/gnu-libstdc++/4.9/libs/x86_64/include/:      directory
ndk/sources/cxx-stl/gnu-libstdc++/4.9/libs/x86/:                 directory
ndk/sources/cxx-stl/gnu-libstdc++/4.9/libs/x86/include/:         directory
ndk/sources/cxx-stl/llvm-libc++abi/libcxxabi/:                   directory
ndk/sources/cxx-stl/llvm-libc++abi/libcxxabi/include/:           directory
ndk/sources/cxx-stl/llvm-libc++/libcxx/:                         directory
ndk/sources/cxx-stl/llvm-libc++/libcxx/include/:                 directory
ndk/sources/cxx-stl/llvm-libc++/libs/arm64-v8a/:                 directory
ndk/sources/cxx-stl/llvm-libc++/libs/armeabi/:                   directory
ndk/sources/cxx-stl/llvm-libc++/libs/armeabi-v7a/:               directory
ndk/sources/cxx-stl/llvm-libc++/libs/mips64/:                    directory
ndk/sources/cxx-stl/llvm-libc++/libs/mips/:                      directory
ndk/sources/cxx-stl/llvm-libc++/libs/x86_64/:                    directory
ndk/sources/cxx-stl/llvm-libc++/libs/x86/:                       directory
 
 
jingwen@jingwen:~/code/tensorflow/bazel-tensorflow/external/androidndk
$ grep -o -E "ndk/sources.*\\+.*[^\*]\/" BUILD.bazel | xargs file | sort | uniq
ndk/sources/cxx-stl/gabi++/:                                     directory
ndk/sources/cxx-stl/gabi++/include/:                             directory
ndk/sources/cxx-stl/gnu-libstdc++/4.9/:                          directory
ndk/sources/cxx-stl/gnu-libstdc++/4.9/include/backward/:         directory
ndk/sources/cxx-stl/gnu-libstdc++/4.9/include/:                  directory
ndk/sources/cxx-stl/gnu-libstdc++/4.9/libs/arm64-v8a/:           directory
ndk/sources/cxx-stl/gnu-libstdc++/4.9/libs/arm64-v8a/include/:   directory
ndk/sources/cxx-stl/gnu-libstdc++/4.9/libs/armeabi/:             directory
ndk/sources/cxx-stl/gnu-libstdc++/4.9/libs/armeabi/include/:     directory
ndk/sources/cxx-stl/gnu-libstdc++/4.9/libs/armeabi-v7a/:         directory
ndk/sources/cxx-stl/gnu-libstdc++/4.9/libs/armeabi-v7a/include/: directory
ndk/sources/cxx-stl/gnu-libstdc++/4.9/libs/mips64/:              directory
ndk/sources/cxx-stl/gnu-libstdc++/4.9/libs/mips64/include/:      directory
ndk/sources/cxx-stl/gnu-libstdc++/4.9/libs/mips/:                directory
ndk/sources/cxx-stl/gnu-libstdc++/4.9/libs/mips/include/:        directory
ndk/sources/cxx-stl/gnu-libstdc++/4.9/libs/x86_64/:              directory
ndk/sources/cxx-stl/gnu-libstdc++/4.9/libs/x86_64/include/:      directory
ndk/sources/cxx-stl/gnu-libstdc++/4.9/libs/x86/:                 directory
ndk/sources/cxx-stl/gnu-libstdc++/4.9/libs/x86/include/:         directory
ndk/sources/cxx-stl/llvm-libc++abi/libcxxabi/:                   cannot open `ndk/sources/cxx-stl/llvm-libc++abi/libcxxabi/' (No such file or directory)
ndk/sources/cxx-stl/llvm-libc++abi/libcxxabi/include/:           cannot open `ndk/sources/cxx-stl/llvm-libc++abi/libcxxabi/include/' (No such file or directory)
ndk/sources/cxx-stl/llvm-libc++/libcxx/:                         cannot open `ndk/sources/cxx-stl/llvm-libc++/libcxx/' (No such file or directory)
ndk/sources/cxx-stl/llvm-libc++/libcxx/include/:                 cannot open `ndk/sources/cxx-stl/llvm-libc++/libcxx/include/' (No such file or directory)
ndk/sources/cxx-stl/llvm-libc++/libs/arm64-v8a/:                 directory
ndk/sources/cxx-stl/llvm-libc++/libs/armeabi/:                   directory
ndk/sources/cxx-stl/llvm-libc++/libs/armeabi-v7a/:               directory
ndk/sources/cxx-stl/llvm-libc++/libs/mips64/:                    directory
ndk/sources/cxx-stl/llvm-libc++/libs/mips/:                      directory
ndk/sources/cxx-stl/llvm-libc++/libs/x86_64/:                    directory
ndk/sources/cxx-stl/llvm-libc++/libs/x86/:                       directory
```

**Comment by jin** [comment] 2018-02-22 00:46
fix is incoming here: https://bazel-review.googlesource.com/c/bazel/+/40712

The patchdiffs on Gerrit are a little bit wonky, however.

**Closed** 2018-02-23 18:01 UTC
Labels: category: rules > android, type: bug

**Comment by jin** [comment] 2018-02-23 18:06
Hi all, the fix for this is in master. Please feel free to try it out and let me know if you still face problems - thanks!
