### ISSUE TITLE
failed to install bazel on RedHat 6.5

### ISSUE THREAD

**Issue by 333caowei** [bazelbuild/bazel#1208] opened 2016-04-28 15:04 UTC
##### Here is the information of my cluster:

```[chaowei@mgt ~]$ cat /etc/redhat-release Red Hat Enterprise Linux Server release 6.5 (Santiago)```

##### The default gcc of system is 4.4.7. But I install a new gcc in my local path:
```[chaowei@mgt ~]$ gcc -v Using built-in specs. COLLECT_GCC=gcc COLLECT_LTO_WRAPPER=/gpfs/home/chaowei/software/gcc-4.8.4/libexec/gcc/x86_64-unknown-linux-gnu/4.8.4/lto-wrapper Target:x86_64-unknown-linux-gnu Configured with：./configure --prefix=/gpfs/home/chaowei/software/gcc-4.8.4 --with-mpfr=/gpfs/home/chaowei/software/mpfr-3.1.4/ --with-gmp=/gpfs/home/chaowei/software/gmp-6.1.0/ --with-mpc=/gpfs/home/chaowei/software/mpc-1.0.3/ Thread model: posix gcc version 4.8.4 (GCC)```

##### Here is my .bash_profile:
```.bash_profile

PATH=$PATH:$HOME/bin

PYTHON_HOME=/gpfs/home/chaowei/software/python-3.4.3
JAVA_HOME=/gpfs/home/chaowei/software/jdk1.8.0_91
CLASSPATH=.:$JAVA_HOME/lib/dt.jar:$JAVA_HOME/lib/tools.jar

OPENSSL=/gpfs/home/chaowei/software/openssl-1.0.1
GMP=/gpfs/home/chaowei/software/gmp-6.1.0
MPFR=/gpfs/home/chaowei/software/mpfr-3.1.4
MPC=/gpfs/home/chaowei/software/mpc-1.0.3
GCC=/gpfs/home/chaowei/software/gcc-4.8.4

export JAVA_HOME=$JAVA_HOME
export CLASSPATH=$CLASSPATH
export PATH=$PYTHON_HOME/bin:$JAVA_HOME/bin:$GCC/bin:$PATH

export LD_LIBRARY_PATH=$OPENSSL/ssl/lib:$OPENSSL/lib:$GMP/lib:$MPFR/lib:$MPC/lib:$GCC/lib:$LD_LIBRARY_PATH
```

##### I followed the answer of this link [tensorflow/tensorflow#110 replied by "rdipietro" to edit CROSSTOOL file. Here is my CROSSTOOL file:
```
toolchain {
abi_version: "local"
abi_libc_version: "local"
builtin_sysroot: ""
compiler: "compiler"
host_system_name: "local"
needsPic: true
supports_gold_linker: false
supports_incremental_linker: false
supports_fission: false
supports_interface_shared_objects: false
supports_normalizing_ar: false
supports_start_end_lib: false
supports_thin_archives: false
target_libc: "local"
target_cpu: "local"
target_system_name: "local"
toolchain_identifier: "local_linux"

tool_path { name: "ar" path: "/usr/bin/ar" }
tool_path { name: "compat-ld" path: "/usr/bin/ld" }
tool_path { name: "cpp" path: "/gpfs/home/chaowei/software/gcc-4.8.4/bin/cpp" }
tool_path { name: "dwp" path: "/usr/bin/dwp" }
tool_path { name: "gcc" path: "/gpfs/home/chaowei/software/gcc-4.8.4/bin/gcc" }
cxx_flag: "-std=c++0x"
linker_flag: "-lstdc++"
linker_flag: "-B/usr/bin/"

linker_flag: "-Wl,-R/gpfs/home/chaowei/software/gcc-4.8.4/lib64"

# TODO(bazel-team): In theory, the path here ought to exactly match the path
# used by gcc. That works because bazel currently doesn't track files at
# absolute locations and has no remote execution, yet. However, this will need
# to be fixed, maybe with auto-detection?
cxx_builtin_include_directory: "/usr/lib/gcc/"
cxx_builtin_include_directory: "/usr/local/include"
cxx_builtin_include_directory: "/usr/include"
tool_path { name: "gcov" path: "/usr/bin/gcov" }

cxx_builtin_include_directory: "/gpfs/home/chaowei/software/gcc-4.8.4/lib/gcc/x86_64-unknown-linux-gnu/4.8.4/include"
cxx_builtin_include_directory: "/gpfs/home/chaowei/software/gcc-4.8.4/lib/gcc/x86_64-unknown-linux-gnu/4.8.4/include-fixed"
cxx_builtin_include_directory: "/gpfs/home/chaowei/software/gcc-4.8.4/include/c++/4.8.4"

# C(++) compiles invoke the compiler (as that is the one knowing where
# to find libraries), but we provide LD so other rules can invoke the linker.
tool_path { name: "ld" path: "/usr/bin/ld" }

tool_path { name: "nm" path: "/usr/bin/nm" }
tool_path { name: "objcopy" path: "/usr/bin/objcopy" }
objcopy_embed_flag: "-I"
objcopy_embed_flag: "binary"
tool_path { name: "objdump" path: "/usr/bin/objdump" }
tool_path { name: "strip" path: "/usr/bin/strip" }

# Anticipated future default.
unfiltered_cxx_flag: "-no-canonical-prefixes"
unfiltered_cxx_flag: "-fno-canonical-system-headers"

# Make C++ compilation deterministic. Use linkstamping instead of these
# compiler symbols.
unfiltered_cxx_flag: "-Wno-builtin-macro-redefined"
unfiltered_cxx_flag: "-D__DATE__=\"redacted\""
unfiltered_cxx_flag: "-D__TIMESTAMP__=\"redacted\""
unfiltered_cxx_flag: "-D__TIME__=\"redacted\""

# Security hardening on by default.
# Conservative choice; -D_FORTIFY_SOURCE=2 may be unsafe in some cases.
# We need to undef it before redefining it as some distributions now have
# it enabled by default.
compiler_flag: "-U_FORTIFY_SOURCE"
compiler_flag: "-D_FORTIFY_SOURCE=1"
compiler_flag: "-fstack-protector"
linker_flag: "-Wl,-z,relro,-z,now"

# Enable coloring even if there's no attached terminal. Bazel removes the
# escape sequences if --nocolor is specified. This isn't supported by gcc
# on Ubuntu 14.04.
# compiler_flag: "-fcolor-diagnostics"

# All warnings are enabled. Maybe enable -Werror as well?
compiler_flag: "-Wall"
# Enable a few more warnings that aren't part of -Wall.
compiler_flag: "-Wunused-but-set-parameter"
# But disable some that are problematic.
compiler_flag: "-Wno-free-nonheap-object" # has false positives

# Keep stack frames for debugging, even in opt mode.
compiler_flag: "-fno-omit-frame-pointer"

# Anticipated future default.
linker_flag: "-no-canonical-prefixes"
# Have gcc return the exit code from ld.
linker_flag: "-pass-exit-codes"
# Stamp the binary with a unique identifier.
linker_flag: "-Wl,--build-id=md5"
linker_flag: "-Wl,--hash-style=gnu"
# Gold linker only? Can we enable this by default?
# linker_flag: "-Wl,--warn-execstack"
# linker_flag: "-Wl,--detect-odr-violations"

compilation_mode_flags {
mode: DBG
# Enable debug symbols.
compiler_flag: "-g"
}
compilation_mode_flags {
mode: OPT

# No debug symbols.
# Maybe we should enable https://gcc.gnu.org/wiki/DebugFission for opt or
# even generally? However, that can't happen here, as it requires special
# handling in Bazel.
compiler_flag: "-g0"

# Conservative choice for -O
# -O3 can increase binary size and even slow down the resulting binaries.
# Profile first and / or use FDO if you need better performance than this.
compiler_flag: "-O2"

# Disable assertions
compiler_flag: "-DNDEBUG"

# Removal of unused code and data at link time (can this increase binary size in some cases?).
compiler_flag: "-ffunction-sections"
compiler_flag: "-fdata-sections"
linker_flag: "-Wl,--gc-sections"
}
linking_mode_flags { mode: DYNAMIC }
}
```

##### But when I run ./compile, I get the error,
```
INFO: You can skip this first step by providing a path to the bazel binary as second argument:
INFO: ./compile.sh compile /path/to/bazel
Building Bazel from scratch......
Building Bazel with Bazel.
.WARNING: /tmp/bazel.alRY7gp4/out/external/bazel_tools/WORKSPACE:1: Workspace name in /tmp/bazel.alRY7gp4/out/external/bazel_tools/WORKSPACE (@io_bazel) does not match the name given in the repository's definition (@bazel_tools); this will cause a build error in future versions.
WARNING: /gpfs/home/chaowei/download/bazel/src/main/native/BUILD:46:16: in includes attribute of cc_binary rule //src/main/native:libunix.so: '.' resolves to 'src/main/native' not in 'third_party'. This will be an error in the future.
WARNING: /gpfs/home/chaowei/download/bazel/src/main/protobuf/BUILD:37:1: in includes attribute of cc_library rule //src/main/protobuf:command_server_cc_proto: '.' resolves to 'src/main/protobuf' not in 'third_party'. This will be an error in the future. Since this rule was created by the macro 'cc_grpc_library', the error might have been caused by the macro implementation in /gpfs/home/chaowei/download/bazel/tools/build_rules/genproto.bzl:104:18.
INFO: Found 1 target...
ERROR: /gpfs/home/chaowei/download/bazel/src/main/tools/BUILD:26:1: C++ compilation of rule '//src/main/tools:build-runfiles' failed: gcc failed: error executing command 
(cd /tmp/bazel.alRY7gp4/out/bazel && \
exec env - \
PATH=/gpfs/home/chaowei/software/python-3.4.3/bin:/gpfs/home/chaowei/software/jdk1.8.0_91/bin:/gpfs/home/chaowei/software/gcc-4.8.4/bin:/gpfs/mpicomplier/compiler/impi/4.1.0.024/intel64/bin:/gpfs/mpicomplier/compiler/composer_xe_2013.1.117/bin/intel64:/gpfs/mpicomplier/compiler/composer_xe_2013.1.117/mpirt/bin/intel64:/gpfs/mpicomplier/compiler/composer_xe_2013.1.117/bin/intel64:/gpfs/mpicomplier/compiler/composer_xe_2013.1.117/bin/intel64_mic:/gpfs/mpicomplier/compiler/composer_xe_2013.1.117/debugger/gui/intel64:/gpfs/lsf/9.1/linux2.6-glibc2.3-x86_64/etc:/gpfs/lsf/9.1/linux2.6-glibc2.3-x86_64/bin:/opt/xcat/bin:/opt/xcat/sbin:/opt/xcat/share/xcat/tools:/opt/xcat/bin:/opt/xcat/sbin:/opt/xcat/share/xcat/tools:/usr/lib64/qt-3.3/bin:/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin:/opt/ibutils/bin:/root/bin:/usr/lpp/mmfs/bin:/root/bin:/gpfs/home/chaowei/bin \
/gpfs/home/chaowei/software/gcc-4.8.4/bin/gcc -U_FORTIFY_SOURCE '-D_FORTIFY_SOURCE=1' -fstack-protector -Wall -Wl,-z,-relro,-z,now -B/gpfs/home/chaowei/software/gcc-4.8.4/bin -B/usr/bin -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer '-std=c++0x' -iquote . -iquote bazel-out/local-fastbuild/genfiles -iquote external/bazel_tools -iquote bazel-out/local-fastbuild/genfiles/external/bazel_tools -isystem external/bazel_tools/tools/cpp/gcc3 -no-canonical-prefixes -fno-canonical-system-headers -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' '-frandom-seed=bazel-out/local-fastbuild/bin/src/main/tools/_objs/build-runfiles/src/main/tools/build-runfiles.pic.o' -MD -MF bazel-out/local-fastbuild/bin/src/main/tools/_objs/build-runfiles/src/main/tools/build-runfiles.pic.d -fPIC -c src/main/tools/build-runfiles.cc -o bazel-out/local-fastbuild/bin/src/main/tools/_objs/build-runfiles/src/main/tools/build-runfiles.pic.o): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.
/gpfs/home/chaowei/software/gcc-4.8.4/libexec/gcc/x86_64-unknown-linux-gnu/4.8.4/cc1plus: error while loading shared libraries: libmpc.so.3: cannot open shared object file: No such file or directory
Target //src:bazel failed to build
INFO: Elapsed time: 3.540s, Critical Path: 0.11s

Building output/bazel
```

##### How can I do?

**Comment by meteorcloudy** [comment] 2016-04-28 15:41
Can you try to compile bazel from HEAD again, it looks like the same bug at #1190 , should already be fixed in commit [efebc4d](https://github.com/bazelbuild/bazel/commit/efebc4d1419ecfbab19dba305e8de34c9ced5351)

**Comment by 333caowei** [comment] 2016-04-29 04:58
@meteorcloudy Sorry, I have tried it from cloning again. But there is no use, the error is the same. The last line of error shows ```error while loading shared libraries: libmpc.so.3: cannot open shared object file: No such file or directory```, it seems ```libmpc.so.3``` is not found. But actually  I find it in ```/gpfs/home/chaowei/software/mpc-1.0.3/lib``` and I have added path in ```LD_LIBRARY_PATH``` as I showed above the question.

**Comment by 333caowei** [comment] 2016-05-04 07:35
After trying too many times, I fixed this problem. I downloaded the new gcc(6.1.0) and compiled it.
(using: ```cd gcc-6.1.0``` and ```./contrib/download_prerequisites```to download and compile gmp, mpfr, mpc automatically. )
Then I cloned the bazel source from GitHub and compiled it. It worked! It compiled bazel successfully. Then I tried to use bazel to compiled tensorflow, but there was some error. Fortunately,   I found the issue, the bazel version of I cloned from Github was 0.2.2b, it seems that it could not works on tensorflow. So I changed to bazel 0.1.4. Finally, it worked to compile tensorflow!

**Closed** 2016-05-04 07:35 UTC
Labels: P2, type: bug

**Comment by skgumma** [comment] 2016-07-21 04:11
Is the procedure changed for version Release 0.3.0 ? I tried the above options but always failing. My mpc libraries are not in standard location. Bazel never able to recognize that location.

**Comment by 333caowei** [comment] 2016-07-21 04:19
@skgumma Did you try to use  ./contrib/download_prerequisitesto download and compile gmp, mpfr, mvc automatically?

**Comment by skgumma** [comment] 2016-07-21 05:01
@333caowei no. We have gcc already installed in the system and I wanted to use them. Thanks for the prompt response.

**Comment by skgumma** [comment] 2016-07-21 08:38
Hi,

Below is the log of the compilation and i'm not able to find out how to resolve it. 

INFO: You can skip this first step by providing a path to the bazel binary as second argument:
INFO:    ./compile.sh compile /path/to/bazel
🍃  Building Bazel from scratch......
🍃  Building Bazel with Bazel.
.Unrecognized option: --verbose

Building output/bazel
[root@nscc01 bazel-0.3.0]# export EXTRA_BAZEL_ARGS='-s --verbose_failures --ignore_unsupported_sandboxing --genrule_strategy=standalone --spawn_strategy=standalone'
[root@nscc01 bazel-0.3.0]# ./compile.sh
INFO: You can skip this first step by providing a path to the bazel binary as second argument:
INFO:    ./compile.sh compile /path/to/bazel
🍃  Building Bazel from scratch......
🍃  Building Bazel with Bazel.
.WARNING: /tmp/bazel.XJM6j6Tl/out/external/bazel_tools/WORKSPACE:1: Workspace name in /tmp/bazel.XJM6j6Tl/out/external/bazel_tools/WORKSPACE (@io_bazel) does not match the name given in the repository's definition (@bazel_tools); this will cause a build error in future versions.
WARNING: /app/src/DEEPLEARNING/bazel-0.3.0/src/main/native/BUILD:52:16: in includes attribute of cc_binary rule //src/main/native:libunix.so: '.' resolves to 'src/main/native' not in 'third_party'. This will be an error in the future.
WARNING: /app/src/DEEPLEARNING/bazel-0.3.0/src/main/protobuf/BUILD:36:1: in includes attribute of cc_library rule //src/main/protobuf:command_server_cc_proto: '.' resolves to 'src/main/protobuf' not in 'third_party'. This will be an error in the future. Since this rule was created by the macro 'cc_grpc_library', the error might have been caused by the macro implementation in /app/src/DEEPLEARNING/bazel-0.3.0/tools/build_rules/genproto.bzl:104:18.
INFO: Found 1 target...
>>>>> # //third_party/grpc:cpp_plugin [action 'Creating runfiles tree bazel-out/host/bin/third_party/grpc/cpp_plugin.runfiles [for host]']
(cd /tmp/bazel.XJM6j6Tl/out/bazel-0.3.0 && \
  exec env - \
    PATH=/app/cuda/7.5/bin:/app/python/2.7.11/bin:/app/hdf5/1.8.16/gcc493/serial/bin:/app/gnuplot/5.0.3/bin:/app/gcc/4.9.3/bin:/app/binutils/2.26/bin:/usr/lib64/qt-3.3/bin:/app/pbs/bin:/opt/pbs/default/sbin:/opt/pbs/default/bin:/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin:/opt/ibutils/bin:/root/bin \
  /tmp/bazel.XJM6j6Tl/out/bazel-0.3.0/_bin/build-runfiles bazel-out/host/bin/third_party/grpc/cpp_plugin.runfiles_manifest bazel-out/host/bin/third_party/grpc/cpp_plugin.runfiles)
>>>>> # //src/main/tools:process-tools [action 'Compiling src/main/tools/process-tools.c']
(cd /tmp/bazel.XJM6j6Tl/out/bazel-0.3.0 && \
  exec env - \
    PATH=/app/cuda/7.5/bin:/app/python/2.7.11/bin:/app/hdf5/1.8.16/gcc493/serial/bin:/app/gnuplot/5.0.3/bin:/app/gcc/4.9.3/bin:/app/binutils/2.26/bin:/usr/lib64/qt-3.3/bin:/app/pbs/bin:/opt/pbs/default/sbin:/opt/pbs/default/bin:/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin:/opt/ibutils/bin:/root/bin \
  /app/gcc/4.9.3/bin/gcc -U_FORTIFY_SOURCE '-D_FORTIFY_SOURCE=1' -fstack-protector -Wall -Wl,-z,-relro,-z,now -B/app/gcc/4.9.3/bin -B/usr/bin -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -fPIC -iquote . -iquote bazel-out/local-fastbuild/genfiles -iquote external/bazel_tools -iquote bazel-out/local-fastbuild/genfiles/external/bazel_tools -isystem external/bazel_tools/tools/cpp/gcc3 '-std=c99' -fno-canonical-system-headers -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' -MD -MF bazel-out/local-fastbuild/bin/src/main/tools/_objs/process-tools/src/main/tools/process-tools.pic.d -c src/main/tools/process-tools.c -o bazel-out/local-fastbuild/bin/src/main/tools/_objs/process-tools/src/main/tools/process-tools.pic.o)
>>>>> # //src/main/tools:build-runfiles [action 'Compiling src/main/tools/build-runfiles.cc']
(cd /tmp/bazel.XJM6j6Tl/out/bazel-0.3.0 && \
  exec env - \
    PATH=/app/cuda/7.5/bin:/app/python/2.7.11/bin:/app/hdf5/1.8.16/gcc493/serial/bin:/app/gnuplot/5.0.3/bin:/app/gcc/4.9.3/bin:/app/binutils/2.26/bin:/usr/lib64/qt-3.3/bin:/app/pbs/bin:/opt/pbs/default/sbin:/opt/pbs/default/bin:/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin:/opt/ibutils/bin:/root/bin \
  /app/gcc/4.9.3/bin/gcc -U_FORTIFY_SOURCE '-D_FORTIFY_SOURCE=1' -fstack-protector -Wall -Wl,-z,-relro,-z,now -B/app/gcc/4.9.3/bin -B/usr/bin -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer '-std=c++0x' '-frandom-seed=bazel-out/local-fastbuild/bin/src/main/tools/_objs/build-runfiles/src/main/tools/build-runfiles.pic.o' -fPIC -iquote . -iquote bazel-out/local-fastbuild/genfiles -iquote external/bazel_tools -iquote bazel-out/local-fastbuild/genfiles/external/bazel_tools -isystem external/bazel_tools/tools/cpp/gcc3 -fno-canonical-system-headers -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' -MD -MF bazel-out/local-fastbuild/bin/src/main/tools/_objs/build-runfiles/src/main/tools/build-runfiles.pic.d -c src/main/tools/build-runfiles.cc -o bazel-out/local-fastbuild/bin/src/main/tools/_objs/build-runfiles/src/main/tools/build-runfiles.pic.o)
ERROR: /app/src/DEEPLEARNING/bazel-0.3.0/src/main/tools/BUILD:11:1: C++ compilation of rule '//src/main/tools:process-tools' failed: gcc failed: error executing command
  (cd /tmp/bazel.XJM6j6Tl/out/bazel-0.3.0 && \
  exec env - \
    PATH=/app/cuda/7.5/bin:/app/python/2.7.11/bin:/app/hdf5/1.8.16/gcc493/serial/bin:/app/gnuplot/5.0.3/bin:/app/gcc/4.9.3/bin:/app/binutils/2.26/bin:/usr/lib64/qt-3.3/bin:/app/pbs/bin:/opt/pbs/default/sbin:/opt/pbs/default/bin:/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin:/opt/ibutils/bin:/root/bin \
  /app/gcc/4.9.3/bin/gcc -U_FORTIFY_SOURCE '-D_FORTIFY_SOURCE=1' -fstack-protector -Wall -Wl,-z,-relro,-z,now -B/app/gcc/4.9.3/bin -B/usr/bin -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -fPIC -iquote . -iquote bazel-out/local-fastbuild/genfiles -iquote external/bazel_tools -iquote bazel-out/local-fastbuild/genfiles/external/bazel_tools -isystem external/bazel_tools/tools/cpp/gcc3 '-std=c99' -fno-canonical-system-headers -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' -MD -MF bazel-out/local-fastbuild/bin/src/main/tools/_objs/process-tools/src/main/tools/process-tools.pic.d -c src/main/tools/process-tools.c -o bazel-out/local-fastbuild/bin/src/main/tools/_objs/process-tools/src/main/tools/process-tools.pic.o): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.
/app/gcc/4.9.3/libexec/gcc/x86_64-unknown-linux-gnu/4.9.3/cc1: error while loading shared libraries: libmpc.so.3: cannot open shared object file: No such file or directory
Target //src:bazel failed to build
INFO: Elapsed time: 6.206s, Critical Path: 2.67s
