### ISSUE TITLE
Allow customizing Python stub script's shebang in the Python toolchain

### ISSUE THREAD

**Issue by brandjon** [bazelbuild/bazel#8685] opened 2019-06-20 14:41 UTC
Currently the stub script requires (via its shebang) that the target system have a `python` command available on `PATH`. If the target is PY3, the user might reasonable expect that it work if `python` is not available but `python3` is. We can modify the shebang in this case to be `#!/usr/bin/env python3`. However doing so might break if the system has a (Python 3) `python` command but not a `python3` command.

See #8665 for a case where the shebang has been a problem in practice.

**Comment by brandjon** [comment] 2019-06-20 14:49
More generally, we can support customizing the shebang as part of the Python toolchain. I'm not clear on how useful this feature would be in the short to medium term. Long term we'd like to eliminate the Python stub altogether and replace it with a C++ one.

**Comment by brandjon** [comment] 2020-05-01 17:14
Repurposing this bug to track the FR to customize the shebang string in the toolchain. That supersedes requests to make it work with a particular interpreter version / system environment xyz. See also #11269.

**Comment by beasleyr-vmw** [comment] 2020-05-14 22:16
@brandjon I'm not sure if the Bazel maintainers prefer to resolve this independent of issues like #8446 or #137, but I'm pursuing this internally and would be happy to generate a PR within the next day or two.

- Any naming suggestions for the new `py_runtime` parameter?
- Are `PyRuntimeInfoTest` test cases sufficient, or do I need to get down and dirty with `python_stub_test.sh`?

**Comment by chrislovecnm** [comment] 2020-07-30 01:07
@brandjon what is the status on this issue?  I just ran smack into it with trying to do a hermetic python build.  When was this issue introduced?

**Comment by fahhem** [comment] 2020-08-03 21:31
Potentially fixed by: https://github.com/bazelbuild/bazel/pull/6632

**Comment by meteorcloudy** [comment] 2021-04-06 07:37
This issue shouldn't be P4 anymore since Python 2 has already been deprecated.

**Comment by meteorcloudy** [comment] 2021-04-19 15:40
@brandjon Is there any plan to fix this?

**Closed** 2021-04-27 07:33 UTC
Labels: P2, team-Rules-Python, type: feature request

**Comment by codeschlosser** [comment] 2021-05-10 16:10
Seems like the problem holds if `--build_python_zip` flag is used. At least when running `bazel test` (still puts `#!/usr/bin/env python` as shebang for the binary, everything is OK in the zip archive)

**Comment by meteorcloudy** [comment] 2021-05-12 07:41
@codeschlosser Are you testing this on Windows? 
Probably the problem is in the python launcher for Windows:
https://github.com/bazelbuild/bazel/blob/ba4435cc81baee8621b75337b33986cc4fa13731/src/tools/launcher/python_launcher.cc#L45

**Comment by codeschlosser** [comment] 2021-05-12 08:12
@meteorcloudy Just the opposite, it works without a problem on Windows, I faced the problem on Debian 10. [This change](https://github.com/codeschlosser/bazel/commit/17cff8b36747a19235d7276de0bf81e187939da4) seems to resolve the problem (checked within a Docker container with hermetic python and without system-provided interpreter)

**Comment by meteorcloudy** [comment] 2021-05-12 08:44
@codeschlosser Thanks! Can you send this change as a PR 😃

**Comment by EdSchouten** [comment] 2021-06-17 18:46
One downside of the current approach is that in the case of remote execution, workers need to have a copy of Python present, even if you've got a hermetic Python toolchain declared. This leads to situations where people accidentally invoke the wrong copy of Python. To work around this issue, I have written a small Go tool that can be installed as "python" in $PATH. It parses the Python stub script, relaunching it with the copy of Python stored in the input root.

Source code: https://github.com/buildbarn/bb-remote-execution/blob/master/cmd/fake_python/main.go
Precompiled versions can be obtained by looking at the GitHub Actions page for that project.

**Comment by jheaff1** [comment] 2022-05-02 11:17
> One downside of the current approach is that in the case of remote execution, workers need to have a copy of Python present, even if you've got a hermetic Python toolchain declared. This leads to situations where people accidentally invoke the wrong copy of Python. To work around this issue, I have written a small Go tool that can be installed as "python" in $PATH. It parses the Python stub script, relaunching it with the copy of Python stored in the input root.
> 
> Source code: https://github.com/buildbarn/bb-remote-execution/blob/master/cmd/fake_python/main.go Precompiled versions can be obtained by looking at the GitHub Actions page for that project.

Is there any way for Bazel to invoke your fake python without having to manually add it to the PATH? I’m trying to make my builds as hermetic as I can
