### ISSUE TITLE
Failures in Starlark transitions should be fatal

### ISSUE THREAD

**Issue by jayconrod** [bazelbuild/bazel#11409] opened 2020-05-15 15:45 UTC
### Description of the problem / feature request:

If a Starlark transition implementation calls `fail`, Bazel should report an error and stop the build. Currently, Bazel reports the error, but it continues with analysis and execution in a potentially invalid configuration.

I'd like to use `fail` in a transition in rules_go to report invalid combinations of build settings.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Run `bazel build //:x` in the test workspace below. It will run the `_x_binary_impl` function and attempt to run the shell script.

```
-- WORKSPACE --
-- BUILD.bazel --
load(":def.bzl", "x_binary")

x_binary(
    name = "x",
)
-- def.bzl --
def _x_transition_impl(settings, attr):
    fail("transition failed!")

_x_transition = transition(
    implementation = _x_transition_impl,
    inputs = [],
    outputs = [],
)

def _x_binary_impl(ctx):
    f = ctx.actions.declare_file(ctx.label.name + ".txt")
    ctx.actions.run_shell(
        command = "echo should not run >&2; exit 1",
        outputs = [f],
    )
    return [DefaultInfo(files = depset([f]))]

x_binary = rule(
    implementation = _x_binary_impl,
    attrs = {
        "_whitelist_function_transition": attr.label(
            default = "@bazel_tools//tools/whitelists/function_transition_whitelist",
        ),
    },
    cfg = _x_transition,
)
```

### What operating system are you running Bazel on?

macOS 10.15.4, amd64

### What's the output of `bazel info release`?

release 3.1.0

**Comment by brandjon** [comment] 2020-05-15 20:12
@juliexxia

**Comment by juliexxia** [comment] 2021-02-04 02:50
(Context: I'm moving on from Bazel on friday and spending some time triaging all bugs assigned to me before unassigning myself)

I just confirmed that this repros with both Blaze and Bazel. The fail gets reported as an error, but as Jay mentioned, it doesn't seem to fail the actual build and it tries to run the shell command. 

The code that needs to be updated is likely right in here: https://cs.opensource.google/bazel/bazel/+/master:src/main/java/com/google/devtools/build/lib/analysis/config/ConfigurationResolver.java;l=438-441;drc=9804ba5b88e241ac94e25aac6288b307789f0db5;bpv=1;bpt=1

**Comment by mobileink** [comment] 2023-01-04 19:32
This is kind of a biggish problem since the fail message gets buried, so the user has no indication of what went wrong.

**Comment by fmeum** [comment] 2023-08-15 11:11
This is fixed at HEAD:
```shell
$ USE_BAZEL_VERSION=b54046f9b6d7c5d76b015b74ac3d95610532dcac bazel build //:x
Extracting Bazel installation...
Starting local Bazel server and connecting to it...
INFO: Invocation ID: 847a5c4b-62ec-48f8-95f0-ae7d9b18077e
ERROR: Traceback (most recent call last):
	File "/home/fhenneke/tmp/11409/def.bzl", line 2, column 9, in _x_transition_impl
		fail("transition failed!")
Error in fail: transition failed!
ERROR: /home/fhenneke/tmp/11409/BUILD:3:9: Errors encountered while applying Starlark transition
ERROR: Analysis of target '//:x' failed; build aborted
INFO: Elapsed time: 6.420s
INFO: 0 processes.
ERROR: Build did NOT complete successfully
```

**Closed by fmeum** 2023-08-15 11:11 UTC
Labels: type: bug, P3, team-Configurability
