### ISSUE TITLE
Bazel Test - Does not support JUnit 5 test results

### ISSUE THREAD

**Issue by razfriman** [bazelbuild/bazel#10109] opened 2019-10-26 00:05 UTC
### Description of the problem / feature request:

Running the JUnit 5 samples for Bazel do not report test results properly.

It always runs all of the tests even if you select a specific test or test class.

Additionally test results do not display properly at all (in IntelliJ) (Perhaps IntelliJ needs to do some work to support this as well)

### Feature requests: what underlying problem are you trying to solve with this feature?

I want to upgrade an existing Java project using Bazel to JUnit 5.

Currently the tests can "run", but the test reporting does not work as well as filtering tests.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

https://github.com/junit-team/junit5-samples/tree/master/junit5-jupiter-starter-bazel

Open this Bazel project with an IDE (IntelliJ).
Run the tests.
See the test results are incomprehensible
See that every single test runs no matter what test you select to run.

### What operating system are you running Bazel on?

MacOS Mojave

### What's the output of `bazel info release`?

`release 1.0.0`

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

> Replace this line with your answer.

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

```
git@github.com:junit-team/junit5-samples.git
0ec1a870909e794b4a872675316e511f7c0d5852
0ec1a870909e794b4a872675316e511f7c0d5852
```

###  Have you found anything relevant by searching the web?

https://github.com/bazelbuild/bazel/issues/6681
https://github.com/JeffreyFalgout/bazel-junit5

### Any other information, logs, or outputs that you want to share?

<img width="1315" alt="Screen Shot 2019-10-26 at 10 57 35 am" src="https://user-images.githubusercontent.com/1769935/67610749-88b7e980-f7e0-11e9-9bd2-4361ed61e6d3.png">

**Comment by iirina** [comment] 2019-10-29 10:19
I'm closing this as a duplicate of #6681.

**Closed by iirina** 2019-10-29 10:19 UTC
Labels: team-Rules-Java, untriaged

**Comment by ponnapz** [comment] 2020-04-16 15:02
@razfriman Did you figure out a workaround / solution for this?

**Comment by razfriman** [comment] 2020-04-16 20:11
> @razfriman Did you figure out a workaround / solution for this?

No we unfortunately had to continue using JUnit 4 :(
