### ISSUE TITLE
Bazel fails to fallback to local spawn when remote cache is not available

### ISSUE THREAD

**Issue by jgavris** [bazelbuild/bazel#3399] opened 2017-07-17 19:32 UTC
### Description of the problem / feature request / question:

I'm trying to make sure our CI et al doesn't get hosed when the cache server is unavailable, so I tried enabling [remote_local_fallback](https://github.com/bazelbuild/bazel/blob/master/src/main/java/com/google/devtools/build/lib/remote/RemoteOptions.java#L122). It seems this does not work yet?

>deimos:bazel-external-caching (master) λ ./test_fallback.sh
INFO: Found 2 targets...
ERROR: /Users/jgavris/Desktop/bazel-external-caching/BUILD:12:1: C++ compilation of rule '//:hello-world' failed: Unexpected IO error.: Connect to 127.0.0.1:80 [/127.0.0.1] failed: Connection refused (Connection refused).
INFO: Elapsed time: 0.894s, Critical Path: 0.48s

### If possible, provide a minimal example to reproduce the problem:

I've created a small example workspace / test script here

https://github.com/ButterflyNetwork/bazel-external-caching/blob/master/test_fallback.sh

### Environment info
* Operating System:
macOS 10.12.5

* Bazel version (output of `bazel info release`):
`development version`

* If `bazel info release` returns "development version" or "(@non-git)", please tell us what source tree you compiled Bazel from; git commit hash is appreciated (`git rev-parse HEAD`):

`688dbf7a7`

###  Have you found anything relevant by searching the web?
(e.g. [StackOverflow answers](http://stackoverflow.com/questions/tagged/bazel),
[GitHub issues](https://github.com/bazelbuild/bazel/issues),
email threads on the [`bazel-discuss`](https://groups.google.com/forum/#!forum/bazel-discuss) Google group)

### Anything else, information or logs or outputs that would be helpful?
(If they are large, please upload as attachment or provide link).

**Comment by aehlig** [comment] 2017-07-18 06:53
Assigning to @ulfjack and @buchgr who where recently chasing bugs in `remote_local_fallback`.

**Comment by buchgr** [comment] 2017-07-18 06:55
This is a duplicate of #2964. As a temporary workaround, you can disable `remote_upload_local_results`.

**Closed by buchgr** 2017-07-18 06:55 UTC
Labels: type: bug

**Comment by jgavris** [comment] 2017-07-18 13:59
@buchgr Would that mean that without remote execution then remote caching is effectively disabled? I want to keep uploading local results on a cache miss if the cache is reachable right?

**Comment by buchgr** [comment] 2017-07-18 14:51
@jgavris yes that's what it means. I am currently traveling but will try to get a fix in for the 0.5.3 release next week. Can't promise tough.
