### ISSUE TITLE
Bazel v3.7.2 accidentally no longer runs on macOS Mojave

### ISSUE THREAD

**Issue by paul-hammant** [bazelbuild/bazel#12842] opened 2021-01-17 17:10 UTC
Homebrew installed bazel:  v3.7.2.

To reproduce on my 10.14.6 Mojave Mac: 

```
$ bazel build :all  
Starting local Bazel server and connecting to it...

Server terminated abruptly (error code: 14, error message: 'Socket closed', log file: '/private/var/tmp/_bazel_paul/a9ab5cdc21a0933dbff70d9d9882627b/server/jvm.out')

Pauls-MacBook-Air:rules_jvm_external paul$ more /private/var/tmp/_bazel_paul/a9ab5cdc21a0933dbff70d9d9882627b/server/jvm.out
dyld: lazy symbol binding failed: Symbol not found: __os_log_debug_impl
  Referenced from: /private/var/tmp/_bazel_paul/install/5535780c9d03e37fc69c3989a52df13a/libunix_jni.dylib (which was built for Mac OS X 10.15)
  Expected in: /usr/lib/libSystem.B.dylib
```

Similar to https://github.com/bazelbuild/bazel/issues/10297 I think.

**Comment by keith** [comment] 2021-01-17 19:13
Related https://github.com/bazelbuild/bazel/commit/f8a94b9decf4c76c217342ce31a05ec30cfb77e8

**Comment by paul-hammant** [comment] 2021-01-18 15:11
Keith, that  June2020 commit fixed this, or indicates the research area for resolution of this issue?

**Comment by keith** [comment] 2021-01-18 16:14
Not sure I don't have an machines on old enough of a version to check. But likely the issue is in the same code, or the build process. You can try HEAD easily with bazelisk to check

**Comment by jin** [comment] 2021-01-19 04:22
cc @philwo @fweikert

**Comment by philwo** [comment] 2021-01-19 11:13
Bazel 3.7.2 already contains the fix. I checked the code for the mentioned function call and it's not used in any other place:

```
philwo@philwo-imacpro:src/bazel ‹df2f77c2a8›$ git checkout 3.7.2                     
HEAD is now at df2f77c2a8 Release 3.7.2 (2020-12-17)
philwo@philwo-imacpro:src/bazel ‹df2f77c2a8›$ git grep os_log_debug
src/main/native/unix_jni_darwin.cc:      os_log_debug(log, msg);  \
```

Our official Bazel 3.7.1 and 3.7.2 release binaries are built using the same version of Xcode (11.7) and same flags according to the build logs.

Can you reproduce with our own binaries? Please try these:

- https://releases.bazel.build/3.7.1/release/bazel-3.7.1-darwin-x86_64
- https://releases.bazel.build/3.7.2/release/bazel-3.7.2-darwin-x86_64

If it works with them, it's a Homebrew issue, please file an issue with them. If if doesn't work, I'll investigate further.

**Comment by sventiffe** [comment] 2021-02-02 10:03
@philwo can you update this issue please?

**Comment by keith** [comment] 2021-02-03 16:40
I think @philwo was waiting on feedback for whether or not those binaries still reproduce the issue, does it still fail for you?

**Comment by paul-hammant** [comment] 2021-02-03 17:09
I scrubbed my Mojave instance I'm afraid. I could get it back to run a test, but I suspect it is OK to close this with should-be-fixed

**Comment by philwo** [comment] 2021-02-10 15:49
Thanks! Closing this - please let me know if you encounter compatibility issues again.

**Closed by philwo** 2021-02-10 15:49 UTC
Labels: P1, area-EngProd, team-XProduct, type: bug
