### ISSUE TITLE
bazel-0.4.4 android dep. error back for tensorflow

### ISSUE THREAD

**Issue by interestingdev** [bazelbuild/bazel#2478] opened 2017-02-03 03:32 UTC
Hi, 
I can see you rolled back the commit before and made below issue gone. But now it's back with latest release 0.4.4. Please help provide solution, thanks.

When I run .configure under syntaxnet/tensorflow/, following error appears:

ERROR: /root/.cache/bazel/_bazel_root/18eb17b8355c7d22a446de6d75221628/external/bazel_tools/src/tools/android/java/com/google/devtools/build/android/dexer/BUILD:3:1: no such target '//external:android/dx_jar_import': target 'android/dx_jar_import' not declared in package 'external' defined by /root/development/models/syntaxnet/tensorflow/WORKSPACE and referenced by '@bazel_tools//src/tools/android/java/com/google/devtools/build/android/dexer:dexer'.
ERROR: /root/.cache/bazel/_bazel_root/18eb17b8355c7d22a446de6d75221628/external/bazel_tools/src/tools/android/java/com/google/devtools/build/android/dexer/BUILD:3:1: no such target '//external:android/dx_jar_import': target 'android/dx_jar_import' not declared in package 'external' defined by /root/development/models/syntaxnet/tensorflow/WORKSPACE and referenced by '@bazel_tools//src/tools/android/java/com/google/devtools/build/android/dexer:dexer'.
ERROR: Evaluation of query "deps(//tensorflow/...)" failed: errors were encountered while computing transitive closure.
root@ubuntu-512mb-vpn-live-snapshot-512mb-nyc3-01:~/development/models/syntaxnet/tensorflow# vim root/.cache/bazel/_bazel_root/18eb17b8355c7d22a446de6d75221628/external/bazel_tools/src/tools/android/java/com/google/devtools/build/android/dexer/BUILD
root@ubuntu-512mb-vpn-live-snapshot-512mb-nyc3-01:~/development/models/syntaxnet/tensorflow# vim /root/.cache/bazel/_bazel_root/18eb17b8355c7d22a446de6d75221628/external/bazel_tools/src/tools/android/java/com/google/devtools/build/android/dexer/BUILD

Please provide the following information. The more we know about your system and use case, the more easily and likely we can help.

### Environment info
ubuntu

* Bazel version (output of `bazel info release`):
0.4.4

Java:
java version "1.8.0_121"
Java(TM) SE Runtime Environment (build 1.8.0_121-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.121-b13, mixed mode)

**Comment by meteorcloudy** [comment] 2017-02-03 08:56
@aj-michael Any idea how to fix this?

**Comment by aj-michael** [comment] 2017-02-03 14:11
Hmmm, I cleaned this up in the tensorflow repo in https://github.com/tensorflow/tensorflow/pull/6225.

@interestingdev can you clarify as to what git repository you are building (is it https://github.com/tensorflow/tensorflow or something else?) and what commit you are at (run `git rev-parse HEAD`)

**Comment by aj-michael** [comment] 2017-02-03 14:23
Ok, the problem is that https://github.com/tensorflow/models has https://github.com/tensorflow/tensorflow as a submodule, but is using a commit which does not include my fix.

The solution is for the tensorflow/models project to update their submodule. A temporary fix would be `git submodule update --remote -f syntaxnet/tensorflow`  which will update their submodule in your local repository to HEAD. (Although I know nothing about tensorflow's release and versioning process so I don't know if that would cause other problems)

**Comment by interestingdev** [comment] 2017-02-04 02:31
Thanks for your response, now I'm taking bazel-0.4.3 to have tensorflow(syntaxnet) build passed.

**Comment by aj-michael** [comment] 2017-02-08 16:44
I'm going to close this because the README.md for models/syntaxnet explicitly says to use bazel 0.4.3: https://github.com/tensorflow/models/blob/master/syntaxnet/README.md. Of course this is less than ideal, their repo should not be breaking on bazel minor version updates, but this particular problem is probably worth filing an issue to their repo about updating their tensorflow version.

**Closed by aj-michael** 2017-02-08 16:44 UTC
Labels: category: rules > android, P1, type: bug

**Comment by jsamson008** [comment] 2017-02-09 21:19
Can you please highlight this in the README file. Red text would be best. I've had dozens of people ask about this problem. And with reasonably good Google foo.

**Comment by kchodorow** [comment] 2017-02-09 21:28
Could you report this on the syntaxnet repo?
