### ISSUE TITLE
//src/test/shell/bazel:bazel_worker_test is broken on Darwin

### ISSUE THREAD

**Issue by kchodorow** [bazelbuild/bazel#1282] opened 2016-05-18 18:29 UTC
See http://ci.bazel.io/job/bazel-tests/BAZEL_VERSION=latest-jdk7,PLATFORM_NAME=darwin-x86_64/9/console:

```
** test_worker_restarts_when_worker_runfiles_change ****************************
INFO: Reading 'startup' options from /private/var/tmp/_bazel_ci/940f5af164c6de2d99dd0946c1f2eaf3/darwin-x86_64/_tmp/bazel_worker_test_61/bazelrc: --output_user_root=/private/var/tmp/_bazel_ci/940f5af164c6de2d99dd0946c1f2eaf3/darwin-x86_64/_tmp/bazel_worker_test_61/root --host_javabase=/private/var/tmp/_bazel_ci/940f5af164c6de2d99dd0946c1f2eaf3/darwin-x86_64/bazel-out/local-fastbuild/bin/src/test/shell/bazel/bazel_worker_test.runfiles/local_jdk
INFO: $TEST_TMPDIR defined: output root default is '/private/var/tmp/_bazel_ci/940f5af164c6de2d99dd0946c1f2eaf3/darwin-x86_64/_tmp/bazel_worker_test_61'.
____Loading...
____Loading package: @bazel_tools//third_party/java/jdk/langtools
____Loading package: @local_jdk//
____Loading package: @local_config_cc//
____Loading complete.  Analyzing...
____Found 0 targets...
____[0 / 1] BazelWorkspaceStatusAction stable-status.txt
____Elapsed time: 5.602s, Critical Path: 0.29s
INFO: Reading 'startup' options from /private/var/tmp/_bazel_ci/940f5af164c6de2d99dd0946c1f2eaf3/darwin-x86_64/_tmp/bazel_worker_test_61/bazelrc: --output_user_root=/private/var/tmp/_bazel_ci/940f5af164c6de2d99dd0946c1f2eaf3/darwin-x86_64/_tmp/bazel_worker_test_61/root --host_javabase=/private/var/tmp/_bazel_ci/940f5af164c6de2d99dd0946c1f2eaf3/darwin-x86_64/bazel-out/local-fastbuild/bin/src/test/shell/bazel/bazel_worker_test.runfiles/local_jdk
INFO: $TEST_TMPDIR defined: output root default is '/private/var/tmp/_bazel_ci/940f5af164c6de2d99dd0946c1f2eaf3/darwin-x86_64/_tmp/bazel_worker_test_61'.
INFO: Reading 'startup' options from /private/var/tmp/_bazel_ci/940f5af164c6de2d99dd0946c1f2eaf3/darwin-x86_64/_tmp/bazel_worker_test_61/bazelrc: --output_user_root=/private/var/tmp/_bazel_ci/940f5af164c6de2d99dd0946c1f2eaf3/darwin-x86_64/_tmp/bazel_worker_test_61/root --host_javabase=/private/var/tmp/_bazel_ci/940f5af164c6de2d99dd0946c1f2eaf3/darwin-x86_64/bazel-out/local-fastbuild/bin/src/test/shell/bazel/bazel_worker_test.runfiles/local_jdk
INFO: $TEST_TMPDIR defined: output root default is '/private/var/tmp/_bazel_ci/940f5af164c6de2d99dd0946c1f2eaf3/darwin-x86_64/_tmp/bazel_worker_test_61'.
____Loading package: 
____Found 1 target...
____Building...
____[6 / 8] Building worker.jar () [for host]
Target //:hello_world_1 up-to-date:
  bazel-bin/hello_world_1.out
____Elapsed time: 5.927s, Critical Path: 1.71s
INFO: Reading 'startup' options from /private/var/tmp/_bazel_ci/940f5af164c6de2d99dd0946c1f2eaf3/darwin-x86_64/_tmp/bazel_worker_test_61/bazelrc: --output_user_root=/private/var/tmp/_bazel_ci/940f5af164c6de2d99dd0946c1f2eaf3/darwin-x86_64/_tmp/bazel_worker_test_61/root --host_javabase=/private/var/tmp/_bazel_ci/940f5af164c6de2d99dd0946c1f2eaf3/darwin-x86_64/bazel-out/local-fastbuild/bin/src/test/shell/bazel/bazel_worker_test.runfiles/local_jdk
INFO: $TEST_TMPDIR defined: output root default is '/private/var/tmp/_bazel_ci/940f5af164c6de2d99dd0946c1f2eaf3/darwin-x86_64/_tmp/bazel_worker_test_61'.
INFO: Reading 'startup' options from /private/var/tmp/_bazel_ci/940f5af164c6de2d99dd0946c1f2eaf3/darwin-x86_64/_tmp/bazel_worker_test_61/bazelrc: --output_user_root=/private/var/tmp/_bazel_ci/940f5af164c6de2d99dd0946c1f2eaf3/darwin-x86_64/_tmp/bazel_worker_test_61/root --host_javabase=/private/var/tmp/_bazel_ci/940f5af164c6de2d99dd0946c1f2eaf3/darwin-x86_64/bazel-out/local-fastbuild/bin/src/test/shell/bazel/bazel_worker_test.runfiles/local_jdk
INFO: $TEST_TMPDIR defined: output root default is '/private/var/tmp/_bazel_ci/940f5af164c6de2d99dd0946c1f2eaf3/darwin-x86_64/_tmp/bazel_worker_test_61'.
____Loading...
____Found 1 target...
Target //:hello_world_2 up-to-date:
  bazel-bin/hello_world_2.out
____Elapsed time: 1.726s, Critical Path: 0.57s
INFO: Reading 'startup' options from /private/var/tmp/_bazel_ci/940f5af164c6de2d99dd0946c1f2eaf3/darwin-x86_64/_tmp/bazel_worker_test_61/bazelrc: --output_user_root=/private/var/tmp/_bazel_ci/940f5af164c6de2d99dd0946c1f2eaf3/darwin-x86_64/_tmp/bazel_worker_test_61/root --host_javabase=/private/var/tmp/_bazel_ci/940f5af164c6de2d99dd0946c1f2eaf3/darwin-x86_64/bazel-out/local-fastbuild/bin/src/test/shell/bazel/bazel_worker_test.runfiles/local_jdk
INFO: $TEST_TMPDIR defined: output root default is '/private/var/tmp/_bazel_ci/940f5af164c6de2d99dd0946c1f2eaf3/darwin-x86_64/_tmp/bazel_worker_test_61'.
INFO: Reading 'startup' options from /private/var/tmp/_bazel_ci/940f5af164c6de2d99dd0946c1f2eaf3/darwin-x86_64/_tmp/bazel_worker_test_61/bazelrc: --output_user_root=/private/var/tmp/_bazel_ci/940f5af164c6de2d99dd0946c1f2eaf3/darwin-x86_64/_tmp/bazel_worker_test_61/root --host_javabase=/private/var/tmp/_bazel_ci/940f5af164c6de2d99dd0946c1f2eaf3/darwin-x86_64/bazel-out/local-fastbuild/bin/src/test/shell/bazel/bazel_worker_test.runfiles/local_jdk
INFO: $TEST_TMPDIR defined: output root default is '/private/var/tmp/_bazel_ci/940f5af164c6de2d99dd0946c1f2eaf3/darwin-x86_64/_tmp/bazel_worker_test_61'.
____Loading...
____Found 1 target...
Target //:hello_world_3 up-to-date:
  bazel-bin/hello_world_3.out
____Elapsed time: 4.918s, Critical Path: 1.80s
INFO: Reading 'startup' options from /private/var/tmp/_bazel_ci/940f5af164c6de2d99dd0946c1f2eaf3/darwin-x86_64/_tmp/bazel_worker_test_61/bazelrc: --output_user_root=/private/var/tmp/_bazel_ci/940f5af164c6de2d99dd0946c1f2eaf3/darwin-x86_64/_tmp/bazel_worker_test_61/root --host_javabase=/private/var/tmp/_bazel_ci/940f5af164c6de2d99dd0946c1f2eaf3/darwin-x86_64/bazel-out/local-fastbuild/bin/src/test/shell/bazel/bazel_worker_test.runfiles/local_jdk
INFO: $TEST_TMPDIR defined: output root default is '/private/var/tmp/_bazel_ci/940f5af164c6de2d99dd0946c1f2eaf3/darwin-x86_64/_tmp/bazel_worker_test_61'.
-- Test log: -----------------------------------------------------------
------------------------------------------------------------------------
test_worker_restarts_when_worker_runfiles_change FAILED: Expected workers to be running, but found none .
src/test/shell/bazel/bazel_worker_test:79: in call to assert_workers_running
src/test/shell/bazel/bazel_worker_test:306: in call to test_worker_restarts_when_worker_runfiles_change
FAILED: test_worker_restarts_when_worker_runfiles_change
```

Should we have a `categroy: worker` label for issues?

**Comment by kchodorow** [comment] 2016-05-20 13:43
Not a flake, it is broken on 0.2.3 and HEAD on Darwin: 

http://ci.bazel.io/job/bazel-tests/BAZEL_VERSION=HEAD,PLATFORM_NAME=darwin-x86_64/10/console
http://ci.bazel.io/job/bazel-tests/BAZEL_VERSION=HEAD-jdk7,PLATFORM_NAME=darwin-x86_64/10/console
http://ci.bazel.io/job/bazel-tests/BAZEL_VERSION=latest,PLATFORM_NAME=darwin-x86_64/10/console
http://ci.bazel.io/job/bazel-tests/BAZEL_VERSION=latest-jdk7,PLATFORM_NAME=darwin-x86_64/10/console

**Comment by kchodorow** [comment] 2016-05-20 13:48
Sorry, the first one isn't actually failing on bazel_worker_test, just the other three

**Comment by philwo** [comment] 2016-05-20 13:52
I think this is a flake. The particular failure mode also looks flaky to me.

Looking at this log, all worker tests pass:
http://ci.bazel.io/job/bazel-tests/BAZEL_VERSION=HEAD,PLATFORM_NAME=darwin-x86_64/10/console

I will have a look at this. Unfortunately the cause for these flakes is still unknown. :(

**Comment by philwo** [comment] 2016-05-24 14:44
This should be fixed now.

**Closed by philwo** 2016-05-24 14:44 UTC
Labels: P1, type: bug
