### ISSUE TITLE
--experimental_remote_download_outputs=toplevel missing test.xml

### ISSUE THREAD

**Issue by vectoralpha** [bazelbuild/bazel#10106] opened 2019-10-25 18:32 UTC
### Description of the problem / feature request:

The `--experimental_remote_download_outputs=toplevel` fails to download the `test.xml` artifacts from the remote workers.

### Feature requests: what underlying problem are you trying to solve with this feature?

Collecting the `test.xml` artifacts when `--experimental_remote_download_outputs=toplevel` is specified.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Run bazel test in RBE

### What operating system are you running Bazel on?

Linux

### What's the output of `bazel info release`?

`release 0.29.1`

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

Private repository.

###  Have you found anything relevant by searching the web?

Nothing

### Any other information, logs, or outputs that you want to share?

We are overriding the default `test.xml` file generation by having our test write xml output to that location during execution. (We are using the `XML_OUTPUT_FILE` environment variable to write to the correct location)

**Comment by buchgr** [comment] 2019-10-28 10:00
So you are saying that your test action generates the test.xml? Does it work without `--experimental_remote_download_outputs=toplevel`?

**Comment by mvonarx** [comment] 2019-10-28 14:25
Our test action does generate the `test.xml` at the path specified by the `XML_OUTPUT_FILE` environment variable.  The file gets transported back to the build host from the RBE worker if we do not specify `--experimental_remote_download_outputs=toplevel` or specify `--experimental_remote_download_outputs=all`

**Comment by buchgr** [comment] 2019-11-20 13:08
I can't reproduce this error with the latest Bazel.

**Comment by buchgr** [comment] 2019-11-20 13:11
I added a test case for this scenario: https://github.com/bazelbuild/bazel/pull/10279

**Comment by coeuvre** [comment] 2020-12-09 05:09
Is this still an issue?

**Comment by aiuto** [comment] 2021-04-01 20:44
Closing for lack of action.

**Closed by aiuto** 2021-04-01 20:44 UTC
Labels: P3, more data needed, team-Remote-Exec, type: bug
