### ISSUE TITLE
Platform-based flags cannot reset Starlark flags to the default value

### ISSUE THREAD

**Issue by tpudlik** [bazelbuild/bazel#23147] opened 2024-07-30 05:13 UTC
(Original title: "A 'cursed' label flag")

Every Starlark flag has a default value defined when it is declared. If a different value is set, platform-based flags should be able to explicitly set the default and have that override the previous value, but currently they are ignored.

See https://github.com/katre/bazel/commit/2aa5c32c9390160f9ea62a796de06a00786be565 for a small demo.

# Original description

### Description of the bug:

I found a truly bizarre bug that I can't make heads or tails of. If a custom host platform explicitly sets a _particular label flag in Pigweed_ to a value, and a platform set via `platform_data` attempts to override it, then the override will fail.

What's bizarre about it is that,

1. It only happens when the target platform is set via `platform_data`, not if it's set on the command line.
2. I've not been able to reproduce this with a minimal upstream repository, only with Pigweed itself.
3. In fact I've not been able to reproduce it with other label flags in Pigweed, including label flags defined in the same `BUILD.bazel` file. As far as I can tell, there's only one unlucky flag that cannot be overridden!

@katre I know you have a lot on your plate, but if you have any suggestions for how to debug this, they'd be very appreciated. This one is a real head-scratcher, and also prevented me from deploying platform-based flags.

### Which category does this issue belong to?

Configurability

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

https://github.com/tpudlik/cursed_flag

### Which operating system are you running Bazel on?

Linux

### What is the output of `bazel info release`?

release 8.0.0-pre.20240618.2

**Comment by katre** [comment] 2024-07-30 16:22
Looks like your [device platform is setting the `label_flag` back to the default](https://github.com/tpudlik/cursed_flag/blob/main/BUILD.bazel#L24): is that also what you're doing with the other flag you tested (`@pigweed//pw_system:device_handler_backend`)?

I wonder if there's something that says "oh, this is the default, so it's not set"? I'll also try debugging, but if you can test that case it'd be handy.

**Comment by katre** [comment] 2024-07-30 16:29
A better way to cquery for these things is to use `filter` and `deps`:

```
$ bazel-dev cquery --implicit_deps --tool_deps -- 'filter("@pigweed//pw_system:", deps(//:binary_for_device)'
```

This shows all the deps in `@pigweed//pw_system`, so you can see whether it's the one you want, rather than probing via `somepath`. The one restriction is that you need `--implicit_deps --tool_deps` to make sure nothing is filtered out.

**Comment by katre** [comment] 2024-07-30 17:24
Good to know, that should help narrow it down.

**Comment by katre** [comment] 2024-07-30 17:34
Okay, I have a very minimal test that shows the same problem, so now I can debug and fix that. I'm going to update the issue name and description to clarify the problem.

**Comment by tpudlik** [comment] 2024-07-30 17:36
Ah, that's great. I _tried_ to produce such a minimal test (having the host platform set the flag to default and the target platform override it), but couldn't get it to work. That is, my minimal repro didn't actually reproduce the bug, everything worked as intended.

**Comment by katre** [comment] 2024-07-30 17:58
@tpudlik Can you build bazel from https://github.com/katre/bazel/tree/i23147-cursed-flag-fix and let me know if it addresses your reproduction?

**Comment by tpudlik** [comment] 2024-07-30 18:43
Yes, I verified that Bazel built from that branch doesn't exhibit the bug, either in my minimal example or in the larger project that originally motivated it. Thank you!

**Comment by katre** [comment] 2024-07-30 18:44
Excellent, I'll clean it up a bit and get it merged.

**Comment by katre** [comment] 2024-08-02 18:29
Okay, got more involved after @gregestren's comment (https://github.com/bazelbuild/bazel/pull/23159#discussion_r1697576017).

Sending out a bunch of changes (unfortunately internally, not in GH), hopefully will address this properly.

**Closed** 2024-08-05 21:42 UTC
Labels: type: bug, team-Configurability, untriaged
