### ISSUE TITLE
Disallow + operator for dicts in Skylark

### ISSUE THREAD

**Issue by davidzchen** [bazelbuild/bazel#1086] opened 2016-03-25 09:56 UTC
Currently, we define the `+` operator for concatenating dictionaries in Skylark. However, this is not valid in Python. This will be a problem when the Skylark docgen tool is available (see #712) since the tool will evaluate the Skylark code as Python.

Since Skylark is meant to be a subset of Python anyway, we should disallow `+` for dictionaries in Skylark and recommend an alternative.

**Comment by davidzchen** [comment] 2016-06-20 19:14
Also see bazelbuild/skydoc#10

**Comment by MarkusTeufelberger** [comment] 2017-06-01 12:26
How does skylark handle this case anyways?

````
a = {"foo":"bar"}
b = {"foo":"baz"}
a + b = ?
````

**Comment by laurentlb** [comment] 2019-02-20 19:22
Duplicate of https://github.com/bazelbuild/bazel/issues/6461

**Closed by laurentlb** 2019-02-20 19:22 UTC
Labels: P2, incompatible-change, team-Starlark
