### ISSUE TITLE
Track down dependencies generated by external repositories

### ISSUE THREAD

**Issue by damienmg** [bazelbuild/bazel#3082] opened 2017-05-30 22:49 UTC
If you develop external repository, some of them are non hermetic (eg. pulling from a branch or a tag) but can generate hermetic data (e.g. commit hash). Providing a way to specify that output that can be reuse to do a reproducible build would be ideal. This mechanism could generate a manifest file that contains all the hermetic build info.

@mattmoor express the interest to be able to inspect which dependencies are running in production.

@schroederc and people from Kythe might be interested as well

We also discussed that kind of similar mechanism with @kchodorow about providing user address for CAS storage to enable caching on ctx.execute.

Also this is similar to build-info file from reproducible-builds.org

**Comment by mattmoor** [comment] 2017-05-30 23:27
@dlorenc FYI

**Comment by dslomov** [comment] 2018-01-10 17:30
This very much calls for a WORKSPACE.lock

**Comment by luser** [comment] 2019-06-17 16:17
> This very much calls for a WORKSPACE.lock

I've been trying out a bazel build at my new workplace (to replace an existing maven build) and I had this exact same thought. I love the reproducibility of bazel's model but the user experience of having to specify everything is pretty rough. Do you know if anyone has made a specific proposal in this vein or is this just an idle thought? It'd be awesome to be able to specify simple tags/branches/non-transitive dependencies in WORKSPACE and have a `bazel lock` or something like that to generate a WORKSPACE.lock file containing the full set of transitive dependencies with hashes.

**Comment by jin** [comment] 2019-06-17 16:24
@luser check out github.com/bazelbuild/rules_jvm_external. The lockfile support is being done in https://github.com/bazelbuild/rules_jvm_external/pull/169

**Comment by jin** [comment] 2019-06-17 16:25
I think this is completed by @aehlig's work on WORKSPACE.resolved for the general case?

**Comment by aehlig** [comment] 2019-06-18 06:54
> I think this is completed by @aehlig's work on WORKSPACE.resolved for the general case?

I also think, that [resolved files](https://blog.bazel.build/2018/09/28/first-class-resolved-file.html) solve this problem. The only thing missing is to declare them non-experimental, but they're certainly not going away.

**Comment by luser** [comment] 2019-06-18 10:30
This sounds great, thanks for the pointers! I think with a few tweaks to streamline their usage resolved files will strike a great balance between usability and reproducibility.

**Comment by aehlig** [comment] 2019-10-08 09:20
Closing, as this seems to be fixed by the use of resolved files. Feel free to open a new issue, if problems remain.

**Closed by aehlig** 2019-10-08 09:20 UTC
Labels: P3, team-ExternalDeps, type: feature request
