### ISSUE TITLE
Display status of repository_ctx.execute commands during analysis phase

### ISSUE THREAD

**Issue by beasleyr-vmw** [bazelbuild/bazel#6427] opened 2018-10-17 21:01 UTC
### Description of the problem / feature request:

Add an optional `status_msg` string parameter to `repository_ctx.execute`. During Bazel's analysis phase, it could display status messages for long-running commands. If the user omits `status_msg`, perhaps Bazel could display some abbreviated form of the command line.

### Feature requests: what underlying problem are you trying to solve with this feature?

Suppose a repository rule spawns a long-running command via `repository_ctx.execute`. There is no way to communicate to the user what is going on, and so the user (who may be new to Bazel) only sees "Analyzing: N targets (M packages loaded)" and may think their process hung.

More concretely, I have a repository rule which invokes a proprietary package manager to download build artifacts and stage them into Bazel's external repository tree. When downloading a 1.1GiB archive via the corporate VPN, I have no indication that Bazel's analysis is blocking on the completion of my package download. I would love to be able to pass a descriptive status string to `repository_ctx.execute` such that Bazel could display it to the end user while waiting for the respective command to complete.

### What operating system are you running Bazel on?

Bazel 0.18rc8

### What's the output of `bazel info release`?

```console
$ bazel info release
release 0.16.1- (@non-git)
```

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

n/a. (This is a feature request.)

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

n/a. (This is a feature request.)

###  Have you found anything relevant by searching the web?

Not really.

Tangentially related:
* #5731

**Comment by ittaiz** [comment] 2018-10-21 20:31
@aehlig you had a change in progress about this, right?

**Comment by jin** [comment] 2018-11-05 18:01
I believe @aehlig has a design document there https://github.com/bazelbuild/proposals/commit/f41029b212995229af03daadc76bdecc68c70956

**Comment by aehlig** [comment] 2018-11-07 07:59
This issue is actually a duplicate of #1289 (and probably a few others).

The current state is that I have
- a [design document](https://github.com/bazelbuild/proposals/blob/f41029b212995229af03daadc76bdecc68c70956/designs/2018-10-29-external-repositories-reporting.md)
- an [implementation](https://bazel-review.googlesource.com/c/bazel/+/79731), and
- a [usage by `git_repository` and `http_archive`](https://bazel-review.googlesource.com/c/bazel/+/79731).

The [design discussion](https://groups.google.com/forum/#!topic/bazel-dev/cKIXXIYRoYo) is going on. As soon as it is finished, I will try to get everything in; this should be in time for `0.21.0`.  BTW, if I remember correctly, in the latest release, which is `0.19.0` we're at least already showing which repositories are being fetched.

**Comment by ittaiz** [comment] 2018-11-07 08:43
I‘m pretty sure it didn’t make 0.19 (but not 100% sure)

**Closed** 2018-11-09 10:31 UTC
Labels: team-ExternalDeps, type: feature request
