### ISSUE TITLE
action_env=PATH breaks build

### ISSUE THREAD

**Issue by salguarnieri** [bazelbuild/bazel#2035] opened 2016-11-03 16:24 UTC
Please provide the following information. The more we know about your system and use case, the more easily and likely we can help.

### Description of the problem / feature request / question:

project: http://kythe.io -- https://github.com/google/kythe

I just upgraded to .4 and it looks like action_env=PATH was added to my /etc/bazel.bazelrc. If I comment out this line, the build is fine, if i leave it in, it cannot properly execute cmake in our build.

### If possible, provide a minimal example to reproduce the problem:

clone our repo
set it up following instructions at http://kythe.io/getting-started

bazel build //kythe/release -- this fails with the line in the bazel.bazelrc, succeeds without the line

the error we get is:
CMake Error: Could not find CMAKE_ROOT !!!
CMake has most likely not been installed correctly.
Modules directory not found in
/share/cmake-3.6
CMake Error: Error executing cmake::LoadCache(). Aborting.

### Environment info
* Operating System: Ubuntu

* Bazel version (output of `bazel info release`):
0.4.0

Based on quick debugging, it looks like when action_env=PATH is set, the path bazel uses is nearly empty and useless, when it isn't set, it looks like my path, which is what I would naively expect.

**Comment by shahms** [comment] 2016-11-03 16:28
Specifically, without --action_env=PATH, the client PATH is preserved (as it was previously) with it, it is overwritten with the completely useless PATH="/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/bin:/sbin:."

**Comment by shahms** [comment] 2016-11-03 16:39
FWIW, the rule(s) getting their PATH inappropriately munged have `use_default_shell_env` specified.

While users can work around this by always running `bazel {command} --action_env=PATH="$PATH"` there is no way to avoid this obnoxiously verbose repetition as bazel does not evaluate environment variables when read from a bazelrc.

**Comment by shahms** [comment] 2016-11-03 16:41
(In other words: This breaks our build and there is no way we can fix this with code changes)

**Comment by damienmg** [comment] 2016-11-03 20:55
So `--action_env` should behave this way:
If `use_default_shell_env` is true, the action gets an environment specified by `--action_env`, if no action env is specified, it behave the legacy way. If `use_default_shell_env` is false, the environment is stripped down.

What is broken:
```
dmarting-macbookair:ws dmarting$ cat BUILD 
load("//:build.bzl", "environ")

environ(name = "default", env = 0)
environ(name = "from_env", env = 1)
dmarting-macbookair:ws dmarting$ cat WORKSPACE 
dmarting-macbookair:ws dmarting$ cat build.bzl 
def _impl(ctx):
  output = ctx.outputs.out
  ctx.action(
      inputs=[],
      outputs=[output],
      use_default_shell_env = ctx.attr.env,
      command="export > %s" % output.path)


environ = rule(
    implementation=_impl,
    attrs={"env": attr.bool(default=True)},
    outputs={"out": "%{name}.env"},
)
```

result:
```
dmarting-macbookair:ws dmarting$ bazel build --action_env PATH=bleh :*; grep PATH bazel-bin/*.env
INFO: Analysed 5 targets.
INFO: Found 5 targets...
INFO: Elapsed time: 0.252s, Critical Path: 0.00s
INFO: Build completed successfully, 1 total action
bazel-bin/from_env.env:declare -x PATH="bleh"
dmarting-macbookair:ws dmarting$ bazel build --action_env PATH :*; grep PATH bazel-bin/*.env
INFO: Analysed 5 targets.
INFO: Found 5 targets...
INFO: Elapsed time: 0.257s, Critical Path: 0.04s
INFO: Build completed successfully, 2 total actions
dmarting-macbookair:ws dmarting$ bazel build :*; grep PATH bazel-bin/*.env
INFO: Analysed 5 targets.
INFO: Found 5 targets...
INFO: Elapsed time: 0.252s, Critical Path: 0.04s
INFO: Build completed successfully, 2 total actions
bazel-bin/from_env.env:declare -x PATH="/<...stripped...>/Users/dmarting/bin"
```

**Comment by shahms** [comment] 2016-11-03 22:56
FWIW, this inspired me to remove the failing rule in favor of doing the replacements manually (rather than invoking cmake to do so).  It works for us now, but it still seems like this is not quite working as intended.

**Comment by aehlig** [comment] 2016-11-07 09:43
The problem is not the --action_env=PATH which is to allow the transition to get rid of the PATH taken from the server environment (in fact, PATH was never(!) taken from the client environment). The actual problem problem is that SpawnActions do not honor the dynamic environment. https://bazel-review.googlesource.com/#/c/7211/ contains a fix for this.

**Closed** 2016-11-07 14:02 UTC
