### ISSUE TITLE
Documentation issue: Bazel (but not Bazel)

### ISSUE THREAD

**Issue by mumbleskates** [bazelbuild/bazel#13932] opened 2021-09-02 08:57 UTC
Documentation URL: https://docs.bazel.build/versions/main/be/general.html#genrule-environment

> However, Bazel (but not Bazel) passes through the value of the user's PATH environment variable.

**Comment by regisd** [comment] 2021-09-08 19:25
Likely duplicate of #13885

**Comment by communikit** [comment] 2021-09-16 21:50
Closing as duplicate of #13885

**Closed by communikit** 2021-09-16 21:50 UTC
Labels: untriaged, team-Documentation
