### ISSUE TITLE
java_library has no attribute constraints?

### ISSUE THREAD

**Issue by perezd** [bazelbuild/bazel#3555] opened 2017-08-14 22:33 UTC
It's not documented here:
https://docs.bazel.build/versions/master/be/java.html#java_library

But according to android_library it should have that field:
https://docs.bazel.build/versions/master/be/android.html#android_library.deps

Without this you can't depend on a java_library from an android_library, correct?

Confirmed its missing on bazel build 0.5.3

**Comment by ahumesky** [comment] 2017-08-15 00:22
The documentation is out of date, `constraints` was replaced with `compatible_with` (though I don't think we enforce compatible_with for the android rules at the moment).

**Comment by perezd** [comment] 2017-08-15 00:54
So if I depend on a java_library as a dep in an android_library, what happens today?

**Comment by aj-michael** [comment] 2017-08-15 13:39
It works.

**Comment by perezd** [comment] 2017-08-15 15:26
Hi, no it doesn't. I'm using version 0.5.3. Maybe you have an older version?

**Comment by aj-michael** [comment] 2017-08-15 15:27
Can you provide an example of it not working?

**Comment by perezd** [comment] 2017-08-15 15:30
In 0.5.3 make a java_library rule and add the the constraints attr and set
it to ["android"].

This results in an error that the attr does not exist.

**Comment by aj-michael** [comment] 2017-08-15 15:36
Sorry, I think there was a miscommunication. When I said "It works", I was responding to your question of "So if I depend on a java_library as a dep in an android_library, what happens today?".

There is no constraints attribute. That was an internal feature that we decided not to open-source.

Consider the following working example:

```
$ cat WORKSPACE
android_sdk_repository(name = "androidsdk")

$ cat BUILD
java_library(name = "jlib", srcs = ["Java.java"])
android_library(name = "alib", srcs = ["Android.java"], deps = [":jlib"])

$ cat Java.java
package java;
public class Java {}

$ cat Android.java
package android;
import java.Java;
class Android {
  Java j = new Java();
} 
```

**Comment by perezd** [comment] 2017-08-15 15:37
Oh! Ok so there's no way to limit? What if you want to prevent Android code
from depending on something it shouldn't?

**Comment by aj-michael** [comment] 2017-08-15 17:15
That's correct, it's a missing feature. Bazel currently does not have a way to express that other than visibility.

**Comment by perezd** [comment] 2017-08-15 17:16
Ok so that's really what this issue is about, I'd like to advocate for
adding that functionality.

**Comment by ahumesky** [comment] 2017-08-15 20:26
To do this with the new constraints system, you could create something like this:

`build_environments/BUILD`:
```python
package(default_visibility = ["//visibility:public"])

environment(name = "android")

environment(name = "server")

environment_group(
  name = "execution_environment",
  defaults = [":server"],
  environments = [
    ":android",
    ":server",
  ]
)
```
Then for your `android_binary` you would add `restricted_to = ["//build_environments:android"]`, then anything that the android binary depends on has to have `compatibile_with = ["//build_environments:android"]`. The thing that's maybe annoying here is that even targets that are already android (`android_library`, `aar_import`, etc) also need to be marked as compatible with android.

**Comment by perezd** [comment] 2017-08-15 20:53
yeah this seems like a functional regression. Why not add back the standard
constraints?

**Comment by ahumesky** [comment] 2017-08-15 21:25
The old constraints system (which used the `constraints` attribute) was hardcoded into blaze, and wasn't open sourced into bazel, so in that sense it's not a regression. 

We can probably add some default environments to `@bazel_tools` and have android rules default their `restricted_to`/`compatible_with` to e.g. `@bazel_tools//build_environments:android`.

**Comment by perezd** [comment] 2017-08-15 21:27
I suppose that would be fine...given we have bazel-specific rules, it also
seems like constraints could be forward ported.

**Comment by ahumesky** [comment] 2017-08-15 21:29
we actually have this bug over here: https://github.com/bazelbuild/bazel/issues/1386, though as I outlined above, it's possible to do this, we just don't have defaults. I'll dupe this one against #1386 and update the title

**Closed** 2017-08-15 21:29 UTC
Labels: category: extensibility > configurability, category: rules > android, type: feature request
