### ISSUE TITLE
Label used in external Bazel workspace is looked up in local workspace

### ISSUE THREAD

**Issue by kobersotzek** [bazelbuild/bazel#4690] opened 2018-02-23 14:36 UTC
### Description of the problem / feature request:

I'm trying to use a rule which is defined in an external Bazel workspace. The implementation of that rule uses a Bazel label internally to refer to other parts of that Bazel workspace. When I build my workspace, Bazel for some reason tries to locate that label in my workspace, though.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

For the example, we need the following files:

WORKSPACE
```
workspace(name = "test_intellij_plugin")

http_archive(
    name = "intellij_with_bazel",
    strip_prefix = "intellij-master",
    urls = ["https://github.com/bazelbuild/intellij/archive/master.zip"],
)
```
BUILD
```
load(
    "@intellij_with_bazel//build_defs:build_defs.bzl",
    "merged_plugin_xml",
)

merged_plugin_xml(
    name = "merged_plugin_xml",
    srcs = [
        "plugin1.xml",
        "plugin2.xml",
    ],
)
```
plugin1.xml
```
<idea-plugin>
  <vendor>Some Company</vendor>
</idea-plugin>
```
plugin2.xml
```
<idea-plugin>
  <description>
    <![CDATA[
      Foo support for IntelliJ.
      ]]>
  </description>
</idea-plugin>
```

If I run `bazel build merged_plugin_xml`, I get an error saying 
> no such target '//build_defs:merge_xml': target 'merge_xml' not declared in package 'build_defs'

The error goes away if I insert the following file:
build_defs/BUILD
```
package(default_visibility = ["//visibility:public"])

alias(
    name = "merge_xml",
    actual = "@intellij_with_bazel//build_defs:merge_xml",
)
```
Am I doing something wrong with the specification of the external Bazel workspace?

By the way, the definition for merged_plugin_xml is in https://github.com/bazelbuild/intellij/blob/master/build_defs/build_defs.bzl.

### What operating system are you running Bazel on?

Linux.

### What's the output of `bazel info release`?

release 0.10.1

### Any other information, logs, or outputs that you want to share?

According to https://bazel-review.googlesource.com/c/bazel/+/39950, labels should be interpreted in their enclosing namespace, which would be the external Bazel workspace in my case.

**Comment by aehlig** [comment] 2018-02-23 16:33
> By the way, the definition for merged_plugin_xml is in https://github.com/bazelbuild/intellij/blob/master/build_defs/build_defs.bzl.

The problem is that a macro is used here; macros are pure subsitution and you end up
getting the string(!) "//build_defs:merge_xml" as argument in the genrule, and that
is then interpreted in the context of the caller (and not found there). This is
perfectly working as intended, as all the string handling in the macro is supposed
to be done on behalf of the caller.

If a name should be resolved in a different context, an explict Label constructor
is to be used. The proper way is to write a rule, with a internal attribute that
is a label, and the (always used) default value is an explicitly call to the
Label constructor. Then the string passed to the constructor is expanded in the
correct namespace.

https://github.com/bazelbuild/bazel/commit/ac650ffa388531b7f2d06b273ed17cf4ae33e99d#diff-7a9fe6805226e679eb218bae4299e65aR430
demonstrates how to do it correctly.

-- 
Klaus Aehlig
Google Germany GmbH, Erika-Mann-Str. 33, 80636 Muenchen
Registergericht und -nummer: Hamburg, HRB 86891
Sitz der Gesellschaft: Hamburg
Geschaeftsfuehrer: Paul Terence Manicle, Halimah DeLaine Prado

**Comment by aehlig** [comment] 2018-02-23 19:03
As explained, this is working as intended.

**Closed by aehlig** 2018-02-23 19:03 UTC
