### ISSUE TITLE
Windows, Java: uncaught exception if JAVA_HOME is undefined [duplicate of #6118]

### ISSUE THREAD

**Issue by laszlocsomor** [bazelbuild/bazel#6475] opened 2018-10-23 13:01 UTC
### Description of the problem / feature request:

Building a java_binary fails with an uncaught exception when JAVA_HOME is undefined.
Bazel should display an informative error message instead.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

1.  Build Bazel at 2fda17d46088f2bb07b049fa35759002ea1dd5db
2.  Unset every environment variable except for:

    ```
    BAZEL_SH=c:\src\fake-msys\usr\bin\bash.exe
    SystemDrive=C:
    SystemRoot=C:\WINDOWS
    ```

    The fake MSYS is a C++ binary that prints its arguments then exits with 1.

3.  Create a workspace with just a java_binary rule and a hello world Java file:
    ```
    C:\src\tmp>type build
    java_binary(
      name = "hello-java",
      srcs = ["Hello.java"],
      main_class = "Hello",
    )

    C:\src\tmp>type hello.java
    public class Hello {
      public static void main(String[] args) {
        System.out.println("hello Java");
      }
    }
    ```

4.  Try building the target. You'll get an uncaught exception:
    ```
    ERROR: C:/users/laszlocsomor/_bazel_laszlocsomor/zovul4l7/external/bazel_tools/tools/jdk/BUILD:197:1: SkylarkAction external/bazel_tools/tools/jdk/platformclasspath.jar failed (Exit 1)
    warning: could not find a JDK 8 bootclasspath in external\local_jdk, falling back to --release
    Exception in thread "main" java.lang.IllegalArgumentException: external\local_jdk
            at jdk.compiler/com.sun.tools.javac.file.Locations$SystemModulesLocationHandler.update(Unknown Source)
            at jdk.compiler/com.sun.tools.javac.file.Locations$SystemModulesLocationHandler.handleOption(Unknown Source)
            at jdk.compiler/com.sun.tools.javac.file.Locations.handleOption(Unknown Source)
            at jdk.compiler/com.sun.tools.javac.file.BaseFileManager.handleOption(Unknown Source)
            at jdk.compiler/com.sun.tools.javac.file.BaseFileManager$2.handleFileManagerOption(Unknown Source)
            at jdk.compiler/com.sun.tools.javac.main.Option.process(Unknown Source)
            at jdk.compiler/com.sun.tools.javac.main.Option.handleOption(Unknown Source)
            at jdk.compiler/com.sun.tools.javac.file.BaseFileManager.handleOption(Unknown Source)
            at jdk.compiler/com.sun.tools.javac.main.Arguments.doProcessArgs(Unknown Source)
            at jdk.compiler/com.sun.tools.javac.main.Arguments.processArgs(Unknown Source)
            at jdk.compiler/com.sun.tools.javac.main.Arguments.init(Unknown Source)
            at jdk.compiler/com.sun.tools.javac.api.JavacTool.getTask(Unknown Source)
            at DumpPlatformClassPath.dumpJDK9AndNewerBootClassPath(DumpPlatformClassPath.java:141)
            at DumpPlatformClassPath.main(DumpPlatformClassPath.java:76)
    ```

5.  Finally, set JAVA_HOME to the right value, and try building again. Now it works:

    ```
    C:\src\tmp>set JAVA_HOME=c:\Program Files\Java\jdk1.8.0_191
    
    C:\src\tmp>bazel-head.exe build //:hello-java
    ...
    INFO: Build completed successfully, 5 total actions
    ```

### What operating system are you running Bazel on?

Windows Server 2016 (v1607)

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

see above at repro instructions

**Comment by laszlocsomor** [comment] 2018-10-23 13:02
This is a bad first-time user experience so I'm linking to https://github.com/bazelbuild/bazel/issues/5254

**Comment by cushon** [comment] 2018-10-23 15:08
This is a duplicate of #6118. That bug discusses a more general fix for recognizing invalid `java_runtime` configurations, but we could also improve the error handling in `DumpPlatformClassPath` in the interim.

**Closed** 2018-11-02 16:10 UTC
Labels: team-Windows, untriaged
