### ISSUE TITLE
Bazel CI: Projects are failing on RBE platform

### ISSUE THREAD

**Issue by meteorcloudy** [bazelbuild/bazel#6742] opened 2018-11-22 14:12 UTC
https://buildkite.com/bazel/bazel-with-downstream-projects-bazel/builds/607#b722acb8-b6a6-413f-87b6-eed40d652fe1
```

ERROR: No toolchain found for cpu 'k8'. Valid toolchains are: [
--
  | stub_armeabi-v7a: --cpu='armeabi-v7a' --compiler='compiler',
  | linux_gnu_x86: --cpu='k8' --compiler='clang',
  | msys_x64_mingw: --cpu='x64_windows' --compiler='mingw-gcc',
  | msvc_x64: --cpu='x64_windows' --compiler='msvc-cl',
  | ]


```

@mhlopko Any idea what caused this error?
FYI @nlopezgi @xingao267

**Comment by nlopezgi** [comment] 2018-11-23 18:01
This is caused by using an old toolchain config with a newer bazel version which fails due to https://docs.bazel.build/versions/master/skylark/backward-compatibility.html#disallow-using-crosstool-to-select-the-cc_toolchain-label. Please double check the WORKSPACE pin to the bazel-toolchains repo for the project that is failing and make sure its at the latest value published here https://releases.bazel.build/bazel-toolchains.html and that they are using "latest" (https://github.com/bazelbuild/bazel-toolchains/blob/master/configs/ubuntu16_04_clang/latest/BUILD) targets for their toolchain config flags (platforms, crosstool, javabase) (if this is part of a buildkite rbe CI run which should already be using the "latest" toolchain targets, just making sure the failing project is pinned to the latest bazel-toolchains release should fix this)

**Comment by nlopezgi** [comment] 2018-11-23 18:03
Note if this is failing with Bazel head then it means a recent change in toolchain selection is breaking for using old toolchain configs. If so, this change will be problematic to release w/o proper guarding via --incompatible_xx flags.

**Comment by mhlopko** [comment] 2018-11-27 13:15
Looking into it.

CC @vladmos FYI

**Comment by mhlopko** [comment] 2018-11-27 14:01
All PRs uploaded, @vladmos pls close the issue once they are all submitted (currently only rules_nodejs is pending) Thanks all!

**Comment by vladmos** [comment] 2018-11-30 13:53
All PRs are submitted.

**Closed by vladmos** 2018-11-30 13:53 UTC
Labels: P1, breakage, team-Rules-CPP
