### ISSUE TITLE
Poor errors when using CPU constraints

### ISSUE THREAD

**Issue by AustinSchuh** [bazelbuild/bazel#3898] opened 2017-10-13 00:28 UTC
I've got a cc_binary marked with `restricted_to = ["@//tools:armhf-debian"]`

When I build the package with that binary in it, I get the following error:
```
austin[114436] aschuh-debian-z620 (bazel-0.6.0) ~/local/repo/vehicle
$ bazel build -c opt //vehicle/radio/... --cpu=k8 --verbose_failures
INFO: Analysed 4 targets.
INFO: Found 4 targets...
INFO: Writing explanation of rebuilds to '/tmp/bazel_explain.log'
Target //vehicle/radio:mk5_files up-to-date (nothing to build)
Target //vehicle/radio:readme up-to-date:
  bazel-bin/vehicle/radio/readme.native
Target //vehicle/radio:echo up-to-date:
  bazel-bin/vehicle/radio/echo
Target //vehicle/radio:echo_arm_only failed to build
Target //vehicle/radio:echo_arm_only failed to build
INFO: Elapsed time: 1.338s, Critical Path: 0.05s
INFO: Build completed successfully, 1 total action
```

When I build up one folder, I get no error.

```
austin[114438] aschuh-debian-z620 (bazel-0.6.0) ~/local/peloton-tech/vehicle
$ bazel build -c opt //vehicle/... --cpu=k8 --verbose_failures
INFO: Analysed 2676 targets.
INFO: Found 2676 targets...
INFO: Writing explanation of rebuilds to '/tmp/bazel_explain.log'
INFO: Elapsed time: 4.191s, Critical Path: 0.17s
INFO: Build completed successfully, 2 total actions
```

**Comment by buchgr** [comment] 2017-10-16 16:13
@mhlopko please take a look :)

**Comment by gregestren** [comment] 2017-10-17 21:23
Austin, in this case are you saying that you're not applying incompatible target skipping, and that you therefore expect the error in both cases?

**Comment by AustinSchuh** [comment] 2017-10-18 00:28
Greg,

(I'm sure there's a technical reason for it as is due to something with how ... gets expanded, but it still was surprising and confusing.  I'm coming at this purely from a user surprised at the output.)

I would have expected the error (Target //vehicle/radio:echo_arm_only failed to build) to be returned in either neither or both cases.  Given a choice, I think neither is the right behavior.  We expect to not run/test a target because it's excluded, and that's not an error.

If you want to keep the error, something like "Target //vehicle/radio:echo_arm_only skipped due to constraints" would be much more user friendly.  "failed to build" sounds pretty drastic and like I should do something different.

Thanks!

**Comment by gregestren** [comment] 2017-10-18 18:20
Yes, I'd appreciate a simple repro example. Because the above behavior definitely doesn't make sense. :)

In particular, it shouldn't be possible to fail the target just by giving it a restricted_to clause. Without --experimental_auto_cpu_environment_group, the target should just build (since no enforcement is checked). With --experimental_auto_cpu_environment_group, it should be skipped without error, since that's the point of the flag.

I did mention in the thread comment that --experimental_auto_cpu_environment_group was inspired by tests, not binaries. So it is possible that's where the problem is coming up. Either way, if you can give me a simple repro I'll see exactly what's going on.

**Comment by gregestren** [comment] 2017-10-18 18:23
Discussion context: https://groups.google.com/d/msg/bazel-discuss/U6sFbPWiXGM/oAteZx8FFQAJ

**Comment by AustinSchuh** [comment] 2017-10-20 00:24
Repo here: [multicpu_test_repo.zip](https://github.com/bazelbuild/bazel/files/1400397/multicpu_test_repo.zip)

Hopefully it's minimal enough for you.  I've got 4 toolchains setup in it.  Fair warning, I'm also pulling in bazel-0.6.1 with //tools/bazel.  I extracted this out of a repo I'm using to run my robotics team's software.

```
austin[115739] aschuh-debian-z620 /tmp/mimial_repo
$ bazel build -c opt ... --cpu=k8
INFO: Analysed 46 targets.
INFO: Found 46 targets...
INFO: Writing explanation of rebuilds to '/tmp/bazel_explain.log'
INFO: Elapsed time: 0.351s, Critical Path: 0.00s
INFO: Build completed successfully, 1 total action
austin[115739] aschuh-debian-z620 /tmp/mimial_repo
$ cd folder1/
austin[115740] aschuh-debian-z620 /tmp/mimial_repo/folder1
$ bazel build -c opt ... --cpu=k8
INFO: Analysed 2 targets.
INFO: Found 2 targets...
INFO: Writing explanation of rebuilds to '/tmp/bazel_explain.log'
Target //folder1:main1 up-to-date:
  bazel-bin/folder1/main1
Target //folder1/folder2:main2 failed to build
Target //folder1/folder2:main2 failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 0.209s, Critical Path: 0.00s
INFO: Build completed successfully, 1 total action
austin[115741] aschuh-debian-z620 /tmp/mimial_repo/folder1
$ bazel build -c opt ... --cpu=roborio
INFO: Analysed 2 targets.
INFO: Found 2 targets...
INFO: Writing explanation of rebuilds to '/tmp/bazel_explain.log'
Target //folder1/folder2:main2 up-to-date:
  bazel-bin/folder1/folder2/main2
Target //folder1:main1 up-to-date:
  bazel-bin/folder1/main1
INFO: Elapsed time: 0.809s, Critical Path: 0.31s
INFO: Build completed successfully, 11 total actions
austin[115742] aschuh-debian-z620 /tmp/mimial_repo/folder1
$ cd ../
austin[115743] aschuh-debian-z620 /tmp/mimial_repo
$ bazel build -c opt ... --cpu=roborio
INFO: Analysed 46 targets.
INFO: Found 46 targets...
INFO: Writing explanation of rebuilds to '/tmp/bazel_explain.log'
INFO: Elapsed time: 0.825s, Critical Path: 0.31s
INFO: Build completed successfully, 13 total actions
```

**Comment by dslomov** [comment] 2019-02-15 16:08
Please do not assign issues to more than one team.

**Comment by gregestren** [comment] 2020-05-11 21:11
Closing this due to age. Let's chat if this is still a concern, especially as our understanding of constraints continues to evolve.

**Closed by gregestren** 2020-05-11 21:11 UTC
Labels: P2, team-Configurability
