### ISSUE TITLE
--incompatible_disable_depset_items=false no longer correctly disables depset items 

### ISSUE THREAD

**Issue by tjoneslo** [bazelbuild/bazel#14365] opened 2021-12-02 13:48 UTC
### Description of the problem / feature request:

In the earlier Bazel 5 releases there was a flag added `--incompatible_disable_depset_items=false` to work around an issue with some libraries. In order to use `rules_jsonnet` you needed to set this flag because it used a `deepest()` where one was no longer needed.

In the 5.0.0rc2 release, this flag is no longer honored for the `rules_jsonnet` case. It simply errors out. 

The `rules_jsonnet` work correctly in Bazel 4.2.0, worked correctly with the Bazel 5 dev releases with the flag, but don't with the Bazel 5.0.0rc2 release

### Feature requests: what underlying problem are you trying to solve with this feature?

Allow builds to work with `rules_jsonnet` until the new version can be released. 

### What's the output of `bazel info release`?

$ bazel info release
Starting local Bazel server and connecting to it...
INFO: Invocation ID: 924c6506-17f4-48de-9bc2-5f86554bf88c
release 5.0.0rc2

###  Have you found anything relevant by searching the web?

https://github.com/bazelbuild/rules_jsonnet/pull/147 - This fixes the problem in Rules Jsonnet 

### Any other information, logs, or outputs that you want to share?

```
ERROR: /Users/tjoneslo/Documents/workspace/apple_federation/examples/all/jsonnet/BUILD.bazel:15:16: in jsonnet_to_json rule //jsonnet:appliaction: 
Traceback (most recent call last):
        File "/private/var/tmp/_bazel_tjoneslo/edceab2f0b51be678cb5fbfba5b387c3/external/io_bazel_rules_jsonnet/jsonnet/jsonnet.bzl", line 239, column 34, in _jsonnet_to_json_impl
                transitive_files = depset(transitive_data),
Error in depset: in call to depset(), parameter 'direct' got value of type 'depset', want 'sequence or NoneType'
ERROR: /Users/tjoneslo/Documents/workspace/apple_federation/examples/all/jsonnet/BUILD.bazel:15:16: Analysis of target '//jsonnet:appliaction' failed
ERROR: Analysis of target '//jsonnet:appliaction' failed; build aborted: 
```

**Comment by tjoneslo** [comment] 2021-12-02 13:57
See also https://github.com/bazelbuild/rules_jsonnet/issues/149

**Comment by meteorcloudy** [comment] 2021-12-02 14:20
This is an intentional breaking change: https://github.com/bazelbuild/bazel/commit/ef967be1718dd7662ed83ea7ef2899fc09576a8e

But do you mean `--incompatible_disable_depset_items=false` no longer works with Bazel 5.0.0rc2?

**Comment by meteorcloudy** [comment] 2021-12-02 14:49
I'm not able to reproduce 
```
pcloudy@pcloudy:~/workspace/rules_jsonnet
$ bazel --version
bazel 5.0.0rc2
pcloudy@pcloudy:~/workspace/rules_jsonnet
$ bazel build @examples//...
INFO: Options provided by the client:
  Inherited 'common' options: --isatty=1 --terminal_columns=283
INFO: Reading rc options for 'build' from /usr/local/google/home/pcloudy/workspace/rules_jsonnet/tools/bazel.rc:
  'build' options: --action_env MYTEST=test --action_env MYJSONNET={code: 'some code'} --define mydefine=sky --workspace_status_command=tools/stamping/workspace_status.sh --verbose_failures
INFO: Reading rc options for 'build' from /usr/local/google/home/pcloudy/.bazelrc:
  'build' options: --verbose_failures --announce_rc
INFO: Analyzed 29 targets (0 packages loaded, 0 targets configured).
INFO: Found 29 targets...
INFO: Elapsed time: 0.154s, Critical Path: 0.01s
INFO: 1 process: 1 internal.
INFO: Build completed successfully, 1 total action
```

Can you produce a reproducible case?

**Comment by tjoneslo** [comment] 2021-12-02 16:09
In the rules_jsonnet repo, verify you are using the 0.3.0 tag release, then edit the file `examples/BUILD` and add the following rule: 

```
jsonnet_to_json(
    name = "wordcount",
    src = "wordcount.jsonnet",
    outs = ["wordcount.json"],
    deps = [":workflow"],
)
```

update the load statement at the top of the file to include the `jsonnet_to_json`. 

From this I get the following: 

```
% bazel build @examples//...
INFO: Invocation ID: c17f5a28-54a5-4ddf-8b2c-5fadd9c059f8
DEBUG: /private/var/tmp/_bazel_tjoneslo/d0da50951c52f8d27c05f56c29b5a512/external/bazel_gazelle/internal/go_repository.bzl:117:18: fetch_repo: go: finding github.com/mattn/go-colorable v0.1.1
DEBUG: /private/var/tmp/_bazel_tjoneslo/d0da50951c52f8d27c05f56c29b5a512/external/bazel_gazelle/internal/go_repository.bzl:117:18: fetch_repo: go: finding github.com/mattn/go-isatty v0.0.7
ERROR: /private/var/tmp/_bazel_tjoneslo/d0da50951c52f8d27c05f56c29b5a512/external/examples/BUILD:19:16: in jsonnet_to_json rule @examples//:wordcount: 
Traceback (most recent call last):
	File "/Users/tjoneslo/Documents/workspace/rules_jsonnet/jsonnet/jsonnet.bzl", line 239, column 34, in _jsonnet_to_json_impl
		transitive_files = depset(transitive_data),
Error in depset: in call to depset(), parameter 'direct' got value of type 'depset', want 'sequence or NoneType'
ERROR: /private/var/tmp/_bazel_tjoneslo/d0da50951c52f8d27c05f56c29b5a512/external/examples/BUILD:19:16: Analysis of target '@examples//:wordcount' failed
ERROR: Analysis of target '@examples//:wordcount' failed; build aborted: 
```

The error we're seeing is in the `jsonnet_to_json` rule only. The other places have been fixed.

**Comment by meteorcloudy** [comment] 2021-12-02 17:22
@laurentlb Looking at this change, maybe it doesn't suppose to be cut into 5.0 or we should document `--incompatible_disable_depset_items` is a no-op from 5.0.

**Comment by Wyverald** [comment] 2021-12-07 12:49
I don't think this is a release blocker (or an issue at all, in fact). The incompatible flag has been there for many releases (https://github.com/bazelbuild/bazel/issues/9017) and 5.0 is a perfectly reasonable time to stop kicking the can down the road. Users should simply wait for https://github.com/bazelbuild/rules_jsonnet/issues/149 and use an updated version.

**Comment by sventiffe** [comment] 2021-12-08 13:26
@Wyverald should this issue be closed then with https://github.com/bazelbuild/rules_jsonnet/issues/149 as resolution?

**Comment by meteorcloudy** [comment] 2021-12-08 14:11
So the problem is that we still keep [the --incompatible_disable_depset_items flag](https://cs.opensource.google/bazel/bazel/+/master:src/main/java/com/google/devtools/build/lib/packages/semantics/BuildLanguageOptions.java;l=324) in Bazel but never use it.

I'll send a change to completely remove the existence of `--incompatible_disable_depset_items` from Bazel, so that it's clear this flag isn't supported anymore. After that we can close this issue.

**Closed** 2021-12-08 14:44 UTC
Labels: type: bug, P2, untriaged, team-Starlark-Integration
