### ISSUE TITLE
Release 0.5

### ISSUE THREAD

**Issue by hermione521** [bazelbuild/bazel#2692] opened 2017-03-16 15:53 UTC
Quote from last release manager: hopefully this time it can be 0.5!

**Comment by meteorcloudy** [comment] 2017-03-21 10:12
In https://bazel-review.googlesource.com/#/c/9461/, bazel_bootstrap_distfile_test is disabled temporarily on Windows due to https://github.com/bazelbuild/bazel/issues/2708

We need to test it manually before release 0.5

**Comment by mhlopko** [comment] 2017-03-21 13:21
Thanks for letting me know!

**Comment by meteorcloudy** [comment] 2017-04-26 07:31
Please cherry-pick https://github.com/bazelbuild/bazel/pull/2862 if it's not in 0.5. Our users depend on it.

**Comment by buchgr** [comment] 2017-04-26 11:52
How is it decided / Who decides what gets into 0.5? 

Having bcd23553f38f54fd4846aa507c827a4ee40cfab4 in 0.5 would also be nice, as this is a blocker for google/protobuf.

**Comment by mhlopko** [comment] 2017-04-26 11:55
It depends on when we will do the cut. We still wait for #1666, then we'll wait for a green ci, then we will do the cut. So https://github.com/bazelbuild/bazel/commit/bcd23553f38f54fd4846aa507c827a4ee40cfab4 will definitely be in the 0.5.

**Comment by buchgr** [comment] 2017-04-26 12:14
Makes sense. thanks @mhlopko :)

**Comment by damienmg** [comment] 2017-05-01 06:55
FTR 1fb094ecd573b77159f3bc73553ce0750152d2d6 needs to be in the release (regression detected inside google)

**Comment by damienmg** [comment] 2017-05-03 15:43
I suggest cutting the release at f3ae88ee043846e7acdffd645137075a4e72c573 since there is only a handful of breakage that needs investigation and no clear regression so far. We can cherry-pick change needed to stabilize the release.

**Comment by damienmg** [comment] 2017-05-03 15:44
Note that the release testing is not very good so it would be good to run the docker test on a workstation and send the release branch as a gerrit code review to get bazel test coverage for it.

**Comment by buchgr** [comment] 2017-05-03 18:07
@laszlocsomor just informed me that he found 4 very serious bugs in his protobuf patch [1]. We included this patch when updating protobuf in 2b49f678a7dfaf27afc0e44ed7a65b00ec06d413. So we should not include the updated protobuf in the new release.

It looks like the protobuf updated happened before `f3ae88e` but after `1fb094e`.

[1] https://github.com/google/protobuf/pull/2969

**Comment by rahul-malik** [comment] 2017-05-03 18:20
@damienmg - Is 0.5 going to include https://github.com/bazelbuild/bazel/issues/1666? 

This would be very helpful for distribution of Bazel updates to our team.

**Comment by damienmg** [comment] 2017-05-03 18:40
Yes it will include it, the bug isnt closed yet because we still need to
test the release part of it.

Jakob: we need to rollback all those change then :/

**Comment by buchgr** [comment] 2017-05-03 18:41
@damienmg :-( ... let's talk with laszo tomorrow before the release.

**Comment by laszlocsomor** [comment] 2017-05-04 06:55
> 4 very serious bugs

The situation isn't so severe. See the commit message for full context: https://github.com/google/protobuf/pull/2969/commits/c4c8806e288915f903f5c2b09a2205b740ffd0d2

**Comment by abergmeier-dsfishlabs** [comment] 2017-05-04 08:45
> The situation isn't so severe.

That might be true.
Be aware that due to increasingly fewer Bazel releases/months people might stay on that release for quite some time.
What I am asking is probably - will there be 0.5.x before 0.6?

**Comment by damienmg** [comment] 2017-05-04 08:51
Yes 0.5.1 will come soon, 0.5.0 cycle was just too slow.

**Comment by rahul-malik** [comment] 2017-05-04 14:10
Is there a plan to have a release candidate available before officially shipping 5.0 to incorporate feedback / fix issues before the final release?

**Comment by damienmg** [comment] 2017-05-04 14:12
we always do release candidate. We bake them for at least a week.

**Comment by mhlopko** [comment] 2017-05-05 09:27
Creating RC3, for the info:
base: f3ae88ee043846e7acdffd645137075a4e72c573
cherrypicks:
c58ba098526b748f9c73e6229cafd74748205aa1
0acead4ea3631240659836ce6ecd6d7f67fd352b
59b099b2a7868a0516c54f38f59e89fef8704473
8725fe432897960993431904167f145ef4e30128
d0242ce4a87929f2528f4602d0fb09d1ccfcea94

**Comment by petemounce** [comment] 2017-05-05 09:46
@mhlopko I had a look for https://storage.googleapis.com/bazel/0.5.0/rc3/index.html to publish a chocolatey package for the RC, but I get a `NoSuchKey` from it. Is that still the correct URL? I also didn't see a note in bazel-dev...?

**Comment by damienmg** [comment] 2017-05-05 09:47
It is not published yet. The CI system has to build the artifact and
publish them. A mail is send to the mailing list right after it is done.

**Comment by mhlopko** [comment] 2017-05-05 09:48
Wow @petemounce you''re quick! I just created it minutes ago, it should show up soon.

**Comment by petemounce** [comment] 2017-05-05 09:55
If you point me at the release automation, perhaps I can build the chocolatey package publishing into it?

**Comment by damienmg** [comment] 2017-05-05 10:44
Hi peter, this is a bit tricky. How are you building the chocolatey package?

**Comment by petemounce** [comment] 2017-05-05 10:55
Via `scripts/packages/chocolatey/build|test.ps1`. `choco` itself apparently runs on linux, but no binaries for that are distributed [according to a stackoverflow answer](https://stackoverflow.com/questions/39386471/can-i-build-chocolatey-packages-on-linux).

I'd be fine to rewrite the build/test/release scripts into golang, actually, if that makes this easier - I'd use them internally too.

**Comment by damienmg** [comment] 2017-05-05 11:01
We can run steps on windows that's not an issue. I'll try to add it as part of the revamp of our ci.

**Comment by Helcaraxan** [comment] 2017-05-08 10:39
@damienmg what is happening to the RC3 image? From what I can see the page given above by @petemounce (https://storage.googleapis.com/bazel/0.5.0/rc3/index.html) still returns:
```xml
<Error>
  <Code>NoSuchKey</Code>
  <Message>The specified key does not exist.</Message>
</Error>
```

**Comment by damienmg** [comment] 2017-05-08 10:53
https://storage.googleapis.com/bazel/0.5/rc3/index.html the release number
was set to 0.5 not 0.5.0, we will correct it for the next release candidate.

**Comment by petemounce** [comment] 2017-05-10 07:41
I've published `0.5.0-rc3` by local hacks to the scripts. Nuget only accepts semver-compliant version numbers, so wouldn't accept `0.5-rc3`. Maybe some validation to the release-creation script - if you point me at that I could add it?

https://chocolatey.org/packages/bazel/0.5.0-rc3

Diff
```diff
λ  git d
diff --git i/scripts/packages/chocolatey/build.ps1 w/scripts/packages/chocolatey/build.ps1
index 3d479ad65..263de241e 100644
--- i/scripts/packages/chocolatey/build.ps1
+++ w/scripts/packages/chocolatey/build.ps1
@@ -13,7 +13,7 @@ if ($mode -eq "release") {
   $tvUri = "https://github.com/bazelbuild/bazel/releases/download/$($tvVersion)/$($tvFilename)"
   $tvReleaseNotesUri = "https://github.com/bazelbuild/bazel/releases/tag/$tvVersion"
 } elseif ($mode -eq "rc") {
-  $tvVersion = "$($version)-rc$($rc)"
+  $tvVersion = "$($version).0-rc$($rc)"
   $tvFilename = "bazel-$($version)rc$($rc)-windows-x86_64.zip"
   $tvUri = "https://storage.googleapis.com/bazel/$($version)/rc$($rc)/$($tvFilename)"
   $tvReleaseNotesUri = "https://storage.googleapis.com/bazel/$($version)/rc$($rc)/index.html"
diff --git i/scripts/packages/chocolatey/test.ps1 w/scripts/packages/chocolatey/test.ps1
index a2349351c..39dc023dd 100644
--- i/scripts/packages/chocolatey/test.ps1
+++ w/scripts/packages/chocolatey/test.ps1
@@ -6,9 +6,9 @@ param(

 choco uninstall bazel --force -y
 if ($prerelease) {
-  choco install ".\bazel.$($version).nupkg" --verbose --debug --prerelease --force -y -s $sources
+  choco install ".\bazel.$($version).0-rc3.nupkg" --verbose --debug --prerelease --force -y -s $sources
 } else {
-  choco install ".\bazel.$($version).nupkg" --verbose --debug --force -y -s $sources
+  choco install ".\bazel.$($version).0-rc3.nupkg" --verbose --debug --force -y -s $sources
 }

 if ($LASTEXITCODE -ne 0)
```

**Comment by mhlopko** [comment] 2017-05-10 07:43
That would be very helpful! This is the script: https://github.com/bazelbuild/bazel/blob/master/scripts/release/release.sh

**Comment by mhlopko** [comment] 2017-05-10 11:52
I created rc4, now in a correct branch named 0.5.0:
https://storage.googleapis.com/bazel/0.5.0/rc4/index.html

base: f3ae88e
cherrypicks:
c58ba09
0acead4
d0242ce
d953ca8
755669fb5de1f4e762f27c19776cac9f410fcb94
6f041661ca159903691fcb443d86dc7b6454253d 
720561113bfa702acfc2ca24ce3cc3fd7ee9c115 
511c35b46cead500d4e76706e0a709e50995ceba

And we already know we will have at least one more rc.

**Comment by damienmg** [comment] 2017-05-12 16:42
Some updates:
There 2 release blocker open right now, @philwo pinged me about another bug that surfaced inside of Google and we are still waiting for a green from some of users of Bazel (including TensorFlow).

The good part is rc6 is bootstrapping fine in homebrew :p

**Comment by petemounce** [comment] 2017-05-13 09:11
I've pushed RCs that I know about:
* https://chocolatey.org/packages/bazel/0.5.0-rc4
* https://chocolatey.org/packages/bazel/0.5.0-rc5
* https://chocolatey.org/packages/bazel/0.5.0-rc6

**Comment by petemounce** [comment] 2017-05-14 21:46
@damienmg @laszlocsomor et al - what, if anything, would you like me to do to the chocolatey package to represent the fact that there are now 3 flavours of bazel possible to get as I can see:
* current one
* one that doesn't have jdk7 bundled
* one that is msysless
?

I could add a flag to the installer to specify which zip to download, and therefore which checksum to use, but that would be a bit of work. Fine to do it, but thought I'd check first. At work, we'll be trying out the msysless one, I think, so will want to make that easy to install.

What is the lifetime of the different flavours expected to be? Is this kind of scenario one that would be beneficial to support now and/or in future?

Caveat: the package should only end up providing one bazel.exe - any other exes should be named for the flavour, so that they can coexist on a system and not have the user juggle the PATH to choose which one to use, I think.

**Comment by laszlocsomor** [comment] 2017-05-15 07:47
@petemounce : I replied on https://github.com/bazelbuild/bazel/issues/3006
Also, thank you for pushing the RCs!

**Comment by dslomov** [comment] 2017-05-16 13:33
Please cherrypick (infrastructure changes):
https://github.com/bazelbuild/bazel/commit/eb565f408e03125e92d42b00756e519795be6593
https://github.com/bazelbuild/bazel/commit/39f328cf392056618d1a3ead4835a138b189a06d
https://github.com/bazelbuild/bazel/commit/624802893f4fe72118f00a78452605d41a2e1c6f

**Comment by philwo** [comment] 2017-05-19 17:31
@mhlopko Can we put a big note in the release notes regarding sandboxing:

"Bazel's Linux sandbox no longer mounts an empty tmpfs on /tmp, instead the existing /tmp is mounted read-write. If you prefer to have a tmpfs on /tmp for sandboxed actions for increased hermeticity, please use the flag --sandbox_tmpfs_path=/tmp."

**Comment by mhlopko** [comment] 2017-05-23 08:58
Please celebrate another rc :) Including big note and 3b08f774e7938928e3a240a47a0a7554cdc8d50b :)

**Comment by meteorcloudy** [comment] 2017-05-23 09:04
Thank you, Marcel!! \o/

**Comment by ittaiz** [comment] 2017-05-23 11:32
@iirina will https://github.com/bazelbuild/bazel/commit/7e91ad631a660ae12a2b8dcfb8ba42574a7a76d3 get in 0.5.0?

**Comment by iirina** [comment] 2017-05-23 13:43
It wasn't planned for, but if you have a strong opinion about it being included you can ask @mhlopko if he would create another RC. But since this is already the 8th RC and a release should be done soon, I'm not very sure about it.

**Comment by philwo** [comment] 2017-05-23 13:46
If you do another round of cherry-picks, please pick this in: https://github.com/bazelbuild/bazel/commit/db5e06a29fccd31ad8ae13e7d271509807d87d7c

I promised it to a user here: https://stackoverflow.com/questions/43849651/how-to-lock-down-the-bazel-filesystem-sandbox/43897863#43897863

But, to be honest, I think we should call it a day and release this if it's stable and then quickly do a 0.5.1 instead of dragging this out even longer...

**Comment by ittaiz** [comment] 2017-05-23 13:56
@philwo @iirina realistically when can we expect 0.5.1?
If 0.5.1 can be cut in a few days (week or two) then of course no objection.
If it's a month from now then I'd say pretty please :)

**Comment by damienmg** [comment] 2017-05-23 13:59
We need another release out by the end of June and that's a hard deadline
for us so we will cut 0.5.1 a few days after 0.5.0 is released.

+1 for Philip's words

**Comment by petemounce** [comment] 2017-05-23 14:04
I tried to push rc7 (https://github.com/bazelbuild/bazel/issues/2692#issuecomment-303335602), but it doesn't appear to have arrived in the bucket yet?

**Comment by mhlopko** [comment] 2017-05-23 14:07
Oh sorry about that, I messed 7 up and didn't push it, and only realized so when I pushed 8... So there's no RC 7...

**Comment by petemounce** [comment] 2017-05-23 14:12
Ah, no worries. Thanks.

https://chocolatey.org/packages/bazel/0.5.0-rc8 has been published.

**Comment by philwo** [comment] 2017-05-24 16:34
@mhlopko A release critical bug was found in our internal version in which the linux-sandbox is completely non functional (can't even execute /bin/true), cf. b/62022773. The bug does not seem to affect Bazel 0.5.0, but please let me verify this manually before finally releasing Bazel 0.5.0. :( Sorry for the mess...

Amazingly, the bug is present in Bazel's HEAD and causes Bazel to automatically fall back to non-sandboxed execution, but nothing in our CI is catching it. It's totally green and saying that sandboxed tests are passing - WTF.

**Comment by damienmg** [comment] 2017-05-25 16:33
IIUC from the internal bug, the causing CL is not in the release branch. All the test from Google teams have come back green, no regression reported by external users, seems like we are good to push 0.5.0rc9 as the 0.5.0 release tomorrow?

**Comment by petemounce** [comment] 2017-05-26 10:06
https://chocolatey.org/packages/bazel/0.5.0-rc9 has been published.

**Comment by philwo** [comment] 2017-05-26 10:13
Damien: OK, I think we can then go ahead with the release.

**Comment by damienmg** [comment] 2017-05-26 22:40
This was released but there is a regression: https://github.com/bazelbuild/bazel/issues/3063 :(

Anyway closing this bug.

**Closed by damienmg** 2017-05-26 22:40 UTC
Labels: category: misc > release / binary, P1, Release blocker, type: process

**Comment by petemounce** [comment] 2017-05-27 00:28
https://chocolatey.org/packages/bazel/0.5.0 is published, awaiting automated review.
