### ISSUE TITLE
Build (after clean) with disk cache is missing empty subdirectories

### ISSUE THREAD

**Issue by george-enf** [bazelbuild/bazel#15789] opened 2022-07-01 21:48 UTC
### Description of the bug:

I build a rule with disk cache enabled. I've added a 5 second delay in `rule1.sh` to prove that it is executing:

```
$ bazel build //:rule1 --disk_cache=diskcache
Target //:rule1 up-to-date:
  bazel-bin/tree
  bazel-bin/empty_dir
INFO: Elapsed time: 5.092s, Critical Path: 5.02s
```

The rule generates 2 directory trees. The `empty_dir` is completely empty. And the `tree` has an empty subdirectory.

```
$ find bazel-bin/
bazel-bin/
bazel-bin/empty_dir
bazel-bin/tree
bazel-bin/tree/subdir
bazel-bin/tree/subdir/file
bazel-bin/tree/empty_subdir
```

I do:
```
$ bazel clean
```

Then, I rebuild. `rule1.sh` is not re-executed.
```
$ bazel build //:rule1 --disk_cache=diskcache
Target //:rule1 up-to-date:
  bazel-bin/tree
  bazel-bin/empty_dir
INFO: Elapsed time: 0.163s, Critical Path: 0.01s
```

The empty subdirectory `empty_subdir` is missing:

```
$ find bazel-bin/
bazel-bin/
bazel-bin/empty_dir
bazel-bin/tree
bazel-bin/tree/subdir
bazel-bin/tree/subdir/file
```

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

BUILD
```
genrule(
    name = "rule1",
    cmd = "./rule1.sh $(RULEDIR)",
    tools = [
        "rule1.sh",
    ],
    outs = [
        "tree",
        "empty_tree",
    ],
)
```

rule1.sh
```
#!/bin/bash

set -e

RULEDIR="$1"
mkdir -p "$RULEDIR"
cd "$RULEDIR"

sleep 5

mkdir -p tree/subdir tree/empty_subdir
echo test > tree/subdir/file

mkdir -p empty_tree
```

### Which operating system are you running Bazel on?

Ubuntu 20.04.1 LTS

### What is the output of `bazel info release`?

release 5.2.0

### Any other information, logs, or outputs that you want to share?

It looks like there is special handing for empty directories here: https://github.com/bazelbuild/bazel/blob/24a494145a9236579d7d159cec29c3899a47967d/src/main/java/com/google/devtools/build/lib/remote/RemoteExecutionService.java#L1086-L1090
I am not sure how empty subdirectories are/should be handled.

**Comment by fmeum** [comment] 2022-07-02 07:31
@coeuvre Resolving this would probably require generalizing what I did in https://github.com/bazelbuild/bazel/pull/15276 to apply to all empty (leaf) directories, not just the top-level one. 

What do you think of the approach to add a new artifact type representing an empty directory? I think that this could even clean up some of the existing logic introduced for https://github.com/bazelbuild/bazel/pull/15276.

**Comment by tjgq** [comment] 2022-07-15 09:03
I had a chat with @coeuvre. We believe the issue is that we fail to create empty directories [here](https://cs.opensource.google/bazel/bazel/+/master:src/main/java/com/google/devtools/build/lib/remote/RemoteExecutionService.java;l=1183;drc=3eeae238ab38c8527439e2f79393e9b496ad89f0) when downloading from the remote cache.

**Comment by tjgq** [comment] 2022-07-18 10:12
I think this issue actually runs deeper: we don't track empty directories inside tree artifacts properly (see #15901). However, it should be possible to fix the disk cache issue separately.

**Comment by coeuvre** [comment] 2023-10-20 14:05
Duplicated of https://github.com/bazelbuild/bazel/issues/15789.

**Closed by coeuvre** 2023-10-20 14:05 UTC
Labels: type: bug, P2, team-Remote-Exec

**Comment by brentleyjones** [comment] 2023-10-20 14:58
@coeuvre duplicated what? Did you mean #15901?

**Comment by coeuvre** [comment] 2023-10-20 15:24
Argh, yes, that's what I had in my mind.
