### ISSUE TITLE
Buildkite CI breakage: 

### ISSUE THREAD

**Issue by c-parsons** [bazelbuild/bazel#5642] opened 2018-07-19 20:14 UTC
A number of bazel downstream dependencies are broken in recent CI runs.

The breakages have some error message in common, for example:

https://buildkite.com/bazel/bazel-with-downstream-projects-bazel/builds/349#a31ac896-3769-483e-9876-81c55ddbe4ba

```

this rule is missing dependency declarations for the following files included by 'external/grpc/src/core/ext/transport/chttp2/server/insecure/server_chttp2_posix.cc':
  '/usr/lib/gcc/x86_64-linux-gnu/7/include/stdint.h'
  '/usr/lib/gcc/x86_64-linux-gnu/7/include/stddef.h'
  '/usr/lib/gcc/x86_64-linux-gnu/7/include/stdarg.h'
  '/usr/lib/gcc/x86_64-linux-gnu/7/include/stdbool.h'
```

could be that cxx_builtin_include_directory part of the generated CROSSTOOL files are not generated correctly on these workers?

**Comment by schroederc** [comment] 2018-07-20 17:09
I've seen something similar (Clang instead of GCC) while building the [Kythe](https://github.com/google/kythe) project after switching on the ` --experimental_strict_action_env` flag, but only when a `--remote_http_cache` is used (even when the cache is empty) inside our Docker-based builder environment:

```
ERROR: /root/.cache/bazel/_bazel_root/4f73afa106ce3d0150a791fe597d9aab/external/org_libzip/BUILD.bazel:147:1: Couldn't build file external/org_libzip/_objs/zip/external/org_libzip/lib/zip_file_set_external_attributes.pic.o: undeclared inclusion(s) in rule '@org_libzip//:zip':
this rule is missing dependency declarations for the following files included by 'external/org_libzip/lib/zip_file_set_external_attributes.c':
  '/usr/lib/llvm-4.0/lib/clang/4.0.1/include/stdint.h'
  '/usr/lib/llvm-4.0/lib/clang/4.0.1/include/stdbool.h'
  '/usr/lib/llvm-4.0/lib/clang/4.0.1/include/limits.h'
  '/usr/lib/llvm-4.0/lib/clang/4.0.1/include/stddef.h'
  '/usr/lib/llvm-4.0/lib/clang/4.0.1/include/stdarg.h'
```

**Comment by mhlopko** [comment] 2018-07-20 17:10
Sorry I missed the notification, I'll take a look first thing on Monday.

**Comment by schroederc** [comment] 2018-07-20 17:15
Another note.  I've seen this happen with Bazel 0.15.2 but have had no problems with Bazel 0.14.0.

**Comment by mhlopko** [comment] 2018-07-24 06:38
Looking now.

**Comment by mhlopko** [comment] 2018-07-24 07:12
In case of TF build, the problem seems to be that the toolchain is configured for gcc-7 (extrapolating from the include path, e.g. `/usr/lib/gcc/x86_64-linux-gnu/7/include/stddef.h` contains 7, which suggests gcc-7). But I only see gcc-5 installed on the worker.

Coincidentally, we have now ubuntu-18 workers, that have gcc-7 installed.

Probably remote cache doesn't like our nonhermetic toolchain. Investigating further.

**Comment by mhlopko** [comment] 2018-07-30 16:02
I'm sorry I didn't have time to look into this one today (still recovering from the training last week). Will take a look tomorrow.

**Comment by mhlopko** [comment] 2018-07-31 13:18
Ok, dumping my brain and hopefully I or somebody else will see a flaw in my thinking and correct me.

My gut feeling is that the reason is we get remote cache hit. The current host is ubuntu16, and the cache was populated from ubuntu18. Since we are passing `--experimental_remote_platform_override=properties:{name:"platform" value:"ubuntu1604"}` (and ubuntu1804 respectively), this should not be possible.

I was able to simulate the failure by running the build with `--experimental_strict_action_env` and passing `--experimental_remote_platform_override=properties:{name:"platform" value:"hlopko-5642"}` on both ubuntu16 and ubuntu18.

I was not able to repro the issue by running with `--experimental_strict_action_env` and with different platform values.

Welp.

**Comment by mhlopko** [comment] 2018-07-31 14:35
The error is not happening on buildkite for last 4 days. Having spent days investigating this I'm tempted to close as fixed by magic.

**Comment by schroederc** [comment] 2018-07-31 16:57
This hasn't magic'd yet.

I can still repro this for https://github.com/google/kythe:

1. Start with a clean remote cache
2. On a Goobuntu workstation: `bazel clean && bazel build --experimental_strict_action_env --remote_http_cache=$CACHE @org_libzip//...`

```
INFO: Starting clean (this may take a while). Consider using --async if the clean takes more than several minutes.
INFO: Build options have changed, discarding analysis cache.
INFO: Analysed 3 targets (10 packages loaded).
INFO: Found 3 targets...
INFO: Elapsed time: 6.002s, Critical Path: 0.83s
INFO: 126 processes: 126 linux-sandbox.
INFO: Build completed successfully, 131 total actions
```

3. Inside our [Buildbot docker container](https://github.com/google/kythe/blob/master/kythe/release/appengine/buildbot/Dockerfile): `bazel clean && bazel build --experimental_strict_action_env --remote_http_cache=$CACHE @org_libzip//...` (same command/cache)

```
INFO: Starting clean (this may take a while). Consider using --async if the clean takes more than several minutes.
INFO: Build options have changed, discarding analysis cache.
INFO: Analysed 3 targets (10 packages loaded).
INFO: Found 3 targets...
ERROR: /root/.cache/bazel/_bazel_root/6cb3ee7c114856715eefe894bc6b49cc/external/net_zlib/BUILD.bazel:30:1: undeclared inclusion(s) in rule '@net_zlib//:zlib':
this rule is missing dependency declarations for the following files included by 'external/net_zlib/inffast.c':
  '/usr/lib/llvm-4.0/lib/clang/4.0.1/include/stddef.h'
  '/usr/lib/llvm-4.0/lib/clang/4.0.1/include/__stddef_max_align_t.h'
  '/usr/lib/llvm-4.0/lib/clang/4.0.1/include/limits.h'
  '/usr/lib/llvm-4.0/lib/clang/4.0.1/include/stdarg.h'
INFO: Elapsed time: 0.824s, Critical Path: 0.19s
INFO: 0 processes.
FAILED: Build did NOT complete successfully
```

If you flip steps 2 and 3, you get the error on the Goobuntu workstation:

```
INFO: Starting clean (this may take a while). Consider using --async if the clean takes more than several minutes.
INFO: Build options have changed, discarding analysis cache.
INFO: Analysed 3 targets (10 packages loaded).
INFO: Found 3 targets...
ERROR: /home/schroederc/.cache/bazel/_bazel_schroederc/c48582765972a15180970afb1bdc98a2/external/org_libzip/BUILD.bazel:147:1: undeclared inclusion(s) in rule '@org_libzip//:zip':
this rule is missing dependency declarations for the following files included by 'external/org_libzip/lib/zip_open.c':
  '/usr/lib/gcc/x86_64-linux-gnu/4.9/include/stdint.h'
INFO: Elapsed time: 1.033s, Critical Path: 0.17s
INFO: 0 processes.
FAILED: Build did NOT complete successfully
```

The remote caching mechanism does not seem to take into account the complete cc_toolchain.

**Comment by mhlopko** [comment] 2018-07-31 17:03
I also have a repro for your situation. But on buildkite we pass `--experimental_remote_platform_override='properties:{name:"platform" value:"ubuntu16"}'` and `--experimental_remote_platform_override='properties:{name:"platform" value:"ubuntu18"}'` to differentiate different platforms. Adding similar flags to kythe build should be done no matter what. The question that is still open is how was it possible that our buildkite build failed.

**Comment by schroederc** [comment] 2018-07-31 17:10
This is the first I've heard of that flag.  It doesn't appear in the [Remote Caching documentation](https://docs.bazel.build/versions/master/remote-caching.html).  Should that be updated?

**Comment by mhlopko** [comment] 2018-08-01 13:33
@buchgr could you take care of that?

**Comment by mhlopko** [comment] 2018-08-02 16:16
Cody: Another option is to pass --action_env with an environment variable specific to the host. That will also influence the cache key.

**Comment by mhlopko** [comment] 2018-08-02 16:17
After many hours of debugging and trying to repro (and only discovering that stuff works like it should) I declare the cause to be Sun eruptions. Please reopen if I'm wrong.

**Closed by mhlopko** 2018-08-02 16:17 UTC
Labels: P2
