### ISSUE TITLE
How to build a single .so library which doesn't depend on other libraries

### ISSUE THREAD

**Issue by rainStone819** [bazelbuild/bazel#2253] opened 2016-12-16 06:56 UTC
I want to build a .so library and use jna invoke it, my c++ project depend on another project. When i invoked the .so library, i got the error:

`java.lang.UnsatisfiedLinkError: lib*.so: undefined symbol: ...`

I think the reason is the .so library depend on other library, how to solve it?

**Comment by mhlopko** [comment] 2017-03-15 13:08
Can you come up with a build file that demonstrates the problem? Is the missing symbol defined in the direct dependency of cc_binary or in transitive?

If it is in the direct dependency, it should work and I need more information to debug this. If it is in the transitive dependency, this will not work at the moment, although we're fixing it soon.

**Comment by mhlopko** [comment] 2017-04-04 09:00
Closing due the lack of information (which was caused by my super-slow reply, sorry about that). Feel free to reopen if you didn't fix this yet. Thanks!

**Closed by mhlopko** 2017-04-04 09:00 UTC
Labels: category: rules > C++, P2, type: documentation
