### ISSUE TITLE
bazel test failure when mixing standalone and in tree plugin build modes

### ISSUE THREAD

**Issue by davido** [bazelbuild/bazel#2797] opened 2017-04-10 06:25 UTC
I'm using Bazel 0.4.5.

Gerrit Code Review project supports ca. 100 plugins. There are two supported Bazel build modes:

* in Gerrit tree, by linking a plugin directory to gerrit/plugins directory
* Standalone plugin build mode

We are seeing failure when running `build test //...` command in gerrit tree, after a plugin, that is linked to the gerrit plugins directory, was built in standalone build mode.

Consider this command sequence:

```
  # Build verify status in standalone build mode and run tests
  $ cd projects/verify-status
  $ bazel test //...
INFO: Found 1 test target...
Target //:verify-status-tests up-to-date:
  bazel-bin/verify-status-tests.jar
  bazel-bin/verify-status-tests
INFO: Elapsed time: 1.168s, Critical Path: 0.69s
//:verify-status-tests                                          (cached) PASSED in 29.8s
```
Now link this plugin to gerrit tree, under plugins/verify-status directory, and try to run the tests in gerrit tree, using plugin specific tag:

```
  $ cd projects/gerrit
  $ bazel test --test_output=streamed --test_tag_filters=verify-status //...
WARNING: Streamed test output requested. All tests will be run locally, without sharding, one at a time.
ERROR: error loading package 'plugins/verify-status/bazel-verify-status/external/bazel_tools/third_party/jformatstring': Extension file not found. Unable to load package for '//tools/build_rules:java_rules_skylark.bzl': BUILD file not found on package path.
INFO: Elapsed time: 0.513s
ERROR: Couldn't start the build. Unable to run tests.
```

Woraround: run `bazel clean` in the plugin directory first and shut down bazel daemon. Now the tests succeed:

```
  $ cd ../verify-status
  $ bazel clean --async
INFO: Starting clean.
INFO: Output tree moved to /home/davido/.cache/bazel/_bazel_davido/8e1b42a476e2e960f4d5330e60e9c003/execroot/verify-status_tmp_21377 for deletion
  $ bazel shutdown
  $ cd ../gerrit
  $ bazel test --test_output=streamed --test_tag_filters=verify-status //...
WARNING: Streamed test output requested. All tests will be run locally, without sharding, one at a time.
INFO: Found 1 test target...
Target //plugins/verify-status:verify-status-tests up-to-date:
  bazel-bin/plugins/verify-status/verify-status-tests.jar
  bazel-bin/plugins/verify-status/verify-status-tests
INFO: Elapsed time: 1.071s, Critical Path: 0.51s
//plugins/verify-status:verify-status-tests                     (cached) PASSED in 14.5s

Executed 0 out of 1 test: 1 test passes.
```

To reproduce use Gerrit Code Review[1] and Verify-Status plugin[2].

* [1] git clone https://gerrit.googlesource.com/gerrit
* [2] git clone https://gerrit.googlesource.com/plugins/verify-status

**Comment by laszlocsomor** [comment] 2017-05-30 11:25
> Now link this plugin to gerrit tree, under plugins/verify-status directory

Do you mean creating a symlink?

**Comment by davido** [comment] 2017-05-30 14:39
Yes, sorry for not being clear. Clone both `verify-status`-plugin and `gerrit` in say `/home/<users>/projects` directory. Then execute:

```
  $ cd gerrit/plugins
  $ ln -s ../../verify-status .
```

**Comment by damienmg** [comment] 2017-06-26 15:32
Wow how come that bug has stayed univestigated for 3 months? Sorry for that, I'll try to understand what's going on tomorrow.

**Comment by damienmg** [comment] 2017-06-28 08:30
Ok I understand what is happening, bazel recurse into the convenience symlinks.

/cc @haxorz IIRC we discussed excluding some directory from the build, do we have that?

**Comment by damienmg** [comment] 2017-06-30 07:55
Dupe of #1293 actually

**Closed by damienmg** 2017-06-30 07:55 UTC
Labels: category: rules > misc native, P2, type: bug
