### ISSUE TITLE
[Windows msys-less] Build fails with path not found, rerun fails with source forest creation.

### ISSUE THREAD

**Issue by Helcaraxan** [bazelbuild/bazel#3025] opened 2017-05-18 15:54 UTC
### Description of the problem:

I have been trying out the 'msysless' version of Bazel on 0.5.0-rc6 while running in PowerShell. I have used it succesfully on one machine, now trying it out on another the build fails with a path that is not found.

Rerunning does not fail with the same error but rather raises a `Source forest creation failed`.

Here follows the output:
```
$> ..\..\bazel-0.5.0-rc6.exe build //cpp/core_sdk/... --verbose_failures
INFO: Found 4 targets...
ERROR: C:/users/duco/appdata/local/temp/_bazel_duco/ut5qhvy-/external/gtest/BUILD.bazel:3:1: C++ compilation of rule '@g                                                                                                                                                       test//:main' failed: msvc_cl.bat failed: error executing command
  cd C:/users/duco/appdata/local/temp/_bazel_duco/ut5qhvy-/execroot/repo
  SET INCLUDE=C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE;C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\ATLMFC\INCLUDE;C:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt;C:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um;C:\Program Files (x86)\Windows Kits\8.1\include\\shared;C:\Program Files (x86)\Windows Kits\8.1\include\\um;C:\Program Files (x86)\Windows Kits\8.1\include\\winrt;c:/tools/python2/include
    SET LIB=C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\LIB\amd64;C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\ATLMFC\LIB\amd64;C:\Program Files (x86)\Windows Kits\10\lib\10.0.10240.0\ucrt\x64;C:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\lib\um\x64;C:\Program Files (x86)\Windows Kits\8.1\lib\winv6.3\um\x64;c:/tools/python2/libs
    SET PATH=C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\CommonExtensions\Microsoft\TestWindow;C:\Program Files (x86)\MSBuild\14.0\bin\amd64;C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\amd64;C:\WINDOWS\Microsoft.NET\Framework64\v4.0.30319;C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\VCPackages;C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE;C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\Tools;C:\Program Files (x86)\HTML Help Workshop;C:\Program Files (x86)\Microsoft Visual Studio 14.0\Team Tools\Performance Tools\x64;C:\Program Files (x86)\Microsoft Visual Studio 14.0\Team Tools\Performance Tools;C:\Program Files (x86)\Windows Kits\8.1\bin\x64;C:\Program Files (x86)\Windows Kits\8.1\bin\x86;C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.6                                                                                                                                                       .1 Tools\x64\;C:\tools\ruby23\bin;C:\Python27\;C:\Python27\Scripts;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\ProgramData\chocolatey\bin;C:\Program Files\Java\jdk1.8.0_121\bin;C:\tools\go\bin;\usr\bin;C:\Program Files (x86)\vim\vim80;C:\Program Files\7-Zip;C:\Program Files (x86)\GNU\GnuPG\pub;C:\Program Files\OpenVPN\bin;C:\Program Files\Puppet Labs\Puppet\puppet\bin;C:\Program Files\Puppet Labs\Puppet\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\tools\apache-maven-3.3.9\bin;C:\Program Files (x86)\MSBuild\14.0\Bin;C:\tools\python2;C:\tools\python2\Scripts;C:\Program Files (x86)\NUnit.org\nunit-console;C:\Program Files (x86)\CMake\bin;C:\Program Files\Git\cmd;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\bin;C:\Program Files\Git\bin;C:\tools\phabricator\arcanist\bin;C:\WINDOWS\system32\config\systemprofile\.dnx\bin;C:\Program Files\Microsoft DNX\Dnvm\;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files (x86)\s
bt\\bin;C:\Program Files (x86)\sbt\bin;C:\Users\duco\AppData\Local\Microsoft\WindowsApps;C:\ProgramData\chocolatey\lib\m                                                                                                                                                       sys2;C:\tools\msys64;C:\Users\duco\AppData\Local\atom\bin;C:\Program Files (x86)\Microsoft VS Code\bin;C:\tools\php;;C:\WINDOWS\system32
    SET PWD=/proc/self/cwd
    SET TMP=C:\Users\duco\AppData\Local\Temp
  external/local_config_cc/wrapper/bin/msvc_cl.bat /DOS_WINDOWS=OS_WINDOWS /DCOMPILER_MSVC /DNOGDI /DNOMINMAX /DPRAG
WINDOWS=OS_WINDOWS /DCOMPILER_MSVC /DNOGDI /DNOMINMAX /DPRAGMA_SUPPORTED /D_WIN32_WINNT=0x0600 /D_CRT_SECURE_NO_DEPRECATE /D_CRT_SECURE_NO_WARNINGS /D_SILENCE_STDEXT_HASH_DEPRECATION_W
m32
    SET PWD=/proc/self/cwd
    SET TMP=C:\Users\duco\ApData\Local\Temp
  external/local_config_cc/wrapper/bin/msvc_cl.bat /DOS_WINDOWS=OS_WINDOWS /DCOMPILER_MSVC /DNOGDI /DNOMINMAX /DPRAGMA_SUPPORTED /D_WIN32_WINNT=0x0600 /D_CRT_SECURE_NO_DEPRECATE /D_CRT_SECURE_NO_WARNINGS /D_SILENCE_STDEXT_HASH_DEPRECATION_WARNINGS /D_USE_MATH_DEFINES /bigobj /Zm500 /J /Gy /GF /W3 /EHsc /wd4351 /wd4291 /wd4250 /wd4996 -Xcompilation-mode=fastb Microsoft\WindowsApps;C:\ProgramData\chocolatey\lib\msys2;C:\tools\msys64;C:\Users\duco\AppData\Local\atom\bin;C:\Program Files (x86)\Microsoft VS Code\bin;C:\tools\php;;C:\WINDOWS\system32
    SET PWD=/proc/self/cwd
    SET TMP=C:\Users\duco\AppData\Local\Temp
  external/local_config_cc/wrapper/bin/msvc_cl.bat /DOS_WINDOWS=OS_WINDOWS /DCOMPILER_MSVC /DNOGDI /DNOMINMAX /DPRAGMA_SUPPORTED /D_WIN32_WINNT=0x0600 /D_CRT_SECURE_NO_DEPRECATE /D_CRT_SECURE_NO_WARNINGS /D_SILENCE_STDEXT_HASH_DEPRECATION_WARNINGS /D_USE_MATH_DEFINES /bigobj /Zm500 /J /Gy /GF /W3 /EHsc /wd4351 /wd4291 /wd4250 /wd4996 -Xcompilation-mode=fastbuild /nologo /Iexternal/gtest /Ibazel-out/msvc_x64-fastbuild/genfiles/external/gtest /Iexternal/bazel_tools /Ibazel-out/msvc_x64-fastbuild/genfiles/external/bazel_tools /Iexternal/gtest/include /Ibazel-out/msvc_x64-fastbuild/genfiles/external/gtest/include /Iexternal/bazel_tools/tools/cpp/gcc3 /showIncludes /Od /Z7 /c external/gtest/src/gtest.cc /Fobazel-out/msvc_x64-fastbuild/bin/external/gtest/_objs/main/external/gtest/src/gtest.o: com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.
The system cannot find the path specified.
INFO: Elapsed time: 5.098s, Critical Path: 0.13s

$> ..\..\bazel-0.5.0-rc6.exe build //cpp/core_sdk/... --verbose_failures
INFO: Found 4 targets...
ERROR: Source forest creation failed: C:/users/duco/appdata/local/temp/_bazel_duco/ut5qhvy-/execroot/repo/external (Directory not empty).
INFO: Elapsed time: 13.439s
```

### If possible, provide a minimal example to reproduce the problem:

Given that the behaviour is different on two seperate machines I have not yet found an easily reproducable situation. 

I can reproduce this locally though. Running `bazel clean` (which hangs on the first run but succeeds on the second run after Ctrl+C-ing the first attempt) resets the issue so it occurs in the same fashion when running `bazel build` again. I am not yet filing a new issue for the `bazel clean` error as it might well be directly related to the `Source forest creation failed` error.

### Environment info
* Operating System: Windows 10 Pro

* Bazel version (output of `bazel info release`): 0.5.0-rc6 - bazel-msvc-0.5.0rc6-windows-msvc-x86_64.exe

**Comment by dslomov** [comment] 2017-05-19 13:37
@laszlocsomor @meteorcloudy rings a bell?

**Comment by meteorcloudy** [comment] 2017-05-24 13:37
Unfortunately, I couldn't reproduce the exactly same error, yet found another one https://github.com/bazelbuild/bazel/issues/3043, which looks like more severe...

**Comment by buchgr** [comment] 2017-05-31 17:03
I am also getting a "Source forest creation failed" error on our CI:

http://ci.bazel.io/job/CR/job/bazel-tests/24/BAZEL_VERSION=latest,PLATFORM_NAME=windows-x86_64/console

```
ERROR: Source forest creation failed: C:/bazel_ci/temp/_bazel_system/xb1clndd/execroot/windows-x86_64/external/com_google_guava/guava-21.0.jar (Permission denied).
```

For me it's always reproducible actually. Let's check tomorrow.

**Comment by laszlocsomor** [comment] 2017-11-30 16:57
I'm dropping priority due to lack of activity.
@Helcaraxan , @buchgr : has any of you seen this bug recently?

**Comment by Helcaraxan** [comment] 2017-12-28 14:12
Sorry for the late reply and happy festive season everyone!

We have not observed this behaviour over the past 2 / 3 months. Am happy to see this closed for my part but will leave that up to @buchgr and the Bazel team to decide.

**Comment by laszlocsomor** [comment] 2018-01-02 06:53
@buchgr -- I'll close this bug for now. Please reopen if you see it again!

**Closed by laszlocsomor** 2018-01-02 06:53 UTC
Labels: category: multi-platform > windows, P3, type: bug
