### ISSUE TITLE
`@` and `@workspacename` considered different repositories

### ISSUE THREAD

**Issue by jayconrod** [bazelbuild/bazel#3115] opened 2017-06-02 17:28 UTC
### Description of the problem / feature request / question:

Bazel evaluates the same Skylark file multiple times if it is loaded with a local path and an absolute path. This creates problems for rules, since everything gets defined twice. It is particularly problematic for named providers, since the duplicate definitions are neither equivalent nor compatible.

We ran into this issue when trying to migrate rules_go to use named providers. We load our .bzl files with local labels in our own repository, but repositories that depend on ours load using absolute labels, which causes errors.

Bazel should not evaluate the same .bzl file in the same repository more than once.

### If possible, provide a minimal example to reproduce the problem:

Create an empty workspace with these files.

```
# WORKSPACE
workspace(name = "scratch")
```

```
# BUILD
load("//:def.bzl", "a")
load("@scratch//:def.bzl", "a")
```

```
# def.bzl
print("def.bzl evaluated")
a = 10
```

Run `bazel query //...` to evaluate the files. The message is printed twice.

```
$ bazel query //...
____Loading package: 
WARNING: /usr/local/google/home/jayconrod/Code/scratch/def.bzl:1:1: def.bzl evaluated.
WARNING: /usr/local/google/home/jayconrod/.cache/bazel/_bazel_jayconrod/1df8d8ad4cb35ee83522d81953b4d69f/external/scratch/def.bzl:1:1: def.bzl evaluated.
____Empty results
```

### Environment info
* Operating System: Linux
* Bazel version (output of `bazel info release`): 0.5.0

cc @ianthehat

**Comment by jwnimmer-tri** [comment] 2017-11-09 00:59
This is acutely annoying for providers, since it both breaks things, and gives bad diagnostics ("does not have mandatory providers Foo" even though it has "Foo", just a different foo).  If it is difficult to fix, it might be worth at least failing-fast in the meantime, even if only for providers.

**Comment by laurentlb** [comment] 2018-05-16 09:54
Klaus, are you aware of this issue?
I don't know exactly at which level we need to fix this (so assigning to both Jon and Klaus).

**Comment by brandjon** [comment] 2018-05-25 12:31
FYI if it's a local and absolute path within the same repo ("//" vs ":") it doesn't reproduce, so I believe it has to be a repository-specific issue.

**Comment by jayconrod** [comment] 2018-05-25 13:37
Labels that include the repository name are still treated as different though, i.e., in the example above, `@scratch//:def.bzl` is treated as different from `//:def.bzl`, even they they refer to the same file.

This is an issue with rules and named providers. It's easy to get two incompatible copies of something with the same name.

**Comment by ittaiz** [comment] 2018-05-25 13:58
The question is then what to do with a bzl file in repo A which is needed
in both repositories A and B which *additionally* has a dependency on a
label inside A (for example a tool). We get invoked twice with different
strict deps outputs...

**Comment by jayconrod** [comment] 2018-05-25 14:18
@ittaiz In rules_go, we work around this by always loading .bzl files using absolute labels that include the repo name. So we always load `@io_bazel_rules_go//go:def.bzl` even from inside the repository.

**Comment by ittaiz** [comment] 2018-05-25 14:23
We also did that and it didn't solve the problem. I think since the label
that the bzl is dependent on gets loaded twice.

**Comment by aehlig** [comment] 2018-06-05 09:34
Two remarks.
- The problem is the `@scratch`. Loading `@//:def.bzl` and `//:def.bzl` evaluates the file only once. So it seems that `@` and `@scratch` are treated as different repositories.
- That also fits with the debug message: the direct location of the file, and in bazel's output base under `external/scratch`---as if `@scratch` where an external repository (of type `local_repository`) located at the current working directory.

Added @dkelmer, as this has to be considered as part of the label renaming project as well.

**Comment by aehlig** [comment] 2018-06-05 10:18
A better way to demonstrate that `@scratch` is really treated as a different `local_repository` is shown below. Note that not only another action is carried out when building `@scratch//:it` after having built `@//:it`, but it also has a different output file.

```
/memfs/tmp/work>cat WORKSPACE 
workspace(name="scratch")
/memfs/tmp/work>cat BUILD 
genrule(
  name = "it",
  outs = ["it.txt"],
  cmd = "echo hello > $@",
)
/memfs/tmp/work>bazel clean --expunge
Starting local Bazel server and connecting to it...
........
(12:13:55) INFO: Starting clean.
/memfs/tmp/work>bazel build -s @//...
Starting local Bazel server and connecting to it...
........
(12:14:10) INFO: Current date is 2018-06-05
(12:14:10) INFO: Analysed target //:it (8 packages loaded).
(12:14:10) INFO: Found 1 target...
(12:14:11) SUBCOMMAND: # //:it [action 'Executing genrule //:it']
(cd /crypto/general/aehlig/.cache/bazel/_bazel_aehlig/ea3a7c72d5e8b43a0d4e9c691a291e8f/execroot/scratch && \
  exec env - \
    PATH=/home/aehlig/bin:/usr/local/bin:/home/aehlig/bin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/sbin:/usr/local/bin:/home/aehlig/bin:/sbin:/usr/sbin:/sbin:/usr/sbin \
  /usr/local/bin/bash -c 'source external/bazel_tools/tools/genrule/genrule-setup.sh; echo hello > bazel-out/freebsd-fastbuild/genfiles/it.txt')
Target //:it up-to-date:
  /crypto/general/aehlig/.cache/bazel/_bazel_aehlig/ea3a7c72d5e8b43a0d4e9c691a291e8f/execroot/scratch/bazel-out/freebsd-fastbuild/genfiles/it.txt
(12:14:11) INFO: Elapsed time: 0.959s, Critical Path: 0.07s
(12:14:11) INFO: 1 process: 1 processwrapper-sandbox.
(12:14:11) INFO: Build completed successfully, 2 total actions
/memfs/tmp/work>bazel build -s @scratch//...
(12:14:27) INFO: Current date is 2018-06-05
(12:14:27) INFO: Analysed target @scratch//:it (1 packages loaded).
(12:14:27) INFO: Found 1 target...
(12:14:27) SUBCOMMAND: # @scratch//:it [action 'Executing genrule @scratch//:it']
(cd /crypto/general/aehlig/.cache/bazel/_bazel_aehlig/ea3a7c72d5e8b43a0d4e9c691a291e8f/execroot/scratch && \
  exec env - \
    PATH=/home/aehlig/bin:/usr/local/bin:/home/aehlig/bin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/sbin:/usr/local/bin:/home/aehlig/bin:/sbin:/usr/sbin:/sbin:/usr/sbin \
  /usr/local/bin/bash -c 'source external/bazel_tools/tools/genrule/genrule-setup.sh; echo hello > bazel-out/freebsd-fastbuild/genfiles/external/scratch/it.txt')
Target @scratch//:it up-to-date:
  /crypto/general/aehlig/.cache/bazel/_bazel_aehlig/ea3a7c72d5e8b43a0d4e9c691a291e8f/execroot/scratch/bazel-out/freebsd-fastbuild/genfiles/external/scratch/it.txt
(12:14:27) INFO: Elapsed time: 0.199s, Critical Path: 0.04s
(12:14:27) INFO: 1 process: 1 processwrapper-sandbox.
(12:14:27) INFO: Build completed successfully, 2 total actions
/memfs/tmp/work> 
```

**Comment by dkelmer** [comment] 2018-07-16 18:43
This issue should now be fixed at head. Please reopen the bug if it doesn't address your use case. Note that referencing @<workspace_name> from the command line will still be treated as a separate repository.

**Comment by ittaiz** [comment] 2018-07-16 19:06
Thanks!
I'll try to verify in the next two days locally.
If I have in my repo (`some_repo`) a target `//foo:bar` and a bzl which is
exposed to other repos and so depends on `@some_repo//foo:bar` and one last
target which uses this bzl.
Today I'll build `//foo:bar` and `@some_repo//foo:bar` right? This was
fixed

**Comment by ittaiz** [comment] 2018-07-17 10:54
I checked on a small repo and it's solved! Will hopefully verify on our bigger repo soon :)

**Comment by ittaiz** [comment] 2018-07-21 18:08
@dkelmer any chance you know if I can cherry pick this commit onto 0.15.2? Not asking git wise but rather if it's part of a chain of changes.
We've tried using HEAD and are seeing very weird errors (probably unrelated to this change)

**Comment by dkelmer** [comment] 2018-07-21 18:46
Another option is to try and use the current RC if that one is stable enough for your purposes and cherry pick just the last commit. The RC definitely contains all necessary previous commits.

**Comment by natansil** [comment] 2018-07-22 11:39
Hey @dkelmer I've tried building a bazel version, where I've started from 0.15.2 and cherry-picked c349585 and 3149beb
I'm getting the following error:
```
ERROR: /Users/natans/Work/bazel/src/main/java/com/google/devtools/build/lib/BUILD:1332:11: in cmd attribute of genrule rule //src/main/java/com/google/devtools/build/lib:merge_licenses: '$1' syntax is not supported; use '$(1)' instead for "Make" variables, or escape the '$' as '$$' if you intended this for the shell
ERROR: Analysis of target '//src:bazel' failed; build aborted: Analysis of target '//src/main/java/com/google/devtools/build/lib:merge_licenses' failed; build aborted
```

I've created a branch in my fork with these changes:
https://github.com/natansil/bazel/tree/special_version

Why am I getting this error? Do I need another commit?
CC: @ittaiz

**Comment by natansil** [comment] 2018-07-22 14:48
please note the same error happened when working from `0.16 rc3` sa well
@dkelmer @ittaiz

**Comment by dkelmer** [comment] 2018-07-23 20:04
I can't seem to reproduce the error (on linux, about to try on a mac). But the error you're seeing is unrelated to the cherry-picked changes/not an indication of other missing commits. What version of released bazel are you using to build your branch? Bazels cut past the 0.15 cut can only be built with bazel 0.15+ (issue for reference: https://github.com/bazelbuild/bazel/issues/5493). Another thing I can think to check is your bazelrc. Are there any flags you might be passing? I'll update here if I can reproduce on a mac.

**Comment by natansil** [comment] 2018-07-24 21:20
@dkelmer, I've managed to successfuly build another version in a linux docker container on top of 0.16 rc3.
https://github.com/natansil/bazel/tree/0.16-mapping-self-repo

tomorrow I'll check it more extensively. hope it should be ok...
thank you for your help!

**Comment by dkelmer** [comment] 2018-07-26 12:52
Just to follow up, I wasn't able to reproduce the error on a mac either, but I'm glad you got it working on linux :)

**Comment by dkelmer** [comment] 2018-07-30 21:28
Apologies, this is still not working for load statements in bzl files. Working on a fix now. You can look at the issue referenced above for a repro case.

**Comment by natansil** [comment] 2018-09-09 08:59
@dkelmer can you please provide the current state of this issue.
from #5059 it seems like the fix may have been rolled-back.

Does 0.17.1 have this fix?

**Comment by laurentlb** [comment] 2018-09-10 11:11
Yes. Bazel 0.17.1 contains every change up to https://github.com/bazelbuild/bazel/commit/aa118ca818baf722aede0bc48d0a17584fa45b6e (August 22nd).

**Comment by natansil** [comment] 2018-09-10 18:52
Good. Thank you @laurentlb for the quick answer.
In that case why is this issue still open?

**Comment by dkelmer** [comment] 2018-09-10 19:36
The issue is still open because the feature isn't fully working yet. In particular, the remapping does not work for repository names that appear in the WORKSPACE file itself or for bzl files loaded transitively during WORKSPACE evaluation. So the partial state is submitted and is in 0.17.1, but it may not fully work. If you would like to try anyway, it's gated behind --experimental_remap_main_repo.

**Comment by natansil** [comment] 2018-09-11 19:53
Thank you @dkelmer for the detailed answer. 
We will definitely try it out with the flag.

**Comment by ittaiz** [comment] 2018-10-10 13:43
@dkelmer I'm now in BazelCon and @ulfjack @dslomov and others have said several times that we should *not* use experimental flags and features on production builds. We are using this :) When can this be made default?

**Comment by or-shachar** [comment] 2018-10-25 14:12
Tried to run bazel 0.19.0 rc9 with that flag and got:
```ERROR: Unrecognized option: --experimental_remap_main_repo=true```

Is it possible that this flag was removed or changed into a startup option?

**Comment by katre** [comment] 2018-10-25 15:01
@or-shachar I can't reproduce that error with 0.19.0rc9 (both downloaded from https://releases.bazel.build/0.19.0/rc9/index.html or built from the branch on github):
```
$ ~/Downloads/bazel-0.19.0rc9-linux-x86_64 build --experimental_remap_main_repo=true //:star
Extracting Bazel installation...
Starting local Bazel server and connecting to it...
INFO: Analysed target //:star (3 packages loaded, 7 targets configured).
INFO: Found 1 target...
Target //:star up-to-date (nothing to build)
INFO: Elapsed time: 3.260s, Critical Path: 0.02s, Remote (0.00% of the time): [queue: 0.00%, setup: 0.00%, process: 0.00%]
INFO: 0 processes.
INFO: Build completed successfully, 1 total action
```

Are you sure which binary you're using? Let me know which version you downloaded.

**Comment by or-shachar** [comment] 2018-10-25 15:28
@katre right. false alarm. Seems like my custom installer of RC did not really link it well. 
I was running `0.13.0` 🤦‍♂️ 
Thanks for your quick reply!

**Comment by ittaiz** [comment] 2018-10-26 03:05
@dkelmer
Any updates about this with respect to WORKSPACE loading?

**Comment by achew22** [comment] 2018-11-02 02:31
This also pops up if you are importing a provider. `load("@something//:foo.bzl", "MyProvider")` and `load("//:foo.bzl", "MyProvider")` are not considered equivalent. In some cases it may make it impossible to take a provider since the internal form is referring to `//:foo.bzl%MyProvider` but you're passing in a `@something//:foo.bzl%MyProvider`.

**Comment by dkelmer** [comment] 2018-11-09 20:34
This should work with Bazel at head now. Let me know if you get a chance to test it and encounter problems!

**Comment by sergiocampama** [comment] 2019-05-09 17:56
I'm still seeing these issues in Bazel 0.25.1. Was the `--incompatible_remap_main_repo` flag made the default?

**Comment by dhalperi** [comment] 2019-05-09 18:11
@sergiocampama - yes, `experimental_enable_repo_mapping` has been the default behavior for a while, and the flag has even been removed in 0.24.0: https://github.com/bazelbuild/bazel/commit/c32c334434ddcc0a3222552f551a337b9e0234a0

**Comment by sergiocampama** [comment] 2019-05-09 18:15
what about https://github.com/bazelbuild/bazel/blob/9a005f730518fc2b818ce995cac6db9f9d0bdff3/src/main/java/com/google/devtools/build/lib/packages/StarlarkSemanticsOptions.java#L504? It is also a noop? Or was the experimental flag migrated to incompatible and never flipped?

**Comment by sergiocampama** [comment] 2019-05-09 18:16
I'm seeing the exact provider missing error described in this issue in https://buildkite.com/bazel/rules-apple-darwin/builds/827#5ef4767f-56d7-48b6-a07e-992c9fa26db9

**Comment by katre** [comment] 2019-05-09 18:19
The flag is now `--incompatible_remap_main_repo`: https://source.bazel.build/bazel/+/master:src/main/java/com/google/devtools/build/lib/packages/StarlarkSemanticsOptions.java;l=503?q=main_repo

It was scheduled to be flipped but there was missing functionality, and it was not made default in 0.26.

See the tracking issue: #7130.

**Comment by sergiocampama** [comment] 2019-05-09 18:54
Shouldn't this issue be open then until the incompatible flag is flipped?

**Comment by aehlig** [comment] 2019-08-23 12:12
Interestingly, the issue is not fully solved by (the current implementation of) `--incompatible_remap_main_repo` (#7130). Consider the following test cases
- https://bazel-review.googlesource.com/c/bazel/+/111890/1
- https://bazel-review.googlesource.com/c/bazel/+/111891/1

The first test passes, whereas the second fails in [the build with remapping](https://bazel-review.googlesource.com/c/bazel/+/111891/1); interestingly enough, that command passes if we build `//:y` instead of `@foo//:y`.

**Comment by aehlig** [comment] 2019-12-03 11:59
#7130 is flipped now.

**Closed by aehlig** 2019-12-03 11:59 UTC
Labels: P1, team-Starlark

**Comment by ittaiz** [comment] 2020-07-20 03:42
@aehlig if there are test cases that are failing with the flag on, shouldn't they be fixed?

**Comment by katre** [comment] 2020-07-20 12:34
@ittaiz Klaus is no longer working at Google or on Bazel. As far as I know there are open issues for a few related problems, if there are any more, can you file them separately?

**Comment by ittaiz** [comment] 2020-07-20 16:54
Didn't know that. Will do, thanks.
