### ISSUE TITLE
JavaInfo must be referenced by full path in queries since 7.0.0

### ISSUE THREAD

**Issue by tpasternak** [bazelbuild/bazel#20745] opened 2024-01-04 14:02 UTC
### Description of the bug:

not sure if this is a bug, but since 7.0.0 the JavaInfo has to be refernced directly in queries:

### Which category does this issue belong to?

Java Rules

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

`USE_BAZEL_VERSION=7.x bazelisk cquery --starlark:expr='[f for f in providers(target)]'  --output=starlark -- <some_java_library> `

### Which operating system are you running Bazel on?

Linux

### What is the output of `bazel info release`?

7.0.0

### Is this a regression? If yes, please try to identify the Bazel commit where the bug was introduced.

n/a

### Any other information, logs, or outputs that you want to share?

`USE_BAZEL_VERSION=6.x bazelisk cquery --starlark:expr='[f for f in providers(target)]'  --output=starlark -- //greeting_lib` results in: 
```
["LicenseInfo", "@@_builtins//:common/java/java_info.bzl%JavaInfo", "InstrumentedFilesInfo", "ProguardSpecProvider", "FileProvider", "FilesToRunProvider", "OutputGroupInfo"]
```

while `USE_BAZEL_VERSION=6.x bazelisk cquery --starlark:expr='[f for f in providers(target)]'  --output=starlark -- //greeting_lib` in:
```
["JavaInfo", "InstrumentedFilesInfo", "ProguardSpecProvider", "FileProvider", "FilesToRunProvider", "OutputGroupInfo"]
```

**Comment by tjgq** [comment] 2024-01-04 14:10
Duplicate of https://github.com/bazelbuild/bazel/issues/20473, please refer to the discussion there.

**Closed by tjgq** 2024-01-04 14:10 UTC
Labels: type: bug, team-Rules-Java, untriaged
