### ISSUE TITLE
Compile Line Length Limit hit under Windows

### ISSUE THREAD

**Issue by herry-c** [bazelbuild/bazel#13691] opened 2021-07-16 08:28 UTC
> ATTENTION! Please read and follow:
> - if this is a _question_ about how to build / test / query / deploy using Bazel, or a _discussion starter_, send it to bazel-discuss@googlegroups.com
> - if this is a _bug_ or _feature request_, fill the form below as best as you can.

### Description of the problem / feature request:

> I tried to compile the Java project on Windows 10, but because the project has too many dependencies, an error message is displayed during dependency parsing, indicating that command is longer than CreateProcessW's limit. My maven_install() defines nearly 500 dependencies.

### Feature requests: what underlying problem are you trying to solve with this feature?

>I saw in historical problems that the --features=compiler_param_file method was provided to file parameters, but it did not take effect in local experiments.How can I solve this problem? My project does rely on many third-party components.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

 ```bazel
# worspace
maven_install(
    artifacts = [
        "org.apache.zookeeper:zookeeper-jute:3.6.0",
        "org.apache.zookeeper:zookeeper-jute:3.6.2",
        "org.apache.zookeeper:zookeeper:3.6.2-h0.gdd.sop.r18",
        "io.grpc:grpc-api:1.36.1",
        ...
        # ....nearly 500 dependencies
]
)
```

### What operating system are you running Bazel on?
windows10
> Replace this line with your answer.

### What's the output of `bazel info release`?
```
no such package '@maven//': Error while fetching artifact with coursier: java.io.IOException: ERROR: 
src/main/native/windows/process.cc(165): CreateProcessWithExplicitHandles("D:\tools\javajdk\bin\java" -noverify -jar 
C:/users/xxx/esyrauaw/external/maven/coursier fetch org.apache.zookeeper:zookeeper-jute:3.6.0 
org.apache.zookeeper:zookeeper-jute:3.6.2 org.apache.zookeeper:zookeeper:3.6.2-h0.gdd.sop.r18 io.grpc:grpc-api:1.36.1 
io.grpc:grpc-context:1.36.1 io.grpc:grpc-core:1.36.1 io.grpc:grpc-grpclb:1.36.1 io.grpc:grpc-netty:1.36.1 io.grpc:grpc-protobuf-
lite:1.36.1 io.grpc:grpc-protobuf:1.36.1 io.grpc:grpc-stub:1.36.1 org.quartz-scheduler.in(...)): command is longer than 
CreateProcessW's limit (32767 characters)
```
> Replace this line with your answer.

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

> Replace this line with your answer.

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

> Replace this line with your answer.

###  Have you found anything relevant by searching the web?

> Replace these lines with your answer.
>
> Places to look:
> - StackOverflow: http://stackoverflow.com/questions/tagged/bazel
> - GitHub issues: https://github.com/bazelbuild/bazel/issues
> - email threads on https://groups.google.com/forum/#!forum/bazel-discuss

### Any other information, logs, or outputs that you want to share?

> Replace these lines with your answer.
>
> If the files are large, upload as attachment or provide link.

**Comment by meteorcloudy** [comment] 2021-07-21 08:39
Windows has a limit of 32767 characters for command line length. This command line is generated by [rules_jvm_external](https://github.com/bazelbuild/rules_jvm_external), please file an issue there. I think the correct fix is to use a parameter file when the command line length exceeds that limit.

**Comment by meteorcloudy** [comment] 2021-07-21 08:39
As this is not a bug in Bazel, I'll close this issue.

**Closed** 2021-07-21 08:42 UTC
Labels: area-Windows, platform: windows, team-XProduct
