### ISSUE TITLE
Unable to load package for '@bazel_tools//third_party/protobuf/3.2.0:protobuf.bzl

### ISSUE THREAD

**Issue by prestonvanloon** [bazelbuild/bazel#3587] opened 2017-08-18 23:20 UTC
### Description of the problem / feature request / question:
```
ERROR: error loading package '@bazel_tools//src/main/protobuf': Extension file not found. Unable to load package for '@bazel_tools//third_party/protobuf/3.2.0:protobuf.bzl': BUILD file not found on package path
```

The goal here is to query `@bazel_tools` to see what targets are available. My specific use case is that I am looking for the well known protos https://github.com/bazelbuild/bazel/tree/master/third_party/protobuf

### If possible, provide a minimal example to reproduce the problem:
Build bazel at https://github.com/bazelbuild/bazel/commit/2f38404728a12840e416566b453e9cdebab5d859

Run the following in any workspace: 
```
/tmp/bazel/bazel-bin/src/bazel query "@bazel_tools//src/main/protobuf/..."
```

### Environment info
* Operating System:
ubuntu 17

* Bazel version (output of `bazel info release`):
development version

* If `bazel info release` returns "development version" or "(@non-git)", please tell us what source tree you compiled Bazel from; git commit hash is appreciated (`git rev-parse HEAD`):
2f38404728a12840e416566b453e9cdebab5d859

### Anything else, information or logs or outputs that would be helpful?
(If they are large, please upload as attachment or provide link).

https://github.com/googleapis/googleapis/issues/317
https://github.com/bazelbuild/bazel/issues/2265
https://github.com/google/protobuf/issues/2763

**Comment by prestonvanloon** [comment] 2017-08-18 23:33
It may be a wider issue, but querying like `bazel query @bazel_tools//third_party/...` fails due to other extensions missing. 

```
tmp/bazel/bazel-bin/src/bazel query "@bazel_tools//third_party/..." 
ERROR: error loading package '@bazel_tools//third_party/checker_framework_dataflow': Extension file not found. Unable to load file '@bazel_tools//tools/build_rules:java_rules_skylark.bzl': file doesn't exist or isn't a file
```

**Comment by prestonvanloon** [comment] 2017-08-18 23:40
In my follow up comment, that issue can be resolved with a change like: 
```
-load("//tools/build_rules:java_rules_skylark.bzl", "bootstrap_java_library")
+load("@//tools/build_rules:java_rules_skylark.bzl", "bootstrap_java_library")
```
I'll create a PR for this later.

**Comment by prestonvanloon** [comment] 2017-08-19 00:03
So I created that PR, but the protobuf srcs in `third_party` don't return targets in the query results. Is there something that needs to be done to make these protos available via `@bazel_tools`? 

I tried removing the visibility restriction on the srcs `filegroup` in `third_party/protobuf/BUILD`, but no luck.

**Comment by meisterT** [comment] 2020-05-15 12:41
Dupe of #1787

**Closed by meisterT** 2020-05-15 12:41 UTC
Labels: P4, good first issue, team-XProduct, type: bug
