### ISSUE TITLE
external repositories without an embedded name shouldn't warn

### ISSUE THREAD

**Issue by shahms** [bazelbuild/bazel#1166] opened 2016-04-20 16:52 UTC
After https://github.com/bazelbuild/bazel/commit/857cda2c45a5cc68c3fa398311c48c571a64915d all external repository rules warn about mismatched local/remote workspace names, even the `new_*` variety, for which there is no explicit external workspace name.

Either the warning should take the new `__main__` name into account or (arguably better) generate an initial `WORKSPACE` file with `workspace(name="{local_repository_name}")` instead.

**Comment by kchodorow** [comment] 2016-04-20 16:55
There is actually an LGTM'd (but not pushed yet) fix for this.

**Comment by shahms** [comment] 2016-04-20 17:06
Awesome, thanks!

**Comment by shahms** [comment] 2016-04-21 15:59
I don't know how to re-open, but this only mostly fixed it.  There are a couple of cases not currently covered (at least for Kythe, there may be others):

1. maven_jar still warns
2. http_file still warns
3. git_repository for a repository with a WORKSPACE which doesn't set the name still warns

**Comment by kchodorow** [comment] 2016-05-02 18:05
3. is working as intended.  Working on the other two.

**Comment by shahms** [comment] 2016-05-03 16:35
That commit doesn't appear to have fixed the issue (unless 4b71d2e1bc3afa0ce0a5b6e68dac3c559654d975 undid it).

    $ bazel info release
    release 0.2.2b-2016-05-03 (@4b71d2e)
    $ bazel clean
    $ bazel test //...
    WARNING: <snip>/external/com_googlesource_code_re2/WORKSPACE:1: Workspace name in <snip>/external/com_googlesource_code_re2/WORKSPACE (@__main__) does not match the name given in the repository's definition (@com_googlesource_code_re2); this will cause a build error in future versions.
    WARNING: <snip>/external/com_apache_org_license_2_0/WORKSPACE:1: Workspace name in <snip>/external/com_apache_org_license_2_0/WORKSPACE (@__main__) does not match the name given in the repository's definition (@com_apache_org_license_2_0); this will cause a build error in future versions.
    WARNING: <snip>/external/maven_guava/WORKSPACE:1: Workspace name in <snip>/external/maven_guava/WORKSPACE (@__main__) does not match the name given in the repository's definition (@maven_guava); this will cause a build error in future versions.


The `@com_googlesource_code_re2` repository was case 3, but `@com_apache_org_license_2_0` is an `http_file`.

**Comment by damienmg** [comment] 2016-05-03 17:00
Kristina: another fallout of 4b71d2e

**Closed** 2016-05-20 14:57 UTC
Labels: category: External repositories, P2, type: bug

**Comment by kchodorow** [comment] 2016-05-20 15:02
@shahms: bazel clean doesn't actually delete the external repositories and the fact that they needed to change wasn't noticed (because of the bug d5512bf fixed).

**Comment by shahms** [comment] 2016-05-20 15:31
Thanks, Kristina.  This does appear to be fixed (except for the upstream which has a nameless WORKSPACE, which you've indicated is intentional).

**Comment by kchodorow** [comment] 2016-05-20 16:26
What do you mean, the upstream has a nameless workspace?

**Comment by shahms** [comment] 2016-05-20 16:27
I mean the upstream external repository has a WORKSPACE file with no `workspace(name=...)` directive:

https://code.googlesource.com/re2/+/master/WORKSPACE
