### ISSUE TITLE
Allow @canonical//targets of main repository

### ISSUE THREAD

**Issue by jart** [bazelbuild/bazel#1866] opened 2016-09-30 20:38 UTC
This issue is probably the biggest issue for the code health of Closure Rules.

1. I can't reference targets from my main repository from within new_http_archive BUILD file
2. *Tangential but related:* When writing `deps` inside my build files, I can't use a canonical naming convention including the `@workspace_name//`, which might confuse people who try to copy and paste stuff from my build files into their own project.

## Explanation

If I define a custom BUILD file for a `new_http_archive`, I want that BUILD file to be able to `load()` a Skylark rule I defined in my repository, assuming that I've set `workspace(name)` accordingly. But it isn't able to do this. It's only able to reference targets in its own build file, or in the build files of other external repositories I've defined.

Here's a more detailed explanation. Assume I have the following in my `WORKSPACE` file:

```python
workspace(name = "io_bazel_rules_closure")

new_http_archive(
    name = "soy_jssrc",
    sha256 = "15f5bf0b8ca40211a29bcd6486bd3198155ecc76e8bbf06407deb695ca848be6",
    url = "http://bazel-mirror.storage.googleapis.com/repo1.maven.org/maven2/com/google/template/soy/2016-08-25/soy-2016-08-25-jssrc_js.jar",
    build_file = str(Label("//:soy_jssrc.BUILD")),
    type = "zip",
)
```

I want to be able to write `soy_jssrc.BUILD` to look like this:

```python
load("@io_bazel_rules_closure//closure:defs.bzl", "closure_js_library")

licenses(["notice"])  # Apache 2.0

closure_js_library(
    name = "jssrc",
    srcs = [
        "jspbconversions.js",
        "soydata_converters.js",
        "soyutils_usegoog.js",
    ],
    deps = ["@closure_library//:library"],
    visibility = ["//visibility:public"],
)
```

But this happens:

ERROR: error loading package '@soy_jssrc//': Encountered error while reading extension file 'closure/compiler/closure_js_library.bzl': no such package '@io_bazel_rules_closure//closure/compiler': error loading package 'external':  **The repository named 'io_bazel_rules_closure' could not be resolved.**

## Workaround

What I'm doing right now is I change `soy_jssrc.BUILD` to just use `filegroup` instead of `closure_js_library`.

```python
licenses(["notice"])  # Apache 2.0

filegroup(
    name = "jssrc",
    srcs = [
        "jspbconversions.js",
        "soydata_converters.js",
        "soyutils_usegoog.js",
    ],
    visibility = ["//visibility:public"],
)
```

Then in my main repository, I write a second build file called `third_party/javascript/jssrc/BUILD` where I use the proper rule that references the fileset in the external build file.

```python
licenses(["notice"])  # Apache 2.0                                                                                                                                                                     

load("//closure:defs.bzl", "closure_js_library")

closure_js_library(
    name = "jssrc",
    srcs = ["@soy_jssrc//:jssrc"],
    deps = ["//closure/library"],
    visibility = ["//visibility:public"],
)
```

It works. But I need two separate build files to define each third party JavaScript dependency.

## Solution

It would be nice if Bazel simply said, "oh you took the time to put `workspace(name = "foo")` in your `WORKSPACE` file" and then was smart enough to know that `@foo//bar` points to stuff in the main repository. This would solve both of the concerns above.

## Alternatives Considered

One thing I could do is I could limit bazelbuild/rules_closure to *only* have the Skylark rules and nothing more. Then I could start a separate project called bazelbuild/kitchensink_closure which defines the rules as an external. That project would then be able to reference the rules in its external build files.

The problem with this is the rules and the external dependencies are so tightly intertwined. The closure_js_binary needs to directly reference targets in `@closure_library` in order to compile, such as `base.js`. These external dependencies are all very intertwined. The rules themselves need to ship with the kitchen sink in order to be useful.

CC: @kchodorow

**Comment by steven-johnson** [comment] 2016-09-30 22:16
> Tangential but related: When writing deps inside my build files, I can't use a canonical 
> naming convention including the @workspace_name//, which might confuse people who 
> try to copy and paste stuff from my build files into their own project.

Big +1 to this; I'd like to be able to have various "example" subprojects be able to refer to the top-level workspace in a canonical way.

**Comment by ittaiz** [comment] 2016-10-01 03:09
I also spent a reasonable amount of hours on copying an example from
rules_scala only to understand there is a difference in how one relates to
the external repo

**Comment by bsilver8192** [comment] 2016-10-02 05:17
+1. For reference, #1033 started out as basically the same thing (but the title and description of this bug are much more focused, so it isn't really a duplicate).

**Comment by kchodorow** [comment] 2016-10-03 13:55
This is a duplicate of #1248, but since there's so much interest, let me give an update here.

This is definitely something we want to implement.

Right now, the blocking issue is: if you have your workspace in ~/rules_closure and you create a WORKSPACE file that says `workspace(name = "io_bazel_rules_closure")`,  then the execution root will put everything under `execroot/rules_closure/` (not execroot/io_bazel_rules_closure) so Bazel won't be able to find the files.  Bazel figures out what this directory name should be extremely early in Bazel's lifecycle and it's threaded throughout the codebase.  I've been chipping away at the places Bazel refers to this (incorrect) directory, see, for example:

* 3fd3f1b7c103379353dd50756aefc051761cfb61
* 8cb36d6bee170da857df3e50e72c8dcfceb5b7ff
* 94e2742db235c7bf7d254a8d5a4c10ff3495c656
* 36a6c17629e76872a876cd313623246d4d0aa082, partially reverted by 5c7f4b0a488a859a94e073cf0946a9552e68ae7c
* e423fdb81d601886299f53081238bbe2874d26ce
* And many more!

So progress is being made on this (it's definitely on our radar!), but there's a lot more to be done.

**Closed by kchodorow** 2016-10-03 13:55 UTC
