### ISSUE TITLE
Windows: CreateProcess(): The parameter is incorrect (due to long argument list)

### ISSUE THREAD

**Issue by j3parker** [bazelbuild/bazel#4083] opened 2017-11-13 20:27 UTC
### Description of the problem:

When the total length of the arguments + executable (+ null terminator etc.) exceeds 32,767 Bazel fails ungracefully with the error

```
Action failed to execute: java.io.IOException: CreateProcess(): The parameter is incorrect.
```

It would be nice if this had a better error message, at least.

Generally this is pretty worrying because Bazel seems to like creating very large argument lists and this definitely something Bazel can just "fix" :) I've been able to solve my specific case with [param files](https://docs.bazel.build/versions/master/skylark/lib/Args.html#use_param_file) but I think there should be an error message so folks know what's up.

### Minimal reproduction:

In `foo.bzl`:

```BUILD
def _broken(ctx):
  dummy = ctx.actions.declare_file("dummy.txt")

  ctx.actions.run(
    outputs = [dummy],
    executable = "echo",
    arguments = ["x"*32760],
  )

broken = rule(
  implementation = _broken,
  outputs = {"foo": "dummy.txt"},
)
```

In a `BUILD`:

```BUILD
load("//:foo.bzl", "broken")

broken(name = "whoops")
```

Changing 32760 to something lower (e.g. 32759) causes the build to fail for legitimate reasons.

* Bazel version (output of `bazel info release`): release 0.7.0

###  Have you found anything relevant by searching the web?

The following issues may be related. They both contain the same error message (`CreateProcess(): The parameter is incorrect`) and the one's log showed what appeared to be a 51k long process creation.

* [Zipper fails under Windows due to incorrect parameters](https://github.com/bazelbuild/bazel/issues/2164)
* [appengine_war cannot complete due to incorrect zipper parameters](https://github.com/bazelbuild/rules_appengine/issues/29)

### Anything else, information or logs or outputs that would be helpful?

* [MSDN docs](https://msdn.microsoft.com/en-us/library/windows/desktop/ms682425(v=vs.85).aspx) for `CreateProcess` which documents the 32,767 restriction

**Comment by laszlocsomor** [comment] 2017-11-15 15:05
Thanks for reporting this error!
I started seeing the same error a few days ago when building Bazel itself. I'll investigate.

**Comment by j3parker** [comment] 2017-11-15 15:16
I noticed it while trying to get my Windows build of Bazel to run too, I think during some code coverage stuff (I haven't looked too closely.)

**Comment by j3parker** [comment] 2017-11-30 21:10
In 0.8.0 the error message now looks like:

```
Action failed to execute: java.io.IOException: ERROR: src/main/native/windows/processes-jni.cc(410): nativeCreateProcess(csc.exe): The filename or extension is too long.
```

**Comment by laszlocsomor** [comment] 2017-12-01 09:02
0.8.0 doesn't yet contain https://github.com/Androbin/bazel/commit/b110dfb5cca8961051426e669566cc3aeeac55ee .

We also need your PR (https://github.com/bazelbuild/bazel/pull/4088) with the Java-side changes, so the Java code won't even attempt to create a process if it knows the cmdline is too long.

I figured that one situation where Bazel produces this error is with Java header compilation. Bazel tries to compile all headers in one action, passing all files as arguments. If that fails, Bazel just retries using parameter files. That's why the error is non-fatal, see issue #4096.

**Comment by laszlocsomor** [comment] 2017-12-13 16:54
Dropping to P2, because Bazel still displays error messages making this a problem with usability, the errors are benign so Bazel is usable.

**Comment by laszlocsomor** [comment] 2018-03-28 14:26
I think this is a duplicate of https://github.com/bazelbuild/bazel/issues/4096.

**Closed by laszlocsomor** 2018-03-28 14:26 UTC
Labels: P2, category: misc > misc, platform: windows, type: bug
