### ISSUE TITLE
Make $(location) work for top-level executables

### ISSUE THREAD

**Issue by jmmv** [bazelbuild/bazel#966] opened 2016-02-23 19:25 UTC
Consider the following workspace:

```
cat >WORKSPACE <<EOF
workspace(name = 'test')
EOF

cat >BUILD <<EOF
genrule(
    name = 'the_test',
    cmd = "$(location :hello.sh) >$@",
    outs = ['test_output'],
    tools = [":hello.sh"],
)
EOF

cat >hello.sh <<EOF
#! /bin/sh
echo Hello
EOF
chmod +x hello.sh
```

Given the above, `the_test` is unbuildable because the execution of `hello.sh` fails. The problem is that `$(location :hello.sh)` expands to simply `hello.sh` which cannot be resolved given a sane `PATH` (where a "sane path" means a set of directories that does not include the current directory for security reasons; see #958).

A possible fix would be to prefix all relative paths emitted by `$(location)` with `./`. A worse fix (because it wouldn't be consistent in all cases) would be to do so only for outputs composed of a single path component. I don't know what the implications of doing any of these two would be.

**Comment by bsilver8192** [comment] 2016-02-23 19:46
Sounds like a duplicate of #347.

**Comment by jmmv** [comment] 2016-02-23 19:49
Indeed. Closing as such. I forgot to search for duplicates before filing this particular report.

**Closed** 2016-02-23 19:50 UTC
Labels: duplicate
