### ISSUE TITLE
no good error message on external repo download failure

### ISSUE THREAD

**Issue by brown** [bazelbuild/bazel#5731] opened 2018-08-01 14:27 UTC
### Description of the problem / feature request:

Bazel does not output a descriptive error when downloading external repos fails.

### Feature requests: what underlying problem are you trying to solve with this feature?

Build failure is mysterious if Bazel outputs no description of why the build failed.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Run Bazel with a WORKSPACE that needs to download external repos while your machine is not
connected to a network.

### What operating system are you running Bazel on?

Debian Linux.

### What's the output of `bazel info release`?

release 0.15.0

### Any other information, logs, or outputs that you want to share?

When I build bazel 0.16.0 using bazel 0.15.0 without setting up an http proxy, so that bazel
is unable download artifacts, I get the following output.  The output does not describe why
the build has failed.

home [106226]  bazel build src:bazel-bin Starting local Bazel server and connecting to it...
...........
Loading: 
Loading: 0 packages loaded
Analyzing: target //src:bazel-bin (2 packages loaded)
Analyzing: target //src:bazel-bin (41 packages loaded)
Analyzing: target //src:bazel-bin (54 packages loaded)
Analyzing: target //src:bazel-bin (54 packages loaded)
Analyzing: target //src:bazel-bin (54 packages loaded)
Analyzing: target //src:bazel-bin (54 packages loaded)
Analyzing: target //src:bazel-bin (54 packages loaded)
Analyzing: target //src:bazel-bin (54 packages loaded)
Analyzing: target //src:bazel-bin (54 packages loaded)
Analyzing: target //src:bazel-bin (54 packages loaded)
Analyzing: target //src:bazel-bin (54 packages loaded)
Analyzing: target //src:bazel-bin (54 packages loaded)
Analyzing: target //src:bazel-bin (54 packages loaded)
Analyzing: target //src:bazel-bin (54 packages loaded)
ERROR: build interrupted
INFO: Elapsed time: 58.017s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (54 packages loaded)
FAILED: Build did NOT complete successfully (54 packages loaded)

**Comment by aehlig** [comment] 2019-04-26 10:37
As far as I can see, this is a duplicate of #3851. Trying with current bazel with the pending fix for #3851 applied seems to also have this issue fixed.

Please reopen, with more detailled instructions if the problem remains after https://bazel-review.googlesource.com/c/bazel/+/97551 is submitted.

**Closed by aehlig** 2019-04-26 10:37 UTC
Labels: P1, team-ExternalDeps, type: bug
