### ISSUE TITLE
Bazel CI: rules_nodejs failing in downstream

### ISSUE THREAD

**Issue by meteorcloudy** [bazelbuild/bazel#10554] opened 2020-01-09 15:01 UTC
https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/1344#1691d1c8-522e-4710-baa9-2161041776b8/686-759

```
=================== Test output for //e2e:e2e_bazel_managed_deps:
[test_runner.js] running 'bazel version'
$TEST_TMPDIR defined: output root default is '/var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/46c4c29f5d9b2d484aea1632cdfa4e0a/execroot/build_bazel_rules_nodejs/_tmp/94c5d7d14cbe2a3ef9ba6b4e108b5fb8' and max_idle_secs default is '15'.
ERROR: The project you're trying to build requires Bazel /tmp/tmpdv0dc1z8/bazel-bin/src/bazel (specified in $USE_BAZEL_VERSION), but it wasn't found in /var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/46c4c29f5d9b2d484aea1632cdfa4e0a/external/build_bazel_bazel_2_0_0.
```

The e2e test is failing because inside the test, Bazel 2.0.0 is used and at the same time we pass `--test_env=USE_BAZEL_VERSION=<path_to_bazel_binary>`. The shell wrapper of 2.0.0 respects `USE_BAZEL_VERSION` but it doesn't accept this env var as path.

/cc @philwo

**Comment by philwo** [comment] 2020-01-09 19:51
Thanks for the fix :)

Two questions:
- Why do they test with specific Bazel versions using their own mechanism, instead of using the mechanism that Bazel CI offers? (the `bazel: $version` thing in the YAML).
- Where does the shell wrapper come from? It's only installed when you install Bazel via `apt-get`, but that should never be the case on our CI, right?

**Comment by alexeagle** [comment] 2020-01-10 03:43
@gregmagolan can probably answer

**Comment by meteorcloudy** [comment] 2020-01-10 09:51
> - Why do they test with specific Bazel versions using their own mechanism, instead of using the mechanism that Bazel CI offers? (the bazel: $version thing in the YAML).

rules_nodejs has its own [bazel_integration_test.bzl](https://github.com/bazelbuild/rules_nodejs/blob/master/internal/bazel_integration_test/bazel_integration_test.bzl) implementation, where you can specify which Bazel version is [supported](https://github.com/bazelbuild/rules_nodejs/blob/f217519253e7468de82c2dfccdfedc7dac4f98be/index.bzl#L98).

> - Where does the shell wrapper come from? It's only installed when you install Bazel via apt-get, but that should never be the case on our CI, right?

rules_nodejs also uses the [bazel_integration_test](https://github.com/bazelbuild/bazel-integration-testing) framework to get specific version of Bazel binary. And it downloads the installer, unzip it and offers both `bazel` (the wrapper) and `bazel-real`, see
https://github.com/bazelbuild/bazel-integration-testing/blob/922d2b04bfb9721ab14ff6d26d4a8a6ab847aa07/tools/repositories.bzl#L62

**Comment by gregmagolan** [comment] 2020-01-15 06:26
Thanks for the fix @meteorcloudy . Closing this as its is fixed by https://github.com/bazelbuild/rules_nodejs/pull/1538.

I opened up https://github.com/bazelbuild/rules_nodejs/issues/1546 to follow up on the root cause.

**Closed** 2020-01-21 10:08 UTC
Labels: P1, breakage, team-EngProd
