### ISSUE TITLE
Error in building bazel 0.17.1 on macOS El Capitan

### ISSUE THREAD

**Issue by fxcoudert** [bazelbuild/bazel#6188] opened 2018-09-20 08:00 UTC
bazel 0.17.1 fails to build from source on macOS El Capitan: https://github.com/Homebrew/homebrew-core/pull/32104 It works with later macOS versions, from Sierra to Mojave.

Running `./compile.sh` is successful, but when we run `./output/bazel --output_user_root /private/tmp/bazel-20180920-17363-1gm6zdi/output_user_root build scripts:bash_completion` this leads to the following error:

```
[1,523 / 1,590] Building src/main/java/com/google/devtools/build/lib/rules/cpp/libcpp.jar (110 source files) and running annotation processors (SkylarkCallableProcessor, SkylarkConfigurationFieldProcessor, AutoCodecProcessor, OptionProcessor, AutoAnnotationProcessor, AutoValueProcessor) [for host]; 12s worker ... (4 actions, 3 running)
ERROR: /private/tmp/bazel-20180920-17363-1gm6zdi/sources/src/BUILD:248:2: Executing genrule //src:package-zip failed (Exit 18)
warning:  symbolic link (jdk/legal/java.corba/LICENSE) failed
warning:  symbolic link (jdk/legal/java.corba/ADDITIONAL_LICENSE_INFO) failed
warning:  symbolic link (jdk/legal/java.corba/ASSEMBLY_EXCEPTION) failed
warning:  symbolic link (jdk/legal/jdk.xml.bind/LICENSE) failed
warning:  symbolic link (jdk/legal/jdk.xml.bind/ADDITIONAL_LICENSE_INFO) failed
warning:  symbolic link (jdk/legal/jdk.xml.bind/ASSEMBLY_EXCEPTION) failed
warning:  symbolic link (jdk/legal/jdk.xml.bind/xmlresolver.md) failed
warning:  symbolic link (jdk/legal/jdk.internal.vm.ci/LICENSE) failed
warning:  symbolic link (jdk/legal/jdk.internal.vm.ci/ADDITIONAL_LICENSE_INFO) failed
warning:  symbolic link (jdk/legal/jdk.internal.vm.ci/ASSEMBLY_EXCEPTION) failed
warning:  symbolic link (jdk/legal/java.xml.crypto/LICENSE) failed
warning:  symbolic link (jdk/legal/java.xml.crypto/ADDITIONAL_LICENSE_INFO) failed
warning:  symbolic link (jdk/legal/java.xml.crypto/ASSEMBLY_EXCEPTION) failed
warning:  symbolic link (jdk/legal/jdk.management.agent/LICENSE) failed
warning:  symbolic link (jdk/legal/jdk.management.agent/ADDITIONAL_LICENSE_INFO) failed
warning:  symbolic link (jdk/legal/jdk.management.agent/ASSEMBLY_EXCEPTION) failed
warning:  symbolic link (jdk/legal/jdk.crypto.ec/LICENSE) failed
warning:  symbolic link (jdk/legal/jdk.crypto.ec/ADDITIONAL_LICENSE_INFO) failed
warning:  symbolic link (jdk/legal/jdk.crypto.ec/ASSEMBLY_EXCEPTION) failed
warning:  symbolic link (jdk/legal/java.desktop/LICENSE) failed
warning:  symbolic link (jdk/legal/java.desktop/ADDITIONAL_LICENSE_INFO) failed
warning:  symbolic link (jdk/legal/java.desktop/ASSEMBLY_EXCEPTION) failed
warning:  symbolic link (jdk/legal/jdk.jdeps/LICENSE) failed
warning:  symbolic link (jdk/legal/jdk.jdeps/ADDITIONAL_LICENSE_INFO) failed
warning:  symbolic link (jdk/legal/jdk.jdeps/ASSEMBLY_EXCEPTION) failed
warning:  symbolic link (jdk/legal/jdk.jshell/LICENSE) failed
warning:  symbolic link (jdk/legal/jdk.jshell/ADDITIONAL_LICENSE_INFO) failed
warning:  symbolic link (jdk/legal/jdk.jshell/ASSEMBLY_EXCEPTION) failed
warning:  symbolic link (jdk/legal/java.datatransfer/LICENSE) failed
warning:  symbolic link (jdk/legal/java.datatransfer/ADDITIONAL_LICENSE_INFO) failed
warning:  symbolic link (jdk/legal/java.datatransfer/ASSEMBLY_EXCEPTION) failed
warning:  symbolic link (jdk/legal/jdk.accessibility/LICENSE) failed
warning:  symbolic link (jdk/legal/jdk.accessibility/ADDITIONAL_LICENSE_INFO) failed
warning:  symbolic link (jdk/legal/jdk.accessibility/ASSEMBLY_EXCEPTION) failed
warning:  symbolic link (jdk/legal/java.sql/LICENSE) failed
warning:  symbolic link (jdk/legal/java.sql/ADDITIONAL_LICENSE_INFO) failed
warning:  symbolic link (jdk/legal/java.sql/ASSEMBLY_EXCEPTION) failed
warning:  symbolic link (jdk/legal/java.se.ee/LICENSE) failed
warning:  symbolic link (jdk/legal/java.se.ee/ADDITIONAL_LICENSE_INFO) failed
warning:  symbolic link (jdk/legal/java.se.ee/ASSEMBLY_EXCEPTION) failed
warning:  symbolic link (jdk/legal/java.xml.bind/LICENSE) failed
warning:  symbolic link (jdk/legal/java.xml.bind/ADDITIONAL_LICENSE_INFO) failed
warning:  symbolic link (jdk/legal/java.xml.bind/ASSEMBLY_EXCEPTION) failed
warning:  symbolic link (jdk/legal/jdk.jlink/LICENSE) failed
warning:  symbolic link (jdk/legal/jdk.jlink/ADDITIONAL_LICENSE_INFO) failed
warning:  symbolic link (jdk/legal/jdk.jlink/ASSEMBLY_EXCEPTION) failed
warning:  symbolic link (jdk/legal/jdk.javadoc/LICENSE) failed
warning:  symbolic link (jdk/legal/jdk.javadoc/ADDITIONAL_LICENSE_INFO) failed
warning:  symbolic link (jdk/legal/jdk.javadoc/ASSEMBLY_EXCEPTION) failed
warning:  symbolic link (jdk/legal/jdk.jdi/LICENSE) failed
warning:  symbolic link (jdk/legal/jdk.jdi/ADDITIONAL_LICENSE_INFO) failed
warning:  symbolic link (jdk/legal/jdk.jdi/ASSEMBLY_EXCEPTION) failed
warning:  symbolic link (jdk/legal/jdk.hotspot.agent/LICENSE) failed
warning:  symbolic link (jdk/legal/jdk.hotspot.agent/ADDITIONAL_LICENSE_INFO) failed
warning:  symbolic link (jdk/legal/jdk.hotspot.agent/ASSEMBLY_EXCEPTION) failed
warning:  symbolic link (jdk/legal/jdk.jstatd/LICENSE) failed
warning:  symbolic link (jdk/legal/jdk.jstatd/ADDITIONAL_LICENSE_INFO) failed
warning:  symbolic link (jdk/legal/jdk.jstatd/ASSEMBLY_EXCEPTION) failed
warning:  symbolic link (jdk/legal/java.smartcardio/LICENSE) failed
warning:  symbolic link (jdk/legal/java.smartcardio/ADDITIONAL_LICENSE_INFO) failed
warning:  symbolic link (jdk/legal/java.smartcardio/ASSEMBLY_EXCEPTION) failed
warning:  symbolic link (jdk/legal/java.rmi/LICENSE) failed
warning:  symbolic link (jdk/legal/java.rmi/ADDITIONAL_LICENSE_INFO) failed
warning:  symbolic link (jdk/legal/java.rmi/ASSEMBLY_EXCEPTION) failed
warning:  symbolic link (jdk/legal/jdk.sctp/LICENSE) failed
warning:  symbolic link (jdk/legal/jdk.sctp/ADDITIONAL_LICENSE_INFO) failed
warning:  symbolic link (jdk/legal/jdk.sctp/ASSEMBLY_EXCEPTION) failed
warning:  symbolic link (jdk/legal/jdk.scripting.nashorn/LICENSE) failed
warning:  symbolic link (jdk/legal/jdk.scripting.nashorn/ADDITIONAL_LICENSE_INFO) failed
warning:  symbolic link (jdk/legal/jdk.scripting.nashorn/ASSEMBLY_EXCEPTION) failed
warning:  symbolic link (jdk/legal/java.xml.ws/LICENSE) failed
warning:  symbolic link (jdk/legal/java.xml.ws/ADDITIONAL_LICENSE_INFO) failed
warning:  symbolic link (jdk/legal/java.xml.ws/ASSEMBLY_EXCEPTION) failed
warning:  symbolic link (jdk/legal/jdk.charsets/LICENSE) failed
warning:  symbolic link (jdk/legal/jdk.charsets/ADDITIONAL_LICENSE_INFO) failed
warning:  symbolic link (jdk/legal/jdk.charsets/ASSEMBLY_EXCEPTION) failed
warning:  symbolic link (jdk/legal/jdk.xml.dom/LICENSE) failed
warning:  symbolic link (jdk/legal/jdk.xml.dom/ADDITIONAL_LICENSE_INFO) failed
warning:  symbolic link (jdk/legal/jdk.xml.dom/ASSEMBLY_EXCEPTION) failed
warning:  symbolic link (jdk/legal/jdk.security.auth/LICENSE) failed
warning:  symbolic link (jdk/legal/jdk.security.auth/ADDITIONAL_LICENSE_INFO) failed
warning:  symbolic link (jdk/legal/jdk.security.auth/ASSEMBLY_EXCEPTION) failed
warning:  symbolic link (jdk/legal/jdk.attach/LICENSE) failed
warning:  symbolic link (jdk/legal/jdk.attach/ADDITIONAL_LICENSE_INFO) failed
warning:  symbolic link (jdk/legal/jdk.attach/ASSEMBLY_EXCEPTION) failed
warning:  symbolic link (jdk/legal/java.scripting/LICENSE) failed
warning:  symbolic link (jdk/legal/java.scripting/ADDITIONAL_LICENSE_INFO) failed
warning:  symbolic link (jdk/legal/java.scripting/ASSEMBLY_EXCEPTION) failed
warning:  symbolic link (jdk/legal/jdk.internal.ed/LICENSE) failed
warning:  symbolic link (jdk/legal/jdk.internal.ed/ADDITIONAL_LICENSE_INFO) failed
warning:  symbolic link (jdk/legal/jdk.internal.ed/ASSEMBLY_EXCEPTION) failed
warning:  symbolic link (jdk/legal/jdk.xml.ws/LICENSE) failed
warning:  symbolic link (jdk/legal/jdk.xml.ws/ADDITIONAL_LICENSE_INFO) failed
warning:  symbolic link (jdk/legal/jdk.xml.ws/ASSEMBLY_EXCEPTION) failed
warning:  symbolic link (jdk/legal/jdk.internal.le/LICENSE) failed
warning:  symbolic link (jdk/legal/jdk.internal.le/ADDITIONAL_LICENSE_INFO) failed
warning:  symbolic link (jdk/legal/jdk.internal.le/ASSEMBLY_EXCEPTION) failed
warning:  symbolic link (jdk/legal/jdk.jdwp.agent/LICENSE) failed
warning:  symbolic link (jdk/legal/jdk.jdwp.agent/ADDITIONAL_LICENSE_INFO) failed
warning:  symbolic link (jdk/legal/jdk.jdwp.agent/ASSEMBLY_EXCEPTION) failed
warning:  symbolic link (jdk/legal/jdk.unsupported/LICENSE) failed
warning:  symbolic link (jdk/legal/jdk.unsupported/ADDITIONAL_LICENSE_INFO) failed
warning:  symbolic link (jdk/legal/jdk.unsupported/ASSEMBLY_EXCEPTION) failed
warning:  symbolic link (jdk/legal/jdk.jartool/LICENSE) failed
warning:  symbolic link (jdk/legal/jdk.jartool/ADDITIONAL_LICENSE_INFO) failed
warning:  symbolic link (jdk/legal/jdk.jartool/ASSEMBLY_EXCEPTION) failed
warning:  symbolic link (jdk/legal/jdk.internal.jvmstat/LICENSE) failed
warning:  symbolic link (jdk/legal/jdk.internal.jvmstat/ADDITIONAL_LICENSE_INFO) failed
warning:  symbolic link (jdk/legal/jdk.internal.jvmstat/ASSEMBLY_EXCEPTION) failed
warning:  symbolic link (jdk/legal/jdk.policytool/LICENSE) failed
warning:  symbolic link (jdk/legal/jdk.policytool/ADDITIONAL_LICENSE_INFO) failed
warning:  symbolic link (jdk/legal/jdk.policytool/ASSEMBLY_EXCEPTION) failed
warning:  symbolic link (jdk/legal/java.naming/LICENSE) failed
warning:  symbolic link (jdk/legal/java.naming/ADDITIONAL_LICENSE_INFO) failed
warning:  symbolic link (jdk/legal/java.naming/ASSEMBLY_EXCEPTION) failed
warning:  symbolic link (jdk/legal/jdk.httpserver/LICENSE) failed
warning:  symbolic link (jdk/legal/jdk.httpserver/ADDITIONAL_LICENSE_INFO) failed
warning:  symbolic link (jdk/legal/jdk.httpserver/ASSEMBLY_EXCEPTION) failed
warning:  symbolic link (jdk/legal/jdk.security.jgss/LICENSE) failed
warning:  symbolic link (jdk/legal/jdk.security.jgss/ADDITIONAL_LICENSE_INFO) failed
warning:  symbolic link (jdk/legal/jdk.security.jgss/ASSEMBLY_EXCEPTION) failed
warning:  symbolic link (jdk/legal/java.sql.rowset/LICENSE) failed
warning:  symbolic link (jdk/legal/java.sql.rowset/ADDITIONAL_LICENSE_INFO) failed
warning:  symbolic link (jdk/legal/java.sql.rowset/ASSEMBLY_EXCEPTION) failed
warning:  symbolic link (jdk/legal/jdk.jconsole/LICENSE) failed
warning:  symbolic link (jdk/legal/jdk.jconsole/ADDITIONAL_LICENSE_INFO) failed
warning:  symbolic link (jdk/legal/jdk.jconsole/ASSEMBLY_EXCEPTION) failed
warning:  symbolic link (jdk/legal/jdk.internal.opt/LICENSE) failed
warning:  symbolic link (jdk/legal/jdk.internal.opt/ADDITIONAL_LICENSE_INFO) failed
warning:  symbolic link (jdk/legal/jdk.internal.opt/ASSEMBLY_EXCEPTION) failed
warning:  symbolic link (jdk/legal/jdk.management/LICENSE) failed
warning:  symbolic link (jdk/legal/jdk.management/ADDITIONAL_LICENSE_INFO) failed
warning:  symbolic link (jdk/legal/jdk.management/ASSEMBLY_EXCEPTION) failed
warning:  symbolic link (jdk/legal/java.logging/LICENSE) failed
warning:  symbolic link (jdk/legal/java.logging/ADDITIONAL_LICENSE_INFO) failed
warning:  symbolic link (jdk/legal/java.logging/ASSEMBLY_EXCEPTION) failed
warning:  symbolic link (jdk/legal/jdk.editpad/LICENSE) failed
warning:  symbolic link (jdk/legal/jdk.editpad/ADDITIONAL_LICENSE_INFO) failed
warning:  symbolic link (jdk/legal/jdk.editpad/ASSEMBLY_EXCEPTION) failed
warning:  symbolic link (jdk/legal/jdk.crypto.cryptoki/LICENSE) failed
warning:  symbolic link (jdk/legal/jdk.crypto.cryptoki/ADDITIONAL_LICENSE_INFO) failed
warning:  symbolic link (jdk/legal/jdk.crypto.cryptoki/ASSEMBLY_EXCEPTION) failed
warning:  symbolic link (jdk/legal/java.prefs/LICENSE) failed
warning:  symbolic link (jdk/legal/java.prefs/ADDITIONAL_LICENSE_INFO) failed
warning:  symbolic link (jdk/legal/java.prefs/ASSEMBLY_EXCEPTION) failed
warning:  symbolic link (jdk/legal/jdk.pack/LICENSE) failed
warning:  symbolic link (jdk/legal/jdk.pack/ADDITIONAL_LICENSE_INFO) failed
warning:  symbolic link (jdk/legal/jdk.pack/ASSEMBLY_EXCEPTION) failed
warning:  symbolic link (jdk/legal/jdk.compiler/LICENSE) failed
warning:  symbolic link (jdk/legal/jdk.compiler/ADDITIONAL_LICENSE_INFO) failed
warning:  symbolic link (jdk/legal/jdk.compiler/ASSEMBLY_EXCEPTION) failed
warning:  symbolic link (jdk/legal/jdk.naming.rmi/LICENSE) failed
warning:  symbolic link (jdk/legal/jdk.naming.rmi/ADDITIONAL_LICENSE_INFO) failed
warning:  symbolic link (jdk/legal/jdk.naming.rmi/ASSEMBLY_EXCEPTION) failed
warning:  symbolic link (jdk/legal/jdk.localedata/LICENSE) failed
warning:  symbolic link (jdk/legal/jdk.localedata/ADDITIONAL_LICENSE_INFO) failed
warning:  symbolic link (jdk/legal/jdk.localedata/ASSEMBLY_EXCEPTION) failed
warning:  symbolic link (jdk/legal/jdk.localedata/cldr.md) failed
warning:  symbolic link (jdk/legal/java.instrument/LICENSE) failed
warning:  symbolic link (jdk/legal/java.instrument/ADDITIONAL_LICENSE_INFO) failed
warning:  symbolic link (jdk/legal/java.instrument/ASSEMBLY_EXCEPTION) failed
warning:  symbolic link (jdk/legal/jdk.naming.dns/LICENSE) failed
warning:  symbolic link (jdk/legal/jdk.naming.dns/ADDITIONAL_LICENSE_INFO) failed
warning:  symbolic link (jdk/legal/jdk.naming.dns/ASSEMBLY_EXCEPTION) failed
warning:  symbolic link (jdk/legal/jdk.jcmd/LICENSE) failed
warning:  symbolic link (jdk/legal/jdk.jcmd/ADDITIONAL_LICENSE_INFO) failed
warning:  symbolic link (jdk/legal/jdk.jcmd/ASSEMBLY_EXCEPTION) failed
warning:  symbolic link (jdk/legal/java.xml/LICENSE) failed
warning:  symbolic link (jdk/legal/java.xml/ADDITIONAL_LICENSE_INFO) failed
warning:  symbolic link (jdk/legal/java.xml/ASSEMBLY_EXCEPTION) failed
warning:  symbolic link (jdk/legal/java.compiler/LICENSE) failed
warning:  symbolic link (jdk/legal/java.compiler/ADDITIONAL_LICENSE_INFO) failed
warning:  symbolic link (jdk/legal/java.compiler/ASSEMBLY_EXCEPTION) failed
warning:  symbolic link (jdk/legal/jdk.dynalink/LICENSE) failed
warning:  symbolic link (jdk/legal/jdk.dynalink/ADDITIONAL_LICENSE_INFO) failed
warning:  symbolic link (jdk/legal/jdk.dynalink/ASSEMBLY_EXCEPTION) failed
warning:  symbolic link (jdk/legal/java.transaction/LICENSE) failed
warning:  symbolic link (jdk/legal/java.transaction/ADDITIONAL_LICENSE_INFO) failed
warning:  symbolic link (jdk/legal/java.transaction/ASSEMBLY_EXCEPTION) failed
warning:  symbolic link (jdk/legal/jdk.zipfs/LICENSE) failed
warning:  symbolic link (jdk/legal/jdk.zipfs/ADDITIONAL_LICENSE_INFO) failed
warning:  symbolic link (jdk/legal/jdk.zipfs/ASSEMBLY_EXCEPTION) failed
warning:  symbolic link (jdk/legal/jdk.rmic/LICENSE) failed
warning:  symbolic link (jdk/legal/jdk.rmic/ADDITIONAL_LICENSE_INFO) failed
warning:  symbolic link (jdk/legal/jdk.rmic/ASSEMBLY_EXCEPTION) failed
warning:  symbolic link (jdk/legal/jdk.incubator.httpclient/LICENSE) failed
warning:  symbolic link (jdk/legal/jdk.incubator.httpclient/ADDITIONAL_LICENSE_INFO) failed
warning:  symbolic link (jdk/legal/jdk.incubator.httpclient/ASSEMBLY_EXCEPTION) failed
warning:  symbolic link (jdk/legal/jdk.jsobject/LICENSE) failed
warning:  symbolic link (jdk/legal/jdk.jsobject/ADDITIONAL_LICENSE_INFO) failed
warning:  symbolic link (jdk/legal/jdk.jsobject/ASSEMBLY_EXCEPTION) failed
warning:  symbolic link (jdk/legal/jdk.net/LICENSE) failed
warning:  symbolic link (jdk/legal/jdk.net/ADDITIONAL_LICENSE_INFO) failed
warning:  symbolic link (jdk/legal/jdk.net/ASSEMBLY_EXCEPTION) failed
warning:  symbolic link (jdk/legal/java.security.sasl/LICENSE) failed
warning:  symbolic link (jdk/legal/java.security.sasl/ADDITIONAL_LICENSE_INFO) failed
warning:  symbolic link (jdk/legal/java.security.sasl/ASSEMBLY_EXCEPTION) failed
warning:  symbolic link (jdk/legal/java.activation/LICENSE) failed
warning:  symbolic link (jdk/legal/java.activation/ADDITIONAL_LICENSE_INFO) failed
warning:  symbolic link (jdk/legal/java.activation/ASSEMBLY_EXCEPTION) failed
warning:  symbolic link (jdk/legal/java.management/LICENSE) failed
warning:  symbolic link (jdk/legal/java.management/ADDITIONAL_LICENSE_INFO) failed
warning:  symbolic link (jdk/legal/java.management/ASSEMBLY_EXCEPTION) failed
warning:  symbolic link (jdk/legal/java.security.jgss/LICENSE) failed
warning:  symbolic link (jdk/legal/java.security.jgss/ADDITIONAL_LICENSE_INFO) failed
warning:  symbolic link (jdk/legal/java.security.jgss/ASSEMBLY_EXCEPTION) failed
warning:  symbolic link (jdk/legal/java.xml.ws.annotation/LICENSE) failed
warning:  symbolic link (jdk/legal/java.xml.ws.annotation/ADDITIONAL_LICENSE_INFO) failed
warning:  symbolic link (jdk/legal/java.xml.ws.annotation/ASSEMBLY_EXCEPTION) failed
warning:  symbolic link (jdk/legal/java.se/LICENSE) failed
warning:  symbolic link (jdk/legal/java.se/ADDITIONAL_LICENSE_INFO) failed
warning:  symbolic link (jdk/legal/java.se/ASSEMBLY_EXCEPTION) failed
warning:  symbolic link (jdk/legal/jdk.scripting.nashorn.shell/LICENSE) failed
warning:  symbolic link (jdk/legal/jdk.scripting.nashorn.shell/ADDITIONAL_LICENSE_INFO) failed
warning:  symbolic link (jdk/legal/jdk.scripting.nashorn.shell/ASSEMBLY_EXCEPTION) failed
warning:  symbolic link (jdk/legal/java.management.rmi/LICENSE) failed
warning:  symbolic link (jdk/legal/java.management.rmi/ADDITIONAL_LICENSE_INFO) failed
warning:  symbolic link (jdk/legal/java.management.rmi/ASSEMBLY_EXCEPTION) failed
zip warning: Permission denied
[many more identical lines]
Target //scripts:bash_completion failed to build
Use --verbose_failures to see the command lines of failed build steps.
```

The full output of the build is there: https://gist.github.com/fxcoudert/76655beb3b79881768d5ef4f63dfe600

**Comment by mdaniel** [comment] 2018-10-08 16:15
For those who find this issue and do want it to build on El Capitan, those symlink and permission denied errors are caused by the older version of `/usr/bin/unzip`. I found that brew installing a modern unzip, then placing `/usr/local/opt/unzip/bin` at the beginning of `ENV["PATH"]` in the formula allowed bazel to build successfully.

**Comment by jmmv** [comment] 2018-10-11 19:32
What version of unzip comes with El Capitan?

**Comment by philwo** [comment] 2018-10-11 20:07
El Capitan:

```
buildkite-macpro-elcapitan-1:~ ci$ unzip -v       
UnZip 5.52 of 28 February 2005, by Info-ZIP.  Maintained by C. Spieler.  Send
bug reports using http://www.info-zip.org/zip-bug.html; see README for details.

Latest sources and executables are at ftp://ftp.info-zip.org/pub/infozip/ ;
see ftp://ftp.info-zip.org/pub/infozip/UnZip.html for other sites.

Compiled with gcc 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.0.59.1) for Unix on Aug  1 2015.

UnZip special compilation options:
	COPYRIGHT_CLEAN (PKZIP 0.9x unreducing method not supported)
	SET_DIR_ATTRIB
	TIMESTAMP
	USE_EF_UT_TIME
	USE_UNSHRINK (PKZIP/Zip 1.x unshrinking method supported)
	USE_DEFLATE64 (PKZIP 4.x Deflate64(tm) supported)
	VMS_TEXT_CONV
	[decryption, version 2.9 of 05 May 2000]

UnZip and ZipInfo environment options:
           UNZIP:  [none]
        UNZIPOPT:  [none]
         ZIPINFO:  [none]
      ZIPINFOOPT:  [none]
```

Sierra, High Sierra, Mojave (except differing compiler version):

```
buildkite-macpro-sierra-1:~ ci$ unzip -v
UnZip 6.00 of 20 April 2009, by Info-ZIP.  Maintained by C. Spieler.  Send
bug reports using http://www.info-zip.org/zip-bug.html; see README for details.

Latest sources and executables are at ftp://ftp.info-zip.org/pub/infozip/ ;
see ftp://ftp.info-zip.org/pub/infozip/UnZip.html for other sites.

Compiled with gcc 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34) for Unix Mac OS X on Oct 14 2016.

UnZip special compilation options:
        COPYRIGHT_CLEAN (PKZIP 0.9x unreducing method not supported)
        SET_DIR_ATTRIB
        SYMLINKS (symbolic links supported, if RTL and file system permit)
        TIMESTAMP
        UNIXBACKUP
        USE_EF_UT_TIME
        USE_UNSHRINK (PKZIP/Zip 1.x unshrinking method supported)
        USE_DEFLATE64 (PKZIP 4.x Deflate64(tm) supported)
        LARGE_FILE_SUPPORT (large files over 2 GiB supported)
        ZIP64_SUPPORT (archives using Zip64 for large files supported)
        VMS_TEXT_CONV
        [decryption, version 2.11 of 05 Jan 2007]

UnZip and ZipInfo environment options:
           UNZIP:  [none]
        UNZIPOPT:  [none]
         ZIPINFO:  [none]
      ZIPINFOOPT:  [none]
```

**Comment by jmmv** [comment] 2018-10-11 20:45
Hm. I built Unzip 5.52 on High Sierra and used it for the build and couldn't reproduce the problem. Should try with Zip as well; it's probably a combination of the two that's causing this.

**Comment by philwo** [comment] 2018-10-11 20:52
@jmmv Maybe it's a problem of the configure flags in the older version? The El Capitan one is lacking quite a few from the latter versions (SYMLINKS, UNIXBACKUP, LARGE_FILE_SUPPORT and ZIP64_SUPPORT).

**Comment by jmmv** [comment] 2018-10-15 17:55
@philwo The build I did of `unzip` didn't have any of those options either. Is there a way for me to log into the El Capitan buildkite node to investigate this interactively?

**Comment by philwo** [comment] 2018-10-17 11:57
@jmmv I'll send you instructions via chat.

**Comment by dslomov** [comment] 2019-02-15 16:03
Please do not assign issues to more than one team

**Comment by meisterT** [comment] 2020-05-16 21:28
Is this still an issue today?

**Comment by philwo** [comment] 2020-05-18 15:02
The affected macOS versions are no longer supported, so I think we can close this.

**Closed by philwo** 2020-05-18 15:02 UTC
Labels: P3, team-EngProd, type: bug
